AWS SDK for Qt: QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient Class Reference
QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient Class Reference
Client for Amazon Cognito Identity Provider.
Public Slots
AddCustomAttributesResponse * addCustomAttributes (const AddCustomAttributesRequest &request)
AdminAddUserToGroupResponse * adminAddUserToGroup (const AdminAddUserToGroupRequest &request)
AdminConfirmSignUpResponse * adminConfirmSignUp (const AdminConfirmSignUpRequest &request)
AdminCreateUserResponse * adminCreateUser (const AdminCreateUserRequest &request)
AdminDeleteUserResponse * adminDeleteUser (const AdminDeleteUserRequest &request)
AdminDeleteUserAttributesResponse * adminDeleteUserAttributes (const AdminDeleteUserAttributesRequest &request)
AdminDisableProviderForUserResponse * adminDisableProviderForUser (const AdminDisableProviderForUserRequest &request)
AdminDisableUserResponse * adminDisableUser (const AdminDisableUserRequest &request)
AdminEnableUserResponse * adminEnableUser (const AdminEnableUserRequest &request)
AdminForgetDeviceResponse * adminForgetDevice (const AdminForgetDeviceRequest &request)
AdminGetDeviceResponse * adminGetDevice (const AdminGetDeviceRequest &request)
AdminGetUserResponse * adminGetUser (const AdminGetUserRequest &request)
AdminInitiateAuthResponse * adminInitiateAuth (const AdminInitiateAuthRequest &request)
AdminLinkProviderForUserResponse * adminLinkProviderForUser (const AdminLinkProviderForUserRequest &request)
AdminListDevicesResponse * adminListDevices (const AdminListDevicesRequest &request)
AdminListGroupsForUserResponse * adminListGroupsForUser (const AdminListGroupsForUserRequest &request)
AdminListUserAuthEventsResponse * adminListUserAuthEvents (const AdminListUserAuthEventsRequest &request)
AdminRemoveUserFromGroupResponse * adminRemoveUserFromGroup (const AdminRemoveUserFromGroupRequest &request)
AdminResetUserPasswordResponse * adminResetUserPassword (const AdminResetUserPasswordRequest &request)
AdminRespondToAuthChallengeResponse * adminRespondToAuthChallenge (const AdminRespondToAuthChallengeRequest &request)
AdminSetUserMFAPreferenceResponse * adminSetUserMFAPreference (const AdminSetUserMFAPreferenceRequest &request)
AdminSetUserSettingsResponse * adminSetUserSettings (const AdminSetUserSettingsRequest &request)
AdminUpdateAuthEventFeedbackResponse * adminUpdateAuthEventFeedback (const AdminUpdateAuthEventFeedbackRequest &request)
AdminUpdateDeviceStatusResponse * adminUpdateDeviceStatus (const AdminUpdateDeviceStatusRequest &request)
AdminUpdateUserAttributesResponse * adminUpdateUserAttributes (const AdminUpdateUserAttributesRequest &request)
AdminUserGlobalSignOutResponse * adminUserGlobalSignOut (const AdminUserGlobalSignOutRequest &request)
AssociateSoftwareTokenResponse * associateSoftwareToken (const AssociateSoftwareTokenRequest &request)
ChangePasswordResponse * changePassword (const ChangePasswordRequest &request)
ConfirmDeviceResponse * confirmDevice (const ConfirmDeviceRequest &request)
ConfirmForgotPasswordResponse * confirmForgotPassword (const ConfirmForgotPasswordRequest &request)
ConfirmSignUpResponse * confirmSignUp (const ConfirmSignUpRequest &request)
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
CreateIdentityProviderResponse * createIdentityProvider (const CreateIdentityProviderRequest &request)
CreateResourceServerResponse * createResourceServer (const CreateResourceServerRequest &request)
CreateUserImportJobResponse * createUserImportJob (const CreateUserImportJobRequest &request)
CreateUserPoolResponse * createUserPool (const CreateUserPoolRequest &request)
CreateUserPoolClientResponse * createUserPoolClient (const CreateUserPoolClientRequest &request)
CreateUserPoolDomainResponse * createUserPoolDomain (const CreateUserPoolDomainRequest &request)
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
DeleteIdentityProviderResponse * deleteIdentityProvider (const DeleteIdentityProviderRequest &request)
DeleteResourceServerResponse * deleteResourceServer (const DeleteResourceServerRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DeleteUserAttributesResponse * deleteUserAttributes (const DeleteUserAttributesRequest &request)
DeleteUserPoolResponse * deleteUserPool (const DeleteUserPoolRequest &request)
DeleteUserPoolClientResponse * deleteUserPoolClient (const DeleteUserPoolClientRequest &request)
DeleteUserPoolDomainResponse * deleteUserPoolDomain (const DeleteUserPoolDomainRequest &request)
DescribeIdentityProviderResponse * describeIdentityProvider (const DescribeIdentityProviderRequest &request)
DescribeResourceServerResponse * describeResourceServer (const DescribeResourceServerRequest &request)
DescribeRiskConfigurationResponse * describeRiskConfiguration (const DescribeRiskConfigurationRequest &request)
DescribeUserImportJobResponse * describeUserImportJob (const DescribeUserImportJobRequest &request)
DescribeUserPoolResponse * describeUserPool (const DescribeUserPoolRequest &request)
DescribeUserPoolClientResponse * describeUserPoolClient (const DescribeUserPoolClientRequest &request)
DescribeUserPoolDomainResponse * describeUserPoolDomain (const DescribeUserPoolDomainRequest &request)
ForgetDeviceResponse * forgetDevice (const ForgetDeviceRequest &request)
ForgotPasswordResponse * forgotPassword (const ForgotPasswordRequest &request)
GetCSVHeaderResponse * getCSVHeader (const GetCSVHeaderRequest &request)
GetDeviceResponse * getDevice (const GetDeviceRequest &request)
GetGroupResponse * getGroup (const GetGroupRequest &request)
GetIdentityProviderByIdentifierResponse * getIdentityProviderByIdentifier (const GetIdentityProviderByIdentifierRequest &request)
GetSigningCertificateResponse * getSigningCertificate (const GetSigningCertificateRequest &request)
GetUICustomizationResponse * getUICustomization (const GetUICustomizationRequest &request)
GetUserResponse * getUser (const GetUserRequest &request)
GetUserAttributeVerificationCodeResponse * getUserAttributeVerificationCode (const GetUserAttributeVerificationCodeRequest &request)
GetUserPoolMfaConfigResponse * getUserPoolMfaConfig (const GetUserPoolMfaConfigRequest &request)
GlobalSignOutResponse * globalSignOut (const GlobalSignOutRequest &request)
InitiateAuthResponse * initiateAuth (const InitiateAuthRequest &request)
ListDevicesResponse * listDevices (const ListDevicesRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
ListIdentityProvidersResponse * listIdentityProviders (const ListIdentityProvidersRequest &request)
ListResourceServersResponse * listResourceServers (const ListResourceServersRequest &request)
ListUserImportJobsResponse * listUserImportJobs (const ListUserImportJobsRequest &request)
ListUserPoolClientsResponse * listUserPoolClients (const ListUserPoolClientsRequest &request)
ListUserPoolsResponse * listUserPools (const ListUserPoolsRequest &request)
ListUsersResponse * listUsers (const ListUsersRequest &request)
ListUsersInGroupResponse * listUsersInGroup (const ListUsersInGroupRequest &request)
ResendConfirmationCodeResponse * resendConfirmationCode (const ResendConfirmationCodeRequest &request)
RespondToAuthChallengeResponse * respondToAuthChallenge (const RespondToAuthChallengeRequest &request)
SetRiskConfigurationResponse * setRiskConfiguration (const SetRiskConfigurationRequest &request)
SetUICustomizationResponse * setUICustomization (const SetUICustomizationRequest &request)
SetUserMFAPreferenceResponse * setUserMFAPreference (const SetUserMFAPreferenceRequest &request)
SetUserPoolMfaConfigResponse * setUserPoolMfaConfig (const SetUserPoolMfaConfigRequest &request)
SetUserSettingsResponse * setUserSettings (const SetUserSettingsRequest &request)
SignUpResponse * signUp (const SignUpRequest &request)
StartUserImportJobResponse * startUserImportJob (const StartUserImportJobRequest &request)
StopUserImportJobResponse * stopUserImportJob (const StopUserImportJobRequest &request)
UpdateAuthEventFeedbackResponse * updateAuthEventFeedback (const UpdateAuthEventFeedbackRequest &request)
UpdateDeviceStatusResponse * updateDeviceStatus (const UpdateDeviceStatusRequest &request)
UpdateGroupResponse * updateGroup (const UpdateGroupRequest &request)
UpdateIdentityProviderResponse * updateIdentityProvider (const UpdateIdentityProviderRequest &request)
UpdateResourceServerResponse * updateResourceServer (const UpdateResourceServerRequest &request)
UpdateUserAttributesResponse * updateUserAttributes (const UpdateUserAttributesRequest &request)
UpdateUserPoolResponse * updateUserPool (const UpdateUserPoolRequest &request)
UpdateUserPoolClientResponse * updateUserPoolClient (const UpdateUserPoolClientRequest &request)
VerifySoftwareTokenResponse * verifySoftwareToken (const VerifySoftwareTokenRequest &request)
VerifyUserAttributeResponse * verifyUserAttribute (const VerifyUserAttributeRequest &request)
Public Member Functions
CognitoIdentityProviderClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoIdentityProviderClient object.
CognitoIdentityProviderClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoIdentityProviderClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Cognito Identity Provider.
Using the Amazon Cognito User Pools API, you can create a user pool to manage directories and users. You can authenticate a user to obtain tokens related to user identity and access
policies>
This API reference provides information about user pools in Amazon Cognito User
Pools>
For more information, see the Amazon Cognito
Definition at line 222 of file cognitoidentityproviderclient.h.
Constructor & Destructor Documentation
CognitoIdentityProviderClient() [1/2]
QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoIdentityProviderClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 246 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CognitoIdentityProviderClientPrivate(this), parent)
 {
     Q_D(CognitoIdentityProviderClient);
     d->apiVersion = QStringLiteral("2016-04-18");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cognito-idp");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Cognito Identity Provider");
     d->serviceName = QStringLiteral("cognito-idp");
 }
CognitoIdentityProviderClient() [2/2]
QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoIdentityProviderClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 279 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CognitoIdentityProviderClientPrivate(this), parent)
 {
     Q_D(CognitoIdentityProviderClient);
     d->apiVersion = QStringLiteral("2016-04-18");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cognito-idp");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Cognito Identity Provider");
     d->serviceName = QStringLiteral("cognito-idp");
 }
Member Function Documentation
addCustomAttributes
AddCustomAttributesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::addCustomAttributes (const AddCustomAttributesRequest & request) slot
Adds additional user attributes to the user pool
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddCustomAttributesResponse *>(send(request));
 }
adminAddUserToGroup
AdminAddUserToGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminAddUserToGroup (const AdminAddUserToGroupRequest & request) slot
Adds the specified user to the specified
group>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 323 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminAddUserToGroupResponse *>(send(request));
 }
adminConfirmSignUp
AdminConfirmSignUpResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminConfirmSignUp (const AdminConfirmSignUpRequest & request) slot
Confirms user registration as an admin without using a confirmation code. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 341 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminConfirmSignUpResponse *>(send(request));
 }
adminCreateUser
AdminCreateUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminCreateUser (const AdminCreateUserRequest & request) slot
Creates a new user in the specified user
pool>
If MessageAction is not set, the default is to send a welcome message via email or phone
(SMS)> <note>
This message is based on a template that you configured in your call to or . This template includes your custom sign-up instructions and placeholders for user name and temporary
password> </note>
Alternatively, you can call AdminCreateUser with SUPPRESS for the MessageAction parameter, and Amazon Cognito will not send any email.
</p
In either case, the user will be in the FORCE_CHANGE_PASSWORD state until they sign in and change their
password>
AdminCreateUser requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminCreateUserResponse *>(send(request));
 }
adminDeleteUser
AdminDeleteUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDeleteUser (const AdminDeleteUserRequest & request) slot
Deletes a user as an administrator. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminDeleteUserResponse *>(send(request));
 }
adminDeleteUserAttributes
AdminDeleteUserAttributesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDeleteUserAttributes (const AdminDeleteUserAttributesRequest & request) slot
Deletes the user attributes in a user pool as an administrator. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 413 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminDeleteUserAttributesResponse *>(send(request));
 }
adminDisableProviderForUser
AdminDisableProviderForUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDisableProviderForUser (const AdminDisableProviderForUserRequest & request) slot
Disables the user from signing in with the specified external (SAML or social) identity provider. If the user to disable is a Cognito User Pools native username + password user, they are not permitted to use their password to sign-in. If the user to disable is a linked external IdP user, any link between that user and an existing user is removed. The next time the external user (no longer attached to the previously linked DestinationUser) signs in, they must create a new user account. See
This action is enabled only for admin access and requires developer
credentials>
The ProviderName must match the value specified when creating an IdP for the pool.
</p
To disable a native username + password user, the ProviderName value must be Cognito and the ProviderAttributeName must be Cognito_Subject, with the ProviderAttributeValue being the name that is used in the user pool for the
user>
The ProviderAttributeName must always be Cognito_Subject for social identity providers. The ProviderAttributeValue must always be the exact subject that was used when the user was originally linked as a source
user>
For de-linking a SAML identity, there are two scenarios. If the linked identity has not yet been used to sign-in, the ProviderAttributeName and ProviderAttributeValue must be the same values that were used for the SourceUser when the identities were originally linked in the call. (If the linking was done with ProviderAttributeName set to Cognito_Subject, the same applies here). However, if the user has already signed in, the ProviderAttributeName must be Cognito_Subject and ProviderAttributeValue must be the subject of the SAML
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 460 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminDisableProviderForUserResponse *>(send(request));
 }
adminDisableUser
AdminDisableUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDisableUser (const AdminDisableUserRequest & request) slot
Disables the specified user as an administrator. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 478 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminDisableUserResponse *>(send(request));
 }
adminEnableUser
AdminEnableUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminEnableUser (const AdminEnableUserRequest & request) slot
Enables the specified user as an administrator. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 496 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminEnableUserResponse *>(send(request));
 }
adminForgetDevice
AdminForgetDeviceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminForgetDevice (const AdminForgetDeviceRequest & request) slot
Forgets the device, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 514 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminForgetDeviceResponse *>(send(request));
 }
adminGetDevice
AdminGetDeviceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminGetDevice (const AdminGetDeviceRequest & request) slot
Gets the device, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 532 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminGetDeviceResponse *>(send(request));
 }
adminGetUser
AdminGetUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminGetUser (const AdminGetUserRequest & request) slot
Gets the specified user by user name in a user pool as an administrator. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 550 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminGetUserResponse *>(send(request));
 }
adminInitiateAuth
AdminInitiateAuthResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminInitiateAuth (const AdminInitiateAuthRequest & request) slot
Initiates the authentication flow, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 568 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminInitiateAuthResponse *>(send(request));
 }
adminLinkProviderForUser
AdminLinkProviderForUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminLinkProviderForUser (const AdminLinkProviderForUserRequest & request) slot
Links an existing user account in a user pool (DestinationUser) to an identity from an external identity provider (SourceUser) based on a specified attribute name and value from the external identity provider. This allows you to create a link from the existing user account to an external federated user identity that has not yet been used to sign in, so that the federated user identity can be used to sign in as the existing user account.
</p
For example, if there is an existing user with a username and password, this API links that user to a federated user identity, so that when the federated user identity is used, the user signs in as the existing user account.
</p
Because this API allows a user with an external federated identity to sign in as an existing user in the user pool, it is critical that it only be used with external identity providers and provider attributes that have been trusted by the application
owner>
See also
This action is enabled only for admin access and requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 604 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminLinkProviderForUserResponse *>(send(request));
 }
adminListDevices
AdminListDevicesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListDevices (const AdminListDevicesRequest & request) slot
Lists devices, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 622 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminListDevicesResponse *>(send(request));
 }
adminListGroupsForUser
AdminListGroupsForUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListGroupsForUser (const AdminListGroupsForUserRequest & request) slot
Lists the groups that the user belongs
to>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 640 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminListGroupsForUserResponse *>(send(request));
 }
adminListUserAuthEvents
AdminListUserAuthEventsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListUserAuthEvents (const AdminListUserAuthEventsRequest & request) slot
Lists a history of user activity and any risks detected as part of Amazon Cognito advanced
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 654 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminListUserAuthEventsResponse *>(send(request));
 }
adminRemoveUserFromGroup
AdminRemoveUserFromGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminRemoveUserFromGroup (const AdminRemoveUserFromGroupRequest & request) slot
Removes the specified user from the specified
group>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 672 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminRemoveUserFromGroupResponse *>(send(request));
 }
adminResetUserPassword
AdminResetUserPasswordResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminResetUserPassword (const AdminResetUserPasswordRequest & request) slot
Resets the specified user's password in a user pool as an administrator. Works on any
user>
When a developer calls this API, the current password is invalidated, so it must be changed. If a user tries to sign in after the API is called, the app will get a PasswordResetRequiredException exception back and should direct the user down the flow to reset the password, which is the same as the forgot password flow. In addition, if the user pool has phone verification selected and a verified phone number exists for the user, or if email verification is selected and a verified email exists for the user, calling this API will also result in sending a message to the end user with the code to change their
password>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 699 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminResetUserPasswordResponse *>(send(request));
 }
adminRespondToAuthChallenge
AdminRespondToAuthChallengeResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminRespondToAuthChallenge (const AdminRespondToAuthChallengeRequest & request) slot
Responds to an authentication challenge, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 717 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminRespondToAuthChallengeResponse *>(send(request));
 }
adminSetUserMFAPreference
AdminSetUserMFAPreferenceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminSetUserMFAPreference (const AdminSetUserMFAPreferenceRequest & request) slot
Sets the user's multi-factor authentication (MFA)
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 731 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminSetUserMFAPreferenceResponse *>(send(request));
 }
adminSetUserSettings
AdminSetUserSettingsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminSetUserSettings (const AdminSetUserSettingsRequest & request) slot
Sets all the user settings for a specified user name. Works on any
user>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 749 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminSetUserSettingsResponse *>(send(request));
 }
adminUpdateAuthEventFeedback
AdminUpdateAuthEventFeedbackResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateAuthEventFeedback (const AdminUpdateAuthEventFeedbackRequest & request) slot
Provides feedback for an authentication event as to whether it was from a valid user. This feedback is used for improving the risk evaluation decision for the user pool as part of Amazon Cognito advanced
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 764 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminUpdateAuthEventFeedbackResponse *>(send(request));
 }
adminUpdateDeviceStatus
AdminUpdateDeviceStatusResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateDeviceStatus (const AdminUpdateDeviceStatusRequest & request) slot
Updates the device status as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 782 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminUpdateDeviceStatusResponse *>(send(request));
 }
adminUpdateUserAttributes
AdminUpdateUserAttributesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateUserAttributes (const AdminUpdateUserAttributesRequest & request) slot
Updates the specified user's attributes, including developer attributes, as an administrator. Works on any
user>
For custom attributes, you must prepend the custom: prefix to the attribute
name>
In addition to updating user attributes, this API can also be used to mark phone and email as
verified>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 808 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminUpdateUserAttributesResponse *>(send(request));
 }
adminUserGlobalSignOut
AdminUserGlobalSignOutResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUserGlobalSignOut (const AdminUserGlobalSignOutRequest & request) slot
Signs out users from all devices, as an
administrator>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 826 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AdminUserGlobalSignOutResponse *>(send(request));
 }
associateSoftwareToken
AssociateSoftwareTokenResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::associateSoftwareToken (const AssociateSoftwareTokenRequest & request) slot
Returns a unique generated shared secret key code for the user account. The request takes an access token or a session string, but not
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 841 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateSoftwareTokenResponse *>(send(request));
 }
changePassword
ChangePasswordResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::changePassword (const ChangePasswordRequest & request) slot
Changes the password for a specified user in a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 855 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangePasswordResponse *>(send(request));
 }
confirmDevice
ConfirmDeviceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmDevice (const ConfirmDeviceRequest & request) slot
Confirms tracking of the device. This API call is the call that begins device
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 869 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmDeviceResponse *>(send(request));
 }
confirmForgotPassword
ConfirmForgotPasswordResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmForgotPassword (const ConfirmForgotPasswordRequest & request) slot
Allows a user to enter a confirmation code to reset a forgotten
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 883 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmForgotPasswordResponse *>(send(request));
 }
confirmSignUp
ConfirmSignUpResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmSignUp (const ConfirmSignUpRequest & request) slot
Confirms registration of a user and handles the existing alias from a previous
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 897 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmSignUpResponse *>(send(request));
 }
createGroup
CreateGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createGroup (const CreateGroupRequest & request) slot
Creates a new group in the specified user
pool>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 915 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGroupResponse *>(send(request));
 }
createIdentityProvider
CreateIdentityProviderResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createIdentityProvider (const CreateIdentityProviderRequest & request) slot
Creates an identity provider for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 929 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateIdentityProviderResponse *>(send(request));
 }
createResourceServer
CreateResourceServerResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createResourceServer (const CreateResourceServerRequest & request) slot
Creates a new OAuth2.0 resource server and defines custom scopes in
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 943 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateResourceServerResponse *>(send(request));
 }
createUserImportJob
CreateUserImportJobResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserImportJob (const CreateUserImportJobRequest & request) slot
Creates the user import
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 957 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserImportJobResponse *>(send(request));
 }
createUserPool
CreateUserPoolResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPool (const CreateUserPoolRequest & request) slot
Creates a new Amazon Cognito user pool and sets the password policy for the
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 971 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserPoolResponse *>(send(request));
 }
createUserPoolClient
CreateUserPoolClientResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPoolClient (const CreateUserPoolClientRequest & request) slot
Creates the user pool
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 985 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserPoolClientResponse *>(send(request));
 }
createUserPoolDomain
CreateUserPoolDomainResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPoolDomain (const CreateUserPoolDomainRequest & request) slot
Creates a new domain for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 999 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserPoolDomainResponse *>(send(request));
 }
deleteGroup
DeleteGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteGroup (const DeleteGroupRequest & request) slot
Deletes a group. Currently only groups with no members can be
deleted>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1017 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGroupResponse *>(send(request));
 }
deleteIdentityProvider
DeleteIdentityProviderResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteIdentityProvider (const DeleteIdentityProviderRequest & request) slot
Deletes an identity provider for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1031 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIdentityProviderResponse *>(send(request));
 }
deleteResourceServer
DeleteResourceServerResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteResourceServer (const DeleteResourceServerRequest & request) slot
Deletes a resource
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1045 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteResourceServerResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUser (const DeleteUserRequest & request) slot
Allows a user to delete himself or
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1059 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
deleteUserAttributes
DeleteUserAttributesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserAttributes (const DeleteUserAttributesRequest & request) slot
Deletes the attributes for a
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1073 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserAttributesResponse *>(send(request));
 }
deleteUserPool
DeleteUserPoolResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPool (const DeleteUserPoolRequest & request) slot
Deletes the specified Amazon Cognito user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1087 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserPoolResponse *>(send(request));
 }
deleteUserPoolClient
DeleteUserPoolClientResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPoolClient (const DeleteUserPoolClientRequest & request) slot
Allows the developer to delete the user pool
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1101 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserPoolClientResponse *>(send(request));
 }
deleteUserPoolDomain
DeleteUserPoolDomainResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPoolDomain (const DeleteUserPoolDomainRequest & request) slot
Deletes a domain for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1115 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserPoolDomainResponse *>(send(request));
 }
describeIdentityProvider
DescribeIdentityProviderResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeIdentityProvider (const DescribeIdentityProviderRequest & request) slot
Gets information about a specific identity
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1129 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIdentityProviderResponse *>(send(request));
 }
describeResourceServer
DescribeResourceServerResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeResourceServer (const DescribeResourceServerRequest & request) slot
Describes a resource
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1143 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeResourceServerResponse *>(send(request));
 }
describeRiskConfiguration
DescribeRiskConfigurationResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeRiskConfiguration (const DescribeRiskConfigurationRequest & request) slot
Describes the risk
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1157 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRiskConfigurationResponse *>(send(request));
 }
describeUserImportJob
DescribeUserImportJobResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserImportJob (const DescribeUserImportJobRequest & request) slot
Describes the user import
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1171 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserImportJobResponse *>(send(request));
 }
describeUserPool
DescribeUserPoolResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPool (const DescribeUserPoolRequest & request) slot
Returns the configuration information and metadata of the specified user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1185 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserPoolResponse *>(send(request));
 }
describeUserPoolClient
DescribeUserPoolClientResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPoolClient (const DescribeUserPoolClientRequest & request) slot
Client method for returning the configuration information and metadata of the specified user pool
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1199 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserPoolClientResponse *>(send(request));
 }
describeUserPoolDomain
DescribeUserPoolDomainResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPoolDomain (const DescribeUserPoolDomainRequest & request) slot
Gets information about a
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1213 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserPoolDomainResponse *>(send(request));
 }
forgetDevice
ForgetDeviceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::forgetDevice (const ForgetDeviceRequest & request) slot
Forgets the specified
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1227 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ForgetDeviceResponse *>(send(request));
 }
forgotPassword
ForgotPasswordResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::forgotPassword (const ForgotPasswordRequest & request) slot
Calling this API causes a message to be sent to the end user with a confirmation code that is required to change the user's password. For the Username parameter, you can use the username or user alias. If a verified phone number exists for the user, the confirmation code is sent to the phone number. Otherwise, if a verified email exists, the confirmation code is sent to the email. If neither a verified phone number nor a verified email exists, InvalidParameterException is thrown. To use the confirmation code for resetting the password, call
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1245 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ForgotPasswordResponse *>(send(request));
 }
getCSVHeader
GetCSVHeaderResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getCSVHeader (const GetCSVHeaderRequest & request) slot
Gets the header information for the .csv file to be used as input for the user import
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1259 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCSVHeaderResponse *>(send(request));
 }
getDevice
GetDeviceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getDevice (const GetDeviceRequest & request) slot
Gets the
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1273 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeviceResponse *>(send(request));
 }
getGroup
GetGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getGroup (const GetGroupRequest & request) slot
Gets a
group>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1291 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGroupResponse *>(send(request));
 }
getIdentityProviderByIdentifier
GetIdentityProviderByIdentifierResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getIdentityProviderByIdentifier (const GetIdentityProviderByIdentifierRequest & request) slot
Gets the specified identity
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1305 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityProviderByIdentifierResponse *>(send(request));
 }
getSigningCertificate
GetSigningCertificateResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getSigningCertificate (const GetSigningCertificateRequest & request) slot
This method takes a user pool ID, and returns the signing
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1319 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSigningCertificateResponse *>(send(request));
 }
getUICustomization
GetUICustomizationResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUICustomization (const GetUICustomizationRequest & request) slot
Gets the UI Customization information for a particular app client's app UI, if there is something set. If nothing is set for the particular client, but there is an existing pool level customization (app clientId will be ALL), then that is returned. If nothing is present, then an empty shape is
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1335 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUICustomizationResponse *>(send(request));
 }
getUser
GetUserResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUser (const GetUserRequest & request) slot
Gets the user attributes and metadata for a
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1349 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserResponse *>(send(request));
 }
getUserAttributeVerificationCode
GetUserAttributeVerificationCodeResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUserAttributeVerificationCode (const GetUserAttributeVerificationCodeRequest & request) slot
Gets the user attribute verification code for the specified attribute
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1363 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserAttributeVerificationCodeResponse *>(send(request));
 }
getUserPoolMfaConfig
GetUserPoolMfaConfigResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUserPoolMfaConfig (const GetUserPoolMfaConfigRequest & request) slot
Gets the user pool multi-factor authentication (MFA)
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1377 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserPoolMfaConfigResponse *>(send(request));
 }
globalSignOut
GlobalSignOutResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::globalSignOut (const GlobalSignOutRequest & request) slot
Signs out users from all
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1391 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GlobalSignOutResponse *>(send(request));
 }
initiateAuth
InitiateAuthResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::initiateAuth (const InitiateAuthRequest & request) slot
Initiates the authentication
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1405 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InitiateAuthResponse *>(send(request));
 }
listDevices
ListDevicesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listDevices (const ListDevicesRequest & request) slot
Lists the
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1419 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDevicesResponse *>(send(request));
 }
listGroups
ListGroupsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listGroups (const ListGroupsRequest & request) slot
Lists the groups associated with a user
pool>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1437 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupsResponse *>(send(request));
 }
listIdentityProviders
ListIdentityProvidersResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listIdentityProviders (const ListIdentityProvidersRequest & request) slot
Lists information about all identity providers for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1451 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListIdentityProvidersResponse *>(send(request));
 }
listResourceServers
ListResourceServersResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listResourceServers (const ListResourceServersRequest & request) slot
Lists the resource servers for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1465 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListResourceServersResponse *>(send(request));
 }
listUserImportJobs
ListUserImportJobsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserImportJobs (const ListUserImportJobsRequest & request) slot
Lists the user import
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1479 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUserImportJobsResponse *>(send(request));
 }
listUserPoolClients
ListUserPoolClientsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserPoolClients (const ListUserPoolClientsRequest & request) slot
Lists the clients that have been created for the specified user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1493 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUserPoolClientsResponse *>(send(request));
 }
listUserPools
ListUserPoolsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserPools (const ListUserPoolsRequest & request) slot
Lists the user pools associated with an AWS
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1507 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUserPoolsResponse *>(send(request));
 }
listUsers
ListUsersResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUsers (const ListUsersRequest & request) slot
Lists the users in the Amazon Cognito user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1521 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUsersResponse *>(send(request));
 }
listUsersInGroup
ListUsersInGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUsersInGroup (const ListUsersInGroupRequest & request) slot
Lists the users in the specified
group>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1539 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUsersInGroupResponse *>(send(request));
 }
resendConfirmationCode
ResendConfirmationCodeResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::resendConfirmationCode (const ResendConfirmationCodeRequest & request) slot
Resends the confirmation (for confirmation of registration) to a specific user in the user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1553 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResendConfirmationCodeResponse *>(send(request));
 }
respondToAuthChallenge
RespondToAuthChallengeResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::respondToAuthChallenge (const RespondToAuthChallengeRequest & request) slot
Responds to the authentication
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1567 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RespondToAuthChallengeResponse *>(send(request));
 }
setRiskConfiguration
SetRiskConfigurationResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setRiskConfiguration (const SetRiskConfigurationRequest & request) slot
Configures actions on detected risks. To delete the risk configuration for UserPoolId or ClientId, pass null values for all four configuration
types>
To enable Amazon Cognito advanced security features, update the user pool to include the UserPoolAddOns
keyAdvancedSecurityMode>
See
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1590 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetRiskConfigurationResponse *>(send(request));
 }
setUICustomization
SetUICustomizationResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUICustomization (const SetUICustomizationRequest & request) slot
Sets the UI customization information for a user pool's built-in app
UI>
You can specify app UI customization settings for a single client (with a specific clientId) or for all clients (by setting the clientId to ALL). If you specify ALL, the default configuration will be used for every client that has no UI customization set previously. If you specify UI customization settings for a particular client, it will no longer fall back to the ALL configuration.
</p <note>
To use this API, your user pool must have a domain associated with it. Otherwise, there is no place to host the app's pages, and the service will throw an
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1616 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetUICustomizationResponse *>(send(request));
 }
setUserMFAPreference
SetUserMFAPreferenceResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserMFAPreference (const SetUserMFAPreferenceRequest & request) slot
Set the user's multi-factor authentication (MFA) method
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1630 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetUserMFAPreferenceResponse *>(send(request));
 }
setUserPoolMfaConfig
SetUserPoolMfaConfigResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserPoolMfaConfig (const SetUserPoolMfaConfigRequest & request) slot
Set the user pool MFA
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1644 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetUserPoolMfaConfigResponse *>(send(request));
 }
setUserSettings
SetUserSettingsResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserSettings (const SetUserSettingsRequest & request) slot
Sets the user settings like multi-factor authentication (MFA). If MFA is to be removed for a particular attribute pass the attribute with code delivery as null. If null list is passed, all MFA options are
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1659 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetUserSettingsResponse *>(send(request));
 }
signUp
SignUpResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::signUp (const SignUpRequest & request) slot
Registers the user in the specified user pool and creates a user name, password, and user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1673 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SignUpResponse *>(send(request));
 }
startUserImportJob
StartUserImportJobResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::startUserImportJob (const StartUserImportJobRequest & request) slot
Starts the user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1687 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartUserImportJobResponse *>(send(request));
 }
stopUserImportJob
StopUserImportJobResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::stopUserImportJob (const StopUserImportJobRequest & request) slot
Stops the user import
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1701 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopUserImportJobResponse *>(send(request));
 }
updateAuthEventFeedback
UpdateAuthEventFeedbackResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateAuthEventFeedback (const UpdateAuthEventFeedbackRequest & request) slot
Provides the feedback for an authentication event whether it was from a valid user or not. This feedback is used for improving the risk evaluation decision for the user pool as part of Amazon Cognito advanced
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1716 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAuthEventFeedbackResponse *>(send(request));
 }
updateDeviceStatus
UpdateDeviceStatusResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateDeviceStatus (const UpdateDeviceStatusRequest & request) slot
Updates the device
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1730 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDeviceStatusResponse *>(send(request));
 }
updateGroup
UpdateGroupResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateGroup (const UpdateGroupRequest & request) slot
Updates the specified group with the specified
attributes>
Requires developer
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1748 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGroupResponse *>(send(request));
 }
updateIdentityProvider
UpdateIdentityProviderResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateIdentityProvider (const UpdateIdentityProviderRequest & request) slot
Updates identity provider information for a user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1762 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateIdentityProviderResponse *>(send(request));
 }
updateResourceServer
UpdateResourceServerResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateResourceServer (const UpdateResourceServerRequest & request) slot
Updates the name and scopes of resource server. All other fields are
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1776 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateResourceServerResponse *>(send(request));
 }
updateUserAttributes
UpdateUserAttributesResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserAttributes (const UpdateUserAttributesRequest & request) slot
Allows a user to update a specific attribute (one at a
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1790 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserAttributesResponse *>(send(request));
 }
updateUserPool
UpdateUserPoolResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserPool (const UpdateUserPoolRequest & request) slot
Updates the specified user pool with the specified
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1804 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserPoolResponse *>(send(request));
 }
updateUserPoolClient
UpdateUserPoolClientResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserPoolClient (const UpdateUserPoolClientRequest & request) slot
Allows the developer to update the specified user pool client and password
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1818 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserPoolClientResponse *>(send(request));
 }
verifySoftwareToken
VerifySoftwareTokenResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::verifySoftwareToken (const VerifySoftwareTokenRequest & request) slot
Use this API to register a user's entered TOTP code and mark the user's software token MFA status as "verified" if
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1832 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifySoftwareTokenResponse *>(send(request));
 }
verifyUserAttribute
VerifyUserAttributeResponse * QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::verifyUserAttribute (const VerifyUserAttributeRequest & request) slot
Verifies the specified user attributes in the user
Parameters
request Request to send to Amazon Cognito Identity Provider.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1846 of file cognitoidentityproviderclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifyUserAttributeResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cognito-idp/cognitoidentityproviderclient.h
cognito-idp/cognitoidentityproviderclient.cpp