AWS SDK for Qt: QtAws::CodePipeline::CodePipelineClient Class Reference
QtAws::CodePipeline::CodePipelineClient Class Reference
Client for AWS CodePipeline.
Public Slots
AcknowledgeJobResponse * acknowledgeJob (const AcknowledgeJobRequest &request)
AcknowledgeThirdPartyJobResponse * acknowledgeThirdPartyJob (const AcknowledgeThirdPartyJobRequest &request)
CreateCustomActionTypeResponse * createCustomActionType (const CreateCustomActionTypeRequest &request)
CreatePipelineResponse * createPipeline (const CreatePipelineRequest &request)
DeleteCustomActionTypeResponse * deleteCustomActionType (const DeleteCustomActionTypeRequest &request)
DeletePipelineResponse * deletePipeline (const DeletePipelineRequest &request)
DisableStageTransitionResponse * disableStageTransition (const DisableStageTransitionRequest &request)
EnableStageTransitionResponse * enableStageTransition (const EnableStageTransitionRequest &request)
GetJobDetailsResponse * getJobDetails (const GetJobDetailsRequest &request)
GetPipelineResponse * getPipeline (const GetPipelineRequest &request)
GetPipelineExecutionResponse * getPipelineExecution (const GetPipelineExecutionRequest &request)
GetPipelineStateResponse * getPipelineState (const GetPipelineStateRequest &request)
GetThirdPartyJobDetailsResponse * getThirdPartyJobDetails (const GetThirdPartyJobDetailsRequest &request)
ListActionTypesResponse * listActionTypes (const ListActionTypesRequest &request)
ListPipelineExecutionsResponse * listPipelineExecutions (const ListPipelineExecutionsRequest &request)
ListPipelinesResponse * listPipelines (const ListPipelinesRequest &request)
PollForJobsResponse * pollForJobs (const PollForJobsRequest &request)
PollForThirdPartyJobsResponse * pollForThirdPartyJobs (const PollForThirdPartyJobsRequest &request)
PutActionRevisionResponse * putActionRevision (const PutActionRevisionRequest &request)
PutApprovalResultResponse * putApprovalResult (const PutApprovalResultRequest &request)
PutJobFailureResultResponse * putJobFailureResult (const PutJobFailureResultRequest &request)
PutJobSuccessResultResponse * putJobSuccessResult (const PutJobSuccessResultRequest &request)
PutThirdPartyJobFailureResultResponse * putThirdPartyJobFailureResult (const PutThirdPartyJobFailureResultRequest &request)
PutThirdPartyJobSuccessResultResponse * putThirdPartyJobSuccessResult (const PutThirdPartyJobSuccessResultRequest &request)
RetryStageExecutionResponse * retryStageExecution (const RetryStageExecutionRequest &request)
StartPipelineExecutionResponse * startPipelineExecution (const StartPipelineExecutionRequest &request)
UpdatePipelineResponse * updatePipeline (const UpdatePipelineRequest &request)
Public Member Functions
CodePipelineClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodePipelineClient object.
CodePipelineClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodePipelineClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodePipeline.
<fullname>AWS CodePipeline</fullname>
Overview
</p
This is the AWS CodePipeline API Reference. This guide provides descriptions of the actions and data types for AWS CodePipeline. Some functionality for your pipeline is only configurable through the API. For additional information, see the AWS CodePipeline User Guide>
You can use the AWS CodePipeline API to work with pipelines, stages, actions, gates, and transitions, as described
below>
Pipelines are models of automated release processes. Each pipeline is uniquely named, and consists of actions, gates, and stages.
CreatePipeline, which creates a uniquely-named
pipeline>
DeletePipeline, which deletes the specified
pipeline>
GetPipeline, which returns information about the pipeline structure and pipeline metadata, including the pipeline Amazon Resource Name
(ARN)>
GetPipelineExecution, which returns information about a specific execution of a
pipeline>
GetPipelineState, which returns information about the current state of the stages and actions of a
pipeline>
ListPipelines, which gets a summary of all of the pipelines associated with your
account>
ListPipelineExecutions, which gets a summary of the most recent executions for a
pipeline>
StartPipelineExecution, which runs the the most recent revision of an artifact through the
pipeline>
UpdatePipeline, which updates a pipeline with edits or changes to the structure of the
pipeline>
Pipelines include stages, which are logical groupings of gates and actions. Each stage contains one or more actions that must complete before the next stage begins. A stage will result in success or failure. If a stage fails, then the pipeline stops at that stage and will remain stopped until either a new version of an artifact appears in the source location, or a user takes action to re-run the most recent artifact through the pipeline. You can call GetPipelineState, which displays the status of a pipeline, including the status of stages in the pipeline, or GetPipeline, which returns the entire structure of the pipeline, including the stages of that pipeline. For more information about the structure of stages and actions, also refer to the AWS CodePipeline Pipeline Structure Reference>
Pipeline stages include actions, which are categorized into categories such as source or build actions performed within a stage of a pipeline. For example, you can use a source action to import artifacts into a pipeline from a source such as Amazon S3. Like stages, you do not work with actions directly in most cases, but you do define and interact with actions when working with pipeline operations such as CreatePipeline and GetPipelineState.
</p
Pipelines also include transitions, which allow the transition of artifacts from one stage to the next in a pipeline after the actions in one stage
complete>
You can work with transitions by
calling>
DisableStageTransition, which prevents artifacts from transitioning to the next stage in a
pipeline>
EnableStageTransition, which enables transition of artifacts between stages in a pipeline.
</p
Using the API to integrate with AWS CodePipeline
</p
For third-party integrators or developers who want to create their own integrations with AWS CodePipeline, the expected sequence varies from the standard API user. In order to integrate with AWS CodePipeline, developers will need to work with the following
items>
Jobs, which are instances of an action. For example, a job for a source action might import a revision of an artifact from a source.
AcknowledgeJob, which confirms whether a job worker has received the specified
job>
GetJobDetails, which returns the details of a
job>
PollForJobs, which determines whether there are any jobs to act upon,
</p
PutJobFailureResult, which provides details of a job failure,
an>
PutJobSuccessResult, which provides details of a job
success>
Third party jobs, which are instances of an action created by a partner action and integrated into AWS CodePipeline. Partner actions are created by members of the AWS Partner
Network>
You can work with third party jobs by
calling>
AcknowledgeThirdPartyJob, which confirms whether a job worker has received the specified
job>
GetThirdPartyJobDetails, which requests the details of a job for a partner
action>
PollForThirdPartyJobs, which determines whether there are any jobs to act upon,
</p
PutThirdPartyJobFailureResult, which provides details of a job failure,
an>
PutThirdPartyJobSuccessResult, which provides details of a job
Definition at line 86 of file codepipelineclient.h.
Constructor & Destructor Documentation
CodePipelineClient() [1/2]
QtAws::CodePipeline::CodePipelineClient::CodePipelineClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodePipelineClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 263 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CodePipelineClientPrivate(this), parent)
 {
     Q_D(CodePipelineClient);
     d->apiVersion = QStringLiteral("2015-07-09");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("codepipeline");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CodePipeline");
     d->serviceName = QStringLiteral("codepipeline");
 }
CodePipelineClient() [2/2]
QtAws::CodePipeline::CodePipelineClient::CodePipelineClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodePipelineClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 296 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CodePipelineClientPrivate(this), parent)
 {
     Q_D(CodePipelineClient);
     d->apiVersion = QStringLiteral("2015-07-09");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("codepipeline");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CodePipeline");
     d->serviceName = QStringLiteral("codepipeline");
 }
Member Function Documentation
acknowledgeJob
AcknowledgeJobResponse * QtAws::CodePipeline::CodePipelineClient::acknowledgeJob (const AcknowledgeJobRequest & request) slot
Returns information about a specified job and whether that job has been received by the job worker. Only used for custom
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 322 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcknowledgeJobResponse *>(send(request));
 }
acknowledgeThirdPartyJob
AcknowledgeThirdPartyJobResponse * QtAws::CodePipeline::CodePipelineClient::acknowledgeThirdPartyJob (const AcknowledgeThirdPartyJobRequest & request) slot
Confirms a job worker has received the specified job. Only used for partner
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 336 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcknowledgeThirdPartyJobResponse *>(send(request));
 }
createCustomActionType
CreateCustomActionTypeResponse * QtAws::CodePipeline::CodePipelineClient::createCustomActionType (const CreateCustomActionTypeRequest & request) slot
Creates a new custom action that can be used in all pipelines associated with the AWS account. Only used for custom
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 350 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCustomActionTypeResponse *>(send(request));
 }
createPipeline
CreatePipelineResponse * QtAws::CodePipeline::CodePipelineClient::createPipeline (const CreatePipelineRequest & request) slot
Creates a
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 364 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePipelineResponse *>(send(request));
 }
deleteCustomActionType
DeleteCustomActionTypeResponse * QtAws::CodePipeline::CodePipelineClient::deleteCustomActionType (const DeleteCustomActionTypeRequest & request) slot
Marks a custom action as deleted. PollForJobs for the custom action will fail after the action is marked for deletion. Only used for custom
actions>
You cannot recreate a custom action after it has been deleted unless you increase the version number of the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 383 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCustomActionTypeResponse *>(send(request));
 }
deletePipeline
DeletePipelineResponse * QtAws::CodePipeline::CodePipelineClient::deletePipeline (const DeletePipelineRequest & request) slot
Deletes the specified
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 397 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePipelineResponse *>(send(request));
 }
disableStageTransition
DisableStageTransitionResponse * QtAws::CodePipeline::CodePipelineClient::disableStageTransition (const DisableStageTransitionRequest & request) slot
Prevents artifacts in a pipeline from transitioning to the next stage in the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 411 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableStageTransitionResponse *>(send(request));
 }
enableStageTransition
EnableStageTransitionResponse * QtAws::CodePipeline::CodePipelineClient::enableStageTransition (const EnableStageTransitionRequest & request) slot
Enables artifacts in a pipeline to transition to a stage in a
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 425 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableStageTransitionResponse *>(send(request));
 }
getJobDetails
GetJobDetailsResponse * QtAws::CodePipeline::CodePipelineClient::getJobDetails (const GetJobDetailsRequest & request) slot
Returns information about a job. Only used for custom
actions>
When this API is called, AWS CodePipeline returns temporary credentials for the Amazon S3 bucket used to store artifacts for the pipeline, if the action requires access to that Amazon S3 bucket for input or output artifacts. Additionally, this API returns any secret values defined for the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 445 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobDetailsResponse *>(send(request));
 }
getPipeline
GetPipelineResponse * QtAws::CodePipeline::CodePipelineClient::getPipeline (const GetPipelineRequest & request) slot
Returns the metadata, structure, stages, and actions of a pipeline. Can be used to return the entire structure of a pipeline in JSON format, which can then be modified and used to update the pipeline structure with
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 460 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPipelineResponse *>(send(request));
 }
getPipelineExecution
GetPipelineExecutionResponse * QtAws::CodePipeline::CodePipelineClient::getPipelineExecution (const GetPipelineExecutionRequest & request) slot
Returns information about an execution of a pipeline, including details about artifacts, the pipeline execution ID, and the name, version, and status of the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 475 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPipelineExecutionResponse *>(send(request));
 }
getPipelineState
GetPipelineStateResponse * QtAws::CodePipeline::CodePipelineClient::getPipelineState (const GetPipelineStateRequest & request) slot
Returns information about the state of a pipeline, including the stages and
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 489 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPipelineStateResponse *>(send(request));
 }
getThirdPartyJobDetails
GetThirdPartyJobDetailsResponse * QtAws::CodePipeline::CodePipelineClient::getThirdPartyJobDetails (const GetThirdPartyJobDetailsRequest & request) slot
Requests the details of a job for a third party action. Only used for partner
actions>
When this API is called, AWS CodePipeline returns temporary credentials for the Amazon S3 bucket used to store artifacts for the pipeline, if the action requires access to that Amazon S3 bucket for input or output artifacts. Additionally, this API returns any secret values defined for the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 509 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetThirdPartyJobDetailsResponse *>(send(request));
 }
listActionTypes
ListActionTypesResponse * QtAws::CodePipeline::CodePipelineClient::listActionTypes (const ListActionTypesRequest & request) slot
Gets a summary of all AWS CodePipeline action types associated with your
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 523 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListActionTypesResponse *>(send(request));
 }
listPipelineExecutions
ListPipelineExecutionsResponse * QtAws::CodePipeline::CodePipelineClient::listPipelineExecutions (const ListPipelineExecutionsRequest & request) slot
Gets a summary of the most recent executions for a
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 537 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPipelineExecutionsResponse *>(send(request));
 }
listPipelines
ListPipelinesResponse * QtAws::CodePipeline::CodePipelineClient::listPipelines (const ListPipelinesRequest & request) slot
Gets a summary of all of the pipelines associated with your
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 551 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPipelinesResponse *>(send(request));
 }
pollForJobs
PollForJobsResponse * QtAws::CodePipeline::CodePipelineClient::pollForJobs (const PollForJobsRequest & request) slot
Returns information about any jobs for AWS CodePipeline to act
upon>
When this API is called, AWS CodePipeline returns temporary credentials for the Amazon S3 bucket used to store artifacts for the pipeline, if the action requires access to that Amazon S3 bucket for input or output artifacts. Additionally, this API returns any secret values defined for the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 571 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PollForJobsResponse *>(send(request));
 }
pollForThirdPartyJobs
PollForThirdPartyJobsResponse * QtAws::CodePipeline::CodePipelineClient::pollForThirdPartyJobs (const PollForThirdPartyJobsRequest & request) slot
Determines whether there are any third party jobs for a job worker to act on. Only used for partner
actions>
When this API is called, AWS CodePipeline returns temporary credentials for the Amazon S3 bucket used to store artifacts for the pipeline, if the action requires access to that Amazon S3 bucket for input or output
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 590 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PollForThirdPartyJobsResponse *>(send(request));
 }
putActionRevision
PutActionRevisionResponse * QtAws::CodePipeline::CodePipelineClient::putActionRevision (const PutActionRevisionRequest & request) slot
Provides information to AWS CodePipeline about new revisions to a
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 604 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutActionRevisionResponse *>(send(request));
 }
putApprovalResult
PutApprovalResultResponse * QtAws::CodePipeline::CodePipelineClient::putApprovalResult (const PutApprovalResultRequest & request) slot
Provides the response to a manual approval request to AWS CodePipeline. Valid responses include Approved and
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 618 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutApprovalResultResponse *>(send(request));
 }
putJobFailureResult
PutJobFailureResultResponse * QtAws::CodePipeline::CodePipelineClient::putJobFailureResult (const PutJobFailureResultRequest & request) slot
Represents the failure of a job as returned to the pipeline by a job worker. Only used for custom
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 632 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutJobFailureResultResponse *>(send(request));
 }
putJobSuccessResult
PutJobSuccessResultResponse * QtAws::CodePipeline::CodePipelineClient::putJobSuccessResult (const PutJobSuccessResultRequest & request) slot
Represents the success of a job as returned to the pipeline by a job worker. Only used for custom
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 646 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutJobSuccessResultResponse *>(send(request));
 }
putThirdPartyJobFailureResult
PutThirdPartyJobFailureResultResponse * QtAws::CodePipeline::CodePipelineClient::putThirdPartyJobFailureResult (const PutThirdPartyJobFailureResultRequest & request) slot
Represents the failure of a third party job as returned to the pipeline by a job worker. Only used for partner
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 660 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutThirdPartyJobFailureResultResponse *>(send(request));
 }
putThirdPartyJobSuccessResult
PutThirdPartyJobSuccessResultResponse * QtAws::CodePipeline::CodePipelineClient::putThirdPartyJobSuccessResult (const PutThirdPartyJobSuccessResultRequest & request) slot
Represents the success of a third party job as returned to the pipeline by a job worker. Only used for partner
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 674 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutThirdPartyJobSuccessResultResponse *>(send(request));
 }
retryStageExecution
RetryStageExecutionResponse * QtAws::CodePipeline::CodePipelineClient::retryStageExecution (const RetryStageExecutionRequest & request) slot
Resumes the pipeline execution by retrying the last failed actions in a
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 688 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RetryStageExecutionResponse *>(send(request));
 }
startPipelineExecution
StartPipelineExecutionResponse * QtAws::CodePipeline::CodePipelineClient::startPipelineExecution (const StartPipelineExecutionRequest & request) slot
Starts the specified pipeline. Specifically, it begins processing the latest commit to the source location specified as part of the
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 703 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartPipelineExecutionResponse *>(send(request));
 }
updatePipeline
UpdatePipelineResponse * QtAws::CodePipeline::CodePipelineClient::updatePipeline (const UpdatePipelineRequest & request) slot
Updates a specified pipeline with edits or changes to its structure. Use a JSON file with the pipeline structure in conjunction with UpdatePipeline to provide the full structure of the pipeline. Updating the pipeline increases the version number of the pipeline by
Parameters
request Request to send to AWS CodePipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file codepipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdatePipelineResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
codepipeline/codepipelineclient.h
codepipeline/codepipelineclient.cpp