AWS SDK for Qt: QtAws::ServiceDiscovery::ServiceDiscoveryClient Class Reference
QtAws::ServiceDiscovery::ServiceDiscoveryClient Class Reference
Client for Amazon Route 53 Auto Naming (ServiceDiscovery)
Public Slots
CreatePrivateDnsNamespaceResponse * createPrivateDnsNamespace (const CreatePrivateDnsNamespaceRequest &request)
CreatePublicDnsNamespaceResponse * createPublicDnsNamespace (const CreatePublicDnsNamespaceRequest &request)
CreateServiceResponse * createService (const CreateServiceRequest &request)
DeleteNamespaceResponse * deleteNamespace (const DeleteNamespaceRequest &request)
DeleteServiceResponse * deleteService (const DeleteServiceRequest &request)
DeregisterInstanceResponse * deregisterInstance (const DeregisterInstanceRequest &request)
GetInstanceResponse * getInstance (const GetInstanceRequest &request)
GetInstancesHealthStatusResponse * getInstancesHealthStatus (const GetInstancesHealthStatusRequest &request)
GetNamespaceResponse * getNamespace (const GetNamespaceRequest &request)
GetOperationResponse * getOperation (const GetOperationRequest &request)
GetServiceResponse * getService (const GetServiceRequest &request)
ListInstancesResponse * listInstances (const ListInstancesRequest &request)
ListNamespacesResponse * listNamespaces (const ListNamespacesRequest &request)
ListOperationsResponse * listOperations (const ListOperationsRequest &request)
ListServicesResponse * listServices (const ListServicesRequest &request)
RegisterInstanceResponse * registerInstance (const RegisterInstanceRequest &request)
UpdateInstanceCustomHealthStatusResponse * updateInstanceCustomHealthStatus (const UpdateInstanceCustomHealthStatusRequest &request)
UpdateServiceResponse * updateService (const UpdateServiceRequest &request)
Public Member Functions
ServiceDiscoveryClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServiceDiscoveryClient object.
ServiceDiscoveryClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServiceDiscoveryClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Route 53 Auto Naming (ServiceDiscovery)
Amazon Route 53 auto naming lets you configure public or private namespaces that your microservice applications run in. When instances of the service become available, you can call the auto naming API to register the instance, and Route 53 automatically creates up to five DNS records and an optional health check. Clients that submit DNS queries for the service receive an answer that contains up to eight healthy
Definition at line 68 of file servicediscoveryclient.h.
Constructor & Destructor Documentation
ServiceDiscoveryClient() [1/2]
QtAws::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServiceDiscoveryClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 86 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ServiceDiscoveryClientPrivate(this), parent)
 {
     Q_D(ServiceDiscoveryClient);
     d->apiVersion = QStringLiteral("2017-03-14");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("servicediscovery");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Route 53 Auto Naming");
     d->serviceName = QStringLiteral("servicediscovery");
 }
ServiceDiscoveryClient() [2/2]
QtAws::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServiceDiscoveryClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 119 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ServiceDiscoveryClientPrivate(this), parent)
 {
     Q_D(ServiceDiscoveryClient);
     d->apiVersion = QStringLiteral("2017-03-14");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("servicediscovery");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Route 53 Auto Naming");
     d->serviceName = QStringLiteral("servicediscovery");
 }
Member Function Documentation
createPrivateDnsNamespace
CreatePrivateDnsNamespaceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::createPrivateDnsNamespace (const CreatePrivateDnsNamespaceRequest & request) slot
Creates a private namespace based on DNS, which will be visible only inside a specified Amazon VPC. The namespace defines your service naming scheme. For example, if you name your namespace example.com and name your service backend, the resulting DNS name for the service will be backend.example.com. For the current limit on the number of namespaces that you can create using the same AWS account, see Limits on Auto Naming in the Route 53 Developer
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 150 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePrivateDnsNamespaceResponse *>(send(request));
 }
createPublicDnsNamespace
CreatePublicDnsNamespaceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::createPublicDnsNamespace (const CreatePublicDnsNamespaceRequest & request) slot
Creates a public namespace based on DNS, which will be visible on the internet. The namespace defines your service naming scheme. For example, if you name your namespace example.com and name your service backend, the resulting DNS name for the service will be backend.example.com. For the current limit on the number of namespaces that you can create using the same AWS account, see Limits on Auto Naming in the Route 53 Developer
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 169 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePublicDnsNamespaceResponse *>(send(request));
 }
createService
CreateServiceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::createService (const CreateServiceRequest & request) slot
Creates a service, which defines the configuration for the following
entities>
Up to three records (A, AAAA, and SRV) or one CNAME
recor>
Optionally, a health
chec>
After you create the service, you can submit a RegisterInstance request, and Amazon Route 53 uses the values in the configuration to create the specified
entities>
For the current limit on the number of instances that you can register using the same namespace and using the same service, see Limits on Auto Naming in the Route 53 Developer
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 203 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateServiceResponse *>(send(request));
 }
deleteNamespace
DeleteNamespaceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::deleteNamespace (const DeleteNamespaceRequest & request) slot
Deletes a namespace from the current account. If the namespace still contains one or more services, the request
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 217 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNamespaceResponse *>(send(request));
 }
deleteService
DeleteServiceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::deleteService (const DeleteServiceRequest & request) slot
Deletes a specified service. If the service still contains one or more registered instances, the request
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 231 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServiceResponse *>(send(request));
 }
deregisterInstance
DeregisterInstanceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::deregisterInstance (const DeregisterInstanceRequest & request) slot
Deletes the records and the health check, if any, that Amazon Route 53 created for the specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterInstanceResponse *>(send(request));
 }
getInstance
GetInstanceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::getInstance (const GetInstanceRequest & request) slot
Gets information about a specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetInstanceResponse *>(send(request));
 }
getInstancesHealthStatus
GetInstancesHealthStatusResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::getInstancesHealthStatus (const GetInstancesHealthStatusRequest & request) slot
Gets the current health status (Healthy, Unhealthy, or Unknown) of one or more instances that are associated with a specified
service> <note>
There is a brief delay between when you register an instance and when the health status for the instance is available.
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetInstancesHealthStatusResponse *>(send(request));
 }
getNamespace
GetNamespaceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::getNamespace (const GetNamespaceRequest & request) slot
Gets information about a
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetNamespaceResponse *>(send(request));
 }
getOperation
GetOperationResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::getOperation (const GetOperationRequest & request) slot
Gets information about any operation that returns an operation ID in the response, such as a CreateService
request> <note>
To get a list of operations that match specified criteria, see
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 310 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetOperationResponse *>(send(request));
 }
getService
GetServiceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::getService (const GetServiceRequest & request) slot
Gets the settings for a specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 324 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetServiceResponse *>(send(request));
 }
listInstances
ListInstancesResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::listInstances (const ListInstancesRequest & request) slot
Lists summary information about the instances that you registered by using a specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 338 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstancesResponse *>(send(request));
 }
listNamespaces
ListNamespacesResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::listNamespaces (const ListNamespacesRequest & request) slot
Lists summary information about the namespaces that were created by the current AWS
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 352 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListNamespacesResponse *>(send(request));
 }
listOperations
ListOperationsResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::listOperations (const ListOperationsRequest & request) slot
Lists operations that match the criteria that you
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 366 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOperationsResponse *>(send(request));
 }
listServices
ListServicesResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::listServices (const ListServicesRequest & request) slot
Lists summary information for all the services that are associated with one or more specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 380 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListServicesResponse *>(send(request));
 }
registerInstance
RegisterInstanceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::registerInstance (const RegisterInstanceRequest & request) slot
Creates or updates one or more records and optionally a health check based on the settings in a specified service. When you submit a RegisterInstance request, Amazon Route 53 does the
following>
For each DNS record that you define in the service specified by ServiceId, creates or updates a record in the hosted zone that is associated with the corresponding
namespac>
If the service includes HealthCheckConfig, creates or updates a health check based on the settings in the health check
configuratio>
Associates the health check, if any, with each of the
record>
One RegisterInstance request must complete before you can submit another request and specify the same service ID and instance
ID>
For more information, see
CreateService>
When Route 53 receives a DNS query for the specified DNS name, it returns the applicable
value>
If the health check is healthy: returns all the
record>
If the health check is unhealthy: returns the applicable value for the last healthy
instanc>
If you didn't specify a health check configuration: returns all the
record>
For the current limit on the number of instances that you can register using the same namespace and using the same service, see Limits on Auto Naming in the Route 53 Developer
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 441 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterInstanceResponse *>(send(request));
 }
updateInstanceCustomHealthStatus
UpdateInstanceCustomHealthStatusResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::updateInstanceCustomHealthStatus (const UpdateInstanceCustomHealthStatusRequest & request) slot
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 454 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateInstanceCustomHealthStatusResponse *>(send(request));
 }
updateService
UpdateServiceResponse * QtAws::ServiceDiscovery::ServiceDiscoveryClient::updateService (const UpdateServiceRequest & request) slot
Submits a request to perform the following
operations>
Add or delete DnsRecords
configuration>
Update the TTL setting for existing DnsRecords
configuration>
Add, update, or delete HealthCheckConfig for a specified
servic>
You must specify all DnsRecords configurations (and, optionally, HealthCheckConfig) that you want to appear in the updated service. Any current configurations that don't appear in an UpdateService request are
deleted>
When you update the TTL setting for a service, Amazon Route 53 also updates the corresponding settings in all the records and health checks that were created by using the specified
Parameters
request Request to send to Amazon Route 53 Auto Naming.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 491 of file servicediscoveryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateServiceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
servicediscovery/servicediscoveryclient.h
servicediscovery/servicediscoveryclient.cpp