AWS SDK for Qt: QtAws::GameLift::GameLiftRequest Class Reference
QtAws::GameLift::GameLiftRequest Class Reference
Interface class for providing GameLift requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::GameLift::AcceptMatchRequest, QtAws::GameLift::CreateAliasRequest, QtAws::GameLift::CreateBuildRequest, QtAws::GameLift::CreateFleetRequest, QtAws::GameLift::CreateGameSessionQueueRequest, QtAws::GameLift::CreateGameSessionRequest, QtAws::GameLift::CreateMatchmakingConfigurationRequest, QtAws::GameLift::CreateMatchmakingRuleSetRequest, QtAws::GameLift::CreatePlayerSessionRequest, QtAws::GameLift::CreatePlayerSessionsRequest, QtAws::GameLift::CreateVpcPeeringAuthorizationRequest, QtAws::GameLift::CreateVpcPeeringConnectionRequest, QtAws::GameLift::DeleteAliasRequest, QtAws::GameLift::DeleteBuildRequest, QtAws::GameLift::DeleteFleetRequest, QtAws::GameLift::DeleteGameSessionQueueRequest, QtAws::GameLift::DeleteMatchmakingConfigurationRequest, QtAws::GameLift::DeleteScalingPolicyRequest, QtAws::GameLift::DeleteVpcPeeringAuthorizationRequest, QtAws::GameLift::DeleteVpcPeeringConnectionRequest, QtAws::GameLift::DescribeAliasRequest, QtAws::GameLift::DescribeBuildRequest, QtAws::GameLift::DescribeEC2InstanceLimitsRequest, QtAws::GameLift::DescribeFleetAttributesRequest, QtAws::GameLift::DescribeFleetCapacityRequest, QtAws::GameLift::DescribeFleetEventsRequest, QtAws::GameLift::DescribeFleetPortSettingsRequest, QtAws::GameLift::DescribeFleetUtilizationRequest, QtAws::GameLift::DescribeGameSessionDetailsRequest, QtAws::GameLift::DescribeGameSessionPlacementRequest, QtAws::GameLift::DescribeGameSessionQueuesRequest, QtAws::GameLift::DescribeGameSessionsRequest, QtAws::GameLift::DescribeInstancesRequest, QtAws::GameLift::DescribeMatchmakingConfigurationsRequest, QtAws::GameLift::DescribeMatchmakingRequest, QtAws::GameLift::DescribeMatchmakingRuleSetsRequest, QtAws::GameLift::DescribePlayerSessionsRequest, QtAws::GameLift::DescribeRuntimeConfigurationRequest, QtAws::GameLift::DescribeScalingPoliciesRequest, QtAws::GameLift::DescribeVpcPeeringAuthorizationsRequest, QtAws::GameLift::DescribeVpcPeeringConnectionsRequest, QtAws::GameLift::GetGameSessionLogUrlRequest, QtAws::GameLift::GetInstanceAccessRequest, QtAws::GameLift::ListAliasesRequest, QtAws::GameLift::ListBuildsRequest, QtAws::GameLift::ListFleetsRequest, QtAws::GameLift::PutScalingPolicyRequest, QtAws::GameLift::RequestUploadCredentialsRequest, QtAws::GameLift::ResolveAliasRequest, QtAws::GameLift::SearchGameSessionsRequest, QtAws::GameLift::StartGameSessionPlacementRequest, QtAws::GameLift::StartMatchBackfillRequest, QtAws::GameLift::StartMatchmakingRequest, QtAws::GameLift::StopGameSessionPlacementRequest, QtAws::GameLift::StopMatchmakingRequest, QtAws::GameLift::UpdateAliasRequest, QtAws::GameLift::UpdateBuildRequest, QtAws::GameLift::UpdateFleetAttributesRequest, QtAws::GameLift::UpdateFleetCapacityRequest, QtAws::GameLift::UpdateFleetPortSettingsRequest, QtAws::GameLift::UpdateGameSessionQueueRequest, QtAws::GameLift::UpdateGameSessionRequest, QtAws::GameLift::UpdateMatchmakingConfigurationRequest, QtAws::GameLift::UpdateRuntimeConfigurationRequest, and QtAws::GameLift::ValidateMatchmakingRuleSetRequest.
Public Types
enum Action {
AcceptMatchAction, CreateAliasAction, CreateBuildAction, CreateFleetAction,
CreateGameSessionAction, CreateGameSessionQueueAction, CreateMatchmakingConfigurationAction, CreateMatchmakingRuleSetAction,
CreatePlayerSessionAction, CreatePlayerSessionsAction, CreateVpcPeeringAuthorizationAction, CreateVpcPeeringConnectionAction,
DeleteAliasAction, DeleteBuildAction, DeleteFleetAction, DeleteGameSessionQueueAction,
DeleteMatchmakingConfigurationAction, DeleteScalingPolicyAction, DeleteVpcPeeringAuthorizationAction, DeleteVpcPeeringConnectionAction,
DescribeAliasAction, DescribeBuildAction, DescribeEC2InstanceLimitsAction, DescribeFleetAttributesAction,
DescribeFleetCapacityAction, DescribeFleetEventsAction, DescribeFleetPortSettingsAction, DescribeFleetUtilizationAction,
DescribeGameSessionDetailsAction, DescribeGameSessionPlacementAction, DescribeGameSessionQueuesAction, DescribeGameSessionsAction,
DescribeInstancesAction, DescribeMatchmakingAction, DescribeMatchmakingConfigurationsAction, DescribeMatchmakingRuleSetsAction,
DescribePlayerSessionsAction, DescribeRuntimeConfigurationAction, DescribeScalingPoliciesAction, DescribeVpcPeeringAuthorizationsAction,
DescribeVpcPeeringConnectionsAction, GetGameSessionLogUrlAction, GetInstanceAccessAction, ListAliasesAction,
ListBuildsAction, ListFleetsAction, PutScalingPolicyAction, RequestUploadCredentialsAction,
ResolveAliasAction, SearchGameSessionsAction, StartGameSessionPlacementAction, StartMatchBackfillAction,
StartMatchmakingAction, StopGameSessionPlacementAction, StopMatchmakingAction, UpdateAliasAction,
UpdateBuildAction, UpdateFleetAttributesAction, UpdateFleetCapacityAction, UpdateFleetPortSettingsAction,
UpdateGameSessionAction, UpdateGameSessionQueueAction, UpdateMatchmakingConfigurationAction, UpdateRuntimeConfigurationAction,
ValidateMatchmakingRuleSetAction
}
Actions supported by GameLift.
Public Member Functions
GameLiftRequest (const Action action)
Constructs a new GameLiftRequest object.
GameLiftRequest (const GameLiftRequest &other)
Constructs a new GameLiftRequest object by copying another.
GameLiftRequest & operator= (const GameLiftRequest &other)
Assignment operator.
Action action () const
Get the GameLift action to be performed by this request.
QString actionString () const
Get the name of the GameLift action to be performed by this request.
QString apiVersion () const
Get the GameLift API version implemented by this request.
void setAction (const Action action)
Set the GameLift action to be performed by this request.
void setApiVersion (const QString &version)
Set the GameLift API version to include in this request.
virtual bool operator== (const GameLiftRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
GameLiftRequest (GameLiftRequestPrivate *const d)
Constructs a new GameLiftRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid GameLift queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this GameLift request.
const QVariantMap & parameters () const
Get all parameters included with this GameLift request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this GameLift request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this GameLift request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this GameLift request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing GameLift requests.
Definition at line 35 of file gameliftrequest.h.
Constructor & Destructor Documentation
GameLiftRequest() [1/3]
QtAws::GameLift::GameLiftRequest::GameLiftRequest (const Action action)
Constructs a new GameLiftRequest object.
Parameters
action The GameLift action to request.
Definition at line 38 of file gameliftrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new GameLiftRequestPrivate(action, this))
 {
 }
GameLiftRequest() [2/3]
QtAws::GameLift::GameLiftRequest::GameLiftRequest (const GameLiftRequest & other)
Constructs a new GameLiftRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file gameliftrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new GameLiftRequestPrivate(*other.d_func(), this))
 {
 }
GameLiftRequest() [3/3]
QtAws::GameLift::GameLiftRequest::GameLiftRequest (GameLiftRequestPrivate *const d) protected
Constructs a new GameLiftRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from GameLiftRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file gameliftrequest.cpp.
                                                                  : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
GameLiftRequest::Action QtAws::GameLift::GameLiftRequest::action () const
Get the GameLift action to be performed by this request.
Returns
The GameLift action to be performed by this request.
Definition at line 93 of file gameliftrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const GameLiftRequest);
     return d->action;
 }
actionString()
QString QtAws::GameLift::GameLiftRequest::actionString () const
Get the name of the GameLift action to be performed by this request.
Returns
The name of the GameLift action to be performed by this request.
Definition at line 104 of file gameliftrequest.cpp.
References action(), and QtAws::GameLift::GameLiftRequestPrivate::toString().
 {
     return GameLiftRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::GameLift::GameLiftRequest::apiVersion () const
Get the GameLift API version implemented by this request.
Returns
The GameLift API version implmented by this request.
Definition at line 114 of file gameliftrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const GameLiftRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::GameLift::GameLiftRequest::clearParameter (const QString & name) protected
Check if queueName is a valid GameLift queue name.
From GameLift FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid GameLift queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file gameliftrequest.cpp.
 {
     Q_D(GameLiftRequest);
     return d->parameters.remove(name);
 }
operator=()
GameLiftRequest & QtAws::GameLift::GameLiftRequest::operator= (const GameLiftRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file gameliftrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(GameLiftRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::GameLift::GameLiftRequest::operator== (const GameLiftRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file gameliftrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::GameLift::GameLiftRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this GameLift request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file gameliftrequest.cpp.
 {
     Q_D(const GameLiftRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::GameLift::GameLiftRequest::parameters () const protected
Get all parameters included with this GameLift request.
Returns
A map of parameters included with this request.
Definition at line 222 of file gameliftrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const GameLiftRequest);
     return d->parameters;
 }
setAction()
void QtAws::GameLift::GameLiftRequest::setAction (const Action action)
Set the GameLift action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file gameliftrequest.cpp.
References action().
 {
     Q_D(GameLiftRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::GameLift::GameLiftRequest::setApiVersion (const QString & version)
Set the GameLift API version to include in this request.
Parameters
version The GameLift API version to include in this request.
Definition at line 136 of file gameliftrequest.cpp.
 {
     Q_D(GameLiftRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::GameLift::GameLiftRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this GameLift request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file gameliftrequest.cpp.
 {
     Q_D(GameLiftRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::GameLift::GameLiftRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this GameLift request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file gameliftrequest.cpp.
References parameters().
 {
     Q_D(GameLiftRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::GameLift::GameLiftRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this GameLift request.
This GameLift implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this GameLift request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file gameliftrequest.cpp.
 {
     Q_D(const GameLiftRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
gamelift/gameliftrequest.h
gamelift/gameliftrequest.cpp