AWS SDK for Qt: QtAws::EFS::EfsClient Class Reference
QtAws::EFS::EfsClient Class Reference
Client for Amazon Elastic File System (EFS)
Public Slots
CreateFileSystemResponse * createFileSystem (const CreateFileSystemRequest &request)
CreateMountTargetResponse * createMountTarget (const CreateMountTargetRequest &request)
CreateTagsResponse * createTags (const CreateTagsRequest &request)
DeleteFileSystemResponse * deleteFileSystem (const DeleteFileSystemRequest &request)
DeleteMountTargetResponse * deleteMountTarget (const DeleteMountTargetRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeFileSystemsResponse * describeFileSystems (const DescribeFileSystemsRequest &request)
DescribeMountTargetSecurityGroupsResponse * describeMountTargetSecurityGroups (const DescribeMountTargetSecurityGroupsRequest &request)
DescribeMountTargetsResponse * describeMountTargets (const DescribeMountTargetsRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
ModifyMountTargetSecurityGroupsResponse * modifyMountTargetSecurityGroups (const ModifyMountTargetSecurityGroupsRequest &request)
Public Member Functions
EfsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EfsClient object.
EfsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EfsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Elastic File System (EFS)
<fullname>Amazon Elastic File System</fullname>
Amazon Elastic File System (Amazon EFS) provides simple, scalable file storage for use with Amazon EC2 instances in the AWS Cloud. With Amazon EFS, storage capacity is elastic, growing and shrinking automatically as you add and remove files, so your applications have the storage they need, when they need it. For more information, see the User
Definition at line 54 of file efsclient.h.
Constructor & Destructor Documentation
EfsClient() [1/2]
QtAws::EFS::EfsClient::EfsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EfsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 74 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new EfsClientPrivate(this), parent)
 {
     Q_D(EfsClient);
     d->apiVersion = QStringLiteral("2015-02-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("elasticfilesystem");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Elastic File System");
     d->serviceName = QStringLiteral("elasticfilesystem");
 }
EfsClient() [2/2]
QtAws::EFS::EfsClient::EfsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EfsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 107 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new EfsClientPrivate(this), parent)
 {
     Q_D(EfsClient);
     d->apiVersion = QStringLiteral("2015-02-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("elasticfilesystem");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Elastic File System");
     d->serviceName = QStringLiteral("elasticfilesystem");
 }
Member Function Documentation
createFileSystem
CreateFileSystemResponse * QtAws::EFS::EfsClient::createFileSystem (const CreateFileSystemRequest & request) slot
Creates a new, empty file system. The operation requires a creation token in the request that Amazon EFS uses to ensure idempotent creation (calling the operation with same creation token has no effect). If a file system does not currently exist that is owned by the caller's AWS account with the specified creation token, this operation does the
following>
Creates a new, empty file system. The file system will have an Amazon EFS assigned ID, and an initial lifecycle state
creating>
Returns with the description of the created file
system>
Otherwise, this operation returns a FileSystemAlreadyExists error with the ID of the existing file
system> <note>
For basic use cases, you can use a randomly generated UUID for the creation
token> </note>
The idempotent operation allows you to retry a CreateFileSystem call without risk of creating an extra file system. This can happen when an initial call fails in a way that leaves it uncertain whether or not a file system was actually created. An example might be that a transport level timeout occurred or your connection was reset. As long as you use the same creation token, if the initial call had succeeded in creating a file system, the client can learn of its existence from the FileSystemAlreadyExists
error> <note>
The CreateFileSystem call returns while the file system's lifecycle state is still creating. You can check the file system creation status by calling the DescribeFileSystems operation, which among other things returns the file system
state> </note>
This operation also takes an optional PerformanceMode parameter that you choose for your file system. We recommend generalPurpose performance mode for most file systems. File systems using the maxIO performance mode can scale to higher levels of aggregate throughput and operations per second with a tradeoff of slightly higher latencies for most file operations. The performance mode can't be changed after the file system has been created. For more information, see Amazon EFS: Performance Modes>
After the file system is fully created, Amazon EFS sets its lifecycle state to available, at which point you can create one or more mount targets for the file system in your VPC. For more information, see CreateMountTarget. You mount your Amazon EFS file system on an EC2 instances in your VPC via the mount target. For more information, see Amazon EFS: How it Works.
</p
This operation requires permissions for the elasticfilesystem:CreateFileSystem action.
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 186 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFileSystemResponse *>(send(request));
 }
createMountTarget
CreateMountTargetResponse * QtAws::EFS::EfsClient::createMountTarget (const CreateMountTargetRequest & request) slot
Creates a mount target for a file system. You can then mount the file system on EC2 instances via the mount
target>
You can create one mount target in each Availability Zone in your VPC. All EC2 instances in a VPC within a given Availability Zone share a single mount target for a given file system. If you have multiple subnets in an Availability Zone, you create a mount target in one of the subnets. EC2 instances do not need to be in the same subnet as the mount target in order to access their file system. For more information, see Amazon EFS: How it Works.
</p
In the request, you also specify a file system ID for which you are creating the mount target and the file system's lifecycle state must be available. For more information, see
DescribeFileSystems>
In the request, you also provide a subnet ID, which determines the
following>
VPC in which Amazon EFS creates the mount
targe>
Availability Zone in which Amazon EFS creates the mount
targe>
IP address range from which Amazon EFS selects the IP address of the mount target (if you don't specify an IP address in the
request>
After creating the mount target, Amazon EFS returns a response that includes, a MountTargetId and an IpAddress. You use this IP address when mounting the file system in an EC2 instance. You can also use the mount target's DNS name when mounting the file system. The EC2 instance on which you mount the file system via the mount target can resolve the mount target's DNS name to its IP address. For more information, see How it Works: Implementation Overview.
</p
Note that you can create mount targets for a file system in only one VPC, and there can be only one mount target per Availability Zone. That is, if the file system already has one or more mount targets created for it, the subnet specified in the request to add another mount target must meet the following
requirements>
Must belong to the same VPC as the subnets of the existing mount
target>
Must not be in the same Availability Zone as any of the subnets of the existing mount
target>
If the request satisfies the requirements, Amazon EFS does the
following>
Creates a new mount target in the specified
subnet>
Also creates a new network interface in the subnet as
follows>
If the request provides an IpAddress, Amazon EFS assigns that IP address to the network interface. Otherwise, Amazon EFS assigns a free address in the subnet (in the same way that the Amazon EC2 CreateNetworkInterface call does when a request does not specify a primary private IP
address)>
If the request provides SecurityGroups, this network interface is associated with those security groups. Otherwise, it belongs to the default security group for the subnet's
VPC>
Assigns the description Mount target fsmt-id for file system fs-id where fsmt-id is the mount target ID, and fs-id is the
FileSystemId>
Sets the requesterManaged property of the network interface to true, and the requesterId value to
EFS>
Each Amazon EFS mount target has one corresponding requester-managed EC2 network interface. After the network interface is created, Amazon EFS sets the NetworkInterfaceId field in the mount target's description to the network interface ID, and the IpAddress field to its address. If network interface creation fails, the entire CreateMountTarget operation
fails>
<note>
The CreateMountTarget call returns only after creating the network interface, but while the mount target state is still creating, you can check the mount target creation status by calling the DescribeMountTargets operation, which among other things returns the mount target
state> </note>
We recommend you create a mount target in each of the Availability Zones. There are cost considerations for using a file system in an Availability Zone through a mount target created in another Availability Zone. For more information, see Amazon EFS. In addition, by always using a mount target local to the instance's Availability Zone, you eliminate a partial failure scenario. If the Availability Zone in which your mount target is created goes down, then you won't be able to access your file system through that mount target.
elasticfilesystem:CreateMountTarget
</p
This operation also requires permissions for the following Amazon EC2
actions>
ec2:DescribeSubnets
</p
ec2:DescribeNetworkInterfaces
</p
ec2:CreateNetworkInterface
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 331 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateMountTargetResponse *>(send(request));
 }
createTags
CreateTagsResponse * QtAws::EFS::EfsClient::createTags (const CreateTagsRequest & request) slot
Creates or overwrites tags associated with a file system. Each tag is a key-value pair. If a tag key specified in the request already exists on the file system, this operation overwrites its value with the value provided in the request. If you add the Name tag to your file system, Amazon EFS returns it in the response to the DescribeFileSystems operation.
</p
This operation requires permission for the elasticfilesystem:CreateTags
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 352 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTagsResponse *>(send(request));
 }
deleteFileSystem
DeleteFileSystemResponse * QtAws::EFS::EfsClient::deleteFileSystem (const DeleteFileSystemRequest & request) slot
Deletes a file system, permanently severing access to its contents. Upon return, the file system no longer exists and you can't access any contents of the deleted file
system>
You can't delete a file system that is in use. That is, if the file system has any mount targets, you must first delete them. For more information, see DescribeMountTargets and DeleteMountTarget.
</p <note>
The DeleteFileSystem call returns while the file system state is still deleting. You can check the file system deletion status by calling the DescribeFileSystems operation, which returns a list of file systems in your account. If you pass file system ID or creation token for the deleted file system, the DescribeFileSystems returns a 404 FileSystemNotFound
error> </note>
This operation requires permissions for the elasticfilesystem:DeleteFileSystem
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 383 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFileSystemResponse *>(send(request));
 }
deleteMountTarget
DeleteMountTargetResponse * QtAws::EFS::EfsClient::deleteMountTarget (const DeleteMountTargetRequest & request) slot
Deletes the specified mount
target>
This operation forcibly breaks any mounts of the file system via the mount target that is being deleted, which might disrupt instances or applications using those mounts. To avoid applications getting cut off abruptly, you might consider unmounting any mounts of the mount target, if feasible. The operation also deletes the associated network interface. Uncommitted writes may be lost, but breaking a mount target using this operation does not corrupt the file system itself. The file system you created remains. You can mount an EC2 instance in your VPC via another mount
target>
This operation requires permissions for the following action on the file
system>
elasticfilesystem:DeleteMountTarget
</p
<note>
The DeleteMountTarget call returns while the mount target state is still deleting. You can check the mount target deletion by calling the DescribeMountTargets operation, which returns a list of mount target descriptions for the given file system.
</p </note>
The operation also requires permissions for the following Amazon EC2 action on the mount target's network
interface>
ec2:DeleteNetworkInterface
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 427 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMountTargetResponse *>(send(request));
 }
deleteTags
DeleteTagsResponse * QtAws::EFS::EfsClient::deleteTags (const DeleteTagsRequest & request) slot
Deletes the specified tags from a file system. If the DeleteTags request includes a tag key that does not exist, Amazon EFS ignores it and doesn't cause an error. For more information about tags and related restrictions, see Tag Restrictions in the AWS Billing and Cost Management User
Guide>
This operation requires permissions for the elasticfilesystem:DeleteTags
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 448 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsResponse *>(send(request));
 }
describeFileSystems
DescribeFileSystemsResponse * QtAws::EFS::EfsClient::describeFileSystems (const DescribeFileSystemsRequest & request) slot
Returns the description of a specific Amazon EFS file system if either the file system CreationToken or the FileSystemId is provided. Otherwise, it returns descriptions of all file systems owned by the caller's AWS account in the AWS Region of the endpoint that you're
calling>
When retrieving all file system descriptions, you can optionally specify the MaxItems parameter to limit the number of descriptions in a response. If more file system descriptions remain, Amazon EFS returns a NextMarker, an opaque token, in the response. In this case, you should send a subsequent request with the Marker request parameter set to the value of NextMarker.
</p
To retrieve a list of your file system descriptions, this operation is used in an iterative process, where DescribeFileSystems is called first without the Marker and then the operation continues to call it with the Marker parameter set to the value of the NextMarker from the previous response until the response has no NextMarker.
</p
The implementation may return fewer than MaxItems file system descriptions while still including a NextMarker value.
</p
The order of file systems returned in the response of one DescribeFileSystems call and the order of file systems returned across the responses of a multi-call iteration is unspecified.
</p
This operation requires permissions for the elasticfilesystem:DescribeFileSystems action.
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 492 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFileSystemsResponse *>(send(request));
 }
describeMountTargets
DescribeMountTargetsResponse * QtAws::EFS::EfsClient::describeMountTargets (const DescribeMountTargetsRequest & request) slot
Returns the descriptions of all the current mount targets, or a specific mount target, for a file system. When requesting all of the current mount targets, the order of mount targets returned in the response is
unspecified>
This operation requires permissions for the elasticfilesystem:DescribeMountTargets action, on either the file system ID that you specify in FileSystemId, or on the file system of the mount target that you specify in
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 540 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMountTargetsResponse *>(send(request));
 }
describeMountTargetSecurityGroups
DescribeMountTargetSecurityGroupsResponse * QtAws::EFS::EfsClient::describeMountTargetSecurityGroups (const DescribeMountTargetSecurityGroupsRequest & request) slot
Returns the security groups currently in effect for a mount target. This operation requires that the network interface of the mount target has been created and the lifecycle state of the mount target is not
deleted>
This operation requires permissions for the following
actions>
elasticfilesystem:DescribeMountTargetSecurityGroups action on the mount target's file system.
</p
ec2:DescribeNetworkInterfaceAttribute action on the mount target's network interface.
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 519 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMountTargetSecurityGroupsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::EFS::EfsClient::describeTags (const DescribeTagsRequest & request) slot
Returns the tags associated with a file system. The order of tags returned in the response of one DescribeTags call and the order of tags returned across the responses of a multi-call iteration (when using pagination) is unspecified.
</p
This operation requires permissions for the elasticfilesystem:DescribeTags action.
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 560 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
modifyMountTargetSecurityGroups
ModifyMountTargetSecurityGroupsResponse * QtAws::EFS::EfsClient::modifyMountTargetSecurityGroups (const ModifyMountTargetSecurityGroupsRequest & request) slot
Modifies the set of security groups in effect for a mount
target>
When you create a mount target, Amazon EFS also creates a new network interface. For more information, see CreateMountTarget. This operation replaces the security groups in effect for the network interface associated with a mount target, with the SecurityGroups provided in the request. This operation requires that the network interface of the mount target has been created and the lifecycle state of the mount target is not deleted.
elasticfilesystem:ModifyMountTargetSecurityGroups action on the mount target's file system.
</p
ec2:ModifyNetworkInterfaceAttribute action on the mount target's network interface.
Parameters
request Request to send to Amazon Elastic File System.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 594 of file efsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyMountTargetSecurityGroupsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
elasticfilesystem/efsclient.h
elasticfilesystem/efsclient.cpp