AWS SDK for Qt: QtAws::SMS::SmsClient Class Reference
QtAws::SMS::SmsClient Class Reference
Client for AWS Server Migration Service (SMS)
Public Slots
CreateReplicationJobResponse * createReplicationJob (const CreateReplicationJobRequest &request)
DeleteReplicationJobResponse * deleteReplicationJob (const DeleteReplicationJobRequest &request)
DeleteServerCatalogResponse * deleteServerCatalog (const DeleteServerCatalogRequest &request)
DisassociateConnectorResponse * disassociateConnector (const DisassociateConnectorRequest &request)
GetConnectorsResponse * getConnectors (const GetConnectorsRequest &request)
GetReplicationJobsResponse * getReplicationJobs (const GetReplicationJobsRequest &request)
GetReplicationRunsResponse * getReplicationRuns (const GetReplicationRunsRequest &request)
GetServersResponse * getServers (const GetServersRequest &request)
ImportServerCatalogResponse * importServerCatalog (const ImportServerCatalogRequest &request)
StartOnDemandReplicationRunResponse * startOnDemandReplicationRun (const StartOnDemandReplicationRunRequest &request)
UpdateReplicationJobResponse * updateReplicationJob (const UpdateReplicationJobRequest &request)
Public Member Functions
SmsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SmsClient object.
SmsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SmsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Server Migration Service (SMS)
Definition at line 54 of file smsclient.h.
Constructor & Destructor Documentation
SmsClient() [1/2]
QtAws::SMS::SmsClient::SmsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SmsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SmsClientPrivate(this), parent)
 {
     Q_D(SmsClient);
     d->apiVersion = QStringLiteral("2016-10-24");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("sms");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Server Migration Service");
     d->serviceName = QStringLiteral("sms");
 }
SmsClient() [2/2]
QtAws::SMS::SmsClient::SmsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SmsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 101 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SmsClientPrivate(this), parent)
 {
     Q_D(SmsClient);
     d->apiVersion = QStringLiteral("2016-10-24");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("sms");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Server Migration Service");
     d->serviceName = QStringLiteral("sms");
 }
Member Function Documentation
createReplicationJob
CreateReplicationJobResponse * QtAws::SMS::SmsClient::createReplicationJob (const CreateReplicationJobRequest & request) slot
The CreateReplicationJob API is used to create a ReplicationJob to replicate a server on AWS. Call this API to first create a ReplicationJob, which will then schedule periodic ReplicationRuns to replicate your server to AWS. Each
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 128 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReplicationJobResponse *>(send(request));
 }
deleteReplicationJob
DeleteReplicationJobResponse * QtAws::SMS::SmsClient::deleteReplicationJob (const DeleteReplicationJobRequest & request) slot
The DeleteReplicationJob API is used to delete a ReplicationJob, resulting in no further ReplicationRuns. This will delete the contents of the S3 bucket used to store SMS artifacts, but will not delete any AMIs created by the SMS
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 143 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReplicationJobResponse *>(send(request));
 }
deleteServerCatalog
DeleteServerCatalogResponse * QtAws::SMS::SmsClient::deleteServerCatalog (const DeleteServerCatalogRequest & request) slot
The DeleteServerCatalog API clears all servers from your server catalog. This means that these servers will no longer be
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 157 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServerCatalogResponse *>(send(request));
 }
disassociateConnector
DisassociateConnectorResponse * QtAws::SMS::SmsClient::disassociateConnector (const DisassociateConnectorRequest & request) slot
The DisassociateConnector API will disassociate a connector from the Server Migration Service, rendering it unavailable
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 171 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateConnectorResponse *>(send(request));
 }
getConnectors
GetConnectorsResponse * QtAws::SMS::SmsClient::getConnectors (const GetConnectorsRequest & request) slot
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 184 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConnectorsResponse *>(send(request));
 }
getReplicationJobs
GetReplicationJobsResponse * QtAws::SMS::SmsClient::getReplicationJobs (const GetReplicationJobsRequest & request) slot
The GetReplicationJobs API will return all of your ReplicationJobs and their details. This API returns a paginated list,
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 198 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReplicationJobsResponse *>(send(request));
 }
getReplicationRuns
GetReplicationRunsResponse * QtAws::SMS::SmsClient::getReplicationRuns (const GetReplicationRunsRequest & request) slot
The GetReplicationRuns API will return all ReplicationRuns for a given ReplicationJob. This API returns a paginated
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 212 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReplicationRunsResponse *>(send(request));
 }
getServers
GetServersResponse * QtAws::SMS::SmsClient::getServers (const GetServersRequest & request) slot
The GetServers API returns a list of all servers in your server catalog. For this call to succeed, you must previously
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 226 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetServersResponse *>(send(request));
 }
importServerCatalog
ImportServerCatalogResponse * QtAws::SMS::SmsClient::importServerCatalog (const ImportServerCatalogRequest & request) slot
The ImportServerCatalog API is used to gather the complete list of on-premises servers on your premises. This API call requires connectors to be installed and monitoring all servers you would like imported. This API call returns
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 241 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportServerCatalogResponse *>(send(request));
 }
startOnDemandReplicationRun
StartOnDemandReplicationRunResponse * QtAws::SMS::SmsClient::startOnDemandReplicationRun (const StartOnDemandReplicationRunRequest & request) slot
The StartOnDemandReplicationRun API is used to start a ReplicationRun on demand (in addition to those that are scheduled based on your frequency). This ReplicationRun will start immediately. StartOnDemandReplicationRun is subject to limits
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 256 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartOnDemandReplicationRunResponse *>(send(request));
 }
updateReplicationJob
UpdateReplicationJobResponse * QtAws::SMS::SmsClient::updateReplicationJob (const UpdateReplicationJobRequest & request) slot
The UpdateReplicationJob API is used to change the settings of your existing ReplicationJob created using
Parameters
request Request to send to AWS Server Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 270 of file smsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateReplicationJobResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
sms/smsclient.h
sms/smsclient.cpp