AWS SDK for Qt: QtAws::DynamoDB::DynamoDBClient Class Reference
QtAws::DynamoDB::DynamoDBClient Class Reference
Client for Amazon DynamoDB.
Public Slots
BatchGetItemResponse * batchGetItem (const BatchGetItemRequest &request)
BatchWriteItemResponse * batchWriteItem (const BatchWriteItemRequest &request)
CreateBackupResponse * createBackup (const CreateBackupRequest &request)
CreateGlobalTableResponse * createGlobalTable (const CreateGlobalTableRequest &request)
CreateTableResponse * createTable (const CreateTableRequest &request)
DeleteBackupResponse * deleteBackup (const DeleteBackupRequest &request)
DeleteItemResponse * deleteItem (const DeleteItemRequest &request)
DeleteTableResponse * deleteTable (const DeleteTableRequest &request)
DescribeBackupResponse * describeBackup (const DescribeBackupRequest &request)
DescribeContinuousBackupsResponse * describeContinuousBackups (const DescribeContinuousBackupsRequest &request)
DescribeGlobalTableResponse * describeGlobalTable (const DescribeGlobalTableRequest &request)
DescribeLimitsResponse * describeLimits (const DescribeLimitsRequest &request)
DescribeTableResponse * describeTable (const DescribeTableRequest &request)
DescribeTimeToLiveResponse * describeTimeToLive (const DescribeTimeToLiveRequest &request)
GetItemResponse * getItem (const GetItemRequest &request)
ListBackupsResponse * listBackups (const ListBackupsRequest &request)
ListGlobalTablesResponse * listGlobalTables (const ListGlobalTablesRequest &request)
ListTablesResponse * listTables (const ListTablesRequest &request)
ListTagsOfResourceResponse * listTagsOfResource (const ListTagsOfResourceRequest &request)
PutItemResponse * putItem (const PutItemRequest &request)
QueryResponse * query (const QueryRequest &request)
RestoreTableFromBackupResponse * restoreTableFromBackup (const RestoreTableFromBackupRequest &request)
RestoreTableToPointInTimeResponse * restoreTableToPointInTime (const RestoreTableToPointInTimeRequest &request)
ScanResponse * scan (const ScanRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateContinuousBackupsResponse * updateContinuousBackups (const UpdateContinuousBackupsRequest &request)
UpdateGlobalTableResponse * updateGlobalTable (const UpdateGlobalTableRequest &request)
UpdateItemResponse * updateItem (const UpdateItemRequest &request)
UpdateTableResponse * updateTable (const UpdateTableRequest &request)
UpdateTimeToLiveResponse * updateTimeToLive (const UpdateTimeToLiveRequest &request)
Public Member Functions
DynamoDBClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBClient object.
DynamoDBClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon DynamoDB.
<fullname>Amazon DynamoDB</fullname>
Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster
scaling>
With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the AWS Management Console to monitor resource utilization and performance
metrics>
DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an AWS region, providing built-in high availability and data durability.
Definition at line 94 of file dynamodbclient.h.
Constructor & Destructor Documentation
DynamoDBClient() [1/2]
QtAws::DynamoDB::DynamoDBClient::DynamoDBClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 127 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DynamoDBClientPrivate(this), parent)
 {
     Q_D(DynamoDBClient);
     d->apiVersion = QStringLiteral("2012-08-10");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("dynamodb");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon DynamoDB");
     d->serviceName = QStringLiteral("dynamodb");
 }
DynamoDBClient() [2/2]
QtAws::DynamoDB::DynamoDBClient::DynamoDBClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 160 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DynamoDBClientPrivate(this), parent)
 {
     Q_D(DynamoDBClient);
     d->apiVersion = QStringLiteral("2012-08-10");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("dynamodb");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon DynamoDB");
     d->serviceName = QStringLiteral("dynamodb");
 }
Member Function Documentation
batchGetItem
BatchGetItemResponse * QtAws::DynamoDB::DynamoDBClient::batchGetItem (const BatchGetItemRequest & request) slot
The BatchGetItem operation returns the attributes of one or more items from one or more tables. You identify requested items by primary
key>
A single operation can retrieve up to 16 MB of data, which can contain as many as 100 items. BatchGetItem will return a partial result if the response size limit is exceeded, the table's provisioned throughput is exceeded, or an internal processing failure occurs. If a partial result is returned, the operation returns a value for UnprocessedKeys. You can use this value to retry the operation starting with the next item to
get>
If you request more than 100 items BatchGetItem will return a ValidationException with the message "Too many items requested for the BatchGetItem
call">
For example, if you ask to retrieve 100 items, but each individual item is 300 KB in size, the system returns 52 items (so as not to exceed the 16 MB limit). It also returns an appropriate UnprocessedKeys value so you can get the next page of results. If desired, your application can include its own logic to assemble the pages of results into one data
set>
If none of the items can be processed due to insufficient provisioned throughput on all of the tables in the request, then BatchGetItem will return a ProvisionedThroughputExceededException. If at least one of the items is successfully processed, then BatchGetItem completes successfully, while returning the keys of the unread items in
UnprocessedKeys>
If DynamoDB returns any unprocessed items, you should retry the batch operation on those items. However, we strongly recommend that you use an exponential backoff algorithm. If you retry the batch operation immediately, the underlying read or write requests can still fail due to throttling on the individual tables. If you delay the batch operation using exponential backoff, the individual requests in the batch are much more likely to
succeed>
For more information, see Batch Operations and Error Handling in the Amazon DynamoDB Developer
Guide>
By default, BatchGetItem performs eventually consistent reads on every table in the request. If you want strongly consistent reads instead, you can set ConsistentRead to true for any or all
tables>
In order to minimize response latency, BatchGetItem retrieves items in
parallel>
When designing your application, keep in mind that DynamoDB does not return items in any particular order. To help parse the response by item, include the primary key values for the items in your request in the ProjectionExpression
parameter>
If a requested item does not exist, it is not returned in the result. Requests for nonexistent items consume the minimum read capacity units according to the type of read. For more information, see Capacity Units Calculations in the Amazon DynamoDB Developer
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 248 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetItemResponse *>(send(request));
 }
batchWriteItem
BatchWriteItemResponse * QtAws::DynamoDB::DynamoDBClient::batchWriteItem (const BatchWriteItemRequest & request) slot
The BatchWriteItem operation puts or deletes multiple items in one or more tables. A single call to BatchWriteItem can write up to 16 MB of data, which can comprise as many as 25 put or delete requests. Individual items to be written can be as large as 400
KB> <note>
BatchWriteItem cannot update items. To update items, use the UpdateItem
action> </note>
The individual PutItem and DeleteItem operations specified in BatchWriteItem are atomic; however BatchWriteItem as a whole is not. If any requested operations fail because the table's provisioned throughput is exceeded or an internal processing failure occurs, the failed operations are returned in the UnprocessedItems response parameter. You can investigate and optionally resend the requests. Typically, you would call BatchWriteItem in a loop. Each iteration would check for unprocessed items and submit a new BatchWriteItem request with those unprocessed items until all items have been
processed>
Note that if none of the items can be processed due to insufficient provisioned throughput on all of the tables in the request, then BatchWriteItem will return a
ProvisionedThroughputExceededException>
If DynamoDB returns any unprocessed items, you should retry the batch operation on those items. However, we strongly recommend that you use an exponential backoff algorithm. If you retry the batch operation immediately, the underlying read or write requests can still fail due to throttling on the individual tables. If you delay the batch operation using exponential backoff, the individual requests in the batch are much more likely to
succeed>
For more information, see Batch Operations and Error Handling in the Amazon DynamoDB Developer
Guide>
With BatchWriteItem, you can efficiently write or delete large amounts of data, such as from Amazon Elastic MapReduce (EMR), or copy data from another database into DynamoDB. In order to improve performance with these large-scale operations, BatchWriteItem does not behave in the same way as individual PutItem and DeleteItem calls would. For example, you cannot specify conditions on individual put and delete requests, and BatchWriteItem does not return deleted items in the
response>
If you use a programming language that supports concurrency, you can use threads to write items in parallel. Your application must include the necessary logic to manage the threads. With languages that don't support threading, you must update or delete the specified items one at a time. In both situations, BatchWriteItem performs the specified put and delete operations in parallel, giving you the power of the thread pool approach without having to introduce complexity into your
application>
Parallel processing reduces latency, but each specified put and delete request consumes the same number of write capacity units whether it is processed in parallel or not. Delete operations on nonexistent items consume one write capacity
unit>
If one or more of the following is true, DynamoDB rejects the entire batch write
operation>
One or more tables specified in the BatchWriteItem request does not
exist>
Primary key attributes specified on an item in the request do not match those in the corresponding table's primary key
schema>
You try to perform multiple operations on the same item in the same BatchWriteItem request. For example, you cannot put and delete the same item in the same BatchWriteItem request.
</p
Your request contains at least two items with identical hash and range keys (which essentially is two put operations).
</p
There are more than 25 requests in the
batch>
Any individual item in a batch exceeds 400
KB>
The total request size exceeds 16
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 350 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchWriteItemResponse *>(send(request));
 }
createBackup
CreateBackupResponse * QtAws::DynamoDB::DynamoDBClient::createBackup (const CreateBackupRequest & request) slot
Creates a backup for an existing
table>
Each time you create an On-Demand Backup, the entire table data is backed up. There is no limit to the number of on-demand backups that can be taken.
</p
When you create an On-Demand Backup, a time marker of the request is cataloged, and the backup is created asynchronously, by applying all changes until the time of the request to the last full table snapshot. Backup requests are processed instantaneously and become available for restore within minutes.
</p
You can call CreateBackup at a maximum rate of 50 times per
second>
All backups in DynamoDB work without consuming any provisioned throughput on the
table>
If you submit a backup request on 2018-12-14 at 14:25:00, the backup is guaranteed to contain all data committed to the table up to 14:24:00, and data committed after 14:26:00 will not be. The backup may or may not contain data modifications made between 14:24:00 and 14:26:00. On-Demand Backup does not support causal consistency.
</p
Along with data, the following are also included on the backups:
</p
Global secondary indexes
(GSIs>
Local secondary indexes
(LSIs>
Stream>
Provisioned read and write
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 407 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBackupResponse *>(send(request));
 }
createGlobalTable
CreateGlobalTableResponse * QtAws::DynamoDB::DynamoDBClient::createGlobalTable (const CreateGlobalTableRequest & request) slot
Creates a global table from an existing table. A global table creates a replication relationship between two or more DynamoDB tables with the same table name in the provided regions.
</p
Tables can only be added as the replicas of a global table group under the following conditions:
</p
The tables must have the same name.
</p
The tables must contain no items.
</p
The tables must have the same hash key and sort key (if present).
</p
The tables must have DynamoDB Streams enabled (NEW_AND_OLD_IMAGES).
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 442 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGlobalTableResponse *>(send(request));
 }
createTable
CreateTableResponse * QtAws::DynamoDB::DynamoDBClient::createTable (const CreateTableRequest & request) slot
The CreateTable operation adds a new table to your account. In an AWS account, table names must be unique within each region. That is, you can have two tables with same name if you create the tables in different
regions>
CreateTable is an asynchronous operation. Upon receiving a CreateTable request, DynamoDB immediately returns a response with a TableStatus of CREATING. After the table is created, DynamoDB sets the TableStatus to ACTIVE. You can perform read and write operations only on an ACTIVE table.
</p
You can optionally define secondary indexes on the new table, as part of the CreateTable operation. If you want to create multiple tables with secondary indexes on them, you must create the tables sequentially. Only one table with secondary indexes can be in the CREATING state at any given
time>
You can use the DescribeTable action to check the table
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 474 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTableResponse *>(send(request));
 }
deleteBackup
DeleteBackupResponse * QtAws::DynamoDB::DynamoDBClient::deleteBackup (const DeleteBackupRequest & request) slot
Deletes an existing backup of a
table>
You can call DeleteBackup at a maximum rate of 10 times per
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 492 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBackupResponse *>(send(request));
 }
deleteItem
DeleteItemResponse * QtAws::DynamoDB::DynamoDBClient::deleteItem (const DeleteItemRequest & request) slot
Deletes a single item in a table by primary key. You can perform a conditional delete operation that deletes the item if it exists, or if it has an expected attribute
value>
In addition to deleting an item, you can also return the item's attribute values in the same operation, using the ReturnValues
parameter>
Unless you specify conditions, the DeleteItem is an idempotent operation; running it multiple times on the same item or attribute does not result in an error
response>
Conditional deletes are useful for deleting items only if specific conditions are met. If those conditions are met, DynamoDB performs the delete. Otherwise, the item is not
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 522 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteItemResponse *>(send(request));
 }
deleteTable
DeleteTableResponse * QtAws::DynamoDB::DynamoDBClient::deleteTable (const DeleteTableRequest & request) slot
The DeleteTable operation deletes a table and all of its items. After a DeleteTable request, the specified table is in the DELETING state until DynamoDB completes the deletion. If the table is in the ACTIVE state, you can delete it. If a table is in CREATING or UPDATING states, then DynamoDB returns a ResourceInUseException. If the specified table does not exist, DynamoDB returns a ResourceNotFoundException. If table is already in the DELETING state, no error is returned.
</p <note>
DynamoDB might continue to accept data read and write operations, such as GetItem and PutItem, on a table in the DELETING state until the table deletion is
complete> </note>
When you delete a table, any indexes on that table are also
deleted>
If you have DynamoDB Streams enabled on the table, then the corresponding stream on that table goes into the DISABLED state, and the stream is automatically deleted after 24
hours>
Use the DescribeTable action to check the status of the table.
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 558 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTableResponse *>(send(request));
 }
describeBackup
DescribeBackupResponse * QtAws::DynamoDB::DynamoDBClient::describeBackup (const DescribeBackupRequest & request) slot
Describes an existing backup of a
table>
You can call DescribeBackup at a maximum rate of 10 times per
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 576 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBackupResponse *>(send(request));
 }
describeContinuousBackups
DescribeContinuousBackupsResponse * QtAws::DynamoDB::DynamoDBClient::describeContinuousBackups (const DescribeContinuousBackupsRequest & request) slot
Checks the status of continuous backups and point in time recovery on the specified table. Continuous backups are ENABLED on all tables at table creation. If point in time recovery is enabled, PointInTimeRecoveryStatus will be set to
ENABLED>
Once continuous backups and point in time recovery are enabled, you can restore to any point in time within EarliestRestorableDateTime and LatestRestorableDateTime.
</p
LatestRestorableDateTime is typically 5 minutes before the current time. You can restore your table to any point in time during the last 35 days with a 1-minute granularity.
</p
You can call DescribeContinuousBackups at a maximum rate of 10 times per
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 606 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeContinuousBackupsResponse *>(send(request));
 }
describeGlobalTable
DescribeGlobalTableResponse * QtAws::DynamoDB::DynamoDBClient::describeGlobalTable (const DescribeGlobalTableRequest & request) slot
Returns information about the specified global
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 620 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGlobalTableResponse *>(send(request));
 }
describeLimits
DescribeLimitsResponse * QtAws::DynamoDB::DynamoDBClient::describeLimits (const DescribeLimitsRequest & request) slot
Returns the current provisioned-capacity limits for your AWS account in a region, both for the region as a whole and for any one DynamoDB table that you create
there>
When you establish an AWS account, the account has initial limits on the maximum read capacity units and write capacity units that you can provision across all of your DynamoDB tables in a given region. Also, there are per-table limits that apply when you create a table there. For more information, see Limits page in the Amazon DynamoDB Developer
Guide>
Although you can increase these limits by filing a case at AWS Support Center, obtaining the increase is not instantaneous. The DescribeLimits action lets you write code to compare the capacity you are currently using to those limits imposed by your account so that you have enough time to apply for an increase before you hit a
limit>
For example, you could use one of the AWS SDKs to do the
following>
Call DescribeLimits for a particular region to obtain your current account limits on provisioned capacity
there>
Create a variable to hold the aggregate read capacity units provisioned for all your tables in that region, and one to hold the aggregate write capacity units. Zero them
both>
Call ListTables to obtain a list of all your DynamoDB
tables>
For each table name listed by ListTables, do the
following>
Call DescribeTable with the table
name>
Use the data returned by DescribeTable to add the read capacity units and write capacity units provisioned for the table itself to your
variables>
If the table has one or more global secondary indexes (GSIs), loop over these GSIs and add their provisioned capacity values to your variables as
well>
Report the account limits for that region returned by DescribeLimits, along with the total current provisioned capacity levels you have
calculated>
This will let you see whether you are getting close to your account-level
limits>
The per-table limits apply only when you are creating a new table. They restrict the sum of the provisioned capacity of the new table itself and all its global secondary
indexes>
For existing tables and their GSIs, DynamoDB will not let you increase provisioned capacity extremely rapidly, but the only upper limit that applies is that the aggregate provisioned capacity over all your tables and GSIs cannot exceed either of the per-account
limits> <note>
DescribeLimits should only be called periodically. You can expect throttling errors if you call it more than once in a
minute> </note>
The DescribeLimits Request element has no
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 714 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLimitsResponse *>(send(request));
 }
describeTable
DescribeTableResponse * QtAws::DynamoDB::DynamoDBClient::describeTable (const DescribeTableRequest & request) slot
Returns information about the table, including the current status of the table, when it was created, the primary key schema, and any indexes on the
table> <note>
If you issue a DescribeTable request immediately after a CreateTable request, DynamoDB might return a ResourceNotFoundException. This is because DescribeTable uses an eventually consistent query, and the metadata for your table might not be available at that moment. Wait for a few seconds, and then try the DescribeTable request
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 736 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTableResponse *>(send(request));
 }
describeTimeToLive
DescribeTimeToLiveResponse * QtAws::DynamoDB::DynamoDBClient::describeTimeToLive (const DescribeTimeToLiveRequest & request) slot
Gives a description of the Time to Live (TTL) status on the specified table.
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 750 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTimeToLiveResponse *>(send(request));
 }
getItem
GetItemResponse * QtAws::DynamoDB::DynamoDBClient::getItem (const GetItemRequest & request) slot
The GetItem operation returns a set of attributes for the item with the given primary key. If there is no matching item, GetItem does not return any data and there will be no Item element in the
response>
GetItem provides an eventually consistent read by default. If your application requires a strongly consistent read, set ConsistentRead to true. Although a strongly consistent read might take more time than an eventually consistent read, it always returns the last updated
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 771 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetItemResponse *>(send(request));
 }
listBackups
ListBackupsResponse * QtAws::DynamoDB::DynamoDBClient::listBackups (const ListBackupsRequest & request) slot
List backups associated with an AWS account. To list backups for a given table, specify TableName. ListBackups returns a paginated list of results with at most 1MB worth of items in a page. You can also specify a limit for the maximum number of entries to be returned in a page.
</p
In the request, start time is inclusive but end time is exclusive. Note that these limits are for the time at which the original backup was
requested>
You can call ListBackups a maximum of 5 times per
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 796 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBackupsResponse *>(send(request));
 }
listGlobalTables
ListGlobalTablesResponse * QtAws::DynamoDB::DynamoDBClient::listGlobalTables (const ListGlobalTablesRequest & request) slot
Lists all global tables that have a replica in the specified
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 810 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGlobalTablesResponse *>(send(request));
 }
listTables
ListTablesResponse * QtAws::DynamoDB::DynamoDBClient::listTables (const ListTablesRequest & request) slot
Returns an array of table names associated with the current account and endpoint. The output from ListTables is paginated, with each page returning a maximum of 100 table
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 825 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTablesResponse *>(send(request));
 }
listTagsOfResource
ListTagsOfResourceResponse * QtAws::DynamoDB::DynamoDBClient::listTagsOfResource (const ListTagsOfResourceRequest & request) slot
List all tags on an Amazon DynamoDB resource. You can call ListTagsOfResource up to 10 times per second, per
account>
For an overview on tagging DynamoDB resources, see Tagging for DynamoDB in the Amazon DynamoDB Developer
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 845 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsOfResourceResponse *>(send(request));
 }
putItem
PutItemResponse * QtAws::DynamoDB::DynamoDBClient::putItem (const PutItemRequest & request) slot
Creates a new item, or replaces an old item with a new item. If an item that has the same primary key as the new item already exists in the specified table, the new item completely replaces the existing item. You can perform a conditional put operation (add a new item if one with the specified primary key doesn't exist), or replace an existing item if it has certain attribute values. You can return the item's attribute values in the same operation, using the ReturnValues
parameter>
This topic provides general information about the PutItem
API>
For information on how to call the PutItem API using the AWS SDK in specific languages, see the
following>
PutItem in the AWS Command Line Interface
</p
PutItem in the AWS SDK for .NET
</p
PutItem in the AWS SDK for C++
</p
PutItem in the AWS SDK for Go
</p
PutItem in the AWS SDK for Java
</p
PutItem in the AWS SDK for JavaScript
</p
PutItem in the AWS SDK for PHP V3
</p
PutItem in the AWS SDK for Python
</p
PutItem in the AWS SDK for Ruby V2
</p
When you add an item, the primary key attribute(s) are the only required attributes. Attribute values cannot be null. String and Binary type attributes must have lengths greater than zero. Set type attributes cannot be empty. Requests with empty values will be rejected with a ValidationException
exception> <note>
To prevent a new item from replacing an existing item, use a conditional expression that contains the attribute_not_exists function with the name of the attribute being used as the partition key for the table. Since every record must contain that attribute, the attribute_not_exists function will only succeed if no matching item
exists> </note>
For more information about PutItem, see Working with Items in the Amazon DynamoDB Developer
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 930 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutItemResponse *>(send(request));
 }
query
QueryResponse * QtAws::DynamoDB::DynamoDBClient::query (const QueryRequest & request) slot
The Query operation finds items based on primary key values. You can query any table or secondary index that has a composite primary key (a partition key and a sort key).
</p
Use the KeyConditionExpression parameter to provide a specific value for the partition key. The Query operation will return all of the items from the table or index with that partition key value. You can optionally narrow the scope of the Query operation by specifying a sort key value and a comparison operator in KeyConditionExpression. To further refine the Query results, you can optionally provide a FilterExpression. A FilterExpression determines which items within the results should be returned to you. All of the other results are discarded.
</p
A Query operation always returns a result set. If no matching items are found, the result set will be empty. Queries that do not return results consume the minimum number of read capacity units for that type of read operation.
</p <note>
DynamoDB calculates the number of read capacity units consumed based on item size, not on the amount of data that is returned to an application. The number of capacity units consumed will be the same whether you request all of the attributes (the default behavior) or just some of them (using a projection expression). The number will also be the same whether or not you use a FilterExpression.
</p </note>
Query results are always sorted by the sort key value. If the data type of the sort key is Number, the results are returned in numeric order; otherwise, the results are returned in order of UTF-8 bytes. By default, the sort order is ascending. To reverse the order, set the ScanIndexForward parameter to false.
</p
A single Query operation will read up to the maximum number of items set (if using the Limit parameter) or a maximum of 1 MB of data and then apply any filtering to the results using FilterExpression. If LastEvaluatedKey is present in the response, you will need to paginate the result set. For more information, see Paginating the Results in the Amazon DynamoDB Developer Guide.
</p
FilterExpression is applied after a Query finishes, but before the results are returned. A FilterExpression cannot contain partition key or sort key attributes. You need to specify those attributes in the KeyConditionExpression.
</p <note>
A Query operation can return an empty result set and a LastEvaluatedKey if all the items read for the page of results are filtered out.
</p </note>
You can query a table, a local secondary index, or a global secondary index. For a query on a table or on a local secondary index, you can set the ConsistentRead parameter to true and obtain a strongly consistent result. Global secondary indexes support eventually consistent reads only, so do not specify ConsistentRead when querying a global secondary
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1000 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<QueryResponse *>(send(request));
 }
restoreTableFromBackup
RestoreTableFromBackupResponse * QtAws::DynamoDB::DynamoDBClient::restoreTableFromBackup (const RestoreTableFromBackupRequest & request) slot
Creates a new table from an existing backup. Any number of users can execute up to 4 concurrent restores (any type of restore) in a given account.
</p
You can call RestoreTableFromBackup at a maximum rate of 10 times per
second>
You must manually set up the following on the restored
table>
Auto scaling
policie>
IAM
policie>
Cloudwatch metrics and
alarm>
Tag>
Stream
setting>
Time to Live (TTL)
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1045 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreTableFromBackupResponse *>(send(request));
 }
restoreTableToPointInTime
RestoreTableToPointInTimeResponse * QtAws::DynamoDB::DynamoDBClient::restoreTableToPointInTime (const RestoreTableToPointInTimeRequest & request) slot
Restores the specified table to the specified point in time within EarliestRestorableDateTime and LatestRestorableDateTime. You can restore your table to any point in time during the last 35 days with a 1-minute granularity. Any number of users can execute up to 4 concurrent restores (any type of restore) in a given account.
Auto scaling
policie>
IAM
policie>
Cloudwatch metrics and
alarm>
Tag>
Stream
setting>
Time to Live (TTL)
setting>
Point in time recovery
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1092 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreTableToPointInTimeResponse *>(send(request));
 }
scan
ScanResponse * QtAws::DynamoDB::DynamoDBClient::scan (const ScanRequest & request) slot
The Scan operation returns one or more items and item attributes by accessing every item in a table or a secondary index. To have DynamoDB return fewer items, you can provide a FilterExpression
operation>
If the total number of scanned items exceeds the maximum data set size limit of 1 MB, the scan stops and results are returned to the user as a LastEvaluatedKey value to continue the scan in a subsequent operation. The results also include the number of items exceeding the limit. A scan can result in no table data meeting the filter criteria.
</p
A single Scan operation will read up to the maximum number of items set (if using the Limit parameter) or a maximum of 1 MB of data and then apply any filtering to the results using FilterExpression. If LastEvaluatedKey is present in the response, you will need to paginate the result set. For more information, see Paginating the Results in the Amazon DynamoDB Developer Guide.
</p
Scan operations proceed sequentially; however, for faster performance on a large table or secondary index, applications can request a parallel Scan operation by providing the Segment and TotalSegments parameters. For more information, see Parallel Scan in the Amazon DynamoDB Developer
Guide>
Scan uses eventually consistent reads when accessing the data in a table; therefore, the result set might not include the changes to data in the table immediately before the operation began. If you need a consistent copy of the data, as of the time that the Scan begins, you can set the ConsistentRead parameter to
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1137 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ScanResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::DynamoDB::DynamoDBClient::tagResource (const TagResourceRequest & request) slot
Associate a set of tags with an Amazon DynamoDB resource. You can then activate these user-defined tags so that they appear on the Billing and Cost Management console for cost allocation tracking. You can call TagResource up to 5 times per second, per account.
</p
For an overview on tagging DynamoDB resources, see Tagging for DynamoDB in the Amazon DynamoDB Developer
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1159 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::DynamoDB::DynamoDBClient::untagResource (const UntagResourceRequest & request) slot
Removes the association of tags from an Amazon DynamoDB resource. You can call UntagResource up to 5 times per second, per account.
</p
For an overview on tagging DynamoDB resources, see Tagging for DynamoDB in the Amazon DynamoDB Developer
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1180 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateContinuousBackups
UpdateContinuousBackupsResponse * QtAws::DynamoDB::DynamoDBClient::updateContinuousBackups (const UpdateContinuousBackupsRequest & request) slot
UpdateContinuousBackups enables or disables point in time recovery for the specified table. A successful UpdateContinuousBackups call returns the current ContinuousBackupsDescription. Continuous backups are ENABLED on all tables at table creation. If point in time recovery is enabled, PointInTimeRecoveryStatus will be set to
ENABLED>
Once continuous backups and point in time recovery are enabled, you can restore to any point in time within EarliestRestorableDateTime and LatestRestorableDateTime.
</p
LatestRestorableDateTime is typically 5 minutes before the current time. You can restore your table to any point in time during the last 35 days with a 1-minute granularity.
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1207 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateContinuousBackupsResponse *>(send(request));
 }
updateGlobalTable
UpdateGlobalTableResponse * QtAws::DynamoDB::DynamoDBClient::updateGlobalTable (const UpdateGlobalTableRequest & request) slot
Adds or removes replicas in the specified global table. The global table must already exist to be able to use this operation. Any replica to be added must be empty, must have the same name as the global table, must have the same key schema, and must have DynamoDB Streams
enabled> <note>
Although you can use UpdateGlobalTable to add replicas and remove replicas in a single request, for simplicity we recommend that you issue separate requests for adding or removing
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1228 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGlobalTableResponse *>(send(request));
 }
updateItem
UpdateItemResponse * QtAws::DynamoDB::DynamoDBClient::updateItem (const UpdateItemRequest & request) slot
Edits an existing item's attributes, or adds a new item to the table if it does not already exist. You can put, delete, or add attribute values. You can also perform a conditional update on an existing item (insert a new attribute name-value pair if it doesn't exist, or replace an existing name-value pair if it has certain expected attribute
values)>
You can also return the item's attribute values in the same UpdateItem operation using the ReturnValues
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1249 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateItemResponse *>(send(request));
 }
updateTable
UpdateTableResponse * QtAws::DynamoDB::DynamoDBClient::updateTable (const UpdateTableRequest & request) slot
Modifies the provisioned throughput settings, global secondary indexes, or DynamoDB Streams settings for a given
table>
You can only perform one of the following operations at
once>
Modify the provisioned throughput settings of the
table>
Enable or disable Streams on the
table>
Remove a global secondary index from the
table>
Create a new global secondary index on the table. Once the index begins backfilling, you can use UpdateTable to perform other
operations>
UpdateTable is an asynchronous operation; while it is executing, the table status changes from ACTIVE to UPDATING. While it is UPDATING, you cannot issue another UpdateTable request. When the table returns to the ACTIVE state, the UpdateTable operation is
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1291 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTableResponse *>(send(request));
 }
updateTimeToLive
UpdateTimeToLiveResponse * QtAws::DynamoDB::DynamoDBClient::updateTimeToLive (const UpdateTimeToLiveRequest & request) slot
The UpdateTimeToLive method will enable or disable TTL for the specified table. A successful UpdateTimeToLive call returns the current TimeToLiveSpecification; it may take up to one hour for the change to fully process. Any additional UpdateTimeToLive calls for the same table during this one hour duration result in a ValidationException.
</p
TTL compares the current time in epoch time format to the time stored in the TTL attribute of an item. If the epoch time value stored in the attribute is less than the current time, the item is marked as expired and subsequently
deleted> <note>
The epoch time format is the number of seconds elapsed since 12:00:00 AM January 1st, 1970 UTC.
</p </note>
DynamoDB deletes expired items on a best-effort basis to ensure availability of throughput for other data operations.
</p
DynamoDB typically deletes expired items within two days of expiration. The exact duration within which an item gets deleted after expiration is specific to the nature of the workload. Items that have expired and not been deleted will still show up in reads, queries, and
scans>
As items are deleted, they are removed from any Local Secondary Index and Global Secondary Index immediately in the same eventually consistent way as a standard delete
operation>
For more information, see Time To Live in the Amazon DynamoDB Developer Guide.
Parameters
request Request to send to Amazon DynamoDB.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1337 of file dynamodbclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTimeToLiveResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
dynamodb/dynamodbclient.h
dynamodb/dynamodbclient.cpp