AWS SDK for Qt: QtAws::Glue::GlueClient Class Reference
QtAws::Glue::GlueClient Class Reference
Client for AWS Glue.
Public Slots
BatchCreatePartitionResponse * batchCreatePartition (const BatchCreatePartitionRequest &request)
BatchDeleteConnectionResponse * batchDeleteConnection (const BatchDeleteConnectionRequest &request)
BatchDeletePartitionResponse * batchDeletePartition (const BatchDeletePartitionRequest &request)
BatchDeleteTableResponse * batchDeleteTable (const BatchDeleteTableRequest &request)
BatchDeleteTableVersionResponse * batchDeleteTableVersion (const BatchDeleteTableVersionRequest &request)
BatchGetPartitionResponse * batchGetPartition (const BatchGetPartitionRequest &request)
BatchStopJobRunResponse * batchStopJobRun (const BatchStopJobRunRequest &request)
CreateClassifierResponse * createClassifier (const CreateClassifierRequest &request)
CreateConnectionResponse * createConnection (const CreateConnectionRequest &request)
CreateCrawlerResponse * createCrawler (const CreateCrawlerRequest &request)
CreateDatabaseResponse * createDatabase (const CreateDatabaseRequest &request)
CreateDevEndpointResponse * createDevEndpoint (const CreateDevEndpointRequest &request)
CreateJobResponse * createJob (const CreateJobRequest &request)
CreatePartitionResponse * createPartition (const CreatePartitionRequest &request)
CreateScriptResponse * createScript (const CreateScriptRequest &request)
CreateTableResponse * createTable (const CreateTableRequest &request)
CreateTriggerResponse * createTrigger (const CreateTriggerRequest &request)
CreateUserDefinedFunctionResponse * createUserDefinedFunction (const CreateUserDefinedFunctionRequest &request)
DeleteClassifierResponse * deleteClassifier (const DeleteClassifierRequest &request)
DeleteConnectionResponse * deleteConnection (const DeleteConnectionRequest &request)
DeleteCrawlerResponse * deleteCrawler (const DeleteCrawlerRequest &request)
DeleteDatabaseResponse * deleteDatabase (const DeleteDatabaseRequest &request)
DeleteDevEndpointResponse * deleteDevEndpoint (const DeleteDevEndpointRequest &request)
DeleteJobResponse * deleteJob (const DeleteJobRequest &request)
DeletePartitionResponse * deletePartition (const DeletePartitionRequest &request)
DeleteTableResponse * deleteTable (const DeleteTableRequest &request)
DeleteTableVersionResponse * deleteTableVersion (const DeleteTableVersionRequest &request)
DeleteTriggerResponse * deleteTrigger (const DeleteTriggerRequest &request)
DeleteUserDefinedFunctionResponse * deleteUserDefinedFunction (const DeleteUserDefinedFunctionRequest &request)
GetCatalogImportStatusResponse * getCatalogImportStatus (const GetCatalogImportStatusRequest &request)
GetClassifierResponse * getClassifier (const GetClassifierRequest &request)
GetClassifiersResponse * getClassifiers (const GetClassifiersRequest &request)
GetConnectionResponse * getConnection (const GetConnectionRequest &request)
GetConnectionsResponse * getConnections (const GetConnectionsRequest &request)
GetCrawlerResponse * getCrawler (const GetCrawlerRequest &request)
GetCrawlerMetricsResponse * getCrawlerMetrics (const GetCrawlerMetricsRequest &request)
GetCrawlersResponse * getCrawlers (const GetCrawlersRequest &request)
GetDatabaseResponse * getDatabase (const GetDatabaseRequest &request)
GetDatabasesResponse * getDatabases (const GetDatabasesRequest &request)
GetDataflowGraphResponse * getDataflowGraph (const GetDataflowGraphRequest &request)
GetDevEndpointResponse * getDevEndpoint (const GetDevEndpointRequest &request)
GetDevEndpointsResponse * getDevEndpoints (const GetDevEndpointsRequest &request)
GetJobResponse * getJob (const GetJobRequest &request)
GetJobRunResponse * getJobRun (const GetJobRunRequest &request)
GetJobRunsResponse * getJobRuns (const GetJobRunsRequest &request)
GetJobsResponse * getJobs (const GetJobsRequest &request)
GetMappingResponse * getMapping (const GetMappingRequest &request)
GetPartitionResponse * getPartition (const GetPartitionRequest &request)
GetPartitionsResponse * getPartitions (const GetPartitionsRequest &request)
GetPlanResponse * getPlan (const GetPlanRequest &request)
GetTableResponse * getTable (const GetTableRequest &request)
GetTableVersionResponse * getTableVersion (const GetTableVersionRequest &request)
GetTableVersionsResponse * getTableVersions (const GetTableVersionsRequest &request)
GetTablesResponse * getTables (const GetTablesRequest &request)
GetTriggerResponse * getTrigger (const GetTriggerRequest &request)
GetTriggersResponse * getTriggers (const GetTriggersRequest &request)
GetUserDefinedFunctionResponse * getUserDefinedFunction (const GetUserDefinedFunctionRequest &request)
GetUserDefinedFunctionsResponse * getUserDefinedFunctions (const GetUserDefinedFunctionsRequest &request)
ImportCatalogToGlueResponse * importCatalogToGlue (const ImportCatalogToGlueRequest &request)
ResetJobBookmarkResponse * resetJobBookmark (const ResetJobBookmarkRequest &request)
StartCrawlerResponse * startCrawler (const StartCrawlerRequest &request)
StartCrawlerScheduleResponse * startCrawlerSchedule (const StartCrawlerScheduleRequest &request)
StartJobRunResponse * startJobRun (const StartJobRunRequest &request)
StartTriggerResponse * startTrigger (const StartTriggerRequest &request)
StopCrawlerResponse * stopCrawler (const StopCrawlerRequest &request)
StopCrawlerScheduleResponse * stopCrawlerSchedule (const StopCrawlerScheduleRequest &request)
StopTriggerResponse * stopTrigger (const StopTriggerRequest &request)
UpdateClassifierResponse * updateClassifier (const UpdateClassifierRequest &request)
UpdateConnectionResponse * updateConnection (const UpdateConnectionRequest &request)
UpdateCrawlerResponse * updateCrawler (const UpdateCrawlerRequest &request)
UpdateCrawlerScheduleResponse * updateCrawlerSchedule (const UpdateCrawlerScheduleRequest &request)
UpdateDatabaseResponse * updateDatabase (const UpdateDatabaseRequest &request)
UpdateDevEndpointResponse * updateDevEndpoint (const UpdateDevEndpointRequest &request)
UpdateJobResponse * updateJob (const UpdateJobRequest &request)
UpdatePartitionResponse * updatePartition (const UpdatePartitionRequest &request)
UpdateTableResponse * updateTable (const UpdateTableRequest &request)
UpdateTriggerResponse * updateTrigger (const UpdateTriggerRequest &request)
UpdateUserDefinedFunctionResponse * updateUserDefinedFunction (const UpdateUserDefinedFunctionRequest &request)
Public Member Functions
GlueClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlueClient object.
GlueClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlueClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Glue.
<fullname>AWS Glue</fullname>
Defines the public endpoint for the AWS Glue
Definition at line 188 of file glueclient.h.
Constructor & Destructor Documentation
GlueClient() [1/2]
QtAws::Glue::GlueClient::GlueClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlueClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 205 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new GlueClientPrivate(this), parent)
 {
     Q_D(GlueClient);
     d->apiVersion = QStringLiteral("2017-03-31");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("glue");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Glue");
     d->serviceName = QStringLiteral("glue");
 }
GlueClient() [2/2]
QtAws::Glue::GlueClient::GlueClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlueClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 238 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new GlueClientPrivate(this), parent)
 {
     Q_D(GlueClient);
     d->apiVersion = QStringLiteral("2017-03-31");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("glue");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Glue");
     d->serviceName = QStringLiteral("glue");
 }
Member Function Documentation
batchCreatePartition
BatchCreatePartitionResponse * QtAws::Glue::GlueClient::batchCreatePartition (const BatchCreatePartitionRequest & request) slot
Creates one or more partitions in a batch
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 264 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchCreatePartitionResponse *>(send(request));
 }
batchDeleteConnection
BatchDeleteConnectionResponse * QtAws::Glue::GlueClient::batchDeleteConnection (const BatchDeleteConnectionRequest & request) slot
Deletes a list of connection definitions from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDeleteConnectionResponse *>(send(request));
 }
batchDeletePartition
BatchDeletePartitionResponse * QtAws::Glue::GlueClient::batchDeletePartition (const BatchDeletePartitionRequest & request) slot
Deletes one or more partitions in a batch
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDeletePartitionResponse *>(send(request));
 }
batchDeleteTable
BatchDeleteTableResponse * QtAws::Glue::GlueClient::batchDeleteTable (const BatchDeleteTableRequest & request) slot
Deletes multiple tables at
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDeleteTableResponse *>(send(request));
 }
batchDeleteTableVersion
BatchDeleteTableVersionResponse * QtAws::Glue::GlueClient::batchDeleteTableVersion (const BatchDeleteTableVersionRequest & request) slot
Deletes a specified batch of versions of a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 320 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDeleteTableVersionResponse *>(send(request));
 }
batchGetPartition
BatchGetPartitionResponse * QtAws::Glue::GlueClient::batchGetPartition (const BatchGetPartitionRequest & request) slot
Retrieves partitions in a batch
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetPartitionResponse *>(send(request));
 }
batchStopJobRun
BatchStopJobRunResponse * QtAws::Glue::GlueClient::batchStopJobRun (const BatchStopJobRunRequest & request) slot
Stops one or more job runs for a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 348 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchStopJobRunResponse *>(send(request));
 }
createClassifier
CreateClassifierResponse * QtAws::Glue::GlueClient::createClassifier (const CreateClassifierRequest & request) slot
Creates a classifier in the user's account. This may be a GrokClassifier, an XMLClassifier, or abbrev JsonClassifier, depending on which field of the request is
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 363 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateClassifierResponse *>(send(request));
 }
createConnection
CreateConnectionResponse * QtAws::Glue::GlueClient::createConnection (const CreateConnectionRequest & request) slot
Creates a connection definition in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConnectionResponse *>(send(request));
 }
createCrawler
CreateCrawlerResponse * QtAws::Glue::GlueClient::createCrawler (const CreateCrawlerRequest & request) slot
Creates a new crawler with specified targets, role, configuration, and optional schedule. At least one crawl target must be specified, in either the s3Targets or the jdbcTargets
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 392 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCrawlerResponse *>(send(request));
 }
createDatabase
CreateDatabaseResponse * QtAws::Glue::GlueClient::createDatabase (const CreateDatabaseRequest & request) slot
Creates a new database in a Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDatabaseResponse *>(send(request));
 }
createDevEndpoint
CreateDevEndpointResponse * QtAws::Glue::GlueClient::createDevEndpoint (const CreateDevEndpointRequest & request) slot
Creates a new
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDevEndpointResponse *>(send(request));
 }
createJob
CreateJobResponse * QtAws::Glue::GlueClient::createJob (const CreateJobRequest & request) slot
Creates a new
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 434 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateJobResponse *>(send(request));
 }
createPartition
CreatePartitionResponse * QtAws::Glue::GlueClient::createPartition (const CreatePartitionRequest & request) slot
Creates a new
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 448 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePartitionResponse *>(send(request));
 }
createScript
CreateScriptResponse * QtAws::Glue::GlueClient::createScript (const CreateScriptRequest & request) slot
Transforms a directed acyclic graph (DAG) into
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 462 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateScriptResponse *>(send(request));
 }
createTable
CreateTableResponse * QtAws::Glue::GlueClient::createTable (const CreateTableRequest & request) slot
Creates a new table definition in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 476 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTableResponse *>(send(request));
 }
createTrigger
CreateTriggerResponse * QtAws::Glue::GlueClient::createTrigger (const CreateTriggerRequest & request) slot
Creates a new
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 490 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTriggerResponse *>(send(request));
 }
createUserDefinedFunction
CreateUserDefinedFunctionResponse * QtAws::Glue::GlueClient::createUserDefinedFunction (const CreateUserDefinedFunctionRequest & request) slot
Creates a new function definition in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 504 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserDefinedFunctionResponse *>(send(request));
 }
deleteClassifier
DeleteClassifierResponse * QtAws::Glue::GlueClient::deleteClassifier (const DeleteClassifierRequest & request) slot
Removes a classifier from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 518 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteClassifierResponse *>(send(request));
 }
deleteConnection
DeleteConnectionResponse * QtAws::Glue::GlueClient::deleteConnection (const DeleteConnectionRequest & request) slot
Deletes a connection from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 532 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConnectionResponse *>(send(request));
 }
deleteCrawler
DeleteCrawlerResponse * QtAws::Glue::GlueClient::deleteCrawler (const DeleteCrawlerRequest & request) slot
Removes a specified crawler from the Data Catalog, unless the crawler state is
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 546 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCrawlerResponse *>(send(request));
 }
deleteDatabase
DeleteDatabaseResponse * QtAws::Glue::GlueClient::deleteDatabase (const DeleteDatabaseRequest & request) slot
Removes a specified Database from a Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 560 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDatabaseResponse *>(send(request));
 }
deleteDevEndpoint
DeleteDevEndpointResponse * QtAws::Glue::GlueClient::deleteDevEndpoint (const DeleteDevEndpointRequest & request) slot
Deletes a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 574 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDevEndpointResponse *>(send(request));
 }
deleteJob
DeleteJobResponse * QtAws::Glue::GlueClient::deleteJob (const DeleteJobRequest & request) slot
Deletes a specified job. If the job is not found, no exception is
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 588 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteJobResponse *>(send(request));
 }
deletePartition
DeletePartitionResponse * QtAws::Glue::GlueClient::deletePartition (const DeletePartitionRequest & request) slot
Deletes a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 602 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePartitionResponse *>(send(request));
 }
deleteTable
DeleteTableResponse * QtAws::Glue::GlueClient::deleteTable (const DeleteTableRequest & request) slot
Removes a table definition from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 616 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTableResponse *>(send(request));
 }
deleteTableVersion
DeleteTableVersionResponse * QtAws::Glue::GlueClient::deleteTableVersion (const DeleteTableVersionRequest & request) slot
Deletes a specified version of a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 630 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTableVersionResponse *>(send(request));
 }
deleteTrigger
DeleteTriggerResponse * QtAws::Glue::GlueClient::deleteTrigger (const DeleteTriggerRequest & request) slot
Deletes a specified trigger. If the trigger is not found, no exception is
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 644 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTriggerResponse *>(send(request));
 }
deleteUserDefinedFunction
DeleteUserDefinedFunctionResponse * QtAws::Glue::GlueClient::deleteUserDefinedFunction (const DeleteUserDefinedFunctionRequest & request) slot
Deletes an existing function definition from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 658 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserDefinedFunctionResponse *>(send(request));
 }
getCatalogImportStatus
GetCatalogImportStatusResponse * QtAws::Glue::GlueClient::getCatalogImportStatus (const GetCatalogImportStatusRequest & request) slot
Retrieves the status of a migration
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 672 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCatalogImportStatusResponse *>(send(request));
 }
getClassifier
GetClassifierResponse * QtAws::Glue::GlueClient::getClassifier (const GetClassifierRequest & request) slot
Retrieve a classifier by
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 686 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetClassifierResponse *>(send(request));
 }
getClassifiers
GetClassifiersResponse * QtAws::Glue::GlueClient::getClassifiers (const GetClassifiersRequest & request) slot
Lists all classifier objects in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 700 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetClassifiersResponse *>(send(request));
 }
getConnection
GetConnectionResponse * QtAws::Glue::GlueClient::getConnection (const GetConnectionRequest & request) slot
Retrieves a connection definition from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 714 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConnectionResponse *>(send(request));
 }
getConnections
GetConnectionsResponse * QtAws::Glue::GlueClient::getConnections (const GetConnectionsRequest & request) slot
Retrieves a list of connection definitions from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 728 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConnectionsResponse *>(send(request));
 }
getCrawler
GetCrawlerResponse * QtAws::Glue::GlueClient::getCrawler (const GetCrawlerRequest & request) slot
Retrieves metadata for a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 742 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCrawlerResponse *>(send(request));
 }
getCrawlerMetrics
GetCrawlerMetricsResponse * QtAws::Glue::GlueClient::getCrawlerMetrics (const GetCrawlerMetricsRequest & request) slot
Retrieves metrics about specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 756 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCrawlerMetricsResponse *>(send(request));
 }
getCrawlers
GetCrawlersResponse * QtAws::Glue::GlueClient::getCrawlers (const GetCrawlersRequest & request) slot
Retrieves metadata for all crawlers defined in the customer
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 770 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCrawlersResponse *>(send(request));
 }
getDatabase
GetDatabaseResponse * QtAws::Glue::GlueClient::getDatabase (const GetDatabaseRequest & request) slot
Retrieves the definition of a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 784 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDatabaseResponse *>(send(request));
 }
getDatabases
GetDatabasesResponse * QtAws::Glue::GlueClient::getDatabases (const GetDatabasesRequest & request) slot
Retrieves all Databases defined in a given Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 798 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDatabasesResponse *>(send(request));
 }
getDataflowGraph
GetDataflowGraphResponse * QtAws::Glue::GlueClient::getDataflowGraph (const GetDataflowGraphRequest & request) slot
Transforms a Python script into a directed acyclic graph (DAG).
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 812 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDataflowGraphResponse *>(send(request));
 }
getDevEndpoint
GetDevEndpointResponse * QtAws::Glue::GlueClient::getDevEndpoint (const GetDevEndpointRequest & request) slot
Retrieves information about a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 826 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDevEndpointResponse *>(send(request));
 }
getDevEndpoints
GetDevEndpointsResponse * QtAws::Glue::GlueClient::getDevEndpoints (const GetDevEndpointsRequest & request) slot
Retrieves all the DevEndpoints in this AWS
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 840 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDevEndpointsResponse *>(send(request));
 }
getJob
GetJobResponse * QtAws::Glue::GlueClient::getJob (const GetJobRequest & request) slot
Retrieves an existing job
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 854 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobResponse *>(send(request));
 }
getJobRun
GetJobRunResponse * QtAws::Glue::GlueClient::getJobRun (const GetJobRunRequest & request) slot
Retrieves the metadata for a given job
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 868 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobRunResponse *>(send(request));
 }
getJobRuns
GetJobRunsResponse * QtAws::Glue::GlueClient::getJobRuns (const GetJobRunsRequest & request) slot
Retrieves metadata for all runs of a given
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 882 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobRunsResponse *>(send(request));
 }
getJobs
GetJobsResponse * QtAws::Glue::GlueClient::getJobs (const GetJobsRequest & request) slot
Retrieves all current
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 896 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobsResponse *>(send(request));
 }
getMapping
GetMappingResponse * QtAws::Glue::GlueClient::getMapping (const GetMappingRequest & request) slot
Creates
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 910 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetMappingResponse *>(send(request));
 }
getPartition
GetPartitionResponse * QtAws::Glue::GlueClient::getPartition (const GetPartitionRequest & request) slot
Retrieves information about a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 924 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPartitionResponse *>(send(request));
 }
getPartitions
GetPartitionsResponse * QtAws::Glue::GlueClient::getPartitions (const GetPartitionsRequest & request) slot
Retrieves information about the partitions in a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 938 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPartitionsResponse *>(send(request));
 }
getPlan
GetPlanResponse * QtAws::Glue::GlueClient::getPlan (const GetPlanRequest & request) slot
Gets code to perform a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 952 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPlanResponse *>(send(request));
 }
getTable
GetTableResponse * QtAws::Glue::GlueClient::getTable (const GetTableRequest & request) slot
Retrieves the Table definition in a Data Catalog for a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 966 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTableResponse *>(send(request));
 }
getTables
GetTablesResponse * QtAws::Glue::GlueClient::getTables (const GetTablesRequest & request) slot
Retrieves the definitions of some or all of the tables in a given
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1008 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTablesResponse *>(send(request));
 }
getTableVersion
GetTableVersionResponse * QtAws::Glue::GlueClient::getTableVersion (const GetTableVersionRequest & request) slot
Retrieves a specified version of a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 980 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTableVersionResponse *>(send(request));
 }
getTableVersions
GetTableVersionsResponse * QtAws::Glue::GlueClient::getTableVersions (const GetTableVersionsRequest & request) slot
Retrieves a list of strings that identify available versions of a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 994 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTableVersionsResponse *>(send(request));
 }
getTrigger
GetTriggerResponse * QtAws::Glue::GlueClient::getTrigger (const GetTriggerRequest & request) slot
Retrieves the definition of a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1022 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTriggerResponse *>(send(request));
 }
getTriggers
GetTriggersResponse * QtAws::Glue::GlueClient::getTriggers (const GetTriggersRequest & request) slot
Gets all the triggers associated with a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1036 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTriggersResponse *>(send(request));
 }
getUserDefinedFunction
GetUserDefinedFunctionResponse * QtAws::Glue::GlueClient::getUserDefinedFunction (const GetUserDefinedFunctionRequest & request) slot
Retrieves a specified function definition from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1050 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserDefinedFunctionResponse *>(send(request));
 }
getUserDefinedFunctions
GetUserDefinedFunctionsResponse * QtAws::Glue::GlueClient::getUserDefinedFunctions (const GetUserDefinedFunctionsRequest & request) slot
Retrieves a multiple function definitions from the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1064 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserDefinedFunctionsResponse *>(send(request));
 }
importCatalogToGlue
ImportCatalogToGlueResponse * QtAws::Glue::GlueClient::importCatalogToGlue (const ImportCatalogToGlueRequest & request) slot
Imports an existing Athena Data Catalog to AWS
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1078 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportCatalogToGlueResponse *>(send(request));
 }
resetJobBookmark
ResetJobBookmarkResponse * QtAws::Glue::GlueClient::resetJobBookmark (const ResetJobBookmarkRequest & request) slot
Resets a bookmark
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1092 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetJobBookmarkResponse *>(send(request));
 }
startCrawler
StartCrawlerResponse * QtAws::Glue::GlueClient::startCrawler (const StartCrawlerRequest & request) slot
Starts a crawl using the specified crawler, regardless of what is scheduled. If the crawler is already running, does
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1106 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartCrawlerResponse *>(send(request));
 }
startCrawlerSchedule
StartCrawlerScheduleResponse * QtAws::Glue::GlueClient::startCrawlerSchedule (const StartCrawlerScheduleRequest & request) slot
Changes the schedule state of the specified crawler to SCHEDULED, unless the crawler is already running or the schedule state is already
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1121 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartCrawlerScheduleResponse *>(send(request));
 }
startJobRun
StartJobRunResponse * QtAws::Glue::GlueClient::startJobRun (const StartJobRunRequest & request) slot
Runs a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1135 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartJobRunResponse *>(send(request));
 }
startTrigger
StartTriggerResponse * QtAws::Glue::GlueClient::startTrigger (const StartTriggerRequest & request) slot
Starts an existing trigger. See Triggering Jobs for information about how different types of trigger are
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1150 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartTriggerResponse *>(send(request));
 }
stopCrawler
StopCrawlerResponse * QtAws::Glue::GlueClient::stopCrawler (const StopCrawlerRequest & request) slot
If the specified crawler is running, stops the
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1164 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopCrawlerResponse *>(send(request));
 }
stopCrawlerSchedule
StopCrawlerScheduleResponse * QtAws::Glue::GlueClient::stopCrawlerSchedule (const StopCrawlerScheduleRequest & request) slot
Sets the schedule state of the specified crawler to NOT_SCHEDULED, but does not stop the crawler if it is already
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1179 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopCrawlerScheduleResponse *>(send(request));
 }
stopTrigger
StopTriggerResponse * QtAws::Glue::GlueClient::stopTrigger (const StopTriggerRequest & request) slot
Stops a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1193 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopTriggerResponse *>(send(request));
 }
updateClassifier
UpdateClassifierResponse * QtAws::Glue::GlueClient::updateClassifier (const UpdateClassifierRequest & request) slot
Modifies an existing classifier (a GrokClassifier, XMLClassifier, or JsonClassifier, depending on which field is
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1208 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateClassifierResponse *>(send(request));
 }
updateConnection
UpdateConnectionResponse * QtAws::Glue::GlueClient::updateConnection (const UpdateConnectionRequest & request) slot
Updates a connection definition in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1222 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConnectionResponse *>(send(request));
 }
updateCrawler
UpdateCrawlerResponse * QtAws::Glue::GlueClient::updateCrawler (const UpdateCrawlerRequest & request) slot
Updates a crawler. If a crawler is running, you must stop it using StopCrawler before updating
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1236 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCrawlerResponse *>(send(request));
 }
updateCrawlerSchedule
UpdateCrawlerScheduleResponse * QtAws::Glue::GlueClient::updateCrawlerSchedule (const UpdateCrawlerScheduleRequest & request) slot
Updates the schedule of a crawler using a cron expression.
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1250 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCrawlerScheduleResponse *>(send(request));
 }
updateDatabase
UpdateDatabaseResponse * QtAws::Glue::GlueClient::updateDatabase (const UpdateDatabaseRequest & request) slot
Updates an existing database definition in a Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1264 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDatabaseResponse *>(send(request));
 }
updateDevEndpoint
UpdateDevEndpointResponse * QtAws::Glue::GlueClient::updateDevEndpoint (const UpdateDevEndpointRequest & request) slot
Updates a specified
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1278 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDevEndpointResponse *>(send(request));
 }
updateJob
UpdateJobResponse * QtAws::Glue::GlueClient::updateJob (const UpdateJobRequest & request) slot
Updates an existing job
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1292 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateJobResponse *>(send(request));
 }
updatePartition
UpdatePartitionResponse * QtAws::Glue::GlueClient::updatePartition (const UpdatePartitionRequest & request) slot
Updates a
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1306 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdatePartitionResponse *>(send(request));
 }
updateTable
UpdateTableResponse * QtAws::Glue::GlueClient::updateTable (const UpdateTableRequest & request) slot
Updates a metadata table in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1320 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTableResponse *>(send(request));
 }
updateTrigger
UpdateTriggerResponse * QtAws::Glue::GlueClient::updateTrigger (const UpdateTriggerRequest & request) slot
Updates a trigger
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1334 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTriggerResponse *>(send(request));
 }
updateUserDefinedFunction
UpdateUserDefinedFunctionResponse * QtAws::Glue::GlueClient::updateUserDefinedFunction (const UpdateUserDefinedFunctionRequest & request) slot
Updates an existing function definition in the Data
Parameters
request Request to send to AWS Glue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1348 of file glueclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserDefinedFunctionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
glue/glueclient.h
glue/glueclient.cpp