AWS SDK for Qt: QtAws::GameLift::GameLiftClient Class Reference
QtAws::GameLift::GameLiftClient Class Reference
Client for Amazon GameLift.
Public Slots
AcceptMatchResponse * acceptMatch (const AcceptMatchRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateBuildResponse * createBuild (const CreateBuildRequest &request)
CreateFleetResponse * createFleet (const CreateFleetRequest &request)
CreateGameSessionResponse * createGameSession (const CreateGameSessionRequest &request)
CreateGameSessionQueueResponse * createGameSessionQueue (const CreateGameSessionQueueRequest &request)
CreateMatchmakingConfigurationResponse * createMatchmakingConfiguration (const CreateMatchmakingConfigurationRequest &request)
CreateMatchmakingRuleSetResponse * createMatchmakingRuleSet (const CreateMatchmakingRuleSetRequest &request)
CreatePlayerSessionResponse * createPlayerSession (const CreatePlayerSessionRequest &request)
CreatePlayerSessionsResponse * createPlayerSessions (const CreatePlayerSessionsRequest &request)
CreateVpcPeeringAuthorizationResponse * createVpcPeeringAuthorization (const CreateVpcPeeringAuthorizationRequest &request)
CreateVpcPeeringConnectionResponse * createVpcPeeringConnection (const CreateVpcPeeringConnectionRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteBuildResponse * deleteBuild (const DeleteBuildRequest &request)
DeleteFleetResponse * deleteFleet (const DeleteFleetRequest &request)
DeleteGameSessionQueueResponse * deleteGameSessionQueue (const DeleteGameSessionQueueRequest &request)
DeleteMatchmakingConfigurationResponse * deleteMatchmakingConfiguration (const DeleteMatchmakingConfigurationRequest &request)
DeleteScalingPolicyResponse * deleteScalingPolicy (const DeleteScalingPolicyRequest &request)
DeleteVpcPeeringAuthorizationResponse * deleteVpcPeeringAuthorization (const DeleteVpcPeeringAuthorizationRequest &request)
DeleteVpcPeeringConnectionResponse * deleteVpcPeeringConnection (const DeleteVpcPeeringConnectionRequest &request)
DescribeAliasResponse * describeAlias (const DescribeAliasRequest &request)
DescribeBuildResponse * describeBuild (const DescribeBuildRequest &request)
DescribeEC2InstanceLimitsResponse * describeEC2InstanceLimits (const DescribeEC2InstanceLimitsRequest &request)
DescribeFleetAttributesResponse * describeFleetAttributes (const DescribeFleetAttributesRequest &request)
DescribeFleetCapacityResponse * describeFleetCapacity (const DescribeFleetCapacityRequest &request)
DescribeFleetEventsResponse * describeFleetEvents (const DescribeFleetEventsRequest &request)
DescribeFleetPortSettingsResponse * describeFleetPortSettings (const DescribeFleetPortSettingsRequest &request)
DescribeFleetUtilizationResponse * describeFleetUtilization (const DescribeFleetUtilizationRequest &request)
DescribeGameSessionDetailsResponse * describeGameSessionDetails (const DescribeGameSessionDetailsRequest &request)
DescribeGameSessionPlacementResponse * describeGameSessionPlacement (const DescribeGameSessionPlacementRequest &request)
DescribeGameSessionQueuesResponse * describeGameSessionQueues (const DescribeGameSessionQueuesRequest &request)
DescribeGameSessionsResponse * describeGameSessions (const DescribeGameSessionsRequest &request)
DescribeInstancesResponse * describeInstances (const DescribeInstancesRequest &request)
DescribeMatchmakingResponse * describeMatchmaking (const DescribeMatchmakingRequest &request)
DescribeMatchmakingConfigurationsResponse * describeMatchmakingConfigurations (const DescribeMatchmakingConfigurationsRequest &request)
DescribeMatchmakingRuleSetsResponse * describeMatchmakingRuleSets (const DescribeMatchmakingRuleSetsRequest &request)
DescribePlayerSessionsResponse * describePlayerSessions (const DescribePlayerSessionsRequest &request)
DescribeRuntimeConfigurationResponse * describeRuntimeConfiguration (const DescribeRuntimeConfigurationRequest &request)
DescribeScalingPoliciesResponse * describeScalingPolicies (const DescribeScalingPoliciesRequest &request)
DescribeVpcPeeringAuthorizationsResponse * describeVpcPeeringAuthorizations (const DescribeVpcPeeringAuthorizationsRequest &request)
DescribeVpcPeeringConnectionsResponse * describeVpcPeeringConnections (const DescribeVpcPeeringConnectionsRequest &request)
GetGameSessionLogUrlResponse * getGameSessionLogUrl (const GetGameSessionLogUrlRequest &request)
GetInstanceAccessResponse * getInstanceAccess (const GetInstanceAccessRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListBuildsResponse * listBuilds (const ListBuildsRequest &request)
ListFleetsResponse * listFleets (const ListFleetsRequest &request)
PutScalingPolicyResponse * putScalingPolicy (const PutScalingPolicyRequest &request)
RequestUploadCredentialsResponse * requestUploadCredentials (const RequestUploadCredentialsRequest &request)
ResolveAliasResponse * resolveAlias (const ResolveAliasRequest &request)
SearchGameSessionsResponse * searchGameSessions (const SearchGameSessionsRequest &request)
StartGameSessionPlacementResponse * startGameSessionPlacement (const StartGameSessionPlacementRequest &request)
StartMatchBackfillResponse * startMatchBackfill (const StartMatchBackfillRequest &request)
StartMatchmakingResponse * startMatchmaking (const StartMatchmakingRequest &request)
StopGameSessionPlacementResponse * stopGameSessionPlacement (const StopGameSessionPlacementRequest &request)
StopMatchmakingResponse * stopMatchmaking (const StopMatchmakingRequest &request)
UpdateAliasResponse * updateAlias (const UpdateAliasRequest &request)
UpdateBuildResponse * updateBuild (const UpdateBuildRequest &request)
UpdateFleetAttributesResponse * updateFleetAttributes (const UpdateFleetAttributesRequest &request)
UpdateFleetCapacityResponse * updateFleetCapacity (const UpdateFleetCapacityRequest &request)
UpdateFleetPortSettingsResponse * updateFleetPortSettings (const UpdateFleetPortSettingsRequest &request)
UpdateGameSessionResponse * updateGameSession (const UpdateGameSessionRequest &request)
UpdateGameSessionQueueResponse * updateGameSessionQueue (const UpdateGameSessionQueueRequest &request)
UpdateMatchmakingConfigurationResponse * updateMatchmakingConfiguration (const UpdateMatchmakingConfigurationRequest &request)
UpdateRuntimeConfigurationResponse * updateRuntimeConfiguration (const UpdateRuntimeConfigurationRequest &request)
ValidateMatchmakingRuleSetResponse * validateMatchmakingRuleSet (const ValidateMatchmakingRuleSetRequest &request)
Public Member Functions
GameLiftClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GameLiftClient object.
GameLiftClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GameLiftClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon GameLift.
<fullname>Amazon GameLift Service</fullname>
Amazon GameLift is a managed service for developers who need a scalable, dedicated server solution for their multiplayer games. Use Amazon GameLift for these tasks: (1) set up computing resources and deploy your game servers, (2) run game sessions and get players into games, (3) automatically scale your resources to meet player demand and manage costs, and (4) track in-depth metrics on game server performance and player
usage>
The Amazon GameLift service API includes two important function
sets>
Manage game sessions and player access – Retrieve information on available game sessions; create new game sessions; send player requests to join a game
session>
Configure and manage game server resources – Manage builds, fleets, queues, and aliases; set autoscaling policies; retrieve logs and
metrics>
This reference guide describes the low-level service API for Amazon GameLift. You can use the API functionality with these tools:
</p
The Amazon Web Services software development kit (AWS SDK) is available in multiple languages including C++ and C#. Use the SDK to access the API programmatically from an application, such as a game
client>
The AWS command-line interface (CLI) tool is primarily useful for handling administrative actions, such as setting up and managing Amazon GameLift settings and resources. You can use the AWS CLI to manage all of your AWS
services>
The AWS Management Console for Amazon GameLift provides a web interface to manage your Amazon GameLift settings and resources. The console includes a dashboard for tracking key resources, including builds and fleets, and displays usage and performance metrics for your games as customizable
graphs>
Amazon GameLift Local is a tool for testing your game's integration with Amazon GameLift before deploying it on the service. This tools supports a subset of key API actions, which can be called from either the AWS CLI or programmatically. See Testing an Integration>
Learn more
</p
Developer Guide – Read about Amazon GameLift features and how to use them.
</p
Tutorials – Get started fast with walkthroughs and sample
projects>
GameDev Blog – Stay up to date with new features and
techniques>
GameDev Forums – Connect with the GameDev
community>
Release notes and document history – Stay current with updates to the Amazon GameLift service, SDKs, and documentation.
</p
API SUMMARY
Managing Games and Players
</p
Use these actions to start new game sessions, find existing game sessions, track game session status and other information, and enable player access to game
sessions>
Discover existing game sessions
</p
SearchGameSessions – Retrieve all available game sessions or search for game sessions that match a set of criteria.
</p
Start new game sessions
</p
Start new games with Queues to find the best available hosting resources across multiple regions, minimize player latency, and balance game session activity for efficiency and cost effectiveness.
</p
StartGameSessionPlacement – Request a new game session placement and add one or more players to
it>
DescribeGameSessionPlacement – Get details on a placement request, including
status>
StopGameSessionPlacement – Cancel a placement request.
</p
CreateGameSession – Start a new game session on a specific fleet. Available in Amazon GameLift Local.
</p
Match players to game sessions with FlexMatch matchmaking
</p
StartMatchmaking – Request matchmaking for one players or a group who want to play together.
</p
StartMatchBackfill - Request additional player matches to fill empty slots in an existing game session.
</p
DescribeMatchmaking – Get details on a matchmaking request, including
status>
AcceptMatch – Register that a player accepts a proposed match, for matches that require player acceptance.
</p
StopMatchmaking – Cancel a matchmaking request.
</p
Manage game session data
</p
DescribeGameSessions – Retrieve metadata for one or more game sessions, including length of time active and current player count. Available in Amazon GameLift Local.
</p
DescribeGameSessionDetails – Retrieve metadata and the game session protection setting for one or more game
sessions>
UpdateGameSession – Change game session settings, such as maximum player count and join
policy>
GetGameSessionLogUrl – Get the location of saved logs for a game
session>
Manage player sessions
</p
CreatePlayerSession – Send a request for a player to join a game session. Available in Amazon GameLift Local.
</p
CreatePlayerSessions – Send a request for multiple players to join a game session. Available in Amazon GameLift Local.
</p
DescribePlayerSessions – Get details on player activity, including status, playing time, and player data. Available in Amazon GameLift Local.
</p
Setting Up and Managing Game Servers
</p
When setting up Amazon GameLift resources for your game, you first create a game build and upload it to Amazon GameLift. You can then use these actions to configure and manage a fleet of resources to run your game servers, scale capacity to meet player demand, access performance and utilization metrics, and
more>
Manage game builds
</p
CreateBuild – Create a new build using files stored in an Amazon S3 bucket. To create a build and upload files from a local path, use the AWS CLI command
upload-build>
ListBuilds – Get a list of all builds uploaded to a Amazon GameLift
region>
DescribeBuild – Retrieve information associated with a
build>
UpdateBuild – Change build metadata, including build name and
version>
DeleteBuild – Remove a build from Amazon
GameLift>
Manage fleets
</p
CreateFleet – Configure and activate a new fleet to run a build's game
servers>
ListFleets – Get a list of all fleet IDs in a Amazon GameLift region (all
statuses)>
DeleteFleet – Terminate a fleet that is no longer running game servers or hosting
players>
View / update fleet
configurations>
DescribeFleetAttributes / UpdateFleetAttributes – View or change a fleet's metadata and settings for game session protection and resource creation
limits>
DescribeFleetPortSettings / UpdateFleetPortSettings – View or change the inbound permissions (IP address and port setting ranges) allowed for a
fleet>
DescribeRuntimeConfiguration / UpdateRuntimeConfiguration – View or change what server processes (and how many) to run on each instance in a
fleet>
Control fleet capacity
</p
DescribeEC2InstanceLimits – Retrieve maximum number of instances allowed for the current AWS account and the current usage
level>
DescribeFleetCapacity / UpdateFleetCapacity – Retrieve the capacity settings and the current number of instances in a fleet; adjust fleet capacity settings to scale up or
down>
Autoscale – Manage autoscaling rules and apply them to a
fleet>
PutScalingPolicy – Create a new autoscaling policy, or update an existing
one>
DescribeScalingPolicies – Retrieve an existing autoscaling
policy>
DeleteScalingPolicy – Delete an autoscaling policy and stop it from affecting a fleet's
capacity>
Manage VPC peering connections for fleets
</p
CreateVpcPeeringAuthorization – Authorize a peering connection to one of your
VPCs>
DescribeVpcPeeringAuthorizations – Retrieve valid peering connection authorizations.
</p
DeleteVpcPeeringAuthorization – Delete a peering connection
authorization>
CreateVpcPeeringConnection – Establish a peering connection between the VPC for a Amazon GameLift fleet and one of your
VPCs>
DescribeVpcPeeringConnections – Retrieve information on active or pending VPC peering connections with a Amazon GameLift
fleet>
DeleteVpcPeeringConnection – Delete a VPC peering connection with a Amazon GameLift
fleet>
Access fleet activity statistics
</p
DescribeFleetUtilization – Get current data on the number of server processes, game sessions, and players currently active on a
fleet>
DescribeFleetEvents – Get a fleet's logged events for a specified time
span>
DescribeGameSessions – Retrieve metadata associated with one or more game sessions, including length of time active and current player
count>
Remotely access an instance
</p
DescribeInstances – Get information on each instance in a fleet, including instance ID, IP address, and
status>
GetInstanceAccess – Request access credentials needed to remotely connect to a specified instance in a
fleet>
Manage fleet aliases
</p
CreateAlias – Define a new alias and optionally assign it to a
fleet>
ListAliases – Get all fleet aliases defined in a Amazon GameLift
region>
DescribeAlias – Retrieve information on an existing
alias>
UpdateAlias – Change settings for a alias, such as redirecting it from one fleet to
another>
DeleteAlias – Remove an alias from the
region>
ResolveAlias – Get the fleet ID that a specified alias points
to>
Manage game session queues
</p
CreateGameSessionQueue – Create a queue for processing requests for new game sessions.
</p
DescribeGameSessionQueues – Retrieve game session queues defined in a Amazon GameLift
region>
UpdateGameSessionQueue – Change the configuration of a game session
queue>
DeleteGameSessionQueue – Remove a game session queue from the
region>
Manage FlexMatch resources
</p
CreateMatchmakingConfiguration – Create a matchmaking configuration with instructions for building a player group and placing in a new game session.
</p
DescribeMatchmakingConfigurations – Retrieve matchmaking configurations defined a Amazon GameLift
region>
UpdateMatchmakingConfiguration – Change settings for matchmaking configuration.
queue>
DeleteMatchmakingConfiguration – Remove a matchmaking configuration from the
region>
CreateMatchmakingRuleSet – Create a set of rules to use when searching for player matches.
</p
DescribeMatchmakingRuleSets – Retrieve matchmaking rule sets defined in a Amazon GameLift
region>
ValidateMatchmakingRuleSet – Verify syntax for a set of matchmaking rules.
Definition at line 162 of file gameliftclient.h.
Constructor & Destructor Documentation
GameLiftClient() [1/2]
QtAws::GameLift::GameLiftClient::GameLiftClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GameLiftClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 612 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new GameLiftClientPrivate(this), parent)
 {
     Q_D(GameLiftClient);
     d->apiVersion = QStringLiteral("2015-10-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("gamelift");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon GameLift");
     d->serviceName = QStringLiteral("gamelift");
 }
GameLiftClient() [2/2]
QtAws::GameLift::GameLiftClient::GameLiftClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GameLiftClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 645 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new GameLiftClientPrivate(this), parent)
 {
     Q_D(GameLiftClient);
     d->apiVersion = QStringLiteral("2015-10-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("gamelift");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon GameLift");
     d->serviceName = QStringLiteral("gamelift");
 }
Member Function Documentation
acceptMatch
AcceptMatchResponse * QtAws::GameLift::GameLiftClient::acceptMatch (const AcceptMatchRequest & request) slot
Registers a player's acceptance or rejection of a proposed FlexMatch match. A matchmaking configuration may require player acceptance; if so, then matches built with that configuration cannot be completed unless all players accept the proposed match within a specified time limit.
</p
When FlexMatch builds a match, all the matchmaking tickets involved in the proposed match are placed into status REQUIRES_ACCEPTANCE. This is a trigger for your game to get acceptance from all players in the ticket. Acceptances are only valid for tickets when they are in this status; all other acceptances result in an
error>
To register acceptance, specify the ticket ID, a response, and one or more players. Once all players have registered acceptance, the matchmaking tickets advance to status PLACING, where a new game session is created for the match.
</p
If any player rejects the match, or if acceptances are not received before a specified timeout, the proposed match is dropped. The matchmaking tickets are then handled in one of two ways: For tickets where all players accepted the match, the ticket status is returned to SEARCHING to find a new match. For tickets where one or more players failed to accept the match, the ticket status is set to FAILED, and processing is terminated. A new matchmaking request for these players can be submitted as needed.
StartMatchmaking
</p
DescribeMatchmaking
</p
StopMatchmaking
</p
AcceptMatch
</p
StartMatchBackfill
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 717 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcceptMatchResponse *>(send(request));
 }
createAlias
CreateAliasResponse * QtAws::GameLift::GameLiftClient::createAlias (const CreateAliasRequest & request) slot
Creates an alias for a fleet. In most situations, you can use an alias ID in place of a fleet ID. By using a fleet alias instead of a specific fleet ID, you can switch gameplay and players to a new fleet without changing your game client or other game components. For example, for games in production, using an alias allows you to seamlessly redirect your player base to a new game server update.
</p
Amazon GameLift supports two types of routing strategies for aliases: simple and terminal. A simple alias points to an active fleet. A terminal alias is used to display messaging or link to a URL instead of routing players to an active fleet. For example, you might use a terminal alias when a game version is no longer supported and you want to direct players to an upgrade site.
</p
To create a fleet alias, specify an alias name, routing strategy, and optional description. Each simple alias can point to only one fleet, but a fleet can have multiple aliases. If successful, a new alias record is returned, including an alias ID, which you can reference when creating a game session. You can reassign an alias to another fleet by calling
UpdateAlias>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 775 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAliasResponse *>(send(request));
 }
createBuild
CreateBuildResponse * QtAws::GameLift::GameLiftClient::createBuild (const CreateBuildRequest & request) slot
Creates a new Amazon GameLift build record for your game server binary files and points to the location of your game server build files in an Amazon Simple Storage Service (Amazon S3) location.
</p
Game server binaries must be combined into a .zip file for use with Amazon GameLift. See Uploading Your Game for more information.
</p
To create new builds quickly and easily, use the AWS CLI command upload-build . This helper command uploads your build and creates a new build record in one step, and automatically handles the necessary permissions. See Upload Build Files to Amazon GameLift for more
help>
The CreateBuild operation should be used only when you need to manually upload your build files, as in the following
scenarios>
Store a build file in an Amazon S3 bucket under your own AWS account. To use this option, you must first give Amazon GameLift access to that Amazon S3 bucket. See Create a Build with Files in Amazon S3 for detailed help. To create a new build record using files in your Amazon S3 bucket, call CreateBuild and specify a build name, operating system, and the storage location of your game
build>
Upload a build file directly to Amazon GameLift's Amazon S3 account. To use this option, you first call CreateBuild with a build name and operating system. This action creates a new build record and returns an Amazon S3 storage location (bucket and key only) and temporary access credentials. Use the credentials to manually upload your build file to the storage location (see the Amazon S3 topic Uploading Objects). You can upload files to a location only once.
</p
If successful, this operation creates a new build record with a unique build ID and places it in INITIALIZED status. You can use DescribeBuild to check the status of your build. A build must be in READY status before it can be used to create
fleets>
Build-related operations
include>
CreateBuild
</p
ListBuilds
</p
DescribeBuild
</p
UpdateBuild
</p
DeleteBuild
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 856 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBuildResponse *>(send(request));
 }
createFleet
CreateFleetResponse * QtAws::GameLift::GameLiftClient::createFleet (const CreateFleetRequest & request) slot
Creates a new fleet to run your game servers. A fleet is a set of Amazon Elastic Compute Cloud (Amazon EC2) instances, each of which can run multiple server processes to host game sessions. You set up a fleet to use instances with certain hardware specifications (see Amazon EC2 Instance Types for more information), and deploy your game build to run on each instance.
</p
To create a new fleet, you must specify the following: (1) a fleet name, (2) the build ID of a successfully uploaded game build, (3) an EC2 instance type, and (4) a run-time configuration, which describes the server processes to run on each instance in the fleet. If you don't specify a fleet type (on-demand or spot), the new fleet uses on-demand instances by
default>
You can also configure the new fleet with the following
settings>
Fleet
descriptio>
Access permissions for inbound
traffi>
Fleet-wide game session
protectio>
Resource usage
limit>
VPC peering connection (see VPC Peering with Amazon GameLift Fleets>
If you use Amazon CloudWatch for metrics, you can add the new fleet to a metric group. By adding multiple fleets to a metric group, you can view aggregated metrics for all the fleets in the group.
</p
If the CreateFleet call is successful, Amazon GameLift performs the following tasks. You can track the process of a fleet by checking the fleet status or by monitoring fleet creation
events>
Creates a fleet record. Status:
NEW>
Begins writing events to the fleet event log, which can be accessed in the Amazon GameLift
console>
Sets the fleet's target capacity to 1 (desired instances), which triggers Amazon GameLift to start one new EC2
instance>
Downloads the game build to the new instance and installs it. Statuses: DOWNLOADING, VALIDATING, BUILDING.
</p
Starts launching server processes on the instance. If the fleet is configured to run multiple server processes per instance, Amazon GameLift staggers each launch by a few seconds. Status:
ACTIVATING>
Sets the fleet's status to ACTIVE as soon as one server process is ready to host a game
session>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1029 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFleetResponse *>(send(request));
 }
createGameSession
CreateGameSessionResponse * QtAws::GameLift::GameLiftClient::createGameSession (const CreateGameSessionRequest & request) slot
Creates a multiplayer game session for players. This action creates a game session record and assigns an available server process in the specified fleet to host the game session. A fleet must have an ACTIVE status before a game session can be created in
it>
To create a game session, specify either fleet ID or alias ID and indicate a maximum number of players to allow in the game session. You can also provide a name and game-specific properties for this game session. If successful, a GameSession object is returned containing the game session properties and other settings you
specified>
Idempotency tokens. You can add a token that uniquely identifies game session requests. This is useful for ensuring that game session requests are idempotent. Multiple requests with the same idempotency token are processed only once; subsequent requests return the original result. All response values are the same with the exception of game session status, which may
change>
Resource creation limits. If you are creating a game session on a fleet with a resource creation limit policy in force, then you must specify a creator ID. Without this ID, Amazon GameLift has no way to evaluate the policy for this new game session
request>
Player acceptance policy. By default, newly created game sessions are open to new players. You can restrict new player access by using UpdateGameSession to change the game session's player session creation
policy>
Game session logs. Logs are retained for all active game sessions for 14 days. To access the logs, call GetGameSessionLogUrl to download the log
files>
Available in Amazon GameLift Local.
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1122 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGameSessionResponse *>(send(request));
 }
createGameSessionQueue
CreateGameSessionQueueResponse * QtAws::GameLift::GameLiftClient::createGameSessionQueue (const CreateGameSessionQueueRequest & request) slot
Establishes a new queue for processing requests to place new game sessions. A queue identifies where new game sessions can be hosted – by specifying a list of destinations (fleets or aliases) – and how long requests can wait in the queue before timing out. You can set up a queue to try to place game sessions on fleets in multiple regions. To add placement requests to a queue, call StartGameSessionPlacement and reference the queue
name>
Destination order. When processing a request for a game session, Amazon GameLift tries each destination in order until it finds one with available resources to host the new game session. A queue's default order is determined by how destinations are listed. The default order is overridden when a game session placement request provides player latency information. Player latency information enables Amazon GameLift to prioritize destinations where players report the lowest average latency, as a result placing the new game session where the majority of players will have the best possible gameplay
experience>
Player latency policies. For placement requests containing player latency information, use player latency policies to protect individual players from very high latencies. With a latency cap, even when a destination can deliver a low latency for most players, the game is not placed where any individual player is reporting latency higher than a policy's maximum. A queue can have multiple latency policies, which are enforced consecutively starting with the policy with the lowest latency cap. Use multiple policies to gradually relax latency controls; for example, you might set a policy with a low latency cap for the first 60 seconds, a second policy with a higher cap for the next 60 seconds, etc.
</p
To create a new queue, provide a name, timeout value, a list of destinations and, if desired, a set of latency policies. If successful, a new queue object is
returned>
Queue-related operations
include>
CreateGameSessionQueue
</p
DescribeGameSessionQueues
</p
UpdateGameSessionQueue
</p
DeleteGameSessionQueue
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1182 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGameSessionQueueResponse *>(send(request));
 }
createMatchmakingConfiguration
CreateMatchmakingConfigurationResponse * QtAws::GameLift::GameLiftClient::createMatchmakingConfiguration (const CreateMatchmakingConfigurationRequest & request) slot
Defines a new matchmaking configuration for use with FlexMatch. A matchmaking configuration sets out guidelines for matching players and getting the matches into games. You can set up multiple matchmaking configurations to handle the scenarios needed for your game. Each matchmaking ticket (StartMatchmaking or StartMatchBackfill) specifies a configuration for the match and provides player attributes to support the configuration being used.
</p
To create a matchmaking configuration, at a minimum you must specify the following: configuration name; a rule set that governs how to evaluate players and find acceptable matches; a game session queue to use when placing a new game session for the match; and the maximum time allowed for a matchmaking
attempt>
Player acceptance – In each configuration, you have the option to require that all players accept participation in a proposed match. To enable this feature, set AcceptanceRequired to true and specify a time limit for player acceptance. Players have the option to accept or reject a proposed match, and a match does not move ahead to game session placement unless all matched players accept.
</p
Matchmaking status notification – There are two ways to track the progress of matchmaking tickets: (1) polling ticket status with DescribeMatchmaking; or (2) receiving notifications with Amazon Simple Notification Service (SNS). To use notifications, you first need to set up an SNS topic to receive the notifications, and provide the topic ARN in the matchmaking configuration (see Setting up Notifications for Matchmaking). Since notifications promise only "best effort" delivery, we recommend calling DescribeMatchmaking if no notifications are received within 30
seconds>
Operations related to match configurations and rule sets
include>
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1254 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateMatchmakingConfigurationResponse *>(send(request));
 }
createMatchmakingRuleSet
CreateMatchmakingRuleSetResponse * QtAws::GameLift::GameLiftClient::createMatchmakingRuleSet (const CreateMatchmakingRuleSetRequest & request) slot
Creates a new rule set for FlexMatch matchmaking. A rule set describes the type of match to create, such as the number and size of teams, and sets the parameters for acceptable player matches, such as minimum skill level or character type. Rule sets are used in matchmaking configurations, which define how matchmaking requests are handled. Each MatchmakingConfiguration uses one rule set; you can set up multiple rule sets to handle the scenarios that suit your game (such as for different game modes), and create a separate matchmaking configuration for each rule set. See additional information on rule set content in the MatchmakingRuleSet structure. For help creating rule sets, including useful examples, see the topic Adding FlexMatch to Your Game>
Once created, matchmaking rule sets cannot be changed or deleted, so we recommend checking the rule set syntax using ValidateMatchmakingRuleSet before creating the rule
set>
To create a matchmaking rule set, provide the set of rules and a unique name. Rule sets must be defined in the same region as the matchmaking configuration they will be used with. Rule sets cannot be edited or deleted. If you need to change a rule set, create a new one with the necessary edits and then update matchmaking configurations to use the new rule
set>
Operations related to match configurations and rule sets
include>
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1319 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateMatchmakingRuleSetResponse *>(send(request));
 }
createPlayerSession
CreatePlayerSessionResponse * QtAws::GameLift::GameLiftClient::createPlayerSession (const CreatePlayerSessionRequest & request) slot
Adds a player to a game session and creates a player session record. Before a player can be added, a game session must have an ACTIVE status, have a creation policy of ALLOW_ALL, and have an open player slot. To add a group of players to a game session, use
CreatePlayerSessions>
To create a player session, specify a game session ID, player ID, and optionally a string of player data. If successful, the player is added to the game session and a new PlayerSession object is returned. Player sessions cannot be updated.
</p
Available in Amazon GameLift Local.
CreatePlayerSession
</p
CreatePlayerSessions
</p
DescribePlayerSessions
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1377 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePlayerSessionResponse *>(send(request));
 }
createPlayerSessions
CreatePlayerSessionsResponse * QtAws::GameLift::GameLiftClient::createPlayerSessions (const CreatePlayerSessionsRequest & request) slot
Adds a group of players to a game session. This action is useful with a team matching feature. Before players can be added, a game session must have an ACTIVE status, have a creation policy of ALLOW_ALL, and have an open player slot. To add a single player to a game session, use
CreatePlayerSession>
To create player sessions, specify a game session ID, a list of player IDs, and optionally a set of player data strings. If successful, the players are added to the game session and a set of new PlayerSession objects is returned. Player sessions cannot be
updated>
Available in Amazon GameLift Local.
CreatePlayerSession
</p
CreatePlayerSessions
</p
DescribePlayerSessions
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1435 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePlayerSessionsResponse *>(send(request));
 }
createVpcPeeringAuthorization
CreateVpcPeeringAuthorizationResponse * QtAws::GameLift::GameLiftClient::createVpcPeeringAuthorization (const CreateVpcPeeringAuthorizationRequest & request) slot
Requests authorization to create or delete a peer connection between the VPC for your Amazon GameLift fleet and a virtual private cloud (VPC) in your AWS account. VPC peering enables the game servers on your fleet to communicate directly with other AWS resources. Once you've received authorization, call CreateVpcPeeringConnection to establish the peering connection. For more information, see VPC Peering with Amazon GameLift Fleets>
You can peer with VPCs that are owned by any AWS account you have access to, including the account that you use to manage your Amazon GameLift fleets. You cannot peer with VPCs that are in different
regions>
To request authorization to create a connection, call this operation from the AWS account with the VPC that you want to peer to your Amazon GameLift fleet. For example, to enable your game servers to retrieve data from a DynamoDB table, use the account that manages that DynamoDB resource. Identify the following values: (1) The ID of the VPC that you want to peer with, and (2) the ID of the AWS account that you use to manage Amazon GameLift. If successful, VPC peering is authorized for the specified VPC.
</p
To request authorization to delete a connection, call this operation from the AWS account with the VPC that is peered with your Amazon GameLift fleet. Identify the following values: (1) VPC ID that you want to delete the peering connection for, and (2) ID of the AWS account that you use to manage Amazon GameLift.
</p
The authorization remains valid for 24 hours unless it is canceled by a call to DeleteVpcPeeringAuthorization. You must create or delete the peering connection while the authorization is valid.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1505 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcPeeringAuthorizationResponse *>(send(request));
 }
createVpcPeeringConnection
CreateVpcPeeringConnectionResponse * QtAws::GameLift::GameLiftClient::createVpcPeeringConnection (const CreateVpcPeeringConnectionRequest & request) slot
Establishes a VPC peering connection between a virtual private cloud (VPC) in an AWS account with the VPC for your Amazon GameLift fleet. VPC peering enables the game servers on your fleet to communicate directly with other AWS resources. You can peer with VPCs in any AWS account that you have access to, including the account that you use to manage your Amazon GameLift fleets. You cannot peer with VPCs that are in different regions. For more information, see VPC Peering with Amazon GameLift Fleets>
Before calling this operation to establish the peering connection, you first need to call CreateVpcPeeringAuthorization and identify the VPC you want to peer with. Once the authorization for the specified VPC is issued, you have 24 hours to establish the connection. These two operations handle all tasks necessary to peer the two VPCs, including acceptance, updating routing tables, etc.
</p
To establish the connection, call this operation from the AWS account that is used to manage the Amazon GameLift fleets. Identify the following values: (1) The ID of the fleet you want to be enable a VPC peering connection for; (2) The AWS account with the VPC that you want to peer with; and (3) The ID of the VPC you want to peer with. This operation is asynchronous. If successful, a VpcPeeringConnection request is created. You can use continuous polling to track the request's status using DescribeVpcPeeringConnections, or by monitoring fleet events for success or failure using DescribeFleetEvents.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1567 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcPeeringConnectionResponse *>(send(request));
 }
deleteAlias
DeleteAliasResponse * QtAws::GameLift::GameLiftClient::deleteAlias (const DeleteAliasRequest & request) slot
Deletes an alias. This action removes all record of the alias. Game clients attempting to access a server process using the deleted alias receive an error. To delete an alias, specify the alias ID to be
deleted>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1610 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAliasResponse *>(send(request));
 }
deleteBuild
DeleteBuildResponse * QtAws::GameLift::GameLiftClient::deleteBuild (const DeleteBuildRequest & request) slot
Deletes a build. This action permanently deletes the build record and any uploaded build
files>
To delete a build, specify its ID. Deleting a build does not affect the status of any active fleets using the build, but you can no longer create new fleets with the deleted
build>
Build-related operations
include>
CreateBuild
</p
ListBuilds
</p
DescribeBuild
</p
UpdateBuild
</p
DeleteBuild
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1653 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBuildResponse *>(send(request));
 }
deleteFleet
DeleteFleetResponse * QtAws::GameLift::GameLiftClient::deleteFleet (const DeleteFleetRequest & request) slot
Deletes everything related to a fleet. Before deleting a fleet, you must set the fleet's desired capacity to zero. See
UpdateFleetCapacity>
This action removes the fleet's resources and the fleet record. Once a fleet is deleted, you can no longer use that
fleet>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1759 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFleetResponse *>(send(request));
 }
deleteGameSessionQueue
DeleteGameSessionQueueResponse * QtAws::GameLift::GameLiftClient::deleteGameSessionQueue (const DeleteGameSessionQueueRequest & request) slot
Deletes a game session queue. This action means that any StartGameSessionPlacement requests that reference this queue will fail. To delete a queue, specify the queue
name>
Queue-related operations
include>
CreateGameSessionQueue
</p
DescribeGameSessionQueues
</p
UpdateGameSessionQueue
</p
DeleteGameSessionQueue
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1794 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGameSessionQueueResponse *>(send(request));
 }
deleteMatchmakingConfiguration
DeleteMatchmakingConfigurationResponse * QtAws::GameLift::GameLiftClient::deleteMatchmakingConfiguration (const DeleteMatchmakingConfigurationRequest & request) slot
Permanently removes a FlexMatch matchmaking configuration. To delete, specify the configuration name. A matchmaking configuration cannot be deleted if it is being used in any active matchmaking
tickets>
Operations related to match configurations and rule sets
include>
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1841 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMatchmakingConfigurationResponse *>(send(request));
 }
deleteScalingPolicy
DeleteScalingPolicyResponse * QtAws::GameLift::GameLiftClient::deleteScalingPolicy (const DeleteScalingPolicyRequest & request) slot
Deletes a fleet scaling policy. This action means that the policy is no longer in force and removes all record of it. To delete a scaling policy, specify both the scaling policy name and the fleet ID it is associated
with>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1944 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteScalingPolicyResponse *>(send(request));
 }
deleteVpcPeeringAuthorization
DeleteVpcPeeringAuthorizationResponse * QtAws::GameLift::GameLiftClient::deleteVpcPeeringAuthorization (const DeleteVpcPeeringAuthorizationRequest & request) slot
Cancels a pending VPC peering authorization for the specified VPC. If the authorization has already been used to create a peering connection, call DeleteVpcPeeringConnection to remove the connection.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1987 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcPeeringAuthorizationResponse *>(send(request));
 }
deleteVpcPeeringConnection
DeleteVpcPeeringConnectionResponse * QtAws::GameLift::GameLiftClient::deleteVpcPeeringConnection (const DeleteVpcPeeringConnectionRequest & request) slot
Removes a VPC peering connection. To delete the connection, you must have a valid authorization for the VPC peering connection that you want to delete. You can check for an authorization by calling DescribeVpcPeeringAuthorizations or request a new one using CreateVpcPeeringAuthorization.
</p
Once a valid authorization exists, call this operation from the AWS account that is used to manage the Amazon GameLift fleets. Identify the connection to delete by the connection ID and fleet ID. If successful, the connection is removed.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2036 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcPeeringConnectionResponse *>(send(request));
 }
describeAlias
DescribeAliasResponse * QtAws::GameLift::GameLiftClient::describeAlias (const DescribeAliasRequest & request) slot
Retrieves properties for an alias. This operation returns all alias metadata and settings. To get an alias's target fleet ID only, use ResolveAlias.
</p
To get alias properties, specify the alias ID. If successful, the requested alias record is
returned>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2083 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAliasResponse *>(send(request));
 }
describeBuild
DescribeBuildResponse * QtAws::GameLift::GameLiftClient::describeBuild (const DescribeBuildRequest & request) slot
Retrieves properties for a build. To request a build record, specify a build ID. If successful, an object containing the build properties is
returned>
Build-related operations
include>
CreateBuild
</p
ListBuilds
</p
DescribeBuild
</p
UpdateBuild
</p
DeleteBuild
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2122 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBuildResponse *>(send(request));
 }
describeEC2InstanceLimits
DescribeEC2InstanceLimitsResponse * QtAws::GameLift::GameLiftClient::describeEC2InstanceLimits (const DescribeEC2InstanceLimitsRequest & request) slot
Retrieves the following information for the specified EC2 instance
type>
maximum number of instances allowed per AWS account (service
limit>
current usage level for the AWS
accoun>
Service limits vary depending on region. Available regions for Amazon GameLift can be found in the AWS Management Console for Amazon GameLift (see the drop-down list in the upper right
corner)>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2237 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEC2InstanceLimitsResponse *>(send(request));
 }
describeFleetAttributes
DescribeFleetAttributesResponse * QtAws::GameLift::GameLiftClient::describeFleetAttributes (const DescribeFleetAttributesRequest & request) slot
Retrieves fleet properties, including metadata, status, and configuration, for one or more fleets. You can request attributes for all fleets, or specify a list of one or more fleet IDs. When requesting multiple fleets, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a FleetAttributes object is returned for each requested fleet ID. When specifying a list of fleet IDs, attribute objects are returned only for fleets that currently exist.
</p <note>
Some API actions may limit the number of fleet IDs allowed in one request. If a request exceeds this limit, the request fails and the error message includes the maximum
allowed> </note>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2348 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetAttributesResponse *>(send(request));
 }
describeFleetCapacity
DescribeFleetCapacityResponse * QtAws::GameLift::GameLiftClient::describeFleetCapacity (const DescribeFleetCapacityRequest & request) slot
Retrieves the current status of fleet capacity for one or more fleets. This information includes the number of instances that have been requested for the fleet and the number currently active. You can request capacity for all fleets, or specify a list of one or more fleet IDs. When requesting multiple fleets, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a FleetCapacity object is returned for each requested fleet ID. When specifying a list of fleet IDs, attribute objects are returned only for fleets that currently exist.
</p <note>
Some API actions may limit the number of fleet IDs allowed in one request. If a request exceeds this limit, the request fails and the error message includes the maximum
allowed> </note>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2459 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetCapacityResponse *>(send(request));
 }
describeFleetEvents
DescribeFleetEventsResponse * QtAws::GameLift::GameLiftClient::describeFleetEvents (const DescribeFleetEventsRequest & request) slot
Retrieves entries from the specified fleet's event log. You can specify a time range to limit the result set. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, a collection of event log entries matching the request are
returned>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2563 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetEventsResponse *>(send(request));
 }
describeFleetPortSettings
DescribeFleetPortSettingsResponse * QtAws::GameLift::GameLiftClient::describeFleetPortSettings (const DescribeFleetPortSettingsRequest & request) slot
Retrieves the inbound connection permissions for a fleet. Connection permissions include a range of IP addresses and port settings that incoming traffic can use to access server processes in the fleet. To get a fleet's inbound connection permissions, specify a fleet ID. If successful, a collection of IpPermission objects is returned for the requested fleet ID. If the requested fleet has been deleted, the result set is
empty>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2668 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetPortSettingsResponse *>(send(request));
 }
describeFleetUtilization
DescribeFleetUtilizationResponse * QtAws::GameLift::GameLiftClient::describeFleetUtilization (const DescribeFleetUtilizationRequest & request) slot
Retrieves utilization statistics for one or more fleets. You can request utilization data for all fleets, or specify a list of one or more fleet IDs. When requesting multiple fleets, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a FleetUtilization object is returned for each requested fleet ID. When specifying a list of fleet IDs, utilization objects are returned only for fleets that currently exist.
</p <note>
Some API actions may limit the number of fleet IDs allowed in one request. If a request exceeds this limit, the request fails and the error message includes the maximum
allowed> </note>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2778 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetUtilizationResponse *>(send(request));
 }
describeGameSessionDetails
DescribeGameSessionDetailsResponse * QtAws::GameLift::GameLiftClient::describeGameSessionDetails (const DescribeGameSessionDetailsRequest & request) slot
Retrieves properties, including the protection policy in force, for one or more game sessions. This action can be used in several ways: (1) provide a GameSessionId or GameSessionArn to request details for a specific game session; (2) provide either a FleetId or an AliasId to request properties for all game sessions running on a fleet.
</p
To get game session record(s), specify just one of the following: game session ID, fleet ID, or alias ID. You can filter this request by game session status. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, a GameSessionDetail object is returned for each session matching the
request>
Game-session-related operations
include>
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2845 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGameSessionDetailsResponse *>(send(request));
 }
describeGameSessionPlacement
DescribeGameSessionPlacementResponse * QtAws::GameLift::GameLiftClient::describeGameSessionPlacement (const DescribeGameSessionPlacementRequest & request) slot
Retrieves properties and current status of a game session placement request. To get game session placement details, specify the placement ID. If successful, a GameSessionPlacement object is
returned>
Game-session-related operations
include>
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2904 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGameSessionPlacementResponse *>(send(request));
 }
describeGameSessionQueues
DescribeGameSessionQueuesResponse * QtAws::GameLift::GameLiftClient::describeGameSessionQueues (const DescribeGameSessionQueuesRequest & request) slot
Retrieves the properties for one or more game session queues. When requesting multiple queues, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a GameSessionQueue object is returned for each requested queue. When specifying a list of queues, objects are returned only for queues that currently exist in the
region>
Queue-related operations
include>
CreateGameSessionQueue
</p
DescribeGameSessionQueues
</p
UpdateGameSessionQueue
</p
DeleteGameSessionQueue
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2941 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGameSessionQueuesResponse *>(send(request));
 }
describeGameSessions
DescribeGameSessionsResponse * QtAws::GameLift::GameLiftClient::describeGameSessions (const DescribeGameSessionsRequest & request) slot
Retrieves a set of one or more game sessions. Request a specific game session or request all game sessions on a fleet. Alternatively, use SearchGameSessions to request a set of active game sessions that are filtered by certain criteria. To retrieve protection policy settings for game sessions, use
DescribeGameSessionDetails>
To get game sessions, specify one of the following: game session ID, fleet ID, or alias ID. You can filter this request by game session status. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, a GameSession object is returned for each game session matching the
request>
Available in Amazon GameLift Local.
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3011 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGameSessionsResponse *>(send(request));
 }
describeInstances
DescribeInstancesResponse * QtAws::GameLift::GameLiftClient::describeInstances (const DescribeInstancesRequest & request) slot
Retrieves information about a fleet's instances, including instance IDs. Use this action to get details on all instances in the fleet or get details on one specific
instance>
To get a specific instance, specify fleet ID and instance ID. To get all instances in a fleet, specify a fleet ID only. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, an Instance object is returned for each
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3032 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstancesResponse *>(send(request));
 }
describeMatchmaking
DescribeMatchmakingResponse * QtAws::GameLift::GameLiftClient::describeMatchmaking (const DescribeMatchmakingRequest & request) slot
Retrieves one or more matchmaking tickets. Use this operation to retrieve ticket information, including status and–once a successful match is made–acquire connection information for the resulting new game session.
</p
You can use this operation to track the progress of matchmaking requests (through polling) as an alternative to using event notifications. See more details on tracking matchmaking requests through polling or notifications in StartMatchmaking.
</p
To request matchmaking tickets, provide a list of up to 10 ticket IDs. If the request is successful, a ticket object is returned for each requested ID that currently
exists>
Matchmaking-related operations
include>
StartMatchmaking
</p
DescribeMatchmaking
</p
StopMatchmaking
</p
AcceptMatch
</p
StartMatchBackfill
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3082 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMatchmakingResponse *>(send(request));
 }
describeMatchmakingConfigurations
DescribeMatchmakingConfigurationsResponse * QtAws::GameLift::GameLiftClient::describeMatchmakingConfigurations (const DescribeMatchmakingConfigurationsRequest & request) slot
Retrieves the details of FlexMatch matchmaking configurations. with this operation, you have the following options: (1) retrieve all existing configurations, (2) provide the names of one or more configurations to retrieve, or (3) retrieve all configurations that use a specified rule set name. When requesting multiple items, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a configuration is returned for each requested name. When specifying a list of names, only configurations that currently exist are returned.
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3132 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMatchmakingConfigurationsResponse *>(send(request));
 }
describeMatchmakingRuleSets
DescribeMatchmakingRuleSetsResponse * QtAws::GameLift::GameLiftClient::describeMatchmakingRuleSets (const DescribeMatchmakingRuleSetsRequest & request) slot
Retrieves the details for FlexMatch matchmaking rule sets. You can request all existing rule sets for the region, or provide a list of one or more rule set names. When requesting multiple items, use the pagination parameters to retrieve results as a set of sequential pages. If successful, a rule set is returned for each requested name.
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3180 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMatchmakingRuleSetsResponse *>(send(request));
 }
describePlayerSessions
DescribePlayerSessionsResponse * QtAws::GameLift::GameLiftClient::describePlayerSessions (const DescribePlayerSessionsRequest & request) slot
Retrieves properties for one or more player sessions. This action can be used in several ways: (1) provide a PlayerSessionId to request properties for a specific player session; (2) provide a GameSessionId to request properties for all player sessions in the specified game session; (3) provide a PlayerId to request properties for all player sessions of a specified player.
</p
To get game session record(s), specify only one of the following: a player session ID, a game session ID, or a player ID. You can filter this request by player session status. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, a PlayerSession object is returned for each session matching the
request>
Available in Amazon GameLift Local.
CreatePlayerSession
</p
CreatePlayerSessions
</p
DescribePlayerSessions
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3239 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePlayerSessionsResponse *>(send(request));
 }
describeRuntimeConfiguration
DescribeRuntimeConfigurationResponse * QtAws::GameLift::GameLiftClient::describeRuntimeConfiguration (const DescribeRuntimeConfigurationRequest & request) slot
Retrieves the current run-time configuration for the specified fleet. The run-time configuration tells Amazon GameLift how to launch server processes on instances in the
fleet>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3342 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRuntimeConfigurationResponse *>(send(request));
 }
describeScalingPolicies
DescribeScalingPoliciesResponse * QtAws::GameLift::GameLiftClient::describeScalingPolicies (const DescribeScalingPoliciesRequest & request) slot
Retrieves all scaling policies applied to a
fleet>
To get a fleet's scaling policies, specify the fleet ID. You can filter this request by policy status, such as to retrieve only active scaling policies. Use the pagination parameters to retrieve results as a set of sequential pages. If successful, set of ScalingPolicy objects is returned for the
fleet>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3450 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingPoliciesResponse *>(send(request));
 }
describeVpcPeeringAuthorizations
DescribeVpcPeeringAuthorizationsResponse * QtAws::GameLift::GameLiftClient::describeVpcPeeringAuthorizations (const DescribeVpcPeeringAuthorizationsRequest & request) slot
Retrieves valid VPC peering authorizations that are pending for the AWS account. This operation returns all VPC peering authorizations and requests for peering. This includes those initiated and received by this account.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3493 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcPeeringAuthorizationsResponse *>(send(request));
 }
describeVpcPeeringConnections
DescribeVpcPeeringConnectionsResponse * QtAws::GameLift::GameLiftClient::describeVpcPeeringConnections (const DescribeVpcPeeringConnectionsRequest & request) slot
Retrieves information on VPC peering connections. Use this operation to get peering information for all fleets or for one specific fleet ID.
</p
To retrieve connection information, call this operation from the AWS account that is used to manage the Amazon GameLift fleets. Specify a fleet ID or leave the parameter empty to retrieve all connection records. If successful, the retrieved information includes both active and pending connections. Active connections identify the IpV4 CIDR block that the VPC uses to connect.
CreateVpcPeeringAuthorization
</p
DescribeVpcPeeringAuthorizations
</p
DeleteVpcPeeringAuthorization
</p
CreateVpcPeeringConnection
</p
DescribeVpcPeeringConnections
</p
DeleteVpcPeeringConnection
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3543 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcPeeringConnectionsResponse *>(send(request));
 }
getGameSessionLogUrl
GetGameSessionLogUrlResponse * QtAws::GameLift::GameLiftClient::getGameSessionLogUrl (const GetGameSessionLogUrlRequest & request) slot
Retrieves the location of stored game session logs for a specified game session. When a game session is terminated, Amazon GameLift automatically stores the logs in Amazon S3 and retains them for 14 days. Use this URL to download the
logs> <note>
See the AWS Service Limits page for maximum log file sizes. Log files that exceed this limit are not
saved> </note>
Game-session-related operations
include>
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3607 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGameSessionLogUrlResponse *>(send(request));
 }
getInstanceAccess
GetInstanceAccessResponse * QtAws::GameLift::GameLiftClient::getInstanceAccess (const GetInstanceAccessRequest & request) slot
Requests remote access to a fleet instance. Remote access is useful for debugging, gathering benchmarking data, or watching activity in real time.
</p
Access requires credentials that match the operating system of the instance. For a Windows instance, Amazon GameLift returns a user name and password as strings for use with a Windows Remote Desktop client. For a Linux instance, Amazon GameLift returns a user name and RSA private key, also as strings, for use with an SSH client. The private key must be saved in the proper format to a .pem file before using. If you're making this request using the AWS CLI, saving the secret can be handled as part of the GetInstanceAccess request. (See the example later in this topic). For more information on remote access, see Remotely Accessing an Instance>
To request access to a specific instance, specify the IDs of the instance and the fleet it belongs to. If successful, an InstanceAccess object is returned containing the instance's IP address and a set of
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3637 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetInstanceAccessResponse *>(send(request));
 }
listAliases
ListAliasesResponse * QtAws::GameLift::GameLiftClient::listAliases (const ListAliasesRequest & request) slot
Retrieves all aliases for this AWS account. You can filter the result set by alias name and/or routing strategy type. Use the pagination parameters to retrieve results in sequential
pages> <note>
Returned aliases are not listed in any particular
order> </note>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3684 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAliasesResponse *>(send(request));
 }
listBuilds
ListBuildsResponse * QtAws::GameLift::GameLiftClient::listBuilds (const ListBuildsRequest & request) slot
Retrieves build records for all builds associated with the AWS account in use. You can limit results to builds that are in a specific status by using the Status parameter. Use the pagination parameters to retrieve results in a set of sequential pages.
</p <note>
Build records are not listed in any particular
order> </note>
Build-related operations
include>
CreateBuild
</p
ListBuilds
</p
DescribeBuild
</p
UpdateBuild
</p
DeleteBuild
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3728 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBuildsResponse *>(send(request));
 }
listFleets
ListFleetsResponse * QtAws::GameLift::GameLiftClient::listFleets (const ListFleetsRequest & request) slot
Retrieves a collection of fleet records for this AWS account. You can filter the result set by build ID. Use the pagination parameters to retrieve results in sequential
pages> <note>
Fleet records are not listed in any particular
order> </note>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3835 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListFleetsResponse *>(send(request));
 }
putScalingPolicy
PutScalingPolicyResponse * QtAws::GameLift::GameLiftClient::putScalingPolicy (const PutScalingPolicyRequest & request) slot
Creates or updates a scaling policy for a fleet. An active scaling policy prompts Amazon GameLift to track a certain metric for a fleet and automatically change the fleet's capacity in specific circumstances. Each scaling policy contains one rule statement. Fleets can have multiple scaling policies in force
simultaneously>
A scaling policy rule statement has the following
structure>
If [MetricName] is [ComparisonOperator] [Threshold] for [EvaluationPeriods] minutes, then [ScalingAdjustmentType] to/by
[ScalingAdjustment]>
For example, this policy: "If the number of idle instances exceeds 20 for more than 15 minutes, then reduce the fleet capacity by 10 instances" could be implemented as the following rule
statement>
If [IdleInstances] is [GreaterThanOrEqualToThreshold] [20] for [15] minutes, then [ChangeInCapacity] by
[-10]>
To create or update a scaling policy, specify a unique combination of name and fleet ID, and set the rule values. All parameters for this action are required. If successful, the policy name is returned. Scaling policies cannot be suspended or made inactive. To stop enforcing a scaling policy, call
DeleteScalingPolicy>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3963 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutScalingPolicyResponse *>(send(request));
 }
requestUploadCredentials
RequestUploadCredentialsResponse * QtAws::GameLift::GameLiftClient::requestUploadCredentials (const RequestUploadCredentialsRequest & request) slot
Retrieves a fresh set of credentials for use when uploading a new set of game build files to Amazon GameLift's Amazon S3. This is done as part of the build creation process; see
CreateBuild>
To request new credentials, specify the build ID as returned with an initial CreateBuild request. If successful, a new set of credentials are returned, along with the S3 storage location associated with the build
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3983 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RequestUploadCredentialsResponse *>(send(request));
 }
resolveAlias
ResolveAliasResponse * QtAws::GameLift::GameLiftClient::resolveAlias (const ResolveAliasRequest & request) slot
Retrieves the fleet ID that a specified alias is currently pointing
to>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4025 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResolveAliasResponse *>(send(request));
 }
searchGameSessions
SearchGameSessionsResponse * QtAws::GameLift::GameLiftClient::searchGameSessions (const SearchGameSessionsRequest & request) slot
Retrieves all active game sessions that match a set of search criteria and sorts them in a specified order. You can search or sort by the following game session
attributes>
gameSessionId – Unique identifier for the game session. You can use either a GameSessionId or GameSessionArn value.
</p
gameSessionName – Name assigned to a game session. This value is set when requesting a new game session with CreateGameSession or updating with UpdateGameSession. Game session names do not need to be unique to a game
session>
gameSessionProperties – Custom data defined in a game session's GameProperty parameter. GameProperty values are stored as key:value pairs; the filter expression must indicate the key and a string to search the data values for. For example, to search for game sessions with custom data containing the key:value pair "gameMode:brawl", specify the following: gameSessionProperties.gameMode = "brawl". All custom data values are searched as
strings>
maximumSessions – Maximum number of player sessions allowed for a game session. This value is set when requesting a new game session with CreateGameSession or updating with
UpdateGameSession>
creationTimeMillis – Value indicating when a game session was created. It is expressed in Unix time as
milliseconds>
playerSessionCount – Number of players currently connected to a game session. This value changes rapidly as players join the session or drop
out>
hasAvailablePlayerSessions – Boolean value indicating whether a game session has reached its maximum number of players. It is highly recommended that all search requests include this filter attribute to optimize search performance and return only sessions that players can join.
</p
<note>
Returned values for playerSessionCount and hasAvailablePlayerSessions change quickly as players join sessions and others drop out. Results should be considered a snapshot in time. Be sure to refresh search results often, and handle sessions that fill up before a player can join.
</p </note>
To search or sort, specify either a fleet ID or an alias ID, and provide a search filter expression, a sort expression, or both. If successful, a collection of GameSession objects matching the request is returned. Use the pagination parameters to retrieve results as a set of sequential pages.
</p
You can search for game sessions one fleet at a time only. To find game sessions across multiple fleets, you must search each fleet separately and combine the results. This search feature finds only game sessions that are in ACTIVE status. To locate games in statuses other than active, use
DescribeGameSessionDetails>
Game-session-related operations
include>
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4141 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchGameSessionsResponse *>(send(request));
 }
startGameSessionPlacement
StartGameSessionPlacementResponse * QtAws::GameLift::GameLiftClient::startGameSessionPlacement (const StartGameSessionPlacementRequest & request) slot
Places a request for a new game session in a queue (see CreateGameSessionQueue). When processing a placement request, Amazon GameLift searches for available resources on the queue's destinations, scanning each until it finds resources or the placement request times
out>
A game session placement request can also request player sessions. When a new game session is successfully created, Amazon GameLift creates a player session for each player included in the
request>
When placing a game session, by default Amazon GameLift tries each fleet in the order they are listed in the queue configuration. Ideally, a queue's destinations are listed in preference
order>
Alternatively, when requesting a game session with players, you can also provide latency data for each player in relevant regions. Latency data indicates the performance lag a player experiences when connected to a fleet in the region. Amazon GameLift uses latency data to reorder the list of destinations to place the game session in a region with minimal lag. If latency data is provided for multiple players, Amazon GameLift calculates each region's average lag for all players and reorders to get the best game play across all players.
</p
To place a new game session request, specify the
following>
The queue name and a set of game session properties and
setting>
A unique ID (such as a UUID) for the placement. You use this ID to track the status of the placement
reques>
(Optional) A set of IDs and player data for each player you want to join to the new game
sessio>
Latency data for all players (if you want to optimize game play for the
players>
If successful, a new game session placement is
created>
To track the status of a placement request, call DescribeGameSessionPlacement and check the request's status. If the status is FULFILLED, a new game session has been created and a game session ARN and region are referenced. If the placement request times out, you can resubmit the request or retry it with a different queue.
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4249 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartGameSessionPlacementResponse *>(send(request));
 }
startMatchBackfill
StartMatchBackfillResponse * QtAws::GameLift::GameLiftClient::startMatchBackfill (const StartMatchBackfillRequest & request) slot
Finds new players to fill open slots in an existing game session. This operation can be used to add players to matched games that start with fewer than the maximum number of players or to replace players when they drop out. By backfilling with the same matchmaker used to create the original match, you ensure that new players meet the match criteria and maintain a consistent experience throughout the game session. You can backfill a match anytime after a game session has been created.
</p
To request a match backfill, specify a unique ticket ID, the existing game session's ARN, a matchmaking configuration, and a set of data that describes all current players in the game session. If successful, a match backfill ticket is created and returned with status set to QUEUED. The ticket is placed in the matchmaker's ticket pool and processed. Track the status of the ticket to respond as needed. For more detail how to set up backfilling, see Backfill Existing Games with FlexMatch.
</p
The process of finding backfill matches is essentially identical to the initial matchmaking process. The matchmaker searches the pool and groups tickets together to form potential matches, allowing only one backfill ticket per potential match. Once the a match is formed, the matchmaker creates player sessions for the new players. All tickets in the match are updated with the game session's connection information, and the GameSession object is updated to include matchmaker data on the new players. For more detail on how match backfill requests are processed, see How Amazon GameLift FlexMatch Works.
StartMatchmaking
</p
DescribeMatchmaking
</p
StopMatchmaking
</p
AcceptMatch
</p
StartMatchBackfill
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4310 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartMatchBackfillResponse *>(send(request));
 }
startMatchmaking
StartMatchmakingResponse * QtAws::GameLift::GameLiftClient::startMatchmaking (const StartMatchmakingRequest & request) slot
Uses FlexMatch to create a game match for a group of players based on custom matchmaking rules, and starts a new game for the matched players. Each matchmaking request specifies the type of match to build (team configuration, rules for an acceptable match, etc.). The request also specifies the players to find a match for and where to host the new game session for optimal performance. A matchmaking request might start with a single player or a group of players who want to play together. FlexMatch finds additional players as needed to fill the match. Match type, rules, and the queue used to place a new game session are defined in a MatchmakingConfiguration. For complete information on setting up and using FlexMatch, see the topic Adding FlexMatch to Your Game>
To start matchmaking, provide a unique ticket ID, specify a matchmaking configuration, and include the players to be matched. You must also include a set of player attributes relevant for the matchmaking configuration. If successful, a matchmaking ticket is returned with status set to QUEUED. Track the status of the ticket to respond as needed and acquire game session connection information for successfully completed
matches>
Tracking ticket status – A couple of options are available for tracking the status of matchmaking requests:
</p
Polling – Call DescribeMatchmaking. This operation returns the full ticket object, including current status and (for completed tickets) game session connection info. We recommend polling no more than once every 10
seconds>
Notifications – Get event notifications for changes in ticket status using Amazon Simple Notification Service (SNS). Notifications are easy to set up (see CreateMatchmakingConfiguration) and typically deliver match status changes faster and more efficiently than polling. We recommend that you use polling to back up to notifications (since delivery is not guaranteed) and call DescribeMatchmaking only when notifications are not received within 30
seconds>
Processing a matchmaking request – FlexMatch handles a matchmaking request as follows:
</p
Your client code submits a StartMatchmaking request for one or more players and tracks the status of the request ticket.
</p
FlexMatch uses this ticket and others in process to build an acceptable match. When a potential match is identified, all tickets in the proposed match are advanced to the next status.
</p
If the match requires player acceptance (set in the matchmaking configuration), the tickets move into status REQUIRES_ACCEPTANCE. This status triggers your client code to solicit acceptance from all players in every ticket involved in the match, and then call AcceptMatch for each player. If any player rejects or fails to accept the match before a specified timeout, the proposed match is dropped (see AcceptMatch for more
details)>
Once a match is proposed and accepted, the matchmaking tickets move into status PLACING. FlexMatch locates resources for a new game session using the game session queue (set in the matchmaking configuration) and creates the game session based on the match data.
</p
When the match is successfully placed, the matchmaking tickets move into COMPLETED status. Connection information (including game session endpoint and player session) is added to the matchmaking tickets. Matched players can use the connection information to join the game.
</p
Matchmaking-related operations
include>
StartMatchmaking
</p
DescribeMatchmaking
</p
StopMatchmaking
</p
AcceptMatch
</p
StartMatchBackfill
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4411 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartMatchmakingResponse *>(send(request));
 }
stopGameSessionPlacement
StopGameSessionPlacementResponse * QtAws::GameLift::GameLiftClient::stopGameSessionPlacement (const StopGameSessionPlacementRequest & request) slot
Cancels a game session placement that is in PENDING status. To stop a placement, provide the placement ID values. If successful, the placement is moved to CANCELLED
status>
Game-session-related operations
include>
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4470 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopGameSessionPlacementResponse *>(send(request));
 }
stopMatchmaking
StopMatchmakingResponse * QtAws::GameLift::GameLiftClient::stopMatchmaking (const StopMatchmakingRequest & request) slot
Cancels a matchmaking ticket that is currently being processed. To stop the matchmaking operation, specify the ticket ID. If successful, work on the ticket is stopped, and the ticket status is changed to
CANCELLED>
Matchmaking-related operations
include>
StartMatchmaking
</p
DescribeMatchmaking
</p
StopMatchmaking
</p
AcceptMatch
</p
StartMatchBackfill
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4509 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopMatchmakingResponse *>(send(request));
 }
updateAlias
UpdateAliasResponse * QtAws::GameLift::GameLiftClient::updateAlias (const UpdateAliasRequest & request) slot
Updates properties for an alias. To update properties, specify the alias ID to be updated and provide the information to be changed. To reassign an alias to another fleet, provide an updated routing strategy. If successful, the updated alias record is
returned>
Alias-related operations
include>
CreateAlias
</p
ListAliases
</p
DescribeAlias
</p
UpdateAlias
</p
DeleteAlias
</p
ResolveAlias
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4553 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAliasResponse *>(send(request));
 }
updateBuild
UpdateBuildResponse * QtAws::GameLift::GameLiftClient::updateBuild (const UpdateBuildRequest & request) slot
Updates metadata in a build record, including the build name and version. To update the metadata, specify the build ID to update and provide the new values. If successful, a build object containing the updated metadata is
returned>
Build-related operations
include>
CreateBuild
</p
ListBuilds
</p
DescribeBuild
</p
UpdateBuild
</p
DeleteBuild
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4592 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBuildResponse *>(send(request));
 }
updateFleetAttributes
UpdateFleetAttributesResponse * QtAws::GameLift::GameLiftClient::updateFleetAttributes (const UpdateFleetAttributesRequest & request) slot
Updates fleet properties, including name and description, for a fleet. To update metadata, specify the fleet ID and the property values that you want to change. If successful, the fleet ID for the updated fleet is
returned>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4695 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFleetAttributesResponse *>(send(request));
 }
updateFleetCapacity
UpdateFleetCapacityResponse * QtAws::GameLift::GameLiftClient::updateFleetCapacity (const UpdateFleetCapacityRequest & request) slot
Updates capacity settings for a fleet. Use this action to specify the number of EC2 instances (hosts) that you want this fleet to contain. Before calling this action, you may want to call DescribeEC2InstanceLimits to get the maximum capacity based on the fleet's EC2 instance
type>
If you're using autoscaling (see PutScalingPolicy), you may want to specify a minimum and/or maximum capacity. If you don't provide these, autoscaling can set capacity anywhere between zero and the service limits>
To update fleet capacity, specify the fleet ID and the number of instances you want the fleet to host. If successful, Amazon GameLift starts or terminates instances so that the fleet's active instance count matches the desired instance count. You can view a fleet's current capacity information by calling DescribeFleetCapacity. If the desired instance count is higher than the instance type's limit, the "Limit Exceeded" exception
occurs>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4812 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFleetCapacityResponse *>(send(request));
 }
updateFleetPortSettings
UpdateFleetPortSettingsResponse * QtAws::GameLift::GameLiftClient::updateFleetPortSettings (const UpdateFleetPortSettingsRequest & request) slot
Updates port settings for a fleet. To update settings, specify the fleet ID to be updated and list the permissions you want to update. List the permissions you want to add in InboundPermissionAuthorizations, and permissions you want to remove in InboundPermissionRevocations. Permissions to be removed must match existing fleet permissions. If successful, the fleet ID for the updated fleet is
returned>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4917 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFleetPortSettingsResponse *>(send(request));
 }
updateGameSession
UpdateGameSessionResponse * QtAws::GameLift::GameLiftClient::updateGameSession (const UpdateGameSessionRequest & request) slot
Updates game session properties. This includes the session name, maximum player count, protection policy, which controls whether or not an active game session can be terminated during a scale-down event, and the player session creation policy, which controls whether or not new players can join the session. To update a game session, specify the game session ID and the values you want to change. If successful, an updated GameSession object is returned.
CreateGameSession
</p
DescribeGameSessions
</p
DescribeGameSessionDetails
</p
SearchGameSessions
</p
UpdateGameSession
</p
GetGameSessionLogUrl
</p
Game session
placement>
StartGameSessionPlacement
</p
DescribeGameSessionPlacement
</p
StopGameSessionPlacement
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4978 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGameSessionResponse *>(send(request));
 }
updateGameSessionQueue
UpdateGameSessionQueueResponse * QtAws::GameLift::GameLiftClient::updateGameSessionQueue (const UpdateGameSessionQueueRequest & request) slot
Updates settings for a game session queue, which determines how new game session requests in the queue are processed. To update settings, specify the queue name to be updated and provide the new settings. When updating destinations, provide a complete list of destinations.
CreateGameSessionQueue
</p
DescribeGameSessionQueues
</p
UpdateGameSessionQueue
</p
DeleteGameSessionQueue
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5014 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGameSessionQueueResponse *>(send(request));
 }
updateMatchmakingConfiguration
UpdateMatchmakingConfigurationResponse * QtAws::GameLift::GameLiftClient::updateMatchmakingConfiguration (const UpdateMatchmakingConfigurationRequest & request) slot
Updates settings for a FlexMatch matchmaking configuration. To update settings, specify the configuration name to be updated and provide the new settings.
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5061 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateMatchmakingConfigurationResponse *>(send(request));
 }
updateRuntimeConfiguration
UpdateRuntimeConfigurationResponse * QtAws::GameLift::GameLiftClient::updateRuntimeConfiguration (const UpdateRuntimeConfigurationRequest & request) slot
Updates the current run-time configuration for the specified fleet, which tells Amazon GameLift how to launch server processes on instances in the fleet. You can update a fleet's run-time configuration at any time after the fleet is created; it does not need to be in an ACTIVE
status>
To update run-time configuration, specify the fleet ID and provide a RuntimeConfiguration object with the updated collection of server process
configurations>
Each instance in a Amazon GameLift fleet checks regularly for an updated run-time configuration and changes how it launches server processes to comply with the latest version. Existing server processes are not affected by the update; they continue to run until they end, while Amazon GameLift simply adds new server processes to fit the current run-time configuration. As a result, the run-time configuration changes are applied gradually as existing processes shut down and new processes are launched in Amazon GameLift's normal process recycling
activity>
Fleet-related operations
include>
CreateFleet
</p
ListFleets
</p
Describe
fleets>
DescribeFleetAttributes
</p
DescribeFleetPortSettings
</p
DescribeFleetUtilization
</p
DescribeRuntimeConfiguration
</p
DescribeFleetEvents
</p
Update
fleets>
UpdateFleetAttributes
</p
UpdateFleetCapacity
</p
UpdateFleetPortSettings
</p
UpdateRuntimeConfiguration
</p
Manage fleet
capacity>
DescribeFleetCapacity
</p
UpdateFleetCapacity
</p
PutScalingPolicy (automatic
scaling>
DescribeScalingPolicies (automatic
scaling>
DeleteScalingPolicy (automatic
scaling>
DescribeEC2InstanceLimits
</p
DeleteFleet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5178 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRuntimeConfigurationResponse *>(send(request));
 }
validateMatchmakingRuleSet
ValidateMatchmakingRuleSetResponse * QtAws::GameLift::GameLiftClient::validateMatchmakingRuleSet (const ValidateMatchmakingRuleSetRequest & request) slot
Validates the syntax of a matchmaking rule or rule set. This operation checks that the rule set uses syntactically correct JSON and that it conforms to allowed property expressions. To validate syntax, provide a rule set
string>
Operations related to match configurations and rule sets
include>
CreateMatchmakingConfiguration
</p
DescribeMatchmakingConfigurations
</p
UpdateMatchmakingConfiguration
</p
DeleteMatchmakingConfiguration
</p
CreateMatchmakingRuleSet
</p
DescribeMatchmakingRuleSets
</p
ValidateMatchmakingRuleSet
Parameters
request Request to send to Amazon GameLift.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5225 of file gameliftclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ValidateMatchmakingRuleSetResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
gamelift/gameliftclient.h
gamelift/gameliftclient.cpp