AWS SDK for Qt: QtAws::AppStream::AppStreamClient Class Reference
QtAws::AppStream::AppStreamClient Class Reference
Client for Amazon AppStream.
Public Slots
AssociateFleetResponse * associateFleet (const AssociateFleetRequest &request)
CopyImageResponse * copyImage (const CopyImageRequest &request)
CreateDirectoryConfigResponse * createDirectoryConfig (const CreateDirectoryConfigRequest &request)
CreateFleetResponse * createFleet (const CreateFleetRequest &request)
CreateImageBuilderResponse * createImageBuilder (const CreateImageBuilderRequest &request)
CreateImageBuilderStreamingURLResponse * createImageBuilderStreamingURL (const CreateImageBuilderStreamingURLRequest &request)
CreateStackResponse * createStack (const CreateStackRequest &request)
CreateStreamingURLResponse * createStreamingURL (const CreateStreamingURLRequest &request)
DeleteDirectoryConfigResponse * deleteDirectoryConfig (const DeleteDirectoryConfigRequest &request)
DeleteFleetResponse * deleteFleet (const DeleteFleetRequest &request)
DeleteImageResponse * deleteImage (const DeleteImageRequest &request)
DeleteImageBuilderResponse * deleteImageBuilder (const DeleteImageBuilderRequest &request)
DeleteStackResponse * deleteStack (const DeleteStackRequest &request)
DescribeDirectoryConfigsResponse * describeDirectoryConfigs (const DescribeDirectoryConfigsRequest &request)
DescribeFleetsResponse * describeFleets (const DescribeFleetsRequest &request)
DescribeImageBuildersResponse * describeImageBuilders (const DescribeImageBuildersRequest &request)
DescribeImagesResponse * describeImages (const DescribeImagesRequest &request)
DescribeSessionsResponse * describeSessions (const DescribeSessionsRequest &request)
DescribeStacksResponse * describeStacks (const DescribeStacksRequest &request)
DisassociateFleetResponse * disassociateFleet (const DisassociateFleetRequest &request)
ExpireSessionResponse * expireSession (const ExpireSessionRequest &request)
ListAssociatedFleetsResponse * listAssociatedFleets (const ListAssociatedFleetsRequest &request)
ListAssociatedStacksResponse * listAssociatedStacks (const ListAssociatedStacksRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
StartFleetResponse * startFleet (const StartFleetRequest &request)
StartImageBuilderResponse * startImageBuilder (const StartImageBuilderRequest &request)
StopFleetResponse * stopFleet (const StopFleetRequest &request)
StopImageBuilderResponse * stopImageBuilder (const StopImageBuilderRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateDirectoryConfigResponse * updateDirectoryConfig (const UpdateDirectoryConfigRequest &request)
UpdateFleetResponse * updateFleet (const UpdateFleetRequest &request)
UpdateStackResponse * updateStack (const UpdateStackRequest &request)
Public Member Functions
AppStreamClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AppStreamClient object.
AppStreamClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AppStreamClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon AppStream.
<fullname>Amazon AppStream 2.0</fullname>
You can use Amazon AppStream 2.0 to stream desktop applications to any device running a web browser, without rewriting
Definition at line 98 of file appstreamclient.h.
Constructor & Destructor Documentation
AppStreamClient() [1/2]
QtAws::AppStream::AppStreamClient::AppStreamClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AppStreamClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 115 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new AppStreamClientPrivate(this), parent)
 {
     Q_D(AppStreamClient);
     d->apiVersion = QStringLiteral("2016-12-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("appstream2");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon AppStream");
     d->serviceName = QStringLiteral("appstream");
 }
AppStreamClient() [2/2]
QtAws::AppStream::AppStreamClient::AppStreamClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AppStreamClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 148 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new AppStreamClientPrivate(this), parent)
 {
     Q_D(AppStreamClient);
     d->apiVersion = QStringLiteral("2016-12-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("appstream2");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon AppStream");
     d->serviceName = QStringLiteral("appstream");
 }
Member Function Documentation
associateFleet
AssociateFleetResponse * QtAws::AppStream::AppStreamClient::associateFleet (const AssociateFleetRequest & request) slot
Associates the specified fleet with the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 174 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateFleetResponse *>(send(request));
 }
copyImage
CopyImageResponse * QtAws::AppStream::AppStreamClient::copyImage (const CopyImageRequest & request) slot
Copies the image within the same region or to a new region within the same AWS account. Note that any tags you added to the image will not be
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 189 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyImageResponse *>(send(request));
 }
createDirectoryConfig
CreateDirectoryConfigResponse * QtAws::AppStream::AppStreamClient::createDirectoryConfig (const CreateDirectoryConfigRequest & request) slot
Creates a directory
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 203 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDirectoryConfigResponse *>(send(request));
 }
createFleet
CreateFleetResponse * QtAws::AppStream::AppStreamClient::createFleet (const CreateFleetRequest & request) slot
Creates a
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 217 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFleetResponse *>(send(request));
 }
createImageBuilder
CreateImageBuilderResponse * QtAws::AppStream::AppStreamClient::createImageBuilder (const CreateImageBuilderRequest & request) slot
Creates an image
builder>
The initial state of the builder is PENDING. When it is ready, the state is
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 235 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateImageBuilderResponse *>(send(request));
 }
createImageBuilderStreamingURL
CreateImageBuilderStreamingURLResponse * QtAws::AppStream::AppStreamClient::createImageBuilderStreamingURL (const CreateImageBuilderStreamingURLRequest & request) slot
Creates a URL to start an image builder streaming
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 249 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateImageBuilderStreamingURLResponse *>(send(request));
 }
createStack
CreateStackResponse * QtAws::AppStream::AppStreamClient::createStack (const CreateStackRequest & request) slot
Creates a
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 263 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStackResponse *>(send(request));
 }
createStreamingURL
CreateStreamingURLResponse * QtAws::AppStream::AppStreamClient::createStreamingURL (const CreateStreamingURLRequest & request) slot
Creates a URL to start a streaming session for the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 277 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStreamingURLResponse *>(send(request));
 }
deleteDirectoryConfig
DeleteDirectoryConfigResponse * QtAws::AppStream::AppStreamClient::deleteDirectoryConfig (const DeleteDirectoryConfigRequest & request) slot
Deletes the specified directory
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 291 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDirectoryConfigResponse *>(send(request));
 }
deleteFleet
DeleteFleetResponse * QtAws::AppStream::AppStreamClient::deleteFleet (const DeleteFleetRequest & request) slot
Deletes the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFleetResponse *>(send(request));
 }
deleteImage
DeleteImageResponse * QtAws::AppStream::AppStreamClient::deleteImage (const DeleteImageRequest & request) slot
Deletes the specified image. You cannot delete an image that is currently in use. After you delete an image, you cannot provision new capacity using the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 320 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteImageResponse *>(send(request));
 }
deleteImageBuilder
DeleteImageBuilderResponse * QtAws::AppStream::AppStreamClient::deleteImageBuilder (const DeleteImageBuilderRequest & request) slot
Deletes the specified image builder and releases the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteImageBuilderResponse *>(send(request));
 }
deleteStack
DeleteStackResponse * QtAws::AppStream::AppStreamClient::deleteStack (const DeleteStackRequest & request) slot
Deletes the specified stack. After this operation completes, the environment can no longer be activated and any reservations made for the stack are
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 349 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStackResponse *>(send(request));
 }
describeDirectoryConfigs
DescribeDirectoryConfigsResponse * QtAws::AppStream::AppStreamClient::describeDirectoryConfigs (const DescribeDirectoryConfigsRequest & request) slot
Describes the specified directory configurations. Note that although the response syntax in this topic includes the account password, this password is not returned in the actual response.
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 364 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDirectoryConfigsResponse *>(send(request));
 }
describeFleets
DescribeFleetsResponse * QtAws::AppStream::AppStreamClient::describeFleets (const DescribeFleetsRequest & request) slot
Describes the specified fleets or all fleets in the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFleetsResponse *>(send(request));
 }
describeImageBuilders
DescribeImageBuildersResponse * QtAws::AppStream::AppStreamClient::describeImageBuilders (const DescribeImageBuildersRequest & request) slot
Describes the specified image builders or all image builders in the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 392 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImageBuildersResponse *>(send(request));
 }
describeImages
DescribeImagesResponse * QtAws::AppStream::AppStreamClient::describeImages (const DescribeImagesRequest & request) slot
Describes the specified images or all images in the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImagesResponse *>(send(request));
 }
describeSessions
DescribeSessionsResponse * QtAws::AppStream::AppStreamClient::describeSessions (const DescribeSessionsRequest & request) slot
Describes the streaming sessions for the specified stack and fleet. If a user ID is provided, only the streaming sessions for only that user are returned. If an authentication type is not provided, the default is to authenticate users using a streaming
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 422 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSessionsResponse *>(send(request));
 }
describeStacks
DescribeStacksResponse * QtAws::AppStream::AppStreamClient::describeStacks (const DescribeStacksRequest & request) slot
Describes the specified stacks or all stacks in the
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 436 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStacksResponse *>(send(request));
 }
disassociateFleet
DisassociateFleetResponse * QtAws::AppStream::AppStreamClient::disassociateFleet (const DisassociateFleetRequest & request) slot
Disassociates the specified fleet from the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 450 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateFleetResponse *>(send(request));
 }
expireSession
ExpireSessionResponse * QtAws::AppStream::AppStreamClient::expireSession (const ExpireSessionRequest & request) slot
Stops the specified streaming
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 464 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExpireSessionResponse *>(send(request));
 }
listAssociatedFleets
ListAssociatedFleetsResponse * QtAws::AppStream::AppStreamClient::listAssociatedFleets (const ListAssociatedFleetsRequest & request) slot
Lists the fleets associated with the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 478 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAssociatedFleetsResponse *>(send(request));
 }
listAssociatedStacks
ListAssociatedStacksResponse * QtAws::AppStream::AppStreamClient::listAssociatedStacks (const ListAssociatedStacksRequest & request) slot
Lists the stacks associated with the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 492 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAssociatedStacksResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::AppStream::AppStreamClient::listTagsForResource (const ListTagsForResourceRequest & request) slot
Lists the tags for the specified AppStream 2.0 resource. You can tag AppStream 2.0 image builders, images, fleets, and
stacks>
For more information about tags, see Tagging Your Resources in the Amazon AppStream 2.0 Developer
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 512 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
startFleet
StartFleetResponse * QtAws::AppStream::AppStreamClient::startFleet (const StartFleetRequest & request) slot
Starts the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 526 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartFleetResponse *>(send(request));
 }
startImageBuilder
StartImageBuilderResponse * QtAws::AppStream::AppStreamClient::startImageBuilder (const StartImageBuilderRequest & request) slot
Starts the specified image
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 540 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartImageBuilderResponse *>(send(request));
 }
stopFleet
StopFleetResponse * QtAws::AppStream::AppStreamClient::stopFleet (const StopFleetRequest & request) slot
Stops the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 554 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopFleetResponse *>(send(request));
 }
stopImageBuilder
StopImageBuilderResponse * QtAws::AppStream::AppStreamClient::stopImageBuilder (const StopImageBuilderRequest & request) slot
Stops the specified image
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 568 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopImageBuilderResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::AppStream::AppStreamClient::tagResource (const TagResourceRequest & request) slot
Adds or overwrites one or more tags for the specified AppStream 2.0 resource. You can tag AppStream 2.0 image builders, images, fleets, and
stacks>
Each tag consists of a key and an optional value. If a resource already has a tag with the same key, this operation updates its
value>
To list the current tags for your resources, use ListTagsForResource. To disassociate tags from your resources, use
UntagResource>
For more information about tags, see Tagging Your Resources in the Amazon AppStream 2.0 Developer
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 599 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::AppStream::AppStreamClient::untagResource (const UntagResourceRequest & request) slot
Disassociates the specified tags from the specified AppStream 2.0
resource>
To list the current tags for your resources, use
ListTagsForResource>
For more information about tags, see Tagging Your Resources in the Amazon AppStream 2.0 Developer
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 623 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateDirectoryConfig
UpdateDirectoryConfigResponse * QtAws::AppStream::AppStreamClient::updateDirectoryConfig (const UpdateDirectoryConfigRequest & request) slot
Updates the specified directory
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 637 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDirectoryConfigResponse *>(send(request));
 }
updateFleet
UpdateFleetResponse * QtAws::AppStream::AppStreamClient::updateFleet (const UpdateFleetRequest & request) slot
Updates the specified
fleet>
If the fleet is in the STOPPED state, you can update any attribute except the fleet name. If the fleet is in the RUNNING state, you can update the DisplayName and ComputeCapacity attributes. If the fleet is in the STARTING or STOPPING state, you can't update
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 657 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFleetResponse *>(send(request));
 }
updateStack
UpdateStackResponse * QtAws::AppStream::AppStreamClient::updateStack (const UpdateStackRequest & request) slot
Updates the specified
Parameters
request Request to send to Amazon AppStream.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 671 of file appstreamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStackResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
appstream/appstreamclient.h
appstream/appstreamclient.cpp