AWS SDK for Qt: QtAws::CloudFormation::CloudFormationClient Class Reference
QtAws::CloudFormation::CloudFormationClient Class Reference
Client for AWS CloudFormation.
Public Slots
CancelUpdateStackResponse * cancelUpdateStack (const CancelUpdateStackRequest &request)
ContinueUpdateRollbackResponse * continueUpdateRollback (const ContinueUpdateRollbackRequest &request)
CreateChangeSetResponse * createChangeSet (const CreateChangeSetRequest &request)
CreateStackResponse * createStack (const CreateStackRequest &request)
CreateStackInstancesResponse * createStackInstances (const CreateStackInstancesRequest &request)
CreateStackSetResponse * createStackSet (const CreateStackSetRequest &request)
DeleteChangeSetResponse * deleteChangeSet (const DeleteChangeSetRequest &request)
DeleteStackResponse * deleteStack (const DeleteStackRequest &request)
DeleteStackInstancesResponse * deleteStackInstances (const DeleteStackInstancesRequest &request)
DeleteStackSetResponse * deleteStackSet (const DeleteStackSetRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits (const DescribeAccountLimitsRequest &request)
DescribeChangeSetResponse * describeChangeSet (const DescribeChangeSetRequest &request)
DescribeStackEventsResponse * describeStackEvents (const DescribeStackEventsRequest &request)
DescribeStackInstanceResponse * describeStackInstance (const DescribeStackInstanceRequest &request)
DescribeStackResourceResponse * describeStackResource (const DescribeStackResourceRequest &request)
DescribeStackResourcesResponse * describeStackResources (const DescribeStackResourcesRequest &request)
DescribeStackSetResponse * describeStackSet (const DescribeStackSetRequest &request)
DescribeStackSetOperationResponse * describeStackSetOperation (const DescribeStackSetOperationRequest &request)
DescribeStacksResponse * describeStacks (const DescribeStacksRequest &request)
EstimateTemplateCostResponse * estimateTemplateCost (const EstimateTemplateCostRequest &request)
ExecuteChangeSetResponse * executeChangeSet (const ExecuteChangeSetRequest &request)
GetStackPolicyResponse * getStackPolicy (const GetStackPolicyRequest &request)
GetTemplateResponse * getTemplate (const GetTemplateRequest &request)
GetTemplateSummaryResponse * getTemplateSummary (const GetTemplateSummaryRequest &request)
ListChangeSetsResponse * listChangeSets (const ListChangeSetsRequest &request)
ListExportsResponse * listExports (const ListExportsRequest &request)
ListImportsResponse * listImports (const ListImportsRequest &request)
ListStackInstancesResponse * listStackInstances (const ListStackInstancesRequest &request)
ListStackResourcesResponse * listStackResources (const ListStackResourcesRequest &request)
ListStackSetOperationResultsResponse * listStackSetOperationResults (const ListStackSetOperationResultsRequest &request)
ListStackSetOperationsResponse * listStackSetOperations (const ListStackSetOperationsRequest &request)
ListStackSetsResponse * listStackSets (const ListStackSetsRequest &request)
ListStacksResponse * listStacks (const ListStacksRequest &request)
SetStackPolicyResponse * setStackPolicy (const SetStackPolicyRequest &request)
SignalResourceResponse * signalResource (const SignalResourceRequest &request)
StopStackSetOperationResponse * stopStackSetOperation (const StopStackSetOperationRequest &request)
UpdateStackResponse * updateStack (const UpdateStackRequest &request)
UpdateStackInstancesResponse * updateStackInstances (const UpdateStackInstancesRequest &request)
UpdateStackSetResponse * updateStackSet (const UpdateStackSetRequest &request)
UpdateTerminationProtectionResponse * updateTerminationProtection (const UpdateTerminationProtectionRequest &request)
ValidateTemplateResponse * validateTemplate (const ValidateTemplateRequest &request)
Public Member Functions
CloudFormationClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFormationClient object.
CloudFormationClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFormationClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CloudFormation.
<fullname>AWS CloudFormation</fullname>
AWS CloudFormation allows you to create and manage AWS infrastructure deployments predictably and repeatedly. You can use AWS CloudFormation to leverage AWS products, such as Amazon Elastic Compute Cloud, Amazon Elastic Block Store, Amazon Simple Notification Service, Elastic Load Balancing, and Auto Scaling to build highly-reliable, highly scalable, cost-effective applications without creating or configuring the underlying AWS
infrastructure>
With AWS CloudFormation, you declare all of your resources and dependencies in a template file. The template defines a collection of resources as a single unit called a stack. AWS CloudFormation creates and deletes all member resources of the stack together and manages all dependencies between the resources for
you>
For more information about AWS CloudFormation, see the AWS CloudFormation Product Page>
Amazon CloudFormation makes use of other AWS products. If you need additional technical information about a specific AWS product, you can find the product's technical documentation at <a
Definition at line 114 of file cloudformationclient.h.
Constructor & Destructor Documentation
CloudFormationClient() [1/2]
QtAws::CloudFormation::CloudFormationClient::CloudFormationClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFormationClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 150 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudFormationClientPrivate(this), parent)
 {
     Q_D(CloudFormationClient);
     d->apiVersion = QStringLiteral("2010-05-15");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudformation");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CloudFormation");
     d->serviceName = QStringLiteral("cloudformation");
 }
CloudFormationClient() [2/2]
QtAws::CloudFormation::CloudFormationClient::CloudFormationClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFormationClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 183 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudFormationClientPrivate(this), parent)
 {
     Q_D(CloudFormationClient);
     d->apiVersion = QStringLiteral("2010-05-15");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudformation");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CloudFormation");
     d->serviceName = QStringLiteral("cloudformation");
 }
Member Function Documentation
cancelUpdateStack
CancelUpdateStackResponse * QtAws::CloudFormation::CloudFormationClient::cancelUpdateStack (const CancelUpdateStackRequest & request) slot
Cancels an update on the specified stack. If the call completes successfully, the stack rolls back the update and reverts to the previous stack
configuration> <note>
You can cancel only stacks that are in the UPDATE_IN_PROGRESS
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelUpdateStackResponse *>(send(request));
 }
continueUpdateRollback
ContinueUpdateRollbackResponse * QtAws::CloudFormation::CloudFormationClient::continueUpdateRollback (const ContinueUpdateRollbackRequest & request) slot
For a specified stack that is in the UPDATE_ROLLBACK_FAILED state, continues rolling it back to the UPDATE_ROLLBACK_COMPLETE state. Depending on the cause of the failure, you can manually fix the error and continue the rollback. By continuing the rollback, you can return your stack to a working state (the UPDATE_ROLLBACK_COMPLETE state), and then try to update the stack
again>
A stack goes into the UPDATE_ROLLBACK_FAILED state when AWS CloudFormation cannot roll back all changes after a failed stack update. For example, you might have a stack that is rolling back to an old database instance that was deleted outside of AWS CloudFormation. Because AWS CloudFormation doesn't know the database was deleted, it assumes that the database instance still exists and attempts to roll back to it, causing the update rollback to
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 239 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ContinueUpdateRollbackResponse *>(send(request));
 }
createChangeSet
CreateChangeSetResponse * QtAws::CloudFormation::CloudFormationClient::createChangeSet (const CreateChangeSetRequest & request) slot
Creates a list of changes that will be applied to a stack so that you can review the changes before executing them. You can create a change set for a stack that doesn't exist or an existing stack. If you create a change set for a stack that doesn't exist, the change set shows all of the resources that AWS CloudFormation will create. If you create a change set for an existing stack, AWS CloudFormation compares the stack's information with the information that you submit in the change set and lists the differences. Use change sets to understand which resources AWS CloudFormation will create or change, and how it will change resources in an existing stack, before you create or update a
stack>
To create a change set for a stack that doesn't exist, for the ChangeSetType parameter, specify CREATE. To create a change set for an existing stack, specify UPDATE for the ChangeSetType parameter. After the CreateChangeSet call successfully completes, AWS CloudFormation starts creating the change set. To check the status of the change set or to review it, use the DescribeChangeSet
action>
When you are satisfied with the changes the change set will make, execute the change set by using the ExecuteChangeSet action. AWS CloudFormation doesn't make changes until you execute the change
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 271 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateChangeSetResponse *>(send(request));
 }
createStack
CreateStackResponse * QtAws::CloudFormation::CloudFormationClient::createStack (const CreateStackRequest & request) slot
Creates a stack as specified in the template. After the call completes successfully, the stack creation starts. You can check the status of the stack via the DescribeStacks
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 286 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStackResponse *>(send(request));
 }
createStackInstances
CreateStackInstancesResponse * QtAws::CloudFormation::CloudFormationClient::createStackInstances (const CreateStackInstancesRequest & request) slot
Creates stack instances for the specified accounts, within the specified regions. A stack instance refers to a stack in a specific account and region. Accounts and Regions are required parametersyou must specify at least one account and one region.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 302 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStackInstancesResponse *>(send(request));
 }
createStackSet
CreateStackSetResponse * QtAws::CloudFormation::CloudFormationClient::createStackSet (const CreateStackSetRequest & request) slot
Creates a stack
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 316 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStackSetResponse *>(send(request));
 }
deleteChangeSet
DeleteChangeSetResponse * QtAws::CloudFormation::CloudFormationClient::deleteChangeSet (const DeleteChangeSetRequest & request) slot
Deletes the specified change set. Deleting change sets ensures that no one executes the wrong change
set>
If the call successfully completes, AWS CloudFormation successfully deleted the change
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteChangeSetResponse *>(send(request));
 }
deleteStack
DeleteStackResponse * QtAws::CloudFormation::CloudFormationClient::deleteStack (const DeleteStackRequest & request) slot
Deletes a specified stack. Once the call completes successfully, stack deletion starts. Deleted stacks do not show up in the DescribeStacks API if the deletion has been completed
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 349 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStackResponse *>(send(request));
 }
deleteStackInstances
DeleteStackInstancesResponse * QtAws::CloudFormation::CloudFormationClient::deleteStackInstances (const DeleteStackInstancesRequest & request) slot
Deletes stack instances for the specified accounts, in the specified regions.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 363 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStackInstancesResponse *>(send(request));
 }
deleteStackSet
DeleteStackSetResponse * QtAws::CloudFormation::CloudFormationClient::deleteStackSet (const DeleteStackSetRequest & request) slot
Deletes a stack set. Before you can delete a stack set, all of its member stack instances must be deleted. For more information about how to do this, see DeleteStackInstances.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStackSetResponse *>(send(request));
 }
describeAccountLimits
DescribeAccountLimitsResponse * QtAws::CloudFormation::CloudFormationClient::describeAccountLimits (const DescribeAccountLimitsRequest & request) slot
Retrieves your account's AWS CloudFormation limits, such as the maximum number of stacks that you can create in your
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 392 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountLimitsResponse *>(send(request));
 }
describeChangeSet
DescribeChangeSetResponse * QtAws::CloudFormation::CloudFormationClient::describeChangeSet (const DescribeChangeSetRequest & request) slot
Returns the inputs for the change set and a list of changes that AWS CloudFormation will make if you execute the change set. For more information, see Updating Stacks Using Change Sets in the AWS CloudFormation User
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeChangeSetResponse *>(send(request));
 }
describeStackEvents
DescribeStackEventsResponse * QtAws::CloudFormation::CloudFormationClient::describeStackEvents (const DescribeStackEventsRequest & request) slot
Returns all stack related events for a specified stack in reverse chronological order. For more information about a stack's event history, go to Stacks in the AWS CloudFormation User
Guide> <note>
You can list events for stacks that have failed to create or have been deleted by specifying the unique stack identifier (stack
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 431 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackEventsResponse *>(send(request));
 }
describeStackInstance
DescribeStackInstanceResponse * QtAws::CloudFormation::CloudFormationClient::describeStackInstance (const DescribeStackInstanceRequest & request) slot
Returns the stack instance that's associated with the specified stack set, AWS account, and
region>
For a list of stack instances that are associated with a specific stack set, use
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 449 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackInstanceResponse *>(send(request));
 }
describeStackResource
DescribeStackResourceResponse * QtAws::CloudFormation::CloudFormationClient::describeStackResource (const DescribeStackResourceRequest & request) slot
Returns a description of the specified resource in the specified
stack>
For deleted stacks, DescribeStackResource returns resource information for up to 90 days after the stack has been
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 467 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackResourceResponse *>(send(request));
 }
describeStackResources
DescribeStackResourcesResponse * QtAws::CloudFormation::CloudFormationClient::describeStackResources (const DescribeStackResourcesRequest & request) slot
Returns AWS resource descriptions for running and deleted stacks. If StackName is specified, all the associated resources that are part of the stack are returned. If PhysicalResourceId is specified, the associated resources of the stack that the resource belongs to are
returned> <note>
Only the first 100 resources will be returned. If your stack has more resources than this, you should use ListStackResources
instead> </note>
For deleted stacks, DescribeStackResources returns resource information for up to 90 days after the stack has been
deleted>
You must specify either StackName or PhysicalResourceId, but not both. In addition, you can specify LogicalResourceId to filter the returned result. For more information about resources, the LogicalResourceId and PhysicalResourceId, go to the AWS CloudFormation User Guide> <note>
A ValidationError is returned if you specify both StackName and PhysicalResourceId in the same
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 505 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackResourcesResponse *>(send(request));
 }
describeStacks
DescribeStacksResponse * QtAws::CloudFormation::CloudFormationClient::describeStacks (const DescribeStacksRequest & request) slot
Returns the description for the specified stack; if no stack name was specified, then it returns the description for all the stacks
created> <note>
If the stack does not exist, an AmazonCloudFormationException is
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 552 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStacksResponse *>(send(request));
 }
describeStackSet
DescribeStackSetResponse * QtAws::CloudFormation::CloudFormationClient::describeStackSet (const DescribeStackSetRequest & request) slot
Returns the description of the specified stack set.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 519 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackSetResponse *>(send(request));
 }
describeStackSetOperation
DescribeStackSetOperationResponse * QtAws::CloudFormation::CloudFormationClient::describeStackSetOperation (const DescribeStackSetOperationRequest & request) slot
Returns the description of the specified stack set operation.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 533 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackSetOperationResponse *>(send(request));
 }
estimateTemplateCost
EstimateTemplateCostResponse * QtAws::CloudFormation::CloudFormationClient::estimateTemplateCost (const EstimateTemplateCostRequest & request) slot
Returns the estimated monthly cost of a template. The return value is an AWS Simple Monthly Calculator URL with a query string that describes the resources required to run the
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 567 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EstimateTemplateCostResponse *>(send(request));
 }
executeChangeSet
ExecuteChangeSetResponse * QtAws::CloudFormation::CloudFormationClient::executeChangeSet (const ExecuteChangeSetRequest & request) slot
Updates a stack using the input information that was provided when the specified change set was created. After the call successfully completes, AWS CloudFormation starts updating the stack. Use the DescribeStacks action to view the status of the
update>
When you execute a change set, AWS CloudFormation deletes all other change sets associated with the stack because they aren't valid for the updated
stack>
If a stack policy is associated with the stack, AWS CloudFormation enforces the policy during the update. You can't specify a temporary stack policy that overrides the current
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 593 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExecuteChangeSetResponse *>(send(request));
 }
getStackPolicy
GetStackPolicyResponse * QtAws::CloudFormation::CloudFormationClient::getStackPolicy (const GetStackPolicyRequest & request) slot
Returns the stack policy for a specified stack. If a stack doesn't have a policy, a null value is
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 607 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStackPolicyResponse *>(send(request));
 }
getTemplate
GetTemplateResponse * QtAws::CloudFormation::CloudFormationClient::getTemplate (const GetTemplateRequest & request) slot
Returns the template body for a specified stack. You can get the template for running or deleted
stacks>
For deleted stacks, GetTemplate returns the template for up to 90 days after the stack has been
deleted> <note>
If the template does not exist, a ValidationError is returned.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 629 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTemplateResponse *>(send(request));
 }
getTemplateSummary
GetTemplateSummaryResponse * QtAws::CloudFormation::CloudFormationClient::getTemplateSummary (const GetTemplateSummaryRequest & request) slot
Returns information about a new or existing template. The GetTemplateSummary action is useful for viewing parameter information, such as default parameter values and parameter types, before you create or update a stack or stack
set>
You can use the GetTemplateSummary action when you submit a template, or you can get template information for a stack set, or a running or deleted
stack>
For deleted stacks, GetTemplateSummary returns the template information for up to 90 days after the stack has been deleted. If the template does not exist, a ValidationError is
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 655 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTemplateSummaryResponse *>(send(request));
 }
listChangeSets
ListChangeSetsResponse * QtAws::CloudFormation::CloudFormationClient::listChangeSets (const ListChangeSetsRequest & request) slot
Returns the ID and status of each active change set for a stack. For example, AWS CloudFormation lists change sets that are in the CREATE_IN_PROGRESS or CREATE_PENDING
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 670 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListChangeSetsResponse *>(send(request));
 }
listExports
ListExportsResponse * QtAws::CloudFormation::CloudFormationClient::listExports (const ListExportsRequest & request) slot
Lists all exported output values in the account and region in which you call this action. Use this action to see the exported output values that you can import into other stacks. To import values, use the Fn::ImportValue function.
</p
For more information, see AWS CloudFormation Export Stack Output request Request to send to AWS CloudFormation. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 693 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListExportsResponse *>(send(request));
 }
listImports
ListImportsResponse * QtAws::CloudFormation::CloudFormationClient::listImports (const ListImportsRequest & request) slot
Lists all stacks that are importing an exported output value. To modify or remove an exported output value, first use this action to see which stacks are using it. To see the exported output values in your account, see ListExports.
</p
For more information about importing an exported output value, see the Fn::ImportValue function.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 714 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListImportsResponse *>(send(request));
 }
listStackInstances
ListStackInstancesResponse * QtAws::CloudFormation::CloudFormationClient::listStackInstances (const ListStackInstancesRequest & request) slot
Returns summary information about stack instances that are associated with the specified stack set. You can filter for stack instances that are associated with a specific AWS account name or
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 729 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStackInstancesResponse *>(send(request));
 }
listStackResources
ListStackResourcesResponse * QtAws::CloudFormation::CloudFormationClient::listStackResources (const ListStackResourcesRequest & request) slot
Returns descriptions of all resources of the specified
stack>
For deleted stacks, ListStackResources returns resource information for up to 90 days after the stack has been
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 747 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStackResourcesResponse *>(send(request));
 }
listStacks
ListStacksResponse * QtAws::CloudFormation::CloudFormationClient::listStacks (const ListStacksRequest & request) slot
Returns the summary information for stacks whose status matches the specified StackStatusFilter. Summary information for stacks that have been deleted is kept for 90 days after the stack is deleted. If no StackStatusFilter is specified, summary information for all stacks is returned (including existing stacks and stacks that have been
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 805 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStacksResponse *>(send(request));
 }
listStackSetOperationResults
ListStackSetOperationResultsResponse * QtAws::CloudFormation::CloudFormationClient::listStackSetOperationResults (const ListStackSetOperationResultsRequest & request) slot
Returns summary information about the results of a stack set operation.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 761 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStackSetOperationResultsResponse *>(send(request));
 }
listStackSetOperations
ListStackSetOperationsResponse * QtAws::CloudFormation::CloudFormationClient::listStackSetOperations (const ListStackSetOperationsRequest & request) slot
Returns summary information about operations performed on a stack set.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 775 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStackSetOperationsResponse *>(send(request));
 }
listStackSets
ListStackSetsResponse * QtAws::CloudFormation::CloudFormationClient::listStackSets (const ListStackSetsRequest & request) slot
Returns summary information about stack sets that are associated with the
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 789 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStackSetsResponse *>(send(request));
 }
setStackPolicy
SetStackPolicyResponse * QtAws::CloudFormation::CloudFormationClient::setStackPolicy (const SetStackPolicyRequest & request) slot
Sets a stack policy for a specified
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 819 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetStackPolicyResponse *>(send(request));
 }
signalResource
SignalResourceResponse * QtAws::CloudFormation::CloudFormationClient::signalResource (const SignalResourceRequest & request) slot
Sends a signal to the specified resource with a success or failure status. You can use the SignalResource API in conjunction with a creation policy or update policy. AWS CloudFormation doesn't proceed with a stack creation or update until resources receive the required number of signals or the timeout period is exceeded. The SignalResource API is useful in cases where you want to send signals from anywhere other than an Amazon EC2
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 836 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SignalResourceResponse *>(send(request));
 }
stopStackSetOperation
StopStackSetOperationResponse * QtAws::CloudFormation::CloudFormationClient::stopStackSetOperation (const StopStackSetOperationRequest & request) slot
Stops an in-progress operation on a stack set and its associated stack instances.
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 850 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopStackSetOperationResponse *>(send(request));
 }
updateStack
UpdateStackResponse * QtAws::CloudFormation::CloudFormationClient::updateStack (const UpdateStackRequest & request) slot
Updates a stack as specified in the template. After the call completes successfully, the stack update starts. You can check the status of the stack via the DescribeStacks
action>
To get a copy of the template for an existing stack, you can use the GetTemplate
action>
For more information about creating an update template, updating a stack, and monitoring the progress of the update, see Updating a request Request to send to AWS CloudFormation. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 874 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStackResponse *>(send(request));
 }
updateStackInstances
UpdateStackInstancesResponse * QtAws::CloudFormation::CloudFormationClient::updateStackInstances (const UpdateStackInstancesRequest & request) slot
Updates the parameter values for stack instances for the specified accounts, within the specified regions. A stack instance refers to a stack in a specific account and region.
</p
You can only update stack instances in regions and accounts where they already exist; to create additional stack instances, use CreateStackInstances.
</p
During stack set updates, any parameters overridden for a stack instance are not updated, but retain their overridden
value>
You can only update the parameter values that are specified in the stack set; to add or delete a parameter itself, use UpdateStackSet to update the stack set template. If you add a parameter to a template, before you can override the parameter value specified in the stack set you must first use UpdateStackSet to update all stack instances with the updated template and parameter value specified in the stack set. Once a stack instance has been updated with the new parameter, you can then override the parameter value using
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 910 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStackInstancesResponse *>(send(request));
 }
updateStackSet
UpdateStackSetResponse * QtAws::CloudFormation::CloudFormationClient::updateStackSet (const UpdateStackSetRequest & request) slot
Updates the stack set and all associated stack
instances>
Even if the stack set operation created by updating the stack set fails (completely or partially, below or above a specified failure tolerance), the stack set is updated with your changes. Subsequent CreateStackInstances calls on the specified stack set use the updated stack
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 930 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStackSetResponse *>(send(request));
 }
updateTerminationProtection
UpdateTerminationProtectionResponse * QtAws::CloudFormation::CloudFormationClient::updateTerminationProtection (const UpdateTerminationProtectionRequest & request) slot
Updates termination protection for the specified stack. If a user attempts to delete a stack with termination protection enabled, the operation fails and the stack remains unchanged. For more information, see Protecting a Stack From Being Deleted in the AWS CloudFormation User
Guide>
For nested stacks, termination protection is set on the root stack and cannot be changed directly on the nested
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 952 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTerminationProtectionResponse *>(send(request));
 }
validateTemplate
ValidateTemplateResponse * QtAws::CloudFormation::CloudFormationClient::validateTemplate (const ValidateTemplateRequest & request) slot
Validates a specified template. AWS CloudFormation first checks if the template is valid JSON. If it isn't, AWS CloudFormation checks if the template is valid YAML. If both these checks fail, AWS CloudFormation returns a template validation
Parameters
request Request to send to AWS CloudFormation.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 968 of file cloudformationclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ValidateTemplateResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudformation/cloudformationclient.h
cloudformation/cloudformationclient.cpp