AWS SDK for Qt: QtAws::Support::SupportClient Class Reference
QtAws::Support::SupportClient Class Reference
Client for AWS Support.
Public Slots
AddAttachmentsToSetResponse * addAttachmentsToSet (const AddAttachmentsToSetRequest &request)
AddCommunicationToCaseResponse * addCommunicationToCase (const AddCommunicationToCaseRequest &request)
CreateCaseResponse * createCase (const CreateCaseRequest &request)
DescribeAttachmentResponse * describeAttachment (const DescribeAttachmentRequest &request)
DescribeCasesResponse * describeCases (const DescribeCasesRequest &request)
DescribeCommunicationsResponse * describeCommunications (const DescribeCommunicationsRequest &request)
DescribeServicesResponse * describeServices (const DescribeServicesRequest &request)
DescribeSeverityLevelsResponse * describeSeverityLevels (const DescribeSeverityLevelsRequest &request)
DescribeTrustedAdvisorCheckRefreshStatusesResponse * describeTrustedAdvisorCheckRefreshStatuses (const DescribeTrustedAdvisorCheckRefreshStatusesRequest &request)
DescribeTrustedAdvisorCheckResultResponse * describeTrustedAdvisorCheckResult (const DescribeTrustedAdvisorCheckResultRequest &request)
DescribeTrustedAdvisorCheckSummariesResponse * describeTrustedAdvisorCheckSummaries (const DescribeTrustedAdvisorCheckSummariesRequest &request)
DescribeTrustedAdvisorChecksResponse * describeTrustedAdvisorChecks (const DescribeTrustedAdvisorChecksRequest &request)
RefreshTrustedAdvisorCheckResponse * refreshTrustedAdvisorCheck (const RefreshTrustedAdvisorCheckRequest &request)
ResolveCaseResponse * resolveCase (const ResolveCaseRequest &request)
Public Member Functions
SupportClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SupportClient object.
SupportClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SupportClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Support.
<fullname>AWS Support</fullname>
The AWS Support API reference is intended for programmers who need detailed information about the AWS Support operations and data types. This service enables you to manage your AWS Support cases programmatically. It uses HTTP methods that return results in JSON
format>
The AWS Support service also exposes a set of Trusted Advisor features. You can retrieve a list of checks and their descriptions, get check results, specify checks to refresh, and get the refresh status of checks.
Service names, issue categories, and available severity levels. The DescribeServices and DescribeSeverityLevels operations return AWS service names, service codes, service categories, and problem severity levels. You use these values when you call the CreateCase operation.
</p
Case creation, case details, and case resolution. The CreateCase, DescribeCases, DescribeAttachment, and ResolveCase operations create AWS Support cases, retrieve information about cases, and resolve
cases>
Case communication. The DescribeCommunications, AddCommunicationToCase, and AddAttachmentsToSet operations retrieve and add communications and attachments to AWS Support cases.
</p
The following list describes the operations available from the AWS Support service for Trusted
Advisor>
DescribeTrustedAdvisorChecks returns the list of checks that run against your AWS
resources>
Using the checkId for a specific check returned by DescribeTrustedAdvisorChecks, you can call DescribeTrustedAdvisorCheckResult to obtain the results for the check you
specified>
DescribeTrustedAdvisorCheckSummaries returns summarized results for one or more Trusted Advisor
checks>
RefreshTrustedAdvisorCheck requests that Trusted Advisor rerun a specified check.
</p
DescribeTrustedAdvisorCheckRefreshStatuses reports the refresh status of one or more checks.
</p
For authentication of requests, AWS Support uses Signature Version 4 Signing Process>
See About the AWS Support API in the AWS Support User Guide for information about how to use this service to create and manage your support cases, and how to call Trusted Advisor for results of checks on your resources.
Definition at line 60 of file supportclient.h.
Constructor & Destructor Documentation
SupportClient() [1/2]
QtAws::Support::SupportClient::SupportClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SupportClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 142 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SupportClientPrivate(this), parent)
 {
     Q_D(SupportClient);
     d->apiVersion = QStringLiteral("2013-04-15");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("support");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Support");
     d->serviceName = QStringLiteral("support");
 }
SupportClient() [2/2]
QtAws::Support::SupportClient::SupportClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SupportClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 175 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SupportClientPrivate(this), parent)
 {
     Q_D(SupportClient);
     d->apiVersion = QStringLiteral("2013-04-15");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("support");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Support");
     d->serviceName = QStringLiteral("support");
 }
Member Function Documentation
addAttachmentsToSet
AddAttachmentsToSetResponse * QtAws::Support::SupportClient::addAttachmentsToSet (const AddAttachmentsToSetRequest & request) slot
Adds one or more attachments to an attachment set. If an attachmentSetId is not specified, a new attachment set is created, and the ID of the set is returned in the response. If an attachmentSetId is specified, the attachments are added to the specified set, if it
exists>
An attachment set is a temporary container for attachments that are to be added to a case or case communication. The set is available for one hour after it is created; the expiryTime returned in the response indicates when the set expires. The maximum number of attachments in a set is 3, and the maximum size of any attachment in the set is 5
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 209 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddAttachmentsToSetResponse *>(send(request));
 }
addCommunicationToCase
AddCommunicationToCaseResponse * QtAws::Support::SupportClient::addCommunicationToCase (const AddCommunicationToCaseRequest & request) slot
Adds additional customer communication to an AWS Support case. You use the caseId value to identify the case to add communication to. You can list a set of email addresses to copy on the communication using the ccEmailAddresses value. The communicationBody value contains the text of the
communication>
The response indicates the success or failure of the
request>
This operation implements a subset of the features of the AWS Support
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 233 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddCommunicationToCaseResponse *>(send(request));
 }
createCase
CreateCaseResponse * QtAws::Support::SupportClient::createCase (const CreateCaseRequest & request) slot
Creates a new case in the AWS Support Center. This operation is modeled on the behavior of the AWS Support Center Create Case page. Its parameters require you to specify the following information:
</p
issueType. The type of issue for the case. You can specify either "customer-service" or "technical." If you do not indicate a value, the default is "technical."
</p
serviceCode. The code for an AWS service. You obtain the serviceCode by calling DescribeServices.
</p
categoryCode. The category for the service defined for the serviceCode value. You also obtain the category code for a service by calling DescribeServices. Each AWS service defines its own set of category codes.
</p
severityCode. A value that indicates the urgency of the case, which in turn determines the response time according to your service level agreement with AWS Support. You obtain the SeverityCode by calling
DescribeSeverityLevels>
subject. The Subject field on the AWS Support Center Create Case
page>
communicationBody. The Description field on the AWS Support Center Create Case
page>
attachmentSetId. The ID of a set of attachments that has been created by using
AddAttachmentsToSet>
language. The human language in which AWS Support handles the case. English and Japanese are currently
supported>
ccEmailAddresses. The AWS Support Center CC field on the Create Case page. You can list email addresses to be copied on any correspondence about the case. The account that opens the case is already identified by passing the AWS Credentials in the HTTP POST method or in a method or function call from one of the programming languages supported by an AWS SDK.
</p
<note>
To add additional communication or attachments to an existing case, use
AddCommunicationToCase> </note>
A successful CreateCase request returns an AWS Support case number. Case numbers are used by the DescribeCases operation to retrieve existing AWS Support cases.
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 304 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCaseResponse *>(send(request));
 }
describeAttachment
DescribeAttachmentResponse * QtAws::Support::SupportClient::describeAttachment (const DescribeAttachmentRequest & request) slot
Returns the attachment that has the specified ID. Attachment IDs are generated by the case management system when you add an attachment to a case or case communication. Attachment IDs are returned in the AttachmentDetails objects that are returned by the DescribeCommunications
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 320 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAttachmentResponse *>(send(request));
 }
describeCases
DescribeCasesResponse * QtAws::Support::SupportClient::describeCases (const DescribeCasesRequest & request) slot
Returns a list of cases that you specify by passing one or more case IDs. In addition, you can filter the cases by date by setting values for the afterTime and beforeTime request parameters. You can set values for the includeResolvedCases and includeCommunications request parameters to control how much information is returned.
</p
Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request for data might cause an
error>
The response returns the following in JSON
format>
One or more CaseDetails data types.
</p
One or more nextToken values, which specify where to paginate the returned records represented by the CaseDetails
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 355 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCasesResponse *>(send(request));
 }
describeCommunications
DescribeCommunicationsResponse * QtAws::Support::SupportClient::describeCommunications (const DescribeCommunicationsRequest & request) slot
Returns communications (and attachments) for one or more support cases. You can use the afterTime and beforeTime parameters to filter by date. You can use the caseId parameter to restrict the results to a particular
case>
Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request for data might cause an
error>
You can use the maxResults and nextToken parameters to control the pagination of the result set. Set maxResults to the number of cases you want displayed on each page, and use nextToken to specify the resumption of
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 382 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCommunicationsResponse *>(send(request));
 }
describeServices
DescribeServicesResponse * QtAws::Support::SupportClient::describeServices (const DescribeServicesRequest & request) slot
Returns the current list of AWS services and a list of service categories that applies to each one. You then use service names and categories in your CreateCase requests. Each AWS service has its own set of
categories>
The service codes and category codes correspond to the values that are displayed in the Service and Category drop-down lists on the AWS Support Center Create Case page. The values in those fields, however, do not necessarily match the service codes and categories returned by the DescribeServices request. Always use the service codes and categories obtained programmatically. This practice ensures that you always have the most recent set of service and category
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeServicesResponse *>(send(request));
 }
describeSeverityLevels
DescribeSeverityLevelsResponse * QtAws::Support::SupportClient::describeSeverityLevels (const DescribeSeverityLevelsRequest & request) slot
Returns the list of severity levels that you can assign to an AWS Support case. The severity level for a case is also a field in the CaseDetails data type included in any CreateCase request.
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 421 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSeverityLevelsResponse *>(send(request));
 }
describeTrustedAdvisorCheckRefreshStatuses
DescribeTrustedAdvisorCheckRefreshStatusesResponse * QtAws::Support::SupportClient::describeTrustedAdvisorCheckRefreshStatuses (const DescribeTrustedAdvisorCheckRefreshStatusesRequest & request) slot
Returns the refresh status of the Trusted Advisor checks that have the specified check IDs. Check IDs can be obtained by calling
DescribeTrustedAdvisorChecks> <note>
Some checks are refreshed automatically, and their refresh statuses cannot be retrieved by using this operation. Use of the DescribeTrustedAdvisorCheckRefreshStatuses operation for these checks causes an InvalidParameterValue
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 442 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTrustedAdvisorCheckRefreshStatusesResponse *>(send(request));
 }
describeTrustedAdvisorCheckResult
DescribeTrustedAdvisorCheckResultResponse * QtAws::Support::SupportClient::describeTrustedAdvisorCheckResult (const DescribeTrustedAdvisorCheckResultRequest & request) slot
Returns the results of the Trusted Advisor check that has the specified check ID. Check IDs can be obtained by calling
DescribeTrustedAdvisorChecks>
The response contains a TrustedAdvisorCheckResult object, which contains these three
objects>
TrustedAdvisorCategorySpecificSummary
</p
TrustedAdvisorResourceDetail
</p
TrustedAdvisorResourcesSummary
</p
In addition, the response contains these
fields>
status. The alert status of the check: "ok" (green), "warning" (yellow), "error" (red), or
"not_available">
timestamp. The time of the last refresh of the
check>
checkId. The unique identifier for the
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 488 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTrustedAdvisorCheckResultResponse *>(send(request));
 }
describeTrustedAdvisorChecks
DescribeTrustedAdvisorChecksResponse * QtAws::Support::SupportClient::describeTrustedAdvisorChecks (const DescribeTrustedAdvisorChecksRequest & request) slot
Returns information about all available Trusted Advisor checks, including name, ID, category, description, and metadata. You must specify a language code; English ("en") and Japanese ("ja") are currently supported. The response contains a TrustedAdvisorCheckDescription for each
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 523 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTrustedAdvisorChecksResponse *>(send(request));
 }
describeTrustedAdvisorCheckSummaries
DescribeTrustedAdvisorCheckSummariesResponse * QtAws::Support::SupportClient::describeTrustedAdvisorCheckSummaries (const DescribeTrustedAdvisorCheckSummariesRequest & request) slot
Returns the summaries of the results of the Trusted Advisor checks that have the specified check IDs. Check IDs can be obtained by calling
DescribeTrustedAdvisorChecks>
The response contains an array of TrustedAdvisorCheckSummary
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 507 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTrustedAdvisorCheckSummariesResponse *>(send(request));
 }
refreshTrustedAdvisorCheck
RefreshTrustedAdvisorCheckResponse * QtAws::Support::SupportClient::refreshTrustedAdvisorCheck (const RefreshTrustedAdvisorCheckRequest & request) slot
Requests a refresh of the Trusted Advisor check that has the specified check ID. Check IDs can be obtained by calling
DescribeTrustedAdvisorChecks> <note>
Some checks are refreshed automatically, and they cannot be refreshed by using this operation. Use of the RefreshTrustedAdvisorCheck operation for these checks causes an InvalidParameterValue
error> </note>
The response contains a TrustedAdvisorCheckRefreshStatus object, which contains these
fields>
status. The refresh status of the check: "none", "enqueued", "processing", "success", or
"abandoned">
millisUntilNextRefreshable. The amount of time, in milliseconds, until the check is eligible for
refresh>
checkId. The unique identifier for the
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 558 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RefreshTrustedAdvisorCheckResponse *>(send(request));
 }
resolveCase
ResolveCaseResponse * QtAws::Support::SupportClient::resolveCase (const ResolveCaseRequest & request) slot
Takes a caseId and returns the initial state of the case along with the state of the case after the call to ResolveCase
Parameters
request Request to send to AWS Support.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 573 of file supportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResolveCaseResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
support/supportclient.h
support/supportclient.cpp