AWS SDK for Qt: QtAws::MTurk::MTurkClient Class Reference
QtAws::MTurk::MTurkClient Class Reference
Client for Amazon Mechanical Turk (MTurk)
Public Slots
AcceptQualificationRequestResponse * acceptQualificationRequest (const AcceptQualificationRequestRequest &request)
ApproveAssignmentResponse * approveAssignment (const ApproveAssignmentRequest &request)
AssociateQualificationWithWorkerResponse * associateQualificationWithWorker (const AssociateQualificationWithWorkerRequest &request)
CreateAdditionalAssignmentsForHITResponse * createAdditionalAssignmentsForHIT (const CreateAdditionalAssignmentsForHITRequest &request)
CreateHITResponse * createHIT (const CreateHITRequest &request)
CreateHITTypeResponse * createHITType (const CreateHITTypeRequest &request)
CreateHITWithHITTypeResponse * createHITWithHITType (const CreateHITWithHITTypeRequest &request)
CreateQualificationTypeResponse * createQualificationType (const CreateQualificationTypeRequest &request)
CreateWorkerBlockResponse * createWorkerBlock (const CreateWorkerBlockRequest &request)
DeleteHITResponse * deleteHIT (const DeleteHITRequest &request)
DeleteQualificationTypeResponse * deleteQualificationType (const DeleteQualificationTypeRequest &request)
DeleteWorkerBlockResponse * deleteWorkerBlock (const DeleteWorkerBlockRequest &request)
DisassociateQualificationFromWorkerResponse * disassociateQualificationFromWorker (const DisassociateQualificationFromWorkerRequest &request)
GetAccountBalanceResponse * getAccountBalance (const GetAccountBalanceRequest &request)
GetAssignmentResponse * getAssignment (const GetAssignmentRequest &request)
GetFileUploadURLResponse * getFileUploadURL (const GetFileUploadURLRequest &request)
GetHITResponse * getHIT (const GetHITRequest &request)
GetQualificationScoreResponse * getQualificationScore (const GetQualificationScoreRequest &request)
GetQualificationTypeResponse * getQualificationType (const GetQualificationTypeRequest &request)
ListAssignmentsForHITResponse * listAssignmentsForHIT (const ListAssignmentsForHITRequest &request)
ListBonusPaymentsResponse * listBonusPayments (const ListBonusPaymentsRequest &request)
ListHITsResponse * listHITs (const ListHITsRequest &request)
ListHITsForQualificationTypeResponse * listHITsForQualificationType (const ListHITsForQualificationTypeRequest &request)
ListQualificationRequestsResponse * listQualificationRequests (const ListQualificationRequestsRequest &request)
ListQualificationTypesResponse * listQualificationTypes (const ListQualificationTypesRequest &request)
ListReviewPolicyResultsForHITResponse * listReviewPolicyResultsForHIT (const ListReviewPolicyResultsForHITRequest &request)
ListReviewableHITsResponse * listReviewableHITs (const ListReviewableHITsRequest &request)
ListWorkerBlocksResponse * listWorkerBlocks (const ListWorkerBlocksRequest &request)
ListWorkersWithQualificationTypeResponse * listWorkersWithQualificationType (const ListWorkersWithQualificationTypeRequest &request)
NotifyWorkersResponse * notifyWorkers (const NotifyWorkersRequest &request)
RejectAssignmentResponse * rejectAssignment (const RejectAssignmentRequest &request)
RejectQualificationRequestResponse * rejectQualificationRequest (const RejectQualificationRequestRequest &request)
SendBonusResponse * sendBonus (const SendBonusRequest &request)
SendTestEventNotificationResponse * sendTestEventNotification (const SendTestEventNotificationRequest &request)
UpdateExpirationForHITResponse * updateExpirationForHIT (const UpdateExpirationForHITRequest &request)
UpdateHITReviewStatusResponse * updateHITReviewStatus (const UpdateHITReviewStatusRequest &request)
UpdateHITTypeOfHITResponse * updateHITTypeOfHIT (const UpdateHITTypeOfHITRequest &request)
UpdateNotificationSettingsResponse * updateNotificationSettings (const UpdateNotificationSettingsRequest &request)
UpdateQualificationTypeResponse * updateQualificationType (const UpdateQualificationTypeRequest &request)
Public Member Functions
MTurkClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MTurkClient object.
MTurkClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MTurkClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Mechanical Turk (MTurk)
Definition at line 110 of file mturkclient.h.
Constructor & Destructor Documentation
MTurkClient() [1/2]
QtAws::MTurk::MTurkClient::MTurkClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MTurkClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 124 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MTurkClientPrivate(this), parent)
 {
     Q_D(MTurkClient);
     d->apiVersion = QStringLiteral("2017-01-17");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("mturk-requester");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Mechanical Turk");
     d->serviceName = QStringLiteral("mturk-requester");
 }
MTurkClient() [2/2]
QtAws::MTurk::MTurkClient::MTurkClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MTurkClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 157 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MTurkClientPrivate(this), parent)
 {
     Q_D(MTurkClient);
     d->apiVersion = QStringLiteral("2017-01-17");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("mturk-requester");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Mechanical Turk");
     d->serviceName = QStringLiteral("mturk-requester");
 }
Member Function Documentation
acceptQualificationRequest
AcceptQualificationRequestResponse * QtAws::MTurk::MTurkClient::acceptQualificationRequest (const AcceptQualificationRequestRequest & request) slot
The AcceptQualificationRequest operation approves a Worker's request for a Qualification.
</p
Only the owner of the Qualification type can grant a Qualification request for that type.
</p
A successful request for the AcceptQualificationRequest operation returns with no errors and an empty body.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 191 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcceptQualificationRequestResponse *>(send(request));
 }
approveAssignment
ApproveAssignmentResponse * QtAws::MTurk::MTurkClient::approveAssignment (const ApproveAssignmentRequest & request) slot
The ApproveAssignment operation approves the results of a completed assignment.
</p
Approving an assignment initiates two payments from the Requester's Amazon.com account
</p
The Worker who submitted the results is paid the reward specified in the HIT.
</p
Amazon Mechanical Turk fees are debited.
</p
If the Requester's account does not have adequate funds for these payments, the call to ApproveAssignment returns an exception, and the approval is not processed. You can include an optional feedback message with the approval, which the Worker can see in the Status section of the web site.
</p
You can also call this operation for assignments that were previous rejected and approve them by explicitly overriding the previous rejection. This only works on rejected assignments that were submitted within the previous 30 days and only if the assignment's related HIT has not been deleted.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 229 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ApproveAssignmentResponse *>(send(request));
 }
associateQualificationWithWorker
AssociateQualificationWithWorkerResponse * QtAws::MTurk::MTurkClient::associateQualificationWithWorker (const AssociateQualificationWithWorkerRequest & request) slot
The AssociateQualificationWithWorker operation gives a Worker a Qualification. AssociateQualificationWithWorker does not require that the Worker submit a Qualification request. It gives the Qualification directly to the Worker.
</p
You can only assign a Qualification of a Qualification type that you created (using the CreateQualificationType operation).
</p <note>
Note: AssociateQualificationWithWorker does not affect any pending Qualification requests for the Qualification by the Worker. If you assign a Qualification to a Worker, then later grant a Qualification request made by the Worker, the granting of the request may modify the Qualification score. To resolve a pending Qualification request without affecting the Qualification the Worker already has, reject the request with the RejectQualificationRequest operation.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 258 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateQualificationWithWorkerResponse *>(send(request));
 }
createAdditionalAssignmentsForHIT
CreateAdditionalAssignmentsForHITResponse * QtAws::MTurk::MTurkClient::createAdditionalAssignmentsForHIT (const CreateAdditionalAssignmentsForHITRequest & request) slot
The CreateAdditionalAssignmentsForHIT operation increases the maximum number of assignments of an existing HIT.
</p
To extend the maximum number of assignments, specify the number of additional
assignments> <note>
HITs created with fewer than 10 assignments cannot be extended to have 10 or more assignments. Attempting to add assignments in a way that brings the total number of assignments for a HIT from fewer than 10 assignments to 10 or more assignments will result in an AWS.MechanicalTurk.InvalidMaximumAssignmentsIncrease
exception>
HITs that were created before July 22, 2015 cannot be extended. Attempting to extend HITs that were created before July 22, 2015 will result in an AWS.MechanicalTurk.HITTooOldForExtension exception.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 288 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAdditionalAssignmentsForHITResponse *>(send(request));
 }
createHIT
CreateHITResponse * QtAws::MTurk::MTurkClient::createHIT (const CreateHITRequest & request) slot
The CreateHIT operation creates a new Human Intelligence Task (HIT). The new HIT is made available for Workers to find and accept on the Amazon Mechanical Turk website.
</p
This operation allows you to specify a new HIT by passing in values for the properties of the HIT, such as its title, reward amount and number of assignments. When you pass these values to CreateHIT, a new HIT is created for you, with a new HITTypeID. The HITTypeID can be used to create additional HITs in the future without needing to specify common parameters such as the title, description and reward amount each
time>
An alternative way to create HITs is to first generate a HITTypeID using the CreateHITType operation and then call the CreateHITWithHITType operation. This is the recommended best practice for Requesters who are creating large numbers of HITs.
</p
CreateHIT also supports several ways to provide question data: by providing a value for the Question parameter that fully specifies the contents of the HIT, or by providing a HitLayoutId and associated HitLayoutParameters.
</p <note>
If a HIT is created with 10 or more maximum assignments, there is an additional fee. For more information, see Amazon Mechanical Turk request Request to send to Amazon Mechanical Turk. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 327 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHITResponse *>(send(request));
 }
createHITType
CreateHITTypeResponse * QtAws::MTurk::MTurkClient::createHITType (const CreateHITTypeRequest & request) slot
The CreateHITType operation creates a new HIT type. This operation allows you to define a standard set of HIT properties to use when creating HITs. If you register a HIT type with values that match an existing HIT type, the HIT type ID of the existing type will be returned.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 343 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHITTypeResponse *>(send(request));
 }
createHITWithHITType
CreateHITWithHITTypeResponse * QtAws::MTurk::MTurkClient::createHITWithHITType (const CreateHITWithHITTypeRequest & request) slot
The CreateHITWithHITType operation creates a new Human Intelligence Task (HIT) using an existing HITTypeID generated by the CreateHITType operation.
</p
This is an alternative way to create HITs from the CreateHIT operation. This is the recommended best practice for Requesters who are creating large numbers of HITs.
</p
CreateHITWithHITType also supports several ways to provide question data: by providing a value for the Question parameter that fully specifies the contents of the HIT, or by providing a HitLayoutId and associated HitLayoutParameters.
</p <note>
If a HIT is created with 10 or more maximum assignments, there is an additional fee. For more information, see Amazon Mechanical Turk Pricing.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 374 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHITWithHITTypeResponse *>(send(request));
 }
createQualificationType
CreateQualificationTypeResponse * QtAws::MTurk::MTurkClient::createQualificationType (const CreateQualificationTypeRequest & request) slot
The CreateQualificationType operation creates a new Qualification type, which is represented by a QualificationType data structure.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 389 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateQualificationTypeResponse *>(send(request));
 }
createWorkerBlock
CreateWorkerBlockResponse * QtAws::MTurk::MTurkClient::createWorkerBlock (const CreateWorkerBlockRequest & request) slot
The CreateWorkerBlock operation allows you to prevent a Worker from working on your HITs. For example, you can block a Worker who is producing poor quality work. You can block up to 100,000
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 404 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateWorkerBlockResponse *>(send(request));
 }
deleteHIT
DeleteHITResponse * QtAws::MTurk::MTurkClient::deleteHIT (const DeleteHITRequest & request) slot
The DeleteHIT operation is used to delete HIT that is no longer needed. Only the Requester who created the HIT can delete it.
</p
You can only dispose of HITs that are in the Reviewable state, with all of their submitted assignments already either approved or rejected. If you call the DeleteHIT operation on a HIT that is not in the Reviewable state (for example, that has not expired, or still has active assignments), or on a HIT that is Reviewable but without all of its submitted assignments already approved or rejected, the service will return an error.
</p <note>
HITs are automatically disposed of after 120 days.
</p
After you dispose of a HIT, you can no longer approve the HIT's rejected assignments.
</p
Disposed HITs are not returned in results for the ListHITs operation.
</p
Disposing HITs can improve the performance of operations such as ListReviewableHITs and ListHITs.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 442 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHITResponse *>(send(request));
 }
deleteQualificationType
DeleteQualificationTypeResponse * QtAws::MTurk::MTurkClient::deleteQualificationType (const DeleteQualificationTypeRequest & request) slot
The DeleteQualificationType deletes a Qualification type and deletes any HIT types that are associated with the Qualification type.
</p
This operation does not revoke Qualifications already assigned to Workers because the Qualifications might be needed for active HITs. If there are any pending requests for the Qualification type, Amazon Mechanical Turk rejects those requests. After you delete a Qualification type, you can no longer use it to create HITs or HIT
types> <note>
DeleteQualificationType must wait for all the HITs that use the deleted Qualification type to be deleted before completing. It may take up to 48 hours before DeleteQualificationType completes and the unique name of the Qualification type is available for reuse with
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 469 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteQualificationTypeResponse *>(send(request));
 }
deleteWorkerBlock
DeleteWorkerBlockResponse * QtAws::MTurk::MTurkClient::deleteWorkerBlock (const DeleteWorkerBlockRequest & request) slot
The DeleteWorkerBlock operation allows you to reinstate a blocked Worker to work on your HITs. This operation reverses the effects of the CreateWorkerBlock operation. You need the Worker ID to use this operation. If the Worker ID is missing or invalid, this operation fails and returns the message WorkerId is invalid. If the specified Worker is not blocked, this operation returns
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 486 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteWorkerBlockResponse *>(send(request));
 }
disassociateQualificationFromWorker
DisassociateQualificationFromWorkerResponse * QtAws::MTurk::MTurkClient::disassociateQualificationFromWorker (const DisassociateQualificationFromWorkerRequest & request) slot
The DisassociateQualificationFromWorker revokes a previously granted Qualification from a user.
</p
You can provide a text message explaining why the Qualification was revoked. The user who had the Qualification can see this message.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 505 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateQualificationFromWorkerResponse *>(send(request));
 }
getAccountBalance
GetAccountBalanceResponse * QtAws::MTurk::MTurkClient::getAccountBalance (const GetAccountBalanceRequest & request) slot
The GetAccountBalance operation retrieves the amount of money in your Amazon Mechanical Turk
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 519 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountBalanceResponse *>(send(request));
 }
getAssignment
GetAssignmentResponse * QtAws::MTurk::MTurkClient::getAssignment (const GetAssignmentRequest & request) slot
The GetAssignment operation retrieves the details of the specified Assignment.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 533 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAssignmentResponse *>(send(request));
 }
getFileUploadURL
GetFileUploadURLResponse * QtAws::MTurk::MTurkClient::getFileUploadURL (const GetFileUploadURLRequest & request) slot
The GetFileUploadURL operation generates and returns a temporary URL. You use the temporary URL to retrieve a file uploaded by a Worker as an answer to a FileUploadAnswer question for a HIT. The temporary URL is generated the instant the GetFileUploadURL operation is called, and is valid for 60 seconds. You can get a temporary file upload URL any time until the HIT is disposed. After the HIT is disposed, any uploaded files are deleted, and cannot be retrieved. Pending Deprecation on December 12, 2017. The Answer Specification structure will no longer support the FileUploadAnswer element to be used for the QuestionForm data structure. Instead, we recommend that Requesters who want to create HITs asking Workers to upload files to use Amazon S3.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 553 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetFileUploadURLResponse *>(send(request));
 }
getHIT
GetHITResponse * QtAws::MTurk::MTurkClient::getHIT (const GetHITRequest & request) slot
The GetHIT operation retrieves the details of the specified HIT.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 567 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHITResponse *>(send(request));
 }
getQualificationScore
GetQualificationScoreResponse * QtAws::MTurk::MTurkClient::getQualificationScore (const GetQualificationScoreRequest & request) slot
The GetQualificationScore operation returns the value of a Worker's Qualification for a given Qualification type.
</p
To get a Worker's Qualification, you must know the Worker's ID. The Worker's ID is included in the assignment data returned by the ListAssignmentsForHIT operation.
</p
Only the owner of a Qualification type can query the value of a Worker's Qualification of that
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 591 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQualificationScoreResponse *>(send(request));
 }
getQualificationType
GetQualificationTypeResponse * QtAws::MTurk::MTurkClient::getQualificationType (const GetQualificationTypeRequest & request) slot
The GetQualificationTypeoperation retrieves information about a Qualification type using its ID.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 605 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQualificationTypeResponse *>(send(request));
 }
listAssignmentsForHIT
ListAssignmentsForHITResponse * QtAws::MTurk::MTurkClient::listAssignmentsForHIT (const ListAssignmentsForHITRequest & request) slot
The ListAssignmentsForHIT operation retrieves completed assignments for a HIT. You can use this operation to retrieve the results for a HIT.
</p
You can get assignments for a HIT at any time, even if the HIT is not yet Reviewable. If a HIT requested multiple assignments, and has received some results but has not yet become Reviewable, you can still retrieve the partial results with this operation.
</p
Use the AssignmentStatus parameter to control which set of assignments for a HIT are returned. The ListAssignmentsForHIT operation can return submitted assignments awaiting approval, or it can return assignments that have already been approved or rejected. You can set AssignmentStatus=Approved,Rejected to get assignments that have already been approved and rejected together in one result set.
</p
Only the Requester who created the HIT can retrieve the assignments for that HIT.
</p
Results are sorted and divided into numbered pages and the operation returns a single page of results. You can use the parameters of the operation to control sorting and pagination.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 642 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAssignmentsForHITResponse *>(send(request));
 }
listBonusPayments
ListBonusPaymentsResponse * QtAws::MTurk::MTurkClient::listBonusPayments (const ListBonusPaymentsRequest & request) slot
The ListBonusPayments operation retrieves the amounts of bonuses you have paid to Workers for a given HIT or assignment.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 657 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBonusPaymentsResponse *>(send(request));
 }
listHITs
ListHITsResponse * QtAws::MTurk::MTurkClient::listHITs (const ListHITsRequest & request) slot
The ListHITs operation returns all of a Requester's HITs. The operation returns HITs of any status, except for HITs that have been deleted of with the DeleteHIT operation or that have been auto-deleted.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 672 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHITsResponse *>(send(request));
 }
listHITsForQualificationType
ListHITsForQualificationTypeResponse * QtAws::MTurk::MTurkClient::listHITsForQualificationType (const ListHITsForQualificationTypeRequest & request) slot
The ListHITsForQualificationType operation returns the HITs that use the given Qualification type for a Qualification requirement. The operation returns HITs of any status, except for HITs that have been deleted with the DeleteHIT operation or that have been auto-deleted.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 688 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHITsForQualificationTypeResponse *>(send(request));
 }
listQualificationRequests
ListQualificationRequestsResponse * QtAws::MTurk::MTurkClient::listQualificationRequests (const ListQualificationRequestsRequest & request) slot
The ListQualificationRequests operation retrieves requests for Qualifications of a particular Qualification type. The owner of the Qualification type calls this operation to poll for pending requests, and accepts them using the AcceptQualification operation.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 704 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQualificationRequestsResponse *>(send(request));
 }
listQualificationTypes
ListQualificationTypesResponse * QtAws::MTurk::MTurkClient::listQualificationTypes (const ListQualificationTypesRequest & request) slot
The ListQualificationTypes operation returns a list of Qualification types, filtered by an optional search term.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQualificationTypesResponse *>(send(request));
 }
listReviewableHITs
ListReviewableHITsResponse * QtAws::MTurk::MTurkClient::listReviewableHITs (const ListReviewableHITsRequest & request) slot
The ListReviewableHITs operation retrieves the HITs with Status equal to Reviewable or Status equal to Reviewing that belong to the Requester calling the operation.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 751 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListReviewableHITsResponse *>(send(request));
 }
listReviewPolicyResultsForHIT
ListReviewPolicyResultsForHITResponse * QtAws::MTurk::MTurkClient::listReviewPolicyResultsForHIT (const ListReviewPolicyResultsForHITRequest & request) slot
The ListReviewPolicyResultsForHIT operation retrieves the computed results and the actions taken in the course of executing your Review Policies for a given HIT. For information about how to specify Review Policies when you call CreateHIT, see Review Policies. The ListReviewPolicyResultsForHIT operation can return results for both Assignment-level and HIT-level review results.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 736 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListReviewPolicyResultsForHITResponse *>(send(request));
 }
listWorkerBlocks
ListWorkerBlocksResponse * QtAws::MTurk::MTurkClient::listWorkerBlocks (const ListWorkerBlocksRequest & request) slot
The ListWorkersBlocks operation retrieves a list of Workers who are blocked from working on your
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 765 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListWorkerBlocksResponse *>(send(request));
 }
listWorkersWithQualificationType
ListWorkersWithQualificationTypeResponse * QtAws::MTurk::MTurkClient::listWorkersWithQualificationType (const ListWorkersWithQualificationTypeRequest & request) slot
The ListWorkersWithQualificationType operation returns all of the Workers that have been associated with a given Qualification type.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 780 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListWorkersWithQualificationTypeResponse *>(send(request));
 }
notifyWorkers
NotifyWorkersResponse * QtAws::MTurk::MTurkClient::notifyWorkers (const NotifyWorkersRequest & request) slot
The NotifyWorkers operation sends an email to one or more Workers that you specify with the Worker ID. You can specify up to 100 Worker IDs to send the same message with a single call to the NotifyWorkers operation. The NotifyWorkers operation will send a notification email to a Worker only if you have previously approved or rejected work from the Worker.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 797 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<NotifyWorkersResponse *>(send(request));
 }
rejectAssignment
RejectAssignmentResponse * QtAws::MTurk::MTurkClient::rejectAssignment (const RejectAssignmentRequest & request) slot
The RejectAssignment operation rejects the results of a completed assignment.
</p
You can include an optional feedback message with the rejection, which the Worker can see in the Status section of the web site. When you include a feedback message with the rejection, it helps the Worker understand why the assignment was rejected, and can improve the quality of the results the Worker submits in the future.
</p
Only the Requester who created the HIT can reject an assignment for the HIT.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 821 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RejectAssignmentResponse *>(send(request));
 }
rejectQualificationRequest
RejectQualificationRequestResponse * QtAws::MTurk::MTurkClient::rejectQualificationRequest (const RejectQualificationRequestRequest & request) slot
The RejectQualificationRequest operation rejects a user's request for a Qualification.
</p
You can provide a text message explaining why the request was rejected. The Worker who made the request can see this
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 839 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RejectQualificationRequestResponse *>(send(request));
 }
sendBonus
SendBonusResponse * QtAws::MTurk::MTurkClient::sendBonus (const SendBonusRequest & request) slot
The SendBonus operation issues a payment of money from your account to a Worker. This payment happens separately from the reward you pay to the Worker when you approve the Worker's assignment. The SendBonus operation requires the Worker's ID and the assignment ID as parameters to initiate payment of the bonus. You must include a message that explains the reason for the bonus payment, as the Worker may not be expecting the payment. Amazon Mechanical Turk collects a fee for bonus payments, similar to the HIT listing fee. This operation fails if your account does not have enough funds to pay for both the bonus and the fees.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 858 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendBonusResponse *>(send(request));
 }
sendTestEventNotification
SendTestEventNotificationResponse * QtAws::MTurk::MTurkClient::sendTestEventNotification (const SendTestEventNotificationRequest & request) slot
The SendTestEventNotification operation causes Amazon Mechanical Turk to send a notification message as if a HIT event occurred, according to the provided notification specification. This allows you to test notifications without setting up notifications for a real HIT type and trying to trigger them using the website. When you call this operation, the service attempts to send the test notification immediately.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 875 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendTestEventNotificationResponse *>(send(request));
 }
updateExpirationForHIT
UpdateExpirationForHITResponse * QtAws::MTurk::MTurkClient::updateExpirationForHIT (const UpdateExpirationForHITRequest & request) slot
The UpdateExpirationForHIT operation allows you update the expiration time of a HIT. If you update it to a time in the past, the HIT will be immediately expired.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 890 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateExpirationForHITResponse *>(send(request));
 }
updateHITReviewStatus
UpdateHITReviewStatusResponse * QtAws::MTurk::MTurkClient::updateHITReviewStatus (const UpdateHITReviewStatusRequest & request) slot
The UpdateHITReviewStatus operation updates the status of a HIT. If the status is Reviewable, this operation can update the status to Reviewing, or it can revert a Reviewing HIT back to the Reviewable status.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 905 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateHITReviewStatusResponse *>(send(request));
 }
updateHITTypeOfHIT
UpdateHITTypeOfHITResponse * QtAws::MTurk::MTurkClient::updateHITTypeOfHIT (const UpdateHITTypeOfHITRequest & request) slot
The UpdateHITTypeOfHIT operation allows you to change the HITType properties of a HIT. This operation disassociates the HIT from its old HITType properties and associates it with the new HITType properties. The HIT takes on the properties of the new HITType in place of the old ones.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 921 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateHITTypeOfHITResponse *>(send(request));
 }
updateNotificationSettings
UpdateNotificationSettingsResponse * QtAws::MTurk::MTurkClient::updateNotificationSettings (const UpdateNotificationSettingsRequest & request) slot
The UpdateNotificationSettings operation creates, updates, disables or re-enables notifications for a HIT type. If you call the UpdateNotificationSettings operation for a HIT type that already has a notification specification, the operation replaces the old specification with a new one. You can call the UpdateNotificationSettings operation to enable or disable notifications for the HIT type, without having to modify the notification specification itself by providing updates to the Active status without specifying a new notification specification. To change the Active status of a HIT type's notifications, the HIT type must already have a notification specification, or one must be provided in the same call to UpdateNotificationSettings.
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 941 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateNotificationSettingsResponse *>(send(request));
 }
updateQualificationType
UpdateQualificationTypeResponse * QtAws::MTurk::MTurkClient::updateQualificationType (const UpdateQualificationTypeRequest & request) slot
The UpdateQualificationType operation modifies the attributes of an existing Qualification type, which is represented by a QualificationType data structure. Only the owner of a Qualification type can modify its attributes.
</p
Most attributes of a Qualification type can be changed after the type has been created. However, the Name and Keywords fields cannot be modified. The RetryDelayInSeconds parameter can be modified or added to change the delay or to enable retries, but RetryDelayInSeconds cannot be used to disable retries.
</p
You can use this operation to update the test for a Qualification type. The test is updated based on the values specified for the Test, TestDurationInSeconds and AnswerKey parameters. All three parameters specify the updated test. If you are updating the test for a type, you must specify the Test and TestDurationInSeconds parameters. The AnswerKey parameter is optional; omitting it specifies that the updated test does not have an answer key.
</p
If you omit the Test parameter, the test for the Qualification type is unchanged. There is no way to remove a test from a Qualification type that has one. If the type already has a test, you cannot update it to be AutoGranted. If the Qualification type does not have a test and one is provided by an update, the type will henceforth have a test.
</p
If you want to update the test duration or answer key for an existing test without changing the questions, you must specify a Test parameter with the original questions, along with the updated values.
</p
If you provide an updated Test but no AnswerKey, the new test will not have an answer key. Requests for such Qualifications must be granted manually.
</p
You can also update the AutoGranted and AutoGrantedValue attributes of the Qualification
Parameters
request Request to send to Amazon Mechanical Turk.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 989 of file mturkclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateQualificationTypeResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mturk-requester/mturkclient.h
mturk-requester/mturkclient.cpp