AWS SDK for Qt: QtAws::WAF::WAFRequest Class Reference
QtAws::WAF::WAFRequest Class Reference
Interface class for providing WAF requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::WAF::CreateByteMatchSetRequest, QtAws::WAF::CreateGeoMatchSetRequest, QtAws::WAF::CreateIPSetRequest, QtAws::WAF::CreateRateBasedRuleRequest, QtAws::WAF::CreateRegexMatchSetRequest, QtAws::WAF::CreateRegexPatternSetRequest, QtAws::WAF::CreateRuleGroupRequest, QtAws::WAF::CreateRuleRequest, QtAws::WAF::CreateSizeConstraintSetRequest, QtAws::WAF::CreateSqlInjectionMatchSetRequest, QtAws::WAF::CreateWebACLRequest, QtAws::WAF::CreateXssMatchSetRequest, QtAws::WAF::DeleteByteMatchSetRequest, QtAws::WAF::DeleteGeoMatchSetRequest, QtAws::WAF::DeleteIPSetRequest, QtAws::WAF::DeletePermissionPolicyRequest, QtAws::WAF::DeleteRateBasedRuleRequest, QtAws::WAF::DeleteRegexMatchSetRequest, QtAws::WAF::DeleteRegexPatternSetRequest, QtAws::WAF::DeleteRuleGroupRequest, QtAws::WAF::DeleteRuleRequest, QtAws::WAF::DeleteSizeConstraintSetRequest, QtAws::WAF::DeleteSqlInjectionMatchSetRequest, QtAws::WAF::DeleteWebACLRequest, QtAws::WAF::DeleteXssMatchSetRequest, QtAws::WAF::GetByteMatchSetRequest, QtAws::WAF::GetChangeTokenRequest, QtAws::WAF::GetChangeTokenStatusRequest, QtAws::WAF::GetGeoMatchSetRequest, QtAws::WAF::GetIPSetRequest, QtAws::WAF::GetPermissionPolicyRequest, QtAws::WAF::GetRateBasedRuleManagedKeysRequest, QtAws::WAF::GetRateBasedRuleRequest, QtAws::WAF::GetRegexMatchSetRequest, QtAws::WAF::GetRegexPatternSetRequest, QtAws::WAF::GetRuleGroupRequest, QtAws::WAF::GetRuleRequest, QtAws::WAF::GetSampledRequestsRequest, QtAws::WAF::GetSizeConstraintSetRequest, QtAws::WAF::GetSqlInjectionMatchSetRequest, QtAws::WAF::GetWebACLRequest, QtAws::WAF::GetXssMatchSetRequest, QtAws::WAF::ListActivatedRulesInRuleGroupRequest, QtAws::WAF::ListByteMatchSetsRequest, QtAws::WAF::ListGeoMatchSetsRequest, QtAws::WAF::ListIPSetsRequest, QtAws::WAF::ListRateBasedRulesRequest, QtAws::WAF::ListRegexMatchSetsRequest, QtAws::WAF::ListRegexPatternSetsRequest, QtAws::WAF::ListRuleGroupsRequest, QtAws::WAF::ListRulesRequest, QtAws::WAF::ListSizeConstraintSetsRequest, QtAws::WAF::ListSqlInjectionMatchSetsRequest, QtAws::WAF::ListSubscribedRuleGroupsRequest, QtAws::WAF::ListWebACLsRequest, QtAws::WAF::ListXssMatchSetsRequest, QtAws::WAF::PutPermissionPolicyRequest, QtAws::WAF::UpdateByteMatchSetRequest, QtAws::WAF::UpdateGeoMatchSetRequest, QtAws::WAF::UpdateIPSetRequest, QtAws::WAF::UpdateRateBasedRuleRequest, QtAws::WAF::UpdateRegexMatchSetRequest, QtAws::WAF::UpdateRegexPatternSetRequest, QtAws::WAF::UpdateRuleGroupRequest, QtAws::WAF::UpdateRuleRequest, QtAws::WAF::UpdateSizeConstraintSetRequest, QtAws::WAF::UpdateSqlInjectionMatchSetRequest, QtAws::WAF::UpdateWebACLRequest, and QtAws::WAF::UpdateXssMatchSetRequest.
Public Types
enum Action {
CreateByteMatchSetAction, CreateGeoMatchSetAction, CreateIPSetAction, CreateRateBasedRuleAction,
CreateRegexMatchSetAction, CreateRegexPatternSetAction, CreateRuleAction, CreateRuleGroupAction,
CreateSizeConstraintSetAction, CreateSqlInjectionMatchSetAction, CreateWebACLAction, CreateXssMatchSetAction,
DeleteByteMatchSetAction, DeleteGeoMatchSetAction, DeleteIPSetAction, DeletePermissionPolicyAction,
DeleteRateBasedRuleAction, DeleteRegexMatchSetAction, DeleteRegexPatternSetAction, DeleteRuleAction,
DeleteRuleGroupAction, DeleteSizeConstraintSetAction, DeleteSqlInjectionMatchSetAction, DeleteWebACLAction,
DeleteXssMatchSetAction, GetByteMatchSetAction, GetChangeTokenAction, GetChangeTokenStatusAction,
GetGeoMatchSetAction, GetIPSetAction, GetPermissionPolicyAction, GetRateBasedRuleAction,
GetRateBasedRuleManagedKeysAction, GetRegexMatchSetAction, GetRegexPatternSetAction, GetRuleAction,
GetRuleGroupAction, GetSampledRequestsAction, GetSizeConstraintSetAction, GetSqlInjectionMatchSetAction,
GetWebACLAction, GetXssMatchSetAction, ListActivatedRulesInRuleGroupAction, ListByteMatchSetsAction,
ListGeoMatchSetsAction, ListIPSetsAction, ListRateBasedRulesAction, ListRegexMatchSetsAction,
ListRegexPatternSetsAction, ListRuleGroupsAction, ListRulesAction, ListSizeConstraintSetsAction,
ListSqlInjectionMatchSetsAction, ListSubscribedRuleGroupsAction, ListWebACLsAction, ListXssMatchSetsAction,
PutPermissionPolicyAction, UpdateByteMatchSetAction, UpdateGeoMatchSetAction, UpdateIPSetAction,
UpdateRateBasedRuleAction, UpdateRegexMatchSetAction, UpdateRegexPatternSetAction, UpdateRuleAction,
UpdateRuleGroupAction, UpdateSizeConstraintSetAction, UpdateSqlInjectionMatchSetAction, UpdateWebACLAction,
UpdateXssMatchSetAction
}
Actions supported by WAF.
Public Member Functions
WAFRequest (const Action action)
Constructs a new WAFRequest object.
WAFRequest (const WAFRequest &other)
Constructs a new WAFRequest object by copying another.
WAFRequest & operator= (const WAFRequest &other)
Assignment operator.
Action action () const
Get the WAF action to be performed by this request.
QString actionString () const
Get the name of the WAF action to be performed by this request.
QString apiVersion () const
Get the WAF API version implemented by this request.
void setAction (const Action action)
Set the WAF action to be performed by this request.
void setApiVersion (const QString &version)
Set the WAF API version to include in this request.
virtual bool operator== (const WAFRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
WAFRequest (WAFRequestPrivate *const d)
Constructs a new WAFRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid WAF queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this WAF request.
const QVariantMap & parameters () const
Get all parameters included with this WAF request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this WAF request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this WAF request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this WAF request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing WAF requests.
Definition at line 35 of file wafrequest.h.
Constructor & Destructor Documentation
WAFRequest() [1/3]
QtAws::WAF::WAFRequest::WAFRequest (const Action action)
Constructs a new WAFRequest object.
Parameters
action The WAF action to request.
Definition at line 38 of file wafrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new WAFRequestPrivate(action, this))
 {
 }
WAFRequest() [2/3]
QtAws::WAF::WAFRequest::WAFRequest (const WAFRequest & other)
Constructs a new WAFRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file wafrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new WAFRequestPrivate(*other.d_func(), this))
 {
 }
WAFRequest() [3/3]
QtAws::WAF::WAFRequest::WAFRequest (WAFRequestPrivate *const d) protected
Constructs a new WAFRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from WAFRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file wafrequest.cpp.
                                                   : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
WAFRequest::Action QtAws::WAF::WAFRequest::action () const
Get the WAF action to be performed by this request.
Returns
The WAF action to be performed by this request.
Definition at line 93 of file wafrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const WAFRequest);
     return d->action;
 }
actionString()
QString QtAws::WAF::WAFRequest::actionString () const
Get the name of the WAF action to be performed by this request.
Returns
The name of the WAF action to be performed by this request.
Definition at line 104 of file wafrequest.cpp.
References action(), and QtAws::WAF::WAFRequestPrivate::toString().
 {
     return WAFRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::WAF::WAFRequest::apiVersion () const
Get the WAF API version implemented by this request.
Returns
The WAF API version implmented by this request.
Definition at line 114 of file wafrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const WAFRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::WAF::WAFRequest::clearParameter (const QString & name) protected
Check if queueName is a valid WAF queue name.
From WAF FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid WAF queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file wafrequest.cpp.
 {
     Q_D(WAFRequest);
     return d->parameters.remove(name);
 }
operator=()
WAFRequest & QtAws::WAF::WAFRequest::operator= (const WAFRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file wafrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(WAFRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::WAF::WAFRequest::operator== (const WAFRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file wafrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::WAF::WAFRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this WAF request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file wafrequest.cpp.
 {
     Q_D(const WAFRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::WAF::WAFRequest::parameters () const protected
Get all parameters included with this WAF request.
Returns
A map of parameters included with this request.
Definition at line 222 of file wafrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const WAFRequest);
     return d->parameters;
 }
setAction()
void QtAws::WAF::WAFRequest::setAction (const Action action)
Set the WAF action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file wafrequest.cpp.
References action().
 {
     Q_D(WAFRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::WAF::WAFRequest::setApiVersion (const QString & version)
Set the WAF API version to include in this request.
Parameters
version The WAF API version to include in this request.
Definition at line 136 of file wafrequest.cpp.
 {
     Q_D(WAFRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::WAF::WAFRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this WAF request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file wafrequest.cpp.
 {
     Q_D(WAFRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::WAF::WAFRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this WAF request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file wafrequest.cpp.
References parameters().
 {
     Q_D(WAFRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::WAF::WAFRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this WAF request.
This WAF implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this WAF request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file wafrequest.cpp.
 {
     Q_D(const WAFRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
waf/wafrequest.h
waf/wafrequest.cpp