AWS SDK for Qt: QtAws::MediaPackage::MediaPackageClient Class Reference
QtAws::MediaPackage::MediaPackageClient Class Reference
Client for AWS Elemental MediaPackage.
Public Slots
CreateChannelResponse * createChannel (const CreateChannelRequest &request)
CreateOriginEndpointResponse * createOriginEndpoint (const CreateOriginEndpointRequest &request)
DeleteChannelResponse * deleteChannel (const DeleteChannelRequest &request)
DeleteOriginEndpointResponse * deleteOriginEndpoint (const DeleteOriginEndpointRequest &request)
DescribeChannelResponse * describeChannel (const DescribeChannelRequest &request)
DescribeOriginEndpointResponse * describeOriginEndpoint (const DescribeOriginEndpointRequest &request)
ListChannelsResponse * listChannels (const ListChannelsRequest &request)
ListOriginEndpointsResponse * listOriginEndpoints (const ListOriginEndpointsRequest &request)
RotateChannelCredentialsResponse * rotateChannelCredentials (const RotateChannelCredentialsRequest &request)
UpdateChannelResponse * updateChannel (const UpdateChannelRequest &request)
UpdateOriginEndpointResponse * updateOriginEndpoint (const UpdateOriginEndpointRequest &request)
Public Member Functions
MediaPackageClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaPackageClient object.
MediaPackageClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaPackageClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elemental MediaPackage.
Definition at line 54 of file mediapackageclient.h.
Constructor & Destructor Documentation
MediaPackageClient() [1/2]
QtAws::MediaPackage::MediaPackageClient::MediaPackageClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaPackageClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MediaPackageClientPrivate(this), parent)
 {
     Q_D(MediaPackageClient);
     d->apiVersion = QStringLiteral("2017-10-12");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("mediapackage");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaPackage");
     d->serviceName = QStringLiteral("mediapackage");
 }
MediaPackageClient() [2/2]
QtAws::MediaPackage::MediaPackageClient::MediaPackageClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaPackageClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 101 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MediaPackageClientPrivate(this), parent)
 {
     Q_D(MediaPackageClient);
     d->apiVersion = QStringLiteral("2017-10-12");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("mediapackage");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaPackage");
     d->serviceName = QStringLiteral("mediapackage");
 }
Member Function Documentation
createChannel
CreateChannelResponse * QtAws::MediaPackage::MediaPackageClient::createChannel (const CreateChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 126 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateChannelResponse *>(send(request));
 }
createOriginEndpoint
CreateOriginEndpointResponse * QtAws::MediaPackage::MediaPackageClient::createOriginEndpoint (const CreateOriginEndpointRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 139 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateOriginEndpointResponse *>(send(request));
 }
deleteChannel
DeleteChannelResponse * QtAws::MediaPackage::MediaPackageClient::deleteChannel (const DeleteChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 152 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteChannelResponse *>(send(request));
 }
deleteOriginEndpoint
DeleteOriginEndpointResponse * QtAws::MediaPackage::MediaPackageClient::deleteOriginEndpoint (const DeleteOriginEndpointRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 165 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteOriginEndpointResponse *>(send(request));
 }
describeChannel
DescribeChannelResponse * QtAws::MediaPackage::MediaPackageClient::describeChannel (const DescribeChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 178 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeChannelResponse *>(send(request));
 }
describeOriginEndpoint
DescribeOriginEndpointResponse * QtAws::MediaPackage::MediaPackageClient::describeOriginEndpoint (const DescribeOriginEndpointRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 191 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOriginEndpointResponse *>(send(request));
 }
listChannels
ListChannelsResponse * QtAws::MediaPackage::MediaPackageClient::listChannels (const ListChannelsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 204 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListChannelsResponse *>(send(request));
 }
listOriginEndpoints
ListOriginEndpointsResponse * QtAws::MediaPackage::MediaPackageClient::listOriginEndpoints (const ListOriginEndpointsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 217 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOriginEndpointsResponse *>(send(request));
 }
rotateChannelCredentials
RotateChannelCredentialsResponse * QtAws::MediaPackage::MediaPackageClient::rotateChannelCredentials (const RotateChannelCredentialsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RotateChannelCredentialsResponse *>(send(request));
 }
updateChannel
UpdateChannelResponse * QtAws::MediaPackage::MediaPackageClient::updateChannel (const UpdateChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 243 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateChannelResponse *>(send(request));
 }
updateOriginEndpoint
UpdateOriginEndpointResponse * QtAws::MediaPackage::MediaPackageClient::updateOriginEndpoint (const UpdateOriginEndpointRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaPackage.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 256 of file mediapackageclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateOriginEndpointResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mediapackage/mediapackageclient.h
mediapackage/mediapackageclient.cpp