AWS SDK for Qt: QtAws::Route53::Route53Client Class Reference
QtAws::Route53::Route53Client Class Reference
Client for Amazon Route 53.
Public Slots
AssociateVPCWithHostedZoneResponse * associateVPCWithHostedZone (const AssociateVPCWithHostedZoneRequest &request)
ChangeResourceRecordSetsResponse * changeResourceRecordSets (const ChangeResourceRecordSetsRequest &request)
ChangeTagsForResourceResponse * changeTagsForResource (const ChangeTagsForResourceRequest &request)
CreateHealthCheckResponse * createHealthCheck (const CreateHealthCheckRequest &request)
CreateHostedZoneResponse * createHostedZone (const CreateHostedZoneRequest &request)
CreateQueryLoggingConfigResponse * createQueryLoggingConfig (const CreateQueryLoggingConfigRequest &request)
CreateReusableDelegationSetResponse * createReusableDelegationSet (const CreateReusableDelegationSetRequest &request)
CreateTrafficPolicyResponse * createTrafficPolicy (const CreateTrafficPolicyRequest &request)
CreateTrafficPolicyInstanceResponse * createTrafficPolicyInstance (const CreateTrafficPolicyInstanceRequest &request)
CreateTrafficPolicyVersionResponse * createTrafficPolicyVersion (const CreateTrafficPolicyVersionRequest &request)
CreateVPCAssociationAuthorizationResponse * createVPCAssociationAuthorization (const CreateVPCAssociationAuthorizationRequest &request)
DeleteHealthCheckResponse * deleteHealthCheck (const DeleteHealthCheckRequest &request)
DeleteHostedZoneResponse * deleteHostedZone (const DeleteHostedZoneRequest &request)
DeleteQueryLoggingConfigResponse * deleteQueryLoggingConfig (const DeleteQueryLoggingConfigRequest &request)
DeleteReusableDelegationSetResponse * deleteReusableDelegationSet (const DeleteReusableDelegationSetRequest &request)
DeleteTrafficPolicyResponse * deleteTrafficPolicy (const DeleteTrafficPolicyRequest &request)
DeleteTrafficPolicyInstanceResponse * deleteTrafficPolicyInstance (const DeleteTrafficPolicyInstanceRequest &request)
DeleteVPCAssociationAuthorizationResponse * deleteVPCAssociationAuthorization (const DeleteVPCAssociationAuthorizationRequest &request)
DisassociateVPCFromHostedZoneResponse * disassociateVPCFromHostedZone (const DisassociateVPCFromHostedZoneRequest &request)
GetAccountLimitResponse * getAccountLimit (const GetAccountLimitRequest &request)
GetChangeResponse * getChange (const GetChangeRequest &request)
GetCheckerIpRangesResponse * getCheckerIpRanges (const GetCheckerIpRangesRequest &request)
GetGeoLocationResponse * getGeoLocation (const GetGeoLocationRequest &request)
GetHealthCheckResponse * getHealthCheck (const GetHealthCheckRequest &request)
GetHealthCheckCountResponse * getHealthCheckCount (const GetHealthCheckCountRequest &request)
GetHealthCheckLastFailureReasonResponse * getHealthCheckLastFailureReason (const GetHealthCheckLastFailureReasonRequest &request)
GetHealthCheckStatusResponse * getHealthCheckStatus (const GetHealthCheckStatusRequest &request)
GetHostedZoneResponse * getHostedZone (const GetHostedZoneRequest &request)
GetHostedZoneCountResponse * getHostedZoneCount (const GetHostedZoneCountRequest &request)
GetHostedZoneLimitResponse * getHostedZoneLimit (const GetHostedZoneLimitRequest &request)
GetQueryLoggingConfigResponse * getQueryLoggingConfig (const GetQueryLoggingConfigRequest &request)
GetReusableDelegationSetResponse * getReusableDelegationSet (const GetReusableDelegationSetRequest &request)
GetReusableDelegationSetLimitResponse * getReusableDelegationSetLimit (const GetReusableDelegationSetLimitRequest &request)
GetTrafficPolicyResponse * getTrafficPolicy (const GetTrafficPolicyRequest &request)
GetTrafficPolicyInstanceResponse * getTrafficPolicyInstance (const GetTrafficPolicyInstanceRequest &request)
GetTrafficPolicyInstanceCountResponse * getTrafficPolicyInstanceCount (const GetTrafficPolicyInstanceCountRequest &request)
ListGeoLocationsResponse * listGeoLocations (const ListGeoLocationsRequest &request)
ListHealthChecksResponse * listHealthChecks (const ListHealthChecksRequest &request)
ListHostedZonesResponse * listHostedZones (const ListHostedZonesRequest &request)
ListHostedZonesByNameResponse * listHostedZonesByName (const ListHostedZonesByNameRequest &request)
ListQueryLoggingConfigsResponse * listQueryLoggingConfigs (const ListQueryLoggingConfigsRequest &request)
ListResourceRecordSetsResponse * listResourceRecordSets (const ListResourceRecordSetsRequest &request)
ListReusableDelegationSetsResponse * listReusableDelegationSets (const ListReusableDelegationSetsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ListTagsForResourcesResponse * listTagsForResources (const ListTagsForResourcesRequest &request)
ListTrafficPoliciesResponse * listTrafficPolicies (const ListTrafficPoliciesRequest &request)
ListTrafficPolicyInstancesResponse * listTrafficPolicyInstances (const ListTrafficPolicyInstancesRequest &request)
ListTrafficPolicyInstancesByHostedZoneResponse * listTrafficPolicyInstancesByHostedZone (const ListTrafficPolicyInstancesByHostedZoneRequest &request)
ListTrafficPolicyInstancesByPolicyResponse * listTrafficPolicyInstancesByPolicy (const ListTrafficPolicyInstancesByPolicyRequest &request)
ListTrafficPolicyVersionsResponse * listTrafficPolicyVersions (const ListTrafficPolicyVersionsRequest &request)
ListVPCAssociationAuthorizationsResponse * listVPCAssociationAuthorizations (const ListVPCAssociationAuthorizationsRequest &request)
TestDNSAnswerResponse * testDNSAnswer (const TestDNSAnswerRequest &request)
UpdateHealthCheckResponse * updateHealthCheck (const UpdateHealthCheckRequest &request)
UpdateHostedZoneCommentResponse * updateHostedZoneComment (const UpdateHostedZoneCommentRequest &request)
UpdateTrafficPolicyCommentResponse * updateTrafficPolicyComment (const UpdateTrafficPolicyCommentRequest &request)
UpdateTrafficPolicyInstanceResponse * updateTrafficPolicyInstance (const UpdateTrafficPolicyInstanceRequest &request)
Public Member Functions
Route53Client (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53Client object.
Route53Client (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53Client object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Route 53.
Definition at line 144 of file route53client.h.
Constructor & Destructor Documentation
Route53Client() [1/2]
QtAws::Route53::Route53Client::Route53Client (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 158 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new Route53ClientPrivate(this), parent)
 {
     Q_D(Route53Client);
     d->apiVersion = QStringLiteral("2013-04-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("route53");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Route 53");
     d->serviceName = QStringLiteral("route53");
 }
Route53Client() [2/2]
QtAws::Route53::Route53Client::Route53Client (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 191 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new Route53ClientPrivate(this), parent)
 {
     Q_D(Route53Client);
     d->apiVersion = QStringLiteral("2013-04-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("route53");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Route 53");
     d->serviceName = QStringLiteral("route53");
 }
Member Function Documentation
associateVPCWithHostedZone
AssociateVPCWithHostedZoneResponse * QtAws::Route53::Route53Client::associateVPCWithHostedZone (const AssociateVPCWithHostedZoneRequest & request) slot
Associates an Amazon VPC with a private hosted zone.
</p
To perform the association, the VPC and the private hosted zone must already exist. You can't convert a public hosted zone into a private hosted
zone> <note>
If you want to associate a VPC that was created by using one AWS account with a private hosted zone that was created by using a different account, the AWS account that created the private hosted zone must first submit a CreateVPCAssociationAuthorization request. Then the account that created the VPC must submit an AssociateVPCWithHostedZone
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 229 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateVPCWithHostedZoneResponse *>(send(request));
 }
changeResourceRecordSets
ChangeResourceRecordSetsResponse * QtAws::Route53::Route53Client::changeResourceRecordSets (const ChangeResourceRecordSetsRequest & request) slot
Creates, changes, or deletes a resource record set, which contains authoritative DNS information for a specified domain name or subdomain name. For example, you can use ChangeResourceRecordSets to create a resource record set that routes traffic for test.example.com to a web server that has an IP address of
192.0.2.44>
Change Batches and Transactional Changes
</p
The request body must include a document with a ChangeResourceRecordSetsRequest element. The request body contains a list of change items, known as a change batch. Change batches are considered transactional changes. When using the Amazon Route 53 API to change resource record sets, Amazon Route 53 either makes all or none of the changes in a change batch request. This ensures that Amazon Route 53 never partially implements the intended changes to the resource record sets in a hosted zone.
</p
For example, a change batch request that deletes the CNAME record for www.example.com and creates an alias resource record set for www.example.com. Amazon Route 53 deletes the first resource record set and creates the second resource record set in a single operation. If either the DELETE or the CREATE action fails, then both changes (plus any other changes in the batch) fail, and the original CNAME record continues to
exist>
Due to the nature of transactional changes, you can't delete the same resource record set more than once in a single change batch. If you attempt to delete the same change batch more than once, Amazon Route 53 returns an InvalidChangeBatch
error>
Traffic Flow
</p
To create resource record sets for complex routing configurations, use either the traffic flow visual editor in the Amazon Route 53 console or the API actions for traffic policies and traffic policy instances. Save the configuration as a traffic policy, then associate the traffic policy with one or more domain names (such as example.com) or subdomain names (such as www.example.com), in the same hosted zone or in multiple hosted zones. You can roll back the updates if the new configuration isn't performing as expected. For more information, see Using Traffic Flow to Route DNS Traffic in the Amazon Route 53 Developer
Guide>
Create, Delete, and Upsert
</p
Use ChangeResourceRecordsSetsRequest to perform the following
actions>
CREATE: Creates a resource record set that has the specified
values>
DELETE: Deletes an existing resource record set that has the specified
values>
UPSERT: If a resource record set does not already exist, AWS creates it. If a resource set does exist, Amazon Route 53 updates it with the values in the request.
</p
Syntaxes for Creating, Updating, and Deleting Resource Record Sets
</p
The syntax for a request depends on the type of resource record set that you want to create, delete, or update, such as weighted, alias, or failover. The XML elements in your request must appear in the order listed in the syntax.
</p
For an example for each type of resource record set, see
"Examples.>
Don't refer to the syntax in the "Parameter Syntax" section, which includes all of the elements for every kind of resource record set that you can create, delete, or update by using ChangeResourceRecordSets.
</p
Change Propagation to Amazon Route 53 DNS Servers
</p
When you submit a ChangeResourceRecordSets request, Amazon Route 53 propagates your changes to all of the Amazon Route 53 authoritative DNS servers. While your changes are propagating, GetChange returns a status of PENDING. When propagation is complete, GetChange returns a status of INSYNC. Changes generally propagate to all Amazon Route 53 name servers within 60 seconds. For more information, see
GetChange>
Limits on ChangeResourceRecordSets Requests
</p
For information about the limits on a ChangeResourceRecordSets request, see Limits in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 344 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangeResourceRecordSetsResponse *>(send(request));
 }
changeTagsForResource
ChangeTagsForResourceResponse * QtAws::Route53::Route53Client::changeTagsForResource (const ChangeTagsForResourceRequest & request) slot
Adds, edits, or deletes tags for a health check or a hosted
zone>
For information about using tags for cost allocation, see Using Cost Allocation Tags in the AWS Billing and Cost Management User
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 364 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangeTagsForResourceResponse *>(send(request));
 }
createHealthCheck
CreateHealthCheckResponse * QtAws::Route53::Route53Client::createHealthCheck (const CreateHealthCheckRequest & request) slot
Creates a new health
check>
For information about adding health checks to resource record sets, see ResourceRecordSet$HealthCheckId in ChangeResourceRecordSets.
</p
ELB Load Balancers
</p
If you're registering EC2 instances with an Elastic Load Balancing (ELB) load balancer, do not create Amazon Route 53 health checks for the EC2 instances. When you register an EC2 instance with a load balancer, you configure settings for an ELB health check, which performs a similar function to an Amazon Route 53 health
check>
Private Hosted Zones
</p
You can associate health checks with failover resource record sets in a private hosted zone. Note the
following>
Amazon Route 53 health checkers are outside the VPC. To check the health of an endpoint within a VPC by IP address, you must assign a public IP address to the instance in the
VPC>
You can configure a health checker to check the health of an external resource that the instance relies on, such as a database
server>
You can create a CloudWatch metric, associate an alarm with the metric, and then create a health check that is based on the state of the alarm. For example, you might create a CloudWatch metric that checks the status of the Amazon EC2 StatusCheckFailed metric, add an alarm to the metric, and then create a health check that is based on the state of the alarm. For information about creating CloudWatch metrics and alarms by using the CloudWatch console, see the Amazon CloudWatch User request Request to send to Amazon Route 53. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHealthCheckResponse *>(send(request));
 }
createHostedZone
CreateHostedZoneResponse * QtAws::Route53::Route53Client::createHostedZone (const CreateHostedZoneRequest & request) slot
Creates a new public hosted zone, which you use to specify how the Domain Name System (DNS) routes traffic on the Internet for a domain, such as example.com, and its subdomains.
</p
You can't convert a public hosted zones to a private hosted zone or vice versa. Instead, you must create a new hosted zone with the same name and create new resource record
sets>
For more information about charges for hosted zones, see Amazon Route 53 Pricing>
Note the
following>
You can't create a hosted zone for a top-level domain
(TLD)>
Amazon Route 53 automatically creates a default SOA record and four NS records for the zone. For more information about SOA and NS records, see NS and SOA Records that Amazon Route 53 Creates for a Hosted Zone in the Amazon Route 53 Developer
Guide>
If you want to use the same name servers for multiple hosted zones, you can optionally associate a reusable delegation set with the hosted zone. See the DelegationSetId
element>
If your domain is registered with a registrar other than Amazon Route 53, you must update the name servers with your registrar to make Amazon Route 53 your DNS service. For more information, see Configuring Amazon Route 53 as your DNS Service in the Amazon Route 53 Developer Guide.
</p
When you submit a CreateHostedZone request, the initial status of the hosted zone is PENDING. This means that the NS and SOA records are not yet available on all Amazon Route 53 DNS servers. When the NS and SOA records are available, the status of the zone changes to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 477 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHostedZoneResponse *>(send(request));
 }
createQueryLoggingConfig
CreateQueryLoggingConfigResponse * QtAws::Route53::Route53Client::createQueryLoggingConfig (const CreateQueryLoggingConfigRequest & request) slot
Creates a configuration for DNS query logging. After you create a query logging configuration, Amazon Route 53 begins to publish log data to an Amazon CloudWatch Logs log
group>
DNS query logs contain information about the queries that Amazon Route 53 receives for a specified public hosted zone, such as the
following>
Amazon Route 53 edge location that responded to the DNS
quer>
Domain or subdomain that was
requeste>
DNS record type, such as A or
AAA>
DNS response code, such as NoError or ServFail
</p
Log Group and Resource Policy
Before you create a query logging configuration, perform the following
operations> <note>
If you create a query logging configuration using the Amazon Route 53 console, Amazon Route 53 performs these operations
automatically> </note>
Create a CloudWatch Logs log group, and make note of the ARN, which you specify when you create a query logging configuration. Note the
following>
You must create the log group in the us-east-1
region>
You must use the same AWS account to create the log group and the hosted zone that you want to configure query logging
for>
When you create log groups for query logging, we recommend that you use a consistent prefix, for
example>
/aws/route53/hosted zone name
</p
In the next step, you'll create a resource policy, which controls access to one or more log groups and the associated AWS resources, such as Amazon Route 53 hosted zones. There's a limit on the number of resource policies that you can create, so we recommend that you use a consistent prefix so you can use the same resource policy for all the log groups that you create for query
logging>
Create a CloudWatch Logs resource policy, and give it the permissions that Amazon Route 53 needs to create log streams and to send query logs to log streams. For the value of Resource, specify the ARN for the log group that you created in the previous step. To use the same resource policy for all the CloudWatch Logs log groups that you created for query logging configurations, replace the hosted zone name with *, for
example>
arn:aws:logs:us-east-1:123412341234:log-group:/aws/route53/*
</p <note>
You can't use the CloudWatch console to create or edit a resource policy. You must use the CloudWatch API, one of the AWS SDKs, or the AWS
CLI> </note>
Log Streams and Edge Locations
When Amazon Route 53 finishes creating the configuration for DNS query logging, it does the
following>
Creates a log stream for an edge location the first time that the edge location responds to DNS queries for the specified hosted zone. That log stream is used to log all queries that Amazon Route 53 responds to for that edge
location>
Begins to send query logs to the applicable log
stream>
The name of each log stream is in the following
format>
hosted zone ID/edge location code
</p
The edge location code is a three-letter code and an arbitrarily assigned number, for example, DFW3. The three-letter code typically corresponds with the International Air Transport Association airport code for an airport near the edge location. (These abbreviations might change in the future.) For a list of edge locations, see "The Amazon Route 53 Global Network" on the Amazon Route 53 Product Details
page>
Queries That Are Logged
Query logs contain only the queries that DNS resolvers forward to Amazon Route 53. If a DNS resolver has already cached the response to a query (such as the IP address for a load balancer for example.com), the resolver will continue to return the cached response. It doesn't forward another query to Amazon Route 53 until the TTL for the corresponding resource record set expires. Depending on how many DNS queries are submitted for a resource record set, and depending on the TTL for that resource record set, query logs might contain information about only one query out of every several thousand queries that are submitted to DNS. For more information about how DNS works, see Routing Internet Traffic to Your Website or Web Application in the Amazon Route 53 Developer
Guide>
Log File Format
For a list of the values in each query log and the format of each value, see Logging DNS Queries in the Amazon Route 53 Developer
Guide>
Pricing
For information about charges for query logs, see Amazon CloudWatch Pricing>
How to Stop Logging
If you want Amazon Route 53 to stop sending query logs to CloudWatch Logs, delete the query logging configuration. For more information, see
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 619 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateQueryLoggingConfigResponse *>(send(request));
 }
createReusableDelegationSet
CreateReusableDelegationSetResponse * QtAws::Route53::Route53Client::createReusableDelegationSet (const CreateReusableDelegationSetRequest & request) slot
Creates a delegation set (a group of four name servers) that can be reused by multiple hosted zones. If a hosted zoned ID is specified, CreateReusableDelegationSet marks the delegation set associated with that zone as
reusable> <note>
You can't associate a reusable delegation set with a private hosted
zone> </note>
For information about using a reusable delegation set to configure white label name servers, see Configuring White Label Name Servers>
The process for migrating existing hosted zones to use a reusable delegation set is comparable to the process for configuring white label name servers. You need to perform the following
steps>
Create a reusable delegation
set>
Recreate hosted zones, and reduce the TTL to 60 seconds or
less>
Recreate resource record sets in the new hosted
zones>
Change the registrar's name servers to use the name servers for the new hosted
zones>
Monitor traffic for the website or
application>
Change TTLs back to their original
values>
If you want to migrate existing hosted zones to use a reusable delegation set, the existing hosted zones can't use any of the name servers that are assigned to the reusable delegation set. If one or more hosted zones do use one or more name servers that are assigned to the reusable delegation set, you can do one of the
following>
For small numbers of hosted zonesup to a few hundredit's relatively easy to create reusable delegation sets until you get one that has four name servers that don't overlap with any of the name servers in your hosted
zones>
For larger numbers of hosted zones, the easiest solution is to use more than one reusable delegation
set>
For larger numbers of hosted zones, you can also migrate hosted zones that have overlapping name servers to hosted zones that don't have overlapping name servers, then migrate the hosted zones again to use the reusable delegation
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 693 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReusableDelegationSetResponse *>(send(request));
 }
createTrafficPolicy
CreateTrafficPolicyResponse * QtAws::Route53::Route53Client::createTrafficPolicy (const CreateTrafficPolicyRequest & request) slot
Creates a traffic policy, which you use to create multiple DNS resource record sets for one domain name (such as example.com) or one subdomain name (such as
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 708 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTrafficPolicyResponse *>(send(request));
 }
createTrafficPolicyInstance
CreateTrafficPolicyInstanceResponse * QtAws::Route53::Route53Client::createTrafficPolicyInstance (const CreateTrafficPolicyInstanceRequest & request) slot
Creates resource record sets in a specified hosted zone based on the settings in a specified traffic policy version. In addition, CreateTrafficPolicyInstance associates the resource record sets with a specified domain name (such as example.com) or subdomain name (such as www.example.com). Amazon Route 53 responds to DNS queries for the domain or subdomain name by using the resource record sets that CreateTrafficPolicyInstance
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 725 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTrafficPolicyInstanceResponse *>(send(request));
 }
createTrafficPolicyVersion
CreateTrafficPolicyVersionResponse * QtAws::Route53::Route53Client::createTrafficPolicyVersion (const CreateTrafficPolicyVersionRequest & request) slot
Creates a new version of an existing traffic policy. When you create a new version of a traffic policy, you specify the ID of the traffic policy that you want to update and a JSON-formatted document that describes the new version. You use traffic policies to create multiple DNS resource record sets for one domain name (such as example.com) or one subdomain name (such as www.example.com). You can create a maximum of 1000 versions of a traffic policy. If you reach the limit and need to create another version, you'll need to start a new traffic
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 743 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTrafficPolicyVersionResponse *>(send(request));
 }
createVPCAssociationAuthorization
CreateVPCAssociationAuthorizationResponse * QtAws::Route53::Route53Client::createVPCAssociationAuthorization (const CreateVPCAssociationAuthorizationRequest & request) slot
Authorizes the AWS account that created a specified VPC to submit an AssociateVPCWithHostedZone request to associate the VPC with a specified hosted zone that was created by a different account. To submit a CreateVPCAssociationAuthorization request, you must use the account that created the hosted zone. After you authorize the association, use the account that created the VPC to submit an AssociateVPCWithHostedZone
request> <note>
If you want to associate multiple VPCs that you created by using one account with a hosted zone that you created by using a different account, you must submit one authorization request for each
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 765 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVPCAssociationAuthorizationResponse *>(send(request));
 }
deleteHealthCheck
DeleteHealthCheckResponse * QtAws::Route53::Route53Client::deleteHealthCheck (const DeleteHealthCheckRequest & request) slot
Deletes a health
check>
Amazon Route 53 does not prevent you from deleting a health check even if the health check is associated with one or more resource record sets. If you delete a health check and you don't update the associated resource record sets, the future status of the health check can't be predicted and may change. This will affect the routing of DNS queries for your DNS failover configuration. For more information, see Replacing and Deleting Health Checks in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 788 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHealthCheckResponse *>(send(request));
 }
deleteHostedZone
DeleteHostedZoneResponse * QtAws::Route53::Route53Client::deleteHostedZone (const DeleteHostedZoneRequest & request) slot
Deletes a hosted
zone>
If the name servers for the hosted zone are associated with a domain and if you want to make the domain unavailable on the Internet, we recommend that you delete the name servers from the domain to prevent future DNS queries from possibly being misrouted. If the domain is registered with Amazon Route 53, see UpdateDomainNameservers. If the domain is registered with another registrar, use the method provided by the registrar to delete name servers for the
domain>
Some domain registries don't allow you to remove all of the name servers for a domain. If the registry for your domain requires one or more name servers, we recommend that you delete the hosted zone only if you transfer DNS service to another service provider, and you replace the name servers for the domain with name servers from the new
provider>
You can delete a hosted zone only if it contains only the default SOA record and NS resource record sets. If the hosted zone contains other resource record sets, you must delete them before you can delete the hosted zone. If you try to delete a hosted zone that contains other resource record sets, the request fails, and Amazon Route 53 returns a HostedZoneNotEmpty error. For information about deleting records from your hosted zone, see
ChangeResourceRecordSets>
To verify that the hosted zone has been deleted, do one of the
following>
Use the GetHostedZone action to request information about the hosted
zone>
Use the ListHostedZones action to get a list of the hosted zones associated with the current AWS
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 834 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHostedZoneResponse *>(send(request));
 }
deleteQueryLoggingConfig
DeleteQueryLoggingConfigResponse * QtAws::Route53::Route53Client::deleteQueryLoggingConfig (const DeleteQueryLoggingConfigRequest & request) slot
Deletes a configuration for DNS query logging. If you delete a configuration, Amazon Route 53 stops sending query logs to CloudWatch Logs. Amazon Route 53 doesn't delete any logs that are already in CloudWatch
Logs>
For more information about DNS query logs, see
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 853 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteQueryLoggingConfigResponse *>(send(request));
 }
deleteReusableDelegationSet
DeleteReusableDelegationSetResponse * QtAws::Route53::Route53Client::deleteReusableDelegationSet (const DeleteReusableDelegationSetRequest & request) slot
Deletes a reusable delegation
set>
You can delete a reusable delegation set only if it isn't associated with any hosted
zones>
To verify that the reusable delegation set is not associated with any hosted zones, submit a GetReusableDelegationSet request and specify the ID of the reusable delegation set that you want to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 876 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReusableDelegationSetResponse *>(send(request));
 }
deleteTrafficPolicy
DeleteTrafficPolicyResponse * QtAws::Route53::Route53Client::deleteTrafficPolicy (const DeleteTrafficPolicyRequest & request) slot
Deletes a traffic
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 890 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTrafficPolicyResponse *>(send(request));
 }
deleteTrafficPolicyInstance
DeleteTrafficPolicyInstanceResponse * QtAws::Route53::Route53Client::deleteTrafficPolicyInstance (const DeleteTrafficPolicyInstanceRequest & request) slot
Deletes a traffic policy instance and all of the resource record sets that Amazon Route 53 created when you created the
instance> <note>
In the Amazon Route 53 console, traffic policy instances are known as policy
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 908 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTrafficPolicyInstanceResponse *>(send(request));
 }
deleteVPCAssociationAuthorization
DeleteVPCAssociationAuthorizationResponse * QtAws::Route53::Route53Client::deleteVPCAssociationAuthorization (const DeleteVPCAssociationAuthorizationRequest & request) slot
Removes authorization to submit an AssociateVPCWithHostedZone request to associate a specified VPC with a hosted zone that was created by a different account. You must use the account that created the hosted zone to submit a DeleteVPCAssociationAuthorization
request>
Sending this request only prevents the AWS account that created the VPC from associating the VPC with the Amazon Route 53 hosted zone in the future. If the VPC is already associated with the hosted zone, DeleteVPCAssociationAuthorization won't disassociate the VPC from the hosted zone. If you want to delete an existing association, use
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 931 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVPCAssociationAuthorizationResponse *>(send(request));
 }
disassociateVPCFromHostedZone
DisassociateVPCFromHostedZoneResponse * QtAws::Route53::Route53Client::disassociateVPCFromHostedZone (const DisassociateVPCFromHostedZoneRequest & request) slot
Disassociates a VPC from a Amazon Route 53 private hosted zone.
</p <note>
You can't disassociate the last VPC from a private hosted
zone> </note>
You can't disassociate a VPC from a private hosted zone when only one VPC is associated with the hosted zone. You also can't convert a private hosted zone into a public hosted
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 954 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateVPCFromHostedZoneResponse *>(send(request));
 }
getAccountLimit
GetAccountLimitResponse * QtAws::Route53::Route53Client::getAccountLimit (const GetAccountLimitRequest & request) slot
Gets the specified limit for the current account, for example, the maximum number of health checks that you can create using the
account>
For the default limit, see Limits in the Amazon Route 53 Developer Guide. To request a higher limit, open a request Request to send to Amazon Route 53. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 977 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountLimitResponse *>(send(request));
 }
getChange
GetChangeResponse * QtAws::Route53::Route53Client::getChange (const GetChangeRequest & request) slot
Returns the current status of a change batch request. The status is one of the following
values>
PENDING indicates that the changes in this request have not propagated to all Amazon Route 53 DNS servers. This is the initial status of all change batch
requests>
INSYNC indicates that the changes have propagated to all Amazon Route 53 DNS servers.
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1000 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetChangeResponse *>(send(request));
 }
getCheckerIpRanges
GetCheckerIpRangesResponse * QtAws::Route53::Route53Client::getCheckerIpRanges (const GetCheckerIpRangesRequest & request) slot
GetCheckerIpRanges still works, but we recommend that you download ip-ranges.json, which includes IP address ranges for all AWS services. For more information, see IP Address Ranges of Amazon Route 53 Servers in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1017 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCheckerIpRangesResponse *>(send(request));
 }
getGeoLocation
GetGeoLocationResponse * QtAws::Route53::Route53Client::getGeoLocation (const GetGeoLocationRequest & request) slot
Gets information about whether a specified geographic location is supported for Amazon Route 53 geolocation resource record
sets>
Use the following syntax to determine whether a continent is supported for
geolocation>
GET /2013-04-01/geolocation?ContinentCode=two-letter abbreviation for a continent
GET /2013-04-01/geolocation?CountryCode=two-character country code
GET /2013-04-01/geolocation?CountryCode=two-character country code&SubdivisionCode=subdivision code
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1057 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGeoLocationResponse *>(send(request));
 }
getHealthCheck
GetHealthCheckResponse * QtAws::Route53::Route53Client::getHealthCheck (const GetHealthCheckRequest & request) slot
Gets information about a specified health
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1071 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHealthCheckResponse *>(send(request));
 }
getHealthCheckCount
GetHealthCheckCountResponse * QtAws::Route53::Route53Client::getHealthCheckCount (const GetHealthCheckCountRequest & request) slot
Retrieves the number of health checks that are associated with the current AWS
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1085 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHealthCheckCountResponse *>(send(request));
 }
getHealthCheckLastFailureReason
GetHealthCheckLastFailureReasonResponse * QtAws::Route53::Route53Client::getHealthCheckLastFailureReason (const GetHealthCheckLastFailureReasonRequest & request) slot
Gets the reason that a specified health check failed most
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1099 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHealthCheckLastFailureReasonResponse *>(send(request));
 }
getHealthCheckStatus
GetHealthCheckStatusResponse * QtAws::Route53::Route53Client::getHealthCheckStatus (const GetHealthCheckStatusRequest & request) slot
Gets status of a specified health check.
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1113 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHealthCheckStatusResponse *>(send(request));
 }
getHostedZone
GetHostedZoneResponse * QtAws::Route53::Route53Client::getHostedZone (const GetHostedZoneRequest & request) slot
Gets information about a specified hosted zone including the four name servers assigned to the hosted
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1127 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHostedZoneResponse *>(send(request));
 }
getHostedZoneCount
GetHostedZoneCountResponse * QtAws::Route53::Route53Client::getHostedZoneCount (const GetHostedZoneCountRequest & request) slot
Retrieves the number of hosted zones that are associated with the current AWS
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1141 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHostedZoneCountResponse *>(send(request));
 }
getHostedZoneLimit
GetHostedZoneLimitResponse * QtAws::Route53::Route53Client::getHostedZoneLimit (const GetHostedZoneLimitRequest & request) slot
Gets the specified limit for a specified hosted zone, for example, the maximum number of records that you can create in the hosted zone.
</p
For the default limit, see Limits in the Amazon Route 53 Developer Guide. To request a higher limit, open a request Request to send to Amazon Route 53. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1164 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHostedZoneLimitResponse *>(send(request));
 }
getQueryLoggingConfig
GetQueryLoggingConfigResponse * QtAws::Route53::Route53Client::getQueryLoggingConfig (const GetQueryLoggingConfigRequest & request) slot
Gets information about a specified configuration for DNS query
logging>
For more information about DNS query logs, see CreateQueryLoggingConfig and Logging DNS request Request to send to Amazon Route 53. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1183 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQueryLoggingConfigResponse *>(send(request));
 }
getReusableDelegationSet
GetReusableDelegationSetResponse * QtAws::Route53::Route53Client::getReusableDelegationSet (const GetReusableDelegationSetRequest & request) slot
Retrieves information about a specified reusable delegation set, including the four name servers that are assigned to the delegation
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1198 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReusableDelegationSetResponse *>(send(request));
 }
getReusableDelegationSetLimit
GetReusableDelegationSetLimitResponse * QtAws::Route53::Route53Client::getReusableDelegationSetLimit (const GetReusableDelegationSetLimitRequest & request) slot
Gets the maximum number of hosted zones that you can associate with the specified reusable delegation
set>
For the default limit, see Limits in the Amazon Route 53 Developer Guide. To request a higher limit, open a request Request to send to Amazon Route 53. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1220 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReusableDelegationSetLimitResponse *>(send(request));
 }
getTrafficPolicy
GetTrafficPolicyResponse * QtAws::Route53::Route53Client::getTrafficPolicy (const GetTrafficPolicyRequest & request) slot
Gets information about a specific traffic policy
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1234 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTrafficPolicyResponse *>(send(request));
 }
getTrafficPolicyInstance
GetTrafficPolicyInstanceResponse * QtAws::Route53::Route53Client::getTrafficPolicyInstance (const GetTrafficPolicyInstanceRequest & request) slot
Gets information about a specified traffic policy
instance> <note>
After you submit a CreateTrafficPolicyInstance or an UpdateTrafficPolicyInstance request, there's a brief delay while Amazon Route 53 creates the resource record sets that are specified in the traffic policy definition. For more information, see the State response
element> </note> <note>
In the Amazon Route 53 console, traffic policy instances are known as policy
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1258 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTrafficPolicyInstanceResponse *>(send(request));
 }
getTrafficPolicyInstanceCount
GetTrafficPolicyInstanceCountResponse * QtAws::Route53::Route53Client::getTrafficPolicyInstanceCount (const GetTrafficPolicyInstanceCountRequest & request) slot
Gets the number of traffic policy instances that are associated with the current AWS
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1272 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTrafficPolicyInstanceCountResponse *>(send(request));
 }
listGeoLocations
ListGeoLocationsResponse * QtAws::Route53::Route53Client::listGeoLocations (const ListGeoLocationsRequest & request) slot
Retrieves a list of supported geo
locations>
Countries are listed first, and continents are listed last. If Amazon Route 53 supports subdivisions for a country (for example, states or provinces), the subdivisions for that country are listed in alphabetical order immediately after the corresponding
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1292 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGeoLocationsResponse *>(send(request));
 }
listHealthChecks
ListHealthChecksResponse * QtAws::Route53::Route53Client::listHealthChecks (const ListHealthChecksRequest & request) slot
Retrieve a list of the health checks that are associated with the current AWS account.
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1306 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHealthChecksResponse *>(send(request));
 }
listHostedZones
ListHostedZonesResponse * QtAws::Route53::Route53Client::listHostedZones (const ListHostedZonesRequest & request) slot
Retrieves a list of the public and private hosted zones that are associated with the current AWS account. The response includes a HostedZones child element for each hosted
zone>
Amazon Route 53 returns a maximum of 100 items in each response. If you have a lot of hosted zones, you can use the maxitems parameter to list them in groups of up to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1326 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHostedZonesResponse *>(send(request));
 }
listHostedZonesByName
ListHostedZonesByNameResponse * QtAws::Route53::Route53Client::listHostedZonesByName (const ListHostedZonesByNameRequest & request) slot
Retrieves a list of your hosted zones in lexicographic order. The response includes a HostedZones child element for each hosted zone created by the current AWS account.
</p
ListHostedZonesByName sorts hosted zones by name with the labels reversed. For
example>
com.example.www.
</p
Note the trailing dot, which can change the sort order in some
circumstances>
If the domain name includes escape characters or Punycode, ListHostedZonesByName alphabetizes the domain name using the escaped or Punycoded value, which is the format that Amazon Route 53 saves in its database. For example, to create a hosted zone for exmple.com, you specify ex\344mple.com for the domain name. ListHostedZonesByName alphabetizes it
as>
com.ex\344mple.
</p
The labels are reversed and alphabetized using the escaped value. For more information about valid domain name formats, including internationalized domain names, see DNS Domain Name Format in the Amazon Route 53 Developer
Guide>
Amazon Route 53 returns up to 100 items in each response. If you have a lot of hosted zones, use the MaxItems parameter to list them in groups of up to 100. The response includes values that help navigate from one group of MaxItems hosted zones to the
next>
The DNSName and HostedZoneId elements in the response contain the values, if any, specified for the dnsname and hostedzoneid parameters in the request that produced the current
response>
The MaxItems element in the response contains the value, if any, that you specified for the maxitems parameter in the request that produced the current
response>
If the value of IsTruncated in the response is true, there are more hosted zones associated with the current AWS account.
</p
If IsTruncated is false, this response includes the last hosted zone that is associated with the current account. The NextDNSName element and NextHostedZoneId elements are omitted from the
response>
The NextDNSName and NextHostedZoneId elements in the response contain the domain name and the hosted zone ID of the next hosted zone that is associated with the current AWS account. If you want to list more hosted zones, make another call to ListHostedZonesByName, and specify the value of NextDNSName and NextHostedZoneId in the dnsname and hostedzoneid parameters,
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1404 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHostedZonesByNameResponse *>(send(request));
 }
listQueryLoggingConfigs
ListQueryLoggingConfigsResponse * QtAws::Route53::Route53Client::listQueryLoggingConfigs (const ListQueryLoggingConfigsRequest & request) slot
Lists the configurations for DNS query logging that are associated with the current AWS account or the configuration that is associated with a specified hosted
zone>
For more information about DNS query logs, see CreateQueryLoggingConfig. Additional information, including the format of DNS query logs, appears in Logging DNS Queries in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1426 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQueryLoggingConfigsResponse *>(send(request));
 }
listResourceRecordSets
ListResourceRecordSetsResponse * QtAws::Route53::Route53Client::listResourceRecordSets (const ListResourceRecordSetsRequest & request) slot
Lists the resource record sets in a specified hosted
zone>
ListResourceRecordSets returns up to 100 resource record sets at a time in ASCII order, beginning at a position specified by the name and type elements. The action sorts results first by DNS name with the labels reversed, for
example>
com.example.www.
</p
Note the trailing dot, which can change the sort order in some
circumstances>
When multiple records have the same DNS name, the action sorts results by the record
type>
You can use the name and type elements to adjust the beginning position of the list of resource record sets
returned>
If you do not specify Name or Type
The results begin with the first resource record set that the hosted zone
contains>
If you specify Name but not Type
The results begin with the first resource record set in the list whose name is greater than or equal to
Name>
If you specify Type but not Name
Amazon Route 53 returns the InvalidInput
error>
If you specify both Name and Type
The results begin with the first resource record set in the list whose name is greater than or equal to Name, and whose type is greater than or equal to
Type>
This action returns the most current version of the records. This includes records that are PENDING, and that are not yet available on all Amazon Route 53 DNS
servers>
To ensure that you get an accurate listing of the resource record sets for a hosted zone at a point in time, do not submit a ChangeResourceRecordSets request while you're paging through the results of a ListResourceRecordSets request. If you do, some pages may display results without the latest changes while other pages display results with the latest
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1491 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListResourceRecordSetsResponse *>(send(request));
 }
listReusableDelegationSets
ListReusableDelegationSetsResponse * QtAws::Route53::Route53Client::listReusableDelegationSets (const ListReusableDelegationSetsRequest & request) slot
Retrieves a list of the reusable delegation sets that are associated with the current AWS
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1505 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListReusableDelegationSetsResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::Route53::Route53Client::listTagsForResource (const ListTagsForResourceRequest & request) slot
Lists tags for one health check or hosted zone.
</p
For information about using tags for cost allocation, see Using Cost Allocation Tags in the AWS Billing and Cost Management User
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1525 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
listTagsForResources
ListTagsForResourcesResponse * QtAws::Route53::Route53Client::listTagsForResources (const ListTagsForResourcesRequest & request) slot
Lists tags for up to 10 health checks or hosted
zones>
For information about using tags for cost allocation, see Using Cost Allocation Tags in the AWS Billing and Cost Management User
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1545 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourcesResponse *>(send(request));
 }
listTrafficPolicies
ListTrafficPoliciesResponse * QtAws::Route53::Route53Client::listTrafficPolicies (const ListTrafficPoliciesRequest & request) slot
Gets information about the latest version for every traffic policy that is associated with the current AWS account. Policies are listed in the order in which they were created.
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1560 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTrafficPoliciesResponse *>(send(request));
 }
listTrafficPolicyInstances
ListTrafficPolicyInstancesResponse * QtAws::Route53::Route53Client::listTrafficPolicyInstances (const ListTrafficPolicyInstancesRequest & request) slot
Gets information about the traffic policy instances that you created by using the current AWS
account> <note>
After you submit an UpdateTrafficPolicyInstance request, there's a brief delay while Amazon Route 53 creates the resource record sets that are specified in the traffic policy definition. For more information, see the State response
element> </note>
Amazon Route 53 returns a maximum of 100 items in each response. If you have a lot of traffic policy instances, you can use the MaxItems parameter to list them in groups of up to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1585 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTrafficPolicyInstancesResponse *>(send(request));
 }
listTrafficPolicyInstancesByHostedZone
ListTrafficPolicyInstancesByHostedZoneResponse * QtAws::Route53::Route53Client::listTrafficPolicyInstancesByHostedZone (const ListTrafficPolicyInstancesByHostedZoneRequest & request) slot
Gets information about the traffic policy instances that you created in a specified hosted
zone> <note>
After you submit a CreateTrafficPolicyInstance or an UpdateTrafficPolicyInstance request, there's a brief delay while Amazon Route 53 creates the resource record sets that are specified in the traffic policy definition. For more information, see the State response
element> </note>
Amazon Route 53 returns a maximum of 100 items in each response. If you have a lot of traffic policy instances, you can use the MaxItems parameter to list them in groups of up to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1610 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTrafficPolicyInstancesByHostedZoneResponse *>(send(request));
 }
listTrafficPolicyInstancesByPolicy
ListTrafficPolicyInstancesByPolicyResponse * QtAws::Route53::Route53Client::listTrafficPolicyInstancesByPolicy (const ListTrafficPolicyInstancesByPolicyRequest & request) slot
Gets information about the traffic policy instances that you created by using a specify traffic policy
version> <note>
After you submit a CreateTrafficPolicyInstance or an UpdateTrafficPolicyInstance request, there's a brief delay while Amazon Route 53 creates the resource record sets that are specified in the traffic policy definition. For more information, see the State response
element> </note>
Amazon Route 53 returns a maximum of 100 items in each response. If you have a lot of traffic policy instances, you can use the MaxItems parameter to list them in groups of up to
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1635 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTrafficPolicyInstancesByPolicyResponse *>(send(request));
 }
listTrafficPolicyVersions
ListTrafficPolicyVersionsResponse * QtAws::Route53::Route53Client::listTrafficPolicyVersions (const ListTrafficPolicyVersionsRequest & request) slot
Gets information about all of the versions for a specified traffic
policy>
Traffic policy versions are listed in numerical order by
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1653 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTrafficPolicyVersionsResponse *>(send(request));
 }
listVPCAssociationAuthorizations
ListVPCAssociationAuthorizationsResponse * QtAws::Route53::Route53Client::listVPCAssociationAuthorizations (const ListVPCAssociationAuthorizationsRequest & request) slot
Gets a list of the VPCs that were created by other accounts and that can be associated with a specified hosted zone because you've submitted one or more CreateVPCAssociationAuthorization requests.
</p
The response includes a VPCs element with a VPC child element for each VPC that can be associated with the hosted
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1673 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListVPCAssociationAuthorizationsResponse *>(send(request));
 }
testDNSAnswer
TestDNSAnswerResponse * QtAws::Route53::Route53Client::testDNSAnswer (const TestDNSAnswerRequest & request) slot
Gets the value that Amazon Route 53 returns in response to a DNS request for a specified record name and type. You can optionally specify the IP address of a DNS resolver, an EDNS0 client subnet IP address, and a subnet mask.
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1688 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestDNSAnswerResponse *>(send(request));
 }
updateHealthCheck
UpdateHealthCheckResponse * QtAws::Route53::Route53Client::updateHealthCheck (const UpdateHealthCheckRequest & request) slot
Updates an existing health check. Note that some values can't be updated.
</p
For more information about updating health checks, see Creating, Updating, and Deleting Health Checks in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1708 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateHealthCheckResponse *>(send(request));
 }
updateHostedZoneComment
UpdateHostedZoneCommentResponse * QtAws::Route53::Route53Client::updateHostedZoneComment (const UpdateHostedZoneCommentRequest & request) slot
Updates the comment for a specified hosted
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1722 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateHostedZoneCommentResponse *>(send(request));
 }
updateTrafficPolicyComment
UpdateTrafficPolicyCommentResponse * QtAws::Route53::Route53Client::updateTrafficPolicyComment (const UpdateTrafficPolicyCommentRequest & request) slot
Updates the comment for a specified traffic policy
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1736 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTrafficPolicyCommentResponse *>(send(request));
 }
updateTrafficPolicyInstance
UpdateTrafficPolicyInstanceResponse * QtAws::Route53::Route53Client::updateTrafficPolicyInstance (const UpdateTrafficPolicyInstanceRequest & request) slot
Updates the resource record sets in a specified hosted zone that were created based on the settings in a specified traffic policy
version>
When you update a traffic policy instance, Amazon Route 53 continues to respond to DNS queries for the root resource record set name (such as example.com) while it replaces one group of resource record sets with another. Amazon Route 53 performs the following
operations>
Amazon Route 53 creates a new group of resource record sets based on the specified traffic policy. This is true regardless of how significant the differences are between the existing resource record sets and the new resource record sets.
</p
When all of the new resource record sets have been created, Amazon Route 53 starts to respond to DNS queries for the root resource record set name (such as example.com) by using the new resource record
sets>
Amazon Route 53 deletes the old group of resource record sets that are associated with the root resource record set
Parameters
request Request to send to Amazon Route 53.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1772 of file route53client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTrafficPolicyInstanceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
route53/route53client.h
route53/route53client.cpp