AWS SDK for Qt: QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient Class Reference
QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient Class Reference
Client for AWSServerlessApplicationRepository.
Public Slots
CreateApplicationResponse * createApplication (const CreateApplicationRequest &request)
CreateApplicationVersionResponse * createApplicationVersion (const CreateApplicationVersionRequest &request)
CreateCloudFormationChangeSetResponse * createCloudFormationChangeSet (const CreateCloudFormationChangeSetRequest &request)
DeleteApplicationResponse * deleteApplication (const DeleteApplicationRequest &request)
GetApplicationResponse * getApplication (const GetApplicationRequest &request)
GetApplicationPolicyResponse * getApplicationPolicy (const GetApplicationPolicyRequest &request)
ListApplicationVersionsResponse * listApplicationVersions (const ListApplicationVersionsRequest &request)
ListApplicationsResponse * listApplications (const ListApplicationsRequest &request)
PutApplicationPolicyResponse * putApplicationPolicy (const PutApplicationPolicyRequest &request)
UpdateApplicationResponse * updateApplication (const UpdateApplicationRequest &request)
Public Member Functions
ServerlessApplicationRepositoryClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServerlessApplicationRepositoryClient object.
ServerlessApplicationRepositoryClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServerlessApplicationRepositoryClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWSServerlessApplicationRepository.
The AWS Serverless Application Repository makes it easy for developers and enterprises to quickly find and deploy serverless applications in the AWS Cloud. For more information about serverless applications, see Serverless Computing and Applications on the AWS website.
The AWS Serverless Application Repository is deeply integrated with the AWS Lambda console, so that developers of all levels can get started with serverless computing without needing to learn anything new. You can use category keywords to browse for applications such as web and mobile backends, data processing applications, or chatbots. You can also search for applications by name, publisher, or event source. To use an application, you simply choose it, configure any required fields, and deploy it with a few clicks.
You can also easily publish applications, sharing them publicly with the community at large, or privately within your team or across your organization. To publish a serverless application (or app), you can use the AWS Management Console, AWS Command Line Interface (AWS CLI), or AWS SDKs to upload the code. Along with the code, you upload a simple manifest file, also known as the AWS Serverless Application Model (AWS SAM) template. For more information about AWS SAM, see AWS Serverless Application Model (AWS SAM) on the AWS Labs GitHub repository.
The AWS Serverless Application Repository Developer Guide contains more information about the two developer experiences available:
Consuming Applications – Browse for applications and view information about them, including source code and readme files. Also install, configure, and deploy applications of your choosing.
</p
Publishing Applications – Configure and upload applications to make them available to other developers, and publish new versions of applications.
Definition at line 52 of file serverlessapplicationrepositoryclient.h.
Constructor & Destructor Documentation
ServerlessApplicationRepositoryClient() [1/2]
QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServerlessApplicationRepositoryClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 87 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ServerlessApplicationRepositoryClientPrivate(this), parent)
 {
     Q_D(ServerlessApplicationRepositoryClient);
     d->apiVersion = QStringLiteral("2017-09-08");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("serverlessrepo");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWSServerlessApplicationRepository");
     d->serviceName = QStringLiteral("serverlessrepo");
 }
ServerlessApplicationRepositoryClient() [2/2]
QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServerlessApplicationRepositoryClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 120 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ServerlessApplicationRepositoryClientPrivate(this), parent)
 {
     Q_D(ServerlessApplicationRepositoryClient);
     d->apiVersion = QStringLiteral("2017-09-08");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("serverlessrepo");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWSServerlessApplicationRepository");
     d->serviceName = QStringLiteral("serverlessrepo");
 }
Member Function Documentation
createApplication
CreateApplicationResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createApplication (const CreateApplicationRequest & request) slot
Creates an application, optionally including an AWS SAM file to create the first application version in the same
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 146 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateApplicationResponse *>(send(request));
 }
createApplicationVersion
CreateApplicationVersionResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createApplicationVersion (const CreateApplicationVersionRequest & request) slot
Creates an application
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 160 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateApplicationVersionResponse *>(send(request));
 }
createCloudFormationChangeSet
CreateCloudFormationChangeSetResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createCloudFormationChangeSet (const CreateCloudFormationChangeSetRequest & request) slot
Creates an AWS CloudFormation ChangeSet for the given
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 174 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCloudFormationChangeSetResponse *>(send(request));
 }
deleteApplication
DeleteApplicationResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::deleteApplication (const DeleteApplicationRequest & request) slot
Deletes the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 188 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationResponse *>(send(request));
 }
getApplication
GetApplicationResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::getApplication (const GetApplicationRequest & request) slot
Gets the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 202 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApplicationResponse *>(send(request));
 }
getApplicationPolicy
GetApplicationPolicyResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::getApplicationPolicy (const GetApplicationPolicyRequest & request) slot
Gets the policy for the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApplicationPolicyResponse *>(send(request));
 }
listApplications
ListApplicationsResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::listApplications (const ListApplicationsRequest & request) slot
Lists applications owned by the
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 244 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListApplicationsResponse *>(send(request));
 }
listApplicationVersions
ListApplicationVersionsResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::listApplicationVersions (const ListApplicationVersionsRequest & request) slot
Lists versions for the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListApplicationVersionsResponse *>(send(request));
 }
putApplicationPolicy
PutApplicationPolicyResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::putApplicationPolicy (const PutApplicationPolicyRequest & request) slot
Puts the policy for the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 258 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutApplicationPolicyResponse *>(send(request));
 }
updateApplication
UpdateApplicationResponse * QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::updateApplication (const UpdateApplicationRequest & request) slot
Updates the specified
Parameters
request Request to send to AWSServerlessApplicationRepository.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 272 of file serverlessapplicationrepositoryclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApplicationResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
serverlessrepo/serverlessapplicationrepositoryclient.h
serverlessrepo/serverlessapplicationrepositoryclient.cpp