AWS SDK for Qt: QtAws::Comprehend::ComprehendClient Class Reference
QtAws::Comprehend::ComprehendClient Class Reference
Client for Amazon Comprehend.
Public Slots
BatchDetectDominantLanguageResponse * batchDetectDominantLanguage (const BatchDetectDominantLanguageRequest &request)
BatchDetectEntitiesResponse * batchDetectEntities (const BatchDetectEntitiesRequest &request)
BatchDetectKeyPhrasesResponse * batchDetectKeyPhrases (const BatchDetectKeyPhrasesRequest &request)
BatchDetectSentimentResponse * batchDetectSentiment (const BatchDetectSentimentRequest &request)
DescribeTopicsDetectionJobResponse * describeTopicsDetectionJob (const DescribeTopicsDetectionJobRequest &request)
DetectDominantLanguageResponse * detectDominantLanguage (const DetectDominantLanguageRequest &request)
DetectEntitiesResponse * detectEntities (const DetectEntitiesRequest &request)
DetectKeyPhrasesResponse * detectKeyPhrases (const DetectKeyPhrasesRequest &request)
DetectSentimentResponse * detectSentiment (const DetectSentimentRequest &request)
ListTopicsDetectionJobsResponse * listTopicsDetectionJobs (const ListTopicsDetectionJobsRequest &request)
StartTopicsDetectionJobResponse * startTopicsDetectionJob (const StartTopicsDetectionJobRequest &request)
Public Member Functions
ComprehendClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ComprehendClient object.
ComprehendClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ComprehendClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Comprehend.
Amazon Comprehend is an AWS service for gaining insight into the content of documents. Use these actions to determine the topics contained in your documents, the topics they discuss, the predominant sentiment expressed in them, the predominant language used, and
Definition at line 54 of file comprehendclient.h.
Constructor & Destructor Documentation
ComprehendClient() [1/2]
QtAws::Comprehend::ComprehendClient::ComprehendClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ComprehendClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 71 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ComprehendClientPrivate(this), parent)
 {
     Q_D(ComprehendClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("comprehend");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Comprehend");
     d->serviceName = QStringLiteral("comprehend");
 }
ComprehendClient() [2/2]
QtAws::Comprehend::ComprehendClient::ComprehendClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ComprehendClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 104 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ComprehendClientPrivate(this), parent)
 {
     Q_D(ComprehendClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("comprehend");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Comprehend");
     d->serviceName = QStringLiteral("comprehend");
 }
Member Function Documentation
batchDetectDominantLanguage
BatchDetectDominantLanguageResponse * QtAws::Comprehend::ComprehendClient::batchDetectDominantLanguage (const BatchDetectDominantLanguageRequest & request) slot
Determines the dominant language of the input text for a batch of documents. For a list of languages that Amazon Comprehend can detect, see Amazon Comprehend Supported Languages.
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 132 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDetectDominantLanguageResponse *>(send(request));
 }
batchDetectEntities
BatchDetectEntitiesResponse * QtAws::Comprehend::ComprehendClient::batchDetectEntities (const BatchDetectEntitiesRequest & request) slot
Inspects the text of a batch of documents and returns information about them. For more information about entities, see how-entities
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 147 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDetectEntitiesResponse *>(send(request));
 }
batchDetectKeyPhrases
BatchDetectKeyPhrasesResponse * QtAws::Comprehend::ComprehendClient::batchDetectKeyPhrases (const BatchDetectKeyPhrasesRequest & request) slot
Detects the key noun phrases found in a batch of
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 161 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDetectKeyPhrasesResponse *>(send(request));
 }
batchDetectSentiment
BatchDetectSentimentResponse * QtAws::Comprehend::ComprehendClient::batchDetectSentiment (const BatchDetectSentimentRequest & request) slot
Inspects a batch of documents and returns an inference of the prevailing sentiment, POSITIVE, NEUTRAL, MIXED, or NEGATIVE, in each
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 176 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDetectSentimentResponse *>(send(request));
 }
describeTopicsDetectionJob
DescribeTopicsDetectionJobResponse * QtAws::Comprehend::ComprehendClient::describeTopicsDetectionJob (const DescribeTopicsDetectionJobRequest & request) slot
Gets the properties associated with a topic detection job. Use this operation to get the status of a detection
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 190 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTopicsDetectionJobResponse *>(send(request));
 }
detectDominantLanguage
DetectDominantLanguageResponse * QtAws::Comprehend::ComprehendClient::detectDominantLanguage (const DetectDominantLanguageRequest & request) slot
Determines the dominant language of the input text. For a list of languages that Amazon Comprehend can detect, see Amazon Comprehend Supported Languages.
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 205 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetectDominantLanguageResponse *>(send(request));
 }
detectEntities
DetectEntitiesResponse * QtAws::Comprehend::ComprehendClient::detectEntities (const DetectEntitiesRequest & request) slot
Inspects text for entities, and returns information about them. For more information, about entities, see how-entities.
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 220 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetectEntitiesResponse *>(send(request));
 }
detectKeyPhrases
DetectKeyPhrasesResponse * QtAws::Comprehend::ComprehendClient::detectKeyPhrases (const DetectKeyPhrasesRequest & request) slot
Detects the key noun phrases found in the text.
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 234 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetectKeyPhrasesResponse *>(send(request));
 }
detectSentiment
DetectSentimentResponse * QtAws::Comprehend::ComprehendClient::detectSentiment (const DetectSentimentRequest & request) slot
Inspects text and returns an inference of the prevailing sentiment (POSITIVE, NEUTRAL, MIXED, or NEGATIVE).
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 249 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetectSentimentResponse *>(send(request));
 }
listTopicsDetectionJobs
ListTopicsDetectionJobsResponse * QtAws::Comprehend::ComprehendClient::listTopicsDetectionJobs (const ListTopicsDetectionJobsRequest & request) slot
Gets a list of the topic detection jobs that you have
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 263 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTopicsDetectionJobsResponse *>(send(request));
 }
startTopicsDetectionJob
StartTopicsDetectionJobResponse * QtAws::Comprehend::ComprehendClient::startTopicsDetectionJob (const StartTopicsDetectionJobRequest & request) slot
Starts an asynchronous topic detection job. Use the DescribeTopicDetectionJob operation to track the status of a
Parameters
request Request to send to Amazon Comprehend.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file comprehendclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartTopicsDetectionJobResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
comprehend/comprehendclient.h
comprehend/comprehendclient.cpp