AWS SDK for Qt: QtAws::TranscribeService::TranscribeServiceRequest Class Reference
QtAws::TranscribeService::TranscribeServiceRequest Class Reference
Interface class for providing TranscribeService requests.
Public Types
enum Action { GetTranscriptionJobAction, ListTranscriptionJobsAction, StartTranscriptionJobAction }
Actions supported by TranscribeService.
Public Member Functions
TranscribeServiceRequest (const Action action)
Constructs a new TranscribeServiceRequest object.
TranscribeServiceRequest (const TranscribeServiceRequest &other)
Constructs a new TranscribeServiceRequest object by copying another.
TranscribeServiceRequest & operator= (const TranscribeServiceRequest &other)
Assignment operator.
Action action () const
Get the TranscribeService action to be performed by this request.
QString actionString () const
Get the name of the TranscribeService action to be performed by this request.
QString apiVersion () const
Get the TranscribeService API version implemented by this request.
void setAction (const Action action)
Set the TranscribeService action to be performed by this request.
void setApiVersion (const QString &version)
Set the TranscribeService API version to include in this request.
virtual bool operator== (const TranscribeServiceRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
TranscribeServiceRequest (TranscribeServiceRequestPrivate *const d)
Constructs a new TranscribeServiceRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid TranscribeService queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this TranscribeService request.
const QVariantMap & parameters () const
Get all parameters included with this TranscribeService request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this TranscribeService request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this TranscribeService request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this TranscribeService request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing TranscribeService requests.
Definition at line 35 of file transcribeservicerequest.h.
Constructor & Destructor Documentation
TranscribeServiceRequest() [1/3]
QtAws::TranscribeService::TranscribeServiceRequest::TranscribeServiceRequest (const Action action)
Constructs a new TranscribeServiceRequest object.
Parameters
action The TranscribeService action to request.
Definition at line 38 of file transcribeservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new TranscribeServiceRequestPrivate(action, this))
 {
 }
TranscribeServiceRequest() [2/3]
QtAws::TranscribeService::TranscribeServiceRequest::TranscribeServiceRequest (const TranscribeServiceRequest & other)
Constructs a new TranscribeServiceRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file transcribeservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new TranscribeServiceRequestPrivate(*other.d_func(), this))
 {
 }
TranscribeServiceRequest() [3/3]
QtAws::TranscribeService::TranscribeServiceRequest::TranscribeServiceRequest (TranscribeServiceRequestPrivate *const d) protected
Constructs a new TranscribeServiceRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from TranscribeServiceRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file transcribeservicerequest.cpp.
                                                                                             : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
TranscribeServiceRequest::Action QtAws::TranscribeService::TranscribeServiceRequest::action () const
Get the TranscribeService action to be performed by this request.
Returns
The TranscribeService action to be performed by this request.
Definition at line 93 of file transcribeservicerequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const TranscribeServiceRequest);
     return d->action;
 }
actionString()
QString QtAws::TranscribeService::TranscribeServiceRequest::actionString () const
Get the name of the TranscribeService action to be performed by this request.
Returns
The name of the TranscribeService action to be performed by this request.
Definition at line 104 of file transcribeservicerequest.cpp.
References action(), and QtAws::TranscribeService::TranscribeServiceRequestPrivate::toString().
 {
     return TranscribeServiceRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::TranscribeService::TranscribeServiceRequest::apiVersion () const
Get the TranscribeService API version implemented by this request.
Returns
The TranscribeService API version implmented by this request.
Definition at line 114 of file transcribeservicerequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const TranscribeServiceRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::TranscribeService::TranscribeServiceRequest::clearParameter (const QString & name) protected
Check if queueName is a valid TranscribeService queue name.
From TranscribeService FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid TranscribeService queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file transcribeservicerequest.cpp.
 {
     Q_D(TranscribeServiceRequest);
     return d->parameters.remove(name);
 }
operator=()
TranscribeServiceRequest & QtAws::TranscribeService::TranscribeServiceRequest::operator= (const TranscribeServiceRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file transcribeservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(TranscribeServiceRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::TranscribeService::TranscribeServiceRequest::operator== (const TranscribeServiceRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file transcribeservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::TranscribeService::TranscribeServiceRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this TranscribeService request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file transcribeservicerequest.cpp.
 {
     Q_D(const TranscribeServiceRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::TranscribeService::TranscribeServiceRequest::parameters () const protected
Get all parameters included with this TranscribeService request.
Returns
A map of parameters included with this request.
Definition at line 222 of file transcribeservicerequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const TranscribeServiceRequest);
     return d->parameters;
 }
setAction()
void QtAws::TranscribeService::TranscribeServiceRequest::setAction (const Action action)
Set the TranscribeService action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file transcribeservicerequest.cpp.
References action().
 {
     Q_D(TranscribeServiceRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::TranscribeService::TranscribeServiceRequest::setApiVersion (const QString & version)
Set the TranscribeService API version to include in this request.
Parameters
version The TranscribeService API version to include in this request.
Definition at line 136 of file transcribeservicerequest.cpp.
 {
     Q_D(TranscribeServiceRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::TranscribeService::TranscribeServiceRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this TranscribeService request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file transcribeservicerequest.cpp.
 {
     Q_D(TranscribeServiceRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::TranscribeService::TranscribeServiceRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this TranscribeService request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file transcribeservicerequest.cpp.
References parameters().
 {
     Q_D(TranscribeServiceRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::TranscribeService::TranscribeServiceRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this TranscribeService request.
This TranscribeService implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this TranscribeService request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file transcribeservicerequest.cpp.
 {
     Q_D(const TranscribeServiceRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
transcribe/transcribeservicerequest.h
transcribe/transcribeservicerequest.cpp