AWS SDK for Qt: QtAws::OpsWorks::OpsWorksClient Class Reference
QtAws::OpsWorks::OpsWorksClient Class Reference
Client for AWS OpsWorks.
Public Slots
AssignInstanceResponse * assignInstance (const AssignInstanceRequest &request)
AssignVolumeResponse * assignVolume (const AssignVolumeRequest &request)
AssociateElasticIpResponse * associateElasticIp (const AssociateElasticIpRequest &request)
AttachElasticLoadBalancerResponse * attachElasticLoadBalancer (const AttachElasticLoadBalancerRequest &request)
CloneStackResponse * cloneStack (const CloneStackRequest &request)
CreateAppResponse * createApp (const CreateAppRequest &request)
CreateDeploymentResponse * createDeployment (const CreateDeploymentRequest &request)
CreateInstanceResponse * createInstance (const CreateInstanceRequest &request)
CreateLayerResponse * createLayer (const CreateLayerRequest &request)
CreateStackResponse * createStack (const CreateStackRequest &request)
CreateUserProfileResponse * createUserProfile (const CreateUserProfileRequest &request)
DeleteAppResponse * deleteApp (const DeleteAppRequest &request)
DeleteInstanceResponse * deleteInstance (const DeleteInstanceRequest &request)
DeleteLayerResponse * deleteLayer (const DeleteLayerRequest &request)
DeleteStackResponse * deleteStack (const DeleteStackRequest &request)
DeleteUserProfileResponse * deleteUserProfile (const DeleteUserProfileRequest &request)
DeregisterEcsClusterResponse * deregisterEcsCluster (const DeregisterEcsClusterRequest &request)
DeregisterElasticIpResponse * deregisterElasticIp (const DeregisterElasticIpRequest &request)
DeregisterInstanceResponse * deregisterInstance (const DeregisterInstanceRequest &request)
DeregisterRdsDbInstanceResponse * deregisterRdsDbInstance (const DeregisterRdsDbInstanceRequest &request)
DeregisterVolumeResponse * deregisterVolume (const DeregisterVolumeRequest &request)
DescribeAgentVersionsResponse * describeAgentVersions (const DescribeAgentVersionsRequest &request)
DescribeAppsResponse * describeApps (const DescribeAppsRequest &request)
DescribeCommandsResponse * describeCommands (const DescribeCommandsRequest &request)
DescribeDeploymentsResponse * describeDeployments (const DescribeDeploymentsRequest &request)
DescribeEcsClustersResponse * describeEcsClusters (const DescribeEcsClustersRequest &request)
DescribeElasticIpsResponse * describeElasticIps (const DescribeElasticIpsRequest &request)
DescribeElasticLoadBalancersResponse * describeElasticLoadBalancers (const DescribeElasticLoadBalancersRequest &request)
DescribeInstancesResponse * describeInstances (const DescribeInstancesRequest &request)
DescribeLayersResponse * describeLayers (const DescribeLayersRequest &request)
DescribeLoadBasedAutoScalingResponse * describeLoadBasedAutoScaling (const DescribeLoadBasedAutoScalingRequest &request)
DescribeMyUserProfileResponse * describeMyUserProfile ()
DescribeOperatingSystemsResponse * describeOperatingSystems ()
DescribePermissionsResponse * describePermissions (const DescribePermissionsRequest &request)
DescribeRaidArraysResponse * describeRaidArrays (const DescribeRaidArraysRequest &request)
DescribeRdsDbInstancesResponse * describeRdsDbInstances (const DescribeRdsDbInstancesRequest &request)
DescribeServiceErrorsResponse * describeServiceErrors (const DescribeServiceErrorsRequest &request)
DescribeStackProvisioningParametersResponse * describeStackProvisioningParameters (const DescribeStackProvisioningParametersRequest &request)
DescribeStackSummaryResponse * describeStackSummary (const DescribeStackSummaryRequest &request)
DescribeStacksResponse * describeStacks (const DescribeStacksRequest &request)
DescribeTimeBasedAutoScalingResponse * describeTimeBasedAutoScaling (const DescribeTimeBasedAutoScalingRequest &request)
DescribeUserProfilesResponse * describeUserProfiles (const DescribeUserProfilesRequest &request)
DescribeVolumesResponse * describeVolumes (const DescribeVolumesRequest &request)
DetachElasticLoadBalancerResponse * detachElasticLoadBalancer (const DetachElasticLoadBalancerRequest &request)
DisassociateElasticIpResponse * disassociateElasticIp (const DisassociateElasticIpRequest &request)
GetHostnameSuggestionResponse * getHostnameSuggestion (const GetHostnameSuggestionRequest &request)
GrantAccessResponse * grantAccess (const GrantAccessRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
RebootInstanceResponse * rebootInstance (const RebootInstanceRequest &request)
RegisterEcsClusterResponse * registerEcsCluster (const RegisterEcsClusterRequest &request)
RegisterElasticIpResponse * registerElasticIp (const RegisterElasticIpRequest &request)
RegisterInstanceResponse * registerInstance (const RegisterInstanceRequest &request)
RegisterRdsDbInstanceResponse * registerRdsDbInstance (const RegisterRdsDbInstanceRequest &request)
RegisterVolumeResponse * registerVolume (const RegisterVolumeRequest &request)
SetLoadBasedAutoScalingResponse * setLoadBasedAutoScaling (const SetLoadBasedAutoScalingRequest &request)
SetPermissionResponse * setPermission (const SetPermissionRequest &request)
SetTimeBasedAutoScalingResponse * setTimeBasedAutoScaling (const SetTimeBasedAutoScalingRequest &request)
StartInstanceResponse * startInstance (const StartInstanceRequest &request)
StartStackResponse * startStack (const StartStackRequest &request)
StopInstanceResponse * stopInstance (const StopInstanceRequest &request)
StopStackResponse * stopStack (const StopStackRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UnassignInstanceResponse * unassignInstance (const UnassignInstanceRequest &request)
UnassignVolumeResponse * unassignVolume (const UnassignVolumeRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateAppResponse * updateApp (const UpdateAppRequest &request)
UpdateElasticIpResponse * updateElasticIp (const UpdateElasticIpRequest &request)
UpdateInstanceResponse * updateInstance (const UpdateInstanceRequest &request)
UpdateLayerResponse * updateLayer (const UpdateLayerRequest &request)
UpdateMyUserProfileResponse * updateMyUserProfile (const UpdateMyUserProfileRequest &request)
UpdateRdsDbInstanceResponse * updateRdsDbInstance (const UpdateRdsDbInstanceRequest &request)
UpdateStackResponse * updateStack (const UpdateStackRequest &request)
UpdateUserProfileResponse * updateUserProfile (const UpdateUserProfileRequest &request)
UpdateVolumeResponse * updateVolume (const UpdateVolumeRequest &request)
Public Member Functions
OpsWorksClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksClient object.
OpsWorksClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS OpsWorks.
<fullname>AWS OpsWorks</fullname>
Welcome to the AWS OpsWorks Stacks API Reference. This guide provides descriptions, syntax, and usage examples for AWS OpsWorks Stacks actions and data types, including common parameters and error codes.
</p
AWS OpsWorks Stacks is an application management service that provides an integrated experience for overseeing the complete application lifecycle. For information about this product, go to the AWS OpsWorks details page.
</p
SDKs and CLI
</p
The most common way to use the AWS OpsWorks Stacks API is by using the AWS Command Line Interface (CLI) or by using one of the AWS SDKs to implement applications in your preferred language. For more information,
see>
AWS CLI
</p
AWS SDK for Java
</p
AWS SDK for .NET
</p
AWS SDK for PHP 2
</p
AWS SDK for Ruby
</p
AWS SDK for Node.js
</p
AWS SDK for Python(Boto)
</p
Endpoints
</p
AWS OpsWorks Stacks supports the following endpoints, all HTTPS. You must connect to one of the following endpoints. Stacks can only be accessed or managed within the endpoint in which they are
created>
opsworks.us-east-1.amazonaws.co>
opsworks.us-east-2.amazonaws.co>
opsworks.us-west-1.amazonaws.co>
opsworks.us-west-2.amazonaws.co>
opsworks.ca-central-1.amazonaws.com (API only; not available in the AWS
console>
opsworks.eu-west-1.amazonaws.co>
opsworks.eu-west-2.amazonaws.co>
opsworks.eu-west-3.amazonaws.co>
opsworks.eu-central-1.amazonaws.co>
opsworks.ap-northeast-1.amazonaws.co>
opsworks.ap-northeast-2.amazonaws.co>
opsworks.ap-south-1.amazonaws.co>
opsworks.ap-southeast-1.amazonaws.co>
opsworks.ap-southeast-2.amazonaws.co>
opsworks.sa-east-1.amazonaws.co>
Chef Versions
</p
When you call CreateStack, CloneStack, or UpdateStack we recommend you use the ConfigurationManager parameter to specify the Chef version. The recommended and default value for Linux stacks is currently 12. Windows stacks use Chef 12.2. For more information, see Chef Versions> <note>
You can specify Chef 12, 11.10, or 11.4 for your Linux stack. We recommend migrating your existing Linux stacks to Chef 12 as soon as
Definition at line 178 of file opsworksclient.h.
Constructor & Destructor Documentation
OpsWorksClient() [1/2]
QtAws::OpsWorks::OpsWorksClient::OpsWorksClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 298 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new OpsWorksClientPrivate(this), parent)
 {
     Q_D(OpsWorksClient);
     d->apiVersion = QStringLiteral("2013-02-18");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("opsworks");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS OpsWorks");
     d->serviceName = QStringLiteral("opsworks");
 }
OpsWorksClient() [2/2]
QtAws::OpsWorks::OpsWorksClient::OpsWorksClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 331 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new OpsWorksClientPrivate(this), parent)
 {
     Q_D(OpsWorksClient);
     d->apiVersion = QStringLiteral("2013-02-18");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("opsworks");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS OpsWorks");
     d->serviceName = QStringLiteral("opsworks");
 }
Member Function Documentation
assignInstance
AssignInstanceResponse * QtAws::OpsWorks::OpsWorksClient::assignInstance (const AssignInstanceRequest & request) slot
Assign a registered instance to a
layer>
You can assign registered on-premises instances to any layer
type>
You can assign registered Amazon EC2 instances only to custom
layers>
You cannot use this action with instances that were created with AWS OpsWorks
Stacks>
Required Permissions: To use this action, an AWS Identity and Access Management (IAM) user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 376 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssignInstanceResponse *>(send(request));
 }
assignVolume
AssignVolumeResponse * QtAws::OpsWorks::OpsWorksClient::assignVolume (const AssignVolumeRequest & request) slot
Assigns one of the stack's registered Amazon EBS volumes to a specified instance. The volume must first be registered with the stack by calling RegisterVolume. After you register the volume, you must call UpdateVolume to specify a mount point before calling AssignVolume. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 399 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssignVolumeResponse *>(send(request));
 }
associateElasticIp
AssociateElasticIpResponse * QtAws::OpsWorks::OpsWorksClient::associateElasticIp (const AssociateElasticIpRequest & request) slot
Associates one of the stack's registered Elastic IP addresses with a specified instance. The address must first be registered with the stack by calling RegisterElasticIp. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 421 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateElasticIpResponse *>(send(request));
 }
attachElasticLoadBalancer
AttachElasticLoadBalancerResponse * QtAws::OpsWorks::OpsWorksClient::attachElasticLoadBalancer (const AttachElasticLoadBalancerRequest & request) slot
Attaches an Elastic Load Balancing load balancer to a specified layer. AWS OpsWorks Stacks does not support Application Load Balancer. You can only use Classic Load Balancer with AWS OpsWorks Stacks. For more information, see Elastic Load Balancing> <note>
You must create the Elastic Load Balancing instance separately, by using the Elastic Load Balancing console, API, or CLI. For more information, see Elastic Load Balancing Developer Guide> </note>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 450 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachElasticLoadBalancerResponse *>(send(request));
 }
cloneStack
CloneStackResponse * QtAws::OpsWorks::OpsWorksClient::cloneStack (const CloneStackRequest & request) slot
Creates a clone of a specified stack. For more information, see Clone a Stack. By default, all parameters are set to the values used by the parent
stack>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 472 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CloneStackResponse *>(send(request));
 }
createApp
CreateAppResponse * QtAws::OpsWorks::OpsWorksClient::createApp (const CreateAppRequest & request) slot
Creates an app for a specified stack. For more information, see Creating Apps>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 493 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAppResponse *>(send(request));
 }
createDeployment
CreateDeploymentResponse * QtAws::OpsWorks::OpsWorksClient::createDeployment (const CreateDeploymentRequest & request) slot
Runs deployment or stack commands. For more information, see Deploying Apps and Run Stack Commands>
Required Permissions: To use this action, an IAM user must have a Deploy or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 515 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDeploymentResponse *>(send(request));
 }
createInstance
CreateInstanceResponse * QtAws::OpsWorks::OpsWorksClient::createInstance (const CreateInstanceRequest & request) slot
Creates an instance in a specified stack. For more information, see Adding an Instance to a Layer>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 536 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInstanceResponse *>(send(request));
 }
createLayer
CreateLayerResponse * QtAws::OpsWorks::OpsWorksClient::createLayer (const CreateLayerRequest & request) slot
Creates a layer. For more information, see How to Create a Layer> <note>
You should use CreateLayer for noncustom layer types such as PHP App Server only if the stack does not have an existing layer of that type. A stack can have at most one instance of each noncustom layer; if you attempt to create a second instance, CreateLayer fails. A stack can have an arbitrary number of custom layers, so you can call CreateLayer as many times as you like for that layer
type> </note>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 564 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLayerResponse *>(send(request));
 }
createStack
CreateStackResponse * QtAws::OpsWorks::OpsWorksClient::createStack (const CreateStackRequest & request) slot
Creates a new stack. For more information, see Create a New Stack>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 585 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStackResponse *>(send(request));
 }
createUserProfile
CreateUserProfileResponse * QtAws::OpsWorks::OpsWorksClient::createUserProfile (const CreateUserProfileRequest & request) slot
Creates a new user
profile>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 605 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserProfileResponse *>(send(request));
 }
deleteApp
DeleteAppResponse * QtAws::OpsWorks::OpsWorksClient::deleteApp (const DeleteAppRequest & request) slot
Deletes a specified
app>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 625 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAppResponse *>(send(request));
 }
deleteInstance
DeleteInstanceResponse * QtAws::OpsWorks::OpsWorksClient::deleteInstance (const DeleteInstanceRequest & request) slot
Deletes a specified instance, which terminates the associated Amazon EC2 instance. You must stop an instance before you can delete
it>
For more information, see Deleting Instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 651 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInstanceResponse *>(send(request));
 }
deleteLayer
DeleteLayerResponse * QtAws::OpsWorks::OpsWorksClient::deleteLayer (const DeleteLayerRequest & request) slot
Deletes a specified layer. You must first stop and then delete all associated instances or unassign registered instances. For more information, see How to Delete a Layer>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 673 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLayerResponse *>(send(request));
 }
deleteStack
DeleteStackResponse * QtAws::OpsWorks::OpsWorksClient::deleteStack (const DeleteStackRequest & request) slot
Deletes a specified stack. You must first delete all instances, layers, and apps or deregister registered instances. For more information, see Shut Down a Stack>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 695 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStackResponse *>(send(request));
 }
deleteUserProfile
DeleteUserProfileResponse * QtAws::OpsWorks::OpsWorksClient::deleteUserProfile (const DeleteUserProfileRequest & request) slot
Deletes a user
profile>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 715 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserProfileResponse *>(send(request));
 }
deregisterEcsCluster
DeregisterEcsClusterResponse * QtAws::OpsWorks::OpsWorksClient::deregisterEcsCluster (const DeregisterEcsClusterRequest & request) slot
Deregisters a specified Amazon ECS cluster from a stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see <a
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 736 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterEcsClusterResponse *>(send(request));
 }
deregisterElasticIp
DeregisterElasticIpResponse * QtAws::OpsWorks::OpsWorksClient::deregisterElasticIp (const DeregisterElasticIpRequest & request) slot
Deregisters a specified Elastic IP address. The address can then be registered by another stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 757 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterElasticIpResponse *>(send(request));
 }
deregisterInstance
DeregisterInstanceResponse * QtAws::OpsWorks::OpsWorksClient::deregisterInstance (const DeregisterInstanceRequest & request) slot
Deregister a registered Amazon EC2 or on-premises instance. This action removes the instance from the stack and returns it to your control. This action can not be used with instances that were created with AWS OpsWorks
Stacks>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 778 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterInstanceResponse *>(send(request));
 }
deregisterRdsDbInstance
DeregisterRdsDbInstanceResponse * QtAws::OpsWorks::OpsWorksClient::deregisterRdsDbInstance (const DeregisterRdsDbInstanceRequest & request) slot
Deregisters an Amazon RDS
instance>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 798 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterRdsDbInstanceResponse *>(send(request));
 }
deregisterVolume
DeregisterVolumeResponse * QtAws::OpsWorks::OpsWorksClient::deregisterVolume (const DeregisterVolumeRequest & request) slot
Deregisters an Amazon EBS volume. The volume can then be registered by another stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 819 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterVolumeResponse *>(send(request));
 }
describeAgentVersions
DescribeAgentVersionsResponse * QtAws::OpsWorks::OpsWorksClient::describeAgentVersions (const DescribeAgentVersionsRequest & request) slot
Describes the available AWS OpsWorks Stacks agent versions. You must specify a stack ID or a configuration manager. DescribeAgentVersions returns a list of available agent versions for the specified stack or configuration
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 834 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAgentVersionsResponse *>(send(request));
 }
describeApps
DescribeAppsResponse * QtAws::OpsWorks::OpsWorksClient::describeApps (const DescribeAppsRequest & request) slot
Requests a description of a specified set of
apps> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 858 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAppsResponse *>(send(request));
 }
describeCommands
DescribeCommandsResponse * QtAws::OpsWorks::OpsWorksClient::describeCommands (const DescribeCommandsRequest & request) slot
Describes the results of specified
commands> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 882 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCommandsResponse *>(send(request));
 }
describeDeployments
DescribeDeploymentsResponse * QtAws::OpsWorks::OpsWorksClient::describeDeployments (const DescribeDeploymentsRequest & request) slot
Requests a description of a specified set of
deployments> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 906 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDeploymentsResponse *>(send(request));
 }
describeEcsClusters
DescribeEcsClustersResponse * QtAws::OpsWorks::OpsWorksClient::describeEcsClusters (const DescribeEcsClustersRequest & request) slot
Describes Amazon ECS clusters that are registered with a stack. If you specify only a stack ID, you can use the MaxResults and NextToken parameters to paginate the response. However, AWS OpsWorks Stacks currently supports only one cluster per layer, so the result set has a maximum of one
element>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack or an attached policy that explicitly grants permission. For more information on user permissions, see Managing User Permissions>
This call accepts only one resource-identifying
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 932 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEcsClustersResponse *>(send(request));
 }
describeElasticIps
DescribeElasticIpsResponse * QtAws::OpsWorks::OpsWorksClient::describeElasticIps (const DescribeElasticIpsRequest & request) slot
Describes Elastic IP addresses> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 956 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticIpsResponse *>(send(request));
 }
describeElasticLoadBalancers
DescribeElasticLoadBalancersResponse * QtAws::OpsWorks::OpsWorksClient::describeElasticLoadBalancers (const DescribeElasticLoadBalancersRequest & request) slot
Describes a stack's Elastic Load Balancing
instances> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 980 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticLoadBalancersResponse *>(send(request));
 }
describeInstances
DescribeInstancesResponse * QtAws::OpsWorks::OpsWorksClient::describeInstances (const DescribeInstancesRequest & request) slot
Requests a description of a set of
instances> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1004 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstancesResponse *>(send(request));
 }
describeLayers
DescribeLayersResponse * QtAws::OpsWorks::OpsWorksClient::describeLayers (const DescribeLayersRequest & request) slot
Requests a description of one or more layers in a specified
stack> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1028 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLayersResponse *>(send(request));
 }
describeLoadBasedAutoScaling
DescribeLoadBasedAutoScalingResponse * QtAws::OpsWorks::OpsWorksClient::describeLoadBasedAutoScaling (const DescribeLoadBasedAutoScalingRequest & request) slot
Describes load-based auto scaling configurations for specified
layers> <note>
You must specify at least one of the
parameters> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1052 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBasedAutoScalingResponse *>(send(request));
 }
describeMyUserProfile
DescribeMyUserProfileResponse * QtAws::OpsWorks::OpsWorksClient::describeMyUserProfile () slot
Describes a user's SSH
information>
Required Permissions: To use this action, an IAM user must have self-management enabled or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1072 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMyUserProfileResponse *>(send(request));
 }
describeOperatingSystems
DescribeOperatingSystemsResponse * QtAws::OpsWorks::OpsWorksClient::describeOperatingSystems () slot
Describes the operating systems that are supported by AWS OpsWorks
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1086 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOperatingSystemsResponse *>(send(request));
 }
describePermissions
DescribePermissionsResponse * QtAws::OpsWorks::OpsWorksClient::describePermissions (const DescribePermissionsRequest & request) slot
Describes the permissions for a specified
stack>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1106 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePermissionsResponse *>(send(request));
 }
describeRaidArrays
DescribeRaidArraysResponse * QtAws::OpsWorks::OpsWorksClient::describeRaidArrays (const DescribeRaidArraysRequest & request) slot
Describe an instance's RAID
arrays> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1130 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRaidArraysResponse *>(send(request));
 }
describeRdsDbInstances
DescribeRdsDbInstancesResponse * QtAws::OpsWorks::OpsWorksClient::describeRdsDbInstances (const DescribeRdsDbInstancesRequest & request) slot
Describes Amazon RDS
instances>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User Permissions>
This call accepts only one resource-identifying
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1154 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRdsDbInstancesResponse *>(send(request));
 }
describeServiceErrors
DescribeServiceErrorsResponse * QtAws::OpsWorks::OpsWorksClient::describeServiceErrors (const DescribeServiceErrorsRequest & request) slot
Describes AWS OpsWorks Stacks service
errors>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User Permissions>
This call accepts only one resource-identifying
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1178 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeServiceErrorsResponse *>(send(request));
 }
describeStackProvisioningParameters
DescribeStackProvisioningParametersResponse * QtAws::OpsWorks::OpsWorksClient::describeStackProvisioningParameters (const DescribeStackProvisioningParametersRequest & request) slot
Requests a description of a stack's provisioning
parameters>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1198 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackProvisioningParametersResponse *>(send(request));
 }
describeStacks
DescribeStacksResponse * QtAws::OpsWorks::OpsWorksClient::describeStacks (const DescribeStacksRequest & request) slot
Requests a description of one or more
stacks>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1239 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStacksResponse *>(send(request));
 }
describeStackSummary
DescribeStackSummaryResponse * QtAws::OpsWorks::OpsWorksClient::describeStackSummary (const DescribeStackSummaryRequest & request) slot
Describes the number of layers and apps in a specified stack, and the number of instances in each state, such as running_setup or
online>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1219 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStackSummaryResponse *>(send(request));
 }
describeTimeBasedAutoScaling
DescribeTimeBasedAutoScalingResponse * QtAws::OpsWorks::OpsWorksClient::describeTimeBasedAutoScaling (const DescribeTimeBasedAutoScalingRequest & request) slot
Describes time-based auto scaling configurations for specified
instances> <note>
You must specify at least one of the
parameters> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1263 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTimeBasedAutoScalingResponse *>(send(request));
 }
describeUserProfiles
DescribeUserProfilesResponse * QtAws::OpsWorks::OpsWorksClient::describeUserProfiles (const DescribeUserProfilesRequest & request) slot
Describe specified
users>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1283 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserProfilesResponse *>(send(request));
 }
describeVolumes
DescribeVolumesResponse * QtAws::OpsWorks::OpsWorksClient::describeVolumes (const DescribeVolumesRequest & request) slot
Describes an instance's Amazon EBS
volumes> <note>
This call accepts only one resource-identifying
parameter> </note>
Required Permissions: To use this action, an IAM user must have a Show, Deploy, or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1307 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVolumesResponse *>(send(request));
 }
detachElasticLoadBalancer
DetachElasticLoadBalancerResponse * QtAws::OpsWorks::OpsWorksClient::detachElasticLoadBalancer (const DetachElasticLoadBalancerRequest & request) slot
Detaches a specified Elastic Load Balancing instance from its
layer>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1327 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachElasticLoadBalancerResponse *>(send(request));
 }
disassociateElasticIp
DisassociateElasticIpResponse * QtAws::OpsWorks::OpsWorksClient::disassociateElasticIp (const DisassociateElasticIpRequest & request) slot
Disassociates an Elastic IP address from its instance. The address remains registered with the stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1348 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateElasticIpResponse *>(send(request));
 }
getHostnameSuggestion
GetHostnameSuggestionResponse * QtAws::OpsWorks::OpsWorksClient::getHostnameSuggestion (const GetHostnameSuggestionRequest & request) slot
Gets a generated host name for the specified layer, based on the current host name
theme>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1368 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHostnameSuggestionResponse *>(send(request));
 }
grantAccess
GrantAccessResponse * QtAws::OpsWorks::OpsWorksClient::grantAccess (const GrantAccessRequest & request) slot
<note>
This action can be used only with Windows
stacks> </note>
Grants RDP access to a Windows instance for a specified time
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1388 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GrantAccessResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::OpsWorks::OpsWorksClient::listTags (const ListTagsRequest & request) slot
Returns a list of tags that are applied to the specified stack or
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1402 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
rebootInstance
RebootInstanceResponse * QtAws::OpsWorks::OpsWorksClient::rebootInstance (const RebootInstanceRequest & request) slot
Reboots a specified instance. For more information, see Starting, Stopping, and Rebooting Instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1424 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootInstanceResponse *>(send(request));
 }
registerEcsCluster
RegisterEcsClusterResponse * QtAws::OpsWorks::OpsWorksClient::registerEcsCluster (const RegisterEcsClusterRequest & request) slot
Registers a specified Amazon ECS cluster with a stack. You can register only one cluster with a stack. A cluster can be registered with only one stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1446 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterEcsClusterResponse *>(send(request));
 }
registerElasticIp
RegisterElasticIpResponse * QtAws::OpsWorks::OpsWorksClient::registerElasticIp (const RegisterElasticIpRequest & request) slot
Registers an Elastic IP address with a specified stack. An address can be registered with only one stack at a time. If the address is already registered, you must first deregister it by calling DeregisterElasticIp. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1468 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterElasticIpResponse *>(send(request));
 }
registerInstance
RegisterInstanceResponse * QtAws::OpsWorks::OpsWorksClient::registerInstance (const RegisterInstanceRequest & request) slot
Registers instances that were created outside of AWS OpsWorks Stacks with a specified
stack> <note>
We do not recommend using this action to register instances. The complete registration operation includes two tasks: installing the AWS OpsWorks Stacks agent on the instance, and registering the instance with the stack. RegisterInstance handles only the second step. You should instead use the AWS CLI register command, which performs the entire registration operation. For more information, see Registering an Instance with an AWS OpsWorks Stacks Stack> </note>
Registered instances have the same requirements as instances that are created by using the CreateInstance API. For example, registered instances must be running a supported Linux-based operating system, and they must have a supported instance type. For more information about requirements for instances that you want to register, see Preparing the Instance>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1505 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterInstanceResponse *>(send(request));
 }
registerRdsDbInstance
RegisterRdsDbInstanceResponse * QtAws::OpsWorks::OpsWorksClient::registerRdsDbInstance (const RegisterRdsDbInstanceRequest & request) slot
Registers an Amazon RDS instance with a
stack>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1525 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterRdsDbInstanceResponse *>(send(request));
 }
registerVolume
RegisterVolumeResponse * QtAws::OpsWorks::OpsWorksClient::registerVolume (const RegisterVolumeRequest & request) slot
Registers an Amazon EBS volume with a specified stack. A volume can be registered with only one stack at a time. If the volume is already registered, you must first deregister it by calling DeregisterVolume. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1547 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterVolumeResponse *>(send(request));
 }
setLoadBasedAutoScaling
SetLoadBasedAutoScalingResponse * QtAws::OpsWorks::OpsWorksClient::setLoadBasedAutoScaling (const SetLoadBasedAutoScalingRequest & request) slot
Specify the load-based auto scaling configuration for a specified layer. For more information, see Managing Load with Time-based and Load-based Instances> <note>
To use load-based auto scaling, you must create a set of load-based auto scaling instances. Load-based auto scaling operates only on the instances from that set, so you must ensure that you have created enough instances to handle the maximum anticipated
load> </note>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1575 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetLoadBasedAutoScalingResponse *>(send(request));
 }
setPermission
SetPermissionResponse * QtAws::OpsWorks::OpsWorksClient::setPermission (const SetPermissionRequest & request) slot
Specifies a user's permissions. For more information, see Security and Permissions>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1596 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetPermissionResponse *>(send(request));
 }
setTimeBasedAutoScaling
SetTimeBasedAutoScalingResponse * QtAws::OpsWorks::OpsWorksClient::setTimeBasedAutoScaling (const SetTimeBasedAutoScalingRequest & request) slot
Specify the time-based auto scaling configuration for a specified instance. For more information, see Managing Load with Time-based and Load-based Instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1618 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetTimeBasedAutoScalingResponse *>(send(request));
 }
startInstance
StartInstanceResponse * QtAws::OpsWorks::OpsWorksClient::startInstance (const StartInstanceRequest & request) slot
Starts a specified instance. For more information, see Starting, Stopping, and Rebooting Instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1640 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartInstanceResponse *>(send(request));
 }
startStack
StartStackResponse * QtAws::OpsWorks::OpsWorksClient::startStack (const StartStackRequest & request) slot
Starts a stack's
instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1660 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartStackResponse *>(send(request));
 }
stopInstance
StopInstanceResponse * QtAws::OpsWorks::OpsWorksClient::stopInstance (const StopInstanceRequest & request) slot
Stops a specified instance. When you stop a standard instance, the data disappears and must be reinstalled when you restart the instance. You can stop an Amazon EBS-backed instance without losing data. For more information, see Starting, Stopping, and Rebooting Instances>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1683 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopInstanceResponse *>(send(request));
 }
stopStack
StopStackResponse * QtAws::OpsWorks::OpsWorksClient::stopStack (const StopStackRequest & request) slot
Stops a specified
stack>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1703 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopStackResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::OpsWorks::OpsWorksClient::tagResource (const TagResourceRequest & request) slot
Apply cost-allocation tags to a specified stack or layer in AWS OpsWorks Stacks. For more information about how tagging works, see Tags in the AWS OpsWorks User
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1718 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
unassignInstance
UnassignInstanceResponse * QtAws::OpsWorks::OpsWorksClient::unassignInstance (const UnassignInstanceRequest & request) slot
Unassigns a registered instance from all of it's layers. The instance remains in the stack as an unassigned instance and can be assigned to another layer, as needed. You cannot use this action with instances that were created with AWS OpsWorks
Stacks>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1740 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnassignInstanceResponse *>(send(request));
 }
unassignVolume
UnassignVolumeResponse * QtAws::OpsWorks::OpsWorksClient::unassignVolume (const UnassignVolumeRequest & request) slot
Unassigns an assigned Amazon EBS volume. The volume remains registered with the stack. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1761 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnassignVolumeResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::OpsWorks::OpsWorksClient::untagResource (const UntagResourceRequest & request) slot
Removes tags from a specified stack or
Parameters
request Request to send to AWS OpsWorks.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1775 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateApp
UpdateAppResponse * QtAws::OpsWorks::OpsWorksClient::updateApp (const UpdateAppRequest & request) slot
Updates a specified
app>
Required Permissions: To use this action, an IAM user must have a Deploy or Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1795 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAppResponse *>(send(request));
 }
updateElasticIp
UpdateElasticIpResponse * QtAws::OpsWorks::OpsWorksClient::updateElasticIp (const UpdateElasticIpRequest & request) slot
Updates a registered Elastic IP address's name. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1816 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateElasticIpResponse *>(send(request));
 }
updateInstance
UpdateInstanceResponse * QtAws::OpsWorks::OpsWorksClient::updateInstance (const UpdateInstanceRequest & request) slot
Updates a specified
instance>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1836 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateInstanceResponse *>(send(request));
 }
updateLayer
UpdateLayerResponse * QtAws::OpsWorks::OpsWorksClient::updateLayer (const UpdateLayerRequest & request) slot
Updates a specified
layer>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1856 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateLayerResponse *>(send(request));
 }
updateMyUserProfile
UpdateMyUserProfileResponse * QtAws::OpsWorks::OpsWorksClient::updateMyUserProfile (const UpdateMyUserProfileRequest & request) slot
Updates a user's SSH public
key>
Required Permissions: To use this action, an IAM user must have self-management enabled or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1876 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateMyUserProfileResponse *>(send(request));
 }
updateRdsDbInstance
UpdateRdsDbInstanceResponse * QtAws::OpsWorks::OpsWorksClient::updateRdsDbInstance (const UpdateRdsDbInstanceRequest & request) slot
Updates an Amazon RDS
instance>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1896 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRdsDbInstanceResponse *>(send(request));
 }
updateStack
UpdateStackResponse * QtAws::OpsWorks::OpsWorksClient::updateStack (const UpdateStackRequest & request) slot
Updates a specified
stack>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1916 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStackResponse *>(send(request));
 }
updateUserProfile
UpdateUserProfileResponse * QtAws::OpsWorks::OpsWorksClient::updateUserProfile (const UpdateUserProfileRequest & request) slot
Updates a specified user
profile>
Required Permissions: To use this action, an IAM user must have an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1936 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserProfileResponse *>(send(request));
 }
updateVolume
UpdateVolumeResponse * QtAws::OpsWorks::OpsWorksClient::updateVolume (const UpdateVolumeRequest & request) slot
Updates an Amazon EBS volume's name or mount point. For more information, see Resource Management>
Required Permissions: To use this action, an IAM user must have a Manage permissions level for the stack, or an attached policy that explicitly grants permissions. For more information on user permissions, see Managing User request Request to send to AWS OpsWorks. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1957 of file opsworksclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateVolumeResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
opsworks/opsworksclient.h
opsworks/opsworksclient.cpp