AWS SDK for Qt: QtAws::ImportExport::ImportExportClient Class Reference
QtAws::ImportExport::ImportExportClient Class Reference
Client for AWS Import/Export.
Public Slots
CancelJobResponse * cancelJob (const CancelJobRequest &request)
CreateJobResponse * createJob (const CreateJobRequest &request)
GetShippingLabelResponse * getShippingLabel (const GetShippingLabelRequest &request)
GetStatusResponse * getStatus (const GetStatusRequest &request)
ListJobsResponse * listJobs (const ListJobsRequest &request)
UpdateJobResponse * updateJob (const UpdateJobRequest &request)
Public Member Functions
ImportExportClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ImportExportClient object.
ImportExportClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ImportExportClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Import/Export.
<fullname>AWS Import/Export Service</fullname> AWS Import/Export accelerates transferring large amounts of data between the AWS cloud and portable storage devices that you mail to us. AWS Import/Export transfers data directly onto and off of your storage devices using Amazon's high-speed internal network and bypassing the Internet. For large data sets, AWS
Definition at line 44 of file importexportclient.h.
Constructor & Destructor Documentation
ImportExportClient() [1/2]
QtAws::ImportExport::ImportExportClient::ImportExportClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ImportExportClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 61 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ImportExportClientPrivate(this), parent)
 {
     Q_D(ImportExportClient);
     d->apiVersion = QStringLiteral("2010-06-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("importexport");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Import/Export");
     d->serviceName = QStringLiteral("importexport");
 }
ImportExportClient() [2/2]
QtAws::ImportExport::ImportExportClient::ImportExportClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ImportExportClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 94 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ImportExportClientPrivate(this), parent)
 {
     Q_D(ImportExportClient);
     d->apiVersion = QStringLiteral("2010-06-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("importexport");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Import/Export");
     d->serviceName = QStringLiteral("importexport");
 }
Member Function Documentation
cancelJob
CancelJobResponse * QtAws::ImportExport::ImportExportClient::cancelJob (const CancelJobRequest & request) slot
This operation cancels a specified job. Only the job owner can cancel it. The operation fails if the job has already
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 120 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelJobResponse *>(send(request));
 }
createJob
CreateJobResponse * QtAws::ImportExport::ImportExportClient::createJob (const CreateJobRequest & request) slot
This operation initiates the process of scheduling an upload or download of your data. You include in the request a manifest that describes the data transfer specifics. The response to the request includes a job ID, which you can use in other operations, a signature that you use to identify your storage device, and the address where you should ship your
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 136 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateJobResponse *>(send(request));
 }
getShippingLabel
GetShippingLabelResponse * QtAws::ImportExport::ImportExportClient::getShippingLabel (const GetShippingLabelRequest & request) slot
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 149 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetShippingLabelResponse *>(send(request));
 }
getStatus
GetStatusResponse * QtAws::ImportExport::ImportExportClient::getStatus (const GetStatusRequest & request) slot
This operation returns information about a job, including where the job is in the processing pipeline, the status of the
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 163 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStatusResponse *>(send(request));
 }
listJobs
ListJobsResponse * QtAws::ImportExport::ImportExportClient::listJobs (const ListJobsRequest & request) slot
This operation returns the jobs associated with the requester. AWS Import/Export lists the jobs in reverse chronological order based on the date of creation. For example if Job Test1 was created 2009Dec30 and Test2 was created 2010Feb05, the
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 178 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListJobsResponse *>(send(request));
 }
updateJob
UpdateJobResponse * QtAws::ImportExport::ImportExportClient::updateJob (const UpdateJobRequest & request) slot
You use this operation to change the parameters specified in the original manifest file by supplying a new manifest file. The manifest file attached to this request replaces the original manifest file. You can only use the operation
Parameters
request Request to send to AWS Import/Export.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 193 of file importexportclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateJobResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
importexport/importexportclient.h
importexport/importexportclient.cpp