AWS SDK for Qt: QtAws::KinesisVideo::KinesisVideoClient Class Reference
QtAws::KinesisVideo::KinesisVideoClient Class Reference
Client for Amazon Kinesis Video Streams.
Public Slots
CreateStreamResponse * createStream (const CreateStreamRequest &request)
DeleteStreamResponse * deleteStream (const DeleteStreamRequest &request)
DescribeStreamResponse * describeStream (const DescribeStreamRequest &request)
GetDataEndpointResponse * getDataEndpoint (const GetDataEndpointRequest &request)
ListStreamsResponse * listStreams (const ListStreamsRequest &request)
ListTagsForStreamResponse * listTagsForStream (const ListTagsForStreamRequest &request)
TagStreamResponse * tagStream (const TagStreamRequest &request)
UntagStreamResponse * untagStream (const UntagStreamRequest &request)
UpdateDataRetentionResponse * updateDataRetention (const UpdateDataRetentionRequest &request)
UpdateStreamResponse * updateStream (const UpdateStreamRequest &request)
Public Member Functions
KinesisVideoClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisVideoClient object.
KinesisVideoClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisVideoClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Kinesis Video Streams.
Definition at line 52 of file kinesisvideoclient.h.
Constructor & Destructor Documentation
KinesisVideoClient() [1/2]
QtAws::KinesisVideo::KinesisVideoClient::KinesisVideoClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisVideoClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 66 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new KinesisVideoClientPrivate(this), parent)
 {
     Q_D(KinesisVideoClient);
     d->apiVersion = QStringLiteral("2017-09-30");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("kinesisvideo");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Video Streams");
     d->serviceName = QStringLiteral("kinesisvideo");
 }
KinesisVideoClient() [2/2]
QtAws::KinesisVideo::KinesisVideoClient::KinesisVideoClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisVideoClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 99 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new KinesisVideoClientPrivate(this), parent)
 {
     Q_D(KinesisVideoClient);
     d->apiVersion = QStringLiteral("2017-09-30");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("kinesisvideo");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Video Streams");
     d->serviceName = QStringLiteral("kinesisvideo");
 }
Member Function Documentation
createStream
CreateStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::createStream (const CreateStreamRequest & request) slot
Creates a new Kinesis video stream.
</p
When you create a new stream, Kinesis Video Streams assigns it a version number. When you change the stream's metadata, Kinesis Video Streams updates the version.
</p
CreateStream is an asynchronous
operation>
For information about how the service works, see How it Works.
</p
You must have permissions for the KinesisVideo:CreateStream
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 143 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStreamResponse *>(send(request));
 }
deleteStream
DeleteStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::deleteStream (const DeleteStreamRequest & request) slot
Deletes a Kinesis video stream and the data contained in the stream.
</p
This method marks the stream for deletion, and makes the data in the stream inaccessible
immediately>
</p
To ensure that you have the latest version of the stream before deleting it, you can specify the stream version. Kinesis Video Streams assigns a version to each stream. When you update a stream, Kinesis Video Streams assigns a new version number. To get the latest stream version, use the DescribeStream API.
</p
This operation requires permission for the KinesisVideo:DeleteStream
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 174 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStreamResponse *>(send(request));
 }
describeStream
DescribeStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::describeStream (const DescribeStreamRequest & request) slot
Returns the most current information about the specified stream. You must specify either the StreamName or the StreamARN.
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 189 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStreamResponse *>(send(request));
 }
getDataEndpoint
GetDataEndpointResponse * QtAws::KinesisVideo::KinesisVideoClient::getDataEndpoint (const GetDataEndpointRequest & request) slot
Gets an endpoint for a specified stream for either reading or writing. Use this endpoint in your application to read from the specified stream (using the GetMedia or GetMediaForFragmentList operations) or write to it (using the PutMedia operation).
</p <note>
The returned endpoint does not have the API name appended. The client needs to add the API name to the returned
endpoint> </note>
In the request, specify the stream either by StreamName or
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 213 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDataEndpointResponse *>(send(request));
 }
listStreams
ListStreamsResponse * QtAws::KinesisVideo::KinesisVideoClient::listStreams (const ListStreamsRequest & request) slot
Returns an array of StreamInfo objects. Each object describes a stream. To retrieve only streams that satisfy a specific condition, you can specify a StreamNameCondition.
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 228 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStreamsResponse *>(send(request));
 }
listTagsForStream
ListTagsForStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::listTagsForStream (const ListTagsForStreamRequest & request) slot
Returns a list of tags associated with the specified
stream>
In the request, you must specify either the StreamName or the StreamARN.
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 246 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForStreamResponse *>(send(request));
 }
tagStream
TagStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::tagStream (const TagStreamRequest & request) slot
Adds one or more tags to a stream. A tag is a key-value pair (the value is optional) that you can define and assign to AWS resources. If you specify a tag that already exists, the tag value is replaced with the value that you specify in the request. For more information, see Using Cost Allocation Tags in the AWS Billing and Cost Management User Guide.
</p
You must provide either the StreamName or the
StreamARN>
This operation requires permission for the KinesisVideo:TagStream
action>
Kinesis video streams support up to 50
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 276 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagStreamResponse *>(send(request));
 }
untagStream
UntagStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::untagStream (const UntagStreamRequest & request) slot
Removes one or more tags from a stream. In the request, specify only a tag key or keys; don't specify the value. If you specify a tag key that does not exist, it's
ignored>
In the request, you must provide the StreamName or
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 295 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagStreamResponse *>(send(request));
 }
updateDataRetention
UpdateDataRetentionResponse * QtAws::KinesisVideo::KinesisVideoClient::updateDataRetention (const UpdateDataRetentionRequest & request) slot
Increases or decreases the stream's data retention period by the value that you specify. To indicate whether you want to increase or decrease the data retention period, specify the Operation parameter in the request body. In the request, you must specify either the StreamName or the StreamARN.
</p <note>
The retention period that you specify replaces the current
value> </note>
This operation requires permission for the KinesisVideo:UpdateDataRetention
action>
Changing the data retention period affects the data in the stream as
follows>
If the data retention period is increased, existing data is retained for the new retention period. For example, if the data retention period is increased from one hour to seven hours, all existing data is retained for seven
hours>
If the data retention period is decreased, existing data is retained for the new retention period. For example, if the data retention period is decreased from seven hours to one hour, all existing data is retained for one hour, and any data older than one hour is deleted
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDataRetentionResponse *>(send(request));
 }
updateStream
UpdateStreamResponse * QtAws::KinesisVideo::KinesisVideoClient::updateStream (const UpdateStreamRequest & request) slot
Updates stream metadata, such as the device name and media
type>
You must provide the stream name or the Amazon Resource Name (ARN) of the
stream>
To make sure that you have the latest version of the stream before updating it, you can specify the stream version. Kinesis Video Streams assigns a version to each stream. When you update a stream, Kinesis Video Streams assigns a new version number. To get the latest stream version, use the DescribeStream API.
</p
UpdateStream is an asynchronous operation, and takes time to
Parameters
request Request to send to Amazon Kinesis Video Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 362 of file kinesisvideoclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStreamResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
kinesisvideo/kinesisvideoclient.h
kinesisvideo/kinesisvideoclient.cpp