AWS SDK for Qt: QtAws::ConfigService::ConfigServiceClient Class Reference
QtAws::ConfigService::ConfigServiceClient Class Reference
Client for AWS Config (Config Service)
Public Slots
BatchGetResourceConfigResponse * batchGetResourceConfig (const BatchGetResourceConfigRequest &request)
DeleteConfigRuleResponse * deleteConfigRule (const DeleteConfigRuleRequest &request)
DeleteConfigurationRecorderResponse * deleteConfigurationRecorder (const DeleteConfigurationRecorderRequest &request)
DeleteDeliveryChannelResponse * deleteDeliveryChannel (const DeleteDeliveryChannelRequest &request)
DeleteEvaluationResultsResponse * deleteEvaluationResults (const DeleteEvaluationResultsRequest &request)
DeliverConfigSnapshotResponse * deliverConfigSnapshot (const DeliverConfigSnapshotRequest &request)
DescribeComplianceByConfigRuleResponse * describeComplianceByConfigRule (const DescribeComplianceByConfigRuleRequest &request)
DescribeComplianceByResourceResponse * describeComplianceByResource (const DescribeComplianceByResourceRequest &request)
DescribeConfigRuleEvaluationStatusResponse * describeConfigRuleEvaluationStatus (const DescribeConfigRuleEvaluationStatusRequest &request)
DescribeConfigRulesResponse * describeConfigRules (const DescribeConfigRulesRequest &request)
DescribeConfigurationRecorderStatusResponse * describeConfigurationRecorderStatus (const DescribeConfigurationRecorderStatusRequest &request)
DescribeConfigurationRecordersResponse * describeConfigurationRecorders (const DescribeConfigurationRecordersRequest &request)
DescribeDeliveryChannelStatusResponse * describeDeliveryChannelStatus (const DescribeDeliveryChannelStatusRequest &request)
DescribeDeliveryChannelsResponse * describeDeliveryChannels (const DescribeDeliveryChannelsRequest &request)
GetComplianceDetailsByConfigRuleResponse * getComplianceDetailsByConfigRule (const GetComplianceDetailsByConfigRuleRequest &request)
GetComplianceDetailsByResourceResponse * getComplianceDetailsByResource (const GetComplianceDetailsByResourceRequest &request)
GetComplianceSummaryByConfigRuleResponse * getComplianceSummaryByConfigRule ()
GetComplianceSummaryByResourceTypeResponse * getComplianceSummaryByResourceType (const GetComplianceSummaryByResourceTypeRequest &request)
GetDiscoveredResourceCountsResponse * getDiscoveredResourceCounts (const GetDiscoveredResourceCountsRequest &request)
GetResourceConfigHistoryResponse * getResourceConfigHistory (const GetResourceConfigHistoryRequest &request)
ListDiscoveredResourcesResponse * listDiscoveredResources (const ListDiscoveredResourcesRequest &request)
PutConfigRuleResponse * putConfigRule (const PutConfigRuleRequest &request)
PutConfigurationRecorderResponse * putConfigurationRecorder (const PutConfigurationRecorderRequest &request)
PutDeliveryChannelResponse * putDeliveryChannel (const PutDeliveryChannelRequest &request)
PutEvaluationsResponse * putEvaluations (const PutEvaluationsRequest &request)
StartConfigRulesEvaluationResponse * startConfigRulesEvaluation (const StartConfigRulesEvaluationRequest &request)
StartConfigurationRecorderResponse * startConfigurationRecorder (const StartConfigurationRecorderRequest &request)
StopConfigurationRecorderResponse * stopConfigurationRecorder (const StopConfigurationRecorderRequest &request)
Public Member Functions
ConfigServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ConfigServiceClient object.
ConfigServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ConfigServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Config (Config Service)
<fullname>AWS Config</fullname>
AWS Config provides a way to keep track of the configurations of all the AWS resources associated with your AWS account. You can use AWS Config to get the current and historical configurations of each AWS resource and also to get information about the relationship between the resources. An AWS resource can be an Amazon Compute Cloud (Amazon EC2) instance, an Elastic Block Store (EBS) volume, an Elastic network Interface (ENI), or a security group. For a complete list of resources currently supported by AWS Config, see Supported AWS Resources>
You can access and manage AWS Config through the AWS Management Console, the AWS Command Line Interface (AWS CLI), the AWS Config API, or the AWS SDKs for AWS
Confi>
This reference guide contains documentation for the AWS Config API and the AWS CLI commands that you can use to manage AWS
Config>
The AWS Config API uses the Signature Version 4 protocol for signing requests. For more information about how to sign a request with this protocol, see Signature Version 4 Signing Process>
For detailed information about AWS Config features and their associated actions or commands, as well as how to work with AWS Management Console, see What Is AWS Config? in the AWS Config Developer
Definition at line 87 of file configserviceclient.h.
Constructor & Destructor Documentation
ConfigServiceClient() [1/2]
QtAws::ConfigService::ConfigServiceClient::ConfigServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ConfigServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 132 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ConfigServiceClientPrivate(this), parent)
 {
     Q_D(ConfigServiceClient);
     d->apiVersion = QStringLiteral("2014-11-12");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("config");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Config");
     d->serviceName = QStringLiteral("config");
 }
ConfigServiceClient() [2/2]
QtAws::ConfigService::ConfigServiceClient::ConfigServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ConfigServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 165 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ConfigServiceClientPrivate(this), parent)
 {
     Q_D(ConfigServiceClient);
     d->apiVersion = QStringLiteral("2014-11-12");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("config");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Config");
     d->serviceName = QStringLiteral("config");
 }
Member Function Documentation
batchGetResourceConfig
BatchGetResourceConfigResponse * QtAws::ConfigService::ConfigServiceClient::batchGetResourceConfig (const BatchGetResourceConfigRequest & request) slot
Returns the current configuration for one or more requested resources. The operation also returns a list of resources that are not processed in the current request. If there are no unprocessed resources, the operation returns an empty unprocessedResourceKeys list.
</p <note>
The API does not return results for deleted
resources>
The API does not return any tags for the requested resources. This information is filtered out of the supplementaryConfiguration section of the API
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 202 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetResourceConfigResponse *>(send(request));
 }
deleteConfigRule
DeleteConfigRuleResponse * QtAws::ConfigService::ConfigServiceClient::deleteConfigRule (const DeleteConfigRuleRequest & request) slot
Deletes the specified AWS Config rule and all of its evaluation
results>
AWS Config sets the state of a rule to DELETING until the deletion is complete. You cannot update a rule while it is in this state. If you make a PutConfigRule or DeleteConfigRule request for the rule, you will receive a
ResourceInUseException>
You can check the state of a rule by using the DescribeConfigRules
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 226 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConfigRuleResponse *>(send(request));
 }
deleteConfigurationRecorder
DeleteConfigurationRecorderResponse * QtAws::ConfigService::ConfigServiceClient::deleteConfigurationRecorder (const DeleteConfigurationRecorderRequest & request) slot
Deletes the configuration
recorder>
After the configuration recorder is deleted, AWS Config will not record resource configuration changes until you create a new configuration
recorder>
This action does not delete the configuration information that was previously recorded. You will be able to access the previously recorded information by using the GetResourceConfigHistory action, but you will not be able to access this information in the AWS Config console until you create a new configuration
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 251 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConfigurationRecorderResponse *>(send(request));
 }
deleteDeliveryChannel
DeleteDeliveryChannelResponse * QtAws::ConfigService::ConfigServiceClient::deleteDeliveryChannel (const DeleteDeliveryChannelRequest & request) slot
Deletes the delivery
channel>
Before you can delete the delivery channel, you must stop the configuration recorder by using the StopConfigurationRecorder
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 270 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDeliveryChannelResponse *>(send(request));
 }
deleteEvaluationResults
DeleteEvaluationResultsResponse * QtAws::ConfigService::ConfigServiceClient::deleteEvaluationResults (const DeleteEvaluationResultsRequest & request) slot
Deletes the evaluation results for the specified Config rule. You can specify one Config rule per request. After you delete the evaluation results, you can call the StartConfigRulesEvaluation API to start evaluating your AWS resources against the
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 286 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEvaluationResultsResponse *>(send(request));
 }
deliverConfigSnapshot
DeliverConfigSnapshotResponse * QtAws::ConfigService::ConfigServiceClient::deliverConfigSnapshot (const DeliverConfigSnapshotRequest & request) slot
Schedules delivery of a configuration snapshot to the Amazon S3 bucket in the specified delivery channel. After the delivery has started, AWS Config sends following notifications using an Amazon SNS topic that you have
specified>
Notification of starting the
delivery>
Notification of delivery completed, if the delivery was successfully
completed>
Notification of delivery failure, if the delivery failed to
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 313 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeliverConfigSnapshotResponse *>(send(request));
 }
describeComplianceByConfigRule
DescribeComplianceByConfigRuleResponse * QtAws::ConfigService::ConfigServiceClient::describeComplianceByConfigRule (const DescribeComplianceByConfigRuleRequest & request) slot
Indicates whether the specified AWS Config rules are compliant. If a rule is noncompliant, this action returns the number of AWS resources that do not comply with the
rule>
A rule is compliant if all of the evaluated resources comply with it, and it is noncompliant if any of these resources do not
comply>
If AWS Config has no current evaluation results for the rule, it returns INSUFFICIENT_DATA. This result might indicate one of the following
conditions>
AWS Config has never invoked an evaluation for the rule. To check whether it has, use the DescribeConfigRuleEvaluationStatus action to get the LastSuccessfulInvocationTime and
LastFailedInvocationTime>
The rule's AWS Lambda function is failing to send evaluation results to AWS Config. Verify that the role that you assigned to your configuration recorder includes the config:PutEvaluations permission. If the rule is a custom rule, verify that the AWS Lambda execution role includes the config:PutEvaluations
permission>
The rule's AWS Lambda function has returned NOT_APPLICABLE for all evaluation results. This can occur if the resources were deleted or removed from the rule's
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 354 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeComplianceByConfigRuleResponse *>(send(request));
 }
describeComplianceByResource
DescribeComplianceByResourceResponse * QtAws::ConfigService::ConfigServiceClient::describeComplianceByResource (const DescribeComplianceByResourceRequest & request) slot
Indicates whether the specified AWS resources are compliant. If a resource is noncompliant, this action returns the number of AWS Config rules that the resource does not comply
with>
A resource is compliant if it complies with all the AWS Config rules that evaluate it. It is noncompliant if it does not comply with one or more of these
rules>
If AWS Config has no current evaluation results for the resource, it returns INSUFFICIENT_DATA. This result might indicate one of the following conditions about the rules that evaluate the
resource>
AWS Config has never invoked an evaluation for the rule. To check whether it has, use the DescribeConfigRuleEvaluationStatus action to get the LastSuccessfulInvocationTime and
LastFailedInvocationTime>
The rule's AWS Lambda function is failing to send evaluation results to AWS Config. Verify that the role that you assigned to your configuration recorder includes the config:PutEvaluations permission. If the rule is a custom rule, verify that the AWS Lambda execution role includes the config:PutEvaluations
permission>
The rule's AWS Lambda function has returned NOT_APPLICABLE for all evaluation results. This can occur if the resources were deleted or removed from the rule's
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeComplianceByResourceResponse *>(send(request));
 }
describeConfigRuleEvaluationStatus
DescribeConfigRuleEvaluationStatusResponse * QtAws::ConfigService::ConfigServiceClient::describeConfigRuleEvaluationStatus (const DescribeConfigRuleEvaluationStatusRequest & request) slot
Returns status information for each of your AWS managed Config rules. The status includes information such as the last time AWS Config invoked the rule, the last time AWS Config failed to invoke the rule, and the related error for the last
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 410 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigRuleEvaluationStatusResponse *>(send(request));
 }
describeConfigRules
DescribeConfigRulesResponse * QtAws::ConfigService::ConfigServiceClient::describeConfigRules (const DescribeConfigRulesRequest & request) slot
Returns details about your AWS Config
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 424 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigRulesResponse *>(send(request));
 }
describeConfigurationRecorders
DescribeConfigurationRecordersResponse * QtAws::ConfigService::ConfigServiceClient::describeConfigurationRecorders (const DescribeConfigurationRecordersRequest & request) slot
Returns the details for the specified configuration recorders. If the configuration recorder is not specified, this action returns the details for all configuration recorders associated with the
account> <note>
Currently, you can specify only one configuration recorder per region in your
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 462 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigurationRecordersResponse *>(send(request));
 }
describeConfigurationRecorderStatus
DescribeConfigurationRecorderStatusResponse * QtAws::ConfigService::ConfigServiceClient::describeConfigurationRecorderStatus (const DescribeConfigurationRecorderStatusRequest & request) slot
Returns the current status of the specified configuration recorder. If a configuration recorder is not specified, this action returns the status of all configuration recorder associated with the
account> <note>
Currently, you can specify only one configuration recorder per region in your
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 443 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigurationRecorderStatusResponse *>(send(request));
 }
describeDeliveryChannels
DescribeDeliveryChannelsResponse * QtAws::ConfigService::ConfigServiceClient::describeDeliveryChannels (const DescribeDeliveryChannelsRequest & request) slot
Returns details about the specified delivery channel. If a delivery channel is not specified, this action returns the details of all delivery channels associated with the
account> <note>
Currently, you can specify only one delivery channel per region in your
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 500 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDeliveryChannelsResponse *>(send(request));
 }
describeDeliveryChannelStatus
DescribeDeliveryChannelStatusResponse * QtAws::ConfigService::ConfigServiceClient::describeDeliveryChannelStatus (const DescribeDeliveryChannelStatusRequest & request) slot
Returns the current status of the specified delivery channel. If a delivery channel is not specified, this action returns the current status of all delivery channels associated with the
account> <note>
Currently, you can specify only one delivery channel per region in your
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 481 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDeliveryChannelStatusResponse *>(send(request));
 }
getComplianceDetailsByConfigRule
GetComplianceDetailsByConfigRuleResponse * QtAws::ConfigService::ConfigServiceClient::getComplianceDetailsByConfigRule (const GetComplianceDetailsByConfigRuleRequest & request) slot
Returns the evaluation results for the specified AWS Config rule. The results indicate which AWS resources were evaluated by the rule, when each resource was last evaluated, and whether each resource complies with the
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 515 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetComplianceDetailsByConfigRuleResponse *>(send(request));
 }
getComplianceDetailsByResource
GetComplianceDetailsByResourceResponse * QtAws::ConfigService::ConfigServiceClient::getComplianceDetailsByResource (const GetComplianceDetailsByResourceRequest & request) slot
Returns the evaluation results for the specified AWS resource. The results indicate which AWS Config rules were used to evaluate the resource, when each rule was last used, and whether the resource complies with each
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 530 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetComplianceDetailsByResourceResponse *>(send(request));
 }
getComplianceSummaryByConfigRule
GetComplianceSummaryByConfigRuleResponse * QtAws::ConfigService::ConfigServiceClient::getComplianceSummaryByConfigRule () slot
Returns the number of AWS Config rules that are compliant and noncompliant, up to a maximum of 25 for
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 544 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetComplianceSummaryByConfigRuleResponse *>(send(request));
 }
getComplianceSummaryByResourceType
GetComplianceSummaryByResourceTypeResponse * QtAws::ConfigService::ConfigServiceClient::getComplianceSummaryByResourceType (const GetComplianceSummaryByResourceTypeRequest & request) slot
Returns the number of resources that are compliant and the number that are noncompliant. You can specify one or more resource types to get these numbers for each resource type. The maximum number returned is
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetComplianceSummaryByResourceTypeResponse *>(send(request));
 }
getDiscoveredResourceCounts
GetDiscoveredResourceCountsResponse * QtAws::ConfigService::ConfigServiceClient::getDiscoveredResourceCounts (const GetDiscoveredResourceCountsRequest & request) slot
Returns the resource types, the number of each resource type, and the total number of resources that AWS Config is recording in this region for your AWS account.
</p
Example
</p
AWS Config is recording three resource types in the US East (Ohio) Region for your account: 25 EC2 instances, 20 IAM users, and 15 S3
buckets>
You make a call to the GetDiscoveredResourceCounts action and specify that you want all resource types.
</p
AWS Config returns the
following>
The resource types (EC2 instances, IAM users, and S3
buckets>
The number of each resource type (25, 20, and
15>
The total number of all resources
(60>
The response is paginated. By default, AWS Config lists 100 ResourceCount objects on each page. You can customize this number with the limit parameter. The response includes a nextToken string. To get the next page of results, run the request again and specify the string for the nextToken
parameter> <note>
If you make a call to the GetDiscoveredResourceCounts action, you may not immediately receive resource counts in the following
situations>
You are a new AWS Config
custome>
You just enabled resource
recordin>
It may take a few minutes for AWS Config to record and count your resources. Wait a few minutes and then retry the GetDiscoveredResourceCounts action.
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 625 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDiscoveredResourceCountsResponse *>(send(request));
 }
getResourceConfigHistory
GetResourceConfigHistoryResponse * QtAws::ConfigService::ConfigServiceClient::getResourceConfigHistory (const GetResourceConfigHistoryRequest & request) slot
Returns a list of configuration items for the specified resource. The list contains details about each state of the resource during the specified time
interval>
The response is paginated. By default, AWS Config returns a limit of 10 configuration items per page. You can customize this number with the limit parameter. The response includes a nextToken string. To get the next page of results, run the request again and specify the string for the nextToken
parameter> <note>
Each call to the API is limited to span a duration of seven days. It is likely that the number of records returned is smaller than the specified limit. In such cases, you can make another call, using the
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 651 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetResourceConfigHistoryResponse *>(send(request));
 }
listDiscoveredResources
ListDiscoveredResourcesResponse * QtAws::ConfigService::ConfigServiceClient::listDiscoveredResources (const ListDiscoveredResourcesRequest & request) slot
Accepts a resource type and returns a list of resource identifiers for the resources of that type. A resource identifier includes the resource type, ID, and (if available) the custom resource name. The results consist of resources that AWS Config has discovered, including those that AWS Config is not currently recording. You can narrow the results to include only resources that have specific resource IDs or a resource
name> <note>
You can specify either resource IDs or a resource name but not both in the same
request> </note>
The response is paginated. By default, AWS Config lists 100 resource identifiers on each page. You can customize this number with the limit parameter. The response includes a nextToken string. To get the next page of results, run the request again and specify the string for the nextToken
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 678 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDiscoveredResourcesResponse *>(send(request));
 }
putConfigRule
PutConfigRuleResponse * QtAws::ConfigService::ConfigServiceClient::putConfigRule (const PutConfigRuleRequest & request) slot
Adds or updates an AWS Config rule for evaluating whether your AWS resources comply with your desired
configurations>
You can use this action for custom Config rules and AWS managed Config rules. A custom Config rule is a rule that you develop and maintain. An AWS managed Config rule is a customizable, predefined rule that AWS Config
provides>
If you are adding a new custom Config rule, you must first create the AWS Lambda function that the rule invokes to evaluate your resources. When you use the PutConfigRule action to add the rule to AWS Config, you must specify the Amazon Resource Name (ARN) that AWS Lambda assigns to the function. Specify the ARN for the SourceIdentifier key. This key is part of the Source object, which is part of the ConfigRule object.
</p
If you are adding an AWS managed Config rule, specify the rule's identifier for the SourceIdentifier key. To reference AWS managed Config rule identifiers, see About AWS Managed Config Rules>
For any new rule that you add, specify the ConfigRuleName in the ConfigRule object. Do not specify the ConfigRuleArn or the ConfigRuleId. These values are generated by AWS Config for new
rules>
If you are updating a rule that you added previously, you can specify the rule by ConfigRuleName, ConfigRuleId, or ConfigRuleArn in the ConfigRule data type that you use in this
request>
The maximum number of rules that AWS Config supports is
50>
For more information about requesting a rule limit increase, see AWS Config Limits in the AWS General Reference
Guide>
For more information about developing and using AWS Config rules, see Evaluating AWS Resource Configurations with AWS Config in the AWS Config Developer
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 739 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutConfigRuleResponse *>(send(request));
 }
putConfigurationRecorder
PutConfigurationRecorderResponse * QtAws::ConfigService::ConfigServiceClient::putConfigurationRecorder (const PutConfigurationRecorderRequest & request) slot
Creates a new configuration recorder to record the selected resource
configurations>
You can use this action to change the role roleARN and/or the recordingGroup of an existing recorder. To change the role, call the action on the existing configuration recorder and specify a
role> <note>
Currently, you can specify only one configuration recorder per region in your
account>
If ConfigurationRecorder does not have the recordingGroup parameter specified, the default is to record all supported resource
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 767 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutConfigurationRecorderResponse *>(send(request));
 }
putDeliveryChannel
PutDeliveryChannelResponse * QtAws::ConfigService::ConfigServiceClient::putDeliveryChannel (const PutDeliveryChannelRequest & request) slot
Creates a delivery channel object to deliver configuration information to an Amazon S3 bucket and Amazon SNS
topic>
Before you can create a delivery channel, you must create a configuration
recorder>
You can use this action to change the Amazon S3 bucket or an Amazon SNS topic of the existing delivery channel. To change the Amazon S3 bucket or an Amazon SNS topic, call this action and specify the changed values for the S3 bucket and the SNS topic. If you specify a different value for either the S3 bucket or the SNS topic, this action will keep the existing value for the parameter that is not
changed> <note>
You can have only one delivery channel per region in your
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 796 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutDeliveryChannelResponse *>(send(request));
 }
putEvaluations
PutEvaluationsResponse * QtAws::ConfigService::ConfigServiceClient::putEvaluations (const PutEvaluationsRequest & request) slot
Used by an AWS Lambda function to deliver evaluation results to AWS Config. This action is required in every AWS Lambda function that is invoked by an AWS Config
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 811 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutEvaluationsResponse *>(send(request));
 }
startConfigRulesEvaluation
StartConfigRulesEvaluationResponse * QtAws::ConfigService::ConfigServiceClient::startConfigRulesEvaluation (const StartConfigRulesEvaluationRequest & request) slot
Runs an on-demand evaluation for the specified Config rules against the last known configuration state of the resources. Use StartConfigRulesEvaluation when you want to test a rule that you updated is working as expected. StartConfigRulesEvaluation does not re-record the latest configuration state for your resources; it re-runs an evaluation against the last known state of your resources.
</p
You can specify up to 25 Config rules per request.
</p
An existing StartConfigRulesEvaluation call must complete for the specified rules before you can call the API again. If you chose to have AWS Config stream to an Amazon SNS topic, you will receive a ConfigRuleEvaluationStarted notification when the evaluation
starts> <note>
You don't need to call the StartConfigRulesEvaluation API to run an evaluation for a new rule. When you create a new rule, AWS Config automatically evaluates your resources against the rule.
</p </note>
The StartConfigRulesEvaluation API is useful if you want to run on-demand evaluations, such as the following
example>
You have a custom rule that evaluates your IAM resources every 24
hours>
You update your Lambda function to add additional conditions to your
rule>
Instead of waiting for the next periodic evaluation, you call the StartConfigRulesEvaluation
API>
AWS Config invokes your Lambda function and evaluates your IAM
resources>
Your custom rule will still run periodic evaluations every 24
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 868 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartConfigRulesEvaluationResponse *>(send(request));
 }
startConfigurationRecorder
StartConfigurationRecorderResponse * QtAws::ConfigService::ConfigServiceClient::startConfigurationRecorder (const StartConfigurationRecorderRequest & request) slot
Starts recording configurations of the AWS resources you have selected to record in your AWS
account>
You must have created at least one delivery channel to successfully start the configuration
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 886 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartConfigurationRecorderResponse *>(send(request));
 }
stopConfigurationRecorder
StopConfigurationRecorderResponse * QtAws::ConfigService::ConfigServiceClient::stopConfigurationRecorder (const StopConfigurationRecorderRequest & request) slot
Stops recording configurations of the AWS resources you have selected to record in your AWS
Parameters
request Request to send to AWS Config.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 900 of file configserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopConfigurationRecorderResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
config/configserviceclient.h
config/configserviceclient.cpp