AWS SDK for Qt: QtAws::Health::HealthClient Class Reference
QtAws::Health::HealthClient Class Reference
Client for AWS Health APIs and Notifications.
Public Slots
DescribeAffectedEntitiesResponse * describeAffectedEntities (const DescribeAffectedEntitiesRequest &request)
DescribeEntityAggregatesResponse * describeEntityAggregates (const DescribeEntityAggregatesRequest &request)
DescribeEventAggregatesResponse * describeEventAggregates (const DescribeEventAggregatesRequest &request)
DescribeEventDetailsResponse * describeEventDetails (const DescribeEventDetailsRequest &request)
DescribeEventTypesResponse * describeEventTypes (const DescribeEventTypesRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
Public Member Functions
HealthClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new HealthClient object.
HealthClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new HealthClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Health APIs and Notifications.
<fullname>AWS Health</fullname>
The AWS Health API provides programmatic access to the AWS Health information that is presented in the AWS Personal Health Dashboard. You can get information about events that affect your AWS
resources>
DescribeEvents: Summary information about
events>
DescribeEventDetails: Detailed information about one or more
events>
DescribeAffectedEntities: Information about AWS resources that are affected by one or more
events>
In addition, these operations provide information about event types and summary counts of events or affected
entities>
DescribeEventTypes: Information about the kinds of events that AWS Health
tracks>
DescribeEventAggregates: A count of the number of events that meet specified
criteria>
DescribeEntityAggregates: A count of the number of affected entities that meet specified
criteria>
The Health API requires a Business or Enterprise support plan from AWS Support. Calling the Health API from an account that does not have a Business or Enterprise support plan causes a SubscriptionRequiredException.
</p
For authentication of requests, AWS Health uses the Signature Version 4 Signing Process>
See the AWS Health User Guide for information about how to use the
API>
Service Endpoint
https://health.us-east-1.amazonaws.com
Definition at line 44 of file healthclient.h.
Constructor & Destructor Documentation
HealthClient() [1/2]
QtAws::Health::HealthClient::HealthClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new HealthClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 119 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new HealthClientPrivate(this), parent)
 {
     Q_D(HealthClient);
     d->apiVersion = QStringLiteral("2016-08-04");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("health");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Health APIs and Notifications");
     d->serviceName = QStringLiteral("health");
 }
HealthClient() [2/2]
QtAws::Health::HealthClient::HealthClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new HealthClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 152 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new HealthClientPrivate(this), parent)
 {
     Q_D(HealthClient);
     d->apiVersion = QStringLiteral("2016-08-04");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("health");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Health APIs and Notifications");
     d->serviceName = QStringLiteral("health");
 }
Member Function Documentation
describeAffectedEntities
DescribeAffectedEntitiesResponse * QtAws::Health::HealthClient::describeAffectedEntities (const DescribeAffectedEntitiesRequest & request) slot
Returns a list of entities that have been affected by the specified events, based on the specified filter criteria. Entities can refer to individual customer resources, groups of customer resources, or any other construct, depending on the AWS service. Events that have impact beyond that of the affected entities, or where the extent of impact is unknown, include at least one entity indicating
this>
At least one event ARN is required. Results are sorted by the lastUpdatedTime of the entity, starting with the most
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 186 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAffectedEntitiesResponse *>(send(request));
 }
describeEntityAggregates
DescribeEntityAggregatesResponse * QtAws::Health::HealthClient::describeEntityAggregates (const DescribeEntityAggregatesRequest & request) slot
Returns the number of entities that are affected by each of the specified events. If no events are specified, the counts of all affected entities are
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 201 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEntityAggregatesResponse *>(send(request));
 }
describeEventAggregates
DescribeEventAggregatesResponse * QtAws::Health::HealthClient::describeEventAggregates (const DescribeEventAggregatesRequest & request) slot
Returns the number of events of each event type (issue, scheduled change, and account notification). If no filter is specified, the counts of all events in each category are
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventAggregatesResponse *>(send(request));
 }
describeEventDetails
DescribeEventDetailsResponse * QtAws::Health::HealthClient::describeEventDetails (const DescribeEventDetailsRequest & request) slot
Returns detailed information about one or more specified events. Information includes standard event data (region, service, etc., as returned by DescribeEvents), a detailed event description, and possible additional metadata that depends upon the nature of the event. Affected entities are not included; to retrieve those, use the DescribeAffectedEntities
operation>
If a specified event cannot be retrieved, an error message is returned for that
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 237 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventDetailsResponse *>(send(request));
 }
describeEvents
DescribeEventsResponse * QtAws::Health::HealthClient::describeEvents (const DescribeEventsRequest & request) slot
Returns information about events that meet the specified filter criteria. Events are returned in a summary form and do not include the detailed description, any additional metadata that depends on the event type, or any affected resources. To retrieve that information, use the DescribeEventDetails and DescribeAffectedEntities
operations>
If no filter criteria are specified, all events are returned. Results are sorted by lastModifiedTime, starting with the most
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventsResponse *>(send(request));
 }
describeEventTypes
DescribeEventTypesResponse * QtAws::Health::HealthClient::describeEventTypes (const DescribeEventTypesRequest & request) slot
Returns the event types that meet the specified filter criteria. If no filter criteria are specified, all event types are returned, in no particular
Parameters
request Request to send to AWS Health APIs and Notifications.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 252 of file healthclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventTypesResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
health/healthclient.h
health/healthclient.cpp