AWS SDK for Qt: QtAws::CloudFront::CloudFrontClient Class Reference
QtAws::CloudFront::CloudFrontClient Class Reference
Client for Amazon CloudFront.
Public Slots
CreateCloudFrontOriginAccessIdentityResponse * createCloudFrontOriginAccessIdentity (const CreateCloudFrontOriginAccessIdentityRequest &request)
CreateDistributionResponse * createDistribution (const CreateDistributionRequest &request)
CreateDistributionWithTagsResponse * createDistributionWithTags (const CreateDistributionWithTagsRequest &request)
CreateInvalidationResponse * createInvalidation (const CreateInvalidationRequest &request)
CreateStreamingDistributionResponse * createStreamingDistribution (const CreateStreamingDistributionRequest &request)
CreateStreamingDistributionWithTagsResponse * createStreamingDistributionWithTags (const CreateStreamingDistributionWithTagsRequest &request)
DeleteCloudFrontOriginAccessIdentityResponse * deleteCloudFrontOriginAccessIdentity (const DeleteCloudFrontOriginAccessIdentityRequest &request)
DeleteDistributionResponse * deleteDistribution (const DeleteDistributionRequest &request)
DeleteServiceLinkedRoleResponse * deleteServiceLinkedRole (const DeleteServiceLinkedRoleRequest &request)
DeleteStreamingDistributionResponse * deleteStreamingDistribution (const DeleteStreamingDistributionRequest &request)
GetCloudFrontOriginAccessIdentityResponse * getCloudFrontOriginAccessIdentity (const GetCloudFrontOriginAccessIdentityRequest &request)
GetCloudFrontOriginAccessIdentityConfigResponse * getCloudFrontOriginAccessIdentityConfig (const GetCloudFrontOriginAccessIdentityConfigRequest &request)
GetDistributionResponse * getDistribution (const GetDistributionRequest &request)
GetDistributionConfigResponse * getDistributionConfig (const GetDistributionConfigRequest &request)
GetInvalidationResponse * getInvalidation (const GetInvalidationRequest &request)
GetStreamingDistributionResponse * getStreamingDistribution (const GetStreamingDistributionRequest &request)
GetStreamingDistributionConfigResponse * getStreamingDistributionConfig (const GetStreamingDistributionConfigRequest &request)
ListCloudFrontOriginAccessIdentitiesResponse * listCloudFrontOriginAccessIdentities (const ListCloudFrontOriginAccessIdentitiesRequest &request)
ListDistributionsResponse * listDistributions (const ListDistributionsRequest &request)
ListDistributionsByWebACLIdResponse * listDistributionsByWebACLId (const ListDistributionsByWebACLIdRequest &request)
ListInvalidationsResponse * listInvalidations (const ListInvalidationsRequest &request)
ListStreamingDistributionsResponse * listStreamingDistributions (const ListStreamingDistributionsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateCloudFrontOriginAccessIdentityResponse * updateCloudFrontOriginAccessIdentity (const UpdateCloudFrontOriginAccessIdentityRequest &request)
UpdateDistributionResponse * updateDistribution (const UpdateDistributionRequest &request)
UpdateStreamingDistributionResponse * updateStreamingDistribution (const UpdateStreamingDistributionRequest &request)
Public Member Functions
CloudFrontClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFrontClient object.
CloudFrontClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFrontClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudFront.
<fullname>Amazon CloudFront</fullname>
This is the Amazon CloudFront API Reference. This guide is for developers who need detailed information about CloudFront API actions, data types, and errors. For detailed information about CloudFront features, see the Amazon CloudFront Developer
Definition at line 88 of file cloudfrontclient.h.
Constructor & Destructor Documentation
CloudFrontClient() [1/2]
QtAws::CloudFront::CloudFrontClient::CloudFrontClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFrontClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 107 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudFrontClientPrivate(this), parent)
 {
     Q_D(CloudFrontClient);
     d->apiVersion = QStringLiteral("2017-03-25");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudfront");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudFront");
     d->serviceName = QStringLiteral("cloudfront");
 }
CloudFrontClient() [2/2]
QtAws::CloudFront::CloudFrontClient::CloudFrontClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFrontClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 140 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudFrontClientPrivate(this), parent)
 {
     Q_D(CloudFrontClient);
     d->apiVersion = QStringLiteral("2017-03-25");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudfront");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudFront");
     d->serviceName = QStringLiteral("cloudfront");
 }
Member Function Documentation
createCloudFrontOriginAccessIdentity
CreateCloudFrontOriginAccessIdentityResponse * QtAws::CloudFront::CloudFrontClient::createCloudFrontOriginAccessIdentity (const CreateCloudFrontOriginAccessIdentityRequest & request) slot
Creates a new origin access identity. If you're using Amazon S3 for your origin, you can use an origin access identity to require users to access your content using a CloudFront URL instead of the Amazon S3 URL. For more information about how to use origin access identities, see Serving Private Content through CloudFront in the Amazon CloudFront Developer
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 170 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCloudFrontOriginAccessIdentityResponse *>(send(request));
 }
createDistribution
CreateDistributionResponse * QtAws::CloudFront::CloudFrontClient::createDistribution (const CreateDistributionRequest & request) slot
Creates a new web distribution. Send a POST request to the /CloudFront API version/distribution/distribution ID
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 185 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDistributionResponse *>(send(request));
 }
createDistributionWithTags
CreateDistributionWithTagsResponse * QtAws::CloudFront::CloudFrontClient::createDistributionWithTags (const CreateDistributionWithTagsRequest & request) slot
Create a new distribution with
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 199 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDistributionWithTagsResponse *>(send(request));
 }
createInvalidation
CreateInvalidationResponse * QtAws::CloudFront::CloudFrontClient::createInvalidation (const CreateInvalidationRequest & request) slot
Create a new invalidation.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 213 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInvalidationResponse *>(send(request));
 }
createStreamingDistribution
CreateStreamingDistributionResponse * QtAws::CloudFront::CloudFrontClient::createStreamingDistribution (const CreateStreamingDistributionRequest & request) slot
Creates a new RMTP distribution. An RTMP distribution is similar to a web distribution, but an RTMP distribution streams media files using the Adobe Real-Time Messaging Protocol (RTMP) instead of serving files using HTTP.
</p
To create a new web distribution, submit a POST request to the CloudFront API version/distribution resource. The request body must include a document with a StreamingDistributionConfig element. The response echoes the StreamingDistributionConfig element and returns other information about the RTMP
distribution>
To get the status of your request, use the GET StreamingDistribution API action. When the value of Enabled is true and the value of Status is Deployed, your distribution is ready. A distribution usually deploys in less than 15
minutes>
For more information about web distributions, see Working with RTMP Distributions in the Amazon CloudFront Developer
Guide>
Beginning with the 2012-05-05 version of the CloudFront API, we made substantial changes to the format of the XML document that you include in the request body when you create or update a web distribution or an RTMP distribution, and when you invalidate objects. With previous versions of the API, we discovered that it was too easy to accidentally delete one or more values for an element that accepts multiple values, for example, CNAMEs and trusted signers. Our changes for the 2012-05-05 release are intended to prevent these accidental deletions and to notify you when there's a mismatch between the number of values you say you're specifying in the Quantity element and the number of values
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 256 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStreamingDistributionResponse *>(send(request));
 }
createStreamingDistributionWithTags
CreateStreamingDistributionWithTagsResponse * QtAws::CloudFront::CloudFrontClient::createStreamingDistributionWithTags (const CreateStreamingDistributionWithTagsRequest & request) slot
Create a new streaming distribution with
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 270 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStreamingDistributionWithTagsResponse *>(send(request));
 }
deleteCloudFrontOriginAccessIdentity
DeleteCloudFrontOriginAccessIdentityResponse * QtAws::CloudFront::CloudFrontClient::deleteCloudFrontOriginAccessIdentity (const DeleteCloudFrontOriginAccessIdentityRequest & request) slot
Delete an origin access identity.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 284 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCloudFrontOriginAccessIdentityResponse *>(send(request));
 }
deleteDistribution
DeleteDistributionResponse * QtAws::CloudFront::CloudFrontClient::deleteDistribution (const DeleteDistributionRequest & request) slot
Delete a distribution.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 298 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDistributionResponse *>(send(request));
 }
deleteServiceLinkedRole
DeleteServiceLinkedRoleResponse * QtAws::CloudFront::CloudFrontClient::deleteServiceLinkedRole (const DeleteServiceLinkedRoleRequest & request) slot
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 311 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServiceLinkedRoleResponse *>(send(request));
 }
deleteStreamingDistribution
DeleteStreamingDistributionResponse * QtAws::CloudFront::CloudFrontClient::deleteStreamingDistribution (const DeleteStreamingDistributionRequest & request) slot
Delete a streaming distribution. To delete an RTMP distribution using the CloudFront API, perform the following
steps>
To delete an RTMP distribution using the CloudFront
API>
Disable the RTMP
distribution>
Submit a GET Streaming Distribution Config request to get the current configuration and the Etag header for the distribution.
</p
Update the XML document that was returned in the response to your GET Streaming Distribution Config request to change the value of Enabled to
false>
Submit a PUT Streaming Distribution Config request to update the configuration for your distribution. In the request body, include the XML document that you updated in Step 3. Then set the value of the HTTP If-Match header to the value of the ETag header that CloudFront returned when you submitted the GET Streaming Distribution Config request in Step
2>
Review the response to the PUT Streaming Distribution Config request to confirm that the distribution was successfully
disabled>
Submit a GET Streaming Distribution Config request to confirm that your changes have propagated. When propagation is complete, the value of Status is
Deployed>
Submit a DELETE Streaming Distribution request. Set the value of the HTTP If-Match header to the value of the ETag header that CloudFront returned when you submitted the GET Streaming Distribution Config request in Step
2>
Review the response to your DELETE Streaming Distribution request to confirm that the distribution was successfully
deleted>
For information about deleting a distribution using the CloudFront console, see Deleting a Distribution in the Amazon CloudFront Developer
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStreamingDistributionResponse *>(send(request));
 }
getCloudFrontOriginAccessIdentity
GetCloudFrontOriginAccessIdentityResponse * QtAws::CloudFront::CloudFrontClient::getCloudFrontOriginAccessIdentity (const GetCloudFrontOriginAccessIdentityRequest & request) slot
Get the information about an origin access identity.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 391 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCloudFrontOriginAccessIdentityResponse *>(send(request));
 }
getCloudFrontOriginAccessIdentityConfig
GetCloudFrontOriginAccessIdentityConfigResponse * QtAws::CloudFront::CloudFrontClient::getCloudFrontOriginAccessIdentityConfig (const GetCloudFrontOriginAccessIdentityConfigRequest & request) slot
Get the configuration information about an origin access identity.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 405 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCloudFrontOriginAccessIdentityConfigResponse *>(send(request));
 }
getDistribution
GetDistributionResponse * QtAws::CloudFront::CloudFrontClient::getDistribution (const GetDistributionRequest & request) slot
Get the information about a distribution.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 419 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDistributionResponse *>(send(request));
 }
getDistributionConfig
GetDistributionConfigResponse * QtAws::CloudFront::CloudFrontClient::getDistributionConfig (const GetDistributionConfigRequest & request) slot
Get the configuration information about a distribution.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 433 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDistributionConfigResponse *>(send(request));
 }
getInvalidation
GetInvalidationResponse * QtAws::CloudFront::CloudFrontClient::getInvalidation (const GetInvalidationRequest & request) slot
Get the information about an invalidation.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 447 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetInvalidationResponse *>(send(request));
 }
getStreamingDistribution
GetStreamingDistributionResponse * QtAws::CloudFront::CloudFrontClient::getStreamingDistribution (const GetStreamingDistributionRequest & request) slot
Gets information about a specified RTMP distribution, including the distribution
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 461 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStreamingDistributionResponse *>(send(request));
 }
getStreamingDistributionConfig
GetStreamingDistributionConfigResponse * QtAws::CloudFront::CloudFrontClient::getStreamingDistributionConfig (const GetStreamingDistributionConfigRequest & request) slot
Get the configuration information about a streaming distribution.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 475 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStreamingDistributionConfigResponse *>(send(request));
 }
listCloudFrontOriginAccessIdentities
ListCloudFrontOriginAccessIdentitiesResponse * QtAws::CloudFront::CloudFrontClient::listCloudFrontOriginAccessIdentities (const ListCloudFrontOriginAccessIdentitiesRequest & request) slot
Lists origin access
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 489 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListCloudFrontOriginAccessIdentitiesResponse *>(send(request));
 }
listDistributions
ListDistributionsResponse * QtAws::CloudFront::CloudFrontClient::listDistributions (const ListDistributionsRequest & request) slot
List distributions.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 503 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDistributionsResponse *>(send(request));
 }
listDistributionsByWebACLId
ListDistributionsByWebACLIdResponse * QtAws::CloudFront::CloudFrontClient::listDistributionsByWebACLId (const ListDistributionsByWebACLIdRequest & request) slot
List the distributions that are associated with a specified AWS WAF web ACL.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 517 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDistributionsByWebACLIdResponse *>(send(request));
 }
listInvalidations
ListInvalidationsResponse * QtAws::CloudFront::CloudFrontClient::listInvalidations (const ListInvalidationsRequest & request) slot
Lists invalidation batches.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 531 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInvalidationsResponse *>(send(request));
 }
listStreamingDistributions
ListStreamingDistributionsResponse * QtAws::CloudFront::CloudFrontClient::listStreamingDistributions (const ListStreamingDistributionsRequest & request) slot
List streaming distributions.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 545 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStreamingDistributionsResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::CloudFront::CloudFrontClient::listTagsForResource (const ListTagsForResourceRequest & request) slot
List tags for a CloudFront
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::CloudFront::CloudFrontClient::tagResource (const TagResourceRequest & request) slot
Add tags to a CloudFront
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 573 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::CloudFront::CloudFrontClient::untagResource (const UntagResourceRequest & request) slot
Remove tags from a CloudFront
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 587 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateCloudFrontOriginAccessIdentity
UpdateCloudFrontOriginAccessIdentityResponse * QtAws::CloudFront::CloudFrontClient::updateCloudFrontOriginAccessIdentity (const UpdateCloudFrontOriginAccessIdentityRequest & request) slot
Update an origin access identity.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 601 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCloudFrontOriginAccessIdentityResponse *>(send(request));
 }
updateDistribution
UpdateDistributionResponse * QtAws::CloudFront::CloudFrontClient::updateDistribution (const UpdateDistributionRequest & request) slot
Updates the configuration for a web distribution. Perform the following
steps>
For information about updating a distribution using the CloudFront console, see Creating or Updating a Web Distribution Using the CloudFront Console in the Amazon CloudFront Developer
Guide>
To update a web distribution using the CloudFront API
</p
Submit a GetDistributionConfig request to get the current configuration and an Etag header for the
distribution> <note>
If you update the distribution again, you need to get a new Etag
header> </note>
Update the XML document that was returned in the response to your GetDistributionConfig request to include the desired changes. You can't change the value of CallerReference. If you try to change this value, CloudFront returns an IllegalUpdate
error>
The new configuration replaces the existing configuration; the values that you specify in an UpdateDistribution request are not merged into the existing configuration. When you add, delete, or replace values in an element that allows multiple values (for example, CNAME), you must specify all of the values that you want to appear in the updated distribution. In addition, you must update the corresponding Quantity
element>
Submit an UpdateDistribution request to update the configuration for your
distribution>
In the request body, include the XML document that you updated in Step 2. The request body must include an XML document with a DistributionConfig
element>
Set the value of the HTTP If-Match header to the value of the ETag header that CloudFront returned when you submitted the GetDistributionConfig request in Step
1>
Review the response to the UpdateDistribution request to confirm that the configuration was successfully
updated>
Optional: Submit a GetDistribution request to confirm that your changes have propagated. When propagation is complete, the value of Status is
Deployed>
Beginning with the 2012-05-05 version of the CloudFront API, we made substantial changes to the format of the XML document that you include in the request body when you create or update a distribution. With previous versions of the API, we discovered that it was too easy to accidentally delete one or more values for an element that accepts multiple values, for example, CNAMEs and trusted signers. Our changes for the 2012-05-05 release are intended to prevent these accidental deletions and to notify you when there's a mismatch between the number of values you say you're specifying in the Quantity element and the number of values you're actually
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 679 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDistributionResponse *>(send(request));
 }
updateStreamingDistribution
UpdateStreamingDistributionResponse * QtAws::CloudFront::CloudFrontClient::updateStreamingDistribution (const UpdateStreamingDistributionRequest & request) slot
Update a streaming distribution.
Parameters
request Request to send to Amazon CloudFront.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 693 of file cloudfrontclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStreamingDistributionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudfront/cloudfrontclient.h
cloudfront/cloudfrontclient.cpp