AWS SDK for Qt: QtAws::CloudSearch::CloudSearchClient Class Reference
QtAws::CloudSearch::CloudSearchClient Class Reference
Client for Amazon CloudSearch.
Public Slots
BuildSuggestersResponse * buildSuggesters (const BuildSuggestersRequest &request)
CreateDomainResponse * createDomain (const CreateDomainRequest &request)
DefineAnalysisSchemeResponse * defineAnalysisScheme (const DefineAnalysisSchemeRequest &request)
DefineExpressionResponse * defineExpression (const DefineExpressionRequest &request)
DefineIndexFieldResponse * defineIndexField (const DefineIndexFieldRequest &request)
DefineSuggesterResponse * defineSuggester (const DefineSuggesterRequest &request)
DeleteAnalysisSchemeResponse * deleteAnalysisScheme (const DeleteAnalysisSchemeRequest &request)
DeleteDomainResponse * deleteDomain (const DeleteDomainRequest &request)
DeleteExpressionResponse * deleteExpression (const DeleteExpressionRequest &request)
DeleteIndexFieldResponse * deleteIndexField (const DeleteIndexFieldRequest &request)
DeleteSuggesterResponse * deleteSuggester (const DeleteSuggesterRequest &request)
DescribeAnalysisSchemesResponse * describeAnalysisSchemes (const DescribeAnalysisSchemesRequest &request)
DescribeAvailabilityOptionsResponse * describeAvailabilityOptions (const DescribeAvailabilityOptionsRequest &request)
DescribeDomainsResponse * describeDomains (const DescribeDomainsRequest &request)
DescribeExpressionsResponse * describeExpressions (const DescribeExpressionsRequest &request)
DescribeIndexFieldsResponse * describeIndexFields (const DescribeIndexFieldsRequest &request)
DescribeScalingParametersResponse * describeScalingParameters (const DescribeScalingParametersRequest &request)
DescribeServiceAccessPoliciesResponse * describeServiceAccessPolicies (const DescribeServiceAccessPoliciesRequest &request)
DescribeSuggestersResponse * describeSuggesters (const DescribeSuggestersRequest &request)
IndexDocumentsResponse * indexDocuments (const IndexDocumentsRequest &request)
ListDomainNamesResponse * listDomainNames ()
UpdateAvailabilityOptionsResponse * updateAvailabilityOptions (const UpdateAvailabilityOptionsRequest &request)
UpdateScalingParametersResponse * updateScalingParameters (const UpdateScalingParametersRequest &request)
UpdateServiceAccessPoliciesResponse * updateServiceAccessPolicies (const UpdateServiceAccessPoliciesRequest &request)
Public Member Functions
CloudSearchClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchClient object.
CloudSearchClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudSearch.
<fullname>Amazon CloudSearch Configuration Service</fullname>
You use the Amazon CloudSearch configuration service to create, configure, and manage search domains. Configuration service requests are submitted using the AWS Query protocol. AWS Query requests are HTTP or HTTPS requests submitted via HTTP GET or POST with a query parameter named
Action>
The endpoint for configuration service requests is region-specific: cloudsearch.region.amazonaws.com. For example, cloudsearch.us-east-1.amazonaws.com. For a current list of supported regions and endpoints, see Regions and
Definition at line 79 of file cloudsearchclient.h.
Constructor & Destructor Documentation
CloudSearchClient() [1/2]
QtAws::CloudSearch::CloudSearchClient::CloudSearchClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 104 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudSearchClientPrivate(this), parent)
 {
     Q_D(CloudSearchClient);
     d->apiVersion = QStringLiteral("2013-01-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudsearch");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudSearch");
     d->serviceName = QStringLiteral("cloudsearch");
 }
CloudSearchClient() [2/2]
QtAws::CloudSearch::CloudSearchClient::CloudSearchClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 137 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudSearchClientPrivate(this), parent)
 {
     Q_D(CloudSearchClient);
     d->apiVersion = QStringLiteral("2013-01-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudsearch");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudSearch");
     d->serviceName = QStringLiteral("cloudsearch");
 }
Member Function Documentation
buildSuggesters
BuildSuggestersResponse * QtAws::CloudSearch::CloudSearchClient::buildSuggesters (const BuildSuggestersRequest & request) slot
Indexes the search suggestions. For more information, see Configuring Suggesters in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 165 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BuildSuggestersResponse *>(send(request));
 }
createDomain
CreateDomainResponse * QtAws::CloudSearch::CloudSearchClient::createDomain (const CreateDomainRequest & request) slot
Creates a new search domain. For more information, see Creating a Search Domain in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 181 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDomainResponse *>(send(request));
 }
defineAnalysisScheme
DefineAnalysisSchemeResponse * QtAws::CloudSearch::CloudSearchClient::defineAnalysisScheme (const DefineAnalysisSchemeRequest & request) slot
Configures an analysis scheme that can be applied to a text or text-array field to define language-specific text processing options. For more information, see Configuring Analysis Schemes in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 198 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DefineAnalysisSchemeResponse *>(send(request));
 }
defineExpression
DefineExpressionResponse * QtAws::CloudSearch::CloudSearchClient::defineExpression (const DefineExpressionRequest & request) slot
Configures an Expression for the search domain. Used to create new expressions and modify existing ones. If the expression exists, the new configuration replaces the old one. For more information, see Configuring Expressions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 215 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DefineExpressionResponse *>(send(request));
 }
defineIndexField
DefineIndexFieldResponse * QtAws::CloudSearch::CloudSearchClient::defineIndexField (const DefineIndexFieldRequest & request) slot
Configures an IndexField for the search domain. Used to create new fields and modify existing ones. You must specify the name of the domain you are configuring and an index field configuration. The index field configuration specifies a unique name, the index field type, and the options you want to configure for the field. The options you can specify depend on the IndexFieldType. If the field exists, the new configuration replaces the old one. For more information, see Configuring Index Fields in the Amazon CloudSearch Developer Guide.
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 235 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DefineIndexFieldResponse *>(send(request));
 }
defineSuggester
DefineSuggesterResponse * QtAws::CloudSearch::CloudSearchClient::defineSuggester (const DefineSuggesterRequest & request) slot
Configures a suggester for a domain. A suggester enables you to display possible matches before users finish typing their queries. When you configure a suggester, you must specify the name of the text field you want to search for possible matches and a unique name for the suggester. For more information, see Getting Search Suggestions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 253 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DefineSuggesterResponse *>(send(request));
 }
deleteAnalysisScheme
DeleteAnalysisSchemeResponse * QtAws::CloudSearch::CloudSearchClient::deleteAnalysisScheme (const DeleteAnalysisSchemeRequest & request) slot
Deletes an analysis scheme. For more information, see Configuring Analysis Schemes in the Amazon CloudSearch Developer Guide.
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 269 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAnalysisSchemeResponse *>(send(request));
 }
deleteDomain
DeleteDomainResponse * QtAws::CloudSearch::CloudSearchClient::deleteDomain (const DeleteDomainRequest & request) slot
Permanently deletes a search domain and all of its data. Once a domain has been deleted, it cannot be recovered. For more information, see Deleting a Search Domain in the Amazon CloudSearch Developer Guide.
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 285 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDomainResponse *>(send(request));
 }
deleteExpression
DeleteExpressionResponse * QtAws::CloudSearch::CloudSearchClient::deleteExpression (const DeleteExpressionRequest & request) slot
Removes an Expression from the search domain. For more information, see Configuring Expressions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 301 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteExpressionResponse *>(send(request));
 }
deleteIndexField
DeleteIndexFieldResponse * QtAws::CloudSearch::CloudSearchClient::deleteIndexField (const DeleteIndexFieldRequest & request) slot
Removes an IndexField from the search domain. For more information, see Configuring Index Fields in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 317 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIndexFieldResponse *>(send(request));
 }
deleteSuggester
DeleteSuggesterResponse * QtAws::CloudSearch::CloudSearchClient::deleteSuggester (const DeleteSuggesterRequest & request) slot
Deletes a suggester. For more information, see Getting Search Suggestions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 333 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSuggesterResponse *>(send(request));
 }
describeAnalysisSchemes
DescribeAnalysisSchemesResponse * QtAws::CloudSearch::CloudSearchClient::describeAnalysisSchemes (const DescribeAnalysisSchemesRequest & request) slot
Gets the analysis schemes configured for a domain. An analysis scheme defines language-specific text processing options for a text field. Can be limited to specific analysis schemes by name. By default, shows all analysis schemes and includes any pending changes to the configuration. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Configuring Analysis Schemes in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 352 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAnalysisSchemesResponse *>(send(request));
 }
describeAvailabilityOptions
DescribeAvailabilityOptionsResponse * QtAws::CloudSearch::CloudSearchClient::describeAvailabilityOptions (const DescribeAvailabilityOptionsRequest & request) slot
Gets the availability options configured for a domain. By default, shows the configuration with any pending changes. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Configuring Availability Options in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 370 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAvailabilityOptionsResponse *>(send(request));
 }
describeDomains
DescribeDomainsResponse * QtAws::CloudSearch::CloudSearchClient::describeDomains (const DescribeDomainsRequest & request) slot
Gets information about the search domains owned by this account. Can be limited to specific domains. Shows all domains by default. To get the number of searchable documents in a domain, use the console or submit a matchall request to your domain's search endpoint: q=matchall&amp;q.parser=structured&amp;size=0. For more information, see Getting Information about a Search Domain in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 388 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDomainsResponse *>(send(request));
 }
describeExpressions
DescribeExpressionsResponse * QtAws::CloudSearch::CloudSearchClient::describeExpressions (const DescribeExpressionsRequest & request) slot
Gets the expressions configured for the search domain. Can be limited to specific expressions by name. By default, shows all expressions and includes any pending changes to the configuration. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Configuring Expressions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeExpressionsResponse *>(send(request));
 }
describeIndexFields
DescribeIndexFieldsResponse * QtAws::CloudSearch::CloudSearchClient::describeIndexFields (const DescribeIndexFieldsRequest & request) slot
Gets information about the index fields configured for the search domain. Can be limited to specific fields by name. By default, shows all fields and includes any pending changes to the configuration. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Getting Domain Information in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 424 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIndexFieldsResponse *>(send(request));
 }
describeScalingParameters
DescribeScalingParametersResponse * QtAws::CloudSearch::CloudSearchClient::describeScalingParameters (const DescribeScalingParametersRequest & request) slot
Gets the scaling parameters configured for a domain. A domain's scaling parameters specify the desired search instance type and replication count. For more information, see Configuring Scaling Options in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 441 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingParametersResponse *>(send(request));
 }
describeServiceAccessPolicies
DescribeServiceAccessPoliciesResponse * QtAws::CloudSearch::CloudSearchClient::describeServiceAccessPolicies (const DescribeServiceAccessPoliciesRequest & request) slot
Gets information about the access policies that control access to the domain's document and search endpoints. By default, shows the configuration with any pending changes. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Configuring Access for a Search Domain in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 459 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeServiceAccessPoliciesResponse *>(send(request));
 }
describeSuggesters
DescribeSuggestersResponse * QtAws::CloudSearch::CloudSearchClient::describeSuggesters (const DescribeSuggestersRequest & request) slot
Gets the suggesters configured for a domain. A suggester enables you to display possible matches before users finish typing their queries. Can be limited to specific suggesters by name. By default, shows all suggesters and includes any pending changes to the configuration. Set the Deployed option to true to show the active configuration and exclude pending changes. For more information, see Getting Search Suggestions in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 478 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSuggestersResponse *>(send(request));
 }
indexDocuments
IndexDocumentsResponse * QtAws::CloudSearch::CloudSearchClient::indexDocuments (const IndexDocumentsRequest & request) slot
Tells the search domain to start indexing its documents using the latest indexing options. This operation must be invoked to activate options whose OptionStatus is
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 493 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<IndexDocumentsResponse *>(send(request));
 }
listDomainNames
ListDomainNamesResponse * QtAws::CloudSearch::CloudSearchClient::listDomainNames () slot
Lists all search domains owned by an
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 507 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDomainNamesResponse *>(send(request));
 }
updateAvailabilityOptions
UpdateAvailabilityOptionsResponse * QtAws::CloudSearch::CloudSearchClient::updateAvailabilityOptions (const UpdateAvailabilityOptionsRequest & request) slot
Configures the availability options for a domain. Enabling the Multi-AZ option expands an Amazon CloudSearch domain to an additional Availability Zone in the same Region to increase fault tolerance in the event of a service disruption. Changes to the Multi-AZ option can take about half an hour to become active. For more information, see Configuring Availability Options in the Amazon CloudSearch Developer
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 525 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAvailabilityOptionsResponse *>(send(request));
 }
updateScalingParameters
UpdateScalingParametersResponse * QtAws::CloudSearch::CloudSearchClient::updateScalingParameters (const UpdateScalingParametersRequest & request) slot
Configures scaling parameters for a domain. A domain's scaling parameters specify the desired search instance type and replication count. Amazon CloudSearch will still automatically scale your domain based on the volume of data and traffic, but not below the desired instance type and replication count. If the Multi-AZ option is enabled, these values control the resources used per Availability Zone. For more information, see Configuring Scaling Options in the Amazon CloudSearch Developer Guide.
Parameters
request Request to send to Amazon CloudSearch.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 544 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateScalingParametersResponse *>(send(request));
 }
updateServiceAccessPolicies
UpdateServiceAccessPoliciesResponse * QtAws::CloudSearch::CloudSearchClient::updateServiceAccessPolicies (const UpdateServiceAccessPoliciesRequest & request) slot
Configures the access rules that control access to the domain's document and search endpoints. For more information, see Configuring Access for an Amazon CloudSearch request Request to send to Amazon CloudSearch. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 560 of file cloudsearchclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateServiceAccessPoliciesResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudsearch/cloudsearchclient.h
cloudsearch/cloudsearchclient.cpp