AWS SDK for Qt: QtAws::StorageGateway::StorageGatewayRequest Class Reference
QtAws::StorageGateway::StorageGatewayRequest Class Reference
Interface class for providing StorageGateway requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::StorageGateway::ActivateGatewayRequest, QtAws::StorageGateway::AddCacheRequest, QtAws::StorageGateway::AddTagsToResourceRequest, QtAws::StorageGateway::AddUploadBufferRequest, QtAws::StorageGateway::AddWorkingStorageRequest, QtAws::StorageGateway::CancelArchivalRequest, QtAws::StorageGateway::CancelRetrievalRequest, QtAws::StorageGateway::CreateCachediSCSIVolumeRequest, QtAws::StorageGateway::CreateNFSFileShareRequest, QtAws::StorageGateway::CreateSnapshotFromVolumeRecoveryPointRequest, QtAws::StorageGateway::CreateSnapshotRequest, QtAws::StorageGateway::CreateStorediSCSIVolumeRequest, QtAws::StorageGateway::CreateTapesRequest, QtAws::StorageGateway::CreateTapeWithBarcodeRequest, QtAws::StorageGateway::DeleteBandwidthRateLimitRequest, QtAws::StorageGateway::DeleteChapCredentialsRequest, QtAws::StorageGateway::DeleteFileShareRequest, QtAws::StorageGateway::DeleteGatewayRequest, QtAws::StorageGateway::DeleteSnapshotScheduleRequest, QtAws::StorageGateway::DeleteTapeArchiveRequest, QtAws::StorageGateway::DeleteTapeRequest, QtAws::StorageGateway::DeleteVolumeRequest, QtAws::StorageGateway::DescribeBandwidthRateLimitRequest, QtAws::StorageGateway::DescribeCachediSCSIVolumesRequest, QtAws::StorageGateway::DescribeCacheRequest, QtAws::StorageGateway::DescribeChapCredentialsRequest, QtAws::StorageGateway::DescribeGatewayInformationRequest, QtAws::StorageGateway::DescribeMaintenanceStartTimeRequest, QtAws::StorageGateway::DescribeNFSFileSharesRequest, QtAws::StorageGateway::DescribeSnapshotScheduleRequest, QtAws::StorageGateway::DescribeStorediSCSIVolumesRequest, QtAws::StorageGateway::DescribeTapeArchivesRequest, QtAws::StorageGateway::DescribeTapeRecoveryPointsRequest, QtAws::StorageGateway::DescribeTapesRequest, QtAws::StorageGateway::DescribeUploadBufferRequest, QtAws::StorageGateway::DescribeVTLDevicesRequest, QtAws::StorageGateway::DescribeWorkingStorageRequest, QtAws::StorageGateway::DisableGatewayRequest, QtAws::StorageGateway::ListFileSharesRequest, QtAws::StorageGateway::ListGatewaysRequest, QtAws::StorageGateway::ListLocalDisksRequest, QtAws::StorageGateway::ListTagsForResourceRequest, QtAws::StorageGateway::ListTapesRequest, QtAws::StorageGateway::ListVolumeInitiatorsRequest, QtAws::StorageGateway::ListVolumeRecoveryPointsRequest, QtAws::StorageGateway::ListVolumesRequest, QtAws::StorageGateway::NotifyWhenUploadedRequest, QtAws::StorageGateway::RefreshCacheRequest, QtAws::StorageGateway::RemoveTagsFromResourceRequest, QtAws::StorageGateway::ResetCacheRequest, QtAws::StorageGateway::RetrieveTapeArchiveRequest, QtAws::StorageGateway::RetrieveTapeRecoveryPointRequest, QtAws::StorageGateway::SetLocalConsolePasswordRequest, QtAws::StorageGateway::ShutdownGatewayRequest, QtAws::StorageGateway::StartGatewayRequest, QtAws::StorageGateway::UpdateBandwidthRateLimitRequest, QtAws::StorageGateway::UpdateChapCredentialsRequest, QtAws::StorageGateway::UpdateGatewayInformationRequest, QtAws::StorageGateway::UpdateGatewaySoftwareNowRequest, QtAws::StorageGateway::UpdateMaintenanceStartTimeRequest, QtAws::StorageGateway::UpdateNFSFileShareRequest, QtAws::StorageGateway::UpdateSnapshotScheduleRequest, and QtAws::StorageGateway::UpdateVTLDeviceTypeRequest.
Public Types
enum Action {
ActivateGatewayAction, AddCacheAction, AddTagsToResourceAction, AddUploadBufferAction,
AddWorkingStorageAction, CancelArchivalAction, CancelRetrievalAction, CreateCachediSCSIVolumeAction,
CreateNFSFileShareAction, CreateSnapshotAction, CreateSnapshotFromVolumeRecoveryPointAction, CreateStorediSCSIVolumeAction,
CreateTapeWithBarcodeAction, CreateTapesAction, DeleteBandwidthRateLimitAction, DeleteChapCredentialsAction,
DeleteFileShareAction, DeleteGatewayAction, DeleteSnapshotScheduleAction, DeleteTapeAction,
DeleteTapeArchiveAction, DeleteVolumeAction, DescribeBandwidthRateLimitAction, DescribeCacheAction,
DescribeCachediSCSIVolumesAction, DescribeChapCredentialsAction, DescribeGatewayInformationAction, DescribeMaintenanceStartTimeAction,
DescribeNFSFileSharesAction, DescribeSnapshotScheduleAction, DescribeStorediSCSIVolumesAction, DescribeTapeArchivesAction,
DescribeTapeRecoveryPointsAction, DescribeTapesAction, DescribeUploadBufferAction, DescribeVTLDevicesAction,
DescribeWorkingStorageAction, DisableGatewayAction, ListFileSharesAction, ListGatewaysAction,
ListLocalDisksAction, ListTagsForResourceAction, ListTapesAction, ListVolumeInitiatorsAction,
ListVolumeRecoveryPointsAction, ListVolumesAction, NotifyWhenUploadedAction, RefreshCacheAction,
RemoveTagsFromResourceAction, ResetCacheAction, RetrieveTapeArchiveAction, RetrieveTapeRecoveryPointAction,
SetLocalConsolePasswordAction, ShutdownGatewayAction, StartGatewayAction, UpdateBandwidthRateLimitAction,
UpdateChapCredentialsAction, UpdateGatewayInformationAction, UpdateGatewaySoftwareNowAction, UpdateMaintenanceStartTimeAction,
UpdateNFSFileShareAction, UpdateSnapshotScheduleAction, UpdateVTLDeviceTypeAction
}
Actions supported by StorageGateway.
Public Member Functions
StorageGatewayRequest (const Action action)
Constructs a new StorageGatewayRequest object.
StorageGatewayRequest (const StorageGatewayRequest &other)
Constructs a new StorageGatewayRequest object by copying another.
StorageGatewayRequest & operator= (const StorageGatewayRequest &other)
Assignment operator.
Action action () const
Get the StorageGateway action to be performed by this request.
QString actionString () const
Get the name of the StorageGateway action to be performed by this request.
QString apiVersion () const
Get the StorageGateway API version implemented by this request.
void setAction (const Action action)
Set the StorageGateway action to be performed by this request.
void setApiVersion (const QString &version)
Set the StorageGateway API version to include in this request.
virtual bool operator== (const StorageGatewayRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
StorageGatewayRequest (StorageGatewayRequestPrivate *const d)
Constructs a new StorageGatewayRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid StorageGateway queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this StorageGateway request.
const QVariantMap & parameters () const
Get all parameters included with this StorageGateway request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this StorageGateway request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this StorageGateway request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this StorageGateway request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing StorageGateway requests.
Definition at line 35 of file storagegatewayrequest.h.
Constructor & Destructor Documentation
StorageGatewayRequest() [1/3]
QtAws::StorageGateway::StorageGatewayRequest::StorageGatewayRequest (const Action action)
Constructs a new StorageGatewayRequest object.
Parameters
action The StorageGateway action to request.
Definition at line 38 of file storagegatewayrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new StorageGatewayRequestPrivate(action, this))
 {
 }
StorageGatewayRequest() [2/3]
QtAws::StorageGateway::StorageGatewayRequest::StorageGatewayRequest (const StorageGatewayRequest & other)
Constructs a new StorageGatewayRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file storagegatewayrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new StorageGatewayRequestPrivate(*other.d_func(), this))
 {
 }
StorageGatewayRequest() [3/3]
QtAws::StorageGateway::StorageGatewayRequest::StorageGatewayRequest (StorageGatewayRequestPrivate *const d) protected
Constructs a new StorageGatewayRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from StorageGatewayRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file storagegatewayrequest.cpp.
                                                                                    : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
StorageGatewayRequest::Action QtAws::StorageGateway::StorageGatewayRequest::action () const
Get the StorageGateway action to be performed by this request.
Returns
The StorageGateway action to be performed by this request.
Definition at line 93 of file storagegatewayrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const StorageGatewayRequest);
     return d->action;
 }
actionString()
QString QtAws::StorageGateway::StorageGatewayRequest::actionString () const
Get the name of the StorageGateway action to be performed by this request.
Returns
The name of the StorageGateway action to be performed by this request.
Definition at line 104 of file storagegatewayrequest.cpp.
References action(), and QtAws::StorageGateway::StorageGatewayRequestPrivate::toString().
 {
     return StorageGatewayRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::StorageGateway::StorageGatewayRequest::apiVersion () const
Get the StorageGateway API version implemented by this request.
Returns
The StorageGateway API version implmented by this request.
Definition at line 114 of file storagegatewayrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const StorageGatewayRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::StorageGateway::StorageGatewayRequest::clearParameter (const QString & name) protected
Check if queueName is a valid StorageGateway queue name.
From StorageGateway FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid StorageGateway queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file storagegatewayrequest.cpp.
 {
     Q_D(StorageGatewayRequest);
     return d->parameters.remove(name);
 }
operator=()
StorageGatewayRequest & QtAws::StorageGateway::StorageGatewayRequest::operator= (const StorageGatewayRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file storagegatewayrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(StorageGatewayRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::StorageGateway::StorageGatewayRequest::operator== (const StorageGatewayRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file storagegatewayrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::StorageGateway::StorageGatewayRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this StorageGateway request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file storagegatewayrequest.cpp.
 {
     Q_D(const StorageGatewayRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::StorageGateway::StorageGatewayRequest::parameters () const protected
Get all parameters included with this StorageGateway request.
Returns
A map of parameters included with this request.
Definition at line 222 of file storagegatewayrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const StorageGatewayRequest);
     return d->parameters;
 }
setAction()
void QtAws::StorageGateway::StorageGatewayRequest::setAction (const Action action)
Set the StorageGateway action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file storagegatewayrequest.cpp.
References action().
 {
     Q_D(StorageGatewayRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::StorageGateway::StorageGatewayRequest::setApiVersion (const QString & version)
Set the StorageGateway API version to include in this request.
Parameters
version The StorageGateway API version to include in this request.
Definition at line 136 of file storagegatewayrequest.cpp.
 {
     Q_D(StorageGatewayRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::StorageGateway::StorageGatewayRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this StorageGateway request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file storagegatewayrequest.cpp.
 {
     Q_D(StorageGatewayRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::StorageGateway::StorageGatewayRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this StorageGateway request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file storagegatewayrequest.cpp.
References parameters().
 {
     Q_D(StorageGatewayRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::StorageGateway::StorageGatewayRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this StorageGateway request.
This StorageGateway implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this StorageGateway request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file storagegatewayrequest.cpp.
 {
     Q_D(const StorageGatewayRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
storagegateway/storagegatewayrequest.h
storagegateway/storagegatewayrequest.cpp