AWS SDK for Qt: QtAws::APIGateway::APIGatewayClient Class Reference
QtAws::APIGateway::APIGatewayClient Class Reference
Client for Amazon API Gateway.
Public Slots
CreateApiKeyResponse * createApiKey (const CreateApiKeyRequest &request)
CreateAuthorizerResponse * createAuthorizer (const CreateAuthorizerRequest &request)
CreateBasePathMappingResponse * createBasePathMapping (const CreateBasePathMappingRequest &request)
CreateDeploymentResponse * createDeployment (const CreateDeploymentRequest &request)
CreateDocumentationPartResponse * createDocumentationPart (const CreateDocumentationPartRequest &request)
CreateDocumentationVersionResponse * createDocumentationVersion (const CreateDocumentationVersionRequest &request)
CreateDomainNameResponse * createDomainName (const CreateDomainNameRequest &request)
CreateModelResponse * createModel (const CreateModelRequest &request)
CreateRequestValidatorResponse * createRequestValidator (const CreateRequestValidatorRequest &request)
CreateResourceResponse * createResource (const CreateResourceRequest &request)
CreateRestApiResponse * createRestApi (const CreateRestApiRequest &request)
CreateStageResponse * createStage (const CreateStageRequest &request)
CreateUsagePlanResponse * createUsagePlan (const CreateUsagePlanRequest &request)
CreateUsagePlanKeyResponse * createUsagePlanKey (const CreateUsagePlanKeyRequest &request)
CreateVpcLinkResponse * createVpcLink (const CreateVpcLinkRequest &request)
DeleteApiKeyResponse * deleteApiKey (const DeleteApiKeyRequest &request)
DeleteAuthorizerResponse * deleteAuthorizer (const DeleteAuthorizerRequest &request)
DeleteBasePathMappingResponse * deleteBasePathMapping (const DeleteBasePathMappingRequest &request)
DeleteClientCertificateResponse * deleteClientCertificate (const DeleteClientCertificateRequest &request)
DeleteDeploymentResponse * deleteDeployment (const DeleteDeploymentRequest &request)
DeleteDocumentationPartResponse * deleteDocumentationPart (const DeleteDocumentationPartRequest &request)
DeleteDocumentationVersionResponse * deleteDocumentationVersion (const DeleteDocumentationVersionRequest &request)
DeleteDomainNameResponse * deleteDomainName (const DeleteDomainNameRequest &request)
DeleteGatewayResponseResponse * deleteGatewayResponse (const DeleteGatewayResponseRequest &request)
DeleteIntegrationResponse * deleteIntegration (const DeleteIntegrationRequest &request)
DeleteIntegrationResponseResponse * deleteIntegrationResponse (const DeleteIntegrationResponseRequest &request)
DeleteMethodResponse * deleteMethod (const DeleteMethodRequest &request)
DeleteMethodResponseResponse * deleteMethodResponse (const DeleteMethodResponseRequest &request)
DeleteModelResponse * deleteModel (const DeleteModelRequest &request)
DeleteRequestValidatorResponse * deleteRequestValidator (const DeleteRequestValidatorRequest &request)
DeleteResourceResponse * deleteResource (const DeleteResourceRequest &request)
DeleteRestApiResponse * deleteRestApi (const DeleteRestApiRequest &request)
DeleteStageResponse * deleteStage (const DeleteStageRequest &request)
DeleteUsagePlanResponse * deleteUsagePlan (const DeleteUsagePlanRequest &request)
DeleteUsagePlanKeyResponse * deleteUsagePlanKey (const DeleteUsagePlanKeyRequest &request)
DeleteVpcLinkResponse * deleteVpcLink (const DeleteVpcLinkRequest &request)
FlushStageAuthorizersCacheResponse * flushStageAuthorizersCache (const FlushStageAuthorizersCacheRequest &request)
FlushStageCacheResponse * flushStageCache (const FlushStageCacheRequest &request)
GenerateClientCertificateResponse * generateClientCertificate (const GenerateClientCertificateRequest &request)
GetAccountResponse * getAccount (const GetAccountRequest &request)
GetApiKeyResponse * getApiKey (const GetApiKeyRequest &request)
GetApiKeysResponse * getApiKeys (const GetApiKeysRequest &request)
GetAuthorizerResponse * getAuthorizer (const GetAuthorizerRequest &request)
GetAuthorizersResponse * getAuthorizers (const GetAuthorizersRequest &request)
GetBasePathMappingResponse * getBasePathMapping (const GetBasePathMappingRequest &request)
GetBasePathMappingsResponse * getBasePathMappings (const GetBasePathMappingsRequest &request)
GetClientCertificateResponse * getClientCertificate (const GetClientCertificateRequest &request)
GetClientCertificatesResponse * getClientCertificates (const GetClientCertificatesRequest &request)
GetDeploymentResponse * getDeployment (const GetDeploymentRequest &request)
GetDeploymentsResponse * getDeployments (const GetDeploymentsRequest &request)
GetDocumentationPartResponse * getDocumentationPart (const GetDocumentationPartRequest &request)
GetDocumentationPartsResponse * getDocumentationParts (const GetDocumentationPartsRequest &request)
GetDocumentationVersionResponse * getDocumentationVersion (const GetDocumentationVersionRequest &request)
GetDocumentationVersionsResponse * getDocumentationVersions (const GetDocumentationVersionsRequest &request)
GetDomainNameResponse * getDomainName (const GetDomainNameRequest &request)
GetDomainNamesResponse * getDomainNames (const GetDomainNamesRequest &request)
GetExportResponse * getExport (const GetExportRequest &request)
GetGatewayResponseResponse * getGatewayResponse (const GetGatewayResponseRequest &request)
GetGatewayResponsesResponse * getGatewayResponses (const GetGatewayResponsesRequest &request)
GetIntegrationResponse * getIntegration (const GetIntegrationRequest &request)
GetIntegrationResponseResponse * getIntegrationResponse (const GetIntegrationResponseRequest &request)
GetMethodResponse * getMethod (const GetMethodRequest &request)
GetMethodResponseResponse * getMethodResponse (const GetMethodResponseRequest &request)
GetModelResponse * getModel (const GetModelRequest &request)
GetModelTemplateResponse * getModelTemplate (const GetModelTemplateRequest &request)
GetModelsResponse * getModels (const GetModelsRequest &request)
GetRequestValidatorResponse * getRequestValidator (const GetRequestValidatorRequest &request)
GetRequestValidatorsResponse * getRequestValidators (const GetRequestValidatorsRequest &request)
GetResourceResponse * getResource (const GetResourceRequest &request)
GetResourcesResponse * getResources (const GetResourcesRequest &request)
GetRestApiResponse * getRestApi (const GetRestApiRequest &request)
GetRestApisResponse * getRestApis (const GetRestApisRequest &request)
GetSdkResponse * getSdk (const GetSdkRequest &request)
GetSdkTypeResponse * getSdkType (const GetSdkTypeRequest &request)
GetSdkTypesResponse * getSdkTypes (const GetSdkTypesRequest &request)
GetStageResponse * getStage (const GetStageRequest &request)
GetStagesResponse * getStages (const GetStagesRequest &request)
GetTagsResponse * getTags (const GetTagsRequest &request)
GetUsageResponse * getUsage (const GetUsageRequest &request)
GetUsagePlanResponse * getUsagePlan (const GetUsagePlanRequest &request)
GetUsagePlanKeyResponse * getUsagePlanKey (const GetUsagePlanKeyRequest &request)
GetUsagePlanKeysResponse * getUsagePlanKeys (const GetUsagePlanKeysRequest &request)
GetUsagePlansResponse * getUsagePlans (const GetUsagePlansRequest &request)
GetVpcLinkResponse * getVpcLink (const GetVpcLinkRequest &request)
GetVpcLinksResponse * getVpcLinks (const GetVpcLinksRequest &request)
ImportApiKeysResponse * importApiKeys (const ImportApiKeysRequest &request)
ImportDocumentationPartsResponse * importDocumentationParts (const ImportDocumentationPartsRequest &request)
ImportRestApiResponse * importRestApi (const ImportRestApiRequest &request)
PutGatewayResponseResponse * putGatewayResponse (const PutGatewayResponseRequest &request)
PutIntegrationResponse * putIntegration (const PutIntegrationRequest &request)
PutIntegrationResponseResponse * putIntegrationResponse (const PutIntegrationResponseRequest &request)
PutMethodResponse * putMethod (const PutMethodRequest &request)
PutMethodResponseResponse * putMethodResponse (const PutMethodResponseRequest &request)
PutRestApiResponse * putRestApi (const PutRestApiRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
TestInvokeAuthorizerResponse * testInvokeAuthorizer (const TestInvokeAuthorizerRequest &request)
TestInvokeMethodResponse * testInvokeMethod (const TestInvokeMethodRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateAccountResponse * updateAccount (const UpdateAccountRequest &request)
UpdateApiKeyResponse * updateApiKey (const UpdateApiKeyRequest &request)
UpdateAuthorizerResponse * updateAuthorizer (const UpdateAuthorizerRequest &request)
UpdateBasePathMappingResponse * updateBasePathMapping (const UpdateBasePathMappingRequest &request)
UpdateClientCertificateResponse * updateClientCertificate (const UpdateClientCertificateRequest &request)
UpdateDeploymentResponse * updateDeployment (const UpdateDeploymentRequest &request)
UpdateDocumentationPartResponse * updateDocumentationPart (const UpdateDocumentationPartRequest &request)
UpdateDocumentationVersionResponse * updateDocumentationVersion (const UpdateDocumentationVersionRequest &request)
UpdateDomainNameResponse * updateDomainName (const UpdateDomainNameRequest &request)
UpdateGatewayResponseResponse * updateGatewayResponse (const UpdateGatewayResponseRequest &request)
UpdateIntegrationResponse * updateIntegration (const UpdateIntegrationRequest &request)
UpdateIntegrationResponseResponse * updateIntegrationResponse (const UpdateIntegrationResponseRequest &request)
UpdateMethodResponse * updateMethod (const UpdateMethodRequest &request)
UpdateMethodResponseResponse * updateMethodResponse (const UpdateMethodResponseRequest &request)
UpdateModelResponse * updateModel (const UpdateModelRequest &request)
UpdateRequestValidatorResponse * updateRequestValidator (const UpdateRequestValidatorRequest &request)
UpdateResourceResponse * updateResource (const UpdateResourceRequest &request)
UpdateRestApiResponse * updateRestApi (const UpdateRestApiRequest &request)
UpdateStageResponse * updateStage (const UpdateStageRequest &request)
UpdateUsageResponse * updateUsage (const UpdateUsageRequest &request)
UpdateUsagePlanResponse * updateUsagePlan (const UpdateUsagePlanRequest &request)
UpdateVpcLinkResponse * updateVpcLink (const UpdateVpcLinkRequest &request)
Public Member Functions
APIGatewayClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new APIGatewayClient object.
APIGatewayClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new APIGatewayClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon API Gateway.
<fullname>Amazon API Gateway</fullname>
Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of
Definition at line 272 of file apigatewayclient.h.
Constructor & Destructor Documentation
APIGatewayClient() [1/2]
QtAws::APIGateway::APIGatewayClient::APIGatewayClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new APIGatewayClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 291 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new APIGatewayClientPrivate(this), parent)
 {
     Q_D(APIGatewayClient);
     d->apiVersion = QStringLiteral("2015-07-09");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("apigateway");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon API Gateway");
     d->serviceName = QStringLiteral("apigateway");
 }
APIGatewayClient() [2/2]
QtAws::APIGateway::APIGatewayClient::APIGatewayClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new APIGatewayClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 324 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new APIGatewayClientPrivate(this), parent)
 {
     Q_D(APIGatewayClient);
     d->apiVersion = QStringLiteral("2015-07-09");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("apigateway");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon API Gateway");
     d->serviceName = QStringLiteral("apigateway");
 }
Member Function Documentation
createApiKey
CreateApiKeyResponse * QtAws::APIGateway::APIGatewayClient::createApiKey (const CreateApiKeyRequest & request) slot
Create an ApiKey resource.
</p
AWS request Request to send to Amazon API Gateway. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 352 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateApiKeyResponse *>(send(request));
 }
createAuthorizer
CreateAuthorizerResponse * QtAws::APIGateway::APIGatewayClient::createAuthorizer (const CreateAuthorizerRequest & request) slot
Adds a new Authorizer resource to an existing RestApi
resource>
<a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 368 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAuthorizerResponse *>(send(request));
 }
createBasePathMapping
CreateBasePathMappingResponse * QtAws::APIGateway::APIGatewayClient::createBasePathMapping (const CreateBasePathMappingRequest & request) slot
Creates a new BasePathMapping
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 382 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBasePathMappingResponse *>(send(request));
 }
createDeployment
CreateDeploymentResponse * QtAws::APIGateway::APIGatewayClient::createDeployment (const CreateDeploymentRequest & request) slot
Creates a Deployment resource, which makes a specified RestApi callable over the
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 396 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDeploymentResponse *>(send(request));
 }
createDocumentationPart
CreateDocumentationPartResponse * QtAws::APIGateway::APIGatewayClient::createDocumentationPart (const CreateDocumentationPartRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDocumentationPartResponse *>(send(request));
 }
createDocumentationVersion
CreateDocumentationVersionResponse * QtAws::APIGateway::APIGatewayClient::createDocumentationVersion (const CreateDocumentationVersionRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 422 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDocumentationVersionResponse *>(send(request));
 }
createDomainName
CreateDomainNameResponse * QtAws::APIGateway::APIGatewayClient::createDomainName (const CreateDomainNameRequest & request) slot
Creates a new domain
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 436 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDomainNameResponse *>(send(request));
 }
createModel
CreateModelResponse * QtAws::APIGateway::APIGatewayClient::createModel (const CreateModelRequest & request) slot
Adds a new Model resource to an existing RestApi
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 450 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateModelResponse *>(send(request));
 }
createRequestValidator
CreateRequestValidatorResponse * QtAws::APIGateway::APIGatewayClient::createRequestValidator (const CreateRequestValidatorRequest & request) slot
Creates a ReqeustValidator of a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 464 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRequestValidatorResponse *>(send(request));
 }
createResource
CreateResourceResponse * QtAws::APIGateway::APIGatewayClient::createResource (const CreateResourceRequest & request) slot
Creates a Resource
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 478 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateResourceResponse *>(send(request));
 }
createRestApi
CreateRestApiResponse * QtAws::APIGateway::APIGatewayClient::createRestApi (const CreateRestApiRequest & request) slot
Creates a new RestApi
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 492 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRestApiResponse *>(send(request));
 }
createStage
CreateStageResponse * QtAws::APIGateway::APIGatewayClient::createStage (const CreateStageRequest & request) slot
Creates a new Stage resource that references a pre-existing Deployment for the API.
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 506 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStageResponse *>(send(request));
 }
createUsagePlan
CreateUsagePlanResponse * QtAws::APIGateway::APIGatewayClient::createUsagePlan (const CreateUsagePlanRequest & request) slot
Creates a usage plan with the throttle and quota limits, as well as the associated API stages, specified in the payload.
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 520 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUsagePlanResponse *>(send(request));
 }
createUsagePlanKey
CreateUsagePlanKeyResponse * QtAws::APIGateway::APIGatewayClient::createUsagePlanKey (const CreateUsagePlanKeyRequest & request) slot
Creates a usage plan key for adding an existing API key to a usage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 534 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUsagePlanKeyResponse *>(send(request));
 }
createVpcLink
CreateVpcLinkResponse * QtAws::APIGateway::APIGatewayClient::createVpcLink (const CreateVpcLinkRequest & request) slot
Creates a VPC link, under the caller's account in a selected region, in an asynchronous operation that typically takes 2-4 minutes to complete and become operational. The caller must have permissions to create and update VPC Endpoint
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 549 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcLinkResponse *>(send(request));
 }
deleteApiKey
DeleteApiKeyResponse * QtAws::APIGateway::APIGatewayClient::deleteApiKey (const DeleteApiKeyRequest & request) slot
Deletes the ApiKey
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 563 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApiKeyResponse *>(send(request));
 }
deleteAuthorizer
DeleteAuthorizerResponse * QtAws::APIGateway::APIGatewayClient::deleteAuthorizer (const DeleteAuthorizerRequest & request) slot
Deletes an existing Authorizer
resource>
<a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 579 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAuthorizerResponse *>(send(request));
 }
deleteBasePathMapping
DeleteBasePathMappingResponse * QtAws::APIGateway::APIGatewayClient::deleteBasePathMapping (const DeleteBasePathMappingRequest & request) slot
Deletes the BasePathMapping
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 593 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBasePathMappingResponse *>(send(request));
 }
deleteClientCertificate
DeleteClientCertificateResponse * QtAws::APIGateway::APIGatewayClient::deleteClientCertificate (const DeleteClientCertificateRequest & request) slot
Deletes the ClientCertificate
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 607 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteClientCertificateResponse *>(send(request));
 }
deleteDeployment
DeleteDeploymentResponse * QtAws::APIGateway::APIGatewayClient::deleteDeployment (const DeleteDeploymentRequest & request) slot
Deletes a Deployment resource. Deleting a deployment will only succeed if there are no Stage resources associated with
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 622 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDeploymentResponse *>(send(request));
 }
deleteDocumentationPart
DeleteDocumentationPartResponse * QtAws::APIGateway::APIGatewayClient::deleteDocumentationPart (const DeleteDocumentationPartRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 635 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDocumentationPartResponse *>(send(request));
 }
deleteDocumentationVersion
DeleteDocumentationVersionResponse * QtAws::APIGateway::APIGatewayClient::deleteDocumentationVersion (const DeleteDocumentationVersionRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 648 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDocumentationVersionResponse *>(send(request));
 }
deleteDomainName
DeleteDomainNameResponse * QtAws::APIGateway::APIGatewayClient::deleteDomainName (const DeleteDomainNameRequest & request) slot
Deletes the DomainName
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 662 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDomainNameResponse *>(send(request));
 }
deleteGatewayResponse
DeleteGatewayResponseResponse * QtAws::APIGateway::APIGatewayClient::deleteGatewayResponse (const DeleteGatewayResponseRequest & request) slot
Clears any customization of a GatewayResponse of a specified response type on the given RestApi and resets it with the default
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 677 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGatewayResponseResponse *>(send(request));
 }
deleteIntegration
DeleteIntegrationResponse * QtAws::APIGateway::APIGatewayClient::deleteIntegration (const DeleteIntegrationRequest & request) slot
Represents a delete
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 691 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIntegrationResponse *>(send(request));
 }
deleteIntegrationResponse
DeleteIntegrationResponseResponse * QtAws::APIGateway::APIGatewayClient::deleteIntegrationResponse (const DeleteIntegrationResponseRequest & request) slot
Represents a delete integration
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 705 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIntegrationResponseResponse *>(send(request));
 }
deleteMethod
DeleteMethodResponse * QtAws::APIGateway::APIGatewayClient::deleteMethod (const DeleteMethodRequest & request) slot
Deletes an existing Method
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMethodResponse *>(send(request));
 }
deleteMethodResponse
DeleteMethodResponseResponse * QtAws::APIGateway::APIGatewayClient::deleteMethodResponse (const DeleteMethodResponseRequest & request) slot
Deletes an existing MethodResponse
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 733 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMethodResponseResponse *>(send(request));
 }
deleteModel
DeleteModelResponse * QtAws::APIGateway::APIGatewayClient::deleteModel (const DeleteModelRequest & request) slot
Deletes a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 747 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteModelResponse *>(send(request));
 }
deleteRequestValidator
DeleteRequestValidatorResponse * QtAws::APIGateway::APIGatewayClient::deleteRequestValidator (const DeleteRequestValidatorRequest & request) slot
Deletes a RequestValidator of a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 761 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRequestValidatorResponse *>(send(request));
 }
deleteResource
DeleteResourceResponse * QtAws::APIGateway::APIGatewayClient::deleteResource (const DeleteResourceRequest & request) slot
Deletes a Resource
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 775 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteResourceResponse *>(send(request));
 }
deleteRestApi
DeleteRestApiResponse * QtAws::APIGateway::APIGatewayClient::deleteRestApi (const DeleteRestApiRequest & request) slot
Deletes the specified
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 789 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRestApiResponse *>(send(request));
 }
deleteStage
DeleteStageResponse * QtAws::APIGateway::APIGatewayClient::deleteStage (const DeleteStageRequest & request) slot
Deletes a Stage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 803 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStageResponse *>(send(request));
 }
deleteUsagePlan
DeleteUsagePlanResponse * QtAws::APIGateway::APIGatewayClient::deleteUsagePlan (const DeleteUsagePlanRequest & request) slot
Deletes a usage plan of a given plan
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 817 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUsagePlanResponse *>(send(request));
 }
deleteUsagePlanKey
DeleteUsagePlanKeyResponse * QtAws::APIGateway::APIGatewayClient::deleteUsagePlanKey (const DeleteUsagePlanKeyRequest & request) slot
Deletes a usage plan key and remove the underlying API key from the associated usage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 831 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUsagePlanKeyResponse *>(send(request));
 }
deleteVpcLink
DeleteVpcLinkResponse * QtAws::APIGateway::APIGatewayClient::deleteVpcLink (const DeleteVpcLinkRequest & request) slot
Deletes an existing VpcLink of a specified
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 845 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcLinkResponse *>(send(request));
 }
flushStageAuthorizersCache
FlushStageAuthorizersCacheResponse * QtAws::APIGateway::APIGatewayClient::flushStageAuthorizersCache (const FlushStageAuthorizersCacheRequest & request) slot
Flushes all authorizer cache entries on a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 859 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<FlushStageAuthorizersCacheResponse *>(send(request));
 }
flushStageCache
FlushStageCacheResponse * QtAws::APIGateway::APIGatewayClient::flushStageCache (const FlushStageCacheRequest & request) slot
Flushes a stage's
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 873 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<FlushStageCacheResponse *>(send(request));
 }
generateClientCertificate
GenerateClientCertificateResponse * QtAws::APIGateway::APIGatewayClient::generateClientCertificate (const GenerateClientCertificateRequest & request) slot
Generates a ClientCertificate
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 887 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GenerateClientCertificateResponse *>(send(request));
 }
getAccount
GetAccountResponse * QtAws::APIGateway::APIGatewayClient::getAccount (const GetAccountRequest & request) slot
Gets information about the current Account
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 901 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountResponse *>(send(request));
 }
getApiKey
GetApiKeyResponse * QtAws::APIGateway::APIGatewayClient::getApiKey (const GetApiKeyRequest & request) slot
Gets information about the current ApiKey
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 915 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApiKeyResponse *>(send(request));
 }
getApiKeys
GetApiKeysResponse * QtAws::APIGateway::APIGatewayClient::getApiKeys (const GetApiKeysRequest & request) slot
Gets information about the current ApiKeys
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 929 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApiKeysResponse *>(send(request));
 }
getAuthorizer
GetAuthorizerResponse * QtAws::APIGateway::APIGatewayClient::getAuthorizer (const GetAuthorizerRequest & request) slot
Describe an existing Authorizer
resource>
<a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 945 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAuthorizerResponse *>(send(request));
 }
getAuthorizers
GetAuthorizersResponse * QtAws::APIGateway::APIGatewayClient::getAuthorizers (const GetAuthorizersRequest & request) slot
Describe an existing Authorizers
resource>
<a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 961 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAuthorizersResponse *>(send(request));
 }
getBasePathMapping
GetBasePathMappingResponse * QtAws::APIGateway::APIGatewayClient::getBasePathMapping (const GetBasePathMappingRequest & request) slot
Describe a BasePathMapping
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 975 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBasePathMappingResponse *>(send(request));
 }
getBasePathMappings
GetBasePathMappingsResponse * QtAws::APIGateway::APIGatewayClient::getBasePathMappings (const GetBasePathMappingsRequest & request) slot
Represents a collection of BasePathMapping
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 989 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBasePathMappingsResponse *>(send(request));
 }
getClientCertificate
GetClientCertificateResponse * QtAws::APIGateway::APIGatewayClient::getClientCertificate (const GetClientCertificateRequest & request) slot
Gets information about the current ClientCertificate
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1003 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetClientCertificateResponse *>(send(request));
 }
getClientCertificates
GetClientCertificatesResponse * QtAws::APIGateway::APIGatewayClient::getClientCertificates (const GetClientCertificatesRequest & request) slot
Gets a collection of ClientCertificate
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1017 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetClientCertificatesResponse *>(send(request));
 }
getDeployment
GetDeploymentResponse * QtAws::APIGateway::APIGatewayClient::getDeployment (const GetDeploymentRequest & request) slot
Gets information about a Deployment
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1031 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentResponse *>(send(request));
 }
getDeployments
GetDeploymentsResponse * QtAws::APIGateway::APIGatewayClient::getDeployments (const GetDeploymentsRequest & request) slot
Gets information about a Deployments
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1045 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentsResponse *>(send(request));
 }
getDocumentationPart
GetDocumentationPartResponse * QtAws::APIGateway::APIGatewayClient::getDocumentationPart (const GetDocumentationPartRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1058 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentationPartResponse *>(send(request));
 }
getDocumentationParts
GetDocumentationPartsResponse * QtAws::APIGateway::APIGatewayClient::getDocumentationParts (const GetDocumentationPartsRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1071 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentationPartsResponse *>(send(request));
 }
getDocumentationVersion
GetDocumentationVersionResponse * QtAws::APIGateway::APIGatewayClient::getDocumentationVersion (const GetDocumentationVersionRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1084 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentationVersionResponse *>(send(request));
 }
getDocumentationVersions
GetDocumentationVersionsResponse * QtAws::APIGateway::APIGatewayClient::getDocumentationVersions (const GetDocumentationVersionsRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1097 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentationVersionsResponse *>(send(request));
 }
getDomainName
GetDomainNameResponse * QtAws::APIGateway::APIGatewayClient::getDomainName (const GetDomainNameRequest & request) slot
Represents a domain name that is contained in a simpler, more intuitive URL that can be
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1111 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDomainNameResponse *>(send(request));
 }
getDomainNames
GetDomainNamesResponse * QtAws::APIGateway::APIGatewayClient::getDomainNames (const GetDomainNamesRequest & request) slot
Represents a collection of DomainName
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1125 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDomainNamesResponse *>(send(request));
 }
getExport
GetExportResponse * QtAws::APIGateway::APIGatewayClient::getExport (const GetExportRequest & request) slot
Exports a deployed version of a RestApi in a specified
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1139 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetExportResponse *>(send(request));
 }
getGatewayResponse
GetGatewayResponseResponse * QtAws::APIGateway::APIGatewayClient::getGatewayResponse (const GetGatewayResponseRequest & request) slot
Gets a GatewayResponse of a specified response type on the given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1153 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGatewayResponseResponse *>(send(request));
 }
getGatewayResponses
GetGatewayResponsesResponse * QtAws::APIGateway::APIGatewayClient::getGatewayResponses (const GetGatewayResponsesRequest & request) slot
Gets the GatewayResponses collection on the given RestApi. If an API developer has not added any definitions for gateway responses, the result will be the API Gateway-generated default GatewayResponses collection for the supported response
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1169 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGatewayResponsesResponse *>(send(request));
 }
getIntegration
GetIntegrationResponse * QtAws::APIGateway::APIGatewayClient::getIntegration (const GetIntegrationRequest & request) slot
Get the integration
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1183 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIntegrationResponse *>(send(request));
 }
getIntegrationResponse
GetIntegrationResponseResponse * QtAws::APIGateway::APIGatewayClient::getIntegrationResponse (const GetIntegrationResponseRequest & request) slot
Represents a get integration
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1197 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIntegrationResponseResponse *>(send(request));
 }
getMethod
GetMethodResponse * QtAws::APIGateway::APIGatewayClient::getMethod (const GetMethodRequest & request) slot
Describe an existing Method
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1211 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetMethodResponse *>(send(request));
 }
getMethodResponse
GetMethodResponseResponse * QtAws::APIGateway::APIGatewayClient::getMethodResponse (const GetMethodResponseRequest & request) slot
Describes a MethodResponse
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1225 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetMethodResponseResponse *>(send(request));
 }
getModel
GetModelResponse * QtAws::APIGateway::APIGatewayClient::getModel (const GetModelRequest & request) slot
Describes an existing model defined for a RestApi
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1239 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetModelResponse *>(send(request));
 }
getModels
GetModelsResponse * QtAws::APIGateway::APIGatewayClient::getModels (const GetModelsRequest & request) slot
Describes existing Models defined for a RestApi
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1267 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetModelsResponse *>(send(request));
 }
getModelTemplate
GetModelTemplateResponse * QtAws::APIGateway::APIGatewayClient::getModelTemplate (const GetModelTemplateRequest & request) slot
Generates a sample mapping template that can be used to transform a payload into the structure of a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1253 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetModelTemplateResponse *>(send(request));
 }
getRequestValidator
GetRequestValidatorResponse * QtAws::APIGateway::APIGatewayClient::getRequestValidator (const GetRequestValidatorRequest & request) slot
Gets a RequestValidator of a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1281 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRequestValidatorResponse *>(send(request));
 }
getRequestValidators
GetRequestValidatorsResponse * QtAws::APIGateway::APIGatewayClient::getRequestValidators (const GetRequestValidatorsRequest & request) slot
Gets the RequestValidators collection of a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1295 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRequestValidatorsResponse *>(send(request));
 }
getResource
GetResourceResponse * QtAws::APIGateway::APIGatewayClient::getResource (const GetResourceRequest & request) slot
Lists information about a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1309 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetResourceResponse *>(send(request));
 }
getResources
GetResourcesResponse * QtAws::APIGateway::APIGatewayClient::getResources (const GetResourcesRequest & request) slot
Lists information about a collection of Resource
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1323 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetResourcesResponse *>(send(request));
 }
getRestApi
GetRestApiResponse * QtAws::APIGateway::APIGatewayClient::getRestApi (const GetRestApiRequest & request) slot
Lists the RestApi resource in the
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1337 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRestApiResponse *>(send(request));
 }
getRestApis
GetRestApisResponse * QtAws::APIGateway::APIGatewayClient::getRestApis (const GetRestApisRequest & request) slot
Lists the RestApis resources for your
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1351 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRestApisResponse *>(send(request));
 }
getSdk
GetSdkResponse * QtAws::APIGateway::APIGatewayClient::getSdk (const GetSdkRequest & request) slot
Generates a client SDK for a RestApi and
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1365 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSdkResponse *>(send(request));
 }
getSdkType
GetSdkTypeResponse * QtAws::APIGateway::APIGatewayClient::getSdkType (const GetSdkTypeRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1378 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSdkTypeResponse *>(send(request));
 }
getSdkTypes
GetSdkTypesResponse * QtAws::APIGateway::APIGatewayClient::getSdkTypes (const GetSdkTypesRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1391 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSdkTypesResponse *>(send(request));
 }
getStage
GetStageResponse * QtAws::APIGateway::APIGatewayClient::getStage (const GetStageRequest & request) slot
Gets information about a Stage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1405 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStageResponse *>(send(request));
 }
getStages
GetStagesResponse * QtAws::APIGateway::APIGatewayClient::getStages (const GetStagesRequest & request) slot
Gets information about one or more Stage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1419 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetStagesResponse *>(send(request));
 }
getTags
GetTagsResponse * QtAws::APIGateway::APIGatewayClient::getTags (const GetTagsRequest & request) slot
Gets the Tags collection for a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1433 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTagsResponse *>(send(request));
 }
getUsage
GetUsageResponse * QtAws::APIGateway::APIGatewayClient::getUsage (const GetUsageRequest & request) slot
Gets the usage data of a usage plan in a specified time
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1447 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUsageResponse *>(send(request));
 }
getUsagePlan
GetUsagePlanResponse * QtAws::APIGateway::APIGatewayClient::getUsagePlan (const GetUsagePlanRequest & request) slot
Gets a usage plan of a given plan
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1461 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUsagePlanResponse *>(send(request));
 }
getUsagePlanKey
GetUsagePlanKeyResponse * QtAws::APIGateway::APIGatewayClient::getUsagePlanKey (const GetUsagePlanKeyRequest & request) slot
Gets a usage plan key of a given key
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1475 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUsagePlanKeyResponse *>(send(request));
 }
getUsagePlanKeys
GetUsagePlanKeysResponse * QtAws::APIGateway::APIGatewayClient::getUsagePlanKeys (const GetUsagePlanKeysRequest & request) slot
Gets all the usage plan keys representing the API keys added to a specified usage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1489 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUsagePlanKeysResponse *>(send(request));
 }
getUsagePlans
GetUsagePlansResponse * QtAws::APIGateway::APIGatewayClient::getUsagePlans (const GetUsagePlansRequest & request) slot
Gets all the usage plans of the caller's
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1503 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUsagePlansResponse *>(send(request));
 }
getVpcLink
GetVpcLinkResponse * QtAws::APIGateway::APIGatewayClient::getVpcLink (const GetVpcLinkRequest & request) slot
Gets a specified VPC link under the caller's account in a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1517 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetVpcLinkResponse *>(send(request));
 }
getVpcLinks
GetVpcLinksResponse * QtAws::APIGateway::APIGatewayClient::getVpcLinks (const GetVpcLinksRequest & request) slot
Gets the VpcLinks collection under the caller's account in a selected
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1531 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetVpcLinksResponse *>(send(request));
 }
importApiKeys
ImportApiKeysResponse * QtAws::APIGateway::APIGatewayClient::importApiKeys (const ImportApiKeysRequest & request) slot
Import API keys from an external source, such as a CSV-formatted
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1545 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportApiKeysResponse *>(send(request));
 }
importDocumentationParts
ImportDocumentationPartsResponse * QtAws::APIGateway::APIGatewayClient::importDocumentationParts (const ImportDocumentationPartsRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1558 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportDocumentationPartsResponse *>(send(request));
 }
importRestApi
ImportRestApiResponse * QtAws::APIGateway::APIGatewayClient::importRestApi (const ImportRestApiRequest & request) slot
A feature of the API Gateway control service for creating a new API from an external API definition
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1572 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportRestApiResponse *>(send(request));
 }
putGatewayResponse
PutGatewayResponseResponse * QtAws::APIGateway::APIGatewayClient::putGatewayResponse (const PutGatewayResponseRequest & request) slot
Creates a customization of a GatewayResponse of a specified response type and status code on the given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1586 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutGatewayResponseResponse *>(send(request));
 }
putIntegration
PutIntegrationResponse * QtAws::APIGateway::APIGatewayClient::putIntegration (const PutIntegrationRequest & request) slot
Sets up a method's
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1600 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutIntegrationResponse *>(send(request));
 }
putIntegrationResponse
PutIntegrationResponseResponse * QtAws::APIGateway::APIGatewayClient::putIntegrationResponse (const PutIntegrationResponseRequest & request) slot
Represents a put
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1614 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutIntegrationResponseResponse *>(send(request));
 }
putMethod
PutMethodResponse * QtAws::APIGateway::APIGatewayClient::putMethod (const PutMethodRequest & request) slot
Add a method to an existing Resource
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1628 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutMethodResponse *>(send(request));
 }
putMethodResponse
PutMethodResponseResponse * QtAws::APIGateway::APIGatewayClient::putMethodResponse (const PutMethodResponseRequest & request) slot
Adds a MethodResponse to an existing Method
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1642 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutMethodResponseResponse *>(send(request));
 }
putRestApi
PutRestApiResponse * QtAws::APIGateway::APIGatewayClient::putRestApi (const PutRestApiRequest & request) slot
A feature of the API Gateway control service for updating an existing API with an input of external API definitions. The update can take the form of merging the supplied definition into the existing API or overwriting the existing
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1657 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutRestApiResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::APIGateway::APIGatewayClient::tagResource (const TagResourceRequest & request) slot
Adds or updates Tags on a gievn
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1671 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
testInvokeAuthorizer
TestInvokeAuthorizerResponse * QtAws::APIGateway::APIGatewayClient::testInvokeAuthorizer (const TestInvokeAuthorizerRequest & request) slot
Simulate the execution of an Authorizer in your RestApi with headers, parameters, and an incoming request
body>
Enable custom request Request to send to Amazon API Gateway. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1688 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestInvokeAuthorizerResponse *>(send(request));
 }
testInvokeMethod
TestInvokeMethodResponse * QtAws::APIGateway::APIGatewayClient::testInvokeMethod (const TestInvokeMethodRequest & request) slot
Simulate the execution of a Method in your RestApi with headers, parameters, and an incoming request
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1702 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestInvokeMethodResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::APIGateway::APIGatewayClient::untagResource (const UntagResourceRequest & request) slot
Removes Tags from a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1716 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateAccount
UpdateAccountResponse * QtAws::APIGateway::APIGatewayClient::updateAccount (const UpdateAccountRequest & request) slot
Changes information about the current Account
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1730 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAccountResponse *>(send(request));
 }
updateApiKey
UpdateApiKeyResponse * QtAws::APIGateway::APIGatewayClient::updateApiKey (const UpdateApiKeyRequest & request) slot
Changes information about an ApiKey
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1744 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApiKeyResponse *>(send(request));
 }
updateAuthorizer
UpdateAuthorizerResponse * QtAws::APIGateway::APIGatewayClient::updateAuthorizer (const UpdateAuthorizerRequest & request) slot
Updates an existing Authorizer
resource>
<a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1760 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAuthorizerResponse *>(send(request));
 }
updateBasePathMapping
UpdateBasePathMappingResponse * QtAws::APIGateway::APIGatewayClient::updateBasePathMapping (const UpdateBasePathMappingRequest & request) slot
Changes information about the BasePathMapping
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1774 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBasePathMappingResponse *>(send(request));
 }
updateClientCertificate
UpdateClientCertificateResponse * QtAws::APIGateway::APIGatewayClient::updateClientCertificate (const UpdateClientCertificateRequest & request) slot
Changes information about an ClientCertificate
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1788 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateClientCertificateResponse *>(send(request));
 }
updateDeployment
UpdateDeploymentResponse * QtAws::APIGateway::APIGatewayClient::updateDeployment (const UpdateDeploymentRequest & request) slot
Changes information about a Deployment
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1802 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDeploymentResponse *>(send(request));
 }
updateDocumentationPart
UpdateDocumentationPartResponse * QtAws::APIGateway::APIGatewayClient::updateDocumentationPart (const UpdateDocumentationPartRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1815 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDocumentationPartResponse *>(send(request));
 }
updateDocumentationVersion
UpdateDocumentationVersionResponse * QtAws::APIGateway::APIGatewayClient::updateDocumentationVersion (const UpdateDocumentationVersionRequest & request) slot
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1828 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDocumentationVersionResponse *>(send(request));
 }
updateDomainName
UpdateDomainNameResponse * QtAws::APIGateway::APIGatewayClient::updateDomainName (const UpdateDomainNameRequest & request) slot
Changes information about the DomainName
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1842 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDomainNameResponse *>(send(request));
 }
updateGatewayResponse
UpdateGatewayResponseResponse * QtAws::APIGateway::APIGatewayClient::updateGatewayResponse (const UpdateGatewayResponseRequest & request) slot
Updates a GatewayResponse of a specified response type on the given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1856 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGatewayResponseResponse *>(send(request));
 }
updateIntegration
UpdateIntegrationResponse * QtAws::APIGateway::APIGatewayClient::updateIntegration (const UpdateIntegrationRequest & request) slot
Represents an update
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1870 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateIntegrationResponse *>(send(request));
 }
updateIntegrationResponse
UpdateIntegrationResponseResponse * QtAws::APIGateway::APIGatewayClient::updateIntegrationResponse (const UpdateIntegrationResponseRequest & request) slot
Represents an update integration
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1884 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateIntegrationResponseResponse *>(send(request));
 }
updateMethod
UpdateMethodResponse * QtAws::APIGateway::APIGatewayClient::updateMethod (const UpdateMethodRequest & request) slot
Updates an existing Method
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1898 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateMethodResponse *>(send(request));
 }
updateMethodResponse
UpdateMethodResponseResponse * QtAws::APIGateway::APIGatewayClient::updateMethodResponse (const UpdateMethodResponseRequest & request) slot
Updates an existing MethodResponse
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1912 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateMethodResponseResponse *>(send(request));
 }
updateModel
UpdateModelResponse * QtAws::APIGateway::APIGatewayClient::updateModel (const UpdateModelRequest & request) slot
Changes information about a
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1926 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateModelResponse *>(send(request));
 }
updateRequestValidator
UpdateRequestValidatorResponse * QtAws::APIGateway::APIGatewayClient::updateRequestValidator (const UpdateRequestValidatorRequest & request) slot
Updates a RequestValidator of a given
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1940 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRequestValidatorResponse *>(send(request));
 }
updateResource
UpdateResourceResponse * QtAws::APIGateway::APIGatewayClient::updateResource (const UpdateResourceRequest & request) slot
Changes information about a Resource
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1954 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateResourceResponse *>(send(request));
 }
updateRestApi
UpdateRestApiResponse * QtAws::APIGateway::APIGatewayClient::updateRestApi (const UpdateRestApiRequest & request) slot
Changes information about the specified
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1968 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRestApiResponse *>(send(request));
 }
updateStage
UpdateStageResponse * QtAws::APIGateway::APIGatewayClient::updateStage (const UpdateStageRequest & request) slot
Changes information about a Stage
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1982 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStageResponse *>(send(request));
 }
updateUsage
UpdateUsageResponse * QtAws::APIGateway::APIGatewayClient::updateUsage (const UpdateUsageRequest & request) slot
Grants a temporary extension to the remaining quota of a usage plan associated with a specified API
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1996 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUsageResponse *>(send(request));
 }
updateUsagePlan
UpdateUsagePlanResponse * QtAws::APIGateway::APIGatewayClient::updateUsagePlan (const UpdateUsagePlanRequest & request) slot
Updates a usage plan of a given plan
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2010 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUsagePlanResponse *>(send(request));
 }
updateVpcLink
UpdateVpcLinkResponse * QtAws::APIGateway::APIGatewayClient::updateVpcLink (const UpdateVpcLinkRequest & request) slot
Updates an existing VpcLink of a specified
Parameters
request Request to send to Amazon API Gateway.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2024 of file apigatewayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateVpcLinkResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
apigateway/apigatewayclient.h
apigateway/apigatewayclient.cpp