AWS SDK for Qt: QtAws::CloudSearchDomain::CloudSearchDomainClient Class Reference
QtAws::CloudSearchDomain::CloudSearchDomainClient Class Reference
Client for Amazon CloudSearch Domain.
Public Slots
SearchResponse * search (const SearchRequest &request)
SuggestResponse * suggest (const SuggestRequest &request)
UploadDocumentsResponse * uploadDocuments (const UploadDocumentsRequest &request)
Public Member Functions
CloudSearchDomainClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchDomainClient object.
CloudSearchDomainClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchDomainClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudSearch Domain.
You use the AmazonCloudSearch2013 API to upload documents to a search domain and search those documents.
</p
The endpoints for submitting UploadDocuments, Search, and Suggest requests are domain-specific. To get the endpoints for your domain, use the Amazon CloudSearch configuration service DescribeDomains action. The domain endpoints are also displayed on the domain dashboard in the Amazon CloudSearch console. You submit suggest requests to the search endpoint.
</p
For more information, see the Amazon CloudSearch Developer
Definition at line 38 of file cloudsearchdomainclient.h.
Constructor & Destructor Documentation
CloudSearchDomainClient() [1/2]
QtAws::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchDomainClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 65 of file cloudsearchdomainclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudSearchDomainClientPrivate(this), parent)
 {
     Q_D(CloudSearchDomainClient);
     d->apiVersion = QStringLiteral("2013-01-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudsearchdomain");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudSearch Domain");
     d->serviceName = QStringLiteral("cloudsearch");
 }
CloudSearchDomainClient() [2/2]
QtAws::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchDomainClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 98 of file cloudsearchdomainclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudSearchDomainClientPrivate(this), parent)
 {
     Q_D(CloudSearchDomainClient);
     d->apiVersion = QStringLiteral("2013-01-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudsearchdomain");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudSearch Domain");
     d->serviceName = QStringLiteral("cloudsearch");
 }
Member Function Documentation
search
SearchResponse * QtAws::CloudSearchDomain::CloudSearchDomainClient::search (const SearchRequest & request) slot
Retrieves a list of documents that match the specified search criteria. How you specify the search criteria depends on which query parser you use. Amazon CloudSearch supports four query
parsers>
simple: search all text and text-array fields for the specified string. Search for phrases, individual terms, and prefixes.
structured: search specific fields, construct compound queries using Boolean operators, and use advanced features such as term boosting and proximity searching.
lucene: specify search criteria using the Apache Lucene query parser syntax.
dismax: specify search criteria using the simplified subset of the Apache Lucene query parser syntax defined by the DisMax query parser.
For more information, see Searching Your Data in the Amazon CloudSearch Developer
Guide>
The endpoint for submitting Search requests is domain-specific. You submit search requests to a domain's search endpoint. To get the search endpoint for your domain, use the Amazon CloudSearch configuration service DescribeDomains action. A domain's endpoints are also displayed on the domain dashboard in the Amazon CloudSearch console.
Parameters
request Request to send to Amazon CloudSearch Domain.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 143 of file cloudsearchdomainclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchResponse *>(send(request));
 }
suggest
SuggestResponse * QtAws::CloudSearchDomain::CloudSearchDomainClient::suggest (const SuggestRequest & request) slot
Retrieves autocomplete suggestions for a partial query string. You can use suggestions enable you to display likely matches before users finish typing. In Amazon CloudSearch, suggestions are based on the contents of a particular text field. When you request suggestions, Amazon CloudSearch finds all of the documents whose values in the suggester field start with the specified query string. The beginning of the field must match the query string to be considered a match.
</p
For more information about configuring suggesters and retrieving suggestions, see Getting Suggestions in the Amazon CloudSearch Developer Guide.
</p
The endpoint for submitting Suggest requests is domain-specific. You submit suggest requests to a domain's search endpoint. To get the search endpoint for your domain, use the Amazon CloudSearch configuration service DescribeDomains action. A domain's endpoints are also displayed on the domain dashboard in the Amazon CloudSearch console.
Parameters
request Request to send to Amazon CloudSearch Domain.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file cloudsearchdomainclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SuggestResponse *>(send(request));
 }
uploadDocuments
UploadDocumentsResponse * QtAws::CloudSearchDomain::CloudSearchDomainClient::uploadDocuments (const UploadDocumentsRequest & request) slot
Posts a batch of documents to a search domain for indexing. A document batch is a collection of add and delete operations that represent the documents you want to add, update, or delete from your domain. Batches can be described in either JSON or XML. Each item that you want Amazon CloudSearch to return as a search result (such as a product) is represented as a document. Every document has a unique ID and one or more fields that contain the data that you want to search and return in results. Individual documents cannot contain more than 1 MB of data. The entire batch cannot exceed 5 MB. To get the best possible upload performance, group add and delete operations in batches that are close the 5 MB limit. Submitting a large volume of single-document batches can overload a domain's document service.
</p
The endpoint for submitting UploadDocuments requests is domain-specific. To get the document endpoint for your domain, use the Amazon CloudSearch configuration service DescribeDomains action. A domain's endpoints are also displayed on the domain dashboard in the Amazon CloudSearch console.
</p
For more information about formatting your data for Amazon CloudSearch, see Preparing Your Data in the Amazon CloudSearch Developer Guide. For more information about uploading data for indexing, see Uploading Data in the Amazon CloudSearch Developer Guide.
Parameters
request Request to send to Amazon CloudSearch Domain.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 207 of file cloudsearchdomainclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadDocumentsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudsearchdomain/cloudsearchdomainclient.h
cloudsearchdomain/cloudsearchdomainclient.cpp