AWS SDK for Qt: QtAws::RDS::RdsClient Class Reference
QtAws::RDS::RdsClient Class Reference
Client for Amazon Relational Database Service (RDS)
Public Slots
AddRoleToDBClusterResponse * addRoleToDBCluster (const AddRoleToDBClusterRequest &request)
AddSourceIdentifierToSubscriptionResponse * addSourceIdentifierToSubscription (const AddSourceIdentifierToSubscriptionRequest &request)
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
ApplyPendingMaintenanceActionResponse * applyPendingMaintenanceAction (const ApplyPendingMaintenanceActionRequest &request)
AuthorizeDBSecurityGroupIngressResponse * authorizeDBSecurityGroupIngress (const AuthorizeDBSecurityGroupIngressRequest &request)
CopyDBClusterParameterGroupResponse * copyDBClusterParameterGroup (const CopyDBClusterParameterGroupRequest &request)
CopyDBClusterSnapshotResponse * copyDBClusterSnapshot (const CopyDBClusterSnapshotRequest &request)
CopyDBParameterGroupResponse * copyDBParameterGroup (const CopyDBParameterGroupRequest &request)
CopyDBSnapshotResponse * copyDBSnapshot (const CopyDBSnapshotRequest &request)
CopyOptionGroupResponse * copyOptionGroup (const CopyOptionGroupRequest &request)
CreateDBClusterResponse * createDBCluster (const CreateDBClusterRequest &request)
CreateDBClusterParameterGroupResponse * createDBClusterParameterGroup (const CreateDBClusterParameterGroupRequest &request)
CreateDBClusterSnapshotResponse * createDBClusterSnapshot (const CreateDBClusterSnapshotRequest &request)
CreateDBInstanceResponse * createDBInstance (const CreateDBInstanceRequest &request)
CreateDBInstanceReadReplicaResponse * createDBInstanceReadReplica (const CreateDBInstanceReadReplicaRequest &request)
CreateDBParameterGroupResponse * createDBParameterGroup (const CreateDBParameterGroupRequest &request)
CreateDBSecurityGroupResponse * createDBSecurityGroup (const CreateDBSecurityGroupRequest &request)
CreateDBSnapshotResponse * createDBSnapshot (const CreateDBSnapshotRequest &request)
CreateDBSubnetGroupResponse * createDBSubnetGroup (const CreateDBSubnetGroupRequest &request)
CreateEventSubscriptionResponse * createEventSubscription (const CreateEventSubscriptionRequest &request)
CreateOptionGroupResponse * createOptionGroup (const CreateOptionGroupRequest &request)
DeleteDBClusterResponse * deleteDBCluster (const DeleteDBClusterRequest &request)
DeleteDBClusterParameterGroupResponse * deleteDBClusterParameterGroup (const DeleteDBClusterParameterGroupRequest &request)
DeleteDBClusterSnapshotResponse * deleteDBClusterSnapshot (const DeleteDBClusterSnapshotRequest &request)
DeleteDBInstanceResponse * deleteDBInstance (const DeleteDBInstanceRequest &request)
DeleteDBParameterGroupResponse * deleteDBParameterGroup (const DeleteDBParameterGroupRequest &request)
DeleteDBSecurityGroupResponse * deleteDBSecurityGroup (const DeleteDBSecurityGroupRequest &request)
DeleteDBSnapshotResponse * deleteDBSnapshot (const DeleteDBSnapshotRequest &request)
DeleteDBSubnetGroupResponse * deleteDBSubnetGroup (const DeleteDBSubnetGroupRequest &request)
DeleteEventSubscriptionResponse * deleteEventSubscription (const DeleteEventSubscriptionRequest &request)
DeleteOptionGroupResponse * deleteOptionGroup (const DeleteOptionGroupRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes (const DescribeAccountAttributesRequest &request)
DescribeCertificatesResponse * describeCertificates (const DescribeCertificatesRequest &request)
DescribeDBClusterParameterGroupsResponse * describeDBClusterParameterGroups (const DescribeDBClusterParameterGroupsRequest &request)
DescribeDBClusterParametersResponse * describeDBClusterParameters (const DescribeDBClusterParametersRequest &request)
DescribeDBClusterSnapshotAttributesResponse * describeDBClusterSnapshotAttributes (const DescribeDBClusterSnapshotAttributesRequest &request)
DescribeDBClusterSnapshotsResponse * describeDBClusterSnapshots (const DescribeDBClusterSnapshotsRequest &request)
DescribeDBClustersResponse * describeDBClusters (const DescribeDBClustersRequest &request)
DescribeDBEngineVersionsResponse * describeDBEngineVersions (const DescribeDBEngineVersionsRequest &request)
DescribeDBInstancesResponse * describeDBInstances (const DescribeDBInstancesRequest &request)
DescribeDBLogFilesResponse * describeDBLogFiles (const DescribeDBLogFilesRequest &request)
DescribeDBParameterGroupsResponse * describeDBParameterGroups (const DescribeDBParameterGroupsRequest &request)
DescribeDBParametersResponse * describeDBParameters (const DescribeDBParametersRequest &request)
DescribeDBSecurityGroupsResponse * describeDBSecurityGroups (const DescribeDBSecurityGroupsRequest &request)
DescribeDBSnapshotAttributesResponse * describeDBSnapshotAttributes (const DescribeDBSnapshotAttributesRequest &request)
DescribeDBSnapshotsResponse * describeDBSnapshots (const DescribeDBSnapshotsRequest &request)
DescribeDBSubnetGroupsResponse * describeDBSubnetGroups (const DescribeDBSubnetGroupsRequest &request)
DescribeEngineDefaultClusterParametersResponse * describeEngineDefaultClusterParameters (const DescribeEngineDefaultClusterParametersRequest &request)
DescribeEngineDefaultParametersResponse * describeEngineDefaultParameters (const DescribeEngineDefaultParametersRequest &request)
DescribeEventCategoriesResponse * describeEventCategories (const DescribeEventCategoriesRequest &request)
DescribeEventSubscriptionsResponse * describeEventSubscriptions (const DescribeEventSubscriptionsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeOptionGroupOptionsResponse * describeOptionGroupOptions (const DescribeOptionGroupOptionsRequest &request)
DescribeOptionGroupsResponse * describeOptionGroups (const DescribeOptionGroupsRequest &request)
DescribeOrderableDBInstanceOptionsResponse * describeOrderableDBInstanceOptions (const DescribeOrderableDBInstanceOptionsRequest &request)
DescribePendingMaintenanceActionsResponse * describePendingMaintenanceActions (const DescribePendingMaintenanceActionsRequest &request)
DescribeReservedDBInstancesResponse * describeReservedDBInstances (const DescribeReservedDBInstancesRequest &request)
DescribeReservedDBInstancesOfferingsResponse * describeReservedDBInstancesOfferings (const DescribeReservedDBInstancesOfferingsRequest &request)
DescribeSourceRegionsResponse * describeSourceRegions (const DescribeSourceRegionsRequest &request)
DescribeValidDBInstanceModificationsResponse * describeValidDBInstanceModifications (const DescribeValidDBInstanceModificationsRequest &request)
DownloadDBLogFilePortionResponse * downloadDBLogFilePortion (const DownloadDBLogFilePortionRequest &request)
FailoverDBClusterResponse * failoverDBCluster (const FailoverDBClusterRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyDBClusterResponse * modifyDBCluster (const ModifyDBClusterRequest &request)
ModifyDBClusterParameterGroupResponse * modifyDBClusterParameterGroup (const ModifyDBClusterParameterGroupRequest &request)
ModifyDBClusterSnapshotAttributeResponse * modifyDBClusterSnapshotAttribute (const ModifyDBClusterSnapshotAttributeRequest &request)
ModifyDBInstanceResponse * modifyDBInstance (const ModifyDBInstanceRequest &request)
ModifyDBParameterGroupResponse * modifyDBParameterGroup (const ModifyDBParameterGroupRequest &request)
ModifyDBSnapshotResponse * modifyDBSnapshot (const ModifyDBSnapshotRequest &request)
ModifyDBSnapshotAttributeResponse * modifyDBSnapshotAttribute (const ModifyDBSnapshotAttributeRequest &request)
ModifyDBSubnetGroupResponse * modifyDBSubnetGroup (const ModifyDBSubnetGroupRequest &request)
ModifyEventSubscriptionResponse * modifyEventSubscription (const ModifyEventSubscriptionRequest &request)
ModifyOptionGroupResponse * modifyOptionGroup (const ModifyOptionGroupRequest &request)
PromoteReadReplicaResponse * promoteReadReplica (const PromoteReadReplicaRequest &request)
PromoteReadReplicaDBClusterResponse * promoteReadReplicaDBCluster (const PromoteReadReplicaDBClusterRequest &request)
PurchaseReservedDBInstancesOfferingResponse * purchaseReservedDBInstancesOffering (const PurchaseReservedDBInstancesOfferingRequest &request)
RebootDBInstanceResponse * rebootDBInstance (const RebootDBInstanceRequest &request)
RemoveRoleFromDBClusterResponse * removeRoleFromDBCluster (const RemoveRoleFromDBClusterRequest &request)
RemoveSourceIdentifierFromSubscriptionResponse * removeSourceIdentifierFromSubscription (const RemoveSourceIdentifierFromSubscriptionRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
ResetDBClusterParameterGroupResponse * resetDBClusterParameterGroup (const ResetDBClusterParameterGroupRequest &request)
ResetDBParameterGroupResponse * resetDBParameterGroup (const ResetDBParameterGroupRequest &request)
RestoreDBClusterFromS3Response * restoreDBClusterFromS3 (const RestoreDBClusterFromS3Request &request)
RestoreDBClusterFromSnapshotResponse * restoreDBClusterFromSnapshot (const RestoreDBClusterFromSnapshotRequest &request)
RestoreDBClusterToPointInTimeResponse * restoreDBClusterToPointInTime (const RestoreDBClusterToPointInTimeRequest &request)
RestoreDBInstanceFromDBSnapshotResponse * restoreDBInstanceFromDBSnapshot (const RestoreDBInstanceFromDBSnapshotRequest &request)
RestoreDBInstanceFromS3Response * restoreDBInstanceFromS3 (const RestoreDBInstanceFromS3Request &request)
RestoreDBInstanceToPointInTimeResponse * restoreDBInstanceToPointInTime (const RestoreDBInstanceToPointInTimeRequest &request)
RevokeDBSecurityGroupIngressResponse * revokeDBSecurityGroupIngress (const RevokeDBSecurityGroupIngressRequest &request)
StartDBInstanceResponse * startDBInstance (const StartDBInstanceRequest &request)
StopDBInstanceResponse * stopDBInstance (const StopDBInstanceRequest &request)
Public Member Functions
RdsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RdsClient object.
RdsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RdsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Relational Database Service (RDS)
<fullname>Amazon Relational Database Service</fullname>
</p
Amazon Relational Database Service (Amazon RDS) is a web service that makes it easier to set up, operate, and scale a relational database in the cloud. It provides cost-efficient, resizable capacity for an industry-standard relational database and manages common database administration tasks, freeing up developers to focus on what makes their applications and businesses
unique>
Amazon RDS gives you access to the capabilities of a MySQL, MariaDB, PostgreSQL, Microsoft SQL Server, Oracle, or Amazon Aurora database server. These capabilities mean that the code, applications, and tools you already use today with your existing databases work with Amazon RDS without modification. Amazon RDS automatically backs up your database and maintains the database software that powers your DB instance. Amazon RDS is flexible: you can scale your DB instance's compute resources and storage capacity to meet your application's demand. As with all Amazon Web Services, there are no up-front investments, and you pay only for the resources you
use>
This interface reference for Amazon RDS contains documentation for a programming or command line interface you can use to manage Amazon RDS. Note that Amazon RDS is asynchronous, which means that some interfaces might require techniques such as polling or callback functions to determine when a command has been applied. In this reference, the parameter descriptions indicate whether a command is applied immediately, on the next instance reboot, or during the maintenance window. The reference structure is as follows, and we list following some related topics from the user
guide>
Amazon RDS API Reference
</p
For the alphabetical list of API actions, see API Actions>
For the alphabetical list of data types, see Data Types>
For a list of common query parameters, see Common Parameters>
For descriptions of the error codes, see Common Errors>
Amazon RDS User Guide
</p
For a summary of the Amazon RDS interfaces, see Available RDS Interfaces>
For more information about how to use the Query API, see Using the Query
Definition at line 214 of file rdsclient.h.
Constructor & Destructor Documentation
RdsClient() [1/2]
QtAws::RDS::RdsClient::RdsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RdsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 292 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new RdsClientPrivate(this), parent)
 {
     Q_D(RdsClient);
     d->apiVersion = QStringLiteral("2014-10-31");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("rds");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Relational Database Service");
     d->serviceName = QStringLiteral("rds");
 }
RdsClient() [2/2]
QtAws::RDS::RdsClient::RdsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RdsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 325 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new RdsClientPrivate(this), parent)
 {
     Q_D(RdsClient);
     d->apiVersion = QStringLiteral("2014-10-31");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("rds");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Relational Database Service");
     d->serviceName = QStringLiteral("rds");
 }
Member Function Documentation
addRoleToDBCluster
AddRoleToDBClusterResponse * QtAws::RDS::RdsClient::addRoleToDBCluster (const AddRoleToDBClusterRequest & request) slot
Associates an Identity and Access Management (IAM) role from an Aurora DB cluster. For more information, see Authorizing Amazon Aurora to Access Other AWS Services On Your request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 353 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddRoleToDBClusterResponse *>(send(request));
 }
addSourceIdentifierToSubscription
AddSourceIdentifierToSubscriptionResponse * QtAws::RDS::RdsClient::addSourceIdentifierToSubscription (const AddSourceIdentifierToSubscriptionRequest & request) slot
Adds a source identifier to an existing RDS event notification
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 367 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddSourceIdentifierToSubscriptionResponse *>(send(request));
 }
addTagsToResource
AddTagsToResourceResponse * QtAws::RDS::RdsClient::addTagsToResource (const AddTagsToResourceRequest & request) slot
Adds metadata tags to an Amazon RDS resource. These tags can also be used with cost allocation reporting to track cost associated with Amazon RDS resources, or used in a Condition statement in an IAM policy for Amazon
RDS>
For an overview on tagging Amazon RDS resources, see Tagging Amazon RDS request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 387 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsToResourceResponse *>(send(request));
 }
applyPendingMaintenanceAction
ApplyPendingMaintenanceActionResponse * QtAws::RDS::RdsClient::applyPendingMaintenanceAction (const ApplyPendingMaintenanceActionRequest & request) slot
Applies a pending maintenance action to a resource (for example, to a DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 401 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ApplyPendingMaintenanceActionResponse *>(send(request));
 }
authorizeDBSecurityGroupIngress
AuthorizeDBSecurityGroupIngressResponse * QtAws::RDS::RdsClient::authorizeDBSecurityGroupIngress (const AuthorizeDBSecurityGroupIngressRequest & request) slot
Enables ingress to a DBSecurityGroup using one of two forms of authorization. First, EC2 or VPC security groups can be added to the DBSecurityGroup if the application using the database is running on EC2 or VPC instances. Second, IP ranges are available if the application accessing your database is running on the Internet. Required parameters for this API are one of CIDR range, EC2SecurityGroupId for VPC, or (EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId for
non-VPC)> <note>
You can't authorize ingress from an EC2 security group in one AWS Region to an Amazon RDS DB instance in another. You can't authorize ingress from a VPC security group in one VPC to an Amazon RDS DB instance in
another> </note>
For an overview of CIDR ranges, go to the Wikipedia Tutorial.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 429 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AuthorizeDBSecurityGroupIngressResponse *>(send(request));
 }
copyDBClusterParameterGroup
CopyDBClusterParameterGroupResponse * QtAws::RDS::RdsClient::copyDBClusterParameterGroup (const CopyDBClusterParameterGroupRequest & request) slot
Copies the specified DB cluster parameter
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 443 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyDBClusterParameterGroupResponse *>(send(request));
 }
copyDBClusterSnapshot
CopyDBClusterSnapshotResponse * QtAws::RDS::RdsClient::copyDBClusterSnapshot (const CopyDBClusterSnapshotRequest & request) slot
Copies a snapshot of a DB
cluster>
To copy a DB cluster snapshot from a shared manual DB cluster snapshot, SourceDBClusterSnapshotIdentifier must be the Amazon Resource Name (ARN) of the shared DB cluster
snapshot>
You can copy an encrypted DB cluster snapshot from another AWS Region. In that case, the AWS Region where you call the CopyDBClusterSnapshot action is the destination AWS Region for the encrypted DB cluster snapshot to be copied to. To copy an encrypted DB cluster snapshot from another AWS Region, you must provide the following
values>
KmsKeyId - The AWS Key Management System (AWS KMS) key identifier for the key to use to encrypt the copy of the DB cluster snapshot in the destination AWS
Region>
PreSignedUrl - A URL that contains a Signature Version 4 signed request for the CopyDBClusterSnapshot action to be called in the source AWS Region where the DB cluster snapshot is copied from. The pre-signed URL must be a valid request for the CopyDBClusterSnapshot API action that can be executed in the source AWS Region that contains the encrypted DB cluster snapshot to be
copied>
The pre-signed URL request must contain the following parameter
values>
KmsKeyId - The KMS key identifier for the key to use to encrypt the copy of the DB cluster snapshot in the destination AWS Region. This is the same identifier for both the CopyDBClusterSnapshot action that is called in the destination AWS Region, and the action contained in the pre-signed
URL>
DestinationRegion - The name of the AWS Region that the DB cluster snapshot will be created
in>
SourceDBClusterSnapshotIdentifier - The DB cluster snapshot identifier for the encrypted DB cluster snapshot to be copied. This identifier must be in the Amazon Resource Name (ARN) format for the source AWS Region. For example, if you are copying an encrypted DB cluster snapshot from the us-west-2 AWS Region, then your SourceDBClusterSnapshotIdentifier looks like the following example:
arn:aws:rds:us-west-2:123456789012:cluster-snapshot:aurora-cluster1-snapshot-20161115>
To learn how to generate a Signature Version 4 signed request, see Authenticating Requests: Using Query Parameters (AWS Signature Version 4) and Signature Version 4 Signing Process>
TargetDBClusterSnapshotIdentifier - The identifier for the new copy of the DB cluster snapshot in the destination AWS
Region>
SourceDBClusterSnapshotIdentifier - The DB cluster snapshot identifier for the encrypted DB cluster snapshot to be copied. This identifier must be in the ARN format for the source AWS Region and is the same value as the SourceDBClusterSnapshotIdentifier in the pre-signed URL.
</p
To cancel the copy operation once it is in progress, delete the target DB cluster snapshot identified by TargetDBClusterSnapshotIdentifier while that DB cluster snapshot is in "copying"
status>
For more information on copying encrypted DB cluster snapshots from one AWS Region to another, see Copying a DB Cluster Snapshot in the Same Account, Either in the Same Region or Across Regions in the Amazon RDS User
Guide>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 537 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyDBClusterSnapshotResponse *>(send(request));
 }
copyDBParameterGroup
CopyDBParameterGroupResponse * QtAws::RDS::RdsClient::copyDBParameterGroup (const CopyDBParameterGroupRequest & request) slot
Copies the specified DB parameter
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 551 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyDBParameterGroupResponse *>(send(request));
 }
copyDBSnapshot
CopyDBSnapshotResponse * QtAws::RDS::RdsClient::copyDBSnapshot (const CopyDBSnapshotRequest & request) slot
Copies the specified DB snapshot. The source DB snapshot must be in the "available"
state>
You can copy a snapshot from one AWS Region to another. In that case, the AWS Region where you call the CopyDBSnapshot action is the destination AWS Region for the DB snapshot copy.
</p
For more information about copying snapshots, see Copying a DB Snapshot in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 576 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyDBSnapshotResponse *>(send(request));
 }
copyOptionGroup
CopyOptionGroupResponse * QtAws::RDS::RdsClient::copyOptionGroup (const CopyOptionGroupRequest & request) slot
Copies the specified option
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 590 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyOptionGroupResponse *>(send(request));
 }
createDBCluster
CreateDBClusterResponse * QtAws::RDS::RdsClient::createDBCluster (const CreateDBClusterRequest & request) slot
Creates a new Amazon Aurora DB
cluster>
You can use the ReplicationSourceIdentifier parameter to create the DB cluster as a Read Replica of another DB cluster or Amazon RDS MySQL DB instance. For cross-region replication where the DB cluster identified by ReplicationSourceIdentifier is encrypted, you must also specify the PreSignedUrl
parameter>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 616 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBClusterResponse *>(send(request));
 }
createDBClusterParameterGroup
CreateDBClusterParameterGroupResponse * QtAws::RDS::RdsClient::createDBClusterParameterGroup (const CreateDBClusterParameterGroupRequest & request) slot
Creates a new DB cluster parameter
group>
Parameters in a DB cluster parameter group apply to all of the instances in a DB
cluster>
A DB cluster parameter group is initially created with the default parameters for the database engine used by instances in the DB cluster. To provide custom values for any of the parameters, you must modify the group after creating it using ModifyDBClusterParameterGroup. Once you've created a DB cluster parameter group, you need to associate it with your DB cluster using ModifyDBCluster. When you associate a new DB cluster parameter group with a running DB cluster, you need to reboot the DB instances in the DB cluster without failover for the new DB cluster parameter group and associated settings to take effect.
</p
After you create a DB cluster parameter group, you should wait at least 5 minutes before creating your first DB cluster that uses that DB cluster parameter group as the default parameter group. This allows Amazon RDS to fully complete the create action before the DB cluster parameter group is used as the default for a new DB cluster. This is especially important for parameters that are critical when creating the default database for a DB cluster, such as the character set for the default database defined by the character_set_database parameter. You can use the Parameter Groups option of the Amazon RDS console or the DescribeDBClusterParameters command to verify that your DB cluster parameter group has been created or
modified>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 659 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBClusterParameterGroupResponse *>(send(request));
 }
createDBClusterSnapshot
CreateDBClusterSnapshotResponse * QtAws::RDS::RdsClient::createDBClusterSnapshot (const CreateDBClusterSnapshotRequest & request) slot
Creates a snapshot of a DB cluster. For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 675 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBClusterSnapshotResponse *>(send(request));
 }
createDBInstance
CreateDBInstanceResponse * QtAws::RDS::RdsClient::createDBInstance (const CreateDBInstanceRequest & request) slot
Creates a new DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 689 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBInstanceResponse *>(send(request));
 }
createDBInstanceReadReplica
CreateDBInstanceReadReplicaResponse * QtAws::RDS::RdsClient::createDBInstanceReadReplica (const CreateDBInstanceReadReplicaRequest & request) slot
Creates a new DB instance that acts as a Read Replica for an existing source DB instance. You can create a Read Replica for a DB instance running MySQL, MariaDB, or PostgreSQL. For more information, see Working with PostgreSQL, MySQL, and MariaDB Read Replicas.
</p
Amazon Aurora doesn't support this action. You must call the CreateDBInstance action to create a DB instance for an Aurora DB cluster.
</p
All Read Replica DB instances are created with backups disabled. All other DB instance attributes (including DB security groups and DB parameter groups) are inherited from the source DB instance, except as specified following.
</p
Your source DB instance must have backup retention enabled.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 720 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBInstanceReadReplicaResponse *>(send(request));
 }
createDBParameterGroup
CreateDBParameterGroupResponse * QtAws::RDS::RdsClient::createDBParameterGroup (const CreateDBParameterGroupRequest & request) slot
Creates a new DB parameter
group>
A DB parameter group is initially created with the default parameters for the database engine used by the DB instance. To provide custom values for any of the parameters, you must modify the group after creating it using ModifyDBParameterGroup. Once you've created a DB parameter group, you need to associate it with your DB instance using ModifyDBInstance. When you associate a new DB parameter group with a running DB instance, you need to reboot the DB instance without failover for the new DB parameter group and associated settings to take effect.
</p
After you create a DB parameter group, you should wait at least 5 minutes before creating your first DB instance that uses that DB parameter group as the default parameter group. This allows Amazon RDS to fully complete the create action before the parameter group is used as the default for a new DB instance. This is especially important for parameters that are critical when creating the default database for a DB instance, such as the character set for the default database defined by the character_set_database parameter. You can use the Parameter Groups option of the Amazon RDS console or the DescribeDBParameters command to verify that your DB parameter group has been created or
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 752 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBParameterGroupResponse *>(send(request));
 }
createDBSecurityGroup
CreateDBSecurityGroupResponse * QtAws::RDS::RdsClient::createDBSecurityGroup (const CreateDBSecurityGroupRequest & request) slot
Creates a new DB security group. DB security groups control access to a DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 766 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBSecurityGroupResponse *>(send(request));
 }
createDBSnapshot
CreateDBSnapshotResponse * QtAws::RDS::RdsClient::createDBSnapshot (const CreateDBSnapshotRequest & request) slot
Creates a DBSnapshot. The source DBInstance must be in "available"
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 780 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBSnapshotResponse *>(send(request));
 }
createDBSubnetGroup
CreateDBSubnetGroupResponse * QtAws::RDS::RdsClient::createDBSubnetGroup (const CreateDBSubnetGroupRequest & request) slot
Creates a new DB subnet group. DB subnet groups must contain at least one subnet in at least two AZs in the AWS
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 794 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDBSubnetGroupResponse *>(send(request));
 }
createEventSubscription
CreateEventSubscriptionResponse * QtAws::RDS::RdsClient::createEventSubscription (const CreateEventSubscriptionRequest & request) slot
Creates an RDS event notification subscription. This action requires a topic ARN (Amazon Resource Name) created by either the RDS console, the SNS console, or the SNS API. To obtain an ARN with SNS, you must create a topic in Amazon SNS and subscribe to the topic. The ARN is displayed in the SNS
console>
You can specify the type of source (SourceType) you want to be notified of, provide a list of RDS sources (SourceIds) that triggers the events, and provide a list of event categories (EventCategories) for events you want to be notified of. For example, you can specify SourceType = db-instance, SourceIds = mydbinstance1, mydbinstance2 and EventCategories = Availability,
Backup>
If you specify both the SourceType and SourceIds, such as SourceType = db-instance and SourceIdentifier = myDBInstance1, you are notified of all the db-instance events for the specified source. If you specify a SourceType but do not specify a SourceIdentifier, you receive notice of the events for that source type for all your RDS sources. If you do not specify either the SourceType nor the SourceIdentifier, you are notified of events generated from all RDS sources belonging to your customer
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 825 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEventSubscriptionResponse *>(send(request));
 }
createOptionGroup
CreateOptionGroupResponse * QtAws::RDS::RdsClient::createOptionGroup (const CreateOptionGroupRequest & request) slot
Creates a new option group. You can create up to 20 option
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 839 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateOptionGroupResponse *>(send(request));
 }
deleteDBCluster
DeleteDBClusterResponse * QtAws::RDS::RdsClient::deleteDBCluster (const DeleteDBClusterRequest & request) slot
The DeleteDBCluster action deletes a previously provisioned DB cluster. When you delete a DB cluster, all automated backups for that DB cluster are deleted and can't be recovered. Manual DB cluster snapshots of the specified DB cluster are not
deleted>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 861 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBClusterResponse *>(send(request));
 }
deleteDBClusterParameterGroup
DeleteDBClusterParameterGroupResponse * QtAws::RDS::RdsClient::deleteDBClusterParameterGroup (const DeleteDBClusterParameterGroupRequest & request) slot
Deletes a specified DB cluster parameter group. The DB cluster parameter group to be deleted can't be associated with any DB
clusters>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 882 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBClusterParameterGroupResponse *>(send(request));
 }
deleteDBClusterSnapshot
DeleteDBClusterSnapshotResponse * QtAws::RDS::RdsClient::deleteDBClusterSnapshot (const DeleteDBClusterSnapshotRequest & request) slot
Deletes a DB cluster snapshot. If the snapshot is being copied, the copy operation is
terminated> <note>
The DB cluster snapshot must be in the available state to be
deleted> </note>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 906 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBClusterSnapshotResponse *>(send(request));
 }
deleteDBInstance
DeleteDBInstanceResponse * QtAws::RDS::RdsClient::deleteDBInstance (const DeleteDBInstanceRequest & request) slot
The DeleteDBInstance action deletes a previously provisioned DB instance. When you delete a DB instance, all automated backups for that instance are deleted and can't be recovered. Manual DB snapshots of the DB instance to be deleted by DeleteDBInstance are not
deleted>
If you request a final DB snapshot the status of the Amazon RDS DB instance is deleting until the DB snapshot is created. The API action DescribeDBInstance is used to monitor the status of this operation. The action can't be canceled or reverted once submitted.
</p
Note that when a DB instance is in a failure state and has a status of failed, incompatible-restore, or incompatible-network, you can only delete it when the SkipFinalSnapshot parameter is set to
true>
If the specified DB instance is part of an Amazon Aurora DB cluster, you can't delete the DB instance if both of the following conditions are
true>
The DB cluster is a Read Replica of another Amazon Aurora DB
cluster>
The DB instance is the only instance in the DB
cluster>
To delete a DB instance in this case, first call the PromoteReadReplicaDBCluster API action to promote the DB cluster so it's no longer a Read Replica. After the promotion completes, then call the DeleteDBInstance API action to delete the final instance in the DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 953 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBInstanceResponse *>(send(request));
 }
deleteDBParameterGroup
DeleteDBParameterGroupResponse * QtAws::RDS::RdsClient::deleteDBParameterGroup (const DeleteDBParameterGroupRequest & request) slot
Deletes a specified DBParameterGroup. The DBParameterGroup to be deleted can't be associated with any DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 967 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBParameterGroupResponse *>(send(request));
 }
deleteDBSecurityGroup
DeleteDBSecurityGroupResponse * QtAws::RDS::RdsClient::deleteDBSecurityGroup (const DeleteDBSecurityGroupRequest & request) slot
Deletes a DB security
group> <note>
The specified DB security group must not be associated with any DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 985 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBSecurityGroupResponse *>(send(request));
 }
deleteDBSnapshot
DeleteDBSnapshotResponse * QtAws::RDS::RdsClient::deleteDBSnapshot (const DeleteDBSnapshotRequest & request) slot
Deletes a DBSnapshot. If the snapshot is being copied, the copy operation is
terminated> <note>
The DBSnapshot must be in the available state to be
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1003 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBSnapshotResponse *>(send(request));
 }
deleteDBSubnetGroup
DeleteDBSubnetGroupResponse * QtAws::RDS::RdsClient::deleteDBSubnetGroup (const DeleteDBSubnetGroupRequest & request) slot
Deletes a DB subnet
group> <note>
The specified database subnet group must not be associated with any DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1021 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDBSubnetGroupResponse *>(send(request));
 }
deleteEventSubscription
DeleteEventSubscriptionResponse * QtAws::RDS::RdsClient::deleteEventSubscription (const DeleteEventSubscriptionRequest & request) slot
Deletes an RDS event notification
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1035 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEventSubscriptionResponse *>(send(request));
 }
deleteOptionGroup
DeleteOptionGroupResponse * QtAws::RDS::RdsClient::deleteOptionGroup (const DeleteOptionGroupRequest & request) slot
Deletes an existing option
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1049 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteOptionGroupResponse *>(send(request));
 }
describeAccountAttributes
DescribeAccountAttributesResponse * QtAws::RDS::RdsClient::describeAccountAttributes (const DescribeAccountAttributesRequest & request) slot
Lists all of the attributes for a customer account. The attributes include Amazon RDS quotas for the account, such as the number of DB instances allowed. The description for a quota includes the quota name, current usage toward that quota, and the quota's maximum
value>
This command doesn't take any
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1069 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountAttributesResponse *>(send(request));
 }
describeCertificates
DescribeCertificatesResponse * QtAws::RDS::RdsClient::describeCertificates (const DescribeCertificatesRequest & request) slot
Lists the set of CA certificates provided by Amazon RDS for this AWS
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1083 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCertificatesResponse *>(send(request));
 }
describeDBClusterParameterGroups
DescribeDBClusterParameterGroupsResponse * QtAws::RDS::RdsClient::describeDBClusterParameterGroups (const DescribeDBClusterParameterGroupsRequest & request) slot
Returns a list of DBClusterParameterGroup descriptions. If a DBClusterParameterGroupName parameter is specified, the list will contain only the description of the specified DB cluster parameter group.
</p
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1104 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBClusterParameterGroupsResponse *>(send(request));
 }
describeDBClusterParameters
DescribeDBClusterParametersResponse * QtAws::RDS::RdsClient::describeDBClusterParameters (const DescribeDBClusterParametersRequest & request) slot
Returns the detailed parameter list for a particular DB cluster parameter
group>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1124 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBClusterParametersResponse *>(send(request));
 }
describeDBClusters
DescribeDBClustersResponse * QtAws::RDS::RdsClient::describeDBClusters (const DescribeDBClustersRequest & request) slot
Returns information about provisioned Aurora DB clusters. This API supports
pagination>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1190 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBClustersResponse *>(send(request));
 }
describeDBClusterSnapshotAttributes
DescribeDBClusterSnapshotAttributesResponse * QtAws::RDS::RdsClient::describeDBClusterSnapshotAttributes (const DescribeDBClusterSnapshotAttributesRequest & request) slot
Returns a list of DB cluster snapshot attribute names and values for a manual DB cluster
snapshot>
When sharing snapshots with other AWS accounts, DescribeDBClusterSnapshotAttributes returns the restore attribute and a list of IDs for the AWS accounts that are authorized to copy or restore the manual DB cluster snapshot. If all is included in the list of values for the restore attribute, then the manual DB cluster snapshot is public and can be copied or restored by all AWS
accounts>
To add or remove access for an AWS account to copy or restore a manual DB cluster snapshot, or to make the manual DB cluster snapshot public or private, use the ModifyDBClusterSnapshotAttribute API
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1150 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBClusterSnapshotAttributesResponse *>(send(request));
 }
describeDBClusterSnapshots
DescribeDBClusterSnapshotsResponse * QtAws::RDS::RdsClient::describeDBClusterSnapshots (const DescribeDBClusterSnapshotsRequest & request) slot
Returns information about DB cluster snapshots. This API action supports
pagination>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1170 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBClusterSnapshotsResponse *>(send(request));
 }
describeDBEngineVersions
DescribeDBEngineVersionsResponse * QtAws::RDS::RdsClient::describeDBEngineVersions (const DescribeDBEngineVersionsRequest & request) slot
Returns a list of the available DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1204 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBEngineVersionsResponse *>(send(request));
 }
describeDBInstances
DescribeDBInstancesResponse * QtAws::RDS::RdsClient::describeDBInstances (const DescribeDBInstancesRequest & request) slot
Returns information about provisioned RDS instances. This API supports
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1218 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBInstancesResponse *>(send(request));
 }
describeDBLogFiles
DescribeDBLogFilesResponse * QtAws::RDS::RdsClient::describeDBLogFiles (const DescribeDBLogFilesRequest & request) slot
Returns a list of DB log files for the DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1232 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBLogFilesResponse *>(send(request));
 }
describeDBParameterGroups
DescribeDBParameterGroupsResponse * QtAws::RDS::RdsClient::describeDBParameterGroups (const DescribeDBParameterGroupsRequest & request) slot
Returns a list of DBParameterGroup descriptions. If a DBParameterGroupName is specified, the list will contain only the description of the specified DB parameter group.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1247 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBParameterGroupsResponse *>(send(request));
 }
describeDBParameters
DescribeDBParametersResponse * QtAws::RDS::RdsClient::describeDBParameters (const DescribeDBParametersRequest & request) slot
Returns the detailed parameter list for a particular DB parameter
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1261 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBParametersResponse *>(send(request));
 }
describeDBSecurityGroups
DescribeDBSecurityGroupsResponse * QtAws::RDS::RdsClient::describeDBSecurityGroups (const DescribeDBSecurityGroupsRequest & request) slot
Returns a list of DBSecurityGroup descriptions. If a DBSecurityGroupName is specified, the list will contain only the descriptions of the specified DB security group.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1276 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBSecurityGroupsResponse *>(send(request));
 }
describeDBSnapshotAttributes
DescribeDBSnapshotAttributesResponse * QtAws::RDS::RdsClient::describeDBSnapshotAttributes (const DescribeDBSnapshotAttributesRequest & request) slot
Returns a list of DB snapshot attribute names and values for a manual DB
snapshot>
When sharing snapshots with other AWS accounts, DescribeDBSnapshotAttributes returns the restore attribute and a list of IDs for the AWS accounts that are authorized to copy or restore the manual DB snapshot. If all is included in the list of values for the restore attribute, then the manual DB snapshot is public and can be copied or restored by all AWS
accounts>
To add or remove access for an AWS account to copy or restore a manual DB snapshot, or to make the manual DB snapshot public or private, use the ModifyDBSnapshotAttribute API
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1302 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBSnapshotAttributesResponse *>(send(request));
 }
describeDBSnapshots
DescribeDBSnapshotsResponse * QtAws::RDS::RdsClient::describeDBSnapshots (const DescribeDBSnapshotsRequest & request) slot
Returns information about DB snapshots. This API action supports
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1316 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBSnapshotsResponse *>(send(request));
 }
describeDBSubnetGroups
DescribeDBSubnetGroupsResponse * QtAws::RDS::RdsClient::describeDBSubnetGroups (const DescribeDBSubnetGroupsRequest & request) slot
Returns a list of DBSubnetGroup descriptions. If a DBSubnetGroupName is specified, the list will contain only the descriptions of the specified
DBSubnetGroup>
For an overview of CIDR ranges, go to the Wikipedia Tutorial.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1336 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDBSubnetGroupsResponse *>(send(request));
 }
describeEngineDefaultClusterParameters
DescribeEngineDefaultClusterParametersResponse * QtAws::RDS::RdsClient::describeEngineDefaultClusterParameters (const DescribeEngineDefaultClusterParametersRequest & request) slot
Returns the default engine and system parameter information for the cluster database
engine>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1356 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEngineDefaultClusterParametersResponse *>(send(request));
 }
describeEngineDefaultParameters
DescribeEngineDefaultParametersResponse * QtAws::RDS::RdsClient::describeEngineDefaultParameters (const DescribeEngineDefaultParametersRequest & request) slot
Returns the default engine and system parameter information for the specified database
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1370 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEngineDefaultParametersResponse *>(send(request));
 }
describeEventCategories
DescribeEventCategoriesResponse * QtAws::RDS::RdsClient::describeEventCategories (const DescribeEventCategoriesRequest & request) slot
Displays a list of categories for all event source types, or, if specified, for a specified source type. You can see a list of the event categories and source types in the Events topic in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1387 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventCategoriesResponse *>(send(request));
 }
describeEvents
DescribeEventsResponse * QtAws::RDS::RdsClient::describeEvents (const DescribeEventsRequest & request) slot
Returns events related to DB instances, DB security groups, DB snapshots, and DB parameter groups for the past 14 days. Events specific to a particular DB instance, DB security group, database snapshot, or DB parameter group can be obtained by providing the name as a parameter. By default, the past hour of events are
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1422 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventsResponse *>(send(request));
 }
describeEventSubscriptions
DescribeEventSubscriptionsResponse * QtAws::RDS::RdsClient::describeEventSubscriptions (const DescribeEventSubscriptionsRequest & request) slot
Lists all the subscription descriptions for a customer account. The description for a subscription includes SubscriptionName, SNSTopicARN, CustomerID, SourceType, SourceID, CreationTime, and
Status>
If you specify a SubscriptionName, lists the description for that
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1406 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventSubscriptionsResponse *>(send(request));
 }
describeOptionGroupOptions
DescribeOptionGroupOptionsResponse * QtAws::RDS::RdsClient::describeOptionGroupOptions (const DescribeOptionGroupOptionsRequest & request) slot
Describes all available
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1436 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOptionGroupOptionsResponse *>(send(request));
 }
describeOptionGroups
DescribeOptionGroupsResponse * QtAws::RDS::RdsClient::describeOptionGroups (const DescribeOptionGroupsRequest & request) slot
Describes the available option
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1450 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOptionGroupsResponse *>(send(request));
 }
describeOrderableDBInstanceOptions
DescribeOrderableDBInstanceOptionsResponse * QtAws::RDS::RdsClient::describeOrderableDBInstanceOptions (const DescribeOrderableDBInstanceOptionsRequest & request) slot
Returns a list of orderable DB instance options for the specified
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1464 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOrderableDBInstanceOptionsResponse *>(send(request));
 }
describePendingMaintenanceActions
DescribePendingMaintenanceActionsResponse * QtAws::RDS::RdsClient::describePendingMaintenanceActions (const DescribePendingMaintenanceActionsRequest & request) slot
Returns a list of resources (for example, DB instances) that have at least one pending maintenance
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1478 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePendingMaintenanceActionsResponse *>(send(request));
 }
describeReservedDBInstances
DescribeReservedDBInstancesResponse * QtAws::RDS::RdsClient::describeReservedDBInstances (const DescribeReservedDBInstancesRequest & request) slot
Returns information about reserved DB instances for this account, or about a specified reserved DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1492 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedDBInstancesResponse *>(send(request));
 }
describeReservedDBInstancesOfferings
DescribeReservedDBInstancesOfferingsResponse * QtAws::RDS::RdsClient::describeReservedDBInstancesOfferings (const DescribeReservedDBInstancesOfferingsRequest & request) slot
Lists available reserved DB instance
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1506 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedDBInstancesOfferingsResponse *>(send(request));
 }
describeSourceRegions
DescribeSourceRegionsResponse * QtAws::RDS::RdsClient::describeSourceRegions (const DescribeSourceRegionsRequest & request) slot
Returns a list of the source AWS Regions where the current AWS Region can create a Read Replica or copy a DB snapshot from. This API action supports
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1521 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSourceRegionsResponse *>(send(request));
 }
describeValidDBInstanceModifications
DescribeValidDBInstanceModificationsResponse * QtAws::RDS::RdsClient::describeValidDBInstanceModifications (const DescribeValidDBInstanceModificationsRequest & request) slot
You can call DescribeValidDBInstanceModifications to learn what modifications you can make to your DB instance. You can use this information when you call ModifyDBInstance.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1536 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeValidDBInstanceModificationsResponse *>(send(request));
 }
downloadDBLogFilePortion
DownloadDBLogFilePortionResponse * QtAws::RDS::RdsClient::downloadDBLogFilePortion (const DownloadDBLogFilePortionRequest & request) slot
Downloads all or a portion of the specified log file, up to 1 MB in
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1550 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DownloadDBLogFilePortionResponse *>(send(request));
 }
failoverDBCluster
FailoverDBClusterResponse * QtAws::RDS::RdsClient::failoverDBCluster (const FailoverDBClusterRequest & request) slot
Forces a failover for a DB
cluster>
A failover for a DB cluster promotes one of the Aurora Replicas (read-only instances) in the DB cluster to be the primary instance (the cluster
writer)>
Amazon Aurora will automatically fail over to an Aurora Replica, if one exists, when the primary instance fails. You can force a failover when you want to simulate a failure of a primary instance for testing. Because each instance in a DB cluster has its own endpoint address, you will need to clean up and re-establish any existing connections that use those endpoint addresses when the failover is
complete>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1582 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<FailoverDBClusterResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::RDS::RdsClient::listTagsForResource (const ListTagsForResourceRequest & request) slot
Lists all tags on an Amazon RDS
resource>
For an overview on tagging an Amazon RDS resource, see Tagging Amazon RDS request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1601 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
modifyDBCluster
ModifyDBClusterResponse * QtAws::RDS::RdsClient::modifyDBCluster (const ModifyDBClusterRequest & request) slot
Modify a setting for an Amazon Aurora DB cluster. You can change one or more database configuration parameters by specifying these parameters and the new values in the request. For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1618 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBClusterResponse *>(send(request));
 }
modifyDBClusterParameterGroup
ModifyDBClusterParameterGroupResponse * QtAws::RDS::RdsClient::modifyDBClusterParameterGroup (const ModifyDBClusterParameterGroupRequest & request) slot
Modifies the parameters of a DB cluster parameter group. To modify more than one parameter, submit a list of the following: ParameterName, ParameterValue, and ApplyMethod. A maximum of 20 parameters can be modified in a single request.
</p
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
</p <note>
Changes to dynamic parameters are applied immediately. Changes to static parameters require a reboot without failover to the DB cluster associated with the parameter group before the change can take
effect> </note>
After you create a DB cluster parameter group, you should wait at least 5 minutes before creating your first DB cluster that uses that DB cluster parameter group as the default parameter group. This allows Amazon RDS to fully complete the create action before the parameter group is used as the default for a new DB cluster. This is especially important for parameters that are critical when creating the default database for a DB cluster, such as the character set for the default database defined by the character_set_database parameter. You can use the Parameter Groups option of the Amazon RDS console or the DescribeDBClusterParameters command to verify that your DB cluster parameter group has been created or
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1655 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBClusterParameterGroupResponse *>(send(request));
 }
modifyDBClusterSnapshotAttribute
ModifyDBClusterSnapshotAttributeResponse * QtAws::RDS::RdsClient::modifyDBClusterSnapshotAttribute (const ModifyDBClusterSnapshotAttributeRequest & request) slot
Adds an attribute and values to, or removes an attribute and values from, a manual DB cluster
snapshot>
To share a manual DB cluster snapshot with other AWS accounts, specify restore as the AttributeName and use the ValuesToAdd parameter to add a list of IDs of the AWS accounts that are authorized to restore the manual DB cluster snapshot. Use the value all to make the manual DB cluster snapshot public, which means that it can be copied or restored by all AWS accounts. Do not add the all value for any manual DB cluster snapshots that contain private information that you don't want available to all AWS accounts. If a manual DB cluster snapshot is encrypted, it can be shared, but only by specifying a list of authorized AWS account IDs for the ValuesToAdd parameter. You can't use all as a value for that parameter in this
case>
To view which AWS accounts have access to copy or restore a manual DB cluster snapshot, or whether a manual DB cluster snapshot public or private, use the DescribeDBClusterSnapshotAttributes API
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1685 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBClusterSnapshotAttributeResponse *>(send(request));
 }
modifyDBInstance
ModifyDBInstanceResponse * QtAws::RDS::RdsClient::modifyDBInstance (const ModifyDBInstanceRequest & request) slot
Modifies settings for a DB instance. You can change one or more database configuration parameters by specifying these parameters and the new values in the request. To learn what modifications you can make to your DB instance, call DescribeValidDBInstanceModifications before you call ModifyDBInstance.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1701 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBInstanceResponse *>(send(request));
 }
modifyDBParameterGroup
ModifyDBParameterGroupResponse * QtAws::RDS::RdsClient::modifyDBParameterGroup (const ModifyDBParameterGroupRequest & request) slot
Modifies the parameters of a DB parameter group. To modify more than one parameter, submit a list of the following: ParameterName, ParameterValue, and ApplyMethod. A maximum of 20 parameters can be modified in a single request.
</p <note>
Changes to dynamic parameters are applied immediately. Changes to static parameters require a reboot without failover to the DB instance associated with the parameter group before the change can take
effect> </note>
After you modify a DB parameter group, you should wait at least 5 minutes before creating your first DB instance that uses that DB parameter group as the default parameter group. This allows Amazon RDS to fully complete the modify action before the parameter group is used as the default for a new DB instance. This is especially important for parameters that are critical when creating the default database for a DB instance, such as the character set for the default database defined by the character_set_database parameter. You can use the Parameter Groups option of the Amazon RDS console or the DescribeDBParameters command to verify that your DB parameter group has been created or
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1732 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBParameterGroupResponse *>(send(request));
 }
modifyDBSnapshot
ModifyDBSnapshotResponse * QtAws::RDS::RdsClient::modifyDBSnapshot (const ModifyDBSnapshotRequest & request) slot
Updates a manual DB snapshot, which can be encrypted or not encrypted, with a new engine version.
</p
Amazon RDS supports upgrading DB snapshots for MySQL and Oracle.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1750 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBSnapshotResponse *>(send(request));
 }
modifyDBSnapshotAttribute
ModifyDBSnapshotAttributeResponse * QtAws::RDS::RdsClient::modifyDBSnapshotAttribute (const ModifyDBSnapshotAttributeRequest & request) slot
Adds an attribute and values to, or removes an attribute and values from, a manual DB
snapshot>
To share a manual DB snapshot with other AWS accounts, specify restore as the AttributeName and use the ValuesToAdd parameter to add a list of IDs of the AWS accounts that are authorized to restore the manual DB snapshot. Uses the value all to make the manual DB snapshot public, which means it can be copied or restored by all AWS accounts. Do not add the all value for any manual DB snapshots that contain private information that you don't want available to all AWS accounts. If the manual DB snapshot is encrypted, it can be shared, but only by specifying a list of authorized AWS account IDs for the ValuesToAdd parameter. You can't use all as a value for that parameter in this
case>
To view which AWS accounts have access to copy or restore a manual DB snapshot, or whether a manual DB snapshot public or private, use the DescribeDBSnapshotAttributes API
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1779 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBSnapshotAttributeResponse *>(send(request));
 }
modifyDBSubnetGroup
ModifyDBSubnetGroupResponse * QtAws::RDS::RdsClient::modifyDBSubnetGroup (const ModifyDBSubnetGroupRequest & request) slot
Modifies an existing DB subnet group. DB subnet groups must contain at least one subnet in at least two AZs in the AWS
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1793 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyDBSubnetGroupResponse *>(send(request));
 }
modifyEventSubscription
ModifyEventSubscriptionResponse * QtAws::RDS::RdsClient::modifyEventSubscription (const ModifyEventSubscriptionRequest & request) slot
Modifies an existing RDS event notification subscription. Note that you can't modify the source identifiers using this call; to change source identifiers for a subscription, use the AddSourceIdentifierToSubscription and RemoveSourceIdentifierFromSubscription
calls>
You can see a list of the event categories for a given SourceType in the Events topic in the Amazon RDS User Guide or by using the DescribeEventCategories
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1815 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyEventSubscriptionResponse *>(send(request));
 }
modifyOptionGroup
ModifyOptionGroupResponse * QtAws::RDS::RdsClient::modifyOptionGroup (const ModifyOptionGroupRequest & request) slot
Modifies an existing option
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1829 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyOptionGroupResponse *>(send(request));
 }
promoteReadReplica
PromoteReadReplicaResponse * QtAws::RDS::RdsClient::promoteReadReplica (const PromoteReadReplicaRequest & request) slot
Promotes a Read Replica DB instance to a standalone DB
instance> <note>
Backup duration is a function of the amount of changes to the database since the previous backup. If you plan to promote a Read Replica to a standalone instance, we recommend that you enable backups and complete at least one backup prior to promotion. In addition, a Read Replica cannot be promoted to a standalone instance when it is in the backing-up status. If you have enabled backups on your Read Replica, configure the automated backup window so that daily backups do not interfere with Read Replica
promotion>
This command doesn't apply to Aurora MySQL and Aurora
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1855 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PromoteReadReplicaResponse *>(send(request));
 }
promoteReadReplicaDBCluster
PromoteReadReplicaDBClusterResponse * QtAws::RDS::RdsClient::promoteReadReplicaDBCluster (const PromoteReadReplicaDBClusterRequest & request) slot
Promotes a Read Replica DB cluster to a standalone DB
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1869 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PromoteReadReplicaDBClusterResponse *>(send(request));
 }
purchaseReservedDBInstancesOffering
PurchaseReservedDBInstancesOfferingResponse * QtAws::RDS::RdsClient::purchaseReservedDBInstancesOffering (const PurchaseReservedDBInstancesOfferingRequest & request) slot
Purchases a reserved DB instance
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1883 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurchaseReservedDBInstancesOfferingResponse *>(send(request));
 }
rebootDBInstance
RebootDBInstanceResponse * QtAws::RDS::RdsClient::rebootDBInstance (const RebootDBInstanceRequest & request) slot
You might need to reboot your DB instance, usually for maintenance reasons. For example, if you make certain modifications, or if you change the DB parameter group associated with the DB instance, you must reboot the instance for the changes to take effect.
</p
Rebooting a DB instance restarts the database engine service. Rebooting a DB instance results in a momentary outage, during which the DB instance status is set to rebooting.
</p
For more information about rebooting, see Rebooting a DB Instance.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1909 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootDBInstanceResponse *>(send(request));
 }
removeRoleFromDBCluster
RemoveRoleFromDBClusterResponse * QtAws::RDS::RdsClient::removeRoleFromDBCluster (const RemoveRoleFromDBClusterRequest & request) slot
Disassociates an Identity and Access Management (IAM) role from an Aurora DB cluster. For more information, see Authorizing Amazon Aurora to Access Other AWS Services On Your request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1925 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveRoleFromDBClusterResponse *>(send(request));
 }
removeSourceIdentifierFromSubscription
RemoveSourceIdentifierFromSubscriptionResponse * QtAws::RDS::RdsClient::removeSourceIdentifierFromSubscription (const RemoveSourceIdentifierFromSubscriptionRequest & request) slot
Removes a source identifier from an existing RDS event notification
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1939 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveSourceIdentifierFromSubscriptionResponse *>(send(request));
 }
removeTagsFromResource
RemoveTagsFromResourceResponse * QtAws::RDS::RdsClient::removeTagsFromResource (const RemoveTagsFromResourceRequest & request) slot
Removes metadata tags from an Amazon RDS
resource>
For an overview on tagging an Amazon RDS resource, see Tagging Amazon RDS request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1958 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsFromResourceResponse *>(send(request));
 }
resetDBClusterParameterGroup
ResetDBClusterParameterGroupResponse * QtAws::RDS::RdsClient::resetDBClusterParameterGroup (const ResetDBClusterParameterGroupRequest & request) slot
Modifies the parameters of a DB cluster parameter group to the default value. To reset specific parameters submit a list of the following: ParameterName and ApplyMethod. To reset the entire DB cluster parameter group, specify the DBClusterParameterGroupName and ResetAllParameters parameters.
</p
When resetting the entire group, dynamic parameters are updated immediately and static parameters are set to pending-reboot to take effect on the next DB instance restart or RebootDBInstance request. You must call RebootDBInstance for every DB instance in your DB cluster that you want the updated static parameter to apply
to>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1987 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetDBClusterParameterGroupResponse *>(send(request));
 }
resetDBParameterGroup
ResetDBParameterGroupResponse * QtAws::RDS::RdsClient::resetDBParameterGroup (const ResetDBParameterGroupRequest & request) slot
Modifies the parameters of a DB parameter group to the engine/system default value. To reset specific parameters, provide a list of the following: ParameterName and ApplyMethod. To reset the entire DB parameter group, specify the DBParameterGroup name and ResetAllParameters parameters. When resetting the entire group, dynamic parameters are updated immediately and static parameters are set to pending-reboot to take effect on the next DB instance restart or RebootDBInstance request.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2005 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetDBParameterGroupResponse *>(send(request));
 }
restoreDBClusterFromS3
RestoreDBClusterFromS3Response * QtAws::RDS::RdsClient::restoreDBClusterFromS3 (const RestoreDBClusterFromS3Request & request) slot
Creates an Amazon Aurora DB cluster from data stored in an Amazon S3 bucket. Amazon RDS must be authorized to access the Amazon S3 bucket and the data must be created using the Percona XtraBackup utility as described in Migrating Data from MySQL by Using an Amazon S3 request Request to send to Amazon Relational Database Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2022 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBClusterFromS3Response *>(send(request));
 }
restoreDBClusterFromSnapshot
RestoreDBClusterFromSnapshotResponse * QtAws::RDS::RdsClient::restoreDBClusterFromSnapshot (const RestoreDBClusterFromSnapshotRequest & request) slot
Creates a new DB cluster from a DB snapshot or DB cluster
snapshot>
If a DB snapshot is specified, the target DB cluster is created from the source DB snapshot with a default configuration and default security
group>
If a DB cluster snapshot is specified, the target DB cluster is created from the source DB cluster restore point with the same configuration as the original source DB cluster, except that the new DB cluster is created with the default security
group>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2053 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBClusterFromSnapshotResponse *>(send(request));
 }
restoreDBClusterToPointInTime
RestoreDBClusterToPointInTimeResponse * QtAws::RDS::RdsClient::restoreDBClusterToPointInTime (const RestoreDBClusterToPointInTimeRequest & request) slot
Restores a DB cluster to an arbitrary point in time. Users can restore to any point in time before LatestRestorableTime for up to BackupRetentionPeriod days. The target DB cluster is created from the source DB cluster with the same configuration as the original DB cluster, except that the new DB cluster is created with the default DB security group.
</p <note>
This action only restores the DB cluster, not the DB instances for that DB cluster. You must invoke the CreateDBInstance action to create DB instances for the restored DB cluster, specifying the identifier of the restored DB cluster in DBClusterIdentifier. You can create DB instances only after the RestoreDBClusterToPointInTime action has completed and the DB cluster is
available> </note>
For more information on Amazon Aurora, see Aurora on Amazon RDS in the Amazon RDS User Guide.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2083 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBClusterToPointInTimeResponse *>(send(request));
 }
restoreDBInstanceFromDBSnapshot
RestoreDBInstanceFromDBSnapshotResponse * QtAws::RDS::RdsClient::restoreDBInstanceFromDBSnapshot (const RestoreDBInstanceFromDBSnapshotRequest & request) slot
Creates a new DB instance from a DB snapshot. The target database is created from the source database restore point with the most of original configuration with the default security group and the default DB parameter group. By default, the new DB instance is created as a single-AZ deployment except when the instance is a SQL Server instance that has an option group that is associated with mirroring; in this case, the instance becomes a mirrored AZ deployment and not a single-AZ
deployment>
If your intent is to replace your original DB instance with the new, restored DB instance, then rename your original DB instance before you call the RestoreDBInstanceFromDBSnapshot action. RDS doesn't allow two DB instances with the same name. Once you have renamed your original DB instance with a different identifier, then you can pass the original name of the DB instance as the DBInstanceIdentifier in the call to the RestoreDBInstanceFromDBSnapshot action. The result is that you will replace the original DB instance with the DB instance created from the
snapshot>
If you are restoring from a shared manual DB snapshot, the DBSnapshotIdentifier must be the ARN of the shared DB
snapshot> <note>
This command doesn't apply to Aurora MySQL and Aurora PostgreSQL. For Aurora, use
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2118 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBInstanceFromDBSnapshotResponse *>(send(request));
 }
restoreDBInstanceFromS3
RestoreDBInstanceFromS3Response * QtAws::RDS::RdsClient::restoreDBInstanceFromS3 (const RestoreDBInstanceFromS3Request & request) slot
Amazon Relational Database Service (Amazon RDS) supports importing MySQL databases by using backup files. You can create a backup of your on-premises database, store it on Amazon Simple Storage Service (Amazon S3), and then restore the backup file onto a new Amazon RDS DB instance running MySQL. For more information, see Importing Data into an Amazon RDS MySQL DB Instance.
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2136 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBInstanceFromS3Response *>(send(request));
 }
restoreDBInstanceToPointInTime
RestoreDBInstanceToPointInTimeResponse * QtAws::RDS::RdsClient::restoreDBInstanceToPointInTime (const RestoreDBInstanceToPointInTimeRequest & request) slot
Restores a DB instance to an arbitrary point in time. You can restore to any point in time before the time identified by the LatestRestorableTime property. You can restore to a point up to the number of days specified by the BackupRetentionPeriod
property>
The target database is created with most of the original configuration, but in a system-selected availability zone, with the default security group, the default subnet group, and the default DB parameter group. By default, the new DB instance is created as a single-AZ deployment except when the instance is a SQL Server instance that has an option group that is associated with mirroring; in this case, the instance becomes a mirrored deployment and not a single-AZ
deployment> <note>
This command doesn't apply to Aurora MySQL and Aurora PostgreSQL. For Aurora, use
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2163 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreDBInstanceToPointInTimeResponse *>(send(request));
 }
revokeDBSecurityGroupIngress
RevokeDBSecurityGroupIngressResponse * QtAws::RDS::RdsClient::revokeDBSecurityGroupIngress (const RevokeDBSecurityGroupIngressRequest & request) slot
Revokes ingress from a DBSecurityGroup for previously authorized IP ranges or EC2 or VPC Security Groups. Required parameters for this API are one of CIDRIP, EC2SecurityGroupId for VPC, or (EC2SecurityGroupOwnerId and either EC2SecurityGroupName or
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2179 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RevokeDBSecurityGroupIngressResponse *>(send(request));
 }
startDBInstance
StartDBInstanceResponse * QtAws::RDS::RdsClient::startDBInstance (const StartDBInstanceRequest & request) slot
Starts a DB instance that was stopped using the AWS console, the stop-db-instance AWS CLI command, or the StopDBInstance action. For more information, see Stopping and Starting a DB instance in the AWS RDS user guide.
</p <note>
This command doesn't apply to Aurora MySQL and Aurora
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2198 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartDBInstanceResponse *>(send(request));
 }
stopDBInstance
StopDBInstanceResponse * QtAws::RDS::RdsClient::stopDBInstance (const StopDBInstanceRequest & request) slot
Stops a DB instance. When you stop a DB instance, Amazon RDS retains the DB instance's metadata, including its endpoint, DB parameter group, and option group membership. Amazon RDS also retains the transaction logs so you can do a point-in-time restore if necessary. For more information, see Stopping and Starting a DB instance in the AWS RDS user guide.
</p <note>
This command doesn't apply to Aurora MySQL and Aurora
Parameters
request Request to send to Amazon Relational Database Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2219 of file rdsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopDBInstanceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
rds/rdsclient.h
rds/rdsclient.cpp