AWS SDK for Qt: QtAws::EC2::Ec2Client Class Reference
QtAws::EC2::Ec2Client Class Reference
Client for Amazon Elastic Compute Cloud (EC2)
Public Slots
AcceptReservedInstancesExchangeQuoteResponse * acceptReservedInstancesExchangeQuote (const AcceptReservedInstancesExchangeQuoteRequest &request)
AcceptVpcEndpointConnectionsResponse * acceptVpcEndpointConnections (const AcceptVpcEndpointConnectionsRequest &request)
AcceptVpcPeeringConnectionResponse * acceptVpcPeeringConnection (const AcceptVpcPeeringConnectionRequest &request)
AllocateAddressResponse * allocateAddress (const AllocateAddressRequest &request)
AllocateHostsResponse * allocateHosts (const AllocateHostsRequest &request)
AssignIpv6AddressesResponse * assignIpv6Addresses (const AssignIpv6AddressesRequest &request)
AssignPrivateIpAddressesResponse * assignPrivateIpAddresses (const AssignPrivateIpAddressesRequest &request)
AssociateAddressResponse * associateAddress (const AssociateAddressRequest &request)
AssociateDhcpOptionsResponse * associateDhcpOptions (const AssociateDhcpOptionsRequest &request)
AssociateIamInstanceProfileResponse * associateIamInstanceProfile (const AssociateIamInstanceProfileRequest &request)
AssociateRouteTableResponse * associateRouteTable (const AssociateRouteTableRequest &request)
AssociateSubnetCidrBlockResponse * associateSubnetCidrBlock (const AssociateSubnetCidrBlockRequest &request)
AssociateVpcCidrBlockResponse * associateVpcCidrBlock (const AssociateVpcCidrBlockRequest &request)
AttachClassicLinkVpcResponse * attachClassicLinkVpc (const AttachClassicLinkVpcRequest &request)
AttachInternetGatewayResponse * attachInternetGateway (const AttachInternetGatewayRequest &request)
AttachNetworkInterfaceResponse * attachNetworkInterface (const AttachNetworkInterfaceRequest &request)
AttachVolumeResponse * attachVolume (const AttachVolumeRequest &request)
AttachVpnGatewayResponse * attachVpnGateway (const AttachVpnGatewayRequest &request)
AuthorizeSecurityGroupEgressResponse * authorizeSecurityGroupEgress (const AuthorizeSecurityGroupEgressRequest &request)
AuthorizeSecurityGroupIngressResponse * authorizeSecurityGroupIngress (const AuthorizeSecurityGroupIngressRequest &request)
BundleInstanceResponse * bundleInstance (const BundleInstanceRequest &request)
CancelBundleTaskResponse * cancelBundleTask (const CancelBundleTaskRequest &request)
CancelConversionTaskResponse * cancelConversionTask (const CancelConversionTaskRequest &request)
CancelExportTaskResponse * cancelExportTask (const CancelExportTaskRequest &request)
CancelImportTaskResponse * cancelImportTask (const CancelImportTaskRequest &request)
CancelReservedInstancesListingResponse * cancelReservedInstancesListing (const CancelReservedInstancesListingRequest &request)
CancelSpotFleetRequestsResponse * cancelSpotFleetRequests (const CancelSpotFleetRequestsRequest &request)
CancelSpotInstanceRequestsResponse * cancelSpotInstanceRequests (const CancelSpotInstanceRequestsRequest &request)
ConfirmProductInstanceResponse * confirmProductInstance (const ConfirmProductInstanceRequest &request)
CopyFpgaImageResponse * copyFpgaImage (const CopyFpgaImageRequest &request)
CopyImageResponse * copyImage (const CopyImageRequest &request)
CopySnapshotResponse * copySnapshot (const CopySnapshotRequest &request)
CreateCustomerGatewayResponse * createCustomerGateway (const CreateCustomerGatewayRequest &request)
CreateDefaultSubnetResponse * createDefaultSubnet (const CreateDefaultSubnetRequest &request)
CreateDefaultVpcResponse * createDefaultVpc (const CreateDefaultVpcRequest &request)
CreateDhcpOptionsResponse * createDhcpOptions (const CreateDhcpOptionsRequest &request)
CreateEgressOnlyInternetGatewayResponse * createEgressOnlyInternetGateway (const CreateEgressOnlyInternetGatewayRequest &request)
CreateFlowLogsResponse * createFlowLogs (const CreateFlowLogsRequest &request)
CreateFpgaImageResponse * createFpgaImage (const CreateFpgaImageRequest &request)
CreateImageResponse * createImage (const CreateImageRequest &request)
CreateInstanceExportTaskResponse * createInstanceExportTask (const CreateInstanceExportTaskRequest &request)
CreateInternetGatewayResponse * createInternetGateway (const CreateInternetGatewayRequest &request)
CreateKeyPairResponse * createKeyPair (const CreateKeyPairRequest &request)
CreateLaunchTemplateResponse * createLaunchTemplate (const CreateLaunchTemplateRequest &request)
CreateLaunchTemplateVersionResponse * createLaunchTemplateVersion (const CreateLaunchTemplateVersionRequest &request)
CreateNatGatewayResponse * createNatGateway (const CreateNatGatewayRequest &request)
CreateNetworkAclResponse * createNetworkAcl (const CreateNetworkAclRequest &request)
CreateNetworkAclEntryResponse * createNetworkAclEntry (const CreateNetworkAclEntryRequest &request)
CreateNetworkInterfaceResponse * createNetworkInterface (const CreateNetworkInterfaceRequest &request)
CreateNetworkInterfacePermissionResponse * createNetworkInterfacePermission (const CreateNetworkInterfacePermissionRequest &request)
CreatePlacementGroupResponse * createPlacementGroup (const CreatePlacementGroupRequest &request)
CreateReservedInstancesListingResponse * createReservedInstancesListing (const CreateReservedInstancesListingRequest &request)
CreateRouteResponse * createRoute (const CreateRouteRequest &request)
CreateRouteTableResponse * createRouteTable (const CreateRouteTableRequest &request)
CreateSecurityGroupResponse * createSecurityGroup (const CreateSecurityGroupRequest &request)
CreateSnapshotResponse * createSnapshot (const CreateSnapshotRequest &request)
CreateSpotDatafeedSubscriptionResponse * createSpotDatafeedSubscription (const CreateSpotDatafeedSubscriptionRequest &request)
CreateSubnetResponse * createSubnet (const CreateSubnetRequest &request)
CreateTagsResponse * createTags (const CreateTagsRequest &request)
CreateVolumeResponse * createVolume (const CreateVolumeRequest &request)
CreateVpcResponse * createVpc (const CreateVpcRequest &request)
CreateVpcEndpointResponse * createVpcEndpoint (const CreateVpcEndpointRequest &request)
CreateVpcEndpointConnectionNotificationResponse * createVpcEndpointConnectionNotification (const CreateVpcEndpointConnectionNotificationRequest &request)
CreateVpcEndpointServiceConfigurationResponse * createVpcEndpointServiceConfiguration (const CreateVpcEndpointServiceConfigurationRequest &request)
CreateVpcPeeringConnectionResponse * createVpcPeeringConnection (const CreateVpcPeeringConnectionRequest &request)
CreateVpnConnectionResponse * createVpnConnection (const CreateVpnConnectionRequest &request)
CreateVpnConnectionRouteResponse * createVpnConnectionRoute (const CreateVpnConnectionRouteRequest &request)
CreateVpnGatewayResponse * createVpnGateway (const CreateVpnGatewayRequest &request)
DeleteCustomerGatewayResponse * deleteCustomerGateway (const DeleteCustomerGatewayRequest &request)
DeleteDhcpOptionsResponse * deleteDhcpOptions (const DeleteDhcpOptionsRequest &request)
DeleteEgressOnlyInternetGatewayResponse * deleteEgressOnlyInternetGateway (const DeleteEgressOnlyInternetGatewayRequest &request)
DeleteFlowLogsResponse * deleteFlowLogs (const DeleteFlowLogsRequest &request)
DeleteFpgaImageResponse * deleteFpgaImage (const DeleteFpgaImageRequest &request)
DeleteInternetGatewayResponse * deleteInternetGateway (const DeleteInternetGatewayRequest &request)
DeleteKeyPairResponse * deleteKeyPair (const DeleteKeyPairRequest &request)
DeleteLaunchTemplateResponse * deleteLaunchTemplate (const DeleteLaunchTemplateRequest &request)
DeleteLaunchTemplateVersionsResponse * deleteLaunchTemplateVersions (const DeleteLaunchTemplateVersionsRequest &request)
DeleteNatGatewayResponse * deleteNatGateway (const DeleteNatGatewayRequest &request)
DeleteNetworkAclResponse * deleteNetworkAcl (const DeleteNetworkAclRequest &request)
DeleteNetworkAclEntryResponse * deleteNetworkAclEntry (const DeleteNetworkAclEntryRequest &request)
DeleteNetworkInterfaceResponse * deleteNetworkInterface (const DeleteNetworkInterfaceRequest &request)
DeleteNetworkInterfacePermissionResponse * deleteNetworkInterfacePermission (const DeleteNetworkInterfacePermissionRequest &request)
DeletePlacementGroupResponse * deletePlacementGroup (const DeletePlacementGroupRequest &request)
DeleteRouteResponse * deleteRoute (const DeleteRouteRequest &request)
DeleteRouteTableResponse * deleteRouteTable (const DeleteRouteTableRequest &request)
DeleteSecurityGroupResponse * deleteSecurityGroup (const DeleteSecurityGroupRequest &request)
DeleteSnapshotResponse * deleteSnapshot (const DeleteSnapshotRequest &request)
DeleteSpotDatafeedSubscriptionResponse * deleteSpotDatafeedSubscription (const DeleteSpotDatafeedSubscriptionRequest &request)
DeleteSubnetResponse * deleteSubnet (const DeleteSubnetRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DeleteVolumeResponse * deleteVolume (const DeleteVolumeRequest &request)
DeleteVpcResponse * deleteVpc (const DeleteVpcRequest &request)
DeleteVpcEndpointConnectionNotificationsResponse * deleteVpcEndpointConnectionNotifications (const DeleteVpcEndpointConnectionNotificationsRequest &request)
DeleteVpcEndpointServiceConfigurationsResponse * deleteVpcEndpointServiceConfigurations (const DeleteVpcEndpointServiceConfigurationsRequest &request)
DeleteVpcEndpointsResponse * deleteVpcEndpoints (const DeleteVpcEndpointsRequest &request)
DeleteVpcPeeringConnectionResponse * deleteVpcPeeringConnection (const DeleteVpcPeeringConnectionRequest &request)
DeleteVpnConnectionResponse * deleteVpnConnection (const DeleteVpnConnectionRequest &request)
DeleteVpnConnectionRouteResponse * deleteVpnConnectionRoute (const DeleteVpnConnectionRouteRequest &request)
DeleteVpnGatewayResponse * deleteVpnGateway (const DeleteVpnGatewayRequest &request)
DeregisterImageResponse * deregisterImage (const DeregisterImageRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes (const DescribeAccountAttributesRequest &request)
DescribeAddressesResponse * describeAddresses (const DescribeAddressesRequest &request)
DescribeAggregateIdFormatResponse * describeAggregateIdFormat (const DescribeAggregateIdFormatRequest &request)
DescribeAvailabilityZonesResponse * describeAvailabilityZones (const DescribeAvailabilityZonesRequest &request)
DescribeBundleTasksResponse * describeBundleTasks (const DescribeBundleTasksRequest &request)
DescribeClassicLinkInstancesResponse * describeClassicLinkInstances (const DescribeClassicLinkInstancesRequest &request)
DescribeConversionTasksResponse * describeConversionTasks (const DescribeConversionTasksRequest &request)
DescribeCustomerGatewaysResponse * describeCustomerGateways (const DescribeCustomerGatewaysRequest &request)
DescribeDhcpOptionsResponse * describeDhcpOptions (const DescribeDhcpOptionsRequest &request)
DescribeEgressOnlyInternetGatewaysResponse * describeEgressOnlyInternetGateways (const DescribeEgressOnlyInternetGatewaysRequest &request)
DescribeElasticGpusResponse * describeElasticGpus (const DescribeElasticGpusRequest &request)
DescribeExportTasksResponse * describeExportTasks (const DescribeExportTasksRequest &request)
DescribeFlowLogsResponse * describeFlowLogs (const DescribeFlowLogsRequest &request)
DescribeFpgaImageAttributeResponse * describeFpgaImageAttribute (const DescribeFpgaImageAttributeRequest &request)
DescribeFpgaImagesResponse * describeFpgaImages (const DescribeFpgaImagesRequest &request)
DescribeHostReservationOfferingsResponse * describeHostReservationOfferings (const DescribeHostReservationOfferingsRequest &request)
DescribeHostReservationsResponse * describeHostReservations (const DescribeHostReservationsRequest &request)
DescribeHostsResponse * describeHosts (const DescribeHostsRequest &request)
DescribeIamInstanceProfileAssociationsResponse * describeIamInstanceProfileAssociations (const DescribeIamInstanceProfileAssociationsRequest &request)
DescribeIdFormatResponse * describeIdFormat (const DescribeIdFormatRequest &request)
DescribeIdentityIdFormatResponse * describeIdentityIdFormat (const DescribeIdentityIdFormatRequest &request)
DescribeImageAttributeResponse * describeImageAttribute (const DescribeImageAttributeRequest &request)
DescribeImagesResponse * describeImages (const DescribeImagesRequest &request)
DescribeImportImageTasksResponse * describeImportImageTasks (const DescribeImportImageTasksRequest &request)
DescribeImportSnapshotTasksResponse * describeImportSnapshotTasks (const DescribeImportSnapshotTasksRequest &request)
DescribeInstanceAttributeResponse * describeInstanceAttribute (const DescribeInstanceAttributeRequest &request)
DescribeInstanceCreditSpecificationsResponse * describeInstanceCreditSpecifications (const DescribeInstanceCreditSpecificationsRequest &request)
DescribeInstanceStatusResponse * describeInstanceStatus (const DescribeInstanceStatusRequest &request)
DescribeInstancesResponse * describeInstances (const DescribeInstancesRequest &request)
DescribeInternetGatewaysResponse * describeInternetGateways (const DescribeInternetGatewaysRequest &request)
DescribeKeyPairsResponse * describeKeyPairs (const DescribeKeyPairsRequest &request)
DescribeLaunchTemplateVersionsResponse * describeLaunchTemplateVersions (const DescribeLaunchTemplateVersionsRequest &request)
DescribeLaunchTemplatesResponse * describeLaunchTemplates (const DescribeLaunchTemplatesRequest &request)
DescribeMovingAddressesResponse * describeMovingAddresses (const DescribeMovingAddressesRequest &request)
DescribeNatGatewaysResponse * describeNatGateways (const DescribeNatGatewaysRequest &request)
DescribeNetworkAclsResponse * describeNetworkAcls (const DescribeNetworkAclsRequest &request)
DescribeNetworkInterfaceAttributeResponse * describeNetworkInterfaceAttribute (const DescribeNetworkInterfaceAttributeRequest &request)
DescribeNetworkInterfacePermissionsResponse * describeNetworkInterfacePermissions (const DescribeNetworkInterfacePermissionsRequest &request)
DescribeNetworkInterfacesResponse * describeNetworkInterfaces (const DescribeNetworkInterfacesRequest &request)
DescribePlacementGroupsResponse * describePlacementGroups (const DescribePlacementGroupsRequest &request)
DescribePrefixListsResponse * describePrefixLists (const DescribePrefixListsRequest &request)
DescribePrincipalIdFormatResponse * describePrincipalIdFormat (const DescribePrincipalIdFormatRequest &request)
DescribeRegionsResponse * describeRegions (const DescribeRegionsRequest &request)
DescribeReservedInstancesResponse * describeReservedInstances (const DescribeReservedInstancesRequest &request)
DescribeReservedInstancesListingsResponse * describeReservedInstancesListings (const DescribeReservedInstancesListingsRequest &request)
DescribeReservedInstancesModificationsResponse * describeReservedInstancesModifications (const DescribeReservedInstancesModificationsRequest &request)
DescribeReservedInstancesOfferingsResponse * describeReservedInstancesOfferings (const DescribeReservedInstancesOfferingsRequest &request)
DescribeRouteTablesResponse * describeRouteTables (const DescribeRouteTablesRequest &request)
DescribeScheduledInstanceAvailabilityResponse * describeScheduledInstanceAvailability (const DescribeScheduledInstanceAvailabilityRequest &request)
DescribeScheduledInstancesResponse * describeScheduledInstances (const DescribeScheduledInstancesRequest &request)
DescribeSecurityGroupReferencesResponse * describeSecurityGroupReferences (const DescribeSecurityGroupReferencesRequest &request)
DescribeSecurityGroupsResponse * describeSecurityGroups (const DescribeSecurityGroupsRequest &request)
DescribeSnapshotAttributeResponse * describeSnapshotAttribute (const DescribeSnapshotAttributeRequest &request)
DescribeSnapshotsResponse * describeSnapshots (const DescribeSnapshotsRequest &request)
DescribeSpotDatafeedSubscriptionResponse * describeSpotDatafeedSubscription (const DescribeSpotDatafeedSubscriptionRequest &request)
DescribeSpotFleetInstancesResponse * describeSpotFleetInstances (const DescribeSpotFleetInstancesRequest &request)
DescribeSpotFleetRequestHistoryResponse * describeSpotFleetRequestHistory (const DescribeSpotFleetRequestHistoryRequest &request)
DescribeSpotFleetRequestsResponse * describeSpotFleetRequests (const DescribeSpotFleetRequestsRequest &request)
DescribeSpotInstanceRequestsResponse * describeSpotInstanceRequests (const DescribeSpotInstanceRequestsRequest &request)
DescribeSpotPriceHistoryResponse * describeSpotPriceHistory (const DescribeSpotPriceHistoryRequest &request)
DescribeStaleSecurityGroupsResponse * describeStaleSecurityGroups (const DescribeStaleSecurityGroupsRequest &request)
DescribeSubnetsResponse * describeSubnets (const DescribeSubnetsRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeVolumeAttributeResponse * describeVolumeAttribute (const DescribeVolumeAttributeRequest &request)
DescribeVolumeStatusResponse * describeVolumeStatus (const DescribeVolumeStatusRequest &request)
DescribeVolumesResponse * describeVolumes (const DescribeVolumesRequest &request)
DescribeVolumesModificationsResponse * describeVolumesModifications (const DescribeVolumesModificationsRequest &request)
DescribeVpcAttributeResponse * describeVpcAttribute (const DescribeVpcAttributeRequest &request)
DescribeVpcClassicLinkResponse * describeVpcClassicLink (const DescribeVpcClassicLinkRequest &request)
DescribeVpcClassicLinkDnsSupportResponse * describeVpcClassicLinkDnsSupport (const DescribeVpcClassicLinkDnsSupportRequest &request)
DescribeVpcEndpointConnectionNotificationsResponse * describeVpcEndpointConnectionNotifications (const DescribeVpcEndpointConnectionNotificationsRequest &request)
DescribeVpcEndpointConnectionsResponse * describeVpcEndpointConnections (const DescribeVpcEndpointConnectionsRequest &request)
DescribeVpcEndpointServiceConfigurationsResponse * describeVpcEndpointServiceConfigurations (const DescribeVpcEndpointServiceConfigurationsRequest &request)
DescribeVpcEndpointServicePermissionsResponse * describeVpcEndpointServicePermissions (const DescribeVpcEndpointServicePermissionsRequest &request)
DescribeVpcEndpointServicesResponse * describeVpcEndpointServices (const DescribeVpcEndpointServicesRequest &request)
DescribeVpcEndpointsResponse * describeVpcEndpoints (const DescribeVpcEndpointsRequest &request)
DescribeVpcPeeringConnectionsResponse * describeVpcPeeringConnections (const DescribeVpcPeeringConnectionsRequest &request)
DescribeVpcsResponse * describeVpcs (const DescribeVpcsRequest &request)
DescribeVpnConnectionsResponse * describeVpnConnections (const DescribeVpnConnectionsRequest &request)
DescribeVpnGatewaysResponse * describeVpnGateways (const DescribeVpnGatewaysRequest &request)
DetachClassicLinkVpcResponse * detachClassicLinkVpc (const DetachClassicLinkVpcRequest &request)
DetachInternetGatewayResponse * detachInternetGateway (const DetachInternetGatewayRequest &request)
DetachNetworkInterfaceResponse * detachNetworkInterface (const DetachNetworkInterfaceRequest &request)
DetachVolumeResponse * detachVolume (const DetachVolumeRequest &request)
DetachVpnGatewayResponse * detachVpnGateway (const DetachVpnGatewayRequest &request)
DisableVgwRoutePropagationResponse * disableVgwRoutePropagation (const DisableVgwRoutePropagationRequest &request)
DisableVpcClassicLinkResponse * disableVpcClassicLink (const DisableVpcClassicLinkRequest &request)
DisableVpcClassicLinkDnsSupportResponse * disableVpcClassicLinkDnsSupport (const DisableVpcClassicLinkDnsSupportRequest &request)
DisassociateAddressResponse * disassociateAddress (const DisassociateAddressRequest &request)
DisassociateIamInstanceProfileResponse * disassociateIamInstanceProfile (const DisassociateIamInstanceProfileRequest &request)
DisassociateRouteTableResponse * disassociateRouteTable (const DisassociateRouteTableRequest &request)
DisassociateSubnetCidrBlockResponse * disassociateSubnetCidrBlock (const DisassociateSubnetCidrBlockRequest &request)
DisassociateVpcCidrBlockResponse * disassociateVpcCidrBlock (const DisassociateVpcCidrBlockRequest &request)
EnableVgwRoutePropagationResponse * enableVgwRoutePropagation (const EnableVgwRoutePropagationRequest &request)
EnableVolumeIOResponse * enableVolumeIO (const EnableVolumeIORequest &request)
EnableVpcClassicLinkResponse * enableVpcClassicLink (const EnableVpcClassicLinkRequest &request)
EnableVpcClassicLinkDnsSupportResponse * enableVpcClassicLinkDnsSupport (const EnableVpcClassicLinkDnsSupportRequest &request)
GetConsoleOutputResponse * getConsoleOutput (const GetConsoleOutputRequest &request)
GetConsoleScreenshotResponse * getConsoleScreenshot (const GetConsoleScreenshotRequest &request)
GetHostReservationPurchasePreviewResponse * getHostReservationPurchasePreview (const GetHostReservationPurchasePreviewRequest &request)
GetLaunchTemplateDataResponse * getLaunchTemplateData (const GetLaunchTemplateDataRequest &request)
GetPasswordDataResponse * getPasswordData (const GetPasswordDataRequest &request)
GetReservedInstancesExchangeQuoteResponse * getReservedInstancesExchangeQuote (const GetReservedInstancesExchangeQuoteRequest &request)
ImportImageResponse * importImage (const ImportImageRequest &request)
ImportInstanceResponse * importInstance (const ImportInstanceRequest &request)
ImportKeyPairResponse * importKeyPair (const ImportKeyPairRequest &request)
ImportSnapshotResponse * importSnapshot (const ImportSnapshotRequest &request)
ImportVolumeResponse * importVolume (const ImportVolumeRequest &request)
ModifyFpgaImageAttributeResponse * modifyFpgaImageAttribute (const ModifyFpgaImageAttributeRequest &request)
ModifyHostsResponse * modifyHosts (const ModifyHostsRequest &request)
ModifyIdFormatResponse * modifyIdFormat (const ModifyIdFormatRequest &request)
ModifyIdentityIdFormatResponse * modifyIdentityIdFormat (const ModifyIdentityIdFormatRequest &request)
ModifyImageAttributeResponse * modifyImageAttribute (const ModifyImageAttributeRequest &request)
ModifyInstanceAttributeResponse * modifyInstanceAttribute (const ModifyInstanceAttributeRequest &request)
ModifyInstanceCreditSpecificationResponse * modifyInstanceCreditSpecification (const ModifyInstanceCreditSpecificationRequest &request)
ModifyInstancePlacementResponse * modifyInstancePlacement (const ModifyInstancePlacementRequest &request)
ModifyLaunchTemplateResponse * modifyLaunchTemplate (const ModifyLaunchTemplateRequest &request)
ModifyNetworkInterfaceAttributeResponse * modifyNetworkInterfaceAttribute (const ModifyNetworkInterfaceAttributeRequest &request)
ModifyReservedInstancesResponse * modifyReservedInstances (const ModifyReservedInstancesRequest &request)
ModifySnapshotAttributeResponse * modifySnapshotAttribute (const ModifySnapshotAttributeRequest &request)
ModifySpotFleetRequestResponse * modifySpotFleetRequest (const ModifySpotFleetRequestRequest &request)
ModifySubnetAttributeResponse * modifySubnetAttribute (const ModifySubnetAttributeRequest &request)
ModifyVolumeResponse * modifyVolume (const ModifyVolumeRequest &request)
ModifyVolumeAttributeResponse * modifyVolumeAttribute (const ModifyVolumeAttributeRequest &request)
ModifyVpcAttributeResponse * modifyVpcAttribute (const ModifyVpcAttributeRequest &request)
ModifyVpcEndpointResponse * modifyVpcEndpoint (const ModifyVpcEndpointRequest &request)
ModifyVpcEndpointConnectionNotificationResponse * modifyVpcEndpointConnectionNotification (const ModifyVpcEndpointConnectionNotificationRequest &request)
ModifyVpcEndpointServiceConfigurationResponse * modifyVpcEndpointServiceConfiguration (const ModifyVpcEndpointServiceConfigurationRequest &request)
ModifyVpcEndpointServicePermissionsResponse * modifyVpcEndpointServicePermissions (const ModifyVpcEndpointServicePermissionsRequest &request)
ModifyVpcPeeringConnectionOptionsResponse * modifyVpcPeeringConnectionOptions (const ModifyVpcPeeringConnectionOptionsRequest &request)
ModifyVpcTenancyResponse * modifyVpcTenancy (const ModifyVpcTenancyRequest &request)
MonitorInstancesResponse * monitorInstances (const MonitorInstancesRequest &request)
MoveAddressToVpcResponse * moveAddressToVpc (const MoveAddressToVpcRequest &request)
PurchaseHostReservationResponse * purchaseHostReservation (const PurchaseHostReservationRequest &request)
PurchaseReservedInstancesOfferingResponse * purchaseReservedInstancesOffering (const PurchaseReservedInstancesOfferingRequest &request)
PurchaseScheduledInstancesResponse * purchaseScheduledInstances (const PurchaseScheduledInstancesRequest &request)
RebootInstancesResponse * rebootInstances (const RebootInstancesRequest &request)
RegisterImageResponse * registerImage (const RegisterImageRequest &request)
RejectVpcEndpointConnectionsResponse * rejectVpcEndpointConnections (const RejectVpcEndpointConnectionsRequest &request)
RejectVpcPeeringConnectionResponse * rejectVpcPeeringConnection (const RejectVpcPeeringConnectionRequest &request)
ReleaseAddressResponse * releaseAddress (const ReleaseAddressRequest &request)
ReleaseHostsResponse * releaseHosts (const ReleaseHostsRequest &request)
ReplaceIamInstanceProfileAssociationResponse * replaceIamInstanceProfileAssociation (const ReplaceIamInstanceProfileAssociationRequest &request)
ReplaceNetworkAclAssociationResponse * replaceNetworkAclAssociation (const ReplaceNetworkAclAssociationRequest &request)
ReplaceNetworkAclEntryResponse * replaceNetworkAclEntry (const ReplaceNetworkAclEntryRequest &request)
ReplaceRouteResponse * replaceRoute (const ReplaceRouteRequest &request)
ReplaceRouteTableAssociationResponse * replaceRouteTableAssociation (const ReplaceRouteTableAssociationRequest &request)
ReportInstanceStatusResponse * reportInstanceStatus (const ReportInstanceStatusRequest &request)
RequestSpotFleetResponse * requestSpotFleet (const RequestSpotFleetRequest &request)
RequestSpotInstancesResponse * requestSpotInstances (const RequestSpotInstancesRequest &request)
ResetFpgaImageAttributeResponse * resetFpgaImageAttribute (const ResetFpgaImageAttributeRequest &request)
ResetImageAttributeResponse * resetImageAttribute (const ResetImageAttributeRequest &request)
ResetInstanceAttributeResponse * resetInstanceAttribute (const ResetInstanceAttributeRequest &request)
ResetNetworkInterfaceAttributeResponse * resetNetworkInterfaceAttribute (const ResetNetworkInterfaceAttributeRequest &request)
ResetSnapshotAttributeResponse * resetSnapshotAttribute (const ResetSnapshotAttributeRequest &request)
RestoreAddressToClassicResponse * restoreAddressToClassic (const RestoreAddressToClassicRequest &request)
RevokeSecurityGroupEgressResponse * revokeSecurityGroupEgress (const RevokeSecurityGroupEgressRequest &request)
RevokeSecurityGroupIngressResponse * revokeSecurityGroupIngress (const RevokeSecurityGroupIngressRequest &request)
RunInstancesResponse * runInstances (const RunInstancesRequest &request)
RunScheduledInstancesResponse * runScheduledInstances (const RunScheduledInstancesRequest &request)
StartInstancesResponse * startInstances (const StartInstancesRequest &request)
StopInstancesResponse * stopInstances (const StopInstancesRequest &request)
TerminateInstancesResponse * terminateInstances (const TerminateInstancesRequest &request)
UnassignIpv6AddressesResponse * unassignIpv6Addresses (const UnassignIpv6AddressesRequest &request)
UnassignPrivateIpAddressesResponse * unassignPrivateIpAddresses (const UnassignPrivateIpAddressesRequest &request)
UnmonitorInstancesResponse * unmonitorInstances (const UnmonitorInstancesRequest &request)
UpdateSecurityGroupRuleDescriptionsEgressResponse * updateSecurityGroupRuleDescriptionsEgress (const UpdateSecurityGroupRuleDescriptionsEgressRequest &request)
UpdateSecurityGroupRuleDescriptionsIngressResponse * updateSecurityGroupRuleDescriptionsIngress (const UpdateSecurityGroupRuleDescriptionsIngressRequest &request)
Public Member Functions
Ec2Client (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Ec2Client object.
Ec2Client (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Ec2Client object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Elastic Compute Cloud (EC2)
<fullname>Amazon Elastic Compute Cloud</fullname>
Amazon Elastic Compute Cloud (Amazon EC2) provides resizable computing capacity in the AWS Cloud. Using Amazon EC2 eliminates the need to invest in hardware up front, so you can develop and deploy applications
Definition at line 568 of file ec2client.h.
Constructor & Destructor Documentation
Ec2Client() [1/2]
QtAws::EC2::Ec2Client::Ec2Client (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Ec2Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 586 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new Ec2ClientPrivate(this), parent)
 {
     Q_D(Ec2Client);
     d->apiVersion = QStringLiteral("2016-11-15");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("ec2");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Elastic Compute Cloud");
     d->serviceName = QStringLiteral("ec2");
 }
Ec2Client() [2/2]
QtAws::EC2::Ec2Client::Ec2Client (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Ec2Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 619 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new Ec2ClientPrivate(this), parent)
 {
     Q_D(Ec2Client);
     d->apiVersion = QStringLiteral("2016-11-15");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("ec2");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Elastic Compute Cloud");
     d->serviceName = QStringLiteral("ec2");
 }
Member Function Documentation
acceptReservedInstancesExchangeQuote
AcceptReservedInstancesExchangeQuoteResponse * QtAws::EC2::Ec2Client::acceptReservedInstancesExchangeQuote (const AcceptReservedInstancesExchangeQuoteRequest & request) slot
Accepts the Convertible Reserved Instance exchange quote described in the GetReservedInstancesExchangeQuote
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 645 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcceptReservedInstancesExchangeQuoteResponse *>(send(request));
 }
acceptVpcEndpointConnections
AcceptVpcEndpointConnectionsResponse * QtAws::EC2::Ec2Client::acceptVpcEndpointConnections (const AcceptVpcEndpointConnectionsRequest & request) slot
Accepts one or more interface VPC endpoint connection requests to your VPC endpoint
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 659 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcceptVpcEndpointConnectionsResponse *>(send(request));
 }
acceptVpcPeeringConnection
AcceptVpcPeeringConnectionResponse * QtAws::EC2::Ec2Client::acceptVpcPeeringConnection (const AcceptVpcPeeringConnectionRequest & request) slot
Accept a VPC peering connection request. To accept a request, the VPC peering connection must be in the pending-acceptance state, and you must be the owner of the peer VPC. Use DescribeVpcPeeringConnections to view your outstanding VPC peering connection
requests>
For an inter-region VPC peering connection request, you must accept the VPC peering connection in the region of the accepter
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 680 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AcceptVpcPeeringConnectionResponse *>(send(request));
 }
allocateAddress
AllocateAddressResponse * QtAws::EC2::Ec2Client::allocateAddress (const AllocateAddressRequest & request) slot
Allocates an Elastic IP
address>
An Elastic IP address is for use either in the EC2-Classic platform or in a VPC. By default, you can allocate 5 Elastic IP addresses for EC2-Classic per region and 5 Elastic IP addresses for EC2-VPC per
region>
If you release an Elastic IP address for use in a VPC, you might be able to recover it. To recover an Elastic IP address that you released, specify it in the Address parameter. Note that you cannot recover an Elastic IP address that you released after it is allocated to another AWS
account>
For more information, see Elastic IP Addresses in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 711 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocateAddressResponse *>(send(request));
 }
allocateHosts
AllocateHostsResponse * QtAws::EC2::Ec2Client::allocateHosts (const AllocateHostsRequest & request) slot
Allocates a Dedicated Host to your account. At minimum you need to specify the instance size type, Availability Zone, and quantity of hosts you want to
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 726 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocateHostsResponse *>(send(request));
 }
assignIpv6Addresses
AssignIpv6AddressesResponse * QtAws::EC2::Ec2Client::assignIpv6Addresses (const AssignIpv6AddressesRequest & request) slot
Assigns one or more IPv6 addresses to the specified network interface. You can specify one or more specific IPv6 addresses, or you can specify the number of IPv6 addresses to be automatically assigned from within the subnet's IPv6 CIDR block range. You can assign as many IPv6 addresses to a network interface as you can assign private IPv4 addresses, and the limit varies per instance type. For information, see IP Addresses Per Network Interface Per Instance Type in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 745 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssignIpv6AddressesResponse *>(send(request));
 }
assignPrivateIpAddresses
AssignPrivateIpAddressesResponse * QtAws::EC2::Ec2Client::assignPrivateIpAddresses (const AssignPrivateIpAddressesRequest & request) slot
Assigns one or more secondary private IP addresses to the specified network interface. You can specify one or more specific secondary IP addresses, or you can specify the number of secondary IP addresses to be automatically assigned within the subnet's CIDR block range. The number of secondary IP addresses that you can assign to an instance varies by instance type. For information about instance types, see Instance Types in the Amazon Elastic Compute Cloud User Guide. For more information about Elastic IP addresses, see Elastic IP Addresses in the Amazon Elastic Compute Cloud User
Guide>
AssignPrivateIpAddresses is available only in
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 770 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssignPrivateIpAddressesResponse *>(send(request));
 }
associateAddress
AssociateAddressResponse * QtAws::EC2::Ec2Client::associateAddress (const AssociateAddressRequest & request) slot
Associates an Elastic IP address with an instance or a network
interface>
An Elastic IP address is for use in either the EC2-Classic platform or in a VPC. For more information, see Elastic IP Addresses in the Amazon Elastic Compute Cloud User
Guide>
[EC2-Classic, VPC in an EC2-VPC-only account] If the Elastic IP address is already associated with a different instance, it is disassociated from that instance and associated with the specified instance. If you associate an Elastic IP address with an instance that has an existing Elastic IP address, the existing address is disassociated from the instance, but remains allocated to your
account>
[VPC in an EC2-Classic account] If you don't specify a private IP address, the Elastic IP address is associated with the primary IP address. If the Elastic IP address is already associated with a different instance or a network interface, you get an error unless you allow reassociation. You cannot associate an Elastic IP address with an instance or network interface that has an existing Elastic IP
address>
This is an idempotent operation. If you perform the operation more than once, Amazon EC2 doesn't return an error, and you may be charged for each time the Elastic IP address is remapped to the same instance. For more information, see the Elastic IP Addresses section of Amazon EC2 request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 810 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateAddressResponse *>(send(request));
 }
associateDhcpOptions
AssociateDhcpOptionsResponse * QtAws::EC2::Ec2Client::associateDhcpOptions (const AssociateDhcpOptionsRequest & request) slot
Associates a set of DHCP options (that you've previously created) with the specified VPC, or associates no DHCP options with the
VPC>
After you associate the options with the VPC, any existing instances and all new instances that you launch in that VPC use the options. You don't need to restart or relaunch the instances. They automatically pick up the changes within a few hours, depending on how frequently the instance renews its DHCP lease. You can explicitly renew the lease using the operating system on the
instance>
For more information, see DHCP Options Sets in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 837 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateDhcpOptionsResponse *>(send(request));
 }
associateIamInstanceProfile
AssociateIamInstanceProfileResponse * QtAws::EC2::Ec2Client::associateIamInstanceProfile (const AssociateIamInstanceProfileRequest & request) slot
Associates an IAM instance profile with a running or stopped instance. You cannot associate more than one IAM instance profile with an
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 852 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateIamInstanceProfileResponse *>(send(request));
 }
associateRouteTable
AssociateRouteTableResponse * QtAws::EC2::Ec2Client::associateRouteTable (const AssociateRouteTableRequest & request) slot
Associates a subnet with a route table. The subnet and route table must be in the same VPC. This association causes traffic originating from the subnet to be routed according to the routes in the route table. The action returns an association ID, which you need in order to disassociate the route table from the subnet later. A route table can be associated with multiple
subnets>
For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 875 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateRouteTableResponse *>(send(request));
 }
associateSubnetCidrBlock
AssociateSubnetCidrBlockResponse * QtAws::EC2::Ec2Client::associateSubnetCidrBlock (const AssociateSubnetCidrBlockRequest & request) slot
Associates a CIDR block with your subnet. You can only associate a single IPv6 CIDR block with your subnet. An IPv6 CIDR block must have a prefix length of
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 890 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateSubnetCidrBlockResponse *>(send(request));
 }
associateVpcCidrBlock
AssociateVpcCidrBlockResponse * QtAws::EC2::Ec2Client::associateVpcCidrBlock (const AssociateVpcCidrBlockRequest & request) slot
Associates a CIDR block with your VPC. You can associate a secondary IPv4 CIDR block, or you can associate an Amazon-provided IPv6 CIDR block. The IPv6 CIDR block size is fixed at
/56>
For more information about associating CIDR blocks with your VPC and applicable restrictions, see VPC and Subnet Sizing in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 911 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateVpcCidrBlockResponse *>(send(request));
 }
attachClassicLinkVpc
AttachClassicLinkVpcResponse * QtAws::EC2::Ec2Client::attachClassicLinkVpc (const AttachClassicLinkVpcRequest & request) slot
Links an EC2-Classic instance to a ClassicLink-enabled VPC through one or more of the VPC's security groups. You cannot link an EC2-Classic instance to more than one VPC at a time. You can only link an instance that's in the running state. An instance is automatically unlinked from a VPC when it's stopped - you can link it to the VPC again when you restart
it>
After you've linked an instance, you cannot change the VPC security groups that are associated with it. To change the security groups, you must first unlink the instance, and then link it
again>
Linking your instance to a VPC is sometimes referred to as attaching your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 937 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachClassicLinkVpcResponse *>(send(request));
 }
attachInternetGateway
AttachInternetGatewayResponse * QtAws::EC2::Ec2Client::attachInternetGateway (const AttachInternetGatewayRequest & request) slot
Attaches an Internet gateway to a VPC, enabling connectivity between the Internet and the VPC. For more information about your VPC and Internet gateway, see the Amazon Virtual Private Cloud User request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 953 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachInternetGatewayResponse *>(send(request));
 }
attachNetworkInterface
AttachNetworkInterfaceResponse * QtAws::EC2::Ec2Client::attachNetworkInterface (const AttachNetworkInterfaceRequest & request) slot
Attaches a network interface to an
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 967 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachNetworkInterfaceResponse *>(send(request));
 }
attachVolume
AttachVolumeResponse * QtAws::EC2::Ec2Client::attachVolume (const AttachVolumeRequest & request) slot
Attaches an EBS volume to a running or stopped instance and exposes it to the instance with the specified device
name>
Encrypted EBS volumes may only be attached to instances that support Amazon EBS encryption. For more information, see Amazon EBS Encryption in the Amazon Elastic Compute Cloud User
Guide>
For a list of supported device names, see Attaching an EBS Volume to an Instance. Any device names that aren't reserved for instance store volumes can be used for EBS volumes. For more information, see Amazon EC2 Instance Store in the Amazon Elastic Compute Cloud User
Guide>
If a volume has an AWS Marketplace product
code>
The volume can be attached only to a stopped
instance>
AWS Marketplace product codes are copied from the volume to the
instance>
You must be subscribed to the
product>
The instance type and operating system of the instance must support the product. For example, you can't detach a volume from a Windows instance and attach it to a Linux
instance>
For an overview of the AWS Marketplace, see Introducing AWS Marketplace>
For more information about EBS volumes, see Attaching Amazon EBS Volumes in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1026 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachVolumeResponse *>(send(request));
 }
attachVpnGateway
AttachVpnGatewayResponse * QtAws::EC2::Ec2Client::attachVpnGateway (const AttachVpnGatewayRequest & request) slot
Attaches a virtual private gateway to a VPC. You can attach one virtual private gateway to one VPC at a
time>
For more information, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1045 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachVpnGatewayResponse *>(send(request));
 }
authorizeSecurityGroupEgress
AuthorizeSecurityGroupEgressResponse * QtAws::EC2::Ec2Client::authorizeSecurityGroupEgress (const AuthorizeSecurityGroupEgressRequest & request) slot
[EC2-VPC only] Adds one or more egress rules to a security group for use with a VPC. Specifically, this action permits instances to send traffic to one or more destination IPv4 or IPv6 CIDR address ranges, or to one or more destination security groups for the same VPC. This action doesn't apply to security groups for use in EC2-Classic. For more information, see Security Groups for Your VPC in the Amazon Virtual Private Cloud User Guide. For more information about security group limits, see Amazon VPC Limits>
Each rule consists of the protocol (for example, TCP), plus either a CIDR range or a source group. For the TCP and UDP protocols, you must also specify the destination port or port range. For the ICMP protocol, you must also specify the ICMP type and code. You can use -1 for the type or code to mean all types or all codes. You can optionally specify a description for the
rule>
Rule changes are propagated to affected instances as quickly as possible. However, a small delay might
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1075 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AuthorizeSecurityGroupEgressResponse *>(send(request));
 }
authorizeSecurityGroupIngress
AuthorizeSecurityGroupIngressResponse * QtAws::EC2::Ec2Client::authorizeSecurityGroupIngress (const AuthorizeSecurityGroupIngressRequest & request) slot
Adds one or more ingress rules to a security
group>
Rule changes are propagated to instances within the security group as quickly as possible. However, a small delay might
occur>
[EC2-Classic] This action gives one or more IPv4 CIDR address ranges permission to access a security group in your account, or gives one or more security groups (called the source groups) permission to access a security group for your account. A source group can be for your own AWS account, or another. You can have up to 100 rules per
group>
[EC2-VPC] This action gives one or more IPv4 or IPv6 CIDR address ranges permission to access a security group in your VPC, or gives one or more other security groups (called the source groups) permission to access a security group for your VPC. The security groups must all be for the same VPC or a peer VPC in a VPC peering connection. For more information about VPC security group limits, see Amazon VPC Limits>
You can optionally specify a description for the security group
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1111 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AuthorizeSecurityGroupIngressResponse *>(send(request));
 }
bundleInstance
BundleInstanceResponse * QtAws::EC2::Ec2Client::bundleInstance (const BundleInstanceRequest & request) slot
Bundles an Amazon instance store-backed Windows
instance>
During bundling, only the root device volume (C:) is bundled. Data on other instance store volumes is not
preserved> <note>
This action is not applicable for Linux/Unix instances or Windows instances that are backed by Amazon
EBS> </note>
For more information, see Creating an Instance Store-Backed Windows request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1139 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BundleInstanceResponse *>(send(request));
 }
cancelBundleTask
CancelBundleTaskResponse * QtAws::EC2::Ec2Client::cancelBundleTask (const CancelBundleTaskRequest & request) slot
Cancels a bundling operation for an instance store-backed Windows
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1153 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelBundleTaskResponse *>(send(request));
 }
cancelConversionTask
CancelConversionTaskResponse * QtAws::EC2::Ec2Client::cancelConversionTask (const CancelConversionTaskRequest & request) slot
Cancels an active conversion task. The task can be the import of an instance or volume. The action removes all artifacts of the conversion, including a partially uploaded volume or instance. If the conversion is complete or is in the process of transferring the final disk image, the command fails and returns an
exception>
For more information, see Importing a Virtual Machine Using the Amazon EC2 request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1175 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelConversionTaskResponse *>(send(request));
 }
cancelExportTask
CancelExportTaskResponse * QtAws::EC2::Ec2Client::cancelExportTask (const CancelExportTaskRequest & request) slot
Cancels an active export task. The request removes all artifacts of the export, including any partially-created Amazon S3 objects. If the export task is complete or is in the process of transferring the final disk image, the command fails and returns an
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1191 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelExportTaskResponse *>(send(request));
 }
cancelImportTask
CancelImportTaskResponse * QtAws::EC2::Ec2Client::cancelImportTask (const CancelImportTaskRequest & request) slot
Cancels an in-process import virtual machine or import snapshot
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1205 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelImportTaskResponse *>(send(request));
 }
cancelReservedInstancesListing
CancelReservedInstancesListingResponse * QtAws::EC2::Ec2Client::cancelReservedInstancesListing (const CancelReservedInstancesListingRequest & request) slot
Cancels the specified Reserved Instance listing in the Reserved Instance
Marketplace>
For more information, see Reserved Instance Marketplace in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1224 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelReservedInstancesListingResponse *>(send(request));
 }
cancelSpotFleetRequests
CancelSpotFleetRequestsResponse * QtAws::EC2::Ec2Client::cancelSpotFleetRequests (const CancelSpotFleetRequestsRequest & request) slot
Cancels the specified Spot Fleet
requests>
After you cancel a Spot Fleet request, the Spot Fleet launches no new Spot Instances. You must specify whether the Spot Fleet should also terminate its Spot Instances. If you terminate the instances, the Spot Fleet request enters the cancelled_terminating state. Otherwise, the Spot Fleet request enters the cancelled_running state and the instances continue to run until they are interrupted or you terminate them
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1245 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelSpotFleetRequestsResponse *>(send(request));
 }
cancelSpotInstanceRequests
CancelSpotInstanceRequestsResponse * QtAws::EC2::Ec2Client::cancelSpotInstanceRequests (const CancelSpotInstanceRequestsRequest & request) slot
Cancels one or more Spot Instance requests. Spot Instances are instances that Amazon EC2 starts on your behalf when the maximum price that you specify exceeds the current Spot price. For more information, see Spot Instance Requests in the Amazon Elastic Compute Cloud User
Guide>
Canceling a Spot Instance request does not terminate running Spot Instances associated with the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1266 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelSpotInstanceRequestsResponse *>(send(request));
 }
confirmProductInstance
ConfirmProductInstanceResponse * QtAws::EC2::Ec2Client::confirmProductInstance (const ConfirmProductInstanceRequest & request) slot
Determines whether a product code is associated with an instance. This action can only be used by the owner of the product code. It is useful when a product code owner must verify whether another user's instance is eligible for
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1281 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmProductInstanceResponse *>(send(request));
 }
copyFpgaImage
CopyFpgaImageResponse * QtAws::EC2::Ec2Client::copyFpgaImage (const CopyFpgaImageRequest & request) slot
Copies the specified Amazon FPGA Image (AFI) to the current
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1295 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyFpgaImageResponse *>(send(request));
 }
copyImage
CopyImageResponse * QtAws::EC2::Ec2Client::copyImage (const CopyImageRequest & request) slot
Initiates the copy of an AMI from the specified source region to the current region. You specify the destination region by using its endpoint when making the
request>
For more information about the prerequisites and limits when copying an AMI, see Copying an AMI in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1316 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyImageResponse *>(send(request));
 }
copySnapshot
CopySnapshotResponse * QtAws::EC2::Ec2Client::copySnapshot (const CopySnapshotRequest & request) slot
Copies a point-in-time snapshot of an EBS volume and stores it in Amazon S3. You can copy the snapshot within the same region or from one region to another. You can use the snapshot to create EBS volumes or Amazon Machine Images (AMIs). The snapshot is copied to the regional endpoint that you send the HTTP request
to>
Copies of encrypted EBS snapshots remain encrypted. Copies of unencrypted snapshots remain unencrypted, unless the Encrypted flag is specified during the snapshot copy operation. By default, encrypted snapshot copies use the default AWS Key Management Service (AWS KMS) customer master key (CMK); however, you can specify a non-default CMK with the KmsKeyId parameter.
</p <note>
To copy an encrypted snapshot that has been shared from another account, you must have permissions for the CMK used to encrypt the
snapshot> </note> <note>
Snapshots created by the CopySnapshot action have an arbitrary volume ID that should not be used for any
purpose> </note>
For more information, see Copying an Amazon EBS Snapshot in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1353 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopySnapshotResponse *>(send(request));
 }
createCustomerGateway
CreateCustomerGatewayResponse * QtAws::EC2::Ec2Client::createCustomerGateway (const CreateCustomerGatewayRequest & request) slot
Provides information to AWS about your VPN customer gateway device. The customer gateway is the appliance at your end of the VPN connection. (The device on the AWS side of the VPN connection is the virtual private gateway.) You must provide the Internet-routable IP address of the customer gateway's external interface. The IP address must be static and may be behind a device performing network address translation
(NAT)>
For devices that use Border Gateway Protocol (BGP), you can also provide the device's BGP Autonomous System Number (ASN). You can use an existing ASN assigned to your network. If you don't have an ASN already, you can use a private ASN (in the 64512 - 65534
range)> <note>
Amazon EC2 supports all 2-byte ASN numbers in the range of 1 - 65534, with the exception of 7224, which is reserved in the us-east-1 region, and 9059, which is reserved in the eu-west-1
region> </note>
For more information about VPN customer gateways, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Guide>
You cannot create more than one customer gateway with the same VPN type, IP address, and BGP ASN parameter values. If you run an identical request more than one time, the first request creates the customer gateway, and subsequent requests return information about the existing customer gateway. The subsequent requests do not create new customer gateway
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1393 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCustomerGatewayResponse *>(send(request));
 }
createDefaultSubnet
CreateDefaultSubnetResponse * QtAws::EC2::Ec2Client::createDefaultSubnet (const CreateDefaultSubnetRequest & request) slot
Creates a default subnet with a size /20 IPv4 CIDR block in the specified Availability Zone in your default VPC. You can have only one default subnet per Availability Zone. For more information, see Creating a Default Subnet in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1410 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDefaultSubnetResponse *>(send(request));
 }
createDefaultVpc
CreateDefaultVpcResponse * QtAws::EC2::Ec2Client::createDefaultVpc (const CreateDefaultVpcRequest & request) slot
Creates a default VPC with a size /16 IPv4 CIDR block and a default subnet in each Availability Zone. For more information about the components of a default VPC, see Default VPC and Default Subnets in the Amazon Virtual Private Cloud User Guide. You cannot specify the components of the default VPC
yourself>
You can create a default VPC if you deleted your previous default VPC. You cannot have more than one default VPC per region.
</p
If your account supports EC2-Classic, you cannot use this action to create a default VPC in a region that supports EC2-Classic. If you want a default VPC in a region that supports EC2-Classic, see "I really want a default VPC for my existing EC2 account. Is that possible?" in the Default VPCs request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1438 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDefaultVpcResponse *>(send(request));
 }
createDhcpOptions
CreateDhcpOptionsResponse * QtAws::EC2::Ec2Client::createDhcpOptions (const CreateDhcpOptionsRequest & request) slot
Creates a set of DHCP options for your VPC. After creating the set, you must associate it with the VPC, causing all existing and new instances that you launch in the VPC to use this set of DHCP options. The following are the individual DHCP options you can specify. For more information about the options, see RFC 2132>
domain-name-servers - The IP addresses of up to four domain name servers, or AmazonProvidedDNS. The default DHCP option set specifies AmazonProvidedDNS. If specifying more than one domain name server, specify the IP addresses in a single parameter, separated by commas. If you want your instance to receive a custom DNS hostname as specified in domain-name, you must set domain-name-servers to a custom DNS
server>
domain-name - If you're using AmazonProvidedDNS in us-east-1, specify ec2.internal. If you're using AmazonProvidedDNS in another region, specify region.compute.internal (for example, ap-northeast-1.compute.internal). Otherwise, specify a domain name (for example, MyCompany.com). This value is used to complete unqualified DNS hostnames. Important: Some Linux operating systems accept multiple domain names separated by spaces. However, Windows and other Linux operating systems treat the value as a single domain, which results in unexpected behavior. If your DHCP options set is associated with a VPC that has instances with multiple operating systems, specify only one domain
name>
ntp-servers - The IP addresses of up to four Network Time Protocol (NTP)
servers>
netbios-name-servers - The IP addresses of up to four NetBIOS name
servers>
netbios-node-type - The NetBIOS node type (1, 2, 4, or 8). We recommend that you specify 2 (broadcast and multicast are not currently supported). For more information about these node types, see RFC 2132>
Your VPC automatically starts out with a set of DHCP options that includes only a DNS server that we provide (AmazonProvidedDNS). If you create a set of options, and if your VPC has an Internet gateway, make sure to set the domain-name-servers option either to AmazonProvidedDNS or to a domain name server of your choice. For more information about DHCP options, see DHCP Options Sets in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1495 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDhcpOptionsResponse *>(send(request));
 }
createEgressOnlyInternetGateway
CreateEgressOnlyInternetGatewayResponse * QtAws::EC2::Ec2Client::createEgressOnlyInternetGateway (const CreateEgressOnlyInternetGatewayRequest & request) slot
[IPv6 only] Creates an egress-only Internet gateway for your VPC. An egress-only Internet gateway is used to enable outbound communication over IPv6 from instances in your VPC to the Internet, and prevents hosts outside of your VPC from initiating an IPv6 connection with your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1511 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEgressOnlyInternetGatewayResponse *>(send(request));
 }
createFlowLogs
CreateFlowLogsResponse * QtAws::EC2::Ec2Client::createFlowLogs (const CreateFlowLogsRequest & request) slot
Creates one or more flow logs to capture IP traffic for a specific network interface, subnet, or VPC. Flow logs are delivered to a specified log group in Amazon CloudWatch Logs. If you specify a VPC or subnet in the request, a log stream is created in CloudWatch Logs for each network interface in the subnet or VPC. Log streams can include information about accepted and rejected traffic to a network interface. You can view the data in your log streams using Amazon CloudWatch
Logs>
In your request, you must also specify an IAM role that has permission to publish logs to CloudWatch
Logs>
For more information, see VPC Flow Logs in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1538 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFlowLogsResponse *>(send(request));
 }
createFpgaImage
CreateFpgaImageResponse * QtAws::EC2::Ec2Client::createFpgaImage (const CreateFpgaImageRequest & request) slot
Creates an Amazon FPGA Image (AFI) from the specified design checkpoint
(DCP)>
The create operation is asynchronous. To verify that the AFI is ready for use, check the output
logs>
An AFI contains the FPGA bitstream that is ready to download to an FPGA. You can securely deploy an AFI on one or more FPGA-accelerated instances. For more information, see the AWS FPGA Hardware Development request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1562 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFpgaImageResponse *>(send(request));
 }
createImage
CreateImageResponse * QtAws::EC2::Ec2Client::createImage (const CreateImageRequest & request) slot
Creates an Amazon EBS-backed AMI from an Amazon EBS-backed instance that is either running or
stopped>
If you customized your instance with instance store volumes or EBS volumes in addition to the root device volume, the new AMI contains block device mapping information for those volumes. When you launch an instance from this new AMI, the instance automatically launches with those additional
volumes>
For more information, see Creating Amazon EBS-Backed Linux AMIs in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1587 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateImageResponse *>(send(request));
 }
createInstanceExportTask
CreateInstanceExportTaskResponse * QtAws::EC2::Ec2Client::createInstanceExportTask (const CreateInstanceExportTaskRequest & request) slot
Exports a running or stopped instance to an S3
bucket>
For information about the supported operating systems, image formats, and known limitations for the types of instances you can export, see Exporting an Instance as a VM Using VM Import/Export in the VM Import/Export User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1607 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInstanceExportTaskResponse *>(send(request));
 }
createInternetGateway
CreateInternetGatewayResponse * QtAws::EC2::Ec2Client::createInternetGateway (const CreateInternetGatewayRequest & request) slot
Creates an Internet gateway for use with a VPC. After creating the Internet gateway, you attach it to a VPC using
AttachInternetGateway>
For more information about your VPC and Internet gateway, see the Amazon Virtual Private Cloud User request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1626 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInternetGatewayResponse *>(send(request));
 }
createKeyPair
CreateKeyPairResponse * QtAws::EC2::Ec2Client::createKeyPair (const CreateKeyPairRequest & request) slot
Creates a 2048-bit RSA key pair with the specified name. Amazon EC2 stores the public key and displays the private key for you to save to a file. The private key is returned as an unencrypted PEM encoded PKCS#1 private key. If a key with the specified name already exists, Amazon EC2 returns an
error>
You can have up to five thousand key pairs per
region>
The key pair returned to you is available only in the region in which you create it. If you prefer, you can create your own key pair using a third-party tool and upload it to any region using
ImportKeyPair>
For more information, see Key Pairs in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1656 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateKeyPairResponse *>(send(request));
 }
createLaunchTemplate
CreateLaunchTemplateResponse * QtAws::EC2::Ec2Client::createLaunchTemplate (const CreateLaunchTemplateRequest & request) slot
Creates a launch template. A launch template contains the parameters to launch an instance. When you launch an instance using RunInstances, you can specify a launch template instead of providing the launch parameters in the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1671 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLaunchTemplateResponse *>(send(request));
 }
createLaunchTemplateVersion
CreateLaunchTemplateVersionResponse * QtAws::EC2::Ec2Client::createLaunchTemplateVersion (const CreateLaunchTemplateVersionRequest & request) slot
Creates a new version for a launch template. You can specify an existing version of launch template from which to base the new
version>
Launch template versions are numbered in the order in which they are created. You cannot specify, change, or replace the numbering of launch template
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1691 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLaunchTemplateVersionResponse *>(send(request));
 }
createNatGateway
CreateNatGatewayResponse * QtAws::EC2::Ec2Client::createNatGateway (const CreateNatGatewayRequest & request) slot
Creates a NAT gateway in the specified subnet. A NAT gateway can be used to enable instances in a private subnet to connect to the Internet. This action creates a network interface in the specified subnet with a private IP address from the IP address range of the subnet. For more information, see NAT Gateways in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1709 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNatGatewayResponse *>(send(request));
 }
createNetworkAcl
CreateNetworkAclResponse * QtAws::EC2::Ec2Client::createNetworkAcl (const CreateNetworkAclRequest & request) slot
Creates a network ACL in a VPC. Network ACLs provide an optional layer of security (in addition to security groups) for the instances in your
VPC>
For more information about network ACLs, see Network ACLs in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1730 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNetworkAclResponse *>(send(request));
 }
createNetworkAclEntry
CreateNetworkAclEntryResponse * QtAws::EC2::Ec2Client::createNetworkAclEntry (const CreateNetworkAclEntryRequest & request) slot
Creates an entry (a rule) in a network ACL with the specified rule number. Each network ACL has a set of numbered ingress rules and a separate set of numbered egress rules. When determining whether a packet should be allowed in or out of a subnet associated with the ACL, we process the entries in the ACL according to the rule numbers, in ascending order. Each network ACL has a set of ingress rules and a separate set of egress
rules>
We recommend that you leave room between the rule numbers (for example, 100, 110, 120, ...), and not number them one right after the other (for example, 101, 102, 103, ...). This makes it easier to add a rule between existing ones without having to renumber the
rules>
After you add an entry, you can't modify it; you must either replace it, or create an entry and delete the old
one>
For more information about network ACLs, see Network ACLs in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1763 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNetworkAclEntryResponse *>(send(request));
 }
createNetworkInterface
CreateNetworkInterfaceResponse * QtAws::EC2::Ec2Client::createNetworkInterface (const CreateNetworkInterfaceRequest & request) slot
Creates a network interface in the specified
subnet>
For more information about network interfaces, see Elastic Network Interfaces in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1783 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNetworkInterfaceResponse *>(send(request));
 }
createNetworkInterfacePermission
CreateNetworkInterfacePermissionResponse * QtAws::EC2::Ec2Client::createNetworkInterfacePermission (const CreateNetworkInterfacePermissionRequest & request) slot
Grants an AWS authorized partner account permission to attach the specified network interface to an instance in their
account>
You can grant permission to a single AWS account only, and only one account at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1801 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNetworkInterfacePermissionResponse *>(send(request));
 }
createPlacementGroup
CreatePlacementGroupResponse * QtAws::EC2::Ec2Client::createPlacementGroup (const CreatePlacementGroupRequest & request) slot
Creates a placement group in which to launch instances. The strategy of the placement group determines how the instances are organized within the group.
</p
A cluster placement group is a logical grouping of instances within a single Availability Zone that benefit from low network latency, high network throughput. A spread placement group places instances on distinct
hardware>
For more information, see Placement Groups in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1826 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePlacementGroupResponse *>(send(request));
 }
createReservedInstancesListing
CreateReservedInstancesListingResponse * QtAws::EC2::Ec2Client::createReservedInstancesListing (const CreateReservedInstancesListingRequest & request) slot
Creates a listing for Amazon EC2 Standard Reserved Instances to be sold in the Reserved Instance Marketplace. You can submit one Standard Reserved Instance listing at a time. To get a list of your Standard Reserved Instances, you can use the DescribeReservedInstances
operation> <note>
Only Standard Reserved Instances with a capacity reservation can be sold in the Reserved Instance Marketplace. Convertible Reserved Instances and Standard Reserved Instances with a regional benefit cannot be
sold> </note>
The Reserved Instance Marketplace matches sellers who want to resell Standard Reserved Instance capacity that they no longer need with buyers who want to purchase additional capacity. Reserved Instances bought and sold through the Reserved Instance Marketplace work like any other Reserved
Instances>
To sell your Standard Reserved Instances, you must first register as a seller in the Reserved Instance Marketplace. After completing the registration process, you can create a Reserved Instance Marketplace listing of some or all of your Standard Reserved Instances, and specify the upfront price to receive for them. Your Standard Reserved Instance listings then become available for purchase. To view the details of your Standard Reserved Instance listing, you can use the DescribeReservedInstancesListings
operation>
For more information, see Reserved Instance Marketplace in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1866 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReservedInstancesListingResponse *>(send(request));
 }
createRoute
CreateRouteResponse * QtAws::EC2::Ec2Client::createRoute (const CreateRouteRequest & request) slot
Creates a route in a route table within a
VPC>
You must specify one of the following targets: Internet gateway or virtual private gateway, NAT instance, NAT gateway, VPC peering connection, network interface, or egress-only Internet
gateway>
When determining how to route traffic, we use the route with the most specific match. For example, traffic is destined for the IPv4 address 192.0.2.3, and the route table includes the following two IPv4
routes>
192.0.2.0/24 (goes to some target
A>
192.0.2.0/28 (goes to some target
B>
Both routes apply to the traffic destined for 192.0.2.3. However, the second route in the list covers a smaller number of IP addresses and is therefore more specific, so we use that route to determine where to target the
traffic>
For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1909 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRouteResponse *>(send(request));
 }
createRouteTable
CreateRouteTableResponse * QtAws::EC2::Ec2Client::createRouteTable (const CreateRouteTableRequest & request) slot
Creates a route table for the specified VPC. After you create a route table, you can add routes and associate the table with a
subnet>
For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1930 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRouteTableResponse *>(send(request));
 }
createSecurityGroup
CreateSecurityGroupResponse * QtAws::EC2::Ec2Client::createSecurityGroup (const CreateSecurityGroupRequest & request) slot
Creates a security
group>
A security group is for use with instances either in the EC2-Classic platform or in a specific VPC. For more information, see Amazon EC2 Security Groups in the Amazon Elastic Compute Cloud User Guide and Security Groups for Your VPC in the Amazon Virtual Private Cloud User
Guide>
EC2-Classic: You can have up to 500 security
groups>
EC2-VPC: You can create up to 500 security groups per
VPC>
When you create a security group, you specify a friendly name of your choice. You can have a security group for use in EC2-Classic with the same name as a security group for use in a VPC. However, you can't have two security groups for use in EC2-Classic with the same name or two security groups for use in a VPC with the same
name>
You have a default security group for use in EC2-Classic and a default security group for use in your VPC. If you don't specify a security group when you launch an instance, the instance is launched into the appropriate default security group. A default security group includes a default rule that grants instances unrestricted network access to each
other>
You can add or remove rules from your security groups using AuthorizeSecurityGroupIngress, AuthorizeSecurityGroupEgress, RevokeSecurityGroupIngress, and
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1977 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSecurityGroupResponse *>(send(request));
 }
createSnapshot
CreateSnapshotResponse * QtAws::EC2::Ec2Client::createSnapshot (const CreateSnapshotRequest & request) slot
Creates a snapshot of an EBS volume and stores it in Amazon S3. You can use snapshots for backups, to make copies of EBS volumes, and to save data before shutting down an
instance>
When a snapshot is created, any AWS Marketplace product codes that are associated with the source volume are propagated to the
snapshot>
You can take a snapshot of an attached volume that is in use. However, snapshots only capture data that has been written to your EBS volume at the time the snapshot command is issued; this may exclude any data that has been cached by any applications or the operating system. If you can pause any file systems on the volume long enough to take a snapshot, your snapshot should be complete. However, if you cannot pause all file writes to the volume, you should unmount the volume from within the instance, issue the snapshot command, and then remount the volume to ensure a consistent and complete snapshot. You may remount and use your volume while the snapshot status is
pending>
To create a snapshot for EBS volumes that serve as root devices, you should stop the instance before taking the
snapshot>
Snapshots that are taken from encrypted volumes are automatically encrypted. Volumes that are created from encrypted snapshots are also automatically encrypted. Your encrypted volumes and any associated snapshots always remain
protected>
You can tag your snapshots during creation. For more information, see Tagging Your Amazon EC2 Resources>
For more information, see Amazon Elastic Block Store and Amazon EBS Encryption in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2026 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSnapshotResponse *>(send(request));
 }
createSpotDatafeedSubscription
CreateSpotDatafeedSubscriptionResponse * QtAws::EC2::Ec2Client::createSpotDatafeedSubscription (const CreateSpotDatafeedSubscriptionRequest & request) slot
Creates a data feed for Spot Instances, enabling you to view Spot Instance usage logs. You can create one data feed per AWS account. For more information, see Spot Instance Data Feed in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2043 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSpotDatafeedSubscriptionResponse *>(send(request));
 }
createSubnet
CreateSubnetResponse * QtAws::EC2::Ec2Client::createSubnet (const CreateSubnetRequest & request) slot
Creates a subnet in an existing
VPC>
When you create each subnet, you provide the VPC ID and the IPv4 CIDR block you want for the subnet. After you create a subnet, you can't change its CIDR block. The size of the subnet's IPv4 CIDR block can be the same as a VPC's IPv4 CIDR block, or a subset of a VPC's IPv4 CIDR block. If you create more than one subnet in a VPC, the subnets' CIDR blocks must not overlap. The smallest IPv4 subnet (and VPC) you can create uses a /28 netmask (16 IPv4 addresses), and the largest uses a /16 netmask (65,536 IPv4
addresses)>
If you've associated an IPv6 CIDR block with your VPC, you can create a subnet with an IPv6 CIDR block that uses a /64 prefix length.
</p
AWS reserves both the first four and the last IPv4 address in each subnet's CIDR block. They're not available for
use>
If you add more than one subnet to a VPC, they're set up in a star topology with a logical router in the
middle>
If you launch an instance in a VPC using an Amazon EBS-backed AMI, the IP address doesn't change if you stop and restart the instance (unlike a similar instance launched outside a VPC, which gets a new IP address when restarted). It's therefore possible to have a subnet with no running instances (they're all stopped), but no remaining IP addresses
available>
For more information about subnets, see Your VPC and Subnets in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2090 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSubnetResponse *>(send(request));
 }
createTags
CreateTagsResponse * QtAws::EC2::Ec2Client::createTags (const CreateTagsRequest & request) slot
Adds or overwrites one or more tags for the specified Amazon EC2 resource or resources. Each resource can have a maximum of 50 tags. Each tag consists of a key and optional value. Tag keys must be unique per
resource>
For more information about tags, see Tagging Your Resources in the Amazon Elastic Compute Cloud User Guide. For more information about creating IAM policies that control users' access to resources based on tags, see Supported Resource-Level Permissions for Amazon EC2 API Actions in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2114 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTagsResponse *>(send(request));
 }
createVolume
CreateVolumeResponse * QtAws::EC2::Ec2Client::createVolume (const CreateVolumeRequest & request) slot
Creates an EBS volume that can be attached to an instance in the same Availability Zone. The volume is created in the regional endpoint that you send the HTTP request to. For more information see Regions and Endpoints>
You can create a new empty volume or restore a volume from an EBS snapshot. Any AWS Marketplace product codes from the snapshot are propagated to the
volume>
You can create encrypted volumes with the Encrypted parameter. Encrypted volumes may only be attached to instances that support Amazon EBS encryption. Volumes that are created from encrypted snapshots are also automatically encrypted. For more information, see Amazon EBS Encryption in the Amazon Elastic Compute Cloud User
Guide>
You can tag your volumes during creation. For more information, see Tagging Your Amazon EC2 Resources>
For more information, see Creating an Amazon EBS Volume in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2153 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVolumeResponse *>(send(request));
 }
createVpc
CreateVpcResponse * QtAws::EC2::Ec2Client::createVpc (const CreateVpcRequest & request) slot
Creates a VPC with the specified IPv4 CIDR block. The smallest VPC you can create uses a /28 netmask (16 IPv4 addresses), and the largest uses a /16 netmask (65,536 IPv4 addresses). To help you decide how big to make your VPC, see Your VPC and Subnets in the Amazon Virtual Private Cloud User
Guide>
You can optionally request an Amazon-provided IPv6 CIDR block for the VPC. The IPv6 CIDR block uses a /56 prefix length, and is allocated from Amazon's pool of IPv6 addresses. You cannot choose the IPv6 range for your
VPC>
By default, each instance you launch in the VPC has the default DHCP options, which includes only a default DNS server that we provide (AmazonProvidedDNS). For more information about DHCP options, see DHCP Options Sets in the Amazon Virtual Private Cloud User
Guide>
You can specify the instance tenancy value for the VPC when you create it. You can't change this value for the VPC after you create it. For more information, see Dedicated Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2189 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcResponse *>(send(request));
 }
createVpcEndpoint
CreateVpcEndpointResponse * QtAws::EC2::Ec2Client::createVpcEndpoint (const CreateVpcEndpointRequest & request) slot
Creates a VPC endpoint for a specified service. An endpoint enables you to create a private connection between your VPC and the service. The service may be provided by AWS, an AWS Marketplace partner, or another AWS account. For more information, see VPC Endpoints in the Amazon Virtual Private Cloud User
Guide>
A gateway endpoint serves as a target for a route in your route table for traffic destined for the AWS service. You can specify an endpoint policy to attach to the endpoint that will control access to the service from your VPC. You can also specify the VPC route tables that use the
endpoint>
An interface endpoint is a network interface in your subnet that serves as an endpoint for communicating with the specified service. You can specify the subnets in which to create an endpoint, and the security groups to associate with the endpoint network
interface>
Use DescribeVpcEndpointServices to get a list of supported
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2222 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcEndpointResponse *>(send(request));
 }
createVpcEndpointConnectionNotification
CreateVpcEndpointConnectionNotificationResponse * QtAws::EC2::Ec2Client::createVpcEndpointConnectionNotification (const CreateVpcEndpointConnectionNotificationRequest & request) slot
Creates a connection notification for a specified VPC endpoint or VPC endpoint service. A connection notification notifies you of specific endpoint events. You must create an SNS topic to receive notifications. For more information, see Create a Topic in the Amazon Simple Notification Service Developer
Guide>
You can create a connection notification for interface endpoints
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2243 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcEndpointConnectionNotificationResponse *>(send(request));
 }
createVpcEndpointServiceConfiguration
CreateVpcEndpointServiceConfigurationResponse * QtAws::EC2::Ec2Client::createVpcEndpointServiceConfiguration (const CreateVpcEndpointServiceConfigurationRequest & request) slot
Creates a VPC endpoint service configuration to which service consumers (AWS accounts, IAM users, and IAM roles) can connect. Service consumers can create an interface VPC endpoint to connect to your
service>
To create an endpoint service configuration, you must first create a Network Load Balancer for your service. For more information, see VPC Endpoint Services in the Amazon Virtual Private Cloud User Guide.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2264 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcEndpointServiceConfigurationResponse *>(send(request));
 }
createVpcPeeringConnection
CreateVpcPeeringConnectionResponse * QtAws::EC2::Ec2Client::createVpcPeeringConnection (const CreateVpcPeeringConnectionRequest & request) slot
Requests a VPC peering connection between two VPCs: a requester VPC that you own and an accepter VPC with which to create the connection. The accepter VPC can belong to another AWS account and can be in a different region to the requester VPC. The requester VPC and accepter VPC cannot have overlapping CIDR
blocks> <note>
Limitations and rules apply to a VPC peering connection. For more information, see the limitations section in the VPC Peering
Guide> </note>
The owner of the accepter VPC must accept the peering request to activate the peering connection. The VPC peering connection request expires after 7 days, after which it cannot be accepted or
rejected>
If you create a VPC peering connection request between VPCs with overlapping CIDR blocks, the VPC peering connection has a status of
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2296 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpcPeeringConnectionResponse *>(send(request));
 }
createVpnConnection
CreateVpnConnectionResponse * QtAws::EC2::Ec2Client::createVpnConnection (const CreateVpnConnectionRequest & request) slot
Creates a VPN connection between an existing virtual private gateway and a VPN customer gateway. The only supported connection type is
ipsec.1>
The response includes information that you need to give to your network administrator to configure your customer
gateway>
We strongly recommend that you use HTTPS when calling this operation because the response contains sensitive cryptographic information for configuring your customer
gateway>
If you decide to shut down your VPN connection for any reason and later create a new VPN connection, you must reconfigure your customer gateway with the new information returned from this
call>
This is an idempotent operation. If you perform the operation more than once, Amazon EC2 doesn't return an
error>
For more information, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2334 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpnConnectionResponse *>(send(request));
 }
createVpnConnectionRoute
CreateVpnConnectionRouteResponse * QtAws::EC2::Ec2Client::createVpnConnectionRoute (const CreateVpnConnectionRouteRequest & request) slot
Creates a static route associated with a VPN connection between an existing virtual private gateway and a VPN customer gateway. The static route allows traffic to be routed from the virtual private gateway to the VPN customer
gateway>
For more information about VPN connections, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2355 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpnConnectionRouteResponse *>(send(request));
 }
createVpnGateway
CreateVpnGatewayResponse * QtAws::EC2::Ec2Client::createVpnGateway (const CreateVpnGatewayRequest & request) slot
Creates a virtual private gateway. A virtual private gateway is the endpoint on the VPC side of your VPN connection. You can create a virtual private gateway before creating the VPC
itself>
For more information about virtual private gateways, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2376 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVpnGatewayResponse *>(send(request));
 }
deleteCustomerGateway
DeleteCustomerGatewayResponse * QtAws::EC2::Ec2Client::deleteCustomerGateway (const DeleteCustomerGatewayRequest & request) slot
Deletes the specified customer gateway. You must delete the VPN connection before you can delete the customer
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2390 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCustomerGatewayResponse *>(send(request));
 }
deleteDhcpOptions
DeleteDhcpOptionsResponse * QtAws::EC2::Ec2Client::deleteDhcpOptions (const DeleteDhcpOptionsRequest & request) slot
Deletes the specified set of DHCP options. You must disassociate the set of DHCP options before you can delete it. You can disassociate the set of DHCP options by associating either a new set of options or the default set of options with the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2406 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDhcpOptionsResponse *>(send(request));
 }
deleteEgressOnlyInternetGateway
DeleteEgressOnlyInternetGatewayResponse * QtAws::EC2::Ec2Client::deleteEgressOnlyInternetGateway (const DeleteEgressOnlyInternetGatewayRequest & request) slot
Deletes an egress-only Internet
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2420 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEgressOnlyInternetGatewayResponse *>(send(request));
 }
deleteFlowLogs
DeleteFlowLogsResponse * QtAws::EC2::Ec2Client::deleteFlowLogs (const DeleteFlowLogsRequest & request) slot
Deletes one or more flow
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2434 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFlowLogsResponse *>(send(request));
 }
deleteFpgaImage
DeleteFpgaImageResponse * QtAws::EC2::Ec2Client::deleteFpgaImage (const DeleteFpgaImageRequest & request) slot
Deletes the specified Amazon FPGA Image
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2448 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFpgaImageResponse *>(send(request));
 }
deleteInternetGateway
DeleteInternetGatewayResponse * QtAws::EC2::Ec2Client::deleteInternetGateway (const DeleteInternetGatewayRequest & request) slot
Deletes the specified Internet gateway. You must detach the Internet gateway from the VPC before you can delete
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2462 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInternetGatewayResponse *>(send(request));
 }
deleteKeyPair
DeleteKeyPairResponse * QtAws::EC2::Ec2Client::deleteKeyPair (const DeleteKeyPairRequest & request) slot
Deletes the specified key pair, by removing the public key from Amazon
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2476 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteKeyPairResponse *>(send(request));
 }
deleteLaunchTemplate
DeleteLaunchTemplateResponse * QtAws::EC2::Ec2Client::deleteLaunchTemplate (const DeleteLaunchTemplateRequest & request) slot
Deletes a launch template. Deleting a launch template deletes all of its
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2490 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLaunchTemplateResponse *>(send(request));
 }
deleteLaunchTemplateVersions
DeleteLaunchTemplateVersionsResponse * QtAws::EC2::Ec2Client::deleteLaunchTemplateVersions (const DeleteLaunchTemplateVersionsRequest & request) slot
Deletes one or more versions of a launch template. You cannot delete the default version of a launch template; you must first assign a different version as the default. If the default version is the only version for the launch template, you must delete the entire launch template using
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2506 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLaunchTemplateVersionsResponse *>(send(request));
 }
deleteNatGateway
DeleteNatGatewayResponse * QtAws::EC2::Ec2Client::deleteNatGateway (const DeleteNatGatewayRequest & request) slot
Deletes the specified NAT gateway. Deleting a NAT gateway disassociates its Elastic IP address, but does not release the address from your account. Deleting a NAT gateway does not delete any NAT gateway routes in your route
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2521 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNatGatewayResponse *>(send(request));
 }
deleteNetworkAcl
DeleteNetworkAclResponse * QtAws::EC2::Ec2Client::deleteNetworkAcl (const DeleteNetworkAclRequest & request) slot
Deletes the specified network ACL. You can't delete the ACL if it's associated with any subnets. You can't delete the default network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2536 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNetworkAclResponse *>(send(request));
 }
deleteNetworkAclEntry
DeleteNetworkAclEntryResponse * QtAws::EC2::Ec2Client::deleteNetworkAclEntry (const DeleteNetworkAclEntryRequest & request) slot
Deletes the specified ingress or egress entry (rule) from the specified network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2550 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNetworkAclEntryResponse *>(send(request));
 }
deleteNetworkInterface
DeleteNetworkInterfaceResponse * QtAws::EC2::Ec2Client::deleteNetworkInterface (const DeleteNetworkInterfaceRequest & request) slot
Deletes the specified network interface. You must detach the network interface before you can delete
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2564 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNetworkInterfaceResponse *>(send(request));
 }
deleteNetworkInterfacePermission
DeleteNetworkInterfacePermissionResponse * QtAws::EC2::Ec2Client::deleteNetworkInterfacePermission (const DeleteNetworkInterfacePermissionRequest & request) slot
Deletes a permission for a network interface. By default, you cannot delete the permission if the account for which you're removing the permission has attached the network interface to an instance. However, you can force delete the permission, regardless of any
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2580 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNetworkInterfacePermissionResponse *>(send(request));
 }
deletePlacementGroup
DeletePlacementGroupResponse * QtAws::EC2::Ec2Client::deletePlacementGroup (const DeletePlacementGroupRequest & request) slot
Deletes the specified placement group. You must terminate all instances in the placement group before you can delete the placement group. For more information, see Placement Groups in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2597 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePlacementGroupResponse *>(send(request));
 }
deleteRoute
DeleteRouteResponse * QtAws::EC2::Ec2Client::deleteRoute (const DeleteRouteRequest & request) slot
Deletes the specified route from the specified route
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2611 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRouteResponse *>(send(request));
 }
deleteRouteTable
DeleteRouteTableResponse * QtAws::EC2::Ec2Client::deleteRouteTable (const DeleteRouteTableRequest & request) slot
Deletes the specified route table. You must disassociate the route table from any subnets before you can delete it. You can't delete the main route
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2626 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRouteTableResponse *>(send(request));
 }
deleteSecurityGroup
DeleteSecurityGroupResponse * QtAws::EC2::Ec2Client::deleteSecurityGroup (const DeleteSecurityGroupRequest & request) slot
Deletes a security
group>
If you attempt to delete a security group that is associated with an instance, or is referenced by another security group, the operation fails with InvalidGroup.InUse in EC2-Classic or DependencyViolation in
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2645 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSecurityGroupResponse *>(send(request));
 }
deleteSnapshot
DeleteSnapshotResponse * QtAws::EC2::Ec2Client::deleteSnapshot (const DeleteSnapshotRequest & request) slot
Deletes the specified
snapshot>
When you make periodic snapshots of a volume, the snapshots are incremental, and only the blocks on the device that have changed since your last snapshot are saved in the new snapshot. When you delete a snapshot, only the data not needed for any other snapshot is removed. So regardless of which prior snapshots have been deleted, all active snapshots will have access to all the information needed to restore the
volume>
You cannot delete a snapshot of the root device of an EBS volume used by a registered AMI. You must first de-register the AMI before you can delete the
snapshot>
For more information, see Deleting an Amazon EBS Snapshot in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2677 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSnapshotResponse *>(send(request));
 }
deleteSpotDatafeedSubscription
DeleteSpotDatafeedSubscriptionResponse * QtAws::EC2::Ec2Client::deleteSpotDatafeedSubscription (const DeleteSpotDatafeedSubscriptionRequest & request) slot
Deletes the data feed for Spot
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2691 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSpotDatafeedSubscriptionResponse *>(send(request));
 }
deleteSubnet
DeleteSubnetResponse * QtAws::EC2::Ec2Client::deleteSubnet (const DeleteSubnetRequest & request) slot
Deletes the specified subnet. You must terminate all running instances in the subnet before you can delete the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2705 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSubnetResponse *>(send(request));
 }
deleteTags
DeleteTagsResponse * QtAws::EC2::Ec2Client::deleteTags (const DeleteTagsRequest & request) slot
Deletes the specified set of tags from the specified set of
resources>
To list the current tags, use DescribeTags. For more information about tags, see Tagging Your Resources in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2725 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsResponse *>(send(request));
 }
deleteVolume
DeleteVolumeResponse * QtAws::EC2::Ec2Client::deleteVolume (const DeleteVolumeRequest & request) slot
Deletes the specified EBS volume. The volume must be in the available state (not attached to an
instance)> <note>
The volume may remain in the deleting state for several
minutes> </note>
For more information, see Deleting an Amazon EBS Volume in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2748 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVolumeResponse *>(send(request));
 }
deleteVpc
DeleteVpcResponse * QtAws::EC2::Ec2Client::deleteVpc (const DeleteVpcRequest & request) slot
Deletes the specified VPC. You must detach or delete all gateways and resources that are associated with the VPC before you can delete it. For example, you must terminate all instances running in the VPC, delete all security groups associated with the VPC (except the default one), delete all route tables associated with the VPC (except the default one), and so
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2765 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcResponse *>(send(request));
 }
deleteVpcEndpointConnectionNotifications
DeleteVpcEndpointConnectionNotificationsResponse * QtAws::EC2::Ec2Client::deleteVpcEndpointConnectionNotifications (const DeleteVpcEndpointConnectionNotificationsRequest & request) slot
Deletes one or more VPC endpoint connection
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2779 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcEndpointConnectionNotificationsResponse *>(send(request));
 }
deleteVpcEndpoints
DeleteVpcEndpointsResponse * QtAws::EC2::Ec2Client::deleteVpcEndpoints (const DeleteVpcEndpointsRequest & request) slot
Deletes one or more specified VPC endpoints. Deleting a gateway endpoint also deletes the endpoint routes in the route tables that were associated with the endpoint. Deleting an interface endpoint deletes the endpoint network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2810 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcEndpointsResponse *>(send(request));
 }
deleteVpcEndpointServiceConfigurations
DeleteVpcEndpointServiceConfigurationsResponse * QtAws::EC2::Ec2Client::deleteVpcEndpointServiceConfigurations (const DeleteVpcEndpointServiceConfigurationsRequest & request) slot
Deletes one or more VPC endpoint service configurations in your account. Before you delete the endpoint service configuration, you must reject any Available or PendingAcceptance interface endpoint connections that are attached to the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2795 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcEndpointServiceConfigurationsResponse *>(send(request));
 }
deleteVpcPeeringConnection
DeleteVpcPeeringConnectionResponse * QtAws::EC2::Ec2Client::deleteVpcPeeringConnection (const DeleteVpcPeeringConnectionRequest & request) slot
Deletes a VPC peering connection. Either the owner of the requester VPC or the owner of the accepter VPC can delete the VPC peering connection if it's in the active state. The owner of the requester VPC can delete a VPC peering connection in the pending-acceptance state. You cannot delete a VPC peering connection that's in the failed
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2827 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpcPeeringConnectionResponse *>(send(request));
 }
deleteVpnConnection
DeleteVpnConnectionResponse * QtAws::EC2::Ec2Client::deleteVpnConnection (const DeleteVpnConnectionRequest & request) slot
Deletes the specified VPN
connection>
If you're deleting the VPC and its associated components, we recommend that you detach the virtual private gateway from the VPC and delete the VPC before deleting the VPN connection. If you believe that the tunnel credentials for your VPN connection have been compromised, you can delete the VPN connection and create a new one that has new keys, without needing to delete the VPC or virtual private gateway. If you create a new VPN connection, you must reconfigure the customer gateway using the new configuration information returned with the new VPN connection
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2849 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpnConnectionResponse *>(send(request));
 }
deleteVpnConnectionRoute
DeleteVpnConnectionRouteResponse * QtAws::EC2::Ec2Client::deleteVpnConnectionRoute (const DeleteVpnConnectionRouteRequest & request) slot
Deletes the specified static route associated with a VPN connection between an existing virtual private gateway and a VPN customer gateway. The static route allows traffic to be routed from the virtual private gateway to the VPN customer
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2864 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpnConnectionRouteResponse *>(send(request));
 }
deleteVpnGateway
DeleteVpnGatewayResponse * QtAws::EC2::Ec2Client::deleteVpnGateway (const DeleteVpnGatewayRequest & request) slot
Deletes the specified virtual private gateway. We recommend that before you delete a virtual private gateway, you detach it from the VPC and delete the VPN connection. Note that you don't need to delete the virtual private gateway if you plan to delete and recreate the VPN connection between your VPC and your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2880 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVpnGatewayResponse *>(send(request));
 }
deregisterImage
DeregisterImageResponse * QtAws::EC2::Ec2Client::deregisterImage (const DeregisterImageRequest & request) slot
Deregisters the specified AMI. After you deregister an AMI, it can't be used to launch new instances; however, it doesn't affect any instances that you've already launched from the AMI. You'll continue to incur usage costs for those instances until you terminate
them>
When you deregister an Amazon EBS-backed AMI, it doesn't affect the snapshot that was created for the root volume of the instance during the AMI creation process. When you deregister an instance store-backed AMI, it doesn't affect the files that you uploaded to Amazon S3 when you created the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2902 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterImageResponse *>(send(request));
 }
describeAccountAttributes
DescribeAccountAttributesResponse * QtAws::EC2::Ec2Client::describeAccountAttributes (const DescribeAccountAttributesRequest & request) slot
Describes attributes of your AWS account. The following are the supported account
attributes>
supported-platforms: Indicates whether your account can launch instances into EC2-Classic and EC2-VPC, or only into
EC2-VPC>
default-vpc: The ID of the default VPC for your account, or
none>
max-instances: The maximum number of On-Demand Instances that you can
run>
vpc-max-security-groups-per-interface: The maximum number of security groups that you can assign to a network
interface>
max-elastic-ips: The maximum number of Elastic IP addresses that you can allocate for use with EC2-Classic.
</p
vpc-max-elastic-ips: The maximum number of Elastic IP addresses that you can allocate for use with
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2942 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountAttributesResponse *>(send(request));
 }
describeAddresses
DescribeAddressesResponse * QtAws::EC2::Ec2Client::describeAddresses (const DescribeAddressesRequest & request) slot
Describes one or more of your Elastic IP
addresses>
An Elastic IP address is for use in either the EC2-Classic platform or in a VPC. For more information, see Elastic IP Addresses in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2962 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAddressesResponse *>(send(request));
 }
describeAggregateIdFormat
DescribeAggregateIdFormatResponse * QtAws::EC2::Ec2Client::describeAggregateIdFormat (const DescribeAggregateIdFormatRequest & request) slot
Describes the longer ID format settings for all resource types in a specific region. This request is useful for performing a quick audit to determine whether a specific region is fully opted in for longer IDs (17-character
IDs)>
This request only returns information about resource types that support longer
IDs>
The following resource types support longer IDs: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | instance | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | reservation | route-table | route-table-association | security-group | snapshot | subnet | subnet-cidr-block-association | volume | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection |
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2993 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAggregateIdFormatResponse *>(send(request));
 }
describeAvailabilityZones
DescribeAvailabilityZonesResponse * QtAws::EC2::Ec2Client::describeAvailabilityZones (const DescribeAvailabilityZonesRequest & request) slot
Describes one or more of the Availability Zones that are available to you. The results include zones only for the region you're currently using. If there is an event impacting an Availability Zone, you can use this request to view the state and any provided message for that Availability
Zone>
For more information, see Regions and Availability Zones in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3015 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAvailabilityZonesResponse *>(send(request));
 }
describeBundleTasks
DescribeBundleTasksResponse * QtAws::EC2::Ec2Client::describeBundleTasks (const DescribeBundleTasksRequest & request) slot
Describes one or more of your bundling
tasks> <note>
Completed bundle tasks are listed for only a limited time. If your bundle task is no longer in the list, you can still register an AMI from it. Just use RegisterImage with the Amazon S3 bucket name and image manifest name you provided to the bundle
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3035 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBundleTasksResponse *>(send(request));
 }
describeClassicLinkInstances
DescribeClassicLinkInstancesResponse * QtAws::EC2::Ec2Client::describeClassicLinkInstances (const DescribeClassicLinkInstancesRequest & request) slot
Describes one or more of your linked EC2-Classic instances. This request only returns information about EC2-Classic instances linked to a VPC through ClassicLink; you cannot use this request to return information about other
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3050 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeClassicLinkInstancesResponse *>(send(request));
 }
describeConversionTasks
DescribeConversionTasksResponse * QtAws::EC2::Ec2Client::describeConversionTasks (const DescribeConversionTasksRequest & request) slot
Describes one or more of your conversion tasks. For more information, see the VM Import/Export User Guide>
For information about the import manifest referenced by this API action, see VM Import request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 3070 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConversionTasksResponse *>(send(request));
 }
describeCustomerGateways
DescribeCustomerGatewaysResponse * QtAws::EC2::Ec2Client::describeCustomerGateways (const DescribeCustomerGatewaysRequest & request) slot
Describes one or more of your VPN customer
gateways>
For more information about VPN customer gateways, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3090 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCustomerGatewaysResponse *>(send(request));
 }
describeDhcpOptions
DescribeDhcpOptionsResponse * QtAws::EC2::Ec2Client::describeDhcpOptions (const DescribeDhcpOptionsRequest & request) slot
Describes one or more of your DHCP options
sets>
For more information about DHCP options sets, see DHCP Options Sets in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3110 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDhcpOptionsResponse *>(send(request));
 }
describeEgressOnlyInternetGateways
DescribeEgressOnlyInternetGatewaysResponse * QtAws::EC2::Ec2Client::describeEgressOnlyInternetGateways (const DescribeEgressOnlyInternetGatewaysRequest & request) slot
Describes one or more of your egress-only Internet
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3124 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEgressOnlyInternetGatewaysResponse *>(send(request));
 }
describeElasticGpus
DescribeElasticGpusResponse * QtAws::EC2::Ec2Client::describeElasticGpus (const DescribeElasticGpusRequest & request) slot
Describes the Elastic GPUs associated with your instances. For more information about Elastic GPUs, see Amazon EC2 Elastic request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 3139 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticGpusResponse *>(send(request));
 }
describeExportTasks
DescribeExportTasksResponse * QtAws::EC2::Ec2Client::describeExportTasks (const DescribeExportTasksRequest & request) slot
Describes one or more of your export
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3153 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeExportTasksResponse *>(send(request));
 }
describeFlowLogs
DescribeFlowLogsResponse * QtAws::EC2::Ec2Client::describeFlowLogs (const DescribeFlowLogsRequest & request) slot
Describes one or more flow logs. To view the information in your flow logs (the log streams for the network interfaces), you must use the CloudWatch Logs console or the CloudWatch Logs
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3168 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFlowLogsResponse *>(send(request));
 }
describeFpgaImageAttribute
DescribeFpgaImageAttributeResponse * QtAws::EC2::Ec2Client::describeFpgaImageAttribute (const DescribeFpgaImageAttributeRequest & request) slot
Describes the specified attribute of the specified Amazon FPGA Image
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3182 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFpgaImageAttributeResponse *>(send(request));
 }
describeFpgaImages
DescribeFpgaImagesResponse * QtAws::EC2::Ec2Client::describeFpgaImages (const DescribeFpgaImagesRequest & request) slot
Describes one or more available Amazon FPGA Images (AFIs). These include public AFIs, private AFIs that you own, and AFIs owned by other AWS accounts for which you have load
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3197 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFpgaImagesResponse *>(send(request));
 }
describeHostReservationOfferings
DescribeHostReservationOfferingsResponse * QtAws::EC2::Ec2Client::describeHostReservationOfferings (const DescribeHostReservationOfferingsRequest & request) slot
Describes the Dedicated Host Reservations that are available to
purchase>
The results describe all the Dedicated Host Reservation offerings, including offerings that may not match the instance family and region of your Dedicated Hosts. When purchasing an offering, ensure that the the instance family and region of the offering matches that of the Dedicated Host/s it will be associated with. For an overview of supported instance types, see Dedicated Hosts Overview in the Amazon Elastic Compute Cloud User Guide.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3219 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHostReservationOfferingsResponse *>(send(request));
 }
describeHostReservations
DescribeHostReservationsResponse * QtAws::EC2::Ec2Client::describeHostReservations (const DescribeHostReservationsRequest & request) slot
Describes Dedicated Host Reservations which are associated with Dedicated Hosts in your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3233 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHostReservationsResponse *>(send(request));
 }
describeHosts
DescribeHostsResponse * QtAws::EC2::Ec2Client::describeHosts (const DescribeHostsRequest & request) slot
Describes one or more of your Dedicated
Hosts>
The results describe only the Dedicated Hosts in the region you're currently using. All listed instances consume capacity on your Dedicated Host. Dedicated Hosts that have recently been released will be listed with the state
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3252 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHostsResponse *>(send(request));
 }
describeIamInstanceProfileAssociations
DescribeIamInstanceProfileAssociationsResponse * QtAws::EC2::Ec2Client::describeIamInstanceProfileAssociations (const DescribeIamInstanceProfileAssociationsRequest & request) slot
Describes your IAM instance profile
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3266 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIamInstanceProfileAssociationsResponse *>(send(request));
 }
describeIdentityIdFormat
DescribeIdentityIdFormatResponse * QtAws::EC2::Ec2Client::describeIdentityIdFormat (const DescribeIdentityIdFormatRequest & request) slot
Describes the ID format settings for resources for the specified IAM user, IAM role, or root user. For example, you can view the resource types that are enabled for longer IDs. This request only returns information about resource types whose ID formats can be modified; it does not return information about other resource types. For more information, see Resource IDs in the Amazon Elastic Compute Cloud User Guide.
</p
The following resource types support longer IDs: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | instance | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | reservation | route-table | route-table-association | security-group | snapshot | subnet | subnet-cidr-block-association | volume | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection | vpn-gateway.
</p
These settings apply to the principal specified in the request. They do not apply to the principal that makes the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3335 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIdentityIdFormatResponse *>(send(request));
 }
describeIdFormat
DescribeIdFormatResponse * QtAws::EC2::Ec2Client::describeIdFormat (const DescribeIdFormatRequest & request) slot
Describes the ID format settings for your resources on a per-region basis, for example, to view which resource types are enabled for longer IDs. This request only returns information about resource types whose ID formats can be modified; it does not return information about other resource
types>
The following resource types support longer IDs: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | instance | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | reservation | route-table | route-table-association | security-group | snapshot | subnet | subnet-cidr-block-association | volume | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection | vpn-gateway.
</p
These settings apply to the IAM user who makes the request; they do not apply to the entire AWS account. By default, an IAM user defaults to the same settings as the root user, unless they explicitly override the settings by running the ModifyIdFormat command. Resources created with longer IDs are visible to all IAM users, regardless of these settings and provided that they have permission to use the relevant Describe command for the resource
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3301 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIdFormatResponse *>(send(request));
 }
describeImageAttribute
DescribeImageAttributeResponse * QtAws::EC2::Ec2Client::describeImageAttribute (const DescribeImageAttributeRequest & request) slot
Describes the specified attribute of the specified AMI. You can specify only one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3349 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImageAttributeResponse *>(send(request));
 }
describeImages
DescribeImagesResponse * QtAws::EC2::Ec2Client::describeImages (const DescribeImagesRequest & request) slot
Describes one or more of the images (AMIs, AKIs, and ARIs) available to you. Images available to you include public images, private images that you own, and private images owned by other AWS accounts but for which you have explicit launch
permissions> <note>
Deregistered images are included in the returned results for an unspecified interval after
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3369 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImagesResponse *>(send(request));
 }
describeImportImageTasks
DescribeImportImageTasksResponse * QtAws::EC2::Ec2Client::describeImportImageTasks (const DescribeImportImageTasksRequest & request) slot
Displays details about an import virtual machine or import snapshot tasks that are already
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3383 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImportImageTasksResponse *>(send(request));
 }
describeImportSnapshotTasks
DescribeImportSnapshotTasksResponse * QtAws::EC2::Ec2Client::describeImportSnapshotTasks (const DescribeImportSnapshotTasksRequest & request) slot
Describes your import snapshot
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3397 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeImportSnapshotTasksResponse *>(send(request));
 }
describeInstanceAttribute
DescribeInstanceAttributeResponse * QtAws::EC2::Ec2Client::describeInstanceAttribute (const DescribeInstanceAttributeRequest & request) slot
Describes the specified attribute of the specified instance. You can specify only one attribute at a time. Valid attribute values are: instanceType | kernel | ramdisk | userData | disableApiTermination | instanceInitiatedShutdownBehavior | rootDeviceName | blockDeviceMapping | productCodes | sourceDestCheck | groupSet | ebsOptimized | sriovNetSupport
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3415 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstanceAttributeResponse *>(send(request));
 }
describeInstanceCreditSpecifications
DescribeInstanceCreditSpecificationsResponse * QtAws::EC2::Ec2Client::describeInstanceCreditSpecifications (const DescribeInstanceCreditSpecificationsRequest & request) slot
Describes the credit option for CPU usage of one or more of your T2 instances. The credit options are standard and
unlimited>
If you do not specify an instance ID, Amazon EC2 returns only the T2 instances with the unlimited credit option. If you specify one or more instance IDs, Amazon EC2 returns the credit option (standard or unlimited) of those instances. If you specify an instance ID that is not valid, such as an instance that is not a T2 instance, an error is
returned>
Recently terminated instances might appear in the returned results. This interval is usually less than one
hour>
If an Availability Zone is experiencing a service disruption and you specify instance IDs in the affected zone, or do not specify any instance IDs at all, the call fails. If you specify only instance IDs in an unaffected zone, the call works
normally>
For more information, see T2 Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3452 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstanceCreditSpecificationsResponse *>(send(request));
 }
describeInstances
DescribeInstancesResponse * QtAws::EC2::Ec2Client::describeInstances (const DescribeInstancesRequest & request) slot
Describes one or more of your
instances>
If you specify one or more instance IDs, Amazon EC2 returns information for those instances. If you do not specify instance IDs, Amazon EC2 returns information for all relevant instances. If you specify an instance ID that is not valid, an error is returned. If you specify an instance that you do not own, it is not included in the returned
results>
Recently terminated instances might appear in the returned results. This interval is usually less than one
hour>
If you describe instances in the rare case where an Availability Zone is experiencing a service disruption and you specify instance IDs that are in the affected zone, or do not specify any instance IDs at all, the call fails. If you describe instances and specify only instance IDs that are in an unaffected zone, the call works
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3523 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstancesResponse *>(send(request));
 }
describeInstanceStatus
DescribeInstanceStatusResponse * QtAws::EC2::Ec2Client::describeInstanceStatus (const DescribeInstanceStatusRequest & request) slot
Describes the status of one or more instances. By default, only running instances are described, unless you specifically indicate to return the status of all
instances>
Instance status includes the following
components>
Status checks - Amazon EC2 performs status checks on running EC2 instances to identify hardware and software issues. For more information, see Status Checks for Your Instances and Troubleshooting Instances with Failed Status Checks in the Amazon Elastic Compute Cloud User
Guide>
Scheduled events - Amazon EC2 can schedule events (such as reboot, stop, or terminate) for your instances related to hardware issues, software updates, or system maintenance. For more information, see Scheduled Events for Your Instances in the Amazon Elastic Compute Cloud User
Guide>
Instance state - You can manage your instances from the moment you launch them through their termination. For more information, see Instance Lifecycle in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3493 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstanceStatusResponse *>(send(request));
 }
describeInternetGateways
DescribeInternetGatewaysResponse * QtAws::EC2::Ec2Client::describeInternetGateways (const DescribeInternetGatewaysRequest & request) slot
Describes one or more of your Internet
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3537 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInternetGatewaysResponse *>(send(request));
 }
describeKeyPairs
DescribeKeyPairsResponse * QtAws::EC2::Ec2Client::describeKeyPairs (const DescribeKeyPairsRequest & request) slot
Describes one or more of your key
pairs>
For more information about key pairs, see Key Pairs in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3557 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeKeyPairsResponse *>(send(request));
 }
describeLaunchTemplates
DescribeLaunchTemplatesResponse * QtAws::EC2::Ec2Client::describeLaunchTemplates (const DescribeLaunchTemplatesRequest & request) slot
Describes one or more launch
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3586 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLaunchTemplatesResponse *>(send(request));
 }
describeLaunchTemplateVersions
DescribeLaunchTemplateVersionsResponse * QtAws::EC2::Ec2Client::describeLaunchTemplateVersions (const DescribeLaunchTemplateVersionsRequest & request) slot
Describes one or more versions of a specified launch template. You can describe all versions, individual versions, or a range of
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3572 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLaunchTemplateVersionsResponse *>(send(request));
 }
describeMovingAddresses
DescribeMovingAddressesResponse * QtAws::EC2::Ec2Client::describeMovingAddresses (const DescribeMovingAddressesRequest & request) slot
Describes your Elastic IP addresses that are being moved to the EC2-VPC platform, or that are being restored to the EC2-Classic platform. This request does not return information about any other Elastic IP addresses in your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3601 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMovingAddressesResponse *>(send(request));
 }
describeNatGateways
DescribeNatGatewaysResponse * QtAws::EC2::Ec2Client::describeNatGateways (const DescribeNatGatewaysRequest & request) slot
Describes one or more of the your NAT
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3615 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNatGatewaysResponse *>(send(request));
 }
describeNetworkAcls
DescribeNetworkAclsResponse * QtAws::EC2::Ec2Client::describeNetworkAcls (const DescribeNetworkAclsRequest & request) slot
Describes one or more of your network
ACLs>
For more information about network ACLs, see Network ACLs in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3635 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNetworkAclsResponse *>(send(request));
 }
describeNetworkInterfaceAttribute
DescribeNetworkInterfaceAttributeResponse * QtAws::EC2::Ec2Client::describeNetworkInterfaceAttribute (const DescribeNetworkInterfaceAttributeRequest & request) slot
Describes a network interface attribute. You can specify only one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3649 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNetworkInterfaceAttributeResponse *>(send(request));
 }
describeNetworkInterfacePermissions
DescribeNetworkInterfacePermissionsResponse * QtAws::EC2::Ec2Client::describeNetworkInterfacePermissions (const DescribeNetworkInterfacePermissionsRequest & request) slot
Describes the permissions for your network interfaces.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3663 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNetworkInterfacePermissionsResponse *>(send(request));
 }
describeNetworkInterfaces
DescribeNetworkInterfacesResponse * QtAws::EC2::Ec2Client::describeNetworkInterfaces (const DescribeNetworkInterfacesRequest & request) slot
Describes one or more of your network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3677 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNetworkInterfacesResponse *>(send(request));
 }
describePlacementGroups
DescribePlacementGroupsResponse * QtAws::EC2::Ec2Client::describePlacementGroups (const DescribePlacementGroupsRequest & request) slot
Describes one or more of your placement groups. For more information, see Placement Groups in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3693 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePlacementGroupsResponse *>(send(request));
 }
describePrefixLists
DescribePrefixListsResponse * QtAws::EC2::Ec2Client::describePrefixLists (const DescribePrefixListsRequest & request) slot
Describes available AWS services in a prefix list format, which includes the prefix list name and prefix list ID of the service and the IP address range for the service. A prefix list ID is required for creating an outbound security group rule that allows traffic from a VPC to access an AWS service through a gateway VPC
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3709 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePrefixListsResponse *>(send(request));
 }
describePrincipalIdFormat
DescribePrincipalIdFormatResponse * QtAws::EC2::Ec2Client::describePrincipalIdFormat (const DescribePrincipalIdFormatRequest & request) slot
Describes the ID format settings for the root user and all IAM roles and IAM users that have explicitly specified a longer ID (17-character ID) preference.
</p
By default, all IAM roles and IAM users default to the same ID settings as the root user, unless they explicitly override the settings. This request is useful for identifying those IAM users and IAM roles that have overridden the default ID
settings>
The following resource types support longer IDs: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | instance | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | reservation | route-table | route-table-association | security-group | snapshot | subnet | subnet-cidr-block-association | volume | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection | vpn-gateway.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3742 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePrincipalIdFormatResponse *>(send(request));
 }
describeRegions
DescribeRegionsResponse * QtAws::EC2::Ec2Client::describeRegions (const DescribeRegionsRequest & request) slot
Describes one or more regions that are currently available to
you>
For a list of the regions supported by Amazon EC2, see Regions and request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 3761 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRegionsResponse *>(send(request));
 }
describeReservedInstances
DescribeReservedInstancesResponse * QtAws::EC2::Ec2Client::describeReservedInstances (const DescribeReservedInstancesRequest & request) slot
Describes one or more of the Reserved Instances that you
purchased>
For more information about Reserved Instances, see Reserved Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3781 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedInstancesResponse *>(send(request));
 }
describeReservedInstancesListings
DescribeReservedInstancesListingsResponse * QtAws::EC2::Ec2Client::describeReservedInstancesListings (const DescribeReservedInstancesListingsRequest & request) slot
Describes your account's Reserved Instance listings in the Reserved Instance
Marketplace>
The Reserved Instance Marketplace matches sellers who want to resell Reserved Instance capacity that they no longer need with buyers who want to purchase additional capacity. Reserved Instances bought and sold through the Reserved Instance Marketplace work like any other Reserved
Instances>
As a seller, you choose to list some or all of your Reserved Instances, and you specify the upfront price to receive for them. Your Reserved Instances are then listed in the Reserved Instance Marketplace and are available for
purchase>
As a buyer, you specify the configuration of the Reserved Instance to purchase, and the Marketplace matches what you're searching for with what's available. The Marketplace first sells the lowest priced Reserved Instances to you, and continues to sell available Reserved Instance listings to you until your demand is met. You are charged based on the total price of all of the listings that you
purchase>
For more information, see Reserved Instance Marketplace in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3818 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedInstancesListingsResponse *>(send(request));
 }
describeReservedInstancesModifications
DescribeReservedInstancesModificationsResponse * QtAws::EC2::Ec2Client::describeReservedInstancesModifications (const DescribeReservedInstancesModificationsRequest & request) slot
Describes the modifications made to your Reserved Instances. If no parameter is specified, information about all your Reserved Instances modification requests is returned. If a modification ID is specified, only information about the specific modification is
returned>
For more information, see Modifying Reserved Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3839 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedInstancesModificationsResponse *>(send(request));
 }
describeReservedInstancesOfferings
DescribeReservedInstancesOfferingsResponse * QtAws::EC2::Ec2Client::describeReservedInstancesOfferings (const DescribeReservedInstancesOfferingsRequest & request) slot
Describes Reserved Instance offerings that are available for purchase. With Reserved Instances, you purchase the right to launch instances for a period of time. During that time period, you do not receive insufficient capacity errors, and you pay a lower usage rate than the rate charged for On-Demand instances for the actual time
used>
If you have listed your own Reserved Instances for sale in the Reserved Instance Marketplace, they will be excluded from these results. This is to ensure that you do not purchase your own Reserved
Instances>
For more information, see Reserved Instance Marketplace in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3865 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReservedInstancesOfferingsResponse *>(send(request));
 }
describeRouteTables
DescribeRouteTablesResponse * QtAws::EC2::Ec2Client::describeRouteTables (const DescribeRouteTablesRequest & request) slot
Describes one or more of your route
tables>
Each subnet in your VPC must be associated with a route table. If a subnet is not explicitly associated with any route table, it is implicitly associated with the main route table. This command does not return the subnet ID for implicit
associations>
For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3890 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRouteTablesResponse *>(send(request));
 }
describeScheduledInstanceAvailability
DescribeScheduledInstanceAvailabilityResponse * QtAws::EC2::Ec2Client::describeScheduledInstanceAvailability (const DescribeScheduledInstanceAvailabilityRequest & request) slot
Finds available schedules that meet the specified
criteria>
You can search for an available schedule no more than 3 months in advance. You must meet the minimum required duration of 1,200 hours per year. For example, the minimum daily schedule is 4 hours, the minimum weekly schedule is 24 hours, and the minimum monthly schedule is 100
hours>
After you find a schedule that meets your needs, call PurchaseScheduledInstances to purchase Scheduled Instances with that
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3915 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScheduledInstanceAvailabilityResponse *>(send(request));
 }
describeScheduledInstances
DescribeScheduledInstancesResponse * QtAws::EC2::Ec2Client::describeScheduledInstances (const DescribeScheduledInstancesRequest & request) slot
Describes one or more of your Scheduled
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3929 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScheduledInstancesResponse *>(send(request));
 }
describeSecurityGroupReferences
DescribeSecurityGroupReferencesResponse * QtAws::EC2::Ec2Client::describeSecurityGroupReferences (const DescribeSecurityGroupReferencesRequest & request) slot
[EC2-VPC only] Describes the VPCs on the other side of a VPC peering connection that are referencing the security groups you've specified in this
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3944 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSecurityGroupReferencesResponse *>(send(request));
 }
describeSecurityGroups
DescribeSecurityGroupsResponse * QtAws::EC2::Ec2Client::describeSecurityGroups (const DescribeSecurityGroupsRequest & request) slot
Describes one or more of your security
groups>
A security group is for use with instances either in the EC2-Classic platform or in a specific VPC. For more information, see Amazon EC2 Security Groups in the Amazon Elastic Compute Cloud User Guide and Security Groups for Your VPC in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3966 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSecurityGroupsResponse *>(send(request));
 }
describeSnapshotAttribute
DescribeSnapshotAttributeResponse * QtAws::EC2::Ec2Client::describeSnapshotAttribute (const DescribeSnapshotAttributeRequest & request) slot
Describes the specified attribute of the specified snapshot. You can specify only one attribute at a
time>
For more information about EBS snapshots, see Amazon EBS Snapshots in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3986 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSnapshotAttributeResponse *>(send(request));
 }
describeSnapshots
DescribeSnapshotsResponse * QtAws::EC2::Ec2Client::describeSnapshots (const DescribeSnapshotsRequest & request) slot
Describes one or more of the EBS snapshots available to you. Available snapshots include public snapshots available for any AWS account to launch, private snapshots that you own, and private snapshots owned by another AWS account but for which you've been given explicit create volume
permissions>
The create volume permissions fall into the following
categories>
public: The owner of the snapshot granted create volume permissions for the snapshot to the all group. All AWS accounts have create volume permissions for these
snapshots>
explicit: The owner of the snapshot granted create volume permissions to a specific AWS
account>
implicit: An AWS account has implicit create volume permissions for all snapshots it
owns>
The list of snapshots returned can be modified by specifying snapshot IDs, snapshot owners, or AWS accounts with create volume permissions. If no options are specified, Amazon EC2 returns all snapshots for which you have create volume
permissions>
If you specify one or more snapshot IDs, only snapshots that have the specified IDs are returned. If you specify an invalid snapshot ID, an error is returned. If you specify a snapshot ID for which you do not have access, it is not included in the returned
results>
If you specify one or more snapshot owners using the OwnerIds option, only snapshots from the specified owners and for which you have access are returned. The results can include the AWS account IDs of the specified owners, amazon for snapshots owned by Amazon, or self for snapshots that you
own>
If you specify a list of restorable users, only snapshots with create snapshot permissions for those users are returned. You can specify AWS account IDs (if you own the snapshots), self for snapshots for which you own or have explicit permissions, or all for public
snapshots>
If you are describing a long list of snapshots, you can paginate the output to make the list more manageable. The MaxResults parameter sets the maximum number of results returned in a single page. If the list of results exceeds your MaxResults value, then that number of results is returned along with a NextToken value that can be passed to a subsequent DescribeSnapshots request to retrieve the remaining
results>
For more information about EBS snapshots, see Amazon EBS Snapshots in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4055 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSnapshotsResponse *>(send(request));
 }
describeSpotDatafeedSubscription
DescribeSpotDatafeedSubscriptionResponse * QtAws::EC2::Ec2Client::describeSpotDatafeedSubscription (const DescribeSpotDatafeedSubscriptionRequest & request) slot
Describes the data feed for Spot Instances. For more information, see Spot Instance Data Feed in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4071 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotDatafeedSubscriptionResponse *>(send(request));
 }
describeSpotFleetInstances
DescribeSpotFleetInstancesResponse * QtAws::EC2::Ec2Client::describeSpotFleetInstances (const DescribeSpotFleetInstancesRequest & request) slot
Describes the running instances for the specified Spot
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4085 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotFleetInstancesResponse *>(send(request));
 }
describeSpotFleetRequestHistory
DescribeSpotFleetRequestHistoryResponse * QtAws::EC2::Ec2Client::describeSpotFleetRequestHistory (const DescribeSpotFleetRequestHistoryRequest & request) slot
Describes the events for the specified Spot Fleet request during the specified
time>
Spot Fleet events are delayed by up to 30 seconds before they can be described. This ensures that you can query by the last evaluated time and not miss a recorded
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4104 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotFleetRequestHistoryResponse *>(send(request));
 }
describeSpotFleetRequests
DescribeSpotFleetRequestsResponse * QtAws::EC2::Ec2Client::describeSpotFleetRequests (const DescribeSpotFleetRequestsRequest & request) slot
Describes your Spot Fleet
requests>
Spot Fleet requests are deleted 48 hours after they are canceled and their instances are
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4122 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotFleetRequestsResponse *>(send(request));
 }
describeSpotInstanceRequests
DescribeSpotInstanceRequestsResponse * QtAws::EC2::Ec2Client::describeSpotInstanceRequests (const DescribeSpotInstanceRequestsRequest & request) slot
Describes the Spot Instance requests that belong to your account. Spot Instances are instances that Amazon EC2 launches when the Spot price that you specify exceeds the current Spot price. For more information, see Spot Instance Requests in the Amazon Elastic Compute Cloud User
Guide>
You can use DescribeSpotInstanceRequests to find a running Spot Instance by examining the response. If the status of the Spot Instance is fulfilled, the instance ID appears in the response and contains the identifier of the instance. Alternatively, you can use DescribeInstances with a filter to look for instances where the instance lifecycle is
spot>
Spot Instance requests are deleted 4 hours after they are canceled and their instances are
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4150 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotInstanceRequestsResponse *>(send(request));
 }
describeSpotPriceHistory
DescribeSpotPriceHistoryResponse * QtAws::EC2::Ec2Client::describeSpotPriceHistory (const DescribeSpotPriceHistoryRequest & request) slot
Describes the Spot price history. For more information, see Spot Instance Pricing History in the Amazon Elastic Compute Cloud User
Guide>
When you specify a start and end time, this operation returns the prices of the instance types within the time range that you specified and the time when the price changed. The price is valid within the time period that you specified; the response merely indicates the last time that the price
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4172 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSpotPriceHistoryResponse *>(send(request));
 }
describeStaleSecurityGroups
DescribeStaleSecurityGroupsResponse * QtAws::EC2::Ec2Client::describeStaleSecurityGroups (const DescribeStaleSecurityGroupsRequest & request) slot
[EC2-VPC only] Describes the stale security group rules for security groups in a specified VPC. Rules are stale when they reference a deleted security group in a peer VPC, or a security group in a peer VPC for which the VPC peering connection has been
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4188 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStaleSecurityGroupsResponse *>(send(request));
 }
describeSubnets
DescribeSubnetsResponse * QtAws::EC2::Ec2Client::describeSubnets (const DescribeSubnetsRequest & request) slot
Describes one or more of your
subnets>
For more information about subnets, see Your VPC and Subnets in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4208 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSubnetsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::EC2::Ec2Client::describeTags (const DescribeTagsRequest & request) slot
Describes one or more of the tags for your EC2
resources>
For more information about tags, see Tagging Your Resources in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4228 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
describeVolumeAttribute
DescribeVolumeAttributeResponse * QtAws::EC2::Ec2Client::describeVolumeAttribute (const DescribeVolumeAttributeRequest & request) slot
Describes the specified attribute of the specified volume. You can specify only one attribute at a
time>
For more information about EBS volumes, see Amazon EBS Volumes in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4248 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVolumeAttributeResponse *>(send(request));
 }
describeVolumes
DescribeVolumesResponse * QtAws::EC2::Ec2Client::describeVolumes (const DescribeVolumesRequest & request) slot
Describes the specified EBS
volumes>
If you are describing a long list of volumes, you can paginate the output to make the list more manageable. The MaxResults parameter sets the maximum number of results returned in a single page. If the list of results exceeds your MaxResults value, then that number of results is returned along with a NextToken value that can be passed to a subsequent DescribeVolumes request to retrieve the remaining
results>
For more information about EBS volumes, see Amazon EBS Volumes in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4325 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVolumesResponse *>(send(request));
 }
describeVolumesModifications
DescribeVolumesModificationsResponse * QtAws::EC2::Ec2Client::describeVolumesModifications (const DescribeVolumesModificationsRequest & request) slot
Reports the current modification status of EBS
volumes>
Current-generation EBS volumes support modification of attributes including type, size, and (for io1 volumes) IOPS provisioning while either attached to or detached from an instance. Following an action from the API or the console to modify a volume, the status of the modification may be modifying, optimizing, completed, or failed. If a volume has never been modified, then certain elements of the returned VolumeModification objects are null.
</p
You can also use CloudWatch Events to check the status of a modification to an EBS volume. For information about CloudWatch Events, see the Amazon CloudWatch Events User Guide. For more information, see Monitoring Volume Modifications".
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4355 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVolumesModificationsResponse *>(send(request));
 }
describeVolumeStatus
DescribeVolumeStatusResponse * QtAws::EC2::Ec2Client::describeVolumeStatus (const DescribeVolumeStatusRequest & request) slot
Describes the status of the specified volumes. Volume status provides the result of the checks performed on your volumes to determine events that can impair the performance of your volumes. The performance of a volume can be affected if an issue occurs on the volume's underlying host. If the volume's underlying host experiences a power outage or system issue, after the system is restored, there could be data inconsistencies on the volume. Volume events notify you if this occurs. Volume actions notify you if any action needs to be taken in response to the
event>
The DescribeVolumeStatus operation provides the following information about the specified
volumes>
Status: Reflects the current status of the volume. The possible values are ok, impaired , warning, or insufficient-data. If all checks pass, the overall status of the volume is ok. If the check fails, the overall status is impaired. If the status is insufficient-data, then the checks may still be taking place on your volume at the time. We recommend that you retry the request. For more information on volume status, see Monitoring the Status of Your Volumes>
Events: Reflect the cause of a volume status and may require you to take action. For example, if your volume returns an impaired status, then the volume event might be potential-data-inconsistency. This means that your volume has been affected by an issue with the underlying host, has all I/O operations disabled, and may have inconsistent
data>
Actions: Reflect the actions you may have to take in response to an event. For example, if the status of the volume is impaired and the volume event shows potential-data-inconsistency, then the action shows enable-volume-io. This means that you may want to enable the I/O operations for the volume by calling the EnableVolumeIO action and then check the volume for data
consistency> <note>
Volume status is based on the volume status checks, and does not reflect the volume state. Therefore, volume status does not indicate volumes in the error state (for example, when a volume is incapable of accepting
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4298 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVolumeStatusResponse *>(send(request));
 }
describeVpcAttribute
DescribeVpcAttributeResponse * QtAws::EC2::Ec2Client::describeVpcAttribute (const DescribeVpcAttributeRequest & request) slot
Describes the specified attribute of the specified VPC. You can specify only one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4369 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcAttributeResponse *>(send(request));
 }
describeVpcClassicLink
DescribeVpcClassicLinkResponse * QtAws::EC2::Ec2Client::describeVpcClassicLink (const DescribeVpcClassicLinkRequest & request) slot
Describes the ClassicLink status of one or more
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4383 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcClassicLinkResponse *>(send(request));
 }
describeVpcClassicLinkDnsSupport
DescribeVpcClassicLinkDnsSupportResponse * QtAws::EC2::Ec2Client::describeVpcClassicLinkDnsSupport (const DescribeVpcClassicLinkDnsSupportRequest & request) slot
Describes the ClassicLink DNS support status of one or more VPCs. If enabled, the DNS hostname of a linked EC2-Classic instance resolves to its private IP address when addressed from an instance in the VPC to which it's linked. Similarly, the DNS hostname of an instance in a VPC resolves to its private IP address when addressed from a linked EC2-Classic instance. For more information, see ClassicLink in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4402 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcClassicLinkDnsSupportResponse *>(send(request));
 }
describeVpcEndpointConnectionNotifications
DescribeVpcEndpointConnectionNotificationsResponse * QtAws::EC2::Ec2Client::describeVpcEndpointConnectionNotifications (const DescribeVpcEndpointConnectionNotificationsRequest & request) slot
Describes the connection notifications for VPC endpoints and VPC endpoint
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4416 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointConnectionNotificationsResponse *>(send(request));
 }
describeVpcEndpointConnections
DescribeVpcEndpointConnectionsResponse * QtAws::EC2::Ec2Client::describeVpcEndpointConnections (const DescribeVpcEndpointConnectionsRequest & request) slot
Describes the VPC endpoint connections to your VPC endpoint services, including any endpoints that are pending your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4430 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointConnectionsResponse *>(send(request));
 }
describeVpcEndpoints
DescribeVpcEndpointsResponse * QtAws::EC2::Ec2Client::describeVpcEndpoints (const DescribeVpcEndpointsRequest & request) slot
Describes one or more of your VPC
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4486 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointsResponse *>(send(request));
 }
describeVpcEndpointServiceConfigurations
DescribeVpcEndpointServiceConfigurationsResponse * QtAws::EC2::Ec2Client::describeVpcEndpointServiceConfigurations (const DescribeVpcEndpointServiceConfigurationsRequest & request) slot
Describes the VPC endpoint service configurations in your account (your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4444 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointServiceConfigurationsResponse *>(send(request));
 }
describeVpcEndpointServicePermissions
DescribeVpcEndpointServicePermissionsResponse * QtAws::EC2::Ec2Client::describeVpcEndpointServicePermissions (const DescribeVpcEndpointServicePermissionsRequest & request) slot
Describes the principals (service consumers) that are permitted to discover your VPC endpoint
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4458 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointServicePermissionsResponse *>(send(request));
 }
describeVpcEndpointServices
DescribeVpcEndpointServicesResponse * QtAws::EC2::Ec2Client::describeVpcEndpointServices (const DescribeVpcEndpointServicesRequest & request) slot
Describes available services to which you can create a VPC
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4472 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcEndpointServicesResponse *>(send(request));
 }
describeVpcPeeringConnections
DescribeVpcPeeringConnectionsResponse * QtAws::EC2::Ec2Client::describeVpcPeeringConnections (const DescribeVpcPeeringConnectionsRequest & request) slot
Describes one or more of your VPC peering
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4500 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcPeeringConnectionsResponse *>(send(request));
 }
describeVpcs
DescribeVpcsResponse * QtAws::EC2::Ec2Client::describeVpcs (const DescribeVpcsRequest & request) slot
Describes one or more of your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4514 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpcsResponse *>(send(request));
 }
describeVpnConnections
DescribeVpnConnectionsResponse * QtAws::EC2::Ec2Client::describeVpnConnections (const DescribeVpnConnectionsRequest & request) slot
Describes one or more of your VPN
connections>
For more information about VPN connections, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4534 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpnConnectionsResponse *>(send(request));
 }
describeVpnGateways
DescribeVpnGatewaysResponse * QtAws::EC2::Ec2Client::describeVpnGateways (const DescribeVpnGatewaysRequest & request) slot
Describes one or more of your virtual private
gateways>
For more information about virtual private gateways, see AWS Managed VPN Connections in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4554 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVpnGatewaysResponse *>(send(request));
 }
detachClassicLinkVpc
DetachClassicLinkVpcResponse * QtAws::EC2::Ec2Client::detachClassicLinkVpc (const DetachClassicLinkVpcRequest & request) slot
Unlinks (detaches) a linked EC2-Classic instance from a VPC. After the instance has been unlinked, the VPC security groups are no longer associated with it. An instance is automatically unlinked from a VPC when it's
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4569 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachClassicLinkVpcResponse *>(send(request));
 }
detachInternetGateway
DetachInternetGatewayResponse * QtAws::EC2::Ec2Client::detachInternetGateway (const DetachInternetGatewayRequest & request) slot
Detaches an Internet gateway from a VPC, disabling connectivity between the Internet and the VPC. The VPC must not contain any running instances with Elastic IP addresses or public IPv4
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4584 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachInternetGatewayResponse *>(send(request));
 }
detachNetworkInterface
DetachNetworkInterfaceResponse * QtAws::EC2::Ec2Client::detachNetworkInterface (const DetachNetworkInterfaceRequest & request) slot
Detaches a network interface from an
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4598 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachNetworkInterfaceResponse *>(send(request));
 }
detachVolume
DetachVolumeResponse * QtAws::EC2::Ec2Client::detachVolume (const DetachVolumeRequest & request) slot
Detaches an EBS volume from an instance. Make sure to unmount any file systems on the device within your operating system before detaching the volume. Failure to do so can result in the volume becoming stuck in the busy state while detaching. If this happens, detachment can be delayed indefinitely until you unmount the volume, force detachment, reboot the instance, or all three. If an EBS volume is the root device of an instance, it can't be detached while the instance is running. To detach the root volume, stop the instance
first>
When a volume with an AWS Marketplace product code is detached from an instance, the product code is no longer associated with the
instance>
For more information, see Detaching an Amazon EBS Volume in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4627 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachVolumeResponse *>(send(request));
 }
detachVpnGateway
DetachVpnGatewayResponse * QtAws::EC2::Ec2Client::detachVpnGateway (const DetachVpnGatewayRequest & request) slot
Detaches a virtual private gateway from a VPC. You do this if you're planning to turn off the VPC and not use it anymore. You can confirm a virtual private gateway has been completely detached from a VPC by describing the virtual private gateway (any attachments to the virtual private gateway are also
described)>
You must wait for the attachment's state to switch to detached before you can delete the VPC or attach a different VPC to the virtual private
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4648 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachVpnGatewayResponse *>(send(request));
 }
disableVgwRoutePropagation
DisableVgwRoutePropagationResponse * QtAws::EC2::Ec2Client::disableVgwRoutePropagation (const DisableVgwRoutePropagationRequest & request) slot
Disables a virtual private gateway (VGW) from propagating routes to a specified route table of a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4662 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableVgwRoutePropagationResponse *>(send(request));
 }
disableVpcClassicLink
DisableVpcClassicLinkResponse * QtAws::EC2::Ec2Client::disableVpcClassicLink (const DisableVpcClassicLinkRequest & request) slot
Disables ClassicLink for a VPC. You cannot disable ClassicLink for a VPC that has EC2-Classic instances linked to
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4676 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableVpcClassicLinkResponse *>(send(request));
 }
disableVpcClassicLinkDnsSupport
DisableVpcClassicLinkDnsSupportResponse * QtAws::EC2::Ec2Client::disableVpcClassicLinkDnsSupport (const DisableVpcClassicLinkDnsSupportRequest & request) slot
Disables ClassicLink DNS support for a VPC. If disabled, DNS hostnames resolve to public IP addresses when addressed between a linked EC2-Classic instance and instances in the VPC to which it's linked. For more information about ClassicLink, see ClassicLink in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4693 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableVpcClassicLinkDnsSupportResponse *>(send(request));
 }
disassociateAddress
DisassociateAddressResponse * QtAws::EC2::Ec2Client::disassociateAddress (const DisassociateAddressRequest & request) slot
Disassociates an Elastic IP address from the instance or network interface it's associated
with>
An Elastic IP address is for use in either the EC2-Classic platform or in a VPC. For more information, see Elastic IP Addresses in the Amazon Elastic Compute Cloud User
Guide>
This is an idempotent operation. If you perform the operation more than once, Amazon EC2 doesn't return an
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4717 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateAddressResponse *>(send(request));
 }
disassociateIamInstanceProfile
DisassociateIamInstanceProfileResponse * QtAws::EC2::Ec2Client::disassociateIamInstanceProfile (const DisassociateIamInstanceProfileRequest & request) slot
Disassociates an IAM instance profile from a running or stopped
instance>
Use DescribeIamInstanceProfileAssociations to get the association
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4735 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateIamInstanceProfileResponse *>(send(request));
 }
disassociateRouteTable
DisassociateRouteTableResponse * QtAws::EC2::Ec2Client::disassociateRouteTable (const DisassociateRouteTableRequest & request) slot
Disassociates a subnet from a route
table>
After you perform this action, the subnet no longer uses the routes in the route table. Instead, it uses the routes in the VPC's main route table. For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4756 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateRouteTableResponse *>(send(request));
 }
disassociateSubnetCidrBlock
DisassociateSubnetCidrBlockResponse * QtAws::EC2::Ec2Client::disassociateSubnetCidrBlock (const DisassociateSubnetCidrBlockRequest & request) slot
Disassociates a CIDR block from a subnet. Currently, you can disassociate an IPv6 CIDR block only. You must detach or delete all gateways and resources that are associated with the CIDR block before you can disassociate it.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4771 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateSubnetCidrBlockResponse *>(send(request));
 }
disassociateVpcCidrBlock
DisassociateVpcCidrBlockResponse * QtAws::EC2::Ec2Client::disassociateVpcCidrBlock (const DisassociateVpcCidrBlockRequest & request) slot
Disassociates a CIDR block from a VPC. To disassociate the CIDR block, you must specify its association ID. You can get the association ID by using DescribeVpcs. You must detach or delete all gateways and resources that are associated with the CIDR block before you can disassociate it.
</p
You cannot disassociate the CIDR block with which you originally created the VPC (the primary CIDR
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4791 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateVpcCidrBlockResponse *>(send(request));
 }
enableVgwRoutePropagation
EnableVgwRoutePropagationResponse * QtAws::EC2::Ec2Client::enableVgwRoutePropagation (const EnableVgwRoutePropagationRequest & request) slot
Enables a virtual private gateway (VGW) to propagate routes to the specified route table of a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4805 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableVgwRoutePropagationResponse *>(send(request));
 }
enableVolumeIO
EnableVolumeIOResponse * QtAws::EC2::Ec2Client::enableVolumeIO (const EnableVolumeIORequest & request) slot
Enables I/O operations for a volume that had I/O operations disabled because the data on the volume was potentially
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4819 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableVolumeIOResponse *>(send(request));
 }
enableVpcClassicLink
EnableVpcClassicLinkResponse * QtAws::EC2::Ec2Client::enableVpcClassicLink (const EnableVpcClassicLinkRequest & request) slot
Enables a VPC for ClassicLink. You can then link EC2-Classic instances to your ClassicLink-enabled VPC to allow communication over private IP addresses. You cannot enable your VPC for ClassicLink if any of your VPC's route tables have existing routes for address ranges within the 10.0.0.0/8 IP address range, excluding local routes for VPCs in the 10.0.0.0/16 and 10.1.0.0/16 IP address ranges. For more information, see ClassicLink in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4838 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableVpcClassicLinkResponse *>(send(request));
 }
enableVpcClassicLinkDnsSupport
EnableVpcClassicLinkDnsSupportResponse * QtAws::EC2::Ec2Client::enableVpcClassicLinkDnsSupport (const EnableVpcClassicLinkDnsSupportRequest & request) slot
Enables a VPC to support DNS hostname resolution for ClassicLink. If enabled, the DNS hostname of a linked EC2-Classic instance resolves to its private IP address when addressed from an instance in the VPC to which it's linked. Similarly, the DNS hostname of an instance in a VPC resolves to its private IP address when addressed from a linked EC2-Classic instance. For more information about ClassicLink, see ClassicLink in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4857 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableVpcClassicLinkDnsSupportResponse *>(send(request));
 }
getConsoleOutput
GetConsoleOutputResponse * QtAws::EC2::Ec2Client::getConsoleOutput (const GetConsoleOutputRequest & request) slot
Gets the console output for the specified
instance>
Instances do not have a physical monitor through which you can view their console output. They also lack physical controls that allow you to power up, reboot, or shut them down. To allow these actions, we provide them through the Amazon EC2 API and command line
interface>
Instance console output is buffered and posted shortly after instance boot, reboot, and termination. Amazon EC2 preserves the most recent 64 KB output, which is available for at least one hour after the most recent
post>
For Linux instances, the instance console output displays the exact console output that would normally be displayed on a physical monitor attached to a computer. This output is buffered because the instance produces it and then posts it to a store where the instance's owner can retrieve
it>
For Windows instances, the instance console output includes output from the EC2Config
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4892 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConsoleOutputResponse *>(send(request));
 }
getConsoleScreenshot
GetConsoleScreenshotResponse * QtAws::EC2::Ec2Client::getConsoleScreenshot (const GetConsoleScreenshotRequest & request) slot
Retrieve a JPG-format screenshot of a running instance to help with
troubleshooting>
The returned content is
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4910 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConsoleScreenshotResponse *>(send(request));
 }
getHostReservationPurchasePreview
GetHostReservationPurchasePreviewResponse * QtAws::EC2::Ec2Client::getHostReservationPurchasePreview (const GetHostReservationPurchasePreviewRequest & request) slot
Preview a reservation purchase with configurations that match those of your Dedicated Host. You must have active Dedicated Hosts in your account before you purchase a
reservation>
This is a preview of the PurchaseHostReservation action and does not result in the offering being
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4929 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetHostReservationPurchasePreviewResponse *>(send(request));
 }
getLaunchTemplateData
GetLaunchTemplateDataResponse * QtAws::EC2::Ec2Client::getLaunchTemplateData (const GetLaunchTemplateDataRequest & request) slot
Retrieves the configuration data of the specified instance. You can use this data to create a launch
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4943 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetLaunchTemplateDataResponse *>(send(request));
 }
getPasswordData
GetPasswordDataResponse * QtAws::EC2::Ec2Client::getPasswordData (const GetPasswordDataRequest & request) slot
Retrieves the encrypted administrator password for a running Windows
instance>
The Windows password is generated at boot by the EC2Config service or EC2Launch scripts (Windows Server 2016 and later). This usually only happens the first time an instance is launched. For more information, see EC2Config and EC2Launch in the Amazon Elastic Compute Cloud User
Guide>
For the EC2Config service, the password is not generated for rebundled AMIs unless Ec2SetPassword is enabled before
bundling>
The password is encrypted using the key pair that you specified when you launched the instance. You must provide the corresponding key pair
file>
When you launch an instance, password generation and encryption may take a few minutes. If you try to retrieve the password before it's available, the output returns an empty string. We recommend that you wait up to 15 minutes after launching an instance before trying to retrieve the generated
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4981 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPasswordDataResponse *>(send(request));
 }
getReservedInstancesExchangeQuote
GetReservedInstancesExchangeQuoteResponse * QtAws::EC2::Ec2Client::getReservedInstancesExchangeQuote (const GetReservedInstancesExchangeQuoteRequest & request) slot
Returns a quote and exchange information for exchanging one or more specified Convertible Reserved Instances for a new Convertible Reserved Instance. If the exchange cannot be performed, the reason is returned in the response. Use AcceptReservedInstancesExchangeQuote to perform the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 4997 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReservedInstancesExchangeQuoteResponse *>(send(request));
 }
importImage
ImportImageResponse * QtAws::EC2::Ec2Client::importImage (const ImportImageRequest & request) slot
Import single or multi-volume disk images or EBS snapshots into an Amazon Machine Image (AMI). For more information, see Importing a VM as an Image Using VM Import/Export in the VM Import/Export User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5013 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportImageResponse *>(send(request));
 }
importInstance
ImportInstanceResponse * QtAws::EC2::Ec2Client::importInstance (const ImportInstanceRequest & request) slot
Creates an import instance task using metadata from the specified disk image. ImportInstance only supports single-volume VMs. To import multi-volume VMs, use ImportImage. For more information, see Importing a Virtual Machine Using the Amazon EC2 CLI>
For information about the import manifest referenced by this API action, see VM Import request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 5035 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportInstanceResponse *>(send(request));
 }
importKeyPair
ImportKeyPairResponse * QtAws::EC2::Ec2Client::importKeyPair (const ImportKeyPairRequest & request) slot
Imports the public key from an RSA key pair that you created with a third-party tool. Compare this with CreateKeyPair, in which AWS creates the key pair and gives the keys to you (AWS keeps a copy of the public key). With ImportKeyPair, you create the key pair and give AWS just the public key. The private key is never transferred between you and
AWS>
For more information about key pairs, see Key Pairs in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5058 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportKeyPairResponse *>(send(request));
 }
importSnapshot
ImportSnapshotResponse * QtAws::EC2::Ec2Client::importSnapshot (const ImportSnapshotRequest & request) slot
Imports a disk into an EBS
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5072 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportSnapshotResponse *>(send(request));
 }
importVolume
ImportVolumeResponse * QtAws::EC2::Ec2Client::importVolume (const ImportVolumeRequest & request) slot
Creates an import volume task using metadata from the specified disk image.For more information, see Importing Disks to Amazon EBS>
For information about the import manifest referenced by this API action, see VM Import request Request to send to Amazon Elastic Compute Cloud. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 5093 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportVolumeResponse *>(send(request));
 }
modifyFpgaImageAttribute
ModifyFpgaImageAttributeResponse * QtAws::EC2::Ec2Client::modifyFpgaImageAttribute (const ModifyFpgaImageAttributeRequest & request) slot
Modifies the specified attribute of the specified Amazon FPGA Image
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5107 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyFpgaImageAttributeResponse *>(send(request));
 }
modifyHosts
ModifyHostsResponse * QtAws::EC2::Ec2Client::modifyHosts (const ModifyHostsRequest & request) slot
Modify the auto-placement setting of a Dedicated Host. When auto-placement is enabled, AWS will place instances that you launch with a tenancy of host, but without targeting a specific host ID, onto any available Dedicated Host in your account which has auto-placement enabled. When auto-placement is disabled, you need to provide a host ID if you want the instance to launch onto a specific host. If no host ID is provided, the instance will be launched onto a suitable host which has auto-placement
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5125 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyHostsResponse *>(send(request));
 }
modifyIdentityIdFormat
ModifyIdentityIdFormatResponse * QtAws::EC2::Ec2Client::modifyIdentityIdFormat (const ModifyIdentityIdFormatRequest & request) slot
Modifies the ID format of a resource for a specified IAM user, IAM role, or the root user for an account; or all IAM users, IAM roles, and the root user for an account. You can specify that resources should receive longer IDs (17-character IDs) when they are created.
</p
This request can only be used to modify longer ID settings for resource types that are within the opt-in period. Resources currently in their opt-in period include: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | route-table | route-table-association | security-group | subnet | subnet-cidr-block-association | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection | vpn-gateway.
</p
For more information, see Resource IDs in the Amazon Elastic Compute Cloud User Guide.
</p
This setting applies to the principal specified in the request; it does not apply to the principal that makes the request.
</p
Resources created with longer IDs are visible to all IAM roles and users, regardless of these settings and provided that they have permission to use the relevant Describe command for the resource
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5210 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyIdentityIdFormatResponse *>(send(request));
 }
modifyIdFormat
ModifyIdFormatResponse * QtAws::EC2::Ec2Client::modifyIdFormat (const ModifyIdFormatRequest & request) slot
Modifies the ID format for the specified resource on a per-region basis. You can specify that resources should receive longer IDs (17-character IDs) when they are
created>
This request can only be used to modify longer ID settings for resource types that are within the opt-in period. Resources currently in their opt-in period include: bundle | conversion-task | customer-gateway | dhcp-options | elastic-ip-allocation | elastic-ip-association | export-task | flow-log | image | import-task | internet-gateway | network-acl | network-acl-association | network-interface | network-interface-attachment | prefix-list | route-table | route-table-association | security-group | subnet | subnet-cidr-block-association | vpc | vpc-cidr-block-association | vpc-endpoint | vpc-peering-connection | vpn-connection |
vpn-gateway>
This setting applies to the IAM user who makes the request; it does not apply to the entire AWS account. By default, an IAM user defaults to the same settings as the root user. If you're using this action as the root user, then these settings apply to the entire account, unless an IAM user explicitly overrides these settings for themselves. For more information, see Resource IDs in the Amazon Elastic Compute Cloud User Guide.
</p
Resources created with longer IDs are visible to all IAM roles and users, regardless of these settings and provided that they have permission to use the relevant Describe command for the resource
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5166 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyIdFormatResponse *>(send(request));
 }
modifyImageAttribute
ModifyImageAttributeResponse * QtAws::EC2::Ec2Client::modifyImageAttribute (const ModifyImageAttributeRequest & request) slot
Modifies the specified attribute of the specified AMI. You can specify only one attribute at a time. You can use the Attribute parameter to specify the attribute or one of the following parameters: Description, LaunchPermission, or
ProductCode>
AWS Marketplace product codes cannot be modified. Images with an AWS Marketplace product code cannot be made
public>
To enable the SriovNetSupport enhanced networking attribute of an image, enable SriovNetSupport on an instance and create an AMI from the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5235 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyImageAttributeResponse *>(send(request));
 }
modifyInstanceAttribute
ModifyInstanceAttributeResponse * QtAws::EC2::Ec2Client::modifyInstanceAttribute (const ModifyInstanceAttributeRequest & request) slot
Modifies the specified attribute of the specified instance. You can specify only one attribute at a
time>
To modify some attributes, the instance must be stopped. For more information, see Modifying Attributes of a Stopped Instance in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5255 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyInstanceAttributeResponse *>(send(request));
 }
modifyInstanceCreditSpecification
ModifyInstanceCreditSpecificationResponse * QtAws::EC2::Ec2Client::modifyInstanceCreditSpecification (const ModifyInstanceCreditSpecificationRequest & request) slot
Modifies the credit option for CPU usage on a running or stopped T2 instance. The credit options are standard and
unlimited>
For more information, see T2 Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5275 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyInstanceCreditSpecificationResponse *>(send(request));
 }
modifyInstancePlacement
ModifyInstancePlacementResponse * QtAws::EC2::Ec2Client::modifyInstancePlacement (const ModifyInstancePlacementRequest & request) slot
Modifies the placement attributes for a specified instance. You can do the
following>
Modify the affinity between an instance and a Dedicated Host. When affinity is set to host and the instance is not associated with a specific Dedicated Host, the next time the instance is launched, it is automatically associated with the host on which it lands. If the instance is restarted or rebooted, this relationship
persists>
Change the Dedicated Host with which an instance is
associated>
Change the instance tenancy of an instance from host to dedicated, or from dedicated to
host>
Move an instance to or from a placement group>
At least one attribute for affinity, host ID, tenancy, or placement group name must be specified in the request. Affinity and tenancy can be modified in the same
request>
To modify the host ID, tenancy, or placement group for an instance, the instance must be in the stopped
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5320 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyInstancePlacementResponse *>(send(request));
 }
modifyLaunchTemplate
ModifyLaunchTemplateResponse * QtAws::EC2::Ec2Client::modifyLaunchTemplate (const ModifyLaunchTemplateRequest & request) slot
Modifies a launch template. You can specify which version of the launch template to set as the default version. When launching an instance, the default version applies when a launch template version is not
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5335 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyLaunchTemplateResponse *>(send(request));
 }
modifyNetworkInterfaceAttribute
ModifyNetworkInterfaceAttributeResponse * QtAws::EC2::Ec2Client::modifyNetworkInterfaceAttribute (const ModifyNetworkInterfaceAttributeRequest & request) slot
Modifies the specified network interface attribute. You can specify only one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5349 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyNetworkInterfaceAttributeResponse *>(send(request));
 }
modifyReservedInstances
ModifyReservedInstancesResponse * QtAws::EC2::Ec2Client::modifyReservedInstances (const ModifyReservedInstancesRequest & request) slot
Modifies the Availability Zone, instance count, instance type, or network platform (EC2-Classic or EC2-VPC) of your Reserved Instances. The Reserved Instances to be modified must be identical, except for Availability Zone, network platform, and instance
type>
For more information, see Modifying Reserved Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5370 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyReservedInstancesResponse *>(send(request));
 }
modifySnapshotAttribute
ModifySnapshotAttributeResponse * QtAws::EC2::Ec2Client::modifySnapshotAttribute (const ModifySnapshotAttributeRequest & request) slot
Adds or removes permission settings for the specified snapshot. You may add or remove specified AWS account IDs from a snapshot's list of create volume permissions, but you cannot do both in a single API call. If you need to both add and remove account IDs for a snapshot, you must use multiple API
calls> <note>
Encrypted snapshots and snapshots with AWS Marketplace product codes cannot be made public. Snapshots encrypted with your default CMK cannot be shared with other
accounts> </note>
For more information on modifying snapshot permissions, see Sharing Snapshots in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5397 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifySnapshotAttributeResponse *>(send(request));
 }
modifySpotFleetRequest
ModifySpotFleetRequestResponse * QtAws::EC2::Ec2Client::modifySpotFleetRequest (const ModifySpotFleetRequestRequest & request) slot
Modifies the specified Spot Fleet
request>
While the Spot Fleet request is being modified, it is in the modifying
state>
To scale up your Spot Fleet, increase its target capacity. The Spot Fleet launches the additional Spot Instances according to the allocation strategy for the Spot Fleet request. If the allocation strategy is lowestPrice, the Spot Fleet launches instances using the Spot pool with the lowest price. If the allocation strategy is diversified, the Spot Fleet distributes the instances across the Spot
pools>
To scale down your Spot Fleet, decrease its target capacity. First, the Spot Fleet cancels any open requests that exceed the new target capacity. You can request that the Spot Fleet terminate Spot Instances until the size of the fleet no longer exceeds the new target capacity. If the allocation strategy is lowestPrice, the Spot Fleet terminates the instances with the highest price per unit. If the allocation strategy is diversified, the Spot Fleet terminates instances across the Spot pools. Alternatively, you can request that the Spot Fleet keep the fleet at its current size, but not replace any Spot Instances that are interrupted or that you terminate
manually>
If you are finished with your Spot Fleet for now, but will use it again later, you can set the target capacity to
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5435 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifySpotFleetRequestResponse *>(send(request));
 }
modifySubnetAttribute
ModifySubnetAttributeResponse * QtAws::EC2::Ec2Client::modifySubnetAttribute (const ModifySubnetAttributeRequest & request) slot
Modifies a subnet attribute. You can only modify one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5449 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifySubnetAttributeResponse *>(send(request));
 }
modifyVolume
ModifyVolumeResponse * QtAws::EC2::Ec2Client::modifyVolume (const ModifyVolumeRequest & request) slot
You can modify several parameters of an existing EBS volume, including volume size, volume type, and IOPS capacity. If your EBS volume is attached to a current-generation EC2 instance type, you may be able to apply these changes without stopping the instance or detaching the volume from it. For more information about modifying an EBS volume running Linux, see Modifying the Size, IOPS, or Type of an EBS Volume on Linux. For more information about modifying an EBS volume running Windows, see Modifying the Size, IOPS, or Type of an EBS Volume on Windows.
</p
When you complete a resize operation on your volume, you need to extend the volume's file-system size to take advantage of the new storage capacity. For information about extending a Linux file system, see Extending a Linux File System. For information about extending a Windows file system, see Extending a Windows File System.
</p
You can use CloudWatch Events to check the status of a modification to an EBS volume. For information about CloudWatch Events, see the Amazon CloudWatch Events User Guide. You can also track the status of a modification using the DescribeVolumesModifications API. For information about tracking status changes using either method, see Monitoring Volume Modifications.
</p <note>
With previous-generation instance types, resizing an EBS volume may require detaching and reattaching the volume or stopping and restarting the instance. For more information about modifying an EBS volume running Linux, see Modifying the Size, IOPS, or Type of an EBS Volume on Linux. For more information about modifying an EBS volume running Windows, see Modifying the Size, IOPS, or Type of an EBS Volume on Windows> </note> <note>
If you reach the maximum volume modification rate per volume limit, you will need to wait at least six hours before applying further modifications to the affected EBS
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5501 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVolumeResponse *>(send(request));
 }
modifyVolumeAttribute
ModifyVolumeAttributeResponse * QtAws::EC2::Ec2Client::modifyVolumeAttribute (const ModifyVolumeAttributeRequest & request) slot
Modifies a volume
attribute>
By default, all I/O operations for the volume are suspended when the data on the volume is determined to be potentially inconsistent, to prevent undetectable, latent data corruption. The I/O access to the volume can be resumed by first enabling I/O access and then checking the data consistency on your
volume>
You can change the default behavior to resume I/O operations. We recommend that you change this only for boot volumes or for volumes that are stateless or
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5526 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVolumeAttributeResponse *>(send(request));
 }
modifyVpcAttribute
ModifyVpcAttributeResponse * QtAws::EC2::Ec2Client::modifyVpcAttribute (const ModifyVpcAttributeRequest & request) slot
Modifies the specified attribute of the specified
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5540 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcAttributeResponse *>(send(request));
 }
modifyVpcEndpoint
ModifyVpcEndpointResponse * QtAws::EC2::Ec2Client::modifyVpcEndpoint (const ModifyVpcEndpointRequest & request) slot
Modifies attributes of a specified VPC endpoint. The attributes that you can modify depend on the type of VPC endpoint (interface or gateway). For more information, see VPC Endpoints in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5557 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcEndpointResponse *>(send(request));
 }
modifyVpcEndpointConnectionNotification
ModifyVpcEndpointConnectionNotificationResponse * QtAws::EC2::Ec2Client::modifyVpcEndpointConnectionNotification (const ModifyVpcEndpointConnectionNotificationRequest & request) slot
Modifies a connection notification for VPC endpoint or VPC endpoint service. You can change the SNS topic for the notification, or the events for which to be notified.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5572 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcEndpointConnectionNotificationResponse *>(send(request));
 }
modifyVpcEndpointServiceConfiguration
ModifyVpcEndpointServiceConfigurationResponse * QtAws::EC2::Ec2Client::modifyVpcEndpointServiceConfiguration (const ModifyVpcEndpointServiceConfigurationRequest & request) slot
Modifies the attributes of your VPC endpoint service configuration. You can change the Network Load Balancers for your service, and you can specify whether acceptance is required for requests to connect to your endpoint service through an interface VPC
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5588 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcEndpointServiceConfigurationResponse *>(send(request));
 }
modifyVpcEndpointServicePermissions
ModifyVpcEndpointServicePermissionsResponse * QtAws::EC2::Ec2Client::modifyVpcEndpointServicePermissions (const ModifyVpcEndpointServicePermissionsRequest & request) slot
Modifies the permissions for your VPC endpoint service. You can add or remove permissions for service consumers (IAM users, IAM roles, and AWS accounts) to connect to your endpoint
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5604 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcEndpointServicePermissionsResponse *>(send(request));
 }
modifyVpcPeeringConnectionOptions
ModifyVpcPeeringConnectionOptionsResponse * QtAws::EC2::Ec2Client::modifyVpcPeeringConnectionOptions (const ModifyVpcPeeringConnectionOptionsRequest & request) slot
Modifies the VPC peering connection options on one side of a VPC peering connection. You can do the
following>
Enable/disable communication over the peering connection between an EC2-Classic instance that's linked to your VPC (using ClassicLink) and instances in the peer
VPC>
Enable/disable communication over the peering connection between instances in your VPC and an EC2-Classic instance that's linked to the peer
VPC>
Enable/disable the ability to resolve public DNS hostnames to private IP addresses when queried from instances in the peer
VPC>
If the peered VPCs are in different accounts, each owner must initiate a separate request to modify the peering connection options, depending on whether their VPC was the requester or accepter for the VPC peering connection. If the peered VPCs are in the same account, you can modify the requester and accepter options in the same request. To confirm which VPC is the accepter and requester for a VPC peering connection, use the DescribeVpcPeeringConnections
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5640 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcPeeringConnectionOptionsResponse *>(send(request));
 }
modifyVpcTenancy
ModifyVpcTenancyResponse * QtAws::EC2::Ec2Client::modifyVpcTenancy (const ModifyVpcTenancyRequest & request) slot
Modifies the instance tenancy attribute of the specified VPC. You can change the instance tenancy attribute of a VPC to default only. You cannot change the instance tenancy attribute to
dedicated>
After you modify the tenancy of the VPC, any new instances that you launch into the VPC have a tenancy of default, unless you specify otherwise during launch. The tenancy of any existing instances in the VPC is not
affected>
For more information about Dedicated Instances, see Dedicated Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5667 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyVpcTenancyResponse *>(send(request));
 }
monitorInstances
MonitorInstancesResponse * QtAws::EC2::Ec2Client::monitorInstances (const MonitorInstancesRequest & request) slot
Enables detailed monitoring for a running instance. Otherwise, basic monitoring is enabled. For more information, see Monitoring Your Instances and Volumes in the Amazon Elastic Compute Cloud User
Guide>
To disable detailed monitoring, see
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5687 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<MonitorInstancesResponse *>(send(request));
 }
moveAddressToVpc
MoveAddressToVpcResponse * QtAws::EC2::Ec2Client::moveAddressToVpc (const MoveAddressToVpcRequest & request) slot
Moves an Elastic IP address from the EC2-Classic platform to the EC2-VPC platform. The Elastic IP address must be allocated to your account for more than 24 hours, and it must not be associated with an instance. After the Elastic IP address is moved, it is no longer available for use in the EC2-Classic platform, unless you move it back using the RestoreAddressToClassic request. You cannot move an Elastic IP address that was originally allocated for use in the EC2-VPC platform to the EC2-Classic platform.
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5705 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<MoveAddressToVpcResponse *>(send(request));
 }
purchaseHostReservation
PurchaseHostReservationResponse * QtAws::EC2::Ec2Client::purchaseHostReservation (const PurchaseHostReservationRequest & request) slot
Purchase a reservation with configurations that match those of your Dedicated Host. You must have active Dedicated Hosts in your account before you purchase a reservation. This action results in the specified reservation being purchased and charged to your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5721 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurchaseHostReservationResponse *>(send(request));
 }
purchaseReservedInstancesOffering
PurchaseReservedInstancesOfferingResponse * QtAws::EC2::Ec2Client::purchaseReservedInstancesOffering (const PurchaseReservedInstancesOfferingRequest & request) slot
Purchases a Reserved Instance for use with your account. With Reserved Instances, you pay a lower hourly rate compared to On-Demand instance
pricing>
Use DescribeReservedInstancesOfferings to get a list of Reserved Instance offerings that match your specifications. After you've purchased a Reserved Instance, you can check for your new Reserved Instance with
DescribeReservedInstances>
For more information, see Reserved Instances and Reserved Instance Marketplace in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5748 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurchaseReservedInstancesOfferingResponse *>(send(request));
 }
purchaseScheduledInstances
PurchaseScheduledInstancesResponse * QtAws::EC2::Ec2Client::purchaseScheduledInstances (const PurchaseScheduledInstancesRequest & request) slot
Purchases one or more Scheduled Instances with the specified
schedule>
Scheduled Instances enable you to purchase Amazon EC2 compute capacity by the hour for a one-year term. Before you can purchase a Scheduled Instance, you must call DescribeScheduledInstanceAvailability to check for available schedules and obtain a purchase token. After you purchase a Scheduled Instance, you must call RunScheduledInstances during each scheduled time
period>
After you purchase a Scheduled Instance, you can't cancel, modify, or resell your
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5773 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurchaseScheduledInstancesResponse *>(send(request));
 }
rebootInstances
RebootInstancesResponse * QtAws::EC2::Ec2Client::rebootInstances (const RebootInstancesRequest & request) slot
Requests a reboot of one or more instances. This operation is asynchronous; it only queues a request to reboot the specified instances. The operation succeeds if the instances are valid and belong to you. Requests to reboot terminated instances are
ignored>
If an instance does not cleanly shut down within four minutes, Amazon EC2 performs a hard
reboot>
For more information about troubleshooting, see Getting Console Output and Rebooting Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5799 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootInstancesResponse *>(send(request));
 }
registerImage
RegisterImageResponse * QtAws::EC2::Ec2Client::registerImage (const RegisterImageRequest & request) slot
Registers an AMI. When you're creating an AMI, this is the final step you must complete before you can launch an instance from the AMI. For more information about creating AMIs, see Creating Your Own AMIs in the Amazon Elastic Compute Cloud User
Guide> <note>
For Amazon EBS-backed instances, CreateImage creates and registers the AMI in a single request, so you don't have to register the AMI
yourself> </note>
You can also use RegisterImage to create an Amazon EBS-backed Linux AMI from a snapshot of a root device volume. You specify the snapshot using the block device mapping. For more information, see Launching a Linux Instance from a Backup in the Amazon Elastic Compute Cloud User
Guide>
You can't register an image where a secondary (non-root) snapshot has AWS Marketplace product
codes>
Some Linux distributions, such as Red Hat Enterprise Linux (RHEL) and SUSE Linux Enterprise Server (SLES), use the EC2 billing product code associated with an AMI to verify the subscription status for package updates. Creating an AMI from an EBS snapshot does not maintain this billing code, and subsequent instances launched from such an AMI will not be able to connect to package update infrastructure. To create an AMI that must retain billing codes, see
CreateImage>
If needed, you can deregister an AMI at any time. Any modifications you make to an AMI backed by an instance store volume invalidates its registration. If you make changes to an image, deregister the previous image and register the new
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5844 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterImageResponse *>(send(request));
 }
rejectVpcEndpointConnections
RejectVpcEndpointConnectionsResponse * QtAws::EC2::Ec2Client::rejectVpcEndpointConnections (const RejectVpcEndpointConnectionsRequest & request) slot
Rejects one or more VPC endpoint connection requests to your VPC endpoint
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5858 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RejectVpcEndpointConnectionsResponse *>(send(request));
 }
rejectVpcPeeringConnection
RejectVpcPeeringConnectionResponse * QtAws::EC2::Ec2Client::rejectVpcPeeringConnection (const RejectVpcPeeringConnectionRequest & request) slot
Rejects a VPC peering connection request. The VPC peering connection must be in the pending-acceptance state. Use the DescribeVpcPeeringConnections request to view your outstanding VPC peering connection requests. To delete an active VPC peering connection, or to delete a VPC peering connection request that you initiated, use
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5874 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RejectVpcPeeringConnectionResponse *>(send(request));
 }
releaseAddress
ReleaseAddressResponse * QtAws::EC2::Ec2Client::releaseAddress (const ReleaseAddressRequest & request) slot
Releases the specified Elastic IP
address>
[EC2-Classic, default VPC] Releasing an Elastic IP address automatically disassociates it from any instance that it's associated with. To disassociate an Elastic IP address without releasing it, use
DisassociateAddress>
[Nondefault VPC] You must use DisassociateAddress to disassociate the Elastic IP address before you can release it. Otherwise, Amazon EC2 returns an error
(InvalidIPAddress.InUse)>
After releasing an Elastic IP address, it is released to the IP address pool. Be sure to update your DNS records and any servers or devices that communicate with the address. If you attempt to release an Elastic IP address that you already released, you'll get an AuthFailure error if the address is already allocated to another AWS
account>
[EC2-VPC] After you release an Elastic IP address for use in a VPC, you might be able to recover it. For more information, see
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5909 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReleaseAddressResponse *>(send(request));
 }
releaseHosts
ReleaseHostsResponse * QtAws::EC2::Ec2Client::releaseHosts (const ReleaseHostsRequest & request) slot
When you no longer want to use an On-Demand Dedicated Host it can be released. On-Demand billing is stopped and the host goes into released state. The host ID of Dedicated Hosts that have been released can no longer be specified in another request, e.g., ModifyHosts. You must stop or terminate all instances on a host before it can be
released>
When Dedicated Hosts are released, it make take some time for them to stop counting toward your limit and you may receive capacity errors when trying to allocate new Dedicated hosts. Try waiting a few minutes, and then try
again>
Released hosts will still appear in a DescribeHosts
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5934 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReleaseHostsResponse *>(send(request));
 }
replaceIamInstanceProfileAssociation
ReplaceIamInstanceProfileAssociationResponse * QtAws::EC2::Ec2Client::replaceIamInstanceProfileAssociation (const ReplaceIamInstanceProfileAssociationRequest & request) slot
Replaces an IAM instance profile for the specified running instance. You can use this action to change the IAM instance profile that's associated with an instance without having to disassociate the existing IAM instance profile
first>
Use DescribeIamInstanceProfileAssociations to get the association
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5953 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReplaceIamInstanceProfileAssociationResponse *>(send(request));
 }
replaceNetworkAclAssociation
ReplaceNetworkAclAssociationResponse * QtAws::EC2::Ec2Client::replaceNetworkAclAssociation (const ReplaceNetworkAclAssociationRequest & request) slot
Changes which network ACL a subnet is associated with. By default when you create a subnet, it's automatically associated with the default network ACL. For more information about network ACLs, see Network ACLs in the Amazon Virtual Private Cloud User
Guide>
This is an idempotent
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5974 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReplaceNetworkAclAssociationResponse *>(send(request));
 }
replaceNetworkAclEntry
ReplaceNetworkAclEntryResponse * QtAws::EC2::Ec2Client::replaceNetworkAclEntry (const ReplaceNetworkAclEntryRequest & request) slot
Replaces an entry (rule) in a network ACL. For more information about network ACLs, see Network ACLs in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 5990 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReplaceNetworkAclEntryResponse *>(send(request));
 }
replaceRoute
ReplaceRouteResponse * QtAws::EC2::Ec2Client::replaceRoute (const ReplaceRouteRequest & request) slot
Replaces an existing route within a route table in a VPC. You must provide only one of the following: Internet gateway or virtual private gateway, NAT instance, NAT gateway, VPC peering connection, network interface, or egress-only Internet
gateway>
For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6012 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReplaceRouteResponse *>(send(request));
 }
replaceRouteTableAssociation
ReplaceRouteTableAssociationResponse * QtAws::EC2::Ec2Client::replaceRouteTableAssociation (const ReplaceRouteTableAssociationRequest & request) slot
Changes the route table associated with a given subnet in a VPC. After the operation completes, the subnet uses the routes in the new route table it's associated with. For more information about route tables, see Route Tables in the Amazon Virtual Private Cloud User
Guide>
You can also use ReplaceRouteTableAssociation to change which table is the main route table in the VPC. You just specify the main route table's association ID and the route table to be the new main route
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6034 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReplaceRouteTableAssociationResponse *>(send(request));
 }
reportInstanceStatus
ReportInstanceStatusResponse * QtAws::EC2::Ec2Client::reportInstanceStatus (const ReportInstanceStatusRequest & request) slot
Submits feedback about the status of an instance. The instance must be in the running state. If your experience with the instance differs from the instance status returned by DescribeInstanceStatus, use ReportInstanceStatus to report your experience with the instance. Amazon EC2 collects this information to improve the accuracy of status
checks>
Use of this action does not change the value returned by
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6055 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReportInstanceStatusResponse *>(send(request));
 }
requestSpotFleet
RequestSpotFleetResponse * QtAws::EC2::Ec2Client::requestSpotFleet (const RequestSpotFleetRequest & request) slot
Creates a Spot Fleet
request>
You can submit a single request that includes multiple launch specifications that vary by instance type, AMI, Availability Zone, or
subnet>
By default, the Spot Fleet requests Spot Instances in the Spot pool where the price per unit is the lowest. Each launch specification can include its own instance weighting that reflects the value of the instance type to your application
workload>
Alternatively, you can specify that the Spot Fleet distribute the target capacity across the Spot pools included in its launch specifications. By ensuring that the Spot Instances in your Spot Fleet are in different Spot pools, you can improve the availability of your
fleet>
You can specify tags for the Spot Instances. You cannot tag other resource types in a Spot Fleet request; only the instance resource type is
supported>
For more information, see Spot Fleet Requests in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6095 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RequestSpotFleetResponse *>(send(request));
 }
requestSpotInstances
RequestSpotInstancesResponse * QtAws::EC2::Ec2Client::requestSpotInstances (const RequestSpotInstancesRequest & request) slot
Creates a Spot Instance request. Spot Instances are instances that Amazon EC2 launches when the maximum price that you specify exceeds the current Spot price. For more information, see Spot Instance Requests in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6112 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RequestSpotInstancesResponse *>(send(request));
 }
resetFpgaImageAttribute
ResetFpgaImageAttributeResponse * QtAws::EC2::Ec2Client::resetFpgaImageAttribute (const ResetFpgaImageAttributeRequest & request) slot
Resets the specified attribute of the specified Amazon FPGA Image (AFI) to its default value. You can only reset the load permission
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6127 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetFpgaImageAttributeResponse *>(send(request));
 }
resetImageAttribute
ResetImageAttributeResponse * QtAws::EC2::Ec2Client::resetImageAttribute (const ResetImageAttributeRequest & request) slot
Resets an attribute of an AMI to its default
value> <note>
The productCodes attribute can't be
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6145 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetImageAttributeResponse *>(send(request));
 }
resetInstanceAttribute
ResetInstanceAttributeResponse * QtAws::EC2::Ec2Client::resetInstanceAttribute (const ResetInstanceAttributeRequest & request) slot
Resets an attribute of an instance to its default value. To reset the kernel or ramdisk, the instance must be in a stopped state. To reset the sourceDestCheck, the instance can be either running or
stopped>
The sourceDestCheck attribute controls whether source/destination checking is enabled. The default value is true, which means checking is enabled. This value must be false for a NAT instance to perform NAT. For more information, see NAT Instances in the Amazon Virtual Private Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6167 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetInstanceAttributeResponse *>(send(request));
 }
resetNetworkInterfaceAttribute
ResetNetworkInterfaceAttributeResponse * QtAws::EC2::Ec2Client::resetNetworkInterfaceAttribute (const ResetNetworkInterfaceAttributeRequest & request) slot
Resets a network interface attribute. You can specify only one attribute at a
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6181 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetNetworkInterfaceAttributeResponse *>(send(request));
 }
resetSnapshotAttribute
ResetSnapshotAttributeResponse * QtAws::EC2::Ec2Client::resetSnapshotAttribute (const ResetSnapshotAttributeRequest & request) slot
Resets permission settings for the specified
snapshot>
For more information on modifying snapshot permissions, see Sharing Snapshots in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6201 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetSnapshotAttributeResponse *>(send(request));
 }
restoreAddressToClassic
RestoreAddressToClassicResponse * QtAws::EC2::Ec2Client::restoreAddressToClassic (const RestoreAddressToClassicRequest & request) slot
Restores an Elastic IP address that was previously moved to the EC2-VPC platform back to the EC2-Classic platform. You cannot move an Elastic IP address that was originally allocated for use in EC2-VPC. The Elastic IP address must not be associated with an instance or network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6217 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreAddressToClassicResponse *>(send(request));
 }
revokeSecurityGroupEgress
RevokeSecurityGroupEgressResponse * QtAws::EC2::Ec2Client::revokeSecurityGroupEgress (const RevokeSecurityGroupEgressRequest & request) slot
[EC2-VPC only] Removes one or more egress rules from a security group for EC2-VPC. This action doesn't apply to security groups for use in EC2-Classic. To remove a rule, the values that you specify (for example, ports) must match the existing rule's values
exactly>
Each rule consists of the protocol and the IPv4 or IPv6 CIDR range or source security group. For the TCP and UDP protocols, you must also specify the destination port or range of ports. For the ICMP protocol, you must also specify the ICMP type and code. If the security group rule has a description, you do not have to specify the description to revoke the
rule>
Rule changes are propagated to instances within the security group as quickly as possible. However, a small delay might
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6244 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RevokeSecurityGroupEgressResponse *>(send(request));
 }
revokeSecurityGroupIngress
RevokeSecurityGroupIngressResponse * QtAws::EC2::Ec2Client::revokeSecurityGroupIngress (const RevokeSecurityGroupIngressRequest & request) slot
Removes one or more ingress rules from a security group. To remove a rule, the values that you specify (for example, ports) must match the existing rule's values
exactly> <note>
[EC2-Classic security groups only] If the values you specify do not match the existing rule's values, no error is returned. Use DescribeSecurityGroups to verify that the rule has been
removed> </note>
Each rule consists of the protocol and the CIDR range or source security group. For the TCP and UDP protocols, you must also specify the destination port or range of ports. For the ICMP protocol, you must also specify the ICMP type and code. If the security group rule has a description, you do not have to specify the description to revoke the
rule>
Rule changes are propagated to instances within the security group as quickly as possible. However, a small delay might
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6274 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RevokeSecurityGroupIngressResponse *>(send(request));
 }
runInstances
RunInstancesResponse * QtAws::EC2::Ec2Client::runInstances (const RunInstancesRequest & request) slot
Launches the specified number of instances using an AMI for which you have permissions.
</p
You can specify a number of options, or leave the default options. The following rules
apply>
[EC2-VPC] If you don't specify a subnet ID, we choose a default subnet from your default VPC for you. If you don't have a default VPC, you must specify a subnet ID in the
request>
[EC2-Classic] If don't specify an Availability Zone, we choose one for
you>
Some instance types must be launched into a VPC. If you do not have a default VPC, or if you do not specify a subnet ID, the request fails. For more information, see Instance Types Available Only in a VPC>
[EC2-VPC] All instances have a network interface with a primary private IPv4 address. If you don't specify this address, we choose one from the IPv4 range of your
subnet>
Not all instance types support IPv6 addresses. For more information, see Instance Types>
If you don't specify a security group ID, we use the default security group. For more information, see Security Groups>
If any of the AMIs have a product code attached for which the user has not subscribed, the request
fails>
You can create a launch template, which is a resource that contains the parameters to launch an instance. When you launch an instance using RunInstances, you can specify the launch template instead of specifying the launch
parameters>
To ensure faster instance launches, break up large requests into smaller batches. For example, create five separate launch requests for 100 instances each instead of one launch request for 500
instances>
An instance is ready for you to use when it's in the running state. You can check the state of your instance using DescribeInstances. You can tag instances and EBS volumes during launch, after launch, or both. For more information, see CreateTags and Tagging Your Amazon EC2 Resources>
Linux instances have access to the public key of the key pair at boot. You can use this key to provide secure access to the instance. Amazon EC2 public images use this feature to provide secure access without passwords. For more information, see Key Pairs in the Amazon Elastic Compute Cloud User
Guide>
For troubleshooting, see What To Do If An Instance Immediately Terminates, and Troubleshooting Connecting to Your Instance in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6360 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RunInstancesResponse *>(send(request));
 }
runScheduledInstances
RunScheduledInstancesResponse * QtAws::EC2::Ec2Client::runScheduledInstances (const RunScheduledInstancesRequest & request) slot
Launches the specified Scheduled
Instances>
Before you can launch a Scheduled Instance, you must purchase it and obtain an identifier using
PurchaseScheduledInstances>
You must launch a Scheduled Instance during its scheduled time period. You can't stop or reboot a Scheduled Instance, but you can terminate it as needed. If you terminate a Scheduled Instance before the current scheduled time period ends, you can launch it again after a few minutes. For more information, see Scheduled Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6386 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RunScheduledInstancesResponse *>(send(request));
 }
startInstances
StartInstancesResponse * QtAws::EC2::Ec2Client::startInstances (const StartInstancesRequest & request) slot
Starts an Amazon EBS-backed instance that you've previously
stopped>
Instances that use Amazon EBS volumes as their root devices can be quickly stopped and started. When an instance is stopped, the compute resources are released and you are not billed for instance usage. However, your root partition Amazon EBS volume remains and continues to persist your data, and you are charged for Amazon EBS volume usage. You can restart your instance at any time. Every time you start your Windows instance, Amazon EC2 charges you for a full instance hour. If you stop and restart your Windows instance, a new instance hour begins and Amazon EC2 charges you for another full instance hour even if you are still within the same 60-minute period when it was stopped. Every time you start your Linux instance, Amazon EC2 charges a one-minute minimum for instance usage, and thereafter charges per second for instance
usage>
Before stopping an instance, make sure it is in a state from which it can be restarted. Stopping an instance does not preserve data stored in
RAM>
Performing this operation on an instance that uses an instance store as its root device returns an
error>
For more information, see Stopping Instances in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6425 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartInstancesResponse *>(send(request));
 }
stopInstances
StopInstancesResponse * QtAws::EC2::Ec2Client::stopInstances (const StopInstancesRequest & request) slot
Stops an Amazon EBS-backed
instance>
We don't charge usage for a stopped instance, or data transfer fees; however, your root partition Amazon EBS volume remains and continues to persist your data, and you are charged for Amazon EBS volume usage. Every time you start your Windows instance, Amazon EC2 charges you for a full instance hour. If you stop and restart your Windows instance, a new instance hour begins and Amazon EC2 charges you for another full instance hour even if you are still within the same 60-minute period when it was stopped. Every time you start your Linux instance, Amazon EC2 charges a one-minute minimum for instance usage, and thereafter charges per second for instance
usage>
You can't start or stop Spot Instances, and you can't stop instance store-backed
instances>
When you stop an instance, we shut it down. You can restart your instance at any time. Before stopping an instance, make sure it is in a state from which it can be restarted. Stopping an instance does not preserve data stored in
RAM>
Stopping an instance is different to rebooting or terminating it. For example, when you stop an instance, the root device and any other devices attached to the instance persist. When you terminate an instance, the root device and any other devices attached during the instance launch are automatically deleted. For more information about the differences between rebooting, stopping, and terminating instances, see Instance Lifecycle in the Amazon Elastic Compute Cloud User
Guide>
When you stop an instance, we attempt to shut it down forcibly after a short while. If your instance appears stuck in the stopping state after a period of time, there may be an issue with the underlying host computer. For more information, see Troubleshooting Stopping Your Instance in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6474 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopInstancesResponse *>(send(request));
 }
terminateInstances
TerminateInstancesResponse * QtAws::EC2::Ec2Client::terminateInstances (const TerminateInstancesRequest & request) slot
Shuts down one or more instances. This operation is idempotent; if you terminate an instance more than once, each call succeeds.
</p
If you specify multiple instances and the request fails (for example, because of a single incorrect instance ID), none of the instances are
terminated>
Terminated instances remain visible after termination (for approximately one
hour)>
By default, Amazon EC2 deletes all EBS volumes that were attached when the instance launched. Volumes attached after instance launch continue
running>
You can stop, start, and terminate EBS-backed instances. You can only terminate instance store-backed instances. What happens to an instance differs if you stop it or terminate it. For example, when you stop an instance, the root device and any other devices attached to the instance persist. When you terminate an instance, any attached EBS volumes with the DeleteOnTermination block device mapping parameter set to true are automatically deleted. For more information about the differences between stopping and terminating instances, see Instance Lifecycle in the Amazon Elastic Compute Cloud User
Guide>
For more information about troubleshooting, see Troubleshooting Terminating Your Instance in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6519 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TerminateInstancesResponse *>(send(request));
 }
unassignIpv6Addresses
UnassignIpv6AddressesResponse * QtAws::EC2::Ec2Client::unassignIpv6Addresses (const UnassignIpv6AddressesRequest & request) slot
Unassigns one or more IPv6 addresses from a network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6533 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnassignIpv6AddressesResponse *>(send(request));
 }
unassignPrivateIpAddresses
UnassignPrivateIpAddressesResponse * QtAws::EC2::Ec2Client::unassignPrivateIpAddresses (const UnassignPrivateIpAddressesRequest & request) slot
Unassigns one or more secondary private IP addresses from a network
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6547 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnassignPrivateIpAddressesResponse *>(send(request));
 }
unmonitorInstances
UnmonitorInstancesResponse * QtAws::EC2::Ec2Client::unmonitorInstances (const UnmonitorInstancesRequest & request) slot
Disables detailed monitoring for a running instance. For more information, see Monitoring Your Instances and Volumes in the Amazon Elastic Compute Cloud User
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6563 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnmonitorInstancesResponse *>(send(request));
 }
updateSecurityGroupRuleDescriptionsEgress
UpdateSecurityGroupRuleDescriptionsEgressResponse * QtAws::EC2::Ec2Client::updateSecurityGroupRuleDescriptionsEgress (const UpdateSecurityGroupRuleDescriptionsEgressRequest & request) slot
[EC2-VPC only] Updates the description of an egress (outbound) security group rule. You can replace an existing description, or add a description to a rule that did not have one
previously>
You specify the description as part of the IP permissions structure. You can remove a description for a security group rule by omitting the description parameter in the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6583 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSecurityGroupRuleDescriptionsEgressResponse *>(send(request));
 }
updateSecurityGroupRuleDescriptionsIngress
UpdateSecurityGroupRuleDescriptionsIngressResponse * QtAws::EC2::Ec2Client::updateSecurityGroupRuleDescriptionsIngress (const UpdateSecurityGroupRuleDescriptionsIngressRequest & request) slot
Updates the description of an ingress (inbound) security group rule. You can replace an existing description, or add a description to a rule that did not have one
previously>
You specify the description as part of the IP permissions structure. You can remove a description for a security group rule by omitting the description parameter in the
Parameters
request Request to send to Amazon Elastic Compute Cloud.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 6603 of file ec2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSecurityGroupRuleDescriptionsIngressResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
ec2/ec2client.h
ec2/ec2client.cpp