AWS SDK for Qt: QtAws::SWF::SwfClient Class Reference
QtAws::SWF::SwfClient Class Reference
Client for Amazon Simple Workflow Service (SWF)
Public Slots
CountClosedWorkflowExecutionsResponse * countClosedWorkflowExecutions (const CountClosedWorkflowExecutionsRequest &request)
CountOpenWorkflowExecutionsResponse * countOpenWorkflowExecutions (const CountOpenWorkflowExecutionsRequest &request)
CountPendingActivityTasksResponse * countPendingActivityTasks (const CountPendingActivityTasksRequest &request)
CountPendingDecisionTasksResponse * countPendingDecisionTasks (const CountPendingDecisionTasksRequest &request)
DeprecateActivityTypeResponse * deprecateActivityType (const DeprecateActivityTypeRequest &request)
DeprecateDomainResponse * deprecateDomain (const DeprecateDomainRequest &request)
DeprecateWorkflowTypeResponse * deprecateWorkflowType (const DeprecateWorkflowTypeRequest &request)
DescribeActivityTypeResponse * describeActivityType (const DescribeActivityTypeRequest &request)
DescribeDomainResponse * describeDomain (const DescribeDomainRequest &request)
DescribeWorkflowExecutionResponse * describeWorkflowExecution (const DescribeWorkflowExecutionRequest &request)
DescribeWorkflowTypeResponse * describeWorkflowType (const DescribeWorkflowTypeRequest &request)
GetWorkflowExecutionHistoryResponse * getWorkflowExecutionHistory (const GetWorkflowExecutionHistoryRequest &request)
ListActivityTypesResponse * listActivityTypes (const ListActivityTypesRequest &request)
ListClosedWorkflowExecutionsResponse * listClosedWorkflowExecutions (const ListClosedWorkflowExecutionsRequest &request)
ListDomainsResponse * listDomains (const ListDomainsRequest &request)
ListOpenWorkflowExecutionsResponse * listOpenWorkflowExecutions (const ListOpenWorkflowExecutionsRequest &request)
ListWorkflowTypesResponse * listWorkflowTypes (const ListWorkflowTypesRequest &request)
PollForActivityTaskResponse * pollForActivityTask (const PollForActivityTaskRequest &request)
PollForDecisionTaskResponse * pollForDecisionTask (const PollForDecisionTaskRequest &request)
RecordActivityTaskHeartbeatResponse * recordActivityTaskHeartbeat (const RecordActivityTaskHeartbeatRequest &request)
RegisterActivityTypeResponse * registerActivityType (const RegisterActivityTypeRequest &request)
RegisterDomainResponse * registerDomain (const RegisterDomainRequest &request)
RegisterWorkflowTypeResponse * registerWorkflowType (const RegisterWorkflowTypeRequest &request)
RequestCancelWorkflowExecutionResponse * requestCancelWorkflowExecution (const RequestCancelWorkflowExecutionRequest &request)
RespondActivityTaskCanceledResponse * respondActivityTaskCanceled (const RespondActivityTaskCanceledRequest &request)
RespondActivityTaskCompletedResponse * respondActivityTaskCompleted (const RespondActivityTaskCompletedRequest &request)
RespondActivityTaskFailedResponse * respondActivityTaskFailed (const RespondActivityTaskFailedRequest &request)
RespondDecisionTaskCompletedResponse * respondDecisionTaskCompleted (const RespondDecisionTaskCompletedRequest &request)
SignalWorkflowExecutionResponse * signalWorkflowExecution (const SignalWorkflowExecutionRequest &request)
StartWorkflowExecutionResponse * startWorkflowExecution (const StartWorkflowExecutionRequest &request)
TerminateWorkflowExecutionResponse * terminateWorkflowExecution (const TerminateWorkflowExecutionRequest &request)
Public Member Functions
SwfClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SwfClient object.
SwfClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SwfClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Workflow Service (SWF)
<fullname>Amazon Simple Workflow Service</fullname>
The Amazon Simple Workflow Service (Amazon SWF) makes it easy to build applications that use Amazon's cloud to coordinate work across distributed components. In Amazon SWF, a task represents a logical unit of work that is performed by a component of your workflow. Coordinating tasks in a workflow involves managing intertask dependencies, scheduling, and concurrency in accordance with the logical flow of the
application>
Amazon SWF gives you full control over implementing tasks and coordinating them without worrying about underlying complexities such as tracking their progress and maintaining their
state>
This documentation serves as reference only. For a broader overview of the Amazon SWF programming model, see the Amazon SWF Developer Guide
Definition at line 94 of file swfclient.h.
Constructor & Destructor Documentation
SwfClient() [1/2]
QtAws::SWF::SwfClient::SwfClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SwfClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 124 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SwfClientPrivate(this), parent)
 {
     Q_D(SwfClient);
     d->apiVersion = QStringLiteral("2012-01-25");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("swf");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Simple Workflow Service");
     d->serviceName = QStringLiteral("swf");
 }
SwfClient() [2/2]
QtAws::SWF::SwfClient::SwfClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SwfClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 157 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SwfClientPrivate(this), parent)
 {
     Q_D(SwfClient);
     d->apiVersion = QStringLiteral("2012-01-25");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("swf");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Simple Workflow Service");
     d->serviceName = QStringLiteral("swf");
 }
Member Function Documentation
countClosedWorkflowExecutions
CountClosedWorkflowExecutionsResponse * QtAws::SWF::SwfClient::countClosedWorkflowExecutions (const CountClosedWorkflowExecutionsRequest & request) slot
Returns the number of closed workflow executions within the given domain that meet the specified filtering
criteria> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
tagFilter.tag: String constraint. The key is
swf:tagFilter.tag>
typeFilter.name: String constraint. The key is
swf:typeFilter.name>
typeFilter.version: String constraint. The key is
swf:typeFilter.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 227 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CountClosedWorkflowExecutionsResponse *>(send(request));
 }
countOpenWorkflowExecutions
CountOpenWorkflowExecutionsResponse * QtAws::SWF::SwfClient::countOpenWorkflowExecutions (const CountOpenWorkflowExecutionsRequest & request) slot
Returns the number of open workflow executions within the given domain that meet the specified filtering
criteria> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
tagFilter.tag: String constraint. The key is
swf:tagFilter.tag>
typeFilter.name: String constraint. The key is
swf:typeFilter.name>
typeFilter.version: String constraint. The key is
swf:typeFilter.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 285 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CountOpenWorkflowExecutionsResponse *>(send(request));
 }
countPendingActivityTasks
CountPendingActivityTasksResponse * QtAws::SWF::SwfClient::countPendingActivityTasks (const CountPendingActivityTasksRequest & request) slot
Returns the estimated number of activity tasks in the specified task list. The count returned is an approximation and isn't guaranteed to be exact. If you specify a task list that no activity task was ever scheduled in then 0 is
returned>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the taskList.name parameter by using a Condition element with the swf:taskList.name key to allow the action to access only certain task
lists>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 330 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CountPendingActivityTasksResponse *>(send(request));
 }
countPendingDecisionTasks
CountPendingDecisionTasksResponse * QtAws::SWF::SwfClient::countPendingDecisionTasks (const CountPendingDecisionTasksRequest & request) slot
Returns the estimated number of decision tasks in the specified task list. The count returned is an approximation and isn't guaranteed to be exact. If you specify a task list that no decision task was ever scheduled in then 0 is
returned>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the taskList.name parameter by using a Condition element with the swf:taskList.name key to allow the action to access only certain task
lists>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 375 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CountPendingDecisionTasksResponse *>(send(request));
 }
deprecateActivityType
DeprecateActivityTypeResponse * QtAws::SWF::SwfClient::deprecateActivityType (const DeprecateActivityTypeRequest & request) slot
Deprecates the specified activity type. After an activity type has been deprecated, you cannot create new tasks of that activity type. Tasks of this type that were scheduled before the type was deprecated continue to
run> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
activityType.name: String constraint. The key is
swf:activityType.name>
activityType.version: String constraint. The key is
swf:activityType.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 430 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeprecateActivityTypeResponse *>(send(request));
 }
deprecateDomain
DeprecateDomainResponse * QtAws::SWF::SwfClient::deprecateDomain (const DeprecateDomainRequest & request) slot
Deprecates the specified domain. After a domain has been deprecated it cannot be used to create new workflow executions or register new types. However, you can still use visibility actions on this domain. Deprecating a domain also deprecates all activity and workflow types registered in the domain. Executions that were started before the domain was deprecated continues to
run> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 479 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeprecateDomainResponse *>(send(request));
 }
deprecateWorkflowType
DeprecateWorkflowTypeResponse * QtAws::SWF::SwfClient::deprecateWorkflowType (const DeprecateWorkflowTypeRequest & request) slot
Deprecates the specified workflow type. After a workflow type has been deprecated, you cannot create new executions of that type. Executions that were started before the type was deprecated continues to run. A deprecated workflow type may still be used when calling visibility
actions> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
workflowType.name: String constraint. The key is
swf:workflowType.name>
workflowType.version: String constraint. The key is
swf:workflowType.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 535 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeprecateWorkflowTypeResponse *>(send(request));
 }
describeActivityType
DescribeActivityTypeResponse * QtAws::SWF::SwfClient::describeActivityType (const DescribeActivityTypeRequest & request) slot
Returns information about the specified activity type. This includes configuration settings provided when the type was registered and other general information about the
type>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
activityType.name: String constraint. The key is
swf:activityType.name>
activityType.version: String constraint. The key is
swf:activityType.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 586 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeActivityTypeResponse *>(send(request));
 }
describeDomain
DescribeDomainResponse * QtAws::SWF::SwfClient::describeDomain (const DescribeDomainRequest & request) slot
Returns information about the specified domain, including description and
status>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 628 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDomainResponse *>(send(request));
 }
describeWorkflowExecution
DescribeWorkflowExecutionResponse * QtAws::SWF::SwfClient::describeWorkflowExecution (const DescribeWorkflowExecutionRequest & request) slot
Returns information about the specified workflow execution including its type and some
statistics> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 674 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkflowExecutionResponse *>(send(request));
 }
describeWorkflowType
DescribeWorkflowTypeResponse * QtAws::SWF::SwfClient::describeWorkflowType (const DescribeWorkflowTypeRequest & request) slot
Returns information about the specified workflow type. This includes configuration settings specified when the type was registered and other information such as creation date, current status,
etc>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
workflowType.name: String constraint. The key is
swf:workflowType.name>
workflowType.version: String constraint. The key is
swf:workflowType.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 725 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkflowTypeResponse *>(send(request));
 }
getWorkflowExecutionHistory
GetWorkflowExecutionHistoryResponse * QtAws::SWF::SwfClient::getWorkflowExecutionHistory (const GetWorkflowExecutionHistoryRequest & request) slot
Returns the history of the specified workflow execution. The results may be split into multiple pages. To retrieve subsequent pages, make the call again using the nextPageToken returned by the initial
call> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 772 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetWorkflowExecutionHistoryResponse *>(send(request));
 }
listActivityTypes
ListActivityTypesResponse * QtAws::SWF::SwfClient::listActivityTypes (const ListActivityTypesRequest & request) slot
Returns information about all activities registered in the specified domain that match the specified name and registration status. The result includes information like creation date, current status of the activity, etc. The results may be split into multiple pages. To retrieve subsequent pages, make the call again using the nextPageToken returned by the initial
call>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 817 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListActivityTypesResponse *>(send(request));
 }
listClosedWorkflowExecutions
ListClosedWorkflowExecutionsResponse * QtAws::SWF::SwfClient::listClosedWorkflowExecutions (const ListClosedWorkflowExecutionsRequest & request) slot
Returns a list of closed workflow executions in the specified domain that meet the filtering criteria. The results may be split into multiple pages. To retrieve subsequent pages, make the call again using the nextPageToken returned by the initial
call> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
tagFilter.tag: String constraint. The key is
swf:tagFilter.tag>
typeFilter.name: String constraint. The key is
swf:typeFilter.name>
typeFilter.version: String constraint. The key is
swf:typeFilter.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 877 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListClosedWorkflowExecutionsResponse *>(send(request));
 }
listDomains
ListDomainsResponse * QtAws::SWF::SwfClient::listDomains (const ListDomainsRequest & request) slot
Returns the list of domains registered in the account. The results may be split into multiple pages. To retrieve subsequent pages, make the call again using the nextPageToken returned by the initial
call> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified domains. The element must be set to arn:aws:swf::AccountID:domain/*, where AccountID is the account ID, with no
dashes>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 925 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDomainsResponse *>(send(request));
 }
listOpenWorkflowExecutions
ListOpenWorkflowExecutionsResponse * QtAws::SWF::SwfClient::listOpenWorkflowExecutions (const ListOpenWorkflowExecutionsRequest & request) slot
Returns a list of open workflow executions in the specified domain that meet the filtering criteria. The results may be split into multiple pages. To retrieve subsequent pages, make the call again using the nextPageToken returned by the initial
call> <note>
This operation is eventually consistent. The results are best effort and may not exactly reflect recent updates and
changes> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
tagFilter.tag: String constraint. The key is
swf:tagFilter.tag>
typeFilter.name: String constraint. The key is
swf:typeFilter.name>
typeFilter.version: String constraint. The key is
swf:typeFilter.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 985 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOpenWorkflowExecutionsResponse *>(send(request));
 }
listWorkflowTypes
ListWorkflowTypesResponse * QtAws::SWF::SwfClient::listWorkflowTypes (const ListWorkflowTypesRequest & request) slot
Returns information about workflow types in the specified domain. The results may be split into multiple pages that can be retrieved by making the call
repeatedly>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1028 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListWorkflowTypesResponse *>(send(request));
 }
pollForActivityTask
PollForActivityTaskResponse * QtAws::SWF::SwfClient::pollForActivityTask (const PollForActivityTaskRequest & request) slot
Used by workers to get an ActivityTask from the specified activity taskList. This initiates a long poll, where the service holds the HTTP connection open and responds as soon as a task becomes available. The maximum time the service holds on to the request before responding is 60 seconds. If no task is available within 60 seconds, the poll returns an empty result. An empty result, in this context, means that an ActivityTask is returned, but that the value of taskToken is an empty string. If a task is returned, the worker should use its type to identify and process it
correctly>
Workers should set their client side socket timeout to at least 70 seconds (10 seconds higher than the maximum time service may hold the poll
request)>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the taskList.name parameter by using a Condition element with the swf:taskList.name key to allow the action to access only certain task
lists>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1080 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PollForActivityTaskResponse *>(send(request));
 }
pollForDecisionTask
PollForDecisionTaskResponse * QtAws::SWF::SwfClient::pollForDecisionTask (const PollForDecisionTaskRequest & request) slot
Used by deciders to get a DecisionTask from the specified decision taskList. A decision task may be returned for any open workflow execution that is using the specified task list. The task includes a paginated view of the history of the workflow execution. The decider should use the workflow type and the history to determine how to properly handle the
task>
This action initiates a long poll, where the service holds the HTTP connection open and responds as soon a task becomes available. If no decision task is available in the specified task list before the timeout of 60 seconds expires, an empty result is returned. An empty result, in this context, means that a DecisionTask is returned, but that the value of taskToken is an empty
string>
Deciders should set their client side socket timeout to at least 70 seconds (10 seconds higher than the
timeout)>
Because the number of workflow history events for a single workflow execution might be very large, the result returned might be split up across a number of pages. To retrieve subsequent pages, make additional calls to PollForDecisionTask using the nextPageToken returned by the initial call. Note that you do not call GetWorkflowExecutionHistory with this nextPageToken. Instead, call PollForDecisionTask
again>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the taskList.name parameter by using a Condition element with the swf:taskList.name key to allow the action to access only certain task
lists>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1145 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PollForDecisionTaskResponse *>(send(request));
 }
recordActivityTaskHeartbeat
RecordActivityTaskHeartbeatResponse * QtAws::SWF::SwfClient::recordActivityTaskHeartbeat (const RecordActivityTaskHeartbeatRequest & request) slot
Used by activity workers to report to the service that the ActivityTask represented by the specified taskToken is still making progress. The worker can also specify details of the progress, for example percent complete, using the details parameter. This action can also be used by the worker as a mechanism to check if cancellation is being requested for the activity task. If a cancellation is being attempted for the specified task, then the boolean cancelRequested flag returned by the service is set to
true>
This action resets the taskHeartbeatTimeout clock. The taskHeartbeatTimeout is specified in
RegisterActivityType>
This action doesn't in itself create an event in the workflow execution history. However, if the task times out, the workflow execution history contains a ActivityTaskTimedOut event that contains the information from the last heartbeat generated by the activity
worker> <note>
The taskStartToCloseTimeout of an activity type is the maximum duration of an activity task, regardless of the number of RecordActivityTaskHeartbeat requests received. The taskStartToCloseTimeout is also specified in
RegisterActivityType> </note> <note>
This operation is only useful for long-lived activities to report liveliness of the task and to determine if a cancellation is being
attempted> </note>
If the cancelRequested flag returns true, a cancellation is being attempted. If the worker can cancel the activity, it should respond with RespondActivityTaskCanceled. Otherwise, it should ignore the cancellation
request>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1218 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RecordActivityTaskHeartbeatResponse *>(send(request));
 }
registerActivityType
RegisterActivityTypeResponse * QtAws::SWF::SwfClient::registerActivityType (const RegisterActivityTypeRequest & request) slot
Registers a new activity type along with its configuration settings in the specified
domain>
A TypeAlreadyExists fault is returned if the type already exists in the domain. You cannot change any configuration settings of the type after its registration, and it must be registered as a new
version>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
defaultTaskList.name: String constraint. The key is
swf:defaultTaskList.name>
name: String constraint. The key is
swf:name>
version: String constraint. The key is
swf:version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1277 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterActivityTypeResponse *>(send(request));
 }
registerDomain
RegisterDomainResponse * QtAws::SWF::SwfClient::registerDomain (const RegisterDomainRequest & request) slot
Registers a new
domain>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
You cannot use an IAM policy to control domain access for this action. The name of the domain being registered is available as the resource of this
action>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1320 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterDomainResponse *>(send(request));
 }
registerWorkflowType
RegisterWorkflowTypeResponse * QtAws::SWF::SwfClient::registerWorkflowType (const RegisterWorkflowTypeRequest & request) slot
Registers a new workflow type and its configuration settings in the specified
domain>
The retention period for the workflow history is set by the RegisterDomain
action>
If the type already exists, then a TypeAlreadyExists fault is returned. You cannot change the configuration settings of a workflow type once it is registered and it must be registered as a new
version>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
defaultTaskList.name: String constraint. The key is
swf:defaultTaskList.name>
name: String constraint. The key is
swf:name>
version: String constraint. The key is
swf:version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1383 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterWorkflowTypeResponse *>(send(request));
 }
requestCancelWorkflowExecution
RequestCancelWorkflowExecutionResponse * QtAws::SWF::SwfClient::requestCancelWorkflowExecution (const RequestCancelWorkflowExecutionRequest & request) slot
Records a WorkflowExecutionCancelRequested event in the currently running workflow execution identified by the given domain, workflowId, and runId. This logically requests the cancellation of the workflow execution as a whole. It is up to the decider to take appropriate actions when it receives an execution history with this
event> <note>
If the runId isn't specified, the WorkflowExecutionCancelRequested event is recorded in the history of the current open workflow execution with the specified workflowId in the
domain> </note> <note>
Because this action allows the workflow to properly clean up and gracefully close, it should be used instead of TerminateWorkflowExecution when
possible> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1437 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RequestCancelWorkflowExecutionResponse *>(send(request));
 }
respondActivityTaskCanceled
RespondActivityTaskCanceledResponse * QtAws::SWF::SwfClient::respondActivityTaskCanceled (const RespondActivityTaskCanceledRequest & request) slot
Used by workers to tell the service that the ActivityTask identified by the taskToken was successfully canceled. Additional details can be provided using the details
argument>
These details (if provided) appear in the ActivityTaskCanceled event added to the workflow
history>
Only use this operation if the canceled flag of a RecordActivityTaskHeartbeat request returns true and if the activity can be safely undone or
abandoned>
A task is considered open from the time that it is scheduled until it is closed. Therefore a task is reported as open while a worker is processing it. A task is closed after it has been specified in a call to RespondActivityTaskCompleted, RespondActivityTaskCanceled, RespondActivityTaskFailed, or the task has timed out>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1496 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RespondActivityTaskCanceledResponse *>(send(request));
 }
respondActivityTaskCompleted
RespondActivityTaskCompletedResponse * QtAws::SWF::SwfClient::respondActivityTaskCompleted (const RespondActivityTaskCompletedRequest & request) slot
Used by workers to tell the service that the ActivityTask identified by the taskToken completed successfully with a result (if provided). The result appears in the ActivityTaskCompleted event in the workflow
history>
If the requested task doesn't complete successfully, use RespondActivityTaskFailed instead. If the worker finds that the task is canceled through the canceled flag returned by RecordActivityTaskHeartbeat, it should cancel the task, clean up and then call
RespondActivityTaskCanceled>
A task is considered open from the time that it is scheduled until it is closed. Therefore a task is reported as open while a worker is processing it. A task is closed after it has been specified in a call to RespondActivityTaskCompleted, RespondActivityTaskCanceled, RespondActivityTaskFailed, or the task has timed out>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1553 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RespondActivityTaskCompletedResponse *>(send(request));
 }
respondActivityTaskFailed
RespondActivityTaskFailedResponse * QtAws::SWF::SwfClient::respondActivityTaskFailed (const RespondActivityTaskFailedRequest & request) slot
Used by workers to tell the service that the ActivityTask identified by the taskToken has failed with reason (if specified). The reason and details appear in the ActivityTaskFailed event added to the workflow
history>
A task is considered open from the time that it is scheduled until it is closed. Therefore a task is reported as open while a worker is processing it. A task is closed after it has been specified in a call to RespondActivityTaskCompleted, RespondActivityTaskCanceled, RespondActivityTaskFailed, or the task has timed out>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1604 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RespondActivityTaskFailedResponse *>(send(request));
 }
respondDecisionTaskCompleted
RespondDecisionTaskCompletedResponse * QtAws::SWF::SwfClient::respondDecisionTaskCompleted (const RespondDecisionTaskCompletedRequest & request) slot
Used by deciders to tell the service that the DecisionTask identified by the taskToken has successfully completed. The decisions argument specifies the list of decisions made while processing the
task>
A DecisionTaskCompleted event is added to the workflow history. The executionContext specified is attached to the event in the workflow execution
history>
Access Control
</p
If an IAM policy grants permission to use RespondDecisionTaskCompleted, it can express permissions for the list of decisions in the decisions parameter. Each of the decisions has one or more parameters, much like a regular API call. To allow for policies to be as readable as possible, you can express permissions on decisions as if they were actual API calls, including applying conditions to some parameters. For more information, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1637 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RespondDecisionTaskCompletedResponse *>(send(request));
 }
signalWorkflowExecution
SignalWorkflowExecutionResponse * QtAws::SWF::SwfClient::signalWorkflowExecution (const SignalWorkflowExecutionRequest & request) slot
Records a WorkflowExecutionSignaled event in the workflow execution history and creates a decision task for the workflow execution identified by the given domain, workflowId and runId. The event is recorded with the specified user defined signalName and input (if
provided)> <note>
If a runId isn't specified, then the WorkflowExecutionSignaled event is recorded in the history of the current open workflow with the matching workflowId in the
domain> </note> <note>
If the specified workflow execution isn't open, this method fails with
UnknownResource> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1690 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SignalWorkflowExecutionResponse *>(send(request));
 }
startWorkflowExecution
StartWorkflowExecutionResponse * QtAws::SWF::SwfClient::startWorkflowExecution (const StartWorkflowExecutionRequest & request) slot
Starts an execution of the workflow type in the specified domain using the provided workflowId and input
data>
This action returns the newly started workflow
execution>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
Constrain the following parameters by using a Condition element with the appropriate
keys>
tagList.member.0: The key is
swf:tagList.member.0>
tagList.member.1: The key is
swf:tagList.member.1>
tagList.member.2: The key is
swf:tagList.member.2>
tagList.member.3: The key is
swf:tagList.member.3>
tagList.member.4: The key is
swf:tagList.member.4>
taskList: String constraint. The key is
swf:taskList.name>
workflowType.name: String constraint. The key is
swf:workflowType.name>
workflowType.version: String constraint. The key is
swf:workflowType.version>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1768 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartWorkflowExecutionResponse *>(send(request));
 }
terminateWorkflowExecution
TerminateWorkflowExecutionResponse * QtAws::SWF::SwfClient::terminateWorkflowExecution (const TerminateWorkflowExecutionRequest & request) slot
Records a WorkflowExecutionTerminated event and forces closure of the workflow execution identified by the given domain, runId, and workflowId. The child policy, registered with the workflow type or specified when starting this execution, is applied to any open child workflow executions of this workflow
execution>
If the identified workflow execution was in progress, it is terminated
immediately> <note>
If a runId isn't specified, then the WorkflowExecutionTerminated event is recorded in the history of the current open workflow with the matching workflowId in the
domain> </note> <note>
You should consider using RequestCancelWorkflowExecution action instead because it allows the workflow to gracefully close while TerminateWorkflowExecution
doesn't> </note>
Access Control
</p
You can use IAM policies to control this action's access to Amazon SWF resources as
follows>
Use a Resource element with the domain name to limit the action to only specified
domains>
Use an Action element to allow or deny permission to call this
action>
You cannot use an IAM policy to constrain this action's
parameters>
If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's cause parameter is set to OPERATION_NOT_PERMITTED. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer
Parameters
request Request to send to Amazon Simple Workflow Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1826 of file swfclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TerminateWorkflowExecutionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
swf/swfclient.h
swf/swfclient.cpp