AWS SDK for Qt: QtAws::CostExplorer::CostExplorerClient Class Reference
QtAws::CostExplorer::CostExplorerClient Class Reference
Client for AWS Cost Explorer Service.
Public Slots
GetCostAndUsageResponse * getCostAndUsage (const GetCostAndUsageRequest &request)
GetDimensionValuesResponse * getDimensionValues (const GetDimensionValuesRequest &request)
GetReservationCoverageResponse * getReservationCoverage (const GetReservationCoverageRequest &request)
GetReservationPurchaseRecommendationResponse * getReservationPurchaseRecommendation (const GetReservationPurchaseRecommendationRequest &request)
GetReservationUtilizationResponse * getReservationUtilization (const GetReservationUtilizationRequest &request)
GetTagsResponse * getTags (const GetTagsRequest &request)
Public Member Functions
CostExplorerClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CostExplorerClient object.
CostExplorerClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CostExplorerClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Cost Explorer Service.
The Cost Explorer API allows you to programmatically query your cost and usage data. You can query for aggregated data such as total monthly costs or total daily usage. You can also query for granular data, such as the number of daily write operations for DynamoDB database tables in your production environment.
The Cost Explorer API provides the following
endpoint>
Definition at line 44 of file costexplorerclient.h.
Constructor & Destructor Documentation
CostExplorerClient() [1/2]
QtAws::CostExplorer::CostExplorerClient::CostExplorerClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CostExplorerClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 71 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CostExplorerClientPrivate(this), parent)
 {
     Q_D(CostExplorerClient);
     d->apiVersion = QStringLiteral("2017-10-25");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("ce");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Cost Explorer Service");
     d->serviceName = QStringLiteral("ce");
 }
CostExplorerClient() [2/2]
QtAws::CostExplorer::CostExplorerClient::CostExplorerClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CostExplorerClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 104 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CostExplorerClientPrivate(this), parent)
 {
     Q_D(CostExplorerClient);
     d->apiVersion = QStringLiteral("2017-10-25");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("ce");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Cost Explorer Service");
     d->serviceName = QStringLiteral("ce");
 }
Member Function Documentation
getCostAndUsage
GetCostAndUsageResponse * QtAws::CostExplorer::CostExplorerClient::getCostAndUsage (const GetCostAndUsageRequest & request) slot
Retrieves cost and usage metrics for your account. You can specify which cost and usage-related metric, such as BlendedCosts or UsageQuantity, that you want the request to return. You can also filter and group your data by various dimensions, such as SERVICE or AZ, in a specific time range. For a complete list of valid dimensions, see the GetDimensionValues operation. Master accounts in an organization in AWS Organizations have access to all member
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 135 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCostAndUsageResponse *>(send(request));
 }
getDimensionValues
GetDimensionValuesResponse * QtAws::CostExplorer::CostExplorerClient::getDimensionValues (const GetDimensionValuesRequest & request) slot
Retrieves all available filter values for a specific filter over a period of time. You can search the dimension values for an arbitrary string.
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 150 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDimensionValuesResponse *>(send(request));
 }
getReservationCoverage
GetReservationCoverageResponse * QtAws::CostExplorer::CostExplorerClient::getReservationCoverage (const GetReservationCoverageRequest & request) slot
Retrieves the reservation coverage for your account. This allows you to see how much of your Amazon Elastic Compute Cloud, Amazon ElastiCache, Amazon Relational Database Service, or Amazon Redshift usage is covered by a reservation. An organization's master account can see the coverage of the associated member accounts. For any time period, you can filter data about reservation usage by the following
dimensions>
A>
INSTANCE_TYP>
LINKED_ACCOUN>
PLATFOR>
REGIO>
TENANC>
To determine valid values for a dimension, use the GetDimensionValues operation.
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 183 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReservationCoverageResponse *>(send(request));
 }
getReservationPurchaseRecommendation
GetReservationPurchaseRecommendationResponse * QtAws::CostExplorer::CostExplorerClient::getReservationPurchaseRecommendation (const GetReservationPurchaseRecommendationRequest & request) slot
Gets recommendations for which reservations to purchase. These recommendations could help you reduce your costs. Reservations provide a discounted hourly rate (up to 75%) compared to On-Demand
pricing>
AWS generates your recommendations by identifying your On-Demand usage during a specific time period and collecting your usage into categories that are eligible for a reservation. After AWS has these categories, it simulates every combination of reservations in each category of usage to identify the best number of each type of RI to purchase to maximize your estimated savings.
</p
For example, AWS automatically aggregates your EC2 Linux, shared tenancy, and c4 family usage in the US West (Oregon) Region and recommends that you buy size-flexible regional reservations to apply to the c4 family usage. AWS recommends the smallest size instance in an instance family. This makes it easier to purchase a size-flexible RI. AWS also shows the equal number of normalized units so that you can purchase any instance size that you want. For this example, your RI recommendation would be for c4.large, because that is the smallest size instance in the c4 instance
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 213 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReservationPurchaseRecommendationResponse *>(send(request));
 }
getReservationUtilization
GetReservationUtilizationResponse * QtAws::CostExplorer::CostExplorerClient::getReservationUtilization (const GetReservationUtilizationRequest & request) slot
You can retrieve the reservation utilization for your account. Master accounts in an organization in AWS Organizations have access to their associated member accounts. You can filter data by dimensions in a time period. You can use GetDimensionValues to determine the possible dimension values. Currently, you can group only by SUBSCRIPTION_ID.
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetReservationUtilizationResponse *>(send(request));
 }
getTags
GetTagsResponse * QtAws::CostExplorer::CostExplorerClient::getTags (const GetTagsRequest & request) slot
You can query for available tag keys and tag values for a specified period. You can search the tag values for an arbitrary string.
Parameters
request Request to send to AWS Cost Explorer Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file costexplorerclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTagsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
ce/costexplorerclient.h
ce/costexplorerclient.cpp