AWS SDK for Qt: QtAws::Lambda::LambdaClient Class Reference
QtAws::Lambda::LambdaClient Class Reference
Client for AWS Lambda.
Public Slots
AddPermissionResponse * addPermission (const AddPermissionRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateEventSourceMappingResponse * createEventSourceMapping (const CreateEventSourceMappingRequest &request)
CreateFunctionResponse * createFunction (const CreateFunctionRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteEventSourceMappingResponse * deleteEventSourceMapping (const DeleteEventSourceMappingRequest &request)
DeleteFunctionResponse * deleteFunction (const DeleteFunctionRequest &request)
DeleteFunctionConcurrencyResponse * deleteFunctionConcurrency (const DeleteFunctionConcurrencyRequest &request)
GetAccountSettingsResponse * getAccountSettings (const GetAccountSettingsRequest &request)
GetAliasResponse * getAlias (const GetAliasRequest &request)
GetEventSourceMappingResponse * getEventSourceMapping (const GetEventSourceMappingRequest &request)
GetFunctionResponse * getFunction (const GetFunctionRequest &request)
GetFunctionConfigurationResponse * getFunctionConfiguration (const GetFunctionConfigurationRequest &request)
GetPolicyResponse * getPolicy (const GetPolicyRequest &request)
InvokeResponse * invoke (const InvokeRequest &request)
InvokeAsyncResponse * invokeAsync (const InvokeAsyncRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListEventSourceMappingsResponse * listEventSourceMappings (const ListEventSourceMappingsRequest &request)
ListFunctionsResponse * listFunctions (const ListFunctionsRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
ListVersionsByFunctionResponse * listVersionsByFunction (const ListVersionsByFunctionRequest &request)
PublishVersionResponse * publishVersion (const PublishVersionRequest &request)
PutFunctionConcurrencyResponse * putFunctionConcurrency (const PutFunctionConcurrencyRequest &request)
RemovePermissionResponse * removePermission (const RemovePermissionRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateAliasResponse * updateAlias (const UpdateAliasRequest &request)
UpdateEventSourceMappingResponse * updateEventSourceMapping (const UpdateEventSourceMappingRequest &request)
UpdateFunctionCodeResponse * updateFunctionCode (const UpdateFunctionCodeRequest &request)
UpdateFunctionConfigurationResponse * updateFunctionConfiguration (const UpdateFunctionConfigurationRequest &request)
Public Member Functions
LambdaClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
LambdaClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Lambda.
<fullname>AWS Lambda</fullname>
Overview
</p
This is the AWS Lambda API Reference. The AWS Lambda Developer Guide provides additional information. For the service overview, see What is AWS Lambda, and for information about how the service works, see AWS Lambda: How it Works in the AWS Lambda Developer
Definition at line 92 of file lambdaclient.h.
Constructor & Destructor Documentation
LambdaClient() [1/2]
QtAws::Lambda::LambdaClient::LambdaClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 117 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->apiVersion = QStringLiteral("2015-03-31");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("lambda");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Lambda");
     d->serviceName = QStringLiteral("lambda");
 }
LambdaClient() [2/2]
QtAws::Lambda::LambdaClient::LambdaClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 150 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->apiVersion = QStringLiteral("2015-03-31");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("lambda");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Lambda");
     d->serviceName = QStringLiteral("lambda");
 }
Member Function Documentation
addPermission
AddPermissionResponse * QtAws::Lambda::LambdaClient::addPermission (const AddPermissionRequest & request) slot
Adds a permission to the resource policy associated with the specified AWS Lambda function. You use resource policies to grant permissions to event sources that use push model. In a push model, event sources (such as Amazon S3 and custom applications) invoke your Lambda function. Each permission you add to the resource policy allows an event source, permission to invoke the Lambda function.
</p
For information about the push model, see AWS Lambda: How it Works.
</p
If you are using versioning, the permissions you add are specific to the Lambda function version or alias you specify in the AddPermission request via the Qualifier parameter. For more information about versioning, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:AddPermission
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 195 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddPermissionResponse *>(send(request));
 }
createAlias
CreateAliasResponse * QtAws::Lambda::LambdaClient::createAlias (const CreateAliasRequest & request) slot
Creates an alias that points to the specified Lambda function version. For more information, see Introduction to AWS Lambda Aliases>
Alias names are unique for a given function. This requires permission for the lambda:CreateAlias
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAliasResponse *>(send(request));
 }
createEventSourceMapping
CreateEventSourceMappingResponse * QtAws::Lambda::LambdaClient::createEventSourceMapping (const CreateEventSourceMappingRequest & request) slot
Identifies a stream as an event source for a Lambda function. It can be either an Amazon Kinesis stream or an Amazon DynamoDB stream. AWS Lambda invokes the specified function when records are posted to the
stream>
This association between a stream source and a Lambda function is called the event source
mapping>
This event source mapping is relevant only in the AWS Lambda pull model, where AWS Lambda invokes the function. For more information, see AWS Lambda: How it Works in the AWS Lambda Developer
Guide>
You provide mapping information (for example, which stream to read from and which Lambda function to invoke) in the request
body>
Each event source, such as an Amazon Kinesis or a DynamoDB stream, can be associated with multiple AWS Lambda function. A given Lambda function can be associated with multiple AWS event
sources>
If you are using versioning, you can specify a specific function version or an alias via the function name parameter. For more information about versioning, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:CreateEventSourceMapping
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 260 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEventSourceMappingResponse *>(send(request));
 }
createFunction
CreateFunctionResponse * QtAws::Lambda::LambdaClient::createFunction (const CreateFunctionRequest & request) slot
Creates a new Lambda function. The function metadata is created from the request parameters, and the code for the function is provided by a .zip file in the request body. If the function name already exists, the operation will fail. Note that the function name is
case-sensitive>
If you are using versioning, you can also publish a version of the Lambda function you are creating using the Publish parameter. For more information about versioning, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:CreateFunction
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 287 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFunctionResponse *>(send(request));
 }
deleteAlias
DeleteAliasResponse * QtAws::Lambda::LambdaClient::deleteAlias (const DeleteAliasRequest & request) slot
Deletes the specified Lambda function alias. For more information, see Introduction to AWS Lambda Aliases>
This requires permission for the lambda:DeleteAlias
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAliasResponse *>(send(request));
 }
deleteEventSourceMapping
DeleteEventSourceMappingResponse * QtAws::Lambda::LambdaClient::deleteEventSourceMapping (const DeleteEventSourceMappingRequest & request) slot
Removes an event source mapping. This means AWS Lambda will no longer invoke the function for events in the associated
source>
This operation requires permission for the lambda:DeleteEventSourceMapping
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 324 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEventSourceMappingResponse *>(send(request));
 }
deleteFunction
DeleteFunctionResponse * QtAws::Lambda::LambdaClient::deleteFunction (const DeleteFunctionRequest & request) slot
Deletes the specified Lambda function code and
configuration>
If you are using the versioning feature and you don't specify a function version in your DeleteFunction request, AWS Lambda will delete the function, including all its versions, and any aliases pointing to the function versions. To delete a specific function version, you must provide the function version via the Qualifier parameter. For information about function versioning, see AWS Lambda Function Versioning and Aliases.
</p
When you delete a function the associated resource policy is also deleted. You will need to delete the event source mappings
explicitly>
This operation requires permission for the lambda:DeleteFunction
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 356 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFunctionResponse *>(send(request));
 }
deleteFunctionConcurrency
DeleteFunctionConcurrencyResponse * QtAws::Lambda::LambdaClient::deleteFunctionConcurrency (const DeleteFunctionConcurrencyRequest & request) slot
Removes concurrent execution limits from this function. For more information, see
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 370 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFunctionConcurrencyResponse *>(send(request));
 }
getAccountSettings
GetAccountSettingsResponse * QtAws::Lambda::LambdaClient::getAccountSettings (const GetAccountSettingsRequest & request) slot
Returns a customer's account
settings>
You can use this operation to retrieve Lambda limits information, such as code size and concurrency limits. For more information about limits, see AWS Lambda Limits. You can also retrieve resource usage statistics, such as code storage usage and function
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 390 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountSettingsResponse *>(send(request));
 }
getAlias
GetAliasResponse * QtAws::Lambda::LambdaClient::getAlias (const GetAliasRequest & request) slot
Returns the specified alias information such as the alias ARN, description, and function version it is pointing to. For more information, see Introduction to AWS Lambda Aliases>
This requires permission for the lambda:GetAlias
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 410 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAliasResponse *>(send(request));
 }
getEventSourceMapping
GetEventSourceMappingResponse * QtAws::Lambda::LambdaClient::getEventSourceMapping (const GetEventSourceMappingRequest & request) slot
Returns configuration information for the specified event source mapping (see
CreateEventSourceMapping)>
This operation requires permission for the lambda:GetEventSourceMapping
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 428 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEventSourceMappingResponse *>(send(request));
 }
getFunction
GetFunctionResponse * QtAws::Lambda::LambdaClient::getFunction (const GetFunctionRequest & request) slot
Returns the configuration information of the Lambda function and a presigned URL link to the .zip file you uploaded with CreateFunction so you can download the .zip file. Note that the URL is valid for up to 10 minutes. The configuration information is the same information you provided as parameters when uploading the
function>
Using the optional Qualifier parameter, you can specify a specific function version for which you want this information. If you don't specify this parameter, the API uses unqualified function ARN which return information about the $LATEST version of the Lambda function. For more information, see AWS Lambda Function Versioning and Aliases>
This operation requires permission for the lambda:GetFunction
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 455 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetFunctionResponse *>(send(request));
 }
getFunctionConfiguration
GetFunctionConfigurationResponse * QtAws::Lambda::LambdaClient::getFunctionConfiguration (const GetFunctionConfigurationRequest & request) slot
Returns the configuration information of the Lambda function. This the same information you provided as parameters when uploading the function by using
CreateFunction>
If you are using the versioning feature, you can retrieve this information for a specific function version by using the optional Qualifier parameter and specifying the function version or alias that points to it. If you don't provide it, the API returns information about the $LATEST version of the function. For more information about versioning, see AWS Lambda Function Versioning and Aliases>
This operation requires permission for the lambda:GetFunctionConfiguration
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 482 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetFunctionConfigurationResponse *>(send(request));
 }
getPolicy
GetPolicyResponse * QtAws::Lambda::LambdaClient::getPolicy (const GetPolicyRequest & request) slot
Returns the resource policy associated with the specified Lambda
function>
If you are using the versioning feature, you can get the resource policy associated with the specific Lambda function version or alias by specifying the version or alias name using the Qualifier parameter. For more information about versioning, see AWS Lambda Function Versioning and Aliases.
</p
You need permission for the lambda:GetPolicy action.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 507 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPolicyResponse *>(send(request));
 }
invoke
InvokeResponse * QtAws::Lambda::LambdaClient::invoke (const InvokeRequest & request) slot
Invokes a specific Lambda function. For an example, see Create the Lambda Function and Test It Manually.
</p
If you are using the versioning feature, you can invoke the specific function version by providing function version or alias name that is pointing to the function version using the Qualifier parameter in the request. If you don't provide the Qualifier parameter, the $LATEST version of the Lambda function is invoked. Invocations occur at least once in response to an event and functions must be idempotent to handle this. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:InvokeFunction
action> <note>
The TooManyRequestsException noted below will return the following: ConcurrentInvocationLimitExceeded will be returned if you have no functions with reserved concurrency and have exceeded your account concurrent limit or if a function without reserved concurrency exceeds the account's unreserved concurrency limit. ReservedFunctionConcurrentInvocationLimitExceeded will be returned when a function with reserved concurrency exceeds its configured concurrency limit.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 544 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InvokeResponse *>(send(request));
 }
invokeAsync
InvokeAsyncResponse * QtAws::Lambda::LambdaClient::invokeAsync (const InvokeAsyncRequest & request) slot
This API is deprecated. We recommend you use Invoke API (see
Invoke)>
Submits an invocation request to AWS Lambda. Upon receiving the request, Lambda executes the specified function asynchronously. To see the logs generated by the Lambda function execution, see the CloudWatch Logs
console>
This operation requires permission for the lambda:InvokeFunction
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 569 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InvokeAsyncResponse *>(send(request));
 }
listAliases
ListAliasesResponse * QtAws::Lambda::LambdaClient::listAliases (const ListAliasesRequest & request) slot
Returns list of aliases created for a Lambda function. For each alias, the response includes information such as the alias ARN, description, alias name, and the function version to which it points. For more information, see Introduction to AWS Lambda Aliases>
This requires permission for the lambda:ListAliases
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 589 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAliasesResponse *>(send(request));
 }
listEventSourceMappings
ListEventSourceMappingsResponse * QtAws::Lambda::LambdaClient::listEventSourceMappings (const ListEventSourceMappingsRequest & request) slot
Returns a list of event source mappings you created using the CreateEventSourceMapping (see CreateEventSourceMapping).
</p
For each mapping, the API returns configuration information. You can optionally specify filters to retrieve specific event source
mappings>
If you are using the versioning feature, you can get list of event source mappings for a specific Lambda function version or an alias as described in the FunctionName parameter. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:ListEventSourceMappings
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 620 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListEventSourceMappingsResponse *>(send(request));
 }
listFunctions
ListFunctionsResponse * QtAws::Lambda::LambdaClient::listFunctions (const ListFunctionsRequest & request) slot
Returns a list of your Lambda functions. For each function, the response includes the function configuration information. You must use GetFunction to retrieve the code for your
function>
This operation requires permission for the lambda:ListFunctions
action>
If you are using the versioning feature, you can list all of your functions or only $LATEST versions. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 646 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListFunctionsResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::Lambda::LambdaClient::listTags (const ListTagsRequest & request) slot
Returns a list of tags assigned to a function when supplied the function ARN (Amazon Resource
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 660 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
listVersionsByFunction
ListVersionsByFunctionResponse * QtAws::Lambda::LambdaClient::listVersionsByFunction (const ListVersionsByFunctionRequest & request) slot
List all versions of a function. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 676 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListVersionsByFunctionResponse *>(send(request));
 }
publishVersion
PublishVersionResponse * QtAws::Lambda::LambdaClient::publishVersion (const PublishVersionRequest & request) slot
Publishes a version of your function from the current snapshot of $LATEST. That is, AWS Lambda takes a snapshot of the function code and configuration information from $LATEST and publishes a new version. The code and configuration cannot be modified after publication. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 694 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PublishVersionResponse *>(send(request));
 }
putFunctionConcurrency
PutFunctionConcurrencyResponse * QtAws::Lambda::LambdaClient::putFunctionConcurrency (const PutFunctionConcurrencyRequest & request) slot
Sets a limit on the number of concurrent executions available to this function. It is a subset of your account's total concurrent execution limit per region. Note that Lambda automatically reserves a buffer of 100 concurrent executions for functions without any reserved concurrency limit. This means if your account limit is 1000, you have a total of 900 available to allocate to individual functions. For more information, see
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 711 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutFunctionConcurrencyResponse *>(send(request));
 }
removePermission
RemovePermissionResponse * QtAws::Lambda::LambdaClient::removePermission (const RemovePermissionRequest & request) slot
You can remove individual permissions from an resource policy associated with a Lambda function by providing a statement ID that you provided when you added the
permission>
If you are using versioning, the permissions you remove are specific to the Lambda function version or alias you specify in the AddPermission request via the Qualifier parameter. For more information about versioning, see AWS Lambda Function Versioning and Aliases.
You need permission for the lambda:RemovePermission
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 741 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemovePermissionResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::Lambda::LambdaClient::tagResource (const TagResourceRequest & request) slot
Creates a list of tags (key-value pairs) on the Lambda function. Requires the Lambda function ARN (Amazon Resource Name). If a key is specified without a value, Lambda creates a tag with the specified key and a value of null.
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 756 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::Lambda::LambdaClient::untagResource (const UntagResourceRequest & request) slot
Removes tags from a Lambda function. Requires the function ARN (Amazon Resource Name).
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 770 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateAlias
UpdateAliasResponse * QtAws::Lambda::LambdaClient::updateAlias (const UpdateAliasRequest & request) slot
Using this API you can update the function version to which the alias points and the alias description. For more information, see Introduction to AWS Lambda Aliases>
This requires permission for the lambda:UpdateAlias
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 789 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAliasResponse *>(send(request));
 }
updateEventSourceMapping
UpdateEventSourceMappingResponse * QtAws::Lambda::LambdaClient::updateEventSourceMapping (const UpdateEventSourceMappingRequest & request) slot
You can update an event source mapping. This is useful if you want to change the parameters of the existing mapping without losing your position in the stream. You can change which function will receive the stream records, but to change the stream itself, you must create a new
mapping>
If you are using the versioning feature, you can update the event source mapping to map to a specific Lambda function version or alias as described in the FunctionName parameter. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
</p
If you disable the event source mapping, AWS Lambda stops polling. If you enable again, it will resume polling from the time it had stopped polling, so you don't lose processing of any records. However, if you delete event source mapping and create it again, it will
reset>
This operation requires permission for the lambda:UpdateEventSourceMapping
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 822 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateEventSourceMappingResponse *>(send(request));
 }
updateFunctionCode
UpdateFunctionCodeResponse * QtAws::Lambda::LambdaClient::updateFunctionCode (const UpdateFunctionCodeRequest & request) slot
Updates the code for the specified Lambda function. This operation must only be used on an existing Lambda function and cannot be used to update the function
configuration>
If you are using the versioning feature, note this API will always update the $LATEST version of your Lambda function. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:UpdateFunctionCode
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 848 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFunctionCodeResponse *>(send(request));
 }
updateFunctionConfiguration
UpdateFunctionConfigurationResponse * QtAws::Lambda::LambdaClient::updateFunctionConfiguration (const UpdateFunctionConfigurationRequest & request) slot
Updates the configuration parameters for the specified Lambda function by using the values provided in the request. You provide only the parameters you want to change. This operation must only be used on an existing Lambda function and cannot be used to update the function's
code>
If you are using the versioning feature, note this API will always update the $LATEST version of your Lambda function. For information about the versioning feature, see AWS Lambda Function Versioning and Aliases.
</p
This operation requires permission for the lambda:UpdateFunctionConfiguration
Parameters
request Request to send to AWS Lambda.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 875 of file lambdaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFunctionConfigurationResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
lambda/lambdaclient.h
lambda/lambdaclient.cpp