AWS SDK for Qt: QtAws::CloudHSMV2::CloudHSMV2Client Class Reference
QtAws::CloudHSMV2::CloudHSMV2Client Class Reference
Client for AWS CloudHSM V2.
Public Slots
CreateClusterResponse * createCluster (const CreateClusterRequest &request)
CreateHsmResponse * createHsm (const CreateHsmRequest &request)
DeleteClusterResponse * deleteCluster (const DeleteClusterRequest &request)
DeleteHsmResponse * deleteHsm (const DeleteHsmRequest &request)
DescribeBackupsResponse * describeBackups (const DescribeBackupsRequest &request)
DescribeClustersResponse * describeClusters (const DescribeClustersRequest &request)
InitializeClusterResponse * initializeCluster (const InitializeClusterRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
Public Member Functions
CloudHSMV2Client (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMV2Client object.
CloudHSMV2Client (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMV2Client object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CloudHSM V2.
For more information about AWS CloudHSM, see AWS CloudHSM and the AWS CloudHSM User
Definition at line 52 of file cloudhsmv2client.h.
Constructor & Destructor Documentation
CloudHSMV2Client() [1/2]
QtAws::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMV2Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudHSMV2ClientPrivate(this), parent)
 {
     Q_D(CloudHSMV2Client);
     d->apiVersion = QStringLiteral("2017-04-28");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudhsmv2");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CloudHSM V2");
     d->serviceName = QStringLiteral("cloudhsm");
 }
CloudHSMV2Client() [2/2]
QtAws::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMV2Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 101 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudHSMV2ClientPrivate(this), parent)
 {
     Q_D(CloudHSMV2Client);
     d->apiVersion = QStringLiteral("2017-04-28");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudhsmv2");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CloudHSM V2");
     d->serviceName = QStringLiteral("cloudhsm");
 }
Member Function Documentation
createCluster
CreateClusterResponse * QtAws::CloudHSMV2::CloudHSMV2Client::createCluster (const CreateClusterRequest & request) slot
Creates a new AWS CloudHSM
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 127 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateClusterResponse *>(send(request));
 }
createHsm
CreateHsmResponse * QtAws::CloudHSMV2::CloudHSMV2Client::createHsm (const CreateHsmRequest & request) slot
Creates a new hardware security module (HSM) in the specified AWS CloudHSM
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 141 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHsmResponse *>(send(request));
 }
deleteCluster
DeleteClusterResponse * QtAws::CloudHSMV2::CloudHSMV2Client::deleteCluster (const DeleteClusterRequest & request) slot
Deletes the specified AWS CloudHSM cluster. Before you can delete a cluster, you must delete all HSMs in the cluster. To see if the cluster contains any HSMs, use DescribeClusters. To delete an HSM, use
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 156 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteClusterResponse *>(send(request));
 }
deleteHsm
DeleteHsmResponse * QtAws::CloudHSMV2::CloudHSMV2Client::deleteHsm (const DeleteHsmRequest & request) slot
Deletes the specified HSM. To specify an HSM, you can use its identifier (ID), the IP address of the HSM's elastic network interface (ENI), or the ID of the HSM's ENI. You need to specify only one of these values. To find these values, use
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 172 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHsmResponse *>(send(request));
 }
describeBackups
DescribeBackupsResponse * QtAws::CloudHSMV2::CloudHSMV2Client::describeBackups (const DescribeBackupsRequest & request) slot
Gets information about backups of AWS CloudHSM
clusters>
This is a paginated operation, which means that each response might contain only a subset of all the backups. When the response contains only a subset of backups, it includes a NextToken value. Use this value in a subsequent DescribeBackups request to get more backups. When you receive a response with no NextToken (or an empty or null value), that means there are no more backups to
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 193 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBackupsResponse *>(send(request));
 }
describeClusters
DescribeClustersResponse * QtAws::CloudHSMV2::CloudHSMV2Client::describeClusters (const DescribeClustersRequest & request) slot
Gets information about AWS CloudHSM
clusters>
This is a paginated operation, which means that each response might contain only a subset of all the clusters. When the response contains only a subset of clusters, it includes a NextToken value. Use this value in a subsequent DescribeClusters request to get more clusters. When you receive a response with no NextToken (or an empty or null value), that means there are no more clusters to
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeClustersResponse *>(send(request));
 }
initializeCluster
InitializeClusterResponse * QtAws::CloudHSMV2::CloudHSMV2Client::initializeCluster (const InitializeClusterRequest & request) slot
Claims an AWS CloudHSM cluster by submitting the cluster certificate issued by your issuing certificate authority (CA) and the CA's root certificate. Before you can claim a cluster, you must sign the cluster's certificate signing request (CSR) with your issuing CA. To get the cluster's CSR, use
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InitializeClusterResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::CloudHSMV2::CloudHSMV2Client::listTags (const ListTagsRequest & request) slot
Gets a list of tags for the specified AWS CloudHSM
cluster>
This is a paginated operation, which means that each response might contain only a subset of all the tags. When the response contains only a subset of tags, it includes a NextToken value. Use this value in a subsequent ListTags request to get more tags. When you receive a response with no NextToken (or an empty or null value), that means there are no more tags to
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 251 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::CloudHSMV2::CloudHSMV2Client::tagResource (const TagResourceRequest & request) slot
Adds or overwrites one or more tags for the specified AWS CloudHSM
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 265 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::CloudHSMV2::CloudHSMV2Client::untagResource (const UntagResourceRequest & request) slot
Removes the specified tag or tags from the specified AWS CloudHSM
Parameters
request Request to send to AWS CloudHSM V2.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 279 of file cloudhsmv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudhsmv2/cloudhsmv2client.h
cloudhsmv2/cloudhsmv2client.cpp