AWS SDK for Qt: QtAws::SqsOld::SqsResponsePrivate Class Reference
QtAws::SqsOld::SqsResponsePrivate Class Reference
Private implementation for SqsResponse.
Public Member Functions
SqsResponsePrivate (SqsResponse *const q)
Constructs a new SqsResponsePrivate object.
void parseErrorResponse (QXmlStreamReader &xml)
Parse an SQS ErrorResponse element.
void parseResponseMetadata (QXmlStreamReader &xml)
Parse an SQS ResponseMetadata element.
Public Attributes
SqsErrorList errors
SQS errors.
QString requestId
SQS request ID.
Detailed Description
Private implementation for SqsResponse.
Definition at line 33 of file sqsresponse_p.h.
Constructor & Destructor Documentation
SqsResponsePrivate()
QtAws::SqsOld::SqsResponsePrivate::SqsResponsePrivate (SqsResponse *const q)
Constructs a new SqsResponsePrivate object.
Parameters
q Pointer to this object's public SqsResponse instance.
Definition at line 181 of file sqsresponse.cpp.
     : AwsAbstractResponsePrivate(q)
 {
 }
Member Function Documentation
parseErrorResponse()
void QtAws::SqsOld::SqsResponsePrivate::parseErrorResponse (QXmlStreamReader & xml)
Parse an SQS ErrorResponse element.
This implementation parses SQS ErrorResponse elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<ErrorResponse>
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>Access to the resource http://sqs.us-east-1.amazonaws.com/ is denied.</Message>
    <Detail/>
  </Error>
  <Error>
    ...
  </Error>
  <RequestId>9a285199-c8d6-47c2-bdb2-314cb47d599d</RequestId>
</ErrorResponse>
Parameters
xml XML stream to parse.
Note
Unlike most other SQS responses, the SQS ErrorResponse does not wrap the RequestId element in a ResponseMetadata element.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 216 of file sqsresponse.cpp.
References errors, and requestId.
 {
     Q_ASSERT(xml.name() == QLatin1String("ErrorResponse"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("Error")) {
             errors.append(SqsError(xml));
         } else if (xml.name() == QLatin1String("RequestId")) {
             requestId = xml.readElementText();
         } else {
            qWarning() << "ignoring" << xml.name();
            xml.skipCurrentElement();
         }
     }
 }
parseResponseMetadata()
void QtAws::SqsOld::SqsResponsePrivate::parseResponseMetadata (QXmlStreamReader & xml)
Parse an SQS ResponseMetadata element.
This implementation parses SQS ResponseMetadata elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<ResponseMetadata>
  <RequestId>9a285199-c8d6-47c2-bdb2-314cb47d599d</RequestId>
</ResponseMetadata>
Parameters
xml XML stream to parse.
Note
This function is not actually used by the SqsResponse or SqsResponsePrivate classes, but provides common functionality employed by most (if not all) derived SqsResponse classes, as the ResponseMetadata element is common to most (if not all) successful SQS responses (its simply not used in the SQS ErrorResponse element).
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 254 of file sqsresponse.cpp.
References requestId.
Referenced by QtAws::SqsOld::SqsAddPermissionResponsePrivate::parseAddPermissionResponse(), QtAws::SqsOld::SqsChangeMessageVisibilityBatchResponsePrivate::parseChangeMessageVisibilityBatchResponse(), QtAws::SqsOld::SqsChangeMessageVisibilityResponsePrivate::parseChangeMessageVisibilityResponse(), QtAws::SqsOld::SqsCreateQueueResponsePrivate::parseCreateQueueResponse(), QtAws::SqsOld::SqsDeleteMessageBatchResponsePrivate::parseDeleteMessageBatchResponse(), QtAws::SqsOld::SqsDeleteMessageResponsePrivate::parseDeleteMessageResponse(), QtAws::SqsOld::SqsDeleteQueueResponsePrivate::parseDeleteQueueResponse(), QtAws::SqsOld::SqsGetQueueAttributesResponsePrivate::parseGetQueueAttributesResponse(), QtAws::SqsOld::SqsGetQueueUrlResponsePrivate::parseGetQueueUrlResponse(), QtAws::SqsOld::SqsListDeadLetterSourceQueuesResponsePrivate::parseListDeadLetterSourceQueuesResponse(), QtAws::SqsOld::SqsListQueuesResponsePrivate::parseListQueuesResponse(), QtAws::SqsOld::SqsPurgeQueueResponsePrivate::parsePurgeQueueResponse(), QtAws::SqsOld::SqsReceiveMessageResponsePrivate::parseReceiveMessageResponse(), QtAws::SqsOld::SqsRemovePermissionResponsePrivate::parseRemovePermissionResponse(), QtAws::SqsOld::SqsSendMessageBatchResponsePrivate::parseSendMessageBatchResponse(), QtAws::SqsOld::SqsSendMessageResponsePrivate::parseSendMessageResponse(), and QtAws::SqsOld::SqsSetQueueAttributesResponsePrivate::parseSetQueueAttributesResponse().
 {
     Q_ASSERT(xml.name() == QLatin1String("ResponseMetadata"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("RequestId")) {
             requestId = xml.readElementText();
         } else {
            qWarning() << "ignoring" << xml.name();
            xml.skipCurrentElement();
         }
     }
 }
The documentation for this class was generated from the following files:
sqs-old/sqsresponse_p.h
sqs-old/sqsresponse.cpp