AWS SDK for Qt: QtAws::WorkMail::WorkMailClient Class Reference
QtAws::WorkMail::WorkMailClient Class Reference
Client for Amazon WorkMail.
Public Slots
AssociateDelegateToResourceResponse * associateDelegateToResource (const AssociateDelegateToResourceRequest &request)
AssociateMemberToGroupResponse * associateMemberToGroup (const AssociateMemberToGroupRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
CreateResourceResponse * createResource (const CreateResourceRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
DeleteResourceResponse * deleteResource (const DeleteResourceRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DeregisterFromWorkMailResponse * deregisterFromWorkMail (const DeregisterFromWorkMailRequest &request)
DescribeGroupResponse * describeGroup (const DescribeGroupRequest &request)
DescribeOrganizationResponse * describeOrganization (const DescribeOrganizationRequest &request)
DescribeResourceResponse * describeResource (const DescribeResourceRequest &request)
DescribeUserResponse * describeUser (const DescribeUserRequest &request)
DisassociateDelegateFromResourceResponse * disassociateDelegateFromResource (const DisassociateDelegateFromResourceRequest &request)
DisassociateMemberFromGroupResponse * disassociateMemberFromGroup (const DisassociateMemberFromGroupRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListGroupMembersResponse * listGroupMembers (const ListGroupMembersRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
ListOrganizationsResponse * listOrganizations (const ListOrganizationsRequest &request)
ListResourceDelegatesResponse * listResourceDelegates (const ListResourceDelegatesRequest &request)
ListResourcesResponse * listResources (const ListResourcesRequest &request)
ListUsersResponse * listUsers (const ListUsersRequest &request)
RegisterToWorkMailResponse * registerToWorkMail (const RegisterToWorkMailRequest &request)
ResetPasswordResponse * resetPassword (const ResetPasswordRequest &request)
UpdatePrimaryEmailAddressResponse * updatePrimaryEmailAddress (const UpdatePrimaryEmailAddressRequest &request)
UpdateResourceResponse * updateResource (const UpdateResourceRequest &request)
Public Member Functions
WorkMailClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkMailClient object.
WorkMailClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkMailClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon WorkMail.
Amazon WorkMail is a secure, managed business email and calendaring service with support for existing desktop and mobile email clients. You can access your email, contacts, and calendars using Microsoft Outlook, your browser, or their native iOS and Android email applications. You can integrate Amazon WorkMail with your existing corporate directory and control both the keys that encrypt your data and the location in which your data is
stored>
The Amazon WorkMail API is designed for the following
scenarios>
Listing and describing
organization>
Managing
user>
Managing
group>
Managing
resource>
All Amazon WorkMail API actions are Amazon-authenticated and certificate-signed. They not only require the use of the AWS SDK, but also allow for the exclusive use of IAM users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the Amazon WorkMail site, the IAM user gains full administrative visibility into the entire Amazon WorkMail organization (or as set in the IAM policy). This includes, but is not limited to, the ability to create, update, and delete users, groups, and resources. This allows developers to perform the scenarios listed above, as well as give users the ability to grant access on a selective basis using the IAM
Definition at line 88 of file workmailclient.h.
Constructor & Destructor Documentation
WorkMailClient() [1/2]
QtAws::WorkMail::WorkMailClient::WorkMailClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkMailClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 135 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new WorkMailClientPrivate(this), parent)
 {
     Q_D(WorkMailClient);
     d->apiVersion = QStringLiteral("2017-10-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("workmail");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon WorkMail");
     d->serviceName = QStringLiteral("workmail");
 }
WorkMailClient() [2/2]
QtAws::WorkMail::WorkMailClient::WorkMailClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkMailClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 168 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new WorkMailClientPrivate(this), parent)
 {
     Q_D(WorkMailClient);
     d->apiVersion = QStringLiteral("2017-10-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("workmail");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon WorkMail");
     d->serviceName = QStringLiteral("workmail");
 }
Member Function Documentation
associateDelegateToResource
AssociateDelegateToResourceResponse * QtAws::WorkMail::WorkMailClient::associateDelegateToResource (const AssociateDelegateToResourceRequest & request) slot
Adds a member to the resource's set of
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 194 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateDelegateToResourceResponse *>(send(request));
 }
associateMemberToGroup
AssociateMemberToGroupResponse * QtAws::WorkMail::WorkMailClient::associateMemberToGroup (const AssociateMemberToGroupRequest & request) slot
Adds a member to the group's
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 208 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateMemberToGroupResponse *>(send(request));
 }
createAlias
CreateAliasResponse * QtAws::WorkMail::WorkMailClient::createAlias (const CreateAliasRequest & request) slot
Adds an alias to the set of a given member of Amazon
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 222 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAliasResponse *>(send(request));
 }
createGroup
CreateGroupResponse * QtAws::WorkMail::WorkMailClient::createGroup (const CreateGroupRequest & request) slot
Creates a group that can be used in Amazon WorkMail by calling the RegisterToWorkMail
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 236 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGroupResponse *>(send(request));
 }
createResource
CreateResourceResponse * QtAws::WorkMail::WorkMailClient::createResource (const CreateResourceRequest & request) slot
Creates a new Amazon WorkMail resource. The available types are equipment and
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 250 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateResourceResponse *>(send(request));
 }
createUser
CreateUserResponse * QtAws::WorkMail::WorkMailClient::createUser (const CreateUserRequest & request) slot
Creates a user who can be used in Amazon WorkMail by calling the RegisterToWorkMail
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 264 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserResponse *>(send(request));
 }
deleteAlias
DeleteAliasResponse * QtAws::WorkMail::WorkMailClient::deleteAlias (const DeleteAliasRequest & request) slot
Remove the alias from a set of aliases for a given
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAliasResponse *>(send(request));
 }
deleteGroup
DeleteGroupResponse * QtAws::WorkMail::WorkMailClient::deleteGroup (const DeleteGroupRequest & request) slot
Deletes a group from Amazon
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGroupResponse *>(send(request));
 }
deleteResource
DeleteResourceResponse * QtAws::WorkMail::WorkMailClient::deleteResource (const DeleteResourceRequest & request) slot
Deletes the specified resource.
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteResourceResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::WorkMail::WorkMailClient::deleteUser (const DeleteUserRequest & request) slot
Deletes a user from Amazon WorkMail and all subsequent systems. The action can't be undone. The mailbox is kept as-is for a minimum of 30 days, without any means to restore it.
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 321 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
deregisterFromWorkMail
DeregisterFromWorkMailResponse * QtAws::WorkMail::WorkMailClient::deregisterFromWorkMail (const DeregisterFromWorkMailRequest & request) slot
Mark a user, group, or resource as no longer used in Amazon WorkMail. This action disassociates the mailbox and schedules it for clean-up. Amazon WorkMail keeps mailboxes for 30 days before they are permanently removed. The functionality in the console is
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 337 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterFromWorkMailResponse *>(send(request));
 }
describeGroup
DescribeGroupResponse * QtAws::WorkMail::WorkMailClient::describeGroup (const DescribeGroupRequest & request) slot
Returns the data available for the
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGroupResponse *>(send(request));
 }
describeOrganization
DescribeOrganizationResponse * QtAws::WorkMail::WorkMailClient::describeOrganization (const DescribeOrganizationRequest & request) slot
Provides more information regarding a given organization based on its
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 365 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOrganizationResponse *>(send(request));
 }
describeResource
DescribeResourceResponse * QtAws::WorkMail::WorkMailClient::describeResource (const DescribeResourceRequest & request) slot
Returns the data available for the
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 379 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeResourceResponse *>(send(request));
 }
describeUser
DescribeUserResponse * QtAws::WorkMail::WorkMailClient::describeUser (const DescribeUserRequest & request) slot
Provides information regarding the
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 393 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserResponse *>(send(request));
 }
disassociateDelegateFromResource
DisassociateDelegateFromResourceResponse * QtAws::WorkMail::WorkMailClient::disassociateDelegateFromResource (const DisassociateDelegateFromResourceRequest & request) slot
Removes a member from the resource's set of
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 407 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateDelegateFromResourceResponse *>(send(request));
 }
disassociateMemberFromGroup
DisassociateMemberFromGroupResponse * QtAws::WorkMail::WorkMailClient::disassociateMemberFromGroup (const DisassociateMemberFromGroupRequest & request) slot
Removes a member from a
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 421 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateMemberFromGroupResponse *>(send(request));
 }
listAliases
ListAliasesResponse * QtAws::WorkMail::WorkMailClient::listAliases (const ListAliasesRequest & request) slot
Creates a paginated call to list the aliases associated with a given
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 435 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAliasesResponse *>(send(request));
 }
listGroupMembers
ListGroupMembersResponse * QtAws::WorkMail::WorkMailClient::listGroupMembers (const ListGroupMembersRequest & request) slot
Returns an overview of the members of a
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 449 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupMembersResponse *>(send(request));
 }
listGroups
ListGroupsResponse * QtAws::WorkMail::WorkMailClient::listGroups (const ListGroupsRequest & request) slot
Returns summaries of the organization's
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 463 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupsResponse *>(send(request));
 }
listOrganizations
ListOrganizationsResponse * QtAws::WorkMail::WorkMailClient::listOrganizations (const ListOrganizationsRequest & request) slot
Returns summaries of the customer's non-deleted
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 477 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOrganizationsResponse *>(send(request));
 }
listResourceDelegates
ListResourceDelegatesResponse * QtAws::WorkMail::WorkMailClient::listResourceDelegates (const ListResourceDelegatesRequest & request) slot
Lists the delegates associated with a resource. Users and groups can be resource delegates and answer requests on behalf of the
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 492 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListResourceDelegatesResponse *>(send(request));
 }
listResources
ListResourcesResponse * QtAws::WorkMail::WorkMailClient::listResources (const ListResourcesRequest & request) slot
Returns summaries of the organization's
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 506 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListResourcesResponse *>(send(request));
 }
listUsers
ListUsersResponse * QtAws::WorkMail::WorkMailClient::listUsers (const ListUsersRequest & request) slot
Returns summaries of the organization's
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 520 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUsersResponse *>(send(request));
 }
registerToWorkMail
RegisterToWorkMailResponse * QtAws::WorkMail::WorkMailClient::registerToWorkMail (const RegisterToWorkMailRequest & request) slot
Registers an existing and disabled user, group, or resource/entity for Amazon WorkMail use by associating a mailbox and calendaring capabilities. It performs no change if the entity is enabled and fails if the entity is deleted. This operation results in the accumulation of costs. For more information, see Pricing. The equivalent console functionality for this operation is Enable. Users can either be created by calling the CreateUser API or they can be synchronized from your directory. For more information, see
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 539 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterToWorkMailResponse *>(send(request));
 }
resetPassword
ResetPasswordResponse * QtAws::WorkMail::WorkMailClient::resetPassword (const ResetPasswordRequest & request) slot
Allows the administrator to reset the password for a
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 553 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetPasswordResponse *>(send(request));
 }
updatePrimaryEmailAddress
UpdatePrimaryEmailAddressResponse * QtAws::WorkMail::WorkMailClient::updatePrimaryEmailAddress (const UpdatePrimaryEmailAddressRequest & request) slot
Updates the primary email for an entity. The current email is moved into the list of aliases (or swapped between an existing alias and the current primary email) and the email provided in the input is promoted as the
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 568 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdatePrimaryEmailAddressResponse *>(send(request));
 }
updateResource
UpdateResourceResponse * QtAws::WorkMail::WorkMailClient::updateResource (const UpdateResourceRequest & request) slot
Updates data for the resource. It must be preceded by a describe call in order to have the latest information. The dataset in the request should be the one expected when performing another describe
Parameters
request Request to send to Amazon WorkMail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 583 of file workmailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateResourceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
workmail/workmailclient.h
workmail/workmailclient.cpp