AWS SDK for Qt: QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest Class Reference
QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest Class Reference
Interface class for providing DatabaseMigrationService requests.
Public Types
enum Action {
AddTagsToResourceAction, CreateEndpointAction, CreateEventSubscriptionAction, CreateReplicationInstanceAction,
CreateReplicationSubnetGroupAction, CreateReplicationTaskAction, DeleteCertificateAction, DeleteEndpointAction,
DeleteEventSubscriptionAction, DeleteReplicationInstanceAction, DeleteReplicationSubnetGroupAction, DeleteReplicationTaskAction,
DescribeAccountAttributesAction, DescribeCertificatesAction, DescribeConnectionsAction, DescribeEndpointTypesAction,
DescribeEndpointsAction, DescribeEventCategoriesAction, DescribeEventSubscriptionsAction, DescribeEventsAction,
DescribeOrderableReplicationInstancesAction, DescribeRefreshSchemasStatusAction, DescribeReplicationInstanceTaskLogsAction, DescribeReplicationInstancesAction,
DescribeReplicationSubnetGroupsAction, DescribeReplicationTaskAssessmentResultsAction, DescribeReplicationTasksAction, DescribeSchemasAction,
DescribeTableStatisticsAction, ImportCertificateAction, ListTagsForResourceAction, ModifyEndpointAction,
ModifyEventSubscriptionAction, ModifyReplicationInstanceAction, ModifyReplicationSubnetGroupAction, ModifyReplicationTaskAction,
RebootReplicationInstanceAction, RefreshSchemasAction, ReloadTablesAction, RemoveTagsFromResourceAction,
StartReplicationTaskAction, StartReplicationTaskAssessmentAction, StopReplicationTaskAction, TestConnectionAction
}
Actions supported by DatabaseMigrationService.
Public Member Functions
DatabaseMigrationServiceRequest (const Action action)
Constructs a new DatabaseMigrationServiceRequest object.
DatabaseMigrationServiceRequest (const DatabaseMigrationServiceRequest &other)
Constructs a new DatabaseMigrationServiceRequest object by copying another.
DatabaseMigrationServiceRequest & operator= (const DatabaseMigrationServiceRequest &other)
Assignment operator.
Action action () const
Get the DatabaseMigrationService action to be performed by this request.
QString actionString () const
Get the name of the DatabaseMigrationService action to be performed by this request.
QString apiVersion () const
Get the DatabaseMigrationService API version implemented by this request.
void setAction (const Action action)
Set the DatabaseMigrationService action to be performed by this request.
void setApiVersion (const QString &version)
Set the DatabaseMigrationService API version to include in this request.
virtual bool operator== (const DatabaseMigrationServiceRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
DatabaseMigrationServiceRequest (DatabaseMigrationServiceRequestPrivate *const d)
Constructs a new DatabaseMigrationServiceRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid DatabaseMigrationService queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this DatabaseMigrationService request.
const QVariantMap & parameters () const
Get all parameters included with this DatabaseMigrationService request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this DatabaseMigrationService request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this DatabaseMigrationService request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this DatabaseMigrationService request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing DatabaseMigrationService requests.
Definition at line 35 of file databasemigrationservicerequest.h.
Constructor & Destructor Documentation
DatabaseMigrationServiceRequest() [1/3]
QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::DatabaseMigrationServiceRequest (const Action action)
Constructs a new DatabaseMigrationServiceRequest object.
Parameters
action The DatabaseMigrationService action to request.
Definition at line 38 of file databasemigrationservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new DatabaseMigrationServiceRequestPrivate(action, this))
 {
 }
DatabaseMigrationServiceRequest() [2/3]
QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::DatabaseMigrationServiceRequest (const DatabaseMigrationServiceRequest & other)
Constructs a new DatabaseMigrationServiceRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file databasemigrationservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new DatabaseMigrationServiceRequestPrivate(*other.d_func(), this))
 {
 }
DatabaseMigrationServiceRequest() [3/3]
QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::DatabaseMigrationServiceRequest (DatabaseMigrationServiceRequestPrivate *const d) protected
Constructs a new DatabaseMigrationServiceRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from DatabaseMigrationServiceRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file databasemigrationservicerequest.cpp.
                                                                                                                  : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
DatabaseMigrationServiceRequest::Action QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::action () const
Get the DatabaseMigrationService action to be performed by this request.
Returns
The DatabaseMigrationService action to be performed by this request.
Definition at line 93 of file databasemigrationservicerequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const DatabaseMigrationServiceRequest);
     return d->action;
 }
actionString()
QString QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::actionString () const
Get the name of the DatabaseMigrationService action to be performed by this request.
Returns
The name of the DatabaseMigrationService action to be performed by this request.
Definition at line 104 of file databasemigrationservicerequest.cpp.
References action(), and QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequestPrivate::toString().
 {
     return DatabaseMigrationServiceRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::apiVersion () const
Get the DatabaseMigrationService API version implemented by this request.
Returns
The DatabaseMigrationService API version implmented by this request.
Definition at line 114 of file databasemigrationservicerequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const DatabaseMigrationServiceRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::clearParameter (const QString & name) protected
Check if queueName is a valid DatabaseMigrationService queue name.
From DatabaseMigrationService FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid DatabaseMigrationService queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file databasemigrationservicerequest.cpp.
 {
     Q_D(DatabaseMigrationServiceRequest);
     return d->parameters.remove(name);
 }
operator=()
DatabaseMigrationServiceRequest & QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::operator= (const DatabaseMigrationServiceRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file databasemigrationservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(DatabaseMigrationServiceRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::operator== (const DatabaseMigrationServiceRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file databasemigrationservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this DatabaseMigrationService request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file databasemigrationservicerequest.cpp.
 {
     Q_D(const DatabaseMigrationServiceRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::parameters () const protected
Get all parameters included with this DatabaseMigrationService request.
Returns
A map of parameters included with this request.
Definition at line 222 of file databasemigrationservicerequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const DatabaseMigrationServiceRequest);
     return d->parameters;
 }
setAction()
void QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::setAction (const Action action)
Set the DatabaseMigrationService action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file databasemigrationservicerequest.cpp.
References action().
 {
     Q_D(DatabaseMigrationServiceRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::setApiVersion (const QString & version)
Set the DatabaseMigrationService API version to include in this request.
Parameters
version The DatabaseMigrationService API version to include in this request.
Definition at line 136 of file databasemigrationservicerequest.cpp.
 {
     Q_D(DatabaseMigrationServiceRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this DatabaseMigrationService request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file databasemigrationservicerequest.cpp.
 {
     Q_D(DatabaseMigrationServiceRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this DatabaseMigrationService request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file databasemigrationservicerequest.cpp.
References parameters().
 {
     Q_D(DatabaseMigrationServiceRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::DatabaseMigrationService::DatabaseMigrationServiceRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this DatabaseMigrationService request.
This DatabaseMigrationService implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this DatabaseMigrationService request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file databasemigrationservicerequest.cpp.
 {
     Q_D(const DatabaseMigrationServiceRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
dms/databasemigrationservicerequest.h
dms/databasemigrationservicerequest.cpp