AWS SDK for Qt: QtAws::ElasticsearchService::ElasticsearchServiceClient Class Reference
QtAws::ElasticsearchService::ElasticsearchServiceClient Class Reference
Client for Amazon Elasticsearch Service.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateElasticsearchDomainResponse * createElasticsearchDomain (const CreateElasticsearchDomainRequest &request)
DeleteElasticsearchDomainResponse * deleteElasticsearchDomain (const DeleteElasticsearchDomainRequest &request)
DeleteElasticsearchServiceRoleResponse * deleteElasticsearchServiceRole ()
DescribeElasticsearchDomainResponse * describeElasticsearchDomain (const DescribeElasticsearchDomainRequest &request)
DescribeElasticsearchDomainConfigResponse * describeElasticsearchDomainConfig (const DescribeElasticsearchDomainConfigRequest &request)
DescribeElasticsearchDomainsResponse * describeElasticsearchDomains (const DescribeElasticsearchDomainsRequest &request)
DescribeElasticsearchInstanceTypeLimitsResponse * describeElasticsearchInstanceTypeLimits (const DescribeElasticsearchInstanceTypeLimitsRequest &request)
ListDomainNamesResponse * listDomainNames ()
ListElasticsearchInstanceTypesResponse * listElasticsearchInstanceTypes (const ListElasticsearchInstanceTypesRequest &request)
ListElasticsearchVersionsResponse * listElasticsearchVersions (const ListElasticsearchVersionsRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
UpdateElasticsearchDomainConfigResponse * updateElasticsearchDomainConfig (const UpdateElasticsearchDomainConfigRequest &request)
Public Member Functions
ElasticsearchServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticsearchServiceClient object.
ElasticsearchServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticsearchServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Elasticsearch Service.
<fullname>Amazon Elasticsearch Configuration Service</fullname>
Use the Amazon Elasticsearch configuration API to create, configure, and manage Elasticsearch
domains>
The endpoint for configuration service requests is region-specific: es.region.amazonaws.com. For example, es.us-east-1.amazonaws.com. For a current list of supported regions and endpoints, see Regions and
Definition at line 58 of file elasticsearchserviceclient.h.
Constructor & Destructor Documentation
ElasticsearchServiceClient() [1/2]
QtAws::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticsearchServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 81 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ElasticsearchServiceClientPrivate(this), parent)
 {
     Q_D(ElasticsearchServiceClient);
     d->apiVersion = QStringLiteral("2015-01-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("es");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Elasticsearch Service");
     d->serviceName = QStringLiteral("es");
 }
ElasticsearchServiceClient() [2/2]
QtAws::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticsearchServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 114 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ElasticsearchServiceClientPrivate(this), parent)
 {
     Q_D(ElasticsearchServiceClient);
     d->apiVersion = QStringLiteral("2015-01-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("es");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Elasticsearch Service");
     d->serviceName = QStringLiteral("es");
 }
Member Function Documentation
addTags
AddTagsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::addTags (const AddTagsRequest & request) slot
Attaches tags to an existing Elasticsearch domain. Tags are a set of case-sensitive key value pairs. An Elasticsearch domain may have up to 10 tags. See Tagging Amazon Elasticsearch Service Domains for more request Request to send to Amazon Elasticsearch Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 143 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
createElasticsearchDomain
CreateElasticsearchDomainResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::createElasticsearchDomain (const CreateElasticsearchDomainRequest & request) slot
Creates a new Elasticsearch domain. For more information, see Creating Elasticsearch Domains in the Amazon Elasticsearch Service Developer
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 159 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateElasticsearchDomainResponse *>(send(request));
 }
deleteElasticsearchDomain
DeleteElasticsearchDomainResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::deleteElasticsearchDomain (const DeleteElasticsearchDomainRequest & request) slot
Permanently deletes the specified Elasticsearch domain and all of its data. Once a domain is deleted, it cannot be
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteElasticsearchDomainResponse *>(send(request));
 }
deleteElasticsearchServiceRole
DeleteElasticsearchServiceRoleResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::deleteElasticsearchServiceRole () slot
Deletes the service-linked role that Elasticsearch Service uses to manage and maintain VPC domains. Role deletion will fail if any existing VPC domains use the role. You must delete any such Elasticsearch domains before deleting the role. See Deleting Elasticsearch Service Role in VPC Endpoints for Amazon Elasticsearch Service
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 190 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteElasticsearchServiceRoleResponse *>(send(request));
 }
describeElasticsearchDomain
DescribeElasticsearchDomainResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomain (const DescribeElasticsearchDomainRequest & request) slot
Returns domain configuration information about the specified Elasticsearch domain, including the domain ID, domain endpoint, and domain
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 205 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticsearchDomainResponse *>(send(request));
 }
describeElasticsearchDomainConfig
DescribeElasticsearchDomainConfigResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomainConfig (const DescribeElasticsearchDomainConfigRequest & request) slot
Provides cluster configuration information about the specified Elasticsearch domain, such as the state, creation date, update version, and update date for cluster
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 220 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticsearchDomainConfigResponse *>(send(request));
 }
describeElasticsearchDomains
DescribeElasticsearchDomainsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomains (const DescribeElasticsearchDomainsRequest & request) slot
Returns domain configuration information about the specified Elasticsearch domains, including the domain ID, domain endpoint, and domain
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 235 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticsearchDomainsResponse *>(send(request));
 }
describeElasticsearchInstanceTypeLimits
DescribeElasticsearchInstanceTypeLimitsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchInstanceTypeLimits (const DescribeElasticsearchInstanceTypeLimitsRequest & request) slot
Describe Elasticsearch Limits for a given InstanceType and ElasticsearchVersion. When modifying existing Domain, specify the DomainName to know what Limits are supported for modifying.
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 250 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeElasticsearchInstanceTypeLimitsResponse *>(send(request));
 }
listDomainNames
ListDomainNamesResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::listDomainNames () slot
Returns the name of all Elasticsearch domains owned by the current user's account.
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 264 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDomainNamesResponse *>(send(request));
 }
listElasticsearchInstanceTypes
ListElasticsearchInstanceTypesResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::listElasticsearchInstanceTypes (const ListElasticsearchInstanceTypesRequest & request) slot
List all Elasticsearch instance types that are supported for given
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListElasticsearchInstanceTypesResponse *>(send(request));
 }
listElasticsearchVersions
ListElasticsearchVersionsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::listElasticsearchVersions (const ListElasticsearchVersionsRequest & request) slot
List all supported Elasticsearch
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListElasticsearchVersionsResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::listTags (const ListTagsRequest & request) slot
Returns all tags for the given Elasticsearch
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::removeTags (const RemoveTagsRequest & request) slot
Removes the specified set of tags from the specified Elasticsearch
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 320 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
updateElasticsearchDomainConfig
UpdateElasticsearchDomainConfigResponse * QtAws::ElasticsearchService::ElasticsearchServiceClient::updateElasticsearchDomainConfig (const UpdateElasticsearchDomainConfigRequest & request) slot
Modifies the cluster configuration of the specified Elasticsearch domain, setting as setting the instance type and the number of instances.
Parameters
request Request to send to Amazon Elasticsearch Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 335 of file elasticsearchserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateElasticsearchDomainConfigResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
es/elasticsearchserviceclient.h
es/elasticsearchserviceclient.cpp