AWS SDK for Qt: QtAws::ResourceGroups::ResourceGroupsClient Class Reference
QtAws::ResourceGroups::ResourceGroupsClient Class Reference
Client for AWS Resource Groups.
Public Slots
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
GetGroupResponse * getGroup (const GetGroupRequest &request)
GetGroupQueryResponse * getGroupQuery (const GetGroupQueryRequest &request)
GetTagsResponse * getTags (const GetTagsRequest &request)
ListGroupResourcesResponse * listGroupResources (const ListGroupResourcesRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
SearchResourcesResponse * searchResources (const SearchResourcesRequest &request)
TagResponse * tag (const TagRequest &request)
UntagResponse * untag (const UntagRequest &request)
UpdateGroupResponse * updateGroup (const UpdateGroupRequest &request)
UpdateGroupQueryResponse * updateGroupQuery (const UpdateGroupQueryRequest &request)
Public Member Functions
ResourceGroupsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ResourceGroupsClient object.
ResourceGroupsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ResourceGroupsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Resource Groups.
<fullname>AWS Resource Groups</fullname>
AWS Resource Groups lets you organize AWS resources such as Amazon EC2 instances, Amazon Relational Database Service databases, and Amazon S3 buckets into groups using criteria that you define as tags. A resource group is a collection of resources that match the resource types specified in a query, and share one or more tags or portions of tags. You can create a group of resources based on their roles in your cloud infrastructure, lifecycle stages, regions, application layers, or virtually any criteria. Resource groups enable you to automate management tasks, such as those in AWS Systems Manager Automation documents, on tag-related resources in AWS Systems Manager. Groups of tagged resources also let you quickly view a custom console in AWS Systems Manager that shows AWS Config compliance and other monitoring data about member
resources>
To create a resource group, build a resource query, and specify tags that identify the criteria that members of the group have in common. Tags are key-value
pairs>
For more information about Resource Groups, see the AWS Resource Groups User Guide>
AWS Resource Groups uses a REST-compliant API that you can use to perform the following types of
operations>
Create, Read, Update, and Delete (CRUD) operations on resource groups and resource query
entitie>
Applying, editing, and removing tags from resource
group>
Resolving resource group member ARNs so they can be returned as search
result>
Getting data about resources that are members of a
grou>
Searching AWS resources based on a resource
Definition at line 56 of file resourcegroupsclient.h.
Constructor & Destructor Documentation
ResourceGroupsClient() [1/2]
QtAws::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ResourceGroupsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 114 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ResourceGroupsClientPrivate(this), parent)
 {
     Q_D(ResourceGroupsClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("resource-groups");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Resource Groups");
     d->serviceName = QStringLiteral("resource-groups");
 }
ResourceGroupsClient() [2/2]
QtAws::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ResourceGroupsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 147 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ResourceGroupsClientPrivate(this), parent)
 {
     Q_D(ResourceGroupsClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("resource-groups");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Resource Groups");
     d->serviceName = QStringLiteral("resource-groups");
 }
Member Function Documentation
createGroup
CreateGroupResponse * QtAws::ResourceGroups::ResourceGroupsClient::createGroup (const CreateGroupRequest & request) slot
Creates a group with a specified name, description, and resource
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGroupResponse *>(send(request));
 }
deleteGroup
DeleteGroupResponse * QtAws::ResourceGroups::ResourceGroupsClient::deleteGroup (const DeleteGroupRequest & request) slot
Deletes a specified resource group. Deleting a resource group does not delete resources that are members of the group; it only deletes the group
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 188 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGroupResponse *>(send(request));
 }
getGroup
GetGroupResponse * QtAws::ResourceGroups::ResourceGroupsClient::getGroup (const GetGroupRequest & request) slot
Returns information about a specified resource
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 202 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGroupResponse *>(send(request));
 }
getGroupQuery
GetGroupQueryResponse * QtAws::ResourceGroups::ResourceGroupsClient::getGroupQuery (const GetGroupQueryRequest & request) slot
Returns the resource query associated with the specified resource
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGroupQueryResponse *>(send(request));
 }
getTags
GetTagsResponse * QtAws::ResourceGroups::ResourceGroupsClient::getTags (const GetTagsRequest & request) slot
Returns a list of tags that are associated with a resource, specified by an
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTagsResponse *>(send(request));
 }
listGroupResources
ListGroupResourcesResponse * QtAws::ResourceGroups::ResourceGroupsClient::listGroupResources (const ListGroupResourcesRequest & request) slot
Returns a list of ARNs of resources that are members of a specified resource
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 244 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupResourcesResponse *>(send(request));
 }
listGroups
ListGroupsResponse * QtAws::ResourceGroups::ResourceGroupsClient::listGroups (const ListGroupsRequest & request) slot
Returns a list of existing resource groups in your
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 258 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupsResponse *>(send(request));
 }
searchResources
SearchResourcesResponse * QtAws::ResourceGroups::ResourceGroupsClient::searchResources (const SearchResourcesRequest & request) slot
Returns a list of AWS resource identifiers that matches a specified query. The query uses the same format as a resource query in a CreateGroup or UpdateGroupQuery
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchResourcesResponse *>(send(request));
 }
tag
TagResponse * QtAws::ResourceGroups::ResourceGroupsClient::tag (const TagRequest & request) slot
Adds specified tags to a resource with the specified ARN. Existing tags on a resource are not changed if they are not specified in the request
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 288 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResponse *>(send(request));
 }
untag
UntagResponse * QtAws::ResourceGroups::ResourceGroupsClient::untag (const UntagRequest & request) slot
Deletes specified tags from a specified
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 302 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResponse *>(send(request));
 }
updateGroup
UpdateGroupResponse * QtAws::ResourceGroups::ResourceGroupsClient::updateGroup (const UpdateGroupRequest & request) slot
Updates an existing group with a new or changed description. You cannot update the name of a resource
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 316 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGroupResponse *>(send(request));
 }
updateGroupQuery
UpdateGroupQueryResponse * QtAws::ResourceGroups::ResourceGroupsClient::updateGroupQuery (const UpdateGroupQueryRequest & request) slot
Updates the resource query of a
Parameters
request Request to send to AWS Resource Groups.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 330 of file resourcegroupsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGroupQueryResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
resource-groups/resourcegroupsclient.h
resource-groups/resourcegroupsclient.cpp