AWS SDK for Qt: QtAws::ACM::AcmClient Class Reference
QtAws::ACM::AcmClient Class Reference
Client for AWS Certificate Manager (ACM)
Public Slots
AddTagsToCertificateResponse * addTagsToCertificate (const AddTagsToCertificateRequest &request)
DeleteCertificateResponse * deleteCertificate (const DeleteCertificateRequest &request)
DescribeCertificateResponse * describeCertificate (const DescribeCertificateRequest &request)
GetCertificateResponse * getCertificate (const GetCertificateRequest &request)
ImportCertificateResponse * importCertificate (const ImportCertificateRequest &request)
ListCertificatesResponse * listCertificates (const ListCertificatesRequest &request)
ListTagsForCertificateResponse * listTagsForCertificate (const ListTagsForCertificateRequest &request)
RemoveTagsFromCertificateResponse * removeTagsFromCertificate (const RemoveTagsFromCertificateRequest &request)
RequestCertificateResponse * requestCertificate (const RequestCertificateRequest &request)
ResendValidationEmailResponse * resendValidationEmail (const ResendValidationEmailRequest &request)
UpdateCertificateOptionsResponse * updateCertificateOptions (const UpdateCertificateOptionsRequest &request)
Public Member Functions
AcmClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AcmClient object.
AcmClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AcmClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Certificate Manager (ACM)
<fullname>AWS Certificate Manager</fullname>
Welcome to the AWS Certificate Manager (ACM) API
documentation>
You can use ACM to manage SSL/TLS certificates for your AWS-based websites and applications. For general information about using ACM, see the AWS Certificate Manager User Guide
Definition at line 54 of file acmclient.h.
Constructor & Destructor Documentation
AcmClient() [1/2]
QtAws::ACM::AcmClient::AcmClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AcmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 77 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new AcmClientPrivate(this), parent)
 {
     Q_D(AcmClient);
     d->apiVersion = QStringLiteral("2015-12-08");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("acm");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Certificate Manager");
     d->serviceName = QStringLiteral("acm");
 }
AcmClient() [2/2]
QtAws::ACM::AcmClient::AcmClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AcmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 110 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new AcmClientPrivate(this), parent)
 {
     Q_D(AcmClient);
     d->apiVersion = QStringLiteral("2015-12-08");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("acm");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Certificate Manager");
     d->serviceName = QStringLiteral("acm");
 }
Member Function Documentation
addTagsToCertificate
AddTagsToCertificateResponse * QtAws::ACM::AcmClient::addTagsToCertificate (const AddTagsToCertificateRequest & request) slot
Adds one or more tags to an ACM certificate. Tags are labels that you can use to identify and organize your AWS resources. Each tag consists of a key and an optional value. You specify the certificate on input by its Amazon Resource Name (ARN). You specify the tag by using a key-value pair.
</p
You can apply a tag to just one certificate if you want to identify a specific characteristic of that certificate, or you can apply the same tag to multiple certificates if you want to filter for a common relationship among those certificates. Similarly, you can apply the same tag to multiple resources if you want to specify a relationship among those resources. For example, you can add the same tag to an ACM certificate and an Elastic Load Balancing load balancer to indicate that they are both used by the same website. For more information, see Tagging ACM certificates.
</p
To remove one or more tags, use the RemoveTagsFromCertificate action. To view all of the tags that have been applied to the certificate, use the ListTagsForCertificate action.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 152 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsToCertificateResponse *>(send(request));
 }
deleteCertificate
DeleteCertificateResponse * QtAws::ACM::AcmClient::deleteCertificate (const DeleteCertificateRequest & request) slot
Deletes a certificate and its associated private key. If this action succeeds, the certificate no longer appears in the list that can be displayed by calling the ListCertificates action or be retrieved by calling the GetCertificate action. The certificate will not be available for use by AWS services integrated with ACM.
</p <note>
You cannot delete an ACM certificate that is being used by another AWS service. To delete a certificate that is in use, the certificate association must first be
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCertificateResponse *>(send(request));
 }
describeCertificate
DescribeCertificateResponse * QtAws::ACM::AcmClient::describeCertificate (const DescribeCertificateRequest & request) slot
Returns detailed metadata about the specified ACM
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 187 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCertificateResponse *>(send(request));
 }
getCertificate
GetCertificateResponse * QtAws::ACM::AcmClient::getCertificate (const GetCertificateRequest & request) slot
Retrieves a certificate specified by an ARN and its certificate chain . The chain is an ordered list of certificates that contains the end entity certificate, intermediate certificates of subordinate CAs, and the root certificate in that order. The certificate and certificate chain are base64 encoded. If you want to decode the certificate to see the individual fields, you can use
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 204 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCertificateResponse *>(send(request));
 }
importCertificate
ImportCertificateResponse * QtAws::ACM::AcmClient::importCertificate (const ImportCertificateRequest & request) slot
Imports a certificate into AWS Certificate Manager (ACM) to use with services that are integrated with ACM. Note that integrated services allow only certificate types and keys they support to be associated with their resources. Further, their support differs depending on whether the certificate is imported into IAM or into ACM. For more information, see the documentation for each service. For more information about importing certificates into ACM, see Importing Certificates in the AWS Certificate Manager User Guide.
</p <note>
ACM does not provide managed renewal for certificates that you
import> </note>
Note the following guidelines when importing third party
certificates>
You must enter the private key that matches the certificate you are
importing>
The private key must be unencrypted. You cannot import a private key that is protected by a password or a
passphrase>
If the certificate you are importing is not self-signed, you must enter its certificate
chain>
If a certificate chain is included, the issuer must be the subject of one of the certificates in the
chain>
The certificate, private key, and certificate chain must be
PEM-encoded>
The current time must be between the Not Before and Not After certificate
fields>
The Issuer field must not be
empty>
The OCSP authority URL, if present, must not exceed 1000
characters>
To import a new certificate, omit the CertificateArn argument. Include this argument only when you want to replace a previously imported
certificate>
When you import a certificate by using the CLI or one of the SDKs, you must specify the certificate, the certificate chain, and the private key by their file names preceded by file://. For example, you can specify a certificate saved in the C: folder as file://C:.pem. If you are making an HTTP or HTTPS Query request, include these arguments as BLOBs.
</p
This operation returns the Amazon Resource Name (ARN) of the imported
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 282 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportCertificateResponse *>(send(request));
 }
listCertificates
ListCertificatesResponse * QtAws::ACM::AcmClient::listCertificates (const ListCertificatesRequest & request) slot
Retrieves a list of certificate ARNs and domain names. You can request that only certificates that match a specific status be listed. You can also filter by specific attributes of the certificate.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 297 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListCertificatesResponse *>(send(request));
 }
listTagsForCertificate
ListTagsForCertificateResponse * QtAws::ACM::AcmClient::listTagsForCertificate (const ListTagsForCertificateRequest & request) slot
Lists the tags that have been applied to the ACM certificate. Use the certificate's Amazon Resource Name (ARN) to specify the certificate. To add a tag to an ACM certificate, use the AddTagsToCertificate action. To delete a tag, use the RemoveTagsFromCertificate action.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 313 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForCertificateResponse *>(send(request));
 }
removeTagsFromCertificate
RemoveTagsFromCertificateResponse * QtAws::ACM::AcmClient::removeTagsFromCertificate (const RemoveTagsFromCertificateRequest & request) slot
Remove one or more tags from an ACM certificate. A tag consists of a key-value pair. If you do not specify the value portion of the tag when calling this function, the tag will be removed regardless of value. If you specify a value, the tag is removed only if it is associated with the specified value.
</p
To add tags to a certificate, use the AddTagsToCertificate action. To view all of the tags that have been applied to a specific ACM certificate, use the ListTagsForCertificate action.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsFromCertificateResponse *>(send(request));
 }
requestCertificate
RequestCertificateResponse * QtAws::ACM::AcmClient::requestCertificate (const RequestCertificateRequest & request) slot
Requests an ACM certificate for use with other AWS services. To request an ACM certificate, you must specify the fully qualified domain name (FQDN) for your site in the DomainName parameter. You can also specify additional FQDNs in the SubjectAlternativeNames parameter if users can reach your site by using other names.
</p
For each domain name you specify, email is sent to the domain owner to request approval to issue the certificate. Email is sent to three registered contact addresses in the WHOIS database and to five common system administration addresses formed from the DomainName you enter or the optional ValidationDomain parameter. For more information, see Validate Domain Ownership.
</p
After receiving approval from the domain owner, the ACM certificate is issued. For more information, see the AWS Certificate Manager User Guide.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 363 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RequestCertificateResponse *>(send(request));
 }
resendValidationEmail
ResendValidationEmailResponse * QtAws::ACM::AcmClient::resendValidationEmail (const ResendValidationEmailRequest & request) slot
Resends the email that requests domain ownership validation. The domain owner or an authorized representative must approve the ACM certificate before it can be issued. The certificate can be approved by clicking a link in the mail to navigate to the Amazon certificate approval website and then clicking I Approve. However, the validation email can be blocked by spam filters. Therefore, if you do not receive the original mail, you can request that the mail be resent within 72 hours of requesting the ACM certificate. If more than 72 hours have elapsed since your original request or since your last attempt to resend validation mail, you must request a new certificate. For more information about setting up your contact email addresses, see Configure Email for your Domain.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 384 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResendValidationEmailResponse *>(send(request));
 }
updateCertificateOptions
UpdateCertificateOptionsResponse * QtAws::ACM::AcmClient::updateCertificateOptions (const UpdateCertificateOptionsRequest & request) slot
Updates a certificate. Currently, you can use this function to specify whether to opt in to or out of recording your certificate in a certificate transparency log. For more information, see Opting Out of Certificate Transparency Logging.
Parameters
request Request to send to AWS Certificate Manager.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 401 of file acmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCertificateOptionsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
acm/acmclient.h
acm/acmclient.cpp