AWS SDK for Qt: QtAws::Route53::Route53Request Class Reference
QtAws::Route53::Route53Request Class Reference
Interface class for providing Route53 requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::Route53::AssociateVPCWithHostedZoneRequest, QtAws::Route53::ChangeResourceRecordSetsRequest, QtAws::Route53::ChangeTagsForResourceRequest, QtAws::Route53::CreateHealthCheckRequest, QtAws::Route53::CreateHostedZoneRequest, QtAws::Route53::CreateQueryLoggingConfigRequest, QtAws::Route53::CreateReusableDelegationSetRequest, QtAws::Route53::CreateTrafficPolicyInstanceRequest, QtAws::Route53::CreateTrafficPolicyRequest, QtAws::Route53::CreateTrafficPolicyVersionRequest, QtAws::Route53::CreateVPCAssociationAuthorizationRequest, QtAws::Route53::DeleteHealthCheckRequest, QtAws::Route53::DeleteHostedZoneRequest, QtAws::Route53::DeleteQueryLoggingConfigRequest, QtAws::Route53::DeleteReusableDelegationSetRequest, QtAws::Route53::DeleteTrafficPolicyInstanceRequest, QtAws::Route53::DeleteTrafficPolicyRequest, QtAws::Route53::DeleteVPCAssociationAuthorizationRequest, QtAws::Route53::DisassociateVPCFromHostedZoneRequest, QtAws::Route53::GetAccountLimitRequest, QtAws::Route53::GetChangeRequest, QtAws::Route53::GetCheckerIpRangesRequest, QtAws::Route53::GetGeoLocationRequest, QtAws::Route53::GetHealthCheckCountRequest, QtAws::Route53::GetHealthCheckLastFailureReasonRequest, QtAws::Route53::GetHealthCheckRequest, QtAws::Route53::GetHealthCheckStatusRequest, QtAws::Route53::GetHostedZoneCountRequest, QtAws::Route53::GetHostedZoneLimitRequest, QtAws::Route53::GetHostedZoneRequest, QtAws::Route53::GetQueryLoggingConfigRequest, QtAws::Route53::GetReusableDelegationSetLimitRequest, QtAws::Route53::GetReusableDelegationSetRequest, QtAws::Route53::GetTrafficPolicyInstanceCountRequest, QtAws::Route53::GetTrafficPolicyInstanceRequest, QtAws::Route53::GetTrafficPolicyRequest, QtAws::Route53::ListGeoLocationsRequest, QtAws::Route53::ListHealthChecksRequest, QtAws::Route53::ListHostedZonesByNameRequest, QtAws::Route53::ListHostedZonesRequest, QtAws::Route53::ListQueryLoggingConfigsRequest, QtAws::Route53::ListResourceRecordSetsRequest, QtAws::Route53::ListReusableDelegationSetsRequest, QtAws::Route53::ListTagsForResourceRequest, QtAws::Route53::ListTagsForResourcesRequest, QtAws::Route53::ListTrafficPoliciesRequest, QtAws::Route53::ListTrafficPolicyInstancesByHostedZoneRequest, QtAws::Route53::ListTrafficPolicyInstancesByPolicyRequest, QtAws::Route53::ListTrafficPolicyInstancesRequest, QtAws::Route53::ListTrafficPolicyVersionsRequest, QtAws::Route53::ListVPCAssociationAuthorizationsRequest, QtAws::Route53::TestDNSAnswerRequest, QtAws::Route53::UpdateHealthCheckRequest, QtAws::Route53::UpdateHostedZoneCommentRequest, QtAws::Route53::UpdateTrafficPolicyCommentRequest, and QtAws::Route53::UpdateTrafficPolicyInstanceRequest.
Public Types
enum Action {
AssociateVPCWithHostedZoneAction, ChangeResourceRecordSetsAction, ChangeTagsForResourceAction, CreateHealthCheckAction,
CreateHostedZoneAction, CreateQueryLoggingConfigAction, CreateReusableDelegationSetAction, CreateTrafficPolicyAction,
CreateTrafficPolicyInstanceAction, CreateTrafficPolicyVersionAction, CreateVPCAssociationAuthorizationAction, DeleteHealthCheckAction,
DeleteHostedZoneAction, DeleteQueryLoggingConfigAction, DeleteReusableDelegationSetAction, DeleteTrafficPolicyAction,
DeleteTrafficPolicyInstanceAction, DeleteVPCAssociationAuthorizationAction, DisassociateVPCFromHostedZoneAction, GetAccountLimitAction,
GetChangeAction, GetCheckerIpRangesAction, GetGeoLocationAction, GetHealthCheckAction,
GetHealthCheckCountAction, GetHealthCheckLastFailureReasonAction, GetHealthCheckStatusAction, GetHostedZoneAction,
GetHostedZoneCountAction, GetHostedZoneLimitAction, GetQueryLoggingConfigAction, GetReusableDelegationSetAction,
GetReusableDelegationSetLimitAction, GetTrafficPolicyAction, GetTrafficPolicyInstanceAction, GetTrafficPolicyInstanceCountAction,
ListGeoLocationsAction, ListHealthChecksAction, ListHostedZonesAction, ListHostedZonesByNameAction,
ListQueryLoggingConfigsAction, ListResourceRecordSetsAction, ListReusableDelegationSetsAction, ListTagsForResourceAction,
ListTagsForResourcesAction, ListTrafficPoliciesAction, ListTrafficPolicyInstancesAction, ListTrafficPolicyInstancesByHostedZoneAction,
ListTrafficPolicyInstancesByPolicyAction, ListTrafficPolicyVersionsAction, ListVPCAssociationAuthorizationsAction, TestDNSAnswerAction,
UpdateHealthCheckAction, UpdateHostedZoneCommentAction, UpdateTrafficPolicyCommentAction, UpdateTrafficPolicyInstanceAction
}
Actions supported by Route53.
Public Member Functions
Route53Request (const Action action)
Constructs a new Route53Request object.
Route53Request (const Route53Request &other)
Constructs a new Route53Request object by copying another.
Route53Request & operator= (const Route53Request &other)
Assignment operator.
Action action () const
Get the Route53 action to be performed by this request.
QString actionString () const
Get the name of the Route53 action to be performed by this request.
QString apiVersion () const
Get the Route53 API version implemented by this request.
void setAction (const Action action)
Set the Route53 action to be performed by this request.
void setApiVersion (const QString &version)
Set the Route53 API version to include in this request.
virtual bool operator== (const Route53Request &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
Route53Request (Route53RequestPrivate *const d)
Constructs a new Route53Request object.
int clearParameter (const QString &name)
Check if queueName is a valid Route53 queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this Route53 request.
const QVariantMap & parameters () const
Get all parameters included with this Route53 request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this Route53 request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this Route53 request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this Route53 request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing Route53 requests.
Definition at line 35 of file route53request.h.
Constructor & Destructor Documentation
Route53Request() [1/3]
QtAws::Route53::Route53Request::Route53Request (const Action action)
Constructs a new Route53Request object.
Parameters
action The Route53 action to request.
Definition at line 38 of file route53request.cpp.
     : QtAws::Core::AwsAbstractRequest(new Route53RequestPrivate(action, this))
 {
 }
Route53Request() [2/3]
QtAws::Route53::Route53Request::Route53Request (const Route53Request & other)
Constructs a new Route53Request object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file route53request.cpp.
     : QtAws::Core::AwsAbstractRequest(new Route53RequestPrivate(*other.d_func(), this))
 {
 }
Route53Request() [3/3]
QtAws::Route53::Route53Request::Route53Request (Route53RequestPrivate *const d) protected
Constructs a new Route53Request object.
This overload allows derived classes to provide their own private class implementation that inherits from Route53RequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file route53request.cpp.
                                                               : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
Route53Request::Action QtAws::Route53::Route53Request::action () const
Get the Route53 action to be performed by this request.
Returns
The Route53 action to be performed by this request.
Definition at line 93 of file route53request.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const Route53Request);
     return d->action;
 }
actionString()
QString QtAws::Route53::Route53Request::actionString () const
Get the name of the Route53 action to be performed by this request.
Returns
The name of the Route53 action to be performed by this request.
Definition at line 104 of file route53request.cpp.
References action(), and QtAws::Route53::Route53RequestPrivate::toString().
 {
     return Route53RequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::Route53::Route53Request::apiVersion () const
Get the Route53 API version implemented by this request.
Returns
The Route53 API version implmented by this request.
Definition at line 114 of file route53request.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const Route53Request);
     return d->apiVersion;
 }
clearParameter()
int QtAws::Route53::Route53Request::clearParameter (const QString & name) protected
Check if queueName is a valid Route53 queue name.
From Route53 FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid Route53 queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file route53request.cpp.
 {
     Q_D(Route53Request);
     return d->parameters.remove(name);
 }
operator=()
Route53Request & QtAws::Route53::Route53Request::operator= (const Route53Request & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file route53request.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(Route53Request);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::Route53::Route53Request::operator== (const Route53Request & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file route53request.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::Route53::Route53Request::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this Route53 request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file route53request.cpp.
 {
     Q_D(const Route53Request);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::Route53::Route53Request::parameters () const protected
Get all parameters included with this Route53 request.
Returns
A map of parameters included with this request.
Definition at line 222 of file route53request.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const Route53Request);
     return d->parameters;
 }
setAction()
void QtAws::Route53::Route53Request::setAction (const Action action)
Set the Route53 action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file route53request.cpp.
References action().
 {
     Q_D(Route53Request);
     d->action = action;
 }
setApiVersion()
void QtAws::Route53::Route53Request::setApiVersion (const QString & version)
Set the Route53 API version to include in this request.
Parameters
version The Route53 API version to include in this request.
Definition at line 136 of file route53request.cpp.
 {
     Q_D(Route53Request);
     d->apiVersion = version;
 }
setParameter()
void QtAws::Route53::Route53Request::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this Route53 request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file route53request.cpp.
 {
     Q_D(Route53Request);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::Route53::Route53Request::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this Route53 request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file route53request.cpp.
References parameters().
 {
     Q_D(Route53Request);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::Route53::Route53Request::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this Route53 request.
This Route53 implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this Route53 request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file route53request.cpp.
 {
     Q_D(const Route53Request);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
route53/route53request.h
route53/route53request.cpp