AWS SDK for Qt: QtAws::DeviceFarm::DeviceFarmRequest Class Reference
QtAws::DeviceFarm::DeviceFarmRequest Class Reference
Interface class for providing DeviceFarm requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::DeviceFarm::CreateDevicePoolRequest, QtAws::DeviceFarm::CreateNetworkProfileRequest, QtAws::DeviceFarm::CreateProjectRequest, QtAws::DeviceFarm::CreateRemoteAccessSessionRequest, QtAws::DeviceFarm::CreateUploadRequest, QtAws::DeviceFarm::DeleteDevicePoolRequest, QtAws::DeviceFarm::DeleteNetworkProfileRequest, QtAws::DeviceFarm::DeleteProjectRequest, QtAws::DeviceFarm::DeleteRemoteAccessSessionRequest, QtAws::DeviceFarm::DeleteRunRequest, QtAws::DeviceFarm::DeleteUploadRequest, QtAws::DeviceFarm::GetAccountSettingsRequest, QtAws::DeviceFarm::GetDevicePoolCompatibilityRequest, QtAws::DeviceFarm::GetDevicePoolRequest, QtAws::DeviceFarm::GetDeviceRequest, QtAws::DeviceFarm::GetJobRequest, QtAws::DeviceFarm::GetNetworkProfileRequest, QtAws::DeviceFarm::GetOfferingStatusRequest, QtAws::DeviceFarm::GetProjectRequest, QtAws::DeviceFarm::GetRemoteAccessSessionRequest, QtAws::DeviceFarm::GetRunRequest, QtAws::DeviceFarm::GetSuiteRequest, QtAws::DeviceFarm::GetTestRequest, QtAws::DeviceFarm::GetUploadRequest, QtAws::DeviceFarm::InstallToRemoteAccessSessionRequest, QtAws::DeviceFarm::ListArtifactsRequest, QtAws::DeviceFarm::ListDevicePoolsRequest, QtAws::DeviceFarm::ListDevicesRequest, QtAws::DeviceFarm::ListJobsRequest, QtAws::DeviceFarm::ListNetworkProfilesRequest, QtAws::DeviceFarm::ListOfferingPromotionsRequest, QtAws::DeviceFarm::ListOfferingsRequest, QtAws::DeviceFarm::ListOfferingTransactionsRequest, QtAws::DeviceFarm::ListProjectsRequest, QtAws::DeviceFarm::ListRemoteAccessSessionsRequest, QtAws::DeviceFarm::ListRunsRequest, QtAws::DeviceFarm::ListSamplesRequest, QtAws::DeviceFarm::ListSuitesRequest, QtAws::DeviceFarm::ListTestsRequest, QtAws::DeviceFarm::ListUniqueProblemsRequest, QtAws::DeviceFarm::ListUploadsRequest, QtAws::DeviceFarm::PurchaseOfferingRequest, QtAws::DeviceFarm::RenewOfferingRequest, QtAws::DeviceFarm::ScheduleRunRequest, QtAws::DeviceFarm::StopRemoteAccessSessionRequest, QtAws::DeviceFarm::StopRunRequest, QtAws::DeviceFarm::UpdateDevicePoolRequest, QtAws::DeviceFarm::UpdateNetworkProfileRequest, and QtAws::DeviceFarm::UpdateProjectRequest.
Public Types
enum Action {
CreateDevicePoolAction, CreateNetworkProfileAction, CreateProjectAction, CreateRemoteAccessSessionAction,
CreateUploadAction, DeleteDevicePoolAction, DeleteNetworkProfileAction, DeleteProjectAction,
DeleteRemoteAccessSessionAction, DeleteRunAction, DeleteUploadAction, GetAccountSettingsAction,
GetDeviceAction, GetDevicePoolAction, GetDevicePoolCompatibilityAction, GetJobAction,
GetNetworkProfileAction, GetOfferingStatusAction, GetProjectAction, GetRemoteAccessSessionAction,
GetRunAction, GetSuiteAction, GetTestAction, GetUploadAction,
InstallToRemoteAccessSessionAction, ListArtifactsAction, ListDevicePoolsAction, ListDevicesAction,
ListJobsAction, ListNetworkProfilesAction, ListOfferingPromotionsAction, ListOfferingTransactionsAction,
ListOfferingsAction, ListProjectsAction, ListRemoteAccessSessionsAction, ListRunsAction,
ListSamplesAction, ListSuitesAction, ListTestsAction, ListUniqueProblemsAction,
ListUploadsAction, PurchaseOfferingAction, RenewOfferingAction, ScheduleRunAction,
StopRemoteAccessSessionAction, StopRunAction, UpdateDevicePoolAction, UpdateNetworkProfileAction,
UpdateProjectAction
}
Actions supported by DeviceFarm.
Public Member Functions
DeviceFarmRequest (const Action action)
Constructs a new DeviceFarmRequest object.
DeviceFarmRequest (const DeviceFarmRequest &other)
Constructs a new DeviceFarmRequest object by copying another.
DeviceFarmRequest & operator= (const DeviceFarmRequest &other)
Assignment operator.
Action action () const
Get the DeviceFarm action to be performed by this request.
QString actionString () const
Get the name of the DeviceFarm action to be performed by this request.
QString apiVersion () const
Get the DeviceFarm API version implemented by this request.
void setAction (const Action action)
Set the DeviceFarm action to be performed by this request.
void setApiVersion (const QString &version)
Set the DeviceFarm API version to include in this request.
virtual bool operator== (const DeviceFarmRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
DeviceFarmRequest (DeviceFarmRequestPrivate *const d)
Constructs a new DeviceFarmRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid DeviceFarm queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this DeviceFarm request.
const QVariantMap & parameters () const
Get all parameters included with this DeviceFarm request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this DeviceFarm request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this DeviceFarm request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this DeviceFarm request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing DeviceFarm requests.
Definition at line 35 of file devicefarmrequest.h.
Constructor & Destructor Documentation
DeviceFarmRequest() [1/3]
QtAws::DeviceFarm::DeviceFarmRequest::DeviceFarmRequest (const Action action)
Constructs a new DeviceFarmRequest object.
Parameters
action The DeviceFarm action to request.
Definition at line 38 of file devicefarmrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new DeviceFarmRequestPrivate(action, this))
 {
 }
DeviceFarmRequest() [2/3]
QtAws::DeviceFarm::DeviceFarmRequest::DeviceFarmRequest (const DeviceFarmRequest & other)
Constructs a new DeviceFarmRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file devicefarmrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new DeviceFarmRequestPrivate(*other.d_func(), this))
 {
 }
DeviceFarmRequest() [3/3]
QtAws::DeviceFarm::DeviceFarmRequest::DeviceFarmRequest (DeviceFarmRequestPrivate *const d) protected
Constructs a new DeviceFarmRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from DeviceFarmRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file devicefarmrequest.cpp.
                                                                        : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
DeviceFarmRequest::Action QtAws::DeviceFarm::DeviceFarmRequest::action () const
Get the DeviceFarm action to be performed by this request.
Returns
The DeviceFarm action to be performed by this request.
Definition at line 93 of file devicefarmrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const DeviceFarmRequest);
     return d->action;
 }
actionString()
QString QtAws::DeviceFarm::DeviceFarmRequest::actionString () const
Get the name of the DeviceFarm action to be performed by this request.
Returns
The name of the DeviceFarm action to be performed by this request.
Definition at line 104 of file devicefarmrequest.cpp.
References action(), and QtAws::DeviceFarm::DeviceFarmRequestPrivate::toString().
 {
     return DeviceFarmRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::DeviceFarm::DeviceFarmRequest::apiVersion () const
Get the DeviceFarm API version implemented by this request.
Returns
The DeviceFarm API version implmented by this request.
Definition at line 114 of file devicefarmrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const DeviceFarmRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::DeviceFarm::DeviceFarmRequest::clearParameter (const QString & name) protected
Check if queueName is a valid DeviceFarm queue name.
From DeviceFarm FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid DeviceFarm queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file devicefarmrequest.cpp.
 {
     Q_D(DeviceFarmRequest);
     return d->parameters.remove(name);
 }
operator=()
DeviceFarmRequest & QtAws::DeviceFarm::DeviceFarmRequest::operator= (const DeviceFarmRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file devicefarmrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(DeviceFarmRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::DeviceFarm::DeviceFarmRequest::operator== (const DeviceFarmRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file devicefarmrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::DeviceFarm::DeviceFarmRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this DeviceFarm request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file devicefarmrequest.cpp.
 {
     Q_D(const DeviceFarmRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::DeviceFarm::DeviceFarmRequest::parameters () const protected
Get all parameters included with this DeviceFarm request.
Returns
A map of parameters included with this request.
Definition at line 222 of file devicefarmrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const DeviceFarmRequest);
     return d->parameters;
 }
setAction()
void QtAws::DeviceFarm::DeviceFarmRequest::setAction (const Action action)
Set the DeviceFarm action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file devicefarmrequest.cpp.
References action().
 {
     Q_D(DeviceFarmRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::DeviceFarm::DeviceFarmRequest::setApiVersion (const QString & version)
Set the DeviceFarm API version to include in this request.
Parameters
version The DeviceFarm API version to include in this request.
Definition at line 136 of file devicefarmrequest.cpp.
 {
     Q_D(DeviceFarmRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::DeviceFarm::DeviceFarmRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this DeviceFarm request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file devicefarmrequest.cpp.
 {
     Q_D(DeviceFarmRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::DeviceFarm::DeviceFarmRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this DeviceFarm request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file devicefarmrequest.cpp.
References parameters().
 {
     Q_D(DeviceFarmRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::DeviceFarm::DeviceFarmRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this DeviceFarm request.
This DeviceFarm implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this DeviceFarm request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file devicefarmrequest.cpp.
 {
     Q_D(const DeviceFarmRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
devicefarm/devicefarmrequest.h
devicefarm/devicefarmrequest.cpp