AWS SDK for Qt: QtAws::EC2::EC2Request Class Reference
QtAws::EC2::EC2Request Class Reference
Interface class for providing EC2 requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::EC2::AcceptReservedInstancesExchangeQuoteRequest, QtAws::EC2::AcceptVpcEndpointConnectionsRequest, QtAws::EC2::AcceptVpcPeeringConnectionRequest, QtAws::EC2::AllocateAddressRequest, QtAws::EC2::AllocateHostsRequest, QtAws::EC2::AssignIpv6AddressesRequest, QtAws::EC2::AssignPrivateIpAddressesRequest, QtAws::EC2::AssociateAddressRequest, QtAws::EC2::AssociateDhcpOptionsRequest, QtAws::EC2::AssociateIamInstanceProfileRequest, QtAws::EC2::AssociateRouteTableRequest, QtAws::EC2::AssociateSubnetCidrBlockRequest, QtAws::EC2::AssociateVpcCidrBlockRequest, QtAws::EC2::AttachClassicLinkVpcRequest, QtAws::EC2::AttachInternetGatewayRequest, QtAws::EC2::AttachNetworkInterfaceRequest, QtAws::EC2::AttachVolumeRequest, QtAws::EC2::AttachVpnGatewayRequest, QtAws::EC2::AuthorizeSecurityGroupEgressRequest, QtAws::EC2::AuthorizeSecurityGroupIngressRequest, QtAws::EC2::BundleInstanceRequest, QtAws::EC2::CancelBundleTaskRequest, QtAws::EC2::CancelConversionTaskRequest, QtAws::EC2::CancelExportTaskRequest, QtAws::EC2::CancelImportTaskRequest, QtAws::EC2::CancelReservedInstancesListingRequest, QtAws::EC2::CancelSpotFleetRequestsRequest, QtAws::EC2::CancelSpotInstanceRequestsRequest, QtAws::EC2::ConfirmProductInstanceRequest, QtAws::EC2::CopyFpgaImageRequest, QtAws::EC2::CopyImageRequest, QtAws::EC2::CopySnapshotRequest, QtAws::EC2::CreateCustomerGatewayRequest, QtAws::EC2::CreateDefaultSubnetRequest, QtAws::EC2::CreateDefaultVpcRequest, QtAws::EC2::CreateDhcpOptionsRequest, QtAws::EC2::CreateEgressOnlyInternetGatewayRequest, QtAws::EC2::CreateFlowLogsRequest, QtAws::EC2::CreateFpgaImageRequest, QtAws::EC2::CreateImageRequest, QtAws::EC2::CreateInstanceExportTaskRequest, QtAws::EC2::CreateInternetGatewayRequest, QtAws::EC2::CreateKeyPairRequest, QtAws::EC2::CreateLaunchTemplateRequest, QtAws::EC2::CreateLaunchTemplateVersionRequest, QtAws::EC2::CreateNatGatewayRequest, QtAws::EC2::CreateNetworkAclEntryRequest, QtAws::EC2::CreateNetworkAclRequest, QtAws::EC2::CreateNetworkInterfacePermissionRequest, QtAws::EC2::CreateNetworkInterfaceRequest, QtAws::EC2::CreatePlacementGroupRequest, QtAws::EC2::CreateReservedInstancesListingRequest, QtAws::EC2::CreateRouteRequest, QtAws::EC2::CreateRouteTableRequest, QtAws::EC2::CreateSecurityGroupRequest, QtAws::EC2::CreateSnapshotRequest, QtAws::EC2::CreateSpotDatafeedSubscriptionRequest, QtAws::EC2::CreateSubnetRequest, QtAws::EC2::CreateTagsRequest, QtAws::EC2::CreateVolumeRequest, QtAws::EC2::CreateVpcEndpointConnectionNotificationRequest, QtAws::EC2::CreateVpcEndpointRequest, QtAws::EC2::CreateVpcEndpointServiceConfigurationRequest, QtAws::EC2::CreateVpcPeeringConnectionRequest, QtAws::EC2::CreateVpcRequest, QtAws::EC2::CreateVpnConnectionRequest, QtAws::EC2::CreateVpnConnectionRouteRequest, QtAws::EC2::CreateVpnGatewayRequest, QtAws::EC2::DeleteCustomerGatewayRequest, QtAws::EC2::DeleteDhcpOptionsRequest, QtAws::EC2::DeleteEgressOnlyInternetGatewayRequest, QtAws::EC2::DeleteFlowLogsRequest, QtAws::EC2::DeleteFpgaImageRequest, QtAws::EC2::DeleteInternetGatewayRequest, QtAws::EC2::DeleteKeyPairRequest, QtAws::EC2::DeleteLaunchTemplateRequest, QtAws::EC2::DeleteLaunchTemplateVersionsRequest, QtAws::EC2::DeleteNatGatewayRequest, QtAws::EC2::DeleteNetworkAclEntryRequest, QtAws::EC2::DeleteNetworkAclRequest, QtAws::EC2::DeleteNetworkInterfacePermissionRequest, QtAws::EC2::DeleteNetworkInterfaceRequest, QtAws::EC2::DeletePlacementGroupRequest, QtAws::EC2::DeleteRouteRequest, QtAws::EC2::DeleteRouteTableRequest, QtAws::EC2::DeleteSecurityGroupRequest, QtAws::EC2::DeleteSnapshotRequest, QtAws::EC2::DeleteSpotDatafeedSubscriptionRequest, QtAws::EC2::DeleteSubnetRequest, QtAws::EC2::DeleteTagsRequest, QtAws::EC2::DeleteVolumeRequest, QtAws::EC2::DeleteVpcEndpointConnectionNotificationsRequest, QtAws::EC2::DeleteVpcEndpointServiceConfigurationsRequest, QtAws::EC2::DeleteVpcEndpointsRequest, QtAws::EC2::DeleteVpcPeeringConnectionRequest, QtAws::EC2::DeleteVpcRequest, QtAws::EC2::DeleteVpnConnectionRequest, QtAws::EC2::DeleteVpnConnectionRouteRequest, QtAws::EC2::DeleteVpnGatewayRequest, QtAws::EC2::DeregisterImageRequest, QtAws::EC2::DescribeAccountAttributesRequest, QtAws::EC2::DescribeAddressesRequest, QtAws::EC2::DescribeAggregateIdFormatRequest, QtAws::EC2::DescribeAvailabilityZonesRequest, QtAws::EC2::DescribeBundleTasksRequest, QtAws::EC2::DescribeClassicLinkInstancesRequest, QtAws::EC2::DescribeConversionTasksRequest, QtAws::EC2::DescribeCustomerGatewaysRequest, QtAws::EC2::DescribeDhcpOptionsRequest, QtAws::EC2::DescribeEgressOnlyInternetGatewaysRequest, QtAws::EC2::DescribeElasticGpusRequest, QtAws::EC2::DescribeExportTasksRequest, QtAws::EC2::DescribeFlowLogsRequest, QtAws::EC2::DescribeFpgaImageAttributeRequest, QtAws::EC2::DescribeFpgaImagesRequest, QtAws::EC2::DescribeHostReservationOfferingsRequest, QtAws::EC2::DescribeHostReservationsRequest, QtAws::EC2::DescribeHostsRequest, QtAws::EC2::DescribeIamInstanceProfileAssociationsRequest, QtAws::EC2::DescribeIdentityIdFormatRequest, QtAws::EC2::DescribeIdFormatRequest, QtAws::EC2::DescribeImageAttributeRequest, QtAws::EC2::DescribeImagesRequest, QtAws::EC2::DescribeImportImageTasksRequest, QtAws::EC2::DescribeImportSnapshotTasksRequest, QtAws::EC2::DescribeInstanceAttributeRequest, QtAws::EC2::DescribeInstanceCreditSpecificationsRequest, QtAws::EC2::DescribeInstancesRequest, QtAws::EC2::DescribeInstanceStatusRequest, QtAws::EC2::DescribeInternetGatewaysRequest, QtAws::EC2::DescribeKeyPairsRequest, QtAws::EC2::DescribeLaunchTemplatesRequest, QtAws::EC2::DescribeLaunchTemplateVersionsRequest, QtAws::EC2::DescribeMovingAddressesRequest, QtAws::EC2::DescribeNatGatewaysRequest, QtAws::EC2::DescribeNetworkAclsRequest, QtAws::EC2::DescribeNetworkInterfaceAttributeRequest, QtAws::EC2::DescribeNetworkInterfacePermissionsRequest, QtAws::EC2::DescribeNetworkInterfacesRequest, QtAws::EC2::DescribePlacementGroupsRequest, QtAws::EC2::DescribePrefixListsRequest, QtAws::EC2::DescribePrincipalIdFormatRequest, QtAws::EC2::DescribeRegionsRequest, QtAws::EC2::DescribeReservedInstancesListingsRequest, QtAws::EC2::DescribeReservedInstancesModificationsRequest, QtAws::EC2::DescribeReservedInstancesOfferingsRequest, QtAws::EC2::DescribeReservedInstancesRequest, QtAws::EC2::DescribeRouteTablesRequest, QtAws::EC2::DescribeScheduledInstanceAvailabilityRequest, QtAws::EC2::DescribeScheduledInstancesRequest, QtAws::EC2::DescribeSecurityGroupReferencesRequest, QtAws::EC2::DescribeSecurityGroupsRequest, QtAws::EC2::DescribeSnapshotAttributeRequest, QtAws::EC2::DescribeSnapshotsRequest, QtAws::EC2::DescribeSpotDatafeedSubscriptionRequest, QtAws::EC2::DescribeSpotFleetInstancesRequest, QtAws::EC2::DescribeSpotFleetRequestHistoryRequest, QtAws::EC2::DescribeSpotFleetRequestsRequest, QtAws::EC2::DescribeSpotInstanceRequestsRequest, QtAws::EC2::DescribeSpotPriceHistoryRequest, QtAws::EC2::DescribeStaleSecurityGroupsRequest, QtAws::EC2::DescribeSubnetsRequest, QtAws::EC2::DescribeTagsRequest, QtAws::EC2::DescribeVolumeAttributeRequest, QtAws::EC2::DescribeVolumesModificationsRequest, QtAws::EC2::DescribeVolumesRequest, QtAws::EC2::DescribeVolumeStatusRequest, QtAws::EC2::DescribeVpcAttributeRequest, QtAws::EC2::DescribeVpcClassicLinkDnsSupportRequest, QtAws::EC2::DescribeVpcClassicLinkRequest, QtAws::EC2::DescribeVpcEndpointConnectionNotificationsRequest, QtAws::EC2::DescribeVpcEndpointConnectionsRequest, QtAws::EC2::DescribeVpcEndpointServiceConfigurationsRequest, QtAws::EC2::DescribeVpcEndpointServicePermissionsRequest, QtAws::EC2::DescribeVpcEndpointServicesRequest, QtAws::EC2::DescribeVpcEndpointsRequest, QtAws::EC2::DescribeVpcPeeringConnectionsRequest, QtAws::EC2::DescribeVpcsRequest, QtAws::EC2::DescribeVpnConnectionsRequest, QtAws::EC2::DescribeVpnGatewaysRequest, QtAws::EC2::DetachClassicLinkVpcRequest, QtAws::EC2::DetachInternetGatewayRequest, QtAws::EC2::DetachNetworkInterfaceRequest, QtAws::EC2::DetachVolumeRequest, QtAws::EC2::DetachVpnGatewayRequest, QtAws::EC2::DisableVgwRoutePropagationRequest, QtAws::EC2::DisableVpcClassicLinkDnsSupportRequest, QtAws::EC2::DisableVpcClassicLinkRequest, QtAws::EC2::DisassociateAddressRequest, QtAws::EC2::DisassociateIamInstanceProfileRequest, QtAws::EC2::DisassociateRouteTableRequest, QtAws::EC2::DisassociateSubnetCidrBlockRequest, QtAws::EC2::DisassociateVpcCidrBlockRequest, QtAws::EC2::EnableVgwRoutePropagationRequest, QtAws::EC2::EnableVolumeIORequest, QtAws::EC2::EnableVpcClassicLinkDnsSupportRequest, QtAws::EC2::EnableVpcClassicLinkRequest, QtAws::EC2::GetConsoleOutputRequest, QtAws::EC2::GetConsoleScreenshotRequest, QtAws::EC2::GetHostReservationPurchasePreviewRequest, QtAws::EC2::GetLaunchTemplateDataRequest, QtAws::EC2::GetPasswordDataRequest, QtAws::EC2::GetReservedInstancesExchangeQuoteRequest, QtAws::EC2::ImportImageRequest, QtAws::EC2::ImportInstanceRequest, QtAws::EC2::ImportKeyPairRequest, QtAws::EC2::ImportSnapshotRequest, QtAws::EC2::ImportVolumeRequest, QtAws::EC2::ModifyFpgaImageAttributeRequest, QtAws::EC2::ModifyHostsRequest, QtAws::EC2::ModifyIdentityIdFormatRequest, QtAws::EC2::ModifyIdFormatRequest, QtAws::EC2::ModifyImageAttributeRequest, QtAws::EC2::ModifyInstanceAttributeRequest, QtAws::EC2::ModifyInstanceCreditSpecificationRequest, QtAws::EC2::ModifyInstancePlacementRequest, QtAws::EC2::ModifyLaunchTemplateRequest, QtAws::EC2::ModifyNetworkInterfaceAttributeRequest, QtAws::EC2::ModifyReservedInstancesRequest, QtAws::EC2::ModifySnapshotAttributeRequest, QtAws::EC2::ModifySpotFleetRequestRequest, QtAws::EC2::ModifySubnetAttributeRequest, QtAws::EC2::ModifyVolumeAttributeRequest, QtAws::EC2::ModifyVolumeRequest, QtAws::EC2::ModifyVpcAttributeRequest, QtAws::EC2::ModifyVpcEndpointConnectionNotificationRequest, QtAws::EC2::ModifyVpcEndpointRequest, QtAws::EC2::ModifyVpcEndpointServiceConfigurationRequest, QtAws::EC2::ModifyVpcEndpointServicePermissionsRequest, QtAws::EC2::ModifyVpcPeeringConnectionOptionsRequest, QtAws::EC2::ModifyVpcTenancyRequest, QtAws::EC2::MonitorInstancesRequest, QtAws::EC2::MoveAddressToVpcRequest, QtAws::EC2::PurchaseHostReservationRequest, QtAws::EC2::PurchaseReservedInstancesOfferingRequest, QtAws::EC2::PurchaseScheduledInstancesRequest, QtAws::EC2::RebootInstancesRequest, QtAws::EC2::RegisterImageRequest, QtAws::EC2::RejectVpcEndpointConnectionsRequest, QtAws::EC2::RejectVpcPeeringConnectionRequest, QtAws::EC2::ReleaseAddressRequest, QtAws::EC2::ReleaseHostsRequest, QtAws::EC2::ReplaceIamInstanceProfileAssociationRequest, QtAws::EC2::ReplaceNetworkAclAssociationRequest, QtAws::EC2::ReplaceNetworkAclEntryRequest, QtAws::EC2::ReplaceRouteRequest, QtAws::EC2::ReplaceRouteTableAssociationRequest, QtAws::EC2::ReportInstanceStatusRequest, QtAws::EC2::RequestSpotFleetRequest, QtAws::EC2::RequestSpotInstancesRequest, QtAws::EC2::ResetFpgaImageAttributeRequest, QtAws::EC2::ResetImageAttributeRequest, QtAws::EC2::ResetInstanceAttributeRequest, QtAws::EC2::ResetNetworkInterfaceAttributeRequest, QtAws::EC2::ResetSnapshotAttributeRequest, QtAws::EC2::RestoreAddressToClassicRequest, QtAws::EC2::RevokeSecurityGroupEgressRequest, QtAws::EC2::RevokeSecurityGroupIngressRequest, QtAws::EC2::RunInstancesRequest, QtAws::EC2::RunScheduledInstancesRequest, QtAws::EC2::StartInstancesRequest, QtAws::EC2::StopInstancesRequest, QtAws::EC2::TerminateInstancesRequest, QtAws::EC2::UnassignIpv6AddressesRequest, QtAws::EC2::UnassignPrivateIpAddressesRequest, QtAws::EC2::UnmonitorInstancesRequest, QtAws::EC2::UpdateSecurityGroupRuleDescriptionsEgressRequest, and QtAws::EC2::UpdateSecurityGroupRuleDescriptionsIngressRequest.
Public Types
enum Action {
AcceptReservedInstancesExchangeQuoteAction, AcceptVpcEndpointConnectionsAction, AcceptVpcPeeringConnectionAction, AllocateAddressAction,
AllocateHostsAction, AssignIpv6AddressesAction, AssignPrivateIpAddressesAction, AssociateAddressAction,
AssociateDhcpOptionsAction, AssociateIamInstanceProfileAction, AssociateRouteTableAction, AssociateSubnetCidrBlockAction,
AssociateVpcCidrBlockAction, AttachClassicLinkVpcAction, AttachInternetGatewayAction, AttachNetworkInterfaceAction,
AttachVolumeAction, AttachVpnGatewayAction, AuthorizeSecurityGroupEgressAction, AuthorizeSecurityGroupIngressAction,
BundleInstanceAction, CancelBundleTaskAction, CancelConversionTaskAction, CancelExportTaskAction,
CancelImportTaskAction, CancelReservedInstancesListingAction, CancelSpotFleetRequestsAction, CancelSpotInstanceRequestsAction,
ConfirmProductInstanceAction, CopyFpgaImageAction, CopyImageAction, CopySnapshotAction,
CreateCustomerGatewayAction, CreateDefaultSubnetAction, CreateDefaultVpcAction, CreateDhcpOptionsAction,
CreateEgressOnlyInternetGatewayAction, CreateFlowLogsAction, CreateFpgaImageAction, CreateImageAction,
CreateInstanceExportTaskAction, CreateInternetGatewayAction, CreateKeyPairAction, CreateLaunchTemplateAction,
CreateLaunchTemplateVersionAction, CreateNatGatewayAction, CreateNetworkAclAction, CreateNetworkAclEntryAction,
CreateNetworkInterfaceAction, CreateNetworkInterfacePermissionAction, CreatePlacementGroupAction, CreateReservedInstancesListingAction,
CreateRouteAction, CreateRouteTableAction, CreateSecurityGroupAction, CreateSnapshotAction,
CreateSpotDatafeedSubscriptionAction, CreateSubnetAction, CreateTagsAction, CreateVolumeAction,
CreateVpcAction, CreateVpcEndpointAction, CreateVpcEndpointConnectionNotificationAction, CreateVpcEndpointServiceConfigurationAction,
CreateVpcPeeringConnectionAction, CreateVpnConnectionAction, CreateVpnConnectionRouteAction, CreateVpnGatewayAction,
DeleteCustomerGatewayAction, DeleteDhcpOptionsAction, DeleteEgressOnlyInternetGatewayAction, DeleteFlowLogsAction,
DeleteFpgaImageAction, DeleteInternetGatewayAction, DeleteKeyPairAction, DeleteLaunchTemplateAction,
DeleteLaunchTemplateVersionsAction, DeleteNatGatewayAction, DeleteNetworkAclAction, DeleteNetworkAclEntryAction,
DeleteNetworkInterfaceAction, DeleteNetworkInterfacePermissionAction, DeletePlacementGroupAction, DeleteRouteAction,
DeleteRouteTableAction, DeleteSecurityGroupAction, DeleteSnapshotAction, DeleteSpotDatafeedSubscriptionAction,
DeleteSubnetAction, DeleteTagsAction, DeleteVolumeAction, DeleteVpcAction,
DeleteVpcEndpointConnectionNotificationsAction, DeleteVpcEndpointServiceConfigurationsAction, DeleteVpcEndpointsAction, DeleteVpcPeeringConnectionAction,
DeleteVpnConnectionAction, DeleteVpnConnectionRouteAction, DeleteVpnGatewayAction, DeregisterImageAction,
DescribeAccountAttributesAction, DescribeAddressesAction, DescribeAggregateIdFormatAction, DescribeAvailabilityZonesAction,
DescribeBundleTasksAction, DescribeClassicLinkInstancesAction, DescribeConversionTasksAction, DescribeCustomerGatewaysAction,
DescribeDhcpOptionsAction, DescribeEgressOnlyInternetGatewaysAction, DescribeElasticGpusAction, DescribeExportTasksAction,
DescribeFlowLogsAction, DescribeFpgaImageAttributeAction, DescribeFpgaImagesAction, DescribeHostReservationOfferingsAction,
DescribeHostReservationsAction, DescribeHostsAction, DescribeIamInstanceProfileAssociationsAction, DescribeIdFormatAction,
DescribeIdentityIdFormatAction, DescribeImageAttributeAction, DescribeImagesAction, DescribeImportImageTasksAction,
DescribeImportSnapshotTasksAction, DescribeInstanceAttributeAction, DescribeInstanceCreditSpecificationsAction, DescribeInstanceStatusAction,
DescribeInstancesAction, DescribeInternetGatewaysAction, DescribeKeyPairsAction, DescribeLaunchTemplateVersionsAction,
DescribeLaunchTemplatesAction, DescribeMovingAddressesAction, DescribeNatGatewaysAction, DescribeNetworkAclsAction,
DescribeNetworkInterfaceAttributeAction, DescribeNetworkInterfacePermissionsAction, DescribeNetworkInterfacesAction, DescribePlacementGroupsAction,
DescribePrefixListsAction, DescribePrincipalIdFormatAction, DescribeRegionsAction, DescribeReservedInstancesAction,
DescribeReservedInstancesListingsAction, DescribeReservedInstancesModificationsAction, DescribeReservedInstancesOfferingsAction, DescribeRouteTablesAction,
DescribeScheduledInstanceAvailabilityAction, DescribeScheduledInstancesAction, DescribeSecurityGroupReferencesAction, DescribeSecurityGroupsAction,
DescribeSnapshotAttributeAction, DescribeSnapshotsAction, DescribeSpotDatafeedSubscriptionAction, DescribeSpotFleetInstancesAction,
DescribeSpotFleetRequestHistoryAction, DescribeSpotFleetRequestsAction, DescribeSpotInstanceRequestsAction, DescribeSpotPriceHistoryAction,
DescribeStaleSecurityGroupsAction, DescribeSubnetsAction, DescribeTagsAction, DescribeVolumeAttributeAction,
DescribeVolumeStatusAction, DescribeVolumesAction, DescribeVolumesModificationsAction, DescribeVpcAttributeAction,
DescribeVpcClassicLinkAction, DescribeVpcClassicLinkDnsSupportAction, DescribeVpcEndpointConnectionNotificationsAction, DescribeVpcEndpointConnectionsAction,
DescribeVpcEndpointServiceConfigurationsAction, DescribeVpcEndpointServicePermissionsAction, DescribeVpcEndpointServicesAction, DescribeVpcEndpointsAction,
DescribeVpcPeeringConnectionsAction, DescribeVpcsAction, DescribeVpnConnectionsAction, DescribeVpnGatewaysAction,
DetachClassicLinkVpcAction, DetachInternetGatewayAction, DetachNetworkInterfaceAction, DetachVolumeAction,
DetachVpnGatewayAction, DisableVgwRoutePropagationAction, DisableVpcClassicLinkAction, DisableVpcClassicLinkDnsSupportAction,
DisassociateAddressAction, DisassociateIamInstanceProfileAction, DisassociateRouteTableAction, DisassociateSubnetCidrBlockAction,
DisassociateVpcCidrBlockAction, EnableVgwRoutePropagationAction, EnableVolumeIOAction, EnableVpcClassicLinkAction,
EnableVpcClassicLinkDnsSupportAction, GetConsoleOutputAction, GetConsoleScreenshotAction, GetHostReservationPurchasePreviewAction,
GetLaunchTemplateDataAction, GetPasswordDataAction, GetReservedInstancesExchangeQuoteAction, ImportImageAction,
ImportInstanceAction, ImportKeyPairAction, ImportSnapshotAction, ImportVolumeAction,
ModifyFpgaImageAttributeAction, ModifyHostsAction, ModifyIdFormatAction, ModifyIdentityIdFormatAction,
ModifyImageAttributeAction, ModifyInstanceAttributeAction, ModifyInstanceCreditSpecificationAction, ModifyInstancePlacementAction,
ModifyLaunchTemplateAction, ModifyNetworkInterfaceAttributeAction, ModifyReservedInstancesAction, ModifySnapshotAttributeAction,
ModifySpotFleetRequestAction, ModifySubnetAttributeAction, ModifyVolumeAction, ModifyVolumeAttributeAction,
ModifyVpcAttributeAction, ModifyVpcEndpointAction, ModifyVpcEndpointConnectionNotificationAction, ModifyVpcEndpointServiceConfigurationAction,
ModifyVpcEndpointServicePermissionsAction, ModifyVpcPeeringConnectionOptionsAction, ModifyVpcTenancyAction, MonitorInstancesAction,
MoveAddressToVpcAction, PurchaseHostReservationAction, PurchaseReservedInstancesOfferingAction, PurchaseScheduledInstancesAction,
RebootInstancesAction, RegisterImageAction, RejectVpcEndpointConnectionsAction, RejectVpcPeeringConnectionAction,
ReleaseAddressAction, ReleaseHostsAction, ReplaceIamInstanceProfileAssociationAction, ReplaceNetworkAclAssociationAction,
ReplaceNetworkAclEntryAction, ReplaceRouteAction, ReplaceRouteTableAssociationAction, ReportInstanceStatusAction,
RequestSpotFleetAction, RequestSpotInstancesAction, ResetFpgaImageAttributeAction, ResetImageAttributeAction,
ResetInstanceAttributeAction, ResetNetworkInterfaceAttributeAction, ResetSnapshotAttributeAction, RestoreAddressToClassicAction,
RevokeSecurityGroupEgressAction, RevokeSecurityGroupIngressAction, RunInstancesAction, RunScheduledInstancesAction,
StartInstancesAction, StopInstancesAction, TerminateInstancesAction, UnassignIpv6AddressesAction,
UnassignPrivateIpAddressesAction, UnmonitorInstancesAction, UpdateSecurityGroupRuleDescriptionsEgressAction, UpdateSecurityGroupRuleDescriptionsIngressAction
}
Actions supported by EC2.
Public Member Functions
EC2Request (const Action action)
Constructs a new EC2Request object.
EC2Request (const EC2Request &other)
Constructs a new EC2Request object by copying another.
EC2Request & operator= (const EC2Request &other)
Assignment operator.
Action action () const
Get the EC2 action to be performed by this request.
QString actionString () const
Get the name of the EC2 action to be performed by this request.
QString apiVersion () const
Get the EC2 API version implemented by this request.
void setAction (const Action action)
Set the EC2 action to be performed by this request.
void setApiVersion (const QString &version)
Set the EC2 API version to include in this request.
virtual bool operator== (const EC2Request &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
EC2Request (EC2RequestPrivate *const d)
Constructs a new EC2Request object.
int clearParameter (const QString &name)
Check if queueName is a valid EC2 queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this EC2 request.
const QVariantMap & parameters () const
Get all parameters included with this EC2 request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this EC2 request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this EC2 request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this EC2 request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing EC2 requests.
Definition at line 35 of file ec2request.h.
Constructor & Destructor Documentation
EC2Request() [1/3]
QtAws::EC2::EC2Request::EC2Request (const Action action)
Constructs a new EC2Request object.
Parameters
action The EC2 action to request.
Definition at line 38 of file ec2request.cpp.
     : QtAws::Core::AwsAbstractRequest(new EC2RequestPrivate(action, this))
 {
 }
EC2Request() [2/3]
QtAws::EC2::EC2Request::EC2Request (const EC2Request & other)
Constructs a new EC2Request object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file ec2request.cpp.
     : QtAws::Core::AwsAbstractRequest(new EC2RequestPrivate(*other.d_func(), this))
 {
 }
EC2Request() [3/3]
QtAws::EC2::EC2Request::EC2Request (EC2RequestPrivate *const d) protected
Constructs a new EC2Request object.
This overload allows derived classes to provide their own private class implementation that inherits from EC2RequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file ec2request.cpp.
                                                   : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
EC2Request::Action QtAws::EC2::EC2Request::action () const
Get the EC2 action to be performed by this request.
Returns
The EC2 action to be performed by this request.
Definition at line 93 of file ec2request.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const EC2Request);
     return d->action;
 }
actionString()
QString QtAws::EC2::EC2Request::actionString () const
Get the name of the EC2 action to be performed by this request.
Returns
The name of the EC2 action to be performed by this request.
Definition at line 104 of file ec2request.cpp.
References action(), and QtAws::EC2::EC2RequestPrivate::toString().
 {
     return EC2RequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::EC2::EC2Request::apiVersion () const
Get the EC2 API version implemented by this request.
Returns
The EC2 API version implmented by this request.
Definition at line 114 of file ec2request.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const EC2Request);
     return d->apiVersion;
 }
clearParameter()
int QtAws::EC2::EC2Request::clearParameter (const QString & name) protected
Check if queueName is a valid EC2 queue name.
From EC2 FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid EC2 queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file ec2request.cpp.
 {
     Q_D(EC2Request);
     return d->parameters.remove(name);
 }
operator=()
EC2Request & QtAws::EC2::EC2Request::operator= (const EC2Request & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file ec2request.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(EC2Request);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::EC2::EC2Request::operator== (const EC2Request & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file ec2request.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::EC2::EC2Request::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this EC2 request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file ec2request.cpp.
 {
     Q_D(const EC2Request);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::EC2::EC2Request::parameters () const protected
Get all parameters included with this EC2 request.
Returns
A map of parameters included with this request.
Definition at line 222 of file ec2request.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const EC2Request);
     return d->parameters;
 }
setAction()
void QtAws::EC2::EC2Request::setAction (const Action action)
Set the EC2 action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file ec2request.cpp.
References action().
 {
     Q_D(EC2Request);
     d->action = action;
 }
setApiVersion()
void QtAws::EC2::EC2Request::setApiVersion (const QString & version)
Set the EC2 API version to include in this request.
Parameters
version The EC2 API version to include in this request.
Definition at line 136 of file ec2request.cpp.
 {
     Q_D(EC2Request);
     d->apiVersion = version;
 }
setParameter()
void QtAws::EC2::EC2Request::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this EC2 request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file ec2request.cpp.
 {
     Q_D(EC2Request);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::EC2::EC2Request::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this EC2 request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file ec2request.cpp.
References parameters().
 {
     Q_D(EC2Request);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::EC2::EC2Request::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this EC2 request.
This EC2 implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this EC2 request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file ec2request.cpp.
 {
     Q_D(const EC2Request);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
ec2/ec2request.h
ec2/ec2request.cpp