AWS SDK for Qt: QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient Class Reference
QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient Class Reference
Client for Elastic Load Balancing.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
ApplySecurityGroupsToLoadBalancerResponse * applySecurityGroupsToLoadBalancer (const ApplySecurityGroupsToLoadBalancerRequest &request)
AttachLoadBalancerToSubnetsResponse * attachLoadBalancerToSubnets (const AttachLoadBalancerToSubnetsRequest &request)
ConfigureHealthCheckResponse * configureHealthCheck (const ConfigureHealthCheckRequest &request)
CreateAppCookieStickinessPolicyResponse * createAppCookieStickinessPolicy (const CreateAppCookieStickinessPolicyRequest &request)
CreateLBCookieStickinessPolicyResponse * createLBCookieStickinessPolicy (const CreateLBCookieStickinessPolicyRequest &request)
CreateLoadBalancerResponse * createLoadBalancer (const CreateLoadBalancerRequest &request)
CreateLoadBalancerListenersResponse * createLoadBalancerListeners (const CreateLoadBalancerListenersRequest &request)
CreateLoadBalancerPolicyResponse * createLoadBalancerPolicy (const CreateLoadBalancerPolicyRequest &request)
DeleteLoadBalancerResponse * deleteLoadBalancer (const DeleteLoadBalancerRequest &request)
DeleteLoadBalancerListenersResponse * deleteLoadBalancerListeners (const DeleteLoadBalancerListenersRequest &request)
DeleteLoadBalancerPolicyResponse * deleteLoadBalancerPolicy (const DeleteLoadBalancerPolicyRequest &request)
DeregisterInstancesFromLoadBalancerResponse * deregisterInstancesFromLoadBalancer (const DeregisterInstancesFromLoadBalancerRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits (const DescribeAccountLimitsRequest &request)
DescribeInstanceHealthResponse * describeInstanceHealth (const DescribeInstanceHealthRequest &request)
DescribeLoadBalancerAttributesResponse * describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest &request)
DescribeLoadBalancerPoliciesResponse * describeLoadBalancerPolicies (const DescribeLoadBalancerPoliciesRequest &request)
DescribeLoadBalancerPolicyTypesResponse * describeLoadBalancerPolicyTypes (const DescribeLoadBalancerPolicyTypesRequest &request)
DescribeLoadBalancersResponse * describeLoadBalancers (const DescribeLoadBalancersRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DetachLoadBalancerFromSubnetsResponse * detachLoadBalancerFromSubnets (const DetachLoadBalancerFromSubnetsRequest &request)
DisableAvailabilityZonesForLoadBalancerResponse * disableAvailabilityZonesForLoadBalancer (const DisableAvailabilityZonesForLoadBalancerRequest &request)
EnableAvailabilityZonesForLoadBalancerResponse * enableAvailabilityZonesForLoadBalancer (const EnableAvailabilityZonesForLoadBalancerRequest &request)
ModifyLoadBalancerAttributesResponse * modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest &request)
RegisterInstancesWithLoadBalancerResponse * registerInstancesWithLoadBalancer (const RegisterInstancesWithLoadBalancerRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
SetLoadBalancerListenerSSLCertificateResponse * setLoadBalancerListenerSSLCertificate (const SetLoadBalancerListenerSSLCertificateRequest &request)
SetLoadBalancerPoliciesForBackendServerResponse * setLoadBalancerPoliciesForBackendServer (const SetLoadBalancerPoliciesForBackendServerRequest &request)
SetLoadBalancerPoliciesOfListenerResponse * setLoadBalancerPoliciesOfListener (const SetLoadBalancerPoliciesOfListenerRequest &request)
Public Member Functions
ElasticLoadBalancingClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
ElasticLoadBalancingClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Elastic Load Balancing.
<fullname>Elastic Load Balancing</fullname>
A load balancer can distribute incoming traffic across your EC2 instances. This enables you to increase the availability of your application. The load balancer also monitors the health of its registered instances and ensures that it routes traffic only to healthy instances. You configure your load balancer to accept incoming traffic by specifying one or more listeners, which are configured with a protocol and port number for connections from clients to the load balancer and a protocol and port number for connections from the load balancer to the
instances>
Elastic Load Balancing supports three types of load balancers: Application Load Balancers, Network Load Balancers, and Classic Load Balancers. You can select a load balancer based on your application needs. For more information, see the Elastic Load Balancing User Guide>
This reference covers the 2012-06-01 API, which supports Classic Load Balancers. The 2015-12-01 API supports Application Load Balancers and Network Load
Balancers>
To get started, create a load balancer with one or more listeners using CreateLoadBalancer. Register your instances with the load balancer using
RegisterInstancesWithLoadBalancer>
All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it succeeds with a 200 OK response
Definition at line 90 of file elasticloadbalancingclient.h.
Constructor & Destructor Documentation
ElasticLoadBalancingClient() [1/2]
QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 132 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->apiVersion = QStringLiteral("2012-06-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("elasticloadbalancing");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Elastic Load Balancing");
     d->serviceName = QStringLiteral("elasticloadbalancing");
 }
ElasticLoadBalancingClient() [2/2]
QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 165 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->apiVersion = QStringLiteral("2012-06-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("elasticloadbalancing");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Elastic Load Balancing");
     d->serviceName = QStringLiteral("elasticloadbalancing");
 }
Member Function Documentation
addTags
AddTagsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::addTags (const AddTagsRequest & request) slot
Adds the specified tags to the specified load balancer. Each load balancer can have a maximum of 10
tags>
Each tag consists of a key and an optional value. If a tag with the same key is already associated with the load balancer, AddTags updates its
value>
For more information, see Tag Your Classic Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 202 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
applySecurityGroupsToLoadBalancer
ApplySecurityGroupsToLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::applySecurityGroupsToLoadBalancer (const ApplySecurityGroupsToLoadBalancerRequest & request) slot
Associates one or more security groups with your load balancer in a virtual private cloud (VPC). The specified security groups override the previously associated security
groups>
For more information, see Security Groups for Load Balancers in a VPC in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 223 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ApplySecurityGroupsToLoadBalancerResponse *>(send(request));
 }
attachLoadBalancerToSubnets
AttachLoadBalancerToSubnetsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::attachLoadBalancerToSubnets (const AttachLoadBalancerToSubnetsRequest & request) slot
Adds one or more subnets to the set of configured subnets for the specified load
balancer>
The load balancer evenly distributes requests across all registered subnets. For more information, see Add or Remove Subnets for Your Load Balancer in a VPC in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 243 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachLoadBalancerToSubnetsResponse *>(send(request));
 }
configureHealthCheck
ConfigureHealthCheckResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::configureHealthCheck (const ConfigureHealthCheckRequest & request) slot
Specifies the health check settings to use when evaluating the health state of your EC2
instances>
For more information, see Configure Health Checks for Your Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 263 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfigureHealthCheckResponse *>(send(request));
 }
createAppCookieStickinessPolicy
CreateAppCookieStickinessPolicyResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createAppCookieStickinessPolicy (const CreateAppCookieStickinessPolicyRequest & request) slot
Generates a stickiness policy with sticky session lifetimes that follow that of an application-generated cookie. This policy can be associated only with HTTP/HTTPS
listeners>
This policy is similar to the policy created by CreateLBCookieStickinessPolicy, except that the lifetime of the special Elastic Load Balancing cookie, AWSELB, follows the lifetime of the application-generated cookie specified in the policy configuration. The load balancer only inserts a new stickiness cookie when the application response includes a new application
cookie>
If the application cookie is explicitly removed or expires, the session stops being sticky until a new application cookie is
issued>
For more information, see Application-Controlled Session Stickiness in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 296 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAppCookieStickinessPolicyResponse *>(send(request));
 }
createLBCookieStickinessPolicy
CreateLBCookieStickinessPolicyResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLBCookieStickinessPolicy (const CreateLBCookieStickinessPolicyRequest & request) slot
Generates a stickiness policy with sticky session lifetimes controlled by the lifetime of the browser (user-agent) or a specified expiration period. This policy can be associated only with HTTP/HTTPS
listeners>
When a load balancer implements this policy, the load balancer uses a special cookie to track the instance for each request. When the load balancer receives a request, it first checks to see if this cookie is present in the request. If so, the load balancer sends the request to the application server specified in the cookie. If not, the load balancer sends the request to a server that is chosen based on the existing load-balancing
algorithm>
A cookie is inserted into the response for binding subsequent requests from the same user to that server. The validity of the cookie is based on the cookie expiration time, which is specified in the policy
configuration>
For more information, see Duration-Based Session Stickiness in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 329 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLBCookieStickinessPolicyResponse *>(send(request));
 }
createLoadBalancer
CreateLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancer (const CreateLoadBalancerRequest & request) slot
Creates a Classic Load
Balancer>
You can add listeners, security groups, subnets, and tags when you create your load balancer, or you can add them later using CreateLoadBalancerListeners, ApplySecurityGroupsToLoadBalancer, AttachLoadBalancerToSubnets, and
AddTags>
To describe your current load balancers, see DescribeLoadBalancers. When you are finished with a load balancer, you can delete it using
DeleteLoadBalancer>
You can create up to 20 load balancers per region per account. You can request an increase for the number of load balancers for your account. For more information, see Limits for Your Classic Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 361 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLoadBalancerResponse *>(send(request));
 }
createLoadBalancerListeners
CreateLoadBalancerListenersResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancerListeners (const CreateLoadBalancerListenersRequest & request) slot
Creates one or more listeners for the specified load balancer. If a listener with the specified port does not already exist, it is created; otherwise, the properties of the new listener must match the properties of the existing
listener>
For more information, see Listeners for Your Classic Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 382 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLoadBalancerListenersResponse *>(send(request));
 }
createLoadBalancerPolicy
CreateLoadBalancerPolicyResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancerPolicy (const CreateLoadBalancerPolicyRequest & request) slot
Creates a policy with the specified attributes for the specified load
balancer>
Policies are settings that are saved for your load balancer and that can be applied to the listener or the application server, depending on the policy
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 401 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLoadBalancerPolicyResponse *>(send(request));
 }
deleteLoadBalancer
DeleteLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancer (const DeleteLoadBalancerRequest & request) slot
Deletes the specified load
balancer>
If you are attempting to recreate a load balancer, you must reconfigure all settings. The DNS name associated with a deleted load balancer are no longer usable. The name and associated DNS record of the deleted load balancer no longer exist and traffic sent to any of its IP addresses is no longer delivered to your
instances>
If the load balancer does not exist or has already been deleted, the call to DeleteLoadBalancer still
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 425 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLoadBalancerResponse *>(send(request));
 }
deleteLoadBalancerListeners
DeleteLoadBalancerListenersResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancerListeners (const DeleteLoadBalancerListenersRequest & request) slot
Deletes the specified listeners from the specified load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 439 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLoadBalancerListenersResponse *>(send(request));
 }
deleteLoadBalancerPolicy
DeleteLoadBalancerPolicyResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancerPolicy (const DeleteLoadBalancerPolicyRequest & request) slot
Deletes the specified policy from the specified load balancer. This policy must not be enabled for any
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 453 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLoadBalancerPolicyResponse *>(send(request));
 }
deregisterInstancesFromLoadBalancer
DeregisterInstancesFromLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deregisterInstancesFromLoadBalancer (const DeregisterInstancesFromLoadBalancerRequest & request) slot
Deregisters the specified instances from the specified load balancer. After the instance is deregistered, it no longer receives traffic from the load
balancer>
You can use DescribeLoadBalancers to verify that the instance is deregistered from the load
balancer>
For more information, see Register or De-Register EC2 Instances in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 478 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterInstancesFromLoadBalancerResponse *>(send(request));
 }
describeAccountLimits
DescribeAccountLimitsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeAccountLimits (const DescribeAccountLimitsRequest & request) slot
Describes the current Elastic Load Balancing resource limits for your AWS
account>
For more information, see Limits for Your Classic Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 498 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountLimitsResponse *>(send(request));
 }
describeInstanceHealth
DescribeInstanceHealthResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeInstanceHealth (const DescribeInstanceHealthRequest & request) slot
Describes the state of the specified instances with respect to the specified load balancer. If no instances are specified, the call describes the state of all instances that are currently registered with the load balancer. If instances are specified, their state is returned even if they are no longer registered with the load balancer. The state of terminated instances is not
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 515 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInstanceHealthResponse *>(send(request));
 }
describeLoadBalancerAttributes
DescribeLoadBalancerAttributesResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest & request) slot
Describes the attributes for the specified load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 529 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancerAttributesResponse *>(send(request));
 }
describeLoadBalancerPolicies
DescribeLoadBalancerPoliciesResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerPolicies (const DescribeLoadBalancerPoliciesRequest & request) slot
Describes the specified
policies>
If you specify a load balancer name, the action returns the descriptions of all policies created for the load balancer. If you specify a policy name associated with your load balancer, the action returns the description of that policy. If you don't specify a load balancer name, the action returns descriptions of the specified sample policies, or descriptions of all sample policies. The names of the sample policies have the ELBSample-
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 550 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancerPoliciesResponse *>(send(request));
 }
describeLoadBalancerPolicyTypes
DescribeLoadBalancerPolicyTypesResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerPolicyTypes (const DescribeLoadBalancerPolicyTypesRequest & request) slot
Describes the specified load balancer policy types or all load balancer policy
types>
The description of each type indicates how it can be used. For example, some policies can be used only with layer 7 listeners, some policies can be used only with layer 4 listeners, and some policies can be used only with your EC2
instances>
You can use CreateLoadBalancerPolicy to create a policy configuration for any of these policy types. Then, depending on the policy type, use either SetLoadBalancerPoliciesOfListener or SetLoadBalancerPoliciesForBackendServer to set the
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 575 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancerPolicyTypesResponse *>(send(request));
 }
describeLoadBalancers
DescribeLoadBalancersResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancers (const DescribeLoadBalancersRequest & request) slot
Describes the specified the load balancers. If no load balancers are specified, the call describes all of your load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 589 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancersResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeTags (const DescribeTagsRequest & request) slot
Describes the tags associated with the specified load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 603 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
detachLoadBalancerFromSubnets
DetachLoadBalancerFromSubnetsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::detachLoadBalancerFromSubnets (const DetachLoadBalancerFromSubnetsRequest & request) slot
Removes the specified subnets from the set of configured subnets for the load
balancer>
After a subnet is removed, all EC2 instances registered with the load balancer in the removed subnet go into the OutOfService state. Then, the load balancer balances the traffic among the remaining routable
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 622 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachLoadBalancerFromSubnetsResponse *>(send(request));
 }
disableAvailabilityZonesForLoadBalancer
DisableAvailabilityZonesForLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::disableAvailabilityZonesForLoadBalancer (const DisableAvailabilityZonesForLoadBalancerRequest & request) slot
Removes the specified Availability Zones from the set of Availability Zones for the specified load
balancer>
There must be at least one Availability Zone registered with a load balancer at all times. After an Availability Zone is removed, all instances registered with the load balancer that are in the removed Availability Zone go into the OutOfService state. Then, the load balancer attempts to equally balance the traffic among its remaining Availability
Zones>
For more information, see Add or Remove Availability Zones in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 649 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableAvailabilityZonesForLoadBalancerResponse *>(send(request));
 }
enableAvailabilityZonesForLoadBalancer
EnableAvailabilityZonesForLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::enableAvailabilityZonesForLoadBalancer (const EnableAvailabilityZonesForLoadBalancerRequest & request) slot
Adds the specified Availability Zones to the set of Availability Zones for the specified load
balancer>
The load balancer evenly distributes requests across all its registered Availability Zones that contain
instances>
For more information, see Add or Remove Availability Zones in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 673 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableAvailabilityZonesForLoadBalancerResponse *>(send(request));
 }
modifyLoadBalancerAttributes
ModifyLoadBalancerAttributesResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest & request) slot
Modifies the attributes of the specified load
balancer>
You can modify the load balancer attributes, such as AccessLogs, ConnectionDraining, and CrossZoneLoadBalancing by either enabling or disabling them. Or, you can modify the load balancer attribute ConnectionSettings by specifying an idle connection timeout value for your load
balancer>
For more information, see the following in the Classic Load Balancer
Guide>
Cross-Zone Load Balancing
</p
Connection Draining
</p
Access Logs
</p
Idle Connection Timeout
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 715 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyLoadBalancerAttributesResponse *>(send(request));
 }
registerInstancesWithLoadBalancer
RegisterInstancesWithLoadBalancerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::registerInstancesWithLoadBalancer (const RegisterInstancesWithLoadBalancerRequest & request) slot
Adds the specified instances to the specified load
balancer>
The instance must be a running instance in the same network as the load balancer (EC2-Classic or the same VPC). If you have EC2-Classic instances and a load balancer in a VPC with ClassicLink enabled, you can link the EC2-Classic instances to that VPC and then register the linked EC2-Classic instances with the load balancer in the
VPC>
Note that RegisterInstanceWithLoadBalancer completes when the request has been registered. Instance registration takes a little time to complete. To check the state of the registered instances, use DescribeLoadBalancers or
DescribeInstanceHealth>
After the instance is registered, it starts receiving traffic and requests from the load balancer. Any instance that is not in one of the Availability Zones registered for the load balancer is moved to the OutOfService state. If an Availability Zone is added to the load balancer later, any instances registered with the load balancer move to the InService
state>
To deregister instances from a load balancer, use
DeregisterInstancesFromLoadBalancer>
For more information, see Register or De-Register EC2 Instances in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 758 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterInstancesWithLoadBalancerResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::removeTags (const RemoveTagsRequest & request) slot
Removes one or more tags from the specified load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 772 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
setLoadBalancerListenerSSLCertificate
SetLoadBalancerListenerSSLCertificateResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerListenerSSLCertificate (const SetLoadBalancerListenerSSLCertificateRequest & request) slot
Sets the certificate that terminates the specified listener's SSL connections. The specified certificate replaces any prior certificate that was used on the same load balancer and
port>
For more information about updating your SSL certificate, see Replace the SSL Certificate for Your Load Balancer in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 793 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetLoadBalancerListenerSSLCertificateResponse *>(send(request));
 }
setLoadBalancerPoliciesForBackendServer
SetLoadBalancerPoliciesForBackendServerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerPoliciesForBackendServer (const SetLoadBalancerPoliciesForBackendServerRequest & request) slot
Replaces the set of policies associated with the specified port on which the EC2 instance is listening with a new set of policies. At this time, only the back-end server authentication policy type can be applied to the instance ports; this policy type is composed of multiple public key
policies>
Each time you use SetLoadBalancerPoliciesForBackendServer to enable the policies, use the PolicyNames parameter to list the policies that you want to
enable>
You can use DescribeLoadBalancers or DescribeLoadBalancerPolicies to verify that the policy is associated with the EC2
instance>
For more information about enabling back-end instance authentication, see Configure Back-end Instance Authentication in the Classic Load Balancer Guide. For more information about Proxy Protocol, see Configure Proxy Protocol Support in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 828 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetLoadBalancerPoliciesForBackendServerResponse *>(send(request));
 }
setLoadBalancerPoliciesOfListener
SetLoadBalancerPoliciesOfListenerResponse * QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerPoliciesOfListener (const SetLoadBalancerPoliciesOfListenerRequest & request) slot
Replaces the current set of policies for the specified load balancer port with the specified set of
policies>
To enable back-end server authentication, use
SetLoadBalancerPoliciesForBackendServer>
For more information about setting policies, see Update the SSL Negotiation Configuration, Duration-Based Session Stickiness, and Application-Controlled Session Stickiness in the Classic Load Balancer
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 856 of file elasticloadbalancingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetLoadBalancerPoliciesOfListenerResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
elasticloadbalancing/elasticloadbalancingclient.h
elasticloadbalancing/elasticloadbalancingclient.cpp