AWS SDK for Qt: QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client Class Reference
QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client Class Reference
Client for Elastic Load Balancing (Elastic Load Balancing v2)
Public Slots
AddListenerCertificatesResponse * addListenerCertificates (const AddListenerCertificatesRequest &request)
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateListenerResponse * createListener (const CreateListenerRequest &request)
CreateLoadBalancerResponse * createLoadBalancer (const CreateLoadBalancerRequest &request)
CreateRuleResponse * createRule (const CreateRuleRequest &request)
CreateTargetGroupResponse * createTargetGroup (const CreateTargetGroupRequest &request)
DeleteListenerResponse * deleteListener (const DeleteListenerRequest &request)
DeleteLoadBalancerResponse * deleteLoadBalancer (const DeleteLoadBalancerRequest &request)
DeleteRuleResponse * deleteRule (const DeleteRuleRequest &request)
DeleteTargetGroupResponse * deleteTargetGroup (const DeleteTargetGroupRequest &request)
DeregisterTargetsResponse * deregisterTargets (const DeregisterTargetsRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits (const DescribeAccountLimitsRequest &request)
DescribeListenerCertificatesResponse * describeListenerCertificates (const DescribeListenerCertificatesRequest &request)
DescribeListenersResponse * describeListeners (const DescribeListenersRequest &request)
DescribeLoadBalancerAttributesResponse * describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest &request)
DescribeLoadBalancersResponse * describeLoadBalancers (const DescribeLoadBalancersRequest &request)
DescribeRulesResponse * describeRules (const DescribeRulesRequest &request)
DescribeSSLPoliciesResponse * describeSSLPolicies (const DescribeSSLPoliciesRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeTargetGroupAttributesResponse * describeTargetGroupAttributes (const DescribeTargetGroupAttributesRequest &request)
DescribeTargetGroupsResponse * describeTargetGroups (const DescribeTargetGroupsRequest &request)
DescribeTargetHealthResponse * describeTargetHealth (const DescribeTargetHealthRequest &request)
ModifyListenerResponse * modifyListener (const ModifyListenerRequest &request)
ModifyLoadBalancerAttributesResponse * modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest &request)
ModifyRuleResponse * modifyRule (const ModifyRuleRequest &request)
ModifyTargetGroupResponse * modifyTargetGroup (const ModifyTargetGroupRequest &request)
ModifyTargetGroupAttributesResponse * modifyTargetGroupAttributes (const ModifyTargetGroupAttributesRequest &request)
RegisterTargetsResponse * registerTargets (const RegisterTargetsRequest &request)
RemoveListenerCertificatesResponse * removeListenerCertificates (const RemoveListenerCertificatesRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
SetIpAddressTypeResponse * setIpAddressType (const SetIpAddressTypeRequest &request)
SetRulePrioritiesResponse * setRulePriorities (const SetRulePrioritiesRequest &request)
SetSecurityGroupsResponse * setSecurityGroups (const SetSecurityGroupsRequest &request)
SetSubnetsResponse * setSubnets (const SetSubnetsRequest &request)
Public Member Functions
ElasticLoadBalancingv2Client (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingv2Client object.
ElasticLoadBalancingv2Client (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingv2Client object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Elastic Load Balancing (Elastic Load Balancing v2)
<fullname>Elastic Load Balancing</fullname>
A load balancer distributes incoming traffic across targets, such as your EC2 instances. This enables you to increase the availability of your application. The load balancer also monitors the health of its registered targets and ensures that it routes traffic only to healthy targets. You configure your load balancer to accept incoming traffic by specifying one or more listeners, which are configured with a protocol and port number for connections from clients to the load balancer. You configure a target group with a protocol and port number for connections from the load balancer to the targets, and with health check settings to be used when checking the health status of the
targets>
Elastic Load Balancing supports the following types of load balancers: Application Load Balancers, Network Load Balancers, and Classic Load
Balancers>
An Application Load Balancer makes routing and load balancing decisions at the application layer (HTTP/HTTPS). A Network Load Balancer makes routing and load balancing decisions at the transport layer (TCP). Both Application Load Balancers and Network Load Balancers can route requests to one or more ports on each EC2 instance or container instance in your virtual private cloud
(VPC)>
A Classic Load Balancer makes routing and load balancing decisions either at the transport layer (TCP/SSL) or the application layer (HTTP/HTTPS), and supports either EC2-Classic or a VPC. For more information, see the Elastic Load Balancing User Guide>
This reference covers the 2015-12-01 API, which supports Application Load Balancers and Network Load Balancers. The 2012-06-01 API supports Classic Load
Balancers>
To get started, complete the following
tasks>
Create a load balancer using
CreateLoadBalancer>
Create a target group using
CreateTargetGroup>
Register targets for the target group using
RegisterTargets>
Create one or more listeners for your load balancer using
CreateListener>
To delete a load balancer and its related resources, complete the following
tasks>
Delete the load balancer using
DeleteLoadBalancer>
Delete the target group using
DeleteTargetGroup>
All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it
Definition at line 100 of file elasticloadbalancingv2client.h.
Constructor & Destructor Documentation
ElasticLoadBalancingv2Client() [1/2]
QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingv2Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 182 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ElasticLoadBalancingv2ClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingv2Client);
     d->apiVersion = QStringLiteral("2015-12-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("elasticloadbalancing");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Elastic Load Balancing");
     d->serviceName = QStringLiteral("elasticloadbalancing");
 }
ElasticLoadBalancingv2Client() [2/2]
QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingv2Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 215 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ElasticLoadBalancingv2ClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingv2Client);
     d->apiVersion = QStringLiteral("2015-12-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("elasticloadbalancing");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Elastic Load Balancing");
     d->serviceName = QStringLiteral("elasticloadbalancing");
 }
Member Function Documentation
addListenerCertificates
AddListenerCertificatesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::addListenerCertificates (const AddListenerCertificatesRequest & request) slot
Adds the specified certificate to the specified secure
listener>
If the certificate was already added, the call is successful but the certificate is not added
again>
To list the certificates for your listener, use DescribeListenerCertificates. To remove certificates from your listener, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 250 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddListenerCertificatesResponse *>(send(request));
 }
addTags
AddTagsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::addTags (const AddTagsRequest & request) slot
Adds the specified tags to the specified Elastic Load Balancing resource. You can tag your Application Load Balancers, Network Load Balancers, and your target
groups>
Each tag consists of a key and an optional value. If a resource already has a tag with the same key, AddTags updates its
value>
To list the current tags for your resources, use DescribeTags. To remove tags from your resources, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 274 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
createListener
CreateListenerResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createListener (const CreateListenerRequest & request) slot
Creates a listener for the specified Application Load Balancer or Network Load
Balancer>
To update a listener, use ModifyListener. When you are finished with a listener, you can delete it using DeleteListener. If you are finished with both the listener and the load balancer, you can delete them both using
DeleteLoadBalancer>
This operation is idempotent, which means that it completes at most one time. If you attempt to create multiple listeners with the same settings, each call
succeeds>
For more information, see Listeners for Your Application Load Balancers in the Application Load Balancers Guide and Listeners for Your Network Load Balancers in the Network Load Balancers
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateListenerResponse *>(send(request));
 }
createLoadBalancer
CreateLoadBalancerResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createLoadBalancer (const CreateLoadBalancerRequest & request) slot
Creates an Application Load Balancer or a Network Load
Balancer>
When you create a load balancer, you can specify security groups, public subnets, IP address type, and tags. Otherwise, you could do so later using SetSecurityGroups, SetSubnets, SetIpAddressType, and
AddTags>
To create listeners for your load balancer, use CreateListener. To describe your current load balancers, see DescribeLoadBalancers. When you are finished with a load balancer, you can delete it using
DeleteLoadBalancer>
For limit information, see Limits for Your Application Load Balancer in the Application Load Balancers Guide and Limits for Your Network Load Balancer in the Network Load Balancers
Guide>
This operation is idempotent, which means that it completes at most one time. If you attempt to create multiple load balancers with the same settings, each call
succeeds>
For more information, see Application Load Balancers in the Application Load Balancers Guide and Network Load Balancers in the Network Load Balancers
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLoadBalancerResponse *>(send(request));
 }
createRule
CreateRuleResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createRule (const CreateRuleRequest & request) slot
Creates a rule for the specified listener. The listener must be associated with an Application Load
Balancer>
Rules are evaluated in priority order, from the lowest value to the highest value. When the condition for a rule is met, the specified action is taken. If no conditions are met, the action for the default rule is taken. For more information, see Listener Rules in the Application Load Balancers
Guide>
To view your current rules, use DescribeRules. To update a rule, use ModifyRule. To set the priorities of your rules, use SetRulePriorities. To delete a rule, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRuleResponse *>(send(request));
 }
createTargetGroup
CreateTargetGroupResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createTargetGroup (const CreateTargetGroupRequest & request) slot
Creates a target
group>
To register targets with the target group, use RegisterTargets. To update the health check settings for the target group, use ModifyTargetGroup. To monitor the health of targets in the target group, use
DescribeTargetHealth>
To route traffic to the targets in a target group, specify the target group in an action using CreateListener or
CreateRule>
To delete a target group, use
DeleteTargetGroup>
This operation is idempotent, which means that it completes at most one time. If you attempt to create multiple target groups with the same settings, each call
succeeds>
For more information, see Target Groups for Your Application Load Balancers in the Application Load Balancers Guide or Target Groups for Your Network Load Balancers in the Network Load Balancers
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 418 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTargetGroupResponse *>(send(request));
 }
deleteListener
DeleteListenerResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteListener (const DeleteListenerRequest & request) slot
Deletes the specified
listener>
Alternatively, your listener is deleted when you delete the load balancer it is attached to using
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 436 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteListenerResponse *>(send(request));
 }
deleteLoadBalancer
DeleteLoadBalancerResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteLoadBalancer (const DeleteLoadBalancerRequest & request) slot
Deletes the specified Application Load Balancer or Network Load Balancer and its attached
listeners>
You can't delete a load balancer if deletion protection is enabled. If the load balancer does not exist or has already been deleted, the call
succeeds>
Deleting a load balancer does not affect its registered targets. For example, your EC2 instances continue to run and are still registered to their target groups. If you no longer need these EC2 instances, you can stop or terminate
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 460 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLoadBalancerResponse *>(send(request));
 }
deleteRule
DeleteRuleResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteRule (const DeleteRuleRequest & request) slot
Deletes the specified
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 474 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRuleResponse *>(send(request));
 }
deleteTargetGroup
DeleteTargetGroupResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteTargetGroup (const DeleteTargetGroupRequest & request) slot
Deletes the specified target
group>
You can delete a target group if it is not referenced by any actions. Deleting a target group also deletes any associated health
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 493 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTargetGroupResponse *>(send(request));
 }
deregisterTargets
DeregisterTargetsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deregisterTargets (const DeregisterTargetsRequest & request) slot
Deregisters the specified targets from the specified target group. After the targets are deregistered, they no longer receive traffic from the load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 508 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterTargetsResponse *>(send(request));
 }
describeAccountLimits
DescribeAccountLimitsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeAccountLimits (const DescribeAccountLimitsRequest & request) slot
Describes the current Elastic Load Balancing resource limits for your AWS
account>
For more information, see Limits for Your Application Load Balancers in the Application Load Balancer Guide or Limits for Your Network Load Balancers in the Network Load Balancers
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 530 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountLimitsResponse *>(send(request));
 }
describeListenerCertificates
DescribeListenerCertificatesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeListenerCertificates (const DescribeListenerCertificatesRequest & request) slot
Describes the certificates for the specified secure
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 544 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeListenerCertificatesResponse *>(send(request));
 }
describeListeners
DescribeListenersResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeListeners (const DescribeListenersRequest & request) slot
Describes the specified listeners or the listeners for the specified Application Load Balancer or Network Load Balancer. You must specify either a load balancer or one or more
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeListenersResponse *>(send(request));
 }
describeLoadBalancerAttributes
DescribeLoadBalancerAttributesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest & request) slot
Describes the attributes for the specified Application Load Balancer or Network Load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 573 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancerAttributesResponse *>(send(request));
 }
describeLoadBalancers
DescribeLoadBalancersResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeLoadBalancers (const DescribeLoadBalancersRequest & request) slot
Describes the specified load balancers or all of your load
balancers>
To describe the listeners for a load balancer, use DescribeListeners. To describe the attributes for a load balancer, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 592 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancersResponse *>(send(request));
 }
describeRules
DescribeRulesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeRules (const DescribeRulesRequest & request) slot
Describes the specified rules or the rules for the specified listener. You must specify either a listener or one or more
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 606 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRulesResponse *>(send(request));
 }
describeSSLPolicies
DescribeSSLPoliciesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeSSLPolicies (const DescribeSSLPoliciesRequest & request) slot
Describes the specified policies or all policies used for SSL
negotiation>
For more information, see Security Policies in the Application Load Balancers
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 626 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSSLPoliciesResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTags (const DescribeTagsRequest & request) slot
Describes the tags for the specified resources. You can describe the tags for one or more Application Load Balancers, Network Load Balancers, and target
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 641 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
describeTargetGroupAttributes
DescribeTargetGroupAttributesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetGroupAttributes (const DescribeTargetGroupAttributesRequest & request) slot
Describes the attributes for the specified target
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 655 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTargetGroupAttributesResponse *>(send(request));
 }
describeTargetGroups
DescribeTargetGroupsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetGroups (const DescribeTargetGroupsRequest & request) slot
Describes the specified target groups or all of your target groups. By default, all target groups are described. Alternatively, you can specify one of the following to filter the results: the ARN of the load balancer, the names of one or more target groups, or the ARNs of one or more target
groups>
To describe the targets for a target group, use DescribeTargetHealth. To describe the attributes of a target group, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 676 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTargetGroupsResponse *>(send(request));
 }
describeTargetHealth
DescribeTargetHealthResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetHealth (const DescribeTargetHealthRequest & request) slot
Describes the health of the specified targets or all of your
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 690 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTargetHealthResponse *>(send(request));
 }
modifyListener
ModifyListenerResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyListener (const ModifyListenerRequest & request) slot
Modifies the specified properties of the specified
listener>
Any properties that you do not specify retain their current values. However, changing the protocol from HTTPS to HTTP removes the security policy and SSL certificate properties. If you change the protocol from HTTP to HTTPS, you must add the security policy and server
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 710 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyListenerResponse *>(send(request));
 }
modifyLoadBalancerAttributes
ModifyLoadBalancerAttributesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest & request) slot
Modifies the specified attributes of the specified Application Load Balancer or Network Load
Balancer>
If any of the specified attributes can't be modified as requested, the call fails. Any existing attributes that you do not modify retain their current
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 729 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyLoadBalancerAttributesResponse *>(send(request));
 }
modifyRule
ModifyRuleResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyRule (const ModifyRuleRequest & request) slot
Modifies the specified
rule>
Any existing properties that you do not modify retain their current
values>
To modify the default action, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 751 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyRuleResponse *>(send(request));
 }
modifyTargetGroup
ModifyTargetGroupResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyTargetGroup (const ModifyTargetGroupRequest & request) slot
Modifies the health checks used when evaluating the health state of the targets in the specified target
group>
To monitor the health of the targets, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 769 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyTargetGroupResponse *>(send(request));
 }
modifyTargetGroupAttributes
ModifyTargetGroupAttributesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyTargetGroupAttributes (const ModifyTargetGroupAttributesRequest & request) slot
Modifies the specified attributes of the specified target
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 783 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyTargetGroupAttributesResponse *>(send(request));
 }
registerTargets
RegisterTargetsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::registerTargets (const RegisterTargetsRequest & request) slot
Registers the specified targets with the specified target
group>
You can register targets by instance ID or by IP address. If the target is an EC2 instance, it must be in the running state when you register
it>
By default, the load balancer routes requests to registered targets using the protocol and port for the target group. Alternatively, you can override the port for a target when you register it. You can register each EC2 instance or IP address with the same target group multiple times using different
ports>
With a Network Load Balancer, you cannot register instances by instance ID if they have the following instance types: C1, CC1, CC2, CG1, CG2, CR1, CS1, G1, G2, HI1, HS1, M1, M2, M3, and T1. You can register instances of these types by IP
address>
To remove a target from a target group, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 817 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterTargetsResponse *>(send(request));
 }
removeListenerCertificates
RemoveListenerCertificatesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::removeListenerCertificates (const RemoveListenerCertificatesRequest & request) slot
Removes the specified certificate from the specified secure
listener>
You can't remove the default certificate for a listener. To replace the default certificate, call
ModifyListener>
To list the certificates for your listener, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 839 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveListenerCertificatesResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::removeTags (const RemoveTagsRequest & request) slot
Removes the specified tags from the specified Elastic Load Balancing
resource>
To list the current tags for your resources, use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 857 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
setIpAddressType
SetIpAddressTypeResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setIpAddressType (const SetIpAddressTypeRequest & request) slot
Sets the type of IP addresses used by the subnets of the specified Application Load Balancer or Network Load
Balancer>
Note that Network Load Balancers must use
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 875 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIpAddressTypeResponse *>(send(request));
 }
setRulePriorities
SetRulePrioritiesResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setRulePriorities (const SetRulePrioritiesRequest & request) slot
Sets the priorities of the specified
rules>
You can reorder the rules as long as there are no priority conflicts in the new order. Any existing rules that you do not specify retain their current
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 894 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetRulePrioritiesResponse *>(send(request));
 }
setSecurityGroups
SetSecurityGroupsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setSecurityGroups (const SetSecurityGroupsRequest & request) slot
Associates the specified security groups with the specified Application Load Balancer. The specified security groups override the previously associated security
groups>
Note that you can't specify a security group for a Network Load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 913 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetSecurityGroupsResponse *>(send(request));
 }
setSubnets
SetSubnetsResponse * QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setSubnets (const SetSubnetsRequest & request) slot
Enables the Availability Zone for the specified public subnets for the specified Application Load Balancer. The specified subnets replace the previously enabled
subnets>
Note that you can't change the subnets for a Network Load
Parameters
request Request to send to Elastic Load Balancing.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 932 of file elasticloadbalancingv2client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetSubnetsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
elasticloadbalancingv2/elasticloadbalancingv2client.h
elasticloadbalancingv2/elasticloadbalancingv2client.cpp