AWS SDK for Qt: QtAws::Glue::GlueRequest Class Reference
QtAws::Glue::GlueRequest Class Reference
Interface class for providing Glue requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::Glue::BatchCreatePartitionRequest, QtAws::Glue::BatchDeleteConnectionRequest, QtAws::Glue::BatchDeletePartitionRequest, QtAws::Glue::BatchDeleteTableRequest, QtAws::Glue::BatchDeleteTableVersionRequest, QtAws::Glue::BatchGetPartitionRequest, QtAws::Glue::BatchStopJobRunRequest, QtAws::Glue::CreateClassifierRequest, QtAws::Glue::CreateConnectionRequest, QtAws::Glue::CreateCrawlerRequest, QtAws::Glue::CreateDatabaseRequest, QtAws::Glue::CreateDevEndpointRequest, QtAws::Glue::CreateJobRequest, QtAws::Glue::CreatePartitionRequest, QtAws::Glue::CreateScriptRequest, QtAws::Glue::CreateTableRequest, QtAws::Glue::CreateTriggerRequest, QtAws::Glue::CreateUserDefinedFunctionRequest, QtAws::Glue::DeleteClassifierRequest, QtAws::Glue::DeleteConnectionRequest, QtAws::Glue::DeleteCrawlerRequest, QtAws::Glue::DeleteDatabaseRequest, QtAws::Glue::DeleteDevEndpointRequest, QtAws::Glue::DeleteJobRequest, QtAws::Glue::DeletePartitionRequest, QtAws::Glue::DeleteTableRequest, QtAws::Glue::DeleteTableVersionRequest, QtAws::Glue::DeleteTriggerRequest, QtAws::Glue::DeleteUserDefinedFunctionRequest, QtAws::Glue::GetCatalogImportStatusRequest, QtAws::Glue::GetClassifierRequest, QtAws::Glue::GetClassifiersRequest, QtAws::Glue::GetConnectionRequest, QtAws::Glue::GetConnectionsRequest, QtAws::Glue::GetCrawlerMetricsRequest, QtAws::Glue::GetCrawlerRequest, QtAws::Glue::GetCrawlersRequest, QtAws::Glue::GetDatabaseRequest, QtAws::Glue::GetDatabasesRequest, QtAws::Glue::GetDataflowGraphRequest, QtAws::Glue::GetDevEndpointRequest, QtAws::Glue::GetDevEndpointsRequest, QtAws::Glue::GetJobRequest, QtAws::Glue::GetJobRunRequest, QtAws::Glue::GetJobRunsRequest, QtAws::Glue::GetJobsRequest, QtAws::Glue::GetMappingRequest, QtAws::Glue::GetPartitionRequest, QtAws::Glue::GetPartitionsRequest, QtAws::Glue::GetPlanRequest, QtAws::Glue::GetTableRequest, QtAws::Glue::GetTablesRequest, QtAws::Glue::GetTableVersionRequest, QtAws::Glue::GetTableVersionsRequest, QtAws::Glue::GetTriggerRequest, QtAws::Glue::GetTriggersRequest, QtAws::Glue::GetUserDefinedFunctionRequest, QtAws::Glue::GetUserDefinedFunctionsRequest, QtAws::Glue::ImportCatalogToGlueRequest, QtAws::Glue::ResetJobBookmarkRequest, QtAws::Glue::StartCrawlerRequest, QtAws::Glue::StartCrawlerScheduleRequest, QtAws::Glue::StartJobRunRequest, QtAws::Glue::StartTriggerRequest, QtAws::Glue::StopCrawlerRequest, QtAws::Glue::StopCrawlerScheduleRequest, QtAws::Glue::StopTriggerRequest, QtAws::Glue::UpdateClassifierRequest, QtAws::Glue::UpdateConnectionRequest, QtAws::Glue::UpdateCrawlerRequest, QtAws::Glue::UpdateCrawlerScheduleRequest, QtAws::Glue::UpdateDatabaseRequest, QtAws::Glue::UpdateDevEndpointRequest, QtAws::Glue::UpdateJobRequest, QtAws::Glue::UpdatePartitionRequest, QtAws::Glue::UpdateTableRequest, QtAws::Glue::UpdateTriggerRequest, and QtAws::Glue::UpdateUserDefinedFunctionRequest.
Public Types
enum Action {
BatchCreatePartitionAction, BatchDeleteConnectionAction, BatchDeletePartitionAction, BatchDeleteTableAction,
BatchDeleteTableVersionAction, BatchGetPartitionAction, BatchStopJobRunAction, CreateClassifierAction,
CreateConnectionAction, CreateCrawlerAction, CreateDatabaseAction, CreateDevEndpointAction,
CreateJobAction, CreatePartitionAction, CreateScriptAction, CreateTableAction,
CreateTriggerAction, CreateUserDefinedFunctionAction, DeleteClassifierAction, DeleteConnectionAction,
DeleteCrawlerAction, DeleteDatabaseAction, DeleteDevEndpointAction, DeleteJobAction,
DeletePartitionAction, DeleteTableAction, DeleteTableVersionAction, DeleteTriggerAction,
DeleteUserDefinedFunctionAction, GetCatalogImportStatusAction, GetClassifierAction, GetClassifiersAction,
GetConnectionAction, GetConnectionsAction, GetCrawlerAction, GetCrawlerMetricsAction,
GetCrawlersAction, GetDatabaseAction, GetDatabasesAction, GetDataflowGraphAction,
GetDevEndpointAction, GetDevEndpointsAction, GetJobAction, GetJobRunAction,
GetJobRunsAction, GetJobsAction, GetMappingAction, GetPartitionAction,
GetPartitionsAction, GetPlanAction, GetTableAction, GetTableVersionAction,
GetTableVersionsAction, GetTablesAction, GetTriggerAction, GetTriggersAction,
GetUserDefinedFunctionAction, GetUserDefinedFunctionsAction, ImportCatalogToGlueAction, ResetJobBookmarkAction,
StartCrawlerAction, StartCrawlerScheduleAction, StartJobRunAction, StartTriggerAction,
StopCrawlerAction, StopCrawlerScheduleAction, StopTriggerAction, UpdateClassifierAction,
UpdateConnectionAction, UpdateCrawlerAction, UpdateCrawlerScheduleAction, UpdateDatabaseAction,
UpdateDevEndpointAction, UpdateJobAction, UpdatePartitionAction, UpdateTableAction,
UpdateTriggerAction, UpdateUserDefinedFunctionAction
}
Actions supported by Glue.
Public Member Functions
GlueRequest (const Action action)
Constructs a new GlueRequest object.
GlueRequest (const GlueRequest &other)
Constructs a new GlueRequest object by copying another.
GlueRequest & operator= (const GlueRequest &other)
Assignment operator.
Action action () const
Get the Glue action to be performed by this request.
QString actionString () const
Get the name of the Glue action to be performed by this request.
QString apiVersion () const
Get the Glue API version implemented by this request.
void setAction (const Action action)
Set the Glue action to be performed by this request.
void setApiVersion (const QString &version)
Set the Glue API version to include in this request.
virtual bool operator== (const GlueRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
GlueRequest (GlueRequestPrivate *const d)
Constructs a new GlueRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid Glue queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this Glue request.
const QVariantMap & parameters () const
Get all parameters included with this Glue request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this Glue request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this Glue request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this Glue request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing Glue requests.
Definition at line 35 of file gluerequest.h.
Constructor & Destructor Documentation
GlueRequest() [1/3]
QtAws::Glue::GlueRequest::GlueRequest (const Action action)
Constructs a new GlueRequest object.
Parameters
action The Glue action to request.
Definition at line 38 of file gluerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new GlueRequestPrivate(action, this))
 {
 }
GlueRequest() [2/3]
QtAws::Glue::GlueRequest::GlueRequest (const GlueRequest & other)
Constructs a new GlueRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file gluerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new GlueRequestPrivate(*other.d_func(), this))
 {
 }
GlueRequest() [3/3]
QtAws::Glue::GlueRequest::GlueRequest (GlueRequestPrivate *const d) protected
Constructs a new GlueRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from GlueRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file gluerequest.cpp.
                                                      : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
GlueRequest::Action QtAws::Glue::GlueRequest::action () const
Get the Glue action to be performed by this request.
Returns
The Glue action to be performed by this request.
Definition at line 93 of file gluerequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const GlueRequest);
     return d->action;
 }
actionString()
QString QtAws::Glue::GlueRequest::actionString () const
Get the name of the Glue action to be performed by this request.
Returns
The name of the Glue action to be performed by this request.
Definition at line 104 of file gluerequest.cpp.
References action(), and QtAws::Glue::GlueRequestPrivate::toString().
 {
     return GlueRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::Glue::GlueRequest::apiVersion () const
Get the Glue API version implemented by this request.
Returns
The Glue API version implmented by this request.
Definition at line 114 of file gluerequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const GlueRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::Glue::GlueRequest::clearParameter (const QString & name) protected
Check if queueName is a valid Glue queue name.
From Glue FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid Glue queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file gluerequest.cpp.
 {
     Q_D(GlueRequest);
     return d->parameters.remove(name);
 }
operator=()
GlueRequest & QtAws::Glue::GlueRequest::operator= (const GlueRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file gluerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(GlueRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::Glue::GlueRequest::operator== (const GlueRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file gluerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::Glue::GlueRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this Glue request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file gluerequest.cpp.
 {
     Q_D(const GlueRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::Glue::GlueRequest::parameters () const protected
Get all parameters included with this Glue request.
Returns
A map of parameters included with this request.
Definition at line 222 of file gluerequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const GlueRequest);
     return d->parameters;
 }
setAction()
void QtAws::Glue::GlueRequest::setAction (const Action action)
Set the Glue action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file gluerequest.cpp.
References action().
 {
     Q_D(GlueRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::Glue::GlueRequest::setApiVersion (const QString & version)
Set the Glue API version to include in this request.
Parameters
version The Glue API version to include in this request.
Definition at line 136 of file gluerequest.cpp.
 {
     Q_D(GlueRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::Glue::GlueRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this Glue request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file gluerequest.cpp.
 {
     Q_D(GlueRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::Glue::GlueRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this Glue request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file gluerequest.cpp.
References parameters().
 {
     Q_D(GlueRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::Glue::GlueRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this Glue request.
This Glue implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this Glue request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file gluerequest.cpp.
 {
     Q_D(const GlueRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
glue/gluerequest.h
glue/gluerequest.cpp