AWS SDK for Qt: QtAws::SqsOld::SqsRequest Class Reference
QtAws::SqsOld::SqsRequest Class Reference
Interface class for providing SQS requests.
Public Types
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Public Member Functions
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Static Public Member Functions
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Member Functions
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Friends
class TestSqsRequest
Detailed Description
Interface class for providing SQS requests.
Definition at line 36 of file sqsrequest.h.
Constructor & Destructor Documentation
SqsRequest() [1/3]
QtAws::SqsOld::SqsRequest::SqsRequest (const Action action)
Constructs a new SqsRequest object.
Parameters
action The SQS action to request.
Definition at line 45 of file sqsrequest.cpp.
     : AwsAbstractRequest(new SqsRequestPrivate(action, this))
 {
 }
SqsRequest() [2/3]
QtAws::SqsOld::SqsRequest::SqsRequest (const SqsRequest & other)
Constructs a new SqsRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 56 of file sqsrequest.cpp.
     : AwsAbstractRequest(new SqsRequestPrivate(*other.d_func(), this))
 {
 }
SqsRequest() [3/3]
QtAws::SqsOld::SqsRequest::SqsRequest (SqsRequestPrivate *const d) protected
Constructs a new SqsRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from SqsRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 90 of file sqsrequest.cpp.
                                                   : AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
SqsRequest::Action QtAws::SqsOld::SqsRequest::action () const
Get the SQS action to be performed by this request.
Returns
The SQS action to be performed by this request.
Definition at line 100 of file sqsrequest.cpp.
Referenced by actionString(), operator=(), operator==(), setAction(), and QtAws::SqsOld::SqsAddPermissionRequest::setPermission().
 {
     Q_D(const SqsRequest);
     return d->action;
 }
actionString()
QString QtAws::SqsOld::SqsRequest::actionString () const
Get the name of the SQS action to be performed by this request.
Returns
The name of the SQS action to be performed by this request.
Definition at line 111 of file sqsrequest.cpp.
References action(), and QtAws::SqsOld::SqsRequestPrivate::toString().
 {
     return SqsRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::SqsOld::SqsRequest::apiVersion () const
Get the SQS API version implemented by this request.
Returns
The SQS API version implmented by this request.
Definition at line 121 of file sqsrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::SqsOld::SqsRequest::clearParameter (const QString & name) protected
Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 195 of file sqsrequest.cpp.
Referenced by QtAws::SqsOld::SqsGetQueueUrlRequest::setQueueOwnerAWSAccountId().
 {
     Q_D(SqsRequest);
     return d->parameters.remove(name);
 }
isValidQueueName()
bool QtAws::SqsOld::SqsRequest::isValidQueueName (const QString & queueName) static
Check if queueName is a valid SQS queue name.
From SQS FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid SQS queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/
Definition at line 182 of file sqsrequest.cpp.
Referenced by QtAws::SqsOld::SqsCreateQueueRequest::isValid(), QtAws::SqsOld::SqsAddPermissionRequest::SqsAddPermissionRequest(), and QtAws::SqsOld::SqsGetQueueUrlRequest::SqsGetQueueUrlRequest().
 {
     const QRegExp pattern(QLatin1String("[a-zA-Z0-9-_]{1,80}"));
     return pattern.exactMatch(queueName);
 }
operator=()
SqsRequest & QtAws::SqsOld::SqsRequest::operator= (const SqsRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 71 of file sqsrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(SqsRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::SqsOld::SqsRequest::operator== (const SqsRequest & other) const virtual
Equality operator.
Note, most derived Sqs*Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 161 of file sqsrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::SqsOld::SqsRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this SQS request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 218 of file sqsrequest.cpp.
Referenced by QtAws::SqsOld::SqsCreateQueueRequest::attributes(), QtAws::SqsOld::SqsRemovePermissionRequest::label(), QtAws::SqsOld::SqsAddPermissionRequest::label(), QtAws::SqsOld::SqsGetQueueUrlRequest::queueName(), QtAws::SqsOld::SqsCreateQueueRequest::queueName(), QtAws::SqsOld::SqsListQueuesRequest::queueNamePrefix(), QtAws::SqsOld::SqsGetQueueUrlRequest::queueOwnerAWSAccountId(), QtAws::SqsOld::SqsDeleteQueueRequest::queueUrl(), QtAws::SqsOld::SqsPurgeQueueRequest::queueUrl(), QtAws::SqsOld::SqsDeleteMessageRequest::queueUrl(), QtAws::SqsOld::SqsListDeadLetterSourceQueuesRequest::queueUrl(), QtAws::SqsOld::SqsRemovePermissionRequest::queueUrl(), QtAws::SqsOld::SqsChangeMessageVisibilityRequest::queueUrl(), QtAws::SqsOld::SqsAddPermissionRequest::queueUrl(), QtAws::SqsOld::SqsDeleteMessageRequest::receiptHandle(), QtAws::SqsOld::SqsChangeMessageVisibilityRequest::receiptHandle(), and QtAws::SqsOld::SqsChangeMessageVisibilityRequest::visibilityTimeout().
 {
     Q_D(const SqsRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::SqsOld::SqsRequest::parameters () const protected
Get all parameters included with this SQS request.
Returns
A map of parameters included with this request.
Definition at line 229 of file sqsrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const SqsRequest);
     return d->parameters;
 }
setAction()
void QtAws::SqsOld::SqsRequest::setAction (const Action action)
Set the SQS action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 132 of file sqsrequest.cpp.
References action().
 {
     Q_D(SqsRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::SqsOld::SqsRequest::setApiVersion (const QString & version)
Set the SQS API version to include in this request.
Parameters
version The SQS API version to include in this request.
Definition at line 143 of file sqsrequest.cpp.
 {
     Q_D(SqsRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::SqsOld::SqsRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this SQS request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 241 of file sqsrequest.cpp.
Referenced by QtAws::SqsOld::SqsCreateQueueRequest::setAttributes(), QtAws::SqsOld::SqsRemovePermissionRequest::setLabel(), QtAws::SqsOld::SqsAddPermissionRequest::setLabel(), QtAws::SqsOld::SqsGetQueueUrlRequest::setQueueName(), QtAws::SqsOld::SqsCreateQueueRequest::setQueueName(), QtAws::SqsOld::SqsListQueuesRequest::setQueueNamePrefix(), QtAws::SqsOld::SqsGetQueueUrlRequest::setQueueOwnerAWSAccountId(), QtAws::SqsOld::SqsPurgeQueueRequest::setQueueUrl(), QtAws::SqsOld::SqsDeleteQueueRequest::setQueueUrl(), QtAws::SqsOld::SqsListDeadLetterSourceQueuesRequest::setQueueUrl(), QtAws::SqsOld::SqsDeleteMessageRequest::setQueueUrl(), QtAws::SqsOld::SqsRemovePermissionRequest::setQueueUrl(), QtAws::SqsOld::SqsChangeMessageVisibilityRequest::setQueueUrl(), QtAws::SqsOld::SqsAddPermissionRequest::setQueueUrl(), QtAws::SqsOld::SqsDeleteMessageRequest::setReceiptHandle(), QtAws::SqsOld::SqsChangeMessageVisibilityRequest::setReceiptHandle(), and QtAws::SqsOld::SqsChangeMessageVisibilityRequest::setVisibilityTimeout().
 {
     Q_D(SqsRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::SqsOld::SqsRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this SQS request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 254 of file sqsrequest.cpp.
References parameters().
 {
     Q_D(SqsRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::SqsOld::SqsRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this SQS request.
This SQS implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this SQS request using the given endpoint.
Definition at line 271 of file sqsrequest.cpp.
 {
     Q_D(const SqsRequest);
     QUrl url(endpoint);
     url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
sqs-old/sqsrequest.h
sqs-old/sqsrequest.cpp