AWS SDK for Qt: QtAws::Budgets::BudgetsClient Class Reference
QtAws::Budgets::BudgetsClient Class Reference
Client for AWS Budgets.
Public Slots
CreateBudgetResponse * createBudget (const CreateBudgetRequest &request)
CreateNotificationResponse * createNotification (const CreateNotificationRequest &request)
CreateSubscriberResponse * createSubscriber (const CreateSubscriberRequest &request)
DeleteBudgetResponse * deleteBudget (const DeleteBudgetRequest &request)
DeleteNotificationResponse * deleteNotification (const DeleteNotificationRequest &request)
DeleteSubscriberResponse * deleteSubscriber (const DeleteSubscriberRequest &request)
DescribeBudgetResponse * describeBudget (const DescribeBudgetRequest &request)
DescribeBudgetsResponse * describeBudgets (const DescribeBudgetsRequest &request)
DescribeNotificationsForBudgetResponse * describeNotificationsForBudget (const DescribeNotificationsForBudgetRequest &request)
DescribeSubscribersForNotificationResponse * describeSubscribersForNotification (const DescribeSubscribersForNotificationRequest &request)
UpdateBudgetResponse * updateBudget (const UpdateBudgetRequest &request)
UpdateNotificationResponse * updateNotification (const UpdateNotificationRequest &request)
UpdateSubscriberResponse * updateSubscriber (const UpdateSubscriberRequest &request)
Public Member Functions
BudgetsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new BudgetsClient object.
BudgetsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new BudgetsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Budgets.
Budgets enable you to plan your service usage, service costs, and your RI utilization. You can also track how close your plan is to your budgeted amount or to the free tier limits. Budgets provide you with a quick way to see your usage-to-date and current estimated charges from AWS and to see how much your predicted usage accrues in charges by the end of the month. Budgets also compare current estimates and charges to the amount that you indicated you want to use or spend and lets you see how much of your budget has been used. AWS updates your budget status several times a day. Budgets track your unblended costs, subscriptions, and refunds. You can create the following types of
budgets>
Cost budgets allow you to say how much you want to spend on a
service>
Usage budgets allow you to say how many hours you want to use for one or more
services>
RI utilization budgets allow you to define a utilization threshold and receive alerts when RIs are tracking below that
threshold>
You can create up to 20,000 budgets per AWS master account. Your first two budgets are free of charge. Each additional budget costs $0.02 per day. You can set up optional notifications that warn you if you exceed, or are forecasted to exceed, your budgeted amount. You can have notifications sent to an Amazon SNS topic, to an email address, or to both. For more information, see Creating an Amazon SNS Topic for Budget Notifications. AWS Free Tier usage alerts via AWS Budgets are provided for you, and do not count toward your budget
limits>
Service
Endpoin>
The AWS Budgets API provides the following
endpoint>
Definition at line 58 of file budgetsclient.h.
Constructor & Destructor Documentation
BudgetsClient() [1/2]
QtAws::Budgets::BudgetsClient::BudgetsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new BudgetsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 110 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new BudgetsClientPrivate(this), parent)
 {
     Q_D(BudgetsClient);
     d->apiVersion = QStringLiteral("2016-10-20");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("budgets");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Budgets");
     d->serviceName = QStringLiteral("budgets");
 }
BudgetsClient() [2/2]
QtAws::Budgets::BudgetsClient::BudgetsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new BudgetsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 143 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new BudgetsClientPrivate(this), parent)
 {
     Q_D(BudgetsClient);
     d->apiVersion = QStringLiteral("2016-10-20");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("budgets");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Budgets");
     d->serviceName = QStringLiteral("budgets");
 }
Member Function Documentation
createBudget
CreateBudgetResponse * QtAws::Budgets::BudgetsClient::createBudget (const CreateBudgetRequest & request) slot
Creates a budget and, if included, notifications and subscribers.
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 169 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBudgetResponse *>(send(request));
 }
createNotification
CreateNotificationResponse * QtAws::Budgets::BudgetsClient::createNotification (const CreateNotificationRequest & request) slot
Creates a notification. You must create the budget before you create the associated
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 183 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNotificationResponse *>(send(request));
 }
createSubscriber
CreateSubscriberResponse * QtAws::Budgets::BudgetsClient::createSubscriber (const CreateSubscriberRequest & request) slot
Creates a subscriber. You must create the associated budget and notification before you create the
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 197 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSubscriberResponse *>(send(request));
 }
deleteBudget
DeleteBudgetResponse * QtAws::Budgets::BudgetsClient::deleteBudget (const DeleteBudgetRequest & request) slot
Deletes a budget. You can delete your budget at any
time>
Deleting a budget also deletes the notifications and subscribers associated with that budget.
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 215 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBudgetResponse *>(send(request));
 }
deleteNotification
DeleteNotificationResponse * QtAws::Budgets::BudgetsClient::deleteNotification (const DeleteNotificationRequest & request) slot
Deletes a
notification>
Deleting a notification also deletes the subscribers associated with the notification.
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 233 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNotificationResponse *>(send(request));
 }
deleteSubscriber
DeleteSubscriberResponse * QtAws::Budgets::BudgetsClient::deleteSubscriber (const DeleteSubscriberRequest & request) slot
Deletes a
subscriber>
Deleting the last subscriber to a notification also deletes the notification.
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 251 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSubscriberResponse *>(send(request));
 }
describeBudget
DescribeBudgetResponse * QtAws::Budgets::BudgetsClient::describeBudget (const DescribeBudgetRequest & request) slot
Describes a
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 265 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBudgetResponse *>(send(request));
 }
describeBudgets
DescribeBudgetsResponse * QtAws::Budgets::BudgetsClient::describeBudgets (const DescribeBudgetsRequest & request) slot
Lists the budgets associated with an
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 279 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBudgetsResponse *>(send(request));
 }
describeNotificationsForBudget
DescribeNotificationsForBudgetResponse * QtAws::Budgets::BudgetsClient::describeNotificationsForBudget (const DescribeNotificationsForBudgetRequest & request) slot
Lists the notifications associated with a
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 293 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNotificationsForBudgetResponse *>(send(request));
 }
describeSubscribersForNotification
DescribeSubscribersForNotificationResponse * QtAws::Budgets::BudgetsClient::describeSubscribersForNotification (const DescribeSubscribersForNotificationRequest & request) slot
Lists the subscribers associated with a
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 307 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSubscribersForNotificationResponse *>(send(request));
 }
updateBudget
UpdateBudgetResponse * QtAws::Budgets::BudgetsClient::updateBudget (const UpdateBudgetRequest & request) slot
Updates a budget. You can change every part of a budget except for the budgetName and the calculatedSpend. When a budget is modified, the calculatedSpend drops to zero until AWS has new usage data to use for
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 323 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBudgetResponse *>(send(request));
 }
updateNotification
UpdateNotificationResponse * QtAws::Budgets::BudgetsClient::updateNotification (const UpdateNotificationRequest & request) slot
Updates a
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 337 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateNotificationResponse *>(send(request));
 }
updateSubscriber
UpdateSubscriberResponse * QtAws::Budgets::BudgetsClient::updateSubscriber (const UpdateSubscriberRequest & request) slot
Updates a
Parameters
request Request to send to AWS Budgets.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file budgetsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSubscriberResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
budgets/budgetsclient.h
budgets/budgetsclient.cpp