AWS SDK for Qt: QtAws::DirectConnect::DirectConnectClient Class Reference
QtAws::DirectConnect::DirectConnectClient Class Reference
Client for AWS Direct Connect.
Public Slots
AllocateConnectionOnInterconnectResponse * allocateConnectionOnInterconnect (const AllocateConnectionOnInterconnectRequest &request)
AllocateHostedConnectionResponse * allocateHostedConnection (const AllocateHostedConnectionRequest &request)
AllocatePrivateVirtualInterfaceResponse * allocatePrivateVirtualInterface (const AllocatePrivateVirtualInterfaceRequest &request)
AllocatePublicVirtualInterfaceResponse * allocatePublicVirtualInterface (const AllocatePublicVirtualInterfaceRequest &request)
AssociateConnectionWithLagResponse * associateConnectionWithLag (const AssociateConnectionWithLagRequest &request)
AssociateHostedConnectionResponse * associateHostedConnection (const AssociateHostedConnectionRequest &request)
AssociateVirtualInterfaceResponse * associateVirtualInterface (const AssociateVirtualInterfaceRequest &request)
ConfirmConnectionResponse * confirmConnection (const ConfirmConnectionRequest &request)
ConfirmPrivateVirtualInterfaceResponse * confirmPrivateVirtualInterface (const ConfirmPrivateVirtualInterfaceRequest &request)
ConfirmPublicVirtualInterfaceResponse * confirmPublicVirtualInterface (const ConfirmPublicVirtualInterfaceRequest &request)
CreateBGPPeerResponse * createBGPPeer (const CreateBGPPeerRequest &request)
CreateConnectionResponse * createConnection (const CreateConnectionRequest &request)
CreateDirectConnectGatewayResponse * createDirectConnectGateway (const CreateDirectConnectGatewayRequest &request)
CreateDirectConnectGatewayAssociationResponse * createDirectConnectGatewayAssociation (const CreateDirectConnectGatewayAssociationRequest &request)
CreateInterconnectResponse * createInterconnect (const CreateInterconnectRequest &request)
CreateLagResponse * createLag (const CreateLagRequest &request)
CreatePrivateVirtualInterfaceResponse * createPrivateVirtualInterface (const CreatePrivateVirtualInterfaceRequest &request)
CreatePublicVirtualInterfaceResponse * createPublicVirtualInterface (const CreatePublicVirtualInterfaceRequest &request)
DeleteBGPPeerResponse * deleteBGPPeer (const DeleteBGPPeerRequest &request)
DeleteConnectionResponse * deleteConnection (const DeleteConnectionRequest &request)
DeleteDirectConnectGatewayResponse * deleteDirectConnectGateway (const DeleteDirectConnectGatewayRequest &request)
DeleteDirectConnectGatewayAssociationResponse * deleteDirectConnectGatewayAssociation (const DeleteDirectConnectGatewayAssociationRequest &request)
DeleteInterconnectResponse * deleteInterconnect (const DeleteInterconnectRequest &request)
DeleteLagResponse * deleteLag (const DeleteLagRequest &request)
DeleteVirtualInterfaceResponse * deleteVirtualInterface (const DeleteVirtualInterfaceRequest &request)
DescribeConnectionLoaResponse * describeConnectionLoa (const DescribeConnectionLoaRequest &request)
DescribeConnectionsResponse * describeConnections (const DescribeConnectionsRequest &request)
DescribeConnectionsOnInterconnectResponse * describeConnectionsOnInterconnect (const DescribeConnectionsOnInterconnectRequest &request)
DescribeDirectConnectGatewayAssociationsResponse * describeDirectConnectGatewayAssociations (const DescribeDirectConnectGatewayAssociationsRequest &request)
DescribeDirectConnectGatewayAttachmentsResponse * describeDirectConnectGatewayAttachments (const DescribeDirectConnectGatewayAttachmentsRequest &request)
DescribeDirectConnectGatewaysResponse * describeDirectConnectGateways (const DescribeDirectConnectGatewaysRequest &request)
DescribeHostedConnectionsResponse * describeHostedConnections (const DescribeHostedConnectionsRequest &request)
DescribeInterconnectLoaResponse * describeInterconnectLoa (const DescribeInterconnectLoaRequest &request)
DescribeInterconnectsResponse * describeInterconnects (const DescribeInterconnectsRequest &request)
DescribeLagsResponse * describeLags (const DescribeLagsRequest &request)
DescribeLoaResponse * describeLoa (const DescribeLoaRequest &request)
DescribeLocationsResponse * describeLocations ()
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeVirtualGatewaysResponse * describeVirtualGateways ()
DescribeVirtualInterfacesResponse * describeVirtualInterfaces (const DescribeVirtualInterfacesRequest &request)
DisassociateConnectionFromLagResponse * disassociateConnectionFromLag (const DisassociateConnectionFromLagRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateLagResponse * updateLag (const UpdateLagRequest &request)
Public Member Functions
DirectConnectClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DirectConnectClient object.
DirectConnectClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DirectConnectClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Direct Connect.
AWS Direct Connect links your internal network to an AWS Direct Connect location over a standard 1 gigabit or 10 gigabit Ethernet fiber-optic cable. One end of the cable is connected to your router, the other to an AWS Direct Connect router. With this connection in place, you can create virtual interfaces directly to the AWS cloud (for example, to Amazon Elastic Compute Cloud (Amazon EC2) and Amazon Simple Storage Service (Amazon S3)) and to Amazon Virtual Private Cloud (Amazon VPC), bypassing Internet service providers in your network path. An AWS Direct Connect location provides access to AWS in the region it is associated with, as well as access to other US regions. For example, you can provision a single connection to any AWS Direct Connect location in the US and use it to access public AWS services in all US Regions and AWS GovCloud
Definition at line 118 of file directconnectclient.h.
Constructor & Destructor Documentation
DirectConnectClient() [1/2]
QtAws::DirectConnect::DirectConnectClient::DirectConnectClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DirectConnectClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 140 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DirectConnectClientPrivate(this), parent)
 {
     Q_D(DirectConnectClient);
     d->apiVersion = QStringLiteral("2012-10-25");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("directconnect");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Direct Connect");
     d->serviceName = QStringLiteral("directconnect");
 }
DirectConnectClient() [2/2]
QtAws::DirectConnect::DirectConnectClient::DirectConnectClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DirectConnectClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 173 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DirectConnectClientPrivate(this), parent)
 {
     Q_D(DirectConnectClient);
     d->apiVersion = QStringLiteral("2012-10-25");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("directconnect");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Direct Connect");
     d->serviceName = QStringLiteral("directconnect");
 }
Member Function Documentation
allocateConnectionOnInterconnect
AllocateConnectionOnInterconnectResponse * QtAws::DirectConnect::DirectConnectClient::allocateConnectionOnInterconnect (const AllocateConnectionOnInterconnectRequest & request) slot
Deprecated in favor of
AllocateHostedConnection>
Creates a hosted connection on an
interconnect>
Allocates a VLAN number and a specified amount of bandwidth for use by a hosted connection on the given
interconnect> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 211 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocateConnectionOnInterconnectResponse *>(send(request));
 }
allocateHostedConnection
AllocateHostedConnectionResponse * QtAws::DirectConnect::DirectConnectClient::allocateHostedConnection (const AllocateHostedConnectionRequest & request) slot
Creates a hosted connection on an interconnect or a link aggregation group
(LAG)>
Allocates a VLAN number and a specified amount of bandwidth for use by a hosted connection on the given interconnect or
LAG> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 233 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocateHostedConnectionResponse *>(send(request));
 }
allocatePrivateVirtualInterface
AllocatePrivateVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::allocatePrivateVirtualInterface (const AllocatePrivateVirtualInterfaceRequest & request) slot
Provisions a private virtual interface to be owned by another AWS
customer>
Virtual interfaces created using this action must be confirmed by the virtual interface owner by using the ConfirmPrivateVirtualInterface action. Until then, the virtual interface will be in 'Confirming' state, and will not be available for handling
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 253 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocatePrivateVirtualInterfaceResponse *>(send(request));
 }
allocatePublicVirtualInterface
AllocatePublicVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::allocatePublicVirtualInterface (const AllocatePublicVirtualInterfaceRequest & request) slot
Provisions a public virtual interface to be owned by a different
customer>
The owner of a connection calls this function to provision a public virtual interface which will be owned by another AWS
customer>
Virtual interfaces created using this function must be confirmed by the virtual interface owner by calling ConfirmPublicVirtualInterface. Until this step has been completed, the virtual interface will be in 'Confirming' state, and will not be available for handling
traffic>
When creating an IPv6 public virtual interface (addressFamily is 'ipv6'), the customer and amazon address fields should be left blank to use auto-assigned IPv6 space. Custom IPv6 Addresses are currently not
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 282 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AllocatePublicVirtualInterfaceResponse *>(send(request));
 }
associateConnectionWithLag
AssociateConnectionWithLagResponse * QtAws::DirectConnect::DirectConnectClient::associateConnectionWithLag (const AssociateConnectionWithLagRequest & request) slot
Associates an existing connection with a link aggregation group (LAG). The connection is interrupted and re-established as a member of the LAG (connectivity to AWS will be interrupted). The connection must be hosted on the same AWS Direct Connect endpoint as the LAG, and its bandwidth must match the bandwidth for the LAG. You can reassociate a connection that's currently associated with a different LAG; however, if removing the connection will cause the original LAG to fall below its setting for minimum number of operational connections, the request
fails>
Any virtual interfaces that are directly associated with the connection are automatically re-associated with the LAG. If the connection was originally associated with a different LAG, the virtual interfaces remain associated with the original
LAG>
For interconnects, any hosted connections are automatically re-associated with the LAG. If the interconnect was originally associated with a different LAG, the hosted connections remain associated with the original
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 311 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateConnectionWithLagResponse *>(send(request));
 }
associateHostedConnection
AssociateHostedConnectionResponse * QtAws::DirectConnect::DirectConnectClient::associateHostedConnection (const AssociateHostedConnectionRequest & request) slot
Associates a hosted connection and its virtual interfaces with a link aggregation group (LAG) or interconnect. If the target interconnect or LAG has an existing hosted connection with a conflicting VLAN number or IP address, the operation fails. This action temporarily interrupts the hosted connection's connectivity to AWS as it is being
migrated> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 331 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateHostedConnectionResponse *>(send(request));
 }
associateVirtualInterface
AssociateVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::associateVirtualInterface (const AssociateVirtualInterfaceRequest & request) slot
Associates a virtual interface with a specified link aggregation group (LAG) or connection. Connectivity to AWS is temporarily interrupted as the virtual interface is being migrated. If the target connection or LAG has an associated virtual interface with a conflicting VLAN number or a conflicting IP address, the operation fails.
</p
Virtual interfaces associated with a hosted connection cannot be associated with a LAG; hosted connections must be migrated along with their virtual interfaces using
AssociateHostedConnection>
In order to reassociate a virtual interface to a new connection or LAG, the requester must own either the virtual interface itself or the connection to which the virtual interface is currently associated. Additionally, the requester must own the connection or LAG to which the virtual interface will be newly
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 358 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateVirtualInterfaceResponse *>(send(request));
 }
confirmConnection
ConfirmConnectionResponse * QtAws::DirectConnect::DirectConnectClient::confirmConnection (const ConfirmConnectionRequest & request) slot
Confirm the creation of a hosted connection on an
interconnect>
Upon creation, the hosted connection is initially in the 'Ordering' state, and will remain in this state until the owner calls ConfirmConnection to confirm creation of the hosted
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmConnectionResponse *>(send(request));
 }
confirmPrivateVirtualInterface
ConfirmPrivateVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::confirmPrivateVirtualInterface (const ConfirmPrivateVirtualInterfaceRequest & request) slot
Accept ownership of a private virtual interface created by another
customer>
After the virtual interface owner calls this function, the virtual interface will be created and attached to the given virtual private gateway or direct connect gateway, and will be available for handling
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 396 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmPrivateVirtualInterfaceResponse *>(send(request));
 }
confirmPublicVirtualInterface
ConfirmPublicVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::confirmPublicVirtualInterface (const ConfirmPublicVirtualInterfaceRequest & request) slot
Accept ownership of a public virtual interface created by another
customer>
After the virtual interface owner calls this function, the specified virtual interface will be created and made available for handling
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 415 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ConfirmPublicVirtualInterfaceResponse *>(send(request));
 }
createBGPPeer
CreateBGPPeerResponse * QtAws::DirectConnect::DirectConnectClient::createBGPPeer (const CreateBGPPeerRequest & request) slot
Creates a new BGP peer on a specified virtual interface. The BGP peer cannot be in the same address family (IPv4/IPv6) of an existing BGP peer on the virtual
interface>
You must create a BGP peer for the corresponding address family in order to access AWS resources that also use that address
family>
When creating a IPv6 BGP peer, the Amazon address and customer address fields must be left blank. IPv6 addresses are automatically assigned from Amazon's pool of IPv6 addresses; you cannot specify custom IPv6
addresses>
For a public virtual interface, the Autonomous System Number (ASN) must be private or already whitelisted for the virtual
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 445 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBGPPeerResponse *>(send(request));
 }
createConnection
CreateConnectionResponse * QtAws::DirectConnect::DirectConnectClient::createConnection (const CreateConnectionRequest & request) slot
Creates a new connection between the customer network and a specific AWS Direct Connect
location>
A connection links your internal network to an AWS Direct Connect location over a standard 1 gigabit or 10 gigabit Ethernet fiber-optic cable. One end of the cable is connected to your router, the other to an AWS Direct Connect router. An AWS Direct Connect location provides access to Amazon Web Services in the region it is associated with. You can establish connections with AWS Direct Connect locations in multiple regions, but a connection in one region does not provide connectivity to other
regions>
To find the locations for your region, use
DescribeLocations>
You can automatically add the new connection to a link aggregation group (LAG) by specifying a LAG ID in the request. This ensures that the new connection is allocated on the same AWS Direct Connect endpoint that hosts the specified LAG. If there are no available ports on the endpoint, the request fails and no connection will be
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 477 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConnectionResponse *>(send(request));
 }
createDirectConnectGateway
CreateDirectConnectGatewayResponse * QtAws::DirectConnect::DirectConnectClient::createDirectConnectGateway (const CreateDirectConnectGatewayRequest & request) slot
Creates a new direct connect gateway. A direct connect gateway is an intermediate object that enables you to connect a set of virtual interfaces and virtual private gateways. direct connect gateways are global and visible in any AWS region after they are created. The virtual interfaces and virtual private gateways that are connected through a direct connect gateway can be in different regions. This enables you to connect to a VPC in any region, regardless of the region in which the virtual interfaces are located, and pass traffic between
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 495 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDirectConnectGatewayResponse *>(send(request));
 }
createDirectConnectGatewayAssociation
CreateDirectConnectGatewayAssociationResponse * QtAws::DirectConnect::DirectConnectClient::createDirectConnectGatewayAssociation (const CreateDirectConnectGatewayAssociationRequest & request) slot
Creates an association between a direct connect gateway and a virtual private gateway (VGW). The VGW must be attached to a VPC and must not be associated with another direct connect
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 510 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDirectConnectGatewayAssociationResponse *>(send(request));
 }
createInterconnect
CreateInterconnectResponse * QtAws::DirectConnect::DirectConnectClient::createInterconnect (const CreateInterconnectRequest & request) slot
Creates a new interconnect between a AWS Direct Connect partner's network and a specific AWS Direct Connect
location>
An interconnect is a connection which is capable of hosting other connections. The AWS Direct Connect partner can use an interconnect to provide sub-1Gbps AWS Direct Connect service to tier 2 customers who do not have their own connections. Like a standard connection, an interconnect links the AWS Direct Connect partner's network to an AWS Direct Connect location over a standard 1 Gbps or 10 Gbps Ethernet fiber-optic cable. One end is connected to the partner's router, the other to an AWS Direct Connect
router>
You can automatically add the new interconnect to a link aggregation group (LAG) by specifying a LAG ID in the request. This ensures that the new interconnect is allocated on the same AWS Direct Connect endpoint that hosts the specified LAG. If there are no available ports on the endpoint, the request fails and no interconnect will be
created>
For each end customer, the AWS Direct Connect partner provisions a connection on their interconnect by calling AllocateConnectionOnInterconnect. The end customer can then connect to AWS resources by creating a virtual interface on their connection, using the VLAN assigned to them by the AWS Direct Connect
partner> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 548 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInterconnectResponse *>(send(request));
 }
createLag
CreateLagResponse * QtAws::DirectConnect::DirectConnectClient::createLag (const CreateLagRequest & request) slot
Creates a new link aggregation group (LAG) with the specified number of bundled physical connections between the customer network and a specific AWS Direct Connect location. A LAG is a logical interface that uses the Link Aggregation Control Protocol (LACP) to aggregate multiple 1 gigabit or 10 gigabit interfaces, allowing you to treat them as a single
interface>
All connections in a LAG must use the same bandwidth (for example, 10 Gbps), and must terminate at the same AWS Direct Connect
endpoint>
You can have up to 10 connections per LAG. Regardless of this limit, if you request more connections for the LAG than AWS Direct Connect can allocate on a single endpoint, no LAG is
created>
You can specify an existing physical connection or interconnect to include in the LAG (which counts towards the total number of connections). Doing so interrupts the current physical connection or hosted connections, and re-establishes them as a member of the LAG. The LAG will be created on the same AWS Direct Connect endpoint to which the connection terminates. Any virtual interfaces associated with the connection are automatically disassociated and re-associated with the LAG. The connection ID does not
change>
If the AWS account used to create a LAG is a registered AWS Direct Connect partner, the LAG is automatically enabled to host sub-connections. For a LAG owned by a partner, any associated virtual interfaces cannot be directly
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 587 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLagResponse *>(send(request));
 }
createPrivateVirtualInterface
CreatePrivateVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::createPrivateVirtualInterface (const CreatePrivateVirtualInterfaceRequest & request) slot
Creates a new private virtual interface. A virtual interface is the VLAN that transports AWS Direct Connect traffic. A private virtual interface supports sending traffic to a single virtual private cloud
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 602 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePrivateVirtualInterfaceResponse *>(send(request));
 }
createPublicVirtualInterface
CreatePublicVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::createPublicVirtualInterface (const CreatePublicVirtualInterfaceRequest & request) slot
Creates a new public virtual interface. A virtual interface is the VLAN that transports AWS Direct Connect traffic. A public virtual interface supports sending traffic to public services of AWS such as Amazon Simple Storage Service (Amazon
S3)>
When creating an IPv6 public virtual interface (addressFamily is 'ipv6'), the customer and amazon address fields should be left blank to use auto-assigned IPv6 space. Custom IPv6 Addresses are currently not
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 623 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePublicVirtualInterfaceResponse *>(send(request));
 }
deleteBGPPeer
DeleteBGPPeerResponse * QtAws::DirectConnect::DirectConnectClient::deleteBGPPeer (const DeleteBGPPeerRequest & request) slot
Deletes a BGP peer on the specified virtual interface that matches the specified customer address and ASN. You cannot delete the last BGP peer from a virtual
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 638 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBGPPeerResponse *>(send(request));
 }
deleteConnection
DeleteConnectionResponse * QtAws::DirectConnect::DirectConnectClient::deleteConnection (const DeleteConnectionRequest & request) slot
Deletes the
connection>
Deleting a connection only stops the AWS Direct Connect port hour and data transfer charges. You need to cancel separately with the providers any services or charges for cross-connects or network circuits that connect you to the AWS Direct Connect
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 658 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConnectionResponse *>(send(request));
 }
deleteDirectConnectGateway
DeleteDirectConnectGatewayResponse * QtAws::DirectConnect::DirectConnectClient::deleteDirectConnectGateway (const DeleteDirectConnectGatewayRequest & request) slot
Deletes a direct connect gateway. You must first delete all virtual interfaces that are attached to the direct connect gateway and disassociate all virtual private gateways that are associated with the direct connect
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 673 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDirectConnectGatewayResponse *>(send(request));
 }
deleteDirectConnectGatewayAssociation
DeleteDirectConnectGatewayAssociationResponse * QtAws::DirectConnect::DirectConnectClient::deleteDirectConnectGatewayAssociation (const DeleteDirectConnectGatewayAssociationRequest & request) slot
Deletes the association between a direct connect gateway and a virtual private
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 687 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDirectConnectGatewayAssociationResponse *>(send(request));
 }
deleteInterconnect
DeleteInterconnectResponse * QtAws::DirectConnect::DirectConnectClient::deleteInterconnect (const DeleteInterconnectRequest & request) slot
Deletes the specified
interconnect> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 705 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInterconnectResponse *>(send(request));
 }
deleteLag
DeleteLagResponse * QtAws::DirectConnect::DirectConnectClient::deleteLag (const DeleteLagRequest & request) slot
Deletes a link aggregation group (LAG). You cannot delete a LAG if it has active virtual interfaces or hosted
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLagResponse *>(send(request));
 }
deleteVirtualInterface
DeleteVirtualInterfaceResponse * QtAws::DirectConnect::DirectConnectClient::deleteVirtualInterface (const DeleteVirtualInterfaceRequest & request) slot
Deletes a virtual
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 733 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVirtualInterfaceResponse *>(send(request));
 }
describeConnectionLoa
DescribeConnectionLoaResponse * QtAws::DirectConnect::DirectConnectClient::describeConnectionLoa (const DescribeConnectionLoaRequest & request) slot
Deprecated in favor of
DescribeLoa>
Returns the LOA-CFA for a
Connection>
The Letter of Authorization - Connecting Facility Assignment (LOA-CFA) is a document that your APN partner or service provider uses when establishing your cross connect to AWS at the colocation facility. For more information, see Requesting Cross Connects at AWS Direct Connect Locations in the AWS Direct Connect user
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 758 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConnectionLoaResponse *>(send(request));
 }
describeConnections
DescribeConnectionsResponse * QtAws::DirectConnect::DirectConnectClient::describeConnections (const DescribeConnectionsRequest & request) slot
Displays all connections in this
region>
If a connection ID is provided, the call returns only that particular
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 776 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConnectionsResponse *>(send(request));
 }
describeConnectionsOnInterconnect
DescribeConnectionsOnInterconnectResponse * QtAws::DirectConnect::DirectConnectClient::describeConnectionsOnInterconnect (const DescribeConnectionsOnInterconnectRequest & request) slot
Deprecated in favor of
DescribeHostedConnections>
Returns a list of connections that have been provisioned on the given
interconnect> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 798 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConnectionsOnInterconnectResponse *>(send(request));
 }
describeDirectConnectGatewayAssociations
DescribeDirectConnectGatewayAssociationsResponse * QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGatewayAssociations (const DescribeDirectConnectGatewayAssociationsRequest & request) slot
Returns a list of all direct connect gateway and virtual private gateway (VGW) associations. Either a direct connect gateway ID or a VGW ID must be provided in the request. If a direct connect gateway ID is provided, the response returns all VGWs associated with the direct connect gateway. If a VGW ID is provided, the response returns all direct connect gateways associated with the VGW. If both are provided, the response only returns the association that matches both the direct connect gateway and the
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 816 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDirectConnectGatewayAssociationsResponse *>(send(request));
 }
describeDirectConnectGatewayAttachments
DescribeDirectConnectGatewayAttachmentsResponse * QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGatewayAttachments (const DescribeDirectConnectGatewayAttachmentsRequest & request) slot
Returns a list of all direct connect gateway and virtual interface (VIF) attachments. Either a direct connect gateway ID or a VIF ID must be provided in the request. If a direct connect gateway ID is provided, the response returns all VIFs attached to the direct connect gateway. If a VIF ID is provided, the response returns all direct connect gateways attached to the VIF. If both are provided, the response only returns the attachment that matches both the direct connect gateway and the
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 834 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDirectConnectGatewayAttachmentsResponse *>(send(request));
 }
describeDirectConnectGateways
DescribeDirectConnectGatewaysResponse * QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGateways (const DescribeDirectConnectGatewaysRequest & request) slot
Returns a list of direct connect gateways in your account. Deleted direct connect gateways are not returned. You can provide a direct connect gateway ID in the request to return information about the specific direct connect gateway only. Otherwise, if a direct connect gateway ID is not provided, information about all of your direct connect gateways is returned.
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 851 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDirectConnectGatewaysResponse *>(send(request));
 }
describeHostedConnections
DescribeHostedConnectionsResponse * QtAws::DirectConnect::DirectConnectClient::describeHostedConnections (const DescribeHostedConnectionsRequest & request) slot
Returns a list of hosted connections that have been provisioned on the given interconnect or link aggregation group
(LAG)> <note>
This is intended for use by AWS Direct Connect partners
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 869 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHostedConnectionsResponse *>(send(request));
 }
describeInterconnectLoa
DescribeInterconnectLoaResponse * QtAws::DirectConnect::DirectConnectClient::describeInterconnectLoa (const DescribeInterconnectLoaRequest & request) slot
Deprecated in favor of
DescribeLoa>
Returns the LOA-CFA for an
Interconnect>
The Letter of Authorization - Connecting Facility Assignment (LOA-CFA) is a document that is used when establishing your cross connect to AWS at the colocation facility. For more information, see Requesting Cross Connects at AWS Direct Connect Locations in the AWS Direct Connect user
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 894 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInterconnectLoaResponse *>(send(request));
 }
describeInterconnects
DescribeInterconnectsResponse * QtAws::DirectConnect::DirectConnectClient::describeInterconnects (const DescribeInterconnectsRequest & request) slot
Returns a list of interconnects owned by the AWS
account>
If an interconnect ID is provided, it will only return this particular
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 912 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInterconnectsResponse *>(send(request));
 }
describeLags
DescribeLagsResponse * QtAws::DirectConnect::DirectConnectClient::describeLags (const DescribeLagsRequest & request) slot
Describes the link aggregation groups (LAGs) in your account.
</p
If a LAG ID is provided, only information about the specified LAG is
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 930 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLagsResponse *>(send(request));
 }
describeLoa
DescribeLoaResponse * QtAws::DirectConnect::DirectConnectClient::describeLoa (const DescribeLoaRequest & request) slot
Returns the LOA-CFA for a connection, interconnect, or link aggregation group
(LAG)>
The Letter of Authorization - Connecting Facility Assignment (LOA-CFA) is a document that is used when establishing your cross connect to AWS at the colocation facility. For more information, see Requesting Cross Connects at AWS Direct Connect Locations in the AWS Direct Connect user
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 951 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoaResponse *>(send(request));
 }
describeLocations
DescribeLocationsResponse * QtAws::DirectConnect::DirectConnectClient::describeLocations () slot
Returns the list of AWS Direct Connect locations in the current AWS region. These are the locations that may be selected when calling CreateConnection or
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 966 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLocationsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::DirectConnect::DirectConnectClient::describeTags (const DescribeTagsRequest & request) slot
Describes the tags associated with the specified Direct Connect
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 980 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
describeVirtualGateways
DescribeVirtualGatewaysResponse * QtAws::DirectConnect::DirectConnectClient::describeVirtualGateways () slot
Returns a list of virtual private gateways owned by the AWS
account>
You can create one or more AWS Direct Connect private virtual interfaces linking to a virtual private gateway. A virtual private gateway can be managed via Amazon Virtual Private Cloud (VPC) console or the EC2 CreateVpnGateway
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1001 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVirtualGatewaysResponse *>(send(request));
 }
describeVirtualInterfaces
DescribeVirtualInterfacesResponse * QtAws::DirectConnect::DirectConnectClient::describeVirtualInterfaces (const DescribeVirtualInterfacesRequest & request) slot
Displays all virtual interfaces for an AWS account. Virtual interfaces deleted fewer than 15 minutes before you make the request are also returned. If you specify a connection ID, only the virtual interfaces associated with the connection are returned. If you specify a virtual interface ID, then only a single virtual interface is
returned>
A virtual interface (VLAN) transmits the traffic between the AWS Direct Connect location and the
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1021 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVirtualInterfacesResponse *>(send(request));
 }
disassociateConnectionFromLag
DisassociateConnectionFromLagResponse * QtAws::DirectConnect::DirectConnectClient::disassociateConnectionFromLag (const DisassociateConnectionFromLagRequest & request) slot
Disassociates a connection from a link aggregation group (LAG). The connection is interrupted and re-established as a standalone connection (the connection is not deleted; to delete the connection, use the DeleteConnection request). If the LAG has associated virtual interfaces or hosted connections, they remain associated with the LAG. A disassociated connection owned by an AWS Direct Connect partner is automatically converted to an
interconnect>
If disassociating the connection will cause the LAG to fall below its setting for minimum number of operational connections, the request fails, except when it's the last member of the LAG. If all connections are disassociated, the LAG continues to exist as an empty LAG with no physical connections.
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1044 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateConnectionFromLagResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::DirectConnect::DirectConnectClient::tagResource (const TagResourceRequest & request) slot
Adds the specified tags to the specified Direct Connect resource. Each Direct Connect resource can have a maximum of 50
tags>
Each tag consists of a key and an optional value. If a tag with the same key is already associated with the Direct Connect resource, this action updates its
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1063 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::DirectConnect::DirectConnectClient::untagResource (const UntagResourceRequest & request) slot
Removes one or more tags from the specified Direct Connect
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1077 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateLag
UpdateLagResponse * QtAws::DirectConnect::DirectConnectClient::updateLag (const UpdateLagRequest & request) slot
Updates the attributes of a link aggregation group (LAG).
</p
You can update the following attributes:
</p
The name of the
LAG>
The value for the minimum number of connections that must be operational for the LAG itself to be operational.
</p
When you create a LAG, the default value for the minimum number of operational connections is zero (0). If you update this value, and the number of operational connections falls below the specified value, the LAG will automatically go down to avoid overutilization of the remaining connections. Adjusting this value should be done with care as it could force the LAG down if the value is set higher than the current number of operational
Parameters
request Request to send to AWS Direct Connect.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1110 of file directconnectclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateLagResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
directconnect/directconnectclient.h
directconnect/directconnectclient.cpp