AWS SDK for Qt: QtAws::SqsOld::SqsError Class Reference
QtAws::SqsOld::SqsError Class Reference
Encapsulation of an Error element from an SQS ErrorResponse response.
Public Types
enum ErrorCode {
AccessDenied, IncompleteSignature, InternalFailure, InvalidAction,
InvalidClientTokenId, InvalidParameterCombination, InvalidParameterValue, InvalidQueryParameter,
MalformedQueryString, MissingAction, MissingAuthenticationToken, MissingParameter,
OptInRequired, RequestExpired, ServiceUnavailable, Throttling,
ValidationError, OtherError = 0xFF
}
enum ErrorType { ReceiverType, SenderType, OtherType = 0xFF }
Public Member Functions
SqsError (QXmlStreamReader &xml)
Constructs a new SqsError object.
SqsError ()
Default constructor.
SqsError (const SqsError &other)
Copy constructor.
SqsError & operator= (const SqsError &other)
Assignment operator.
virtual ~SqsError ()
SqsError destructor.
ErrorCode code () const
Get the parsed SQS error code.
QVariantMap detail () const
Get the SQS error detail, if any.
QString message () const
Get the parsed SQS error message.
QString rawCode () const
Get the raw SQS error code string.
QString rawType () const
Get the raw SQS error type string.
ErrorType type () const
Get the parsed SQS error type.
bool operator== (const SqsError &other) const
Equality operator.
Protected Member Functions
SqsError (SqsErrorPrivate *const d)
Constructs a new SqsError object.
Protected Attributes
SqsErrorPrivate *const d_ptr
Internal d-pointer.
Friends
class TestSqsError
Detailed Description
Encapsulation of an Error element from an SQS ErrorResponse response.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 36 of file sqserror.h.
Member Enumeration Documentation
ErrorCode
enum QtAws::SqsOld::SqsError::ErrorCode
SQS error codes.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 41 of file sqserror.h.
                    {
         AccessDenied,
         IncompleteSignature,
         InternalFailure,
         InvalidAction,
         InvalidClientTokenId,
         InvalidParameterCombination,
         InvalidParameterValue,
         InvalidQueryParameter,
         MalformedQueryString,
         MissingAction,
         MissingAuthenticationToken,
         MissingParameter,
         OptInRequired,
         RequestExpired,
         ServiceUnavailable,
         Throttling,
         ValidationError,
         OtherError = 0xFF
     };
ErrorType
enum QtAws::SqsOld::SqsError::ErrorType
SQS error types.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 64 of file sqserror.h.
                    {
         ReceiverType,
         SenderType,
         OtherType = 0xFF
     };
Constructor & Destructor Documentation
SqsError() [1/4]
QtAws::SqsOld::SqsError::SqsError (QXmlStreamReader & xml)
Constructs a new SqsError object.
Parameters
xml XML stream to parse an SQS ErrorResponse from.
Definition at line 44 of file sqserror.cpp.
                                         : d_ptr(new SqsErrorPrivate(this))
 {
     Q_D(SqsError);
     d->parse(xml);
 }
SqsError() [2/4]
QtAws::SqsOld::SqsError::SqsError ()
Default constructor.
Constructs an invalid SqsError object, useful only for assignment via the assignemnt operator defined below.
Note
This function exists solely for compatability with Qt's container classes, such as QList, which require "assignable data types" - ie ones that "provide a default constructor, a copy constructor, and an assignment operator".
See also
http://doc.qt.io/qt-5/containers.html
Definition at line 65 of file sqserror.cpp.
                    : d_ptr(new SqsErrorPrivate(this))
 {
 }
SqsError() [3/4]
QtAws::SqsOld::SqsError::SqsError (const SqsError & other)
Copy constructor.
Constructs an SqsError object by copying other.
Note
This function exists solely for compatability with Qt's container classes, such as QList, which require "assignable data types" - ie ones that "provide a default constructor, a copy constructor, and an assignment operator".
Parameters
other Instance to copy.
See also
http://doc.qt.io/qt-5/containers.html
Definition at line 101 of file sqserror.cpp.
     : d_ptr(new SqsErrorPrivate(other.d_func(), this))
 {
 }
SqsError() [4/4]
QtAws::SqsOld::SqsError::SqsError (SqsErrorPrivate *const d) protected
Constructs a new SqsError object.
This overload allows derived classes to provide their own private class implementation that inherits from SqsErrorPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 80 of file sqserror.cpp.
                                             : d_ptr(d)
 {
 }
Member Function Documentation
code()
SqsError::ErrorCode QtAws::SqsOld::SqsError::code () const
Get the parsed SQS error code.
Returns
An SQS error code, or SqsError::OtherError if not found or not recognised.
See also
rawCode
Definition at line 152 of file sqserror.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsError);
     return d->code;
 }
detail()
QVariantMap QtAws::SqsOld::SqsError::detail () const
Get the SQS error detail, if any.
Returns
SQS error detail, or an empty QVariantMap if not found.
Definition at line 163 of file sqserror.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsError);
     return d->detail;
 }
message()
QString QtAws::SqsOld::SqsError::message () const
Get the parsed SQS error message.
Returns
SQS error message, or a null QString if not found.
Definition at line 174 of file sqserror.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsError);
     return d->message;
 }
operator=()
SqsError & QtAws::SqsOld::SqsError::operator= (const SqsError & other)
Assignment operator.
Assigns other to this.
Note
This function exists solely for compatability with Qt's container classes, such as QList, which require "assignable data types" - ie ones that "provide a default constructor, a copy constructor, and an assignment operator".
Parameters
other Instance to copy.
Returns
A reference to this object.
See also
http://doc.qt.io/qt-5/containers.html
Definition at line 125 of file sqserror.cpp.
References code(), detail(), message(), rawCode(), rawType(), and type().
 {
     Q_D(SqsError);
     d->code = other.code();
     d->detail = other.detail();
     d->message = other.message();
     d->rawCode = other.rawCode();
     d->rawType = other.rawType();
     d->type = other.type();
     return *this;
 }
operator==()
bool QtAws::SqsOld::SqsError::operator== (const SqsError & other) const
Equality operator.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal
Definition at line 234 of file sqserror.cpp.
References code(), detail(), message(), and type().
 {
     return ((code() == other.code()) &&
             (detail() == other.detail()) &&
             (message() == other.message()) &&
             (type() == other.type()));
 }
rawCode()
QString QtAws::SqsOld::SqsError::rawCode () const
Get the raw SQS error code string.
That may be useful if code returned SqsError::OtherError due to the error code being found, but not recognisable (ie not one of the values specified by the SQS service WSDL).
Returns
The raw SQS error code string, or a null QString is not found.
See also
code
Definition at line 191 of file sqserror.cpp.
Referenced by operator=().
 {
     Q_D(const SqsError);
     return d->rawCode;
 }
rawType()
QString QtAws::SqsOld::SqsError::rawType () const
Get the raw SQS error type string.
That may be useful if type returned SqsError::OtherType due to the error type being found, but not recognisable (ie not one of the values specified by the SQS service WSDL).
Returns
The raw SQS error tyep string, or a null QString is not found.
See also
type
Definition at line 208 of file sqserror.cpp.
Referenced by operator=().
 {
     Q_D(const SqsError);
     return d->rawType;
 }
type()
SqsError::ErrorType QtAws::SqsOld::SqsError::type () const
Get the parsed SQS error type.
Returns
An SQS error type, or SqsError::OtherType if not found or not recognised.
See also
rawType
Definition at line 221 of file sqserror.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsError);
     return d->type;
 }
The documentation for this class was generated from the following files:
sqs-old/sqserror.h
sqs-old/sqserror.cpp