AWS SDK for Qt: QtAws::Pinpoint::PinpointClient Class Reference
QtAws::Pinpoint::PinpointClient Class Reference
Client for Amazon Pinpoint.
Public Slots
CreateAppResponse * createApp (const CreateAppRequest &request)
CreateCampaignResponse * createCampaign (const CreateCampaignRequest &request)
CreateExportJobResponse * createExportJob (const CreateExportJobRequest &request)
CreateImportJobResponse * createImportJob (const CreateImportJobRequest &request)
CreateSegmentResponse * createSegment (const CreateSegmentRequest &request)
DeleteAdmChannelResponse * deleteAdmChannel (const DeleteAdmChannelRequest &request)
DeleteApnsChannelResponse * deleteApnsChannel (const DeleteApnsChannelRequest &request)
DeleteApnsSandboxChannelResponse * deleteApnsSandboxChannel (const DeleteApnsSandboxChannelRequest &request)
DeleteApnsVoipChannelResponse * deleteApnsVoipChannel (const DeleteApnsVoipChannelRequest &request)
DeleteApnsVoipSandboxChannelResponse * deleteApnsVoipSandboxChannel (const DeleteApnsVoipSandboxChannelRequest &request)
DeleteAppResponse * deleteApp (const DeleteAppRequest &request)
DeleteBaiduChannelResponse * deleteBaiduChannel (const DeleteBaiduChannelRequest &request)
DeleteCampaignResponse * deleteCampaign (const DeleteCampaignRequest &request)
DeleteEmailChannelResponse * deleteEmailChannel (const DeleteEmailChannelRequest &request)
DeleteEndpointResponse * deleteEndpoint (const DeleteEndpointRequest &request)
DeleteEventStreamResponse * deleteEventStream (const DeleteEventStreamRequest &request)
DeleteGcmChannelResponse * deleteGcmChannel (const DeleteGcmChannelRequest &request)
DeleteSegmentResponse * deleteSegment (const DeleteSegmentRequest &request)
DeleteSmsChannelResponse * deleteSmsChannel (const DeleteSmsChannelRequest &request)
GetAdmChannelResponse * getAdmChannel (const GetAdmChannelRequest &request)
GetApnsChannelResponse * getApnsChannel (const GetApnsChannelRequest &request)
GetApnsSandboxChannelResponse * getApnsSandboxChannel (const GetApnsSandboxChannelRequest &request)
GetApnsVoipChannelResponse * getApnsVoipChannel (const GetApnsVoipChannelRequest &request)
GetApnsVoipSandboxChannelResponse * getApnsVoipSandboxChannel (const GetApnsVoipSandboxChannelRequest &request)
GetAppResponse * getApp (const GetAppRequest &request)
GetApplicationSettingsResponse * getApplicationSettings (const GetApplicationSettingsRequest &request)
GetAppsResponse * getApps (const GetAppsRequest &request)
GetBaiduChannelResponse * getBaiduChannel (const GetBaiduChannelRequest &request)
GetCampaignResponse * getCampaign (const GetCampaignRequest &request)
GetCampaignActivitiesResponse * getCampaignActivities (const GetCampaignActivitiesRequest &request)
GetCampaignVersionResponse * getCampaignVersion (const GetCampaignVersionRequest &request)
GetCampaignVersionsResponse * getCampaignVersions (const GetCampaignVersionsRequest &request)
GetCampaignsResponse * getCampaigns (const GetCampaignsRequest &request)
GetEmailChannelResponse * getEmailChannel (const GetEmailChannelRequest &request)
GetEndpointResponse * getEndpoint (const GetEndpointRequest &request)
GetEventStreamResponse * getEventStream (const GetEventStreamRequest &request)
GetExportJobResponse * getExportJob (const GetExportJobRequest &request)
GetExportJobsResponse * getExportJobs (const GetExportJobsRequest &request)
GetGcmChannelResponse * getGcmChannel (const GetGcmChannelRequest &request)
GetImportJobResponse * getImportJob (const GetImportJobRequest &request)
GetImportJobsResponse * getImportJobs (const GetImportJobsRequest &request)
GetSegmentResponse * getSegment (const GetSegmentRequest &request)
GetSegmentExportJobsResponse * getSegmentExportJobs (const GetSegmentExportJobsRequest &request)
GetSegmentImportJobsResponse * getSegmentImportJobs (const GetSegmentImportJobsRequest &request)
GetSegmentVersionResponse * getSegmentVersion (const GetSegmentVersionRequest &request)
GetSegmentVersionsResponse * getSegmentVersions (const GetSegmentVersionsRequest &request)
GetSegmentsResponse * getSegments (const GetSegmentsRequest &request)
GetSmsChannelResponse * getSmsChannel (const GetSmsChannelRequest &request)
PutEventStreamResponse * putEventStream (const PutEventStreamRequest &request)
SendMessagesResponse * sendMessages (const SendMessagesRequest &request)
SendUsersMessagesResponse * sendUsersMessages (const SendUsersMessagesRequest &request)
UpdateAdmChannelResponse * updateAdmChannel (const UpdateAdmChannelRequest &request)
UpdateApnsChannelResponse * updateApnsChannel (const UpdateApnsChannelRequest &request)
UpdateApnsSandboxChannelResponse * updateApnsSandboxChannel (const UpdateApnsSandboxChannelRequest &request)
UpdateApnsVoipChannelResponse * updateApnsVoipChannel (const UpdateApnsVoipChannelRequest &request)
UpdateApnsVoipSandboxChannelResponse * updateApnsVoipSandboxChannel (const UpdateApnsVoipSandboxChannelRequest &request)
UpdateApplicationSettingsResponse * updateApplicationSettings (const UpdateApplicationSettingsRequest &request)
UpdateBaiduChannelResponse * updateBaiduChannel (const UpdateBaiduChannelRequest &request)
UpdateCampaignResponse * updateCampaign (const UpdateCampaignRequest &request)
UpdateEmailChannelResponse * updateEmailChannel (const UpdateEmailChannelRequest &request)
UpdateEndpointResponse * updateEndpoint (const UpdateEndpointRequest &request)
UpdateEndpointsBatchResponse * updateEndpointsBatch (const UpdateEndpointsBatchRequest &request)
UpdateGcmChannelResponse * updateGcmChannel (const UpdateGcmChannelRequest &request)
UpdateSegmentResponse * updateSegment (const UpdateSegmentRequest &request)
UpdateSmsChannelResponse * updateSmsChannel (const UpdateSmsChannelRequest &request)
Public Member Functions
PinpointClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PinpointClient object.
PinpointClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PinpointClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Pinpoint.
Definition at line 162 of file pinpointclient.h.
Constructor & Destructor Documentation
PinpointClient() [1/2]
QtAws::Pinpoint::PinpointClient::PinpointClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PinpointClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 176 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new PinpointClientPrivate(this), parent)
 {
     Q_D(PinpointClient);
     d->apiVersion = QStringLiteral("2016-12-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("pinpoint");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Pinpoint");
     d->serviceName = QStringLiteral("mobiletargeting");
 }
PinpointClient() [2/2]
QtAws::Pinpoint::PinpointClient::PinpointClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PinpointClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 209 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new PinpointClientPrivate(this), parent)
 {
     Q_D(PinpointClient);
     d->apiVersion = QStringLiteral("2016-12-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("pinpoint");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Pinpoint");
     d->serviceName = QStringLiteral("mobiletargeting");
 }
Member Function Documentation
createApp
CreateAppResponse * QtAws::Pinpoint::PinpointClient::createApp (const CreateAppRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 234 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAppResponse *>(send(request));
 }
createCampaign
CreateCampaignResponse * QtAws::Pinpoint::PinpointClient::createCampaign (const CreateCampaignRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 247 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCampaignResponse *>(send(request));
 }
createExportJob
CreateExportJobResponse * QtAws::Pinpoint::PinpointClient::createExportJob (const CreateExportJobRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 260 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateExportJobResponse *>(send(request));
 }
createImportJob
CreateImportJobResponse * QtAws::Pinpoint::PinpointClient::createImportJob (const CreateImportJobRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateImportJobResponse *>(send(request));
 }
createSegment
CreateSegmentResponse * QtAws::Pinpoint::PinpointClient::createSegment (const CreateSegmentRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 286 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSegmentResponse *>(send(request));
 }
deleteAdmChannel
DeleteAdmChannelResponse * QtAws::Pinpoint::PinpointClient::deleteAdmChannel (const DeleteAdmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 299 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAdmChannelResponse *>(send(request));
 }
deleteApnsChannel
DeleteApnsChannelResponse * QtAws::Pinpoint::PinpointClient::deleteApnsChannel (const DeleteApnsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 312 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApnsChannelResponse *>(send(request));
 }
deleteApnsSandboxChannel
DeleteApnsSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::deleteApnsSandboxChannel (const DeleteApnsSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 325 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApnsSandboxChannelResponse *>(send(request));
 }
deleteApnsVoipChannel
DeleteApnsVoipChannelResponse * QtAws::Pinpoint::PinpointClient::deleteApnsVoipChannel (const DeleteApnsVoipChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 338 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApnsVoipChannelResponse *>(send(request));
 }
deleteApnsVoipSandboxChannel
DeleteApnsVoipSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::deleteApnsVoipSandboxChannel (const DeleteApnsVoipSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApnsVoipSandboxChannelResponse *>(send(request));
 }
deleteApp
DeleteAppResponse * QtAws::Pinpoint::PinpointClient::deleteApp (const DeleteAppRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 364 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAppResponse *>(send(request));
 }
deleteBaiduChannel
DeleteBaiduChannelResponse * QtAws::Pinpoint::PinpointClient::deleteBaiduChannel (const DeleteBaiduChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBaiduChannelResponse *>(send(request));
 }
deleteCampaign
DeleteCampaignResponse * QtAws::Pinpoint::PinpointClient::deleteCampaign (const DeleteCampaignRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 390 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCampaignResponse *>(send(request));
 }
deleteEmailChannel
DeleteEmailChannelResponse * QtAws::Pinpoint::PinpointClient::deleteEmailChannel (const DeleteEmailChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 403 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEmailChannelResponse *>(send(request));
 }
deleteEndpoint
DeleteEndpointResponse * QtAws::Pinpoint::PinpointClient::deleteEndpoint (const DeleteEndpointRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 416 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEndpointResponse *>(send(request));
 }
deleteEventStream
DeleteEventStreamResponse * QtAws::Pinpoint::PinpointClient::deleteEventStream (const DeleteEventStreamRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 429 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEventStreamResponse *>(send(request));
 }
deleteGcmChannel
DeleteGcmChannelResponse * QtAws::Pinpoint::PinpointClient::deleteGcmChannel (const DeleteGcmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 442 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGcmChannelResponse *>(send(request));
 }
deleteSegment
DeleteSegmentResponse * QtAws::Pinpoint::PinpointClient::deleteSegment (const DeleteSegmentRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 455 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSegmentResponse *>(send(request));
 }
deleteSmsChannel
DeleteSmsChannelResponse * QtAws::Pinpoint::PinpointClient::deleteSmsChannel (const DeleteSmsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 468 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSmsChannelResponse *>(send(request));
 }
getAdmChannel
GetAdmChannelResponse * QtAws::Pinpoint::PinpointClient::getAdmChannel (const GetAdmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 481 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAdmChannelResponse *>(send(request));
 }
getApnsChannel
GetApnsChannelResponse * QtAws::Pinpoint::PinpointClient::getApnsChannel (const GetApnsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 494 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApnsChannelResponse *>(send(request));
 }
getApnsSandboxChannel
GetApnsSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::getApnsSandboxChannel (const GetApnsSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 507 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApnsSandboxChannelResponse *>(send(request));
 }
getApnsVoipChannel
GetApnsVoipChannelResponse * QtAws::Pinpoint::PinpointClient::getApnsVoipChannel (const GetApnsVoipChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 520 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApnsVoipChannelResponse *>(send(request));
 }
getApnsVoipSandboxChannel
GetApnsVoipSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::getApnsVoipSandboxChannel (const GetApnsVoipSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 533 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApnsVoipSandboxChannelResponse *>(send(request));
 }
getApp
GetAppResponse * QtAws::Pinpoint::PinpointClient::getApp (const GetAppRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 546 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAppResponse *>(send(request));
 }
getApplicationSettings
GetApplicationSettingsResponse * QtAws::Pinpoint::PinpointClient::getApplicationSettings (const GetApplicationSettingsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApplicationSettingsResponse *>(send(request));
 }
getApps
GetAppsResponse * QtAws::Pinpoint::PinpointClient::getApps (const GetAppsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 572 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAppsResponse *>(send(request));
 }
getBaiduChannel
GetBaiduChannelResponse * QtAws::Pinpoint::PinpointClient::getBaiduChannel (const GetBaiduChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 585 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBaiduChannelResponse *>(send(request));
 }
getCampaign
GetCampaignResponse * QtAws::Pinpoint::PinpointClient::getCampaign (const GetCampaignRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 598 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCampaignResponse *>(send(request));
 }
getCampaignActivities
GetCampaignActivitiesResponse * QtAws::Pinpoint::PinpointClient::getCampaignActivities (const GetCampaignActivitiesRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 611 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCampaignActivitiesResponse *>(send(request));
 }
getCampaigns
GetCampaignsResponse * QtAws::Pinpoint::PinpointClient::getCampaigns (const GetCampaignsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 650 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCampaignsResponse *>(send(request));
 }
getCampaignVersion
GetCampaignVersionResponse * QtAws::Pinpoint::PinpointClient::getCampaignVersion (const GetCampaignVersionRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 624 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCampaignVersionResponse *>(send(request));
 }
getCampaignVersions
GetCampaignVersionsResponse * QtAws::Pinpoint::PinpointClient::getCampaignVersions (const GetCampaignVersionsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 637 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCampaignVersionsResponse *>(send(request));
 }
getEmailChannel
GetEmailChannelResponse * QtAws::Pinpoint::PinpointClient::getEmailChannel (const GetEmailChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 663 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEmailChannelResponse *>(send(request));
 }
getEndpoint
GetEndpointResponse * QtAws::Pinpoint::PinpointClient::getEndpoint (const GetEndpointRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 676 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEndpointResponse *>(send(request));
 }
getEventStream
GetEventStreamResponse * QtAws::Pinpoint::PinpointClient::getEventStream (const GetEventStreamRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 689 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEventStreamResponse *>(send(request));
 }
getExportJob
GetExportJobResponse * QtAws::Pinpoint::PinpointClient::getExportJob (const GetExportJobRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 702 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetExportJobResponse *>(send(request));
 }
getExportJobs
GetExportJobsResponse * QtAws::Pinpoint::PinpointClient::getExportJobs (const GetExportJobsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 715 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetExportJobsResponse *>(send(request));
 }
getGcmChannel
GetGcmChannelResponse * QtAws::Pinpoint::PinpointClient::getGcmChannel (const GetGcmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 728 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGcmChannelResponse *>(send(request));
 }
getImportJob
GetImportJobResponse * QtAws::Pinpoint::PinpointClient::getImportJob (const GetImportJobRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 741 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetImportJobResponse *>(send(request));
 }
getImportJobs
GetImportJobsResponse * QtAws::Pinpoint::PinpointClient::getImportJobs (const GetImportJobsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 754 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetImportJobsResponse *>(send(request));
 }
getSegment
GetSegmentResponse * QtAws::Pinpoint::PinpointClient::getSegment (const GetSegmentRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 767 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentResponse *>(send(request));
 }
getSegmentExportJobs
GetSegmentExportJobsResponse * QtAws::Pinpoint::PinpointClient::getSegmentExportJobs (const GetSegmentExportJobsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 780 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentExportJobsResponse *>(send(request));
 }
getSegmentImportJobs
GetSegmentImportJobsResponse * QtAws::Pinpoint::PinpointClient::getSegmentImportJobs (const GetSegmentImportJobsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 793 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentImportJobsResponse *>(send(request));
 }
getSegments
GetSegmentsResponse * QtAws::Pinpoint::PinpointClient::getSegments (const GetSegmentsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 832 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentsResponse *>(send(request));
 }
getSegmentVersion
GetSegmentVersionResponse * QtAws::Pinpoint::PinpointClient::getSegmentVersion (const GetSegmentVersionRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 806 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentVersionResponse *>(send(request));
 }
getSegmentVersions
GetSegmentVersionsResponse * QtAws::Pinpoint::PinpointClient::getSegmentVersions (const GetSegmentVersionsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 819 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSegmentVersionsResponse *>(send(request));
 }
getSmsChannel
GetSmsChannelResponse * QtAws::Pinpoint::PinpointClient::getSmsChannel (const GetSmsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 845 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSmsChannelResponse *>(send(request));
 }
putEventStream
PutEventStreamResponse * QtAws::Pinpoint::PinpointClient::putEventStream (const PutEventStreamRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 858 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutEventStreamResponse *>(send(request));
 }
sendMessages
SendMessagesResponse * QtAws::Pinpoint::PinpointClient::sendMessages (const SendMessagesRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 871 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendMessagesResponse *>(send(request));
 }
sendUsersMessages
SendUsersMessagesResponse * QtAws::Pinpoint::PinpointClient::sendUsersMessages (const SendUsersMessagesRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 884 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendUsersMessagesResponse *>(send(request));
 }
updateAdmChannel
UpdateAdmChannelResponse * QtAws::Pinpoint::PinpointClient::updateAdmChannel (const UpdateAdmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 897 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAdmChannelResponse *>(send(request));
 }
updateApnsChannel
UpdateApnsChannelResponse * QtAws::Pinpoint::PinpointClient::updateApnsChannel (const UpdateApnsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 910 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApnsChannelResponse *>(send(request));
 }
updateApnsSandboxChannel
UpdateApnsSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::updateApnsSandboxChannel (const UpdateApnsSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 923 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApnsSandboxChannelResponse *>(send(request));
 }
updateApnsVoipChannel
UpdateApnsVoipChannelResponse * QtAws::Pinpoint::PinpointClient::updateApnsVoipChannel (const UpdateApnsVoipChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 936 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApnsVoipChannelResponse *>(send(request));
 }
updateApnsVoipSandboxChannel
UpdateApnsVoipSandboxChannelResponse * QtAws::Pinpoint::PinpointClient::updateApnsVoipSandboxChannel (const UpdateApnsVoipSandboxChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 949 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApnsVoipSandboxChannelResponse *>(send(request));
 }
updateApplicationSettings
UpdateApplicationSettingsResponse * QtAws::Pinpoint::PinpointClient::updateApplicationSettings (const UpdateApplicationSettingsRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 962 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApplicationSettingsResponse *>(send(request));
 }
updateBaiduChannel
UpdateBaiduChannelResponse * QtAws::Pinpoint::PinpointClient::updateBaiduChannel (const UpdateBaiduChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 975 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBaiduChannelResponse *>(send(request));
 }
updateCampaign
UpdateCampaignResponse * QtAws::Pinpoint::PinpointClient::updateCampaign (const UpdateCampaignRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 988 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCampaignResponse *>(send(request));
 }
updateEmailChannel
UpdateEmailChannelResponse * QtAws::Pinpoint::PinpointClient::updateEmailChannel (const UpdateEmailChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1001 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateEmailChannelResponse *>(send(request));
 }
updateEndpoint
UpdateEndpointResponse * QtAws::Pinpoint::PinpointClient::updateEndpoint (const UpdateEndpointRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1014 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateEndpointResponse *>(send(request));
 }
updateEndpointsBatch
UpdateEndpointsBatchResponse * QtAws::Pinpoint::PinpointClient::updateEndpointsBatch (const UpdateEndpointsBatchRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1027 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateEndpointsBatchResponse *>(send(request));
 }
updateGcmChannel
UpdateGcmChannelResponse * QtAws::Pinpoint::PinpointClient::updateGcmChannel (const UpdateGcmChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1040 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGcmChannelResponse *>(send(request));
 }
updateSegment
UpdateSegmentResponse * QtAws::Pinpoint::PinpointClient::updateSegment (const UpdateSegmentRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1053 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSegmentResponse *>(send(request));
 }
updateSmsChannel
UpdateSmsChannelResponse * QtAws::Pinpoint::PinpointClient::updateSmsChannel (const UpdateSmsChannelRequest & request) slot
Parameters
request Request to send to Amazon Pinpoint.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1066 of file pinpointclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSmsChannelResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
pinpoint/pinpointclient.h
pinpoint/pinpointclient.cpp