AWS SDK for Qt: QtAws::SQS::SqsClient Class Reference
QtAws::SQS::SqsClient Class Reference
Client for Amazon Simple Queue Service (SQS)
Public Slots
AddPermissionResponse * addPermission (const AddPermissionRequest &request)
ChangeMessageVisibilityResponse * changeMessageVisibility (const ChangeMessageVisibilityRequest &request)
ChangeMessageVisibilityBatchResponse * changeMessageVisibilityBatch (const ChangeMessageVisibilityBatchRequest &request)
CreateQueueResponse * createQueue (const CreateQueueRequest &request)
DeleteMessageResponse * deleteMessage (const DeleteMessageRequest &request)
DeleteMessageBatchResponse * deleteMessageBatch (const DeleteMessageBatchRequest &request)
DeleteQueueResponse * deleteQueue (const DeleteQueueRequest &request)
GetQueueAttributesResponse * getQueueAttributes (const GetQueueAttributesRequest &request)
GetQueueUrlResponse * getQueueUrl (const GetQueueUrlRequest &request)
ListDeadLetterSourceQueuesResponse * listDeadLetterSourceQueues (const ListDeadLetterSourceQueuesRequest &request)
ListQueueTagsResponse * listQueueTags (const ListQueueTagsRequest &request)
ListQueuesResponse * listQueues (const ListQueuesRequest &request)
PurgeQueueResponse * purgeQueue (const PurgeQueueRequest &request)
ReceiveMessageResponse * receiveMessage (const ReceiveMessageRequest &request)
RemovePermissionResponse * removePermission (const RemovePermissionRequest &request)
SendMessageResponse * sendMessage (const SendMessageRequest &request)
SendMessageBatchResponse * sendMessageBatch (const SendMessageBatchRequest &request)
SetQueueAttributesResponse * setQueueAttributes (const SetQueueAttributesRequest &request)
TagQueueResponse * tagQueue (const TagQueueRequest &request)
UntagQueueResponse * untagQueue (const UntagQueueRequest &request)
Public Member Functions
SqsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
SqsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Queue Service (SQS)
Welcome to the Amazon Simple Queue Service API
Reference>
Amazon Simple Queue Service (Amazon SQS) is a reliable, highly-scalable hosted queue for storing messages as they travel between applications or microservices. Amazon SQS moves data between distributed application components and helps you decouple these
components> <note>
Standard queues are available in all regions. FIFO queues are available in the US East (N. Virginia), US East (Ohio), US West (Oregon), and EU (Ireland)
regions> </note>
You can use AWS SDKs to access Amazon SQS using your favorite programming language. The SDKs perform tasks such as the following
automatically>
Cryptographically sign your service
request>
Retry
request>
Handle error
response>
Additional Information
</p
Amazon SQS Product Page
</p
Amazon Simple Queue Service Developer Guide
</p
Making API Requests
</p
Using Amazon SQS Message Attributes
</p
Using Amazon SQS Dead-Letter Queues
</p
Amazon Web Services General Reference
</p
Regions and Endpoints
Definition at line 72 of file sqsclient.h.
Constructor & Destructor Documentation
SqsClient() [1/2]
QtAws::SQS::SqsClient::SqsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 152 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->apiVersion = QStringLiteral("2012-11-05");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("sqs");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Simple Queue Service");
     d->serviceName = QStringLiteral("sqs");
 }
SqsClient() [2/2]
QtAws::SQS::SqsClient::SqsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 185 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->apiVersion = QStringLiteral("2012-11-05");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("sqs");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Simple Queue Service");
     d->serviceName = QStringLiteral("sqs");
 }
Member Function Documentation
addPermission
AddPermissionResponse * QtAws::SQS::SqsClient::addPermission (const AddPermissionRequest & request) slot
Adds a permission to a queue for a specific principal. This allows sharing access to the
queue>
When you create a queue, you have full control access rights for the queue. Only you, the owner of the queue, can grant or deny permissions to the queue. For more information about these permissions, see Shared Queues in the Amazon Simple Queue Service Developer
Guide> <note>
AddPermission writes an Amazon-SQS-generated policy. If you want to write your own policy, use SetQueueAttributes to upload your policy. For more information about writing your own policy, see Using The Access Policy Language in the Amazon Simple Queue Service Developer
Guide>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 239 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddPermissionResponse *>(send(request));
 }
changeMessageVisibility
ChangeMessageVisibilityResponse * QtAws::SQS::SqsClient::changeMessageVisibility (const ChangeMessageVisibilityRequest & request) slot
Changes the visibility timeout of a specified message in a queue to a new value. The maximum allowed timeout value is 12 hours. Thus, you can't extend the timeout of a message in an existing queue to more than a total visibility timeout of 12 hours. For more information, see Visibility Timeout in the Amazon Simple Queue Service Developer
Guide>
For example, you have a message with a visibility timeout of 5 minutes. After 3 minutes, you call ChangeMessageVisiblity with a timeout of 10 minutes. At that time, the timeout for the message is extended by 10 minutes beyond the time of the ChangeMessageVisibility action. This results in a total visibility timeout of 13 minutes. You can continue to call the ChangeMessageVisibility to extend the visibility timeout to a maximum of 12 hours. If you try to extend the visibility timeout beyond 12 hours, your request is
rejected>
A message is considered to be in flight after it's received from a queue by a consumer, but not yet deleted from the
queue>
For standard queues, there can be a maximum of 120,000 inflight messages per queue. If you reach this limit, Amazon SQS returns the OverLimit error message. To avoid reaching the limit, you should delete messages from the queue after they're processed. You can also increase the number of queues you use to process your
messages>
For FIFO queues, there can be a maximum of 20,000 inflight messages per queue. If you reach this limit, Amazon SQS returns no error
messages>
If you attempt to set the VisibilityTimeout to a value greater than the maximum time left, Amazon SQS returns an error. Amazon SQS doesn't automatically recalculate and increase the timeout to the maximum remaining
time>
Unlike with a queue, when you change the visibility timeout for a specific message the timeout value is applied immediately but isn't saved in memory for that message. If you don't delete a message after it is received, the visibility timeout for the message reverts to the original timeout value (not to the value you set using the ChangeMessageVisibility action) the next time the message is
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 293 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangeMessageVisibilityResponse *>(send(request));
 }
changeMessageVisibilityBatch
ChangeMessageVisibilityBatchResponse * QtAws::SQS::SqsClient::changeMessageVisibilityBatch (const ChangeMessageVisibilityBatchRequest & request) slot
Changes the visibility timeout of multiple messages. This is a batch version of ChangeMessageVisibility. The result of the action on each message is reported individually in the response. You can send up to 10 ChangeMessageVisibility requests with each ChangeMessageVisibilityBatch
action>
Because the batch request can result in a combination of successful and unsuccessful actions, you should check for batch errors even when the call returns an HTTP status code of
200> <note>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 328 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangeMessageVisibilityBatchResponse *>(send(request));
 }
createQueue
CreateQueueResponse * QtAws::SQS::SqsClient::createQueue (const CreateQueueRequest & request) slot
Creates a new standard or FIFO queue. You can pass one or more attributes in the request. Keep the following caveats in
mind>
If you don't specify the FifoQueue attribute, Amazon SQS creates a standard
queue> <note>
You can't change the queue type after you create it and you can't convert an existing standard queue into a FIFO queue. You must either create a new FIFO queue for your application or delete your existing standard queue and recreate it as a FIFO queue. For more information, see Moving From a Standard Queue to a FIFO Queue in the Amazon Simple Queue Service Developer Guide.
</p </note>
If you don't provide a value for an attribute, the queue is created with the default value for the
attribute>
If you delete a queue, you must wait at least 60 seconds before creating a queue with the same
name>
To successfully create a new queue, you must provide a queue name that adheres to the limits related to queues and is unique within the scope of your
queues>
To get the queue URL, use the GetQueueUrl action. GetQueueUrl requires only the QueueName parameter. be aware of existing queue
names>
If you provide the name of an existing queue along with the exact names and values of all the queue's attributes, CreateQueue returns the queue URL for the existing
queue>
If the queue name, attribute names, or attribute values don't match an existing queue, CreateQueue returns an
error>
<note>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 396 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateQueueResponse *>(send(request));
 }
deleteMessage
DeleteMessageResponse * QtAws::SQS::SqsClient::deleteMessage (const DeleteMessageRequest & request) slot
Deletes the specified message from the specified queue. You specify the message by using the message's receipt handle and not the MessageId you receive when you send the message. Even if the message is locked by another reader due to the visibility timeout setting, it is still deleted from the queue. If you leave a message in the queue for longer than the queue's configured retention period, Amazon SQS automatically deletes the message.
</p <note>
The receipt handle is associated with a specific instance of receiving the message. If you receive a message more than once, the receipt handle you get each time you receive the message is different. If you don't provide the most recently received receipt handle for the message when you use the DeleteMessage action, the request succeeds, but the message might not be
deleted>
For standard queues, it is possible to receive a message even after you delete it. This might happen on rare occasions if one of the servers storing a copy of the message is unavailable when you send the request to delete the message. The copy remains on the server and might be returned to you on a subsequent receive request. You should ensure that your application is idempotent, so that receiving a message more than once does not cause
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 427 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMessageResponse *>(send(request));
 }
deleteMessageBatch
DeleteMessageBatchResponse * QtAws::SQS::SqsClient::deleteMessageBatch (const DeleteMessageBatchRequest & request) slot
Deletes up to ten messages from the specified queue. This is a batch version of DeleteMessage. The result of the action on each message is reported individually in the
response>
Because the batch request can result in a combination of successful and unsuccessful actions, you should check for batch errors even when the call returns an HTTP status code of
200> <note>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 460 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMessageBatchResponse *>(send(request));
 }
deleteQueue
DeleteQueueResponse * QtAws::SQS::SqsClient::deleteQueue (const DeleteQueueRequest & request) slot
Deletes the queue specified by the QueueUrl, regardless of the queue's contents. If the specified queue doesn't exist, Amazon SQS returns a successful
response>
Be careful with the DeleteQueue action: When you delete a queue, any messages in the queue are no longer available.
</p
When you delete a queue, the deletion process takes up to 60 seconds. Requests you send involving that queue during the 60 seconds might succeed. For example, a SendMessage request might succeed, but after 60 seconds the queue and the message you sent no longer
exist>
When you delete a queue, you must wait at least 60 seconds before creating a queue with the same name.
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 490 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteQueueResponse *>(send(request));
 }
getQueueAttributes
GetQueueAttributesResponse * QtAws::SQS::SqsClient::getQueueAttributes (const GetQueueAttributesRequest & request) slot
Gets attributes for the specified
queue> <note>
To determine whether a queue is FIFO, you can check whether QueueName ends with the .fifo
suffix> </note> <note>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 523 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQueueAttributesResponse *>(send(request));
 }
getQueueUrl
GetQueueUrlResponse * QtAws::SQS::SqsClient::getQueueUrl (const GetQueueUrlRequest & request) slot
Returns the URL of an existing queue. This action provides a simple way to retrieve the URL of an Amazon SQS
queue>
To access a queue that belongs to another AWS account, use the QueueOwnerAWSAccountId parameter to specify the account ID of the queue's owner. The queue's owner must grant you permission to access the queue. For more information about shared queue access, see AddPermission or see Shared Queues in the Amazon Simple Queue Service Developer Guide.
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 545 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQueueUrlResponse *>(send(request));
 }
listDeadLetterSourceQueues
ListDeadLetterSourceQueuesResponse * QtAws::SQS::SqsClient::listDeadLetterSourceQueues (const ListDeadLetterSourceQueuesRequest & request) slot
Returns a list of your queues that have the RedrivePolicy queue attribute configured with a dead-letter
queue>
For more information about using dead-letter queues, see Using Amazon SQS Dead-Letter Queues in the Amazon Simple Queue Service Developer
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 565 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDeadLetterSourceQueuesResponse *>(send(request));
 }
listQueues
ListQueuesResponse * QtAws::SQS::SqsClient::listQueues (const ListQueuesRequest & request) slot
Returns a list of your queues. The maximum number of queues that can be returned is 1,000. If you specify a value for the optional QueueNamePrefix parameter, only queues with a name that begins with the specified value are
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 627 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQueuesResponse *>(send(request));
 }
listQueueTags
ListQueueTagsResponse * QtAws::SQS::SqsClient::listQueueTags (const ListQueueTagsRequest & request) slot
List all cost allocation tags added to the specified Amazon SQS queue. For an overview, see Tagging Amazon SQS Queues in the Amazon Simple Queue Service Developer
Guide>
When you use queue tags, keep the following guidelines in
mind>
Adding more than 50 tags to a queue isn't
recommended>
Tags don't have any semantic meaning. Amazon SQS interprets tags as character
strings>
Tags are
case-sensitive>
A new tag with a key identical to that of an existing tag overwrites the existing
tag>
Tagging API actions are limited to 5 TPS per AWS account. If your application requires a higher throughput, file a technical support request>
For a full list of tag restrictions, see Limits Related to Queues in the Amazon Simple Queue Service Developer
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 612 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQueueTagsResponse *>(send(request));
 }
purgeQueue
PurgeQueueResponse * QtAws::SQS::SqsClient::purgeQueue (const PurgeQueueRequest & request) slot
Deletes the messages in a queue specified by the QueueURL
parameter>
When you use the PurgeQueue action, you can't retrieve a message deleted from a
queue>
When you purge a queue, the message deletion process takes up to 60 seconds. All messages sent to the queue before calling the PurgeQueue action are deleted. Messages sent to the queue while it is being purged might be deleted. While the queue is being purged, messages sent to the queue before PurgeQueue is called might be received, but are deleted within the next
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 652 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurgeQueueResponse *>(send(request));
 }
receiveMessage
ReceiveMessageResponse * QtAws::SQS::SqsClient::receiveMessage (const ReceiveMessageRequest & request) slot
Retrieves one or more messages (up to 10), from the specified queue. Using the WaitTimeSeconds parameter enables long-poll support. For more information, see Amazon SQS Long Polling in the Amazon Simple Queue Service Developer Guide.
</p
Short poll is the default behavior where a weighted random set of machines is sampled on a ReceiveMessage call. Thus, only the messages on the sampled machines are returned. If the number of messages in the queue is small (fewer than 1,000), you most likely get fewer messages than you requested per ReceiveMessage call. If the number of messages in the queue is extremely small, you might not receive any messages in a particular ReceiveMessage response. If this happens, repeat the request.
</p
For each message returned, the response includes the
following>
The message
body>
An MD5 digest of the message body. For information about MD5, see RFC1321>
The MessageId you received when you sent the message to the
queue>
The receipt
handle>
The message
attributes>
An MD5 digest of the message
attributes>
The receipt handle is the identifier you must provide when deleting the message. For more information, see Queue and Message Identifiers in the Amazon Simple Queue Service Developer
Guide>
You can provide the VisibilityTimeout parameter in your request. The parameter is applied to the messages that Amazon SQS returns in the response. If you don't include the parameter, the overall visibility timeout for the queue is used for the returned messages. For more information, see Visibility Timeout in the Amazon Simple Queue Service Developer
Guide>
A message that isn't deleted or a message whose visibility isn't extended before the visibility timeout expires counts as a failed receive. Depending on the configuration of the queue, the message might be sent to the dead-letter
queue> <note>
In the future, new attributes might be added. If you write code that calls this action, we recommend that you structure your code so that it can handle new attributes
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 729 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReceiveMessageResponse *>(send(request));
 }
removePermission
RemovePermissionResponse * QtAws::SQS::SqsClient::removePermission (const RemovePermissionRequest & request) slot
Revokes any permissions in the queue policy that matches the specified Label parameter. Only the owner of the queue can remove
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 744 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemovePermissionResponse *>(send(request));
 }
sendMessage
SendMessageResponse * QtAws::SQS::SqsClient::sendMessage (const SendMessageRequest & request) slot
Delivers a message to the specified
queue>
A message can include only XML, JSON, and unformatted text. The following Unicode characters are
allowed>
#x9 | #xA | #xD | #x20 to #xD7FF | #xE000 to #xFFFD | #x10000 to #x10FFFF
</p
Any characters not included in this list will be rejected. For more information, see the W3C specification for request Request to send to Amazon Simple Queue Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 772 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendMessageResponse *>(send(request));
 }
sendMessageBatch
SendMessageBatchResponse * QtAws::SQS::SqsClient::sendMessageBatch (const SendMessageBatchRequest & request) slot
Delivers up to ten messages to the specified queue. This is a batch version of SendMessage. For a FIFO queue, multiple messages within a single batch are enqueued in the order they are
sent>
The result of sending each message is reported individually in the response. Because the batch request can result in a combination of successful and unsuccessful actions, you should check for batch errors even when the call returns an HTTP status code of
200>
The maximum allowed individual message size and the maximum total payload size (the sum of the individual lengths of all of the batched messages) are both 256 KB (262,144
bytes)>
A message can include only XML, JSON, and unformatted text. The following Unicode characters are
allowed>
#x9 | #xA | #xD | #x20 to #xD7FF | #xE000 to #xFFFD | #x10000 to #x10FFFF
</p
Any characters not included in this list will be rejected. For more information, see the W3C specification for characters>
If you don't specify the DelaySeconds parameter for an entry, Amazon SQS uses the default value for the
queue> <note>
Some actions take lists of parameters. These lists are specified using the param.n notation. Values of n are integers starting from 1. For example, a parameter list with two elements looks like
this>
&Attribute.1=this
</p
&Attribute.2=that
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 829 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendMessageBatchResponse *>(send(request));
 }
setQueueAttributes
SetQueueAttributesResponse * QtAws::SQS::SqsClient::setQueueAttributes (const SetQueueAttributesRequest & request) slot
Sets the value of one or more queue attributes. When you change a queue's attributes, the change can take up to 60 seconds for most of the attributes to propagate throughout the Amazon SQS system. Changes made to the MessageRetentionPeriod attribute can take up to 15
minutes> <note>
In the future, new attributes might be added. If you write code that calls this action, we recommend that you structure your code so that it can handle new attributes
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 850 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetQueueAttributesResponse *>(send(request));
 }
tagQueue
TagQueueResponse * QtAws::SQS::SqsClient::tagQueue (const TagQueueRequest & request) slot
Add cost allocation tags to the specified Amazon SQS queue. For an overview, see Tagging Amazon SQS Queues in the Amazon Simple Queue Service Developer
Guide>
When you use queue tags, keep the following guidelines in
mind>
Adding more than 50 tags to a queue isn't
recommended>
Tags don't have any semantic meaning. Amazon SQS interprets tags as character
strings>
Tags are
case-sensitive>
A new tag with a key identical to that of an existing tag overwrites the existing
tag>
Tagging API actions are limited to 5 TPS per AWS account. If your application requires a higher throughput, file a technical support request>
For a full list of tag restrictions, see Limits Related to Queues in the Amazon Simple Queue Service Developer
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 897 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagQueueResponse *>(send(request));
 }
untagQueue
UntagQueueResponse * QtAws::SQS::SqsClient::untagQueue (const UntagQueueRequest & request) slot
Remove cost allocation tags from the specified Amazon SQS queue. For an overview, see Tagging Amazon SQS Queues in the Amazon Simple Queue Service Developer
Guide>
When you use queue tags, keep the following guidelines in
mind>
Adding more than 50 tags to a queue isn't
recommended>
Tags don't have any semantic meaning. Amazon SQS interprets tags as character
strings>
Tags are
case-sensitive>
A new tag with a key identical to that of an existing tag overwrites the existing
tag>
Tagging API actions are limited to 5 TPS per AWS account. If your application requires a higher throughput, file a technical support request>
For a full list of tag restrictions, see Limits Related to Queues in the Amazon Simple Queue Service Developer
Parameters
request Request to send to Amazon Simple Queue Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 944 of file sqsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagQueueResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
sqs/sqsclient.h
sqs/sqsclient.cpp