AWS SDK for Qt: QtAws::IAM::IamClient Class Reference
QtAws::IAM::IamClient Class Reference
Client for AWS Identity and Access Management (IAM)
Public Slots
AddClientIDToOpenIDConnectProviderResponse * addClientIDToOpenIDConnectProvider (const AddClientIDToOpenIDConnectProviderRequest &request)
AddRoleToInstanceProfileResponse * addRoleToInstanceProfile (const AddRoleToInstanceProfileRequest &request)
AddUserToGroupResponse * addUserToGroup (const AddUserToGroupRequest &request)
AttachGroupPolicyResponse * attachGroupPolicy (const AttachGroupPolicyRequest &request)
AttachRolePolicyResponse * attachRolePolicy (const AttachRolePolicyRequest &request)
AttachUserPolicyResponse * attachUserPolicy (const AttachUserPolicyRequest &request)
ChangePasswordResponse * changePassword (const ChangePasswordRequest &request)
CreateAccessKeyResponse * createAccessKey (const CreateAccessKeyRequest &request)
CreateAccountAliasResponse * createAccountAlias (const CreateAccountAliasRequest &request)
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
CreateInstanceProfileResponse * createInstanceProfile (const CreateInstanceProfileRequest &request)
CreateLoginProfileResponse * createLoginProfile (const CreateLoginProfileRequest &request)
CreateOpenIDConnectProviderResponse * createOpenIDConnectProvider (const CreateOpenIDConnectProviderRequest &request)
CreatePolicyResponse * createPolicy (const CreatePolicyRequest &request)
CreatePolicyVersionResponse * createPolicyVersion (const CreatePolicyVersionRequest &request)
CreateRoleResponse * createRole (const CreateRoleRequest &request)
CreateSAMLProviderResponse * createSAMLProvider (const CreateSAMLProviderRequest &request)
CreateServiceLinkedRoleResponse * createServiceLinkedRole (const CreateServiceLinkedRoleRequest &request)
CreateServiceSpecificCredentialResponse * createServiceSpecificCredential (const CreateServiceSpecificCredentialRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
CreateVirtualMFADeviceResponse * createVirtualMFADevice (const CreateVirtualMFADeviceRequest &request)
DeactivateMFADeviceResponse * deactivateMFADevice (const DeactivateMFADeviceRequest &request)
DeleteAccessKeyResponse * deleteAccessKey (const DeleteAccessKeyRequest &request)
DeleteAccountAliasResponse * deleteAccountAlias (const DeleteAccountAliasRequest &request)
DeleteAccountPasswordPolicyResponse * deleteAccountPasswordPolicy ()
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
DeleteGroupPolicyResponse * deleteGroupPolicy (const DeleteGroupPolicyRequest &request)
DeleteInstanceProfileResponse * deleteInstanceProfile (const DeleteInstanceProfileRequest &request)
DeleteLoginProfileResponse * deleteLoginProfile (const DeleteLoginProfileRequest &request)
DeleteOpenIDConnectProviderResponse * deleteOpenIDConnectProvider (const DeleteOpenIDConnectProviderRequest &request)
DeletePolicyResponse * deletePolicy (const DeletePolicyRequest &request)
DeletePolicyVersionResponse * deletePolicyVersion (const DeletePolicyVersionRequest &request)
DeleteRoleResponse * deleteRole (const DeleteRoleRequest &request)
DeleteRolePolicyResponse * deleteRolePolicy (const DeleteRolePolicyRequest &request)
DeleteSAMLProviderResponse * deleteSAMLProvider (const DeleteSAMLProviderRequest &request)
DeleteSSHPublicKeyResponse * deleteSSHPublicKey (const DeleteSSHPublicKeyRequest &request)
DeleteServerCertificateResponse * deleteServerCertificate (const DeleteServerCertificateRequest &request)
DeleteServiceLinkedRoleResponse * deleteServiceLinkedRole (const DeleteServiceLinkedRoleRequest &request)
DeleteServiceSpecificCredentialResponse * deleteServiceSpecificCredential (const DeleteServiceSpecificCredentialRequest &request)
DeleteSigningCertificateResponse * deleteSigningCertificate (const DeleteSigningCertificateRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DeleteUserPolicyResponse * deleteUserPolicy (const DeleteUserPolicyRequest &request)
DeleteVirtualMFADeviceResponse * deleteVirtualMFADevice (const DeleteVirtualMFADeviceRequest &request)
DetachGroupPolicyResponse * detachGroupPolicy (const DetachGroupPolicyRequest &request)
DetachRolePolicyResponse * detachRolePolicy (const DetachRolePolicyRequest &request)
DetachUserPolicyResponse * detachUserPolicy (const DetachUserPolicyRequest &request)
EnableMFADeviceResponse * enableMFADevice (const EnableMFADeviceRequest &request)
GenerateCredentialReportResponse * generateCredentialReport ()
GetAccessKeyLastUsedResponse * getAccessKeyLastUsed (const GetAccessKeyLastUsedRequest &request)
GetAccountAuthorizationDetailsResponse * getAccountAuthorizationDetails (const GetAccountAuthorizationDetailsRequest &request)
GetAccountPasswordPolicyResponse * getAccountPasswordPolicy ()
GetAccountSummaryResponse * getAccountSummary ()
GetContextKeysForCustomPolicyResponse * getContextKeysForCustomPolicy (const GetContextKeysForCustomPolicyRequest &request)
GetContextKeysForPrincipalPolicyResponse * getContextKeysForPrincipalPolicy (const GetContextKeysForPrincipalPolicyRequest &request)
GetCredentialReportResponse * getCredentialReport ()
GetGroupResponse * getGroup (const GetGroupRequest &request)
GetGroupPolicyResponse * getGroupPolicy (const GetGroupPolicyRequest &request)
GetInstanceProfileResponse * getInstanceProfile (const GetInstanceProfileRequest &request)
GetLoginProfileResponse * getLoginProfile (const GetLoginProfileRequest &request)
GetOpenIDConnectProviderResponse * getOpenIDConnectProvider (const GetOpenIDConnectProviderRequest &request)
GetPolicyResponse * getPolicy (const GetPolicyRequest &request)
GetPolicyVersionResponse * getPolicyVersion (const GetPolicyVersionRequest &request)
GetRoleResponse * getRole (const GetRoleRequest &request)
GetRolePolicyResponse * getRolePolicy (const GetRolePolicyRequest &request)
GetSAMLProviderResponse * getSAMLProvider (const GetSAMLProviderRequest &request)
GetSSHPublicKeyResponse * getSSHPublicKey (const GetSSHPublicKeyRequest &request)
GetServerCertificateResponse * getServerCertificate (const GetServerCertificateRequest &request)
GetServiceLinkedRoleDeletionStatusResponse * getServiceLinkedRoleDeletionStatus (const GetServiceLinkedRoleDeletionStatusRequest &request)
GetUserResponse * getUser (const GetUserRequest &request)
GetUserPolicyResponse * getUserPolicy (const GetUserPolicyRequest &request)
ListAccessKeysResponse * listAccessKeys (const ListAccessKeysRequest &request)
ListAccountAliasesResponse * listAccountAliases (const ListAccountAliasesRequest &request)
ListAttachedGroupPoliciesResponse * listAttachedGroupPolicies (const ListAttachedGroupPoliciesRequest &request)
ListAttachedRolePoliciesResponse * listAttachedRolePolicies (const ListAttachedRolePoliciesRequest &request)
ListAttachedUserPoliciesResponse * listAttachedUserPolicies (const ListAttachedUserPoliciesRequest &request)
ListEntitiesForPolicyResponse * listEntitiesForPolicy (const ListEntitiesForPolicyRequest &request)
ListGroupPoliciesResponse * listGroupPolicies (const ListGroupPoliciesRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
ListGroupsForUserResponse * listGroupsForUser (const ListGroupsForUserRequest &request)
ListInstanceProfilesResponse * listInstanceProfiles (const ListInstanceProfilesRequest &request)
ListInstanceProfilesForRoleResponse * listInstanceProfilesForRole (const ListInstanceProfilesForRoleRequest &request)
ListMFADevicesResponse * listMFADevices (const ListMFADevicesRequest &request)
ListOpenIDConnectProvidersResponse * listOpenIDConnectProviders (const ListOpenIDConnectProvidersRequest &request)
ListPoliciesResponse * listPolicies (const ListPoliciesRequest &request)
ListPolicyVersionsResponse * listPolicyVersions (const ListPolicyVersionsRequest &request)
ListRolePoliciesResponse * listRolePolicies (const ListRolePoliciesRequest &request)
ListRolesResponse * listRoles (const ListRolesRequest &request)
ListSAMLProvidersResponse * listSAMLProviders (const ListSAMLProvidersRequest &request)
ListSSHPublicKeysResponse * listSSHPublicKeys (const ListSSHPublicKeysRequest &request)
ListServerCertificatesResponse * listServerCertificates (const ListServerCertificatesRequest &request)
ListServiceSpecificCredentialsResponse * listServiceSpecificCredentials (const ListServiceSpecificCredentialsRequest &request)
ListSigningCertificatesResponse * listSigningCertificates (const ListSigningCertificatesRequest &request)
ListUserPoliciesResponse * listUserPolicies (const ListUserPoliciesRequest &request)
ListUsersResponse * listUsers (const ListUsersRequest &request)
ListVirtualMFADevicesResponse * listVirtualMFADevices (const ListVirtualMFADevicesRequest &request)
PutGroupPolicyResponse * putGroupPolicy (const PutGroupPolicyRequest &request)
PutRolePolicyResponse * putRolePolicy (const PutRolePolicyRequest &request)
PutUserPolicyResponse * putUserPolicy (const PutUserPolicyRequest &request)
RemoveClientIDFromOpenIDConnectProviderResponse * removeClientIDFromOpenIDConnectProvider (const RemoveClientIDFromOpenIDConnectProviderRequest &request)
RemoveRoleFromInstanceProfileResponse * removeRoleFromInstanceProfile (const RemoveRoleFromInstanceProfileRequest &request)
RemoveUserFromGroupResponse * removeUserFromGroup (const RemoveUserFromGroupRequest &request)
ResetServiceSpecificCredentialResponse * resetServiceSpecificCredential (const ResetServiceSpecificCredentialRequest &request)
ResyncMFADeviceResponse * resyncMFADevice (const ResyncMFADeviceRequest &request)
SetDefaultPolicyVersionResponse * setDefaultPolicyVersion (const SetDefaultPolicyVersionRequest &request)
SimulateCustomPolicyResponse * simulateCustomPolicy (const SimulateCustomPolicyRequest &request)
SimulatePrincipalPolicyResponse * simulatePrincipalPolicy (const SimulatePrincipalPolicyRequest &request)
UpdateAccessKeyResponse * updateAccessKey (const UpdateAccessKeyRequest &request)
UpdateAccountPasswordPolicyResponse * updateAccountPasswordPolicy (const UpdateAccountPasswordPolicyRequest &request)
UpdateAssumeRolePolicyResponse * updateAssumeRolePolicy (const UpdateAssumeRolePolicyRequest &request)
UpdateGroupResponse * updateGroup (const UpdateGroupRequest &request)
UpdateLoginProfileResponse * updateLoginProfile (const UpdateLoginProfileRequest &request)
UpdateOpenIDConnectProviderThumbprintResponse * updateOpenIDConnectProviderThumbprint (const UpdateOpenIDConnectProviderThumbprintRequest &request)
UpdateRoleResponse * updateRole (const UpdateRoleRequest &request)
UpdateRoleDescriptionResponse * updateRoleDescription (const UpdateRoleDescriptionRequest &request)
UpdateSAMLProviderResponse * updateSAMLProvider (const UpdateSAMLProviderRequest &request)
UpdateSSHPublicKeyResponse * updateSSHPublicKey (const UpdateSSHPublicKeyRequest &request)
UpdateServerCertificateResponse * updateServerCertificate (const UpdateServerCertificateRequest &request)
UpdateServiceSpecificCredentialResponse * updateServiceSpecificCredential (const UpdateServiceSpecificCredentialRequest &request)
UpdateSigningCertificateResponse * updateSigningCertificate (const UpdateSigningCertificateRequest &request)
UpdateUserResponse * updateUser (const UpdateUserRequest &request)
UploadSSHPublicKeyResponse * uploadSSHPublicKey (const UploadSSHPublicKeyRequest &request)
UploadServerCertificateResponse * uploadServerCertificate (const UploadServerCertificateRequest &request)
UploadSigningCertificateResponse * uploadSigningCertificate (const UploadSigningCertificateRequest &request)
Public Member Functions
IamClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new IamClient object.
IamClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new IamClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Identity and Access Management (IAM)
<fullname>AWS Identity and Access Management</fullname>
AWS Identity and Access Management (IAM) is a web service that you can use to manage users and user permissions under your AWS account. This guide provides descriptions of IAM actions that you can call programmatically. For general information about IAM, see AWS Identity and Access Management (IAM). For the user guide for IAM, see Using IAM.
</p <note>
AWS provides SDKs that consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .NET, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to IAM and AWS. For example, the SDKs take care of tasks such as cryptographically signing requests (see below), managing errors, and retrying requests automatically. For information about the AWS SDKs, including how to download and install them, see the Tools for Amazon Web Services page.
</p </note>
We recommend that you use the AWS SDKs to make programmatic API calls to IAM. However, you can also use the IAM Query API to make direct calls to the IAM web service. To learn more about the IAM Query API, see Making Query Requests in the Using IAM guide. IAM supports GET and POST requests for all actions. That is, the API does not require you to use GET for some actions and POST for others. However, GET requests are subject to the limitation size of a URL. Therefore, for operations that require larger sizes, use a POST request.
</p
Signing Requests
</p
Requests must be signed using an access key ID and a secret access key. We strongly recommend that you do not use your AWS account access key ID and secret access key for everyday work with IAM. You can use the access key ID and secret access key for an IAM user or you can use the AWS Security Token Service to generate temporary security credentials and use those to sign
requests>
To sign requests, we recommend that you use Signature Version 4. If you have an existing application that uses Signature Version 2, you do not have to update it to use Signature Version 4. However, some operations now require Signature Version 4. The documentation for operations that require version 4 indicate this requirement.
</p
Additional Resources
</p
For more information, see the
following>
AWS Security Credentials. This topic provides general information about the types of credentials used for accessing AWS.
</p
IAM Best Practices. This topic presents a list of suggestions for using the IAM service to help secure your AWS resources.
</p
Signing AWS API Requests. This set of topics walk you through the process of signing a request using an access key ID and secret access key.
Definition at line 273 of file iamclient.h.
Constructor & Destructor Documentation
IamClient() [1/2]
QtAws::IAM::IamClient::IamClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new IamClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 352 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new IamClientPrivate(this), parent)
 {
     Q_D(IamClient);
     d->apiVersion = QStringLiteral("2010-05-08");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("iam");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Identity and Access Management");
     d->serviceName = QStringLiteral("iam");
 }
IamClient() [2/2]
QtAws::IAM::IamClient::IamClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new IamClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 385 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new IamClientPrivate(this), parent)
 {
     Q_D(IamClient);
     d->apiVersion = QStringLiteral("2010-05-08");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("iam");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Identity and Access Management");
     d->serviceName = QStringLiteral("iam");
 }
Member Function Documentation
addClientIDToOpenIDConnectProvider
AddClientIDToOpenIDConnectProviderResponse * QtAws::IAM::IamClient::addClientIDToOpenIDConnectProvider (const AddClientIDToOpenIDConnectProviderRequest & request) slot
Adds a new client ID (also known as audience) to the list of client IDs already registered for the specified IAM OpenID Connect (OIDC) provider
resource>
This operation is idempotent; it does not fail or return an error if you add an existing client ID to the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 416 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddClientIDToOpenIDConnectProviderResponse *>(send(request));
 }
addRoleToInstanceProfile
AddRoleToInstanceProfileResponse * QtAws::IAM::IamClient::addRoleToInstanceProfile (const AddRoleToInstanceProfileRequest & request) slot
Adds the specified IAM role to the specified instance profile. An instance profile can contain only one role, and this limit cannot be increased. You can remove the existing role and then add a different role to an instance profile. You must then wait for the change to appear across all of AWS because of eventual consistency. To force the change, you must disassociate the instance profile and then associate the instance profile, or you can stop your instance and then restart
it> <note>
The caller of this API must be granted the PassRole permission on the IAM role by a permission
policy> </note>
For more information about roles, go to Working with Roles. For more information about instance profiles, go to About Instance request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 448 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddRoleToInstanceProfileResponse *>(send(request));
 }
addUserToGroup
AddUserToGroupResponse * QtAws::IAM::IamClient::addUserToGroup (const AddUserToGroupRequest & request) slot
Adds the specified user to the specified
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 462 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddUserToGroupResponse *>(send(request));
 }
attachGroupPolicy
AttachGroupPolicyResponse * QtAws::IAM::IamClient::attachGroupPolicy (const AttachGroupPolicyRequest & request) slot
Attaches the specified managed policy to the specified IAM
group>
You use this API to attach a managed policy to a group. To embed an inline policy in a group, use
PutGroupPolicy>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 486 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachGroupPolicyResponse *>(send(request));
 }
attachRolePolicy
AttachRolePolicyResponse * QtAws::IAM::IamClient::attachRolePolicy (const AttachRolePolicyRequest & request) slot
Attaches the specified managed policy to the specified IAM role. When you attach a managed policy to a role, the managed policy becomes part of the role's permission (access)
policy> <note>
You cannot use a managed policy as the role's trust policy. The role's trust policy is created at the same time as the role, using CreateRole. You can update a role's trust policy using
UpdateAssumeRolePolicy> </note>
Use this API to attach a managed policy to a role. To embed an inline policy in a role, use PutRolePolicy. For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 513 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachRolePolicyResponse *>(send(request));
 }
attachUserPolicy
AttachUserPolicyResponse * QtAws::IAM::IamClient::attachUserPolicy (const AttachUserPolicyRequest & request) slot
Attaches the specified managed policy to the specified
user>
You use this API to attach a managed policy to a user. To embed an inline policy in a user, use
PutUserPolicy>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 537 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachUserPolicyResponse *>(send(request));
 }
changePassword
ChangePasswordResponse * QtAws::IAM::IamClient::changePassword (const ChangePasswordRequest & request) slot
Changes the password of the IAM user who is calling this operation. The AWS account root user password is not affected by this
operation>
To change the password for a different user, see UpdateLoginProfile. For more information about modifying passwords, see Managing Passwords in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 558 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ChangePasswordResponse *>(send(request));
 }
createAccessKey
CreateAccessKeyResponse * QtAws::IAM::IamClient::createAccessKey (const CreateAccessKeyRequest & request) slot
Creates a new AWS secret access key and corresponding AWS access key ID for the specified user. The default status for new keys is
Active>
If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID signing the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials. This is true even if the AWS account has no associated
users>
For information about limits on the number of keys you can create, see Limitations on IAM Entities in the IAM User
Guide>
To ensure the security of your AWS account, the secret access key is accessible only during key and user creation. You must save the key (for example, in a text file) if you want to be able to access it again. If a secret key is lost, you can delete the access keys for the associated user and then create new
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 591 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAccessKeyResponse *>(send(request));
 }
createAccountAlias
CreateAccountAliasResponse * QtAws::IAM::IamClient::createAccountAlias (const CreateAccountAliasRequest & request) slot
Creates an alias for your AWS account. For information about using an AWS account alias, see Using an Alias for Your AWS Account ID in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 607 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAccountAliasResponse *>(send(request));
 }
createGroup
CreateGroupResponse * QtAws::IAM::IamClient::createGroup (const CreateGroupRequest & request) slot
Creates a new
group>
For information about the number of groups you can create, see Limitations on IAM Entities in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 627 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGroupResponse *>(send(request));
 }
createInstanceProfile
CreateInstanceProfileResponse * QtAws::IAM::IamClient::createInstanceProfile (const CreateInstanceProfileRequest & request) slot
Creates a new instance profile. For information about instance profiles, go to About Instance Profiles>
For information about the number of instance profiles you can create, see Limitations on IAM Entities in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 648 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInstanceProfileResponse *>(send(request));
 }
createLoginProfile
CreateLoginProfileResponse * QtAws::IAM::IamClient::createLoginProfile (const CreateLoginProfileRequest & request) slot
Creates a password for the specified user, giving the user the ability to access AWS services through the AWS Management Console. For more information about managing passwords, see Managing Passwords in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 665 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLoginProfileResponse *>(send(request));
 }
createOpenIDConnectProvider
CreateOpenIDConnectProviderResponse * QtAws::IAM::IamClient::createOpenIDConnectProvider (const CreateOpenIDConnectProviderRequest & request) slot
Creates an IAM entity to describe an identity provider (IdP) that supports OpenID Connect (OIDC)>
The OIDC provider that you create with this operation can be used as a principal in a role's trust policy. Such a policy establishes a trust relationship between AWS and the OIDC
provider>
When you create the IAM OIDC provider, you specify the
following>
The URL of the OIDC identity provider (IdP) to
trus>
A list of client IDs (also known as audiences) that identify the application or applications that are allowed to authenticate using the OIDC
provide>
A list of thumbprints of the server certificate(s) that the IdP
uses>
You get all of this information from the OIDC IdP that you want to use to access
AWS> <note>
Because trust for the OIDC provider is derived from the IAM provider that this operation creates, it is best to limit access to the CreateOpenIDConnectProvider operation to highly privileged
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 711 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateOpenIDConnectProviderResponse *>(send(request));
 }
createPolicy
CreatePolicyResponse * QtAws::IAM::IamClient::createPolicy (const CreatePolicyRequest & request) slot
Creates a new managed policy for your AWS
account>
This operation creates a policy version with a version identifier of v1 and sets v1 as the policy's default version. For more information about policy versions, see Versioning for Managed Policies in the IAM User
Guide>
For more information about managed policies in general, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 738 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePolicyResponse *>(send(request));
 }
createPolicyVersion
CreatePolicyVersionResponse * QtAws::IAM::IamClient::createPolicyVersion (const CreatePolicyVersionRequest & request) slot
Creates a new version of the specified managed policy. To update a managed policy, you create a new policy version. A managed policy can have up to five versions. If the policy has five versions, you must delete an existing version using DeletePolicyVersion before you create a new
version>
Optionally, you can set the new version as the policy's default version. The default version is the version that is in effect for the IAM users, groups, and roles to which the policy is
attached>
For more information about managed policy versions, see Versioning for Managed Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 765 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePolicyVersionResponse *>(send(request));
 }
createRole
CreateRoleResponse * QtAws::IAM::IamClient::createRole (const CreateRoleRequest & request) slot
Creates a new role for your AWS account. For more information about roles, go to IAM Roles. For information about limitations on role names and the number of roles you can create, go to Limitations on IAM Entities in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 783 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRoleResponse *>(send(request));
 }
createSAMLProvider
CreateSAMLProviderResponse * QtAws::IAM::IamClient::createSAMLProvider (const CreateSAMLProviderRequest & request) slot
Creates an IAM resource that describes an identity provider (IdP) that supports SAML
2.0>
The SAML provider resource that you create with this operation can be used as a principal in an IAM role's trust policy. Such a policy can enable federated users who sign-in using the SAML IdP to assume the role. You can create an IAM role that supports Web-based single sign-on (SSO) to the AWS Management Console or one that supports API access to
AWS>
When you create the SAML provider resource, you upload a SAML metadata document that you get from your IdP. That document includes the issuer's name, expiration information, and keys that can be used to validate the SAML authentication response (assertions) that the IdP sends. You must generate the metadata document using the identity management software that is used as your organization's
IdP> <note>
This operation requires Signature Version 4> </note>
For more information, see Enabling SAML 2.0 Federated Users to Access the AWS Management Console and About SAML 2.0-based Federation in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 823 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSAMLProviderResponse *>(send(request));
 }
createServiceLinkedRole
CreateServiceLinkedRoleResponse * QtAws::IAM::IamClient::createServiceLinkedRole (const CreateServiceLinkedRoleRequest & request) slot
Creates an IAM role that is linked to a specific AWS service. The service controls the attached policies and when the role can be deleted. This helps ensure that the service is not broken by an unexpectedly changed or deleted role, which could put your AWS resources into an unknown state. Allowing the service to control the role helps improve service stability and proper cleanup when a service and its role are no longer
needed>
The name of the role is generated by combining the string that you specify for the AWSServiceName parameter with the string that you specify for the CustomSuffix parameter. The resulting name must be unique in your account or the request
fails>
To attach a policy to this service-linked role, you must make the request using the AWS service that depends on this
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 850 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateServiceLinkedRoleResponse *>(send(request));
 }
createServiceSpecificCredential
CreateServiceSpecificCredentialResponse * QtAws::IAM::IamClient::createServiceSpecificCredential (const CreateServiceSpecificCredentialRequest & request) slot
Generates a set of credentials consisting of a user name and password that can be used to access the service specified in the request. These credentials are generated by IAM, and can be used only for the specified service.
The only supported service at this time is AWS
CodeCommit>
You can reset the password to a new service-generated value by calling
ResetServiceSpecificCredential>
For more information about service-specific credentials, see Using IAM with AWS CodeCommit: Git Credentials, SSH Keys, and AWS Access Keys in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 883 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateServiceSpecificCredentialResponse *>(send(request));
 }
createUser
CreateUserResponse * QtAws::IAM::IamClient::createUser (const CreateUserRequest & request) slot
Creates a new IAM user for your AWS
account>
For information about limitations on the number of IAM users you can create, see Limitations on IAM Entities in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 903 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserResponse *>(send(request));
 }
createVirtualMFADevice
CreateVirtualMFADeviceResponse * QtAws::IAM::IamClient::createVirtualMFADevice (const CreateVirtualMFADeviceRequest & request) slot
Creates a new virtual MFA device for the AWS account. After creating the virtual MFA, use EnableMFADevice to attach the MFA device to an IAM user. For more information about creating and working with virtual MFA devices, go to Using a Virtual MFA Device in the IAM User
Guide>
For information about limits on the number of MFA devices you can create, see Limitations on Entities in the IAM User
Guide>
The seed information contained in the QR code and the Base32 string should be treated like any other secret access information, such as your AWS access keys or your passwords. After you provision your virtual device, you should ensure that the information is destroyed following secure
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 932 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateVirtualMFADeviceResponse *>(send(request));
 }
deactivateMFADevice
DeactivateMFADeviceResponse * QtAws::IAM::IamClient::deactivateMFADevice (const DeactivateMFADeviceRequest & request) slot
Deactivates the specified MFA device and removes it from association with the user name for which it was originally
enabled>
For more information about creating and working with virtual MFA devices, go to Using a Virtual MFA Device in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 952 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeactivateMFADeviceResponse *>(send(request));
 }
deleteAccessKey
DeleteAccessKeyResponse * QtAws::IAM::IamClient::deleteAccessKey (const DeleteAccessKeyRequest & request) slot
Deletes the access key pair associated with the specified IAM
user>
If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID signing the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 972 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAccessKeyResponse *>(send(request));
 }
deleteAccountAlias
DeleteAccountAliasResponse * QtAws::IAM::IamClient::deleteAccountAlias (const DeleteAccountAliasRequest & request) slot
Deletes the specified AWS account alias. For information about using an AWS account alias, see Using an Alias for Your AWS Account ID in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 988 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAccountAliasResponse *>(send(request));
 }
deleteAccountPasswordPolicy
DeleteAccountPasswordPolicyResponse * QtAws::IAM::IamClient::deleteAccountPasswordPolicy () slot
Deletes the password policy for the AWS account. There are no
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1002 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAccountPasswordPolicyResponse *>(send(request));
 }
deleteGroup
DeleteGroupResponse * QtAws::IAM::IamClient::deleteGroup (const DeleteGroupRequest & request) slot
Deletes the specified IAM group. The group must not contain any users or have any attached
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1016 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGroupResponse *>(send(request));
 }
deleteGroupPolicy
DeleteGroupPolicyResponse * QtAws::IAM::IamClient::deleteGroupPolicy (const DeleteGroupPolicyRequest & request) slot
Deletes the specified inline policy that is embedded in the specified IAM
group>
A group can also have managed policies attached to it. To detach a managed policy from a group, use DetachGroupPolicy. For more information about policies, refer to Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1037 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGroupPolicyResponse *>(send(request));
 }
deleteInstanceProfile
DeleteInstanceProfileResponse * QtAws::IAM::IamClient::deleteInstanceProfile (const DeleteInstanceProfileRequest & request) slot
Deletes the specified instance profile. The instance profile must not have an associated
role>
Make sure that you do not have any Amazon EC2 instances running with the instance profile you are about to delete. Deleting a role or instance profile that is associated with a running instance will break any applications running on the
instance>
For more information about instance profiles, go to About Instance request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1062 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInstanceProfileResponse *>(send(request));
 }
deleteLoginProfile
DeleteLoginProfileResponse * QtAws::IAM::IamClient::deleteLoginProfile (const DeleteLoginProfileRequest & request) slot
Deletes the password for the specified IAM user, which terminates the user's ability to access AWS services through the AWS Management
Console>
Deleting a user's password does not prevent a user from accessing AWS through the command line interface or the API. To prevent all user access you must also either make any access keys inactive or delete them. For more information about making keys inactive or deleting them, see UpdateAccessKey and DeleteAccessKey.
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1083 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLoginProfileResponse *>(send(request));
 }
deleteOpenIDConnectProvider
DeleteOpenIDConnectProviderResponse * QtAws::IAM::IamClient::deleteOpenIDConnectProvider (const DeleteOpenIDConnectProviderRequest & request) slot
Deletes an OpenID Connect identity provider (IdP) resource object in
IAM>
Deleting an IAM OIDC provider resource does not update any roles that reference the provider as a principal in their trust policies. Any attempt to assume a role that references a deleted provider
fails>
This operation is idempotent; it does not fail or return an error if you call the operation for a provider that does not
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1106 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteOpenIDConnectProviderResponse *>(send(request));
 }
deletePolicy
DeletePolicyResponse * QtAws::IAM::IamClient::deletePolicy (const DeletePolicyRequest & request) slot
Deletes the specified managed
policy>
Before you can delete a managed policy, you must first detach the policy from all users, groups, and roles that it is attached to. In addition you must delete all the policy's versions. The following steps describe the process for deleting a managed
policy>
Detach the policy from all users, groups, and roles that the policy is attached to, using the DetachUserPolicy, DetachGroupPolicy, or DetachRolePolicy API operations. To list all the users, groups, and roles that a policy is attached to, use
ListEntitiesForPolicy>
Delete all versions of the policy using DeletePolicyVersion. To list the policy's versions, use ListPolicyVersions. You cannot use DeletePolicyVersion to delete the version that is marked as the default version. You delete the policy's default version in the next step of the
process>
Delete the policy (this automatically deletes the policy's default version) using this
API>
For information about managed policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1148 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePolicyResponse *>(send(request));
 }
deletePolicyVersion
DeletePolicyVersionResponse * QtAws::IAM::IamClient::deletePolicyVersion (const DeletePolicyVersionRequest & request) slot
Deletes the specified version from the specified managed
policy>
You cannot delete the default version from a policy using this API. To delete the default version from a policy, use DeletePolicy. To find out which version of a policy is marked as the default version, use
ListPolicyVersions>
For information about versions for managed policies, see Versioning for Managed Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1173 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePolicyVersionResponse *>(send(request));
 }
deleteRole
DeleteRoleResponse * QtAws::IAM::IamClient::deleteRole (const DeleteRoleRequest & request) slot
Deletes the specified role. The role must not have any policies attached. For more information about roles, go to Working with Roles>
Make sure that you do not have any Amazon EC2 instances running with the role you are about to delete. Deleting a role or instance profile that is associated with a running instance will break any applications running on the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1193 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRoleResponse *>(send(request));
 }
deleteRolePolicy
DeleteRolePolicyResponse * QtAws::IAM::IamClient::deleteRolePolicy (const DeleteRolePolicyRequest & request) slot
Deletes the specified inline policy that is embedded in the specified IAM
role>
A role can also have managed policies attached to it. To detach a managed policy from a role, use DetachRolePolicy. For more information about policies, refer to Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1214 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRolePolicyResponse *>(send(request));
 }
deleteSAMLProvider
DeleteSAMLProviderResponse * QtAws::IAM::IamClient::deleteSAMLProvider (const DeleteSAMLProviderRequest & request) slot
Deletes a SAML provider resource in
IAM>
Deleting the provider resource from IAM does not update any roles that reference the SAML provider resource's ARN as a principal in their trust policies. Any attempt to assume a role that references a non-existent provider resource ARN
fails> <note>
This operation requires Signature Version request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1238 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSAMLProviderResponse *>(send(request));
 }
deleteServerCertificate
DeleteServerCertificateResponse * QtAws::IAM::IamClient::deleteServerCertificate (const DeleteServerCertificateRequest & request) slot
Deletes the specified server
certificate>
For more information about working with server certificates, see Working with Server Certificates in the IAM User Guide. This topic also includes a list of AWS services that can use the server certificates that you manage with
IAM>
If you are using a server certificate with Elastic Load Balancing, deleting the certificate could have implications for your application. If Elastic Load Balancing doesn't detect the deletion of bound certificates, it may continue to use the certificates. This could cause Elastic Load Balancing to stop accepting traffic. We recommend that you remove the reference to the certificate from Elastic Load Balancing before using this command to delete the certificate. For more information, go to DeleteLoadBalancerListeners in the Elastic Load Balancing API
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1290 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServerCertificateResponse *>(send(request));
 }
deleteServiceLinkedRole
DeleteServiceLinkedRoleResponse * QtAws::IAM::IamClient::deleteServiceLinkedRole (const DeleteServiceLinkedRoleRequest & request) slot
Submits a service-linked role deletion request and returns a DeletionTaskId, which you can use to check the status of the deletion. Before you call this operation, confirm that the role has no active sessions and that any resources used by the role in the linked service are deleted. If you call this operation more than once for the same service-linked role and an earlier deletion task is not complete, then the DeletionTaskId of the earlier request is
returned>
If you submit a deletion request for a service-linked role whose linked service is still accessing a resource, then the deletion task fails. If it fails, the GetServiceLinkedRoleDeletionStatus API operation returns the reason for the failure, usually including the resources that must be deleted. To delete the service-linked role, you must first remove those resources from the linked service and then submit the deletion request again. Resources are specific to the service that is linked to the role. For more information about removing resources from a service, see the AWS documentation for your
service>
For more information about service-linked roles, see Roles Terms and Concepts: AWS Service-Linked Role in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1323 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServiceLinkedRoleResponse *>(send(request));
 }
deleteServiceSpecificCredential
DeleteServiceSpecificCredentialResponse * QtAws::IAM::IamClient::deleteServiceSpecificCredential (const DeleteServiceSpecificCredentialRequest & request) slot
Deletes the specified service-specific
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1337 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteServiceSpecificCredentialResponse *>(send(request));
 }
deleteSigningCertificate
DeleteSigningCertificateResponse * QtAws::IAM::IamClient::deleteSigningCertificate (const DeleteSigningCertificateRequest & request) slot
Deletes a signing certificate associated with the specified IAM
user>
If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID signing the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated IAM
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1357 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSigningCertificateResponse *>(send(request));
 }
deleteSSHPublicKey
DeleteSSHPublicKeyResponse * QtAws::IAM::IamClient::deleteSSHPublicKey (const DeleteSSHPublicKeyRequest & request) slot
Deletes the specified SSH public
key>
The SSH public key deleted by this operation is used only for authenticating the associated IAM user to an AWS CodeCommit repository. For more information about using SSH keys to authenticate to an AWS CodeCommit repository, see Set up AWS CodeCommit for SSH Connections in the AWS CodeCommit User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1259 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSSHPublicKeyResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::IAM::IamClient::deleteUser (const DeleteUserRequest & request) slot
Deletes the specified IAM user. The user must not belong to any groups or have any access keys, signing certificates, or attached
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1372 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
deleteUserPolicy
DeleteUserPolicyResponse * QtAws::IAM::IamClient::deleteUserPolicy (const DeleteUserPolicyRequest & request) slot
Deletes the specified inline policy that is embedded in the specified IAM
user>
A user can also have managed policies attached to it. To detach a managed policy from a user, use DetachUserPolicy. For more information about policies, refer to Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1393 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserPolicyResponse *>(send(request));
 }
deleteVirtualMFADevice
DeleteVirtualMFADeviceResponse * QtAws::IAM::IamClient::deleteVirtualMFADevice (const DeleteVirtualMFADeviceRequest & request) slot
Deletes a virtual MFA
device> <note>
You must deactivate a user's virtual MFA device before you can delete it. For information about deactivating MFA devices, see DeactivateMFADevice.
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1412 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVirtualMFADeviceResponse *>(send(request));
 }
detachGroupPolicy
DetachGroupPolicyResponse * QtAws::IAM::IamClient::detachGroupPolicy (const DetachGroupPolicyRequest & request) slot
Removes the specified managed policy from the specified IAM
group>
A group can also have inline policies embedded with it. To delete an inline policy, use the DeleteGroupPolicy API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1433 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachGroupPolicyResponse *>(send(request));
 }
detachRolePolicy
DetachRolePolicyResponse * QtAws::IAM::IamClient::detachRolePolicy (const DetachRolePolicyRequest & request) slot
Removes the specified managed policy from the specified
role>
A role can also have inline policies embedded with it. To delete an inline policy, use the DeleteRolePolicy API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1454 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachRolePolicyResponse *>(send(request));
 }
detachUserPolicy
DetachUserPolicyResponse * QtAws::IAM::IamClient::detachUserPolicy (const DetachUserPolicyRequest & request) slot
Removes the specified managed policy from the specified
user>
A user can also have inline policies embedded with it. To delete an inline policy, use the DeleteUserPolicy API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1475 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachUserPolicyResponse *>(send(request));
 }
enableMFADevice
EnableMFADeviceResponse * QtAws::IAM::IamClient::enableMFADevice (const EnableMFADeviceRequest & request) slot
Enables the specified MFA device and associates it with the specified IAM user. When enabled, the MFA device is required for every subsequent login by the IAM user associated with the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1490 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableMFADeviceResponse *>(send(request));
 }
generateCredentialReport
GenerateCredentialReportResponse * QtAws::IAM::IamClient::generateCredentialReport () slot
Generates a credential report for the AWS account. For more information about the credential report, see Getting Credential Reports in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1506 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GenerateCredentialReportResponse *>(send(request));
 }
getAccessKeyLastUsed
GetAccessKeyLastUsedResponse * QtAws::IAM::IamClient::getAccessKeyLastUsed (const GetAccessKeyLastUsedRequest & request) slot
Retrieves information about when the specified access key was last used. The information includes the date and time of last use, along with the AWS service and region that were specified in the last request made with that
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1521 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccessKeyLastUsedResponse *>(send(request));
 }
getAccountAuthorizationDetails
GetAccountAuthorizationDetailsResponse * QtAws::IAM::IamClient::getAccountAuthorizationDetails (const GetAccountAuthorizationDetailsRequest & request) slot
Retrieves information about all IAM users, groups, roles, and policies in your AWS account, including their relationships to one another. Use this API to obtain a snapshot of the configuration of IAM permissions (users, groups, roles, and policies) in your
account> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
functionality> </note>
You can optionally filter the results using the Filter parameter. You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1549 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountAuthorizationDetailsResponse *>(send(request));
 }
getAccountPasswordPolicy
GetAccountPasswordPolicyResponse * QtAws::IAM::IamClient::getAccountPasswordPolicy () slot
Retrieves the password policy for the AWS account. For more information about using a password policy, go to Managing an IAM Password request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1564 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountPasswordPolicyResponse *>(send(request));
 }
getAccountSummary
GetAccountSummaryResponse * QtAws::IAM::IamClient::getAccountSummary () slot
Retrieves information about IAM entity usage and IAM quotas in the AWS
account>
For information about limitations on IAM entities, see Limitations on IAM Entities in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1584 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountSummaryResponse *>(send(request));
 }
getContextKeysForCustomPolicy
GetContextKeysForCustomPolicyResponse * QtAws::IAM::IamClient::getContextKeysForCustomPolicy (const GetContextKeysForCustomPolicyRequest & request) slot
Gets a list of all of the context keys referenced in the input policies. The policies are supplied as a list of one or more strings. To get the context keys from policies associated with an IAM user, group, or role, use
GetContextKeysForPrincipalPolicy>
Context keys are variables maintained by AWS and its services that provide details about the context of an API query request. Context keys can be evaluated by testing against a value specified in an IAM policy. Use GetContextKeysForCustomPolicy to understand what key names and values you must supply when you call SimulateCustomPolicy. Note that all parameters are shown in unencoded form here for clarity but must be URL encoded to be included as a part of a real HTML
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1607 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetContextKeysForCustomPolicyResponse *>(send(request));
 }
getContextKeysForPrincipalPolicy
GetContextKeysForPrincipalPolicyResponse * QtAws::IAM::IamClient::getContextKeysForPrincipalPolicy (const GetContextKeysForPrincipalPolicyRequest & request) slot
Gets a list of all of the context keys referenced in all the IAM policies that are attached to the specified IAM entity. The entity can be an IAM user, group, or role. If you specify a user, then the request also includes all of the policies attached to groups that the user is a member
of>
You can optionally include a list of one or more additional policies, specified as strings. If you want to include only a list of policies by string, use GetContextKeysForCustomPolicy
instead>
Note: This API discloses information about the permissions granted to other users. If you do not want users to see other user's permissions, then consider allowing them to use GetContextKeysForCustomPolicy
instead>
Context keys are variables maintained by AWS and its services that provide details about the context of an API query request. Context keys can be evaluated by testing against a value in an IAM policy. Use GetContextKeysForPrincipalPolicy to understand what key names and values you must supply when you call
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1639 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetContextKeysForPrincipalPolicyResponse *>(send(request));
 }
getCredentialReport
GetCredentialReportResponse * QtAws::IAM::IamClient::getCredentialReport () slot
Retrieves a credential report for the AWS account. For more information about the credential report, see Getting Credential Reports in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1655 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCredentialReportResponse *>(send(request));
 }
getGroup
GetGroupResponse * QtAws::IAM::IamClient::getGroup (const GetGroupRequest & request) slot
Returns a list of IAM users that are in the specified IAM group. You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1670 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGroupResponse *>(send(request));
 }
getGroupPolicy
GetGroupPolicyResponse * QtAws::IAM::IamClient::getGroupPolicy (const GetGroupPolicyRequest & request) slot
Retrieves the specified inline policy document that is embedded in the specified IAM
group> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
functionality> </note>
An IAM group can also have managed policies attached to it. To retrieve a managed policy document that is attached to a group, use GetPolicy to determine the policy's default version, then use GetPolicyVersion to retrieve the policy
document>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1703 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGroupPolicyResponse *>(send(request));
 }
getInstanceProfile
GetInstanceProfileResponse * QtAws::IAM::IamClient::getInstanceProfile (const GetInstanceProfileRequest & request) slot
Retrieves information about the specified instance profile, including the instance profile's path, GUID, ARN, and role. For more information about instance profiles, see About Instance Profiles in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1720 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetInstanceProfileResponse *>(send(request));
 }
getLoginProfile
GetLoginProfileResponse * QtAws::IAM::IamClient::getLoginProfile (const GetLoginProfileRequest & request) slot
Retrieves the user name and password-creation date for the specified IAM user. If the user has not been assigned a password, the operation returns a 404 (NoSuchEntity)
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1735 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetLoginProfileResponse *>(send(request));
 }
getOpenIDConnectProvider
GetOpenIDConnectProviderResponse * QtAws::IAM::IamClient::getOpenIDConnectProvider (const GetOpenIDConnectProviderRequest & request) slot
Returns information about the specified OpenID Connect (OIDC) provider resource object in
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1749 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetOpenIDConnectProviderResponse *>(send(request));
 }
getPolicy
GetPolicyResponse * QtAws::IAM::IamClient::getPolicy (const GetPolicyRequest & request) slot
Retrieves information about the specified managed policy, including the policy's default version and the total number of IAM users, groups, and roles to which the policy is attached. To retrieve the list of the specific users, groups, and roles that the policy is attached to, use the ListEntitiesForPolicy API. This API returns metadata about the policy. To retrieve the actual policy document for a specific version of the policy, use
GetPolicyVersion>
This API retrieves information about managed policies. To retrieve information about an inline policy that is embedded with an IAM user, group, or role, use the GetUserPolicy, GetGroupPolicy, or GetRolePolicy
API>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1777 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPolicyResponse *>(send(request));
 }
getPolicyVersion
GetPolicyVersionResponse * QtAws::IAM::IamClient::getPolicyVersion (const GetPolicyVersionRequest & request) slot
Retrieves information about the specified version of the specified managed policy, including the policy
document> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
functionality> </note>
To list the available versions for a policy, use
ListPolicyVersions>
This API retrieves information about managed policies. To retrieve information about an inline policy that is embedded in a user, group, or role, use the GetUserPolicy, GetGroupPolicy, or GetRolePolicy
API>
For more information about the types of policies, see Managed Policies and Inline Policies in the IAM User
Guide>
For more information about managed policy versions, see Versioning for Managed Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1819 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPolicyVersionResponse *>(send(request));
 }
getRole
GetRoleResponse * QtAws::IAM::IamClient::getRole (const GetRoleRequest & request) slot
Retrieves information about the specified role, including the role's path, GUID, ARN, and the role's trust policy that grants permission to assume the role. For more information about roles, see Working with Roles> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1842 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRoleResponse *>(send(request));
 }
getRolePolicy
GetRolePolicyResponse * QtAws::IAM::IamClient::getRolePolicy (const GetRolePolicyRequest & request) slot
Retrieves the specified inline policy document that is embedded with the specified IAM
role> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
functionality> </note>
An IAM role can also have managed policies attached to it. To retrieve a managed policy document that is attached to a role, use GetPolicy to determine the policy's default version, then use GetPolicyVersion to retrieve the policy
document>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
For more information about roles, see Using Roles to Delegate Permissions and Federate request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1881 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRolePolicyResponse *>(send(request));
 }
getSAMLProvider
GetSAMLProviderResponse * QtAws::IAM::IamClient::getSAMLProvider (const GetSAMLProviderRequest & request) slot
Returns the SAML provider metadocument that was uploaded when the IAM SAML provider resource object was created or
updated> <note>
This operation requires Signature Version request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1900 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSAMLProviderResponse *>(send(request));
 }
getServerCertificate
GetServerCertificateResponse * QtAws::IAM::IamClient::getServerCertificate (const GetServerCertificateRequest & request) slot
Retrieves information about the specified server certificate stored in
IAM>
For more information about working with server certificates, see Working with Server Certificates in the IAM User Guide. This topic includes a list of AWS services that can use the server certificates that you manage with
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1942 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetServerCertificateResponse *>(send(request));
 }
getServiceLinkedRoleDeletionStatus
GetServiceLinkedRoleDeletionStatusResponse * QtAws::IAM::IamClient::getServiceLinkedRoleDeletionStatus (const GetServiceLinkedRoleDeletionStatusRequest & request) slot
Retrieves the status of your service-linked role deletion. After you use the DeleteServiceLinkedRole API operation to submit a service-linked role for deletion, you can use the DeletionTaskId parameter in GetServiceLinkedRoleDeletionStatus to check the status of the deletion. If the deletion fails, this operation returns the reason that it failed, if that information is returned by the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1959 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetServiceLinkedRoleDeletionStatusResponse *>(send(request));
 }
getSSHPublicKey
GetSSHPublicKeyResponse * QtAws::IAM::IamClient::getSSHPublicKey (const GetSSHPublicKeyRequest & request) slot
Retrieves the specified SSH public key, including metadata about the
key>
The SSH public key retrieved by this operation is used only for authenticating the associated IAM user to an AWS CodeCommit repository. For more information about using SSH keys to authenticate to an AWS CodeCommit repository, see Set up AWS CodeCommit for SSH Connections in the AWS CodeCommit User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1921 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSSHPublicKeyResponse *>(send(request));
 }
getUser
GetUserResponse * QtAws::IAM::IamClient::getUser (const GetUserRequest & request) slot
Retrieves information about the specified IAM user, including the user's creation date, path, unique ID, and
ARN>
If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID used to sign the request to this
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1978 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserResponse *>(send(request));
 }
getUserPolicy
GetUserPolicyResponse * QtAws::IAM::IamClient::getUserPolicy (const GetUserPolicyRequest & request) slot
Retrieves the specified inline policy document that is embedded in the specified IAM
user> <note>
Policies returned by this API are URL-encoded compliant with RFC 3986. You can use a URL decoding method to convert the policy back to plain JSON text. For example, if you use Java, you can use the decode method of the java.net.URLDecoder utility class in the Java SDK. Other languages and SDKs provide similar
functionality> </note>
An IAM user can also have managed policies attached to it. To retrieve a managed policy document that is attached to a user, use GetPolicy to determine the policy's default version, then use GetPolicyVersion to retrieve the policy
document>
For more information about policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2011 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUserPolicyResponse *>(send(request));
 }
listAccessKeys
ListAccessKeysResponse * QtAws::IAM::IamClient::listAccessKeys (const ListAccessKeysRequest & request) slot
Returns information about the access key IDs associated with the specified IAM user. If there are none, the operation returns an empty
list>
Although each user is limited to a small number of keys, you can still paginate the results using the MaxItems and Marker
parameters>
If the UserName field is not specified, the user name is determined implicitly based on the AWS access key ID used to sign the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
users> <note>
To ensure the security of your AWS account, the secret access key is accessible only during key and user
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2041 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAccessKeysResponse *>(send(request));
 }
listAccountAliases
ListAccountAliasesResponse * QtAws::IAM::IamClient::listAccountAliases (const ListAccountAliasesRequest & request) slot
Lists the account alias associated with the AWS account (Note: you can have only one). For information about using an AWS account alias, see Using an Alias for Your AWS Account ID in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2057 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAccountAliasesResponse *>(send(request));
 }
listAttachedGroupPolicies
ListAttachedGroupPoliciesResponse * QtAws::IAM::IamClient::listAttachedGroupPolicies (const ListAttachedGroupPoliciesRequest & request) slot
Lists all managed policies that are attached to the specified IAM
group>
An IAM group can also have inline policies embedded with it. To list the inline policies for a group, use the ListGroupPolicies API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. You can use the PathPrefix parameter to limit the list of policies to only those matching the specified path prefix. If there are no policies attached to the specified group (or none that match the specified path prefix), the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2085 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAttachedGroupPoliciesResponse *>(send(request));
 }
listAttachedRolePolicies
ListAttachedRolePoliciesResponse * QtAws::IAM::IamClient::listAttachedRolePolicies (const ListAttachedRolePoliciesRequest & request) slot
Lists all managed policies that are attached to the specified IAM
role>
An IAM role can also have inline policies embedded with it. To list the inline policies for a role, use the ListRolePolicies API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. You can use the PathPrefix parameter to limit the list of policies to only those matching the specified path prefix. If there are no policies attached to the specified role (or none that match the specified path prefix), the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2113 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAttachedRolePoliciesResponse *>(send(request));
 }
listAttachedUserPolicies
ListAttachedUserPoliciesResponse * QtAws::IAM::IamClient::listAttachedUserPolicies (const ListAttachedUserPoliciesRequest & request) slot
Lists all managed policies that are attached to the specified IAM
user>
An IAM user can also have inline policies embedded with it. To list the inline policies for a user, use the ListUserPolicies API. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. You can use the PathPrefix parameter to limit the list of policies to only those matching the specified path prefix. If there are no policies attached to the specified group (or none that match the specified path prefix), the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2141 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAttachedUserPoliciesResponse *>(send(request));
 }
listEntitiesForPolicy
ListEntitiesForPolicyResponse * QtAws::IAM::IamClient::listEntitiesForPolicy (const ListEntitiesForPolicyRequest & request) slot
Lists all IAM users, groups, and roles that the specified managed policy is attached
to>
You can use the optional EntityFilter parameter to limit the results to a particular type of entity (users, groups, or roles). For example, to list only the roles that are attached to the specified policy, set EntityFilter to
Role>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2165 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListEntitiesForPolicyResponse *>(send(request));
 }
listGroupPolicies
ListGroupPoliciesResponse * QtAws::IAM::IamClient::listGroupPolicies (const ListGroupPoliciesRequest & request) slot
Lists the names of the inline policies that are embedded in the specified IAM
group>
An IAM group can also have managed policies attached to it. To list the managed policies that are attached to a group, use ListAttachedGroupPolicies. For more information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. If there are no inline policies embedded with the specified group, the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2191 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupPoliciesResponse *>(send(request));
 }
listGroups
ListGroupsResponse * QtAws::IAM::IamClient::listGroups (const ListGroupsRequest & request) slot
Lists the IAM groups that have the specified path
prefix>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2209 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupsResponse *>(send(request));
 }
listGroupsForUser
ListGroupsForUserResponse * QtAws::IAM::IamClient::listGroupsForUser (const ListGroupsForUserRequest & request) slot
Lists the IAM groups that the specified IAM user belongs
to>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2227 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGroupsForUserResponse *>(send(request));
 }
listInstanceProfiles
ListInstanceProfilesResponse * QtAws::IAM::IamClient::listInstanceProfiles (const ListInstanceProfilesRequest & request) slot
Lists the instance profiles that have the specified path prefix. If there are none, the operation returns an empty list. For more information about instance profiles, go to About Instance Profiles>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2247 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstanceProfilesResponse *>(send(request));
 }
listInstanceProfilesForRole
ListInstanceProfilesForRoleResponse * QtAws::IAM::IamClient::listInstanceProfilesForRole (const ListInstanceProfilesForRoleRequest & request) slot
Lists the instance profiles that have the specified associated IAM role. If there are none, the operation returns an empty list. For more information about instance profiles, go to About Instance Profiles>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2267 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstanceProfilesForRoleResponse *>(send(request));
 }
listMFADevices
ListMFADevicesResponse * QtAws::IAM::IamClient::listMFADevices (const ListMFADevicesRequest & request) slot
Lists the MFA devices for an IAM user. If the request includes a IAM user name, then this operation lists all the MFA devices associated with the specified user. If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID signing the request for this
API>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2287 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListMFADevicesResponse *>(send(request));
 }
listOpenIDConnectProviders
ListOpenIDConnectProvidersResponse * QtAws::IAM::IamClient::listOpenIDConnectProviders (const ListOpenIDConnectProvidersRequest & request) slot
Lists information about the IAM OpenID Connect (OIDC) provider resource objects defined in the AWS
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2301 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOpenIDConnectProvidersResponse *>(send(request));
 }
listPolicies
ListPoliciesResponse * QtAws::IAM::IamClient::listPolicies (const ListPoliciesRequest & request) slot
Lists all the managed policies that are available in your AWS account, including your own customer-defined managed policies and all AWS managed
policies>
You can filter the list of policies that is returned using the optional OnlyAttached, Scope, and PathPrefix parameters. For example, to list only the customer managed policies in your AWS account, set Scope to Local. To list only AWS managed policies, set Scope to
AWS>
You can paginate the results using the MaxItems and Marker
parameters>
For more information about managed policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2332 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPoliciesResponse *>(send(request));
 }
listPolicyVersions
ListPolicyVersionsResponse * QtAws::IAM::IamClient::listPolicyVersions (const ListPolicyVersionsRequest & request) slot
Lists information about the versions of the specified managed policy, including the version that is currently set as the policy's default
version>
For more information about managed policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2353 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPolicyVersionsResponse *>(send(request));
 }
listRolePolicies
ListRolePoliciesResponse * QtAws::IAM::IamClient::listRolePolicies (const ListRolePoliciesRequest & request) slot
Lists the names of the inline policies that are embedded in the specified IAM
role>
An IAM role can also have managed policies attached to it. To list the managed policies that are attached to a role, use ListAttachedRolePolicies. For more information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. If there are no inline policies embedded with the specified role, the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2379 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRolePoliciesResponse *>(send(request));
 }
listRoles
ListRolesResponse * QtAws::IAM::IamClient::listRoles (const ListRolesRequest & request) slot
Lists the IAM roles that have the specified path prefix. If there are none, the operation returns an empty list. For more information about roles, go to Working with Roles>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2399 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRolesResponse *>(send(request));
 }
listSAMLProviders
ListSAMLProvidersResponse * QtAws::IAM::IamClient::listSAMLProviders (const ListSAMLProvidersRequest & request) slot
Lists the SAML provider resource objects defined in IAM in the
account> <note>
This operation requires Signature Version request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2418 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSAMLProvidersResponse *>(send(request));
 }
listServerCertificates
ListServerCertificatesResponse * QtAws::IAM::IamClient::listServerCertificates (const ListServerCertificatesRequest & request) slot
Lists the server certificates stored in IAM that have the specified path prefix. If none exist, the operation returns an empty
list>
You can paginate the results using the MaxItems and Marker
parameters>
For more information about working with server certificates, see Working with Server Certificates in the IAM User Guide. This topic also includes a list of AWS services that can use the server certificates that you manage with
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2471 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListServerCertificatesResponse *>(send(request));
 }
listServiceSpecificCredentials
ListServiceSpecificCredentialsResponse * QtAws::IAM::IamClient::listServiceSpecificCredentials (const ListServiceSpecificCredentialsRequest & request) slot
Returns information about the service-specific credentials associated with the specified IAM user. If there are none, the operation returns an empty list. The service-specific credentials returned by this operation are used only for authenticating the IAM user to a specific service. For more information about using service-specific credentials to authenticate to an AWS service, see Set Up service-specific credentials in the AWS CodeCommit User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2490 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListServiceSpecificCredentialsResponse *>(send(request));
 }
listSigningCertificates
ListSigningCertificatesResponse * QtAws::IAM::IamClient::listSigningCertificates (const ListSigningCertificatesRequest & request) slot
Returns information about the signing certificates associated with the specified IAM user. If there are none, the operation returns an empty
list>
Although each user is limited to a small number of signing certificates, you can still paginate the results using the MaxItems and Marker
parameters>
If the UserName field is not specified, the user name is determined implicitly based on the AWS access key ID used to sign the request for this API. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2516 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSigningCertificatesResponse *>(send(request));
 }
listSSHPublicKeys
ListSSHPublicKeysResponse * QtAws::IAM::IamClient::listSSHPublicKeys (const ListSSHPublicKeysRequest & request) slot
Returns information about the SSH public keys associated with the specified IAM user. If there are none, the operation returns an empty
list>
The SSH public keys returned by this operation are used only for authenticating the IAM user to an AWS CodeCommit repository. For more information about using SSH keys to authenticate to an AWS CodeCommit repository, see Set up AWS CodeCommit for SSH Connections in the AWS CodeCommit User
Guide>
Although each user is limited to a small number of keys, you can still paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2445 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSSHPublicKeysResponse *>(send(request));
 }
listUserPolicies
ListUserPoliciesResponse * QtAws::IAM::IamClient::listUserPolicies (const ListUserPoliciesRequest & request) slot
Lists the names of the inline policies embedded in the specified IAM
user>
An IAM user can also have managed policies attached to it. To list the managed policies that are attached to a user, use ListAttachedUserPolicies. For more information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
You can paginate the results using the MaxItems and Marker parameters. If there are no inline policies embedded with the specified user, the operation returns an empty
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2542 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUserPoliciesResponse *>(send(request));
 }
listUsers
ListUsersResponse * QtAws::IAM::IamClient::listUsers (const ListUsersRequest & request) slot
Lists the IAM users that have the specified path prefix. If no path prefix is specified, the operation returns all users in the AWS account. If there are none, the operation returns an empty
list>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2561 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUsersResponse *>(send(request));
 }
listVirtualMFADevices
ListVirtualMFADevicesResponse * QtAws::IAM::IamClient::listVirtualMFADevices (const ListVirtualMFADevicesRequest & request) slot
Lists the virtual MFA devices defined in the AWS account by assignment status. If you do not specify an assignment status, the operation returns a list of all virtual MFA devices. Assignment status can be Assigned, Unassigned, or
Any>
You can paginate the results using the MaxItems and Marker
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2581 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListVirtualMFADevicesResponse *>(send(request));
 }
putGroupPolicy
PutGroupPolicyResponse * QtAws::IAM::IamClient::putGroupPolicy (const PutGroupPolicyRequest & request) slot
Adds or updates an inline policy document that is embedded in the specified IAM
group>
A user can also have managed policies attached to it. To attach a managed policy to a group, use AttachGroupPolicy. To create a new managed policy, use CreatePolicy. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
For information about limits on the number of inline policies that you can embed in a group, see Limitations on IAM Entities in the IAM User
Guide> <note>
Because policy documents can be large, you should use POST rather than GET when calling PutGroupPolicy. For general information about using the Query API with IAM, go to Making Query Requests in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2615 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutGroupPolicyResponse *>(send(request));
 }
putRolePolicy
PutRolePolicyResponse * QtAws::IAM::IamClient::putRolePolicy (const PutRolePolicyRequest & request) slot
Adds or updates an inline policy document that is embedded in the specified IAM
role>
When you embed an inline policy in a role, the inline policy is used as part of the role's access (permissions) policy. The role's trust policy is created at the same time as the role, using CreateRole. You can update a role's trust policy using UpdateAssumeRolePolicy. For more information about IAM roles, go to Using Roles to Delegate Permissions and Federate Identities>
A role can also have a managed policy attached to it. To attach a managed policy to a role, use AttachRolePolicy. To create a new managed policy, use CreatePolicy. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
For information about limits on the number of inline policies that you can embed with a role, see Limitations on IAM Entities in the IAM User
Guide> <note>
Because policy documents can be large, you should use POST rather than GET when calling PutRolePolicy. For general information about using the Query API with IAM, go to Making Query Requests in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2657 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutRolePolicyResponse *>(send(request));
 }
putUserPolicy
PutUserPolicyResponse * QtAws::IAM::IamClient::putUserPolicy (const PutUserPolicyRequest & request) slot
Adds or updates an inline policy document that is embedded in the specified IAM
user>
An IAM user can also have a managed policy attached to it. To attach a managed policy to a user, use AttachUserPolicy. To create a new managed policy, use CreatePolicy. For information about policies, see Managed Policies and Inline Policies in the IAM User
Guide>
For information about limits on the number of inline policies that you can embed in a user, see Limitations on IAM Entities in the IAM User
Guide> <note>
Because policy documents can be large, you should use POST rather than GET when calling PutUserPolicy. For general information about using the Query API with IAM, go to Making Query Requests in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2691 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutUserPolicyResponse *>(send(request));
 }
removeClientIDFromOpenIDConnectProvider
RemoveClientIDFromOpenIDConnectProviderResponse * QtAws::IAM::IamClient::removeClientIDFromOpenIDConnectProvider (const RemoveClientIDFromOpenIDConnectProviderRequest & request) slot
Removes the specified client ID (also known as audience) from the list of client IDs registered for the specified IAM OpenID Connect (OIDC) provider resource
object>
This operation is idempotent; it does not fail or return an error if you try to remove a client ID that does not
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2710 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveClientIDFromOpenIDConnectProviderResponse *>(send(request));
 }
removeRoleFromInstanceProfile
RemoveRoleFromInstanceProfileResponse * QtAws::IAM::IamClient::removeRoleFromInstanceProfile (const RemoveRoleFromInstanceProfileRequest & request) slot
Removes the specified IAM role from the specified EC2 instance
profile>
Make sure that you do not have any Amazon EC2 instances running with the role you are about to remove from the instance profile. Removing a role from an instance profile that is associated with a running instance might break any applications running on the
instance>
For more information about IAM roles, go to Working with Roles. For more information about instance profiles, go to About Instance request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2737 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveRoleFromInstanceProfileResponse *>(send(request));
 }
removeUserFromGroup
RemoveUserFromGroupResponse * QtAws::IAM::IamClient::removeUserFromGroup (const RemoveUserFromGroupRequest & request) slot
Removes the specified user from the specified
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2751 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveUserFromGroupResponse *>(send(request));
 }
resetServiceSpecificCredential
ResetServiceSpecificCredentialResponse * QtAws::IAM::IamClient::resetServiceSpecificCredential (const ResetServiceSpecificCredentialRequest & request) slot
Resets the password for a service-specific credential. The new password is AWS generated and cryptographically strong. It cannot be configured by the user. Resetting the password immediately invalidates the previous password associated with this
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2767 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResetServiceSpecificCredentialResponse *>(send(request));
 }
resyncMFADevice
ResyncMFADeviceResponse * QtAws::IAM::IamClient::resyncMFADevice (const ResyncMFADeviceRequest & request) slot
Synchronizes the specified MFA device with its IAM resource object on the AWS
servers>
For more information about creating and working with virtual MFA devices, go to Using a Virtual MFA Device in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2787 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResyncMFADeviceResponse *>(send(request));
 }
setDefaultPolicyVersion
SetDefaultPolicyVersionResponse * QtAws::IAM::IamClient::setDefaultPolicyVersion (const SetDefaultPolicyVersionRequest & request) slot
Sets the specified version of the specified policy as the policy's default (operative)
version>
This operation affects all users, groups, and roles that the policy is attached to. To list the users, groups, and roles that the policy is attached to, use the ListEntitiesForPolicy
API>
For information about managed policies, see Managed Policies and Inline Policies in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2812 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetDefaultPolicyVersionResponse *>(send(request));
 }
simulateCustomPolicy
SimulateCustomPolicyResponse * QtAws::IAM::IamClient::simulateCustomPolicy (const SimulateCustomPolicyRequest & request) slot
Simulate how a set of IAM policies and optionally a resource-based policy works with a list of API operations and AWS resources to determine the policies' effective permissions. The policies are provided as
strings>
The simulation does not perform the API operations; it only checks the authorization to determine if the simulated policies allow or deny the
operations>
If you want to simulate existing policies attached to an IAM user, group, or role, use SimulatePrincipalPolicy
instead>
Context keys are variables maintained by AWS and its services that provide details about the context of an API query request. You can use the Condition element of an IAM policy to evaluate context keys. To get the list of context keys that the policies require for correct simulation, use
GetContextKeysForCustomPolicy>
If the output is long, you can use MaxItems and Marker parameters to paginate the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2846 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SimulateCustomPolicyResponse *>(send(request));
 }
simulatePrincipalPolicy
SimulatePrincipalPolicyResponse * QtAws::IAM::IamClient::simulatePrincipalPolicy (const SimulatePrincipalPolicyRequest & request) slot
Simulate how a set of IAM policies attached to an IAM entity works with a list of API operations and AWS resources to determine the policies' effective permissions. The entity can be an IAM user, group, or role. If you specify a user, then the simulation also includes all of the policies that are attached to groups that the user belongs
to>
You can optionally include a list of one or more additional policies specified as strings to include in the simulation. If you want to simulate only policies specified as strings, use SimulateCustomPolicy
instead>
You can also optionally include one resource-based policy to be evaluated with each of the resources included in the
simulation>
The simulation does not perform the API operations, it only checks the authorization to determine if the simulated policies allow or deny the
operations>
Note: This API discloses information about the permissions granted to other users. If you do not want users to see other user's permissions, then consider allowing them to use SimulateCustomPolicy
instead>
Context keys are variables maintained by AWS and its services that provide details about the context of an API query request. You can use the Condition element of an IAM policy to evaluate context keys. To get the list of context keys that the policies require for correct simulation, use
GetContextKeysForPrincipalPolicy>
If the output is long, you can use the MaxItems and Marker parameters to paginate the
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2891 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SimulatePrincipalPolicyResponse *>(send(request));
 }
updateAccessKey
UpdateAccessKeyResponse * QtAws::IAM::IamClient::updateAccessKey (const UpdateAccessKeyRequest & request) slot
Changes the status of the specified access key from Active to Inactive, or vice versa. This operation can be used to disable a user's key as part of a key rotation
workflow>
If the UserName field is not specified, the user name is determined implicitly based on the AWS access key ID used to sign the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
users>
For information about rotating keys, see Managing Keys and Certificates in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2918 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAccessKeyResponse *>(send(request));
 }
updateAccountPasswordPolicy
UpdateAccountPasswordPolicyResponse * QtAws::IAM::IamClient::updateAccountPasswordPolicy (const UpdateAccountPasswordPolicyRequest & request) slot
Updates the password policy settings for the AWS
account> <note>
This operation does not support partial updates. No parameters are required, but if you do not specify a parameter, that parameter's value reverts to its default value. See the Request Parameters section for each parameter's default value. Also note that some parameters do not allow the default parameter to be explicitly set. Instead, to invoke the default value, do not include that parameter when you invoke the
operation>
</note>
For more information about using a password policy, see Managing an IAM Password Policy in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2945 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAccountPasswordPolicyResponse *>(send(request));
 }
updateAssumeRolePolicy
UpdateAssumeRolePolicyResponse * QtAws::IAM::IamClient::updateAssumeRolePolicy (const UpdateAssumeRolePolicyRequest & request) slot
Updates the policy that grants an IAM entity permission to assume a role. This is typically referred to as the "role trust policy". For more information about roles, go to Using Roles to Delegate Permissions and Federate request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2962 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAssumeRolePolicyResponse *>(send(request));
 }
updateGroup
UpdateGroupResponse * QtAws::IAM::IamClient::updateGroup (const UpdateGroupRequest & request) slot
Updates the name and/or the path of the specified IAM
group>
You should understand the implications of changing a group's path or name. For more information, see Renaming Users and Groups in the IAM User
Guide> <note>
The person making the request (the principal), must have permission to change the role group with the old name and the new name. For example, to change the group named Managers to MGRs, the principal must have a policy that allows them to update both groups. If the principal has permission to update the Managers group, but not the MGRs group, then the update fails. For more information about permissions, see Access Management.
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2990 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGroupResponse *>(send(request));
 }
updateLoginProfile
UpdateLoginProfileResponse * QtAws::IAM::IamClient::updateLoginProfile (const UpdateLoginProfileRequest & request) slot
Changes the password for the specified IAM
user>
IAM users can change their own passwords by calling ChangePassword. For more information about modifying passwords, see Managing Passwords in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3010 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateLoginProfileResponse *>(send(request));
 }
updateOpenIDConnectProviderThumbprint
UpdateOpenIDConnectProviderThumbprintResponse * QtAws::IAM::IamClient::updateOpenIDConnectProviderThumbprint (const UpdateOpenIDConnectProviderThumbprintRequest & request) slot
Replaces the existing list of server certificate thumbprints associated with an OpenID Connect (OIDC) provider resource object with a new list of
thumbprints>
The list that you pass with this operation completely replaces the existing list of thumbprints. (The lists are not
merged.>
Typically, you need to update a thumbprint only when the identity provider's certificate changes, which occurs rarely. However, if the provider's certificate does change, any attempt to assume an IAM role that specifies the OIDC provider as a principal fails until the certificate thumbprint is
updated> <note>
Because trust for the OIDC provider is derived from the provider's certificate and is validated by the thumbprint, it is best to limit access to the UpdateOpenIDConnectProviderThumbprint operation to highly privileged
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3040 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateOpenIDConnectProviderThumbprintResponse *>(send(request));
 }
updateRole
UpdateRoleResponse * QtAws::IAM::IamClient::updateRole (const UpdateRoleRequest & request) slot
Updates the description or maximum session duration setting of a
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3054 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRoleResponse *>(send(request));
 }
updateRoleDescription
UpdateRoleDescriptionResponse * QtAws::IAM::IamClient::updateRoleDescription (const UpdateRoleDescriptionRequest & request) slot
Use
instead>
Modifies only the description of a role. This operation performs the same function as the Description parameter in the UpdateRole
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3073 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRoleDescriptionResponse *>(send(request));
 }
updateSAMLProvider
UpdateSAMLProviderResponse * QtAws::IAM::IamClient::updateSAMLProvider (const UpdateSAMLProviderRequest & request) slot
Updates the metadata document for an existing SAML provider resource
object> <note>
This operation requires Signature Version request Request to send to AWS Identity and Access Management. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 3092 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSAMLProviderResponse *>(send(request));
 }
updateServerCertificate
UpdateServerCertificateResponse * QtAws::IAM::IamClient::updateServerCertificate (const UpdateServerCertificateRequest & request) slot
Updates the name and/or the path of the specified server certificate stored in
IAM>
For more information about working with server certificates, see Working with Server Certificates in the IAM User Guide. This topic also includes a list of AWS services that can use the server certificates that you manage with
IAM>
You should understand the implications of changing a server certificate's path or name. For more information, see Renaming a Server Certificate in the IAM User
Guide> <note>
The person making the request (the principal), must have permission to change the server certificate with the old name and the new name. For example, to change the certificate named ProductionCert to ProdCert, the principal must have a policy that allows them to update both certificates. If the principal has permission to update the ProductionCert group, but not the ProdCert certificate, then the update fails. For more information about permissions, see Access Management in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3150 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateServerCertificateResponse *>(send(request));
 }
updateServiceSpecificCredential
UpdateServiceSpecificCredentialResponse * QtAws::IAM::IamClient::updateServiceSpecificCredential (const UpdateServiceSpecificCredentialRequest & request) slot
Sets the status of a service-specific credential to Active or Inactive. Service-specific credentials that are inactive cannot be used for authentication to the service. This operation can be used to disable a users service-specific credential as part of a credential rotation work
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3166 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateServiceSpecificCredentialResponse *>(send(request));
 }
updateSigningCertificate
UpdateSigningCertificateResponse * QtAws::IAM::IamClient::updateSigningCertificate (const UpdateSigningCertificateRequest & request) slot
Changes the status of the specified user signing certificate from active to disabled, or vice versa. This operation can be used to disable an IAM user's signing certificate as part of a certificate rotation work
flow>
If the UserName field is not specified, the user name is determined implicitly based on the AWS access key ID used to sign the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3187 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSigningCertificateResponse *>(send(request));
 }
updateSSHPublicKey
UpdateSSHPublicKeyResponse * QtAws::IAM::IamClient::updateSSHPublicKey (const UpdateSSHPublicKeyRequest & request) slot
Sets the status of an IAM user's SSH public key to active or inactive. SSH public keys that are inactive cannot be used for authentication. This operation can be used to disable a user's SSH public key as part of a key rotation work
flow>
The SSH public key affected by this operation is used only for authenticating the associated IAM user to an AWS CodeCommit repository. For more information about using SSH keys to authenticate to an AWS CodeCommit repository, see Set up AWS CodeCommit for SSH Connections in the AWS CodeCommit User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3114 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSSHPublicKeyResponse *>(send(request));
 }
updateUser
UpdateUserResponse * QtAws::IAM::IamClient::updateUser (const UpdateUserRequest & request) slot
Updates the name and/or the path of the specified IAM
user>
You should understand the implications of changing an IAM user's path or name. For more information, see Renaming an IAM User and Renaming an IAM Group in the IAM User
Guide> <note>
To change a user name, the requester must have appropriate permissions on both the source object and the target object. For example, to change Bob to Robert, the entity making the request must have permission on Bob and Robert, or must have permission on all (*). For more information about permissions, see Permissions and Policies.
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3215 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserResponse *>(send(request));
 }
uploadServerCertificate
UploadServerCertificateResponse * QtAws::IAM::IamClient::uploadServerCertificate (const UploadServerCertificateRequest & request) slot
Uploads a server certificate entity for the AWS account. The server certificate entity includes a public key certificate, a private key, and an optional certificate chain, which should all be
PEM-encoded>
We recommend that you use AWS Certificate Manager to provision, manage, and deploy your server certificates. With ACM you can request a certificate, deploy it to AWS resources, and let ACM handle certificate renewals for you. Certificates provided by ACM are free. For more information about using ACM, see the AWS Certificate Manager User Guide>
For more information about working with server certificates, see Working with Server Certificates in the IAM User Guide. This topic includes a list of AWS services that can use the server certificates that you manage with
IAM>
For information about the number of server certificates you can upload, see Limitations on IAM Entities and Objects in the IAM User
Guide> <note>
Because the body of the public key certificate, private key, and the certificate chain can be large, you should use POST rather than GET when calling UploadServerCertificate. For information about setting up signatures and authorization through the API, go to Signing AWS API Requests in the AWS General Reference. For general information about using the Query API with IAM, go to Calling the API by Making HTTP Query Requests in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3281 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadServerCertificateResponse *>(send(request));
 }
uploadSigningCertificate
UploadSigningCertificateResponse * QtAws::IAM::IamClient::uploadSigningCertificate (const UploadSigningCertificateRequest & request) slot
Uploads an X.509 signing certificate and associates it with the specified IAM user. Some AWS services use X.509 signing certificates to validate requests that are signed with a corresponding private key. When you upload the certificate, its default status is
Active>
If the UserName field is not specified, the IAM user name is determined implicitly based on the AWS access key ID used to sign the request. Because this operation works for access keys under the AWS account, you can use this operation to manage AWS account root user credentials even if the AWS account has no associated
users> <note>
Because the body of an X.509 certificate can be large, you should use POST rather than GET when calling UploadSigningCertificate. For information about setting up signatures and authorization through the API, go to Signing AWS API Requests in the AWS General Reference. For general information about using the Query API with IAM, go to Making Query Requests in the IAM User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3312 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadSigningCertificateResponse *>(send(request));
 }
uploadSSHPublicKey
UploadSSHPublicKeyResponse * QtAws::IAM::IamClient::uploadSSHPublicKey (const UploadSSHPublicKeyRequest & request) slot
Uploads an SSH public key and associates it with the specified IAM
user>
The SSH public key uploaded by this operation can be used only for authenticating the associated IAM user to an AWS CodeCommit repository. For more information about using SSH keys to authenticate to an AWS CodeCommit repository, see Set up AWS CodeCommit for SSH Connections in the AWS CodeCommit User
Parameters
request Request to send to AWS Identity and Access Management.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 3236 of file iamclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadSSHPublicKeyResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
iam/iamclient.h
iam/iamclient.cpp