AWS SDK for Qt: QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest Class Reference
QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest Class Reference
Interface class for providing ApplicationDiscoveryService requests.
Public Types
enum Action {
AssociateConfigurationItemsToApplicationAction, CreateApplicationAction, CreateTagsAction, DeleteApplicationsAction,
DeleteTagsAction, DescribeAgentsAction, DescribeConfigurationsAction, DescribeExportConfigurationsAction,
DescribeExportTasksAction, DescribeTagsAction, DisassociateConfigurationItemsFromApplicationAction, ExportConfigurationsAction,
GetDiscoverySummaryAction, ListConfigurationsAction, ListServerNeighborsAction, StartDataCollectionByAgentIdsAction,
StartExportTaskAction, StopDataCollectionByAgentIdsAction, UpdateApplicationAction
}
Actions supported by ApplicationDiscoveryService.
Public Member Functions
ApplicationDiscoveryServiceRequest (const Action action)
Constructs a new ApplicationDiscoveryServiceRequest object.
ApplicationDiscoveryServiceRequest (const ApplicationDiscoveryServiceRequest &other)
Constructs a new ApplicationDiscoveryServiceRequest object by copying another.
ApplicationDiscoveryServiceRequest & operator= (const ApplicationDiscoveryServiceRequest &other)
Assignment operator.
Action action () const
Get the ApplicationDiscoveryService action to be performed by this request.
QString actionString () const
Get the name of the ApplicationDiscoveryService action to be performed by this request.
QString apiVersion () const
Get the ApplicationDiscoveryService API version implemented by this request.
void setAction (const Action action)
Set the ApplicationDiscoveryService action to be performed by this request.
void setApiVersion (const QString &version)
Set the ApplicationDiscoveryService API version to include in this request.
virtual bool operator== (const ApplicationDiscoveryServiceRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
ApplicationDiscoveryServiceRequest (ApplicationDiscoveryServiceRequestPrivate *const d)
Constructs a new ApplicationDiscoveryServiceRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid ApplicationDiscoveryService queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this ApplicationDiscoveryService request.
const QVariantMap & parameters () const
Get all parameters included with this ApplicationDiscoveryService request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this ApplicationDiscoveryService request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this ApplicationDiscoveryService request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this ApplicationDiscoveryService request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing ApplicationDiscoveryService requests.
Definition at line 35 of file applicationdiscoveryservicerequest.h.
Constructor & Destructor Documentation
ApplicationDiscoveryServiceRequest() [1/3]
QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::ApplicationDiscoveryServiceRequest (const Action action)
Constructs a new ApplicationDiscoveryServiceRequest object.
Parameters
action The ApplicationDiscoveryService action to request.
Definition at line 38 of file applicationdiscoveryservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new ApplicationDiscoveryServiceRequestPrivate(action, this))
 {
 }
ApplicationDiscoveryServiceRequest() [2/3]
QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::ApplicationDiscoveryServiceRequest (const ApplicationDiscoveryServiceRequest & other)
Constructs a new ApplicationDiscoveryServiceRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file applicationdiscoveryservicerequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new ApplicationDiscoveryServiceRequestPrivate(*other.d_func(), this))
 {
 }
ApplicationDiscoveryServiceRequest() [3/3]
QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::ApplicationDiscoveryServiceRequest (ApplicationDiscoveryServiceRequestPrivate *const d) protected
Constructs a new ApplicationDiscoveryServiceRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from ApplicationDiscoveryServiceRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file applicationdiscoveryservicerequest.cpp.
                                                                                                                           : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
ApplicationDiscoveryServiceRequest::Action QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::action () const
Get the ApplicationDiscoveryService action to be performed by this request.
Returns
The ApplicationDiscoveryService action to be performed by this request.
Definition at line 93 of file applicationdiscoveryservicerequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const ApplicationDiscoveryServiceRequest);
     return d->action;
 }
actionString()
QString QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::actionString () const
Get the name of the ApplicationDiscoveryService action to be performed by this request.
Returns
The name of the ApplicationDiscoveryService action to be performed by this request.
Definition at line 104 of file applicationdiscoveryservicerequest.cpp.
References action(), and QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequestPrivate::toString().
 {
     return ApplicationDiscoveryServiceRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::apiVersion () const
Get the ApplicationDiscoveryService API version implemented by this request.
Returns
The ApplicationDiscoveryService API version implmented by this request.
Definition at line 114 of file applicationdiscoveryservicerequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const ApplicationDiscoveryServiceRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::clearParameter (const QString & name) protected
Check if queueName is a valid ApplicationDiscoveryService queue name.
From ApplicationDiscoveryService FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid ApplicationDiscoveryService queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file applicationdiscoveryservicerequest.cpp.
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     return d->parameters.remove(name);
 }
operator=()
ApplicationDiscoveryServiceRequest & QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::operator= (const ApplicationDiscoveryServiceRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file applicationdiscoveryservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::operator== (const ApplicationDiscoveryServiceRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file applicationdiscoveryservicerequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this ApplicationDiscoveryService request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file applicationdiscoveryservicerequest.cpp.
 {
     Q_D(const ApplicationDiscoveryServiceRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::parameters () const protected
Get all parameters included with this ApplicationDiscoveryService request.
Returns
A map of parameters included with this request.
Definition at line 222 of file applicationdiscoveryservicerequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const ApplicationDiscoveryServiceRequest);
     return d->parameters;
 }
setAction()
void QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::setAction (const Action action)
Set the ApplicationDiscoveryService action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file applicationdiscoveryservicerequest.cpp.
References action().
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::setApiVersion (const QString & version)
Set the ApplicationDiscoveryService API version to include in this request.
Parameters
version The ApplicationDiscoveryService API version to include in this request.
Definition at line 136 of file applicationdiscoveryservicerequest.cpp.
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this ApplicationDiscoveryService request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file applicationdiscoveryservicerequest.cpp.
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this ApplicationDiscoveryService request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file applicationdiscoveryservicerequest.cpp.
References parameters().
 {
     Q_D(ApplicationDiscoveryServiceRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this ApplicationDiscoveryService request.
This ApplicationDiscoveryService implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this ApplicationDiscoveryService request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file applicationdiscoveryservicerequest.cpp.
 {
     Q_D(const ApplicationDiscoveryServiceRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
discovery/applicationdiscoveryservicerequest.h
discovery/applicationdiscoveryservicerequest.cpp