AWS SDK for Qt: QtAws::WorkDocs::WorkDocsClient Class Reference
QtAws::WorkDocs::WorkDocsClient Class Reference
Client for Amazon WorkDocs.
Public Slots
AbortDocumentVersionUploadResponse * abortDocumentVersionUpload (const AbortDocumentVersionUploadRequest &request)
ActivateUserResponse * activateUser (const ActivateUserRequest &request)
AddResourcePermissionsResponse * addResourcePermissions (const AddResourcePermissionsRequest &request)
CreateCommentResponse * createComment (const CreateCommentRequest &request)
CreateCustomMetadataResponse * createCustomMetadata (const CreateCustomMetadataRequest &request)
CreateFolderResponse * createFolder (const CreateFolderRequest &request)
CreateLabelsResponse * createLabels (const CreateLabelsRequest &request)
CreateNotificationSubscriptionResponse * createNotificationSubscription (const CreateNotificationSubscriptionRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeactivateUserResponse * deactivateUser (const DeactivateUserRequest &request)
DeleteCommentResponse * deleteComment (const DeleteCommentRequest &request)
DeleteCustomMetadataResponse * deleteCustomMetadata (const DeleteCustomMetadataRequest &request)
DeleteDocumentResponse * deleteDocument (const DeleteDocumentRequest &request)
DeleteFolderResponse * deleteFolder (const DeleteFolderRequest &request)
DeleteFolderContentsResponse * deleteFolderContents (const DeleteFolderContentsRequest &request)
DeleteLabelsResponse * deleteLabels (const DeleteLabelsRequest &request)
DeleteNotificationSubscriptionResponse * deleteNotificationSubscription (const DeleteNotificationSubscriptionRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DescribeActivitiesResponse * describeActivities (const DescribeActivitiesRequest &request)
DescribeCommentsResponse * describeComments (const DescribeCommentsRequest &request)
DescribeDocumentVersionsResponse * describeDocumentVersions (const DescribeDocumentVersionsRequest &request)
DescribeFolderContentsResponse * describeFolderContents (const DescribeFolderContentsRequest &request)
DescribeGroupsResponse * describeGroups (const DescribeGroupsRequest &request)
DescribeNotificationSubscriptionsResponse * describeNotificationSubscriptions (const DescribeNotificationSubscriptionsRequest &request)
DescribeResourcePermissionsResponse * describeResourcePermissions (const DescribeResourcePermissionsRequest &request)
DescribeRootFoldersResponse * describeRootFolders (const DescribeRootFoldersRequest &request)
DescribeUsersResponse * describeUsers (const DescribeUsersRequest &request)
GetCurrentUserResponse * getCurrentUser (const GetCurrentUserRequest &request)
GetDocumentResponse * getDocument (const GetDocumentRequest &request)
GetDocumentPathResponse * getDocumentPath (const GetDocumentPathRequest &request)
GetDocumentVersionResponse * getDocumentVersion (const GetDocumentVersionRequest &request)
GetFolderResponse * getFolder (const GetFolderRequest &request)
GetFolderPathResponse * getFolderPath (const GetFolderPathRequest &request)
InitiateDocumentVersionUploadResponse * initiateDocumentVersionUpload (const InitiateDocumentVersionUploadRequest &request)
RemoveAllResourcePermissionsResponse * removeAllResourcePermissions (const RemoveAllResourcePermissionsRequest &request)
RemoveResourcePermissionResponse * removeResourcePermission (const RemoveResourcePermissionRequest &request)
UpdateDocumentResponse * updateDocument (const UpdateDocumentRequest &request)
UpdateDocumentVersionResponse * updateDocumentVersion (const UpdateDocumentVersionRequest &request)
UpdateFolderResponse * updateFolder (const UpdateFolderRequest &request)
UpdateUserResponse * updateUser (const UpdateUserRequest &request)
Public Member Functions
WorkDocsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkDocsClient object.
WorkDocsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkDocsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon WorkDocs.
The WorkDocs API is designed for the following use
cases>
File Migration: File migration applications are supported for users who want to migrate their files from an on-premises or off-premises file system or service. Users can insert files into a user directory structure, as well as allow for basic metadata changes, such as modifications to the permissions of
files>
Security: Support security applications are supported for users who have additional security needs, such as antivirus or data loss prevention. The API actions, along with AWS CloudTrail, allow these applications to detect when changes occur in Amazon WorkDocs. Then, the application can take the necessary actions and replace the target file. If the target file violates the policy, the application can also choose to email the
user>
eDiscovery/Analytics: General administrative applications are supported, such as eDiscovery and analytics. These applications can choose to mimic or record the actions in an Amazon WorkDocs site, along with AWS CloudTrail, to replicate data for eDiscovery, backup, or analytical
applications>
All Amazon WorkDocs API actions are Amazon authenticated and certificate-signed. They not only require the use of the AWS SDK, but also allow for the exclusive use of IAM users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the Amazon WorkDocs site, the IAM user gains full administrative visibility into the entire Amazon WorkDocs site (or as set in the IAM policy). This includes, but is not limited to, the ability to modify file permissions and upload any file to any user. This allows developers to perform the three use cases above, as well as give users the ability to grant access on a selective basis using the IAM
Definition at line 112 of file workdocsclient.h.
Constructor & Destructor Documentation
WorkDocsClient() [1/2]
QtAws::WorkDocs::WorkDocsClient::WorkDocsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkDocsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 155 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new WorkDocsClientPrivate(this), parent)
 {
     Q_D(WorkDocsClient);
     d->apiVersion = QStringLiteral("2016-05-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("workdocs");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon WorkDocs");
     d->serviceName = QStringLiteral("workdocs");
 }
WorkDocsClient() [2/2]
QtAws::WorkDocs::WorkDocsClient::WorkDocsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkDocsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 188 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new WorkDocsClientPrivate(this), parent)
 {
     Q_D(WorkDocsClient);
     d->apiVersion = QStringLiteral("2016-05-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("workdocs");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon WorkDocs");
     d->serviceName = QStringLiteral("workdocs");
 }
Member Function Documentation
abortDocumentVersionUpload
AbortDocumentVersionUploadResponse * QtAws::WorkDocs::WorkDocsClient::abortDocumentVersionUpload (const AbortDocumentVersionUploadRequest & request) slot
Aborts the upload of the specified document version that was previously initiated by InitiateDocumentVersionUpload. The client should make this call only when it no longer intends to upload the document version, or fails to do
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AbortDocumentVersionUploadResponse *>(send(request));
 }
activateUser
ActivateUserResponse * QtAws::WorkDocs::WorkDocsClient::activateUser (const ActivateUserRequest & request) slot
Activates the specified user. Only active users can access Amazon
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 230 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ActivateUserResponse *>(send(request));
 }
addResourcePermissions
AddResourcePermissionsResponse * QtAws::WorkDocs::WorkDocsClient::addResourcePermissions (const AddResourcePermissionsRequest & request) slot
Creates a set of permissions for the specified folder or document. The resource permissions are overwritten if the principals already have different
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddResourcePermissionsResponse *>(send(request));
 }
createComment
CreateCommentResponse * QtAws::WorkDocs::WorkDocsClient::createComment (const CreateCommentRequest & request) slot
Adds a new comment to the specified document
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCommentResponse *>(send(request));
 }
createCustomMetadata
CreateCustomMetadataResponse * QtAws::WorkDocs::WorkDocsClient::createCustomMetadata (const CreateCustomMetadataRequest & request) slot
Adds one or more custom properties to the specified resource (a folder, document, or
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCustomMetadataResponse *>(send(request));
 }
createFolder
CreateFolderResponse * QtAws::WorkDocs::WorkDocsClient::createFolder (const CreateFolderRequest & request) slot
Creates a folder with the specified name and parent
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 287 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateFolderResponse *>(send(request));
 }
createLabels
CreateLabelsResponse * QtAws::WorkDocs::WorkDocsClient::createLabels (const CreateLabelsRequest & request) slot
Adds the specified list of labels to the given resource (a document or
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 301 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLabelsResponse *>(send(request));
 }
createNotificationSubscription
CreateNotificationSubscriptionResponse * QtAws::WorkDocs::WorkDocsClient::createNotificationSubscription (const CreateNotificationSubscriptionRequest & request) slot
Configure WorkDocs to use Amazon SNS
notifications>
The endpoint receives a confirmation message, and must confirm the subscription. For more information, see Confirm the Subscription in the Amazon Simple Notification Service Developer
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 321 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNotificationSubscriptionResponse *>(send(request));
 }
createUser
CreateUserResponse * QtAws::WorkDocs::WorkDocsClient::createUser (const CreateUserRequest & request) slot
Creates a user in a Simple AD or Microsoft AD directory. The status of a newly created user is "ACTIVE". New users can access Amazon
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 336 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserResponse *>(send(request));
 }
deactivateUser
DeactivateUserResponse * QtAws::WorkDocs::WorkDocsClient::deactivateUser (const DeactivateUserRequest & request) slot
Deactivates the specified user, which revokes the user's access to Amazon
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 350 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeactivateUserResponse *>(send(request));
 }
deleteComment
DeleteCommentResponse * QtAws::WorkDocs::WorkDocsClient::deleteComment (const DeleteCommentRequest & request) slot
Deletes the specified comment from the document
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 364 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCommentResponse *>(send(request));
 }
deleteCustomMetadata
DeleteCustomMetadataResponse * QtAws::WorkDocs::WorkDocsClient::deleteCustomMetadata (const DeleteCustomMetadataRequest & request) slot
Deletes custom metadata from the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCustomMetadataResponse *>(send(request));
 }
deleteDocument
DeleteDocumentResponse * QtAws::WorkDocs::WorkDocsClient::deleteDocument (const DeleteDocumentRequest & request) slot
Permanently deletes the specified document and its associated
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 392 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDocumentResponse *>(send(request));
 }
deleteFolder
DeleteFolderResponse * QtAws::WorkDocs::WorkDocsClient::deleteFolder (const DeleteFolderRequest & request) slot
Permanently deletes the specified folder and its
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFolderResponse *>(send(request));
 }
deleteFolderContents
DeleteFolderContentsResponse * QtAws::WorkDocs::WorkDocsClient::deleteFolderContents (const DeleteFolderContentsRequest & request) slot
Deletes the contents of the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteFolderContentsResponse *>(send(request));
 }
deleteLabels
DeleteLabelsResponse * QtAws::WorkDocs::WorkDocsClient::deleteLabels (const DeleteLabelsRequest & request) slot
Deletes the specified list of labels from a
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 434 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLabelsResponse *>(send(request));
 }
deleteNotificationSubscription
DeleteNotificationSubscriptionResponse * QtAws::WorkDocs::WorkDocsClient::deleteNotificationSubscription (const DeleteNotificationSubscriptionRequest & request) slot
Deletes the specified subscription from the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 448 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNotificationSubscriptionResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::WorkDocs::WorkDocsClient::deleteUser (const DeleteUserRequest & request) slot
Deletes the specified user from a Simple AD or Microsoft AD
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 462 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
describeActivities
DescribeActivitiesResponse * QtAws::WorkDocs::WorkDocsClient::describeActivities (const DescribeActivitiesRequest & request) slot
Describes the user activities in a specified time
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 476 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeActivitiesResponse *>(send(request));
 }
describeComments
DescribeCommentsResponse * QtAws::WorkDocs::WorkDocsClient::describeComments (const DescribeCommentsRequest & request) slot
List all the comments for the specified document
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 490 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCommentsResponse *>(send(request));
 }
describeDocumentVersions
DescribeDocumentVersionsResponse * QtAws::WorkDocs::WorkDocsClient::describeDocumentVersions (const DescribeDocumentVersionsRequest & request) slot
Retrieves the document versions for the specified
document>
By default, only active versions are
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 508 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDocumentVersionsResponse *>(send(request));
 }
describeFolderContents
DescribeFolderContentsResponse * QtAws::WorkDocs::WorkDocsClient::describeFolderContents (const DescribeFolderContentsRequest & request) slot
Describes the contents of the specified folder, including its documents and
subfolders>
By default, Amazon WorkDocs returns the first 100 active document and folder metadata items. If there are more results, the response includes a marker that you can use to request the next set of results. You can also request initialized
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 527 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeFolderContentsResponse *>(send(request));
 }
describeGroups
DescribeGroupsResponse * QtAws::WorkDocs::WorkDocsClient::describeGroups (const DescribeGroupsRequest & request) slot
Describes the groups specified by
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 541 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeGroupsResponse *>(send(request));
 }
describeNotificationSubscriptions
DescribeNotificationSubscriptionsResponse * QtAws::WorkDocs::WorkDocsClient::describeNotificationSubscriptions (const DescribeNotificationSubscriptionsRequest & request) slot
Lists the specified notification
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 555 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNotificationSubscriptionsResponse *>(send(request));
 }
describeResourcePermissions
DescribeResourcePermissionsResponse * QtAws::WorkDocs::WorkDocsClient::describeResourcePermissions (const DescribeResourcePermissionsRequest & request) slot
Describes the permissions of a specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 569 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeResourcePermissionsResponse *>(send(request));
 }
describeRootFolders
DescribeRootFoldersResponse * QtAws::WorkDocs::WorkDocsClient::describeRootFolders (const DescribeRootFoldersRequest & request) slot
Describes the current user's special folders; the RootFolder and the RecycleBin. RootFolder is the root of user's files and folders and RecycleBin is the root of recycled items. This is not a valid action for SigV4 (administrative API)
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 585 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRootFoldersResponse *>(send(request));
 }
describeUsers
DescribeUsersResponse * QtAws::WorkDocs::WorkDocsClient::describeUsers (const DescribeUsersRequest & request) slot
Describes the specified users. You can describe all users or filter the results (for example, by status or
organization)>
By default, Amazon WorkDocs returns the first 24 active or pending users. If there are more results, the response includes a marker that you can use to request the next set of
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 604 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUsersResponse *>(send(request));
 }
getCurrentUser
GetCurrentUserResponse * QtAws::WorkDocs::WorkDocsClient::getCurrentUser (const GetCurrentUserRequest & request) slot
Retrieves details of the current user for whom the authentication token was generated. This is not a valid action for SigV4 (administrative API)
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 619 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCurrentUserResponse *>(send(request));
 }
getDocument
GetDocumentResponse * QtAws::WorkDocs::WorkDocsClient::getDocument (const GetDocumentRequest & request) slot
Retrieves details of a
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 633 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentResponse *>(send(request));
 }
getDocumentPath
GetDocumentPathResponse * QtAws::WorkDocs::WorkDocsClient::getDocumentPath (const GetDocumentPathRequest & request) slot
Retrieves the path information (the hierarchy from the root folder) for the requested
document>
By default, Amazon WorkDocs returns a maximum of 100 levels upwards from the requested document and only includes the IDs of the parent folders in the path. You can limit the maximum number of levels. You can also request the names of the parent
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 653 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentPathResponse *>(send(request));
 }
getDocumentVersion
GetDocumentVersionResponse * QtAws::WorkDocs::WorkDocsClient::getDocumentVersion (const GetDocumentVersionRequest & request) slot
Retrieves version metadata for the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 667 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDocumentVersionResponse *>(send(request));
 }
getFolder
GetFolderResponse * QtAws::WorkDocs::WorkDocsClient::getFolder (const GetFolderRequest & request) slot
Retrieves the metadata of the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 681 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetFolderResponse *>(send(request));
 }
getFolderPath
GetFolderPathResponse * QtAws::WorkDocs::WorkDocsClient::getFolderPath (const GetFolderPathRequest & request) slot
Retrieves the path information (the hierarchy from the root folder) for the specified
folder>
By default, Amazon WorkDocs returns a maximum of 100 levels upwards from the requested folder and only includes the IDs of the parent folders in the path. You can limit the maximum number of levels. You can also request the parent folder
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 700 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetFolderPathResponse *>(send(request));
 }
initiateDocumentVersionUpload
InitiateDocumentVersionUploadResponse * QtAws::WorkDocs::WorkDocsClient::initiateDocumentVersionUpload (const InitiateDocumentVersionUploadRequest & request) slot
Creates a new document object and version
object>
The client specifies the parent folder ID and name of the document to upload. The ID is optionally specified when creating a new version of an existing document. This is the first step to upload a document. Next, upload the document to the URL returned from the call, and then call
UpdateDocumentVersion>
To cancel the document upload, call
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 724 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InitiateDocumentVersionUploadResponse *>(send(request));
 }
removeAllResourcePermissions
RemoveAllResourcePermissionsResponse * QtAws::WorkDocs::WorkDocsClient::removeAllResourcePermissions (const RemoveAllResourcePermissionsRequest & request) slot
Removes all the permissions from the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 738 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveAllResourcePermissionsResponse *>(send(request));
 }
removeResourcePermission
RemoveResourcePermissionResponse * QtAws::WorkDocs::WorkDocsClient::removeResourcePermission (const RemoveResourcePermissionRequest & request) slot
Removes the permission for the specified principal from the specified
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 752 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveResourcePermissionResponse *>(send(request));
 }
updateDocument
UpdateDocumentResponse * QtAws::WorkDocs::WorkDocsClient::updateDocument (const UpdateDocumentRequest & request) slot
Updates the specified attributes of a document. The user must have access to both the document and its parent folder, if
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 766 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDocumentResponse *>(send(request));
 }
updateDocumentVersion
UpdateDocumentVersionResponse * QtAws::WorkDocs::WorkDocsClient::updateDocumentVersion (const UpdateDocumentVersionRequest & request) slot
Changes the status of the document version to ACTIVE.
</p
Amazon WorkDocs also sets its document container to ACTIVE. This is the last step in a document upload, after the client uploads the document to an S3-presigned URL returned by InitiateDocumentVersionUpload.
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 785 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDocumentVersionResponse *>(send(request));
 }
updateFolder
UpdateFolderResponse * QtAws::WorkDocs::WorkDocsClient::updateFolder (const UpdateFolderRequest & request) slot
Updates the specified attributes of the specified folder. The user must have access to both the folder and its parent folder, if
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 800 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateFolderResponse *>(send(request));
 }
updateUser
UpdateUserResponse * QtAws::WorkDocs::WorkDocsClient::updateUser (const UpdateUserRequest & request) slot
Updates the specified attributes of the specified user, and grants or revokes administrative privileges to the Amazon WorkDocs
Parameters
request Request to send to Amazon WorkDocs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 815 of file workdocsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
workdocs/workdocsclient.h
workdocs/workdocsclient.cpp