AWS SDK for Qt: QtAws::Route53Domains::Route53DomainsClient Class Reference
QtAws::Route53Domains::Route53DomainsClient Class Reference
Client for Amazon Route 53 Domains.
Public Slots
CheckDomainAvailabilityResponse * checkDomainAvailability (const CheckDomainAvailabilityRequest &request)
CheckDomainTransferabilityResponse * checkDomainTransferability (const CheckDomainTransferabilityRequest &request)
DeleteTagsForDomainResponse * deleteTagsForDomain (const DeleteTagsForDomainRequest &request)
DisableDomainAutoRenewResponse * disableDomainAutoRenew (const DisableDomainAutoRenewRequest &request)
DisableDomainTransferLockResponse * disableDomainTransferLock (const DisableDomainTransferLockRequest &request)
EnableDomainAutoRenewResponse * enableDomainAutoRenew (const EnableDomainAutoRenewRequest &request)
EnableDomainTransferLockResponse * enableDomainTransferLock (const EnableDomainTransferLockRequest &request)
GetContactReachabilityStatusResponse * getContactReachabilityStatus (const GetContactReachabilityStatusRequest &request)
GetDomainDetailResponse * getDomainDetail (const GetDomainDetailRequest &request)
GetDomainSuggestionsResponse * getDomainSuggestions (const GetDomainSuggestionsRequest &request)
GetOperationDetailResponse * getOperationDetail (const GetOperationDetailRequest &request)
ListDomainsResponse * listDomains (const ListDomainsRequest &request)
ListOperationsResponse * listOperations (const ListOperationsRequest &request)
ListTagsForDomainResponse * listTagsForDomain (const ListTagsForDomainRequest &request)
RegisterDomainResponse * registerDomain (const RegisterDomainRequest &request)
RenewDomainResponse * renewDomain (const RenewDomainRequest &request)
ResendContactReachabilityEmailResponse * resendContactReachabilityEmail (const ResendContactReachabilityEmailRequest &request)
RetrieveDomainAuthCodeResponse * retrieveDomainAuthCode (const RetrieveDomainAuthCodeRequest &request)
TransferDomainResponse * transferDomain (const TransferDomainRequest &request)
UpdateDomainContactResponse * updateDomainContact (const UpdateDomainContactRequest &request)
UpdateDomainContactPrivacyResponse * updateDomainContactPrivacy (const UpdateDomainContactPrivacyRequest &request)
UpdateDomainNameserversResponse * updateDomainNameservers (const UpdateDomainNameserversRequest &request)
UpdateTagsForDomainResponse * updateTagsForDomain (const UpdateTagsForDomainRequest &request)
ViewBillingResponse * viewBilling (const ViewBillingRequest &request)
Public Member Functions
Route53DomainsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53DomainsClient object.
Route53DomainsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53DomainsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Route 53 Domains.
Amazon Route 53 API actions let you register domain names and perform related
Definition at line 80 of file route53domainsclient.h.
Constructor & Destructor Documentation
Route53DomainsClient() [1/2]
QtAws::Route53Domains::Route53DomainsClient::Route53DomainsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53DomainsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 95 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new Route53DomainsClientPrivate(this), parent)
 {
     Q_D(Route53DomainsClient);
     d->apiVersion = QStringLiteral("2014-05-15");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("route53domains");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Route 53 Domains");
     d->serviceName = QStringLiteral("route53domains");
 }
Route53DomainsClient() [2/2]
QtAws::Route53Domains::Route53DomainsClient::Route53DomainsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53DomainsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 128 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new Route53DomainsClientPrivate(this), parent)
 {
     Q_D(Route53DomainsClient);
     d->apiVersion = QStringLiteral("2014-05-15");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("route53domains");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Route 53 Domains");
     d->serviceName = QStringLiteral("route53domains");
 }
Member Function Documentation
checkDomainAvailability
CheckDomainAvailabilityResponse * QtAws::Route53Domains::Route53DomainsClient::checkDomainAvailability (const CheckDomainAvailabilityRequest & request) slot
This operation checks the availability of one domain name. Note that if the availability status of a domain is pending, you must submit another request to determine the availability of the domain
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 155 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CheckDomainAvailabilityResponse *>(send(request));
 }
checkDomainTransferability
CheckDomainTransferabilityResponse * QtAws::Route53Domains::Route53DomainsClient::checkDomainTransferability (const CheckDomainTransferabilityRequest & request) slot
Checks whether a domain name can be transferred to Amazon Route 53.
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 169 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CheckDomainTransferabilityResponse *>(send(request));
 }
deleteTagsForDomain
DeleteTagsForDomainResponse * QtAws::Route53Domains::Route53DomainsClient::deleteTagsForDomain (const DeleteTagsForDomainRequest & request) slot
This operation deletes the specified tags for a
domain>
All tag operations are eventually consistent; subsequent operations might not immediately represent all issued
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 187 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsForDomainResponse *>(send(request));
 }
disableDomainAutoRenew
DisableDomainAutoRenewResponse * QtAws::Route53Domains::Route53DomainsClient::disableDomainAutoRenew (const DisableDomainAutoRenewRequest & request) slot
This operation disables automatic renewal of domain registration for the specified
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 201 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableDomainAutoRenewResponse *>(send(request));
 }
disableDomainTransferLock
DisableDomainTransferLockResponse * QtAws::Route53Domains::Route53DomainsClient::disableDomainTransferLock (const DisableDomainTransferLockRequest & request) slot
This operation removes the transfer lock on the domain (specifically the clientTransferProhibited status) to allow domain transfers. We recommend you refrain from performing this action unless you intend to transfer the domain to a different registrar. Successful submission returns an operation ID that you can use to track the progress and completion of the action. If the request is not completed successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 218 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableDomainTransferLockResponse *>(send(request));
 }
enableDomainAutoRenew
EnableDomainAutoRenewResponse * QtAws::Route53Domains::Route53DomainsClient::enableDomainAutoRenew (const EnableDomainAutoRenewRequest & request) slot
This operation configures Amazon Route 53 to automatically renew the specified domain before the domain registration expires. The cost of renewing your domain registration is billed to your AWS
account>
The period during which you can renew a domain name varies by TLD. For a list of TLDs and their renewal policies, see "Renewal, restoration, and deletion times" on the website for our registrar partner, Gandi. Route 53 requires that you renew before the end of the renewal period that is listed on the Gandi website so we can complete processing before the
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 240 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableDomainAutoRenewResponse *>(send(request));
 }
enableDomainTransferLock
EnableDomainTransferLockResponse * QtAws::Route53Domains::Route53DomainsClient::enableDomainTransferLock (const EnableDomainTransferLockRequest & request) slot
This operation sets the transfer lock on the domain (specifically the clientTransferProhibited status) to prevent domain transfers. Successful submission returns an operation ID that you can use to track the progress and completion of the action. If the request is not completed successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 256 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableDomainTransferLockResponse *>(send(request));
 }
getContactReachabilityStatus
GetContactReachabilityStatusResponse * QtAws::Route53Domains::Route53DomainsClient::getContactReachabilityStatus (const GetContactReachabilityStatusRequest & request) slot
For operations that require confirmation that the email address for the registrant contact is valid, such as registering a new domain, this operation returns information about whether the registrant contact has
responded>
If you want us to resend the email, use the ResendContactReachabilityEmail
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 275 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetContactReachabilityStatusResponse *>(send(request));
 }
getDomainDetail
GetDomainDetailResponse * QtAws::Route53Domains::Route53DomainsClient::getDomainDetail (const GetDomainDetailRequest & request) slot
This operation returns detailed information about a specified domain that is associated with the current AWS account. Contact information for the domain is also returned as part of the
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 290 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDomainDetailResponse *>(send(request));
 }
getDomainSuggestions
GetDomainSuggestionsResponse * QtAws::Route53Domains::Route53DomainsClient::getDomainSuggestions (const GetDomainSuggestionsRequest & request) slot
The GetDomainSuggestions operation returns a list of suggested domain names given a string, which can either be a domain name or simply a word or phrase (without
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDomainSuggestionsResponse *>(send(request));
 }
getOperationDetail
GetOperationDetailResponse * QtAws::Route53Domains::Route53DomainsClient::getOperationDetail (const GetOperationDetailRequest & request) slot
This operation returns the current status of an operation that is not
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 319 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetOperationDetailResponse *>(send(request));
 }
listDomains
ListDomainsResponse * QtAws::Route53Domains::Route53DomainsClient::listDomains (const ListDomainsRequest & request) slot
This operation returns all the domain names registered with Amazon Route 53 for the current AWS
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 333 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDomainsResponse *>(send(request));
 }
listOperations
ListOperationsResponse * QtAws::Route53Domains::Route53DomainsClient::listOperations (const ListOperationsRequest & request) slot
This operation returns the operation IDs of operations that are not yet
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 347 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOperationsResponse *>(send(request));
 }
listTagsForDomain
ListTagsForDomainResponse * QtAws::Route53Domains::Route53DomainsClient::listTagsForDomain (const ListTagsForDomainRequest & request) slot
This operation returns all of the tags that are associated with the specified
domain>
All tag operations are eventually consistent; subsequent operations might not immediately represent all issued
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 365 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForDomainResponse *>(send(request));
 }
registerDomain
RegisterDomainResponse * QtAws::Route53Domains::Route53DomainsClient::registerDomain (const RegisterDomainRequest & request) slot
This operation registers a domain. Domains are registered by the AWS registrar partner, Gandi. For some top-level domains (TLDs), this operation requires extra
parameters>
When you register a domain, Amazon Route 53 does the
following>
Creates a Amazon Route 53 hosted zone that has the same name as the domain. Amazon Route 53 assigns four name servers to your hosted zone and automatically updates your domain registration with the names of these name
servers>
Enables autorenew, so your domain registration will renew automatically each year. We'll notify you in advance of the renewal date so you can choose whether to renew the
registration>
Optionally enables privacy protection, so WHOIS queries return contact information for our registrar partner, Gandi, instead of the information you entered for registrant, admin, and tech
contacts>
If registration is successful, returns an operation ID that you can use to track the progress and completion of the action. If the request is not completed successfully, the domain registrant is notified by
email>
Charges your AWS account an amount based on the top-level domain. For more information, see Amazon Route 53 request Request to send to Amazon Route 53 Domains. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterDomainResponse *>(send(request));
 }
renewDomain
RenewDomainResponse * QtAws::Route53Domains::Route53DomainsClient::renewDomain (const RenewDomainRequest & request) slot
This operation renews a domain for the specified number of years. The cost of renewing your domain is billed to your AWS
account>
We recommend that you renew your domain several weeks before the expiration date. Some TLD registries delete domains before the expiration date if you haven't renewed far enough in advance. For more information about renewing domain registration, see Renewing Registration for a Domain in the Amazon Route 53 Developer
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 430 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RenewDomainResponse *>(send(request));
 }
resendContactReachabilityEmail
ResendContactReachabilityEmailResponse * QtAws::Route53Domains::Route53DomainsClient::resendContactReachabilityEmail (const ResendContactReachabilityEmailRequest & request) slot
For operations that require confirmation that the email address for the registrant contact is valid, such as registering a new domain, this operation resends the confirmation email to the current email address for the registrant
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 445 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResendContactReachabilityEmailResponse *>(send(request));
 }
retrieveDomainAuthCode
RetrieveDomainAuthCodeResponse * QtAws::Route53Domains::Route53DomainsClient::retrieveDomainAuthCode (const RetrieveDomainAuthCodeRequest & request) slot
This operation returns the AuthCode for the domain. To transfer a domain to another registrar, you provide this value to the new
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 460 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RetrieveDomainAuthCodeResponse *>(send(request));
 }
transferDomain
TransferDomainResponse * QtAws::Route53Domains::Route53DomainsClient::transferDomain (const TransferDomainRequest & request) slot
This operation transfers a domain from another registrar to Amazon Route 53. When the transfer is complete, the domain is registered with the AWS registrar partner,
Gandi>
For transfer requirements, a detailed procedure, and information about viewing the status of a domain transfer, see Transferring Registration for a Domain to Amazon Route 53 in the Amazon Route 53 Developer
Guide>
If the registrar for your domain is also the DNS service provider for the domain, we highly recommend that you consider transferring your DNS service to Amazon Route 53 or to another DNS service provider before you transfer your registration. Some registrars provide free DNS service when you purchase a domain registration. When you transfer the registration, the previous registrar will not renew your domain registration and could end your DNS service at any
time>
If the registrar for your domain is also the DNS service provider for the domain and you don't transfer DNS service to another provider, your website, email, and the web applications associated with the domain might become
unavailable>
If the transfer is successful, this method returns an operation ID that you can use to track the progress and completion of the action. If the transfer doesn't complete successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 498 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TransferDomainResponse *>(send(request));
 }
updateDomainContact
UpdateDomainContactResponse * QtAws::Route53Domains::Route53DomainsClient::updateDomainContact (const UpdateDomainContactRequest & request) slot
This operation updates the contact information for a particular domain. Information for at least one contact (registrant, administrator, or technical) must be supplied for
update>
If the update is successful, this method returns an operation ID that you can use to track the progress and completion of the action. If the request is not completed successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 518 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDomainContactResponse *>(send(request));
 }
updateDomainContactPrivacy
UpdateDomainContactPrivacyResponse * QtAws::Route53Domains::Route53DomainsClient::updateDomainContactPrivacy (const UpdateDomainContactPrivacyRequest & request) slot
This operation updates the specified domain contact's privacy setting. When the privacy option is enabled, personal information such as postal or email address is hidden from the results of a public WHOIS query. The privacy services are provided by the AWS registrar, Gandi. For more information, see the Gandi privacy features>
This operation only affects the privacy of the specified contact type (registrant, administrator, or tech). Successful acceptance returns an operation ID that you can use with GetOperationDetail to track the progress and completion of the action. If the request is not completed successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 541 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDomainContactPrivacyResponse *>(send(request));
 }
updateDomainNameservers
UpdateDomainNameserversResponse * QtAws::Route53Domains::Route53DomainsClient::updateDomainNameservers (const UpdateDomainNameserversRequest & request) slot
This operation replaces the current set of name servers for the domain with the specified set of name servers. If you use Amazon Route 53 as your DNS service, specify the four name servers in the delegation set for the hosted zone for the
domain>
If successful, this operation returns an operation ID that you can use to track the progress and completion of the action. If the request is not completed successfully, the domain registrant will be notified by
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 561 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDomainNameserversResponse *>(send(request));
 }
updateTagsForDomain
UpdateTagsForDomainResponse * QtAws::Route53Domains::Route53DomainsClient::updateTagsForDomain (const UpdateTagsForDomainRequest & request) slot
This operation adds or updates tags for a specified
domain>
All tag operations are eventually consistent; subsequent operations might not immediately represent all issued
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 579 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTagsForDomainResponse *>(send(request));
 }
viewBilling
ViewBillingResponse * QtAws::Route53Domains::Route53DomainsClient::viewBilling (const ViewBillingRequest & request) slot
Returns all the domain-related billing records for the current AWS account for a specified
Parameters
request Request to send to Amazon Route 53 Domains.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 593 of file route53domainsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ViewBillingResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
route53domains/route53domainsclient.h
route53domains/route53domainsclient.cpp