AWS SDK for Qt: QtAws::CodeDeploy::CodeDeployClient Class Reference
QtAws::CodeDeploy::CodeDeployClient Class Reference
Client for AWS CodeDeploy.
Public Slots
AddTagsToOnPremisesInstancesResponse * addTagsToOnPremisesInstances (const AddTagsToOnPremisesInstancesRequest &request)
BatchGetApplicationRevisionsResponse * batchGetApplicationRevisions (const BatchGetApplicationRevisionsRequest &request)
BatchGetApplicationsResponse * batchGetApplications (const BatchGetApplicationsRequest &request)
BatchGetDeploymentGroupsResponse * batchGetDeploymentGroups (const BatchGetDeploymentGroupsRequest &request)
BatchGetDeploymentInstancesResponse * batchGetDeploymentInstances (const BatchGetDeploymentInstancesRequest &request)
BatchGetDeploymentsResponse * batchGetDeployments (const BatchGetDeploymentsRequest &request)
BatchGetOnPremisesInstancesResponse * batchGetOnPremisesInstances (const BatchGetOnPremisesInstancesRequest &request)
ContinueDeploymentResponse * continueDeployment (const ContinueDeploymentRequest &request)
CreateApplicationResponse * createApplication (const CreateApplicationRequest &request)
CreateDeploymentResponse * createDeployment (const CreateDeploymentRequest &request)
CreateDeploymentConfigResponse * createDeploymentConfig (const CreateDeploymentConfigRequest &request)
CreateDeploymentGroupResponse * createDeploymentGroup (const CreateDeploymentGroupRequest &request)
DeleteApplicationResponse * deleteApplication (const DeleteApplicationRequest &request)
DeleteDeploymentConfigResponse * deleteDeploymentConfig (const DeleteDeploymentConfigRequest &request)
DeleteDeploymentGroupResponse * deleteDeploymentGroup (const DeleteDeploymentGroupRequest &request)
DeleteGitHubAccountTokenResponse * deleteGitHubAccountToken (const DeleteGitHubAccountTokenRequest &request)
DeregisterOnPremisesInstanceResponse * deregisterOnPremisesInstance (const DeregisterOnPremisesInstanceRequest &request)
GetApplicationResponse * getApplication (const GetApplicationRequest &request)
GetApplicationRevisionResponse * getApplicationRevision (const GetApplicationRevisionRequest &request)
GetDeploymentResponse * getDeployment (const GetDeploymentRequest &request)
GetDeploymentConfigResponse * getDeploymentConfig (const GetDeploymentConfigRequest &request)
GetDeploymentGroupResponse * getDeploymentGroup (const GetDeploymentGroupRequest &request)
GetDeploymentInstanceResponse * getDeploymentInstance (const GetDeploymentInstanceRequest &request)
GetOnPremisesInstanceResponse * getOnPremisesInstance (const GetOnPremisesInstanceRequest &request)
ListApplicationRevisionsResponse * listApplicationRevisions (const ListApplicationRevisionsRequest &request)
ListApplicationsResponse * listApplications (const ListApplicationsRequest &request)
ListDeploymentConfigsResponse * listDeploymentConfigs (const ListDeploymentConfigsRequest &request)
ListDeploymentGroupsResponse * listDeploymentGroups (const ListDeploymentGroupsRequest &request)
ListDeploymentInstancesResponse * listDeploymentInstances (const ListDeploymentInstancesRequest &request)
ListDeploymentsResponse * listDeployments (const ListDeploymentsRequest &request)
ListGitHubAccountTokenNamesResponse * listGitHubAccountTokenNames (const ListGitHubAccountTokenNamesRequest &request)
ListOnPremisesInstancesResponse * listOnPremisesInstances (const ListOnPremisesInstancesRequest &request)
PutLifecycleEventHookExecutionStatusResponse * putLifecycleEventHookExecutionStatus (const PutLifecycleEventHookExecutionStatusRequest &request)
RegisterApplicationRevisionResponse * registerApplicationRevision (const RegisterApplicationRevisionRequest &request)
RegisterOnPremisesInstanceResponse * registerOnPremisesInstance (const RegisterOnPremisesInstanceRequest &request)
RemoveTagsFromOnPremisesInstancesResponse * removeTagsFromOnPremisesInstances (const RemoveTagsFromOnPremisesInstancesRequest &request)
SkipWaitTimeForInstanceTerminationResponse * skipWaitTimeForInstanceTermination (const SkipWaitTimeForInstanceTerminationRequest &request)
StopDeploymentResponse * stopDeployment (const StopDeploymentRequest &request)
UpdateApplicationResponse * updateApplication (const UpdateApplicationRequest &request)
UpdateDeploymentGroupResponse * updateDeploymentGroup (const UpdateDeploymentGroupRequest &request)
Public Member Functions
CodeDeployClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeDeployClient object.
CodeDeployClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeDeployClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodeDeploy.
<fullname>AWS CodeDeploy</fullname>
AWS CodeDeploy is a deployment service that automates application deployments to Amazon EC2 instances, on-premises instances running in your own facility, or serverless AWS Lambda
functions>
You can deploy a nearly unlimited variety of application content, such as an updated Lambda function, code, web and configuration files, executables, packages, scripts, multimedia files, and so on. AWS CodeDeploy can deploy application content stored in Amazon S3 buckets, GitHub repositories, or Bitbucket repositories. You do not need to make changes to your existing code before you can use AWS
CodeDeploy>
AWS CodeDeploy makes it easier for you to rapidly release new features, helps you avoid downtime during application deployment, and handles the complexity of updating your applications, without many of the risks associated with error-prone manual
deployments>
AWS CodeDeploy Components
Application: A name that uniquely identifies the application you want to deploy. AWS CodeDeploy uses this name, which functions as a container, to ensure the correct combination of revision, deployment configuration, and deployment group are referenced during a
deployment>
Deployment group: A set of individual instances or CodeDeploy Lambda applications. A Lambda deployment group contains a group of applications. An EC2/On-premises deployment group contains individually tagged instances, Amazon EC2 instances in Auto Scaling groups, or both.
</p
Deployment configuration: A set of deployment rules and deployment success and failure conditions used by AWS CodeDeploy during a
deployment>
Deployment: The process and the components used in the process of updating a Lambda function or of installing content on one or more instances.
</p
Application revisions: For an AWS Lambda deployment, this is an AppSpec file that specifies the Lambda function to update and one or more functions to validate deployment lifecycle events. For an EC2/On-premises deployment, this is an archive file containing source contentsource code, web pages, executable files, and deployment scriptsalong with an AppSpec file. Revisions are stored in Amazon S3 buckets or GitHub repositories. For Amazon S3, a revision is uniquely identified by its Amazon S3 object key and its ETag, version, or both. For GitHub, a revision is uniquely identified by its commit
ID>
This guide also contains information to help you get details about the instances in your deployments, to make on-premises instances available for AWS CodeDeploy deployments, and to get details about a Lambda function
deployment>
AWS CodeDeploy Information Resources
</p
AWS CodeDeploy User Guide
</p
AWS CodeDeploy API Reference Guide
</p
AWS CLI Reference for AWS CodeDeploy
</p
AWS CodeDeploy Developer Forum
Definition at line 112 of file codedeployclient.h.
Constructor & Destructor Documentation
CodeDeployClient() [1/2]
QtAws::CodeDeploy::CodeDeployClient::CodeDeployClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeDeployClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 207 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CodeDeployClientPrivate(this), parent)
 {
     Q_D(CodeDeployClient);
     d->apiVersion = QStringLiteral("2014-10-06");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("codedeploy");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CodeDeploy");
     d->serviceName = QStringLiteral("codedeploy");
 }
CodeDeployClient() [2/2]
QtAws::CodeDeploy::CodeDeployClient::CodeDeployClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeDeployClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 240 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CodeDeployClientPrivate(this), parent)
 {
     Q_D(CodeDeployClient);
     d->apiVersion = QStringLiteral("2014-10-06");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("codedeploy");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CodeDeploy");
     d->serviceName = QStringLiteral("codedeploy");
 }
Member Function Documentation
addTagsToOnPremisesInstances
AddTagsToOnPremisesInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::addTagsToOnPremisesInstances (const AddTagsToOnPremisesInstancesRequest & request) slot
Adds tags to on-premises
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 266 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsToOnPremisesInstancesResponse *>(send(request));
 }
batchGetApplicationRevisions
BatchGetApplicationRevisionsResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetApplicationRevisions (const BatchGetApplicationRevisionsRequest & request) slot
Gets information about one or more application
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 280 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetApplicationRevisionsResponse *>(send(request));
 }
batchGetApplications
BatchGetApplicationsResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetApplications (const BatchGetApplicationsRequest & request) slot
Gets information about one or more
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 294 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetApplicationsResponse *>(send(request));
 }
batchGetDeploymentGroups
BatchGetDeploymentGroupsResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetDeploymentGroups (const BatchGetDeploymentGroupsRequest & request) slot
Gets information about one or more deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 308 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetDeploymentGroupsResponse *>(send(request));
 }
batchGetDeploymentInstances
BatchGetDeploymentInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetDeploymentInstances (const BatchGetDeploymentInstancesRequest & request) slot
Gets information about one or more instance that are part of a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 322 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetDeploymentInstancesResponse *>(send(request));
 }
batchGetDeployments
BatchGetDeploymentsResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetDeployments (const BatchGetDeploymentsRequest & request) slot
Gets information about one or more
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 336 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetDeploymentsResponse *>(send(request));
 }
batchGetOnPremisesInstances
BatchGetOnPremisesInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::batchGetOnPremisesInstances (const BatchGetOnPremisesInstancesRequest & request) slot
Gets information about one or more on-premises
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 350 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetOnPremisesInstancesResponse *>(send(request));
 }
continueDeployment
ContinueDeploymentResponse * QtAws::CodeDeploy::CodeDeployClient::continueDeployment (const ContinueDeploymentRequest & request) slot
For a blue/green deployment, starts the process of rerouting traffic from instances in the original environment to instances in the replacement environment without waiting for a specified wait time to elapse. (Traffic rerouting, which is achieved by registering instances in the replacement environment with the load balancer, can start as soon as all instances have a status of Ready.)
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 367 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ContinueDeploymentResponse *>(send(request));
 }
createApplication
CreateApplicationResponse * QtAws::CodeDeploy::CodeDeployClient::createApplication (const CreateApplicationRequest & request) slot
Creates an
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 381 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateApplicationResponse *>(send(request));
 }
createDeployment
CreateDeploymentResponse * QtAws::CodeDeploy::CodeDeployClient::createDeployment (const CreateDeploymentRequest & request) slot
Deploys an application revision through the specified deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDeploymentResponse *>(send(request));
 }
createDeploymentConfig
CreateDeploymentConfigResponse * QtAws::CodeDeploy::CodeDeployClient::createDeploymentConfig (const CreateDeploymentConfigRequest & request) slot
Creates a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDeploymentConfigResponse *>(send(request));
 }
createDeploymentGroup
CreateDeploymentGroupResponse * QtAws::CodeDeploy::CodeDeployClient::createDeploymentGroup (const CreateDeploymentGroupRequest & request) slot
Creates a deployment group to which application revisions will be
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 423 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDeploymentGroupResponse *>(send(request));
 }
deleteApplication
DeleteApplicationResponse * QtAws::CodeDeploy::CodeDeployClient::deleteApplication (const DeleteApplicationRequest & request) slot
Deletes an
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 437 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationResponse *>(send(request));
 }
deleteDeploymentConfig
DeleteDeploymentConfigResponse * QtAws::CodeDeploy::CodeDeployClient::deleteDeploymentConfig (const DeleteDeploymentConfigRequest & request) slot
Deletes a deployment
configuration> <note>
A deployment configuration cannot be deleted if it is currently in use. Predefined configurations cannot be
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 455 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDeploymentConfigResponse *>(send(request));
 }
deleteDeploymentGroup
DeleteDeploymentGroupResponse * QtAws::CodeDeploy::CodeDeployClient::deleteDeploymentGroup (const DeleteDeploymentGroupRequest & request) slot
Deletes a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 469 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDeploymentGroupResponse *>(send(request));
 }
deleteGitHubAccountToken
DeleteGitHubAccountTokenResponse * QtAws::CodeDeploy::CodeDeployClient::deleteGitHubAccountToken (const DeleteGitHubAccountTokenRequest & request) slot
Deletes a GitHub account
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 483 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGitHubAccountTokenResponse *>(send(request));
 }
deregisterOnPremisesInstance
DeregisterOnPremisesInstanceResponse * QtAws::CodeDeploy::CodeDeployClient::deregisterOnPremisesInstance (const DeregisterOnPremisesInstanceRequest & request) slot
Deregisters an on-premises
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 497 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterOnPremisesInstanceResponse *>(send(request));
 }
getApplication
GetApplicationResponse * QtAws::CodeDeploy::CodeDeployClient::getApplication (const GetApplicationRequest & request) slot
Gets information about an
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 511 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApplicationResponse *>(send(request));
 }
getApplicationRevision
GetApplicationRevisionResponse * QtAws::CodeDeploy::CodeDeployClient::getApplicationRevision (const GetApplicationRevisionRequest & request) slot
Gets information about an application
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 525 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetApplicationRevisionResponse *>(send(request));
 }
getDeployment
GetDeploymentResponse * QtAws::CodeDeploy::CodeDeployClient::getDeployment (const GetDeploymentRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 539 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentResponse *>(send(request));
 }
getDeploymentConfig
GetDeploymentConfigResponse * QtAws::CodeDeploy::CodeDeployClient::getDeploymentConfig (const GetDeploymentConfigRequest & request) slot
Gets information about a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 553 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentConfigResponse *>(send(request));
 }
getDeploymentGroup
GetDeploymentGroupResponse * QtAws::CodeDeploy::CodeDeployClient::getDeploymentGroup (const GetDeploymentGroupRequest & request) slot
Gets information about a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 567 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentGroupResponse *>(send(request));
 }
getDeploymentInstance
GetDeploymentInstanceResponse * QtAws::CodeDeploy::CodeDeployClient::getDeploymentInstance (const GetDeploymentInstanceRequest & request) slot
Gets information about an instance as part of a
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 581 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeploymentInstanceResponse *>(send(request));
 }
getOnPremisesInstance
GetOnPremisesInstanceResponse * QtAws::CodeDeploy::CodeDeployClient::getOnPremisesInstance (const GetOnPremisesInstanceRequest & request) slot
Gets information about an on-premises
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 595 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetOnPremisesInstanceResponse *>(send(request));
 }
listApplicationRevisions
ListApplicationRevisionsResponse * QtAws::CodeDeploy::CodeDeployClient::listApplicationRevisions (const ListApplicationRevisionsRequest & request) slot
Lists information about revisions for an
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 609 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListApplicationRevisionsResponse *>(send(request));
 }
listApplications
ListApplicationsResponse * QtAws::CodeDeploy::CodeDeployClient::listApplications (const ListApplicationsRequest & request) slot
Lists the applications registered with the applicable IAM user or AWS
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 623 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListApplicationsResponse *>(send(request));
 }
listDeploymentConfigs
ListDeploymentConfigsResponse * QtAws::CodeDeploy::CodeDeployClient::listDeploymentConfigs (const ListDeploymentConfigsRequest & request) slot
Lists the deployment configurations with the applicable IAM user or AWS
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 637 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDeploymentConfigsResponse *>(send(request));
 }
listDeploymentGroups
ListDeploymentGroupsResponse * QtAws::CodeDeploy::CodeDeployClient::listDeploymentGroups (const ListDeploymentGroupsRequest & request) slot
Lists the deployment groups for an application registered with the applicable IAM user or AWS
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 651 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDeploymentGroupsResponse *>(send(request));
 }
listDeploymentInstances
ListDeploymentInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::listDeploymentInstances (const ListDeploymentInstancesRequest & request) slot
Lists the instance for a deployment associated with the applicable IAM user or AWS
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 665 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDeploymentInstancesResponse *>(send(request));
 }
listDeployments
ListDeploymentsResponse * QtAws::CodeDeploy::CodeDeployClient::listDeployments (const ListDeploymentsRequest & request) slot
Lists the deployments in a deployment group for an application registered with the applicable IAM user or AWS
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 679 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDeploymentsResponse *>(send(request));
 }
listGitHubAccountTokenNames
ListGitHubAccountTokenNamesResponse * QtAws::CodeDeploy::CodeDeployClient::listGitHubAccountTokenNames (const ListGitHubAccountTokenNamesRequest & request) slot
Lists the names of stored connections to GitHub
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 693 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGitHubAccountTokenNamesResponse *>(send(request));
 }
listOnPremisesInstances
ListOnPremisesInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::listOnPremisesInstances (const ListOnPremisesInstancesRequest & request) slot
Gets a list of names for one or more on-premises
instances>
Unless otherwise specified, both registered and deregistered on-premises instance names will be listed. To list only registered or deregistered on-premises instance names, use the registration status
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 712 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOnPremisesInstancesResponse *>(send(request));
 }
putLifecycleEventHookExecutionStatus
PutLifecycleEventHookExecutionStatusResponse * QtAws::CodeDeploy::CodeDeployClient::putLifecycleEventHookExecutionStatus (const PutLifecycleEventHookExecutionStatusRequest & request) slot
Sets the result of a Lambda validation function. The function validates one or both lifecycle events (BeforeAllowTraffic and AfterAllowTraffic) and returns Succeeded or
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 727 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutLifecycleEventHookExecutionStatusResponse *>(send(request));
 }
registerApplicationRevision
RegisterApplicationRevisionResponse * QtAws::CodeDeploy::CodeDeployClient::registerApplicationRevision (const RegisterApplicationRevisionRequest & request) slot
Registers with AWS CodeDeploy a revision for the specified
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 741 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterApplicationRevisionResponse *>(send(request));
 }
registerOnPremisesInstance
RegisterOnPremisesInstanceResponse * QtAws::CodeDeploy::CodeDeployClient::registerOnPremisesInstance (const RegisterOnPremisesInstanceRequest & request) slot
Registers an on-premises
instance> <note>
Only one IAM ARN (an IAM session ARN or IAM user ARN) is supported in the request. You cannot use
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 759 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterOnPremisesInstanceResponse *>(send(request));
 }
removeTagsFromOnPremisesInstances
RemoveTagsFromOnPremisesInstancesResponse * QtAws::CodeDeploy::CodeDeployClient::removeTagsFromOnPremisesInstances (const RemoveTagsFromOnPremisesInstancesRequest & request) slot
Removes one or more tags from one or more on-premises
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 773 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsFromOnPremisesInstancesResponse *>(send(request));
 }
skipWaitTimeForInstanceTermination
SkipWaitTimeForInstanceTerminationResponse * QtAws::CodeDeploy::CodeDeployClient::skipWaitTimeForInstanceTermination (const SkipWaitTimeForInstanceTerminationRequest & request) slot
In a blue/green deployment, overrides any specified wait time and starts terminating instances immediately after the traffic routing is
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 788 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SkipWaitTimeForInstanceTerminationResponse *>(send(request));
 }
stopDeployment
StopDeploymentResponse * QtAws::CodeDeploy::CodeDeployClient::stopDeployment (const StopDeploymentRequest & request) slot
Attempts to stop an ongoing
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 802 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopDeploymentResponse *>(send(request));
 }
updateApplication
UpdateApplicationResponse * QtAws::CodeDeploy::CodeDeployClient::updateApplication (const UpdateApplicationRequest & request) slot
Changes the name of an
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 816 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApplicationResponse *>(send(request));
 }
updateDeploymentGroup
UpdateDeploymentGroupResponse * QtAws::CodeDeploy::CodeDeployClient::updateDeploymentGroup (const UpdateDeploymentGroupRequest & request) slot
Changes information about a deployment
Parameters
request Request to send to AWS CodeDeploy.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 830 of file codedeployclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDeploymentGroupResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
codedeploy/codedeployclient.h
codedeploy/codedeployclient.cpp