AWS SDK for Qt: QtAws::SqsOld::SqsErrorPrivate Class Reference
QtAws::SqsOld::SqsErrorPrivate Class Reference
Private implementation for SqsError.
Public Member Functions
SqsErrorPrivate (SqsError *const q)
Constructs a new SqsErrorPrivate object.
SqsErrorPrivate (const SqsErrorPrivate *const other, SqsError *const q)
Construc an SqsErrorPrivate object by copying another.
virtual ~SqsErrorPrivate ()
SqsErrorPrivate destructor.
void parse (QXmlStreamReader &xml)
Parse an SQS Error element.
Static Public Member Functions
static SqsError::ErrorCode codeFromString (const QString &code)
Convert an SQS error code string to an ErrorCode enum value.
static SqsError::ErrorType typeFromString (const QString &type)
Convert an SQS error type string to an ErrorType enum value.
Public Attributes
SqsError::ErrorCode code
SQS error code.
QVariantMap detail
SQS error detail.
QString message
SQS error message.
QString rawCode
Raw SQS error code.
QString rawType
Raw SQS error type.
SqsError::ErrorType type
SQS error type.
Private Attributes
SqsError *const q_ptr
Internal q-pointer.
Detailed Description
Private implementation for SqsError.
Definition at line 28 of file sqserror_p.h.
Constructor & Destructor Documentation
SqsErrorPrivate() [1/2]
QtAws::SqsOld::SqsErrorPrivate::SqsErrorPrivate (SqsError *const q)
Constructs a new SqsErrorPrivate object.
Parameters
q Pointer to this object's public SqsError instance.
Definition at line 257 of file sqserror.cpp.
     : code(SqsError::OtherError), type(SqsError::OtherType), q_ptr(q)
 {
 }
SqsErrorPrivate() [2/2]
QtAws::SqsOld::SqsErrorPrivate::SqsErrorPrivate (const SqsErrorPrivate *const other, SqsError *const q)
Construc an SqsErrorPrivate object by copying another.
This is a lot like a copy constructor, and exists only to support the SqsError class' copy constructor.
Parameters
other Instance to copy.
q Pointer to this object's public SqsError instance.
Definition at line 274 of file sqserror.cpp.
     : code(other->code), detail(other->detail), message(other->message),
       rawCode(other->rawCode), rawType(other->rawType), type(other->type),
       q_ptr(q)
 {
 }
~SqsErrorPrivate()
QtAws::SqsOld::SqsErrorPrivate::~SqsErrorPrivate () virtual
SqsErrorPrivate destructor.
This virtual destructor does nothing (yet) - its here to allow for safe polymorphic destruction.
Definition at line 288 of file sqserror.cpp.
 {
 }
Member Function Documentation
codeFromString()
SqsError::ErrorCode QtAws::SqsOld::SqsErrorPrivate::codeFromString (const QString & code) static
Convert an SQS error code string to an ErrorCode enum value.
Parameters
code SQS error code.
Returns
ErrorCode equivalent to code, or SqsError::OtherError if not recognised.
Definition at line 343 of file sqserror.cpp.
References code.
Referenced by parse().
 {
     #define IfStringReturnErrorResponse(str) \
         if (code == QLatin1String(#str)) return SqsError::str
     IfStringReturnErrorResponse(AccessDenied);
     IfStringReturnErrorResponse(IncompleteSignature);
     IfStringReturnErrorResponse(InternalFailure);
     IfStringReturnErrorResponse(InvalidAction);
     IfStringReturnErrorResponse(InvalidClientTokenId);
     IfStringReturnErrorResponse(InvalidParameterCombination);
     IfStringReturnErrorResponse(InvalidParameterValue);
     IfStringReturnErrorResponse(InvalidQueryParameter);
     IfStringReturnErrorResponse(MalformedQueryString);
     IfStringReturnErrorResponse(MissingAction);
     IfStringReturnErrorResponse(MissingAuthenticationToken);
     IfStringReturnErrorResponse(MissingParameter);
     IfStringReturnErrorResponse(OptInRequired);
     IfStringReturnErrorResponse(RequestExpired);
     IfStringReturnErrorResponse(ServiceUnavailable);
     IfStringReturnErrorResponse(Throttling);
     IfStringReturnErrorResponse(ValidationError);
     #undef IfStringReturnErrorResponse
     qWarning() << "unknown SQS error code" << code;
     return SqsError::OtherError;
 }
parse()
void QtAws::SqsOld::SqsErrorPrivate::parse (QXmlStreamReader & xml)
Parse an SQS Error element.
This function parses Error XML elements (ie from SQS ErrorResponse elements) as specified in http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<Error>
  <Type>Sender</Type>
  <Code>AccessDenied</Code>
  <Message>Access to the resource http://sqs.us-east-1.amazonaws.com/ is denied.</Message>
  <Detail/>
</Error>
Parameters
xml XML stream to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 314 of file sqserror.cpp.
References code, codeFromString(), detail, message, rawCode, rawType, type, and typeFromString().
 {
     if ((xml.tokenType() == QXmlStreamReader::NoToken) && (!xml.readNextStartElement())) {
         return;
     }
     Q_ASSERT(xml.name() == QLatin1String("Error"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("Type")) {
             type = typeFromString(rawType = xml.readElementText());
         } else if (xml.name() == QLatin1String("Code")) {
             code = codeFromString(rawCode = xml.readElementText());
         } else if (xml.name() == QLatin1String("Message")) {
             message = xml.readElementText();
         } else if (xml.name() == QLatin1String("Detail")) {
             detail = AwsAbstractResponse::toVariant(xml);
         } else {
            qWarning() << "ignoring" << xml.name();
            xml.skipCurrentElement();
         }
     }
 }
typeFromString()
SqsError::ErrorType QtAws::SqsOld::SqsErrorPrivate::typeFromString (const QString & type) static
Convert an SQS error type string to an ErrorType enum value.
Parameters
type SQS error type.
Returns
ErrorType equivalent to type, or SqsError::OtherType if not recognised.
Definition at line 376 of file sqserror.cpp.
References type.
Referenced by parse().
 {
     #define IfStringReturnErrorType(str) \
         if (type == QLatin1String(#str)) return SqsError::str##Type
     IfStringReturnErrorType(Receiver);
     IfStringReturnErrorType(Sender);
     #undef IfStringReturnErrorType
     qWarning() << "unknown SQS error type" << type;
     return SqsError::OtherType;
 }
The documentation for this class was generated from the following files:
sqs-old/sqserror_p.h
sqs-old/sqserror.cpp