AWS SDK for Qt: QtAws::WorkSpaces::WorkSpacesClient Class Reference
QtAws::WorkSpaces::WorkSpacesClient Class Reference
Client for Amazon WorkSpaces.
Public Slots
CreateTagsResponse * createTags (const CreateTagsRequest &request)
CreateWorkspacesResponse * createWorkspaces (const CreateWorkspacesRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeWorkspaceBundlesResponse * describeWorkspaceBundles (const DescribeWorkspaceBundlesRequest &request)
DescribeWorkspaceDirectoriesResponse * describeWorkspaceDirectories (const DescribeWorkspaceDirectoriesRequest &request)
DescribeWorkspacesResponse * describeWorkspaces (const DescribeWorkspacesRequest &request)
DescribeWorkspacesConnectionStatusResponse * describeWorkspacesConnectionStatus (const DescribeWorkspacesConnectionStatusRequest &request)
ModifyWorkspacePropertiesResponse * modifyWorkspaceProperties (const ModifyWorkspacePropertiesRequest &request)
RebootWorkspacesResponse * rebootWorkspaces (const RebootWorkspacesRequest &request)
RebuildWorkspacesResponse * rebuildWorkspaces (const RebuildWorkspacesRequest &request)
StartWorkspacesResponse * startWorkspaces (const StartWorkspacesRequest &request)
StopWorkspacesResponse * stopWorkspaces (const StopWorkspacesRequest &request)
TerminateWorkspacesResponse * terminateWorkspaces (const TerminateWorkspacesRequest &request)
Public Member Functions
WorkSpacesClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkSpacesClient object.
WorkSpacesClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkSpacesClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon WorkSpaces.
<fullname>Amazon WorkSpaces Service</fullname>
Amazon WorkSpaces enables you to provision virtual, cloud-based Microsoft Windows desktops for your
Definition at line 60 of file workspacesclient.h.
Constructor & Destructor Documentation
WorkSpacesClient() [1/2]
QtAws::WorkSpaces::WorkSpacesClient::WorkSpacesClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkSpacesClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 77 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new WorkSpacesClientPrivate(this), parent)
 {
     Q_D(WorkSpacesClient);
     d->apiVersion = QStringLiteral("2015-04-08");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("workspaces");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon WorkSpaces");
     d->serviceName = QStringLiteral("workspaces");
 }
WorkSpacesClient() [2/2]
QtAws::WorkSpaces::WorkSpacesClient::WorkSpacesClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkSpacesClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 110 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new WorkSpacesClientPrivate(this), parent)
 {
     Q_D(WorkSpacesClient);
     d->apiVersion = QStringLiteral("2015-04-08");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("workspaces");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon WorkSpaces");
     d->serviceName = QStringLiteral("workspaces");
 }
Member Function Documentation
createTags
CreateTagsResponse * QtAws::WorkSpaces::WorkSpacesClient::createTags (const CreateTagsRequest & request) slot
Creates tags for the specified
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 136 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTagsResponse *>(send(request));
 }
createWorkspaces
CreateWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::createWorkspaces (const CreateWorkspacesRequest & request) slot
Creates one or more
WorkSpaces>
This operation is asynchronous and returns before the WorkSpaces are
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 154 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateWorkspacesResponse *>(send(request));
 }
deleteTags
DeleteTagsResponse * QtAws::WorkSpaces::WorkSpacesClient::deleteTags (const DeleteTagsRequest & request) slot
Deletes the specified tags from a
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 168 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::WorkSpaces::WorkSpacesClient::describeTags (const DescribeTagsRequest & request) slot
Describes the tags for the specified
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 182 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
describeWorkspaceBundles
DescribeWorkspaceBundlesResponse * QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaceBundles (const DescribeWorkspaceBundlesRequest & request) slot
Describes the available WorkSpace
bundles>
You can filter the results using either bundle ID or owner, but not
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 200 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkspaceBundlesResponse *>(send(request));
 }
describeWorkspaceDirectories
DescribeWorkspaceDirectoriesResponse * QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaceDirectories (const DescribeWorkspaceDirectoriesRequest & request) slot
Describes the available AWS Directory Service directories that are registered with Amazon
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkspaceDirectoriesResponse *>(send(request));
 }
describeWorkspaces
DescribeWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaces (const DescribeWorkspacesRequest & request) slot
Describes the specified
WorkSpaces>
You can filter the results using bundle ID, directory ID, or owner, but you can specify only one filter at a
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 232 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkspacesResponse *>(send(request));
 }
describeWorkspacesConnectionStatus
DescribeWorkspacesConnectionStatusResponse * QtAws::WorkSpaces::WorkSpacesClient::describeWorkspacesConnectionStatus (const DescribeWorkspacesConnectionStatusRequest & request) slot
Describes the connection status of the specified
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 246 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeWorkspacesConnectionStatusResponse *>(send(request));
 }
modifyWorkspaceProperties
ModifyWorkspacePropertiesResponse * QtAws::WorkSpaces::WorkSpacesClient::modifyWorkspaceProperties (const ModifyWorkspacePropertiesRequest & request) slot
Modifies the specified WorkSpace
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 260 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyWorkspacePropertiesResponse *>(send(request));
 }
rebootWorkspaces
RebootWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::rebootWorkspaces (const RebootWorkspacesRequest & request) slot
Reboots the specified
WorkSpaces>
You cannot reboot a WorkSpace unless its state is AVAILABLE, IMPAIRED, or
INOPERABLE>
This operation is asynchronous and returns before the WorkSpaces have
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 282 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootWorkspacesResponse *>(send(request));
 }
rebuildWorkspaces
RebuildWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::rebuildWorkspaces (const RebuildWorkspacesRequest & request) slot
Rebuilds the specified
WorkSpaces>
You cannot rebuild a WorkSpace unless its state is AVAILABLE or
ERROR>
Rebuilding a WorkSpace is a potentially destructive action that can result in the loss of data. For more information, see Rebuild a WorkSpace>
This operation is asynchronous and returns before the WorkSpaces have been completely
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 309 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebuildWorkspacesResponse *>(send(request));
 }
startWorkspaces
StartWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::startWorkspaces (const StartWorkspacesRequest & request) slot
Starts the specified
WorkSpaces>
You cannot start a WorkSpace unless it has a running mode of AutoStop and a state of
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 327 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartWorkspacesResponse *>(send(request));
 }
stopWorkspaces
StopWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::stopWorkspaces (const StopWorkspacesRequest & request) slot
Stops the specified
WorkSpaces>
You cannot stop a WorkSpace unless it has a running mode of AutoStop and a state of AVAILABLE, IMPAIRED, UNHEALTHY, or
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 346 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopWorkspacesResponse *>(send(request));
 }
terminateWorkspaces
TerminateWorkspacesResponse * QtAws::WorkSpaces::WorkSpacesClient::terminateWorkspaces (const TerminateWorkspacesRequest & request) slot
Terminates the specified
WorkSpaces>
Terminating a WorkSpace is a permanent action and cannot be undone. The user's data is destroyed. If you need to archive any user data, contact Amazon Web Services before terminating the
WorkSpace>
You can terminate a WorkSpace that is in any state except
SUSPENDED>
This operation is asynchronous and returns before the WorkSpaces have been completely
Parameters
request Request to send to Amazon WorkSpaces.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 373 of file workspacesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TerminateWorkspacesResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
workspaces/workspacesclient.h
workspaces/workspacesclient.cpp