AWS SDK for Qt: QtAws::MachineLearning::MachineLearningClient Class Reference
QtAws::MachineLearning::MachineLearningClient Class Reference
Client for Amazon Machine Learning.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateBatchPredictionResponse * createBatchPrediction (const CreateBatchPredictionRequest &request)
CreateDataSourceFromRDSResponse * createDataSourceFromRDS (const CreateDataSourceFromRDSRequest &request)
CreateDataSourceFromRedshiftResponse * createDataSourceFromRedshift (const CreateDataSourceFromRedshiftRequest &request)
CreateDataSourceFromS3Response * createDataSourceFromS3 (const CreateDataSourceFromS3Request &request)
CreateEvaluationResponse * createEvaluation (const CreateEvaluationRequest &request)
CreateMLModelResponse * createMLModel (const CreateMLModelRequest &request)
CreateRealtimeEndpointResponse * createRealtimeEndpoint (const CreateRealtimeEndpointRequest &request)
DeleteBatchPredictionResponse * deleteBatchPrediction (const DeleteBatchPredictionRequest &request)
DeleteDataSourceResponse * deleteDataSource (const DeleteDataSourceRequest &request)
DeleteEvaluationResponse * deleteEvaluation (const DeleteEvaluationRequest &request)
DeleteMLModelResponse * deleteMLModel (const DeleteMLModelRequest &request)
DeleteRealtimeEndpointResponse * deleteRealtimeEndpoint (const DeleteRealtimeEndpointRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeBatchPredictionsResponse * describeBatchPredictions (const DescribeBatchPredictionsRequest &request)
DescribeDataSourcesResponse * describeDataSources (const DescribeDataSourcesRequest &request)
DescribeEvaluationsResponse * describeEvaluations (const DescribeEvaluationsRequest &request)
DescribeMLModelsResponse * describeMLModels (const DescribeMLModelsRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
GetBatchPredictionResponse * getBatchPrediction (const GetBatchPredictionRequest &request)
GetDataSourceResponse * getDataSource (const GetDataSourceRequest &request)
GetEvaluationResponse * getEvaluation (const GetEvaluationRequest &request)
GetMLModelResponse * getMLModel (const GetMLModelRequest &request)
PredictResponse * predict (const PredictRequest &request)
UpdateBatchPredictionResponse * updateBatchPrediction (const UpdateBatchPredictionRequest &request)
UpdateDataSourceResponse * updateDataSource (const UpdateDataSourceRequest &request)
UpdateEvaluationResponse * updateEvaluation (const UpdateEvaluationRequest &request)
UpdateMLModelResponse * updateMLModel (const UpdateMLModelRequest &request)
Public Member Functions
MachineLearningClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MachineLearningClient object.
MachineLearningClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MachineLearningClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Machine Learning.
Definition at line 88 of file machinelearningclient.h.
Constructor & Destructor Documentation
MachineLearningClient() [1/2]
QtAws::MachineLearning::MachineLearningClient::MachineLearningClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MachineLearningClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 102 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MachineLearningClientPrivate(this), parent)
 {
     Q_D(MachineLearningClient);
     d->apiVersion = QStringLiteral("2014-12-12");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("machinelearning");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Machine Learning");
     d->serviceName = QStringLiteral("machinelearning");
 }
MachineLearningClient() [2/2]
QtAws::MachineLearning::MachineLearningClient::MachineLearningClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MachineLearningClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 135 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MachineLearningClientPrivate(this), parent)
 {
     Q_D(MachineLearningClient);
     d->apiVersion = QStringLiteral("2014-12-12");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("machinelearning");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Machine Learning");
     d->serviceName = QStringLiteral("machinelearning");
 }
Member Function Documentation
addTags
AddTagsResponse * QtAws::MachineLearning::MachineLearningClient::addTags (const AddTagsRequest & request) slot
Adds one or more tags to an object, up to a limit of 10. Each tag consists of a key and an optional value. If you add a tag using a key that is already associated with the ML object, AddTags updates the tag's
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 162 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
createBatchPrediction
CreateBatchPredictionResponse * QtAws::MachineLearning::MachineLearningClient::createBatchPrediction (const CreateBatchPredictionRequest & request) slot
Generates predictions for a group of observations. The observations to process exist in one or more data files referenced by a DataSource. This operation creates a new BatchPrediction, and uses an MLModel and the data files referenced by the DataSource as information sources.
</p
CreateBatchPrediction is an asynchronous operation. In response to CreateBatchPrediction, Amazon Machine Learning (Amazon ML) immediately returns and sets the BatchPrediction status to PENDING. After the BatchPrediction completes, Amazon ML sets the status to COMPLETED.
</p
You can poll for status updates by using the GetBatchPrediction operation and checking the Status parameter of the result. After the COMPLETED status appears, the results are available in the location specified by the OutputUri
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 191 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBatchPredictionResponse *>(send(request));
 }
createDataSourceFromRDS
CreateDataSourceFromRDSResponse * QtAws::MachineLearning::MachineLearningClient::createDataSourceFromRDS (const CreateDataSourceFromRDSRequest & request) slot
Creates a DataSource object from an Amazon Relational Database Service (Amazon RDS). A DataSource references data that can be used to perform CreateMLModel, CreateEvaluation, or CreateBatchPrediction
operations>
CreateDataSourceFromRDS is an asynchronous operation. In response to CreateDataSourceFromRDS, Amazon Machine Learning (Amazon ML) immediately returns and sets the DataSource status to PENDING. After the DataSource is created and ready for use, Amazon ML sets the Status parameter to COMPLETED. DataSource in the COMPLETED or PENDING state can be used only to perform >CreateMLModel>, CreateEvaluation, or CreateBatchPrediction operations.
</p
If Amazon ML cannot accept the input source, it sets the Status parameter to FAILED and includes an error message in the Message attribute of the GetDataSource operation response.
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 221 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDataSourceFromRDSResponse *>(send(request));
 }
createDataSourceFromRedshift
CreateDataSourceFromRedshiftResponse * QtAws::MachineLearning::MachineLearningClient::createDataSourceFromRedshift (const CreateDataSourceFromRedshiftRequest & request) slot
Creates a DataSource from a database hosted on an Amazon Redshift cluster. A DataSource references data that can be used to perform either CreateMLModel, CreateEvaluation, or CreateBatchPrediction
operations>
CreateDataSourceFromRedshift is an asynchronous operation. In response to CreateDataSourceFromRedshift, Amazon Machine Learning (Amazon ML) immediately returns and sets the DataSource status to PENDING. After the DataSource is created and ready for use, Amazon ML sets the Status parameter to COMPLETED. DataSource in COMPLETED or PENDING states can be used to perform only CreateMLModel, CreateEvaluation, or CreateBatchPrediction operations.
</p
If Amazon ML can't accept the input source, it sets the Status parameter to FAILED and includes an error message in the Message attribute of the GetDataSource operation response.
</p
The observations should be contained in the database hosted on an Amazon Redshift cluster and should be specified by a SelectSqlQuery query. Amazon ML executes an Unload command in Amazon Redshift to transfer the result set of the SelectSqlQuery query to
S3StagingLocation>
After the DataSource has been created, it's ready for use in evaluations and batch predictions. If you plan to use the DataSource to train an MLModel, the DataSource also requires a recipe. A recipe describes how each input variable will be used in training an MLModel. Will the variable be included or excluded from training? Will the variable be manipulated; for example, will it be combined with another variable or will it be split apart into word combinations? The recipe provides answers to these
questions> <?oxy_insert_start author="laurama" timestamp="20160406T153842-0700">
You can't change an existing datasource, but you can copy and modify the settings from an existing Amazon Redshift datasource to create a new datasource. To do so, call GetDataSource for an existing datasource and copy the values to a CreateDataSource call. Change the settings that you want to change and make sure that all required fields have the appropriate
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 271 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDataSourceFromRedshiftResponse *>(send(request));
 }
createDataSourceFromS3
CreateDataSourceFromS3Response * QtAws::MachineLearning::MachineLearningClient::createDataSourceFromS3 (const CreateDataSourceFromS3Request & request) slot
Creates a DataSource object. A DataSource references data that can be used to perform CreateMLModel, CreateEvaluation, or CreateBatchPrediction
operations>
CreateDataSourceFromS3 is an asynchronous operation. In response to CreateDataSourceFromS3, Amazon Machine Learning (Amazon ML) immediately returns and sets the DataSource status to PENDING. After the DataSource has been created and is ready for use, Amazon ML sets the Status parameter to COMPLETED. DataSource in the COMPLETED or PENDING state can be used to perform only CreateMLModel, CreateEvaluation or CreateBatchPrediction operations.
</p
If Amazon ML can't accept the input source, it sets the Status parameter to FAILED and includes an error message in the Message attribute of the GetDataSource operation response.
</p
The observation data used in a DataSource should be ready to use; that is, it should have a consistent structure, and missing data values should be kept to a minimum. The observation data must reside in one or more .csv files in an Amazon Simple Storage Service (Amazon S3) location, along with a schema that describes the data items by name and type. The same schema must be used for all of the data files referenced by the DataSource.
</p
After the DataSource has been created, it's ready to use in evaluations and batch predictions. If you plan to use the DataSource to train an MLModel, the DataSource also needs a recipe. A recipe describes how each input variable will be used in training an MLModel. Will the variable be included or excluded from training? Will the variable be manipulated; for example, will it be combined with another variable or will it be split apart into word combinations? The recipe provides answers to these
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 315 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDataSourceFromS3Response *>(send(request));
 }
createEvaluation
CreateEvaluationResponse * QtAws::MachineLearning::MachineLearningClient::createEvaluation (const CreateEvaluationRequest & request) slot
Creates a new Evaluation of an MLModel. An MLModel is evaluated on a set of observations associated to a DataSource. Like a DataSource for an MLModel, the DataSource for an Evaluation contains values for the Target Variable. The Evaluation compares the predicted result for each observation to the actual outcome and provides a summary so that you know how effective the MLModel functions on the test data. Evaluation generates a relevant performance metric, such as BinaryAUC, RegressionRMSE or MulticlassAvgFScore based on the corresponding MLModelType: BINARY, REGRESSION or MULTICLASS.
</p
CreateEvaluation is an asynchronous operation. In response to CreateEvaluation, Amazon Machine Learning (Amazon ML) immediately returns and sets the evaluation status to PENDING. After the Evaluation is created and ready for use, Amazon ML sets the status to COMPLETED.
</p
You can use the GetEvaluation operation to check progress of the evaluation during the creation
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 345 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEvaluationResponse *>(send(request));
 }
createMLModel
CreateMLModelResponse * QtAws::MachineLearning::MachineLearningClient::createMLModel (const CreateMLModelRequest & request) slot
Creates a new MLModel using the DataSource and the recipe as information sources.
</p
An MLModel is nearly immutable. Users can update only the MLModelName and the ScoreThreshold in an MLModel without creating a new MLModel.
</p
CreateMLModel is an asynchronous operation. In response to CreateMLModel, Amazon Machine Learning (Amazon ML) immediately returns and sets the MLModel status to PENDING. After the MLModel has been created and ready is for use, Amazon ML sets the status to COMPLETED.
</p
You can use the GetMLModel operation to check the progress of the MLModel during the creation
operation>
CreateMLModel requires a DataSource with computed statistics, which can be created by setting ComputeStatistics to true in CreateDataSourceFromRDS, CreateDataSourceFromS3, or CreateDataSourceFromRedshift operations.
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 380 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateMLModelResponse *>(send(request));
 }
createRealtimeEndpoint
CreateRealtimeEndpointResponse * QtAws::MachineLearning::MachineLearningClient::createRealtimeEndpoint (const CreateRealtimeEndpointRequest & request) slot
Creates a real-time endpoint for the MLModel. The endpoint contains the URI of the MLModel; that is, the location to send real-time prediction requests for the specified
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRealtimeEndpointResponse *>(send(request));
 }
deleteBatchPrediction
DeleteBatchPredictionResponse * QtAws::MachineLearning::MachineLearningClient::deleteBatchPrediction (const DeleteBatchPredictionRequest & request) slot
Assigns the DELETED status to a BatchPrediction, rendering it
unusable>
After using the DeleteBatchPrediction operation, you can use the GetBatchPrediction operation to verify that the status of the BatchPrediction changed to
DELETED>
Caution: The result of the DeleteBatchPrediction operation is
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 418 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBatchPredictionResponse *>(send(request));
 }
deleteDataSource
DeleteDataSourceResponse * QtAws::MachineLearning::MachineLearningClient::deleteDataSource (const DeleteDataSourceRequest & request) slot
Assigns the DELETED status to a DataSource, rendering it
unusable>
After using the DeleteDataSource operation, you can use the GetDataSource operation to verify that the status of the DataSource changed to
DELETED>
Caution: The results of the DeleteDataSource operation are
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 441 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDataSourceResponse *>(send(request));
 }
deleteEvaluation
DeleteEvaluationResponse * QtAws::MachineLearning::MachineLearningClient::deleteEvaluation (const DeleteEvaluationRequest & request) slot
Assigns the DELETED status to an Evaluation, rendering it
unusable>
After invoking the DeleteEvaluation operation, you can use the GetEvaluation operation to verify that the status of the Evaluation changed to
DELETED> <caution><title>Caution</title>
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 462 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEvaluationResponse *>(send(request));
 }
deleteMLModel
DeleteMLModelResponse * QtAws::MachineLearning::MachineLearningClient::deleteMLModel (const DeleteMLModelRequest & request) slot
Assigns the DELETED status to an MLModel, rendering it
unusable>
After using the DeleteMLModel operation, you can use the GetMLModel operation to verify that the status of the MLModel changed to
DELETED>
Caution: The result of the DeleteMLModel operation is
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 485 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMLModelResponse *>(send(request));
 }
deleteRealtimeEndpoint
DeleteRealtimeEndpointResponse * QtAws::MachineLearning::MachineLearningClient::deleteRealtimeEndpoint (const DeleteRealtimeEndpointRequest & request) slot
Deletes a real time endpoint of an
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 499 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRealtimeEndpointResponse *>(send(request));
 }
deleteTags
DeleteTagsResponse * QtAws::MachineLearning::MachineLearningClient::deleteTags (const DeleteTagsRequest & request) slot
Deletes the specified tags associated with an ML object. After this operation is complete, you can't recover deleted
tags>
If you specify a tag that doesn't exist, Amazon ML ignores
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 517 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsResponse *>(send(request));
 }
describeBatchPredictions
DescribeBatchPredictionsResponse * QtAws::MachineLearning::MachineLearningClient::describeBatchPredictions (const DescribeBatchPredictionsRequest & request) slot
Returns a list of BatchPrediction operations that match the search criteria in the
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 531 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBatchPredictionsResponse *>(send(request));
 }
describeDataSources
DescribeDataSourcesResponse * QtAws::MachineLearning::MachineLearningClient::describeDataSources (const DescribeDataSourcesRequest & request) slot
Returns a list of DataSource that match the search criteria in the
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 545 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDataSourcesResponse *>(send(request));
 }
describeEvaluations
DescribeEvaluationsResponse * QtAws::MachineLearning::MachineLearningClient::describeEvaluations (const DescribeEvaluationsRequest & request) slot
Returns a list of DescribeEvaluations that match the search criteria in the
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEvaluationsResponse *>(send(request));
 }
describeMLModels
DescribeMLModelsResponse * QtAws::MachineLearning::MachineLearningClient::describeMLModels (const DescribeMLModelsRequest & request) slot
Returns a list of MLModel that match the search criteria in the
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 573 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMLModelsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::MachineLearning::MachineLearningClient::describeTags (const DescribeTagsRequest & request) slot
Describes one or more of the tags for your Amazon ML
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 587 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
getBatchPrediction
GetBatchPredictionResponse * QtAws::MachineLearning::MachineLearningClient::getBatchPrediction (const GetBatchPredictionRequest & request) slot
Returns a BatchPrediction that includes detailed metadata, status, and data file information for a Batch Prediction
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 602 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBatchPredictionResponse *>(send(request));
 }
getDataSource
GetDataSourceResponse * QtAws::MachineLearning::MachineLearningClient::getDataSource (const GetDataSourceRequest & request) slot
Returns a DataSource that includes metadata and data file information, as well as the current status of the
DataSource>
GetDataSource provides results in normal or verbose format. The verbose format adds the schema description and the list of files pointed to by the DataSource to the normal
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 621 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDataSourceResponse *>(send(request));
 }
getEvaluation
GetEvaluationResponse * QtAws::MachineLearning::MachineLearningClient::getEvaluation (const GetEvaluationRequest & request) slot
Returns an Evaluation that includes metadata as well as the current status of the
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 635 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEvaluationResponse *>(send(request));
 }
getMLModel
GetMLModelResponse * QtAws::MachineLearning::MachineLearningClient::getMLModel (const GetMLModelRequest & request) slot
Returns an MLModel that includes detailed metadata, data source information, and the current status of the
MLModel>
GetMLModel provides results in normal or verbose format.
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 653 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetMLModelResponse *>(send(request));
 }
predict
PredictResponse * QtAws::MachineLearning::MachineLearningClient::predict (const PredictRequest & request) slot
Generates a prediction for the observation using the specified ML
Model> <note><title>Note</title>
Not all response parameters will be populated. Whether a response parameter is populated depends on the type of model
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 671 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PredictResponse *>(send(request));
 }
updateBatchPrediction
UpdateBatchPredictionResponse * QtAws::MachineLearning::MachineLearningClient::updateBatchPrediction (const UpdateBatchPredictionRequest & request) slot
Updates the BatchPredictionName of a
BatchPrediction>
You can use the GetBatchPrediction operation to view the contents of the updated data
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 689 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBatchPredictionResponse *>(send(request));
 }
updateDataSource
UpdateDataSourceResponse * QtAws::MachineLearning::MachineLearningClient::updateDataSource (const UpdateDataSourceRequest & request) slot
Updates the DataSourceName of a
DataSource>
You can use the GetDataSource operation to view the contents of the updated data
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 707 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDataSourceResponse *>(send(request));
 }
updateEvaluation
UpdateEvaluationResponse * QtAws::MachineLearning::MachineLearningClient::updateEvaluation (const UpdateEvaluationRequest & request) slot
Updates the EvaluationName of an
Evaluation>
You can use the GetEvaluation operation to view the contents of the updated data
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 725 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateEvaluationResponse *>(send(request));
 }
updateMLModel
UpdateMLModelResponse * QtAws::MachineLearning::MachineLearningClient::updateMLModel (const UpdateMLModelRequest & request) slot
Updates the MLModelName and the ScoreThreshold of an
MLModel>
You can use the GetMLModel operation to view the contents of the updated data
Parameters
request Request to send to Amazon Machine Learning.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 743 of file machinelearningclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateMLModelResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
machinelearning/machinelearningclient.h
machinelearning/machinelearningclient.cpp