AWS SDK for Qt: QtAws::Translate::TranslateClient Class Reference
QtAws::Translate::TranslateClient Class Reference
Client for Amazon Translate.
Public Slots
TranslateTextResponse * translateText (const TranslateTextRequest &request)
Public Member Functions
TranslateClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new TranslateClient object.
TranslateClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new TranslateClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Translate.
Provides translation between English and one of six languages, or between one of the six languages and
Definition at line 34 of file translateclient.h.
Constructor & Destructor Documentation
TranslateClient() [1/2]
QtAws::Translate::TranslateClient::TranslateClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new TranslateClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 49 of file translateclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new TranslateClientPrivate(this), parent)
 {
     Q_D(TranslateClient);
     d->apiVersion = QStringLiteral("2017-07-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("translate");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Translate");
     d->serviceName = QStringLiteral("translate");
 }
TranslateClient() [2/2]
QtAws::Translate::TranslateClient::TranslateClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new TranslateClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 82 of file translateclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new TranslateClientPrivate(this), parent)
 {
     Q_D(TranslateClient);
     d->apiVersion = QStringLiteral("2017-07-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("translate");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Translate");
     d->serviceName = QStringLiteral("translate");
 }
Member Function Documentation
translateText
TranslateTextResponse * QtAws::Translate::TranslateClient::translateText (const TranslateTextRequest & request) slot
Translates input text from the source language to the target language. You can translate between English (en) and one of the following languages, or between one of the following languages and
English>
Arabic
(ar>
Chinese (Simplified)
(zh>
French
(fr>
German
(de>
Portuguese
(pt>
Spanish
Parameters
request Request to send to Amazon Translate.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 133 of file translateclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TranslateTextResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
translate/translateclient.h
translate/translateclient.cpp