AWS SDK for Qt: QtAws::SqsOld::SqsCreateQueueResponsePrivate Class Reference
QtAws::SqsOld::SqsCreateQueueResponsePrivate Class Reference
Private implementation for SqsCreateQueueResponse.
Public Member Functions
SqsCreateQueueResponsePrivate (SqsCreateQueueResponse *const q)
Constructs a new SqsCreateQueueResponsePrivate object.
void parseCreateQueueResponse (QXmlStreamReader &xml)
Parse an SQS CreateQueueResponse element.
void parseCreateQueueResult (QXmlStreamReader &xml)
Parse an SQS CreateQueueResult element.
Public Member Functions inherited from QtAws::SqsOld::SqsResponsePrivate
SqsResponsePrivate (SqsResponse *const q)
Constructs a new SqsResponsePrivate object.
void parseErrorResponse (QXmlStreamReader &xml)
Parse an SQS ErrorResponse element.
void parseResponseMetadata (QXmlStreamReader &xml)
Parse an SQS ResponseMetadata element.
Public Attributes
QString queueUrl
Created queue URL.
Public Attributes inherited from QtAws::SqsOld::SqsResponsePrivate
SqsErrorList errors
SQS errors.
QString requestId
SQS request ID.
Private Attributes
SqsCreateQueueResponse *const q_ptr
Internal q-pointer.
Detailed Description
Private implementation for SqsCreateQueueResponse.
Definition at line 30 of file sqscreatequeueresponse_p.h.
Constructor & Destructor Documentation
SqsCreateQueueResponsePrivate()
QtAws::SqsOld::SqsCreateQueueResponsePrivate::SqsCreateQueueResponsePrivate (SqsCreateQueueResponse *const q)
Constructs a new SqsCreateQueueResponsePrivate object.
Parameters
q Pointer to this object's public SqsCreateQueueResponse instance.
Definition at line 130 of file sqscreatequeueresponse.cpp.
     : SqsResponsePrivate(q), q_ptr(q)
 {
 }
Member Function Documentation
parseCreateQueueResponse()
void QtAws::SqsOld::SqsCreateQueueResponsePrivate::parseCreateQueueResponse (QXmlStreamReader & xml)
Parse an SQS CreateQueueResponse element.
This implementation parses SQS CreateQueueResponse elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<CreateQueueResponse>
  <CreateQueueResult>
    <QueueUrl>http://sqs.us-east-1.amazonaws.com/123456789012/testQueue</QueueUrl>
  </CreateQueueResult>
  <ResponseMetadata>
    <RequestId>7a62c49f-347e-4fc4-9331-6e8e7a96aa73</RequestId>
  </ResponseMetadata>
</CreateQueueResponse>
Parameters
xml XML stream to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 159 of file sqscreatequeueresponse.cpp.
References parseCreateQueueResult(), and QtAws::SqsOld::SqsResponsePrivate::parseResponseMetadata().
 {
     Q_ASSERT(xml.name() == QLatin1String("CreateQueueResponse"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("CreateQueueResult")) {
             parseCreateQueueResult(xml);
         } else if (xml.name() == QLatin1String("ResponseMetadata")) {
             parseResponseMetadata(xml);
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
parseCreateQueueResult()
void QtAws::SqsOld::SqsCreateQueueResponsePrivate::parseCreateQueueResult (QXmlStreamReader & xml)
Parse an SQS CreateQueueResult element.
This implementation parses SQS CreateQueueResult elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<CreateQueueResult>
  <QueueUrl>http://sqs.us-east-1.amazonaws.com/123456789012/testQueue</QueueUrl>
</CreateQueueResult>
Parameters
xml XML stream to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 192 of file sqscreatequeueresponse.cpp.
References queueUrl.
Referenced by parseCreateQueueResponse().
 {
     Q_ASSERT(xml.name() == QLatin1String("CreateQueueResult"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("QueueUrl")) {
             queueUrl = xml.readElementText();
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
The documentation for this class was generated from the following files:
sqs-old/sqscreatequeueresponse_p.h
sqs-old/sqscreatequeueresponse.cpp