AWS SDK for Qt: QtAws::AlexaForBusiness::AlexaForBusinessClient Class Reference
QtAws::AlexaForBusiness::AlexaForBusinessClient Class Reference
Client for Alexa For Business.
Public Slots
AssociateDeviceWithRoomResponse * associateDeviceWithRoom (const AssociateDeviceWithRoomRequest &request)
AssociateSkillGroupWithRoomResponse * associateSkillGroupWithRoom (const AssociateSkillGroupWithRoomRequest &request)
CreateProfileResponse * createProfile (const CreateProfileRequest &request)
CreateRoomResponse * createRoom (const CreateRoomRequest &request)
CreateSkillGroupResponse * createSkillGroup (const CreateSkillGroupRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeleteProfileResponse * deleteProfile (const DeleteProfileRequest &request)
DeleteRoomResponse * deleteRoom (const DeleteRoomRequest &request)
DeleteRoomSkillParameterResponse * deleteRoomSkillParameter (const DeleteRoomSkillParameterRequest &request)
DeleteSkillGroupResponse * deleteSkillGroup (const DeleteSkillGroupRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DisassociateDeviceFromRoomResponse * disassociateDeviceFromRoom (const DisassociateDeviceFromRoomRequest &request)
DisassociateSkillGroupFromRoomResponse * disassociateSkillGroupFromRoom (const DisassociateSkillGroupFromRoomRequest &request)
GetDeviceResponse * getDevice (const GetDeviceRequest &request)
GetProfileResponse * getProfile (const GetProfileRequest &request)
GetRoomResponse * getRoom (const GetRoomRequest &request)
GetRoomSkillParameterResponse * getRoomSkillParameter (const GetRoomSkillParameterRequest &request)
GetSkillGroupResponse * getSkillGroup (const GetSkillGroupRequest &request)
ListSkillsResponse * listSkills (const ListSkillsRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
PutRoomSkillParameterResponse * putRoomSkillParameter (const PutRoomSkillParameterRequest &request)
ResolveRoomResponse * resolveRoom (const ResolveRoomRequest &request)
RevokeInvitationResponse * revokeInvitation (const RevokeInvitationRequest &request)
SearchDevicesResponse * searchDevices (const SearchDevicesRequest &request)
SearchProfilesResponse * searchProfiles (const SearchProfilesRequest &request)
SearchRoomsResponse * searchRooms (const SearchRoomsRequest &request)
SearchSkillGroupsResponse * searchSkillGroups (const SearchSkillGroupsRequest &request)
SearchUsersResponse * searchUsers (const SearchUsersRequest &request)
SendInvitationResponse * sendInvitation (const SendInvitationRequest &request)
StartDeviceSyncResponse * startDeviceSync (const StartDeviceSyncRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateDeviceResponse * updateDevice (const UpdateDeviceRequest &request)
UpdateProfileResponse * updateProfile (const UpdateProfileRequest &request)
UpdateRoomResponse * updateRoom (const UpdateRoomRequest &request)
UpdateSkillGroupResponse * updateSkillGroup (const UpdateSkillGroupRequest &request)
Public Member Functions
AlexaForBusinessClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AlexaForBusinessClient object.
AlexaForBusinessClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AlexaForBusinessClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Alexa For Business.
Alexa for Business makes it easy for you to use Alexa in your organization. Alexa for Business gives you the tools you need to manage Alexa devices, enroll your users, and assign skills, at scale. You can build your own context-aware voice skills using the Alexa Skills Kit, and the Alexa for Business APIs, and you can make these available as private skills for your organization. Alexa for Business also makes it easy to voice-enable your products and services, providing context-aware voice experiences for your
Definition at line 104 of file alexaforbusinessclient.h.
Constructor & Destructor Documentation
AlexaForBusinessClient() [1/2]
QtAws::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AlexaForBusinessClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 123 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new AlexaForBusinessClientPrivate(this), parent)
 {
     Q_D(AlexaForBusinessClient);
     d->apiVersion = QStringLiteral("2017-11-09");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("a4b");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Alexa For Business");
     d->serviceName = QStringLiteral("a4b");
 }
AlexaForBusinessClient() [2/2]
QtAws::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AlexaForBusinessClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 156 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new AlexaForBusinessClientPrivate(this), parent)
 {
     Q_D(AlexaForBusinessClient);
     d->apiVersion = QStringLiteral("2017-11-09");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("a4b");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Alexa For Business");
     d->serviceName = QStringLiteral("a4b");
 }
Member Function Documentation
associateDeviceWithRoom
AssociateDeviceWithRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::associateDeviceWithRoom (const AssociateDeviceWithRoomRequest & request) slot
Associates a device to a given room. This applies all the settings from the room profile to the device, and all the skills in any skill groups added to that room. This operation requires the device to be online, or a manual sync is required.
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 184 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateDeviceWithRoomResponse *>(send(request));
 }
associateSkillGroupWithRoom
AssociateSkillGroupWithRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::associateSkillGroupWithRoom (const AssociateSkillGroupWithRoomRequest & request) slot
Associates a skill group to a given room. This enables all skills in the associated skill group on all devices in the
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 198 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateSkillGroupWithRoomResponse *>(send(request));
 }
createProfile
CreateProfileResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::createProfile (const CreateProfileRequest & request) slot
Creates a new room profile with the specified
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 212 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateProfileResponse *>(send(request));
 }
createRoom
CreateRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::createRoom (const CreateRoomRequest & request) slot
Creates a room with the specified
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 226 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRoomResponse *>(send(request));
 }
createSkillGroup
CreateSkillGroupResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::createSkillGroup (const CreateSkillGroupRequest & request) slot
Creates a skill group with a specified name and
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 240 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSkillGroupResponse *>(send(request));
 }
createUser
CreateUserResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::createUser (const CreateUserRequest & request) slot
Creates a
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 254 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserResponse *>(send(request));
 }
deleteProfile
DeleteProfileResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteProfile (const DeleteProfileRequest & request) slot
Deletes a room profile by the profile
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 268 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteProfileResponse *>(send(request));
 }
deleteRoom
DeleteRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteRoom (const DeleteRoomRequest & request) slot
Deletes a room by the room
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 282 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRoomResponse *>(send(request));
 }
deleteRoomSkillParameter
DeleteRoomSkillParameterResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteRoomSkillParameter (const DeleteRoomSkillParameterRequest & request) slot
Deletes room skill parameter details by room, skill, and parameter key
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 296 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRoomSkillParameterResponse *>(send(request));
 }
deleteSkillGroup
DeleteSkillGroupResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteSkillGroup (const DeleteSkillGroupRequest & request) slot
Deletes a skill group by skill group
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 310 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSkillGroupResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteUser (const DeleteUserRequest & request) slot
Deletes a specified user by user ARN and enrollment
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 324 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
disassociateDeviceFromRoom
DisassociateDeviceFromRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::disassociateDeviceFromRoom (const DisassociateDeviceFromRoomRequest & request) slot
Disassociates a device from its current room. The device continues to be connected to the Wi-Fi network and is still registered to the account. The device settings and skills are removed from the
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 339 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateDeviceFromRoomResponse *>(send(request));
 }
disassociateSkillGroupFromRoom
DisassociateSkillGroupFromRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::disassociateSkillGroupFromRoom (const DisassociateSkillGroupFromRoomRequest & request) slot
Disassociates a skill group from a specified room. This disables all skills in the skill group on all devices in the
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 353 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateSkillGroupFromRoomResponse *>(send(request));
 }
getDevice
GetDeviceResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::getDevice (const GetDeviceRequest & request) slot
Gets the details of a device by device
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 367 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeviceResponse *>(send(request));
 }
getProfile
GetProfileResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::getProfile (const GetProfileRequest & request) slot
Gets the details of a room profile by profile
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 381 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetProfileResponse *>(send(request));
 }
getRoom
GetRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::getRoom (const GetRoomRequest & request) slot
Gets room details by room
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRoomResponse *>(send(request));
 }
getRoomSkillParameter
GetRoomSkillParameterResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::getRoomSkillParameter (const GetRoomSkillParameterRequest & request) slot
Gets room skill parameter details by room, skill, and parameter key
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRoomSkillParameterResponse *>(send(request));
 }
getSkillGroup
GetSkillGroupResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::getSkillGroup (const GetSkillGroupRequest & request) slot
Gets skill group details by skill group
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 423 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSkillGroupResponse *>(send(request));
 }
listSkills
ListSkillsResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::listSkills (const ListSkillsRequest & request) slot
Lists all enabled skills in a specific skill
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 437 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSkillsResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::listTags (const ListTagsRequest & request) slot
Lists all tags for a specific
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 451 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
putRoomSkillParameter
PutRoomSkillParameterResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::putRoomSkillParameter (const PutRoomSkillParameterRequest & request) slot
Updates room skill parameter details by room, skill, and parameter key ID. Not all skills have a room skill
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 465 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutRoomSkillParameterResponse *>(send(request));
 }
resolveRoom
ResolveRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::resolveRoom (const ResolveRoomRequest & request) slot
Determines the details for the room from which a skill request was invoked. This operation is used by skill
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 479 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResolveRoomResponse *>(send(request));
 }
revokeInvitation
RevokeInvitationResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::revokeInvitation (const RevokeInvitationRequest & request) slot
Revokes an invitation and invalidates the enrollment
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 493 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RevokeInvitationResponse *>(send(request));
 }
searchDevices
SearchDevicesResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::searchDevices (const SearchDevicesRequest & request) slot
Searches devices and lists the ones that meet a set of filter
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 507 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchDevicesResponse *>(send(request));
 }
searchProfiles
SearchProfilesResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::searchProfiles (const SearchProfilesRequest & request) slot
Searches room profiles and lists the ones that meet a set of filter
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 521 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchProfilesResponse *>(send(request));
 }
searchRooms
SearchRoomsResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::searchRooms (const SearchRoomsRequest & request) slot
Searches rooms and lists the ones that meet a set of filter and sort
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 535 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchRoomsResponse *>(send(request));
 }
searchSkillGroups
SearchSkillGroupsResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::searchSkillGroups (const SearchSkillGroupsRequest & request) slot
Searches skill groups and lists the ones that meet a set of filter and sort
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 549 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchSkillGroupsResponse *>(send(request));
 }
searchUsers
SearchUsersResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::searchUsers (const SearchUsersRequest & request) slot
Searches users and lists the ones that meet a set of filter and sort
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 563 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SearchUsersResponse *>(send(request));
 }
sendInvitation
SendInvitationResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::sendInvitation (const SendInvitationRequest & request) slot
Sends an enrollment invitation email with a URL to a user. The URL is valid for 72 hours or until you call this operation again, whichever comes first.
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 578 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendInvitationResponse *>(send(request));
 }
startDeviceSync
StartDeviceSyncResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::startDeviceSync (const StartDeviceSyncRequest & request) slot
Resets a device and its account to the known default settings by clearing all information and settings set by previous
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 592 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartDeviceSyncResponse *>(send(request));
 }
tagResource
TagResourceResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::tagResource (const TagResourceRequest & request) slot
Adds metadata tags to a specified
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 606 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagResourceResponse *>(send(request));
 }
untagResource
UntagResourceResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::untagResource (const UntagResourceRequest & request) slot
Removes metadata tags from a specified
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 620 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagResourceResponse *>(send(request));
 }
updateDevice
UpdateDeviceResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::updateDevice (const UpdateDeviceRequest & request) slot
Updates the device name by device
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 634 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDeviceResponse *>(send(request));
 }
updateProfile
UpdateProfileResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::updateProfile (const UpdateProfileRequest & request) slot
Updates an existing room profile by room profile
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 648 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateProfileResponse *>(send(request));
 }
updateRoom
UpdateRoomResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::updateRoom (const UpdateRoomRequest & request) slot
Updates room details by room
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 662 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRoomResponse *>(send(request));
 }
updateSkillGroup
UpdateSkillGroupResponse * QtAws::AlexaForBusiness::AlexaForBusinessClient::updateSkillGroup (const UpdateSkillGroupRequest & request) slot
Updates skill group details by skill group
Parameters
request Request to send to Alexa For Business.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 676 of file alexaforbusinessclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSkillGroupResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
alexaforbusiness/alexaforbusinessclient.h
alexaforbusiness/alexaforbusinessclient.cpp