AWS SDK for Qt: QtAws::CloudWatchEvents::CloudWatchEventsClient Class Reference
QtAws::CloudWatchEvents::CloudWatchEventsClient Class Reference
Client for Amazon CloudWatch Events.
Public Slots
DeleteRuleResponse * deleteRule (const DeleteRuleRequest &request)
DescribeEventBusResponse * describeEventBus (const DescribeEventBusRequest &request)
DescribeRuleResponse * describeRule (const DescribeRuleRequest &request)
DisableRuleResponse * disableRule (const DisableRuleRequest &request)
EnableRuleResponse * enableRule (const EnableRuleRequest &request)
ListRuleNamesByTargetResponse * listRuleNamesByTarget (const ListRuleNamesByTargetRequest &request)
ListRulesResponse * listRules (const ListRulesRequest &request)
ListTargetsByRuleResponse * listTargetsByRule (const ListTargetsByRuleRequest &request)
PutEventsResponse * putEvents (const PutEventsRequest &request)
PutPermissionResponse * putPermission (const PutPermissionRequest &request)
PutRuleResponse * putRule (const PutRuleRequest &request)
PutTargetsResponse * putTargets (const PutTargetsRequest &request)
RemovePermissionResponse * removePermission (const RemovePermissionRequest &request)
RemoveTargetsResponse * removeTargets (const RemoveTargetsRequest &request)
TestEventPatternResponse * testEventPattern (const TestEventPatternRequest &request)
Public Member Functions
CloudWatchEventsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudWatchEventsClient object.
CloudWatchEventsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudWatchEventsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudWatch Events.
Amazon CloudWatch Events helps you to respond to state changes in your AWS resources. When your resources change state, they automatically send events into an event stream. You can create rules that match selected events in the stream and route them to targets to take action. You can also use rules to take action on a pre-determined schedule. For example, you can configure rules
to>
Automatically invoke an AWS Lambda function to update DNS entries when an event notifies you that Amazon EC2 instance enters the running
state>
Direct specific API records from CloudTrail to an Amazon Kinesis stream for detailed analysis of potential security or availability
risks>
Periodically invoke a built-in target to create a snapshot of an Amazon EBS
volume>
For more information about the features of Amazon CloudWatch Events, see the Amazon CloudWatch Events User
Definition at line 62 of file cloudwatcheventsclient.h.
Constructor & Destructor Documentation
CloudWatchEventsClient() [1/2]
QtAws::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudWatchEventsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 99 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudWatchEventsClientPrivate(this), parent)
 {
     Q_D(CloudWatchEventsClient);
     d->apiVersion = QStringLiteral("2015-10-07");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("events");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudWatch Events");
     d->serviceName = QStringLiteral("events");
 }
CloudWatchEventsClient() [2/2]
QtAws::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudWatchEventsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 132 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudWatchEventsClientPrivate(this), parent)
 {
     Q_D(CloudWatchEventsClient);
     d->apiVersion = QStringLiteral("2015-10-07");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("events");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudWatch Events");
     d->serviceName = QStringLiteral("events");
 }
Member Function Documentation
deleteRule
DeleteRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::deleteRule (const DeleteRuleRequest & request) slot
Deletes the specified
rule>
You must remove all targets from a rule using RemoveTargets before you can delete the
rule>
When you delete a rule, incoming events might continue to match to the deleted rule. Please allow a short period of time for changes to take
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 167 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRuleResponse *>(send(request));
 }
describeEventBus
DescribeEventBusResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::describeEventBus (const DescribeEventBusRequest & request) slot
Displays the external AWS accounts that are permitted to write events to your account using your account's event bus, and the associated policy. To enable your account to receive events from other accounts, use
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 182 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventBusResponse *>(send(request));
 }
describeRule
DescribeRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::describeRule (const DescribeRuleRequest & request) slot
Describes the specified
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 196 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRuleResponse *>(send(request));
 }
disableRule
DisableRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::disableRule (const DisableRuleRequest & request) slot
Disables the specified rule. A disabled rule won't match any events, and won't self-trigger if it has a schedule
expression>
When you disable a rule, incoming events might continue to match to the disabled rule. Please allow a short period of time for changes to take
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 215 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableRuleResponse *>(send(request));
 }
enableRule
EnableRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::enableRule (const EnableRuleRequest & request) slot
Enables the specified rule. If the rule does not exist, the operation
fails>
When you enable a rule, incoming events might not immediately start matching to a newly enabled rule. Please allow a short period of time for changes to take
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 234 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableRuleResponse *>(send(request));
 }
listRuleNamesByTarget
ListRuleNamesByTargetResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::listRuleNamesByTarget (const ListRuleNamesByTargetRequest & request) slot
Lists the rules for the specified target. You can see which of the rules in Amazon CloudWatch Events can invoke a specific target in your
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 249 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRuleNamesByTargetResponse *>(send(request));
 }
listRules
ListRulesResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::listRules (const ListRulesRequest & request) slot
Lists your Amazon CloudWatch Events rules. You can either list all the rules or you can provide a prefix to match to the rule
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 264 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRulesResponse *>(send(request));
 }
listTargetsByRule
ListTargetsByRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::listTargetsByRule (const ListTargetsByRuleRequest & request) slot
Lists the targets assigned to the specified
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 278 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTargetsByRuleResponse *>(send(request));
 }
putEvents
PutEventsResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::putEvents (const PutEventsRequest & request) slot
Sends custom events to Amazon CloudWatch Events so that they can be matched to
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutEventsResponse *>(send(request));
 }
putPermission
PutPermissionResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::putPermission (const PutPermissionRequest & request) slot
Running PutPermission permits the specified AWS account to put events to your account's default event bus. CloudWatch Events rules in your account are triggered by these events arriving to your default event bus.
</p
For another account to send events to your account, that external account must have a CloudWatch Events rule with your account's default event bus as a
target>
To enable multiple AWS accounts to put events to your default event bus, run PutPermission once for each of these
accounts>
The permission policy on the default event bus cannot exceed 10KB in
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 321 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutPermissionResponse *>(send(request));
 }
putRule
PutRuleResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::putRule (const PutRuleRequest & request) slot
Creates or updates the specified rule. Rules are enabled by default, or based on value of the state. You can disable a rule using
DisableRule>
If you are updating an existing rule, the rule is completely replaced with what you specify in this PutRule command. If you omit arguments in PutRule, the old values for those arguments are not kept. Instead, they are replaced with null
values>
When you create or update a rule, incoming events might not immediately start matching to new or updated rules. Please allow a short period of time for changes to take
effect>
A rule must contain at least an EventPattern or ScheduleExpression. Rules with EventPatterns are triggered when a matching event is observed. Rules with ScheduleExpressions self-trigger based on the given schedule. A rule can have both an EventPattern and a ScheduleExpression, in which case the rule triggers on matching events as well as on a
schedule>
Most services in AWS treat : or / as the same character in Amazon Resource Names (ARNs). However, CloudWatch Events uses an exact match in event patterns and rules. Be sure to use the correct ARN characters when creating event patterns so that they match the ARN syntax in the event you want to
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 359 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutRuleResponse *>(send(request));
 }
putTargets
PutTargetsResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::putTargets (const PutTargetsRequest & request) slot
Adds the specified targets to the specified rule, or updates the targets if they are already associated with the
rule>
Targets are the resources that are invoked when a rule is
triggered>
You can configure the following as targets for CloudWatch
Events>
EC2
instance>
AWS Lambda
function>
Streams in Amazon Kinesis
Stream>
Delivery streams in Amazon Kinesis
Firehos>
Amazon ECS
task>
AWS Step Functions state
machine>
AWS Batch
job>
Pipelines in Amazon Code
Pipelin>
Amazon Inspector assessment
template>
Amazon SNS
topic>
Amazon SQS queues, including FIFO
queue>
The default event bus of another AWS
accoun>
Note that creating rules with built-in targets is supported only in the AWS Management
Console>
For some target types, PutTargets provides target-specific parameters. If the target is an Amazon Kinesis stream, you can optionally specify which shard the event goes to by using the KinesisParameters argument. To invoke a command on multiple EC2 instances with one rule, you can use the RunCommandParameters
field>
To be able to make API calls against the resources that you own, Amazon CloudWatch Events needs the appropriate permissions. For AWS Lambda and Amazon SNS resources, CloudWatch Events relies on resource-based policies. For EC2 instances, Amazon Kinesis streams, and AWS Step Functions state machines, CloudWatch Events relies on IAM roles that you specify in the RoleARN argument in PutTargets. For more information, see Authentication and Access Control in the Amazon CloudWatch Events User
Guide>
If another AWS account is in the same region and has granted you permission (using PutPermission), you can send events to that account by setting that account's event bus as a target of the rules in your account. To send the matched events to the other account, specify that account's event bus as the Arn when you run PutTargets. If your account sends events to another account, your account is charged for each sent event. Each event sent to antoher account is charged as a custom event. The account receiving the event is not charged. For more information on pricing, see Amazon CloudWatch Pricing>
For more information about enabling cross-account events, see
PutPermission>
Input, InputPath and InputTransformer are mutually exclusive and optional parameters of a target. When a rule is triggered due to a matched
event>
If none of the following arguments are specified for a target, then the entire event is passed to the target in JSON form (unless the target is Amazon EC2 Run Command or Amazon ECS task, in which case nothing from the event is passed to the
target)>
If Input is specified in the form of valid JSON, then the matched event is overridden with this
constant>
If InputPath is specified in the form of JSONPath (for example, $.detail), then only the part of the event specified in the path is passed to the target (for example, only the detail part of the event is
passed)>
If InputTransformer is specified, then one or more specified JSONPaths are extracted from the event and used as values in a template that you specify as the input to the
target>
When you specify InputPath or InputTransformer, you must use JSON dot notation, not bracket
notation>
When you add targets to a rule and the associated rule triggers soon after, new or updated targets might not be immediately invoked. Please allow a short period of time for changes to take
effect>
This action can partially fail if too many requests are made at the same time. If that happens, FailedEntryCount is non-zero in the response and each entry in FailedEntries provides the ID of the failed target and the error
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 501 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutTargetsResponse *>(send(request));
 }
removePermission
RemovePermissionResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::removePermission (const RemovePermissionRequest & request) slot
Revokes the permission of another AWS account to be able to put events to your default event bus. Specify the account to revoke by the StatementId value that you associated with the account when you granted it permission with PutPermission. You can find the StatementId by using
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 517 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemovePermissionResponse *>(send(request));
 }
removeTargets
RemoveTargetsResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::removeTargets (const RemoveTargetsRequest & request) slot
Removes the specified targets from the specified rule. When the rule is triggered, those targets are no longer be
invoked>
When you remove a target, when the associated rule triggers, removed targets might continue to be invoked. Please allow a short period of time for changes to take
effect>
This action can partially fail if too many requests are made at the same time. If that happens, FailedEntryCount is non-zero in the response and each entry in FailedEntries provides the ID of the failed target and the error
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 542 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTargetsResponse *>(send(request));
 }
testEventPattern
TestEventPatternResponse * QtAws::CloudWatchEvents::CloudWatchEventsClient::testEventPattern (const TestEventPatternRequest & request) slot
Tests whether the specified event pattern matches the provided
event>
Most services in AWS treat : or / as the same character in Amazon Resource Names (ARNs). However, CloudWatch Events uses an exact match in event patterns and rules. Be sure to use the correct ARN characters when creating event patterns so that they match the ARN syntax in the event you want to
Parameters
request Request to send to Amazon CloudWatch Events.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 562 of file cloudwatcheventsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestEventPatternResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
events/cloudwatcheventsclient.h
events/cloudwatcheventsclient.cpp