AWS SDK for Qt: QtAws::MediaConvert::MediaConvertClient Class Reference
QtAws::MediaConvert::MediaConvertClient Class Reference
Client for AWS Elemental MediaConvert.
Public Slots
CancelJobResponse * cancelJob (const CancelJobRequest &request)
CreateJobResponse * createJob (const CreateJobRequest &request)
CreateJobTemplateResponse * createJobTemplate (const CreateJobTemplateRequest &request)
CreatePresetResponse * createPreset (const CreatePresetRequest &request)
CreateQueueResponse * createQueue (const CreateQueueRequest &request)
DeleteJobTemplateResponse * deleteJobTemplate (const DeleteJobTemplateRequest &request)
DeletePresetResponse * deletePreset (const DeletePresetRequest &request)
DeleteQueueResponse * deleteQueue (const DeleteQueueRequest &request)
DescribeEndpointsResponse * describeEndpoints (const DescribeEndpointsRequest &request)
GetJobResponse * getJob (const GetJobRequest &request)
GetJobTemplateResponse * getJobTemplate (const GetJobTemplateRequest &request)
GetPresetResponse * getPreset (const GetPresetRequest &request)
GetQueueResponse * getQueue (const GetQueueRequest &request)
ListJobTemplatesResponse * listJobTemplates (const ListJobTemplatesRequest &request)
ListJobsResponse * listJobs (const ListJobsRequest &request)
ListPresetsResponse * listPresets (const ListPresetsRequest &request)
ListQueuesResponse * listQueues (const ListQueuesRequest &request)
UpdateJobTemplateResponse * updateJobTemplate (const UpdateJobTemplateRequest &request)
UpdatePresetResponse * updatePreset (const UpdatePresetRequest &request)
UpdateQueueResponse * updateQueue (const UpdateQueueRequest &request)
Public Member Functions
MediaConvertClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaConvertClient object.
MediaConvertClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaConvertClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elemental MediaConvert.
Definition at line 72 of file mediaconvertclient.h.
Constructor & Destructor Documentation
MediaConvertClient() [1/2]
QtAws::MediaConvert::MediaConvertClient::MediaConvertClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaConvertClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 86 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MediaConvertClientPrivate(this), parent)
 {
     Q_D(MediaConvertClient);
     d->apiVersion = QStringLiteral("2017-08-29");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("mediaconvert");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaConvert");
     d->serviceName = QStringLiteral("mediaconvert");
 }
MediaConvertClient() [2/2]
QtAws::MediaConvert::MediaConvertClient::MediaConvertClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaConvertClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 119 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MediaConvertClientPrivate(this), parent)
 {
     Q_D(MediaConvertClient);
     d->apiVersion = QStringLiteral("2017-08-29");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("mediaconvert");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaConvert");
     d->serviceName = QStringLiteral("mediaconvert");
 }
Member Function Documentation
cancelJob
CancelJobResponse * QtAws::MediaConvert::MediaConvertClient::cancelJob (const CancelJobRequest & request) slot
Permanently remove a job from a queue. Once you have canceled a job, you can't start it again. You can't delete a
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 145 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelJobResponse *>(send(request));
 }
createJob
CreateJobResponse * QtAws::MediaConvert::MediaConvertClient::createJob (const CreateJobRequest & request) slot
Create a new transcoding job. For information about jobs and job settings, see the User Guide at
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 159 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateJobResponse *>(send(request));
 }
createJobTemplate
CreateJobTemplateResponse * QtAws::MediaConvert::MediaConvertClient::createJobTemplate (const CreateJobTemplateRequest & request) slot
Create a new job template. For information about job templates see the User Guide at
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateJobTemplateResponse *>(send(request));
 }
createPreset
CreatePresetResponse * QtAws::MediaConvert::MediaConvertClient::createPreset (const CreatePresetRequest & request) slot
Create a new preset. For information about job templates see the User Guide at
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 187 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePresetResponse *>(send(request));
 }
createQueue
CreateQueueResponse * QtAws::MediaConvert::MediaConvertClient::createQueue (const CreateQueueRequest & request) slot
Create a new transcoding queue. For information about job templates see the User Guide at
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 201 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateQueueResponse *>(send(request));
 }
deleteJobTemplate
DeleteJobTemplateResponse * QtAws::MediaConvert::MediaConvertClient::deleteJobTemplate (const DeleteJobTemplateRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteJobTemplateResponse *>(send(request));
 }
deletePreset
DeletePresetResponse * QtAws::MediaConvert::MediaConvertClient::deletePreset (const DeletePresetRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 227 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePresetResponse *>(send(request));
 }
deleteQueue
DeleteQueueResponse * QtAws::MediaConvert::MediaConvertClient::deleteQueue (const DeleteQueueRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 240 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteQueueResponse *>(send(request));
 }
describeEndpoints
DescribeEndpointsResponse * QtAws::MediaConvert::MediaConvertClient::describeEndpoints (const DescribeEndpointsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 253 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEndpointsResponse *>(send(request));
 }
getJob
GetJobResponse * QtAws::MediaConvert::MediaConvertClient::getJob (const GetJobRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 266 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobResponse *>(send(request));
 }
getJobTemplate
GetJobTemplateResponse * QtAws::MediaConvert::MediaConvertClient::getJobTemplate (const GetJobTemplateRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 279 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobTemplateResponse *>(send(request));
 }
getPreset
GetPresetResponse * QtAws::MediaConvert::MediaConvertClient::getPreset (const GetPresetRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 292 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPresetResponse *>(send(request));
 }
getQueue
GetQueueResponse * QtAws::MediaConvert::MediaConvertClient::getQueue (const GetQueueRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetQueueResponse *>(send(request));
 }
listJobs
ListJobsResponse * QtAws::MediaConvert::MediaConvertClient::listJobs (const ListJobsRequest & request) slot
Retrieve a JSON array of up to twenty of your most recently created jobs. This array includes in-process, completed, and errored jobs. This will return the jobs themselves, not just a list of the jobs. To retrieve the twenty next most recent
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 334 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListJobsResponse *>(send(request));
 }
listJobTemplates
ListJobTemplatesResponse * QtAws::MediaConvert::MediaConvertClient::listJobTemplates (const ListJobTemplatesRequest & request) slot
Retrieve a JSON array of up to twenty of your job templates. This will return the templates themselves, not just a list
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 319 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListJobTemplatesResponse *>(send(request));
 }
listPresets
ListPresetsResponse * QtAws::MediaConvert::MediaConvertClient::listPresets (const ListPresetsRequest & request) slot
Retrieve a JSON array of up to twenty of your presets. This will return the presets themselves, not just a list of them.
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 348 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPresetsResponse *>(send(request));
 }
listQueues
ListQueuesResponse * QtAws::MediaConvert::MediaConvertClient::listQueues (const ListQueuesRequest & request) slot
Retrieve a JSON array of up to twenty of your queues. This will return the queues themselves, not just a list of them.
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 362 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListQueuesResponse *>(send(request));
 }
updateJobTemplate
UpdateJobTemplateResponse * QtAws::MediaConvert::MediaConvertClient::updateJobTemplate (const UpdateJobTemplateRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 375 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateJobTemplateResponse *>(send(request));
 }
updatePreset
UpdatePresetResponse * QtAws::MediaConvert::MediaConvertClient::updatePreset (const UpdatePresetRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 388 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdatePresetResponse *>(send(request));
 }
updateQueue
UpdateQueueResponse * QtAws::MediaConvert::MediaConvertClient::updateQueue (const UpdateQueueRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaConvert.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 401 of file mediaconvertclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateQueueResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mediaconvert/mediaconvertclient.h
mediaconvert/mediaconvertclient.cpp