AWS SDK for Qt: QtAws::CloudWatchLogs::CloudWatchLogsClient Class Reference
QtAws::CloudWatchLogs::CloudWatchLogsClient Class Reference
Client for Amazon CloudWatch Logs.
Public Slots
AssociateKmsKeyResponse * associateKmsKey (const AssociateKmsKeyRequest &request)
CancelExportTaskResponse * cancelExportTask (const CancelExportTaskRequest &request)
CreateExportTaskResponse * createExportTask (const CreateExportTaskRequest &request)
CreateLogGroupResponse * createLogGroup (const CreateLogGroupRequest &request)
CreateLogStreamResponse * createLogStream (const CreateLogStreamRequest &request)
DeleteDestinationResponse * deleteDestination (const DeleteDestinationRequest &request)
DeleteLogGroupResponse * deleteLogGroup (const DeleteLogGroupRequest &request)
DeleteLogStreamResponse * deleteLogStream (const DeleteLogStreamRequest &request)
DeleteMetricFilterResponse * deleteMetricFilter (const DeleteMetricFilterRequest &request)
DeleteResourcePolicyResponse * deleteResourcePolicy (const DeleteResourcePolicyRequest &request)
DeleteRetentionPolicyResponse * deleteRetentionPolicy (const DeleteRetentionPolicyRequest &request)
DeleteSubscriptionFilterResponse * deleteSubscriptionFilter (const DeleteSubscriptionFilterRequest &request)
DescribeDestinationsResponse * describeDestinations (const DescribeDestinationsRequest &request)
DescribeExportTasksResponse * describeExportTasks (const DescribeExportTasksRequest &request)
DescribeLogGroupsResponse * describeLogGroups (const DescribeLogGroupsRequest &request)
DescribeLogStreamsResponse * describeLogStreams (const DescribeLogStreamsRequest &request)
DescribeMetricFiltersResponse * describeMetricFilters (const DescribeMetricFiltersRequest &request)
DescribeResourcePoliciesResponse * describeResourcePolicies (const DescribeResourcePoliciesRequest &request)
DescribeSubscriptionFiltersResponse * describeSubscriptionFilters (const DescribeSubscriptionFiltersRequest &request)
DisassociateKmsKeyResponse * disassociateKmsKey (const DisassociateKmsKeyRequest &request)
FilterLogEventsResponse * filterLogEvents (const FilterLogEventsRequest &request)
GetLogEventsResponse * getLogEvents (const GetLogEventsRequest &request)
ListTagsLogGroupResponse * listTagsLogGroup (const ListTagsLogGroupRequest &request)
PutDestinationResponse * putDestination (const PutDestinationRequest &request)
PutDestinationPolicyResponse * putDestinationPolicy (const PutDestinationPolicyRequest &request)
PutLogEventsResponse * putLogEvents (const PutLogEventsRequest &request)
PutMetricFilterResponse * putMetricFilter (const PutMetricFilterRequest &request)
PutResourcePolicyResponse * putResourcePolicy (const PutResourcePolicyRequest &request)
PutRetentionPolicyResponse * putRetentionPolicy (const PutRetentionPolicyRequest &request)
PutSubscriptionFilterResponse * putSubscriptionFilter (const PutSubscriptionFilterRequest &request)
TagLogGroupResponse * tagLogGroup (const TagLogGroupRequest &request)
TestMetricFilterResponse * testMetricFilter (const TestMetricFilterRequest &request)
UntagLogGroupResponse * untagLogGroup (const UntagLogGroupRequest &request)
Public Member Functions
CloudWatchLogsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudWatchLogsClient object.
CloudWatchLogsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudWatchLogsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudWatch Logs.
You can use Amazon CloudWatch Logs to monitor, store, and access your log files from Amazon EC2 instances, AWS CloudTrail, or other sources. You can then retrieve the associated log data from CloudWatch Logs using the CloudWatch console, CloudWatch Logs commands in the AWS CLI, CloudWatch Logs API, or CloudWatch Logs
SDK>
You can use CloudWatch Logs
to>
Monitor logs from EC2 instances in real-time: You can use CloudWatch Logs to monitor applications and systems using log data. For example, CloudWatch Logs can track the number of errors that occur in your application logs and send you a notification whenever the rate of errors exceeds a threshold that you specify. CloudWatch Logs uses your log data for monitoring; so, no code changes are required. For example, you can monitor application logs for specific literal terms (such as "NullReferenceException") or count the number of occurrences of a literal term at a particular position in log data (such as "404" status codes in an Apache access log). When the term you are searching for is found, CloudWatch Logs reports the data to a CloudWatch metric that you
specify>
Monitor AWS CloudTrail logged events: You can create alarms in CloudWatch and receive notifications of particular API activity as captured by CloudTrail and use the notification to perform
troubleshooting>
Archive log data: You can use CloudWatch Logs to store your log data in highly durable storage. You can change the log retention setting so that any log events older than this setting are automatically deleted. The CloudWatch Logs agent makes it easy to quickly send both rotated and non-rotated log data off of a host and into the log service. You can then access the raw log data when you need
Definition at line 98 of file cloudwatchlogsclient.h.
Constructor & Destructor Documentation
CloudWatchLogsClient() [1/2]
QtAws::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudWatchLogsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 141 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudWatchLogsClientPrivate(this), parent)
 {
     Q_D(CloudWatchLogsClient);
     d->apiVersion = QStringLiteral("2014-03-28");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("logs");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudWatch Logs");
     d->serviceName = QStringLiteral("logs");
 }
CloudWatchLogsClient() [2/2]
QtAws::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudWatchLogsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 174 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudWatchLogsClientPrivate(this), parent)
 {
     Q_D(CloudWatchLogsClient);
     d->apiVersion = QStringLiteral("2014-03-28");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("logs");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudWatch Logs");
     d->serviceName = QStringLiteral("logs");
 }
Member Function Documentation
associateKmsKey
AssociateKmsKeyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::associateKmsKey (const AssociateKmsKeyRequest & request) slot
Associates the specified AWS Key Management Service (AWS KMS) customer master key (CMK) with the specified log
group>
Associating an AWS KMS CMK with a log group overrides any existing associations between the log group and a CMK. After a CMK is associated with a log group, all newly ingested data for the log group is encrypted using the CMK. This association is stored as long as the data encrypted with the CMK is still within Amazon CloudWatch Logs. This enables Amazon CloudWatch Logs to decrypt this data whenever it is
requested>
Note that it can take up to 5 minutes for this operation to take
effect>
If you attempt to associate a CMK with a log group but the CMK does not exist or the CMK is disabled, you will receive an InvalidParameterException error.
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateKmsKeyResponse *>(send(request));
 }
cancelExportTask
CancelExportTaskResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::cancelExportTask (const CancelExportTaskRequest & request) slot
Cancels the specified export
task>
The task must be in the PENDING or RUNNING
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 234 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelExportTaskResponse *>(send(request));
 }
createExportTask
CreateExportTaskResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::createExportTask (const CreateExportTaskRequest & request) slot
Creates an export task, which allows you to efficiently export data from a log group to an Amazon S3
bucket>
This is an asynchronous call. If all the required information is provided, this operation initiates an export task and responds with the ID of the task. After the task has started, you can use DescribeExportTasks to get the status of the export task. Each account can only have one active (RUNNING or PENDING) export task at a time. To cancel an export task, use
CancelExportTask>
You can export logs from multiple log groups or multiple time ranges to the same S3 bucket. To separate out log data for each export task, you can specify a prefix to be used as the Amazon S3 key prefix for all exported
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 260 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateExportTaskResponse *>(send(request));
 }
createLogGroup
CreateLogGroupResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::createLogGroup (const CreateLogGroupRequest & request) slot
Creates a log group with the specified
name>
You can create up to 5000 log groups per
account>
You must use the following guidelines when naming a log
group>
Log group names must be unique within a region for an AWS
account>
Log group names can be between 1 and 512 characters
long>
Log group names consist of the following characters: a-z, A-Z, 0-9, '_' (underscore), '-' (hyphen), '/' (forward slash), and '.'
(period)>
If you associate a AWS Key Management Service (AWS KMS) customer master key (CMK) with the log group, ingested data is encrypted using the CMK. This association is stored as long as the data encrypted with the CMK is still within Amazon CloudWatch Logs. This enables Amazon CloudWatch Logs to decrypt this data whenever it is
requested>
If you attempt to associate a CMK with the log group but the CMK does not exist or the CMK is disabled, you will receive an InvalidParameterException error.
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 306 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLogGroupResponse *>(send(request));
 }
createLogStream
CreateLogStreamResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::createLogStream (const CreateLogStreamRequest & request) slot
Creates a log stream for the specified log
group>
There is no limit on the number of log streams that you can create for a log
group>
You must use the following guidelines when naming a log
stream>
Log stream names must be unique within the log
group>
Log stream names can be between 1 and 512 characters
long>
The ':' (colon) and '*' (asterisk) characters are not
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 340 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLogStreamResponse *>(send(request));
 }
deleteDestination
DeleteDestinationResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteDestination (const DeleteDestinationRequest & request) slot
Deletes the specified destination, and eventually disables all the subscription filters that publish to it. This operation does not delete the physical resource encapsulated by the
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 355 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDestinationResponse *>(send(request));
 }
deleteLogGroup
DeleteLogGroupResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteLogGroup (const DeleteLogGroupRequest & request) slot
Deletes the specified log group and permanently deletes all the archived log events associated with the log
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 369 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLogGroupResponse *>(send(request));
 }
deleteLogStream
DeleteLogStreamResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteLogStream (const DeleteLogStreamRequest & request) slot
Deletes the specified log stream and permanently deletes all the archived log events associated with the log
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 383 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLogStreamResponse *>(send(request));
 }
deleteMetricFilter
DeleteMetricFilterResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteMetricFilter (const DeleteMetricFilterRequest & request) slot
Deletes the specified metric
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 397 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteMetricFilterResponse *>(send(request));
 }
deleteResourcePolicy
DeleteResourcePolicyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteResourcePolicy (const DeleteResourcePolicyRequest & request) slot
Deletes a resource policy from this account. This revokes the access of the identities in that policy to put log events to this
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 412 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteResourcePolicyResponse *>(send(request));
 }
deleteRetentionPolicy
DeleteRetentionPolicyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteRetentionPolicy (const DeleteRetentionPolicyRequest & request) slot
Deletes the specified retention
policy>
Log events do not expire if they belong to log groups without a retention
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 430 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRetentionPolicyResponse *>(send(request));
 }
deleteSubscriptionFilter
DeleteSubscriptionFilterResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteSubscriptionFilter (const DeleteSubscriptionFilterRequest & request) slot
Deletes the specified subscription
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 444 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSubscriptionFilterResponse *>(send(request));
 }
describeDestinations
DescribeDestinationsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeDestinations (const DescribeDestinationsRequest & request) slot
Lists all your destinations. The results are ASCII-sorted by destination
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 458 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDestinationsResponse *>(send(request));
 }
describeExportTasks
DescribeExportTasksResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeExportTasks (const DescribeExportTasksRequest & request) slot
Lists the specified export tasks. You can list all your export tasks or filter the results based on task ID or task
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 472 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeExportTasksResponse *>(send(request));
 }
describeLogGroups
DescribeLogGroupsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeLogGroups (const DescribeLogGroupsRequest & request) slot
Lists the specified log groups. You can list all your log groups or filter the results by prefix. The results are ASCII-sorted by log group
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 487 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLogGroupsResponse *>(send(request));
 }
describeLogStreams
DescribeLogStreamsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeLogStreams (const DescribeLogStreamsRequest & request) slot
Lists the log streams for the specified log group. You can list all the log streams or filter the results by prefix. You can also control how the results are
ordered>
This operation has a limit of five transactions per second, after which transactions are
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 506 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLogStreamsResponse *>(send(request));
 }
describeMetricFilters
DescribeMetricFiltersResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeMetricFilters (const DescribeMetricFiltersRequest & request) slot
Lists the specified metric filters. You can list all the metric filters or filter the results by log name, prefix, metric name, or metric namespace. The results are ASCII-sorted by filter
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 521 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMetricFiltersResponse *>(send(request));
 }
describeResourcePolicies
DescribeResourcePoliciesResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeResourcePolicies (const DescribeResourcePoliciesRequest & request) slot
Lists the resource policies in this
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 535 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeResourcePoliciesResponse *>(send(request));
 }
describeSubscriptionFilters
DescribeSubscriptionFiltersResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::describeSubscriptionFilters (const DescribeSubscriptionFiltersRequest & request) slot
Lists the subscription filters for the specified log group. You can list all the subscription filters or filter the results by prefix. The results are ASCII-sorted by filter
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 550 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSubscriptionFiltersResponse *>(send(request));
 }
disassociateKmsKey
DisassociateKmsKeyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::disassociateKmsKey (const DisassociateKmsKeyRequest & request) slot
Disassociates the associated AWS Key Management Service (AWS KMS) customer master key (CMK) from the specified log
group>
After the AWS KMS CMK is disassociated from the log group, AWS CloudWatch Logs stops encrypting newly ingested data for the log group. All previously ingested data remains encrypted, and AWS CloudWatch Logs requires permissions for the CMK whenever the encrypted data is
requested>
Note that it can take up to 5 minutes for this operation to take
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 574 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateKmsKeyResponse *>(send(request));
 }
filterLogEvents
FilterLogEventsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::filterLogEvents (const FilterLogEventsRequest & request) slot
Lists log events from the specified log group. You can list all the log events or filter the results using a filter pattern, a time range, and the name of the log
stream>
By default, this operation returns as many log events as can fit in 1 MB (up to 10,000 log events), or all the events found within the time range that you specify. If the results include a token, then there are more log events available, and you can get additional results by specifying the token in a subsequent
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 595 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<FilterLogEventsResponse *>(send(request));
 }
getLogEvents
GetLogEventsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::getLogEvents (const GetLogEventsRequest & request) slot
Lists log events from the specified log stream. You can list all the log events or filter using a time
range>
By default, this operation returns as many log events as can fit in a response size of 1MB (up to 10,000 log events). You can get additional log events by specifying one of the tokens in a subsequent
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 614 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetLogEventsResponse *>(send(request));
 }
listTagsLogGroup
ListTagsLogGroupResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::listTagsLogGroup (const ListTagsLogGroupRequest & request) slot
Lists the tags for the specified log
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 628 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsLogGroupResponse *>(send(request));
 }
putDestination
PutDestinationResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putDestination (const PutDestinationRequest & request) slot
Creates or updates a destination. A destination encapsulates a physical resource (such as an Amazon Kinesis stream) and enables you to subscribe to a real-time stream of log events for a different account, ingested using PutLogEvents. Currently, the only supported physical resource is a Kinesis stream belonging to the same account as the
destination>
Through an access policy, a destination controls what is written to its Kinesis stream. By default, PutDestination does not set any access policy with the destination, which means a cross-account user cannot call PutSubscriptionFilter against this destination. To enable this, the destination owner must call PutDestinationPolicy after
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 652 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutDestinationResponse *>(send(request));
 }
putDestinationPolicy
PutDestinationPolicyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putDestinationPolicy (const PutDestinationPolicyRequest & request) slot
Creates or updates an access policy associated with an existing destination. An access policy is an IAM policy document that is used to authorize claims to register a subscription filter against a given
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 668 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutDestinationPolicyResponse *>(send(request));
 }
putLogEvents
PutLogEventsResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putLogEvents (const PutLogEventsRequest & request) slot
Uploads a batch of log events to the specified log
stream>
You must include the sequence token obtained from the response of the previous call. An upload in a newly created log stream does not require a sequence token. You can also get the sequence token using DescribeLogStreams. If you call PutLogEvents twice within a narrow time period using the same value for sequenceToken, both calls may be successful, or one may be
rejected>
The batch of events must satisfy the following
constraints>
The maximum batch size is 1,048,576 bytes, and this size is calculated as the sum of all event messages in UTF-8, plus 26 bytes for each log
event>
None of the log events in the batch can be more than 2 hours in the
future>
None of the log events in the batch can be older than 14 days or the retention period of the log
group>
The log events in the batch must be in chronological ordered by their time stamp (the time the event occurred, expressed as the number of milliseconds after Jan 1, 1970 00:00:00
UTC)>
The maximum number of log events in a batch is
10,000>
A batch of log events in a single request cannot span more than 24 hours. Otherwise, the operation
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutLogEventsResponse *>(send(request));
 }
putMetricFilter
PutMetricFilterResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putMetricFilter (const PutMetricFilterRequest & request) slot
Creates or updates a metric filter and associates it with the specified log group. Metric filters allow you to configure rules to extract metric data from log events ingested through
PutLogEvents>
The maximum number of metric filters that can be associated with a log group is
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 738 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutMetricFilterResponse *>(send(request));
 }
putResourcePolicy
PutResourcePolicyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putResourcePolicy (const PutResourcePolicyRequest & request) slot
Creates or updates a resource policy allowing other AWS services to put log events to this account, such as Amazon Route
An account can have up to 50 resource policies per
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 753 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutResourcePolicyResponse *>(send(request));
 }
putRetentionPolicy
PutRetentionPolicyResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putRetentionPolicy (const PutRetentionPolicyRequest & request) slot
Sets the retention of the specified log group. A retention policy allows you to configure the number of days for which to retain log events in the specified log
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 768 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutRetentionPolicyResponse *>(send(request));
 }
putSubscriptionFilter
PutSubscriptionFilterResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::putSubscriptionFilter (const PutSubscriptionFilterRequest & request) slot
Creates or updates a subscription filter and associates it with the specified log group. Subscription filters allow you to subscribe to a real-time stream of log events ingested through PutLogEvents and have them delivered to a specific destination. Currently, the supported destinations
are>
An Amazon Kinesis stream belonging to the same account as the subscription filter, for same-account
delivery>
A logical destination that belongs to a different account, for cross-account
delivery>
An Amazon Kinesis Firehose delivery stream that belongs to the same account as the subscription filter, for same-account
delivery>
An AWS Lambda function that belongs to the same account as the subscription filter, for same-account
delivery>
There can only be one subscription filter associated with a log group. If you are updating an existing filter, you must specify the correct name in filterName. Otherwise, the call fails because you cannot associate a second filter with a log
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 806 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutSubscriptionFilterResponse *>(send(request));
 }
tagLogGroup
TagLogGroupResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::tagLogGroup (const TagLogGroupRequest & request) slot
Adds or updates the specified tags for the specified log
group>
To list the tags for a log group, use ListTagsLogGroup. To remove tags, use
UntagLogGroup>
For more information about tags, see Tag Log Groups in Amazon CloudWatch Logs in the Amazon CloudWatch Logs User
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 830 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TagLogGroupResponse *>(send(request));
 }
testMetricFilter
TestMetricFilterResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::testMetricFilter (const TestMetricFilterRequest & request) slot
Tests the filter pattern of a metric filter against a sample of log event messages. You can use this operation to validate the correctness of a metric filter
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 845 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestMetricFilterResponse *>(send(request));
 }
untagLogGroup
UntagLogGroupResponse * QtAws::CloudWatchLogs::CloudWatchLogsClient::untagLogGroup (const UntagLogGroupRequest & request) slot
Removes the specified tags from the specified log
group>
To list the tags for a log group, use ListTagsLogGroup. To add tags, use
Parameters
request Request to send to Amazon CloudWatch Logs.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 863 of file cloudwatchlogsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UntagLogGroupResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
logs/cloudwatchlogsclient.h
logs/cloudwatchlogsclient.cpp