AWS SDK for Qt: QtAws::Mobile::MobileClient Class Reference
QtAws::Mobile::MobileClient Class Reference
Client for AWS Mobile.
Public Slots
CreateProjectResponse * createProject (const CreateProjectRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DescribeBundleResponse * describeBundle (const DescribeBundleRequest &request)
DescribeProjectResponse * describeProject (const DescribeProjectRequest &request)
ExportBundleResponse * exportBundle (const ExportBundleRequest &request)
ExportProjectResponse * exportProject (const ExportProjectRequest &request)
ListBundlesResponse * listBundles (const ListBundlesRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
Public Member Functions
MobileClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MobileClient object.
MobileClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MobileClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Mobile.
AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources.
Definition at line 50 of file mobileclient.h.
Constructor & Destructor Documentation
MobileClient() [1/2]
QtAws::Mobile::MobileClient::MobileClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MobileClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 67 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MobileClientPrivate(this), parent)
 {
     Q_D(MobileClient);
     d->apiVersion = QStringLiteral("2017-07-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("mobile");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Mobile");
     d->serviceName = QStringLiteral("AWSMobileHubService");
 }
MobileClient() [2/2]
QtAws::Mobile::MobileClient::MobileClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MobileClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 100 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MobileClientPrivate(this), parent)
 {
     Q_D(MobileClient);
     d->apiVersion = QStringLiteral("2017-07-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("mobile");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Mobile");
     d->serviceName = QStringLiteral("AWSMobileHubService");
 }
Member Function Documentation
createProject
CreateProjectResponse * QtAws::Mobile::MobileClient::createProject (const CreateProjectRequest & request) slot
Creates an AWS Mobile Hub project.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 126 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateProjectResponse *>(send(request));
 }
deleteProject
DeleteProjectResponse * QtAws::Mobile::MobileClient::deleteProject (const DeleteProjectRequest & request) slot
Delets a project in AWS Mobile Hub.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 140 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteProjectResponse *>(send(request));
 }
describeBundle
DescribeBundleResponse * QtAws::Mobile::MobileClient::describeBundle (const DescribeBundleRequest & request) slot
Get the bundle details for the requested bundle id.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 154 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBundleResponse *>(send(request));
 }
describeProject
DescribeProjectResponse * QtAws::Mobile::MobileClient::describeProject (const DescribeProjectRequest & request) slot
Gets details about a project in AWS Mobile Hub.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 168 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeProjectResponse *>(send(request));
 }
exportBundle
ExportBundleResponse * QtAws::Mobile::MobileClient::exportBundle (const ExportBundleRequest & request) slot
Generates customized software development kit (SDK) and or tool packages used to integrate mobile web or mobile app clients with backend AWS resources.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 183 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExportBundleResponse *>(send(request));
 }
exportProject
ExportProjectResponse * QtAws::Mobile::MobileClient::exportProject (const ExportProjectRequest & request) slot
Exports project configuration to a snapshot which can be downloaded and shared. Note that mobile app push credentials are encrypted in exported projects, so they can only be shared successfully within the same AWS account.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 198 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExportProjectResponse *>(send(request));
 }
listBundles
ListBundlesResponse * QtAws::Mobile::MobileClient::listBundles (const ListBundlesRequest & request) slot
List all available bundles.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 212 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBundlesResponse *>(send(request));
 }
listProjects
ListProjectsResponse * QtAws::Mobile::MobileClient::listProjects (const ListProjectsRequest & request) slot
Lists projects in AWS Mobile Hub.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 226 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListProjectsResponse *>(send(request));
 }
updateProject
UpdateProjectResponse * QtAws::Mobile::MobileClient::updateProject (const UpdateProjectRequest & request) slot
Update an existing project.
Parameters
request Request to send to AWS Mobile.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 240 of file mobileclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateProjectResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mobile/mobileclient.h
mobile/mobileclient.cpp