AWS SDK for Qt: QtAws::DeviceFarm::DeviceFarmClient Class Reference
QtAws::DeviceFarm::DeviceFarmClient Class Reference
Client for AWS Device Farm.
Public Slots
CreateDevicePoolResponse * createDevicePool (const CreateDevicePoolRequest &request)
CreateNetworkProfileResponse * createNetworkProfile (const CreateNetworkProfileRequest &request)
CreateProjectResponse * createProject (const CreateProjectRequest &request)
CreateRemoteAccessSessionResponse * createRemoteAccessSession (const CreateRemoteAccessSessionRequest &request)
CreateUploadResponse * createUpload (const CreateUploadRequest &request)
DeleteDevicePoolResponse * deleteDevicePool (const DeleteDevicePoolRequest &request)
DeleteNetworkProfileResponse * deleteNetworkProfile (const DeleteNetworkProfileRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DeleteRemoteAccessSessionResponse * deleteRemoteAccessSession (const DeleteRemoteAccessSessionRequest &request)
DeleteRunResponse * deleteRun (const DeleteRunRequest &request)
DeleteUploadResponse * deleteUpload (const DeleteUploadRequest &request)
GetAccountSettingsResponse * getAccountSettings (const GetAccountSettingsRequest &request)
GetDeviceResponse * getDevice (const GetDeviceRequest &request)
GetDevicePoolResponse * getDevicePool (const GetDevicePoolRequest &request)
GetDevicePoolCompatibilityResponse * getDevicePoolCompatibility (const GetDevicePoolCompatibilityRequest &request)
GetJobResponse * getJob (const GetJobRequest &request)
GetNetworkProfileResponse * getNetworkProfile (const GetNetworkProfileRequest &request)
GetOfferingStatusResponse * getOfferingStatus (const GetOfferingStatusRequest &request)
GetProjectResponse * getProject (const GetProjectRequest &request)
GetRemoteAccessSessionResponse * getRemoteAccessSession (const GetRemoteAccessSessionRequest &request)
GetRunResponse * getRun (const GetRunRequest &request)
GetSuiteResponse * getSuite (const GetSuiteRequest &request)
GetTestResponse * getTest (const GetTestRequest &request)
GetUploadResponse * getUpload (const GetUploadRequest &request)
InstallToRemoteAccessSessionResponse * installToRemoteAccessSession (const InstallToRemoteAccessSessionRequest &request)
ListArtifactsResponse * listArtifacts (const ListArtifactsRequest &request)
ListDevicePoolsResponse * listDevicePools (const ListDevicePoolsRequest &request)
ListDevicesResponse * listDevices (const ListDevicesRequest &request)
ListJobsResponse * listJobs (const ListJobsRequest &request)
ListNetworkProfilesResponse * listNetworkProfiles (const ListNetworkProfilesRequest &request)
ListOfferingPromotionsResponse * listOfferingPromotions (const ListOfferingPromotionsRequest &request)
ListOfferingTransactionsResponse * listOfferingTransactions (const ListOfferingTransactionsRequest &request)
ListOfferingsResponse * listOfferings (const ListOfferingsRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
ListRemoteAccessSessionsResponse * listRemoteAccessSessions (const ListRemoteAccessSessionsRequest &request)
ListRunsResponse * listRuns (const ListRunsRequest &request)
ListSamplesResponse * listSamples (const ListSamplesRequest &request)
ListSuitesResponse * listSuites (const ListSuitesRequest &request)
ListTestsResponse * listTests (const ListTestsRequest &request)
ListUniqueProblemsResponse * listUniqueProblems (const ListUniqueProblemsRequest &request)
ListUploadsResponse * listUploads (const ListUploadsRequest &request)
PurchaseOfferingResponse * purchaseOffering (const PurchaseOfferingRequest &request)
RenewOfferingResponse * renewOffering (const RenewOfferingRequest &request)
ScheduleRunResponse * scheduleRun (const ScheduleRunRequest &request)
StopRemoteAccessSessionResponse * stopRemoteAccessSession (const StopRemoteAccessSessionRequest &request)
StopRunResponse * stopRun (const StopRunRequest &request)
UpdateDevicePoolResponse * updateDevicePool (const UpdateDevicePoolRequest &request)
UpdateNetworkProfileResponse * updateNetworkProfile (const UpdateNetworkProfileRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
Public Member Functions
DeviceFarmClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
DeviceFarmClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Device Farm.
AWS Device Farm is a service that enables mobile app developers to test Android, iOS, and Fire OS apps on physical phones, tablets, and other devices in the
Definition at line 130 of file devicefarmclient.h.
Constructor & Destructor Documentation
DeviceFarmClient() [1/2]
QtAws::DeviceFarm::DeviceFarmClient::DeviceFarmClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 146 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->apiVersion = QStringLiteral("2015-06-23");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("devicefarm");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Device Farm");
     d->serviceName = QStringLiteral("devicefarm");
 }
DeviceFarmClient() [2/2]
QtAws::DeviceFarm::DeviceFarmClient::DeviceFarmClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 179 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->apiVersion = QStringLiteral("2015-06-23");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("devicefarm");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Device Farm");
     d->serviceName = QStringLiteral("devicefarm");
 }
Member Function Documentation
createDevicePool
CreateDevicePoolResponse * QtAws::DeviceFarm::DeviceFarmClient::createDevicePool (const CreateDevicePoolRequest & request) slot
Creates a device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 205 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateDevicePoolResponse *>(send(request));
 }
createNetworkProfile
CreateNetworkProfileResponse * QtAws::DeviceFarm::DeviceFarmClient::createNetworkProfile (const CreateNetworkProfileRequest & request) slot
Creates a network
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 219 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateNetworkProfileResponse *>(send(request));
 }
createProject
CreateProjectResponse * QtAws::DeviceFarm::DeviceFarmClient::createProject (const CreateProjectRequest & request) slot
Creates a new
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 233 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateProjectResponse *>(send(request));
 }
createRemoteAccessSession
CreateRemoteAccessSessionResponse * QtAws::DeviceFarm::DeviceFarmClient::createRemoteAccessSession (const CreateRemoteAccessSessionRequest & request) slot
Specifies and starts a remote access
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 247 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRemoteAccessSessionResponse *>(send(request));
 }
createUpload
CreateUploadResponse * QtAws::DeviceFarm::DeviceFarmClient::createUpload (const CreateUploadRequest & request) slot
Uploads an app or test
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 261 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUploadResponse *>(send(request));
 }
deleteDevicePool
DeleteDevicePoolResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteDevicePool (const DeleteDevicePoolRequest & request) slot
Deletes a device pool given the pool ARN. Does not allow deletion of curated pools owned by the
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 275 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDevicePoolResponse *>(send(request));
 }
deleteNetworkProfile
DeleteNetworkProfileResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteNetworkProfile (const DeleteNetworkProfileRequest & request) slot
Deletes a network
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 289 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNetworkProfileResponse *>(send(request));
 }
deleteProject
DeleteProjectResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteProject (const DeleteProjectRequest & request) slot
Deletes an AWS Device Farm project, given the project
ARN>
Note Deleting this resource does not stop an in-progress
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 307 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteProjectResponse *>(send(request));
 }
deleteRemoteAccessSession
DeleteRemoteAccessSessionResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteRemoteAccessSession (const DeleteRemoteAccessSessionRequest & request) slot
Deletes a completed remote access session and its
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 321 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRemoteAccessSessionResponse *>(send(request));
 }
deleteRun
DeleteRunResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteRun (const DeleteRunRequest & request) slot
Deletes the run, given the run
ARN>
Note Deleting this resource does not stop an in-progress
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 339 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRunResponse *>(send(request));
 }
deleteUpload
DeleteUploadResponse * QtAws::DeviceFarm::DeviceFarmClient::deleteUpload (const DeleteUploadRequest & request) slot
Deletes an upload given the upload
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 353 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUploadResponse *>(send(request));
 }
getAccountSettings
GetAccountSettingsResponse * QtAws::DeviceFarm::DeviceFarmClient::getAccountSettings (const GetAccountSettingsRequest & request) slot
Returns the number of unmetered iOS and/or unmetered Android devices that have been purchased by the
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 367 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountSettingsResponse *>(send(request));
 }
getDevice
GetDeviceResponse * QtAws::DeviceFarm::DeviceFarmClient::getDevice (const GetDeviceRequest & request) slot
Gets information about a unique device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 381 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDeviceResponse *>(send(request));
 }
getDevicePool
GetDevicePoolResponse * QtAws::DeviceFarm::DeviceFarmClient::getDevicePool (const GetDevicePoolRequest & request) slot
Gets information about a device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 395 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDevicePoolResponse *>(send(request));
 }
getDevicePoolCompatibility
GetDevicePoolCompatibilityResponse * QtAws::DeviceFarm::DeviceFarmClient::getDevicePoolCompatibility (const GetDevicePoolCompatibilityRequest & request) slot
Gets information about compatibility with a device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 409 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetDevicePoolCompatibilityResponse *>(send(request));
 }
getJob
GetJobResponse * QtAws::DeviceFarm::DeviceFarmClient::getJob (const GetJobRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 423 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetJobResponse *>(send(request));
 }
getNetworkProfile
GetNetworkProfileResponse * QtAws::DeviceFarm::DeviceFarmClient::getNetworkProfile (const GetNetworkProfileRequest & request) slot
Returns information about a network
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 437 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetNetworkProfileResponse *>(send(request));
 }
getOfferingStatus
GetOfferingStatusResponse * QtAws::DeviceFarm::DeviceFarmClient::getOfferingStatus (const GetOfferingStatusRequest & request) slot
Gets the current status and future status of all offerings purchased by an AWS account. The response indicates how many offerings are currently available and the offerings that will be available in the next period. The API returns a NotEligible error if the user is not permitted to invoke the operation. Please contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 455 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetOfferingStatusResponse *>(send(request));
 }
getProject
GetProjectResponse * QtAws::DeviceFarm::DeviceFarmClient::getProject (const GetProjectRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 469 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetProjectResponse *>(send(request));
 }
getRemoteAccessSession
GetRemoteAccessSessionResponse * QtAws::DeviceFarm::DeviceFarmClient::getRemoteAccessSession (const GetRemoteAccessSessionRequest & request) slot
Returns a link to a currently running remote access
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 483 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRemoteAccessSessionResponse *>(send(request));
 }
getRun
GetRunResponse * QtAws::DeviceFarm::DeviceFarmClient::getRun (const GetRunRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 497 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRunResponse *>(send(request));
 }
getSuite
GetSuiteResponse * QtAws::DeviceFarm::DeviceFarmClient::getSuite (const GetSuiteRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 511 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSuiteResponse *>(send(request));
 }
getTest
GetTestResponse * QtAws::DeviceFarm::DeviceFarmClient::getTest (const GetTestRequest & request) slot
Gets information about a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 525 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTestResponse *>(send(request));
 }
getUpload
GetUploadResponse * QtAws::DeviceFarm::DeviceFarmClient::getUpload (const GetUploadRequest & request) slot
Gets information about an
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 539 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUploadResponse *>(send(request));
 }
installToRemoteAccessSession
InstallToRemoteAccessSessionResponse * QtAws::DeviceFarm::DeviceFarmClient::installToRemoteAccessSession (const InstallToRemoteAccessSessionRequest & request) slot
Installs an application to the device in a remote access session. For Android applications, the file must be in .apk format. For iOS applications, the file must be in .ipa
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 554 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InstallToRemoteAccessSessionResponse *>(send(request));
 }
listArtifacts
ListArtifactsResponse * QtAws::DeviceFarm::DeviceFarmClient::listArtifacts (const ListArtifactsRequest & request) slot
Gets information about
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 568 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListArtifactsResponse *>(send(request));
 }
listDevicePools
ListDevicePoolsResponse * QtAws::DeviceFarm::DeviceFarmClient::listDevicePools (const ListDevicePoolsRequest & request) slot
Gets information about device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 582 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDevicePoolsResponse *>(send(request));
 }
listDevices
ListDevicesResponse * QtAws::DeviceFarm::DeviceFarmClient::listDevices (const ListDevicesRequest & request) slot
Gets information about unique device
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 596 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDevicesResponse *>(send(request));
 }
listJobs
ListJobsResponse * QtAws::DeviceFarm::DeviceFarmClient::listJobs (const ListJobsRequest & request) slot
Gets information about jobs for a given test
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 610 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListJobsResponse *>(send(request));
 }
listNetworkProfiles
ListNetworkProfilesResponse * QtAws::DeviceFarm::DeviceFarmClient::listNetworkProfiles (const ListNetworkProfilesRequest & request) slot
Returns the list of available network
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 624 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListNetworkProfilesResponse *>(send(request));
 }
listOfferingPromotions
ListOfferingPromotionsResponse * QtAws::DeviceFarm::DeviceFarmClient::listOfferingPromotions (const ListOfferingPromotionsRequest & request) slot
Returns a list of offering promotions. Each offering promotion record contains the ID and description of the promotion. The API returns a NotEligible error if the caller is not permitted to invoke the operation. Contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 641 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOfferingPromotionsResponse *>(send(request));
 }
listOfferings
ListOfferingsResponse * QtAws::DeviceFarm::DeviceFarmClient::listOfferings (const ListOfferingsRequest & request) slot
Returns a list of products or offerings that the user can manage through the API. Each offering record indicates the recurring price per unit and the frequency for that offering. The API returns a NotEligible error if the user is not permitted to invoke the operation. Please contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 677 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOfferingsResponse *>(send(request));
 }
listOfferingTransactions
ListOfferingTransactionsResponse * QtAws::DeviceFarm::DeviceFarmClient::listOfferingTransactions (const ListOfferingTransactionsRequest & request) slot
Returns a list of all historical purchases, renewals, and system renewal transactions for an AWS account. The list is paginated and ordered by a descending timestamp (most recent transactions are first). The API returns a NotEligible error if the user is not permitted to invoke the operation. Please contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 659 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListOfferingTransactionsResponse *>(send(request));
 }
listProjects
ListProjectsResponse * QtAws::DeviceFarm::DeviceFarmClient::listProjects (const ListProjectsRequest & request) slot
Gets information about
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 691 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListProjectsResponse *>(send(request));
 }
listRemoteAccessSessions
ListRemoteAccessSessionsResponse * QtAws::DeviceFarm::DeviceFarmClient::listRemoteAccessSessions (const ListRemoteAccessSessionsRequest & request) slot
Returns a list of all currently running remote access
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 705 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRemoteAccessSessionsResponse *>(send(request));
 }
listRuns
ListRunsResponse * QtAws::DeviceFarm::DeviceFarmClient::listRuns (const ListRunsRequest & request) slot
Gets information about runs, given an AWS Device Farm project
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 719 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRunsResponse *>(send(request));
 }
listSamples
ListSamplesResponse * QtAws::DeviceFarm::DeviceFarmClient::listSamples (const ListSamplesRequest & request) slot
Gets information about samples, given an AWS Device Farm project
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 733 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSamplesResponse *>(send(request));
 }
listSuites
ListSuitesResponse * QtAws::DeviceFarm::DeviceFarmClient::listSuites (const ListSuitesRequest & request) slot
Gets information about test suites for a given
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 747 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSuitesResponse *>(send(request));
 }
listTests
ListTestsResponse * QtAws::DeviceFarm::DeviceFarmClient::listTests (const ListTestsRequest & request) slot
Gets information about tests in a given test
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 761 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTestsResponse *>(send(request));
 }
listUniqueProblems
ListUniqueProblemsResponse * QtAws::DeviceFarm::DeviceFarmClient::listUniqueProblems (const ListUniqueProblemsRequest & request) slot
Gets information about unique
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 775 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUniqueProblemsResponse *>(send(request));
 }
listUploads
ListUploadsResponse * QtAws::DeviceFarm::DeviceFarmClient::listUploads (const ListUploadsRequest & request) slot
Gets information about uploads, given an AWS Device Farm project
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 789 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUploadsResponse *>(send(request));
 }
purchaseOffering
PurchaseOfferingResponse * QtAws::DeviceFarm::DeviceFarmClient::purchaseOffering (const PurchaseOfferingRequest & request) slot
Immediately purchases offerings for an AWS account. Offerings renew with the latest total purchased quantity for an offering, unless the renewal was overridden. The API returns a NotEligible error if the user is not permitted to invoke the operation. Please contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 807 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PurchaseOfferingResponse *>(send(request));
 }
renewOffering
RenewOfferingResponse * QtAws::DeviceFarm::DeviceFarmClient::renewOffering (const RenewOfferingRequest & request) slot
Explicitly sets the quantity of devices to renew for an offering, starting from the effectiveDate of the next period. The API returns a NotEligible error if the user is not permitted to invoke the operation. Please contact aws-devicefarm-support@amazon.com if you believe that you should be able to invoke this
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 824 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RenewOfferingResponse *>(send(request));
 }
scheduleRun
ScheduleRunResponse * QtAws::DeviceFarm::DeviceFarmClient::scheduleRun (const ScheduleRunRequest & request) slot
Schedules a
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 838 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ScheduleRunResponse *>(send(request));
 }
stopRemoteAccessSession
StopRemoteAccessSessionResponse * QtAws::DeviceFarm::DeviceFarmClient::stopRemoteAccessSession (const StopRemoteAccessSessionRequest & request) slot
Ends a specified remote access
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 852 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopRemoteAccessSessionResponse *>(send(request));
 }
stopRun
StopRunResponse * QtAws::DeviceFarm::DeviceFarmClient::stopRun (const StopRunRequest & request) slot
Initiates a stop request for the current test run. AWS Device Farm will immediately stop the run on devices where tests have not started executing, and you will not be billed for these devices. On devices where tests have started executing, Setup Suite and Teardown Suite tests will run to completion before stopping execution on those devices. You will be billed for Setup, Teardown, and any tests that were in progress or already
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 869 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopRunResponse *>(send(request));
 }
updateDevicePool
UpdateDevicePoolResponse * QtAws::DeviceFarm::DeviceFarmClient::updateDevicePool (const UpdateDevicePoolRequest & request) slot
Modifies the name, description, and rules in a device pool given the attributes and the pool ARN. Rule updates are all-or-nothing, meaning they can only be updated as a whole (or not at
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 884 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateDevicePoolResponse *>(send(request));
 }
updateNetworkProfile
UpdateNetworkProfileResponse * QtAws::DeviceFarm::DeviceFarmClient::updateNetworkProfile (const UpdateNetworkProfileRequest & request) slot
Updates the network profile with specific
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 898 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateNetworkProfileResponse *>(send(request));
 }
updateProject
UpdateProjectResponse * QtAws::DeviceFarm::DeviceFarmClient::updateProject (const UpdateProjectRequest & request) slot
Modifies the specified project name, given the project ARN and a new
Parameters
request Request to send to AWS Device Farm.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 912 of file devicefarmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateProjectResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
devicefarm/devicefarmclient.h
devicefarm/devicefarmclient.cpp