AWS SDK for Qt: QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient Class Reference
QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient Class Reference
Client for AWS Database Migration Service.
Public Slots
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
CreateEndpointResponse * createEndpoint (const CreateEndpointRequest &request)
CreateEventSubscriptionResponse * createEventSubscription (const CreateEventSubscriptionRequest &request)
CreateReplicationInstanceResponse * createReplicationInstance (const CreateReplicationInstanceRequest &request)
CreateReplicationSubnetGroupResponse * createReplicationSubnetGroup (const CreateReplicationSubnetGroupRequest &request)
CreateReplicationTaskResponse * createReplicationTask (const CreateReplicationTaskRequest &request)
DeleteCertificateResponse * deleteCertificate (const DeleteCertificateRequest &request)
DeleteEndpointResponse * deleteEndpoint (const DeleteEndpointRequest &request)
DeleteEventSubscriptionResponse * deleteEventSubscription (const DeleteEventSubscriptionRequest &request)
DeleteReplicationInstanceResponse * deleteReplicationInstance (const DeleteReplicationInstanceRequest &request)
DeleteReplicationSubnetGroupResponse * deleteReplicationSubnetGroup (const DeleteReplicationSubnetGroupRequest &request)
DeleteReplicationTaskResponse * deleteReplicationTask (const DeleteReplicationTaskRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes (const DescribeAccountAttributesRequest &request)
DescribeCertificatesResponse * describeCertificates (const DescribeCertificatesRequest &request)
DescribeConnectionsResponse * describeConnections (const DescribeConnectionsRequest &request)
DescribeEndpointTypesResponse * describeEndpointTypes (const DescribeEndpointTypesRequest &request)
DescribeEndpointsResponse * describeEndpoints (const DescribeEndpointsRequest &request)
DescribeEventCategoriesResponse * describeEventCategories (const DescribeEventCategoriesRequest &request)
DescribeEventSubscriptionsResponse * describeEventSubscriptions (const DescribeEventSubscriptionsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeOrderableReplicationInstancesResponse * describeOrderableReplicationInstances (const DescribeOrderableReplicationInstancesRequest &request)
DescribeRefreshSchemasStatusResponse * describeRefreshSchemasStatus (const DescribeRefreshSchemasStatusRequest &request)
DescribeReplicationInstanceTaskLogsResponse * describeReplicationInstanceTaskLogs (const DescribeReplicationInstanceTaskLogsRequest &request)
DescribeReplicationInstancesResponse * describeReplicationInstances (const DescribeReplicationInstancesRequest &request)
DescribeReplicationSubnetGroupsResponse * describeReplicationSubnetGroups (const DescribeReplicationSubnetGroupsRequest &request)
DescribeReplicationTaskAssessmentResultsResponse * describeReplicationTaskAssessmentResults (const DescribeReplicationTaskAssessmentResultsRequest &request)
DescribeReplicationTasksResponse * describeReplicationTasks (const DescribeReplicationTasksRequest &request)
DescribeSchemasResponse * describeSchemas (const DescribeSchemasRequest &request)
DescribeTableStatisticsResponse * describeTableStatistics (const DescribeTableStatisticsRequest &request)
ImportCertificateResponse * importCertificate (const ImportCertificateRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyEndpointResponse * modifyEndpoint (const ModifyEndpointRequest &request)
ModifyEventSubscriptionResponse * modifyEventSubscription (const ModifyEventSubscriptionRequest &request)
ModifyReplicationInstanceResponse * modifyReplicationInstance (const ModifyReplicationInstanceRequest &request)
ModifyReplicationSubnetGroupResponse * modifyReplicationSubnetGroup (const ModifyReplicationSubnetGroupRequest &request)
ModifyReplicationTaskResponse * modifyReplicationTask (const ModifyReplicationTaskRequest &request)
RebootReplicationInstanceResponse * rebootReplicationInstance (const RebootReplicationInstanceRequest &request)
RefreshSchemasResponse * refreshSchemas (const RefreshSchemasRequest &request)
ReloadTablesResponse * reloadTables (const ReloadTablesRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
StartReplicationTaskResponse * startReplicationTask (const StartReplicationTaskRequest &request)
StartReplicationTaskAssessmentResponse * startReplicationTaskAssessment (const StartReplicationTaskAssessmentRequest &request)
StopReplicationTaskResponse * stopReplicationTask (const StopReplicationTaskRequest &request)
TestConnectionResponse * testConnection (const TestConnectionRequest &request)
Public Member Functions
DatabaseMigrationServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DatabaseMigrationServiceClient object.
DatabaseMigrationServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DatabaseMigrationServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Database Migration Service.
<fullname>AWS Database Migration Service</fullname>
AWS Database Migration Service (AWS DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to
PostgreSQL>
For more information about AWS DMS, see the AWS DMS user guide at What Is AWS Database Migration Service?
Definition at line 120 of file databasemigrationserviceclient.h.
Constructor & Destructor Documentation
DatabaseMigrationServiceClient() [1/2]
QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DatabaseMigrationServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 145 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DatabaseMigrationServiceClientPrivate(this), parent)
 {
     Q_D(DatabaseMigrationServiceClient);
     d->apiVersion = QStringLiteral("2016-01-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("dms");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Database Migration Service");
     d->serviceName = QStringLiteral("dms");
 }
DatabaseMigrationServiceClient() [2/2]
QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DatabaseMigrationServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 178 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DatabaseMigrationServiceClientPrivate(this), parent)
 {
     Q_D(DatabaseMigrationServiceClient);
     d->apiVersion = QStringLiteral("2016-01-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("dms");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Database Migration Service");
     d->serviceName = QStringLiteral("dms");
 }
Member Function Documentation
addTagsToResource
AddTagsToResourceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::addTagsToResource (const AddTagsToResourceRequest & request) slot
Adds metadata tags to a DMS resource, including replication instance, endpoint, security group, and migration task. These tags can also be used with cost allocation reporting to track cost associated with DMS resources, or used in a Condition statement in an IAM policy for
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 206 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsToResourceResponse *>(send(request));
 }
createEndpoint
CreateEndpointResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createEndpoint (const CreateEndpointRequest & request) slot
Creates an endpoint using the provided
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 220 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEndpointResponse *>(send(request));
 }
createEventSubscription
CreateEventSubscriptionResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createEventSubscription (const CreateEventSubscriptionRequest & request) slot
Creates an AWS DMS event notification subscription.
</p
You can specify the type of source (SourceType) you want to be notified of, provide a list of AWS DMS source IDs (SourceIds) that triggers the events, and provide a list of event categories (EventCategories) for events you want to be notified of. If you specify both the SourceType and SourceIds, such as SourceType = replication-instance and SourceIdentifier = my-replinstance, you will be notified of all the replication instance events for the specified source. If you specify a SourceType but don't specify a SourceIdentifier, you receive notice of the events for that source type for all your AWS DMS sources. If you don't specify either SourceType nor SourceIdentifier, you will be notified of events generated from all AWS DMS sources belonging to your customer
account>
For more information about AWS DMS events, see Working with Events and Notifications in the AWS Database MIgration Service User
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 252 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateEventSubscriptionResponse *>(send(request));
 }
createReplicationInstance
CreateReplicationInstanceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationInstance (const CreateReplicationInstanceRequest & request) slot
Creates the replication instance using the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 266 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReplicationInstanceResponse *>(send(request));
 }
createReplicationSubnetGroup
CreateReplicationSubnetGroupResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationSubnetGroup (const CreateReplicationSubnetGroupRequest & request) slot
Creates a replication subnet group given a list of the subnet IDs in a
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 280 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReplicationSubnetGroupResponse *>(send(request));
 }
createReplicationTask
CreateReplicationTaskResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationTask (const CreateReplicationTaskRequest & request) slot
Creates a replication task using the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 294 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReplicationTaskResponse *>(send(request));
 }
deleteCertificate
DeleteCertificateResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteCertificate (const DeleteCertificateRequest & request) slot
Deletes the specified certificate.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 308 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCertificateResponse *>(send(request));
 }
deleteEndpoint
DeleteEndpointResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteEndpoint (const DeleteEndpointRequest & request) slot
Deletes the specified
endpoint> <note>
All tasks associated with the endpoint must be deleted before you can delete the
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 326 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEndpointResponse *>(send(request));
 }
deleteEventSubscription
DeleteEventSubscriptionResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteEventSubscription (const DeleteEventSubscriptionRequest & request) slot
Deletes an AWS DMS event subscription.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 340 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteEventSubscriptionResponse *>(send(request));
 }
deleteReplicationInstance
DeleteReplicationInstanceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationInstance (const DeleteReplicationInstanceRequest & request) slot
Deletes the specified replication
instance> <note>
You must delete any migration tasks that are associated with the replication instance before you can delete
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 358 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReplicationInstanceResponse *>(send(request));
 }
deleteReplicationSubnetGroup
DeleteReplicationSubnetGroupResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationSubnetGroup (const DeleteReplicationSubnetGroupRequest & request) slot
Deletes a subnet
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 372 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReplicationSubnetGroupResponse *>(send(request));
 }
deleteReplicationTask
DeleteReplicationTaskResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationTask (const DeleteReplicationTaskRequest & request) slot
Deletes the specified replication
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 386 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReplicationTaskResponse *>(send(request));
 }
describeAccountAttributes
DescribeAccountAttributesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeAccountAttributes (const DescribeAccountAttributesRequest & request) slot
Lists all of the AWS DMS attributes for a customer account. The attributes include AWS DMS quotas for the account, such as the number of replication instances allowed. The description for a quota includes the quota name, current usage toward that quota, and the quota's maximum
value>
This command does not take any
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountAttributesResponse *>(send(request));
 }
describeCertificates
DescribeCertificatesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeCertificates (const DescribeCertificatesRequest & request) slot
Provides a description of the
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeCertificatesResponse *>(send(request));
 }
describeConnections
DescribeConnectionsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeConnections (const DescribeConnectionsRequest & request) slot
Describes the status of the connections that have been made between the replication instance and an endpoint. Connections are created when you test an
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 435 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConnectionsResponse *>(send(request));
 }
describeEndpoints
DescribeEndpointsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEndpoints (const DescribeEndpointsRequest & request) slot
Returns information about the endpoints for your account in the current
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 463 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEndpointsResponse *>(send(request));
 }
describeEndpointTypes
DescribeEndpointTypesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEndpointTypes (const DescribeEndpointTypesRequest & request) slot
Returns information about the type of endpoints
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 449 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEndpointTypesResponse *>(send(request));
 }
describeEventCategories
DescribeEventCategoriesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEventCategories (const DescribeEventCategoriesRequest & request) slot
Lists categories for all event source types, or, if specified, for a specified source type. You can see a list of the event categories and source types in Working with Events and Notifications in the AWS Database Migration Service User Guide.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 479 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventCategoriesResponse *>(send(request));
 }
describeEvents
DescribeEventsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEvents (const DescribeEventsRequest & request) slot
Lists events for a given source identifier and source type. You can also specify a start and end time. For more information on AWS DMS events, see Working with Events and Notifications .
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 515 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventsResponse *>(send(request));
 }
describeEventSubscriptions
DescribeEventSubscriptionsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEventSubscriptions (const DescribeEventSubscriptionsRequest & request) slot
Lists all the event subscriptions for a customer account. The description of a subscription includes SubscriptionName, SNSTopicARN, CustomerID, SourceType, SourceID, CreationTime, and Status.
</p
If you specify SubscriptionName, this action lists the description for that
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 499 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeEventSubscriptionsResponse *>(send(request));
 }
describeOrderableReplicationInstances
DescribeOrderableReplicationInstancesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeOrderableReplicationInstances (const DescribeOrderableReplicationInstancesRequest & request) slot
Returns information about the replication instance types that can be created in the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 529 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeOrderableReplicationInstancesResponse *>(send(request));
 }
describeRefreshSchemasStatus
DescribeRefreshSchemasStatusResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeRefreshSchemasStatus (const DescribeRefreshSchemasStatusRequest & request) slot
Returns the status of the RefreshSchemas
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 543 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeRefreshSchemasStatusResponse *>(send(request));
 }
describeReplicationInstances
DescribeReplicationInstancesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationInstances (const DescribeReplicationInstancesRequest & request) slot
Returns information about replication instances for your account in the current
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 571 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReplicationInstancesResponse *>(send(request));
 }
describeReplicationInstanceTaskLogs
DescribeReplicationInstanceTaskLogsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationInstanceTaskLogs (const DescribeReplicationInstanceTaskLogsRequest & request) slot
Returns information about the task logs for the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 557 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReplicationInstanceTaskLogsResponse *>(send(request));
 }
describeReplicationSubnetGroups
DescribeReplicationSubnetGroupsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationSubnetGroups (const DescribeReplicationSubnetGroupsRequest & request) slot
Returns information about the replication subnet
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 585 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReplicationSubnetGroupsResponse *>(send(request));
 }
describeReplicationTaskAssessmentResults
DescribeReplicationTaskAssessmentResultsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationTaskAssessmentResults (const DescribeReplicationTaskAssessmentResultsRequest & request) slot
Returns the task assessment results from Amazon S3. This action always returns the latest
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 599 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReplicationTaskAssessmentResultsResponse *>(send(request));
 }
describeReplicationTasks
DescribeReplicationTasksResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationTasks (const DescribeReplicationTasksRequest & request) slot
Returns information about replication tasks for your account in the current
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 613 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReplicationTasksResponse *>(send(request));
 }
describeSchemas
DescribeSchemasResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeSchemas (const DescribeSchemasRequest & request) slot
Returns information about the schema for the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 627 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSchemasResponse *>(send(request));
 }
describeTableStatistics
DescribeTableStatisticsResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeTableStatistics (const DescribeTableStatisticsRequest & request) slot
Returns table statistics on the database migration task, including table name, rows inserted, rows updated, and rows
deleted>
Note that the "last updated" column the DMS console only indicates the time that AWS DMS last updated the table statistics record for a table. It does not indicate the time of the last update to the
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 646 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTableStatisticsResponse *>(send(request));
 }
importCertificate
ImportCertificateResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::importCertificate (const ImportCertificateRequest & request) slot
Uploads the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 660 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ImportCertificateResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::listTagsForResource (const ListTagsForResourceRequest & request) slot
Lists all tags for an AWS DMS
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 674 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
modifyEndpoint
ModifyEndpointResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyEndpoint (const ModifyEndpointRequest & request) slot
Modifies the specified
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 688 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyEndpointResponse *>(send(request));
 }
modifyEventSubscription
ModifyEventSubscriptionResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyEventSubscription (const ModifyEventSubscriptionRequest & request) slot
Modifies an existing AWS DMS event notification subscription.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 702 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyEventSubscriptionResponse *>(send(request));
 }
modifyReplicationInstance
ModifyReplicationInstanceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationInstance (const ModifyReplicationInstanceRequest & request) slot
Modifies the replication instance to apply new settings. You can change one or more parameters by specifying these parameters and the new values in the
request>
Some settings are applied during the maintenance
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 721 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyReplicationInstanceResponse *>(send(request));
 }
modifyReplicationSubnetGroup
ModifyReplicationSubnetGroupResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationSubnetGroup (const ModifyReplicationSubnetGroupRequest & request) slot
Modifies the settings for the specified replication subnet
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 735 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyReplicationSubnetGroupResponse *>(send(request));
 }
modifyReplicationTask
ModifyReplicationTaskResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationTask (const ModifyReplicationTaskRequest & request) slot
Modifies the specified replication
task>
You can't modify the task endpoints. The task must be stopped before you can modify it.
</p
For more information about AWS DMS tasks, see the AWS DMS user guide at Working with Migration Tasks
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 758 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyReplicationTaskResponse *>(send(request));
 }
rebootReplicationInstance
RebootReplicationInstanceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::rebootReplicationInstance (const RebootReplicationInstanceRequest & request) slot
Reboots a replication instance. Rebooting results in a momentary outage, until the replication instance becomes available
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 773 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootReplicationInstanceResponse *>(send(request));
 }
refreshSchemas
RefreshSchemasResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::refreshSchemas (const RefreshSchemasRequest & request) slot
Populates the schema for the specified endpoint. This is an asynchronous operation and can take several minutes. You can check the status of this operation by calling the DescribeRefreshSchemasStatus
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 788 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RefreshSchemasResponse *>(send(request));
 }
reloadTables
ReloadTablesResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::reloadTables (const ReloadTablesRequest & request) slot
Reloads the target database table with the source data.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 802 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReloadTablesResponse *>(send(request));
 }
removeTagsFromResource
RemoveTagsFromResourceResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::removeTagsFromResource (const RemoveTagsFromResourceRequest & request) slot
Removes metadata tags from a DMS
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 816 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsFromResourceResponse *>(send(request));
 }
startReplicationTask
StartReplicationTaskResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::startReplicationTask (const StartReplicationTaskRequest & request) slot
Starts the replication
task>
For more information about AWS DMS tasks, see the AWS DMS user guide at Working with Migration Tasks
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 835 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartReplicationTaskResponse *>(send(request));
 }
startReplicationTaskAssessment
StartReplicationTaskAssessmentResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::startReplicationTaskAssessment (const StartReplicationTaskAssessmentRequest & request) slot
Starts the replication task assessment for unsupported data types in the source database.
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 849 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartReplicationTaskAssessmentResponse *>(send(request));
 }
stopReplicationTask
StopReplicationTaskResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::stopReplicationTask (const StopReplicationTaskRequest & request) slot
Stops the replication
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 863 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopReplicationTaskResponse *>(send(request));
 }
testConnection
TestConnectionResponse * QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::testConnection (const TestConnectionRequest & request) slot
Tests the connection between the replication instance and the
Parameters
request Request to send to AWS Database Migration Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 877 of file databasemigrationserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestConnectionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
dms/databasemigrationserviceclient.h
dms/databasemigrationserviceclient.cpp