AWS SDK for Qt: QtAws::DynamoDBStreams::DynamoDBStreamsClient Class Reference
QtAws::DynamoDBStreams::DynamoDBStreamsClient Class Reference
Client for Amazon DynamoDB Streams.
Public Slots
DescribeStreamResponse * describeStream (const DescribeStreamRequest &request)
GetRecordsResponse * getRecords (const GetRecordsRequest &request)
GetShardIteratorResponse * getShardIterator (const GetShardIteratorRequest &request)
ListStreamsResponse * listStreams (const ListStreamsRequest &request)
Public Member Functions
DynamoDBStreamsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBStreamsClient object.
DynamoDBStreamsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBStreamsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon DynamoDB Streams.
<fullname>Amazon DynamoDB Streams</fullname>
This is the Amazon DynamoDB Streams API Reference. This guide describes the low-level API actions for accessing streams and processing stream records. For information about application development with DynamoDB Streams, see the Amazon DynamoDB Developer Guide>
Note that this document is intended for use with the following DynamoDB
documentation>
Amazon DynamoDB Developer Guide
</p
Amazon DynamoDB API Reference
</p
The following are short descriptions of each low-level DynamoDB Streams API action, organized by
function>
DescribeStream - Returns detailed information about a particular stream.
GetRecords - Retrieves the stream records from within a
shard>
GetShardIterator - Returns information on how to retrieve the streams record from a shard with a given shard
ID>
ListStreams - Returns a list of all the streams associated with the current AWS account and
Definition at line 40 of file dynamodbstreamsclient.h.
Constructor & Destructor Documentation
DynamoDBStreamsClient() [1/2]
QtAws::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBStreamsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 87 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DynamoDBStreamsClientPrivate(this), parent)
 {
     Q_D(DynamoDBStreamsClient);
     d->apiVersion = QStringLiteral("2012-08-10");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("streams.dynamodb");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon DynamoDB Streams");
     d->serviceName = QStringLiteral("dynamodb");
 }
DynamoDBStreamsClient() [2/2]
QtAws::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBStreamsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 120 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DynamoDBStreamsClientPrivate(this), parent)
 {
     Q_D(DynamoDBStreamsClient);
     d->apiVersion = QStringLiteral("2012-08-10");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("streams.dynamodb");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon DynamoDB Streams");
     d->serviceName = QStringLiteral("dynamodb");
 }
Member Function Documentation
describeStream
DescribeStreamResponse * QtAws::DynamoDBStreams::DynamoDBStreamsClient::describeStream (const DescribeStreamRequest & request) slot
Returns information about a stream, including the current status of the stream, its Amazon Resource Name (ARN), the composition of its shards, and its corresponding DynamoDB
table> <note>
You can call DescribeStream at a maximum rate of 10 times per second.
</note>
Each shard in the stream has a SequenceNumberRange associated with it. If the SequenceNumberRange has a StartingSequenceNumber but no EndingSequenceNumber, then the shard is still open (able to receive more stream records). If both StartingSequenceNumber and EndingSequenceNumber are present, the that shared is closed and can no longer receive more
Parameters
request Request to send to Amazon DynamoDB Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 154 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStreamResponse *>(send(request));
 }
getRecords
GetRecordsResponse * QtAws::DynamoDBStreams::DynamoDBStreamsClient::getRecords (const GetRecordsRequest & request) slot
Retrieves the stream records from a given
shard>
Specify a shard iterator using the ShardIterator parameter. The shard iterator specifies the position in the shard from which you want to start reading stream records sequentially. If there are no stream records available in the portion of the shard that the iterator points to, GetRecords returns an empty list. Note that it might take multiple calls to get to a portion of the shard that contains stream
records> <note>
GetRecords can retrieve a maximum of 1 MB of data or 2000 stream records, whichever comes
Parameters
request Request to send to Amazon DynamoDB Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 177 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRecordsResponse *>(send(request));
 }
getShardIterator
GetShardIteratorResponse * QtAws::DynamoDBStreams::DynamoDBStreamsClient::getShardIterator (const GetShardIteratorRequest & request) slot
Returns a shard iterator. A shard iterator provides information about how to retrieve the stream records from within a shard. Use the shard iterator in a subsequent GetRecords request to read the stream records from the
Parameters
request Request to send to Amazon DynamoDB Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 192 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetShardIteratorResponse *>(send(request));
 }
listStreams
ListStreamsResponse * QtAws::DynamoDBStreams::DynamoDBStreamsClient::listStreams (const ListStreamsRequest & request) slot
Returns an array of stream ARNs associated with the current account and endpoint. If the TableName parameter is present, then ListStreams will return only the streams ARNs for that
Parameters
request Request to send to Amazon DynamoDB Streams.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 207 of file dynamodbstreamsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStreamsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
dynamodbstreams/dynamodbstreamsclient.h
dynamodbstreams/dynamodbstreamsclient.cpp