AWS SDK for Qt: QtAws::MediaLive::MediaLiveClient Class Reference
QtAws::MediaLive::MediaLiveClient Class Reference
Client for AWS Elemental MediaLive.
Public Slots
CreateChannelResponse * createChannel (const CreateChannelRequest &request)
CreateInputResponse * createInput (const CreateInputRequest &request)
CreateInputSecurityGroupResponse * createInputSecurityGroup (const CreateInputSecurityGroupRequest &request)
DeleteChannelResponse * deleteChannel (const DeleteChannelRequest &request)
DeleteInputResponse * deleteInput (const DeleteInputRequest &request)
DeleteInputSecurityGroupResponse * deleteInputSecurityGroup (const DeleteInputSecurityGroupRequest &request)
DescribeChannelResponse * describeChannel (const DescribeChannelRequest &request)
DescribeInputResponse * describeInput (const DescribeInputRequest &request)
DescribeInputSecurityGroupResponse * describeInputSecurityGroup (const DescribeInputSecurityGroupRequest &request)
ListChannelsResponse * listChannels (const ListChannelsRequest &request)
ListInputSecurityGroupsResponse * listInputSecurityGroups (const ListInputSecurityGroupsRequest &request)
ListInputsResponse * listInputs (const ListInputsRequest &request)
StartChannelResponse * startChannel (const StartChannelRequest &request)
StopChannelResponse * stopChannel (const StopChannelRequest &request)
UpdateChannelResponse * updateChannel (const UpdateChannelRequest &request)
UpdateInputResponse * updateInput (const UpdateInputRequest &request)
UpdateInputSecurityGroupResponse * updateInputSecurityGroup (const UpdateInputSecurityGroupRequest &request)
Public Member Functions
MediaLiveClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaLiveClient object.
MediaLiveClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaLiveClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elemental MediaLive.
Definition at line 66 of file medialiveclient.h.
Constructor & Destructor Documentation
MediaLiveClient() [1/2]
QtAws::MediaLive::MediaLiveClient::MediaLiveClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaLiveClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 80 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MediaLiveClientPrivate(this), parent)
 {
     Q_D(MediaLiveClient);
     d->apiVersion = QStringLiteral("2017-10-14");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("medialive");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaLive");
     d->serviceName = QStringLiteral("medialive");
 }
MediaLiveClient() [2/2]
QtAws::MediaLive::MediaLiveClient::MediaLiveClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaLiveClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 113 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MediaLiveClientPrivate(this), parent)
 {
     Q_D(MediaLiveClient);
     d->apiVersion = QStringLiteral("2017-10-14");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("medialive");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaLive");
     d->serviceName = QStringLiteral("medialive");
 }
Member Function Documentation
createChannel
CreateChannelResponse * QtAws::MediaLive::MediaLiveClient::createChannel (const CreateChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 138 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateChannelResponse *>(send(request));
 }
createInput
CreateInputResponse * QtAws::MediaLive::MediaLiveClient::createInput (const CreateInputRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 151 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInputResponse *>(send(request));
 }
createInputSecurityGroup
CreateInputSecurityGroupResponse * QtAws::MediaLive::MediaLiveClient::createInputSecurityGroup (const CreateInputSecurityGroupRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 164 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateInputSecurityGroupResponse *>(send(request));
 }
deleteChannel
DeleteChannelResponse * QtAws::MediaLive::MediaLiveClient::deleteChannel (const DeleteChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 177 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteChannelResponse *>(send(request));
 }
deleteInput
DeleteInputResponse * QtAws::MediaLive::MediaLiveClient::deleteInput (const DeleteInputRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 190 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInputResponse *>(send(request));
 }
deleteInputSecurityGroup
DeleteInputSecurityGroupResponse * QtAws::MediaLive::MediaLiveClient::deleteInputSecurityGroup (const DeleteInputSecurityGroupRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 203 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteInputSecurityGroupResponse *>(send(request));
 }
describeChannel
DescribeChannelResponse * QtAws::MediaLive::MediaLiveClient::describeChannel (const DescribeChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 216 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeChannelResponse *>(send(request));
 }
describeInput
DescribeInputResponse * QtAws::MediaLive::MediaLiveClient::describeInput (const DescribeInputRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 229 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInputResponse *>(send(request));
 }
describeInputSecurityGroup
DescribeInputSecurityGroupResponse * QtAws::MediaLive::MediaLiveClient::describeInputSecurityGroup (const DescribeInputSecurityGroupRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 242 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeInputSecurityGroupResponse *>(send(request));
 }
listChannels
ListChannelsResponse * QtAws::MediaLive::MediaLiveClient::listChannels (const ListChannelsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 255 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListChannelsResponse *>(send(request));
 }
listInputs
ListInputsResponse * QtAws::MediaLive::MediaLiveClient::listInputs (const ListInputsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 281 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInputsResponse *>(send(request));
 }
listInputSecurityGroups
ListInputSecurityGroupsResponse * QtAws::MediaLive::MediaLiveClient::listInputSecurityGroups (const ListInputSecurityGroupsRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 268 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInputSecurityGroupsResponse *>(send(request));
 }
startChannel
StartChannelResponse * QtAws::MediaLive::MediaLiveClient::startChannel (const StartChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 294 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartChannelResponse *>(send(request));
 }
stopChannel
StopChannelResponse * QtAws::MediaLive::MediaLiveClient::stopChannel (const StopChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 307 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopChannelResponse *>(send(request));
 }
updateChannel
UpdateChannelResponse * QtAws::MediaLive::MediaLiveClient::updateChannel (const UpdateChannelRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 320 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateChannelResponse *>(send(request));
 }
updateInput
UpdateInputResponse * QtAws::MediaLive::MediaLiveClient::updateInput (const UpdateInputRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 333 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateInputResponse *>(send(request));
 }
updateInputSecurityGroup
UpdateInputSecurityGroupResponse * QtAws::MediaLive::MediaLiveClient::updateInputSecurityGroup (const UpdateInputSecurityGroupRequest & request) slot
Parameters
request Request to send to AWS Elemental MediaLive.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 346 of file medialiveclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateInputSecurityGroupResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
medialive/medialiveclient.h
medialive/medialiveclient.cpp