AWS SDK for Qt: QtAws::CodeBuild::CodeBuildClient Class Reference
QtAws::CodeBuild::CodeBuildClient Class Reference
Client for AWS CodeBuild.
Public Slots
BatchDeleteBuildsResponse * batchDeleteBuilds (const BatchDeleteBuildsRequest &request)
BatchGetBuildsResponse * batchGetBuilds (const BatchGetBuildsRequest &request)
BatchGetProjectsResponse * batchGetProjects (const BatchGetProjectsRequest &request)
CreateProjectResponse * createProject (const CreateProjectRequest &request)
CreateWebhookResponse * createWebhook (const CreateWebhookRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DeleteWebhookResponse * deleteWebhook (const DeleteWebhookRequest &request)
InvalidateProjectCacheResponse * invalidateProjectCache (const InvalidateProjectCacheRequest &request)
ListBuildsResponse * listBuilds (const ListBuildsRequest &request)
ListBuildsForProjectResponse * listBuildsForProject (const ListBuildsForProjectRequest &request)
ListCuratedEnvironmentImagesResponse * listCuratedEnvironmentImages (const ListCuratedEnvironmentImagesRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
StartBuildResponse * startBuild (const StartBuildRequest &request)
StopBuildResponse * stopBuild (const StopBuildRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
UpdateWebhookResponse * updateWebhook (const UpdateWebhookRequest &request)
Public Member Functions
CodeBuildClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeBuildClient object.
CodeBuildClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeBuildClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodeBuild.
<fullname>AWS CodeBuild</fullname>
AWS CodeBuild is a fully managed build service in the cloud. AWS CodeBuild compiles your source code, runs unit tests, and produces artifacts that are ready to deploy. AWS CodeBuild eliminates the need to provision, manage, and scale your own build servers. It provides prepackaged build environments for the most popular programming languages and build tools, such as Apache Maven, Gradle, and more. You can also fully customize build environments in AWS CodeBuild to use your own build tools. AWS CodeBuild scales automatically to meet peak build requests, and you pay only for the build time you consume. For more information about AWS CodeBuild, see the AWS CodeBuild User
Guide>
AWS CodeBuild supports these
operations>
BatchDeleteBuilds: Deletes one or more
builds>
BatchGetProjects: Gets information about one or more build projects. A build project defines how AWS CodeBuild will run a build. This includes information such as where to get the source code to build, the build environment to use, the build commands to run, and where to store the build output. A build environment represents a combination of operating system, programming language runtime, and tools that AWS CodeBuild will use to run a build. Also, you can add tags to build projects to help manage your resources and
costs>
CreateProject: Creates a build
project>
CreateWebhook: For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, enables AWS CodeBuild to begin automatically rebuilding the source code every time a code change is pushed to the
repository>
UpdateWebhook: Changes the settings of an existing
webhook>
DeleteProject: Deletes a build
project>
DeleteWebhook: For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, stops AWS CodeBuild from automatically rebuilding the source code every time a code change is pushed to the
repository>
ListProjects: Gets a list of build project names, with each build project name representing a single build
project>
UpdateProject: Changes the settings of an existing build
project>
BatchGetBuilds: Gets information about one or more
builds>
ListBuilds: Gets a list of build IDs, with each build ID representing a single
build>
ListBuildsForProject: Gets a list of build IDs for the specified build project, with each build ID representing a single
build>
StartBuild: Starts running a
build>
StopBuild: Attempts to stop running a
build>
ListCuratedEnvironmentImages: Gets information about Docker images that are managed by AWS
Definition at line 64 of file codebuildclient.h.
Constructor & Destructor Documentation
CodeBuildClient() [1/2]
QtAws::CodeBuild::CodeBuildClient::CodeBuildClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeBuildClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 158 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CodeBuildClientPrivate(this), parent)
 {
     Q_D(CodeBuildClient);
     d->apiVersion = QStringLiteral("2016-10-06");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("codebuild");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CodeBuild");
     d->serviceName = QStringLiteral("codebuild");
 }
CodeBuildClient() [2/2]
QtAws::CodeBuild::CodeBuildClient::CodeBuildClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeBuildClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 191 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CodeBuildClientPrivate(this), parent)
 {
     Q_D(CodeBuildClient);
     d->apiVersion = QStringLiteral("2016-10-06");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("codebuild");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CodeBuild");
     d->serviceName = QStringLiteral("codebuild");
 }
Member Function Documentation
batchDeleteBuilds
BatchDeleteBuildsResponse * QtAws::CodeBuild::CodeBuildClient::batchDeleteBuilds (const BatchDeleteBuildsRequest & request) slot
Deletes one or more
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 217 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchDeleteBuildsResponse *>(send(request));
 }
batchGetBuilds
BatchGetBuildsResponse * QtAws::CodeBuild::CodeBuildClient::batchGetBuilds (const BatchGetBuildsRequest & request) slot
Gets information about
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 231 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetBuildsResponse *>(send(request));
 }
batchGetProjects
BatchGetProjectsResponse * QtAws::CodeBuild::CodeBuildClient::batchGetProjects (const BatchGetProjectsRequest & request) slot
Gets information about build
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetProjectsResponse *>(send(request));
 }
createProject
CreateProjectResponse * QtAws::CodeBuild::CodeBuildClient::createProject (const CreateProjectRequest & request) slot
Creates a build
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateProjectResponse *>(send(request));
 }
createWebhook
CreateWebhookResponse * QtAws::CodeBuild::CodeBuildClient::createWebhook (const CreateWebhookRequest & request) slot
For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, enables AWS CodeBuild to begin automatically rebuilding the source code every time a code change is pushed to the
repository>
If you enable webhooks for an AWS CodeBuild project, and the project is used as a build step in AWS CodePipeline, then two identical builds will be created for each commit. One build is triggered through webhooks, and one through AWS CodePipeline. Because billing is on a per-build basis, you will be billed for both builds. Therefore, if you are using AWS CodePipeline, we recommend that you disable webhooks in CodeBuild. In the AWS CodeBuild console, clear the Webhook box. For more information, see step 9 in Change a Build Project's request Request to send to AWS CodeBuild. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 284 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateWebhookResponse *>(send(request));
 }
deleteProject
DeleteProjectResponse * QtAws::CodeBuild::CodeBuildClient::deleteProject (const DeleteProjectRequest & request) slot
Deletes a build
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 298 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteProjectResponse *>(send(request));
 }
deleteWebhook
DeleteWebhookResponse * QtAws::CodeBuild::CodeBuildClient::deleteWebhook (const DeleteWebhookRequest & request) slot
For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, stops AWS CodeBuild from automatically rebuilding the source code every time a code change is pushed to the
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 313 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteWebhookResponse *>(send(request));
 }
invalidateProjectCache
InvalidateProjectCacheResponse * QtAws::CodeBuild::CodeBuildClient::invalidateProjectCache (const InvalidateProjectCacheRequest & request) slot
Resets the cache for a
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 327 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<InvalidateProjectCacheResponse *>(send(request));
 }
listBuilds
ListBuildsResponse * QtAws::CodeBuild::CodeBuildClient::listBuilds (const ListBuildsRequest & request) slot
Gets a list of build IDs, with each build ID representing a single
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 341 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBuildsResponse *>(send(request));
 }
listBuildsForProject
ListBuildsForProjectResponse * QtAws::CodeBuild::CodeBuildClient::listBuildsForProject (const ListBuildsForProjectRequest & request) slot
Gets a list of build IDs for the specified build project, with each build ID representing a single
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 355 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBuildsForProjectResponse *>(send(request));
 }
listCuratedEnvironmentImages
ListCuratedEnvironmentImagesResponse * QtAws::CodeBuild::CodeBuildClient::listCuratedEnvironmentImages (const ListCuratedEnvironmentImagesRequest & request) slot
Gets information about Docker images that are managed by AWS
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 369 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListCuratedEnvironmentImagesResponse *>(send(request));
 }
listProjects
ListProjectsResponse * QtAws::CodeBuild::CodeBuildClient::listProjects (const ListProjectsRequest & request) slot
Gets a list of build project names, with each build project name representing a single build
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 383 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListProjectsResponse *>(send(request));
 }
startBuild
StartBuildResponse * QtAws::CodeBuild::CodeBuildClient::startBuild (const StartBuildRequest & request) slot
Starts running a
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 397 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartBuildResponse *>(send(request));
 }
stopBuild
StopBuildResponse * QtAws::CodeBuild::CodeBuildClient::stopBuild (const StopBuildRequest & request) slot
Attempts to stop running a
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 411 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopBuildResponse *>(send(request));
 }
updateProject
UpdateProjectResponse * QtAws::CodeBuild::CodeBuildClient::updateProject (const UpdateProjectRequest & request) slot
Changes the settings of a build
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 425 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateProjectResponse *>(send(request));
 }
updateWebhook
UpdateWebhookResponse * QtAws::CodeBuild::CodeBuildClient::updateWebhook (const UpdateWebhookRequest & request) slot
Updates the webhook associated with an AWS CodeBuild build project.
Parameters
request Request to send to AWS CodeBuild.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 439 of file codebuildclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateWebhookResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
codebuild/codebuildclient.h
codebuild/codebuildclient.cpp