AWS SDK for Qt: QtAws::SSM::SSMRequest Class Reference
QtAws::SSM::SSMRequest Class Reference
Interface class for providing SSM requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::SSM::AddTagsToResourceRequest, QtAws::SSM::CancelCommandRequest, QtAws::SSM::CreateActivationRequest, QtAws::SSM::CreateAssociationBatchRequest, QtAws::SSM::CreateAssociationRequest, QtAws::SSM::CreateDocumentRequest, QtAws::SSM::CreateMaintenanceWindowRequest, QtAws::SSM::CreatePatchBaselineRequest, QtAws::SSM::CreateResourceDataSyncRequest, QtAws::SSM::DeleteActivationRequest, QtAws::SSM::DeleteAssociationRequest, QtAws::SSM::DeleteDocumentRequest, QtAws::SSM::DeleteMaintenanceWindowRequest, QtAws::SSM::DeleteParameterRequest, QtAws::SSM::DeleteParametersRequest, QtAws::SSM::DeletePatchBaselineRequest, QtAws::SSM::DeleteResourceDataSyncRequest, QtAws::SSM::DeregisterManagedInstanceRequest, QtAws::SSM::DeregisterPatchBaselineForPatchGroupRequest, QtAws::SSM::DeregisterTargetFromMaintenanceWindowRequest, QtAws::SSM::DeregisterTaskFromMaintenanceWindowRequest, QtAws::SSM::DescribeActivationsRequest, QtAws::SSM::DescribeAssociationRequest, QtAws::SSM::DescribeAutomationExecutionsRequest, QtAws::SSM::DescribeAutomationStepExecutionsRequest, QtAws::SSM::DescribeAvailablePatchesRequest, QtAws::SSM::DescribeDocumentPermissionRequest, QtAws::SSM::DescribeDocumentRequest, QtAws::SSM::DescribeEffectiveInstanceAssociationsRequest, QtAws::SSM::DescribeEffectivePatchesForPatchBaselineRequest, QtAws::SSM::DescribeInstanceAssociationsStatusRequest, QtAws::SSM::DescribeInstanceInformationRequest, QtAws::SSM::DescribeInstancePatchesRequest, QtAws::SSM::DescribeInstancePatchStatesForPatchGroupRequest, QtAws::SSM::DescribeInstancePatchStatesRequest, QtAws::SSM::DescribeMaintenanceWindowExecutionsRequest, QtAws::SSM::DescribeMaintenanceWindowExecutionTaskInvocationsRequest, QtAws::SSM::DescribeMaintenanceWindowExecutionTasksRequest, QtAws::SSM::DescribeMaintenanceWindowsRequest, QtAws::SSM::DescribeMaintenanceWindowTargetsRequest, QtAws::SSM::DescribeMaintenanceWindowTasksRequest, QtAws::SSM::DescribeParametersRequest, QtAws::SSM::DescribePatchBaselinesRequest, QtAws::SSM::DescribePatchGroupsRequest, QtAws::SSM::DescribePatchGroupStateRequest, QtAws::SSM::GetAutomationExecutionRequest, QtAws::SSM::GetCommandInvocationRequest, QtAws::SSM::GetDefaultPatchBaselineRequest, QtAws::SSM::GetDeployablePatchSnapshotForInstanceRequest, QtAws::SSM::GetDocumentRequest, QtAws::SSM::GetInventoryRequest, QtAws::SSM::GetInventorySchemaRequest, QtAws::SSM::GetMaintenanceWindowExecutionRequest, QtAws::SSM::GetMaintenanceWindowExecutionTaskInvocationRequest, QtAws::SSM::GetMaintenanceWindowExecutionTaskRequest, QtAws::SSM::GetMaintenanceWindowRequest, QtAws::SSM::GetMaintenanceWindowTaskRequest, QtAws::SSM::GetParameterHistoryRequest, QtAws::SSM::GetParameterRequest, QtAws::SSM::GetParametersByPathRequest, QtAws::SSM::GetParametersRequest, QtAws::SSM::GetPatchBaselineForPatchGroupRequest, QtAws::SSM::GetPatchBaselineRequest, QtAws::SSM::ListAssociationsRequest, QtAws::SSM::ListAssociationVersionsRequest, QtAws::SSM::ListCommandInvocationsRequest, QtAws::SSM::ListCommandsRequest, QtAws::SSM::ListComplianceItemsRequest, QtAws::SSM::ListComplianceSummariesRequest, QtAws::SSM::ListDocumentsRequest, QtAws::SSM::ListDocumentVersionsRequest, QtAws::SSM::ListInventoryEntriesRequest, QtAws::SSM::ListResourceComplianceSummariesRequest, QtAws::SSM::ListResourceDataSyncRequest, QtAws::SSM::ListTagsForResourceRequest, QtAws::SSM::ModifyDocumentPermissionRequest, QtAws::SSM::PutComplianceItemsRequest, QtAws::SSM::PutInventoryRequest, QtAws::SSM::PutParameterRequest, QtAws::SSM::RegisterDefaultPatchBaselineRequest, QtAws::SSM::RegisterPatchBaselineForPatchGroupRequest, QtAws::SSM::RegisterTargetWithMaintenanceWindowRequest, QtAws::SSM::RegisterTaskWithMaintenanceWindowRequest, QtAws::SSM::RemoveTagsFromResourceRequest, QtAws::SSM::SendAutomationSignalRequest, QtAws::SSM::SendCommandRequest, QtAws::SSM::StartAutomationExecutionRequest, QtAws::SSM::StopAutomationExecutionRequest, QtAws::SSM::UpdateAssociationRequest, QtAws::SSM::UpdateAssociationStatusRequest, QtAws::SSM::UpdateDocumentDefaultVersionRequest, QtAws::SSM::UpdateDocumentRequest, QtAws::SSM::UpdateMaintenanceWindowRequest, QtAws::SSM::UpdateMaintenanceWindowTargetRequest, QtAws::SSM::UpdateMaintenanceWindowTaskRequest, QtAws::SSM::UpdateManagedInstanceRoleRequest, and QtAws::SSM::UpdatePatchBaselineRequest.
Public Types
enum Action {
AddTagsToResourceAction, CancelCommandAction, CreateActivationAction, CreateAssociationAction,
CreateAssociationBatchAction, CreateDocumentAction, CreateMaintenanceWindowAction, CreatePatchBaselineAction,
CreateResourceDataSyncAction, DeleteActivationAction, DeleteAssociationAction, DeleteDocumentAction,
DeleteMaintenanceWindowAction, DeleteParameterAction, DeleteParametersAction, DeletePatchBaselineAction,
DeleteResourceDataSyncAction, DeregisterManagedInstanceAction, DeregisterPatchBaselineForPatchGroupAction, DeregisterTargetFromMaintenanceWindowAction,
DeregisterTaskFromMaintenanceWindowAction, DescribeActivationsAction, DescribeAssociationAction, DescribeAutomationExecutionsAction,
DescribeAutomationStepExecutionsAction, DescribeAvailablePatchesAction, DescribeDocumentAction, DescribeDocumentPermissionAction,
DescribeEffectiveInstanceAssociationsAction, DescribeEffectivePatchesForPatchBaselineAction, DescribeInstanceAssociationsStatusAction, DescribeInstanceInformationAction,
DescribeInstancePatchStatesAction, DescribeInstancePatchStatesForPatchGroupAction, DescribeInstancePatchesAction, DescribeMaintenanceWindowExecutionTaskInvocationsAction,
DescribeMaintenanceWindowExecutionTasksAction, DescribeMaintenanceWindowExecutionsAction, DescribeMaintenanceWindowTargetsAction, DescribeMaintenanceWindowTasksAction,
DescribeMaintenanceWindowsAction, DescribeParametersAction, DescribePatchBaselinesAction, DescribePatchGroupStateAction,
DescribePatchGroupsAction, GetAutomationExecutionAction, GetCommandInvocationAction, GetDefaultPatchBaselineAction,
GetDeployablePatchSnapshotForInstanceAction, GetDocumentAction, GetInventoryAction, GetInventorySchemaAction,
GetMaintenanceWindowAction, GetMaintenanceWindowExecutionAction, GetMaintenanceWindowExecutionTaskAction, GetMaintenanceWindowExecutionTaskInvocationAction,
GetMaintenanceWindowTaskAction, GetParameterAction, GetParameterHistoryAction, GetParametersAction,
GetParametersByPathAction, GetPatchBaselineAction, GetPatchBaselineForPatchGroupAction, ListAssociationVersionsAction,
ListAssociationsAction, ListCommandInvocationsAction, ListCommandsAction, ListComplianceItemsAction,
ListComplianceSummariesAction, ListDocumentVersionsAction, ListDocumentsAction, ListInventoryEntriesAction,
ListResourceComplianceSummariesAction, ListResourceDataSyncAction, ListTagsForResourceAction, ModifyDocumentPermissionAction,
PutComplianceItemsAction, PutInventoryAction, PutParameterAction, RegisterDefaultPatchBaselineAction,
RegisterPatchBaselineForPatchGroupAction, RegisterTargetWithMaintenanceWindowAction, RegisterTaskWithMaintenanceWindowAction, RemoveTagsFromResourceAction,
SendAutomationSignalAction, SendCommandAction, StartAutomationExecutionAction, StopAutomationExecutionAction,
UpdateAssociationAction, UpdateAssociationStatusAction, UpdateDocumentAction, UpdateDocumentDefaultVersionAction,
UpdateMaintenanceWindowAction, UpdateMaintenanceWindowTargetAction, UpdateMaintenanceWindowTaskAction, UpdateManagedInstanceRoleAction,
UpdatePatchBaselineAction
}
Actions supported by SSM.
Public Member Functions
SSMRequest (const Action action)
Constructs a new SSMRequest object.
SSMRequest (const SSMRequest &other)
Constructs a new SSMRequest object by copying another.
SSMRequest & operator= (const SSMRequest &other)
Assignment operator.
Action action () const
Get the SSM action to be performed by this request.
QString actionString () const
Get the name of the SSM action to be performed by this request.
QString apiVersion () const
Get the SSM API version implemented by this request.
void setAction (const Action action)
Set the SSM action to be performed by this request.
void setApiVersion (const QString &version)
Set the SSM API version to include in this request.
virtual bool operator== (const SSMRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
SSMRequest (SSMRequestPrivate *const d)
Constructs a new SSMRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid SSM queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SSM request.
const QVariantMap & parameters () const
Get all parameters included with this SSM request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SSM request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SSM request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SSM request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing SSM requests.
Definition at line 35 of file ssmrequest.h.
Constructor & Destructor Documentation
SSMRequest() [1/3]
QtAws::SSM::SSMRequest::SSMRequest (const Action action)
Constructs a new SSMRequest object.
Parameters
action The SSM action to request.
Definition at line 38 of file ssmrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new SSMRequestPrivate(action, this))
 {
 }
SSMRequest() [2/3]
QtAws::SSM::SSMRequest::SSMRequest (const SSMRequest & other)
Constructs a new SSMRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file ssmrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new SSMRequestPrivate(*other.d_func(), this))
 {
 }
SSMRequest() [3/3]
QtAws::SSM::SSMRequest::SSMRequest (SSMRequestPrivate *const d) protected
Constructs a new SSMRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from SSMRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file ssmrequest.cpp.
                                                   : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
SSMRequest::Action QtAws::SSM::SSMRequest::action () const
Get the SSM action to be performed by this request.
Returns
The SSM action to be performed by this request.
Definition at line 93 of file ssmrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const SSMRequest);
     return d->action;
 }
actionString()
QString QtAws::SSM::SSMRequest::actionString () const
Get the name of the SSM action to be performed by this request.
Returns
The name of the SSM action to be performed by this request.
Definition at line 104 of file ssmrequest.cpp.
References action(), and QtAws::SSM::SSMRequestPrivate::toString().
 {
     return SSMRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::SSM::SSMRequest::apiVersion () const
Get the SSM API version implemented by this request.
Returns
The SSM API version implmented by this request.
Definition at line 114 of file ssmrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SSMRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::SSM::SSMRequest::clearParameter (const QString & name) protected
Check if queueName is a valid SSM queue name.
From SSM FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid SSM queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file ssmrequest.cpp.
 {
     Q_D(SSMRequest);
     return d->parameters.remove(name);
 }
operator=()
SSMRequest & QtAws::SSM::SSMRequest::operator= (const SSMRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file ssmrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(SSMRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::SSM::SSMRequest::operator== (const SSMRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file ssmrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::SSM::SSMRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this SSM request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file ssmrequest.cpp.
 {
     Q_D(const SSMRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::SSM::SSMRequest::parameters () const protected
Get all parameters included with this SSM request.
Returns
A map of parameters included with this request.
Definition at line 222 of file ssmrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const SSMRequest);
     return d->parameters;
 }
setAction()
void QtAws::SSM::SSMRequest::setAction (const Action action)
Set the SSM action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file ssmrequest.cpp.
References action().
 {
     Q_D(SSMRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::SSM::SSMRequest::setApiVersion (const QString & version)
Set the SSM API version to include in this request.
Parameters
version The SSM API version to include in this request.
Definition at line 136 of file ssmrequest.cpp.
 {
     Q_D(SSMRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::SSM::SSMRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this SSM request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file ssmrequest.cpp.
 {
     Q_D(SSMRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::SSM::SSMRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this SSM request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file ssmrequest.cpp.
References parameters().
 {
     Q_D(SSMRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::SSM::SSMRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this SSM request.
This SSM implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this SSM request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file ssmrequest.cpp.
 {
     Q_D(const SSMRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
ssm/ssmrequest.h
ssm/ssmrequest.cpp