AWS SDK for Qt: QtAws::WAFRegional::WAFRegionalClient Class Reference
QtAws::WAFRegional::WAFRegionalClient Class Reference
Client for AWS WAF Regional.
Public Slots
AssociateWebACLResponse * associateWebACL (const AssociateWebACLRequest &request)
CreateByteMatchSetResponse * createByteMatchSet (const CreateByteMatchSetRequest &request)
CreateGeoMatchSetResponse * createGeoMatchSet (const CreateGeoMatchSetRequest &request)
CreateIPSetResponse * createIPSet (const CreateIPSetRequest &request)
CreateRateBasedRuleResponse * createRateBasedRule (const CreateRateBasedRuleRequest &request)
CreateRegexMatchSetResponse * createRegexMatchSet (const CreateRegexMatchSetRequest &request)
CreateRegexPatternSetResponse * createRegexPatternSet (const CreateRegexPatternSetRequest &request)
CreateRuleResponse * createRule (const CreateRuleRequest &request)
CreateRuleGroupResponse * createRuleGroup (const CreateRuleGroupRequest &request)
CreateSizeConstraintSetResponse * createSizeConstraintSet (const CreateSizeConstraintSetRequest &request)
CreateSqlInjectionMatchSetResponse * createSqlInjectionMatchSet (const CreateSqlInjectionMatchSetRequest &request)
CreateWebACLResponse * createWebACL (const CreateWebACLRequest &request)
CreateXssMatchSetResponse * createXssMatchSet (const CreateXssMatchSetRequest &request)
DeleteByteMatchSetResponse * deleteByteMatchSet (const DeleteByteMatchSetRequest &request)
DeleteGeoMatchSetResponse * deleteGeoMatchSet (const DeleteGeoMatchSetRequest &request)
DeleteIPSetResponse * deleteIPSet (const DeleteIPSetRequest &request)
DeletePermissionPolicyResponse * deletePermissionPolicy (const DeletePermissionPolicyRequest &request)
DeleteRateBasedRuleResponse * deleteRateBasedRule (const DeleteRateBasedRuleRequest &request)
DeleteRegexMatchSetResponse * deleteRegexMatchSet (const DeleteRegexMatchSetRequest &request)
DeleteRegexPatternSetResponse * deleteRegexPatternSet (const DeleteRegexPatternSetRequest &request)
DeleteRuleResponse * deleteRule (const DeleteRuleRequest &request)
DeleteRuleGroupResponse * deleteRuleGroup (const DeleteRuleGroupRequest &request)
DeleteSizeConstraintSetResponse * deleteSizeConstraintSet (const DeleteSizeConstraintSetRequest &request)
DeleteSqlInjectionMatchSetResponse * deleteSqlInjectionMatchSet (const DeleteSqlInjectionMatchSetRequest &request)
DeleteWebACLResponse * deleteWebACL (const DeleteWebACLRequest &request)
DeleteXssMatchSetResponse * deleteXssMatchSet (const DeleteXssMatchSetRequest &request)
DisassociateWebACLResponse * disassociateWebACL (const DisassociateWebACLRequest &request)
GetByteMatchSetResponse * getByteMatchSet (const GetByteMatchSetRequest &request)
GetChangeTokenResponse * getChangeToken (const GetChangeTokenRequest &request)
GetChangeTokenStatusResponse * getChangeTokenStatus (const GetChangeTokenStatusRequest &request)
GetGeoMatchSetResponse * getGeoMatchSet (const GetGeoMatchSetRequest &request)
GetIPSetResponse * getIPSet (const GetIPSetRequest &request)
GetPermissionPolicyResponse * getPermissionPolicy (const GetPermissionPolicyRequest &request)
GetRateBasedRuleResponse * getRateBasedRule (const GetRateBasedRuleRequest &request)
GetRateBasedRuleManagedKeysResponse * getRateBasedRuleManagedKeys (const GetRateBasedRuleManagedKeysRequest &request)
GetRegexMatchSetResponse * getRegexMatchSet (const GetRegexMatchSetRequest &request)
GetRegexPatternSetResponse * getRegexPatternSet (const GetRegexPatternSetRequest &request)
GetRuleResponse * getRule (const GetRuleRequest &request)
GetRuleGroupResponse * getRuleGroup (const GetRuleGroupRequest &request)
GetSampledRequestsResponse * getSampledRequests (const GetSampledRequestsRequest &request)
GetSizeConstraintSetResponse * getSizeConstraintSet (const GetSizeConstraintSetRequest &request)
GetSqlInjectionMatchSetResponse * getSqlInjectionMatchSet (const GetSqlInjectionMatchSetRequest &request)
GetWebACLResponse * getWebACL (const GetWebACLRequest &request)
GetWebACLForResourceResponse * getWebACLForResource (const GetWebACLForResourceRequest &request)
GetXssMatchSetResponse * getXssMatchSet (const GetXssMatchSetRequest &request)
ListActivatedRulesInRuleGroupResponse * listActivatedRulesInRuleGroup (const ListActivatedRulesInRuleGroupRequest &request)
ListByteMatchSetsResponse * listByteMatchSets (const ListByteMatchSetsRequest &request)
ListGeoMatchSetsResponse * listGeoMatchSets (const ListGeoMatchSetsRequest &request)
ListIPSetsResponse * listIPSets (const ListIPSetsRequest &request)
ListRateBasedRulesResponse * listRateBasedRules (const ListRateBasedRulesRequest &request)
ListRegexMatchSetsResponse * listRegexMatchSets (const ListRegexMatchSetsRequest &request)
ListRegexPatternSetsResponse * listRegexPatternSets (const ListRegexPatternSetsRequest &request)
ListResourcesForWebACLResponse * listResourcesForWebACL (const ListResourcesForWebACLRequest &request)
ListRuleGroupsResponse * listRuleGroups (const ListRuleGroupsRequest &request)
ListRulesResponse * listRules (const ListRulesRequest &request)
ListSizeConstraintSetsResponse * listSizeConstraintSets (const ListSizeConstraintSetsRequest &request)
ListSqlInjectionMatchSetsResponse * listSqlInjectionMatchSets (const ListSqlInjectionMatchSetsRequest &request)
ListSubscribedRuleGroupsResponse * listSubscribedRuleGroups (const ListSubscribedRuleGroupsRequest &request)
ListWebACLsResponse * listWebACLs (const ListWebACLsRequest &request)
ListXssMatchSetsResponse * listXssMatchSets (const ListXssMatchSetsRequest &request)
PutPermissionPolicyResponse * putPermissionPolicy (const PutPermissionPolicyRequest &request)
UpdateByteMatchSetResponse * updateByteMatchSet (const UpdateByteMatchSetRequest &request)
UpdateGeoMatchSetResponse * updateGeoMatchSet (const UpdateGeoMatchSetRequest &request)
UpdateIPSetResponse * updateIPSet (const UpdateIPSetRequest &request)
UpdateRateBasedRuleResponse * updateRateBasedRule (const UpdateRateBasedRuleRequest &request)
UpdateRegexMatchSetResponse * updateRegexMatchSet (const UpdateRegexMatchSetRequest &request)
UpdateRegexPatternSetResponse * updateRegexPatternSet (const UpdateRegexPatternSetRequest &request)
UpdateRuleResponse * updateRule (const UpdateRuleRequest &request)
UpdateRuleGroupResponse * updateRuleGroup (const UpdateRuleGroupRequest &request)
UpdateSizeConstraintSetResponse * updateSizeConstraintSet (const UpdateSizeConstraintSetRequest &request)
UpdateSqlInjectionMatchSetResponse * updateSqlInjectionMatchSet (const UpdateSqlInjectionMatchSetRequest &request)
UpdateWebACLResponse * updateWebACL (const UpdateWebACLRequest &request)
UpdateXssMatchSetResponse * updateXssMatchSet (const UpdateXssMatchSetRequest &request)
Public Member Functions
WAFRegionalClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WAFRegionalClient object.
WAFRegionalClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WAFRegionalClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS WAF Regional.
This is the AWS WAF Regional API Reference for using AWS WAF with Elastic Load Balancing (ELB) Application Load Balancers. The AWS WAF actions and data types listed in the reference are available for protecting Application Load Balancers. You can use these actions and data types by means of the endpoints listed in AWS Regions and Endpoints. This guide is for developers who need detailed information about the AWS WAF API actions, data types, and errors. For detailed information about AWS WAF features and an overview of how to use the AWS WAF API, see the AWS WAF Developer
Definition at line 178 of file wafregionalclient.h.
Constructor & Destructor Documentation
WAFRegionalClient() [1/2]
QtAws::WAFRegional::WAFRegionalClient::WAFRegionalClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WAFRegionalClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 199 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new WAFRegionalClientPrivate(this), parent)
 {
     Q_D(WAFRegionalClient);
     d->apiVersion = QStringLiteral("2016-11-28");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("waf-regional");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS WAF Regional");
     d->serviceName = QStringLiteral("waf-regional");
 }
WAFRegionalClient() [2/2]
QtAws::WAFRegional::WAFRegionalClient::WAFRegionalClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WAFRegionalClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 232 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new WAFRegionalClientPrivate(this), parent)
 {
     Q_D(WAFRegionalClient);
     d->apiVersion = QStringLiteral("2016-11-28");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("waf-regional");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS WAF Regional");
     d->serviceName = QStringLiteral("waf-regional");
 }
Member Function Documentation
associateWebACL
AssociateWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::associateWebACL (const AssociateWebACLRequest & request) slot
Associates a web ACL with a
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 258 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AssociateWebACLResponse *>(send(request));
 }
createByteMatchSet
CreateByteMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::createByteMatchSet (const CreateByteMatchSetRequest & request) slot
Creates a ByteMatchSet. You then use UpdateByteMatchSet to identify the part of a web request that you want AWS WAF to inspect, such as the values of the User-Agent header or the query string. For example, you can create a ByteMatchSet that matches any requests with User-Agent headers that contain the string BadBot. You can then configure AWS WAF to reject those
requests>
To create and configure a ByteMatchSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateByteMatchSet
request>
Submit a CreateByteMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateByteMatchSet
request>
Submit an UpdateByteMatchSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the value that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 303 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateByteMatchSetResponse *>(send(request));
 }
createGeoMatchSet
CreateGeoMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::createGeoMatchSet (const CreateGeoMatchSetRequest & request) slot
Creates an GeoMatchSet, which you use to specify which web requests you want to allow or block based on the country that the requests originate from. For example, if you're receiving a lot of requests from one or more countries and you want to block the requests, you can create an GeoMatchSet that contains those countries and then configure AWS WAF to block the requests.
</p
To create and configure a GeoMatchSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateGeoMatchSet
request>
Submit a CreateGeoMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateGeoMatchSet
request>
Submit an UpdateGeoMatchSetSet request to specify the countries that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 347 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateGeoMatchSetResponse *>(send(request));
 }
createIPSet
CreateIPSetResponse * QtAws::WAFRegional::WAFRegionalClient::createIPSet (const CreateIPSetRequest & request) slot
Creates an IPSet, which you use to specify which web requests you want to allow or block based on the IP addresses that the requests originate from. For example, if you're receiving a lot of requests from one or more individual IP addresses or one or more ranges of IP addresses and you want to block the requests, you can create an IPSet that contains those IP addresses and then configure AWS WAF to block the requests.
</p
To create and configure an IPSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateIPSet
request>
Submit a CreateIPSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateIPSet
request>
Submit an UpdateIPSet request to specify the IP addresses that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 391 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateIPSetResponse *>(send(request));
 }
createRateBasedRule
CreateRateBasedRuleResponse * QtAws::WAFRegional::WAFRegionalClient::createRateBasedRule (const CreateRateBasedRuleRequest & request) slot
Creates a RateBasedRule. The RateBasedRule contains a RateLimit, which specifies the maximum number of requests that AWS WAF allows from a specified IP address in a five-minute period. The RateBasedRule also contains the IPSet objects, ByteMatchSet objects, and other predicates that identify the requests that you want to count or block if these requests exceed the
RateLimit>
If you add more than one predicate to a RateBasedRule, a request not only must exceed the RateLimit, but it also must match all the specifications to be counted or blocked. For example, suppose you add the following to a
RateBasedRule>
An IPSet that matches the IP address 192.0.2.44/32
</p
A ByteMatchSet that matches BadBot in the User-Agent
heade>
Further, you specify a RateLimit of
15,000>
You then add the RateBasedRule to a WebACL and specify that you want to block requests that meet the conditions in the rule. For a request to be blocked, it must come from the IP address 192.0.2.44 and the User-Agent header in the request must contain the value BadBot. Further, requests that match these two conditions must be received at a rate of more than 15,000 requests every five minutes. If both conditions are met and the rate is exceeded, AWS WAF blocks the requests. If the rate drops below 15,000 for a five-minute period, AWS WAF no longer blocks the
requests>
As a second example, suppose you want to limit requests to a particular page on your site. To do this, you could add the following to a
RateBasedRule>
A ByteMatchSet with FieldToMatch of URI
</p
A PositionalConstraint of STARTS_WITH
</p
A TargetString of login
</p
Further, you specify a RateLimit of
15,000>
By adding this RateBasedRule to a WebACL, you could limit requests to your login page without affecting the rest of your
site>
To create and configure a RateBasedRule, perform the following
steps>
Create and update the predicates that you want to include in the rule. For more information, see CreateByteMatchSet, CreateIPSet, and
CreateSqlInjectionMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateRule
request>
Submit a CreateRateBasedRule
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRule
request>
Submit an UpdateRateBasedRule request to specify the predicates that you want to include in the
rule>
Create and update a WebACL that contains the RateBasedRule. For more information, see
CreateWebACL>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 497 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRateBasedRuleResponse *>(send(request));
 }
createRegexMatchSet
CreateRegexMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::createRegexMatchSet (const CreateRegexMatchSetRequest & request) slot
Creates a RegexMatchSet. You then use UpdateRegexMatchSet to identify the part of a web request that you want AWS WAF to inspect, such as the values of the User-Agent header or the query string. For example, you can create a RegexMatchSet that contains a RegexMatchTuple that looks for any requests with User-Agent headers that match a RegexPatternSet with pattern B[a@]dB[o0]t. You can then configure AWS WAF to reject those
requests>
To create and configure a RegexMatchSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateRegexMatchSet
request>
Submit a CreateRegexMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRegexMatchSet
request>
Submit an UpdateRegexMatchSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the value, using a RegexPatternSet, that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 543 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRegexMatchSetResponse *>(send(request));
 }
createRegexPatternSet
CreateRegexPatternSetResponse * QtAws::WAFRegional::WAFRegionalClient::createRegexPatternSet (const CreateRegexPatternSetRequest & request) slot
Creates a RegexPatternSet. You then use UpdateRegexPatternSet to specify the regular expression (regex) pattern that you want AWS WAF to search for, such as B[a@]dB[o0]t. You can then configure AWS WAF to reject those
requests>
To create and configure a RegexPatternSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateRegexPatternSet
request>
Submit a CreateRegexPatternSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRegexPatternSet
request>
Submit an UpdateRegexPatternSet request to specify the string that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 586 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRegexPatternSetResponse *>(send(request));
 }
createRule
CreateRuleResponse * QtAws::WAFRegional::WAFRegionalClient::createRule (const CreateRuleRequest & request) slot
Creates a Rule, which contains the IPSet objects, ByteMatchSet objects, and other predicates that identify the requests that you want to block. If you add more than one predicate to a Rule, a request must match all of the specifications to be allowed or blocked. For example, suppose you add the following to a
Rule>
An IPSet that matches the IP address 192.0.2.44/32
</p
A ByteMatchSet that matches BadBot in the User-Agent
heade>
You then add the Rule to a WebACL and specify that you want to blocks requests that satisfy the Rule. For a request to be blocked, it must come from the IP address 192.0.2.44 and the User-Agent header in the request must contain the value
BadBot>
To create and configure a Rule, perform the following
steps>
Create and update the predicates that you want to include in the Rule. For more information, see CreateByteMatchSet, CreateIPSet, and
CreateSqlInjectionMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateRule
request>
Submit a CreateRule
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRule
request>
Submit an UpdateRule request to specify the predicates that you want to include in the
Rule>
Create and update a WebACL that contains the Rule. For more information, see
CreateWebACL>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 652 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRuleResponse *>(send(request));
 }
createRuleGroup
CreateRuleGroupResponse * QtAws::WAFRegional::WAFRegionalClient::createRuleGroup (const CreateRuleGroupRequest & request) slot
Creates a RuleGroup. A rule group is a collection of predefined rules that you add to a web ACL. You use UpdateRuleGroup to add rules to the rule
group>
Rule groups are subject to the following
limits>
Three rule groups per account. You can request an increase to this limit by contacting customer
support>
One rule group per web
ACL>
Ten rules per rule
group>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 688 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateRuleGroupResponse *>(send(request));
 }
createSizeConstraintSet
CreateSizeConstraintSetResponse * QtAws::WAFRegional::WAFRegionalClient::createSizeConstraintSet (const CreateSizeConstraintSetRequest & request) slot
Creates a SizeConstraintSet. You then use UpdateSizeConstraintSet to identify the part of a web request that you want AWS WAF to check for length, such as the length of the User-Agent header or the length of the query string. For example, you can create a SizeConstraintSet that matches any requests that have a query string that is longer than 100 bytes. You can then configure AWS WAF to reject those
requests>
To create and configure a SizeConstraintSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateSizeConstraintSet
request>
Submit a CreateSizeConstraintSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateSizeConstraintSet
request>
Submit an UpdateSizeConstraintSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the value that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 733 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSizeConstraintSetResponse *>(send(request));
 }
createSqlInjectionMatchSet
CreateSqlInjectionMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::createSqlInjectionMatchSet (const CreateSqlInjectionMatchSetRequest & request) slot
Creates a SqlInjectionMatchSet, which you use to allow, block, or count requests that contain snippets of SQL code in a specified part of web requests. AWS WAF searches for character sequences that are likely to be malicious
strings>
To create and configure a SqlInjectionMatchSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateSqlInjectionMatchSet
request>
Submit a CreateSqlInjectionMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateSqlInjectionMatchSet
request>
Submit an UpdateSqlInjectionMatchSet request to specify the parts of web requests in which you want to allow, block, or count malicious SQL
code>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 776 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSqlInjectionMatchSetResponse *>(send(request));
 }
createWebACL
CreateWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::createWebACL (const CreateWebACLRequest & request) slot
Creates a WebACL, which contains the Rules that identify the CloudFront web requests that you want to allow, block, or count. AWS WAF evaluates Rules in order based on the value of Priority for each
Rule>
You also specify a default action, either ALLOW or BLOCK. If a web request doesn't match any of the Rules in a WebACL, AWS WAF responds to the request with the default action.
</p
To create and configure a WebACL, perform the following
steps>
Create and update the ByteMatchSet objects and other predicates that you want to include in Rules. For more information, see CreateByteMatchSet, UpdateByteMatchSet, CreateIPSet, UpdateIPSet, CreateSqlInjectionMatchSet, and
UpdateSqlInjectionMatchSet>
Create and update the Rules that you want to include in the WebACL. For more information, see CreateRule and
UpdateRule>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateWebACL
request>
Submit a CreateWebACL
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateWebACL
request>
Submit an UpdateWebACL request to specify the Rules that you want to include in the WebACL, to specify the default action, and to associate the WebACL with a CloudFront
distribution>
For more information about how to use the AWS WAF API, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 836 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateWebACLResponse *>(send(request));
 }
createXssMatchSet
CreateXssMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::createXssMatchSet (const CreateXssMatchSetRequest & request) slot
Creates an XssMatchSet, which you use to allow, block, or count requests that contain cross-site scripting attacks in the specified part of web requests. AWS WAF searches for character sequences that are likely to be malicious
strings>
To create and configure an XssMatchSet, perform the following
steps>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a CreateXssMatchSet
request>
Submit a CreateXssMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateXssMatchSet
request>
Submit an UpdateXssMatchSet request to specify the parts of web requests in which you want to allow, block, or count cross-site scripting
attacks>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 879 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateXssMatchSetResponse *>(send(request));
 }
deleteByteMatchSet
DeleteByteMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteByteMatchSet (const DeleteByteMatchSetRequest & request) slot
Permanently deletes a ByteMatchSet. You can't delete a ByteMatchSet if it's still used in any Rules or if it still includes any ByteMatchTuple objects (any
filters)>
If you just want to remove a ByteMatchSet from a Rule, use
UpdateRule>
To permanently delete a ByteMatchSet, perform the following
steps>
Update the ByteMatchSet to remove filters, if any. For more information, see
UpdateByteMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteByteMatchSet
request>
Submit a DeleteByteMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 915 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteByteMatchSetResponse *>(send(request));
 }
deleteGeoMatchSet
DeleteGeoMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteGeoMatchSet (const DeleteGeoMatchSetRequest & request) slot
Permanently deletes a GeoMatchSet. You can't delete a GeoMatchSet if it's still used in any Rules or if it still includes any
countries>
If you just want to remove a GeoMatchSet from a Rule, use
UpdateRule>
To permanently delete a GeoMatchSet from AWS WAF, perform the following
steps>
Update the GeoMatchSet to remove any countries. For more information, see
UpdateGeoMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteGeoMatchSet
request>
Submit a DeleteGeoMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 951 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteGeoMatchSetResponse *>(send(request));
 }
deleteIPSet
DeleteIPSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteIPSet (const DeleteIPSetRequest & request) slot
Permanently deletes an IPSet. You can't delete an IPSet if it's still used in any Rules or if it still includes any IP
addresses>
If you just want to remove an IPSet from a Rule, use
UpdateRule>
To permanently delete an IPSet from AWS WAF, perform the following
steps>
Update the IPSet to remove IP address ranges, if any. For more information, see
UpdateIPSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteIPSet
request>
Submit a DeleteIPSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 987 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIPSetResponse *>(send(request));
 }
deletePermissionPolicy
DeletePermissionPolicyResponse * QtAws::WAFRegional::WAFRegionalClient::deletePermissionPolicy (const DeletePermissionPolicyRequest & request) slot
Permanently deletes an IAM policy from the specified
RuleGroup>
The user making the request must be the owner of the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1005 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePermissionPolicyResponse *>(send(request));
 }
deleteRateBasedRule
DeleteRateBasedRuleResponse * QtAws::WAFRegional::WAFRegionalClient::deleteRateBasedRule (const DeleteRateBasedRuleRequest & request) slot
Permanently deletes a RateBasedRule. You can't delete a rule if it's still used in any WebACL objects or if it still includes any predicates, such as ByteMatchSet
objects>
If you just want to remove a rule from a WebACL, use
UpdateWebACL>
To permanently delete a RateBasedRule from AWS WAF, perform the following
steps>
Update the RateBasedRule to remove predicates, if any. For more information, see
UpdateRateBasedRule>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteRateBasedRule
request>
Submit a DeleteRateBasedRule
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1041 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRateBasedRuleResponse *>(send(request));
 }
deleteRegexMatchSet
DeleteRegexMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteRegexMatchSet (const DeleteRegexMatchSetRequest & request) slot
Permanently deletes a RegexMatchSet. You can't delete a RegexMatchSet if it's still used in any Rules or if it still includes any RegexMatchTuples objects (any
filters)>
If you just want to remove a RegexMatchSet from a Rule, use
UpdateRule>
To permanently delete a RegexMatchSet, perform the following
steps>
Update the RegexMatchSet to remove filters, if any. For more information, see
UpdateRegexMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteRegexMatchSet
request>
Submit a DeleteRegexMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1077 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRegexMatchSetResponse *>(send(request));
 }
deleteRegexPatternSet
DeleteRegexPatternSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteRegexPatternSet (const DeleteRegexPatternSetRequest & request) slot
Permanently deletes a RegexPatternSet. You can't delete a RegexPatternSet if it's still used in any RegexMatchSet or if the RegexPatternSet is not empty.
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1092 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRegexPatternSetResponse *>(send(request));
 }
deleteRule
DeleteRuleResponse * QtAws::WAFRegional::WAFRegionalClient::deleteRule (const DeleteRuleRequest & request) slot
Permanently deletes a Rule. You can't delete a Rule if it's still used in any WebACL objects or if it still includes any predicates, such as ByteMatchSet
objects>
If you just want to remove a Rule from a WebACL, use
UpdateWebACL>
To permanently delete a Rule from AWS WAF, perform the following
steps>
Update the Rule to remove predicates, if any. For more information, see
UpdateRule>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteRule
request>
Submit a DeleteRule
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1128 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRuleResponse *>(send(request));
 }
deleteRuleGroup
DeleteRuleGroupResponse * QtAws::WAFRegional::WAFRegionalClient::deleteRuleGroup (const DeleteRuleGroupRequest & request) slot
Permanently deletes a RuleGroup. You can't delete a RuleGroup if it's still used in any WebACL objects or if it still includes any
rules>
If you just want to remove a RuleGroup from a WebACL, use
UpdateWebACL>
To permanently delete a RuleGroup from AWS WAF, perform the following
steps>
Update the RuleGroup to remove rules, if any. For more information, see
UpdateRuleGroup>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteRuleGroup
request>
Submit a DeleteRuleGroup
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1164 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteRuleGroupResponse *>(send(request));
 }
deleteSizeConstraintSet
DeleteSizeConstraintSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteSizeConstraintSet (const DeleteSizeConstraintSetRequest & request) slot
Permanently deletes a SizeConstraintSet. You can't delete a SizeConstraintSet if it's still used in any Rules or if it still includes any SizeConstraint objects (any
filters)>
If you just want to remove a SizeConstraintSet from a Rule, use
UpdateRule>
To permanently delete a SizeConstraintSet, perform the following
steps>
Update the SizeConstraintSet to remove filters, if any. For more information, see
UpdateSizeConstraintSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteSizeConstraintSet
request>
Submit a DeleteSizeConstraintSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1200 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSizeConstraintSetResponse *>(send(request));
 }
deleteSqlInjectionMatchSet
DeleteSqlInjectionMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteSqlInjectionMatchSet (const DeleteSqlInjectionMatchSetRequest & request) slot
Permanently deletes a SqlInjectionMatchSet. You can't delete a SqlInjectionMatchSet if it's still used in any Rules or if it still contains any SqlInjectionMatchTuple
objects>
If you just want to remove a SqlInjectionMatchSet from a Rule, use
UpdateRule>
To permanently delete a SqlInjectionMatchSet from AWS WAF, perform the following
steps>
Update the SqlInjectionMatchSet to remove filters, if any. For more information, see
UpdateSqlInjectionMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteSqlInjectionMatchSet
request>
Submit a DeleteSqlInjectionMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1236 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSqlInjectionMatchSetResponse *>(send(request));
 }
deleteWebACL
DeleteWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::deleteWebACL (const DeleteWebACLRequest & request) slot
Permanently deletes a WebACL. You can't delete a WebACL if it still contains any
Rules>
To delete a WebACL, perform the following
steps>
Update the WebACL to remove Rules, if any. For more information, see
UpdateWebACL>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteWebACL
request>
Submit a DeleteWebACL
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1267 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteWebACLResponse *>(send(request));
 }
deleteXssMatchSet
DeleteXssMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::deleteXssMatchSet (const DeleteXssMatchSetRequest & request) slot
Permanently deletes an XssMatchSet. You can't delete an XssMatchSet if it's still used in any Rules or if it still contains any XssMatchTuple
objects>
If you just want to remove an XssMatchSet from a Rule, use
UpdateRule>
To permanently delete an XssMatchSet from AWS WAF, perform the following
steps>
Update the XssMatchSet to remove filters, if any. For more information, see
UpdateXssMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of a DeleteXssMatchSet
request>
Submit a DeleteXssMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1303 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteXssMatchSetResponse *>(send(request));
 }
disassociateWebACL
DisassociateWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::disassociateWebACL (const DisassociateWebACLRequest & request) slot
Removes a web ACL from the specified
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1317 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisassociateWebACLResponse *>(send(request));
 }
getByteMatchSet
GetByteMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::getByteMatchSet (const GetByteMatchSetRequest & request) slot
Returns the ByteMatchSet specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1331 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetByteMatchSetResponse *>(send(request));
 }
getChangeToken
GetChangeTokenResponse * QtAws::WAFRegional::WAFRegionalClient::getChangeToken (const GetChangeTokenRequest & request) slot
When you want to create, update, or delete AWS WAF objects, get a change token and include the change token in the create, update, or delete request. Change tokens ensure that your application doesn't submit conflicting requests to AWS
WAF>
Each create, update, or delete request must use a unique change token. If your application submits a GetChangeToken request and then submits a second GetChangeToken request before submitting a create, update, or delete request, the second GetChangeToken request returns the same value as the first GetChangeToken
request>
When you use a change token in a create, update, or delete request, the status of the change token changes to PENDING, which indicates that AWS WAF is propagating the change to all AWS WAF servers. Use GetChangeTokenStatus to determine the status of your change
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1359 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetChangeTokenResponse *>(send(request));
 }
getChangeTokenStatus
GetChangeTokenStatusResponse * QtAws::WAFRegional::WAFRegionalClient::getChangeTokenStatus (const GetChangeTokenStatusRequest & request) slot
Returns the status of a ChangeToken that you got by calling GetChangeToken. ChangeTokenStatus is one of the following
values>
PROVISIONED: You requested the change token by calling GetChangeToken, but you haven't used it yet in a call to create, update, or delete an AWS WAF
object>
PENDING: AWS WAF is propagating the create, update, or delete request to all AWS WAF
servers>
IN_SYNC: Propagation is
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1387 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetChangeTokenStatusResponse *>(send(request));
 }
getGeoMatchSet
GetGeoMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::getGeoMatchSet (const GetGeoMatchSetRequest & request) slot
Returns the GeoMatchSet that is specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1401 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetGeoMatchSetResponse *>(send(request));
 }
getIPSet
GetIPSetResponse * QtAws::WAFRegional::WAFRegionalClient::getIPSet (const GetIPSetRequest & request) slot
Returns the IPSet that is specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1415 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIPSetResponse *>(send(request));
 }
getPermissionPolicy
GetPermissionPolicyResponse * QtAws::WAFRegional::WAFRegionalClient::getPermissionPolicy (const GetPermissionPolicyRequest & request) slot
Returns the IAM policy attached to the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1429 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPermissionPolicyResponse *>(send(request));
 }
getRateBasedRule
GetRateBasedRuleResponse * QtAws::WAFRegional::WAFRegionalClient::getRateBasedRule (const GetRateBasedRuleRequest & request) slot
Returns the RateBasedRule that is specified by the RuleId that you included in the GetRateBasedRule
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1444 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRateBasedRuleResponse *>(send(request));
 }
getRateBasedRuleManagedKeys
GetRateBasedRuleManagedKeysResponse * QtAws::WAFRegional::WAFRegionalClient::getRateBasedRuleManagedKeys (const GetRateBasedRuleManagedKeysRequest & request) slot
Returns an array of IP addresses currently being blocked by the RateBasedRule that is specified by the RuleId. The maximum number of managed keys that will be blocked is 10,000. If more than 10,000 addresses exceed the rate limit, the 10,000 addresses with the highest rates will be
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1460 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRateBasedRuleManagedKeysResponse *>(send(request));
 }
getRegexMatchSet
GetRegexMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::getRegexMatchSet (const GetRegexMatchSetRequest & request) slot
Returns the RegexMatchSet specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1474 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRegexMatchSetResponse *>(send(request));
 }
getRegexPatternSet
GetRegexPatternSetResponse * QtAws::WAFRegional::WAFRegionalClient::getRegexPatternSet (const GetRegexPatternSetRequest & request) slot
Returns the RegexPatternSet specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1488 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRegexPatternSetResponse *>(send(request));
 }
getRule
GetRuleResponse * QtAws::WAFRegional::WAFRegionalClient::getRule (const GetRuleRequest & request) slot
Returns the Rule that is specified by the RuleId that you included in the GetRule
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1502 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRuleResponse *>(send(request));
 }
getRuleGroup
GetRuleGroupResponse * QtAws::WAFRegional::WAFRegionalClient::getRuleGroup (const GetRuleGroupRequest & request) slot
Returns the RuleGroup that is specified by the RuleGroupId that you included in the GetRuleGroup
request>
To view the rules in a rule group, use
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1521 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetRuleGroupResponse *>(send(request));
 }
getSampledRequests
GetSampledRequestsResponse * QtAws::WAFRegional::WAFRegionalClient::getSampledRequests (const GetSampledRequestsRequest & request) slot
Gets detailed information about a specified number of requests–a sample–that AWS WAF randomly selects from among the first 5,000 requests that your AWS resource received during a time range that you choose. You can specify a sample size of up to 500 requests, and you can specify any time range in the previous three
hours>
GetSampledRequests returns a time range, which is usually the time range that you specified. However, if your resource (such as a CloudFront distribution) received 5,000 requests before the specified time range elapsed, GetSampledRequests returns an updated time range. This new time range indicates the actual period during which AWS WAF selected the requests in the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1544 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSampledRequestsResponse *>(send(request));
 }
getSizeConstraintSet
GetSizeConstraintSetResponse * QtAws::WAFRegional::WAFRegionalClient::getSizeConstraintSet (const GetSizeConstraintSetRequest & request) slot
Returns the SizeConstraintSet specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1558 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSizeConstraintSetResponse *>(send(request));
 }
getSqlInjectionMatchSet
GetSqlInjectionMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::getSqlInjectionMatchSet (const GetSqlInjectionMatchSetRequest & request) slot
Returns the SqlInjectionMatchSet that is specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1572 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSqlInjectionMatchSetResponse *>(send(request));
 }
getWebACL
GetWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::getWebACL (const GetWebACLRequest & request) slot
Returns the WebACL that is specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1586 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetWebACLResponse *>(send(request));
 }
getWebACLForResource
GetWebACLForResourceResponse * QtAws::WAFRegional::WAFRegionalClient::getWebACLForResource (const GetWebACLForResourceRequest & request) slot
Returns the web ACL for the specified
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1600 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetWebACLForResourceResponse *>(send(request));
 }
getXssMatchSet
GetXssMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::getXssMatchSet (const GetXssMatchSetRequest & request) slot
Returns the XssMatchSet that is specified by
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1614 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetXssMatchSetResponse *>(send(request));
 }
listActivatedRulesInRuleGroup
ListActivatedRulesInRuleGroupResponse * QtAws::WAFRegional::WAFRegionalClient::listActivatedRulesInRuleGroup (const ListActivatedRulesInRuleGroupRequest & request) slot
Returns an array of ActivatedRule
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1628 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListActivatedRulesInRuleGroupResponse *>(send(request));
 }
listByteMatchSets
ListByteMatchSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listByteMatchSets (const ListByteMatchSetsRequest & request) slot
Returns an array of ByteMatchSetSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1642 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListByteMatchSetsResponse *>(send(request));
 }
listGeoMatchSets
ListGeoMatchSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listGeoMatchSets (const ListGeoMatchSetsRequest & request) slot
Returns an array of GeoMatchSetSummary objects in the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1656 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListGeoMatchSetsResponse *>(send(request));
 }
listIPSets
ListIPSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listIPSets (const ListIPSetsRequest & request) slot
Returns an array of IPSetSummary objects in the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1670 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListIPSetsResponse *>(send(request));
 }
listRateBasedRules
ListRateBasedRulesResponse * QtAws::WAFRegional::WAFRegionalClient::listRateBasedRules (const ListRateBasedRulesRequest & request) slot
Returns an array of RuleSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1684 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRateBasedRulesResponse *>(send(request));
 }
listRegexMatchSets
ListRegexMatchSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listRegexMatchSets (const ListRegexMatchSetsRequest & request) slot
Returns an array of RegexMatchSetSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1698 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRegexMatchSetsResponse *>(send(request));
 }
listRegexPatternSets
ListRegexPatternSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listRegexPatternSets (const ListRegexPatternSetsRequest & request) slot
Returns an array of RegexPatternSetSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1712 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRegexPatternSetsResponse *>(send(request));
 }
listResourcesForWebACL
ListResourcesForWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::listResourcesForWebACL (const ListResourcesForWebACLRequest & request) slot
Returns an array of resources associated with the specified web
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1726 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListResourcesForWebACLResponse *>(send(request));
 }
listRuleGroups
ListRuleGroupsResponse * QtAws::WAFRegional::WAFRegionalClient::listRuleGroups (const ListRuleGroupsRequest & request) slot
Returns an array of RuleGroup
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1740 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRuleGroupsResponse *>(send(request));
 }
listRules
ListRulesResponse * QtAws::WAFRegional::WAFRegionalClient::listRules (const ListRulesRequest & request) slot
Returns an array of RuleSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1754 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRulesResponse *>(send(request));
 }
listSizeConstraintSets
ListSizeConstraintSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listSizeConstraintSets (const ListSizeConstraintSetsRequest & request) slot
Returns an array of SizeConstraintSetSummary
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1768 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSizeConstraintSetsResponse *>(send(request));
 }
listSqlInjectionMatchSets
ListSqlInjectionMatchSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listSqlInjectionMatchSets (const ListSqlInjectionMatchSetsRequest & request) slot
Returns an array of SqlInjectionMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1782 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSqlInjectionMatchSetsResponse *>(send(request));
 }
listSubscribedRuleGroups
ListSubscribedRuleGroupsResponse * QtAws::WAFRegional::WAFRegionalClient::listSubscribedRuleGroups (const ListSubscribedRuleGroupsRequest & request) slot
Returns an array of RuleGroup objects that you are subscribed
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1796 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSubscribedRuleGroupsResponse *>(send(request));
 }
listWebACLs
ListWebACLsResponse * QtAws::WAFRegional::WAFRegionalClient::listWebACLs (const ListWebACLsRequest & request) slot
Returns an array of WebACLSummary objects in the
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1810 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListWebACLsResponse *>(send(request));
 }
listXssMatchSets
ListXssMatchSetsResponse * QtAws::WAFRegional::WAFRegionalClient::listXssMatchSets (const ListXssMatchSetsRequest & request) slot
Returns an array of XssMatchSet
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1824 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListXssMatchSetsResponse *>(send(request));
 }
putPermissionPolicy
PutPermissionPolicyResponse * QtAws::WAFRegional::WAFRegionalClient::putPermissionPolicy (const PutPermissionPolicyRequest & request) slot
Attaches a IAM policy to the specified resource. The only supported use for this action is to share a RuleGroup across
accounts>
The PutPermissionPolicy is subject to the following
restrictions>
You can attach only one policy with each PutPermissionPolicy
request>
The policy must include an Effect, Action and Principal.
</p
Effect must specify
Allow>
The Action in the policy must be waf:UpdateWebACL and waf-regional:UpdateWebACL. Any extra or wildcard actions in the policy will be
rejected>
The policy cannot include a Resource
parameter>
The ARN in the request must be a valid WAF RuleGroup ARN and the RuleGroup must exist in the same
region>
The user making the request must be the owner of the
RuleGroup>
Your policy must be composed using IAM Policy version
2012-10-17>
For more information, see IAM Policies.
</p
An example of a valid policy parameter is shown in the Examples section
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1884 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutPermissionPolicyResponse *>(send(request));
 }
updateByteMatchSet
UpdateByteMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateByteMatchSet (const UpdateByteMatchSetRequest & request) slot
Inserts or deletes ByteMatchTuple objects (filters) in a ByteMatchSet. For each ByteMatchTuple object, you specify the following values:
</p
Whether to insert or delete the object from the array. If you want to change a ByteMatchSetUpdate object, you delete the existing object and add a new
one>
The part of a web request that you want AWS WAF to inspect, such as a query string or the value of the User-Agent header.
</p
The bytes (typically a string that corresponds with ASCII characters) that you want AWS WAF to look for. For more information, including how you specify the values for the AWS WAF API and the AWS CLI or SDKs, see TargetString in the ByteMatchTuple data type.
</p
Where to look, such as at the beginning or the end of a query
string>
Whether to perform any conversions on the request, such as converting it to lowercase, before inspecting it for the specified
string>
For example, you can add a ByteMatchSetUpdate object that matches web requests in which User-Agent headers contain the string BadBot. You can then configure AWS WAF to block those
requests>
To create and configure a ByteMatchSet, perform the following
steps>
Create a ByteMatchSet. For more information, see
CreateByteMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateByteMatchSet
request>
Submit an UpdateByteMatchSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the value that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1952 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateByteMatchSetResponse *>(send(request));
 }
updateGeoMatchSet
UpdateGeoMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateGeoMatchSet (const UpdateGeoMatchSetRequest & request) slot
Inserts or deletes GeoMatchConstraint objects in an GeoMatchSet. For each GeoMatchConstraint object, you specify the following values:
</p
Whether to insert or delete the object from the array. If you want to change an GeoMatchConstraint object, you delete the existing object and add a new
one>
The Type. The only valid value for Type is
Country>
The Value, which is a two character code for the country to add to the GeoMatchConstraint object. Valid codes are listed in
GeoMatchConstraint$Value>
To create and configure an GeoMatchSet, perform the following
steps>
Submit a CreateGeoMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateGeoMatchSet
request>
Submit an UpdateGeoMatchSet request to specify the country that you want AWS WAF to watch
for>
When you update an GeoMatchSet, you specify the country that you want to add and/or the country that you want to delete. If you want to change a country, you delete the existing country and add the new
one>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2008 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateGeoMatchSetResponse *>(send(request));
 }
updateIPSet
UpdateIPSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateIPSet (const UpdateIPSetRequest & request) slot
Inserts or deletes IPSetDescriptor objects in an IPSet. For each IPSetDescriptor object, you specify the following values:
</p
Whether to insert or delete the object from the array. If you want to change an IPSetDescriptor object, you delete the existing object and add a new
one>
The IP address version, IPv4 or IPv6.
</p
The IP address in CIDR notation, for example, 192.0.2.0/24 (for the range of IP addresses from 192.0.2.0 to 192.0.2.255) or 192.0.2.44/32 (for the individual IP address 192.0.2.44).
</p
AWS WAF supports /8, /16, /24, and /32 IP address ranges for IPv4, and /24, /32, /48, /56, /64 and /128 for IPv6. For more information about CIDR notation, see the Wikipedia entry Classless Inter-Domain Routing>
IPv6 addresses can be represented using any of the following
formats>
1111:0000:0000:0000:0000:0000:0000:0111/12>
1111:0:0:0:0:0:0:0111/12>
1111::0111/12>
1111::111/12>
You use an IPSet to specify which web requests you want to allow or block based on the IP addresses that the requests originated from. For example, if you're receiving a lot of requests from one or a small number of IP addresses and you want to block the requests, you can create an IPSet that specifies those IP addresses, and then configure AWS WAF to block the requests.
</p
To create and configure an IPSet, perform the following
steps>
Submit a CreateIPSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateIPSet
request>
Submit an UpdateIPSet request to specify the IP addresses that you want AWS WAF to watch
for>
When you update an IPSet, you specify the IP addresses that you want to add and/or the IP addresses that you want to delete. If you want to change an IP address, you delete the existing IP address and add the new
one>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2090 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateIPSetResponse *>(send(request));
 }
updateRateBasedRule
UpdateRateBasedRuleResponse * QtAws::WAFRegional::WAFRegionalClient::updateRateBasedRule (const UpdateRateBasedRuleRequest & request) slot
Inserts or deletes Predicate objects in a rule and updates the RateLimit in the rule.
</p
Each Predicate object identifies a predicate, such as a ByteMatchSet or an IPSet, that specifies the web requests that you want to block or count. The RateLimit specifies the number of requests every five minutes that triggers the
rule>
If you add more than one predicate to a RateBasedRule, a request must match all the predicates and exceed the RateLimit to be counted or blocked. For example, suppose you add the following to a
RateBasedRule>
An IPSet that matches the IP address 192.0.2.44/32
</p
A ByteMatchSet that matches BadBot in the User-Agent
heade>
Further, you specify a RateLimit of
15,000>
You then add the RateBasedRule to a WebACL and specify that you want to block requests that satisfy the rule. For a request to be blocked, it must come from the IP address 192.0.2.44 and the User-Agent header in the request must contain the value BadBot. Further, requests that match these two conditions much be received at a rate of more than 15,000 every five minutes. If the rate drops below this limit, AWS WAF no longer blocks the
requests>
As a second example, suppose you want to limit requests to a particular page on your site. To do this, you could add the following to a
RateBasedRule>
A ByteMatchSet with FieldToMatch of URI
</p
A PositionalConstraint of STARTS_WITH
</p
A TargetString of login
</p
Further, you specify a RateLimit of
15,000>
By adding this RateBasedRule to a WebACL, you could limit requests to your login page without affecting the rest of your
Parameters
request Request to send to AWS WAF Regional.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2161 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRateBasedRuleResponse *>(send(request));
 }
updateRegexMatchSet
UpdateRegexMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateRegexMatchSet (const UpdateRegexMatchSetRequest & request) slot
Inserts or deletes RegexMatchTuple objects (filters) in a RegexMatchSet. For each RegexMatchSetUpdate object, you specify the following values:
</p
Whether to insert or delete the object from the array. If you want to change a RegexMatchSetUpdate object, you delete the existing object and add a new
one>
The part of a web request that you want AWS WAF to inspectupdate, such as a query string or the value of the User-Agent header.
</p
The identifier of the pattern (a regular expression) that you want AWS WAF to look for. For more information, see RegexPatternSet.
</p
Whether to perform any conversions on the request, such as converting it to lowercase, before inspecting it for the specified
string>
For example, you can create a RegexPatternSet that matches any requests with User-Agent headers that contain the string B[a@]dB[o0]t. You can then configure AWS WAF to reject those
requests>
To create and configure a RegexMatchSet, perform the following
steps>
Create a RegexMatchSet. For more information, see
CreateRegexMatchSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRegexMatchSet
request>
Submit an UpdateRegexMatchSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the identifier of the RegexPatternSet that contain the regular expression patters you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2225 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRegexMatchSetResponse *>(send(request));
 }
updateRegexPatternSet
UpdateRegexPatternSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateRegexPatternSet (const UpdateRegexPatternSetRequest & request) slot
Inserts or deletes RegexPatternString objects in a RegexPatternSet. For each RegexPatternString object, you specify the following values:
</p
Whether to insert or delete the
RegexPatternString>
The regular expression pattern that you want to insert or delete. For more information, see RegexPatternSet.
</p
For example, you can create a RegexPatternString such as B[a@]dB[o0]t. AWS WAF will match this RegexPatternString
to>
BadBo>
BadB0>
B>
B>
To create and configure a RegexPatternSet, perform the following
steps>
Create a RegexPatternSet. For more information, see
CreateRegexPatternSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRegexPatternSet
request>
Submit an UpdateRegexPatternSet request to specify the regular expression pattern that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2284 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRegexPatternSetResponse *>(send(request));
 }
updateRule
UpdateRuleResponse * QtAws::WAFRegional::WAFRegionalClient::updateRule (const UpdateRuleRequest & request) slot
Inserts or deletes Predicate objects in a Rule. Each Predicate object identifies a predicate, such as a ByteMatchSet or an IPSet, that specifies the web requests that you want to allow, block, or count. If you add more than one predicate to a Rule, a request must match all of the specifications to be allowed, blocked, or counted. For example, suppose you add the following to a Rule:
</p
A ByteMatchSet that matches the value BadBot in the User-Agent
heade>
An IPSet that matches the IP address 192.0.2.44
</p
You then add the Rule to a WebACL and specify that you want to block requests that satisfy the Rule. For a request to be blocked, the User-Agent header in the request must contain the value BadBot and the request must originate from the IP address
192.0.2.44>
To create and configure a Rule, perform the following
steps>
Create and update the predicates that you want to include in the
Rule>
Create the Rule. See
CreateRule>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRule
request>
Submit an UpdateRule request to add predicates to the
Rule>
Create and update a WebACL that contains the Rule. See
CreateWebACL>
If you want to replace one ByteMatchSet or IPSet with another, you delete the existing one and add the new
one>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2350 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRuleResponse *>(send(request));
 }
updateRuleGroup
UpdateRuleGroupResponse * QtAws::WAFRegional::WAFRegionalClient::updateRuleGroup (const UpdateRuleGroupRequest & request) slot
Inserts or deletes ActivatedRule objects in a
RuleGroup>
You can only insert REGULAR rules into a rule
group>
You can have a maximum of ten rules per rule
group>
To create and configure a RuleGroup, perform the following
steps>
Create and update the Rules that you want to include in the RuleGroup. See
CreateRule>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateRuleGroup
request>
Submit an UpdateRuleGroup request to add Rules to the
RuleGroup>
Create and update a WebACL that contains the RuleGroup. See
CreateWebACL>
If you want to replace one Rule with another, you delete the existing one and add the new
one>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2402 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRuleGroupResponse *>(send(request));
 }
updateSizeConstraintSet
UpdateSizeConstraintSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateSizeConstraintSet (const UpdateSizeConstraintSetRequest & request) slot
Inserts or deletes SizeConstraint objects (filters) in a SizeConstraintSet. For each SizeConstraint object, you specify the following values:
</p
Whether to insert or delete the object from the array. If you want to change a SizeConstraintSetUpdate object, you delete the existing object and add a new
one>
The part of a web request that you want AWS WAF to evaluate, such as the length of a query string or the length of the User-Agent
header>
Whether to perform any transformations on the request, such as converting it to lowercase, before checking its length. Note that transformations of the request body are not supported because the AWS resource forwards only the first 8192 bytes of your request to AWS
WAF>
A ComparisonOperator used for evaluating the selected part of the request against the specified Size, such as equals, greater than, less than, and so
on>
The length, in bytes, that you want AWS WAF to watch for in selected part of the request. The length is computed after applying the
transformation>
For example, you can add a SizeConstraintSetUpdate object that matches web requests in which the length of the User-Agent header is greater than 100 bytes. You can then configure AWS WAF to block those
requests>
To create and configure a SizeConstraintSet, perform the following
steps>
Create a SizeConstraintSet. For more information, see
CreateSizeConstraintSet>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateSizeConstraintSet
request>
Submit an UpdateSizeConstraintSet request to specify the part of the request that you want AWS WAF to inspect (for example, the header or the URI) and the value that you want AWS WAF to watch
for>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2471 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSizeConstraintSetResponse *>(send(request));
 }
updateSqlInjectionMatchSet
UpdateSqlInjectionMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateSqlInjectionMatchSet (const UpdateSqlInjectionMatchSetRequest & request) slot
Inserts or deletes SqlInjectionMatchTuple objects (filters) in a SqlInjectionMatchSet. For each SqlInjectionMatchTuple object, you specify the following
values>
Action: Whether to insert the object into or delete the object from the array. To change a SqlInjectionMatchTuple, you delete the existing object and add a new
one>
FieldToMatch: The part of web requests that you want AWS WAF to inspect and, if you want AWS WAF to inspect a header, the name of the
header>
TextTransformation: Which text transformation, if any, to perform on the web request before inspecting the request for snippets of malicious SQL
code>
You use SqlInjectionMatchSet objects to specify which CloudFront requests you want to allow, block, or count. For example, if you're receiving requests that contain snippets of SQL code in the query string and you want to block the requests, you can create a SqlInjectionMatchSet with the applicable settings, and then configure AWS WAF to block the requests.
</p
To create and configure a SqlInjectionMatchSet, perform the following
steps>
Submit a CreateSqlInjectionMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateIPSet
request>
Submit an UpdateSqlInjectionMatchSet request to specify the parts of web requests that you want AWS WAF to inspect for snippets of SQL
code>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2531 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateSqlInjectionMatchSetResponse *>(send(request));
 }
updateWebACL
UpdateWebACLResponse * QtAws::WAFRegional::WAFRegionalClient::updateWebACL (const UpdateWebACLRequest & request) slot
Inserts or deletes ActivatedRule objects in a WebACL. Each Rule identifies web requests that you want to allow, block, or count. When you update a WebACL, you specify the following
values>
A default action for the WebACL, either ALLOW or BLOCK. AWS WAF performs the default action if a request doesn't match the criteria in any of the Rules in a
WebACL>
The Rules that you want to add and/or delete. If you want to replace one Rule with another, you delete the existing Rule and add the new
one>
For each Rule, whether you want AWS WAF to allow requests, block requests, or count requests that match the conditions in the
Rule>
The order in which you want AWS WAF to evaluate the Rules in a WebACL. If you add more than one Rule to a WebACL, AWS WAF evaluates each request against the Rules in order based on the value of Priority. (The Rule that has the lowest value for Priority is evaluated first.) When a web request matches all of the predicates (such as ByteMatchSets and IPSets) in a Rule, AWS WAF immediately takes the corresponding action, allow or block, and doesn't evaluate the request against the remaining Rules in the WebACL, if any.
</p
To create and configure a WebACL, perform the following
steps>
Create and update the predicates that you want to include in Rules. For more information, see CreateByteMatchSet, UpdateByteMatchSet, CreateIPSet, UpdateIPSet, CreateSqlInjectionMatchSet, and
UpdateSqlInjectionMatchSet>
Create and update the Rules that you want to include in the WebACL. For more information, see CreateRule and
UpdateRule>
Create a WebACL. See
CreateWebACL>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateWebACL
request>
Submit an UpdateWebACL request to specify the Rules that you want to include in the WebACL, to specify the default action, and to associate the WebACL with a CloudFront distribution.
</p
Be aware that if you try to add a RATE_BASED rule to a web ACL without setting the rule type when first creating the rule, the UpdateWebACL request will fail because the request tries to add a REGULAR rule (the default rule type) with the specified ID, which does not exist.
</p
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2611 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateWebACLResponse *>(send(request));
 }
updateXssMatchSet
UpdateXssMatchSetResponse * QtAws::WAFRegional::WAFRegionalClient::updateXssMatchSet (const UpdateXssMatchSetRequest & request) slot
Inserts or deletes XssMatchTuple objects (filters) in an XssMatchSet. For each XssMatchTuple object, you specify the following
values>
Action: Whether to insert the object into or delete the object from the array. To change a XssMatchTuple, you delete the existing object and add a new
one>
FieldToMatch: The part of web requests that you want AWS WAF to inspect and, if you want AWS WAF to inspect a header, the name of the
header>
TextTransformation: Which text transformation, if any, to perform on the web request before inspecting the request for cross-site scripting
attacks>
You use XssMatchSet objects to specify which CloudFront requests you want to allow, block, or count. For example, if you're receiving requests that contain cross-site scripting attacks in the request body and you want to block the requests, you can create an XssMatchSet with the applicable settings, and then configure AWS WAF to block the requests.
</p
To create and configure an XssMatchSet, perform the following
steps>
Submit a CreateXssMatchSet
request>
Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateIPSet
request>
Submit an UpdateXssMatchSet request to specify the parts of web requests that you want AWS WAF to inspect for cross-site scripting
attacks>
For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer request Request to send to AWS WAF Regional. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 2671 of file wafregionalclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateXssMatchSetResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
waf-regional/wafregionalclient.h
waf-regional/wafregionalclient.cpp