AWS SDK for Qt: QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient Class Reference
QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient Class Reference
Client for Application Auto Scaling.
Public Slots
DeleteScalingPolicyResponse * deleteScalingPolicy (const DeleteScalingPolicyRequest &request)
DeleteScheduledActionResponse * deleteScheduledAction (const DeleteScheduledActionRequest &request)
DeregisterScalableTargetResponse * deregisterScalableTarget (const DeregisterScalableTargetRequest &request)
DescribeScalableTargetsResponse * describeScalableTargets (const DescribeScalableTargetsRequest &request)
DescribeScalingActivitiesResponse * describeScalingActivities (const DescribeScalingActivitiesRequest &request)
DescribeScalingPoliciesResponse * describeScalingPolicies (const DescribeScalingPoliciesRequest &request)
DescribeScheduledActionsResponse * describeScheduledActions (const DescribeScheduledActionsRequest &request)
PutScalingPolicyResponse * putScalingPolicy (const PutScalingPolicyRequest &request)
PutScheduledActionResponse * putScheduledAction (const PutScheduledActionRequest &request)
RegisterScalableTargetResponse * registerScalableTarget (const RegisterScalableTargetRequest &request)
Public Member Functions
ApplicationAutoScalingClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ApplicationAutoScalingClient object.
ApplicationAutoScalingClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ApplicationAutoScalingClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Application Auto Scaling.
With Application Auto Scaling, you can configure automatic scaling for your scalable AWS resources. You can use Application Auto Scaling to accomplish the following
tasks>
Define scaling policies to automatically scale your AWS
resource>
Scale your resources in response to CloudWatch
alarm>
Schedule one-time or recurring scaling
action>
View the history of your scaling
event>
Application Auto Scaling can scale the following AWS
resources>
Amazon ECS services. For more information, see Service Auto Scaling in the Amazon Elastic Container Service Developer
Guide>
Amazon EC2 Spot fleets. For more information, see Automatic Scaling for Spot Fleet in the Amazon EC2 User
Guide>
Amazon EMR clusters. For more information, see Using Automatic Scaling in Amazon EMR in the Amazon EMR Management
Guide>
AppStream 2.0 fleets. For more information, see Fleet Auto Scaling for Amazon AppStream 2.0 in the Amazon AppStream 2.0 Developer
Guide>
Provisioned read and write capacity for Amazon DynamoDB tables and global secondary indexes. For more information, see Managing Throughput Capacity Automatically with DynamoDB Auto Scaling in the Amazon DynamoDB Developer
Guide>
Amazon Aurora Replicas. For more information, see Using Amazon Aurora Auto Scaling with Aurora Replicas>
Amazon SageMaker endpoints. For more information, see Automatically Scaling Amazon SageMaker Models>
To configure automatic scaling for multiple resources across multiple services, use AWS Auto Scaling to create a scaling plan for your application. For more information, see AWS Auto Scaling>
For a list of supported regions, see AWS Regions and Endpoints: Application Auto Scaling in the AWS General
Definition at line 52 of file applicationautoscalingclient.h.
Constructor & Destructor Documentation
ApplicationAutoScalingClient() [1/2]
QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ApplicationAutoScalingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 139 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ApplicationAutoScalingClientPrivate(this), parent)
 {
     Q_D(ApplicationAutoScalingClient);
     d->apiVersion = QStringLiteral("2016-02-06");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("autoscaling");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Application Auto Scaling");
     d->serviceName = QStringLiteral("application-autoscaling");
 }
ApplicationAutoScalingClient() [2/2]
QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ApplicationAutoScalingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 172 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ApplicationAutoScalingClientPrivate(this), parent)
 {
     Q_D(ApplicationAutoScalingClient);
     d->apiVersion = QStringLiteral("2016-02-06");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("autoscaling");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Application Auto Scaling");
     d->serviceName = QStringLiteral("application-autoscaling");
 }
Member Function Documentation
deleteScalingPolicy
DeleteScalingPolicyResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deleteScalingPolicy (const DeleteScalingPolicyRequest & request) slot
Deletes the specified Application Auto Scaling scaling
policy>
Deleting a policy deletes the underlying alarm action, but does not delete the CloudWatch alarm associated with the scaling policy, even if it no longer has an associated
action>
To create a scaling policy or update an existing one, see
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 207 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteScalingPolicyResponse *>(send(request));
 }
deleteScheduledAction
DeleteScheduledActionResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deleteScheduledAction (const DeleteScheduledActionRequest & request) slot
Deletes the specified Application Auto Scaling scheduled
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 221 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteScheduledActionResponse *>(send(request));
 }
deregisterScalableTarget
DeregisterScalableTargetResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deregisterScalableTarget (const DeregisterScalableTargetRequest & request) slot
Deregisters a scalable
target>
Deregistering a scalable target deletes the scaling policies that are associated with
it>
To create a scalable target or update an existing one, see
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 243 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeregisterScalableTargetResponse *>(send(request));
 }
describeScalableTargets
DescribeScalableTargetsResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalableTargets (const DescribeScalableTargetsRequest & request) slot
Gets information about the scalable targets in the specified
namespace>
You can filter the results using the ResourceIds and ScalableDimension
parameters>
To create a scalable target or update an existing one, see RegisterScalableTarget. If you are no longer using a scalable target, you can deregister it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 266 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalableTargetsResponse *>(send(request));
 }
describeScalingActivities
DescribeScalingActivitiesResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalingActivities (const DescribeScalingActivitiesRequest & request) slot
Provides descriptive information about the scaling activities in the specified namespace from the previous six
weeks>
You can filter the results using the ResourceId and ScalableDimension
parameters>
Scaling activities are triggered by CloudWatch alarms that are associated with scaling policies. To view the scaling policies for a service namespace, see DescribeScalingPolicies. To create a scaling policy or update an existing one, see
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 290 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingActivitiesResponse *>(send(request));
 }
describeScalingPolicies
DescribeScalingPoliciesResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalingPolicies (const DescribeScalingPoliciesRequest & request) slot
Describes the scaling policies for the specified service
namespace>
You can filter the results using the ResourceId, ScalableDimension, and PolicyNames
parameters>
To create a scaling policy or update an existing one, see PutScalingPolicy. If you are no longer using a scaling policy, you can delete it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 314 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingPoliciesResponse *>(send(request));
 }
describeScheduledActions
DescribeScheduledActionsResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScheduledActions (const DescribeScheduledActionsRequest & request) slot
Describes the scheduled actions for the specified service
namespace>
You can filter the results using the ResourceId, ScalableDimension, and ScheduledActionNames
parameters>
To create a scheduled action or update an existing one, see PutScheduledAction. If you are no longer using a scheduled action, you can delete it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 338 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScheduledActionsResponse *>(send(request));
 }
putScalingPolicy
PutScalingPolicyResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::putScalingPolicy (const PutScalingPolicyRequest & request) slot
Creates or updates a policy for an Application Auto Scaling scalable
target>
Each scalable target is identified by a service namespace, resource ID, and scalable dimension. A scaling policy applies to the scalable target identified by those three attributes. You cannot create a scaling policy until you register the scalable target using
RegisterScalableTarget>
To update a policy, specify its policy name and the parameters that you want to change. Any parameters that you don't specify are not changed by this update
request>
You can view the scaling policies for a service namespace using DescribeScalingPolicies. If you are no longer using a scaling policy, you can delete it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 368 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutScalingPolicyResponse *>(send(request));
 }
putScheduledAction
PutScheduledActionResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::putScheduledAction (const PutScheduledActionRequest & request) slot
Creates or updates a scheduled action for an Application Auto Scaling scalable
target>
Each scalable target is identified by a service namespace, resource ID, and scalable dimension. A scheduled action applies to the scalable target identified by those three attributes. You cannot create a scheduled action until you register the scalable target using
RegisterScalableTarget>
To update an action, specify its name and the parameters that you want to change. If you don't specify start and end times, the old values are deleted. Any other parameters that you don't specify are not changed by this update
request>
You can view the scheduled actions using DescribeScheduledActions. If you are no longer using a scheduled action, you can delete it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 398 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutScheduledActionResponse *>(send(request));
 }
registerScalableTarget
RegisterScalableTargetResponse * QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::registerScalableTarget (const RegisterScalableTargetRequest & request) slot
Registers or updates a scalable target. A scalable target is a resource that Application Auto Scaling can scale out or scale in. After you have registered a scalable target, you can use this operation to update the minimum and maximum values for its scalable
dimension>
After you register a scalable target, you can create and apply scaling policies using PutScalingPolicy. You can view the scaling policies for a service namespace using DescribeScalableTargets. If you no longer need a scalable target, you can deregister it using
Parameters
request Request to send to Application Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file applicationautoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterScalableTargetResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
application-autoscaling/applicationautoscalingclient.h
application-autoscaling/applicationautoscalingclient.cpp