AWS SDK for Qt: QtAws::XRay::XRayClient Class Reference
QtAws::XRay::XRayClient Class Reference
Client for AWS X-Ray.
Public Slots
BatchGetTracesResponse * batchGetTraces (const BatchGetTracesRequest &request)
GetServiceGraphResponse * getServiceGraph (const GetServiceGraphRequest &request)
GetTraceGraphResponse * getTraceGraph (const GetTraceGraphRequest &request)
GetTraceSummariesResponse * getTraceSummaries (const GetTraceSummariesRequest &request)
PutTelemetryRecordsResponse * putTelemetryRecords (const PutTelemetryRecordsRequest &request)
PutTraceSegmentsResponse * putTraceSegments (const PutTraceSegmentsRequest &request)
Public Member Functions
XRayClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new XRayClient object.
XRayClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new XRayClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS X-Ray.
AWS X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those
Definition at line 44 of file xrayclient.h.
Constructor & Destructor Documentation
XRayClient() [1/2]
QtAws::XRay::XRayClient::XRayClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new XRayClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 59 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new XRayClientPrivate(this), parent)
 {
     Q_D(XRayClient);
     d->apiVersion = QStringLiteral("2016-04-12");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("xray");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS X-Ray");
     d->serviceName = QStringLiteral("xray");
 }
XRayClient() [2/2]
QtAws::XRay::XRayClient::XRayClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new XRayClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 92 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new XRayClientPrivate(this), parent)
 {
     Q_D(XRayClient);
     d->apiVersion = QStringLiteral("2016-04-12");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("xray");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS X-Ray");
     d->serviceName = QStringLiteral("xray");
 }
Member Function Documentation
batchGetTraces
BatchGetTracesResponse * QtAws::XRay::XRayClient::batchGetTraces (const BatchGetTracesRequest & request) slot
Retrieves a list of traces specified by ID. Each trace is a collection of segment documents that originates from a single request. Use GetTraceSummaries to get a list of trace
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 119 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BatchGetTracesResponse *>(send(request));
 }
getServiceGraph
GetServiceGraphResponse * QtAws::XRay::XRayClient::getServiceGraph (const GetServiceGraphRequest & request) slot
Retrieves a document that describes services that process incoming requests, and downstream services that they call as a result. Root services process incoming requests and make calls to downstream services. Root services are applications that use the AWS X-Ray SDK. Downstream services can be other applications, AWS resources, HTTP web APIs, or SQL
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 135 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetServiceGraphResponse *>(send(request));
 }
getTraceGraph
GetTraceGraphResponse * QtAws::XRay::XRayClient::getTraceGraph (const GetTraceGraphRequest & request) slot
Retrieves a service graph for one or more specific trace
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 149 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTraceGraphResponse *>(send(request));
 }
getTraceSummaries
GetTraceSummariesResponse * QtAws::XRay::XRayClient::getTraceSummaries (const GetTraceSummariesRequest & request) slot
Retrieves IDs and metadata for traces available for a specified time frame using an optional filter. To get the full traces, pass the trace IDs to
BatchGetTraces>
A filter expression can target traced requests that hit specific service nodes or edges, have errors, or come from a known user. For example, the following filter expression targets traces that pass through
api.example.com>
service("api.example.com")
</p
This filter expression finds traces that have an annotation named account with the value
12345>
annotation.account = "12345"
</p
For a full list of indexed fields and keywords that you can use in filter expressions, see Using Filter Expressions in the AWS X-Ray Developer
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 187 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTraceSummariesResponse *>(send(request));
 }
putTelemetryRecords
PutTelemetryRecordsResponse * QtAws::XRay::XRayClient::putTelemetryRecords (const PutTelemetryRecordsRequest & request) slot
Used by the AWS X-Ray daemon to upload
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 201 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutTelemetryRecordsResponse *>(send(request));
 }
putTraceSegments
PutTraceSegmentsResponse * QtAws::XRay::XRayClient::putTraceSegments (const PutTraceSegmentsRequest & request) slot
Uploads segment documents to AWS X-Ray. The X-Ray SDK generates segment documents and sends them to the X-Ray daemon, which uploads them in batches. A segment document can be a completed segment, an in-progress segment, or an array of
subsegments>
Segments must include the following fields. For the full segment document schema, see AWS X-Ray Segment Documents in the AWS X-Ray Developer
Guide>
Required Segment Document Fields
</p
name - The name of the service that handled the
request>
id - A 64-bit identifier for the segment, unique among segments in the same trace, in 16 hexadecimal
digits>
trace_id - A unique identifier that connects all segments and subsegments originating from a single client
request>
start_time - Time the segment or subsegment was created, in floating point seconds in epoch time, accurate to milliseconds. For example, 1480615200.010 or
1.480615200010E9>
end_time - Time the segment or subsegment was closed. For example, 1480615200.090 or 1.480615200090E9. Specify either an end_time or
in_progress>
in_progress - Set to true instead of specifying an end_time to record that a segment has been started, but is not complete. Send an in progress segment when your application receives a request that will take a long time to serve, to trace the fact that the request was received. When the response is sent, send the complete segment to overwrite the in-progress
segment>
A trace_id consists of three numbers separated by hyphens. For example, 1-58406520-a006649127e371903a2de979. This
includes>
Trace ID Format
</p
The version number, i.e.
1>
The time of the original request, in Unix epoch time, in 8 hexadecimal digits. For example, 10:00AM December 2nd, 2016 PST in epoch time is 1480615200 seconds, or 58406520 in
hexadecimal>
A 96-bit identifier for the trace, globally unique, in 24 hexadecimal
Parameters
request Request to send to AWS X-Ray.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file xrayclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutTraceSegmentsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
xray/xrayclient.h
xray/xrayclient.cpp