AWS SDK for Qt: QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient Class Reference
QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient Class Reference
Client for AWS IoT Jobs Data Plane.
Public Slots
DescribeJobExecutionResponse * describeJobExecution (const DescribeJobExecutionRequest &request)
GetPendingJobExecutionsResponse * getPendingJobExecutions (const GetPendingJobExecutionsRequest &request)
StartNextPendingJobExecutionResponse * startNextPendingJobExecution (const StartNextPendingJobExecutionRequest &request)
UpdateJobExecutionResponse * updateJobExecution (const UpdateJobExecutionRequest &request)
Public Member Functions
IoTJobsDataPlaneClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new IoTJobsDataPlaneClient object.
IoTJobsDataPlaneClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new IoTJobsDataPlaneClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS IoT Jobs Data Plane.
AWS IoT Jobs is a service that allows you to define a set of jobs — remote operations that are sent to and executed on one or more devices connected to AWS IoT. For example, you can define a job that instructs a set of devices to download and install application or firmware updates, reboot, rotate certificates, or perform remote troubleshooting
operations>
To create a job, you make a job document which is a description of the remote operations to be performed, and you specify a list of targets that should perform the operations. The targets can be individual things, thing groups or
both>
AWS IoT Jobs sends a message to inform the targets that a job is available. The target starts the execution of the job by downloading the job document, performing the operations it specifies, and reporting its progress to AWS IoT. The Jobs service provides commands to track the progress of a job on a specific target and for all the targets of the
Definition at line 40 of file iotjobsdataplaneclient.h.
Constructor & Destructor Documentation
IoTJobsDataPlaneClient() [1/2]
QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new IoTJobsDataPlaneClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new IoTJobsDataPlaneClientPrivate(this), parent)
 {
     Q_D(IoTJobsDataPlaneClient);
     d->apiVersion = QStringLiteral("2017-09-29");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("data.jobs.iot");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS IoT Jobs Data Plane");
     d->serviceName = QStringLiteral("iot-jobs-data");
 }
IoTJobsDataPlaneClient() [2/2]
QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new IoTJobsDataPlaneClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 101 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new IoTJobsDataPlaneClientPrivate(this), parent)
 {
     Q_D(IoTJobsDataPlaneClient);
     d->apiVersion = QStringLiteral("2017-09-29");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("data.jobs.iot");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS IoT Jobs Data Plane");
     d->serviceName = QStringLiteral("iot-jobs-data");
 }
Member Function Documentation
describeJobExecution
DescribeJobExecutionResponse * QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::describeJobExecution (const DescribeJobExecutionRequest & request) slot
Gets details of a job
Parameters
request Request to send to AWS IoT Jobs Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 127 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeJobExecutionResponse *>(send(request));
 }
getPendingJobExecutions
GetPendingJobExecutionsResponse * QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::getPendingJobExecutions (const GetPendingJobExecutionsRequest & request) slot
Gets the list of all jobs for a thing that are not in a terminal
Parameters
request Request to send to AWS IoT Jobs Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 141 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPendingJobExecutionsResponse *>(send(request));
 }
startNextPendingJobExecution
StartNextPendingJobExecutionResponse * QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::startNextPendingJobExecution (const StartNextPendingJobExecutionRequest & request) slot
Gets and starts the next pending (status IN_PROGRESS or QUEUED) job execution for a
Parameters
request Request to send to AWS IoT Jobs Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 155 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartNextPendingJobExecutionResponse *>(send(request));
 }
updateJobExecution
UpdateJobExecutionResponse * QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::updateJobExecution (const UpdateJobExecutionRequest & request) slot
Updates the status of a job
Parameters
request Request to send to AWS IoT Jobs Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 169 of file iotjobsdataplaneclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateJobExecutionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
iot-jobs-data/iotjobsdataplaneclient.h
iot-jobs-data/iotjobsdataplaneclient.cpp