AWS SDK for Qt: QtAws::LexRuntimeService::LexRuntimeServiceClient Class Reference
QtAws::LexRuntimeService::LexRuntimeServiceClient Class Reference
Client for Amazon Lex Runtime Service.
Public Slots
PostContentResponse * postContent (const PostContentRequest &request)
PostTextResponse * postText (const PostTextRequest &request)
Public Member Functions
LexRuntimeServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexRuntimeServiceClient object.
LexRuntimeServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexRuntimeServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Lex Runtime Service.
Amazon Lex provides both build and runtime endpoints. Each endpoint provides a set of operations (API). Your conversational bot uses the runtime API to understand user utterances (user input text or voice). For example, suppose a user says "I want pizza", your bot sends this input to Amazon Lex using the runtime API. Amazon Lex recognizes that the user request is for the OrderPizza intent (one of the intents defined in the bot). Then Amazon Lex engages in user conversation on behalf of the bot to elicit required information (slot values, such as pizza size and crust type), and then performs fulfillment activity (that you configured when you created the bot). You use the build-time API to create and manage your Amazon Lex bot. For a list of build-time operations, see the build-time API, .
Definition at line 36 of file lexruntimeserviceclient.h.
Constructor & Destructor Documentation
LexRuntimeServiceClient() [1/2]
QtAws::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexRuntimeServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 57 of file lexruntimeserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new LexRuntimeServiceClientPrivate(this), parent)
 {
     Q_D(LexRuntimeServiceClient);
     d->apiVersion = QStringLiteral("2016-11-28");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("runtime.lex");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Lex Runtime Service");
     d->serviceName = QStringLiteral("lex");
 }
LexRuntimeServiceClient() [2/2]
QtAws::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexRuntimeServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 90 of file lexruntimeserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new LexRuntimeServiceClientPrivate(this), parent)
 {
     Q_D(LexRuntimeServiceClient);
     d->apiVersion = QStringLiteral("2016-11-28");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("runtime.lex");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Lex Runtime Service");
     d->serviceName = QStringLiteral("lex");
 }
Member Function Documentation
postContent
PostContentResponse * QtAws::LexRuntimeService::LexRuntimeServiceClient::postContent (const PostContentRequest & request) slot
Sends user input (text or speech) to Amazon Lex. Clients use this API to send text and audio requests to Amazon Lex at runtime. Amazon Lex interprets the user input using the machine learning model that it built for the bot.
</p
The PostContent operation supports audio input at 8kHz and 16kHz. You can use 8kHz audio to achieve higher speech recognition accuracy in telephone audio applications.
</p
In response, Amazon Lex returns the next message to convey to the user. Consider the following example messages:
</p
For a user input "I would like a pizza," Amazon Lex might return a response with a message eliciting slot data (for example, PizzaSize): "What size pizza would you like?".
</p
After the user provides all of the pizza order information, Amazon Lex might return a response with a message to get user confirmation: "Order the pizza?".
</p
After the user replies "Yes" to the confirmation prompt, Amazon Lex might return a conclusion statement: "Thank you, your cheese pizza has been ordered.".
</p
Not all Amazon Lex messages require a response from the user. For example, conclusion statements do not require a response. Some messages require only a yes or no response. In addition to the message, Amazon Lex provides additional context about the message in the response that you can use to enhance client behavior, such as displaying the appropriate client user interface. Consider the following examples:
</p
If the message is to elicit slot data, Amazon Lex returns the following context information:
</p
x-amz-lex-dialog-state header set to ElicitSlot
</p
x-amz-lex-intent-name header set to the intent name in the current context
</p
x-amz-lex-slot-to-elicit header set to the slot name for which the message is eliciting information
</p
x-amz-lex-slots header set to a map of slots configured for the intent with their current values
</p
If the message is a confirmation prompt, the x-amz-lex-dialog-state header is set to Confirmation and the x-amz-lex-slot-to-elicit header is omitted.
</p
If the message is a clarification prompt configured for the intent, indicating that the user intent is not understood, the x-amz-dialog-state header is set to ElicitIntent and the x-amz-slot-to-elicit header is omitted.
</p
In addition, Amazon Lex also returns your application-specific sessionAttributes. For more information, see Managing Conversation Context.
Parameters
request Request to send to Amazon Lex Runtime Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 185 of file lexruntimeserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PostContentResponse *>(send(request));
 }
postText
PostTextResponse * QtAws::LexRuntimeService::LexRuntimeServiceClient::postText (const PostTextRequest & request) slot
Sends user input (text-only) to Amazon Lex. Client applications can use this API to send requests to Amazon Lex at runtime. Amazon Lex then interprets the user input using the machine learning model it built for the bot.
</p
In response, Amazon Lex returns the next message to convey to the user an optional responseCard to display. Consider the following example messages:
</p
For a user input "I would like a pizza", Amazon Lex might return a response with a message eliciting slot data (for example, PizzaSize): "What size pizza would you like?"
</p
After the user provides all of the pizza order information, Amazon Lex might return a response with a message to obtain user confirmation "Proceed with the pizza order?".
</p
After the user replies to a confirmation prompt with a "yes", Amazon Lex might return a conclusion statement: "Thank you, your cheese pizza has been ordered.".
</p
Not all Amazon Lex messages require a user response. For example, a conclusion statement does not require a response. Some messages require only a "yes" or "no" user response. In addition to the message, Amazon Lex provides additional context about the message in the response that you might use to enhance client behavior, for example, to display the appropriate client user interface. These are the slotToElicit, dialogState, intentName, and slots fields in the response. Consider the following examples:
</p
If the message is to elicit slot data, Amazon Lex returns the following context
information>
dialogState set to ElicitSlot
</p
intentName set to the intent name in the current context
</p
slotToElicit set to the slot name for which the message is eliciting information
</p
slots set to a map of slots, configured for the intent, with currently known values
</p
If the message is a confirmation prompt, the dialogState is set to ConfirmIntent and SlotToElicit is set to null.
</p
If the message is a clarification prompt (configured for the intent) that indicates that user intent is not understood, the dialogState is set to ElicitIntent and slotToElicit is set to null.
</p
In addition, Amazon Lex also returns your application-specific sessionAttributes. For more information, see Managing Conversation Context.
Parameters
request Request to send to Amazon Lex Runtime Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 263 of file lexruntimeserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PostTextResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
runtime.lex/lexruntimeserviceclient.h
runtime.lex/lexruntimeserviceclient.cpp