AWS SDK for Qt: QtAws::CognitoSync::CognitoSyncClient Class Reference
QtAws::CognitoSync::CognitoSyncClient Class Reference
Client for Amazon Cognito Sync.
Public Slots
BulkPublishResponse * bulkPublish (const BulkPublishRequest &request)
DeleteDatasetResponse * deleteDataset (const DeleteDatasetRequest &request)
DescribeDatasetResponse * describeDataset (const DescribeDatasetRequest &request)
DescribeIdentityPoolUsageResponse * describeIdentityPoolUsage (const DescribeIdentityPoolUsageRequest &request)
DescribeIdentityUsageResponse * describeIdentityUsage (const DescribeIdentityUsageRequest &request)
GetBulkPublishDetailsResponse * getBulkPublishDetails (const GetBulkPublishDetailsRequest &request)
GetCognitoEventsResponse * getCognitoEvents (const GetCognitoEventsRequest &request)
GetIdentityPoolConfigurationResponse * getIdentityPoolConfiguration (const GetIdentityPoolConfigurationRequest &request)
ListDatasetsResponse * listDatasets (const ListDatasetsRequest &request)
ListIdentityPoolUsageResponse * listIdentityPoolUsage (const ListIdentityPoolUsageRequest &request)
ListRecordsResponse * listRecords (const ListRecordsRequest &request)
RegisterDeviceResponse * registerDevice (const RegisterDeviceRequest &request)
SetCognitoEventsResponse * setCognitoEvents (const SetCognitoEventsRequest &request)
SetIdentityPoolConfigurationResponse * setIdentityPoolConfiguration (const SetIdentityPoolConfigurationRequest &request)
SubscribeToDatasetResponse * subscribeToDataset (const SubscribeToDatasetRequest &request)
UnsubscribeFromDatasetResponse * unsubscribeFromDataset (const UnsubscribeFromDatasetRequest &request)
UpdateRecordsResponse * updateRecords (const UpdateRecordsRequest &request)
Public Member Functions
CognitoSyncClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoSyncClient object.
CognitoSyncClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoSyncClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Cognito Sync.
<fullname>Amazon Cognito Sync</fullname>
Amazon Cognito Sync provides an AWS service and client library that enable cross-device syncing of application-related user data. High-level client libraries are available for both iOS and Android. You can use these libraries to persist data locally so that it's available even if the device is offline. Developer credentials don't need to be stored on the mobile device to access the service. You can use Amazon Cognito to obtain a normalized user ID and credentials. User data is persisted in a dataset that can store up to 1 MB of key-value pairs, and you can have up to 20 datasets per user
identity>
With Amazon Cognito Sync, the data stored for each identity is accessible only to credentials assigned to that identity. In order to use the Cognito Sync service, you need to make API calls using credentials retrieved with Amazon Cognito Identity service>
If you want to use Cognito Sync in an Android or iOS application, you will probably want to make API calls via the AWS Mobile SDK. To learn more, see the Developer Guide for Android and the Developer Guide for
Definition at line 66 of file cognitosyncclient.h.
Constructor & Destructor Documentation
CognitoSyncClient() [1/2]
QtAws::CognitoSync::CognitoSyncClient::CognitoSyncClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoSyncClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 100 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CognitoSyncClientPrivate(this), parent)
 {
     Q_D(CognitoSyncClient);
     d->apiVersion = QStringLiteral("2014-06-30");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cognito-sync");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Cognito Sync");
     d->serviceName = QStringLiteral("cognito-sync");
 }
CognitoSyncClient() [2/2]
QtAws::CognitoSync::CognitoSyncClient::CognitoSyncClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoSyncClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 133 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CognitoSyncClientPrivate(this), parent)
 {
     Q_D(CognitoSyncClient);
     d->apiVersion = QStringLiteral("2014-06-30");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cognito-sync");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Cognito Sync");
     d->serviceName = QStringLiteral("cognito-sync");
 }
Member Function Documentation
bulkPublish
BulkPublishResponse * QtAws::CognitoSync::CognitoSyncClient::bulkPublish (const BulkPublishRequest & request) slot
Initiates a bulk publish of all existing datasets for an Identity Pool to the configured stream. Customers are limited to one successful bulk publish per 24 hours. Bulk publish is an asynchronous request, customers can see the status of the request via the GetBulkPublishDetails
operation>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 166 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<BulkPublishResponse *>(send(request));
 }
deleteDataset
DeleteDatasetResponse * QtAws::CognitoSync::CognitoSyncClient::deleteDataset (const DeleteDatasetRequest & request) slot
Deletes the specific dataset. The dataset will be deleted permanently, and the action can't be undone. Datasets that this dataset was merged with will no longer report the merge. Any subsequent operation on this dataset will result in a
ResourceNotFoundException>
This API can be called with temporary user credentials provided by Cognito Identity or with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 185 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteDatasetResponse *>(send(request));
 }
describeDataset
DescribeDatasetResponse * QtAws::CognitoSync::CognitoSyncClient::describeDataset (const DescribeDatasetRequest & request) slot
Gets meta data about a dataset by identity and dataset name. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity
data>
This API can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use Cognito Identity credentials to make this API
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 205 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeDatasetResponse *>(send(request));
 }
describeIdentityPoolUsage
DescribeIdentityPoolUsageResponse * QtAws::CognitoSync::CognitoSyncClient::describeIdentityPoolUsage (const DescribeIdentityPoolUsageRequest & request) slot
Gets usage details (for example, data storage) about a particular identity
pool>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 224 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIdentityPoolUsageResponse *>(send(request));
 }
describeIdentityUsage
DescribeIdentityUsageResponse * QtAws::CognitoSync::CognitoSyncClient::describeIdentityUsage (const DescribeIdentityUsageRequest & request) slot
Gets usage information for an identity, including number of datasets and data
usage>
This API can be called with temporary user credentials provided by Cognito Identity or with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 242 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeIdentityUsageResponse *>(send(request));
 }
getBulkPublishDetails
GetBulkPublishDetailsResponse * QtAws::CognitoSync::CognitoSyncClient::getBulkPublishDetails (const GetBulkPublishDetailsRequest & request) slot
Get the status of the last BulkPublish operation for an identity
pool>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 261 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBulkPublishDetailsResponse *>(send(request));
 }
getCognitoEvents
GetCognitoEventsResponse * QtAws::CognitoSync::CognitoSyncClient::getCognitoEvents (const GetCognitoEventsRequest & request) slot
Gets the events and the corresponding Lambda functions associated with an identity
pool>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 280 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCognitoEventsResponse *>(send(request));
 }
getIdentityPoolConfiguration
GetIdentityPoolConfigurationResponse * QtAws::CognitoSync::CognitoSyncClient::getIdentityPoolConfiguration (const GetIdentityPoolConfigurationRequest & request) slot
Gets the configuration settings of an identity
pool>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 299 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityPoolConfigurationResponse *>(send(request));
 }
listDatasets
ListDatasetsResponse * QtAws::CognitoSync::CognitoSyncClient::listDatasets (const ListDatasetsRequest & request) slot
Lists datasets for an identity. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity
data>
ListDatasets can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use the Cognito Identity credentials to make this API
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 319 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListDatasetsResponse *>(send(request));
 }
listIdentityPoolUsage
ListIdentityPoolUsageResponse * QtAws::CognitoSync::CognitoSyncClient::listIdentityPoolUsage (const ListIdentityPoolUsageRequest & request) slot
Gets a list of identity pools registered with
Cognito>
ListIdentityPoolUsage can only be called with developer credentials. You cannot make this API call with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 338 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListIdentityPoolUsageResponse *>(send(request));
 }
listRecords
ListRecordsResponse * QtAws::CognitoSync::CognitoSyncClient::listRecords (const ListRecordsRequest & request) slot
Gets paginated records, optionally changed after a particular sync count for a dataset and identity. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity
data>
ListRecords can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use Cognito Identity credentials to make this API
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 359 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListRecordsResponse *>(send(request));
 }
registerDevice
RegisterDeviceResponse * QtAws::CognitoSync::CognitoSyncClient::registerDevice (const RegisterDeviceRequest & request) slot
Registers a device to receive push sync
notifications>
This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RegisterDeviceResponse *>(send(request));
 }
setCognitoEvents
SetCognitoEventsResponse * QtAws::CognitoSync::CognitoSyncClient::setCognitoEvents (const SetCognitoEventsRequest & request) slot
Sets the AWS Lambda function for a given event type for an identity pool. This request only updates the key/value pair specified. Other key/values pairs are not updated. To remove a key value pair, pass a empty value for the particular
key>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 398 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetCognitoEventsResponse *>(send(request));
 }
setIdentityPoolConfiguration
SetIdentityPoolConfigurationResponse * QtAws::CognitoSync::CognitoSyncClient::setIdentityPoolConfiguration (const SetIdentityPoolConfigurationRequest & request) slot
Sets the necessary configuration for push
sync>
This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 417 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityPoolConfigurationResponse *>(send(request));
 }
subscribeToDataset
SubscribeToDatasetResponse * QtAws::CognitoSync::CognitoSyncClient::subscribeToDataset (const SubscribeToDatasetRequest & request) slot
Subscribes to receive notifications when a dataset is modified by another
device>
This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 436 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SubscribeToDatasetResponse *>(send(request));
 }
unsubscribeFromDataset
UnsubscribeFromDatasetResponse * QtAws::CognitoSync::CognitoSyncClient::unsubscribeFromDataset (const UnsubscribeFromDatasetRequest & request) slot
Unsubscribes from receiving notifications when a dataset is modified by another
device>
This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 455 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UnsubscribeFromDatasetResponse *>(send(request));
 }
updateRecords
UpdateRecordsResponse * QtAws::CognitoSync::CognitoSyncClient::updateRecords (const UpdateRecordsRequest & request) slot
Posts updates to records and adds and deletes records for a dataset and
user>
The sync count in the record patch is your last known sync count for that record. The server will reject an UpdateRecords request with a ResourceConflictException if you try to patch a record with a new value but a stale sync
count>
For example, if the sync count on the server is 5 for a key called highScore and you try and submit a new highScore with sync count of 4, the request will be rejected. To obtain the current sync count for a record, call ListRecords. On a successful update of the record, the response returns the new sync count for that record. You should present that sync count the next time you try to update that same record. When the record does not exist, specify the sync count as
0>
This API can be called with temporary user credentials provided by Cognito Identity or with developer
Parameters
request Request to send to Amazon Cognito Sync.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 485 of file cognitosyncclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateRecordsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cognito-sync/cognitosyncclient.h
cognito-sync/cognitosyncclient.cpp