AWS SDK for Qt: QtAws::SFN::SfnClient Class Reference
QtAws::SFN::SfnClient Class Reference
Client for AWS Step Functions (SFN)
Public Slots
CreateActivityResponse * createActivity (const CreateActivityRequest &request)
CreateStateMachineResponse * createStateMachine (const CreateStateMachineRequest &request)
DeleteActivityResponse * deleteActivity (const DeleteActivityRequest &request)
DeleteStateMachineResponse * deleteStateMachine (const DeleteStateMachineRequest &request)
DescribeActivityResponse * describeActivity (const DescribeActivityRequest &request)
DescribeExecutionResponse * describeExecution (const DescribeExecutionRequest &request)
DescribeStateMachineResponse * describeStateMachine (const DescribeStateMachineRequest &request)
DescribeStateMachineForExecutionResponse * describeStateMachineForExecution (const DescribeStateMachineForExecutionRequest &request)
GetActivityTaskResponse * getActivityTask (const GetActivityTaskRequest &request)
GetExecutionHistoryResponse * getExecutionHistory (const GetExecutionHistoryRequest &request)
ListActivitiesResponse * listActivities (const ListActivitiesRequest &request)
ListExecutionsResponse * listExecutions (const ListExecutionsRequest &request)
ListStateMachinesResponse * listStateMachines (const ListStateMachinesRequest &request)
SendTaskFailureResponse * sendTaskFailure (const SendTaskFailureRequest &request)
SendTaskHeartbeatResponse * sendTaskHeartbeat (const SendTaskHeartbeatRequest &request)
SendTaskSuccessResponse * sendTaskSuccess (const SendTaskSuccessRequest &request)
StartExecutionResponse * startExecution (const StartExecutionRequest &request)
StopExecutionResponse * stopExecution (const StopExecutionRequest &request)
UpdateStateMachineResponse * updateStateMachine (const UpdateStateMachineRequest &request)
Public Member Functions
SfnClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SfnClient object.
SfnClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SfnClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Step Functions (SFN)
<fullname>AWS Step Functions</fullname>
AWS Step Functions is a service that lets you coordinate the components of distributed applications and microservices using visual
workflows>
You can use Step Functions to build applications from individual components, each of which performs a discrete function, or task, allowing you to scale and change applications quickly. Step Functions provides a console that helps visualize the components of your application as a series of steps. Step Functions automatically triggers and tracks each step, and retries steps when there are errors, so your application executes predictably and in the right order every time. Step Functions logs the state of each step, so you can quickly diagnose and debug any
issues>
Step Functions manages operations and underlying infrastructure to ensure your application is available at any scale. You can run tasks on AWS, your own servers, or any system that has access to AWS. You can access and use Step Functions using the console, the AWS SDKs, or an HTTP API. For more information about Step Functions, see the AWS Step Functions Developer Guide
Definition at line 70 of file sfnclient.h.
Constructor & Destructor Documentation
SfnClient() [1/2]
QtAws::SFN::SfnClient::SfnClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SfnClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 103 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SfnClientPrivate(this), parent)
 {
     Q_D(SfnClient);
     d->apiVersion = QStringLiteral("2016-11-23");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("states");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Step Functions");
     d->serviceName = QStringLiteral("states");
 }
SfnClient() [2/2]
QtAws::SFN::SfnClient::SfnClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SfnClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 136 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SfnClientPrivate(this), parent)
 {
     Q_D(SfnClient);
     d->apiVersion = QStringLiteral("2016-11-23");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("states");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Step Functions");
     d->serviceName = QStringLiteral("states");
 }
Member Function Documentation
createActivity
CreateActivityResponse * QtAws::SFN::SfnClient::createActivity (const CreateActivityRequest & request) slot
Creates an activity. An activity is a task which you write in any programming language and host on any machine which has access to AWS Step Functions. Activities must poll Step Functions using the GetActivityTask API action and respond using SendTask* API actions. This function lets Step Functions know the existence of your activity and returns an identifier for use in a state machine and when polling from the
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 165 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateActivityResponse *>(send(request));
 }
createStateMachine
CreateStateMachineResponse * QtAws::SFN::SfnClient::createStateMachine (const CreateStateMachineRequest & request) slot
Creates a state machine. A state machine consists of a collection of states that can do work (Task states), determine to which states to transition next (Choice states), stop an execution with an error (Fail states), and so on. State machines are specified using a JSON-based, structured
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 181 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateStateMachineResponse *>(send(request));
 }
deleteActivity
DeleteActivityResponse * QtAws::SFN::SfnClient::deleteActivity (const DeleteActivityRequest & request) slot
Deletes an
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 195 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteActivityResponse *>(send(request));
 }
deleteStateMachine
DeleteStateMachineResponse * QtAws::SFN::SfnClient::deleteStateMachine (const DeleteStateMachineRequest & request) slot
Deletes a state machine. This is an asynchronous operation: It sets the state machine's status to DELETING and begins the deletion process. Each state machine execution is deleted the next time it makes a state
transition> <note>
The state machine itself is deleted after all executions are completed or
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 214 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteStateMachineResponse *>(send(request));
 }
describeActivity
DescribeActivityResponse * QtAws::SFN::SfnClient::describeActivity (const DescribeActivityRequest & request) slot
Describes an
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 228 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeActivityResponse *>(send(request));
 }
describeExecution
DescribeExecutionResponse * QtAws::SFN::SfnClient::describeExecution (const DescribeExecutionRequest & request) slot
Describes an
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 242 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeExecutionResponse *>(send(request));
 }
describeStateMachine
DescribeStateMachineResponse * QtAws::SFN::SfnClient::describeStateMachine (const DescribeStateMachineRequest & request) slot
Describes a state
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 256 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStateMachineResponse *>(send(request));
 }
describeStateMachineForExecution
DescribeStateMachineForExecutionResponse * QtAws::SFN::SfnClient::describeStateMachineForExecution (const DescribeStateMachineForExecutionRequest & request) slot
Describes the state machine associated with a specific
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 270 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStateMachineForExecutionResponse *>(send(request));
 }
getActivityTask
GetActivityTaskResponse * QtAws::SFN::SfnClient::getActivityTask (const GetActivityTaskRequest & request) slot
Used by workers to retrieve a task (with the specified activity ARN) which has been scheduled for execution by a running state machine. This initiates a long poll, where the service holds the HTTP connection open and responds as soon as a task becomes available (i.e. an execution of a task of this type is needed.) The maximum time the service holds on to the request before responding is 60 seconds. If no task is available within 60 seconds, the poll returns a taskToken with a null
string>
Workers should set their client side socket timeout to at least 65 seconds (5 seconds higher than the maximum time the service may hold the poll
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 293 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetActivityTaskResponse *>(send(request));
 }
getExecutionHistory
GetExecutionHistoryResponse * QtAws::SFN::SfnClient::getExecutionHistory (const GetExecutionHistoryRequest & request) slot
Returns the history of the specified execution as a list of events. By default, the results are returned in ascending order of the timeStamp of the events. Use the reverseOrder parameter to get the latest events
first>
If a nextToken is returned by a previous call, there are more results available. To retrieve the next page of results, make the call again using the returned token in nextToken. Keep all other arguments
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 313 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetExecutionHistoryResponse *>(send(request));
 }
listActivities
ListActivitiesResponse * QtAws::SFN::SfnClient::listActivities (const ListActivitiesRequest & request) slot
Lists the existing
activities>
If a nextToken is returned by a previous call, there are more results available. To retrieve the next page of results, make the call again using the returned token in nextToken. Keep all other arguments
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 332 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListActivitiesResponse *>(send(request));
 }
listExecutions
ListExecutionsResponse * QtAws::SFN::SfnClient::listExecutions (const ListExecutionsRequest & request) slot
Lists the executions of a state machine that meet the filtering
criteria>
If a nextToken is returned by a previous call, there are more results available. To retrieve the next page of results, make the call again using the returned token in nextToken. Keep all other arguments
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListExecutionsResponse *>(send(request));
 }
listStateMachines
ListStateMachinesResponse * QtAws::SFN::SfnClient::listStateMachines (const ListStateMachinesRequest & request) slot
Lists the existing state
machines>
If a nextToken is returned by a previous call, there are more results available. To retrieve the next page of results, make the call again using the returned token in nextToken. Keep all other arguments
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 370 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStateMachinesResponse *>(send(request));
 }
sendTaskFailure
SendTaskFailureResponse * QtAws::SFN::SfnClient::sendTaskFailure (const SendTaskFailureRequest & request) slot
Used by workers to report that the task identified by the taskToken
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 384 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendTaskFailureResponse *>(send(request));
 }
sendTaskHeartbeat
SendTaskHeartbeatResponse * QtAws::SFN::SfnClient::sendTaskHeartbeat (const SendTaskHeartbeatRequest & request) slot
Used by workers to report to the service that the task represented by the specified taskToken is still making progress. This action resets the Heartbeat clock. The Heartbeat threshold is specified in the state machine's Amazon States Language definition. This action does not in itself create an event in the execution history. However, if the task times out, the execution history contains an ActivityTimedOut
event> <note>
The Timeout of a task, defined in the state machine's Amazon States Language definition, is its maximum allowed duration, regardless of the number of SendTaskHeartbeat requests
received> </note> <note>
This operation is only useful for long-lived tasks to report the liveliness of the
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 410 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendTaskHeartbeatResponse *>(send(request));
 }
sendTaskSuccess
SendTaskSuccessResponse * QtAws::SFN::SfnClient::sendTaskSuccess (const SendTaskSuccessRequest & request) slot
Used by workers to report that the task identified by the taskToken completed
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 424 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendTaskSuccessResponse *>(send(request));
 }
startExecution
StartExecutionResponse * QtAws::SFN::SfnClient::startExecution (const StartExecutionRequest & request) slot
Starts a state machine
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 438 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartExecutionResponse *>(send(request));
 }
stopExecution
StopExecutionResponse * QtAws::SFN::SfnClient::stopExecution (const StopExecutionRequest & request) slot
Stops an
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 452 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopExecutionResponse *>(send(request));
 }
updateStateMachine
UpdateStateMachineResponse * QtAws::SFN::SfnClient::updateStateMachine (const UpdateStateMachineRequest & request) slot
Updates an existing state machine by modifying its definition and/or roleArn. Running executions will continue to use the previous definition and
roleArn> <note>
All StartExecution calls within a few seconds will use the updated definition and roleArn. Executions started immediately after calling UpdateStateMachine may use the previous state machine definition and roleArn. You must include at least one of definition or roleArn or you will receive a MissingRequiredParameter
Parameters
request Request to send to AWS Step Functions.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 474 of file sfnclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateStateMachineResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
states/sfnclient.h
states/sfnclient.cpp