AWS SDK for Qt: QtAws::EMR::EmrClient Class Reference
QtAws::EMR::EmrClient Class Reference
Client for Amazon Elastic MapReduce (EMR)
Public Slots
AddInstanceFleetResponse * addInstanceFleet (const AddInstanceFleetRequest &request)
AddInstanceGroupsResponse * addInstanceGroups (const AddInstanceGroupsRequest &request)
AddJobFlowStepsResponse * addJobFlowSteps (const AddJobFlowStepsRequest &request)
AddTagsResponse * addTags (const AddTagsRequest &request)
CancelStepsResponse * cancelSteps (const CancelStepsRequest &request)
CreateSecurityConfigurationResponse * createSecurityConfiguration (const CreateSecurityConfigurationRequest &request)
DeleteSecurityConfigurationResponse * deleteSecurityConfiguration (const DeleteSecurityConfigurationRequest &request)
DescribeClusterResponse * describeCluster (const DescribeClusterRequest &request)
DescribeJobFlowsResponse * describeJobFlows (const DescribeJobFlowsRequest &request)
DescribeSecurityConfigurationResponse * describeSecurityConfiguration (const DescribeSecurityConfigurationRequest &request)
DescribeStepResponse * describeStep (const DescribeStepRequest &request)
ListBootstrapActionsResponse * listBootstrapActions (const ListBootstrapActionsRequest &request)
ListClustersResponse * listClusters (const ListClustersRequest &request)
ListInstanceFleetsResponse * listInstanceFleets (const ListInstanceFleetsRequest &request)
ListInstanceGroupsResponse * listInstanceGroups (const ListInstanceGroupsRequest &request)
ListInstancesResponse * listInstances (const ListInstancesRequest &request)
ListSecurityConfigurationsResponse * listSecurityConfigurations (const ListSecurityConfigurationsRequest &request)
ListStepsResponse * listSteps (const ListStepsRequest &request)
ModifyInstanceFleetResponse * modifyInstanceFleet (const ModifyInstanceFleetRequest &request)
ModifyInstanceGroupsResponse * modifyInstanceGroups (const ModifyInstanceGroupsRequest &request)
PutAutoScalingPolicyResponse * putAutoScalingPolicy (const PutAutoScalingPolicyRequest &request)
RemoveAutoScalingPolicyResponse * removeAutoScalingPolicy (const RemoveAutoScalingPolicyRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
RunJobFlowResponse * runJobFlow (const RunJobFlowRequest &request)
SetTerminationProtectionResponse * setTerminationProtection (const SetTerminationProtectionRequest &request)
SetVisibleToAllUsersResponse * setVisibleToAllUsers (const SetVisibleToAllUsersRequest &request)
TerminateJobFlowsResponse * terminateJobFlows (const TerminateJobFlowsRequest &request)
Public Member Functions
EmrClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EmrClient object.
EmrClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EmrClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Elastic MapReduce (EMR)
Amazon EMR is a web service that makes it easy to process large amounts of data efficiently. Amazon EMR uses Hadoop processing combined with several AWS products to do tasks such as web indexing, data mining, log file analysis, machine learning, scientific simulation, and data
Definition at line 86 of file emrclient.h.
Constructor & Destructor Documentation
EmrClient() [1/2]
QtAws::EMR::EmrClient::EmrClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EmrClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 103 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new EmrClientPrivate(this), parent)
 {
     Q_D(EmrClient);
     d->apiVersion = QStringLiteral("2009-03-31");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("elasticmapreduce");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Elastic MapReduce");
     d->serviceName = QStringLiteral("elasticmapreduce");
 }
EmrClient() [2/2]
QtAws::EMR::EmrClient::EmrClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EmrClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 136 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new EmrClientPrivate(this), parent)
 {
     Q_D(EmrClient);
     d->apiVersion = QStringLiteral("2009-03-31");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("elasticmapreduce");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Elastic MapReduce");
     d->serviceName = QStringLiteral("elasticmapreduce");
 }
Member Function Documentation
addInstanceFleet
AddInstanceFleetResponse * QtAws::EMR::EmrClient::addInstanceFleet (const AddInstanceFleetRequest & request) slot
Adds an instance fleet to a running
cluster> <note>
The instance fleet configuration is available only in Amazon EMR versions 4.8.0 and later, excluding
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 166 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddInstanceFleetResponse *>(send(request));
 }
addInstanceGroups
AddInstanceGroupsResponse * QtAws::EMR::EmrClient::addInstanceGroups (const AddInstanceGroupsRequest & request) slot
Adds one or more instance groups to a running
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 180 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddInstanceGroupsResponse *>(send(request));
 }
addJobFlowSteps
AddJobFlowStepsResponse * QtAws::EMR::EmrClient::addJobFlowSteps (const AddJobFlowStepsRequest & request) slot
AddJobFlowSteps adds new steps to a running cluster. A maximum of 256 steps are allowed in each job
flow>
If your cluster is long-running (such as a Hive data warehouse) or complex, you may require more than 256 steps to process your data. You can bypass the 256-step limitation in various ways, including using SSH to connect to the master node and submitting queries directly to the software running on the master node, such as Hive and Hadoop. For more information on how to do this, see Add More than 256 Steps to a Cluster in the Amazon EMR Management
Guide>
A step specifies the location of a JAR file stored either on the master node of the cluster or in Amazon S3. Each step is performed by the main function of the main class of the JAR file. The main class can be specified either in the manifest of the JAR or by using the MainFunction parameter of the
step>
Amazon EMR executes each step in the order listed. For a step to be considered complete, the main function must exit with a zero exit code and all Hadoop jobs started while the step was running must have completed and run
successfully>
You can only add steps to a cluster that is in one of the following states: STARTING, BOOTSTRAPPING, RUNNING, or
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 218 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddJobFlowStepsResponse *>(send(request));
 }
addTags
AddTagsResponse * QtAws::EMR::EmrClient::addTags (const AddTagsRequest & request) slot
Adds tags to an Amazon EMR resource. Tags make it easier to associate clusters in various ways, such as grouping clusters to track your Amazon EMR resource allocation costs. For more information, see Tag Clusters.
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 234 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
cancelSteps
CancelStepsResponse * QtAws::EMR::EmrClient::cancelSteps (const CancelStepsRequest & request) slot
Cancels a pending step or steps in a running cluster. Available only in Amazon EMR versions 4.8.0 and later, excluding version 5.0.0. A maximum of 256 steps are allowed in each CancelSteps request. CancelSteps is idempotent but asynchronous; it does not guarantee a step will be canceled, even if the request is successfully submitted. You can only cancel steps that are in a PENDING
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 251 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CancelStepsResponse *>(send(request));
 }
createSecurityConfiguration
CreateSecurityConfigurationResponse * QtAws::EMR::EmrClient::createSecurityConfiguration (const CreateSecurityConfigurationRequest & request) slot
Creates a security configuration, which is stored in the service and can be specified when a cluster is
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 265 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSecurityConfigurationResponse *>(send(request));
 }
deleteSecurityConfiguration
DeleteSecurityConfigurationResponse * QtAws::EMR::EmrClient::deleteSecurityConfiguration (const DeleteSecurityConfigurationRequest & request) slot
Deletes a security
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 279 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSecurityConfigurationResponse *>(send(request));
 }
describeCluster
DescribeClusterResponse * QtAws::EMR::EmrClient::describeCluster (const DescribeClusterRequest & request) slot
Provides cluster-level details including status, hardware and software configuration, VPC settings, and so on. For information about the cluster steps, see
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 294 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeClusterResponse *>(send(request));
 }
describeJobFlows
DescribeJobFlowsResponse * QtAws::EMR::EmrClient::describeJobFlows (const DescribeJobFlowsRequest & request) slot
This API is deprecated and will eventually be removed. We recommend you use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions
instead>
DescribeJobFlows returns a list of job flows that match all of the supplied parameters. The parameters can include a list of job flow IDs, job flow states, and restrictions on job flow creation date and
time>
Regardless of supplied parameters, only job flows created within the last two months are
returned>
If no parameters are supplied, then job flows matching either of the following criteria are
returned>
Job flows created and completed in the last two
week>
Job flows created within the last two months that are in one of the following states: RUNNING, WAITING, SHUTTING_DOWN, STARTING
</p
Amazon EMR can return a maximum of 512 job flow
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 335 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeJobFlowsResponse *>(send(request));
 }
describeSecurityConfiguration
DescribeSecurityConfigurationResponse * QtAws::EMR::EmrClient::describeSecurityConfiguration (const DescribeSecurityConfigurationRequest & request) slot
Provides the details of a security configuration by returning the configuration
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 349 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSecurityConfigurationResponse *>(send(request));
 }
describeStep
DescribeStepResponse * QtAws::EMR::EmrClient::describeStep (const DescribeStepRequest & request) slot
Provides more detail about the cluster
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 363 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeStepResponse *>(send(request));
 }
listBootstrapActions
ListBootstrapActionsResponse * QtAws::EMR::EmrClient::listBootstrapActions (const ListBootstrapActionsRequest & request) slot
Provides information about the bootstrap actions associated with a
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 377 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBootstrapActionsResponse *>(send(request));
 }
listClusters
ListClustersResponse * QtAws::EMR::EmrClient::listClusters (const ListClustersRequest & request) slot
Provides the status of all clusters visible to this AWS account. Allows you to filter the list of clusters based on certain criteria; for example, filtering by cluster creation date and time or by status. This call returns a maximum of 50 clusters per call, but returns a marker to track the paging of the cluster list across multiple ListClusters
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 393 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListClustersResponse *>(send(request));
 }
listInstanceFleets
ListInstanceFleetsResponse * QtAws::EMR::EmrClient::listInstanceFleets (const ListInstanceFleetsRequest & request) slot
Lists all available details about the instance fleets in a
cluster> <note>
The instance fleet configuration is available only in Amazon EMR versions 4.8.0 and later, excluding 5.0.x
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 411 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstanceFleetsResponse *>(send(request));
 }
listInstanceGroups
ListInstanceGroupsResponse * QtAws::EMR::EmrClient::listInstanceGroups (const ListInstanceGroupsRequest & request) slot
Provides all available details about the instance groups in a
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 425 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstanceGroupsResponse *>(send(request));
 }
listInstances
ListInstancesResponse * QtAws::EMR::EmrClient::listInstances (const ListInstancesRequest & request) slot
Provides information for all active EC2 instances and EC2 instances terminated in the last 30 days, up to a maximum of 2,000. EC2 instances in any of the following states are considered active: AWAITING_FULFILLMENT, PROVISIONING, BOOTSTRAPPING,
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 441 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListInstancesResponse *>(send(request));
 }
listSecurityConfigurations
ListSecurityConfigurationsResponse * QtAws::EMR::EmrClient::listSecurityConfigurations (const ListSecurityConfigurationsRequest & request) slot
Lists all the security configurations visible to this account, providing their creation dates and times, and their names. This call returns a maximum of 50 clusters per call, but returns a marker to track the paging of the cluster list across multiple ListSecurityConfigurations
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 457 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListSecurityConfigurationsResponse *>(send(request));
 }
listSteps
ListStepsResponse * QtAws::EMR::EmrClient::listSteps (const ListStepsRequest & request) slot
Provides a list of steps for the cluster in reverse order unless you specify stepIds with the
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 471 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListStepsResponse *>(send(request));
 }
modifyInstanceFleet
ModifyInstanceFleetResponse * QtAws::EMR::EmrClient::modifyInstanceFleet (const ModifyInstanceFleetRequest & request) slot
Modifies the target On-Demand and target Spot capacities for the instance fleet with the specified InstanceFleetID within the cluster specified using ClusterID. The call either succeeds or fails
atomically> <note>
The instance fleet configuration is available only in Amazon EMR versions 4.8.0 and later, excluding 5.0.x
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 490 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyInstanceFleetResponse *>(send(request));
 }
modifyInstanceGroups
ModifyInstanceGroupsResponse * QtAws::EMR::EmrClient::modifyInstanceGroups (const ModifyInstanceGroupsRequest & request) slot
ModifyInstanceGroups modifies the number of nodes and configuration settings of an instance group. The input parameters include the new target instance count for the group and the instance group ID. The call will either succeed or fail
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 505 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyInstanceGroupsResponse *>(send(request));
 }
putAutoScalingPolicy
PutAutoScalingPolicyResponse * QtAws::EMR::EmrClient::putAutoScalingPolicy (const PutAutoScalingPolicyRequest & request) slot
Creates or updates an automatic scaling policy for a core instance group or task instance group in an Amazon EMR cluster. The automatic scaling policy defines how an instance group dynamically adds and terminates EC2 instances in response to the value of a CloudWatch
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 521 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutAutoScalingPolicyResponse *>(send(request));
 }
removeAutoScalingPolicy
RemoveAutoScalingPolicyResponse * QtAws::EMR::EmrClient::removeAutoScalingPolicy (const RemoveAutoScalingPolicyRequest & request) slot
Removes an automatic scaling policy from a specified instance group within an EMR
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 535 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveAutoScalingPolicyResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::EMR::EmrClient::removeTags (const RemoveTagsRequest & request) slot
Removes tags from an Amazon EMR resource. Tags make it easier to associate clusters in various ways, such as grouping clusters to track your Amazon EMR resource allocation costs. For more information, see Tag Clusters.
</p
The following example removes the stack tag with value Prod from a
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 555 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
runJobFlow
RunJobFlowResponse * QtAws::EMR::EmrClient::runJobFlow (const RunJobFlowRequest & request) slot
RunJobFlow creates and starts running a new cluster (job flow). The cluster runs the steps specified. After the steps complete, the cluster stops and the HDFS partition is lost. To prevent loss of data, configure the last step of the job flow to store results in Amazon S3. If the JobFlowInstancesConfig KeepJobFlowAliveWhenNoSteps parameter is set to TRUE, the cluster transitions to the WAITING state rather than shutting down after the steps have completed.
</p
For additional protection, you can set the JobFlowInstancesConfig TerminationProtected parameter to TRUE to lock the cluster and prevent it from being terminated by API call, user intervention, or in the event of a job flow
error>
A maximum of 256 steps are allowed in each job
flow>
If your cluster is long-running (such as a Hive data warehouse) or complex, you may require more than 256 steps to process your data. You can bypass the 256-step limitation in various ways, including using the SSH shell to connect to the master node and submitting queries directly to the software running on the master node, such as Hive and Hadoop. For more information on how to do this, see Add More than 256 Steps to a Cluster in the Amazon EMR Management
Guide>
For long running clusters, we recommend that you periodically store your
results> <note>
The instance fleets configuration is available only in Amazon EMR versions 4.8.0 and later, excluding 5.0.x versions. The RunJobFlow request can contain InstanceFleets parameters or InstanceGroups parameters, but not
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 601 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RunJobFlowResponse *>(send(request));
 }
setTerminationProtection
SetTerminationProtectionResponse * QtAws::EMR::EmrClient::setTerminationProtection (const SetTerminationProtectionRequest & request) slot
SetTerminationProtection locks a cluster (job flow) so the EC2 instances in the cluster cannot be terminated by user intervention, an API call, or in the event of a job-flow error. The cluster still terminates upon successful completion of the job flow. Calling SetTerminationProtection on a cluster is similar to calling the Amazon EC2 DisableAPITermination API on all EC2 instances in a
cluster>
SetTerminationProtection is used to prevent accidental termination of a cluster and to ensure that in the event of an error, the instances persist so that you can recover any data stored in their ephemeral instance
storage>
To terminate a cluster that has been locked by setting SetTerminationProtection to true, you must first unlock the job flow by a subsequent call to SetTerminationProtection in which you set the value to false.
</p
For more information, seeManaging Cluster Termination in the Amazon EMR Management Guide.
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 635 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetTerminationProtectionResponse *>(send(request));
 }
setVisibleToAllUsers
SetVisibleToAllUsersResponse * QtAws::EMR::EmrClient::setVisibleToAllUsers (const SetVisibleToAllUsersRequest & request) slot
Sets whether all AWS Identity and Access Management (IAM) users under your account can access the specified clusters (job flows). This action works on running clusters. You can also set the visibility of a cluster when you launch it using the VisibleToAllUsers parameter of RunJobFlow. The SetVisibleToAllUsers action can be called only by an IAM user who created the cluster or the AWS account that owns the
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 652 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetVisibleToAllUsersResponse *>(send(request));
 }
terminateJobFlows
TerminateJobFlowsResponse * QtAws::EMR::EmrClient::terminateJobFlows (const TerminateJobFlowsRequest & request) slot
TerminateJobFlows shuts a list of clusters (job flows) down. When a job flow is shut down, any step not yet completed is canceled and the EC2 instances on which the cluster is running are stopped. Any log files not already saved are uploaded to Amazon S3 if a LogUri was specified when the cluster was
created>
The maximum number of clusters allowed is 10. The call to TerminateJobFlows is asynchronous. Depending on the configuration of the cluster, it may take up to 1-5 minutes for the cluster to completely terminate and release allocated resources, such as Amazon EC2
Parameters
request Request to send to Amazon Elastic MapReduce.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 674 of file emrclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TerminateJobFlowsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
elasticmapreduce/emrclient.h
elasticmapreduce/emrclient.cpp