AWS SDK for Qt: QtAws::SES::SesClient Class Reference
QtAws::SES::SesClient Class Reference
Client for Amazon Simple Email Service (SES)
Public Slots
CloneReceiptRuleSetResponse * cloneReceiptRuleSet (const CloneReceiptRuleSetRequest &request)
CreateConfigurationSetResponse * createConfigurationSet (const CreateConfigurationSetRequest &request)
CreateConfigurationSetEventDestinationResponse * createConfigurationSetEventDestination (const CreateConfigurationSetEventDestinationRequest &request)
CreateConfigurationSetTrackingOptionsResponse * createConfigurationSetTrackingOptions (const CreateConfigurationSetTrackingOptionsRequest &request)
CreateCustomVerificationEmailTemplateResponse * createCustomVerificationEmailTemplate (const CreateCustomVerificationEmailTemplateRequest &request)
CreateReceiptFilterResponse * createReceiptFilter (const CreateReceiptFilterRequest &request)
CreateReceiptRuleResponse * createReceiptRule (const CreateReceiptRuleRequest &request)
CreateReceiptRuleSetResponse * createReceiptRuleSet (const CreateReceiptRuleSetRequest &request)
CreateTemplateResponse * createTemplate (const CreateTemplateRequest &request)
DeleteConfigurationSetResponse * deleteConfigurationSet (const DeleteConfigurationSetRequest &request)
DeleteConfigurationSetEventDestinationResponse * deleteConfigurationSetEventDestination (const DeleteConfigurationSetEventDestinationRequest &request)
DeleteConfigurationSetTrackingOptionsResponse * deleteConfigurationSetTrackingOptions (const DeleteConfigurationSetTrackingOptionsRequest &request)
DeleteCustomVerificationEmailTemplateResponse * deleteCustomVerificationEmailTemplate (const DeleteCustomVerificationEmailTemplateRequest &request)
DeleteIdentityResponse * deleteIdentity (const DeleteIdentityRequest &request)
DeleteIdentityPolicyResponse * deleteIdentityPolicy (const DeleteIdentityPolicyRequest &request)
DeleteReceiptFilterResponse * deleteReceiptFilter (const DeleteReceiptFilterRequest &request)
DeleteReceiptRuleResponse * deleteReceiptRule (const DeleteReceiptRuleRequest &request)
DeleteReceiptRuleSetResponse * deleteReceiptRuleSet (const DeleteReceiptRuleSetRequest &request)
DeleteTemplateResponse * deleteTemplate (const DeleteTemplateRequest &request)
DeleteVerifiedEmailAddressResponse * deleteVerifiedEmailAddress (const DeleteVerifiedEmailAddressRequest &request)
DescribeActiveReceiptRuleSetResponse * describeActiveReceiptRuleSet (const DescribeActiveReceiptRuleSetRequest &request)
DescribeConfigurationSetResponse * describeConfigurationSet (const DescribeConfigurationSetRequest &request)
DescribeReceiptRuleResponse * describeReceiptRule (const DescribeReceiptRuleRequest &request)
DescribeReceiptRuleSetResponse * describeReceiptRuleSet (const DescribeReceiptRuleSetRequest &request)
GetAccountSendingEnabledResponse * getAccountSendingEnabled ()
GetCustomVerificationEmailTemplateResponse * getCustomVerificationEmailTemplate (const GetCustomVerificationEmailTemplateRequest &request)
GetIdentityDkimAttributesResponse * getIdentityDkimAttributes (const GetIdentityDkimAttributesRequest &request)
GetIdentityMailFromDomainAttributesResponse * getIdentityMailFromDomainAttributes (const GetIdentityMailFromDomainAttributesRequest &request)
GetIdentityNotificationAttributesResponse * getIdentityNotificationAttributes (const GetIdentityNotificationAttributesRequest &request)
GetIdentityPoliciesResponse * getIdentityPolicies (const GetIdentityPoliciesRequest &request)
GetIdentityVerificationAttributesResponse * getIdentityVerificationAttributes (const GetIdentityVerificationAttributesRequest &request)
GetSendQuotaResponse * getSendQuota ()
GetSendStatisticsResponse * getSendStatistics ()
GetTemplateResponse * getTemplate (const GetTemplateRequest &request)
ListConfigurationSetsResponse * listConfigurationSets (const ListConfigurationSetsRequest &request)
ListCustomVerificationEmailTemplatesResponse * listCustomVerificationEmailTemplates (const ListCustomVerificationEmailTemplatesRequest &request)
ListIdentitiesResponse * listIdentities (const ListIdentitiesRequest &request)
ListIdentityPoliciesResponse * listIdentityPolicies (const ListIdentityPoliciesRequest &request)
ListReceiptFiltersResponse * listReceiptFilters (const ListReceiptFiltersRequest &request)
ListReceiptRuleSetsResponse * listReceiptRuleSets (const ListReceiptRuleSetsRequest &request)
ListTemplatesResponse * listTemplates (const ListTemplatesRequest &request)
ListVerifiedEmailAddressesResponse * listVerifiedEmailAddresses ()
PutIdentityPolicyResponse * putIdentityPolicy (const PutIdentityPolicyRequest &request)
ReorderReceiptRuleSetResponse * reorderReceiptRuleSet (const ReorderReceiptRuleSetRequest &request)
SendBounceResponse * sendBounce (const SendBounceRequest &request)
SendBulkTemplatedEmailResponse * sendBulkTemplatedEmail (const SendBulkTemplatedEmailRequest &request)
SendCustomVerificationEmailResponse * sendCustomVerificationEmail (const SendCustomVerificationEmailRequest &request)
SendEmailResponse * sendEmail (const SendEmailRequest &request)
SendRawEmailResponse * sendRawEmail (const SendRawEmailRequest &request)
SendTemplatedEmailResponse * sendTemplatedEmail (const SendTemplatedEmailRequest &request)
SetActiveReceiptRuleSetResponse * setActiveReceiptRuleSet (const SetActiveReceiptRuleSetRequest &request)
SetIdentityDkimEnabledResponse * setIdentityDkimEnabled (const SetIdentityDkimEnabledRequest &request)
SetIdentityFeedbackForwardingEnabledResponse * setIdentityFeedbackForwardingEnabled (const SetIdentityFeedbackForwardingEnabledRequest &request)
SetIdentityHeadersInNotificationsEnabledResponse * setIdentityHeadersInNotificationsEnabled (const SetIdentityHeadersInNotificationsEnabledRequest &request)
SetIdentityMailFromDomainResponse * setIdentityMailFromDomain (const SetIdentityMailFromDomainRequest &request)
SetIdentityNotificationTopicResponse * setIdentityNotificationTopic (const SetIdentityNotificationTopicRequest &request)
SetReceiptRulePositionResponse * setReceiptRulePosition (const SetReceiptRulePositionRequest &request)
TestRenderTemplateResponse * testRenderTemplate (const TestRenderTemplateRequest &request)
UpdateAccountSendingEnabledResponse * updateAccountSendingEnabled (const UpdateAccountSendingEnabledRequest &request)
UpdateConfigurationSetEventDestinationResponse * updateConfigurationSetEventDestination (const UpdateConfigurationSetEventDestinationRequest &request)
UpdateConfigurationSetReputationMetricsEnabledResponse * updateConfigurationSetReputationMetricsEnabled (const UpdateConfigurationSetReputationMetricsEnabledRequest &request)
UpdateConfigurationSetSendingEnabledResponse * updateConfigurationSetSendingEnabled (const UpdateConfigurationSetSendingEnabledRequest &request)
UpdateConfigurationSetTrackingOptionsResponse * updateConfigurationSetTrackingOptions (const UpdateConfigurationSetTrackingOptionsRequest &request)
UpdateCustomVerificationEmailTemplateResponse * updateCustomVerificationEmailTemplate (const UpdateCustomVerificationEmailTemplateRequest &request)
UpdateReceiptRuleResponse * updateReceiptRule (const UpdateReceiptRuleRequest &request)
UpdateTemplateResponse * updateTemplate (const UpdateTemplateRequest &request)
VerifyDomainDkimResponse * verifyDomainDkim (const VerifyDomainDkimRequest &request)
VerifyDomainIdentityResponse * verifyDomainIdentity (const VerifyDomainIdentityRequest &request)
VerifyEmailAddressResponse * verifyEmailAddress (const VerifyEmailAddressRequest &request)
VerifyEmailIdentityResponse * verifyEmailIdentity (const VerifyEmailIdentityRequest &request)
Public Member Functions
SesClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SesClient object.
SesClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SesClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Email Service (SES)
<fullname>Amazon Simple Email Service</fullname>
This is the API Reference for Amazon Simple Email Service (Amazon SES). This documentation is intended to be used in conjunction with the Amazon SES Developer Guide.
</p <note>
For a list of Amazon SES endpoints to use in service requests, see Regions and Amazon SES in the Amazon SES Developer Guide.
Definition at line 168 of file sesclient.h.
Constructor & Destructor Documentation
SesClient() [1/2]
QtAws::SES::SesClient::SesClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SesClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 193 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new SesClientPrivate(this), parent)
 {
     Q_D(SesClient);
     d->apiVersion = QStringLiteral("2010-12-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("email");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Simple Email Service");
     d->serviceName = QStringLiteral("ses");
 }
SesClient() [2/2]
QtAws::SES::SesClient::SesClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SesClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 226 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new SesClientPrivate(this), parent)
 {
     Q_D(SesClient);
     d->apiVersion = QStringLiteral("2010-12-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("email");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Simple Email Service");
     d->serviceName = QStringLiteral("ses");
 }
Member Function Documentation
cloneReceiptRuleSet
CloneReceiptRuleSetResponse * QtAws::SES::SesClient::cloneReceiptRuleSet (const CloneReceiptRuleSetRequest & request) slot
Creates a receipt rule set by cloning an existing one. All receipt rules and configurations are copied to the new receipt rule set and are completely independent of the source rule
set>
For information about setting up rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 262 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CloneReceiptRuleSetResponse *>(send(request));
 }
createConfigurationSet
CreateConfigurationSetResponse * QtAws::SES::SesClient::createConfigurationSet (const CreateConfigurationSetRequest & request) slot
Creates a configuration
set>
Configuration sets enable you to publish email sending events. For information about using configuration sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 285 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConfigurationSetResponse *>(send(request));
 }
createConfigurationSetEventDestination
CreateConfigurationSetEventDestinationResponse * QtAws::SES::SesClient::createConfigurationSetEventDestination (const CreateConfigurationSetEventDestinationRequest & request) slot
Creates a configuration set event
destination> <note>
When you create or update an event destination, you must provide one, and only one, destination. The destination can be Amazon CloudWatch, Amazon Kinesis Firehose, or Amazon Simple Notification Service (Amazon
SNS)> </note>
An event destination is the AWS service to which Amazon SES publishes the email sending events associated with a configuration set. For information about using configuration sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 314 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConfigurationSetEventDestinationResponse *>(send(request));
 }
createConfigurationSetTrackingOptions
CreateConfigurationSetTrackingOptionsResponse * QtAws::SES::SesClient::createConfigurationSetTrackingOptions (const CreateConfigurationSetTrackingOptionsRequest & request) slot
Creates an association between a configuration set and a custom domain for open and click event tracking.
</p
By default, images and links used for tracking open and click events are hosted on domains operated by Amazon SES. You can configure a subdomain of your own to handle these events. For information about using configuration sets, see Configuring Custom Domains to Handle Open and Click Tracking in the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 336 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConfigurationSetTrackingOptionsResponse *>(send(request));
 }
createCustomVerificationEmailTemplate
CreateCustomVerificationEmailTemplateResponse * QtAws::SES::SesClient::createCustomVerificationEmailTemplate (const CreateCustomVerificationEmailTemplateRequest & request) slot
Creates a new custom verification email
template>
For more information about custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 360 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateCustomVerificationEmailTemplateResponse *>(send(request));
 }
createReceiptFilter
CreateReceiptFilterResponse * QtAws::SES::SesClient::createReceiptFilter (const CreateReceiptFilterRequest & request) slot
Creates a new IP address
filter>
For information about setting up IP address filters, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 383 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReceiptFilterResponse *>(send(request));
 }
createReceiptRule
CreateReceiptRuleResponse * QtAws::SES::SesClient::createReceiptRule (const CreateReceiptRuleRequest & request) slot
Creates a receipt
rule>
For information about setting up receipt rules, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReceiptRuleResponse *>(send(request));
 }
createReceiptRuleSet
CreateReceiptRuleSetResponse * QtAws::SES::SesClient::createReceiptRuleSet (const CreateReceiptRuleSetRequest & request) slot
Creates an empty receipt rule
set>
For information about setting up receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 429 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateReceiptRuleSetResponse *>(send(request));
 }
createTemplate
CreateTemplateResponse * QtAws::SES::SesClient::createTemplate (const CreateTemplateRequest & request) slot
Creates an email template. Email templates enable you to send personalized email to one or more destinations in a single API operation. For more information, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 449 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTemplateResponse *>(send(request));
 }
deleteConfigurationSet
DeleteConfigurationSetResponse * QtAws::SES::SesClient::deleteConfigurationSet (const DeleteConfigurationSetRequest & request) slot
Deletes a configuration set. Configuration sets enable you to publish email sending events. For information about using configuration sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 469 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConfigurationSetResponse *>(send(request));
 }
deleteConfigurationSetEventDestination
DeleteConfigurationSetEventDestinationResponse * QtAws::SES::SesClient::deleteConfigurationSetEventDestination (const DeleteConfigurationSetEventDestinationRequest & request) slot
Deletes a configuration set event destination. Configuration set event destinations are associated with configuration sets, which enable you to publish email sending events. For information about using configuration sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 489 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConfigurationSetEventDestinationResponse *>(send(request));
 }
deleteConfigurationSetTrackingOptions
DeleteConfigurationSetTrackingOptionsResponse * QtAws::SES::SesClient::deleteConfigurationSetTrackingOptions (const DeleteConfigurationSetTrackingOptionsRequest & request) slot
Deletes an association between a configuration set and a custom domain for open and click event
tracking>
By default, images and links used for tracking open and click events are hosted on domains operated by Amazon SES. You can configure a subdomain of your own to handle these events. For information about using configuration sets, see Configuring Custom Domains to Handle Open and Click Tracking in the Amazon SES Developer Guide> <note>
Deleting this kind of association will result in emails sent using the specified configuration set to capture open and click events using the standard, Amazon SES-operated
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 516 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteConfigurationSetTrackingOptionsResponse *>(send(request));
 }
deleteCustomVerificationEmailTemplate
DeleteCustomVerificationEmailTemplateResponse * QtAws::SES::SesClient::deleteCustomVerificationEmailTemplate (const DeleteCustomVerificationEmailTemplateRequest & request) slot
Deletes an existing custom verification email template.
</p
For more information about custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 540 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteCustomVerificationEmailTemplateResponse *>(send(request));
 }
deleteIdentity
DeleteIdentityResponse * QtAws::SES::SesClient::deleteIdentity (const DeleteIdentityRequest & request) slot
Deletes the specified identity (an email address or a domain) from the list of verified
identities>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 558 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIdentityResponse *>(send(request));
 }
deleteIdentityPolicy
DeleteIdentityPolicyResponse * QtAws::SES::SesClient::deleteIdentityPolicy (const DeleteIdentityPolicyRequest & request) slot
Deletes the specified sending authorization policy for the given identity (an email address or a domain). This API returns successfully even if a policy with the specified name does not
exist> <note>
This API is for the identity owner only. If you have not verified the identity, this API will return an
error> </note>
Sending authorization is a feature that enables an identity owner to authorize other senders to use its identities. For information about using sending authorization, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 587 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIdentityPolicyResponse *>(send(request));
 }
deleteReceiptFilter
DeleteReceiptFilterResponse * QtAws::SES::SesClient::deleteReceiptFilter (const DeleteReceiptFilterRequest & request) slot
Deletes the specified IP address
filter>
For information about managing IP address filters, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 611 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReceiptFilterResponse *>(send(request));
 }
deleteReceiptRule
DeleteReceiptRuleResponse * QtAws::SES::SesClient::deleteReceiptRule (const DeleteReceiptRuleRequest & request) slot
Deletes the specified receipt
rule>
For information about managing receipt rules, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 635 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReceiptRuleResponse *>(send(request));
 }
deleteReceiptRuleSet
DeleteReceiptRuleSetResponse * QtAws::SES::SesClient::deleteReceiptRuleSet (const DeleteReceiptRuleSetRequest & request) slot
Deletes the specified receipt rule set and all of the receipt rules it
contains> <note>
The currently active rule set cannot be
deleted> </note>
For information about managing receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 663 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReceiptRuleSetResponse *>(send(request));
 }
deleteTemplate
DeleteTemplateResponse * QtAws::SES::SesClient::deleteTemplate (const DeleteTemplateRequest & request) slot
Deletes an email
template>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 681 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTemplateResponse *>(send(request));
 }
deleteVerifiedEmailAddress
DeleteVerifiedEmailAddressResponse * QtAws::SES::SesClient::deleteVerifiedEmailAddress (const DeleteVerifiedEmailAddressRequest & request) slot
Deprecated. Use the DeleteIdentity operation to delete email addresses and
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 695 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteVerifiedEmailAddressResponse *>(send(request));
 }
describeActiveReceiptRuleSet
DescribeActiveReceiptRuleSetResponse * QtAws::SES::SesClient::describeActiveReceiptRuleSet (const DescribeActiveReceiptRuleSetRequest & request) slot
Returns the metadata and receipt rules for the receipt rule set that is currently
active>
For information about setting up receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 718 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeActiveReceiptRuleSetResponse *>(send(request));
 }
describeConfigurationSet
DescribeConfigurationSetResponse * QtAws::SES::SesClient::describeConfigurationSet (const DescribeConfigurationSetRequest & request) slot
Returns the details of the specified configuration set. For information about using configuration sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 737 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigurationSetResponse *>(send(request));
 }
describeReceiptRule
DescribeReceiptRuleResponse * QtAws::SES::SesClient::describeReceiptRule (const DescribeReceiptRuleRequest & request) slot
Returns the details of the specified receipt
rule>
For information about setting up receipt rules, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 760 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReceiptRuleResponse *>(send(request));
 }
describeReceiptRuleSet
DescribeReceiptRuleSetResponse * QtAws::SES::SesClient::describeReceiptRuleSet (const DescribeReceiptRuleSetRequest & request) slot
Returns the details of the specified receipt rule
set>
For information about managing receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 784 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReceiptRuleSetResponse *>(send(request));
 }
getAccountSendingEnabled
GetAccountSendingEnabledResponse * QtAws::SES::SesClient::getAccountSendingEnabled () slot
Returns the email sending status of the Amazon SES
account>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 802 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAccountSendingEnabledResponse *>(send(request));
 }
getCustomVerificationEmailTemplate
GetCustomVerificationEmailTemplateResponse * QtAws::SES::SesClient::getCustomVerificationEmailTemplate (const GetCustomVerificationEmailTemplateRequest & request) slot
Returns the custom email verification template for the template name you
specify>
For more information about custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 826 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetCustomVerificationEmailTemplateResponse *>(send(request));
 }
getIdentityDkimAttributes
GetIdentityDkimAttributesResponse * QtAws::SES::SesClient::getIdentityDkimAttributes (const GetIdentityDkimAttributesRequest & request) slot
Returns the current status of Easy DKIM signing for an entity. For domain name identities, this operation also returns the DKIM tokens that are required for Easy DKIM signing, and whether Amazon SES has successfully verified that these tokens have been
published>
This operation takes a list of identities as input and returns the following information for
each>
Whether Easy DKIM signing is enabled or
disabled>
A set of DKIM tokens that represent the identity. If the identity is an email address, the tokens represent the domain of that
address>
Whether Amazon SES has successfully verified the DKIM tokens published in the domain's DNS. This information is only returned for domain name identities, not for email
addresses>
This operation is throttled at one request per second and can only get DKIM attributes for up to 100 identities at a
time>
For more information about creating DNS records using DKIM tokens, go to the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 869 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityDkimAttributesResponse *>(send(request));
 }
getIdentityMailFromDomainAttributes
GetIdentityMailFromDomainAttributesResponse * QtAws::SES::SesClient::getIdentityMailFromDomainAttributes (const GetIdentityMailFromDomainAttributesRequest & request) slot
Returns the custom MAIL FROM attributes for a list of identities (email addresses :
domains)>
This operation is throttled at one request per second and can only get custom MAIL FROM attributes for up to 100 identities at a
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 888 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityMailFromDomainAttributesResponse *>(send(request));
 }
getIdentityNotificationAttributes
GetIdentityNotificationAttributesResponse * QtAws::SES::SesClient::getIdentityNotificationAttributes (const GetIdentityNotificationAttributesRequest & request) slot
Given a list of verified identities (email addresses and/or domains), returns a structure describing identity notification
attributes>
This operation is throttled at one request per second and can only get notification attributes for up to 100 identities at a
time>
For more information about using notifications with Amazon SES, see the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 913 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityNotificationAttributesResponse *>(send(request));
 }
getIdentityPolicies
GetIdentityPoliciesResponse * QtAws::SES::SesClient::getIdentityPolicies (const GetIdentityPoliciesRequest & request) slot
Returns the requested sending authorization policies for the given identity (an email address or a domain). The policies are returned as a map of policy names to policy contents. You can retrieve a maximum of 20 policies at a
time> <note>
This API is for the identity owner only. If you have not verified the identity, this API will return an
error> </note>
Sending authorization is a feature that enables an identity owner to authorize other senders to use its identities. For information about using sending authorization, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 942 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityPoliciesResponse *>(send(request));
 }
getIdentityVerificationAttributes
GetIdentityVerificationAttributesResponse * QtAws::SES::SesClient::getIdentityVerificationAttributes (const GetIdentityVerificationAttributesRequest & request) slot
Given a list of identities (email addresses and/or domains), returns the verification status and (for domain identities) the verification token for each
identity>
The verification status of an email address is "Pending" until the email address owner clicks the link within the verification email that Amazon SES sent to that address. If the email address owner clicks the link within 24 hours, the verification status of the email address changes to "Success". If the link is not clicked within 24 hours, the verification status changes to "Failed." In that case, if you still want to verify the email address, you must restart the verification process from the
beginning>
For domain identities, the domain's verification status is "Pending" as Amazon SES searches for the required TXT record in the DNS settings of the domain. When Amazon SES detects the record, the domain's verification status changes to "Success". If Amazon SES is unable to detect the record within 72 hours, the domain's verification status changes to "Failed." In that case, if you still want to verify the domain, you must restart the verification process from the
beginning>
This operation is throttled at one request per second and can only get verification attributes for up to 100 identities at a
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 977 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIdentityVerificationAttributesResponse *>(send(request));
 }
getSendQuota
GetSendQuotaResponse * QtAws::SES::SesClient::getSendQuota () slot
Provides the sending limits for the Amazon SES account.
</p
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 995 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSendQuotaResponse *>(send(request));
 }
getSendStatistics
GetSendStatisticsResponse * QtAws::SES::SesClient::getSendStatistics () slot
Provides sending statistics for the Amazon SES account. The result is a list of data points, representing the last two weeks of sending activity. Each data point in the list contains statistics for a 15-minute period of
time>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1014 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSendStatisticsResponse *>(send(request));
 }
getTemplate
GetTemplateResponse * QtAws::SES::SesClient::getTemplate (const GetTemplateRequest & request) slot
Displays the template object (which includes the Subject line, HTML part and text part) for the template you
specify>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1032 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTemplateResponse *>(send(request));
 }
listConfigurationSets
ListConfigurationSetsResponse * QtAws::SES::SesClient::listConfigurationSets (const ListConfigurationSetsRequest & request) slot
Provides a list of the configuration sets associated with your Amazon SES account. For information about using configuration sets, see Monitoring Your Amazon SES Sending Activity in the Amazon SES Developer Guide.
</p
You can execute this operation no more than once per second. This operation will return up to 1,000 configuration sets each time it is run. If your Amazon SES account has more than 1,000 configuration sets, this operation will also return a NextToken element. You can then execute the ListConfigurationSets operation again, passing the NextToken parameter and the value of the NextToken element to retrieve additional
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1056 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListConfigurationSetsResponse *>(send(request));
 }
listCustomVerificationEmailTemplates
ListCustomVerificationEmailTemplatesResponse * QtAws::SES::SesClient::listCustomVerificationEmailTemplates (const ListCustomVerificationEmailTemplatesRequest & request) slot
Lists the existing custom verification email templates for your
account>
For more information about custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1080 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListCustomVerificationEmailTemplatesResponse *>(send(request));
 }
listIdentities
ListIdentitiesResponse * QtAws::SES::SesClient::listIdentities (const ListIdentitiesRequest & request) slot
Returns a list containing all of the identities (email addresses and domains) for your AWS account, regardless of verification
status>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1099 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListIdentitiesResponse *>(send(request));
 }
listIdentityPolicies
ListIdentityPoliciesResponse * QtAws::SES::SesClient::listIdentityPolicies (const ListIdentityPoliciesRequest & request) slot
Returns a list of sending authorization policies that are attached to the given identity (an email address or a domain). This API returns only a list. If you want the actual policy content, you can use
GetIdentityPolicies> <note>
This API is for the identity owner only. If you have not verified the identity, this API will return an
error> </note>
Sending authorization is a feature that enables an identity owner to authorize other senders to use its identities. For information about using sending authorization, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1128 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListIdentityPoliciesResponse *>(send(request));
 }
listReceiptFilters
ListReceiptFiltersResponse * QtAws::SES::SesClient::listReceiptFilters (const ListReceiptFiltersRequest & request) slot
Lists the IP address filters associated with your AWS
account>
For information about managing IP address filters, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1152 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListReceiptFiltersResponse *>(send(request));
 }
listReceiptRuleSets
ListReceiptRuleSetsResponse * QtAws::SES::SesClient::listReceiptRuleSets (const ListReceiptRuleSetsRequest & request) slot
Lists the receipt rule sets that exist under your AWS account. If there are additional receipt rule sets to be retrieved, you will receive a NextToken that you can provide to the next call to ListReceiptRuleSets to retrieve the additional
entries>
For information about managing receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1178 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListReceiptRuleSetsResponse *>(send(request));
 }
listTemplates
ListTemplatesResponse * QtAws::SES::SesClient::listTemplates (const ListTemplatesRequest & request) slot
Lists the email templates present in your Amazon SES
account>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1196 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTemplatesResponse *>(send(request));
 }
listVerifiedEmailAddresses
ListVerifiedEmailAddressesResponse * QtAws::SES::SesClient::listVerifiedEmailAddresses () slot
Deprecated. Use the ListIdentities operation to list the email addresses and domains associated with your
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1210 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListVerifiedEmailAddressesResponse *>(send(request));
 }
putIdentityPolicy
PutIdentityPolicyResponse * QtAws::SES::SesClient::putIdentityPolicy (const PutIdentityPolicyRequest & request) slot
Adds or updates a sending authorization policy for the specified identity (an email address or a
domain)> <note>
This API is for the identity owner only. If you have not verified the identity, this API will return an
error> </note>
Sending authorization is a feature that enables an identity owner to authorize other senders to use its identities. For information about using sending authorization, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1238 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutIdentityPolicyResponse *>(send(request));
 }
reorderReceiptRuleSet
ReorderReceiptRuleSetResponse * QtAws::SES::SesClient::reorderReceiptRuleSet (const ReorderReceiptRuleSetRequest & request) slot
Reorders the receipt rules within a receipt rule
set> <note>
All of the rules in the rule set must be represented in this request. That is, this API will return an error if the reorder request doesn't explicitly position all of the
rules> </note>
For information about managing receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1267 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReorderReceiptRuleSetResponse *>(send(request));
 }
sendBounce
SendBounceResponse * QtAws::SES::SesClient::sendBounce (const SendBounceRequest & request) slot
Generates and sends a bounce message to the sender of an email you received through Amazon SES. You can only use this API on an email up to 24 hours after you receive
it> <note>
You cannot use this API to send generic bounces for mail that was not received by Amazon
SES> </note>
For information about receiving email through Amazon SES, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1295 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendBounceResponse *>(send(request));
 }
sendBulkTemplatedEmail
SendBulkTemplatedEmailResponse * QtAws::SES::SesClient::sendBulkTemplatedEmail (const SendBulkTemplatedEmailRequest & request) slot
Composes an email message to multiple destinations. The message body is created using an email
template>
In order to send email using the SendBulkTemplatedEmail operation, your call to the API must meet the following
requirements>
The call must refer to an existing email template. You can create email templates using the CreateTemplate
operation>
The message must be sent from a verified email address or
domain>
If your account is still in the Amazon SES sandbox, you may only send to verified addresses or domains, or to email addresses associated with the Amazon SES Mailbox Simulator. For more information, see Verifying Email Addresses and Domains in the Amazon SES Developer Guide.
</p
The total size of the message, including attachments, must be less than 10
MB>
Each Destination parameter must include at least one recipient email address. The recipient address can be a To: address, a CC: address, or a BCC: address. If a recipient email address is invalid (that is, it is not in the format UserName@[SubDomain.]Domain.TopLevelDomain), the entire message will be rejected, even if the message contains other recipients that are
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1340 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendBulkTemplatedEmailResponse *>(send(request));
 }
sendCustomVerificationEmail
SendCustomVerificationEmailResponse * QtAws::SES::SesClient::sendCustomVerificationEmail (const SendCustomVerificationEmailRequest & request) slot
Adds an email address to the list of identities for your Amazon SES account and attempts to verify it. As a result of executing this operation, a customized verification email is sent to the specified
address>
To use this operation, you must first create a custom verification email template. For more information about creating and using custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1366 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendCustomVerificationEmailResponse *>(send(request));
 }
sendEmail
SendEmailResponse * QtAws::SES::SesClient::sendEmail (const SendEmailRequest & request) slot
Composes an email message and immediately queues it for sending. In order to send email using the SendEmail operation, your message must meet the following
requirements>
The message must be sent from a verified email address or domain. If you attempt to send email using a non-verified address or domain, the operation will result in an "Email address not verified" error.
</p
If your account is still in the Amazon SES sandbox, you may only send to verified addresses or domains, or to email addresses associated with the Amazon SES Mailbox Simulator. For more information, see Verifying Email Addresses and Domains in the Amazon SES Developer Guide.
</p
The total size of the message, including attachments, must be smaller than 10
MB>
The message must include at least one recipient email address. The recipient address can be a To: address, a CC: address, or a BCC: address. If a recipient email address is invalid (that is, it is not in the format UserName@[SubDomain.]Domain.TopLevelDomain), the entire message will be rejected, even if the message contains other recipients that are
valid>
The message may not include more than 50 recipients, across the To:, CC: and BCC: fields. If you need to send an email message to a larger audience, you can divide your recipient list into groups of 50 or fewer, and then call the SendEmail operation several times to send the message to each
group>
For every message that you send, the total number of recipients (including each recipient in the To:, CC: and BCC: fields) is counted against the maximum number of emails you can send in a 24-hour period (your sending quota). For more information about sending quotas in Amazon SES, see Managing Your Amazon SES Sending Limits in the Amazon SES Developer Guide.
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1418 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendEmailResponse *>(send(request));
 }
sendRawEmail
SendRawEmailResponse * QtAws::SES::SesClient::sendRawEmail (const SendRawEmailRequest & request) slot
Composes an email message and immediately queues it for sending. When calling this operation, you may specify the message headers as well as the content. The SendRawEmail operation is particularly useful for sending multipart MIME emails (such as those that contain both a plain-text and an HTML version).
</p
In order to send email using the SendRawEmail operation, your message must meet the following
requirements>
The message must be sent from a verified email address or domain. If you attempt to send email using a non-verified address or domain, the operation will result in an "Email address not verified" error.
</p
If your account is still in the Amazon SES sandbox, you may only send to verified addresses or domains, or to email addresses associated with the Amazon SES Mailbox Simulator. For more information, see Verifying Email Addresses and Domains in the Amazon SES Developer Guide.
</p
The total size of the message, including attachments, must be smaller than 10
MB>
The message must include at least one recipient email address. The recipient address can be a To: address, a CC: address, or a BCC: address. If a recipient email address is invalid (that is, it is not in the format UserName@[SubDomain.]Domain.TopLevelDomain), the entire message will be rejected, even if the message contains other recipients that are
valid>
The message may not include more than 50 recipients, across the To:, CC: and BCC: fields. If you need to send an email message to a larger audience, you can divide your recipient list into groups of 50 or fewer, and then call the SendRawEmail operation several times to send the message to each
group>
For every message that you send, the total number of recipients (including each recipient in the To:, CC: and BCC: fields) is counted against the maximum number of emails you can send in a 24-hour period (your sending quota). For more information about sending quotas in Amazon SES, see Managing Your Amazon SES Sending Limits in the Amazon SES Developer Guide.
</p
Additionally, keep the following considerations in mind when using the SendRawEmail
operation>
Although you can customize the message headers when using the SendRawEmail operation, Amazon SES will automatically apply its own Message-ID and Date headers; if you passed these headers when creating the message, they will be overwritten by the values that Amazon SES
provides>
If you are using sending authorization to send on behalf of another user, SendRawEmail enables you to specify the cross-account identity for the email's Source, From, and Return-Path parameters in one of two ways: you can pass optional parameters SourceArn, FromArn, and/or ReturnPathArn to the API, or you can include the following X-headers in the header of your raw
email>
X-SES-SOURCE-ARN
</p
X-SES-FROM-ARN
</p
X-SES-RETURN-PATH-ARN
</p
Do not include these X-headers in the DKIM signature; Amazon SES will remove them before sending the
email>
For most common sending authorization scenarios, we recommend that you specify the SourceIdentityArn parameter and not the FromIdentityArn or ReturnPathIdentityArn parameters. If you only specify the SourceIdentityArn parameter, Amazon SES will set the From and Return Path addresses to the identity specified in SourceIdentityArn. For more information about sending authorization, see the Using Sending Authorization with Amazon SES in the Amazon SES Developer Guide.
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1517 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendRawEmailResponse *>(send(request));
 }
sendTemplatedEmail
SendTemplatedEmailResponse * QtAws::SES::SesClient::sendTemplatedEmail (const SendTemplatedEmailRequest & request) slot
Composes an email message using an email template and immediately queues it for
sending>
In order to send email using the SendTemplatedEmail operation, your call to the API must meet the following
requirements>
The call must refer to an existing email template. You can create email templates using the CreateTemplate
operation>
The message must be sent from a verified email address or
domain>
If your account is still in the Amazon SES sandbox, you may only send to verified addresses or domains, or to email addresses associated with the Amazon SES Mailbox Simulator. For more information, see Verifying Email Addresses and Domains in the Amazon SES Developer Guide.
</p
The total size of the message, including attachments, must be less than 10
MB>
Calls to the SendTemplatedEmail operation may only include one Destination parameter. A destination is a set of recipients who will receive the same version of the email. The Destination parameter can include up to 50 recipients, across the To:, CC: and BCC:
fields>
The Destination parameter must include at least one recipient email address. The recipient address can be a To: address, a CC: address, or a BCC: address. If a recipient email address is invalid (that is, it is not in the format UserName@[SubDomain.]Domain.TopLevelDomain), the entire message will be rejected, even if the message contains other recipients that are
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1567 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SendTemplatedEmailResponse *>(send(request));
 }
setActiveReceiptRuleSet
SetActiveReceiptRuleSetResponse * QtAws::SES::SesClient::setActiveReceiptRuleSet (const SetActiveReceiptRuleSetRequest & request) slot
Sets the specified receipt rule set as the active receipt rule
set> <note>
To disable your email-receiving through Amazon SES completely, you can call this API with RuleSetName set to
null> </note>
For information about managing receipt rule sets, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1595 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetActiveReceiptRuleSetResponse *>(send(request));
 }
setIdentityDkimEnabled
SetIdentityDkimEnabledResponse * QtAws::SES::SesClient::setIdentityDkimEnabled (const SetIdentityDkimEnabledRequest & request) slot
Enables or disables Easy DKIM signing of email sent from an
identity>
If Easy DKIM signing is enabled for a domain name identity (such as example.com), then Amazon SES will DKIM-sign all email sent by addresses under that domain name (for example,
user@.nosp@m.exam.nosp@m.ple.c.nosp@m.om)>
If Easy DKIM signing is enabled for an email address, then Amazon SES will DKIM-sign all email sent by that email
address>
For email addresses (for example, user@.nosp@m.exam.nosp@m.ple.c.nosp@m.om), you can only enable Easy DKIM signing if the corresponding domain (in this case, example.com) has been set up for Easy DKIM using the AWS Console or the VerifyDomainDkim
operation>
You can execute this operation no more than once per
second>
For more information about Easy DKIM signing, go to the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1633 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityDkimEnabledResponse *>(send(request));
 }
setIdentityFeedbackForwardingEnabled
SetIdentityFeedbackForwardingEnabledResponse * QtAws::SES::SesClient::setIdentityFeedbackForwardingEnabled (const SetIdentityFeedbackForwardingEnabledRequest & request) slot
Given an identity (an email address or a domain), enables or disables whether Amazon SES forwards bounce and complaint notifications as email. Feedback forwarding can only be disabled when Amazon Simple Notification Service (Amazon SNS) topics are specified for both bounces and
complaints> <note>
Feedback forwarding does not apply to delivery notifications. Delivery notifications are only available through Amazon
SNS> </note>
You can execute this operation no more than once per
second>
For more information about using notifications with Amazon SES, see the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1662 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityFeedbackForwardingEnabledResponse *>(send(request));
 }
setIdentityHeadersInNotificationsEnabled
SetIdentityHeadersInNotificationsEnabledResponse * QtAws::SES::SesClient::setIdentityHeadersInNotificationsEnabled (const SetIdentityHeadersInNotificationsEnabledRequest & request) slot
Given an identity (an email address or a domain), sets whether Amazon SES includes the original email headers in the Amazon Simple Notification Service (Amazon SNS) notifications of a specified
type>
You can execute this operation no more than once per
second>
For more information about using notifications with Amazon SES, see the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1686 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityHeadersInNotificationsEnabledResponse *>(send(request));
 }
setIdentityMailFromDomain
SetIdentityMailFromDomainResponse * QtAws::SES::SesClient::setIdentityMailFromDomain (const SetIdentityMailFromDomainRequest & request) slot
Enables or disables the custom MAIL FROM domain setup for a verified identity (an email address or a
domain)>
To send emails using the specified MAIL FROM domain, you must add an MX record to your MAIL FROM domain's DNS settings. If you want your emails to pass Sender Policy Framework (SPF) checks, you must also add or update an SPF record. For more information, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1711 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityMailFromDomainResponse *>(send(request));
 }
setIdentityNotificationTopic
SetIdentityNotificationTopicResponse * QtAws::SES::SesClient::setIdentityNotificationTopic (const SetIdentityNotificationTopicRequest & request) slot
Given an identity (an email address or a domain), sets the Amazon Simple Notification Service (Amazon SNS) topic to which Amazon SES will publish bounce, complaint, and/or delivery notifications for emails sent with that identity as the
Source> <note>
Unless feedback forwarding is enabled, you must specify Amazon SNS topics for bounce and complaint notifications. For more information, see
SetIdentityFeedbackForwardingEnabled> </note>
You can execute this operation no more than once per
second>
For more information about feedback notification, see the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1740 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetIdentityNotificationTopicResponse *>(send(request));
 }
setReceiptRulePosition
SetReceiptRulePositionResponse * QtAws::SES::SesClient::setReceiptRulePosition (const SetReceiptRulePositionRequest & request) slot
Sets the position of the specified receipt rule in the receipt rule
set>
For information about managing receipt rules, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1764 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetReceiptRulePositionResponse *>(send(request));
 }
testRenderTemplate
TestRenderTemplateResponse * QtAws::SES::SesClient::testRenderTemplate (const TestRenderTemplateRequest & request) slot
Creates a preview of the MIME content of an email when provided with a template and a set of replacement
data>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1782 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TestRenderTemplateResponse *>(send(request));
 }
updateAccountSendingEnabled
UpdateAccountSendingEnabledResponse * QtAws::SES::SesClient::updateAccountSendingEnabled (const UpdateAccountSendingEnabledRequest & request) slot
Enables or disables email sending across your entire Amazon SES account. You can use this operation in conjunction with Amazon CloudWatch alarms to temporarily pause email sending across your Amazon SES account when reputation metrics (such as your bounce on complaint rate) reach certain
thresholds>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1802 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAccountSendingEnabledResponse *>(send(request));
 }
updateConfigurationSetEventDestination
UpdateConfigurationSetEventDestinationResponse * QtAws::SES::SesClient::updateConfigurationSetEventDestination (const UpdateConfigurationSetEventDestinationRequest & request) slot
Updates the event destination of a configuration set. Event destinations are associated with configuration sets, which enable you to publish email sending events to Amazon CloudWatch, Amazon Kinesis Firehose, or Amazon Simple Notification Service (Amazon SNS). For information about using configuration sets, see Monitoring Your Amazon SES Sending Activity in the Amazon SES Developer Guide.
</p <note>
When you create or update an event destination, you must provide one, and only one, destination. The destination can be Amazon CloudWatch, Amazon Kinesis Firehose, or Amazon Simple Notification Service (Amazon
SNS)> </note>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1829 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConfigurationSetEventDestinationResponse *>(send(request));
 }
updateConfigurationSetReputationMetricsEnabled
UpdateConfigurationSetReputationMetricsEnabledResponse * QtAws::SES::SesClient::updateConfigurationSetReputationMetricsEnabled (const UpdateConfigurationSetReputationMetricsEnabledRequest & request) slot
Enables or disables the publishing of reputation metrics for emails sent using a specific configuration set. Reputation metrics include bounce and complaint rates. These metrics are published to Amazon CloudWatch. By using Amazon CloudWatch, you can create alarms when bounce or complaint rates exceed a certain
threshold>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1849 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConfigurationSetReputationMetricsEnabledResponse *>(send(request));
 }
updateConfigurationSetSendingEnabled
UpdateConfigurationSetSendingEnabledResponse * QtAws::SES::SesClient::updateConfigurationSetSendingEnabled (const UpdateConfigurationSetSendingEnabledRequest & request) slot
Enables or disables email sending for messages sent using a specific configuration set. You can use this operation in conjunction with Amazon CloudWatch alarms to temporarily pause email sending for a configuration set when the reputation metrics for that configuration set (such as your bounce on complaint rate) reach certain
thresholds>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1869 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConfigurationSetSendingEnabledResponse *>(send(request));
 }
updateConfigurationSetTrackingOptions
UpdateConfigurationSetTrackingOptionsResponse * QtAws::SES::SesClient::updateConfigurationSetTrackingOptions (const UpdateConfigurationSetTrackingOptionsRequest & request) slot
Modifies an association between a configuration set and a custom domain for open and click event tracking.
</p
By default, images and links used for tracking open and click events are hosted on domains operated by Amazon SES. You can configure a subdomain of your own to handle these events. For information about using configuration sets, see Configuring Custom Domains to Handle Open and Click Tracking in the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1891 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConfigurationSetTrackingOptionsResponse *>(send(request));
 }
updateCustomVerificationEmailTemplate
UpdateCustomVerificationEmailTemplateResponse * QtAws::SES::SesClient::updateCustomVerificationEmailTemplate (const UpdateCustomVerificationEmailTemplateRequest & request) slot
Updates an existing custom verification email
template>
For more information about custom verification email templates, see Using Custom Verification Email Templates in the Amazon SES Developer
Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1915 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateCustomVerificationEmailTemplateResponse *>(send(request));
 }
updateReceiptRule
UpdateReceiptRuleResponse * QtAws::SES::SesClient::updateReceiptRule (const UpdateReceiptRuleRequest & request) slot
Updates a receipt
rule>
For information about managing receipt rules, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1939 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateReceiptRuleResponse *>(send(request));
 }
updateTemplate
UpdateTemplateResponse * QtAws::SES::SesClient::updateTemplate (const UpdateTemplateRequest & request) slot
Updates an email template. Email templates enable you to send personalized email to one or more destinations in a single API operation. For more information, see the Amazon SES Developer Guide>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1959 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTemplateResponse *>(send(request));
 }
verifyDomainDkim
VerifyDomainDkimResponse * QtAws::SES::SesClient::verifyDomainDkim (const VerifyDomainDkimRequest & request) slot
Returns a set of DKIM tokens for a domain. DKIM tokens are character strings that represent your domain's identity. Using these tokens, you will need to create DNS CNAME records that point to DKIM public keys hosted by Amazon SES. Amazon Web Services will eventually detect that you have updated your DNS records; this detection process may take up to 72 hours. Upon successful detection, Amazon SES will be able to DKIM-sign email originating from that
domain>
You can execute this operation no more than once per
second>
To enable or disable Easy DKIM signing for a domain, use the SetIdentityDkimEnabled
operation>
For more information about creating DNS records using DKIM tokens, go to the Amazon SES Developer request Request to send to Amazon Simple Email Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 1989 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifyDomainDkimResponse *>(send(request));
 }
verifyDomainIdentity
VerifyDomainIdentityResponse * QtAws::SES::SesClient::verifyDomainIdentity (const VerifyDomainIdentityRequest & request) slot
Adds a domain to the list of identities for your Amazon SES account and attempts to verify it. For more information about verifying domains, see Verifying Email Addresses and Domains in the Amazon SES Developer Guide.
</p
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2010 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifyDomainIdentityResponse *>(send(request));
 }
verifyEmailAddress
VerifyEmailAddressResponse * QtAws::SES::SesClient::verifyEmailAddress (const VerifyEmailAddressRequest & request) slot
Deprecated. Use the VerifyEmailIdentity operation to verify a new email
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2024 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifyEmailAddressResponse *>(send(request));
 }
verifyEmailIdentity
VerifyEmailIdentityResponse * QtAws::SES::SesClient::verifyEmailIdentity (const VerifyEmailIdentityRequest & request) slot
Adds an email address to the list of identities for your Amazon SES account and attempts to verify it. As a result of executing this operation, a verification email is sent to the specified
address>
You can execute this operation no more than once per
Parameters
request Request to send to Amazon Simple Email Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 2043 of file sesclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<VerifyEmailIdentityResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
email/sesclient.h
email/sesclient.cpp