AWS SDK for Qt: QtAws::CostandUsageReportService::CostandUsageReportServiceClient Class Reference
QtAws::CostandUsageReportService::CostandUsageReportServiceClient Class Reference
Client for AWS Cost and Usage Report Service.
Public Slots
DeleteReportDefinitionResponse * deleteReportDefinition (const DeleteReportDefinitionRequest &request)
DescribeReportDefinitionsResponse * describeReportDefinitions (const DescribeReportDefinitionsRequest &request)
PutReportDefinitionResponse * putReportDefinition (const PutReportDefinitionRequest &request)
Public Member Functions
CostandUsageReportServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CostandUsageReportServiceClient object.
CostandUsageReportServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CostandUsageReportServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Cost and Usage Report Service.
Definition at line 38 of file costandusagereportserviceclient.h.
Constructor & Destructor Documentation
CostandUsageReportServiceClient() [1/2]
QtAws::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CostandUsageReportServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 52 of file costandusagereportserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CostandUsageReportServiceClientPrivate(this), parent)
 {
     Q_D(CostandUsageReportServiceClient);
     d->apiVersion = QStringLiteral("2017-01-06");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cur");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Cost and Usage Report Service");
     d->serviceName = QStringLiteral("cur");
 }
CostandUsageReportServiceClient() [2/2]
QtAws::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CostandUsageReportServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 85 of file costandusagereportserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CostandUsageReportServiceClientPrivate(this), parent)
 {
     Q_D(CostandUsageReportServiceClient);
     d->apiVersion = QStringLiteral("2017-01-06");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cur");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Cost and Usage Report Service");
     d->serviceName = QStringLiteral("cur");
 }
Member Function Documentation
deleteReportDefinition
DeleteReportDefinitionResponse * QtAws::CostandUsageReportService::CostandUsageReportServiceClient::deleteReportDefinition (const DeleteReportDefinitionRequest & request) slot
Parameters
request Request to send to AWS Cost and Usage Report Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 110 of file costandusagereportserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteReportDefinitionResponse *>(send(request));
 }
describeReportDefinitions
DescribeReportDefinitionsResponse * QtAws::CostandUsageReportService::CostandUsageReportServiceClient::describeReportDefinitions (const DescribeReportDefinitionsRequest & request) slot
Parameters
request Request to send to AWS Cost and Usage Report Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 123 of file costandusagereportserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeReportDefinitionsResponse *>(send(request));
 }
putReportDefinition
PutReportDefinitionResponse * QtAws::CostandUsageReportService::CostandUsageReportServiceClient::putReportDefinition (const PutReportDefinitionRequest & request) slot
Parameters
request Request to send to AWS Cost and Usage Report Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 136 of file costandusagereportserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutReportDefinitionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cur/costandusagereportserviceclient.h
cur/costandusagereportserviceclient.cpp