AWS SDK for Qt: QtAws::KinesisAnalytics::KinesisAnalyticsClient Class Reference
QtAws::KinesisAnalytics::KinesisAnalyticsClient Class Reference
Client for Amazon Kinesis Analytics.
Public Slots
AddApplicationCloudWatchLoggingOptionResponse * addApplicationCloudWatchLoggingOption (const AddApplicationCloudWatchLoggingOptionRequest &request)
AddApplicationInputResponse * addApplicationInput (const AddApplicationInputRequest &request)
AddApplicationInputProcessingConfigurationResponse * addApplicationInputProcessingConfiguration (const AddApplicationInputProcessingConfigurationRequest &request)
AddApplicationOutputResponse * addApplicationOutput (const AddApplicationOutputRequest &request)
AddApplicationReferenceDataSourceResponse * addApplicationReferenceDataSource (const AddApplicationReferenceDataSourceRequest &request)
CreateApplicationResponse * createApplication (const CreateApplicationRequest &request)
DeleteApplicationResponse * deleteApplication (const DeleteApplicationRequest &request)
DeleteApplicationCloudWatchLoggingOptionResponse * deleteApplicationCloudWatchLoggingOption (const DeleteApplicationCloudWatchLoggingOptionRequest &request)
DeleteApplicationInputProcessingConfigurationResponse * deleteApplicationInputProcessingConfiguration (const DeleteApplicationInputProcessingConfigurationRequest &request)
DeleteApplicationOutputResponse * deleteApplicationOutput (const DeleteApplicationOutputRequest &request)
DeleteApplicationReferenceDataSourceResponse * deleteApplicationReferenceDataSource (const DeleteApplicationReferenceDataSourceRequest &request)
DescribeApplicationResponse * describeApplication (const DescribeApplicationRequest &request)
DiscoverInputSchemaResponse * discoverInputSchema (const DiscoverInputSchemaRequest &request)
ListApplicationsResponse * listApplications (const ListApplicationsRequest &request)
StartApplicationResponse * startApplication (const StartApplicationRequest &request)
StopApplicationResponse * stopApplication (const StopApplicationRequest &request)
UpdateApplicationResponse * updateApplication (const UpdateApplicationRequest &request)
Public Member Functions
KinesisAnalyticsClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisAnalyticsClient object.
KinesisAnalyticsClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisAnalyticsClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Kinesis Analytics.
Definition at line 66 of file kinesisanalyticsclient.h.
Constructor & Destructor Documentation
KinesisAnalyticsClient() [1/2]
QtAws::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisAnalyticsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 80 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new KinesisAnalyticsClientPrivate(this), parent)
 {
     Q_D(KinesisAnalyticsClient);
     d->apiVersion = QStringLiteral("2015-08-14");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("kinesisanalytics");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Analytics");
     d->serviceName = QStringLiteral("kinesisanalytics");
 }
KinesisAnalyticsClient() [2/2]
QtAws::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisAnalyticsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 113 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new KinesisAnalyticsClientPrivate(this), parent)
 {
     Q_D(KinesisAnalyticsClient);
     d->apiVersion = QStringLiteral("2015-08-14");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("kinesisanalytics");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Analytics");
     d->serviceName = QStringLiteral("kinesisanalytics");
 }
Member Function Documentation
addApplicationCloudWatchLoggingOption
AddApplicationCloudWatchLoggingOptionResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationCloudWatchLoggingOption (const AddApplicationCloudWatchLoggingOptionRequest & request) slot
Adds a CloudWatch log stream to monitor application configuration errors. For more information about using CloudWatch log streams with Amazon Kinesis Analytics applications, see Working with Amazon CloudWatch request Request to send to Amazon Kinesis Analytics. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 141 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddApplicationCloudWatchLoggingOptionResponse *>(send(request));
 }
addApplicationInput
AddApplicationInputResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationInput (const AddApplicationInputRequest & request) slot
Adds a streaming source to your Amazon Kinesis application. For conceptual information, see Configuring Application Input.
</p
You can add a streaming source either when you create an application or you can use this operation to add a streaming source after you create an application. For more information, see
CreateApplication>
Any configuration update, including adding a streaming source using this operation, results in a new version of the application. You can use the DescribeApplication operation to find the current application version.
</p
This operation requires permissions to perform the kinesisanalytics:AddApplicationInput
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 170 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddApplicationInputResponse *>(send(request));
 }
addApplicationInputProcessingConfiguration
AddApplicationInputProcessingConfigurationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationInputProcessingConfiguration (const AddApplicationInputProcessingConfigurationRequest & request) slot
Adds an InputProcessingConfiguration to an application. An input processor preprocesses records on the input stream before the application's SQL code executes. Currently, the only input processor available is AWS request Request to send to Amazon Kinesis Analytics. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 186 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddApplicationInputProcessingConfigurationResponse *>(send(request));
 }
addApplicationOutput
AddApplicationOutputResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationOutput (const AddApplicationOutputRequest & request) slot
Adds an external destination to your Amazon Kinesis Analytics
application>
If you want Amazon Kinesis Analytics to deliver data from an in-application stream within your application to an external destination (such as an Amazon Kinesis stream, an Amazon Kinesis Firehose delivery stream, or an Amazon Lambda function), you add the relevant configuration to your application using this operation. You can configure one or more outputs for your application. Each output configuration maps an in-application stream and an external
destination>
You can use one of the output configurations to deliver data from your in-application error stream to an external destination so that you can analyze the errors. For conceptual information, see Understanding Application Output (Destination).
</p
Note that any configuration update, including adding a streaming source using this operation, results in a new version of the application. You can use the DescribeApplication operation to find the current application
version>
For the limits on the number of application inputs and outputs you can configure, see Limits>
This operation requires permissions to perform the kinesisanalytics:AddApplicationOutput
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 227 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddApplicationOutputResponse *>(send(request));
 }
addApplicationReferenceDataSource
AddApplicationReferenceDataSourceResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationReferenceDataSource (const AddApplicationReferenceDataSourceRequest & request) slot
Adds a reference data source to an existing
application>
Amazon Kinesis Analytics reads reference data (that is, an Amazon S3 object) and creates an in-application table within your application. In the request, you provide the source (S3 bucket name and object key name), name of the in-application table to create, and the necessary mapping information that describes how data in Amazon S3 object maps to columns in the resulting in-application
table>
For conceptual information, see Configuring Application Input. For the limits on data sources you can add to your application, see Limits.
</p
This operation requires permissions to perform the kinesisanalytics:AddApplicationOutput action.
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddApplicationReferenceDataSourceResponse *>(send(request));
 }
createApplication
CreateApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::createApplication (const CreateApplicationRequest & request) slot
Creates an Amazon Kinesis Analytics application. You can configure each application with one streaming source as input, application code to process the input, and up to three destinations where you want Amazon Kinesis Analytics to write the output data from your application. For an overview, see How it Works.
</p
In the input configuration, you map the streaming source to an in-application stream, which you can think of as a constantly updating table. In the mapping, you must provide a schema for the in-application stream and map each data column in the in-application stream to a data element in the streaming
source>
Your application code is one or more SQL statements that read input data, transform it, and generate output. Your application code can create one or more SQL artifacts like SQL streams or
pumps>
In the output configuration, you can configure the application to write data from in-application streams created in your applications to up to three
destinations>
To read data from your source stream or write data to destination streams, Amazon Kinesis Analytics needs your permissions. You grant these permissions by creating IAM roles. This operation requires permissions to perform the kinesisanalytics:CreateApplication action.
</p
For introductory exercises to create an Amazon Kinesis Analytics application, see Getting Started.
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 303 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateApplicationResponse *>(send(request));
 }
deleteApplication
DeleteApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplication (const DeleteApplicationRequest & request) slot
Deletes the specified application. Amazon Kinesis Analytics halts application execution and deletes the application, including any application artifacts (such as in-application streams, reference table, and application
code)>
This operation requires permissions to perform the kinesisanalytics:DeleteApplication
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 322 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationResponse *>(send(request));
 }
deleteApplicationCloudWatchLoggingOption
DeleteApplicationCloudWatchLoggingOptionResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationCloudWatchLoggingOption (const DeleteApplicationCloudWatchLoggingOptionRequest & request) slot
Deletes a CloudWatch log stream from an application. For more information about using CloudWatch log streams with Amazon Kinesis Analytics applications, see Working with Amazon CloudWatch request Request to send to Amazon Kinesis Analytics. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 338 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationCloudWatchLoggingOptionResponse *>(send(request));
 }
deleteApplicationInputProcessingConfiguration
DeleteApplicationInputProcessingConfigurationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationInputProcessingConfiguration (const DeleteApplicationInputProcessingConfigurationRequest & request) slot
Deletes an InputProcessingConfiguration from an
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 352 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationInputProcessingConfigurationResponse *>(send(request));
 }
deleteApplicationOutput
DeleteApplicationOutputResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationOutput (const DeleteApplicationOutputRequest & request) slot
Deletes output destination configuration from your application configuration. Amazon Kinesis Analytics will no longer write data from the corresponding in-application stream to the external output
destination>
This operation requires permissions to perform the kinesisanalytics:DeleteApplicationOutput
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 371 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationOutputResponse *>(send(request));
 }
deleteApplicationReferenceDataSource
DeleteApplicationReferenceDataSourceResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationReferenceDataSource (const DeleteApplicationReferenceDataSourceRequest & request) slot
Deletes a reference data source configuration from the specified application
configuration>
If the application is running, Amazon Kinesis Analytics immediately removes the in-application table that you created using the AddApplicationReferenceDataSource operation.
</p
This operation requires permissions to perform the kinesisanalytics.DeleteApplicationReferenceDataSource
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 394 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteApplicationReferenceDataSourceResponse *>(send(request));
 }
describeApplication
DescribeApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::describeApplication (const DescribeApplicationRequest & request) slot
Returns information about a specific Amazon Kinesis Analytics
application>
If you want to retrieve a list of all applications in your account, use the ListApplications
operation>
This operation requires permissions to perform the kinesisanalytics:DescribeApplication action. You can use DescribeApplication to get the current application versionId, which you need to call other operations such as Update.
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 418 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeApplicationResponse *>(send(request));
 }
discoverInputSchema
DiscoverInputSchemaResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::discoverInputSchema (const DiscoverInputSchemaRequest & request) slot
Infers a schema by evaluating sample records on the specified streaming source (Amazon Kinesis stream or Amazon Kinesis Firehose delivery stream) or S3 object. In the response, the operation returns the inferred schema and also the sample records that the operation used to infer the
schema>
You can use the inferred schema when configuring a streaming source for your application. For conceptual information, see Configuring Application Input. Note that when you create an application using the Amazon Kinesis Analytics console, the console uses this operation to infer a schema and show it in the console user interface.
</p
This operation requires permissions to perform the kinesisanalytics:DiscoverInputSchema action.
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 445 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DiscoverInputSchemaResponse *>(send(request));
 }
listApplications
ListApplicationsResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::listApplications (const ListApplicationsRequest & request) slot
Returns a list of Amazon Kinesis Analytics applications in your account. For each application, the response includes the application name, Amazon Resource Name (ARN), and status. If the response returns the HasMoreApplications value as true, you can send another request by adding the ExclusiveStartApplicationName in the request body, and set the value of this to the last application name from the previous response.
</p
If you want detailed information about a specific application, use
DescribeApplication>
This operation requires permissions to perform the kinesisanalytics:ListApplications
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 470 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListApplicationsResponse *>(send(request));
 }
startApplication
StartApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::startApplication (const StartApplicationRequest & request) slot
Starts the specified Amazon Kinesis Analytics application. After creating an application, you must exclusively call this operation to start your
application>
After the application starts, it begins consuming the input data, processes it, and writes the output to the configured
destination>
The application status must be READY for you to start an application. You can get the application status in the console or using the DescribeApplication
operation>
After you start the application, you can stop the application from processing the input by calling the StopApplication
operation>
This operation requires permissions to perform the kinesisanalytics:StartApplication
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 503 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartApplicationResponse *>(send(request));
 }
stopApplication
StopApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::stopApplication (const StopApplicationRequest & request) slot
Stops the application from processing input data. You can stop an application only if it is in the running state. You can use the DescribeApplication operation to find the application state. After the application is stopped, Amazon Kinesis Analytics stops reading data from the input, the application stops processing data, and there is no output written to the destination.
</p
This operation requires permissions to perform the kinesisanalytics:StopApplication
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 524 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopApplicationResponse *>(send(request));
 }
updateApplication
UpdateApplicationResponse * QtAws::KinesisAnalytics::KinesisAnalyticsClient::updateApplication (const UpdateApplicationRequest & request) slot
Updates an existing Amazon Kinesis Analytics application. Using this API, you can update application code, input configuration, and output configuration.
</p
Note that Amazon Kinesis Analytics updates the CurrentApplicationVersionId each time you update your application.
</p
This operation requires permission for the kinesisanalytics:UpdateApplication
Parameters
request Request to send to Amazon Kinesis Analytics.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 548 of file kinesisanalyticsclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateApplicationResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
kinesisanalytics/kinesisanalyticsclient.h
kinesisanalytics/kinesisanalyticsclient.cpp