AWS SDK for Qt: QtAws::Core::AwsAbstractClient Class Reference
QtAws::Core::AwsAbstractClient Class Reference
Interface class for providing access to individual AWS services.
Inherits QObject.
Inherited by QtAws::ACM::AcmClient, QtAws::AlexaForBusiness::AlexaForBusinessClient, QtAws::APIGateway::APIGatewayClient, QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient, QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient, QtAws::AppStream::AppStreamClient, QtAws::AppSync::AppSyncClient, QtAws::Athena::AthenaClient, QtAws::AutoScaling::AutoScalingClient, QtAws::AutoScalingPlans::AutoScalingPlansClient, QtAws::Batch::BatchClient, QtAws::Budgets::BudgetsClient, QtAws::Cloud9::Cloud9Client, QtAws::CloudDirectory::CloudDirectoryClient, QtAws::CloudFormation::CloudFormationClient, QtAws::CloudFront::CloudFrontClient, QtAws::CloudHSM::CloudHSMClient, QtAws::CloudHSMV2::CloudHSMV2Client, QtAws::CloudSearch::CloudSearchClient, QtAws::CloudSearchDomain::CloudSearchDomainClient, QtAws::CloudTrail::CloudTrailClient, QtAws::CloudWatch::CloudWatchClient, QtAws::CloudWatchEvents::CloudWatchEventsClient, QtAws::CloudWatchLogs::CloudWatchLogsClient, QtAws::CodeBuild::CodeBuildClient, QtAws::CodeCommit::CodeCommitClient, QtAws::CodeDeploy::CodeDeployClient, QtAws::CodePipeline::CodePipelineClient, QtAws::CodeStar::CodeStarClient, QtAws::CognitoIdentity::CognitoIdentityClient, QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient, QtAws::CognitoSync::CognitoSyncClient, QtAws::Comprehend::ComprehendClient, QtAws::ConfigService::ConfigServiceClient, QtAws::CostandUsageReportService::CostandUsageReportServiceClient, QtAws::CostExplorer::CostExplorerClient, QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient, QtAws::DataPipeline::DataPipelineClient, QtAws::DAX::DaxClient, QtAws::DeviceFarm::DeviceFarmClient, QtAws::DirectConnect::DirectConnectClient, QtAws::DirectoryService::DirectoryServiceClient, QtAws::DynamoDB::DynamoDBClient, QtAws::DynamoDBStreams::DynamoDBStreamsClient, QtAws::EC2::Ec2Client, QtAws::ECR::EcrClient, QtAws::ECS::EcsClient, QtAws::EFS::EfsClient, QtAws::ElastiCache::ElastiCacheClient, QtAws::ElasticBeanstalk::ElasticBeanstalkClient, QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient, QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client, QtAws::ElasticsearchService::ElasticsearchServiceClient, QtAws::ElasticTranscoder::ElasticTranscoderClient, QtAws::EMR::EmrClient, QtAws::Firehose::FirehoseClient, QtAws::GameLift::GameLiftClient, QtAws::Glacier::GlacierClient, QtAws::Glue::GlueClient, QtAws::Greengrass::GreengrassClient, QtAws::GuardDuty::GuardDutyClient, QtAws::Health::HealthClient, QtAws::IAM::IamClient, QtAws::ImportExport::ImportExportClient, QtAws::Inspector::InspectorClient, QtAws::IoT::IoTClient, QtAws::IoTDataPlane::IoTDataPlaneClient, QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient, QtAws::Kinesis::KinesisClient, QtAws::KinesisAnalytics::KinesisAnalyticsClient, QtAws::KinesisVideo::KinesisVideoClient, QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient, QtAws::KinesisVideoMedia::KinesisVideoMediaClient, QtAws::KMS::KmsClient, QtAws::Lambda::LambdaClient, QtAws::LexModelBuildingService::LexModelBuildingServiceClient, QtAws::LexRuntimeService::LexRuntimeServiceClient, QtAws::Lightsail::LightsailClient, QtAws::MachineLearning::MachineLearningClient, QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient, QtAws::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient, QtAws::MarketplaceMetering::MarketplaceMeteringClient, QtAws::MediaConvert::MediaConvertClient, QtAws::MediaLive::MediaLiveClient, QtAws::MediaPackage::MediaPackageClient, QtAws::MediaStore::MediaStoreClient, QtAws::MediaStoreData::MediaStoreDataClient, QtAws::MigrationHub::MigrationHubClient, QtAws::Mobile::MobileClient, QtAws::MobileAnalytics::MobileAnalyticsClient, QtAws::MQ::MqClient, QtAws::MTurk::MTurkClient, QtAws::OpsWorks::OpsWorksClient, QtAws::OpsWorksCM::OpsWorksCMClient, QtAws::Organizations::OrganizationsClient, QtAws::Pinpoint::PinpointClient, QtAws::Polly::PollyClient, QtAws::Pricing::PricingClient, QtAws::RDS::RdsClient, QtAws::Redshift::RedshiftClient, QtAws::Rekognition::RekognitionClient, QtAws::ResourceGroups::ResourceGroupsClient, QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient, QtAws::Route53::Route53Client, QtAws::Route53Domains::Route53DomainsClient, QtAws::S3::S3Client, QtAws::SageMaker::SageMakerClient, QtAws::SageMakerRuntime::SageMakerRuntimeClient, QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient, QtAws::ServiceCatalog::ServiceCatalogClient, QtAws::ServiceDiscovery::ServiceDiscoveryClient, QtAws::SES::SesClient, QtAws::SFN::SfnClient, QtAws::Shield::ShieldClient, QtAws::SimpleDB::SimpleDBClient, QtAws::SMS::SmsClient, QtAws::Snowball::SnowballClient, QtAws::SNS::SnsClient, QtAws::SQS::SqsClient, QtAws::SSM::SsmClient, QtAws::StorageGateway::StorageGatewayClient, QtAws::STS::StsClient, QtAws::Support::SupportClient, QtAws::SWF::SwfClient, QtAws::TranscribeService::TranscribeServiceClient, QtAws::Translate::TranslateClient, QtAws::WAF::WafClient, QtAws::WAFRegional::WAFRegionalClient, QtAws::WorkDocs::WorkDocsClient, QtAws::WorkMail::WorkMailClient, QtAws::WorkSpaces::WorkSpacesClient, and QtAws::XRay::XRayClient.
Public Member Functions
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Protected Member Functions
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Friends
class TestAwsAbstractClient
Detailed Description
Interface class for providing access to individual AWS services.
Definition at line 39 of file awsabstractclient.h.
Constructor & Destructor Documentation
AwsAbstractClient() [1/2]
AwsAbstractClient::AwsAbstractClient (QObject *const parent = 0)
Constructs a new AwsAbstractClient object.
Parameters
parent This object's parent.
Definition at line 45 of file awsabstractclient.cpp.
     : QObject(parent), d_ptr(new AwsAbstractClientPrivate(this))
 {
 }
AwsAbstractClient() [2/2]
AwsAbstractClient::AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent) protected
Constructs a new AwsAbstractClient object.
This overload allows derived classes to provide their own private class implementation that inherits from AwsAbstractClientPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
parent This object's parent.
Definition at line 62 of file awsabstractclient.cpp.
     : QObject(parent), d_ptr(d)
 {
 }
Member Function Documentation
apiVersion()
QString AwsAbstractClient::apiVersion () const
Get the serivce API version this client implementts.
Returns
An Amazon service API version, such as "2012-11-05".
See also
endpoint
serviceName
Definition at line 87 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     Q_ASSERT(!d->endpointPrefix.isEmpty());
     return d->endpointPrefix;
 }
credentials()
AwsAbstractCredentials * AwsAbstractClient::credentials () const protected virtual
Get the credentials object to be used for signing requests.
Returns
An AWS credentials object.
Definition at line 316 of file awsabstractclient.cpp.
Referenced by QtAws::ACM::AcmClient::AcmClient(), QtAws::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), QtAws::APIGateway::APIGatewayClient::APIGatewayClient(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), QtAws::AppStream::AppStreamClient::AppStreamClient(), QtAws::AppSync::AppSyncClient::AppSyncClient(), QtAws::Athena::AthenaClient::AthenaClient(), QtAws::AutoScaling::AutoScalingClient::AutoScalingClient(), QtAws::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), QtAws::Batch::BatchClient::BatchClient(), QtAws::Budgets::BudgetsClient::BudgetsClient(), QtAws::Cloud9::Cloud9Client::Cloud9Client(), QtAws::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), QtAws::CloudFormation::CloudFormationClient::CloudFormationClient(), QtAws::CloudFront::CloudFrontClient::CloudFrontClient(), QtAws::CloudHSM::CloudHSMClient::CloudHSMClient(), QtAws::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), QtAws::CloudSearch::CloudSearchClient::CloudSearchClient(), QtAws::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), QtAws::CloudTrail::CloudTrailClient::CloudTrailClient(), QtAws::CloudWatch::CloudWatchClient::CloudWatchClient(), QtAws::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), QtAws::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), QtAws::CodeBuild::CodeBuildClient::CodeBuildClient(), QtAws::CodeCommit::CodeCommitClient::CodeCommitClient(), QtAws::CodeDeploy::CodeDeployClient::CodeDeployClient(), QtAws::CodePipeline::CodePipelineClient::CodePipelineClient(), QtAws::CodeStar::CodeStarClient::CodeStarClient(), QtAws::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), QtAws::CognitoSync::CognitoSyncClient::CognitoSyncClient(), QtAws::Comprehend::ComprehendClient::ComprehendClient(), QtAws::ConfigService::ConfigServiceClient::ConfigServiceClient(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), QtAws::CostExplorer::CostExplorerClient::CostExplorerClient(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), QtAws::DataPipeline::DataPipelineClient::DataPipelineClient(), QtAws::DAX::DaxClient::DaxClient(), QtAws::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), QtAws::DirectConnect::DirectConnectClient::DirectConnectClient(), QtAws::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), QtAws::DynamoDB::DynamoDBClient::DynamoDBClient(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), QtAws::EC2::Ec2Client::Ec2Client(), QtAws::ECR::EcrClient::EcrClient(), QtAws::ECS::EcsClient::EcsClient(), QtAws::EFS::EfsClient::EfsClient(), QtAws::ElastiCache::ElastiCacheClient::ElastiCacheClient(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), QtAws::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), QtAws::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), QtAws::EMR::EmrClient::EmrClient(), QtAws::Firehose::FirehoseClient::FirehoseClient(), QtAws::GameLift::GameLiftClient::GameLiftClient(), QtAws::Glacier::GlacierClient::GlacierClient(), QtAws::Glue::GlueClient::GlueClient(), QtAws::Greengrass::GreengrassClient::GreengrassClient(), QtAws::GuardDuty::GuardDutyClient::GuardDutyClient(), QtAws::Health::HealthClient::HealthClient(), QtAws::IAM::IamClient::IamClient(), QtAws::ImportExport::ImportExportClient::ImportExportClient(), QtAws::Inspector::InspectorClient::InspectorClient(), QtAws::IoT::IoTClient::IoTClient(), QtAws::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), QtAws::Kinesis::KinesisClient::KinesisClient(), QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), QtAws::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), QtAws::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), QtAws::KMS::KmsClient::KmsClient(), QtAws::Lambda::LambdaClient::LambdaClient(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), QtAws::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), QtAws::Lightsail::LightsailClient::LightsailClient(), QtAws::MachineLearning::MachineLearningClient::MachineLearningClient(), QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), QtAws::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), QtAws::MediaConvert::MediaConvertClient::MediaConvertClient(), QtAws::MediaLive::MediaLiveClient::MediaLiveClient(), QtAws::MediaPackage::MediaPackageClient::MediaPackageClient(), QtAws::MediaStore::MediaStoreClient::MediaStoreClient(), QtAws::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), QtAws::MigrationHub::MigrationHubClient::MigrationHubClient(), QtAws::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), QtAws::Mobile::MobileClient::MobileClient(), QtAws::MQ::MqClient::MqClient(), QtAws::MTurk::MTurkClient::MTurkClient(), QtAws::OpsWorks::OpsWorksClient::OpsWorksClient(), QtAws::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), QtAws::Organizations::OrganizationsClient::OrganizationsClient(), QtAws::Pinpoint::PinpointClient::PinpointClient(), QtAws::Polly::PollyClient::PollyClient(), QtAws::Pricing::PricingClient::PricingClient(), QtAws::RDS::RdsClient::RdsClient(), QtAws::Redshift::RedshiftClient::RedshiftClient(), QtAws::Rekognition::RekognitionClient::RekognitionClient(), QtAws::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), QtAws::Route53::Route53Client::Route53Client(), QtAws::Route53Domains::Route53DomainsClient::Route53DomainsClient(), QtAws::S3::S3Client::S3Client(), QtAws::SageMaker::SageMakerClient::SageMakerClient(), QtAws::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), QtAws::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), QtAws::SES::SesClient::SesClient(), setCredentials(), QtAws::SFN::SfnClient::SfnClient(), QtAws::Shield::ShieldClient::ShieldClient(), QtAws::SimpleDB::SimpleDBClient::SimpleDBClient(), QtAws::SMS::SmsClient::SmsClient(), QtAws::Snowball::SnowballClient::SnowballClient(), QtAws::SNS::SnsClient::SnsClient(), QtAws::SQS::SqsClient::SqsClient(), QtAws::SSM::SsmClient::SsmClient(), QtAws::StorageGateway::StorageGatewayClient::StorageGatewayClient(), QtAws::STS::StsClient::StsClient(), QtAws::Support::SupportClient::SupportClient(), QtAws::SWF::SwfClient::SwfClient(), QtAws::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), QtAws::Translate::TranslateClient::TranslateClient(), QtAws::WAF::WafClient::WafClient(), QtAws::WAFRegional::WAFRegionalClient::WAFRegionalClient(), QtAws::WorkDocs::WorkDocsClient::WorkDocsClient(), QtAws::WorkMail::WorkMailClient::WorkMailClient(), QtAws::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and QtAws::XRay::XRayClient::XRayClient().
 {
     Q_D(const AwsAbstractClient);
     return d->credentials;
 }
endpoint()
QUrl AwsAbstractClient::endpoint () const
Get the endpoint associated with this AWS client.
If a valid QUrl has been set (usually via setEndpoint), then this base implementation will return that QUrl. Otherwise, this base implementation will use the AwsEndpoint class to determine the endpoint to use based on this object's region and serviceName.
Returns
A QUrl specifying this AWS client's endpoint, or an invalid QUrl if none has been set.
See also
setEndpoint
region
serviceName
AwsEndpoint::getEndpoint
Todo:
Use endpointPrefix here.
Definition at line 110 of file awsabstractclient.cpp.
References QtAws::Core::AwsEndpoint::getEndpoint(), QtAws::Core::AwsRegion::name(), region(), and serviceName().
Referenced by QtAws::ACM::AcmClient::AcmClient(), QtAws::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), QtAws::APIGateway::APIGatewayClient::APIGatewayClient(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), QtAws::AppStream::AppStreamClient::AppStreamClient(), QtAws::AppSync::AppSyncClient::AppSyncClient(), QtAws::Athena::AthenaClient::AthenaClient(), QtAws::AutoScaling::AutoScalingClient::AutoScalingClient(), QtAws::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), QtAws::Batch::BatchClient::BatchClient(), QtAws::Budgets::BudgetsClient::BudgetsClient(), QtAws::Cloud9::Cloud9Client::Cloud9Client(), QtAws::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), QtAws::CloudFormation::CloudFormationClient::CloudFormationClient(), QtAws::CloudFront::CloudFrontClient::CloudFrontClient(), QtAws::CloudHSM::CloudHSMClient::CloudHSMClient(), QtAws::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), QtAws::CloudSearch::CloudSearchClient::CloudSearchClient(), QtAws::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), QtAws::CloudTrail::CloudTrailClient::CloudTrailClient(), QtAws::CloudWatch::CloudWatchClient::CloudWatchClient(), QtAws::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), QtAws::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), QtAws::CodeBuild::CodeBuildClient::CodeBuildClient(), QtAws::CodeCommit::CodeCommitClient::CodeCommitClient(), QtAws::CodeDeploy::CodeDeployClient::CodeDeployClient(), QtAws::CodePipeline::CodePipelineClient::CodePipelineClient(), QtAws::CodeStar::CodeStarClient::CodeStarClient(), QtAws::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), QtAws::CognitoSync::CognitoSyncClient::CognitoSyncClient(), QtAws::Comprehend::ComprehendClient::ComprehendClient(), QtAws::ConfigService::ConfigServiceClient::ConfigServiceClient(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), QtAws::CostExplorer::CostExplorerClient::CostExplorerClient(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), QtAws::DataPipeline::DataPipelineClient::DataPipelineClient(), QtAws::DAX::DaxClient::DaxClient(), QtAws::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), QtAws::DirectConnect::DirectConnectClient::DirectConnectClient(), QtAws::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), QtAws::DynamoDB::DynamoDBClient::DynamoDBClient(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), QtAws::EC2::Ec2Client::Ec2Client(), QtAws::ECR::EcrClient::EcrClient(), QtAws::ECS::EcsClient::EcsClient(), QtAws::EFS::EfsClient::EfsClient(), QtAws::ElastiCache::ElastiCacheClient::ElastiCacheClient(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), QtAws::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), QtAws::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), QtAws::EMR::EmrClient::EmrClient(), QtAws::Firehose::FirehoseClient::FirehoseClient(), QtAws::GameLift::GameLiftClient::GameLiftClient(), QtAws::Glacier::GlacierClient::GlacierClient(), QtAws::Glue::GlueClient::GlueClient(), QtAws::Greengrass::GreengrassClient::GreengrassClient(), QtAws::GuardDuty::GuardDutyClient::GuardDutyClient(), QtAws::Health::HealthClient::HealthClient(), QtAws::IAM::IamClient::IamClient(), QtAws::ImportExport::ImportExportClient::ImportExportClient(), QtAws::Inspector::InspectorClient::InspectorClient(), QtAws::IoT::IoTClient::IoTClient(), QtAws::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), QtAws::Kinesis::KinesisClient::KinesisClient(), QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), QtAws::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), QtAws::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), QtAws::KMS::KmsClient::KmsClient(), QtAws::Lambda::LambdaClient::LambdaClient(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), QtAws::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), QtAws::Lightsail::LightsailClient::LightsailClient(), QtAws::MachineLearning::MachineLearningClient::MachineLearningClient(), QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), QtAws::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), QtAws::MediaConvert::MediaConvertClient::MediaConvertClient(), QtAws::MediaLive::MediaLiveClient::MediaLiveClient(), QtAws::MediaPackage::MediaPackageClient::MediaPackageClient(), QtAws::MediaStore::MediaStoreClient::MediaStoreClient(), QtAws::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), QtAws::MigrationHub::MigrationHubClient::MigrationHubClient(), QtAws::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), QtAws::Mobile::MobileClient::MobileClient(), QtAws::MQ::MqClient::MqClient(), QtAws::MTurk::MTurkClient::MTurkClient(), QtAws::OpsWorks::OpsWorksClient::OpsWorksClient(), QtAws::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), QtAws::Organizations::OrganizationsClient::OrganizationsClient(), QtAws::Pinpoint::PinpointClient::PinpointClient(), QtAws::Polly::PollyClient::PollyClient(), QtAws::Pricing::PricingClient::PricingClient(), QtAws::RDS::RdsClient::RdsClient(), QtAws::Redshift::RedshiftClient::RedshiftClient(), QtAws::Rekognition::RekognitionClient::RekognitionClient(), QtAws::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), QtAws::Route53::Route53Client::Route53Client(), QtAws::Route53Domains::Route53DomainsClient::Route53DomainsClient(), QtAws::S3::S3Client::S3Client(), QtAws::SageMaker::SageMakerClient::SageMakerClient(), QtAws::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), send(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), QtAws::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), QtAws::SES::SesClient::SesClient(), setEndpoint(), QtAws::SFN::SfnClient::SfnClient(), QtAws::Shield::ShieldClient::ShieldClient(), QtAws::SimpleDB::SimpleDBClient::SimpleDBClient(), QtAws::SMS::SmsClient::SmsClient(), QtAws::Snowball::SnowballClient::SnowballClient(), QtAws::SNS::SnsClient::SnsClient(), QtAws::SQS::SqsClient::SqsClient(), QtAws::SSM::SsmClient::SsmClient(), QtAws::StorageGateway::StorageGatewayClient::StorageGatewayClient(), QtAws::STS::StsClient::StsClient(), QtAws::Support::SupportClient::SupportClient(), QtAws::SWF::SwfClient::SwfClient(), QtAws::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), QtAws::Translate::TranslateClient::TranslateClient(), QtAws::WAF::WafClient::WafClient(), QtAws::WAFRegional::WAFRegionalClient::WAFRegionalClient(), QtAws::WorkDocs::WorkDocsClient::WorkDocsClient(), QtAws::WorkMail::WorkMailClient::WorkMailClient(), QtAws::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and QtAws::XRay::XRayClient::XRayClient().
 {
     /// @todo Use endpointPrefix here.
     Q_D(const AwsAbstractClient);
     return (d->endpoint.isValid()) ? d->endpoint :
         AwsEndpoint::getEndpoint(AwsRegion::name(region()), serviceName());
 }
endpointPrefix()
QString AwsAbstractClient::endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
This is the standard endpoint prefix associated with this AWS service, is not affected by any explicit endpoint URL that may have beem set via setEndpoint.
Returns
An Amazon service endpoint prefix, such as "sqs" or "sns".
See also
endpoint
serviceName
Definition at line 129 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     Q_ASSERT(!d->endpointPrefix.isEmpty());
     return d->endpointPrefix;
 }
networkAccessManager()
QNetworkAccessManager * AwsAbstractClient::networkAccessManager () const
Get the network access manager for this AWS service object.
Returns
The QNetworkAccessManager that handles requests for this object.
Definition at line 141 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     return d->networkAccessManager;
 }
region()
AwsRegion::Region AwsAbstractClient::region () const
Get the AWS region associated with this client.
Returns
The AWS region for this client, or AwsRegion::InvalidRegion if none has been set.
See also
setRegion
endpoint
Definition at line 156 of file awsabstractclient.cpp.
Referenced by QtAws::ACM::AcmClient::AcmClient(), QtAws::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), QtAws::APIGateway::APIGatewayClient::APIGatewayClient(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), QtAws::AppStream::AppStreamClient::AppStreamClient(), QtAws::AppSync::AppSyncClient::AppSyncClient(), QtAws::Athena::AthenaClient::AthenaClient(), QtAws::AutoScaling::AutoScalingClient::AutoScalingClient(), QtAws::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), QtAws::Batch::BatchClient::BatchClient(), QtAws::Budgets::BudgetsClient::BudgetsClient(), QtAws::Cloud9::Cloud9Client::Cloud9Client(), QtAws::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), QtAws::CloudFormation::CloudFormationClient::CloudFormationClient(), QtAws::CloudFront::CloudFrontClient::CloudFrontClient(), QtAws::CloudHSM::CloudHSMClient::CloudHSMClient(), QtAws::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), QtAws::CloudSearch::CloudSearchClient::CloudSearchClient(), QtAws::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), QtAws::CloudTrail::CloudTrailClient::CloudTrailClient(), QtAws::CloudWatch::CloudWatchClient::CloudWatchClient(), QtAws::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), QtAws::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), QtAws::CodeBuild::CodeBuildClient::CodeBuildClient(), QtAws::CodeCommit::CodeCommitClient::CodeCommitClient(), QtAws::CodeDeploy::CodeDeployClient::CodeDeployClient(), QtAws::CodePipeline::CodePipelineClient::CodePipelineClient(), QtAws::CodeStar::CodeStarClient::CodeStarClient(), QtAws::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), QtAws::CognitoSync::CognitoSyncClient::CognitoSyncClient(), QtAws::Comprehend::ComprehendClient::ComprehendClient(), QtAws::ConfigService::ConfigServiceClient::ConfigServiceClient(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), QtAws::CostExplorer::CostExplorerClient::CostExplorerClient(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), QtAws::DataPipeline::DataPipelineClient::DataPipelineClient(), QtAws::DAX::DaxClient::DaxClient(), QtAws::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), QtAws::DirectConnect::DirectConnectClient::DirectConnectClient(), QtAws::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), QtAws::DynamoDB::DynamoDBClient::DynamoDBClient(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), QtAws::EC2::Ec2Client::Ec2Client(), QtAws::ECR::EcrClient::EcrClient(), QtAws::ECS::EcsClient::EcsClient(), QtAws::EFS::EfsClient::EfsClient(), QtAws::ElastiCache::ElastiCacheClient::ElastiCacheClient(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), QtAws::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), QtAws::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), QtAws::EMR::EmrClient::EmrClient(), endpoint(), QtAws::Firehose::FirehoseClient::FirehoseClient(), QtAws::GameLift::GameLiftClient::GameLiftClient(), QtAws::Glacier::GlacierClient::GlacierClient(), QtAws::Glue::GlueClient::GlueClient(), QtAws::Greengrass::GreengrassClient::GreengrassClient(), QtAws::GuardDuty::GuardDutyClient::GuardDutyClient(), QtAws::Health::HealthClient::HealthClient(), QtAws::IAM::IamClient::IamClient(), QtAws::ImportExport::ImportExportClient::ImportExportClient(), QtAws::Inspector::InspectorClient::InspectorClient(), QtAws::IoT::IoTClient::IoTClient(), QtAws::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), QtAws::Kinesis::KinesisClient::KinesisClient(), QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), QtAws::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), QtAws::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), QtAws::KMS::KmsClient::KmsClient(), QtAws::Lambda::LambdaClient::LambdaClient(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), QtAws::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), QtAws::Lightsail::LightsailClient::LightsailClient(), QtAws::MachineLearning::MachineLearningClient::MachineLearningClient(), QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), QtAws::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), QtAws::MediaConvert::MediaConvertClient::MediaConvertClient(), QtAws::MediaLive::MediaLiveClient::MediaLiveClient(), QtAws::MediaPackage::MediaPackageClient::MediaPackageClient(), QtAws::MediaStore::MediaStoreClient::MediaStoreClient(), QtAws::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), QtAws::MigrationHub::MigrationHubClient::MigrationHubClient(), QtAws::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), QtAws::Mobile::MobileClient::MobileClient(), QtAws::MQ::MqClient::MqClient(), QtAws::MTurk::MTurkClient::MTurkClient(), QtAws::OpsWorks::OpsWorksClient::OpsWorksClient(), QtAws::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), QtAws::Organizations::OrganizationsClient::OrganizationsClient(), QtAws::Pinpoint::PinpointClient::PinpointClient(), QtAws::Polly::PollyClient::PollyClient(), QtAws::Pricing::PricingClient::PricingClient(), QtAws::RDS::RdsClient::RdsClient(), QtAws::Redshift::RedshiftClient::RedshiftClient(), QtAws::Rekognition::RekognitionClient::RekognitionClient(), QtAws::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), QtAws::Route53::Route53Client::Route53Client(), QtAws::Route53Domains::Route53DomainsClient::Route53DomainsClient(), QtAws::S3::S3Client::S3Client(), QtAws::SageMaker::SageMakerClient::SageMakerClient(), QtAws::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), QtAws::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), QtAws::SES::SesClient::SesClient(), setRegion(), QtAws::SFN::SfnClient::SfnClient(), QtAws::Shield::ShieldClient::ShieldClient(), QtAws::SimpleDB::SimpleDBClient::SimpleDBClient(), QtAws::SMS::SmsClient::SmsClient(), QtAws::Snowball::SnowballClient::SnowballClient(), QtAws::SNS::SnsClient::SnsClient(), QtAws::SQS::SqsClient::SqsClient(), QtAws::SSM::SsmClient::SsmClient(), QtAws::StorageGateway::StorageGatewayClient::StorageGatewayClient(), QtAws::STS::StsClient::StsClient(), QtAws::Support::SupportClient::SupportClient(), QtAws::SWF::SwfClient::SwfClient(), QtAws::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), QtAws::Translate::TranslateClient::TranslateClient(), QtAws::WAF::WafClient::WafClient(), QtAws::WAFRegional::WAFRegionalClient::WAFRegionalClient(), QtAws::WorkDocs::WorkDocsClient::WorkDocsClient(), QtAws::WorkMail::WorkMailClient::WorkMailClient(), QtAws::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and QtAws::XRay::XRayClient::XRayClient().
 {
     Q_D(const AwsAbstractClient);
     return d->region;
 }
send()
AwsAbstractResponse * AwsAbstractClient::send (const AwsAbstractRequest & request) virtual
Send an AWS request.
This base implementation simply uses the request's send method, supplying the necessary resources (ie the credentials, network access manager, and signature object) from this object as required.
Derived classes would not normally need to override this method.
Parameters
request The AWS request to send.
Returns
An object representing the AWS service's response.
Definition at line 175 of file awsabstractclient.cpp.
References endpoint(), QtAws::Core::AwsAbstractRequest::isValid(), QtAws::Core::AwsAbstractRequest::send(), and serviceName().
Referenced by QtAws::WorkDocs::WorkDocsClient::abortDocumentVersionUpload(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::abortEnvironmentUpdate(), QtAws::Glacier::GlacierClient::abortMultipartUpload(), QtAws::S3::S3Client::abortMultipartUpload(), QtAws::Glacier::GlacierClient::abortVaultLock(), QtAws::IoT::IoTClient::acceptCertificateTransfer(), QtAws::Organizations::OrganizationsClient::acceptHandshake(), QtAws::GuardDuty::GuardDutyClient::acceptInvitation(), QtAws::GameLift::GameLiftClient::acceptMatch(), QtAws::ServiceCatalog::ServiceCatalogClient::acceptPortfolioShare(), QtAws::MTurk::MTurkClient::acceptQualificationRequest(), QtAws::EC2::Ec2Client::acceptReservedInstancesExchangeQuote(), QtAws::EC2::Ec2Client::acceptVpcEndpointConnections(), QtAws::EC2::Ec2Client::acceptVpcPeeringConnection(), QtAws::CodePipeline::CodePipelineClient::acknowledgeJob(), QtAws::CodePipeline::CodePipelineClient::acknowledgeThirdPartyJob(), QtAws::StorageGateway::StorageGatewayClient::activateGateway(), QtAws::DataPipeline::DataPipelineClient::activatePipeline(), QtAws::WorkDocs::WorkDocsClient::activateUser(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationCloudWatchLoggingOption(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationInput(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationInputProcessingConfiguration(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationOutput(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::addApplicationReferenceDataSource(), QtAws::Support::SupportClient::addAttachmentsToSet(), QtAws::Inspector::InspectorClient::addAttributesToFindings(), QtAws::StorageGateway::StorageGatewayClient::addCache(), QtAws::IAM::IamClient::addClientIDToOpenIDConnectProvider(), QtAws::Support::SupportClient::addCommunicationToCase(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::addCustomAttributes(), QtAws::CloudDirectory::CloudDirectoryClient::addFacetToObject(), QtAws::EMR::EmrClient::addInstanceFleet(), QtAws::EMR::EmrClient::addInstanceGroups(), QtAws::DirectoryService::DirectoryServiceClient::addIpRoutes(), QtAws::EMR::EmrClient::addJobFlowSteps(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::addListenerCertificates(), QtAws::SQS::SqsClient::addPermission(), QtAws::Lambda::LambdaClient::addPermission(), QtAws::SNS::SnsClient::addPermission(), QtAws::WorkDocs::WorkDocsClient::addResourcePermissions(), QtAws::RDS::RdsClient::addRoleToDBCluster(), QtAws::IAM::IamClient::addRoleToInstanceProfile(), QtAws::RDS::RdsClient::addSourceIdentifierToSubscription(), QtAws::ElasticsearchService::ElasticsearchServiceClient::addTags(), QtAws::CloudTrail::CloudTrailClient::addTags(), QtAws::DataPipeline::DataPipelineClient::addTags(), QtAws::MachineLearning::MachineLearningClient::addTags(), QtAws::EMR::EmrClient::addTags(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::addTags(), QtAws::SageMaker::SageMakerClient::addTags(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::addTags(), QtAws::ACM::AcmClient::addTagsToCertificate(), QtAws::CodeDeploy::CodeDeployClient::addTagsToOnPremisesInstances(), QtAws::CloudHSM::CloudHSMClient::addTagsToResource(), QtAws::ElastiCache::ElastiCacheClient::addTagsToResource(), QtAws::DirectoryService::DirectoryServiceClient::addTagsToResource(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::addTagsToResource(), QtAws::StorageGateway::StorageGatewayClient::addTagsToResource(), QtAws::RDS::RdsClient::addTagsToResource(), QtAws::SSM::SsmClient::addTagsToResource(), QtAws::Kinesis::KinesisClient::addTagsToStream(), QtAws::Glacier::GlacierClient::addTagsToVault(), QtAws::IoT::IoTClient::addThingToThingGroup(), QtAws::StorageGateway::StorageGatewayClient::addUploadBuffer(), QtAws::IAM::IamClient::addUserToGroup(), QtAws::StorageGateway::StorageGatewayClient::addWorkingStorage(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminAddUserToGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminConfirmSignUp(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminCreateUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDeleteUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDeleteUserAttributes(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDisableProviderForUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminDisableUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminEnableUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminForgetDevice(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminGetDevice(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminGetUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminInitiateAuth(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminLinkProviderForUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListDevices(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListGroupsForUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminListUserAuthEvents(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminRemoveUserFromGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminResetUserPassword(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminRespondToAuthChallenge(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminSetUserMFAPreference(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminSetUserSettings(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateAuthEventFeedback(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateDeviceStatus(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUpdateUserAttributes(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::adminUserGlobalSignOut(), QtAws::EC2::Ec2Client::allocateAddress(), QtAws::DirectConnect::DirectConnectClient::allocateConnectionOnInterconnect(), QtAws::DirectConnect::DirectConnectClient::allocateHostedConnection(), QtAws::EC2::Ec2Client::allocateHosts(), QtAws::DirectConnect::DirectConnectClient::allocatePrivateVirtualInterface(), QtAws::DirectConnect::DirectConnectClient::allocatePublicVirtualInterface(), QtAws::Lightsail::LightsailClient::allocateStaticIp(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::applyEnvironmentManagedAction(), QtAws::RDS::RdsClient::applyPendingMaintenanceAction(), QtAws::CloudDirectory::CloudDirectoryClient::applySchema(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::applySecurityGroupsToLoadBalancer(), QtAws::MTurk::MTurkClient::approveAssignment(), QtAws::GuardDuty::GuardDutyClient::archiveFindings(), QtAws::OpsWorks::OpsWorksClient::assignInstance(), QtAws::EC2::Ec2Client::assignIpv6Addresses(), QtAws::EC2::Ec2Client::assignPrivateIpAddresses(), QtAws::OpsWorks::OpsWorksClient::assignVolume(), QtAws::EC2::Ec2Client::associateAddress(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::associateConfigurationItemsToApplication(), QtAws::DirectConnect::DirectConnectClient::associateConnectionWithLag(), QtAws::MigrationHub::MigrationHubClient::associateCreatedArtifact(), QtAws::WorkMail::WorkMailClient::associateDelegateToResource(), QtAws::AlexaForBusiness::AlexaForBusinessClient::associateDeviceWithRoom(), QtAws::EC2::Ec2Client::associateDhcpOptions(), QtAws::MigrationHub::MigrationHubClient::associateDiscoveredResource(), QtAws::OpsWorks::OpsWorksClient::associateElasticIp(), QtAws::AppStream::AppStreamClient::associateFleet(), QtAws::DirectConnect::DirectConnectClient::associateHostedConnection(), QtAws::EC2::Ec2Client::associateIamInstanceProfile(), QtAws::CloudWatchLogs::CloudWatchLogsClient::associateKmsKey(), QtAws::WorkMail::WorkMailClient::associateMemberToGroup(), QtAws::OpsWorksCM::OpsWorksCMClient::associateNode(), QtAws::ServiceCatalog::ServiceCatalogClient::associatePrincipalWithPortfolio(), QtAws::ServiceCatalog::ServiceCatalogClient::associateProductWithPortfolio(), QtAws::MTurk::MTurkClient::associateQualificationWithWorker(), QtAws::Greengrass::GreengrassClient::associateRoleToGroup(), QtAws::EC2::Ec2Client::associateRouteTable(), QtAws::Greengrass::GreengrassClient::associateServiceRoleToAccount(), QtAws::AlexaForBusiness::AlexaForBusinessClient::associateSkillGroupWithRoom(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::associateSoftwareToken(), QtAws::EC2::Ec2Client::associateSubnetCidrBlock(), QtAws::ServiceCatalog::ServiceCatalogClient::associateTagOptionWithResource(), QtAws::IoT::IoTClient::associateTargetsWithJob(), QtAws::CodeStar::CodeStarClient::associateTeamMember(), QtAws::DirectConnect::DirectConnectClient::associateVirtualInterface(), QtAws::EC2::Ec2Client::associateVpcCidrBlock(), QtAws::Route53::Route53Client::associateVPCWithHostedZone(), QtAws::WAFRegional::WAFRegionalClient::associateWebACL(), QtAws::STS::StsClient::assumeRole(), QtAws::STS::StsClient::assumeRoleWithSAML(), QtAws::STS::StsClient::assumeRoleWithWebIdentity(), QtAws::EC2::Ec2Client::attachClassicLinkVpc(), QtAws::Lightsail::LightsailClient::attachDisk(), QtAws::OpsWorks::OpsWorksClient::attachElasticLoadBalancer(), QtAws::IAM::IamClient::attachGroupPolicy(), QtAws::AutoScaling::AutoScalingClient::attachInstances(), QtAws::Lightsail::LightsailClient::attachInstancesToLoadBalancer(), QtAws::EC2::Ec2Client::attachInternetGateway(), QtAws::AutoScaling::AutoScalingClient::attachLoadBalancers(), QtAws::AutoScaling::AutoScalingClient::attachLoadBalancerTargetGroups(), QtAws::Lightsail::LightsailClient::attachLoadBalancerTlsCertificate(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::attachLoadBalancerToSubnets(), QtAws::EC2::Ec2Client::attachNetworkInterface(), QtAws::CloudDirectory::CloudDirectoryClient::attachObject(), QtAws::Organizations::OrganizationsClient::attachPolicy(), QtAws::CloudDirectory::CloudDirectoryClient::attachPolicy(), QtAws::IoT::IoTClient::attachPolicy(), QtAws::IoT::IoTClient::attachPrincipalPolicy(), QtAws::IAM::IamClient::attachRolePolicy(), QtAws::Lightsail::LightsailClient::attachStaticIp(), QtAws::IoT::IoTClient::attachThingPrincipal(), QtAws::CloudDirectory::CloudDirectoryClient::attachToIndex(), QtAws::CloudDirectory::CloudDirectoryClient::attachTypedLink(), QtAws::IAM::IamClient::attachUserPolicy(), QtAws::EC2::Ec2Client::attachVolume(), QtAws::EC2::Ec2Client::attachVpnGateway(), QtAws::ElastiCache::ElastiCacheClient::authorizeCacheSecurityGroupIngress(), QtAws::Redshift::RedshiftClient::authorizeClusterSecurityGroupIngress(), QtAws::RDS::RdsClient::authorizeDBSecurityGroupIngress(), QtAws::EC2::Ec2Client::authorizeSecurityGroupEgress(), QtAws::EC2::Ec2Client::authorizeSecurityGroupIngress(), QtAws::Redshift::RedshiftClient::authorizeSnapshotAccess(), QtAws::ECR::EcrClient::batchCheckLayerAvailability(), QtAws::Glue::GlueClient::batchCreatePartition(), QtAws::SimpleDB::SimpleDBClient::batchDeleteAttributes(), QtAws::CodeBuild::CodeBuildClient::batchDeleteBuilds(), QtAws::Glue::GlueClient::batchDeleteConnection(), QtAws::ECR::EcrClient::batchDeleteImage(), QtAws::Glue::GlueClient::batchDeletePartition(), QtAws::Glue::GlueClient::batchDeleteTable(), QtAws::Glue::GlueClient::batchDeleteTableVersion(), QtAws::Comprehend::ComprehendClient::batchDetectDominantLanguage(), QtAws::Comprehend::ComprehendClient::batchDetectEntities(), QtAws::Comprehend::ComprehendClient::batchDetectKeyPhrases(), QtAws::Comprehend::ComprehendClient::batchDetectSentiment(), QtAws::CodeDeploy::CodeDeployClient::batchGetApplicationRevisions(), QtAws::CodeDeploy::CodeDeployClient::batchGetApplications(), QtAws::CodeBuild::CodeBuildClient::batchGetBuilds(), QtAws::CodeDeploy::CodeDeployClient::batchGetDeploymentGroups(), QtAws::CodeDeploy::CodeDeployClient::batchGetDeploymentInstances(), QtAws::CodeDeploy::CodeDeployClient::batchGetDeployments(), QtAws::ECR::EcrClient::batchGetImage(), QtAws::DynamoDB::DynamoDBClient::batchGetItem(), QtAws::Athena::AthenaClient::batchGetNamedQuery(), QtAws::CodeDeploy::CodeDeployClient::batchGetOnPremisesInstances(), QtAws::Glue::GlueClient::batchGetPartition(), QtAws::CodeBuild::CodeBuildClient::batchGetProjects(), QtAws::Athena::AthenaClient::batchGetQueryExecution(), QtAws::CodeCommit::CodeCommitClient::batchGetRepositories(), QtAws::ConfigService::ConfigServiceClient::batchGetResourceConfig(), QtAws::XRay::XRayClient::batchGetTraces(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::batchMeterUsage(), QtAws::SimpleDB::SimpleDBClient::batchPutAttributes(), QtAws::CloudDirectory::CloudDirectoryClient::batchRead(), QtAws::Glue::GlueClient::batchStopJobRun(), QtAws::CloudDirectory::CloudDirectoryClient::batchWrite(), QtAws::DynamoDB::DynamoDBClient::batchWriteItem(), QtAws::CloudSearch::CloudSearchClient::buildSuggesters(), QtAws::CognitoSync::CognitoSyncClient::bulkPublish(), QtAws::EC2::Ec2Client::bundleInstance(), QtAws::StorageGateway::StorageGatewayClient::cancelArchival(), QtAws::EC2::Ec2Client::cancelBundleTask(), QtAws::IoT::IoTClient::cancelCertificateTransfer(), QtAws::Snowball::SnowballClient::cancelCluster(), QtAws::SSM::SsmClient::cancelCommand(), QtAws::EC2::Ec2Client::cancelConversionTask(), QtAws::CloudWatchLogs::CloudWatchLogsClient::cancelExportTask(), QtAws::EC2::Ec2Client::cancelExportTask(), QtAws::Organizations::OrganizationsClient::cancelHandshake(), QtAws::EC2::Ec2Client::cancelImportTask(), QtAws::ImportExport::ImportExportClient::cancelJob(), QtAws::Batch::BatchClient::cancelJob(), QtAws::ElasticTranscoder::ElasticTranscoderClient::cancelJob(), QtAws::Snowball::SnowballClient::cancelJob(), QtAws::MediaConvert::MediaConvertClient::cancelJob(), QtAws::IoT::IoTClient::cancelJob(), QtAws::KMS::KmsClient::cancelKeyDeletion(), QtAws::EC2::Ec2Client::cancelReservedInstancesListing(), QtAws::StorageGateway::StorageGatewayClient::cancelRetrieval(), QtAws::DirectoryService::DirectoryServiceClient::cancelSchemaExtension(), QtAws::EC2::Ec2Client::cancelSpotFleetRequests(), QtAws::EC2::Ec2Client::cancelSpotInstanceRequests(), QtAws::EMR::EmrClient::cancelSteps(), QtAws::CloudFormation::CloudFormationClient::cancelUpdateStack(), QtAws::SQS::SqsClient::changeMessageVisibility(), QtAws::SQS::SqsClient::changeMessageVisibilityBatch(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::changePassword(), QtAws::IAM::IamClient::changePassword(), QtAws::Route53::Route53Client::changeResourceRecordSets(), QtAws::Route53::Route53Client::changeTagsForResource(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::checkDNSAvailability(), QtAws::Route53Domains::Route53DomainsClient::checkDomainAvailability(), QtAws::Route53Domains::Route53DomainsClient::checkDomainTransferability(), QtAws::SNS::SnsClient::checkIfPhoneNumberIsOptedOut(), QtAws::IoT::IoTClient::clearDefaultAuthorizer(), QtAws::SES::SesClient::cloneReceiptRuleSet(), QtAws::OpsWorks::OpsWorksClient::cloneStack(), QtAws::Lightsail::LightsailClient::closeInstancePublicPorts(), QtAws::Rekognition::RekognitionClient::compareFaces(), QtAws::ECR::EcrClient::completeLayerUpload(), QtAws::AutoScaling::AutoScalingClient::completeLifecycleAction(), QtAws::Glacier::GlacierClient::completeMultipartUpload(), QtAws::S3::S3Client::completeMultipartUpload(), QtAws::Glacier::GlacierClient::completeVaultLock(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::composeEnvironments(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::configureHealthCheck(), QtAws::DirectConnect::DirectConnectClient::confirmConnection(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmDevice(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmForgotPassword(), QtAws::DirectConnect::DirectConnectClient::confirmPrivateVirtualInterface(), QtAws::EC2::Ec2Client::confirmProductInstance(), QtAws::DirectConnect::DirectConnectClient::confirmPublicVirtualInterface(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::confirmSignUp(), QtAws::SNS::SnsClient::confirmSubscription(), QtAws::DirectoryService::DirectoryServiceClient::connectDirectory(), QtAws::CodeDeploy::CodeDeployClient::continueDeployment(), QtAws::CloudFormation::CloudFormationClient::continueUpdateRollback(), QtAws::Redshift::RedshiftClient::copyClusterSnapshot(), QtAws::RDS::RdsClient::copyDBClusterParameterGroup(), QtAws::RDS::RdsClient::copyDBClusterSnapshot(), QtAws::RDS::RdsClient::copyDBParameterGroup(), QtAws::RDS::RdsClient::copyDBSnapshot(), QtAws::EC2::Ec2Client::copyFpgaImage(), QtAws::AppStream::AppStreamClient::copyImage(), QtAws::EC2::Ec2Client::copyImage(), QtAws::S3::S3Client::copyObject(), QtAws::RDS::RdsClient::copyOptionGroup(), QtAws::ServiceCatalog::ServiceCatalogClient::copyProduct(), QtAws::ElastiCache::ElastiCacheClient::copySnapshot(), QtAws::EC2::Ec2Client::copySnapshot(), QtAws::SWF::SwfClient::countClosedWorkflowExecutions(), QtAws::SWF::SwfClient::countOpenWorkflowExecutions(), QtAws::SWF::SwfClient::countPendingActivityTasks(), QtAws::SWF::SwfClient::countPendingDecisionTasks(), QtAws::IAM::IamClient::createAccessKey(), QtAws::Organizations::OrganizationsClient::createAccount(), QtAws::IAM::IamClient::createAccountAlias(), QtAws::SSM::SsmClient::createActivation(), QtAws::SFN::SfnClient::createActivity(), QtAws::MTurk::MTurkClient::createAdditionalAssignmentsForHIT(), QtAws::Snowball::SnowballClient::createAddress(), QtAws::WorkMail::WorkMailClient::createAlias(), QtAws::Lambda::LambdaClient::createAlias(), QtAws::KMS::KmsClient::createAlias(), QtAws::DirectoryService::DirectoryServiceClient::createAlias(), QtAws::GameLift::GameLiftClient::createAlias(), QtAws::AppSync::AppSyncClient::createApiKey(), QtAws::APIGateway::APIGatewayClient::createApiKey(), QtAws::Pinpoint::PinpointClient::createApp(), QtAws::OpsWorks::OpsWorksClient::createApp(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createAppCookieStickinessPolicy(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createApplication(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::createApplication(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::createApplication(), QtAws::CodeDeploy::CodeDeployClient::createApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createApplication(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createApplicationVersion(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createApplicationVersion(), QtAws::Inspector::InspectorClient::createAssessmentTarget(), QtAws::Inspector::InspectorClient::createAssessmentTemplate(), QtAws::SSM::SsmClient::createAssociation(), QtAws::SSM::SsmClient::createAssociationBatch(), QtAws::APIGateway::APIGatewayClient::createAuthorizer(), QtAws::IoT::IoTClient::createAuthorizer(), QtAws::AutoScaling::AutoScalingClient::createAutoScalingGroup(), QtAws::OpsWorksCM::OpsWorksCMClient::createBackup(), QtAws::DynamoDB::DynamoDBClient::createBackup(), QtAws::APIGateway::APIGatewayClient::createBasePathMapping(), QtAws::MachineLearning::MachineLearningClient::createBatchPrediction(), QtAws::DirectConnect::DirectConnectClient::createBGPPeer(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createBotVersion(), QtAws::CodeCommit::CodeCommitClient::createBranch(), QtAws::MQ::MqClient::createBroker(), QtAws::S3::S3Client::createBucket(), QtAws::Budgets::BudgetsClient::createBudget(), QtAws::GameLift::GameLiftClient::createBuild(), QtAws::WAF::WafClient::createByteMatchSet(), QtAws::WAFRegional::WAFRegionalClient::createByteMatchSet(), QtAws::ElastiCache::ElastiCacheClient::createCacheCluster(), QtAws::StorageGateway::StorageGatewayClient::createCachediSCSIVolume(), QtAws::ElastiCache::ElastiCacheClient::createCacheParameterGroup(), QtAws::ElastiCache::ElastiCacheClient::createCacheSecurityGroup(), QtAws::ElastiCache::ElastiCacheClient::createCacheSubnetGroup(), QtAws::Pinpoint::PinpointClient::createCampaign(), QtAws::Support::SupportClient::createCase(), QtAws::IoT::IoTClient::createCertificateFromCsr(), QtAws::CloudFormation::CloudFormationClient::createChangeSet(), QtAws::MediaPackage::MediaPackageClient::createChannel(), QtAws::MediaLive::MediaLiveClient::createChannel(), QtAws::Glue::GlueClient::createClassifier(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::createCloudFormationChangeSet(), QtAws::CloudFront::CloudFrontClient::createCloudFrontOriginAccessIdentity(), QtAws::CloudHSMV2::CloudHSMV2Client::createCluster(), QtAws::Snowball::SnowballClient::createCluster(), QtAws::DAX::DaxClient::createCluster(), QtAws::ECS::EcsClient::createCluster(), QtAws::Redshift::RedshiftClient::createCluster(), QtAws::Redshift::RedshiftClient::createClusterParameterGroup(), QtAws::Redshift::RedshiftClient::createClusterSecurityGroup(), QtAws::Redshift::RedshiftClient::createClusterSnapshot(), QtAws::Redshift::RedshiftClient::createClusterSubnetGroup(), QtAws::Rekognition::RekognitionClient::createCollection(), QtAws::WorkDocs::WorkDocsClient::createComment(), QtAws::Batch::BatchClient::createComputeEnvironment(), QtAws::DirectoryService::DirectoryServiceClient::createComputer(), QtAws::DirectoryService::DirectoryServiceClient::createConditionalForwarder(), QtAws::MQ::MqClient::createConfiguration(), QtAws::SES::SesClient::createConfigurationSet(), QtAws::SES::SesClient::createConfigurationSetEventDestination(), QtAws::SES::SesClient::createConfigurationSetTrackingOptions(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createConfigurationTemplate(), QtAws::DirectConnect::DirectConnectClient::createConnection(), QtAws::Glue::GlueClient::createConnection(), QtAws::ServiceCatalog::ServiceCatalogClient::createConstraint(), QtAws::MediaStore::MediaStoreClient::createContainer(), QtAws::Greengrass::GreengrassClient::createCoreDefinition(), QtAws::Greengrass::GreengrassClient::createCoreDefinitionVersion(), QtAws::Glue::GlueClient::createCrawler(), QtAws::CodePipeline::CodePipelineClient::createCustomActionType(), QtAws::EC2::Ec2Client::createCustomerGateway(), QtAws::WorkDocs::WorkDocsClient::createCustomMetadata(), QtAws::SES::SesClient::createCustomVerificationEmailTemplate(), QtAws::Glue::GlueClient::createDatabase(), QtAws::AppSync::AppSyncClient::createDataSource(), QtAws::MachineLearning::MachineLearningClient::createDataSourceFromRDS(), QtAws::MachineLearning::MachineLearningClient::createDataSourceFromRedshift(), QtAws::MachineLearning::MachineLearningClient::createDataSourceFromS3(), QtAws::RDS::RdsClient::createDBCluster(), QtAws::RDS::RdsClient::createDBClusterParameterGroup(), QtAws::RDS::RdsClient::createDBClusterSnapshot(), QtAws::RDS::RdsClient::createDBInstance(), QtAws::RDS::RdsClient::createDBInstanceReadReplica(), QtAws::RDS::RdsClient::createDBParameterGroup(), QtAws::RDS::RdsClient::createDBSecurityGroup(), QtAws::RDS::RdsClient::createDBSnapshot(), QtAws::RDS::RdsClient::createDBSubnetGroup(), QtAws::EC2::Ec2Client::createDefaultSubnet(), QtAws::EC2::Ec2Client::createDefaultVpc(), QtAws::Firehose::FirehoseClient::createDeliveryStream(), QtAws::CodeDeploy::CodeDeployClient::createDeployment(), QtAws::OpsWorks::OpsWorksClient::createDeployment(), QtAws::Greengrass::GreengrassClient::createDeployment(), QtAws::APIGateway::APIGatewayClient::createDeployment(), QtAws::CodeDeploy::CodeDeployClient::createDeploymentConfig(), QtAws::CodeDeploy::CodeDeployClient::createDeploymentGroup(), QtAws::GuardDuty::GuardDutyClient::createDetector(), QtAws::Glue::GlueClient::createDevEndpoint(), QtAws::Greengrass::GreengrassClient::createDeviceDefinition(), QtAws::Greengrass::GreengrassClient::createDeviceDefinitionVersion(), QtAws::DeviceFarm::DeviceFarmClient::createDevicePool(), QtAws::EC2::Ec2Client::createDhcpOptions(), QtAws::DirectConnect::DirectConnectClient::createDirectConnectGateway(), QtAws::DirectConnect::DirectConnectClient::createDirectConnectGatewayAssociation(), QtAws::DirectoryService::DirectoryServiceClient::createDirectory(), QtAws::CloudDirectory::CloudDirectoryClient::createDirectory(), QtAws::AppStream::AppStreamClient::createDirectoryConfig(), QtAws::Lightsail::LightsailClient::createDisk(), QtAws::Lightsail::LightsailClient::createDiskFromSnapshot(), QtAws::Lightsail::LightsailClient::createDiskSnapshot(), QtAws::CloudFront::CloudFrontClient::createDistribution(), QtAws::CloudFront::CloudFrontClient::createDistributionWithTags(), QtAws::SSM::SsmClient::createDocument(), QtAws::APIGateway::APIGatewayClient::createDocumentationPart(), QtAws::APIGateway::APIGatewayClient::createDocumentationVersion(), QtAws::SimpleDB::SimpleDBClient::createDomain(), QtAws::CloudSearch::CloudSearchClient::createDomain(), QtAws::Lightsail::LightsailClient::createDomain(), QtAws::Lightsail::LightsailClient::createDomainEntry(), QtAws::APIGateway::APIGatewayClient::createDomainName(), QtAws::EC2::Ec2Client::createEgressOnlyInternetGateway(), QtAws::ElasticsearchService::ElasticsearchServiceClient::createElasticsearchDomain(), QtAws::SageMaker::SageMakerClient::createEndpoint(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createEndpoint(), QtAws::SageMaker::SageMakerClient::createEndpointConfig(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createEnvironment(), QtAws::Cloud9::Cloud9Client::createEnvironmentEC2(), QtAws::Cloud9::Cloud9Client::createEnvironmentMembership(), QtAws::MachineLearning::MachineLearningClient::createEvaluation(), QtAws::Lambda::LambdaClient::createEventSourceMapping(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createEventSubscription(), QtAws::Redshift::RedshiftClient::createEventSubscription(), QtAws::RDS::RdsClient::createEventSubscription(), QtAws::Pinpoint::PinpointClient::createExportJob(), QtAws::CloudWatchLogs::CloudWatchLogsClient::createExportTask(), QtAws::CloudDirectory::CloudDirectoryClient::createFacet(), QtAws::EFS::EfsClient::createFileSystem(), QtAws::AppStream::AppStreamClient::createFleet(), QtAws::GameLift::GameLiftClient::createFleet(), QtAws::EC2::Ec2Client::createFlowLogs(), QtAws::WorkDocs::WorkDocsClient::createFolder(), QtAws::EC2::Ec2Client::createFpgaImage(), QtAws::Lambda::LambdaClient::createFunction(), QtAws::Greengrass::GreengrassClient::createFunctionDefinition(), QtAws::Greengrass::GreengrassClient::createFunctionDefinitionVersion(), QtAws::GameLift::GameLiftClient::createGameSession(), QtAws::GameLift::GameLiftClient::createGameSessionQueue(), QtAws::WAF::WafClient::createGeoMatchSet(), QtAws::WAFRegional::WAFRegionalClient::createGeoMatchSet(), QtAws::DynamoDB::DynamoDBClient::createGlobalTable(), QtAws::KMS::KmsClient::createGrant(), QtAws::AppSync::AppSyncClient::createGraphqlApi(), QtAws::ResourceGroups::ResourceGroupsClient::createGroup(), QtAws::WorkMail::WorkMailClient::createGroup(), QtAws::Greengrass::GreengrassClient::createGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createGroup(), QtAws::IAM::IamClient::createGroup(), QtAws::Greengrass::GreengrassClient::createGroupCertificateAuthority(), QtAws::Greengrass::GreengrassClient::createGroupVersion(), QtAws::CloudHSM::CloudHSMClient::createHapg(), QtAws::Route53::Route53Client::createHealthCheck(), QtAws::MTurk::MTurkClient::createHIT(), QtAws::MTurk::MTurkClient::createHITType(), QtAws::MTurk::MTurkClient::createHITWithHITType(), QtAws::Route53::Route53Client::createHostedZone(), QtAws::CloudHSMV2::CloudHSMV2Client::createHsm(), QtAws::CloudHSM::CloudHSMClient::createHsm(), QtAws::Redshift::RedshiftClient::createHsmClientCertificate(), QtAws::Redshift::RedshiftClient::createHsmConfiguration(), QtAws::CognitoIdentity::CognitoIdentityClient::createIdentityPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createIdentityProvider(), QtAws::EC2::Ec2Client::createImage(), QtAws::AppStream::AppStreamClient::createImageBuilder(), QtAws::AppStream::AppStreamClient::createImageBuilderStreamingURL(), QtAws::Pinpoint::PinpointClient::createImportJob(), QtAws::CloudDirectory::CloudDirectoryClient::createIndex(), QtAws::MediaLive::MediaLiveClient::createInput(), QtAws::MediaLive::MediaLiveClient::createInputSecurityGroup(), QtAws::OpsWorks::OpsWorksClient::createInstance(), QtAws::EC2::Ec2Client::createInstanceExportTask(), QtAws::IAM::IamClient::createInstanceProfile(), QtAws::Lightsail::LightsailClient::createInstances(), QtAws::Lightsail::LightsailClient::createInstancesFromSnapshot(), QtAws::Lightsail::LightsailClient::createInstanceSnapshot(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createIntentVersion(), QtAws::DirectConnect::DirectConnectClient::createInterconnect(), QtAws::EC2::Ec2Client::createInternetGateway(), QtAws::CloudFront::CloudFrontClient::createInvalidation(), QtAws::GuardDuty::GuardDutyClient::createIPSet(), QtAws::WAF::WafClient::createIPSet(), QtAws::WAFRegional::WAFRegionalClient::createIPSet(), QtAws::ImportExport::ImportExportClient::createJob(), QtAws::ElasticTranscoder::ElasticTranscoderClient::createJob(), QtAws::Snowball::SnowballClient::createJob(), QtAws::MediaConvert::MediaConvertClient::createJob(), QtAws::Glue::GlueClient::createJob(), QtAws::IoT::IoTClient::createJob(), QtAws::Batch::BatchClient::createJobQueue(), QtAws::MediaConvert::MediaConvertClient::createJobTemplate(), QtAws::KMS::KmsClient::createKey(), QtAws::Lightsail::LightsailClient::createKeyPair(), QtAws::EC2::Ec2Client::createKeyPair(), QtAws::IoT::IoTClient::createKeysAndCertificate(), QtAws::WorkDocs::WorkDocsClient::createLabels(), QtAws::DirectConnect::DirectConnectClient::createLag(), QtAws::AutoScaling::AutoScalingClient::createLaunchConfiguration(), QtAws::EC2::Ec2Client::createLaunchTemplate(), QtAws::EC2::Ec2Client::createLaunchTemplateVersion(), QtAws::OpsWorks::OpsWorksClient::createLayer(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLBCookieStickinessPolicy(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createListener(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancer(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createLoadBalancer(), QtAws::Lightsail::LightsailClient::createLoadBalancer(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancerListeners(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::createLoadBalancerPolicy(), QtAws::Lightsail::LightsailClient::createLoadBalancerTlsCertificate(), QtAws::Greengrass::GreengrassClient::createLoggerDefinition(), QtAws::Greengrass::GreengrassClient::createLoggerDefinitionVersion(), QtAws::CloudWatchLogs::CloudWatchLogsClient::createLogGroup(), QtAws::IAM::IamClient::createLoginProfile(), QtAws::CloudWatchLogs::CloudWatchLogsClient::createLogStream(), QtAws::CloudHSM::CloudHSMClient::createLunaClient(), QtAws::SSM::SsmClient::createMaintenanceWindow(), QtAws::GameLift::GameLiftClient::createMatchmakingConfiguration(), QtAws::GameLift::GameLiftClient::createMatchmakingRuleSet(), QtAws::GuardDuty::GuardDutyClient::createMembers(), QtAws::DirectoryService::DirectoryServiceClient::createMicrosoftAD(), QtAws::MachineLearning::MachineLearningClient::createMLModel(), QtAws::SageMaker::SageMakerClient::createModel(), QtAws::APIGateway::APIGatewayClient::createModel(), QtAws::EFS::EfsClient::createMountTarget(), QtAws::S3::S3Client::createMultipartUpload(), QtAws::Athena::AthenaClient::createNamedQuery(), QtAws::EC2::Ec2Client::createNatGateway(), QtAws::EC2::Ec2Client::createNetworkAcl(), QtAws::EC2::Ec2Client::createNetworkAclEntry(), QtAws::EC2::Ec2Client::createNetworkInterface(), QtAws::EC2::Ec2Client::createNetworkInterfacePermission(), QtAws::DeviceFarm::DeviceFarmClient::createNetworkProfile(), QtAws::StorageGateway::StorageGatewayClient::createNFSFileShare(), QtAws::SageMaker::SageMakerClient::createNotebookInstance(), QtAws::SageMaker::SageMakerClient::createNotebookInstanceLifecycleConfig(), QtAws::Budgets::BudgetsClient::createNotification(), QtAws::WorkDocs::WorkDocsClient::createNotificationSubscription(), QtAws::CloudDirectory::CloudDirectoryClient::createObject(), QtAws::IAM::IamClient::createOpenIDConnectProvider(), QtAws::RDS::RdsClient::createOptionGroup(), QtAws::Organizations::OrganizationsClient::createOrganization(), QtAws::Organizations::OrganizationsClient::createOrganizationalUnit(), QtAws::MediaPackage::MediaPackageClient::createOriginEndpoint(), QtAws::AutoScaling::AutoScalingClient::createOrUpdateTags(), QtAws::IoT::IoTClient::createOTAUpdate(), QtAws::DAX::DaxClient::createParameterGroup(), QtAws::Glue::GlueClient::createPartition(), QtAws::SSM::SsmClient::createPatchBaseline(), QtAws::ElasticTranscoder::ElasticTranscoderClient::createPipeline(), QtAws::DataPipeline::DataPipelineClient::createPipeline(), QtAws::CodePipeline::CodePipelineClient::createPipeline(), QtAws::EC2::Ec2Client::createPlacementGroup(), QtAws::SNS::SnsClient::createPlatformApplication(), QtAws::SNS::SnsClient::createPlatformEndpoint(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createPlatformVersion(), QtAws::GameLift::GameLiftClient::createPlayerSession(), QtAws::GameLift::GameLiftClient::createPlayerSessions(), QtAws::Organizations::OrganizationsClient::createPolicy(), QtAws::IAM::IamClient::createPolicy(), QtAws::IoT::IoTClient::createPolicy(), QtAws::IAM::IamClient::createPolicyVersion(), QtAws::IoT::IoTClient::createPolicyVersion(), QtAws::ServiceCatalog::ServiceCatalogClient::createPortfolio(), QtAws::ServiceCatalog::ServiceCatalogClient::createPortfolioShare(), QtAws::ElasticTranscoder::ElasticTranscoderClient::createPreset(), QtAws::MediaConvert::MediaConvertClient::createPreset(), QtAws::SageMaker::SageMakerClient::createPresignedNotebookInstanceUrl(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::createPrivateDnsNamespace(), QtAws::DirectConnect::DirectConnectClient::createPrivateVirtualInterface(), QtAws::ServiceCatalog::ServiceCatalogClient::createProduct(), QtAws::AlexaForBusiness::AlexaForBusinessClient::createProfile(), QtAws::MigrationHub::MigrationHubClient::createProgressUpdateStream(), QtAws::Mobile::MobileClient::createProject(), QtAws::CodeBuild::CodeBuildClient::createProject(), QtAws::CodeStar::CodeStarClient::createProject(), QtAws::DeviceFarm::DeviceFarmClient::createProject(), QtAws::Shield::ShieldClient::createProtection(), QtAws::ServiceCatalog::ServiceCatalogClient::createProvisionedProductPlan(), QtAws::ServiceCatalog::ServiceCatalogClient::createProvisioningArtifact(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::createPublicDnsNamespace(), QtAws::DirectConnect::DirectConnectClient::createPublicVirtualInterface(), QtAws::CodeCommit::CodeCommitClient::createPullRequest(), QtAws::MTurk::MTurkClient::createQualificationType(), QtAws::Route53::Route53Client::createQueryLoggingConfig(), QtAws::SQS::SqsClient::createQueue(), QtAws::MediaConvert::MediaConvertClient::createQueue(), QtAws::WAF::WafClient::createRateBasedRule(), QtAws::WAFRegional::WAFRegionalClient::createRateBasedRule(), QtAws::MachineLearning::MachineLearningClient::createRealtimeEndpoint(), QtAws::SES::SesClient::createReceiptFilter(), QtAws::SES::SesClient::createReceiptRule(), QtAws::SES::SesClient::createReceiptRuleSet(), QtAws::WAF::WafClient::createRegexMatchSet(), QtAws::WAFRegional::WAFRegionalClient::createRegexMatchSet(), QtAws::WAF::WafClient::createRegexPatternSet(), QtAws::WAFRegional::WAFRegionalClient::createRegexPatternSet(), QtAws::DeviceFarm::DeviceFarmClient::createRemoteAccessSession(), QtAws::ElastiCache::ElastiCacheClient::createReplicationGroup(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationInstance(), QtAws::SMS::SmsClient::createReplicationJob(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationSubnetGroup(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::createReplicationTask(), QtAws::ECR::EcrClient::createRepository(), QtAws::CodeCommit::CodeCommitClient::createRepository(), QtAws::APIGateway::APIGatewayClient::createRequestValidator(), QtAws::EC2::Ec2Client::createReservedInstancesListing(), QtAws::AppSync::AppSyncClient::createResolver(), QtAws::WorkMail::WorkMailClient::createResource(), QtAws::APIGateway::APIGatewayClient::createResource(), QtAws::SSM::SsmClient::createResourceDataSync(), QtAws::Greengrass::GreengrassClient::createResourceDefinition(), QtAws::Greengrass::GreengrassClient::createResourceDefinitionVersion(), QtAws::Inspector::InspectorClient::createResourceGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createResourceServer(), QtAws::APIGateway::APIGatewayClient::createRestApi(), QtAws::Route53::Route53Client::createReusableDelegationSet(), QtAws::IAM::IamClient::createRole(), QtAws::IoT::IoTClient::createRoleAlias(), QtAws::AlexaForBusiness::AlexaForBusinessClient::createRoom(), QtAws::EC2::Ec2Client::createRoute(), QtAws::EC2::Ec2Client::createRouteTable(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createRule(), QtAws::WAF::WafClient::createRule(), QtAws::WAFRegional::WAFRegionalClient::createRule(), QtAws::WAF::WafClient::createRuleGroup(), QtAws::WAFRegional::WAFRegionalClient::createRuleGroup(), QtAws::IAM::IamClient::createSAMLProvider(), QtAws::GuardDuty::GuardDutyClient::createSampleFindings(), QtAws::AutoScalingPlans::AutoScalingPlansClient::createScalingPlan(), QtAws::CloudDirectory::CloudDirectoryClient::createSchema(), QtAws::Glue::GlueClient::createScript(), QtAws::EMR::EmrClient::createSecurityConfiguration(), QtAws::EC2::Ec2Client::createSecurityGroup(), QtAws::Pinpoint::PinpointClient::createSegment(), QtAws::OpsWorksCM::OpsWorksCMClient::createServer(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::createService(), QtAws::ECS::EcsClient::createService(), QtAws::IAM::IamClient::createServiceLinkedRole(), QtAws::IAM::IamClient::createServiceSpecificCredential(), QtAws::WAF::WafClient::createSizeConstraintSet(), QtAws::WAFRegional::WAFRegionalClient::createSizeConstraintSet(), QtAws::AlexaForBusiness::AlexaForBusinessClient::createSkillGroup(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createSlotTypeVersion(), QtAws::ElastiCache::ElastiCacheClient::createSnapshot(), QtAws::DirectoryService::DirectoryServiceClient::createSnapshot(), QtAws::StorageGateway::StorageGatewayClient::createSnapshot(), QtAws::EC2::Ec2Client::createSnapshot(), QtAws::Redshift::RedshiftClient::createSnapshotCopyGrant(), QtAws::StorageGateway::StorageGatewayClient::createSnapshotFromVolumeRecoveryPoint(), QtAws::Greengrass::GreengrassClient::createSoftwareUpdateJob(), QtAws::EC2::Ec2Client::createSpotDatafeedSubscription(), QtAws::WAF::WafClient::createSqlInjectionMatchSet(), QtAws::WAFRegional::WAFRegionalClient::createSqlInjectionMatchSet(), QtAws::AppStream::AppStreamClient::createStack(), QtAws::CloudFormation::CloudFormationClient::createStack(), QtAws::OpsWorks::OpsWorksClient::createStack(), QtAws::CloudFormation::CloudFormationClient::createStackInstances(), QtAws::CloudFormation::CloudFormationClient::createStackSet(), QtAws::APIGateway::APIGatewayClient::createStage(), QtAws::SFN::SfnClient::createStateMachine(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::createStorageLocation(), QtAws::StorageGateway::StorageGatewayClient::createStorediSCSIVolume(), QtAws::KinesisVideo::KinesisVideoClient::createStream(), QtAws::Kinesis::KinesisClient::createStream(), QtAws::IoT::IoTClient::createStream(), QtAws::CloudFront::CloudFrontClient::createStreamingDistribution(), QtAws::CloudFront::CloudFrontClient::createStreamingDistributionWithTags(), QtAws::AppStream::AppStreamClient::createStreamingURL(), QtAws::Rekognition::RekognitionClient::createStreamProcessor(), QtAws::EC2::Ec2Client::createSubnet(), QtAws::DAX::DaxClient::createSubnetGroup(), QtAws::Budgets::BudgetsClient::createSubscriber(), QtAws::Shield::ShieldClient::createSubscription(), QtAws::Greengrass::GreengrassClient::createSubscriptionDefinition(), QtAws::Greengrass::GreengrassClient::createSubscriptionDefinitionVersion(), QtAws::DynamoDB::DynamoDBClient::createTable(), QtAws::Glue::GlueClient::createTable(), QtAws::ServiceCatalog::ServiceCatalogClient::createTagOption(), QtAws::EFS::EfsClient::createTags(), QtAws::WorkSpaces::WorkSpacesClient::createTags(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::createTags(), QtAws::Redshift::RedshiftClient::createTags(), QtAws::EC2::Ec2Client::createTags(), QtAws::StorageGateway::StorageGatewayClient::createTapes(), QtAws::StorageGateway::StorageGatewayClient::createTapeWithBarcode(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::createTargetGroup(), QtAws::SES::SesClient::createTemplate(), QtAws::IoT::IoTClient::createThing(), QtAws::IoT::IoTClient::createThingGroup(), QtAws::IoT::IoTClient::createThingType(), QtAws::GuardDuty::GuardDutyClient::createThreatIntelSet(), QtAws::SNS::SnsClient::createTopic(), QtAws::IoT::IoTClient::createTopicRule(), QtAws::Route53::Route53Client::createTrafficPolicy(), QtAws::Route53::Route53Client::createTrafficPolicyInstance(), QtAws::Route53::Route53Client::createTrafficPolicyVersion(), QtAws::CloudTrail::CloudTrailClient::createTrail(), QtAws::SageMaker::SageMakerClient::createTrainingJob(), QtAws::Glue::GlueClient::createTrigger(), QtAws::DirectoryService::DirectoryServiceClient::createTrust(), QtAws::AppSync::AppSyncClient::createType(), QtAws::CloudDirectory::CloudDirectoryClient::createTypedLinkFacet(), QtAws::DeviceFarm::DeviceFarmClient::createUpload(), QtAws::APIGateway::APIGatewayClient::createUsagePlan(), QtAws::APIGateway::APIGatewayClient::createUsagePlanKey(), QtAws::MQ::MqClient::createUser(), QtAws::WorkMail::WorkMailClient::createUser(), QtAws::AlexaForBusiness::AlexaForBusinessClient::createUser(), QtAws::WorkDocs::WorkDocsClient::createUser(), QtAws::IAM::IamClient::createUser(), QtAws::Glue::GlueClient::createUserDefinedFunction(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserImportJob(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPoolClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::createUserPoolDomain(), QtAws::CodeStar::CodeStarClient::createUserProfile(), QtAws::OpsWorks::OpsWorksClient::createUserProfile(), QtAws::Glacier::GlacierClient::createVault(), QtAws::IAM::IamClient::createVirtualMFADevice(), QtAws::EC2::Ec2Client::createVolume(), QtAws::EC2::Ec2Client::createVpc(), QtAws::Route53::Route53Client::createVPCAssociationAuthorization(), QtAws::EC2::Ec2Client::createVpcEndpoint(), QtAws::EC2::Ec2Client::createVpcEndpointConnectionNotification(), QtAws::EC2::Ec2Client::createVpcEndpointServiceConfiguration(), QtAws::APIGateway::APIGatewayClient::createVpcLink(), QtAws::GameLift::GameLiftClient::createVpcPeeringAuthorization(), QtAws::GameLift::GameLiftClient::createVpcPeeringConnection(), QtAws::EC2::Ec2Client::createVpcPeeringConnection(), QtAws::EC2::Ec2Client::createVpnConnection(), QtAws::EC2::Ec2Client::createVpnConnectionRoute(), QtAws::EC2::Ec2Client::createVpnGateway(), QtAws::WAF::WafClient::createWebACL(), QtAws::WAFRegional::WAFRegionalClient::createWebACL(), QtAws::CodeBuild::CodeBuildClient::createWebhook(), QtAws::MTurk::MTurkClient::createWorkerBlock(), QtAws::WorkSpaces::WorkSpacesClient::createWorkspaces(), QtAws::WAF::WafClient::createXssMatchSet(), QtAws::WAFRegional::WAFRegionalClient::createXssMatchSet(), QtAws::IAM::IamClient::deactivateMFADevice(), QtAws::DataPipeline::DataPipelineClient::deactivatePipeline(), QtAws::WorkDocs::WorkDocsClient::deactivateUser(), QtAws::Organizations::OrganizationsClient::declineHandshake(), QtAws::GuardDuty::GuardDutyClient::declineInvitations(), QtAws::STS::StsClient::decodeAuthorizationMessage(), QtAws::DAX::DaxClient::decreaseReplicationFactor(), QtAws::Kinesis::KinesisClient::decreaseStreamRetentionPeriod(), QtAws::KMS::KmsClient::decrypt(), QtAws::CloudSearch::CloudSearchClient::defineAnalysisScheme(), QtAws::CloudSearch::CloudSearchClient::defineExpression(), QtAws::CloudSearch::CloudSearchClient::defineIndexField(), QtAws::CloudSearch::CloudSearchClient::defineSuggester(), QtAws::IAM::IamClient::deleteAccessKey(), QtAws::IAM::IamClient::deleteAccountAlias(), QtAws::IAM::IamClient::deleteAccountPasswordPolicy(), QtAws::SSM::SsmClient::deleteActivation(), QtAws::SFN::SfnClient::deleteActivity(), QtAws::Pinpoint::PinpointClient::deleteAdmChannel(), QtAws::CloudWatch::CloudWatchClient::deleteAlarms(), QtAws::WorkMail::WorkMailClient::deleteAlias(), QtAws::Lambda::LambdaClient::deleteAlias(), QtAws::KMS::KmsClient::deleteAlias(), QtAws::GameLift::GameLiftClient::deleteAlias(), QtAws::CloudSearch::CloudSearchClient::deleteAnalysisScheme(), QtAws::AppSync::AppSyncClient::deleteApiKey(), QtAws::APIGateway::APIGatewayClient::deleteApiKey(), QtAws::Pinpoint::PinpointClient::deleteApnsChannel(), QtAws::Pinpoint::PinpointClient::deleteApnsSandboxChannel(), QtAws::Pinpoint::PinpointClient::deleteApnsVoipChannel(), QtAws::Pinpoint::PinpointClient::deleteApnsVoipSandboxChannel(), QtAws::Pinpoint::PinpointClient::deleteApp(), QtAws::OpsWorks::OpsWorksClient::deleteApp(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::deleteApplication(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplication(), QtAws::CodeDeploy::CodeDeployClient::deleteApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::deleteApplication(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationCloudWatchLoggingOption(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationInputProcessingConfiguration(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationOutput(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::deleteApplicationReferenceDataSource(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::deleteApplications(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::deleteApplicationVersion(), QtAws::Glacier::GlacierClient::deleteArchive(), QtAws::Inspector::InspectorClient::deleteAssessmentRun(), QtAws::Inspector::InspectorClient::deleteAssessmentTarget(), QtAws::Inspector::InspectorClient::deleteAssessmentTemplate(), QtAws::SSM::SsmClient::deleteAssociation(), QtAws::SimpleDB::SimpleDBClient::deleteAttributes(), QtAws::ECS::EcsClient::deleteAttributes(), QtAws::APIGateway::APIGatewayClient::deleteAuthorizer(), QtAws::IoT::IoTClient::deleteAuthorizer(), QtAws::AutoScaling::AutoScalingClient::deleteAutoScalingGroup(), QtAws::OpsWorksCM::OpsWorksCMClient::deleteBackup(), QtAws::DynamoDB::DynamoDBClient::deleteBackup(), QtAws::Pinpoint::PinpointClient::deleteBaiduChannel(), QtAws::StorageGateway::StorageGatewayClient::deleteBandwidthRateLimit(), QtAws::APIGateway::APIGatewayClient::deleteBasePathMapping(), QtAws::MachineLearning::MachineLearningClient::deleteBatchPrediction(), QtAws::DirectConnect::DirectConnectClient::deleteBGPPeer(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBot(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotAlias(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotChannelAssociation(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotVersion(), QtAws::CodeCommit::CodeCommitClient::deleteBranch(), QtAws::MQ::MqClient::deleteBroker(), QtAws::S3::S3Client::deleteBucket(), QtAws::S3::S3Client::deleteBucketAnalyticsConfiguration(), QtAws::S3::S3Client::deleteBucketCors(), QtAws::S3::S3Client::deleteBucketEncryption(), QtAws::S3::S3Client::deleteBucketInventoryConfiguration(), QtAws::S3::S3Client::deleteBucketLifecycle(), QtAws::S3::S3Client::deleteBucketMetricsConfiguration(), QtAws::S3::S3Client::deleteBucketPolicy(), QtAws::S3::S3Client::deleteBucketReplication(), QtAws::S3::S3Client::deleteBucketTagging(), QtAws::S3::S3Client::deleteBucketWebsite(), QtAws::Budgets::BudgetsClient::deleteBudget(), QtAws::GameLift::GameLiftClient::deleteBuild(), QtAws::WAF::WafClient::deleteByteMatchSet(), QtAws::WAFRegional::WAFRegionalClient::deleteByteMatchSet(), QtAws::IoT::IoTClient::deleteCACertificate(), QtAws::ElastiCache::ElastiCacheClient::deleteCacheCluster(), QtAws::ElastiCache::ElastiCacheClient::deleteCacheParameterGroup(), QtAws::ElastiCache::ElastiCacheClient::deleteCacheSecurityGroup(), QtAws::ElastiCache::ElastiCacheClient::deleteCacheSubnetGroup(), QtAws::Pinpoint::PinpointClient::deleteCampaign(), QtAws::ACM::AcmClient::deleteCertificate(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteCertificate(), QtAws::IoT::IoTClient::deleteCertificate(), QtAws::CloudFormation::CloudFormationClient::deleteChangeSet(), QtAws::MediaPackage::MediaPackageClient::deleteChannel(), QtAws::MediaLive::MediaLiveClient::deleteChannel(), QtAws::StorageGateway::StorageGatewayClient::deleteChapCredentials(), QtAws::Glue::GlueClient::deleteClassifier(), QtAws::APIGateway::APIGatewayClient::deleteClientCertificate(), QtAws::CloudFront::CloudFrontClient::deleteCloudFrontOriginAccessIdentity(), QtAws::CloudHSMV2::CloudHSMV2Client::deleteCluster(), QtAws::DAX::DaxClient::deleteCluster(), QtAws::ECS::EcsClient::deleteCluster(), QtAws::Redshift::RedshiftClient::deleteCluster(), QtAws::Redshift::RedshiftClient::deleteClusterParameterGroup(), QtAws::Redshift::RedshiftClient::deleteClusterSecurityGroup(), QtAws::Redshift::RedshiftClient::deleteClusterSnapshot(), QtAws::Redshift::RedshiftClient::deleteClusterSubnetGroup(), QtAws::Rekognition::RekognitionClient::deleteCollection(), QtAws::WorkDocs::WorkDocsClient::deleteComment(), QtAws::CodeCommit::CodeCommitClient::deleteCommentContent(), QtAws::Batch::BatchClient::deleteComputeEnvironment(), QtAws::DirectoryService::DirectoryServiceClient::deleteConditionalForwarder(), QtAws::ConfigService::ConfigServiceClient::deleteConfigRule(), QtAws::ConfigService::ConfigServiceClient::deleteConfigurationRecorder(), QtAws::SES::SesClient::deleteConfigurationSet(), QtAws::SES::SesClient::deleteConfigurationSetEventDestination(), QtAws::SES::SesClient::deleteConfigurationSetTrackingOptions(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::deleteConfigurationTemplate(), QtAws::DirectConnect::DirectConnectClient::deleteConnection(), QtAws::Glue::GlueClient::deleteConnection(), QtAws::ServiceCatalog::ServiceCatalogClient::deleteConstraint(), QtAws::MediaStore::MediaStoreClient::deleteContainer(), QtAws::MediaStore::MediaStoreClient::deleteContainerPolicy(), QtAws::Greengrass::GreengrassClient::deleteCoreDefinition(), QtAws::MediaStore::MediaStoreClient::deleteCorsPolicy(), QtAws::Glue::GlueClient::deleteCrawler(), QtAws::CodePipeline::CodePipelineClient::deleteCustomActionType(), QtAws::EC2::Ec2Client::deleteCustomerGateway(), QtAws::WorkDocs::WorkDocsClient::deleteCustomMetadata(), QtAws::SES::SesClient::deleteCustomVerificationEmailTemplate(), QtAws::CloudWatch::CloudWatchClient::deleteDashboards(), QtAws::Glue::GlueClient::deleteDatabase(), QtAws::CognitoSync::CognitoSyncClient::deleteDataset(), QtAws::AppSync::AppSyncClient::deleteDataSource(), QtAws::MachineLearning::MachineLearningClient::deleteDataSource(), QtAws::RDS::RdsClient::deleteDBCluster(), QtAws::RDS::RdsClient::deleteDBClusterParameterGroup(), QtAws::RDS::RdsClient::deleteDBClusterSnapshot(), QtAws::RDS::RdsClient::deleteDBInstance(), QtAws::RDS::RdsClient::deleteDBParameterGroup(), QtAws::RDS::RdsClient::deleteDBSecurityGroup(), QtAws::RDS::RdsClient::deleteDBSnapshot(), QtAws::RDS::RdsClient::deleteDBSubnetGroup(), QtAws::ConfigService::ConfigServiceClient::deleteDeliveryChannel(), QtAws::Firehose::FirehoseClient::deleteDeliveryStream(), QtAws::APIGateway::APIGatewayClient::deleteDeployment(), QtAws::CodeDeploy::CodeDeployClient::deleteDeploymentConfig(), QtAws::CodeDeploy::CodeDeployClient::deleteDeploymentGroup(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteDestination(), QtAws::GuardDuty::GuardDutyClient::deleteDetector(), QtAws::Glue::GlueClient::deleteDevEndpoint(), QtAws::Greengrass::GreengrassClient::deleteDeviceDefinition(), QtAws::DeviceFarm::DeviceFarmClient::deleteDevicePool(), QtAws::EC2::Ec2Client::deleteDhcpOptions(), QtAws::DirectConnect::DirectConnectClient::deleteDirectConnectGateway(), QtAws::DirectConnect::DirectConnectClient::deleteDirectConnectGatewayAssociation(), QtAws::DirectoryService::DirectoryServiceClient::deleteDirectory(), QtAws::CloudDirectory::CloudDirectoryClient::deleteDirectory(), QtAws::AppStream::AppStreamClient::deleteDirectoryConfig(), QtAws::Lightsail::LightsailClient::deleteDisk(), QtAws::Lightsail::LightsailClient::deleteDiskSnapshot(), QtAws::CloudFront::CloudFrontClient::deleteDistribution(), QtAws::WorkDocs::WorkDocsClient::deleteDocument(), QtAws::SSM::SsmClient::deleteDocument(), QtAws::APIGateway::APIGatewayClient::deleteDocumentationPart(), QtAws::APIGateway::APIGatewayClient::deleteDocumentationVersion(), QtAws::SimpleDB::SimpleDBClient::deleteDomain(), QtAws::CloudSearch::CloudSearchClient::deleteDomain(), QtAws::Lightsail::LightsailClient::deleteDomain(), QtAws::Lightsail::LightsailClient::deleteDomainEntry(), QtAws::APIGateway::APIGatewayClient::deleteDomainName(), QtAws::EC2::Ec2Client::deleteEgressOnlyInternetGateway(), QtAws::ElasticsearchService::ElasticsearchServiceClient::deleteElasticsearchDomain(), QtAws::ElasticsearchService::ElasticsearchServiceClient::deleteElasticsearchServiceRole(), QtAws::Pinpoint::PinpointClient::deleteEmailChannel(), QtAws::SNS::SnsClient::deleteEndpoint(), QtAws::SageMaker::SageMakerClient::deleteEndpoint(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteEndpoint(), QtAws::Pinpoint::PinpointClient::deleteEndpoint(), QtAws::SageMaker::SageMakerClient::deleteEndpointConfig(), QtAws::Cloud9::Cloud9Client::deleteEnvironment(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::deleteEnvironmentConfiguration(), QtAws::Cloud9::Cloud9Client::deleteEnvironmentMembership(), QtAws::MachineLearning::MachineLearningClient::deleteEvaluation(), QtAws::ConfigService::ConfigServiceClient::deleteEvaluationResults(), QtAws::Lambda::LambdaClient::deleteEventSourceMapping(), QtAws::Pinpoint::PinpointClient::deleteEventStream(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteEventSubscription(), QtAws::Redshift::RedshiftClient::deleteEventSubscription(), QtAws::RDS::RdsClient::deleteEventSubscription(), QtAws::CloudSearch::CloudSearchClient::deleteExpression(), QtAws::Rekognition::RekognitionClient::deleteFaces(), QtAws::CloudDirectory::CloudDirectoryClient::deleteFacet(), QtAws::StorageGateway::StorageGatewayClient::deleteFileShare(), QtAws::EFS::EfsClient::deleteFileSystem(), QtAws::AppStream::AppStreamClient::deleteFleet(), QtAws::GameLift::GameLiftClient::deleteFleet(), QtAws::EC2::Ec2Client::deleteFlowLogs(), QtAws::WorkDocs::WorkDocsClient::deleteFolder(), QtAws::WorkDocs::WorkDocsClient::deleteFolderContents(), QtAws::EC2::Ec2Client::deleteFpgaImage(), QtAws::Lambda::LambdaClient::deleteFunction(), QtAws::Lambda::LambdaClient::deleteFunctionConcurrency(), QtAws::Greengrass::GreengrassClient::deleteFunctionDefinition(), QtAws::GameLift::GameLiftClient::deleteGameSessionQueue(), QtAws::StorageGateway::StorageGatewayClient::deleteGateway(), QtAws::APIGateway::APIGatewayClient::deleteGatewayResponse(), QtAws::Pinpoint::PinpointClient::deleteGcmChannel(), QtAws::WAF::WafClient::deleteGeoMatchSet(), QtAws::WAFRegional::WAFRegionalClient::deleteGeoMatchSet(), QtAws::CodeDeploy::CodeDeployClient::deleteGitHubAccountToken(), QtAws::AppSync::AppSyncClient::deleteGraphqlApi(), QtAws::ResourceGroups::ResourceGroupsClient::deleteGroup(), QtAws::WorkMail::WorkMailClient::deleteGroup(), QtAws::Greengrass::GreengrassClient::deleteGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteGroup(), QtAws::IAM::IamClient::deleteGroup(), QtAws::IAM::IamClient::deleteGroupPolicy(), QtAws::CloudHSM::CloudHSMClient::deleteHapg(), QtAws::Route53::Route53Client::deleteHealthCheck(), QtAws::MTurk::MTurkClient::deleteHIT(), QtAws::Route53::Route53Client::deleteHostedZone(), QtAws::CloudHSMV2::CloudHSMV2Client::deleteHsm(), QtAws::CloudHSM::CloudHSMClient::deleteHsm(), QtAws::Redshift::RedshiftClient::deleteHsmClientCertificate(), QtAws::Redshift::RedshiftClient::deleteHsmConfiguration(), QtAws::CognitoIdentity::CognitoIdentityClient::deleteIdentities(), QtAws::SES::SesClient::deleteIdentity(), QtAws::SES::SesClient::deleteIdentityPolicy(), QtAws::CognitoIdentity::CognitoIdentityClient::deleteIdentityPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteIdentityProvider(), QtAws::AppStream::AppStreamClient::deleteImage(), QtAws::AppStream::AppStreamClient::deleteImageBuilder(), QtAws::KMS::KmsClient::deleteImportedKeyMaterial(), QtAws::CloudSearch::CloudSearchClient::deleteIndexField(), QtAws::MediaLive::MediaLiveClient::deleteInput(), QtAws::MediaLive::MediaLiveClient::deleteInputSecurityGroup(), QtAws::OpsWorks::OpsWorksClient::deleteInstance(), QtAws::Lightsail::LightsailClient::deleteInstance(), QtAws::IAM::IamClient::deleteInstanceProfile(), QtAws::Lightsail::LightsailClient::deleteInstanceSnapshot(), QtAws::APIGateway::APIGatewayClient::deleteIntegration(), QtAws::APIGateway::APIGatewayClient::deleteIntegrationResponse(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteIntent(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteIntentVersion(), QtAws::DirectConnect::DirectConnectClient::deleteInterconnect(), QtAws::EC2::Ec2Client::deleteInternetGateway(), QtAws::GuardDuty::GuardDutyClient::deleteInvitations(), QtAws::GuardDuty::GuardDutyClient::deleteIPSet(), QtAws::WAF::WafClient::deleteIPSet(), QtAws::WAFRegional::WAFRegionalClient::deleteIPSet(), QtAws::DynamoDB::DynamoDBClient::deleteItem(), QtAws::Glue::GlueClient::deleteJob(), QtAws::Batch::BatchClient::deleteJobQueue(), QtAws::MediaConvert::MediaConvertClient::deleteJobTemplate(), QtAws::Lightsail::LightsailClient::deleteKeyPair(), QtAws::EC2::Ec2Client::deleteKeyPair(), QtAws::WorkDocs::WorkDocsClient::deleteLabels(), QtAws::DirectConnect::DirectConnectClient::deleteLag(), QtAws::AutoScaling::AutoScalingClient::deleteLaunchConfiguration(), QtAws::EC2::Ec2Client::deleteLaunchTemplate(), QtAws::EC2::Ec2Client::deleteLaunchTemplateVersions(), QtAws::OpsWorks::OpsWorksClient::deleteLayer(), QtAws::Polly::PollyClient::deleteLexicon(), QtAws::AutoScaling::AutoScalingClient::deleteLifecycleHook(), QtAws::ECR::EcrClient::deleteLifecyclePolicy(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteListener(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancer(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteLoadBalancer(), QtAws::Lightsail::LightsailClient::deleteLoadBalancer(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancerListeners(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deleteLoadBalancerPolicy(), QtAws::Lightsail::LightsailClient::deleteLoadBalancerTlsCertificate(), QtAws::Greengrass::GreengrassClient::deleteLoggerDefinition(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteLogGroup(), QtAws::IAM::IamClient::deleteLoginProfile(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteLogStream(), QtAws::CloudHSM::CloudHSMClient::deleteLunaClient(), QtAws::SSM::SsmClient::deleteMaintenanceWindow(), QtAws::GameLift::GameLiftClient::deleteMatchmakingConfiguration(), QtAws::GuardDuty::GuardDutyClient::deleteMembers(), QtAws::SQS::SqsClient::deleteMessage(), QtAws::SQS::SqsClient::deleteMessageBatch(), QtAws::APIGateway::APIGatewayClient::deleteMethod(), QtAws::APIGateway::APIGatewayClient::deleteMethodResponse(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteMetricFilter(), QtAws::MachineLearning::MachineLearningClient::deleteMLModel(), QtAws::SageMaker::SageMakerClient::deleteModel(), QtAws::APIGateway::APIGatewayClient::deleteModel(), QtAws::EFS::EfsClient::deleteMountTarget(), QtAws::Athena::AthenaClient::deleteNamedQuery(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::deleteNamespace(), QtAws::EC2::Ec2Client::deleteNatGateway(), QtAws::EC2::Ec2Client::deleteNetworkAcl(), QtAws::EC2::Ec2Client::deleteNetworkAclEntry(), QtAws::EC2::Ec2Client::deleteNetworkInterface(), QtAws::EC2::Ec2Client::deleteNetworkInterfacePermission(), QtAws::DeviceFarm::DeviceFarmClient::deleteNetworkProfile(), QtAws::SageMaker::SageMakerClient::deleteNotebookInstance(), QtAws::SageMaker::SageMakerClient::deleteNotebookInstanceLifecycleConfig(), QtAws::Budgets::BudgetsClient::deleteNotification(), QtAws::AutoScaling::AutoScalingClient::deleteNotificationConfiguration(), QtAws::WorkDocs::WorkDocsClient::deleteNotificationSubscription(), QtAws::MediaStoreData::MediaStoreDataClient::deleteObject(), QtAws::CloudDirectory::CloudDirectoryClient::deleteObject(), QtAws::S3::S3Client::deleteObject(), QtAws::S3::S3Client::deleteObjects(), QtAws::S3::S3Client::deleteObjectTagging(), QtAws::IAM::IamClient::deleteOpenIDConnectProvider(), QtAws::RDS::RdsClient::deleteOptionGroup(), QtAws::Organizations::OrganizationsClient::deleteOrganization(), QtAws::Organizations::OrganizationsClient::deleteOrganizationalUnit(), QtAws::MediaPackage::MediaPackageClient::deleteOriginEndpoint(), QtAws::IoT::IoTClient::deleteOTAUpdate(), QtAws::SSM::SsmClient::deleteParameter(), QtAws::DAX::DaxClient::deleteParameterGroup(), QtAws::SSM::SsmClient::deleteParameters(), QtAws::Glue::GlueClient::deletePartition(), QtAws::SSM::SsmClient::deletePatchBaseline(), QtAws::WAF::WafClient::deletePermissionPolicy(), QtAws::WAFRegional::WAFRegionalClient::deletePermissionPolicy(), QtAws::ElasticTranscoder::ElasticTranscoderClient::deletePipeline(), QtAws::DataPipeline::DataPipelineClient::deletePipeline(), QtAws::CodePipeline::CodePipelineClient::deletePipeline(), QtAws::EC2::Ec2Client::deletePlacementGroup(), QtAws::SNS::SnsClient::deletePlatformApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::deletePlatformVersion(), QtAws::Organizations::OrganizationsClient::deletePolicy(), QtAws::AutoScaling::AutoScalingClient::deletePolicy(), QtAws::IAM::IamClient::deletePolicy(), QtAws::IoT::IoTClient::deletePolicy(), QtAws::IAM::IamClient::deletePolicyVersion(), QtAws::IoT::IoTClient::deletePolicyVersion(), QtAws::ServiceCatalog::ServiceCatalogClient::deletePortfolio(), QtAws::ServiceCatalog::ServiceCatalogClient::deletePortfolioShare(), QtAws::ElasticTranscoder::ElasticTranscoderClient::deletePreset(), QtAws::MediaConvert::MediaConvertClient::deletePreset(), QtAws::ServiceCatalog::ServiceCatalogClient::deleteProduct(), QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteProfile(), QtAws::MigrationHub::MigrationHubClient::deleteProgressUpdateStream(), QtAws::Mobile::MobileClient::deleteProject(), QtAws::CodeBuild::CodeBuildClient::deleteProject(), QtAws::CodeStar::CodeStarClient::deleteProject(), QtAws::DeviceFarm::DeviceFarmClient::deleteProject(), QtAws::Shield::ShieldClient::deleteProtection(), QtAws::ServiceCatalog::ServiceCatalogClient::deleteProvisionedProductPlan(), QtAws::ServiceCatalog::ServiceCatalogClient::deleteProvisioningArtifact(), QtAws::MTurk::MTurkClient::deleteQualificationType(), QtAws::Route53::Route53Client::deleteQueryLoggingConfig(), QtAws::SQS::SqsClient::deleteQueue(), QtAws::MediaConvert::MediaConvertClient::deleteQueue(), QtAws::WAF::WafClient::deleteRateBasedRule(), QtAws::WAFRegional::WAFRegionalClient::deleteRateBasedRule(), QtAws::MachineLearning::MachineLearningClient::deleteRealtimeEndpoint(), QtAws::SES::SesClient::deleteReceiptFilter(), QtAws::SES::SesClient::deleteReceiptRule(), QtAws::SES::SesClient::deleteReceiptRuleSet(), QtAws::WAF::WafClient::deleteRegexMatchSet(), QtAws::WAFRegional::WAFRegionalClient::deleteRegexMatchSet(), QtAws::WAF::WafClient::deleteRegexPatternSet(), QtAws::WAFRegional::WAFRegionalClient::deleteRegexPatternSet(), QtAws::IoT::IoTClient::deleteRegistrationCode(), QtAws::DeviceFarm::DeviceFarmClient::deleteRemoteAccessSession(), QtAws::ElastiCache::ElastiCacheClient::deleteReplicationGroup(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationInstance(), QtAws::SMS::SmsClient::deleteReplicationJob(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationSubnetGroup(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::deleteReplicationTask(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::deleteReportDefinition(), QtAws::ECR::EcrClient::deleteRepository(), QtAws::CodeCommit::CodeCommitClient::deleteRepository(), QtAws::ECR::EcrClient::deleteRepositoryPolicy(), QtAws::APIGateway::APIGatewayClient::deleteRequestValidator(), QtAws::AppSync::AppSyncClient::deleteResolver(), QtAws::WorkMail::WorkMailClient::deleteResource(), QtAws::APIGateway::APIGatewayClient::deleteResource(), QtAws::SSM::SsmClient::deleteResourceDataSync(), QtAws::Greengrass::GreengrassClient::deleteResourceDefinition(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteResourcePolicy(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteResourceServer(), QtAws::APIGateway::APIGatewayClient::deleteRestApi(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteRetentionPolicy(), QtAws::Route53::Route53Client::deleteReusableDelegationSet(), QtAws::IAM::IamClient::deleteRole(), QtAws::IoT::IoTClient::deleteRoleAlias(), QtAws::IAM::IamClient::deleteRolePolicy(), QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteRoom(), QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteRoomSkillParameter(), QtAws::EC2::Ec2Client::deleteRoute(), QtAws::EC2::Ec2Client::deleteRouteTable(), QtAws::CloudWatchEvents::CloudWatchEventsClient::deleteRule(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteRule(), QtAws::WAF::WafClient::deleteRule(), QtAws::WAFRegional::WAFRegionalClient::deleteRule(), QtAws::WAF::WafClient::deleteRuleGroup(), QtAws::WAFRegional::WAFRegionalClient::deleteRuleGroup(), QtAws::DeviceFarm::DeviceFarmClient::deleteRun(), QtAws::IAM::IamClient::deleteSAMLProvider(), QtAws::AutoScalingPlans::AutoScalingPlansClient::deleteScalingPlan(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deleteScalingPolicy(), QtAws::GameLift::GameLiftClient::deleteScalingPolicy(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deleteScheduledAction(), QtAws::AutoScaling::AutoScalingClient::deleteScheduledAction(), QtAws::CloudDirectory::CloudDirectoryClient::deleteSchema(), QtAws::EMR::EmrClient::deleteSecurityConfiguration(), QtAws::EC2::Ec2Client::deleteSecurityGroup(), QtAws::Pinpoint::PinpointClient::deleteSegment(), QtAws::OpsWorksCM::OpsWorksCMClient::deleteServer(), QtAws::SMS::SmsClient::deleteServerCatalog(), QtAws::IAM::IamClient::deleteServerCertificate(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::deleteService(), QtAws::ECS::EcsClient::deleteService(), QtAws::CloudFront::CloudFrontClient::deleteServiceLinkedRole(), QtAws::IAM::IamClient::deleteServiceLinkedRole(), QtAws::IAM::IamClient::deleteServiceSpecificCredential(), QtAws::IAM::IamClient::deleteSigningCertificate(), QtAws::WAF::WafClient::deleteSizeConstraintSet(), QtAws::WAFRegional::WAFRegionalClient::deleteSizeConstraintSet(), QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteSkillGroup(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteSlotType(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteSlotTypeVersion(), QtAws::Pinpoint::PinpointClient::deleteSmsChannel(), QtAws::DirectoryService::DirectoryServiceClient::deleteSnapshot(), QtAws::ElastiCache::ElastiCacheClient::deleteSnapshot(), QtAws::EC2::Ec2Client::deleteSnapshot(), QtAws::Redshift::RedshiftClient::deleteSnapshotCopyGrant(), QtAws::StorageGateway::StorageGatewayClient::deleteSnapshotSchedule(), QtAws::EC2::Ec2Client::deleteSpotDatafeedSubscription(), QtAws::WAF::WafClient::deleteSqlInjectionMatchSet(), QtAws::WAFRegional::WAFRegionalClient::deleteSqlInjectionMatchSet(), QtAws::IAM::IamClient::deleteSSHPublicKey(), QtAws::AppStream::AppStreamClient::deleteStack(), QtAws::CloudFormation::CloudFormationClient::deleteStack(), QtAws::OpsWorks::OpsWorksClient::deleteStack(), QtAws::CloudFormation::CloudFormationClient::deleteStackInstances(), QtAws::CloudFormation::CloudFormationClient::deleteStackSet(), QtAws::APIGateway::APIGatewayClient::deleteStage(), QtAws::SFN::SfnClient::deleteStateMachine(), QtAws::KinesisVideo::KinesisVideoClient::deleteStream(), QtAws::Kinesis::KinesisClient::deleteStream(), QtAws::IoT::IoTClient::deleteStream(), QtAws::CloudFront::CloudFrontClient::deleteStreamingDistribution(), QtAws::Rekognition::RekognitionClient::deleteStreamProcessor(), QtAws::EC2::Ec2Client::deleteSubnet(), QtAws::DAX::DaxClient::deleteSubnetGroup(), QtAws::Budgets::BudgetsClient::deleteSubscriber(), QtAws::Shield::ShieldClient::deleteSubscription(), QtAws::Greengrass::GreengrassClient::deleteSubscriptionDefinition(), QtAws::CloudWatchLogs::CloudWatchLogsClient::deleteSubscriptionFilter(), QtAws::CloudSearch::CloudSearchClient::deleteSuggester(), QtAws::DynamoDB::DynamoDBClient::deleteTable(), QtAws::Glue::GlueClient::deleteTable(), QtAws::Glue::GlueClient::deleteTableVersion(), QtAws::ServiceCatalog::ServiceCatalogClient::deleteTagOption(), QtAws::EFS::EfsClient::deleteTags(), QtAws::WorkSpaces::WorkSpacesClient::deleteTags(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::deleteTags(), QtAws::MachineLearning::MachineLearningClient::deleteTags(), QtAws::SageMaker::SageMakerClient::deleteTags(), QtAws::AutoScaling::AutoScalingClient::deleteTags(), QtAws::Redshift::RedshiftClient::deleteTags(), QtAws::EC2::Ec2Client::deleteTags(), QtAws::Route53Domains::Route53DomainsClient::deleteTagsForDomain(), QtAws::StorageGateway::StorageGatewayClient::deleteTape(), QtAws::StorageGateway::StorageGatewayClient::deleteTapeArchive(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deleteTargetGroup(), QtAws::SES::SesClient::deleteTemplate(), QtAws::IoT::IoTClient::deleteThing(), QtAws::IoT::IoTClient::deleteThingGroup(), QtAws::IoTDataPlane::IoTDataPlaneClient::deleteThingShadow(), QtAws::IoT::IoTClient::deleteThingType(), QtAws::GuardDuty::GuardDutyClient::deleteThreatIntelSet(), QtAws::SNS::SnsClient::deleteTopic(), QtAws::IoT::IoTClient::deleteTopicRule(), QtAws::Route53::Route53Client::deleteTrafficPolicy(), QtAws::Route53::Route53Client::deleteTrafficPolicyInstance(), QtAws::CloudTrail::CloudTrailClient::deleteTrail(), QtAws::Glue::GlueClient::deleteTrigger(), QtAws::DirectoryService::DirectoryServiceClient::deleteTrust(), QtAws::AppSync::AppSyncClient::deleteType(), QtAws::CloudDirectory::CloudDirectoryClient::deleteTypedLinkFacet(), QtAws::DeviceFarm::DeviceFarmClient::deleteUpload(), QtAws::APIGateway::APIGatewayClient::deleteUsagePlan(), QtAws::APIGateway::APIGatewayClient::deleteUsagePlanKey(), QtAws::MQ::MqClient::deleteUser(), QtAws::WorkMail::WorkMailClient::deleteUser(), QtAws::AlexaForBusiness::AlexaForBusinessClient::deleteUser(), QtAws::WorkDocs::WorkDocsClient::deleteUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUser(), QtAws::IAM::IamClient::deleteUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserAttributes(), QtAws::Glue::GlueClient::deleteUserDefinedFunction(), QtAws::IAM::IamClient::deleteUserPolicy(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPoolClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::deleteUserPoolDomain(), QtAws::CodeStar::CodeStarClient::deleteUserProfile(), QtAws::OpsWorks::OpsWorksClient::deleteUserProfile(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteUtterances(), QtAws::IoT::IoTClient::deleteV2LoggingLevel(), QtAws::Glacier::GlacierClient::deleteVault(), QtAws::Glacier::GlacierClient::deleteVaultAccessPolicy(), QtAws::Glacier::GlacierClient::deleteVaultNotifications(), QtAws::SES::SesClient::deleteVerifiedEmailAddress(), QtAws::DirectConnect::DirectConnectClient::deleteVirtualInterface(), QtAws::IAM::IamClient::deleteVirtualMFADevice(), QtAws::StorageGateway::StorageGatewayClient::deleteVolume(), QtAws::EC2::Ec2Client::deleteVolume(), QtAws::EC2::Ec2Client::deleteVpc(), QtAws::Route53::Route53Client::deleteVPCAssociationAuthorization(), QtAws::EC2::Ec2Client::deleteVpcEndpointConnectionNotifications(), QtAws::EC2::Ec2Client::deleteVpcEndpoints(), QtAws::EC2::Ec2Client::deleteVpcEndpointServiceConfigurations(), QtAws::APIGateway::APIGatewayClient::deleteVpcLink(), QtAws::GameLift::GameLiftClient::deleteVpcPeeringAuthorization(), QtAws::GameLift::GameLiftClient::deleteVpcPeeringConnection(), QtAws::EC2::Ec2Client::deleteVpcPeeringConnection(), QtAws::EC2::Ec2Client::deleteVpnConnection(), QtAws::EC2::Ec2Client::deleteVpnConnectionRoute(), QtAws::EC2::Ec2Client::deleteVpnGateway(), QtAws::WAF::WafClient::deleteWebACL(), QtAws::WAFRegional::WAFRegionalClient::deleteWebACL(), QtAws::CodeBuild::CodeBuildClient::deleteWebhook(), QtAws::MTurk::MTurkClient::deleteWorkerBlock(), QtAws::WAF::WafClient::deleteXssMatchSet(), QtAws::WAFRegional::WAFRegionalClient::deleteXssMatchSet(), QtAws::ConfigService::ConfigServiceClient::deliverConfigSnapshot(), QtAws::SWF::SwfClient::deprecateActivityType(), QtAws::SWF::SwfClient::deprecateDomain(), QtAws::IoT::IoTClient::deprecateThingType(), QtAws::SWF::SwfClient::deprecateWorkflowType(), QtAws::ECS::EcsClient::deregisterContainerInstance(), QtAws::OpsWorks::OpsWorksClient::deregisterEcsCluster(), QtAws::OpsWorks::OpsWorksClient::deregisterElasticIp(), QtAws::DirectoryService::DirectoryServiceClient::deregisterEventTopic(), QtAws::WorkMail::WorkMailClient::deregisterFromWorkMail(), QtAws::EC2::Ec2Client::deregisterImage(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::deregisterInstance(), QtAws::OpsWorks::OpsWorksClient::deregisterInstance(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::deregisterInstancesFromLoadBalancer(), QtAws::Batch::BatchClient::deregisterJobDefinition(), QtAws::SSM::SsmClient::deregisterManagedInstance(), QtAws::CodeDeploy::CodeDeployClient::deregisterOnPremisesInstance(), QtAws::SSM::SsmClient::deregisterPatchBaselineForPatchGroup(), QtAws::OpsWorks::OpsWorksClient::deregisterRdsDbInstance(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::deregisterScalableTarget(), QtAws::SSM::SsmClient::deregisterTargetFromMaintenanceWindow(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::deregisterTargets(), QtAws::ECS::EcsClient::deregisterTaskDefinition(), QtAws::SSM::SsmClient::deregisterTaskFromMaintenanceWindow(), QtAws::OpsWorks::OpsWorksClient::deregisterVolume(), QtAws::Organizations::OrganizationsClient::describeAccount(), QtAws::OpsWorksCM::OpsWorksCMClient::describeAccountAttributes(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeAccountAttributes(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeAccountAttributes(), QtAws::RDS::RdsClient::describeAccountAttributes(), QtAws::EC2::Ec2Client::describeAccountAttributes(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeAccountLimits(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeAccountLimits(), QtAws::CloudFormation::CloudFormationClient::describeAccountLimits(), QtAws::AutoScaling::AutoScalingClient::describeAccountLimits(), QtAws::SSM::SsmClient::describeActivations(), QtAws::SES::SesClient::describeActiveReceiptRuleSet(), QtAws::WorkDocs::WorkDocsClient::describeActivities(), QtAws::SFN::SfnClient::describeActivity(), QtAws::SWF::SwfClient::describeActivityType(), QtAws::Snowball::SnowballClient::describeAddress(), QtAws::Snowball::SnowballClient::describeAddresses(), QtAws::EC2::Ec2Client::describeAddresses(), QtAws::AutoScaling::AutoScalingClient::describeAdjustmentTypes(), QtAws::Health::HealthClient::describeAffectedEntities(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::describeAgents(), QtAws::OpsWorks::OpsWorksClient::describeAgentVersions(), QtAws::EC2::Ec2Client::describeAggregateIdFormat(), QtAws::CloudWatch::CloudWatchClient::describeAlarmHistory(), QtAws::CloudWatch::CloudWatchClient::describeAlarms(), QtAws::CloudWatch::CloudWatchClient::describeAlarmsForMetric(), QtAws::GameLift::GameLiftClient::describeAlias(), QtAws::CloudSearch::CloudSearchClient::describeAnalysisSchemes(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::describeApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeApplications(), QtAws::MigrationHub::MigrationHubClient::describeApplicationState(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeApplicationVersions(), QtAws::OpsWorks::OpsWorksClient::describeApps(), QtAws::Inspector::InspectorClient::describeAssessmentRuns(), QtAws::Inspector::InspectorClient::describeAssessmentTargets(), QtAws::Inspector::InspectorClient::describeAssessmentTemplates(), QtAws::SSM::SsmClient::describeAssociation(), QtAws::Support::SupportClient::describeAttachment(), QtAws::Shield::ShieldClient::describeAttack(), QtAws::IoT::IoTClient::describeAuthorizer(), QtAws::SSM::SsmClient::describeAutomationExecutions(), QtAws::SSM::SsmClient::describeAutomationStepExecutions(), QtAws::AutoScaling::AutoScalingClient::describeAutoScalingGroups(), QtAws::AutoScaling::AutoScalingClient::describeAutoScalingInstances(), QtAws::AutoScaling::AutoScalingClient::describeAutoScalingNotificationTypes(), QtAws::CloudSearch::CloudSearchClient::describeAvailabilityOptions(), QtAws::EC2::Ec2Client::describeAvailabilityZones(), QtAws::SSM::SsmClient::describeAvailablePatches(), QtAws::DynamoDB::DynamoDBClient::describeBackup(), QtAws::CloudHSMV2::CloudHSMV2Client::describeBackups(), QtAws::OpsWorksCM::OpsWorksCMClient::describeBackups(), QtAws::StorageGateway::StorageGatewayClient::describeBandwidthRateLimit(), QtAws::MachineLearning::MachineLearningClient::describeBatchPredictions(), QtAws::MQ::MqClient::describeBroker(), QtAws::Budgets::BudgetsClient::describeBudget(), QtAws::Budgets::BudgetsClient::describeBudgets(), QtAws::GameLift::GameLiftClient::describeBuild(), QtAws::Mobile::MobileClient::describeBundle(), QtAws::EC2::Ec2Client::describeBundleTasks(), QtAws::IoT::IoTClient::describeCACertificate(), QtAws::StorageGateway::StorageGatewayClient::describeCache(), QtAws::ElastiCache::ElastiCacheClient::describeCacheClusters(), QtAws::StorageGateway::StorageGatewayClient::describeCachediSCSIVolumes(), QtAws::ElastiCache::ElastiCacheClient::describeCacheEngineVersions(), QtAws::ElastiCache::ElastiCacheClient::describeCacheParameterGroups(), QtAws::ElastiCache::ElastiCacheClient::describeCacheParameters(), QtAws::ElastiCache::ElastiCacheClient::describeCacheSecurityGroups(), QtAws::ElastiCache::ElastiCacheClient::describeCacheSubnetGroups(), QtAws::Support::SupportClient::describeCases(), QtAws::ACM::AcmClient::describeCertificate(), QtAws::IoT::IoTClient::describeCertificate(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeCertificates(), QtAws::RDS::RdsClient::describeCertificates(), QtAws::CloudFormation::CloudFormationClient::describeChangeSet(), QtAws::MediaPackage::MediaPackageClient::describeChannel(), QtAws::MediaLive::MediaLiveClient::describeChannel(), QtAws::StorageGateway::StorageGatewayClient::describeChapCredentials(), QtAws::EC2::Ec2Client::describeClassicLinkInstances(), QtAws::Snowball::SnowballClient::describeCluster(), QtAws::EMR::EmrClient::describeCluster(), QtAws::Redshift::RedshiftClient::describeClusterParameterGroups(), QtAws::Redshift::RedshiftClient::describeClusterParameters(), QtAws::CloudHSMV2::CloudHSMV2Client::describeClusters(), QtAws::DAX::DaxClient::describeClusters(), QtAws::ECS::EcsClient::describeClusters(), QtAws::Redshift::RedshiftClient::describeClusters(), QtAws::Redshift::RedshiftClient::describeClusterSecurityGroups(), QtAws::Redshift::RedshiftClient::describeClusterSnapshots(), QtAws::Redshift::RedshiftClient::describeClusterSubnetGroups(), QtAws::Redshift::RedshiftClient::describeClusterVersions(), QtAws::OpsWorks::OpsWorksClient::describeCommands(), QtAws::WorkDocs::WorkDocsClient::describeComments(), QtAws::Support::SupportClient::describeCommunications(), QtAws::ConfigService::ConfigServiceClient::describeComplianceByConfigRule(), QtAws::ConfigService::ConfigServiceClient::describeComplianceByResource(), QtAws::Batch::BatchClient::describeComputeEnvironments(), QtAws::DirectoryService::DirectoryServiceClient::describeConditionalForwarders(), QtAws::ConfigService::ConfigServiceClient::describeConfigRuleEvaluationStatus(), QtAws::ConfigService::ConfigServiceClient::describeConfigRules(), QtAws::MQ::MqClient::describeConfiguration(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeConfigurationOptions(), QtAws::ConfigService::ConfigServiceClient::describeConfigurationRecorders(), QtAws::ConfigService::ConfigServiceClient::describeConfigurationRecorderStatus(), QtAws::MQ::MqClient::describeConfigurationRevision(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::describeConfigurations(), QtAws::SES::SesClient::describeConfigurationSet(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeConfigurationSettings(), QtAws::DirectConnect::DirectConnectClient::describeConnectionLoa(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeConnections(), QtAws::DirectConnect::DirectConnectClient::describeConnections(), QtAws::DirectConnect::DirectConnectClient::describeConnectionsOnInterconnect(), QtAws::ServiceCatalog::ServiceCatalogClient::describeConstraint(), QtAws::MediaStore::MediaStoreClient::describeContainer(), QtAws::ECS::EcsClient::describeContainerInstances(), QtAws::DynamoDB::DynamoDBClient::describeContinuousBackups(), QtAws::EC2::Ec2Client::describeConversionTasks(), QtAws::ServiceCatalog::ServiceCatalogClient::describeCopyProductStatus(), QtAws::Organizations::OrganizationsClient::describeCreateAccountStatus(), QtAws::Inspector::InspectorClient::describeCrossAccountAccessRole(), QtAws::EC2::Ec2Client::describeCustomerGateways(), QtAws::CognitoSync::CognitoSyncClient::describeDataset(), QtAws::MachineLearning::MachineLearningClient::describeDataSources(), QtAws::RDS::RdsClient::describeDBClusterParameterGroups(), QtAws::RDS::RdsClient::describeDBClusterParameters(), QtAws::RDS::RdsClient::describeDBClusters(), QtAws::RDS::RdsClient::describeDBClusterSnapshotAttributes(), QtAws::RDS::RdsClient::describeDBClusterSnapshots(), QtAws::RDS::RdsClient::describeDBEngineVersions(), QtAws::RDS::RdsClient::describeDBInstances(), QtAws::RDS::RdsClient::describeDBLogFiles(), QtAws::RDS::RdsClient::describeDBParameterGroups(), QtAws::RDS::RdsClient::describeDBParameters(), QtAws::RDS::RdsClient::describeDBSecurityGroups(), QtAws::RDS::RdsClient::describeDBSnapshotAttributes(), QtAws::RDS::RdsClient::describeDBSnapshots(), QtAws::RDS::RdsClient::describeDBSubnetGroups(), QtAws::IoT::IoTClient::describeDefaultAuthorizer(), QtAws::Redshift::RedshiftClient::describeDefaultClusterParameters(), QtAws::DAX::DaxClient::describeDefaultParameters(), QtAws::ConfigService::ConfigServiceClient::describeDeliveryChannels(), QtAws::ConfigService::ConfigServiceClient::describeDeliveryChannelStatus(), QtAws::Firehose::FirehoseClient::describeDeliveryStream(), QtAws::OpsWorks::OpsWorksClient::describeDeployments(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeDestinations(), QtAws::EC2::Ec2Client::describeDhcpOptions(), QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGatewayAssociations(), QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGatewayAttachments(), QtAws::DirectConnect::DirectConnectClient::describeDirectConnectGateways(), QtAws::DirectoryService::DirectoryServiceClient::describeDirectories(), QtAws::AppStream::AppStreamClient::describeDirectoryConfigs(), QtAws::SSM::SsmClient::describeDocument(), QtAws::SSM::SsmClient::describeDocumentPermission(), QtAws::WorkDocs::WorkDocsClient::describeDocumentVersions(), QtAws::SWF::SwfClient::describeDomain(), QtAws::DirectoryService::DirectoryServiceClient::describeDomainControllers(), QtAws::CloudSearch::CloudSearchClient::describeDomains(), QtAws::GameLift::GameLiftClient::describeEC2InstanceLimits(), QtAws::OpsWorks::OpsWorksClient::describeEcsClusters(), QtAws::SSM::SsmClient::describeEffectiveInstanceAssociations(), QtAws::SSM::SsmClient::describeEffectivePatchesForPatchBaseline(), QtAws::EC2::Ec2Client::describeEgressOnlyInternetGateways(), QtAws::EC2::Ec2Client::describeElasticGpus(), QtAws::OpsWorks::OpsWorksClient::describeElasticIps(), QtAws::OpsWorks::OpsWorksClient::describeElasticLoadBalancers(), QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomain(), QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomainConfig(), QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchDomains(), QtAws::ElasticsearchService::ElasticsearchServiceClient::describeElasticsearchInstanceTypeLimits(), QtAws::SageMaker::SageMakerClient::describeEndpoint(), QtAws::IoT::IoTClient::describeEndpoint(), QtAws::SageMaker::SageMakerClient::describeEndpointConfig(), QtAws::MediaConvert::MediaConvertClient::describeEndpoints(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEndpoints(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEndpointTypes(), QtAws::RDS::RdsClient::describeEngineDefaultClusterParameters(), QtAws::ElastiCache::ElastiCacheClient::describeEngineDefaultParameters(), QtAws::RDS::RdsClient::describeEngineDefaultParameters(), QtAws::Health::HealthClient::describeEntityAggregates(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEnvironmentHealth(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEnvironmentManagedActionHistory(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEnvironmentManagedActions(), QtAws::Cloud9::Cloud9Client::describeEnvironmentMemberships(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEnvironmentResources(), QtAws::Cloud9::Cloud9Client::describeEnvironments(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEnvironments(), QtAws::Cloud9::Cloud9Client::describeEnvironmentStatus(), QtAws::MachineLearning::MachineLearningClient::describeEvaluations(), QtAws::Health::HealthClient::describeEventAggregates(), QtAws::CloudWatchEvents::CloudWatchEventsClient::describeEventBus(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEventCategories(), QtAws::Redshift::RedshiftClient::describeEventCategories(), QtAws::RDS::RdsClient::describeEventCategories(), QtAws::IoT::IoTClient::describeEventConfigurations(), QtAws::Health::HealthClient::describeEventDetails(), QtAws::Health::HealthClient::describeEvents(), QtAws::OpsWorksCM::OpsWorksCMClient::describeEvents(), QtAws::DAX::DaxClient::describeEvents(), QtAws::ElastiCache::ElastiCacheClient::describeEvents(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEvents(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeEvents(), QtAws::Redshift::RedshiftClient::describeEvents(), QtAws::RDS::RdsClient::describeEvents(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeEventSubscriptions(), QtAws::Redshift::RedshiftClient::describeEventSubscriptions(), QtAws::RDS::RdsClient::describeEventSubscriptions(), QtAws::DirectoryService::DirectoryServiceClient::describeEventTopics(), QtAws::Health::HealthClient::describeEventTypes(), QtAws::SFN::SfnClient::describeExecution(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::describeExportConfigurations(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::describeExportTasks(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeExportTasks(), QtAws::EC2::Ec2Client::describeExportTasks(), QtAws::CloudSearch::CloudSearchClient::describeExpressions(), QtAws::EFS::EfsClient::describeFileSystems(), QtAws::Inspector::InspectorClient::describeFindings(), QtAws::GameLift::GameLiftClient::describeFleetAttributes(), QtAws::GameLift::GameLiftClient::describeFleetCapacity(), QtAws::GameLift::GameLiftClient::describeFleetEvents(), QtAws::GameLift::GameLiftClient::describeFleetPortSettings(), QtAws::AppStream::AppStreamClient::describeFleets(), QtAws::GameLift::GameLiftClient::describeFleetUtilization(), QtAws::EC2::Ec2Client::describeFlowLogs(), QtAws::WorkDocs::WorkDocsClient::describeFolderContents(), QtAws::EC2::Ec2Client::describeFpgaImageAttribute(), QtAws::EC2::Ec2Client::describeFpgaImages(), QtAws::GameLift::GameLiftClient::describeGameSessionDetails(), QtAws::GameLift::GameLiftClient::describeGameSessionPlacement(), QtAws::GameLift::GameLiftClient::describeGameSessionQueues(), QtAws::GameLift::GameLiftClient::describeGameSessions(), QtAws::StorageGateway::StorageGatewayClient::describeGatewayInformation(), QtAws::DynamoDB::DynamoDBClient::describeGlobalTable(), QtAws::WorkMail::WorkMailClient::describeGroup(), QtAws::WorkDocs::WorkDocsClient::describeGroups(), QtAws::Organizations::OrganizationsClient::describeHandshake(), QtAws::CloudHSM::CloudHSMClient::describeHapg(), QtAws::DirectConnect::DirectConnectClient::describeHostedConnections(), QtAws::EC2::Ec2Client::describeHostReservationOfferings(), QtAws::EC2::Ec2Client::describeHostReservations(), QtAws::EC2::Ec2Client::describeHosts(), QtAws::CloudHSM::CloudHSMClient::describeHsm(), QtAws::Redshift::RedshiftClient::describeHsmClientCertificates(), QtAws::Redshift::RedshiftClient::describeHsmConfigurations(), QtAws::EC2::Ec2Client::describeIamInstanceProfileAssociations(), QtAws::CognitoIdentity::CognitoIdentityClient::describeIdentity(), QtAws::EC2::Ec2Client::describeIdentityIdFormat(), QtAws::CognitoIdentity::CognitoIdentityClient::describeIdentityPool(), QtAws::CognitoSync::CognitoSyncClient::describeIdentityPoolUsage(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeIdentityProvider(), QtAws::CognitoSync::CognitoSyncClient::describeIdentityUsage(), QtAws::EC2::Ec2Client::describeIdFormat(), QtAws::EC2::Ec2Client::describeImageAttribute(), QtAws::AppStream::AppStreamClient::describeImageBuilders(), QtAws::ECR::EcrClient::describeImages(), QtAws::AppStream::AppStreamClient::describeImages(), QtAws::EC2::Ec2Client::describeImages(), QtAws::EC2::Ec2Client::describeImportImageTasks(), QtAws::EC2::Ec2Client::describeImportSnapshotTasks(), QtAws::IoT::IoTClient::describeIndex(), QtAws::CloudSearch::CloudSearchClient::describeIndexFields(), QtAws::MediaLive::MediaLiveClient::describeInput(), QtAws::MediaLive::MediaLiveClient::describeInputSecurityGroup(), QtAws::SSM::SsmClient::describeInstanceAssociationsStatus(), QtAws::EC2::Ec2Client::describeInstanceAttribute(), QtAws::EC2::Ec2Client::describeInstanceCreditSpecifications(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeInstanceHealth(), QtAws::SSM::SsmClient::describeInstanceInformation(), QtAws::SSM::SsmClient::describeInstancePatches(), QtAws::SSM::SsmClient::describeInstancePatchStates(), QtAws::SSM::SsmClient::describeInstancePatchStatesForPatchGroup(), QtAws::GameLift::GameLiftClient::describeInstances(), QtAws::OpsWorks::OpsWorksClient::describeInstances(), QtAws::EC2::Ec2Client::describeInstances(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describeInstancesHealth(), QtAws::EC2::Ec2Client::describeInstanceStatus(), QtAws::DirectConnect::DirectConnectClient::describeInterconnectLoa(), QtAws::DirectConnect::DirectConnectClient::describeInterconnects(), QtAws::EC2::Ec2Client::describeInternetGateways(), QtAws::Snowball::SnowballClient::describeJob(), QtAws::Glacier::GlacierClient::describeJob(), QtAws::IoT::IoTClient::describeJob(), QtAws::Batch::BatchClient::describeJobDefinitions(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::describeJobExecution(), QtAws::IoT::IoTClient::describeJobExecution(), QtAws::EMR::EmrClient::describeJobFlows(), QtAws::Batch::BatchClient::describeJobQueues(), QtAws::Batch::BatchClient::describeJobs(), QtAws::KMS::KmsClient::describeKey(), QtAws::EC2::Ec2Client::describeKeyPairs(), QtAws::DirectConnect::DirectConnectClient::describeLags(), QtAws::AutoScaling::AutoScalingClient::describeLaunchConfigurations(), QtAws::EC2::Ec2Client::describeLaunchTemplates(), QtAws::EC2::Ec2Client::describeLaunchTemplateVersions(), QtAws::OpsWorks::OpsWorksClient::describeLayers(), QtAws::AutoScaling::AutoScalingClient::describeLifecycleHooks(), QtAws::AutoScaling::AutoScalingClient::describeLifecycleHookTypes(), QtAws::Kinesis::KinesisClient::describeLimits(), QtAws::DynamoDB::DynamoDBClient::describeLimits(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeListenerCertificates(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeListeners(), QtAws::DirectConnect::DirectConnectClient::describeLoa(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerAttributes(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeLoadBalancerAttributes(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerPolicies(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancerPolicyTypes(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeLoadBalancers(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeLoadBalancers(), QtAws::AutoScaling::AutoScalingClient::describeLoadBalancers(), QtAws::AutoScaling::AutoScalingClient::describeLoadBalancerTargetGroups(), QtAws::OpsWorks::OpsWorksClient::describeLoadBasedAutoScaling(), QtAws::DirectConnect::DirectConnectClient::describeLocations(), QtAws::Redshift::RedshiftClient::describeLoggingStatus(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeLogGroups(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeLogStreams(), QtAws::CloudHSM::CloudHSMClient::describeLunaClient(), QtAws::StorageGateway::StorageGatewayClient::describeMaintenanceStartTime(), QtAws::SSM::SsmClient::describeMaintenanceWindowExecutions(), QtAws::SSM::SsmClient::describeMaintenanceWindowExecutionTaskInvocations(), QtAws::SSM::SsmClient::describeMaintenanceWindowExecutionTasks(), QtAws::SSM::SsmClient::describeMaintenanceWindows(), QtAws::SSM::SsmClient::describeMaintenanceWindowTargets(), QtAws::SSM::SsmClient::describeMaintenanceWindowTasks(), QtAws::GameLift::GameLiftClient::describeMatchmaking(), QtAws::GameLift::GameLiftClient::describeMatchmakingConfigurations(), QtAws::GameLift::GameLiftClient::describeMatchmakingRuleSets(), QtAws::AutoScaling::AutoScalingClient::describeMetricCollectionTypes(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeMetricFilters(), QtAws::MigrationHub::MigrationHubClient::describeMigrationTask(), QtAws::MachineLearning::MachineLearningClient::describeMLModels(), QtAws::SageMaker::SageMakerClient::describeModel(), QtAws::EFS::EfsClient::describeMountTargets(), QtAws::EFS::EfsClient::describeMountTargetSecurityGroups(), QtAws::EC2::Ec2Client::describeMovingAddresses(), QtAws::OpsWorks::OpsWorksClient::describeMyUserProfile(), QtAws::EC2::Ec2Client::describeNatGateways(), QtAws::EC2::Ec2Client::describeNetworkAcls(), QtAws::EC2::Ec2Client::describeNetworkInterfaceAttribute(), QtAws::EC2::Ec2Client::describeNetworkInterfacePermissions(), QtAws::EC2::Ec2Client::describeNetworkInterfaces(), QtAws::StorageGateway::StorageGatewayClient::describeNFSFileShares(), QtAws::OpsWorksCM::OpsWorksCMClient::describeNodeAssociationStatus(), QtAws::SageMaker::SageMakerClient::describeNotebookInstance(), QtAws::SageMaker::SageMakerClient::describeNotebookInstanceLifecycleConfig(), QtAws::AutoScaling::AutoScalingClient::describeNotificationConfigurations(), QtAws::Budgets::BudgetsClient::describeNotificationsForBudget(), QtAws::WorkDocs::WorkDocsClient::describeNotificationSubscriptions(), QtAws::MediaStoreData::MediaStoreDataClient::describeObject(), QtAws::DataPipeline::DataPipelineClient::describeObjects(), QtAws::OpsWorks::OpsWorksClient::describeOperatingSystems(), QtAws::RDS::RdsClient::describeOptionGroupOptions(), QtAws::RDS::RdsClient::describeOptionGroups(), QtAws::Redshift::RedshiftClient::describeOrderableClusterOptions(), QtAws::RDS::RdsClient::describeOrderableDBInstanceOptions(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeOrderableReplicationInstances(), QtAws::WorkMail::WorkMailClient::describeOrganization(), QtAws::Organizations::OrganizationsClient::describeOrganization(), QtAws::Organizations::OrganizationsClient::describeOrganizationalUnit(), QtAws::MediaPackage::MediaPackageClient::describeOriginEndpoint(), QtAws::DAX::DaxClient::describeParameterGroups(), QtAws::DAX::DaxClient::describeParameters(), QtAws::SSM::SsmClient::describeParameters(), QtAws::SSM::SsmClient::describePatchBaselines(), QtAws::SSM::SsmClient::describePatchGroups(), QtAws::SSM::SsmClient::describePatchGroupState(), QtAws::RDS::RdsClient::describePendingMaintenanceActions(), QtAws::OpsWorks::OpsWorksClient::describePermissions(), QtAws::DataPipeline::DataPipelineClient::describePipelines(), QtAws::EC2::Ec2Client::describePlacementGroups(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::describePlatformVersion(), QtAws::GameLift::GameLiftClient::describePlayerSessions(), QtAws::AutoScaling::AutoScalingClient::describePolicies(), QtAws::Organizations::OrganizationsClient::describePolicy(), QtAws::ServiceCatalog::ServiceCatalogClient::describePortfolio(), QtAws::EC2::Ec2Client::describePrefixLists(), QtAws::EC2::Ec2Client::describePrincipalIdFormat(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProduct(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProductAsAdmin(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProductView(), QtAws::Mobile::MobileClient::describeProject(), QtAws::CodeStar::CodeStarClient::describeProject(), QtAws::Shield::ShieldClient::describeProtection(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProvisionedProduct(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProvisionedProductPlan(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProvisioningArtifact(), QtAws::ServiceCatalog::ServiceCatalogClient::describeProvisioningParameters(), QtAws::CodeCommit::CodeCommitClient::describePullRequestEvents(), QtAws::OpsWorks::OpsWorksClient::describeRaidArrays(), QtAws::OpsWorks::OpsWorksClient::describeRdsDbInstances(), QtAws::SES::SesClient::describeReceiptRule(), QtAws::SES::SesClient::describeReceiptRuleSet(), QtAws::ServiceCatalog::ServiceCatalogClient::describeRecord(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeRefreshSchemasStatus(), QtAws::EC2::Ec2Client::describeRegions(), QtAws::ElastiCache::ElastiCacheClient::describeReplicationGroups(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationInstances(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationInstanceTaskLogs(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationSubnetGroups(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationTaskAssessmentResults(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeReplicationTasks(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::describeReportDefinitions(), QtAws::ECR::EcrClient::describeRepositories(), QtAws::ElastiCache::ElastiCacheClient::describeReservedCacheNodes(), QtAws::ElastiCache::ElastiCacheClient::describeReservedCacheNodesOfferings(), QtAws::RDS::RdsClient::describeReservedDBInstances(), QtAws::RDS::RdsClient::describeReservedDBInstancesOfferings(), QtAws::EC2::Ec2Client::describeReservedInstances(), QtAws::EC2::Ec2Client::describeReservedInstancesListings(), QtAws::EC2::Ec2Client::describeReservedInstancesModifications(), QtAws::EC2::Ec2Client::describeReservedInstancesOfferings(), QtAws::Redshift::RedshiftClient::describeReservedNodeOfferings(), QtAws::Redshift::RedshiftClient::describeReservedNodes(), QtAws::Redshift::RedshiftClient::describeResize(), QtAws::WorkMail::WorkMailClient::describeResource(), QtAws::Inspector::InspectorClient::describeResourceGroups(), QtAws::WorkDocs::WorkDocsClient::describeResourcePermissions(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeResourcePolicies(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeResourceServer(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeRiskConfiguration(), QtAws::IoT::IoTClient::describeRoleAlias(), QtAws::WorkDocs::WorkDocsClient::describeRootFolders(), QtAws::EC2::Ec2Client::describeRouteTables(), QtAws::CloudWatchEvents::CloudWatchEventsClient::describeRule(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeRules(), QtAws::Inspector::InspectorClient::describeRulesPackages(), QtAws::GameLift::GameLiftClient::describeRuntimeConfiguration(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalableTargets(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalingActivities(), QtAws::AutoScaling::AutoScalingClient::describeScalingActivities(), QtAws::CloudSearch::CloudSearchClient::describeScalingParameters(), QtAws::AutoScalingPlans::AutoScalingPlansClient::describeScalingPlanResources(), QtAws::AutoScalingPlans::AutoScalingPlansClient::describeScalingPlans(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScalingPolicies(), QtAws::GameLift::GameLiftClient::describeScalingPolicies(), QtAws::AutoScaling::AutoScalingClient::describeScalingProcessTypes(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::describeScheduledActions(), QtAws::AutoScaling::AutoScalingClient::describeScheduledActions(), QtAws::EC2::Ec2Client::describeScheduledInstanceAvailability(), QtAws::EC2::Ec2Client::describeScheduledInstances(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeSchemas(), QtAws::EMR::EmrClient::describeSecurityConfiguration(), QtAws::EC2::Ec2Client::describeSecurityGroupReferences(), QtAws::EC2::Ec2Client::describeSecurityGroups(), QtAws::OpsWorksCM::OpsWorksCMClient::describeServers(), QtAws::CloudSearch::CloudSearchClient::describeServiceAccessPolicies(), QtAws::OpsWorks::OpsWorksClient::describeServiceErrors(), QtAws::Pricing::PricingClient::describeServices(), QtAws::Support::SupportClient::describeServices(), QtAws::ECS::EcsClient::describeServices(), QtAws::AppStream::AppStreamClient::describeSessions(), QtAws::Support::SupportClient::describeSeverityLevels(), QtAws::EC2::Ec2Client::describeSnapshotAttribute(), QtAws::Redshift::RedshiftClient::describeSnapshotCopyGrants(), QtAws::DirectoryService::DirectoryServiceClient::describeSnapshots(), QtAws::ElastiCache::ElastiCacheClient::describeSnapshots(), QtAws::EC2::Ec2Client::describeSnapshots(), QtAws::StorageGateway::StorageGatewayClient::describeSnapshotSchedule(), QtAws::RDS::RdsClient::describeSourceRegions(), QtAws::EC2::Ec2Client::describeSpotDatafeedSubscription(), QtAws::EC2::Ec2Client::describeSpotFleetInstances(), QtAws::EC2::Ec2Client::describeSpotFleetRequestHistory(), QtAws::EC2::Ec2Client::describeSpotFleetRequests(), QtAws::EC2::Ec2Client::describeSpotInstanceRequests(), QtAws::EC2::Ec2Client::describeSpotPriceHistory(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeSSLPolicies(), QtAws::CloudFormation::CloudFormationClient::describeStackEvents(), QtAws::CloudFormation::CloudFormationClient::describeStackInstance(), QtAws::OpsWorks::OpsWorksClient::describeStackProvisioningParameters(), QtAws::CloudFormation::CloudFormationClient::describeStackResource(), QtAws::CloudFormation::CloudFormationClient::describeStackResources(), QtAws::AppStream::AppStreamClient::describeStacks(), QtAws::CloudFormation::CloudFormationClient::describeStacks(), QtAws::OpsWorks::OpsWorksClient::describeStacks(), QtAws::CloudFormation::CloudFormationClient::describeStackSet(), QtAws::CloudFormation::CloudFormationClient::describeStackSetOperation(), QtAws::OpsWorks::OpsWorksClient::describeStackSummary(), QtAws::EC2::Ec2Client::describeStaleSecurityGroups(), QtAws::SFN::SfnClient::describeStateMachine(), QtAws::SFN::SfnClient::describeStateMachineForExecution(), QtAws::EMR::EmrClient::describeStep(), QtAws::StorageGateway::StorageGatewayClient::describeStorediSCSIVolumes(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::describeStream(), QtAws::KinesisVideo::KinesisVideoClient::describeStream(), QtAws::Kinesis::KinesisClient::describeStream(), QtAws::IoT::IoTClient::describeStream(), QtAws::Rekognition::RekognitionClient::describeStreamProcessor(), QtAws::Kinesis::KinesisClient::describeStreamSummary(), QtAws::DAX::DaxClient::describeSubnetGroups(), QtAws::EC2::Ec2Client::describeSubnets(), QtAws::Budgets::BudgetsClient::describeSubscribersForNotification(), QtAws::Shield::ShieldClient::describeSubscription(), QtAws::CloudWatchLogs::CloudWatchLogsClient::describeSubscriptionFilters(), QtAws::CloudSearch::CloudSearchClient::describeSuggesters(), QtAws::DynamoDB::DynamoDBClient::describeTable(), QtAws::Redshift::RedshiftClient::describeTableRestoreStatus(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::describeTableStatistics(), QtAws::ServiceCatalog::ServiceCatalogClient::describeTagOption(), QtAws::EFS::EfsClient::describeTags(), QtAws::WorkSpaces::WorkSpacesClient::describeTags(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::describeTags(), QtAws::MachineLearning::MachineLearningClient::describeTags(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::describeTags(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTags(), QtAws::DirectConnect::DirectConnectClient::describeTags(), QtAws::AutoScaling::AutoScalingClient::describeTags(), QtAws::Redshift::RedshiftClient::describeTags(), QtAws::EC2::Ec2Client::describeTags(), QtAws::StorageGateway::StorageGatewayClient::describeTapeArchives(), QtAws::StorageGateway::StorageGatewayClient::describeTapeRecoveryPoints(), QtAws::StorageGateway::StorageGatewayClient::describeTapes(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetGroupAttributes(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetGroups(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::describeTargetHealth(), QtAws::ECS::EcsClient::describeTaskDefinition(), QtAws::ECS::EcsClient::describeTasks(), QtAws::AutoScaling::AutoScalingClient::describeTerminationPolicyTypes(), QtAws::IoT::IoTClient::describeThing(), QtAws::IoT::IoTClient::describeThingGroup(), QtAws::IoT::IoTClient::describeThingRegistrationTask(), QtAws::IoT::IoTClient::describeThingType(), QtAws::OpsWorks::OpsWorksClient::describeTimeBasedAutoScaling(), QtAws::DynamoDB::DynamoDBClient::describeTimeToLive(), QtAws::Comprehend::ComprehendClient::describeTopicsDetectionJob(), QtAws::CloudTrail::CloudTrailClient::describeTrails(), QtAws::SageMaker::SageMakerClient::describeTrainingJob(), QtAws::Support::SupportClient::describeTrustedAdvisorCheckRefreshStatuses(), QtAws::Support::SupportClient::describeTrustedAdvisorCheckResult(), QtAws::Support::SupportClient::describeTrustedAdvisorChecks(), QtAws::Support::SupportClient::describeTrustedAdvisorCheckSummaries(), QtAws::DirectoryService::DirectoryServiceClient::describeTrusts(), QtAws::StorageGateway::StorageGatewayClient::describeUploadBuffer(), QtAws::MQ::MqClient::describeUser(), QtAws::WorkMail::WorkMailClient::describeUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserImportJob(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPoolClient(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::describeUserPoolDomain(), QtAws::CodeStar::CodeStarClient::describeUserProfile(), QtAws::OpsWorks::OpsWorksClient::describeUserProfiles(), QtAws::WorkDocs::WorkDocsClient::describeUsers(), QtAws::RDS::RdsClient::describeValidDBInstanceModifications(), QtAws::Glacier::GlacierClient::describeVault(), QtAws::DirectConnect::DirectConnectClient::describeVirtualGateways(), QtAws::DirectConnect::DirectConnectClient::describeVirtualInterfaces(), QtAws::Polly::PollyClient::describeVoices(), QtAws::EC2::Ec2Client::describeVolumeAttribute(), QtAws::OpsWorks::OpsWorksClient::describeVolumes(), QtAws::EC2::Ec2Client::describeVolumes(), QtAws::EC2::Ec2Client::describeVolumesModifications(), QtAws::EC2::Ec2Client::describeVolumeStatus(), QtAws::EC2::Ec2Client::describeVpcAttribute(), QtAws::EC2::Ec2Client::describeVpcClassicLink(), QtAws::EC2::Ec2Client::describeVpcClassicLinkDnsSupport(), QtAws::EC2::Ec2Client::describeVpcEndpointConnectionNotifications(), QtAws::EC2::Ec2Client::describeVpcEndpointConnections(), QtAws::EC2::Ec2Client::describeVpcEndpoints(), QtAws::EC2::Ec2Client::describeVpcEndpointServiceConfigurations(), QtAws::EC2::Ec2Client::describeVpcEndpointServicePermissions(), QtAws::EC2::Ec2Client::describeVpcEndpointServices(), QtAws::GameLift::GameLiftClient::describeVpcPeeringAuthorizations(), QtAws::GameLift::GameLiftClient::describeVpcPeeringConnections(), QtAws::EC2::Ec2Client::describeVpcPeeringConnections(), QtAws::EC2::Ec2Client::describeVpcs(), QtAws::EC2::Ec2Client::describeVpnConnections(), QtAws::EC2::Ec2Client::describeVpnGateways(), QtAws::StorageGateway::StorageGatewayClient::describeVTLDevices(), QtAws::SWF::SwfClient::describeWorkflowExecution(), QtAws::SWF::SwfClient::describeWorkflowType(), QtAws::StorageGateway::StorageGatewayClient::describeWorkingStorage(), QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaceBundles(), QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaceDirectories(), QtAws::WorkSpaces::WorkSpacesClient::describeWorkspaces(), QtAws::WorkSpaces::WorkSpacesClient::describeWorkspacesConnectionStatus(), QtAws::EC2::Ec2Client::detachClassicLinkVpc(), QtAws::Lightsail::LightsailClient::detachDisk(), QtAws::OpsWorks::OpsWorksClient::detachElasticLoadBalancer(), QtAws::CloudDirectory::CloudDirectoryClient::detachFromIndex(), QtAws::IAM::IamClient::detachGroupPolicy(), QtAws::AutoScaling::AutoScalingClient::detachInstances(), QtAws::Lightsail::LightsailClient::detachInstancesFromLoadBalancer(), QtAws::EC2::Ec2Client::detachInternetGateway(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::detachLoadBalancerFromSubnets(), QtAws::AutoScaling::AutoScalingClient::detachLoadBalancers(), QtAws::AutoScaling::AutoScalingClient::detachLoadBalancerTargetGroups(), QtAws::EC2::Ec2Client::detachNetworkInterface(), QtAws::CloudDirectory::CloudDirectoryClient::detachObject(), QtAws::Organizations::OrganizationsClient::detachPolicy(), QtAws::CloudDirectory::CloudDirectoryClient::detachPolicy(), QtAws::IoT::IoTClient::detachPolicy(), QtAws::IoT::IoTClient::detachPrincipalPolicy(), QtAws::IAM::IamClient::detachRolePolicy(), QtAws::Lightsail::LightsailClient::detachStaticIp(), QtAws::IoT::IoTClient::detachThingPrincipal(), QtAws::CloudDirectory::CloudDirectoryClient::detachTypedLink(), QtAws::IAM::IamClient::detachUserPolicy(), QtAws::EC2::Ec2Client::detachVolume(), QtAws::EC2::Ec2Client::detachVpnGateway(), QtAws::Comprehend::ComprehendClient::detectDominantLanguage(), QtAws::Comprehend::ComprehendClient::detectEntities(), QtAws::Rekognition::RekognitionClient::detectFaces(), QtAws::Comprehend::ComprehendClient::detectKeyPhrases(), QtAws::Rekognition::RekognitionClient::detectLabels(), QtAws::Rekognition::RekognitionClient::detectModerationLabels(), QtAws::Comprehend::ComprehendClient::detectSentiment(), QtAws::Rekognition::RekognitionClient::detectText(), QtAws::CloudWatch::CloudWatchClient::disableAlarmActions(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::disableAvailabilityZonesForLoadBalancer(), QtAws::Organizations::OrganizationsClient::disableAWSServiceAccess(), QtAws::CloudDirectory::CloudDirectoryClient::disableDirectory(), QtAws::Route53Domains::Route53DomainsClient::disableDomainAutoRenew(), QtAws::Route53Domains::Route53DomainsClient::disableDomainTransferLock(), QtAws::Kinesis::KinesisClient::disableEnhancedMonitoring(), QtAws::StorageGateway::StorageGatewayClient::disableGateway(), QtAws::KMS::KmsClient::disableKey(), QtAws::KMS::KmsClient::disableKeyRotation(), QtAws::Redshift::RedshiftClient::disableLogging(), QtAws::AutoScaling::AutoScalingClient::disableMetricsCollection(), QtAws::Organizations::OrganizationsClient::disablePolicyType(), QtAws::DirectoryService::DirectoryServiceClient::disableRadius(), QtAws::CloudWatchEvents::CloudWatchEventsClient::disableRule(), QtAws::Redshift::RedshiftClient::disableSnapshotCopy(), QtAws::DirectoryService::DirectoryServiceClient::disableSso(), QtAws::CodePipeline::CodePipelineClient::disableStageTransition(), QtAws::IoT::IoTClient::disableTopicRule(), QtAws::EC2::Ec2Client::disableVgwRoutePropagation(), QtAws::EC2::Ec2Client::disableVpcClassicLink(), QtAws::EC2::Ec2Client::disableVpcClassicLinkDnsSupport(), QtAws::EC2::Ec2Client::disassociateAddress(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::disassociateConfigurationItemsFromApplication(), QtAws::DirectConnect::DirectConnectClient::disassociateConnectionFromLag(), QtAws::SMS::SmsClient::disassociateConnector(), QtAws::MigrationHub::MigrationHubClient::disassociateCreatedArtifact(), QtAws::WorkMail::WorkMailClient::disassociateDelegateFromResource(), QtAws::AlexaForBusiness::AlexaForBusinessClient::disassociateDeviceFromRoom(), QtAws::MigrationHub::MigrationHubClient::disassociateDiscoveredResource(), QtAws::OpsWorks::OpsWorksClient::disassociateElasticIp(), QtAws::AppStream::AppStreamClient::disassociateFleet(), QtAws::GuardDuty::GuardDutyClient::disassociateFromMasterAccount(), QtAws::EC2::Ec2Client::disassociateIamInstanceProfile(), QtAws::CloudWatchLogs::CloudWatchLogsClient::disassociateKmsKey(), QtAws::WorkMail::WorkMailClient::disassociateMemberFromGroup(), QtAws::GuardDuty::GuardDutyClient::disassociateMembers(), QtAws::OpsWorksCM::OpsWorksCMClient::disassociateNode(), QtAws::ServiceCatalog::ServiceCatalogClient::disassociatePrincipalFromPortfolio(), QtAws::ServiceCatalog::ServiceCatalogClient::disassociateProductFromPortfolio(), QtAws::MTurk::MTurkClient::disassociateQualificationFromWorker(), QtAws::Greengrass::GreengrassClient::disassociateRoleFromGroup(), QtAws::EC2::Ec2Client::disassociateRouteTable(), QtAws::Greengrass::GreengrassClient::disassociateServiceRoleFromAccount(), QtAws::AlexaForBusiness::AlexaForBusinessClient::disassociateSkillGroupFromRoom(), QtAws::EC2::Ec2Client::disassociateSubnetCidrBlock(), QtAws::ServiceCatalog::ServiceCatalogClient::disassociateTagOptionFromResource(), QtAws::CodeStar::CodeStarClient::disassociateTeamMember(), QtAws::EC2::Ec2Client::disassociateVpcCidrBlock(), QtAws::Route53::Route53Client::disassociateVPCFromHostedZone(), QtAws::WAFRegional::WAFRegionalClient::disassociateWebACL(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::discoverInputSchema(), QtAws::ECS::EcsClient::discoverPollEndpoint(), QtAws::SimpleDB::SimpleDBClient::domainMetadata(), QtAws::RDS::RdsClient::downloadDBLogFilePortion(), QtAws::Lightsail::LightsailClient::downloadDefaultKeyPair(), QtAws::CloudWatch::CloudWatchClient::enableAlarmActions(), QtAws::Organizations::OrganizationsClient::enableAllFeatures(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::enableAvailabilityZonesForLoadBalancer(), QtAws::Organizations::OrganizationsClient::enableAWSServiceAccess(), QtAws::CloudDirectory::CloudDirectoryClient::enableDirectory(), QtAws::Route53Domains::Route53DomainsClient::enableDomainAutoRenew(), QtAws::Route53Domains::Route53DomainsClient::enableDomainTransferLock(), QtAws::Kinesis::KinesisClient::enableEnhancedMonitoring(), QtAws::KMS::KmsClient::enableKey(), QtAws::KMS::KmsClient::enableKeyRotation(), QtAws::Redshift::RedshiftClient::enableLogging(), QtAws::AutoScaling::AutoScalingClient::enableMetricsCollection(), QtAws::IAM::IamClient::enableMFADevice(), QtAws::Organizations::OrganizationsClient::enablePolicyType(), QtAws::DirectoryService::DirectoryServiceClient::enableRadius(), QtAws::CloudWatchEvents::CloudWatchEventsClient::enableRule(), QtAws::Redshift::RedshiftClient::enableSnapshotCopy(), QtAws::DirectoryService::DirectoryServiceClient::enableSso(), QtAws::CodePipeline::CodePipelineClient::enableStageTransition(), QtAws::IoT::IoTClient::enableTopicRule(), QtAws::EC2::Ec2Client::enableVgwRoutePropagation(), QtAws::EC2::Ec2Client::enableVolumeIO(), QtAws::EC2::Ec2Client::enableVpcClassicLink(), QtAws::EC2::Ec2Client::enableVpcClassicLinkDnsSupport(), QtAws::KMS::KmsClient::encrypt(), QtAws::AutoScaling::AutoScalingClient::enterStandby(), QtAws::CloudFormation::CloudFormationClient::estimateTemplateCost(), QtAws::DataPipeline::DataPipelineClient::evaluateExpression(), QtAws::CloudFormation::CloudFormationClient::executeChangeSet(), QtAws::AutoScaling::AutoScalingClient::executePolicy(), QtAws::ServiceCatalog::ServiceCatalogClient::executeProvisionedProductPlan(), QtAws::AutoScaling::AutoScalingClient::exitStandby(), QtAws::AppStream::AppStreamClient::expireSession(), QtAws::Mobile::MobileClient::exportBundle(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::exportConfigurations(), QtAws::Mobile::MobileClient::exportProject(), QtAws::RDS::RdsClient::failoverDBCluster(), QtAws::CloudWatchLogs::CloudWatchLogsClient::filterLogEvents(), QtAws::APIGateway::APIGatewayClient::flushStageAuthorizersCache(), QtAws::APIGateway::APIGatewayClient::flushStageCache(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::forgetDevice(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::forgotPassword(), QtAws::APIGateway::APIGatewayClient::generateClientCertificate(), QtAws::IAM::IamClient::generateCredentialReport(), QtAws::KMS::KmsClient::generateDataKey(), QtAws::KMS::KmsClient::generateDataKeyWithoutPlaintext(), QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::generateDataSet(), QtAws::KMS::KmsClient::generateRandom(), QtAws::IAM::IamClient::getAccessKeyLastUsed(), QtAws::APIGateway::APIGatewayClient::getAccount(), QtAws::IAM::IamClient::getAccountAuthorizationDetails(), QtAws::MTurk::MTurkClient::getAccountBalance(), QtAws::Route53::Route53Client::getAccountLimit(), QtAws::IAM::IamClient::getAccountPasswordPolicy(), QtAws::SES::SesClient::getAccountSendingEnabled(), QtAws::Lambda::LambdaClient::getAccountSettings(), QtAws::DeviceFarm::DeviceFarmClient::getAccountSettings(), QtAws::IAM::IamClient::getAccountSummary(), QtAws::Lightsail::LightsailClient::getActiveNames(), QtAws::SFN::SfnClient::getActivityTask(), QtAws::Pinpoint::PinpointClient::getAdmChannel(), QtAws::Lambda::LambdaClient::getAlias(), QtAws::APIGateway::APIGatewayClient::getApiKey(), QtAws::APIGateway::APIGatewayClient::getApiKeys(), QtAws::Pinpoint::PinpointClient::getApnsChannel(), QtAws::Pinpoint::PinpointClient::getApnsSandboxChannel(), QtAws::Pinpoint::PinpointClient::getApnsVoipChannel(), QtAws::Pinpoint::PinpointClient::getApnsVoipSandboxChannel(), QtAws::Pinpoint::PinpointClient::getApp(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::getApplication(), QtAws::CodeDeploy::CodeDeployClient::getApplication(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::getApplicationPolicy(), QtAws::CodeDeploy::CodeDeployClient::getApplicationRevision(), QtAws::Pinpoint::PinpointClient::getApplicationSettings(), QtAws::CloudDirectory::CloudDirectoryClient::getAppliedSchemaVersion(), QtAws::Pinpoint::PinpointClient::getApps(), QtAws::Inspector::InspectorClient::getAssessmentReport(), QtAws::MTurk::MTurkClient::getAssignment(), QtAws::Greengrass::GreengrassClient::getAssociatedRole(), QtAws::SimpleDB::SimpleDBClient::getAttributes(), QtAws::Pricing::PricingClient::getAttributeValues(), QtAws::ECR::EcrClient::getAuthorizationToken(), QtAws::APIGateway::APIGatewayClient::getAuthorizer(), QtAws::APIGateway::APIGatewayClient::getAuthorizers(), QtAws::SSM::SsmClient::getAutomationExecution(), QtAws::Pinpoint::PinpointClient::getBaiduChannel(), QtAws::APIGateway::APIGatewayClient::getBasePathMapping(), QtAws::APIGateway::APIGatewayClient::getBasePathMappings(), QtAws::MachineLearning::MachineLearningClient::getBatchPrediction(), QtAws::CodeCommit::CodeCommitClient::getBlob(), QtAws::Lightsail::LightsailClient::getBlueprints(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBot(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotAlias(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotAliases(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotChannelAssociation(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotChannelAssociations(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBots(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotVersions(), QtAws::CodeCommit::CodeCommitClient::getBranch(), QtAws::S3::S3Client::getBucketAccelerateConfiguration(), QtAws::S3::S3Client::getBucketAcl(), QtAws::S3::S3Client::getBucketAnalyticsConfiguration(), QtAws::S3::S3Client::getBucketCors(), QtAws::S3::S3Client::getBucketEncryption(), QtAws::S3::S3Client::getBucketInventoryConfiguration(), QtAws::S3::S3Client::getBucketLifecycle(), QtAws::S3::S3Client::getBucketLifecycleConfiguration(), QtAws::S3::S3Client::getBucketLocation(), QtAws::S3::S3Client::getBucketLogging(), QtAws::S3::S3Client::getBucketMetricsConfiguration(), QtAws::S3::S3Client::getBucketNotification(), QtAws::S3::S3Client::getBucketNotificationConfiguration(), QtAws::S3::S3Client::getBucketPolicy(), QtAws::S3::S3Client::getBucketReplication(), QtAws::S3::S3Client::getBucketRequestPayment(), QtAws::S3::S3Client::getBucketTagging(), QtAws::S3::S3Client::getBucketVersioning(), QtAws::S3::S3Client::getBucketWebsite(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinIntent(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinIntents(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinSlotTypes(), QtAws::CognitoSync::CognitoSyncClient::getBulkPublishDetails(), QtAws::Lightsail::LightsailClient::getBundles(), QtAws::WAF::WafClient::getByteMatchSet(), QtAws::WAFRegional::WAFRegionalClient::getByteMatchSet(), QtAws::STS::StsClient::getCallerIdentity(), QtAws::Pinpoint::PinpointClient::getCampaign(), QtAws::Pinpoint::PinpointClient::getCampaignActivities(), QtAws::Pinpoint::PinpointClient::getCampaigns(), QtAws::Pinpoint::PinpointClient::getCampaignVersion(), QtAws::Pinpoint::PinpointClient::getCampaignVersions(), QtAws::Glue::GlueClient::getCatalogImportStatus(), QtAws::Rekognition::RekognitionClient::getCelebrityInfo(), QtAws::Rekognition::RekognitionClient::getCelebrityRecognition(), QtAws::ACM::AcmClient::getCertificate(), QtAws::Route53::Route53Client::getChange(), QtAws::WAF::WafClient::getChangeToken(), QtAws::WAFRegional::WAFRegionalClient::getChangeToken(), QtAws::WAF::WafClient::getChangeTokenStatus(), QtAws::WAFRegional::WAFRegionalClient::getChangeTokenStatus(), QtAws::Route53::Route53Client::getCheckerIpRanges(), QtAws::Glue::GlueClient::getClassifier(), QtAws::Glue::GlueClient::getClassifiers(), QtAws::APIGateway::APIGatewayClient::getClientCertificate(), QtAws::APIGateway::APIGatewayClient::getClientCertificates(), QtAws::CloudFront::CloudFrontClient::getCloudFrontOriginAccessIdentity(), QtAws::CloudFront::CloudFrontClient::getCloudFrontOriginAccessIdentityConfig(), QtAws::Redshift::RedshiftClient::getClusterCredentials(), QtAws::CognitoSync::CognitoSyncClient::getCognitoEvents(), QtAws::SSM::SsmClient::getCommandInvocation(), QtAws::CodeCommit::CodeCommitClient::getComment(), QtAws::CodeCommit::CodeCommitClient::getCommentsForComparedCommit(), QtAws::CodeCommit::CodeCommitClient::getCommentsForPullRequest(), QtAws::CodeCommit::CodeCommitClient::getCommit(), QtAws::ConfigService::ConfigServiceClient::getComplianceDetailsByConfigRule(), QtAws::ConfigService::ConfigServiceClient::getComplianceDetailsByResource(), QtAws::ConfigService::ConfigServiceClient::getComplianceSummaryByConfigRule(), QtAws::ConfigService::ConfigServiceClient::getComplianceSummaryByResourceType(), QtAws::CloudHSM::CloudHSMClient::getConfig(), QtAws::Glue::GlueClient::getConnection(), QtAws::Glue::GlueClient::getConnections(), QtAws::Greengrass::GreengrassClient::getConnectivityInfo(), QtAws::SMS::SmsClient::getConnectors(), QtAws::EC2::Ec2Client::getConsoleOutput(), QtAws::EC2::Ec2Client::getConsoleScreenshot(), QtAws::Route53Domains::Route53DomainsClient::getContactReachabilityStatus(), QtAws::MediaStore::MediaStoreClient::getContainerPolicy(), QtAws::Rekognition::RekognitionClient::getContentModeration(), QtAws::IAM::IamClient::getContextKeysForCustomPolicy(), QtAws::IAM::IamClient::getContextKeysForPrincipalPolicy(), QtAws::Greengrass::GreengrassClient::getCoreDefinition(), QtAws::Greengrass::GreengrassClient::getCoreDefinitionVersion(), QtAws::MediaStore::MediaStoreClient::getCorsPolicy(), QtAws::CostExplorer::CostExplorerClient::getCostAndUsage(), QtAws::Glue::GlueClient::getCrawler(), QtAws::Glue::GlueClient::getCrawlerMetrics(), QtAws::Glue::GlueClient::getCrawlers(), QtAws::IAM::IamClient::getCredentialReport(), QtAws::CognitoIdentity::CognitoIdentityClient::getCredentialsForIdentity(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getCSVHeader(), QtAws::WorkDocs::WorkDocsClient::getCurrentUser(), QtAws::SES::SesClient::getCustomVerificationEmailTemplate(), QtAws::CloudWatch::CloudWatchClient::getDashboard(), QtAws::Glue::GlueClient::getDatabase(), QtAws::Glue::GlueClient::getDatabases(), QtAws::KinesisVideo::KinesisVideoClient::getDataEndpoint(), QtAws::Glue::GlueClient::getDataflowGraph(), QtAws::Glacier::GlacierClient::getDataRetrievalPolicy(), QtAws::AppSync::AppSyncClient::getDataSource(), QtAws::MachineLearning::MachineLearningClient::getDataSource(), QtAws::SSM::SsmClient::getDefaultPatchBaseline(), QtAws::SSM::SsmClient::getDeployablePatchSnapshotForInstance(), QtAws::CodeDeploy::CodeDeployClient::getDeployment(), QtAws::APIGateway::APIGatewayClient::getDeployment(), QtAws::CodeDeploy::CodeDeployClient::getDeploymentConfig(), QtAws::CodeDeploy::CodeDeployClient::getDeploymentGroup(), QtAws::CodeDeploy::CodeDeployClient::getDeploymentInstance(), QtAws::APIGateway::APIGatewayClient::getDeployments(), QtAws::Greengrass::GreengrassClient::getDeploymentStatus(), QtAws::GuardDuty::GuardDutyClient::getDetector(), QtAws::Glue::GlueClient::getDevEndpoint(), QtAws::Glue::GlueClient::getDevEndpoints(), QtAws::AlexaForBusiness::AlexaForBusinessClient::getDevice(), QtAws::DeviceFarm::DeviceFarmClient::getDevice(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getDevice(), QtAws::Greengrass::GreengrassClient::getDeviceDefinition(), QtAws::Greengrass::GreengrassClient::getDeviceDefinitionVersion(), QtAws::DeviceFarm::DeviceFarmClient::getDevicePool(), QtAws::DeviceFarm::DeviceFarmClient::getDevicePoolCompatibility(), QtAws::CodeCommit::CodeCommitClient::getDifferences(), QtAws::CostExplorer::CostExplorerClient::getDimensionValues(), QtAws::CloudDirectory::CloudDirectoryClient::getDirectory(), QtAws::DirectoryService::DirectoryServiceClient::getDirectoryLimits(), QtAws::ConfigService::ConfigServiceClient::getDiscoveredResourceCounts(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::getDiscoverySummary(), QtAws::Lightsail::LightsailClient::getDisk(), QtAws::Lightsail::LightsailClient::getDisks(), QtAws::Lightsail::LightsailClient::getDiskSnapshot(), QtAws::Lightsail::LightsailClient::getDiskSnapshots(), QtAws::CloudFront::CloudFrontClient::getDistribution(), QtAws::CloudFront::CloudFrontClient::getDistributionConfig(), QtAws::WorkDocs::WorkDocsClient::getDocument(), QtAws::SSM::SsmClient::getDocument(), QtAws::APIGateway::APIGatewayClient::getDocumentationPart(), QtAws::APIGateway::APIGatewayClient::getDocumentationParts(), QtAws::APIGateway::APIGatewayClient::getDocumentationVersion(), QtAws::APIGateway::APIGatewayClient::getDocumentationVersions(), QtAws::WorkDocs::WorkDocsClient::getDocumentPath(), QtAws::WorkDocs::WorkDocsClient::getDocumentVersion(), QtAws::Lightsail::LightsailClient::getDomain(), QtAws::Route53Domains::Route53DomainsClient::getDomainDetail(), QtAws::APIGateway::APIGatewayClient::getDomainName(), QtAws::APIGateway::APIGatewayClient::getDomainNames(), QtAws::Lightsail::LightsailClient::getDomains(), QtAws::Route53Domains::Route53DomainsClient::getDomainSuggestions(), QtAws::ECR::EcrClient::getDownloadUrlForLayer(), QtAws::IoT::IoTClient::getEffectivePolicies(), QtAws::Pinpoint::PinpointClient::getEmailChannel(), QtAws::Pinpoint::PinpointClient::getEndpoint(), QtAws::SNS::SnsClient::getEndpointAttributes(), QtAws::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::getEntitlements(), QtAws::MachineLearning::MachineLearningClient::getEvaluation(), QtAws::CloudTrail::CloudTrailClient::getEventSelectors(), QtAws::Lambda::LambdaClient::getEventSourceMapping(), QtAws::Pinpoint::PinpointClient::getEventStream(), QtAws::SFN::SfnClient::getExecutionHistory(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getExport(), QtAws::APIGateway::APIGatewayClient::getExport(), QtAws::Pinpoint::PinpointClient::getExportJob(), QtAws::Pinpoint::PinpointClient::getExportJobs(), QtAws::Rekognition::RekognitionClient::getFaceDetection(), QtAws::Rekognition::RekognitionClient::getFaceSearch(), QtAws::CloudDirectory::CloudDirectoryClient::getFacet(), QtAws::STS::StsClient::getFederationToken(), QtAws::MTurk::MTurkClient::getFileUploadURL(), QtAws::GuardDuty::GuardDutyClient::getFindings(), QtAws::GuardDuty::GuardDutyClient::getFindingsStatistics(), QtAws::WorkDocs::WorkDocsClient::getFolder(), QtAws::WorkDocs::WorkDocsClient::getFolderPath(), QtAws::Lambda::LambdaClient::getFunction(), QtAws::Lambda::LambdaClient::getFunctionConfiguration(), QtAws::Greengrass::GreengrassClient::getFunctionDefinition(), QtAws::Greengrass::GreengrassClient::getFunctionDefinitionVersion(), QtAws::GameLift::GameLiftClient::getGameSessionLogUrl(), QtAws::APIGateway::APIGatewayClient::getGatewayResponse(), QtAws::APIGateway::APIGatewayClient::getGatewayResponses(), QtAws::Pinpoint::PinpointClient::getGcmChannel(), QtAws::Route53::Route53Client::getGeoLocation(), QtAws::WAF::WafClient::getGeoMatchSet(), QtAws::WAFRegional::WAFRegionalClient::getGeoMatchSet(), QtAws::AppSync::AppSyncClient::getGraphqlApi(), QtAws::ResourceGroups::ResourceGroupsClient::getGroup(), QtAws::Greengrass::GreengrassClient::getGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getGroup(), QtAws::IAM::IamClient::getGroup(), QtAws::Greengrass::GreengrassClient::getGroupCertificateAuthority(), QtAws::Greengrass::GreengrassClient::getGroupCertificateConfiguration(), QtAws::IAM::IamClient::getGroupPolicy(), QtAws::ResourceGroups::ResourceGroupsClient::getGroupQuery(), QtAws::Greengrass::GreengrassClient::getGroupVersion(), QtAws::Route53::Route53Client::getHealthCheck(), QtAws::Route53::Route53Client::getHealthCheckCount(), QtAws::Route53::Route53Client::getHealthCheckLastFailureReason(), QtAws::Route53::Route53Client::getHealthCheckStatus(), QtAws::MTurk::MTurkClient::getHIT(), QtAws::Route53::Route53Client::getHostedZone(), QtAws::Route53::Route53Client::getHostedZoneCount(), QtAws::Route53::Route53Client::getHostedZoneLimit(), QtAws::OpsWorks::OpsWorksClient::getHostnameSuggestion(), QtAws::EC2::Ec2Client::getHostReservationPurchasePreview(), QtAws::CognitoIdentity::CognitoIdentityClient::getId(), QtAws::SES::SesClient::getIdentityDkimAttributes(), QtAws::SES::SesClient::getIdentityMailFromDomainAttributes(), QtAws::SES::SesClient::getIdentityNotificationAttributes(), QtAws::SES::SesClient::getIdentityPolicies(), QtAws::CognitoSync::CognitoSyncClient::getIdentityPoolConfiguration(), QtAws::CognitoIdentity::CognitoIdentityClient::getIdentityPoolRoles(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getIdentityProviderByIdentifier(), QtAws::SES::SesClient::getIdentityVerificationAttributes(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getImport(), QtAws::Pinpoint::PinpointClient::getImportJob(), QtAws::Pinpoint::PinpointClient::getImportJobs(), QtAws::IoT::IoTClient::getIndexingConfiguration(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::getInstance(), QtAws::Lightsail::LightsailClient::getInstance(), QtAws::GameLift::GameLiftClient::getInstanceAccess(), QtAws::Lightsail::LightsailClient::getInstanceAccessDetails(), QtAws::Lightsail::LightsailClient::getInstanceMetricData(), QtAws::Lightsail::LightsailClient::getInstancePortStates(), QtAws::IAM::IamClient::getInstanceProfile(), QtAws::Lightsail::LightsailClient::getInstances(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::getInstancesHealthStatus(), QtAws::Lightsail::LightsailClient::getInstanceSnapshot(), QtAws::Lightsail::LightsailClient::getInstanceSnapshots(), QtAws::Lightsail::LightsailClient::getInstanceState(), QtAws::APIGateway::APIGatewayClient::getIntegration(), QtAws::APIGateway::APIGatewayClient::getIntegrationResponse(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntent(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntents(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntentVersions(), QtAws::AppSync::AppSyncClient::getIntrospectionSchema(), QtAws::CloudFront::CloudFrontClient::getInvalidation(), QtAws::SSM::SsmClient::getInventory(), QtAws::SSM::SsmClient::getInventorySchema(), QtAws::GuardDuty::GuardDutyClient::getInvitationsCount(), QtAws::GuardDuty::GuardDutyClient::getIPSet(), QtAws::WAF::WafClient::getIPSet(), QtAws::WAFRegional::WAFRegionalClient::getIPSet(), QtAws::DynamoDB::DynamoDBClient::getItem(), QtAws::MediaConvert::MediaConvertClient::getJob(), QtAws::DeviceFarm::DeviceFarmClient::getJob(), QtAws::Glue::GlueClient::getJob(), QtAws::CodePipeline::CodePipelineClient::getJobDetails(), QtAws::IoT::IoTClient::getJobDocument(), QtAws::Snowball::SnowballClient::getJobManifest(), QtAws::Glacier::GlacierClient::getJobOutput(), QtAws::Glue::GlueClient::getJobRun(), QtAws::Glue::GlueClient::getJobRuns(), QtAws::Glue::GlueClient::getJobs(), QtAws::MediaConvert::MediaConvertClient::getJobTemplate(), QtAws::Snowball::SnowballClient::getJobUnlockCode(), QtAws::Lightsail::LightsailClient::getKeyPair(), QtAws::Lightsail::LightsailClient::getKeyPairs(), QtAws::KMS::KmsClient::getKeyPolicy(), QtAws::KMS::KmsClient::getKeyRotationStatus(), QtAws::Rekognition::RekognitionClient::getLabelDetection(), QtAws::EC2::Ec2Client::getLaunchTemplateData(), QtAws::Polly::PollyClient::getLexicon(), QtAws::ECR::EcrClient::getLifecyclePolicy(), QtAws::ECR::EcrClient::getLifecyclePolicyPreview(), QtAws::Lightsail::LightsailClient::getLoadBalancer(), QtAws::Lightsail::LightsailClient::getLoadBalancerMetricData(), QtAws::Lightsail::LightsailClient::getLoadBalancers(), QtAws::Lightsail::LightsailClient::getLoadBalancerTlsCertificates(), QtAws::CloudWatchLogs::CloudWatchLogsClient::getLogEvents(), QtAws::Greengrass::GreengrassClient::getLoggerDefinition(), QtAws::Greengrass::GreengrassClient::getLoggerDefinitionVersion(), QtAws::IoT::IoTClient::getLoggingOptions(), QtAws::IAM::IamClient::getLoginProfile(), QtAws::SSM::SsmClient::getMaintenanceWindow(), QtAws::SSM::SsmClient::getMaintenanceWindowExecution(), QtAws::SSM::SsmClient::getMaintenanceWindowExecutionTask(), QtAws::SSM::SsmClient::getMaintenanceWindowExecutionTaskInvocation(), QtAws::SSM::SsmClient::getMaintenanceWindowTask(), QtAws::Glue::GlueClient::getMapping(), QtAws::GuardDuty::GuardDutyClient::getMasterAccount(), QtAws::KinesisVideoMedia::KinesisVideoMediaClient::getMedia(), QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::getMediaForFragmentList(), QtAws::GuardDuty::GuardDutyClient::getMembers(), QtAws::CodeCommit::CodeCommitClient::getMergeConflicts(), QtAws::APIGateway::APIGatewayClient::getMethod(), QtAws::APIGateway::APIGatewayClient::getMethodResponse(), QtAws::CloudWatch::CloudWatchClient::getMetricStatistics(), QtAws::MachineLearning::MachineLearningClient::getMLModel(), QtAws::APIGateway::APIGatewayClient::getModel(), QtAws::APIGateway::APIGatewayClient::getModels(), QtAws::APIGateway::APIGatewayClient::getModelTemplate(), QtAws::Athena::AthenaClient::getNamedQuery(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::getNamespace(), QtAws::DeviceFarm::DeviceFarmClient::getNetworkProfile(), QtAws::MediaStoreData::MediaStoreDataClient::getObject(), QtAws::S3::S3Client::getObject(), QtAws::S3::S3Client::getObjectAcl(), QtAws::CloudDirectory::CloudDirectoryClient::getObjectInformation(), QtAws::S3::S3Client::getObjectTagging(), QtAws::S3::S3Client::getObjectTorrent(), QtAws::DeviceFarm::DeviceFarmClient::getOfferingStatus(), QtAws::CodeDeploy::CodeDeployClient::getOnPremisesInstance(), QtAws::IAM::IamClient::getOpenIDConnectProvider(), QtAws::CognitoIdentity::CognitoIdentityClient::getOpenIdToken(), QtAws::CognitoIdentity::CognitoIdentityClient::getOpenIdTokenForDeveloperIdentity(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::getOperation(), QtAws::Lightsail::LightsailClient::getOperation(), QtAws::Route53Domains::Route53DomainsClient::getOperationDetail(), QtAws::Lightsail::LightsailClient::getOperations(), QtAws::Lightsail::LightsailClient::getOperationsForResource(), QtAws::IoT::IoTClient::getOTAUpdate(), QtAws::SSM::SsmClient::getParameter(), QtAws::SSM::SsmClient::getParameterHistory(), QtAws::SSM::SsmClient::getParameters(), QtAws::SSM::SsmClient::getParametersByPath(), QtAws::KMS::KmsClient::getParametersForImport(), QtAws::Glue::GlueClient::getPartition(), QtAws::Glue::GlueClient::getPartitions(), QtAws::EC2::Ec2Client::getPasswordData(), QtAws::SSM::SsmClient::getPatchBaseline(), QtAws::SSM::SsmClient::getPatchBaselineForPatchGroup(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::getPendingJobExecutions(), QtAws::WAF::WafClient::getPermissionPolicy(), QtAws::WAFRegional::WAFRegionalClient::getPermissionPolicy(), QtAws::Rekognition::RekognitionClient::getPersonTracking(), QtAws::CodePipeline::CodePipelineClient::getPipeline(), QtAws::DataPipeline::DataPipelineClient::getPipelineDefinition(), QtAws::CodePipeline::CodePipelineClient::getPipelineExecution(), QtAws::CodePipeline::CodePipelineClient::getPipelineState(), QtAws::Glue::GlueClient::getPlan(), QtAws::SNS::SnsClient::getPlatformApplicationAttributes(), QtAws::Lambda::LambdaClient::getPolicy(), QtAws::IAM::IamClient::getPolicy(), QtAws::IoT::IoTClient::getPolicy(), QtAws::IAM::IamClient::getPolicyVersion(), QtAws::IoT::IoTClient::getPolicyVersion(), QtAws::MediaConvert::MediaConvertClient::getPreset(), QtAws::Pricing::PricingClient::getProducts(), QtAws::AlexaForBusiness::AlexaForBusinessClient::getProfile(), QtAws::DeviceFarm::DeviceFarmClient::getProject(), QtAws::CodeCommit::CodeCommitClient::getPullRequest(), QtAws::MTurk::MTurkClient::getQualificationScore(), QtAws::MTurk::MTurkClient::getQualificationType(), QtAws::Athena::AthenaClient::getQueryExecution(), QtAws::Route53::Route53Client::getQueryLoggingConfig(), QtAws::Athena::AthenaClient::getQueryResults(), QtAws::MediaConvert::MediaConvertClient::getQueue(), QtAws::SQS::SqsClient::getQueueAttributes(), QtAws::SQS::SqsClient::getQueueUrl(), QtAws::WAF::WafClient::getRateBasedRule(), QtAws::WAFRegional::WAFRegionalClient::getRateBasedRule(), QtAws::WAF::WafClient::getRateBasedRuleManagedKeys(), QtAws::WAFRegional::WAFRegionalClient::getRateBasedRuleManagedKeys(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::getRecords(), QtAws::Kinesis::KinesisClient::getRecords(), QtAws::WAF::WafClient::getRegexMatchSet(), QtAws::WAFRegional::WAFRegionalClient::getRegexMatchSet(), QtAws::WAF::WafClient::getRegexPatternSet(), QtAws::WAFRegional::WAFRegionalClient::getRegexPatternSet(), QtAws::Lightsail::LightsailClient::getRegions(), QtAws::IoT::IoTClient::getRegistrationCode(), QtAws::DeviceFarm::DeviceFarmClient::getRemoteAccessSession(), QtAws::SMS::SmsClient::getReplicationJobs(), QtAws::SMS::SmsClient::getReplicationRuns(), QtAws::CodeCommit::CodeCommitClient::getRepository(), QtAws::ECR::EcrClient::getRepositoryPolicy(), QtAws::CodeCommit::CodeCommitClient::getRepositoryTriggers(), QtAws::APIGateway::APIGatewayClient::getRequestValidator(), QtAws::APIGateway::APIGatewayClient::getRequestValidators(), QtAws::CostExplorer::CostExplorerClient::getReservationCoverage(), QtAws::CostExplorer::CostExplorerClient::getReservationPurchaseRecommendation(), QtAws::CostExplorer::CostExplorerClient::getReservationUtilization(), QtAws::EC2::Ec2Client::getReservedInstancesExchangeQuote(), QtAws::AppSync::AppSyncClient::getResolver(), QtAws::APIGateway::APIGatewayClient::getResource(), QtAws::ConfigService::ConfigServiceClient::getResourceConfigHistory(), QtAws::Greengrass::GreengrassClient::getResourceDefinition(), QtAws::Greengrass::GreengrassClient::getResourceDefinitionVersion(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::getResources(), QtAws::APIGateway::APIGatewayClient::getResources(), QtAws::APIGateway::APIGatewayClient::getRestApi(), QtAws::APIGateway::APIGatewayClient::getRestApis(), QtAws::Route53::Route53Client::getReusableDelegationSet(), QtAws::Route53::Route53Client::getReusableDelegationSetLimit(), QtAws::IAM::IamClient::getRole(), QtAws::IAM::IamClient::getRolePolicy(), QtAws::AlexaForBusiness::AlexaForBusinessClient::getRoom(), QtAws::AlexaForBusiness::AlexaForBusinessClient::getRoomSkillParameter(), QtAws::WAF::WafClient::getRule(), QtAws::WAFRegional::WAFRegionalClient::getRule(), QtAws::WAF::WafClient::getRuleGroup(), QtAws::WAFRegional::WAFRegionalClient::getRuleGroup(), QtAws::DeviceFarm::DeviceFarmClient::getRun(), QtAws::IAM::IamClient::getSAMLProvider(), QtAws::WAF::WafClient::getSampledRequests(), QtAws::WAFRegional::WAFRegionalClient::getSampledRequests(), QtAws::CloudDirectory::CloudDirectoryClient::getSchemaAsJson(), QtAws::AppSync::AppSyncClient::getSchemaCreationStatus(), QtAws::APIGateway::APIGatewayClient::getSdk(), QtAws::APIGateway::APIGatewayClient::getSdkType(), QtAws::APIGateway::APIGatewayClient::getSdkTypes(), QtAws::Pinpoint::PinpointClient::getSegment(), QtAws::Pinpoint::PinpointClient::getSegmentExportJobs(), QtAws::Pinpoint::PinpointClient::getSegmentImportJobs(), QtAws::Pinpoint::PinpointClient::getSegments(), QtAws::Pinpoint::PinpointClient::getSegmentVersion(), QtAws::Pinpoint::PinpointClient::getSegmentVersions(), QtAws::SES::SesClient::getSendQuota(), QtAws::SES::SesClient::getSendStatistics(), QtAws::IAM::IamClient::getServerCertificate(), QtAws::SMS::SmsClient::getServers(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::getService(), QtAws::XRay::XRayClient::getServiceGraph(), QtAws::IAM::IamClient::getServiceLinkedRoleDeletionStatus(), QtAws::Greengrass::GreengrassClient::getServiceRoleForAccount(), QtAws::STS::StsClient::getSessionToken(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::getShardIterator(), QtAws::Kinesis::KinesisClient::getShardIterator(), QtAws::ImportExport::ImportExportClient::getShippingLabel(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getSigningCertificate(), QtAws::WAF::WafClient::getSizeConstraintSet(), QtAws::WAFRegional::WAFRegionalClient::getSizeConstraintSet(), QtAws::AlexaForBusiness::AlexaForBusinessClient::getSkillGroup(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotType(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotTypes(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotTypeVersions(), QtAws::SNS::SnsClient::getSMSAttributes(), QtAws::Pinpoint::PinpointClient::getSmsChannel(), QtAws::DirectoryService::DirectoryServiceClient::getSnapshotLimits(), QtAws::Snowball::SnowballClient::getSnowballUsage(), QtAws::WAF::WafClient::getSqlInjectionMatchSet(), QtAws::WAFRegional::WAFRegionalClient::getSqlInjectionMatchSet(), QtAws::IAM::IamClient::getSSHPublicKey(), QtAws::CloudFormation::CloudFormationClient::getStackPolicy(), QtAws::APIGateway::APIGatewayClient::getStage(), QtAws::APIGateway::APIGatewayClient::getStages(), QtAws::Lightsail::LightsailClient::getStaticIp(), QtAws::Lightsail::LightsailClient::getStaticIps(), QtAws::ImportExport::ImportExportClient::getStatus(), QtAws::CloudFront::CloudFrontClient::getStreamingDistribution(), QtAws::CloudFront::CloudFrontClient::getStreamingDistributionConfig(), QtAws::SNS::SnsClient::getSubscriptionAttributes(), QtAws::Greengrass::GreengrassClient::getSubscriptionDefinition(), QtAws::Greengrass::GreengrassClient::getSubscriptionDefinitionVersion(), QtAws::Shield::ShieldClient::getSubscriptionState(), QtAws::DeviceFarm::DeviceFarmClient::getSuite(), QtAws::Glue::GlueClient::getTable(), QtAws::Glue::GlueClient::getTables(), QtAws::Glue::GlueClient::getTableVersion(), QtAws::Glue::GlueClient::getTableVersions(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::getTagKeys(), QtAws::CostExplorer::CostExplorerClient::getTags(), QtAws::ResourceGroups::ResourceGroupsClient::getTags(), QtAws::APIGateway::APIGatewayClient::getTags(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::getTagValues(), QtAws::Inspector::InspectorClient::getTelemetryMetadata(), QtAws::CloudFormation::CloudFormationClient::getTemplate(), QtAws::SES::SesClient::getTemplate(), QtAws::CloudFormation::CloudFormationClient::getTemplateSummary(), QtAws::DeviceFarm::DeviceFarmClient::getTest(), QtAws::IoTDataPlane::IoTDataPlaneClient::getThingShadow(), QtAws::CodePipeline::CodePipelineClient::getThirdPartyJobDetails(), QtAws::GuardDuty::GuardDutyClient::getThreatIntelSet(), QtAws::SNS::SnsClient::getTopicAttributes(), QtAws::IoT::IoTClient::getTopicRule(), QtAws::XRay::XRayClient::getTraceGraph(), QtAws::XRay::XRayClient::getTraceSummaries(), QtAws::Route53::Route53Client::getTrafficPolicy(), QtAws::Route53::Route53Client::getTrafficPolicyInstance(), QtAws::Route53::Route53Client::getTrafficPolicyInstanceCount(), QtAws::CloudTrail::CloudTrailClient::getTrailStatus(), QtAws::TranscribeService::TranscribeServiceClient::getTranscriptionJob(), QtAws::Glue::GlueClient::getTrigger(), QtAws::Glue::GlueClient::getTriggers(), QtAws::AppSync::AppSyncClient::getType(), QtAws::CloudDirectory::CloudDirectoryClient::getTypedLinkFacetInformation(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUICustomization(), QtAws::DeviceFarm::DeviceFarmClient::getUpload(), QtAws::APIGateway::APIGatewayClient::getUsage(), QtAws::APIGateway::APIGatewayClient::getUsagePlan(), QtAws::APIGateway::APIGatewayClient::getUsagePlanKey(), QtAws::APIGateway::APIGatewayClient::getUsagePlanKeys(), QtAws::APIGateway::APIGatewayClient::getUsagePlans(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUser(), QtAws::IAM::IamClient::getUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUserAttributeVerificationCode(), QtAws::Glue::GlueClient::getUserDefinedFunction(), QtAws::Glue::GlueClient::getUserDefinedFunctions(), QtAws::IAM::IamClient::getUserPolicy(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::getUserPoolMfaConfig(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getUtterancesView(), QtAws::IoT::IoTClient::getV2LoggingOptions(), QtAws::Glacier::GlacierClient::getVaultAccessPolicy(), QtAws::Glacier::GlacierClient::getVaultLock(), QtAws::Glacier::GlacierClient::getVaultNotifications(), QtAws::APIGateway::APIGatewayClient::getVpcLink(), QtAws::APIGateway::APIGatewayClient::getVpcLinks(), QtAws::WAF::WafClient::getWebACL(), QtAws::WAFRegional::WAFRegionalClient::getWebACL(), QtAws::WAFRegional::WAFRegionalClient::getWebACLForResource(), QtAws::SWF::SwfClient::getWorkflowExecutionHistory(), QtAws::WAF::WafClient::getXssMatchSet(), QtAws::WAFRegional::WAFRegionalClient::getXssMatchSet(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::globalSignOut(), QtAws::OpsWorks::OpsWorksClient::grantAccess(), QtAws::S3::S3Client::headBucket(), QtAws::S3::S3Client::headObject(), QtAws::APIGateway::APIGatewayClient::importApiKeys(), QtAws::Glue::GlueClient::importCatalogToGlue(), QtAws::ACM::AcmClient::importCertificate(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::importCertificate(), QtAws::APIGateway::APIGatewayClient::importDocumentationParts(), QtAws::EC2::Ec2Client::importImage(), QtAws::EC2::Ec2Client::importInstance(), QtAws::KMS::KmsClient::importKeyMaterial(), QtAws::Lightsail::LightsailClient::importKeyPair(), QtAws::EC2::Ec2Client::importKeyPair(), QtAws::MigrationHub::MigrationHubClient::importMigrationTask(), QtAws::APIGateway::APIGatewayClient::importRestApi(), QtAws::SMS::SmsClient::importServerCatalog(), QtAws::EC2::Ec2Client::importSnapshot(), QtAws::EC2::Ec2Client::importVolume(), QtAws::DAX::DaxClient::increaseReplicationFactor(), QtAws::Kinesis::KinesisClient::increaseStreamRetentionPeriod(), QtAws::CloudSearch::CloudSearchClient::indexDocuments(), QtAws::Rekognition::RekognitionClient::indexFaces(), QtAws::CloudHSMV2::CloudHSMV2Client::initializeCluster(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::initiateAuth(), QtAws::WorkDocs::WorkDocsClient::initiateDocumentVersionUpload(), QtAws::Glacier::GlacierClient::initiateJob(), QtAws::ECR::EcrClient::initiateLayerUpload(), QtAws::Glacier::GlacierClient::initiateMultipartUpload(), QtAws::Glacier::GlacierClient::initiateVaultLock(), QtAws::DeviceFarm::DeviceFarmClient::installToRemoteAccessSession(), QtAws::CodeBuild::CodeBuildClient::invalidateProjectCache(), QtAws::Organizations::OrganizationsClient::inviteAccountToOrganization(), QtAws::GuardDuty::GuardDutyClient::inviteMembers(), QtAws::Lambda::LambdaClient::invoke(), QtAws::Lambda::LambdaClient::invokeAsync(), QtAws::SageMakerRuntime::SageMakerRuntimeClient::invokeEndpoint(), QtAws::Lightsail::LightsailClient::isVpcPeered(), QtAws::Organizations::OrganizationsClient::leaveOrganization(), QtAws::ServiceCatalog::ServiceCatalogClient::listAcceptedPortfolioShares(), QtAws::IAM::IamClient::listAccessKeys(), QtAws::IAM::IamClient::listAccountAliases(), QtAws::Organizations::OrganizationsClient::listAccounts(), QtAws::Organizations::OrganizationsClient::listAccountsForParent(), QtAws::CodePipeline::CodePipelineClient::listActionTypes(), QtAws::WAF::WafClient::listActivatedRulesInRuleGroup(), QtAws::WAFRegional::WAFRegionalClient::listActivatedRulesInRuleGroup(), QtAws::SFN::SfnClient::listActivities(), QtAws::SWF::SwfClient::listActivityTypes(), QtAws::WorkMail::WorkMailClient::listAliases(), QtAws::Lambda::LambdaClient::listAliases(), QtAws::KMS::KmsClient::listAliases(), QtAws::GameLift::GameLiftClient::listAliases(), QtAws::ElastiCache::ElastiCacheClient::listAllowedNodeTypeModifications(), QtAws::AppSync::AppSyncClient::listApiKeys(), QtAws::CodeDeploy::CodeDeployClient::listApplicationRevisions(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::listApplications(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::listApplications(), QtAws::CodeDeploy::CodeDeployClient::listApplications(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::listApplicationVersions(), QtAws::CloudDirectory::CloudDirectoryClient::listAppliedSchemaArns(), QtAws::DeviceFarm::DeviceFarmClient::listArtifacts(), QtAws::Inspector::InspectorClient::listAssessmentRunAgents(), QtAws::Inspector::InspectorClient::listAssessmentRuns(), QtAws::Inspector::InspectorClient::listAssessmentTargets(), QtAws::Inspector::InspectorClient::listAssessmentTemplates(), QtAws::MTurk::MTurkClient::listAssignmentsForHIT(), QtAws::AppStream::AppStreamClient::listAssociatedFleets(), QtAws::AppStream::AppStreamClient::listAssociatedStacks(), QtAws::SSM::SsmClient::listAssociations(), QtAws::SSM::SsmClient::listAssociationVersions(), QtAws::IAM::IamClient::listAttachedGroupPolicies(), QtAws::CloudDirectory::CloudDirectoryClient::listAttachedIndices(), QtAws::IoT::IoTClient::listAttachedPolicies(), QtAws::IAM::IamClient::listAttachedRolePolicies(), QtAws::IAM::IamClient::listAttachedUserPolicies(), QtAws::Shield::ShieldClient::listAttacks(), QtAws::ECS::EcsClient::listAttributes(), QtAws::IoT::IoTClient::listAuthorizers(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::listAvailableSolutionStacks(), QtAws::CloudHSM::CloudHSMClient::listAvailableZones(), QtAws::Organizations::OrganizationsClient::listAWSServiceAccessForOrganization(), QtAws::DynamoDB::DynamoDBClient::listBackups(), QtAws::MTurk::MTurkClient::listBonusPayments(), QtAws::EMR::EmrClient::listBootstrapActions(), QtAws::CodeCommit::CodeCommitClient::listBranches(), QtAws::MQ::MqClient::listBrokers(), QtAws::S3::S3Client::listBucketAnalyticsConfigurations(), QtAws::S3::S3Client::listBucketInventoryConfigurations(), QtAws::S3::S3Client::listBucketMetricsConfigurations(), QtAws::S3::S3Client::listBuckets(), QtAws::CodeBuild::CodeBuildClient::listBuilds(), QtAws::GameLift::GameLiftClient::listBuilds(), QtAws::CodeBuild::CodeBuildClient::listBuildsForProject(), QtAws::Mobile::MobileClient::listBundles(), QtAws::WAF::WafClient::listByteMatchSets(), QtAws::WAFRegional::WAFRegionalClient::listByteMatchSets(), QtAws::IoT::IoTClient::listCACertificates(), QtAws::ACM::AcmClient::listCertificates(), QtAws::IoT::IoTClient::listCertificates(), QtAws::IoT::IoTClient::listCertificatesByCA(), QtAws::CloudFormation::CloudFormationClient::listChangeSets(), QtAws::MediaPackage::MediaPackageClient::listChannels(), QtAws::MediaLive::MediaLiveClient::listChannels(), QtAws::Organizations::OrganizationsClient::listChildren(), QtAws::SWF::SwfClient::listClosedWorkflowExecutions(), QtAws::CloudFront::CloudFrontClient::listCloudFrontOriginAccessIdentities(), QtAws::Snowball::SnowballClient::listClusterJobs(), QtAws::Snowball::SnowballClient::listClusters(), QtAws::EMR::EmrClient::listClusters(), QtAws::ECS::EcsClient::listClusters(), QtAws::Rekognition::RekognitionClient::listCollections(), QtAws::SSM::SsmClient::listCommandInvocations(), QtAws::SSM::SsmClient::listCommands(), QtAws::SSM::SsmClient::listComplianceItems(), QtAws::SSM::SsmClient::listComplianceSummaries(), QtAws::MQ::MqClient::listConfigurationRevisions(), QtAws::MQ::MqClient::listConfigurations(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::listConfigurations(), QtAws::SES::SesClient::listConfigurationSets(), QtAws::ServiceCatalog::ServiceCatalogClient::listConstraintsForPortfolio(), QtAws::ECS::EcsClient::listContainerInstances(), QtAws::MediaStore::MediaStoreClient::listContainers(), QtAws::Greengrass::GreengrassClient::listCoreDefinitions(), QtAws::Greengrass::GreengrassClient::listCoreDefinitionVersions(), QtAws::Organizations::OrganizationsClient::listCreateAccountStatus(), QtAws::MigrationHub::MigrationHubClient::listCreatedArtifacts(), QtAws::CodeBuild::CodeBuildClient::listCuratedEnvironmentImages(), QtAws::SES::SesClient::listCustomVerificationEmailTemplates(), QtAws::CloudWatch::CloudWatchClient::listDashboards(), QtAws::CognitoSync::CognitoSyncClient::listDatasets(), QtAws::AppSync::AppSyncClient::listDataSources(), QtAws::SQS::SqsClient::listDeadLetterSourceQueues(), QtAws::Firehose::FirehoseClient::listDeliveryStreams(), QtAws::CodeDeploy::CodeDeployClient::listDeploymentConfigs(), QtAws::CodeDeploy::CodeDeployClient::listDeploymentGroups(), QtAws::CodeDeploy::CodeDeployClient::listDeploymentInstances(), QtAws::CodeDeploy::CodeDeployClient::listDeployments(), QtAws::Greengrass::GreengrassClient::listDeployments(), QtAws::GuardDuty::GuardDutyClient::listDetectors(), QtAws::CloudDirectory::CloudDirectoryClient::listDevelopmentSchemaArns(), QtAws::Greengrass::GreengrassClient::listDeviceDefinitions(), QtAws::Greengrass::GreengrassClient::listDeviceDefinitionVersions(), QtAws::DeviceFarm::DeviceFarmClient::listDevicePools(), QtAws::DeviceFarm::DeviceFarmClient::listDevices(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listDevices(), QtAws::CloudDirectory::CloudDirectoryClient::listDirectories(), QtAws::MigrationHub::MigrationHubClient::listDiscoveredResources(), QtAws::ConfigService::ConfigServiceClient::listDiscoveredResources(), QtAws::CloudFront::CloudFrontClient::listDistributions(), QtAws::CloudFront::CloudFrontClient::listDistributionsByWebACLId(), QtAws::SSM::SsmClient::listDocuments(), QtAws::SSM::SsmClient::listDocumentVersions(), QtAws::ElasticsearchService::ElasticsearchServiceClient::listDomainNames(), QtAws::CloudSearch::CloudSearchClient::listDomainNames(), QtAws::SimpleDB::SimpleDBClient::listDomains(), QtAws::Route53Domains::Route53DomainsClient::listDomains(), QtAws::SWF::SwfClient::listDomains(), QtAws::ElasticsearchService::ElasticsearchServiceClient::listElasticsearchInstanceTypes(), QtAws::ElasticsearchService::ElasticsearchServiceClient::listElasticsearchVersions(), QtAws::SageMaker::SageMakerClient::listEndpointConfigs(), QtAws::SageMaker::SageMakerClient::listEndpoints(), QtAws::SNS::SnsClient::listEndpointsByPlatformApplication(), QtAws::IAM::IamClient::listEntitiesForPolicy(), QtAws::Cloud9::Cloud9Client::listEnvironments(), QtAws::Lambda::LambdaClient::listEventSourceMappings(), QtAws::Inspector::InspectorClient::listEventSubscriptions(), QtAws::SFN::SfnClient::listExecutions(), QtAws::CloudFormation::CloudFormationClient::listExports(), QtAws::Rekognition::RekognitionClient::listFaces(), QtAws::CloudDirectory::CloudDirectoryClient::listFacetAttributes(), QtAws::CloudDirectory::CloudDirectoryClient::listFacetNames(), QtAws::StorageGateway::StorageGatewayClient::listFileShares(), QtAws::Inspector::InspectorClient::listFindings(), QtAws::GuardDuty::GuardDutyClient::listFindings(), QtAws::GameLift::GameLiftClient::listFleets(), QtAws::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::listFragments(), QtAws::Greengrass::GreengrassClient::listFunctionDefinitions(), QtAws::Greengrass::GreengrassClient::listFunctionDefinitionVersions(), QtAws::Lambda::LambdaClient::listFunctions(), QtAws::StorageGateway::StorageGatewayClient::listGateways(), QtAws::Route53::Route53Client::listGeoLocations(), QtAws::WAF::WafClient::listGeoMatchSets(), QtAws::WAFRegional::WAFRegionalClient::listGeoMatchSets(), QtAws::CodeDeploy::CodeDeployClient::listGitHubAccountTokenNames(), QtAws::DynamoDB::DynamoDBClient::listGlobalTables(), QtAws::KMS::KmsClient::listGrants(), QtAws::AppSync::AppSyncClient::listGraphqlApis(), QtAws::Greengrass::GreengrassClient::listGroupCertificateAuthorities(), QtAws::WorkMail::WorkMailClient::listGroupMembers(), QtAws::IAM::IamClient::listGroupPolicies(), QtAws::ResourceGroups::ResourceGroupsClient::listGroupResources(), QtAws::ResourceGroups::ResourceGroupsClient::listGroups(), QtAws::WorkMail::WorkMailClient::listGroups(), QtAws::Greengrass::GreengrassClient::listGroups(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listGroups(), QtAws::IAM::IamClient::listGroups(), QtAws::IAM::IamClient::listGroupsForUser(), QtAws::Greengrass::GreengrassClient::listGroupVersions(), QtAws::Organizations::OrganizationsClient::listHandshakesForAccount(), QtAws::Organizations::OrganizationsClient::listHandshakesForOrganization(), QtAws::CloudHSM::CloudHSMClient::listHapgs(), QtAws::Route53::Route53Client::listHealthChecks(), QtAws::MTurk::MTurkClient::listHITs(), QtAws::MTurk::MTurkClient::listHITsForQualificationType(), QtAws::Route53::Route53Client::listHostedZones(), QtAws::Route53::Route53Client::listHostedZonesByName(), QtAws::CloudHSM::CloudHSMClient::listHsms(), QtAws::CognitoIdentity::CognitoIdentityClient::listIdentities(), QtAws::SES::SesClient::listIdentities(), QtAws::SES::SesClient::listIdentityPolicies(), QtAws::CognitoIdentity::CognitoIdentityClient::listIdentityPools(), QtAws::CognitoSync::CognitoSyncClient::listIdentityPoolUsage(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listIdentityProviders(), QtAws::ECR::EcrClient::listImages(), QtAws::CloudFormation::CloudFormationClient::listImports(), QtAws::CloudDirectory::CloudDirectoryClient::listIncomingTypedLinks(), QtAws::CloudDirectory::CloudDirectoryClient::listIndex(), QtAws::IoT::IoTClient::listIndices(), QtAws::MediaLive::MediaLiveClient::listInputs(), QtAws::MediaLive::MediaLiveClient::listInputSecurityGroups(), QtAws::EMR::EmrClient::listInstanceFleets(), QtAws::EMR::EmrClient::listInstanceGroups(), QtAws::IAM::IamClient::listInstanceProfiles(), QtAws::IAM::IamClient::listInstanceProfilesForRole(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::listInstances(), QtAws::EMR::EmrClient::listInstances(), QtAws::CloudFront::CloudFrontClient::listInvalidations(), QtAws::SSM::SsmClient::listInventoryEntries(), QtAws::GuardDuty::GuardDutyClient::listInvitations(), QtAws::DirectoryService::DirectoryServiceClient::listIpRoutes(), QtAws::GuardDuty::GuardDutyClient::listIPSets(), QtAws::WAF::WafClient::listIPSets(), QtAws::WAFRegional::WAFRegionalClient::listIPSets(), QtAws::MediaStoreData::MediaStoreDataClient::listItems(), QtAws::IoT::IoTClient::listJobExecutionsForJob(), QtAws::IoT::IoTClient::listJobExecutionsForThing(), QtAws::ImportExport::ImportExportClient::listJobs(), QtAws::Batch::BatchClient::listJobs(), QtAws::Snowball::SnowballClient::listJobs(), QtAws::MediaConvert::MediaConvertClient::listJobs(), QtAws::Glacier::GlacierClient::listJobs(), QtAws::DeviceFarm::DeviceFarmClient::listJobs(), QtAws::IoT::IoTClient::listJobs(), QtAws::ElasticTranscoder::ElasticTranscoderClient::listJobsByPipeline(), QtAws::ElasticTranscoder::ElasticTranscoderClient::listJobsByStatus(), QtAws::MediaConvert::MediaConvertClient::listJobTemplates(), QtAws::KMS::KmsClient::listKeyPolicies(), QtAws::KMS::KmsClient::listKeys(), QtAws::ServiceCatalog::ServiceCatalogClient::listLaunchPaths(), QtAws::Polly::PollyClient::listLexicons(), QtAws::StorageGateway::StorageGatewayClient::listLocalDisks(), QtAws::Greengrass::GreengrassClient::listLoggerDefinitions(), QtAws::Greengrass::GreengrassClient::listLoggerDefinitionVersions(), QtAws::CloudHSM::CloudHSMClient::listLunaClients(), QtAws::GuardDuty::GuardDutyClient::listMembers(), QtAws::CloudWatch::CloudWatchClient::listMetrics(), QtAws::IAM::IamClient::listMFADevices(), QtAws::MigrationHub::MigrationHubClient::listMigrationTasks(), QtAws::SageMaker::SageMakerClient::listModels(), QtAws::Glacier::GlacierClient::listMultipartUploads(), QtAws::S3::S3Client::listMultipartUploads(), QtAws::Athena::AthenaClient::listNamedQueries(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::listNamespaces(), QtAws::DeviceFarm::DeviceFarmClient::listNetworkProfiles(), QtAws::SageMaker::SageMakerClient::listNotebookInstanceLifecycleConfigs(), QtAws::SageMaker::SageMakerClient::listNotebookInstances(), QtAws::CloudDirectory::CloudDirectoryClient::listObjectAttributes(), QtAws::CloudDirectory::CloudDirectoryClient::listObjectChildren(), QtAws::CloudDirectory::CloudDirectoryClient::listObjectParentPaths(), QtAws::CloudDirectory::CloudDirectoryClient::listObjectParents(), QtAws::CloudDirectory::CloudDirectoryClient::listObjectPolicies(), QtAws::S3::S3Client::listObjects(), QtAws::S3::S3Client::listObjectsV2(), QtAws::S3::S3Client::listObjectVersions(), QtAws::DeviceFarm::DeviceFarmClient::listOfferingPromotions(), QtAws::DeviceFarm::DeviceFarmClient::listOfferings(), QtAws::DeviceFarm::DeviceFarmClient::listOfferingTransactions(), QtAws::CodeDeploy::CodeDeployClient::listOnPremisesInstances(), QtAws::IAM::IamClient::listOpenIDConnectProviders(), QtAws::SWF::SwfClient::listOpenWorkflowExecutions(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::listOperations(), QtAws::Route53Domains::Route53DomainsClient::listOperations(), QtAws::Organizations::OrganizationsClient::listOrganizationalUnitsForParent(), QtAws::WorkMail::WorkMailClient::listOrganizations(), QtAws::MediaPackage::MediaPackageClient::listOriginEndpoints(), QtAws::IoT::IoTClient::listOTAUpdates(), QtAws::IoT::IoTClient::listOutgoingCertificates(), QtAws::CloudDirectory::CloudDirectoryClient::listOutgoingTypedLinks(), QtAws::Organizations::OrganizationsClient::listParents(), QtAws::Glacier::GlacierClient::listParts(), QtAws::S3::S3Client::listParts(), QtAws::SNS::SnsClient::listPhoneNumbersOptedOut(), QtAws::CodePipeline::CodePipelineClient::listPipelineExecutions(), QtAws::ElasticTranscoder::ElasticTranscoderClient::listPipelines(), QtAws::DataPipeline::DataPipelineClient::listPipelines(), QtAws::CodePipeline::CodePipelineClient::listPipelines(), QtAws::SNS::SnsClient::listPlatformApplications(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::listPlatformVersions(), QtAws::Organizations::OrganizationsClient::listPolicies(), QtAws::IAM::IamClient::listPolicies(), QtAws::IoT::IoTClient::listPolicies(), QtAws::Organizations::OrganizationsClient::listPoliciesForTarget(), QtAws::CloudDirectory::CloudDirectoryClient::listPolicyAttachments(), QtAws::IoT::IoTClient::listPolicyPrincipals(), QtAws::IAM::IamClient::listPolicyVersions(), QtAws::IoT::IoTClient::listPolicyVersions(), QtAws::ServiceCatalog::ServiceCatalogClient::listPortfolioAccess(), QtAws::ServiceCatalog::ServiceCatalogClient::listPortfolios(), QtAws::ServiceCatalog::ServiceCatalogClient::listPortfoliosForProduct(), QtAws::ElasticTranscoder::ElasticTranscoderClient::listPresets(), QtAws::MediaConvert::MediaConvertClient::listPresets(), QtAws::IoT::IoTClient::listPrincipalPolicies(), QtAws::ServiceCatalog::ServiceCatalogClient::listPrincipalsForPortfolio(), QtAws::IoT::IoTClient::listPrincipalThings(), QtAws::MigrationHub::MigrationHubClient::listProgressUpdateStreams(), QtAws::Mobile::MobileClient::listProjects(), QtAws::CodeBuild::CodeBuildClient::listProjects(), QtAws::CodeStar::CodeStarClient::listProjects(), QtAws::DeviceFarm::DeviceFarmClient::listProjects(), QtAws::Shield::ShieldClient::listProtections(), QtAws::Glacier::GlacierClient::listProvisionedCapacity(), QtAws::ServiceCatalog::ServiceCatalogClient::listProvisionedProductPlans(), QtAws::ServiceCatalog::ServiceCatalogClient::listProvisioningArtifacts(), QtAws::CloudTrail::CloudTrailClient::listPublicKeys(), QtAws::CloudDirectory::CloudDirectoryClient::listPublishedSchemaArns(), QtAws::CodeCommit::CodeCommitClient::listPullRequests(), QtAws::MTurk::MTurkClient::listQualificationRequests(), QtAws::MTurk::MTurkClient::listQualificationTypes(), QtAws::Athena::AthenaClient::listQueryExecutions(), QtAws::Route53::Route53Client::listQueryLoggingConfigs(), QtAws::SQS::SqsClient::listQueues(), QtAws::MediaConvert::MediaConvertClient::listQueues(), QtAws::SQS::SqsClient::listQueueTags(), QtAws::WAF::WafClient::listRateBasedRules(), QtAws::WAFRegional::WAFRegionalClient::listRateBasedRules(), QtAws::SES::SesClient::listReceiptFilters(), QtAws::SES::SesClient::listReceiptRuleSets(), QtAws::ServiceCatalog::ServiceCatalogClient::listRecordHistory(), QtAws::CognitoSync::CognitoSyncClient::listRecords(), QtAws::WAF::WafClient::listRegexMatchSets(), QtAws::WAFRegional::WAFRegionalClient::listRegexMatchSets(), QtAws::WAF::WafClient::listRegexPatternSets(), QtAws::WAFRegional::WAFRegionalClient::listRegexPatternSets(), QtAws::DeviceFarm::DeviceFarmClient::listRemoteAccessSessions(), QtAws::CodeCommit::CodeCommitClient::listRepositories(), QtAws::AppSync::AppSyncClient::listResolvers(), QtAws::SSM::SsmClient::listResourceComplianceSummaries(), QtAws::SSM::SsmClient::listResourceDataSync(), QtAws::Greengrass::GreengrassClient::listResourceDefinitions(), QtAws::Greengrass::GreengrassClient::listResourceDefinitionVersions(), QtAws::WorkMail::WorkMailClient::listResourceDelegates(), QtAws::Route53::Route53Client::listResourceRecordSets(), QtAws::CodeStar::CodeStarClient::listResources(), QtAws::WorkMail::WorkMailClient::listResources(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listResourceServers(), QtAws::ServiceCatalog::ServiceCatalogClient::listResourcesForTagOption(), QtAws::WAFRegional::WAFRegionalClient::listResourcesForWebACL(), QtAws::KMS::KmsClient::listResourceTags(), QtAws::KMS::KmsClient::listRetirableGrants(), QtAws::Route53::Route53Client::listReusableDelegationSets(), QtAws::MTurk::MTurkClient::listReviewableHITs(), QtAws::MTurk::MTurkClient::listReviewPolicyResultsForHIT(), QtAws::IoT::IoTClient::listRoleAliases(), QtAws::IAM::IamClient::listRolePolicies(), QtAws::IAM::IamClient::listRoles(), QtAws::Organizations::OrganizationsClient::listRoots(), QtAws::WAF::WafClient::listRuleGroups(), QtAws::WAFRegional::WAFRegionalClient::listRuleGroups(), QtAws::CloudWatchEvents::CloudWatchEventsClient::listRuleNamesByTarget(), QtAws::CloudWatchEvents::CloudWatchEventsClient::listRules(), QtAws::WAF::WafClient::listRules(), QtAws::WAFRegional::WAFRegionalClient::listRules(), QtAws::Inspector::InspectorClient::listRulesPackages(), QtAws::DeviceFarm::DeviceFarmClient::listRuns(), QtAws::IAM::IamClient::listSAMLProviders(), QtAws::DeviceFarm::DeviceFarmClient::listSamples(), QtAws::DirectoryService::DirectoryServiceClient::listSchemaExtensions(), QtAws::EMR::EmrClient::listSecurityConfigurations(), QtAws::IAM::IamClient::listServerCertificates(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::listServerNeighbors(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::listServices(), QtAws::ECS::EcsClient::listServices(), QtAws::IAM::IamClient::listServiceSpecificCredentials(), QtAws::Kinesis::KinesisClient::listShards(), QtAws::IAM::IamClient::listSigningCertificates(), QtAws::WAF::WafClient::listSizeConstraintSets(), QtAws::WAFRegional::WAFRegionalClient::listSizeConstraintSets(), QtAws::AlexaForBusiness::AlexaForBusinessClient::listSkills(), QtAws::WAF::WafClient::listSqlInjectionMatchSets(), QtAws::WAFRegional::WAFRegionalClient::listSqlInjectionMatchSets(), QtAws::IAM::IamClient::listSSHPublicKeys(), QtAws::CloudFormation::CloudFormationClient::listStackInstances(), QtAws::CloudFormation::CloudFormationClient::listStackResources(), QtAws::CloudFormation::CloudFormationClient::listStacks(), QtAws::CloudFormation::CloudFormationClient::listStackSetOperationResults(), QtAws::CloudFormation::CloudFormationClient::listStackSetOperations(), QtAws::CloudFormation::CloudFormationClient::listStackSets(), QtAws::SFN::SfnClient::listStateMachines(), QtAws::EMR::EmrClient::listSteps(), QtAws::CloudFront::CloudFrontClient::listStreamingDistributions(), QtAws::Rekognition::RekognitionClient::listStreamProcessors(), QtAws::DynamoDBStreams::DynamoDBStreamsClient::listStreams(), QtAws::KinesisVideo::KinesisVideoClient::listStreams(), QtAws::Kinesis::KinesisClient::listStreams(), QtAws::IoT::IoTClient::listStreams(), QtAws::WAF::WafClient::listSubscribedRuleGroups(), QtAws::WAFRegional::WAFRegionalClient::listSubscribedRuleGroups(), QtAws::Greengrass::GreengrassClient::listSubscriptionDefinitions(), QtAws::Greengrass::GreengrassClient::listSubscriptionDefinitionVersions(), QtAws::SNS::SnsClient::listSubscriptions(), QtAws::SNS::SnsClient::listSubscriptionsByTopic(), QtAws::DeviceFarm::DeviceFarmClient::listSuites(), QtAws::DynamoDB::DynamoDBClient::listTables(), QtAws::ServiceCatalog::ServiceCatalogClient::listTagOptions(), QtAws::CloudHSMV2::CloudHSMV2Client::listTags(), QtAws::CloudTrail::CloudTrailClient::listTags(), QtAws::ElasticsearchService::ElasticsearchServiceClient::listTags(), QtAws::DAX::DaxClient::listTags(), QtAws::Lambda::LambdaClient::listTags(), QtAws::AlexaForBusiness::AlexaForBusinessClient::listTags(), QtAws::SageMaker::SageMakerClient::listTags(), QtAws::OpsWorks::OpsWorksClient::listTags(), QtAws::ACM::AcmClient::listTagsForCertificate(), QtAws::Route53Domains::Route53DomainsClient::listTagsForDomain(), QtAws::CodeStar::CodeStarClient::listTagsForProject(), QtAws::CloudHSM::CloudHSMClient::listTagsForResource(), QtAws::CloudFront::CloudFrontClient::listTagsForResource(), QtAws::Inspector::InspectorClient::listTagsForResource(), QtAws::AppStream::AppStreamClient::listTagsForResource(), QtAws::ElastiCache::ElastiCacheClient::listTagsForResource(), QtAws::DirectoryService::DirectoryServiceClient::listTagsForResource(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::listTagsForResource(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::listTagsForResource(), QtAws::Route53::Route53Client::listTagsForResource(), QtAws::StorageGateway::StorageGatewayClient::listTagsForResource(), QtAws::CloudDirectory::CloudDirectoryClient::listTagsForResource(), QtAws::RDS::RdsClient::listTagsForResource(), QtAws::SSM::SsmClient::listTagsForResource(), QtAws::Route53::Route53Client::listTagsForResources(), QtAws::KinesisVideo::KinesisVideoClient::listTagsForStream(), QtAws::Kinesis::KinesisClient::listTagsForStream(), QtAws::Glacier::GlacierClient::listTagsForVault(), QtAws::CloudWatchLogs::CloudWatchLogsClient::listTagsLogGroup(), QtAws::DynamoDB::DynamoDBClient::listTagsOfResource(), QtAws::StorageGateway::StorageGatewayClient::listTapes(), QtAws::CloudWatchEvents::CloudWatchEventsClient::listTargetsByRule(), QtAws::Organizations::OrganizationsClient::listTargetsForPolicy(), QtAws::IoT::IoTClient::listTargetsForPolicy(), QtAws::ECS::EcsClient::listTaskDefinitionFamilies(), QtAws::ECS::EcsClient::listTaskDefinitions(), QtAws::ECS::EcsClient::listTasks(), QtAws::CodeStar::CodeStarClient::listTeamMembers(), QtAws::SES::SesClient::listTemplates(), QtAws::DeviceFarm::DeviceFarmClient::listTests(), QtAws::IoT::IoTClient::listThingGroups(), QtAws::IoT::IoTClient::listThingGroupsForThing(), QtAws::IoT::IoTClient::listThingPrincipals(), QtAws::IoT::IoTClient::listThingRegistrationTaskReports(), QtAws::IoT::IoTClient::listThingRegistrationTasks(), QtAws::IoT::IoTClient::listThings(), QtAws::IoT::IoTClient::listThingsInThingGroup(), QtAws::IoT::IoTClient::listThingTypes(), QtAws::GuardDuty::GuardDutyClient::listThreatIntelSets(), QtAws::IoT::IoTClient::listTopicRules(), QtAws::SNS::SnsClient::listTopics(), QtAws::Comprehend::ComprehendClient::listTopicsDetectionJobs(), QtAws::Route53::Route53Client::listTrafficPolicies(), QtAws::Route53::Route53Client::listTrafficPolicyInstances(), QtAws::Route53::Route53Client::listTrafficPolicyInstancesByHostedZone(), QtAws::Route53::Route53Client::listTrafficPolicyInstancesByPolicy(), QtAws::Route53::Route53Client::listTrafficPolicyVersions(), QtAws::SageMaker::SageMakerClient::listTrainingJobs(), QtAws::TranscribeService::TranscribeServiceClient::listTranscriptionJobs(), QtAws::CloudDirectory::CloudDirectoryClient::listTypedLinkFacetAttributes(), QtAws::CloudDirectory::CloudDirectoryClient::listTypedLinkFacetNames(), QtAws::AppSync::AppSyncClient::listTypes(), QtAws::DeviceFarm::DeviceFarmClient::listUniqueProblems(), QtAws::DeviceFarm::DeviceFarmClient::listUploads(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserImportJobs(), QtAws::IAM::IamClient::listUserPolicies(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserPoolClients(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUserPools(), QtAws::CodeStar::CodeStarClient::listUserProfiles(), QtAws::MQ::MqClient::listUsers(), QtAws::WorkMail::WorkMailClient::listUsers(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUsers(), QtAws::IAM::IamClient::listUsers(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::listUsersInGroup(), QtAws::IoT::IoTClient::listV2LoggingLevels(), QtAws::Glacier::GlacierClient::listVaults(), QtAws::SES::SesClient::listVerifiedEmailAddresses(), QtAws::Lambda::LambdaClient::listVersionsByFunction(), QtAws::IAM::IamClient::listVirtualMFADevices(), QtAws::StorageGateway::StorageGatewayClient::listVolumeInitiators(), QtAws::StorageGateway::StorageGatewayClient::listVolumeRecoveryPoints(), QtAws::StorageGateway::StorageGatewayClient::listVolumes(), QtAws::Route53::Route53Client::listVPCAssociationAuthorizations(), QtAws::WAF::WafClient::listWebACLs(), QtAws::WAFRegional::WAFRegionalClient::listWebACLs(), QtAws::MTurk::MTurkClient::listWorkerBlocks(), QtAws::MTurk::MTurkClient::listWorkersWithQualificationType(), QtAws::SWF::SwfClient::listWorkflowTypes(), QtAws::WAF::WafClient::listXssMatchSets(), QtAws::WAFRegional::WAFRegionalClient::listXssMatchSets(), QtAws::CognitoIdentity::CognitoIdentityClient::lookupDeveloperIdentity(), QtAws::CloudTrail::CloudTrailClient::lookupEvents(), QtAws::CloudDirectory::CloudDirectoryClient::lookupPolicy(), QtAws::CognitoIdentity::CognitoIdentityClient::mergeDeveloperIdentities(), QtAws::CodeCommit::CodeCommitClient::mergePullRequestByFastForward(), QtAws::Kinesis::KinesisClient::mergeShards(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::meterUsage(), QtAws::ElastiCache::ElastiCacheClient::modifyCacheCluster(), QtAws::ElastiCache::ElastiCacheClient::modifyCacheParameterGroup(), QtAws::ElastiCache::ElastiCacheClient::modifyCacheSubnetGroup(), QtAws::Redshift::RedshiftClient::modifyCluster(), QtAws::Redshift::RedshiftClient::modifyClusterIamRoles(), QtAws::Redshift::RedshiftClient::modifyClusterParameterGroup(), QtAws::Redshift::RedshiftClient::modifyClusterSubnetGroup(), QtAws::RDS::RdsClient::modifyDBCluster(), QtAws::RDS::RdsClient::modifyDBClusterParameterGroup(), QtAws::RDS::RdsClient::modifyDBClusterSnapshotAttribute(), QtAws::RDS::RdsClient::modifyDBInstance(), QtAws::RDS::RdsClient::modifyDBParameterGroup(), QtAws::RDS::RdsClient::modifyDBSnapshot(), QtAws::RDS::RdsClient::modifyDBSnapshotAttribute(), QtAws::RDS::RdsClient::modifyDBSubnetGroup(), QtAws::SSM::SsmClient::modifyDocumentPermission(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyEndpoint(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyEventSubscription(), QtAws::Redshift::RedshiftClient::modifyEventSubscription(), QtAws::RDS::RdsClient::modifyEventSubscription(), QtAws::EC2::Ec2Client::modifyFpgaImageAttribute(), QtAws::CloudHSM::CloudHSMClient::modifyHapg(), QtAws::EC2::Ec2Client::modifyHosts(), QtAws::CloudHSM::CloudHSMClient::modifyHsm(), QtAws::EC2::Ec2Client::modifyIdentityIdFormat(), QtAws::EC2::Ec2Client::modifyIdFormat(), QtAws::EC2::Ec2Client::modifyImageAttribute(), QtAws::EC2::Ec2Client::modifyInstanceAttribute(), QtAws::EC2::Ec2Client::modifyInstanceCreditSpecification(), QtAws::EMR::EmrClient::modifyInstanceFleet(), QtAws::EMR::EmrClient::modifyInstanceGroups(), QtAws::EC2::Ec2Client::modifyInstancePlacement(), QtAws::EC2::Ec2Client::modifyLaunchTemplate(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyListener(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::modifyLoadBalancerAttributes(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyLoadBalancerAttributes(), QtAws::CloudHSM::CloudHSMClient::modifyLunaClient(), QtAws::EFS::EfsClient::modifyMountTargetSecurityGroups(), QtAws::EC2::Ec2Client::modifyNetworkInterfaceAttribute(), QtAws::RDS::RdsClient::modifyOptionGroup(), QtAws::ElastiCache::ElastiCacheClient::modifyReplicationGroup(), QtAws::ElastiCache::ElastiCacheClient::modifyReplicationGroupShardConfiguration(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationInstance(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationSubnetGroup(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::modifyReplicationTask(), QtAws::EC2::Ec2Client::modifyReservedInstances(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyRule(), QtAws::EC2::Ec2Client::modifySnapshotAttribute(), QtAws::Redshift::RedshiftClient::modifySnapshotCopyRetentionPeriod(), QtAws::EC2::Ec2Client::modifySpotFleetRequest(), QtAws::EC2::Ec2Client::modifySubnetAttribute(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyTargetGroup(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::modifyTargetGroupAttributes(), QtAws::EC2::Ec2Client::modifyVolume(), QtAws::EC2::Ec2Client::modifyVolumeAttribute(), QtAws::EC2::Ec2Client::modifyVpcAttribute(), QtAws::EC2::Ec2Client::modifyVpcEndpoint(), QtAws::EC2::Ec2Client::modifyVpcEndpointConnectionNotification(), QtAws::EC2::Ec2Client::modifyVpcEndpointServiceConfiguration(), QtAws::EC2::Ec2Client::modifyVpcEndpointServicePermissions(), QtAws::EC2::Ec2Client::modifyVpcPeeringConnectionOptions(), QtAws::EC2::Ec2Client::modifyVpcTenancy(), QtAws::WorkSpaces::WorkSpacesClient::modifyWorkspaceProperties(), QtAws::EC2::Ec2Client::monitorInstances(), QtAws::Organizations::OrganizationsClient::moveAccount(), QtAws::EC2::Ec2Client::moveAddressToVpc(), QtAws::MigrationHub::MigrationHubClient::notifyApplicationState(), QtAws::MigrationHub::MigrationHubClient::notifyMigrationTaskState(), QtAws::StorageGateway::StorageGatewayClient::notifyWhenUploaded(), QtAws::MTurk::MTurkClient::notifyWorkers(), QtAws::Lightsail::LightsailClient::openInstancePublicPorts(), QtAws::SNS::SnsClient::optInPhoneNumber(), QtAws::Lightsail::LightsailClient::peerVpc(), QtAws::SWF::SwfClient::pollForActivityTask(), QtAws::SWF::SwfClient::pollForDecisionTask(), QtAws::CodePipeline::CodePipelineClient::pollForJobs(), QtAws::DataPipeline::DataPipelineClient::pollForTask(), QtAws::CodePipeline::CodePipelineClient::pollForThirdPartyJobs(), QtAws::CodeCommit::CodeCommitClient::postCommentForComparedCommit(), QtAws::CodeCommit::CodeCommitClient::postCommentForPullRequest(), QtAws::CodeCommit::CodeCommitClient::postCommentReply(), QtAws::LexRuntimeService::LexRuntimeServiceClient::postContent(), QtAws::LexRuntimeService::LexRuntimeServiceClient::postText(), QtAws::MachineLearning::MachineLearningClient::predict(), QtAws::Inspector::InspectorClient::previewAgents(), QtAws::RDS::RdsClient::promoteReadReplica(), QtAws::RDS::RdsClient::promoteReadReplicaDBCluster(), QtAws::ServiceCatalog::ServiceCatalogClient::provisionProduct(), QtAws::IoTDataPlane::IoTDataPlaneClient::publish(), QtAws::SNS::SnsClient::publish(), QtAws::CloudDirectory::CloudDirectoryClient::publishSchema(), QtAws::Lambda::LambdaClient::publishVersion(), QtAws::EC2::Ec2Client::purchaseHostReservation(), QtAws::DeviceFarm::DeviceFarmClient::purchaseOffering(), QtAws::Glacier::GlacierClient::purchaseProvisionedCapacity(), QtAws::ElastiCache::ElastiCacheClient::purchaseReservedCacheNodesOffering(), QtAws::RDS::RdsClient::purchaseReservedDBInstancesOffering(), QtAws::EC2::Ec2Client::purchaseReservedInstancesOffering(), QtAws::Redshift::RedshiftClient::purchaseReservedNodeOffering(), QtAws::EC2::Ec2Client::purchaseScheduledInstances(), QtAws::SQS::SqsClient::purgeQueue(), QtAws::CodePipeline::CodePipelineClient::putActionRevision(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::putApplicationPolicy(), QtAws::CodePipeline::CodePipelineClient::putApprovalResult(), QtAws::SimpleDB::SimpleDBClient::putAttributes(), QtAws::ECS::EcsClient::putAttributes(), QtAws::EMR::EmrClient::putAutoScalingPolicy(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putBot(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putBotAlias(), QtAws::S3::S3Client::putBucketAccelerateConfiguration(), QtAws::S3::S3Client::putBucketAcl(), QtAws::S3::S3Client::putBucketAnalyticsConfiguration(), QtAws::S3::S3Client::putBucketCors(), QtAws::S3::S3Client::putBucketEncryption(), QtAws::S3::S3Client::putBucketInventoryConfiguration(), QtAws::S3::S3Client::putBucketLifecycle(), QtAws::S3::S3Client::putBucketLifecycleConfiguration(), QtAws::S3::S3Client::putBucketLogging(), QtAws::S3::S3Client::putBucketMetricsConfiguration(), QtAws::S3::S3Client::putBucketNotification(), QtAws::S3::S3Client::putBucketNotificationConfiguration(), QtAws::S3::S3Client::putBucketPolicy(), QtAws::S3::S3Client::putBucketReplication(), QtAws::S3::S3Client::putBucketRequestPayment(), QtAws::S3::S3Client::putBucketTagging(), QtAws::S3::S3Client::putBucketVersioning(), QtAws::S3::S3Client::putBucketWebsite(), QtAws::SSM::SsmClient::putComplianceItems(), QtAws::ConfigService::ConfigServiceClient::putConfigRule(), QtAws::ConfigService::ConfigServiceClient::putConfigurationRecorder(), QtAws::MediaStore::MediaStoreClient::putContainerPolicy(), QtAws::MediaStore::MediaStoreClient::putCorsPolicy(), QtAws::CloudWatch::CloudWatchClient::putDashboard(), QtAws::ConfigService::ConfigServiceClient::putDeliveryChannel(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putDestination(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putDestinationPolicy(), QtAws::ConfigService::ConfigServiceClient::putEvaluations(), QtAws::MobileAnalytics::MobileAnalyticsClient::putEvents(), QtAws::CloudWatchEvents::CloudWatchEventsClient::putEvents(), QtAws::CloudTrail::CloudTrailClient::putEventSelectors(), QtAws::Pinpoint::PinpointClient::putEventStream(), QtAws::CodeCommit::CodeCommitClient::putFile(), QtAws::Lambda::LambdaClient::putFunctionConcurrency(), QtAws::APIGateway::APIGatewayClient::putGatewayResponse(), QtAws::IAM::IamClient::putGroupPolicy(), QtAws::SES::SesClient::putIdentityPolicy(), QtAws::ECR::EcrClient::putImage(), QtAws::Lightsail::LightsailClient::putInstancePublicPorts(), QtAws::APIGateway::APIGatewayClient::putIntegration(), QtAws::APIGateway::APIGatewayClient::putIntegrationResponse(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putIntent(), QtAws::SSM::SsmClient::putInventory(), QtAws::DynamoDB::DynamoDBClient::putItem(), QtAws::CodePipeline::CodePipelineClient::putJobFailureResult(), QtAws::CodePipeline::CodePipelineClient::putJobSuccessResult(), QtAws::KMS::KmsClient::putKeyPolicy(), QtAws::Polly::PollyClient::putLexicon(), QtAws::CodeDeploy::CodeDeployClient::putLifecycleEventHookExecutionStatus(), QtAws::AutoScaling::AutoScalingClient::putLifecycleHook(), QtAws::ECR::EcrClient::putLifecyclePolicy(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putLogEvents(), QtAws::APIGateway::APIGatewayClient::putMethod(), QtAws::APIGateway::APIGatewayClient::putMethodResponse(), QtAws::CloudWatch::CloudWatchClient::putMetricAlarm(), QtAws::CloudWatch::CloudWatchClient::putMetricData(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putMetricFilter(), QtAws::AutoScaling::AutoScalingClient::putNotificationConfiguration(), QtAws::MediaStoreData::MediaStoreDataClient::putObject(), QtAws::S3::S3Client::putObject(), QtAws::S3::S3Client::putObjectAcl(), QtAws::S3::S3Client::putObjectTagging(), QtAws::SSM::SsmClient::putParameter(), QtAws::CloudWatchEvents::CloudWatchEventsClient::putPermission(), QtAws::WAF::WafClient::putPermissionPolicy(), QtAws::WAFRegional::WAFRegionalClient::putPermissionPolicy(), QtAws::DataPipeline::DataPipelineClient::putPipelineDefinition(), QtAws::Firehose::FirehoseClient::putRecord(), QtAws::Kinesis::KinesisClient::putRecord(), QtAws::Firehose::FirehoseClient::putRecordBatch(), QtAws::Kinesis::KinesisClient::putRecords(), QtAws::CostandUsageReportService::CostandUsageReportServiceClient::putReportDefinition(), QtAws::CodeCommit::CodeCommitClient::putRepositoryTriggers(), QtAws::MigrationHub::MigrationHubClient::putResourceAttributes(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putResourcePolicy(), QtAws::APIGateway::APIGatewayClient::putRestApi(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putRetentionPolicy(), QtAws::IAM::IamClient::putRolePolicy(), QtAws::AlexaForBusiness::AlexaForBusinessClient::putRoomSkillParameter(), QtAws::CloudWatchEvents::CloudWatchEventsClient::putRule(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::putScalingPolicy(), QtAws::AutoScaling::AutoScalingClient::putScalingPolicy(), QtAws::GameLift::GameLiftClient::putScalingPolicy(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::putScheduledAction(), QtAws::AutoScaling::AutoScalingClient::putScheduledUpdateGroupAction(), QtAws::CloudDirectory::CloudDirectoryClient::putSchemaFromJson(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putSlotType(), QtAws::CloudWatchLogs::CloudWatchLogsClient::putSubscriptionFilter(), QtAws::CloudWatchEvents::CloudWatchEventsClient::putTargets(), QtAws::XRay::XRayClient::putTelemetryRecords(), QtAws::CodePipeline::CodePipelineClient::putThirdPartyJobFailureResult(), QtAws::CodePipeline::CodePipelineClient::putThirdPartyJobSuccessResult(), QtAws::XRay::XRayClient::putTraceSegments(), QtAws::IAM::IamClient::putUserPolicy(), QtAws::DynamoDB::DynamoDBClient::query(), QtAws::DataPipeline::DataPipelineClient::queryObjects(), QtAws::ElasticTranscoder::ElasticTranscoderClient::readJob(), QtAws::ElasticTranscoder::ElasticTranscoderClient::readPipeline(), QtAws::ElasticTranscoder::ElasticTranscoderClient::readPreset(), QtAws::MQ::MqClient::rebootBroker(), QtAws::ElastiCache::ElastiCacheClient::rebootCacheCluster(), QtAws::Redshift::RedshiftClient::rebootCluster(), QtAws::RDS::RdsClient::rebootDBInstance(), QtAws::OpsWorks::OpsWorksClient::rebootInstance(), QtAws::Lightsail::LightsailClient::rebootInstance(), QtAws::EC2::Ec2Client::rebootInstances(), QtAws::DAX::DaxClient::rebootNode(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::rebootReplicationInstance(), QtAws::WorkSpaces::WorkSpacesClient::rebootWorkspaces(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::rebuildEnvironment(), QtAws::WorkSpaces::WorkSpacesClient::rebuildWorkspaces(), QtAws::SQS::SqsClient::receiveMessage(), QtAws::Rekognition::RekognitionClient::recognizeCelebrities(), QtAws::SWF::SwfClient::recordActivityTaskHeartbeat(), QtAws::AutoScaling::AutoScalingClient::recordLifecycleActionHeartbeat(), QtAws::KMS::KmsClient::reEncrypt(), QtAws::StorageGateway::StorageGatewayClient::refreshCache(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::refreshSchemas(), QtAws::Support::SupportClient::refreshTrustedAdvisorCheck(), QtAws::SWF::SwfClient::registerActivityType(), QtAws::CodeDeploy::CodeDeployClient::registerApplicationRevision(), QtAws::IoT::IoTClient::registerCACertificate(), QtAws::IoT::IoTClient::registerCertificate(), QtAws::ECS::EcsClient::registerContainerInstance(), QtAws::Inspector::InspectorClient::registerCrossAccountAccessRole(), QtAws::SSM::SsmClient::registerDefaultPatchBaseline(), QtAws::CognitoSync::CognitoSyncClient::registerDevice(), QtAws::Route53Domains::Route53DomainsClient::registerDomain(), QtAws::SWF::SwfClient::registerDomain(), QtAws::OpsWorks::OpsWorksClient::registerEcsCluster(), QtAws::OpsWorks::OpsWorksClient::registerElasticIp(), QtAws::DirectoryService::DirectoryServiceClient::registerEventTopic(), QtAws::EC2::Ec2Client::registerImage(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::registerInstance(), QtAws::OpsWorks::OpsWorksClient::registerInstance(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::registerInstancesWithLoadBalancer(), QtAws::Batch::BatchClient::registerJobDefinition(), QtAws::CodeDeploy::CodeDeployClient::registerOnPremisesInstance(), QtAws::SSM::SsmClient::registerPatchBaselineForPatchGroup(), QtAws::OpsWorks::OpsWorksClient::registerRdsDbInstance(), QtAws::ApplicationAutoScaling::ApplicationAutoScalingClient::registerScalableTarget(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::registerTargets(), QtAws::SSM::SsmClient::registerTargetWithMaintenanceWindow(), QtAws::ECS::EcsClient::registerTaskDefinition(), QtAws::SSM::SsmClient::registerTaskWithMaintenanceWindow(), QtAws::IoT::IoTClient::registerThing(), QtAws::WorkMail::WorkMailClient::registerToWorkMail(), QtAws::OpsWorks::OpsWorksClient::registerVolume(), QtAws::SWF::SwfClient::registerWorkflowType(), QtAws::MTurk::MTurkClient::rejectAssignment(), QtAws::IoT::IoTClient::rejectCertificateTransfer(), QtAws::ServiceCatalog::ServiceCatalogClient::rejectPortfolioShare(), QtAws::MTurk::MTurkClient::rejectQualificationRequest(), QtAws::EC2::Ec2Client::rejectVpcEndpointConnections(), QtAws::EC2::Ec2Client::rejectVpcPeeringConnection(), QtAws::EC2::Ec2Client::releaseAddress(), QtAws::EC2::Ec2Client::releaseHosts(), QtAws::Lightsail::LightsailClient::releaseStaticIp(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::reloadTables(), QtAws::Organizations::OrganizationsClient::removeAccountFromOrganization(), QtAws::WorkDocs::WorkDocsClient::removeAllResourcePermissions(), QtAws::Inspector::InspectorClient::removeAttributesFromFindings(), QtAws::EMR::EmrClient::removeAutoScalingPolicy(), QtAws::IAM::IamClient::removeClientIDFromOpenIDConnectProvider(), QtAws::CloudDirectory::CloudDirectoryClient::removeFacetFromObject(), QtAws::DirectoryService::DirectoryServiceClient::removeIpRoutes(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::removeListenerCertificates(), QtAws::CloudWatchEvents::CloudWatchEventsClient::removePermission(), QtAws::SQS::SqsClient::removePermission(), QtAws::SNS::SnsClient::removePermission(), QtAws::Lambda::LambdaClient::removePermission(), QtAws::WorkDocs::WorkDocsClient::removeResourcePermission(), QtAws::RDS::RdsClient::removeRoleFromDBCluster(), QtAws::IAM::IamClient::removeRoleFromInstanceProfile(), QtAws::RDS::RdsClient::removeSourceIdentifierFromSubscription(), QtAws::CloudTrail::CloudTrailClient::removeTags(), QtAws::ElasticsearchService::ElasticsearchServiceClient::removeTags(), QtAws::DataPipeline::DataPipelineClient::removeTags(), QtAws::EMR::EmrClient::removeTags(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::removeTags(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::removeTags(), QtAws::ACM::AcmClient::removeTagsFromCertificate(), QtAws::CodeDeploy::CodeDeployClient::removeTagsFromOnPremisesInstances(), QtAws::CloudHSM::CloudHSMClient::removeTagsFromResource(), QtAws::DirectoryService::DirectoryServiceClient::removeTagsFromResource(), QtAws::ElastiCache::ElastiCacheClient::removeTagsFromResource(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::removeTagsFromResource(), QtAws::StorageGateway::StorageGatewayClient::removeTagsFromResource(), QtAws::RDS::RdsClient::removeTagsFromResource(), QtAws::SSM::SsmClient::removeTagsFromResource(), QtAws::Kinesis::KinesisClient::removeTagsFromStream(), QtAws::Glacier::GlacierClient::removeTagsFromVault(), QtAws::CloudWatchEvents::CloudWatchEventsClient::removeTargets(), QtAws::IoT::IoTClient::removeThingFromThingGroup(), QtAws::IAM::IamClient::removeUserFromGroup(), QtAws::Route53Domains::Route53DomainsClient::renewDomain(), QtAws::DeviceFarm::DeviceFarmClient::renewOffering(), QtAws::SES::SesClient::reorderReceiptRuleSet(), QtAws::EC2::Ec2Client::replaceIamInstanceProfileAssociation(), QtAws::EC2::Ec2Client::replaceNetworkAclAssociation(), QtAws::EC2::Ec2Client::replaceNetworkAclEntry(), QtAws::EC2::Ec2Client::replaceRoute(), QtAws::EC2::Ec2Client::replaceRouteTableAssociation(), QtAws::IoT::IoTClient::replaceTopicRule(), QtAws::EC2::Ec2Client::reportInstanceStatus(), QtAws::DataPipeline::DataPipelineClient::reportTaskProgress(), QtAws::DataPipeline::DataPipelineClient::reportTaskRunnerHeartbeat(), QtAws::SWF::SwfClient::requestCancelWorkflowExecution(), QtAws::ACM::AcmClient::requestCertificate(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::requestEnvironmentInfo(), QtAws::EC2::Ec2Client::requestSpotFleet(), QtAws::EC2::Ec2Client::requestSpotInstances(), QtAws::GameLift::GameLiftClient::requestUploadCredentials(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::resendConfirmationCode(), QtAws::Route53Domains::Route53DomainsClient::resendContactReachabilityEmail(), QtAws::ACM::AcmClient::resendValidationEmail(), QtAws::StorageGateway::StorageGatewayClient::resetCache(), QtAws::ElastiCache::ElastiCacheClient::resetCacheParameterGroup(), QtAws::Redshift::RedshiftClient::resetClusterParameterGroup(), QtAws::RDS::RdsClient::resetDBClusterParameterGroup(), QtAws::RDS::RdsClient::resetDBParameterGroup(), QtAws::Greengrass::GreengrassClient::resetDeployments(), QtAws::EC2::Ec2Client::resetFpgaImageAttribute(), QtAws::EC2::Ec2Client::resetImageAttribute(), QtAws::EC2::Ec2Client::resetInstanceAttribute(), QtAws::Glue::GlueClient::resetJobBookmark(), QtAws::EC2::Ec2Client::resetNetworkInterfaceAttribute(), QtAws::WorkMail::WorkMailClient::resetPassword(), QtAws::IAM::IamClient::resetServiceSpecificCredential(), QtAws::EC2::Ec2Client::resetSnapshotAttribute(), QtAws::GameLift::GameLiftClient::resolveAlias(), QtAws::Support::SupportClient::resolveCase(), QtAws::MarketplaceMetering::MarketplaceMeteringClient::resolveCustomer(), QtAws::AlexaForBusiness::AlexaForBusinessClient::resolveRoom(), QtAws::SWF::SwfClient::respondActivityTaskCanceled(), QtAws::SWF::SwfClient::respondActivityTaskCompleted(), QtAws::SWF::SwfClient::respondActivityTaskFailed(), QtAws::SWF::SwfClient::respondDecisionTaskCompleted(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::respondToAuthChallenge(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::restartAppServer(), QtAws::EC2::Ec2Client::restoreAddressToClassic(), QtAws::RDS::RdsClient::restoreDBClusterFromS3(), QtAws::RDS::RdsClient::restoreDBClusterFromSnapshot(), QtAws::RDS::RdsClient::restoreDBClusterToPointInTime(), QtAws::RDS::RdsClient::restoreDBInstanceFromDBSnapshot(), QtAws::RDS::RdsClient::restoreDBInstanceFromS3(), QtAws::RDS::RdsClient::restoreDBInstanceToPointInTime(), QtAws::Redshift::RedshiftClient::restoreFromClusterSnapshot(), QtAws::DirectoryService::DirectoryServiceClient::restoreFromSnapshot(), QtAws::S3::S3Client::restoreObject(), QtAws::OpsWorksCM::OpsWorksCMClient::restoreServer(), QtAws::DynamoDB::DynamoDBClient::restoreTableFromBackup(), QtAws::Redshift::RedshiftClient::restoreTableFromClusterSnapshot(), QtAws::DynamoDB::DynamoDBClient::restoreTableToPointInTime(), QtAws::AutoScaling::AutoScalingClient::resumeProcesses(), QtAws::IAM::IamClient::resyncMFADevice(), QtAws::KMS::KmsClient::retireGrant(), QtAws::Route53Domains::Route53DomainsClient::retrieveDomainAuthCode(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::retrieveEnvironmentInfo(), QtAws::StorageGateway::StorageGatewayClient::retrieveTapeArchive(), QtAws::StorageGateway::StorageGatewayClient::retrieveTapeRecoveryPoint(), QtAws::CodePipeline::CodePipelineClient::retryStageExecution(), QtAws::ElastiCache::ElastiCacheClient::revokeCacheSecurityGroupIngress(), QtAws::Redshift::RedshiftClient::revokeClusterSecurityGroupIngress(), QtAws::RDS::RdsClient::revokeDBSecurityGroupIngress(), QtAws::KMS::KmsClient::revokeGrant(), QtAws::AlexaForBusiness::AlexaForBusinessClient::revokeInvitation(), QtAws::EC2::Ec2Client::revokeSecurityGroupEgress(), QtAws::EC2::Ec2Client::revokeSecurityGroupIngress(), QtAws::Redshift::RedshiftClient::revokeSnapshotAccess(), QtAws::MediaPackage::MediaPackageClient::rotateChannelCredentials(), QtAws::Redshift::RedshiftClient::rotateEncryptionKey(), QtAws::EC2::Ec2Client::runInstances(), QtAws::EMR::EmrClient::runJobFlow(), QtAws::EC2::Ec2Client::runScheduledInstances(), QtAws::ECS::EcsClient::runTask(), QtAws::DynamoDB::DynamoDBClient::scan(), QtAws::ServiceCatalog::ServiceCatalogClient::scanProvisionedProducts(), QtAws::KMS::KmsClient::scheduleKeyDeletion(), QtAws::DeviceFarm::DeviceFarmClient::scheduleRun(), QtAws::CloudSearchDomain::CloudSearchDomainClient::search(), QtAws::AlexaForBusiness::AlexaForBusinessClient::searchDevices(), QtAws::Rekognition::RekognitionClient::searchFaces(), QtAws::Rekognition::RekognitionClient::searchFacesByImage(), QtAws::GameLift::GameLiftClient::searchGameSessions(), QtAws::IoT::IoTClient::searchIndex(), QtAws::ServiceCatalog::ServiceCatalogClient::searchProducts(), QtAws::ServiceCatalog::ServiceCatalogClient::searchProductsAsAdmin(), QtAws::AlexaForBusiness::AlexaForBusinessClient::searchProfiles(), QtAws::ServiceCatalog::ServiceCatalogClient::searchProvisionedProducts(), QtAws::ResourceGroups::ResourceGroupsClient::searchResources(), QtAws::AlexaForBusiness::AlexaForBusinessClient::searchRooms(), QtAws::AlexaForBusiness::AlexaForBusinessClient::searchSkillGroups(), QtAws::AlexaForBusiness::AlexaForBusinessClient::searchUsers(), QtAws::SimpleDB::SimpleDBClient::select(), QtAws::SSM::SsmClient::sendAutomationSignal(), QtAws::MTurk::MTurkClient::sendBonus(), QtAws::SES::SesClient::sendBounce(), QtAws::SES::SesClient::sendBulkTemplatedEmail(), QtAws::SSM::SsmClient::sendCommand(), QtAws::SES::SesClient::sendCustomVerificationEmail(), QtAws::SES::SesClient::sendEmail(), QtAws::AlexaForBusiness::AlexaForBusinessClient::sendInvitation(), QtAws::SQS::SqsClient::sendMessage(), QtAws::SQS::SqsClient::sendMessageBatch(), QtAws::Pinpoint::PinpointClient::sendMessages(), QtAws::SES::SesClient::sendRawEmail(), QtAws::SFN::SfnClient::sendTaskFailure(), QtAws::SFN::SfnClient::sendTaskHeartbeat(), QtAws::SFN::SfnClient::sendTaskSuccess(), QtAws::SES::SesClient::sendTemplatedEmail(), QtAws::MTurk::MTurkClient::sendTestEventNotification(), QtAws::Pinpoint::PinpointClient::sendUsersMessages(), QtAws::SES::SesClient::setActiveReceiptRuleSet(), QtAws::CloudWatch::CloudWatchClient::setAlarmState(), QtAws::CognitoSync::CognitoSyncClient::setCognitoEvents(), QtAws::Glacier::GlacierClient::setDataRetrievalPolicy(), QtAws::IoT::IoTClient::setDefaultAuthorizer(), QtAws::IAM::IamClient::setDefaultPolicyVersion(), QtAws::IoT::IoTClient::setDefaultPolicyVersion(), QtAws::AutoScaling::AutoScalingClient::setDesiredCapacity(), QtAws::SNS::SnsClient::setEndpointAttributes(), QtAws::SES::SesClient::setIdentityDkimEnabled(), QtAws::SES::SesClient::setIdentityFeedbackForwardingEnabled(), QtAws::SES::SesClient::setIdentityHeadersInNotificationsEnabled(), QtAws::SES::SesClient::setIdentityMailFromDomain(), QtAws::SES::SesClient::setIdentityNotificationTopic(), QtAws::CognitoSync::CognitoSyncClient::setIdentityPoolConfiguration(), QtAws::CognitoIdentity::CognitoIdentityClient::setIdentityPoolRoles(), QtAws::AutoScaling::AutoScalingClient::setInstanceHealth(), QtAws::AutoScaling::AutoScalingClient::setInstanceProtection(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setIpAddressType(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerListenerSSLCertificate(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerPoliciesForBackendServer(), QtAws::ElasticLoadBalancing::ElasticLoadBalancingClient::setLoadBalancerPoliciesOfListener(), QtAws::OpsWorks::OpsWorksClient::setLoadBasedAutoScaling(), QtAws::StorageGateway::StorageGatewayClient::setLocalConsolePassword(), QtAws::IoT::IoTClient::setLoggingOptions(), QtAws::OpsWorks::OpsWorksClient::setPermission(), QtAws::SNS::SnsClient::setPlatformApplicationAttributes(), QtAws::SQS::SqsClient::setQueueAttributes(), QtAws::SES::SesClient::setReceiptRulePosition(), QtAws::ECR::EcrClient::setRepositoryPolicy(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setRiskConfiguration(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setRulePriorities(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setSecurityGroups(), QtAws::SNS::SnsClient::setSMSAttributes(), QtAws::CloudFormation::CloudFormationClient::setStackPolicy(), QtAws::DataPipeline::DataPipelineClient::setStatus(), QtAws::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::setSubnets(), QtAws::SNS::SnsClient::setSubscriptionAttributes(), QtAws::Inspector::InspectorClient::setTagsForResource(), QtAws::DataPipeline::DataPipelineClient::setTaskStatus(), QtAws::EMR::EmrClient::setTerminationProtection(), QtAws::OpsWorks::OpsWorksClient::setTimeBasedAutoScaling(), QtAws::SNS::SnsClient::setTopicAttributes(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUICustomization(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserMFAPreference(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserPoolMfaConfig(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::setUserSettings(), QtAws::IoT::IoTClient::setV2LoggingLevel(), QtAws::IoT::IoTClient::setV2LoggingOptions(), QtAws::Glacier::GlacierClient::setVaultAccessPolicy(), QtAws::Glacier::GlacierClient::setVaultNotifications(), QtAws::EMR::EmrClient::setVisibleToAllUsers(), QtAws::StorageGateway::StorageGatewayClient::shutdownGateway(), QtAws::CloudFormation::CloudFormationClient::signalResource(), QtAws::SWF::SwfClient::signalWorkflowExecution(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::signUp(), QtAws::IAM::IamClient::simulateCustomPolicy(), QtAws::IAM::IamClient::simulatePrincipalPolicy(), QtAws::CodeDeploy::CodeDeployClient::skipWaitTimeForInstanceTermination(), QtAws::Kinesis::KinesisClient::splitShard(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::startApplication(), QtAws::Inspector::InspectorClient::startAssessmentRun(), QtAws::SSM::SsmClient::startAutomationExecution(), QtAws::CodeBuild::CodeBuildClient::startBuild(), QtAws::Rekognition::RekognitionClient::startCelebrityRecognition(), QtAws::MediaLive::MediaLiveClient::startChannel(), QtAws::ConfigService::ConfigServiceClient::startConfigRulesEvaluation(), QtAws::ConfigService::ConfigServiceClient::startConfigurationRecorder(), QtAws::Rekognition::RekognitionClient::startContentModeration(), QtAws::Glue::GlueClient::startCrawler(), QtAws::Glue::GlueClient::startCrawlerSchedule(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::startDataCollectionByAgentIds(), QtAws::RDS::RdsClient::startDBInstance(), QtAws::AlexaForBusiness::AlexaForBusinessClient::startDeviceSync(), QtAws::SFN::SfnClient::startExecution(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::startExportTask(), QtAws::Rekognition::RekognitionClient::startFaceDetection(), QtAws::Rekognition::RekognitionClient::startFaceSearch(), QtAws::AppStream::AppStreamClient::startFleet(), QtAws::GameLift::GameLiftClient::startGameSessionPlacement(), QtAws::StorageGateway::StorageGatewayClient::startGateway(), QtAws::AppStream::AppStreamClient::startImageBuilder(), QtAws::LexModelBuildingService::LexModelBuildingServiceClient::startImport(), QtAws::OpsWorks::OpsWorksClient::startInstance(), QtAws::Lightsail::LightsailClient::startInstance(), QtAws::EC2::Ec2Client::startInstances(), QtAws::Glue::GlueClient::startJobRun(), QtAws::Rekognition::RekognitionClient::startLabelDetection(), QtAws::ECR::EcrClient::startLifecyclePolicyPreview(), QtAws::CloudTrail::CloudTrailClient::startLogging(), QtAws::OpsWorksCM::OpsWorksCMClient::startMaintenance(), QtAws::GameLift::GameLiftClient::startMatchBackfill(), QtAws::GameLift::GameLiftClient::startMatchmaking(), QtAws::GuardDuty::GuardDutyClient::startMonitoringMembers(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::startNextPendingJobExecution(), QtAws::SageMaker::SageMakerClient::startNotebookInstance(), QtAws::SMS::SmsClient::startOnDemandReplicationRun(), QtAws::Rekognition::RekognitionClient::startPersonTracking(), QtAws::CodePipeline::CodePipelineClient::startPipelineExecution(), QtAws::Athena::AthenaClient::startQueryExecution(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::startReplicationTask(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::startReplicationTaskAssessment(), QtAws::AppSync::AppSyncClient::startSchemaCreation(), QtAws::DirectoryService::DirectoryServiceClient::startSchemaExtension(), QtAws::OpsWorks::OpsWorksClient::startStack(), QtAws::Kinesis::KinesisClient::startStreamEncryption(), QtAws::Rekognition::RekognitionClient::startStreamProcessor(), QtAws::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::startSupportDataExport(), QtAws::ECS::EcsClient::startTask(), QtAws::IoT::IoTClient::startThingRegistrationTask(), QtAws::Comprehend::ComprehendClient::startTopicsDetectionJob(), QtAws::TranscribeService::TranscribeServiceClient::startTranscriptionJob(), QtAws::Glue::GlueClient::startTrigger(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::startUserImportJob(), QtAws::SWF::SwfClient::startWorkflowExecution(), QtAws::WorkSpaces::WorkSpacesClient::startWorkspaces(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::stopApplication(), QtAws::Inspector::InspectorClient::stopAssessmentRun(), QtAws::SSM::SsmClient::stopAutomationExecution(), QtAws::CodeBuild::CodeBuildClient::stopBuild(), QtAws::MediaLive::MediaLiveClient::stopChannel(), QtAws::ConfigService::ConfigServiceClient::stopConfigurationRecorder(), QtAws::Glue::GlueClient::stopCrawler(), QtAws::Glue::GlueClient::stopCrawlerSchedule(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::stopDataCollectionByAgentIds(), QtAws::RDS::RdsClient::stopDBInstance(), QtAws::CodeDeploy::CodeDeployClient::stopDeployment(), QtAws::SFN::SfnClient::stopExecution(), QtAws::AppStream::AppStreamClient::stopFleet(), QtAws::GameLift::GameLiftClient::stopGameSessionPlacement(), QtAws::AppStream::AppStreamClient::stopImageBuilder(), QtAws::OpsWorks::OpsWorksClient::stopInstance(), QtAws::Lightsail::LightsailClient::stopInstance(), QtAws::EC2::Ec2Client::stopInstances(), QtAws::CloudTrail::CloudTrailClient::stopLogging(), QtAws::GameLift::GameLiftClient::stopMatchmaking(), QtAws::GuardDuty::GuardDutyClient::stopMonitoringMembers(), QtAws::SageMaker::SageMakerClient::stopNotebookInstance(), QtAws::Athena::AthenaClient::stopQueryExecution(), QtAws::DeviceFarm::DeviceFarmClient::stopRemoteAccessSession(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::stopReplicationTask(), QtAws::DeviceFarm::DeviceFarmClient::stopRun(), QtAws::OpsWorks::OpsWorksClient::stopStack(), QtAws::CloudFormation::CloudFormationClient::stopStackSetOperation(), QtAws::Kinesis::KinesisClient::stopStreamEncryption(), QtAws::Rekognition::RekognitionClient::stopStreamProcessor(), QtAws::ECS::EcsClient::stopTask(), QtAws::IoT::IoTClient::stopThingRegistrationTask(), QtAws::SageMaker::SageMakerClient::stopTrainingJob(), QtAws::Glue::GlueClient::stopTrigger(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::stopUserImportJob(), QtAws::WorkSpaces::WorkSpacesClient::stopWorkspaces(), QtAws::ECS::EcsClient::submitContainerStateChange(), QtAws::Batch::BatchClient::submitJob(), QtAws::ECS::EcsClient::submitTaskStateChange(), QtAws::SNS::SnsClient::subscribe(), QtAws::CognitoSync::CognitoSyncClient::subscribeToDataset(), QtAws::Inspector::InspectorClient::subscribeToEvent(), QtAws::CloudSearchDomain::CloudSearchDomainClient::suggest(), QtAws::AutoScaling::AutoScalingClient::suspendProcesses(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::swapEnvironmentCNAMEs(), QtAws::Polly::PollyClient::synthesizeSpeech(), QtAws::ResourceGroups::ResourceGroupsClient::tag(), QtAws::CloudWatchLogs::CloudWatchLogsClient::tagLogGroup(), QtAws::CodeStar::CodeStarClient::tagProject(), QtAws::SQS::SqsClient::tagQueue(), QtAws::CloudHSMV2::CloudHSMV2Client::tagResource(), QtAws::DAX::DaxClient::tagResource(), QtAws::CloudFront::CloudFrontClient::tagResource(), QtAws::Lambda::LambdaClient::tagResource(), QtAws::DynamoDB::DynamoDBClient::tagResource(), QtAws::AppStream::AppStreamClient::tagResource(), QtAws::KMS::KmsClient::tagResource(), QtAws::AlexaForBusiness::AlexaForBusinessClient::tagResource(), QtAws::DirectConnect::DirectConnectClient::tagResource(), QtAws::CloudDirectory::CloudDirectoryClient::tagResource(), QtAws::OpsWorks::OpsWorksClient::tagResource(), QtAws::APIGateway::APIGatewayClient::tagResource(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::tagResources(), QtAws::KinesisVideo::KinesisVideoClient::tagStream(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::terminateEnvironment(), QtAws::AutoScaling::AutoScalingClient::terminateInstanceInAutoScalingGroup(), QtAws::EC2::Ec2Client::terminateInstances(), QtAws::Batch::BatchClient::terminateJob(), QtAws::EMR::EmrClient::terminateJobFlows(), QtAws::ServiceCatalog::ServiceCatalogClient::terminateProvisionedProduct(), QtAws::SWF::SwfClient::terminateWorkflowExecution(), QtAws::WorkSpaces::WorkSpacesClient::terminateWorkspaces(), QtAws::IoT::IoTClient::testAuthorization(), QtAws::DatabaseMigrationService::DatabaseMigrationServiceClient::testConnection(), QtAws::Route53::Route53Client::testDNSAnswer(), QtAws::CloudWatchEvents::CloudWatchEventsClient::testEventPattern(), QtAws::ElastiCache::ElastiCacheClient::testFailover(), QtAws::APIGateway::APIGatewayClient::testInvokeAuthorizer(), QtAws::IoT::IoTClient::testInvokeAuthorizer(), QtAws::APIGateway::APIGatewayClient::testInvokeMethod(), QtAws::CloudWatchLogs::CloudWatchLogsClient::testMetricFilter(), QtAws::SES::SesClient::testRenderTemplate(), QtAws::CodeCommit::CodeCommitClient::testRepositoryTriggers(), QtAws::ElasticTranscoder::ElasticTranscoderClient::testRole(), QtAws::IoT::IoTClient::transferCertificate(), QtAws::Route53Domains::Route53DomainsClient::transferDomain(), QtAws::Translate::TranslateClient::translateText(), QtAws::GuardDuty::GuardDutyClient::unarchiveFindings(), QtAws::OpsWorks::OpsWorksClient::unassignInstance(), QtAws::EC2::Ec2Client::unassignIpv6Addresses(), QtAws::EC2::Ec2Client::unassignPrivateIpAddresses(), QtAws::OpsWorks::OpsWorksClient::unassignVolume(), QtAws::CognitoIdentity::CognitoIdentityClient::unlinkDeveloperIdentity(), QtAws::CognitoIdentity::CognitoIdentityClient::unlinkIdentity(), QtAws::EC2::Ec2Client::unmonitorInstances(), QtAws::Lightsail::LightsailClient::unpeerVpc(), QtAws::SNS::SnsClient::unsubscribe(), QtAws::CognitoSync::CognitoSyncClient::unsubscribeFromDataset(), QtAws::Inspector::InspectorClient::unsubscribeFromEvent(), QtAws::ResourceGroups::ResourceGroupsClient::untag(), QtAws::CloudWatchLogs::CloudWatchLogsClient::untagLogGroup(), QtAws::CodeStar::CodeStarClient::untagProject(), QtAws::SQS::SqsClient::untagQueue(), QtAws::CloudHSMV2::CloudHSMV2Client::untagResource(), QtAws::DAX::DaxClient::untagResource(), QtAws::CloudFront::CloudFrontClient::untagResource(), QtAws::Lambda::LambdaClient::untagResource(), QtAws::DynamoDB::DynamoDBClient::untagResource(), QtAws::AppStream::AppStreamClient::untagResource(), QtAws::KMS::KmsClient::untagResource(), QtAws::AlexaForBusiness::AlexaForBusinessClient::untagResource(), QtAws::DirectConnect::DirectConnectClient::untagResource(), QtAws::CloudDirectory::CloudDirectoryClient::untagResource(), QtAws::OpsWorks::OpsWorksClient::untagResource(), QtAws::APIGateway::APIGatewayClient::untagResource(), QtAws::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::untagResources(), QtAws::KinesisVideo::KinesisVideoClient::untagStream(), QtAws::IAM::IamClient::updateAccessKey(), QtAws::APIGateway::APIGatewayClient::updateAccount(), QtAws::IAM::IamClient::updateAccountPasswordPolicy(), QtAws::SES::SesClient::updateAccountSendingEnabled(), QtAws::Pinpoint::PinpointClient::updateAdmChannel(), QtAws::Lambda::LambdaClient::updateAlias(), QtAws::KMS::KmsClient::updateAlias(), QtAws::GameLift::GameLiftClient::updateAlias(), QtAws::AppSync::AppSyncClient::updateApiKey(), QtAws::APIGateway::APIGatewayClient::updateApiKey(), QtAws::Pinpoint::PinpointClient::updateApnsChannel(), QtAws::Pinpoint::PinpointClient::updateApnsSandboxChannel(), QtAws::Pinpoint::PinpointClient::updateApnsVoipChannel(), QtAws::Pinpoint::PinpointClient::updateApnsVoipSandboxChannel(), QtAws::OpsWorks::OpsWorksClient::updateApp(), QtAws::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::updateApplication(), QtAws::KinesisAnalytics::KinesisAnalyticsClient::updateApplication(), QtAws::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::updateApplication(), QtAws::CodeDeploy::CodeDeployClient::updateApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateApplication(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateApplicationResourceLifecycle(), QtAws::Pinpoint::PinpointClient::updateApplicationSettings(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateApplicationVersion(), QtAws::Inspector::InspectorClient::updateAssessmentTarget(), QtAws::SSM::SsmClient::updateAssociation(), QtAws::SSM::SsmClient::updateAssociationStatus(), QtAws::IAM::IamClient::updateAssumeRolePolicy(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateAuthEventFeedback(), QtAws::APIGateway::APIGatewayClient::updateAuthorizer(), QtAws::IoT::IoTClient::updateAuthorizer(), QtAws::AutoScaling::AutoScalingClient::updateAutoScalingGroup(), QtAws::CloudSearch::CloudSearchClient::updateAvailabilityOptions(), QtAws::Pinpoint::PinpointClient::updateBaiduChannel(), QtAws::StorageGateway::StorageGatewayClient::updateBandwidthRateLimit(), QtAws::APIGateway::APIGatewayClient::updateBasePathMapping(), QtAws::MachineLearning::MachineLearningClient::updateBatchPrediction(), QtAws::MQ::MqClient::updateBroker(), QtAws::Budgets::BudgetsClient::updateBudget(), QtAws::GameLift::GameLiftClient::updateBuild(), QtAws::WAF::WafClient::updateByteMatchSet(), QtAws::WAFRegional::WAFRegionalClient::updateByteMatchSet(), QtAws::IoT::IoTClient::updateCACertificate(), QtAws::Pinpoint::PinpointClient::updateCampaign(), QtAws::IoT::IoTClient::updateCertificate(), QtAws::ACM::AcmClient::updateCertificateOptions(), QtAws::MediaPackage::MediaPackageClient::updateChannel(), QtAws::MediaLive::MediaLiveClient::updateChannel(), QtAws::StorageGateway::StorageGatewayClient::updateChapCredentials(), QtAws::Glue::GlueClient::updateClassifier(), QtAws::APIGateway::APIGatewayClient::updateClientCertificate(), QtAws::CloudFront::CloudFrontClient::updateCloudFrontOriginAccessIdentity(), QtAws::Snowball::SnowballClient::updateCluster(), QtAws::DAX::DaxClient::updateCluster(), QtAws::CodeCommit::CodeCommitClient::updateComment(), QtAws::Batch::BatchClient::updateComputeEnvironment(), QtAws::DirectoryService::DirectoryServiceClient::updateConditionalForwarder(), QtAws::MQ::MqClient::updateConfiguration(), QtAws::SES::SesClient::updateConfigurationSetEventDestination(), QtAws::SES::SesClient::updateConfigurationSetReputationMetricsEnabled(), QtAws::SES::SesClient::updateConfigurationSetSendingEnabled(), QtAws::SES::SesClient::updateConfigurationSetTrackingOptions(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateConfigurationTemplate(), QtAws::Glue::GlueClient::updateConnection(), QtAws::Greengrass::GreengrassClient::updateConnectivityInfo(), QtAws::ServiceCatalog::ServiceCatalogClient::updateConstraint(), QtAws::ECS::EcsClient::updateContainerAgent(), QtAws::ECS::EcsClient::updateContainerInstancesState(), QtAws::DynamoDB::DynamoDBClient::updateContinuousBackups(), QtAws::Greengrass::GreengrassClient::updateCoreDefinition(), QtAws::Glue::GlueClient::updateCrawler(), QtAws::Glue::GlueClient::updateCrawlerSchedule(), QtAws::SES::SesClient::updateCustomVerificationEmailTemplate(), QtAws::Glue::GlueClient::updateDatabase(), QtAws::KinesisVideo::KinesisVideoClient::updateDataRetention(), QtAws::AppSync::AppSyncClient::updateDataSource(), QtAws::MachineLearning::MachineLearningClient::updateDataSource(), QtAws::CodeCommit::CodeCommitClient::updateDefaultBranch(), QtAws::APIGateway::APIGatewayClient::updateDeployment(), QtAws::CodeDeploy::CodeDeployClient::updateDeploymentGroup(), QtAws::Firehose::FirehoseClient::updateDestination(), QtAws::GuardDuty::GuardDutyClient::updateDetector(), QtAws::Glue::GlueClient::updateDevEndpoint(), QtAws::AlexaForBusiness::AlexaForBusinessClient::updateDevice(), QtAws::Greengrass::GreengrassClient::updateDeviceDefinition(), QtAws::DeviceFarm::DeviceFarmClient::updateDevicePool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateDeviceStatus(), QtAws::AppStream::AppStreamClient::updateDirectoryConfig(), QtAws::CloudFront::CloudFrontClient::updateDistribution(), QtAws::WorkDocs::WorkDocsClient::updateDocument(), QtAws::SSM::SsmClient::updateDocument(), QtAws::APIGateway::APIGatewayClient::updateDocumentationPart(), QtAws::APIGateway::APIGatewayClient::updateDocumentationVersion(), QtAws::SSM::SsmClient::updateDocumentDefaultVersion(), QtAws::WorkDocs::WorkDocsClient::updateDocumentVersion(), QtAws::Route53Domains::Route53DomainsClient::updateDomainContact(), QtAws::Route53Domains::Route53DomainsClient::updateDomainContactPrivacy(), QtAws::Lightsail::LightsailClient::updateDomainEntry(), QtAws::APIGateway::APIGatewayClient::updateDomainName(), QtAws::Route53Domains::Route53DomainsClient::updateDomainNameservers(), QtAws::OpsWorks::OpsWorksClient::updateElasticIp(), QtAws::ElasticsearchService::ElasticsearchServiceClient::updateElasticsearchDomainConfig(), QtAws::Pinpoint::PinpointClient::updateEmailChannel(), QtAws::SageMaker::SageMakerClient::updateEndpoint(), QtAws::Pinpoint::PinpointClient::updateEndpoint(), QtAws::Pinpoint::PinpointClient::updateEndpointsBatch(), QtAws::SageMaker::SageMakerClient::updateEndpointWeightsAndCapacities(), QtAws::Cloud9::Cloud9Client::updateEnvironment(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateEnvironment(), QtAws::Cloud9::Cloud9Client::updateEnvironmentMembership(), QtAws::MachineLearning::MachineLearningClient::updateEvaluation(), QtAws::IoT::IoTClient::updateEventConfigurations(), QtAws::Lambda::LambdaClient::updateEventSourceMapping(), QtAws::MTurk::MTurkClient::updateExpirationForHIT(), QtAws::CloudDirectory::CloudDirectoryClient::updateFacet(), QtAws::GuardDuty::GuardDutyClient::updateFindingsFeedback(), QtAws::AppStream::AppStreamClient::updateFleet(), QtAws::GameLift::GameLiftClient::updateFleetAttributes(), QtAws::GameLift::GameLiftClient::updateFleetCapacity(), QtAws::GameLift::GameLiftClient::updateFleetPortSettings(), QtAws::WorkDocs::WorkDocsClient::updateFolder(), QtAws::Lambda::LambdaClient::updateFunctionCode(), QtAws::Lambda::LambdaClient::updateFunctionConfiguration(), QtAws::Greengrass::GreengrassClient::updateFunctionDefinition(), QtAws::GameLift::GameLiftClient::updateGameSession(), QtAws::GameLift::GameLiftClient::updateGameSessionQueue(), QtAws::StorageGateway::StorageGatewayClient::updateGatewayInformation(), QtAws::APIGateway::APIGatewayClient::updateGatewayResponse(), QtAws::StorageGateway::StorageGatewayClient::updateGatewaySoftwareNow(), QtAws::Pinpoint::PinpointClient::updateGcmChannel(), QtAws::WAF::WafClient::updateGeoMatchSet(), QtAws::WAFRegional::WAFRegionalClient::updateGeoMatchSet(), QtAws::DynamoDB::DynamoDBClient::updateGlobalTable(), QtAws::AppSync::AppSyncClient::updateGraphqlApi(), QtAws::ResourceGroups::ResourceGroupsClient::updateGroup(), QtAws::Greengrass::GreengrassClient::updateGroup(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateGroup(), QtAws::IAM::IamClient::updateGroup(), QtAws::Greengrass::GreengrassClient::updateGroupCertificateConfiguration(), QtAws::ResourceGroups::ResourceGroupsClient::updateGroupQuery(), QtAws::Route53::Route53Client::updateHealthCheck(), QtAws::MTurk::MTurkClient::updateHITReviewStatus(), QtAws::MTurk::MTurkClient::updateHITTypeOfHIT(), QtAws::Route53::Route53Client::updateHostedZoneComment(), QtAws::CognitoIdentity::CognitoIdentityClient::updateIdentityPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateIdentityProvider(), QtAws::IoT::IoTClient::updateIndexingConfiguration(), QtAws::MediaLive::MediaLiveClient::updateInput(), QtAws::MediaLive::MediaLiveClient::updateInputSecurityGroup(), QtAws::OpsWorks::OpsWorksClient::updateInstance(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::updateInstanceCustomHealthStatus(), QtAws::APIGateway::APIGatewayClient::updateIntegration(), QtAws::APIGateway::APIGatewayClient::updateIntegrationResponse(), QtAws::GuardDuty::GuardDutyClient::updateIPSet(), QtAws::WAF::WafClient::updateIPSet(), QtAws::WAFRegional::WAFRegionalClient::updateIPSet(), QtAws::DynamoDB::DynamoDBClient::updateItem(), QtAws::ImportExport::ImportExportClient::updateJob(), QtAws::Snowball::SnowballClient::updateJob(), QtAws::Glue::GlueClient::updateJob(), QtAws::IoTJobsDataPlane::IoTJobsDataPlaneClient::updateJobExecution(), QtAws::Batch::BatchClient::updateJobQueue(), QtAws::MediaConvert::MediaConvertClient::updateJobTemplate(), QtAws::KMS::KmsClient::updateKeyDescription(), QtAws::DirectConnect::DirectConnectClient::updateLag(), QtAws::OpsWorks::OpsWorksClient::updateLayer(), QtAws::Lightsail::LightsailClient::updateLoadBalancerAttribute(), QtAws::Greengrass::GreengrassClient::updateLoggerDefinition(), QtAws::IAM::IamClient::updateLoginProfile(), QtAws::StorageGateway::StorageGatewayClient::updateMaintenanceStartTime(), QtAws::SSM::SsmClient::updateMaintenanceWindow(), QtAws::SSM::SsmClient::updateMaintenanceWindowTarget(), QtAws::SSM::SsmClient::updateMaintenanceWindowTask(), QtAws::SSM::SsmClient::updateManagedInstanceRole(), QtAws::GameLift::GameLiftClient::updateMatchmakingConfiguration(), QtAws::APIGateway::APIGatewayClient::updateMethod(), QtAws::APIGateway::APIGatewayClient::updateMethodResponse(), QtAws::MachineLearning::MachineLearningClient::updateMLModel(), QtAws::APIGateway::APIGatewayClient::updateModel(), QtAws::OpsWorks::OpsWorksClient::updateMyUserProfile(), QtAws::DeviceFarm::DeviceFarmClient::updateNetworkProfile(), QtAws::StorageGateway::StorageGatewayClient::updateNFSFileShare(), QtAws::SageMaker::SageMakerClient::updateNotebookInstance(), QtAws::SageMaker::SageMakerClient::updateNotebookInstanceLifecycleConfig(), QtAws::Budgets::BudgetsClient::updateNotification(), QtAws::MTurk::MTurkClient::updateNotificationSettings(), QtAws::DirectoryService::DirectoryServiceClient::updateNumberOfDomainControllers(), QtAws::CloudDirectory::CloudDirectoryClient::updateObjectAttributes(), QtAws::IAM::IamClient::updateOpenIDConnectProviderThumbprint(), QtAws::Organizations::OrganizationsClient::updateOrganizationalUnit(), QtAws::MediaPackage::MediaPackageClient::updateOriginEndpoint(), QtAws::DAX::DaxClient::updateParameterGroup(), QtAws::Glue::GlueClient::updatePartition(), QtAws::SSM::SsmClient::updatePatchBaseline(), QtAws::ElasticTranscoder::ElasticTranscoderClient::updatePipeline(), QtAws::CodePipeline::CodePipelineClient::updatePipeline(), QtAws::ElasticTranscoder::ElasticTranscoderClient::updatePipelineNotifications(), QtAws::ElasticTranscoder::ElasticTranscoderClient::updatePipelineStatus(), QtAws::Organizations::OrganizationsClient::updatePolicy(), QtAws::ServiceCatalog::ServiceCatalogClient::updatePortfolio(), QtAws::MediaConvert::MediaConvertClient::updatePreset(), QtAws::WorkMail::WorkMailClient::updatePrimaryEmailAddress(), QtAws::ServiceCatalog::ServiceCatalogClient::updateProduct(), QtAws::AlexaForBusiness::AlexaForBusinessClient::updateProfile(), QtAws::Mobile::MobileClient::updateProject(), QtAws::CodeBuild::CodeBuildClient::updateProject(), QtAws::CodeStar::CodeStarClient::updateProject(), QtAws::DeviceFarm::DeviceFarmClient::updateProject(), QtAws::ServiceCatalog::ServiceCatalogClient::updateProvisionedProduct(), QtAws::ServiceCatalog::ServiceCatalogClient::updateProvisioningArtifact(), QtAws::CodeCommit::CodeCommitClient::updatePullRequestDescription(), QtAws::CodeCommit::CodeCommitClient::updatePullRequestStatus(), QtAws::CodeCommit::CodeCommitClient::updatePullRequestTitle(), QtAws::MTurk::MTurkClient::updateQualificationType(), QtAws::MediaConvert::MediaConvertClient::updateQueue(), QtAws::DirectoryService::DirectoryServiceClient::updateRadius(), QtAws::WAF::WafClient::updateRateBasedRule(), QtAws::WAFRegional::WAFRegionalClient::updateRateBasedRule(), QtAws::OpsWorks::OpsWorksClient::updateRdsDbInstance(), QtAws::SES::SesClient::updateReceiptRule(), QtAws::CognitoSync::CognitoSyncClient::updateRecords(), QtAws::WAF::WafClient::updateRegexMatchSet(), QtAws::WAFRegional::WAFRegionalClient::updateRegexMatchSet(), QtAws::WAF::WafClient::updateRegexPatternSet(), QtAws::WAFRegional::WAFRegionalClient::updateRegexPatternSet(), QtAws::SMS::SmsClient::updateReplicationJob(), QtAws::CodeCommit::CodeCommitClient::updateRepositoryDescription(), QtAws::CodeCommit::CodeCommitClient::updateRepositoryName(), QtAws::APIGateway::APIGatewayClient::updateRequestValidator(), QtAws::AppSync::AppSyncClient::updateResolver(), QtAws::WorkMail::WorkMailClient::updateResource(), QtAws::APIGateway::APIGatewayClient::updateResource(), QtAws::Greengrass::GreengrassClient::updateResourceDefinition(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateResourceServer(), QtAws::APIGateway::APIGatewayClient::updateRestApi(), QtAws::IAM::IamClient::updateRole(), QtAws::IoT::IoTClient::updateRoleAlias(), QtAws::IAM::IamClient::updateRoleDescription(), QtAws::AlexaForBusiness::AlexaForBusinessClient::updateRoom(), QtAws::WAF::WafClient::updateRule(), QtAws::WAFRegional::WAFRegionalClient::updateRule(), QtAws::WAF::WafClient::updateRuleGroup(), QtAws::WAFRegional::WAFRegionalClient::updateRuleGroup(), QtAws::GameLift::GameLiftClient::updateRuntimeConfiguration(), QtAws::IAM::IamClient::updateSAMLProvider(), QtAws::CloudSearch::CloudSearchClient::updateScalingParameters(), QtAws::CloudDirectory::CloudDirectoryClient::updateSchema(), QtAws::EC2::Ec2Client::updateSecurityGroupRuleDescriptionsEgress(), QtAws::EC2::Ec2Client::updateSecurityGroupRuleDescriptionsIngress(), QtAws::Pinpoint::PinpointClient::updateSegment(), QtAws::OpsWorksCM::OpsWorksCMClient::updateServer(), QtAws::IAM::IamClient::updateServerCertificate(), QtAws::OpsWorksCM::OpsWorksCMClient::updateServerEngineAttributes(), QtAws::ServiceDiscovery::ServiceDiscoveryClient::updateService(), QtAws::ECS::EcsClient::updateService(), QtAws::CloudSearch::CloudSearchClient::updateServiceAccessPolicies(), QtAws::IAM::IamClient::updateServiceSpecificCredential(), QtAws::Kinesis::KinesisClient::updateShardCount(), QtAws::IAM::IamClient::updateSigningCertificate(), QtAws::WAF::WafClient::updateSizeConstraintSet(), QtAws::WAFRegional::WAFRegionalClient::updateSizeConstraintSet(), QtAws::AlexaForBusiness::AlexaForBusinessClient::updateSkillGroup(), QtAws::Pinpoint::PinpointClient::updateSmsChannel(), QtAws::StorageGateway::StorageGatewayClient::updateSnapshotSchedule(), QtAws::WAF::WafClient::updateSqlInjectionMatchSet(), QtAws::WAFRegional::WAFRegionalClient::updateSqlInjectionMatchSet(), QtAws::IAM::IamClient::updateSSHPublicKey(), QtAws::AppStream::AppStreamClient::updateStack(), QtAws::CloudFormation::CloudFormationClient::updateStack(), QtAws::OpsWorks::OpsWorksClient::updateStack(), QtAws::CloudFormation::CloudFormationClient::updateStackInstances(), QtAws::CloudFormation::CloudFormationClient::updateStackSet(), QtAws::APIGateway::APIGatewayClient::updateStage(), QtAws::SFN::SfnClient::updateStateMachine(), QtAws::KinesisVideo::KinesisVideoClient::updateStream(), QtAws::IoT::IoTClient::updateStream(), QtAws::CloudFront::CloudFrontClient::updateStreamingDistribution(), QtAws::DAX::DaxClient::updateSubnetGroup(), QtAws::Budgets::BudgetsClient::updateSubscriber(), QtAws::Greengrass::GreengrassClient::updateSubscriptionDefinition(), QtAws::DynamoDB::DynamoDBClient::updateTable(), QtAws::Glue::GlueClient::updateTable(), QtAws::ServiceCatalog::ServiceCatalogClient::updateTagOption(), QtAws::Route53Domains::Route53DomainsClient::updateTagsForDomain(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::updateTagsForResource(), QtAws::CodeStar::CodeStarClient::updateTeamMember(), QtAws::SES::SesClient::updateTemplate(), QtAws::CloudFormation::CloudFormationClient::updateTerminationProtection(), QtAws::IoT::IoTClient::updateThing(), QtAws::IoT::IoTClient::updateThingGroup(), QtAws::IoT::IoTClient::updateThingGroupsForThing(), QtAws::IoTDataPlane::IoTDataPlaneClient::updateThingShadow(), QtAws::GuardDuty::GuardDutyClient::updateThreatIntelSet(), QtAws::DynamoDB::DynamoDBClient::updateTimeToLive(), QtAws::Route53::Route53Client::updateTrafficPolicyComment(), QtAws::Route53::Route53Client::updateTrafficPolicyInstance(), QtAws::CloudTrail::CloudTrailClient::updateTrail(), QtAws::Glue::GlueClient::updateTrigger(), QtAws::AppSync::AppSyncClient::updateType(), QtAws::CloudDirectory::CloudDirectoryClient::updateTypedLinkFacet(), QtAws::APIGateway::APIGatewayClient::updateUsage(), QtAws::APIGateway::APIGatewayClient::updateUsagePlan(), QtAws::MQ::MqClient::updateUser(), QtAws::WorkDocs::WorkDocsClient::updateUser(), QtAws::IAM::IamClient::updateUser(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserAttributes(), QtAws::Glue::GlueClient::updateUserDefinedFunction(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserPool(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::updateUserPoolClient(), QtAws::CodeStar::CodeStarClient::updateUserProfile(), QtAws::OpsWorks::OpsWorksClient::updateUserProfile(), QtAws::OpsWorks::OpsWorksClient::updateVolume(), QtAws::APIGateway::APIGatewayClient::updateVpcLink(), QtAws::StorageGateway::StorageGatewayClient::updateVTLDeviceType(), QtAws::WAF::WafClient::updateWebACL(), QtAws::WAFRegional::WAFRegionalClient::updateWebACL(), QtAws::CodeBuild::CodeBuildClient::updateWebhook(), QtAws::WAF::WafClient::updateXssMatchSet(), QtAws::WAFRegional::WAFRegionalClient::updateXssMatchSet(), QtAws::CloudDirectory::CloudDirectoryClient::upgradeAppliedSchema(), QtAws::CloudDirectory::CloudDirectoryClient::upgradePublishedSchema(), QtAws::Glacier::GlacierClient::uploadArchive(), QtAws::CloudSearchDomain::CloudSearchDomainClient::uploadDocuments(), QtAws::ECR::EcrClient::uploadLayerPart(), QtAws::Glacier::GlacierClient::uploadMultipartPart(), QtAws::S3::S3Client::uploadPart(), QtAws::S3::S3Client::uploadPartCopy(), QtAws::IAM::IamClient::uploadServerCertificate(), QtAws::IAM::IamClient::uploadSigningCertificate(), QtAws::IAM::IamClient::uploadSSHPublicKey(), QtAws::ElasticBeanstalk::ElasticBeanstalkClient::validateConfigurationSettings(), QtAws::GameLift::GameLiftClient::validateMatchmakingRuleSet(), QtAws::DataPipeline::DataPipelineClient::validatePipelineDefinition(), QtAws::CloudFormation::CloudFormationClient::validateTemplate(), QtAws::SES::SesClient::verifyDomainDkim(), QtAws::SES::SesClient::verifyDomainIdentity(), QtAws::SES::SesClient::verifyEmailAddress(), QtAws::SES::SesClient::verifyEmailIdentity(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::verifySoftwareToken(), QtAws::DirectoryService::DirectoryServiceClient::verifyTrust(), QtAws::CognitoIdentityProvider::CognitoIdentityProviderClient::verifyUserAttribute(), and QtAws::Route53Domains::Route53DomainsClient::viewBilling().
 {
     Q_D(AwsAbstractClient);
     Q_ASSERT(d->credentials);
     Q_ASSERT(d->networkAccessManager);
     Q_ASSERT(d->signature);
     Q_ASSERT(request.isValid());
     if (!d->credentials) {
         qWarning() << "credentials not set";
         return NULL;
     } else if (!d->networkAccessManager) {
         qWarning() << "network access manager not set";
         return NULL;
     } else if (!d->signature) {
         qWarning() << "signature not set";
         return NULL;
     } else if (!request.isValid()) {
         qWarning() << serviceName() << "request not valid";
         return NULL;
     }
     return request.send(*d->networkAccessManager, endpoint(),
                         *d->signature, *d->credentials);
 }
serviceFullName()
QString AwsAbstractClient::serviceFullName () const
Get the full name of the Amazon service this client accesses.
Returns
An Amazon full service name, such as "Amazon Simple Queue Service".
Definition at line 206 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     Q_ASSERT(!d->serviceFullName.isEmpty());
     return d->serviceFullName;
 }
serviceName()
QString AwsAbstractClient::serviceName () const
Get the name of the Amazon service this client accesses.
This is name is suitable for generating V4 signatures.
Returns
An Amazon service name, such as "sqs" or "sns".
Definition at line 220 of file awsabstractclient.cpp.
Referenced by endpoint(), and send().
 {
     Q_D(const AwsAbstractClient);
     Q_ASSERT(!d->serviceName.isEmpty());
     return d->serviceName;
 }
setCredentials()
void AwsAbstractClient::setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
This object will not take ownership of the supplied credentials pointer. It is the caller's responsibility to ensure that the pointer remains valid for the life of this object, or until setCredentials is used to set a new pointer.
Parameters
credentials Credentials to use for signing requests.
See also
sign
Definition at line 239 of file awsabstractclient.cpp.
References credentials().
 {
     Q_D(AwsAbstractClient);
     d->credentials = credentials;
 }
setEndpoint()
void AwsAbstractClient::setEndpoint (const QUrl & endpoint)
Set the AWS endpoint to use with this client.
Typically, it is simpler for the user to set this client's region instead (via setRegion), and allow this object to then determine the endpoint based on the serviceName and region. However, this method may be used to set an explicit endpoint URL if desired.
Parameters
endpoint Endpoint URL to use for sending AWS requests.
See also
region
send
setRegion
Definition at line 259 of file awsabstractclient.cpp.
References endpoint().
 {
     Q_D(AwsAbstractClient);
     d->endpoint = endpoint;
 }
setNetworkAccessManager()
void AwsAbstractClient::setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
This object will not take ownership of the supplied manager pointer. It is the caller's responsibility to ensure that the pointer remains valid for the life of this object, or until setNetworkAccessManager is used to set a new pointer.
Parameters
manager Network access manager for this AWS service object to use.
Definition at line 275 of file awsabstractclient.cpp.
 {
     Q_D(AwsAbstractClient);
     // If \a manager is already our network access manager, drop out early.
     if (d->networkAccessManager == manager) {
         return;
     }
     // If the old network access manager was our parent, disown our parent.
     if ((d->networkAccessManager != NULL) && (parent() == d->networkAccessManager)) {
         setParent(NULL);
     }
     // Set the network access manager.
     d->networkAccessManager = manager;
 }
setRegion()
void AwsAbstractClient::setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
If an endpoint is not explicitly set (eg via setEndpoint), then the supplied value may be used (in conjuction with serviceName) to determine the endpoint URL when sending requests to the AWS service.
Parameters
region Amazon region for this client to use.
See also
send
setEndpoint
Definition at line 305 of file awsabstractclient.cpp.
References region().
 {
     Q_D(AwsAbstractClient);
     d->region = region;
 }
signature()
AwsAbstractSignature * AwsAbstractClient::signature () const protected virtual
Get the signature object to be used for signing requests.
Returns
An AWS signature object.
Definition at line 327 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     return d->signature;
 }
The documentation for this class was generated from the following files:
core/awsabstractclient.h
core/awsabstractclient.cpp