AWS SDK for Qt: QtAws::Polly::PollyClient Class Reference
QtAws::Polly::PollyClient Class Reference
Client for Amazon Polly.
Public Slots
DeleteLexiconResponse * deleteLexicon (const DeleteLexiconRequest &request)
DescribeVoicesResponse * describeVoices (const DescribeVoicesRequest &request)
GetLexiconResponse * getLexicon (const GetLexiconRequest &request)
ListLexiconsResponse * listLexicons (const ListLexiconsRequest &request)
PutLexiconResponse * putLexicon (const PutLexiconRequest &request)
SynthesizeSpeechResponse * synthesizeSpeech (const SynthesizeSpeechRequest &request)
Public Member Functions
PollyClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PollyClient object.
PollyClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PollyClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Polly.
Amazon Polly is a web service that makes it easy to synthesize speech from
text>
The Amazon Polly service provides API operations for synthesizing high-quality speech from plain text and Speech Synthesis Markup Language (SSML), along with managing pronunciations lexicons that enable you to get the best results for your application
Definition at line 44 of file pollyclient.h.
Constructor & Destructor Documentation
PollyClient() [1/2]
QtAws::Polly::PollyClient::PollyClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PollyClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 65 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new PollyClientPrivate(this), parent)
 {
     Q_D(PollyClient);
     d->apiVersion = QStringLiteral("2016-06-10");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("polly");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Polly");
     d->serviceName = QStringLiteral("polly");
 }
PollyClient() [2/2]
QtAws::Polly::PollyClient::PollyClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PollyClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 98 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new PollyClientPrivate(this), parent)
 {
     Q_D(PollyClient);
     d->apiVersion = QStringLiteral("2016-06-10");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("polly");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Polly");
     d->serviceName = QStringLiteral("polly");
 }
Member Function Documentation
deleteLexicon
DeleteLexiconResponse * QtAws::Polly::PollyClient::deleteLexicon (const DeleteLexiconRequest & request) slot
Deletes the specified pronunciation lexicon stored in an AWS Region. A lexicon which has been deleted is not available for speech synthesis, nor is it possible to retrieve it using either the GetLexicon or ListLexicon
APIs>
For more information, see Managing request Request to send to Amazon Polly. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 130 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLexiconResponse *>(send(request));
 }
describeVoices
DescribeVoicesResponse * QtAws::Polly::PollyClient::describeVoices (const DescribeVoicesRequest & request) slot
Returns the list of voices that are available for use when requesting speech synthesis. Each voice speaks a specified language, is either male or female, and is identified by an ID, which is the ASCII version of the voice name.
</p
When synthesizing speech (SynthesizeSpeech), you provide the voice ID for the voice you want from the list of voices returned by
DescribeVoices>
For example, you want your news reader application to read news in a specific language, but giving a user the option to choose the voice. Using the DescribeVoices operation you can provide the user with a list of available voices to select
from>
You can optionally specify a language code to filter the available voices. For example, if you specify en-US, the operation returns a list of all available US English voices.
</p
This operation requires permissions to perform the polly:DescribeVoices
Parameters
request Request to send to Amazon Polly.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 165 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeVoicesResponse *>(send(request));
 }
getLexicon
GetLexiconResponse * QtAws::Polly::PollyClient::getLexicon (const GetLexiconRequest & request) slot
Returns the content of the specified pronunciation lexicon stored in an AWS Region. For more information, see Managing request Request to send to Amazon Polly. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 180 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetLexiconResponse *>(send(request));
 }
listLexicons
ListLexiconsResponse * QtAws::Polly::PollyClient::listLexicons (const ListLexiconsRequest & request) slot
Returns a list of pronunciation lexicons stored in an AWS Region. For more information, see Managing request Request to send to Amazon Polly. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 195 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListLexiconsResponse *>(send(request));
 }
putLexicon
PutLexiconResponse * QtAws::Polly::PollyClient::putLexicon (const PutLexiconRequest & request) slot
Stores a pronunciation lexicon in an AWS Region. If a lexicon with the same name already exists in the region, it is overwritten by the new lexicon. Lexicon operations have eventual consistency, therefore, it might take some time before the lexicon is available to the SynthesizeSpeech
operation>
For more information, see Managing request Request to send to Amazon Polly. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 215 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutLexiconResponse *>(send(request));
 }
synthesizeSpeech
SynthesizeSpeechResponse * QtAws::Polly::PollyClient::synthesizeSpeech (const SynthesizeSpeechRequest & request) slot
Synthesizes UTF-8 input, plain text or SSML, to a stream of bytes. SSML input must be valid, well-formed SSML. Some alphabets might not be available with all the voices (for example, Cyrillic might not be read at all by English voices) unless phoneme mapping is used. For more information, see How it request Request to send to Amazon Polly. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 232 of file pollyclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SynthesizeSpeechResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
polly/pollyclient.h
polly/pollyclient.cpp