AWS SDK for Qt: QtAws::SqsOld::SqsGetQueueUrlRequest Class Reference
QtAws::SqsOld::SqsGetQueueUrlRequest Class Reference
Implements SQS GetQueueUrl requests.
Public Member Functions
SqsGetQueueUrlRequest (const QString &queueName, const QString &queueOwnerAWSAccountId=QString())
Constructs a new SqsGetQueueUrlRequest.
SqsGetQueueUrlRequest (const SqsGetQueueUrlRequest &other)
Constructs a new SqsGetQueueUrlRequest object by copying another.
SqsGetQueueUrlRequest ()
Constructs a new SqsGetQueueUrlRequest object.
virtual bool isValid () const
QString queueName () const
Get the name of the queue whose URL must be fetched.
QString queueOwnerAWSAccountId () const
Get the AWS account ID of the account that created the queue.
void setQueueName (const QString &queueName)
Set the name of the queue whose URL must be fetched.
void setQueueOwnerAWSAccountId (const QString &queueOwnerAWSAccountId)
Set the AWS account ID of the account that created the queue.
Public Member Functions inherited from QtAws::SqsOld::SqsRequest
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Protected Member Functions
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const
Construct an SqsGetQueueUrlResponse object.
Protected Member Functions inherited from QtAws::SqsOld::SqsRequest
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Friends
class TestSqsGetQueueUrlRequest
Additional Inherited Members
Public Types inherited from QtAws::SqsOld::SqsRequest
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Static Public Member Functions inherited from QtAws::SqsOld::SqsRequest
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Detailed Description
Implements SQS GetQueueUrl requests.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html
Definition at line 30 of file sqsgetqueueurlrequest.h.
Constructor & Destructor Documentation
SqsGetQueueUrlRequest() [1/2]
QtAws::SqsOld::SqsGetQueueUrlRequest::SqsGetQueueUrlRequest (const QString & queueName, const QString & queueOwnerAWSAccountId = QString())
Constructs a new SqsGetQueueUrlRequest.
Parameters
queueName Name of the queue whose URL must be fetched.
queueOwnerAWSAccountId The AWS account ID of the account that created the queue.
See also
setQueueOwnerAWSAccountId
Definition at line 47 of file sqsgetqueueurlrequest.cpp.
References setQueueName(), and setQueueOwnerAWSAccountId().
     : SqsRequest(new SqsGetQueueUrlRequestPrivate(SqsRequest::GetQueueUrlAction, this))
 {
     setQueueName(queueName);
     setQueueOwnerAWSAccountId(queueOwnerAWSAccountId);
 }
SqsGetQueueUrlRequest() [2/2]
QtAws::SqsOld::SqsGetQueueUrlRequest::SqsGetQueueUrlRequest (const SqsGetQueueUrlRequest & other)
Constructs a new SqsGetQueueUrlRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 60 of file sqsgetqueueurlrequest.cpp.
     : SqsRequest(new SqsGetQueueUrlRequestPrivate(*other.d_func(), this))
 {
 }
Member Function Documentation
queueName()
QString QtAws::SqsOld::SqsGetQueueUrlRequest::queueName () const
Get the name of the queue whose URL must be fetched.
Returns
The name of the queue whose URL must be fetched.
Definition at line 85 of file sqsgetqueueurlrequest.cpp.
References QtAws::SqsOld::SqsRequest::parameter().
Referenced by SqsGetQueueUrlRequest().
 {
     return parameter(QUEUE_NAME).toString();
 }
queueOwnerAWSAccountId()
QString QtAws::SqsOld::SqsGetQueueUrlRequest::queueOwnerAWSAccountId () const
Get the AWS account ID of the account that created the queue.
Returns
The AWS account ID of the account that created the queue
See also
setQueueOwnerAWSAccountId
Definition at line 97 of file sqsgetqueueurlrequest.cpp.
References QtAws::SqsOld::SqsRequest::parameter().
 {
     return parameter(QUEUE_OWNER_AWS_ACCOUNT_ID).toString();
 }
response()
AwsAbstractResponse * QtAws::SqsOld::SqsGetQueueUrlRequest::response (QNetworkReply *const reply) const protected virtual
Construct an SqsGetQueueUrlResponse object.
Parameters
reply Network reply this response should observe.
Returns
An SqsGetQueueUrlResponse instance for reply.
See also
AwsAbstractClient::send
Definition at line 138 of file sqsgetqueueurlrequest.cpp.
 {
     return new SqsGetQueueUrlResponse(*this, reply);
 }
setQueueName()
void QtAws::SqsOld::SqsGetQueueUrlRequest::setQueueName (const QString & queueName)
Set the name of the queue whose URL must be fetched.
Parameters
queueName Name of the queue whose URL must be fetched.
Definition at line 107 of file sqsgetqueueurlrequest.cpp.
References QtAws::SqsOld::SqsRequest::setParameter().
Referenced by SqsGetQueueUrlRequest().
 {
     setParameter(QUEUE_NAME, queueName);
 }
setQueueOwnerAWSAccountId()
void QtAws::SqsOld::SqsGetQueueUrlRequest::setQueueOwnerAWSAccountId (const QString & queueOwnerAWSAccountId)
Set the AWS account ID of the account that created the queue.
Use this method to access a queue that belongs another AWS account.
Parameters
queueOwnerAWSAccountId AWS account ID of the account that created the queue.
Definition at line 119 of file sqsgetqueueurlrequest.cpp.
References QtAws::SqsOld::SqsRequest::clearParameter(), and QtAws::SqsOld::SqsRequest::setParameter().
Referenced by SqsGetQueueUrlRequest().
 {
     if (queueOwnerAWSAccountId.isNull()) {
         clearParameter(QUEUE_OWNER_AWS_ACCOUNT_ID);
     } else {
         setParameter(QUEUE_OWNER_AWS_ACCOUNT_ID, queueOwnerAWSAccountId);
     }
 }
The documentation for this class was generated from the following files:
sqs-old/sqsgetqueueurlrequest.h
sqs-old/sqsgetqueueurlrequest.cpp