AWS SDK for Qt: QtAws::Redshift::RedshiftRequest Class Reference
QtAws::Redshift::RedshiftRequest Class Reference
Interface class for providing Redshift requests.
Inherits QtAws::Core::AwsAbstractRequest.
Inherited by QtAws::Redshift::AuthorizeClusterSecurityGroupIngressRequest, QtAws::Redshift::AuthorizeSnapshotAccessRequest, QtAws::Redshift::CopyClusterSnapshotRequest, QtAws::Redshift::CreateClusterParameterGroupRequest, QtAws::Redshift::CreateClusterRequest, QtAws::Redshift::CreateClusterSecurityGroupRequest, QtAws::Redshift::CreateClusterSnapshotRequest, QtAws::Redshift::CreateClusterSubnetGroupRequest, QtAws::Redshift::CreateEventSubscriptionRequest, QtAws::Redshift::CreateHsmClientCertificateRequest, QtAws::Redshift::CreateHsmConfigurationRequest, QtAws::Redshift::CreateSnapshotCopyGrantRequest, QtAws::Redshift::CreateTagsRequest, QtAws::Redshift::DeleteClusterParameterGroupRequest, QtAws::Redshift::DeleteClusterRequest, QtAws::Redshift::DeleteClusterSecurityGroupRequest, QtAws::Redshift::DeleteClusterSnapshotRequest, QtAws::Redshift::DeleteClusterSubnetGroupRequest, QtAws::Redshift::DeleteEventSubscriptionRequest, QtAws::Redshift::DeleteHsmClientCertificateRequest, QtAws::Redshift::DeleteHsmConfigurationRequest, QtAws::Redshift::DeleteSnapshotCopyGrantRequest, QtAws::Redshift::DeleteTagsRequest, QtAws::Redshift::DescribeClusterParameterGroupsRequest, QtAws::Redshift::DescribeClusterParametersRequest, QtAws::Redshift::DescribeClusterSecurityGroupsRequest, QtAws::Redshift::DescribeClusterSnapshotsRequest, QtAws::Redshift::DescribeClustersRequest, QtAws::Redshift::DescribeClusterSubnetGroupsRequest, QtAws::Redshift::DescribeClusterVersionsRequest, QtAws::Redshift::DescribeDefaultClusterParametersRequest, QtAws::Redshift::DescribeEventCategoriesRequest, QtAws::Redshift::DescribeEventsRequest, QtAws::Redshift::DescribeEventSubscriptionsRequest, QtAws::Redshift::DescribeHsmClientCertificatesRequest, QtAws::Redshift::DescribeHsmConfigurationsRequest, QtAws::Redshift::DescribeLoggingStatusRequest, QtAws::Redshift::DescribeOrderableClusterOptionsRequest, QtAws::Redshift::DescribeReservedNodeOfferingsRequest, QtAws::Redshift::DescribeReservedNodesRequest, QtAws::Redshift::DescribeResizeRequest, QtAws::Redshift::DescribeSnapshotCopyGrantsRequest, QtAws::Redshift::DescribeTableRestoreStatusRequest, QtAws::Redshift::DescribeTagsRequest, QtAws::Redshift::DisableLoggingRequest, QtAws::Redshift::DisableSnapshotCopyRequest, QtAws::Redshift::EnableLoggingRequest, QtAws::Redshift::EnableSnapshotCopyRequest, QtAws::Redshift::GetClusterCredentialsRequest, QtAws::Redshift::ModifyClusterIamRolesRequest, QtAws::Redshift::ModifyClusterParameterGroupRequest, QtAws::Redshift::ModifyClusterRequest, QtAws::Redshift::ModifyClusterSubnetGroupRequest, QtAws::Redshift::ModifyEventSubscriptionRequest, QtAws::Redshift::ModifySnapshotCopyRetentionPeriodRequest, QtAws::Redshift::PurchaseReservedNodeOfferingRequest, QtAws::Redshift::RebootClusterRequest, QtAws::Redshift::ResetClusterParameterGroupRequest, QtAws::Redshift::RestoreFromClusterSnapshotRequest, QtAws::Redshift::RestoreTableFromClusterSnapshotRequest, QtAws::Redshift::RevokeClusterSecurityGroupIngressRequest, QtAws::Redshift::RevokeSnapshotAccessRequest, and QtAws::Redshift::RotateEncryptionKeyRequest.
Public Types
enum Action {
AuthorizeClusterSecurityGroupIngressAction, AuthorizeSnapshotAccessAction, CopyClusterSnapshotAction, CreateClusterAction,
CreateClusterParameterGroupAction, CreateClusterSecurityGroupAction, CreateClusterSnapshotAction, CreateClusterSubnetGroupAction,
CreateEventSubscriptionAction, CreateHsmClientCertificateAction, CreateHsmConfigurationAction, CreateSnapshotCopyGrantAction,
CreateTagsAction, DeleteClusterAction, DeleteClusterParameterGroupAction, DeleteClusterSecurityGroupAction,
DeleteClusterSnapshotAction, DeleteClusterSubnetGroupAction, DeleteEventSubscriptionAction, DeleteHsmClientCertificateAction,
DeleteHsmConfigurationAction, DeleteSnapshotCopyGrantAction, DeleteTagsAction, DescribeClusterParameterGroupsAction,
DescribeClusterParametersAction, DescribeClusterSecurityGroupsAction, DescribeClusterSnapshotsAction, DescribeClusterSubnetGroupsAction,
DescribeClusterVersionsAction, DescribeClustersAction, DescribeDefaultClusterParametersAction, DescribeEventCategoriesAction,
DescribeEventSubscriptionsAction, DescribeEventsAction, DescribeHsmClientCertificatesAction, DescribeHsmConfigurationsAction,
DescribeLoggingStatusAction, DescribeOrderableClusterOptionsAction, DescribeReservedNodeOfferingsAction, DescribeReservedNodesAction,
DescribeResizeAction, DescribeSnapshotCopyGrantsAction, DescribeTableRestoreStatusAction, DescribeTagsAction,
DisableLoggingAction, DisableSnapshotCopyAction, EnableLoggingAction, EnableSnapshotCopyAction,
GetClusterCredentialsAction, ModifyClusterAction, ModifyClusterIamRolesAction, ModifyClusterParameterGroupAction,
ModifyClusterSubnetGroupAction, ModifyEventSubscriptionAction, ModifySnapshotCopyRetentionPeriodAction, PurchaseReservedNodeOfferingAction,
RebootClusterAction, ResetClusterParameterGroupAction, RestoreFromClusterSnapshotAction, RestoreTableFromClusterSnapshotAction,
RevokeClusterSecurityGroupIngressAction, RevokeSnapshotAccessAction, RotateEncryptionKeyAction
}
Actions supported by Redshift.
Public Member Functions
RedshiftRequest (const Action action)
Constructs a new RedshiftRequest object.
RedshiftRequest (const RedshiftRequest &other)
Constructs a new RedshiftRequest object by copying another.
RedshiftRequest & operator= (const RedshiftRequest &other)
Assignment operator.
Action action () const
Get the Redshift action to be performed by this request.
QString actionString () const
Get the name of the Redshift action to be performed by this request.
QString apiVersion () const
Get the Redshift API version implemented by this request.
void setAction (const Action action)
Set the Redshift action to be performed by this request.
void setApiVersion (const QString &version)
Set the Redshift API version to include in this request.
virtual bool operator== (const RedshiftRequest &other) const
Equality operator.
Public Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
RedshiftRequest (RedshiftRequestPrivate *const d)
Constructs a new RedshiftRequest object.
int clearParameter (const QString &name)
Check if queueName is a valid Redshift queue name.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this Redshift request.
const QVariantMap & parameters () const
Get all parameters included with this Redshift request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this Redshift request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this Redshift request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this Redshift request.
Protected Member Functions inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Additional Inherited Members
Protected Attributes inherited from QtAws::Core::AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing Redshift requests.
Definition at line 35 of file redshiftrequest.h.
Constructor & Destructor Documentation
RedshiftRequest() [1/3]
QtAws::Redshift::RedshiftRequest::RedshiftRequest (const Action action)
Constructs a new RedshiftRequest object.
Parameters
action The Redshift action to request.
Definition at line 38 of file redshiftrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new RedshiftRequestPrivate(action, this))
 {
 }
RedshiftRequest() [2/3]
QtAws::Redshift::RedshiftRequest::RedshiftRequest (const RedshiftRequest & other)
Constructs a new RedshiftRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 49 of file redshiftrequest.cpp.
     : QtAws::Core::AwsAbstractRequest(new RedshiftRequestPrivate(*other.d_func(), this))
 {
 }
RedshiftRequest() [3/3]
QtAws::Redshift::RedshiftRequest::RedshiftRequest (RedshiftRequestPrivate *const d) protected
Constructs a new RedshiftRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from RedshiftRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 83 of file redshiftrequest.cpp.
                                                                  : QtAws::Core::AwsAbstractRequest(d)
 {
 }
Member Function Documentation
action()
RedshiftRequest::Action QtAws::Redshift::RedshiftRequest::action () const
Get the Redshift action to be performed by this request.
Returns
The Redshift action to be performed by this request.
Definition at line 93 of file redshiftrequest.cpp.
Referenced by actionString(), operator=(), operator==(), and setAction().
 {
     Q_D(const RedshiftRequest);
     return d->action;
 }
actionString()
QString QtAws::Redshift::RedshiftRequest::actionString () const
Get the name of the Redshift action to be performed by this request.
Returns
The name of the Redshift action to be performed by this request.
Definition at line 104 of file redshiftrequest.cpp.
References action(), and QtAws::Redshift::RedshiftRequestPrivate::toString().
 {
     return RedshiftRequestPrivate::toString(action());
 }
apiVersion()
QString QtAws::Redshift::RedshiftRequest::apiVersion () const
Get the Redshift API version implemented by this request.
Returns
The Redshift API version implmented by this request.
Definition at line 114 of file redshiftrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const RedshiftRequest);
     return d->apiVersion;
 }
clearParameter()
int QtAws::Redshift::RedshiftRequest::clearParameter (const QString & name) protected
Check if queueName is a valid Redshift queue name.
From Redshift FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid Redshift queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/ Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 188 of file redshiftrequest.cpp.
 {
     Q_D(RedshiftRequest);
     return d->parameters.remove(name);
 }
operator=()
RedshiftRequest & QtAws::Redshift::RedshiftRequest::operator= (const RedshiftRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 64 of file redshiftrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(RedshiftRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
operator==()
bool QtAws::Redshift::RedshiftRequest::operator== (const RedshiftRequest & other) const virtual
Equality operator.
Note, most derived *Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 154 of file redshiftrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (QtAws::Core::AwsAbstractRequest::operator ==(other)));
 }
parameter()
QVariant QtAws::Redshift::RedshiftRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this Redshift request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 211 of file redshiftrequest.cpp.
 {
     Q_D(const RedshiftRequest);
     return d->parameters.value(name, defaultValue);
 }
parameters()
const QVariantMap & QtAws::Redshift::RedshiftRequest::parameters () const protected
Get all parameters included with this Redshift request.
Returns
A map of parameters included with this request.
Definition at line 222 of file redshiftrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const RedshiftRequest);
     return d->parameters;
 }
setAction()
void QtAws::Redshift::RedshiftRequest::setAction (const Action action)
Set the Redshift action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 125 of file redshiftrequest.cpp.
References action().
 {
     Q_D(RedshiftRequest);
     d->action = action;
 }
setApiVersion()
void QtAws::Redshift::RedshiftRequest::setApiVersion (const QString & version)
Set the Redshift API version to include in this request.
Parameters
version The Redshift API version to include in this request.
Definition at line 136 of file redshiftrequest.cpp.
 {
     Q_D(RedshiftRequest);
     d->apiVersion = version;
 }
setParameter()
void QtAws::Redshift::RedshiftRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this Redshift request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 234 of file redshiftrequest.cpp.
 {
     Q_D(RedshiftRequest);
     d->parameters.insert(name, value);
 }
setParameters()
void QtAws::Redshift::RedshiftRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this Redshift request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 247 of file redshiftrequest.cpp.
References parameters().
 {
     Q_D(RedshiftRequest);
     d->parameters = parameters;
 }
unsignedRequest()
QNetworkRequest QtAws::Redshift::RedshiftRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this Redshift request.
This Redshift implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this Redshift request using the given endpoint.
Todo:
url.setQuery(d->urlQuery());
Implements QtAws::Core::AwsAbstractRequest.
Definition at line 264 of file redshiftrequest.cpp.
 {
     Q_D(const RedshiftRequest);
     QUrl url(endpoint);
     /// @todo url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
redshift/redshiftrequest.h
redshift/redshiftrequest.cpp