AWS SDK for Qt: QtAws::CloudTrail::CloudTrailClient Class Reference
QtAws::CloudTrail::CloudTrailClient Class Reference
Client for AWS CloudTrail.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateTrailResponse * createTrail (const CreateTrailRequest &request)
DeleteTrailResponse * deleteTrail (const DeleteTrailRequest &request)
DescribeTrailsResponse * describeTrails (const DescribeTrailsRequest &request)
GetEventSelectorsResponse * getEventSelectors (const GetEventSelectorsRequest &request)
GetTrailStatusResponse * getTrailStatus (const GetTrailStatusRequest &request)
ListPublicKeysResponse * listPublicKeys (const ListPublicKeysRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
LookupEventsResponse * lookupEvents (const LookupEventsRequest &request)
PutEventSelectorsResponse * putEventSelectors (const PutEventSelectorsRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
StartLoggingResponse * startLogging (const StartLoggingRequest &request)
StopLoggingResponse * stopLogging (const StopLoggingRequest &request)
UpdateTrailResponse * updateTrail (const UpdateTrailRequest &request)
Public Member Functions
CloudTrailClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudTrailClient object.
CloudTrailClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudTrailClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CloudTrail.
<fullname>AWS CloudTrail</fullname>
This is the CloudTrail API Reference. It provides descriptions of actions, data types, common parameters, and common errors for
CloudTrail>
CloudTrail is a web service that records AWS API calls for your AWS account and delivers log files to an Amazon S3 bucket. The recorded information includes the identity of the user, the start time of the AWS API call, the source IP address, the request parameters, and the response elements returned by the
service> <note>
As an alternative to the API, you can use one of the AWS SDKs, which consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .NET, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to AWSCloudTrail. For example, the SDKs take care of cryptographically signing requests, managing errors, and retrying requests automatically. For information about the AWS SDKs, including how to download and install them, see the Tools for Amazon Web Services page> </note>
See the AWS CloudTrail User Guide for information about the data that is included with each AWS API call listed in the log
Definition at line 60 of file cloudtrailclient.h.
Constructor & Destructor Documentation
CloudTrailClient() [1/2]
QtAws::CloudTrail::CloudTrailClient::CloudTrailClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudTrailClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 97 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudTrailClientPrivate(this), parent)
 {
     Q_D(CloudTrailClient);
     d->apiVersion = QStringLiteral("2013-11-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudtrail");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS CloudTrail");
     d->serviceName = QStringLiteral("cloudtrail");
 }
CloudTrailClient() [2/2]
QtAws::CloudTrail::CloudTrailClient::CloudTrailClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudTrailClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 130 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudTrailClientPrivate(this), parent)
 {
     Q_D(CloudTrailClient);
     d->apiVersion = QStringLiteral("2013-11-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudtrail");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS CloudTrail");
     d->serviceName = QStringLiteral("cloudtrail");
 }
Member Function Documentation
addTags
AddTagsResponse * QtAws::CloudTrail::CloudTrailClient::addTags (const AddTagsRequest & request) slot
Adds one or more tags to a trail, up to a limit of 50. Tags must be unique per trail. Overwrites an existing tag's value when a new value is specified for an existing tag key. If you specify a key without a value, the tag will be created with the specified key and a value of null. You can tag a trail that applies to all regions only from the region in which the trail was created (that is, from its home
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 159 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
createTrail
CreateTrailResponse * QtAws::CloudTrail::CloudTrailClient::createTrail (const CreateTrailRequest & request) slot
Creates a trail that specifies the settings for delivery of log data to an Amazon S3 bucket. A maximum of five trails can exist in a region, irrespective of the region in which they were
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 174 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateTrailResponse *>(send(request));
 }
deleteTrail
DeleteTrailResponse * QtAws::CloudTrail::CloudTrailClient::deleteTrail (const DeleteTrailRequest & request) slot
Deletes a trail. This operation must be called from the region in which the trail was created. DeleteTrail cannot be called on the shadow trails (replicated trails in other regions) of a trail that is enabled in all
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 189 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTrailResponse *>(send(request));
 }
describeTrails
DescribeTrailsResponse * QtAws::CloudTrail::CloudTrailClient::describeTrails (const DescribeTrailsRequest & request) slot
Retrieves settings for the trail associated with the current region for your
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 203 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTrailsResponse *>(send(request));
 }
getEventSelectors
GetEventSelectorsResponse * QtAws::CloudTrail::CloudTrailClient::getEventSelectors (const GetEventSelectorsRequest & request) slot
Describes the settings for the event selectors that you configured for your trail. The information returned for your event selectors includes the
following>
The S3 objects that you are logging for data
events>
If your event selector includes management
events>
If your event selector includes read-only events, write-only events, or all.
</p
For more information, see Logging Data and Management Events for Trails in the AWS CloudTrail User
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 236 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetEventSelectorsResponse *>(send(request));
 }
getTrailStatus
GetTrailStatusResponse * QtAws::CloudTrail::CloudTrailClient::getTrailStatus (const GetTrailStatusRequest & request) slot
Returns a JSON-formatted list of information about the specified trail. Fields include information on delivery errors, Amazon SNS and Amazon S3 errors, and start and stop logging times for each trail. This operation returns trail status from a single region. To return trail status from all regions, you must call the operation on each
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 252 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetTrailStatusResponse *>(send(request));
 }
listPublicKeys
ListPublicKeysResponse * QtAws::CloudTrail::CloudTrailClient::listPublicKeys (const ListPublicKeysRequest & request) slot
Returns all public keys whose private keys were used to sign the digest files within the specified time range. The public key is needed to validate digest files that were signed with its corresponding private
key> <note>
CloudTrail uses different private/public key pairs per region. Each digest file is signed with a private key unique to its region. Therefore, when you validate a digest file from a particular region, you must look in the same region for its corresponding public
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 273 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPublicKeysResponse *>(send(request));
 }
listTags
ListTagsResponse * QtAws::CloudTrail::CloudTrailClient::listTags (const ListTagsRequest & request) slot
Lists the tags for the trail in the current
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 287 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsResponse *>(send(request));
 }
lookupEvents
LookupEventsResponse * QtAws::CloudTrail::CloudTrailClient::lookupEvents (const LookupEventsRequest & request) slot
Looks up API activity events captured by CloudTrail that create, update, or delete resources in your account. Events for a region can be looked up for the times in which you had CloudTrail turned on in that region during the last seven days. Lookup supports the following
attributes>
Event
I>
Event
nam>
Event
sourc>
Resource
nam>
Resource
typ>
User
nam>
All attributes are optional. The default number of results returned is 10, with a maximum of 50 possible. The response includes a token that you can use to get the next page of
results>
The rate of lookup requests is limited to one per second per account. If this limit is exceeded, a throttling error
occurs>
Events that occurred during the selected time range will not be available for lookup if CloudTrail logging was not enabled when the events
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 341 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<LookupEventsResponse *>(send(request));
 }
putEventSelectors
PutEventSelectorsResponse * QtAws::CloudTrail::CloudTrailClient::putEventSelectors (const PutEventSelectorsRequest & request) slot
Configures an event selector for your trail. Use event selectors to specify whether you want your trail to log management and/or data events. When an event occurs in your account, CloudTrail evaluates the event selectors in all trails. For each trail, if the event matches any event selector, the trail processes and logs the event. If the event doesn't match any event selector, the trail doesn't log the event.
You create an event selector for a trail and specify that you want write-only
events>
The EC2 GetConsoleOutput and RunInstances API operations occur in your
account>
CloudTrail evaluates whether the events match your event
selectors>
The RunInstances is a write-only event and it matches your event selector. The trail logs the
event>
The GetConsoleOutput is a read-only event but it doesn't match your event selector. The trail doesn't log the event.
</p
The PutEventSelectors operation must be called from the region in which the trail was created; otherwise, an InvalidHomeRegionException is
thrown>
You can configure up to five event selectors for each trail. For more information, see Logging Data and Management Events for Trails in the AWS CloudTrail User
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 392 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutEventSelectorsResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::CloudTrail::CloudTrailClient::removeTags (const RemoveTagsRequest & request) slot
Removes the specified tags from a
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 406 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
startLogging
StartLoggingResponse * QtAws::CloudTrail::CloudTrailClient::startLogging (const StartLoggingRequest & request) slot
Starts the recording of AWS API calls and log file delivery for a trail. For a trail that is enabled in all regions, this operation must be called from the region in which the trail was created. This operation cannot be called on the shadow trails (replicated trails in other regions) of a trail that is enabled in all
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 422 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartLoggingResponse *>(send(request));
 }
stopLogging
StopLoggingResponse * QtAws::CloudTrail::CloudTrailClient::stopLogging (const StopLoggingRequest & request) slot
Suspends the recording of AWS API calls and log file delivery for the specified trail. Under most circumstances, there is no need to use this action. You can update a trail without stopping it first. This action is the only way to stop recording. For a trail enabled in all regions, this operation must be called from the region in which the trail was created, or an InvalidHomeRegionException will occur. This operation cannot be called on the shadow trails (replicated trails in other regions) of a trail enabled in all
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 440 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StopLoggingResponse *>(send(request));
 }
updateTrail
UpdateTrailResponse * QtAws::CloudTrail::CloudTrailClient::updateTrail (const UpdateTrailRequest & request) slot
Updates the settings that specify delivery of log files. Changes to a trail do not require stopping the CloudTrail service. Use this action to designate an existing bucket for log delivery. If the existing bucket has previously been a target for CloudTrail log files, an IAM policy exists for the bucket. UpdateTrail must be called from the region in which the trail was created; otherwise, an InvalidHomeRegionException is
Parameters
request Request to send to AWS CloudTrail.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 457 of file cloudtrailclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateTrailResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudtrail/cloudtrailclient.h
cloudtrail/cloudtrailclient.cpp