AWS SDK for Qt: QtAws::MediaStoreData::MediaStoreDataClient Class Reference
QtAws::MediaStoreData::MediaStoreDataClient Class Reference
Client for AWS Elemental MediaStore Data Plane.
Public Slots
DeleteObjectResponse * deleteObject (const DeleteObjectRequest &request)
DescribeObjectResponse * describeObject (const DescribeObjectRequest &request)
GetObjectResponse * getObject (const GetObjectRequest &request)
ListItemsResponse * listItems (const ListItemsRequest &request)
PutObjectResponse * putObject (const PutObjectRequest &request)
Public Member Functions
MediaStoreDataClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaStoreDataClient object.
MediaStoreDataClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaStoreDataClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elemental MediaStore Data Plane.
An AWS Elemental MediaStore asset is an object, similar to an object in the Amazon S3 service. Objects are the fundamental entities that are stored in AWS Elemental
Definition at line 42 of file mediastoredataclient.h.
Constructor & Destructor Documentation
MediaStoreDataClient() [1/2]
QtAws::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaStoreDataClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 58 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MediaStoreDataClientPrivate(this), parent)
 {
     Q_D(MediaStoreDataClient);
     d->apiVersion = QStringLiteral("2017-09-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("data.mediastore");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaStore Data Plane");
     d->serviceName = QStringLiteral("mediastore");
 }
MediaStoreDataClient() [2/2]
QtAws::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaStoreDataClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 91 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MediaStoreDataClientPrivate(this), parent)
 {
     Q_D(MediaStoreDataClient);
     d->apiVersion = QStringLiteral("2017-09-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("data.mediastore");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Elemental MediaStore Data Plane");
     d->serviceName = QStringLiteral("mediastore");
 }
Member Function Documentation
deleteObject
DeleteObjectResponse * QtAws::MediaStoreData::MediaStoreDataClient::deleteObject (const DeleteObjectRequest & request) slot
Deletes an object at the specified
Parameters
request Request to send to AWS Elemental MediaStore Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 117 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteObjectResponse *>(send(request));
 }
describeObject
DescribeObjectResponse * QtAws::MediaStoreData::MediaStoreDataClient::describeObject (const DescribeObjectRequest & request) slot
Gets the headers for an object at the specified
Parameters
request Request to send to AWS Elemental MediaStore Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 131 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeObjectResponse *>(send(request));
 }
getObject
GetObjectResponse * QtAws::MediaStoreData::MediaStoreDataClient::getObject (const GetObjectRequest & request) slot
Downloads the object at the specified
Parameters
request Request to send to AWS Elemental MediaStore Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 145 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetObjectResponse *>(send(request));
 }
listItems
ListItemsResponse * QtAws::MediaStoreData::MediaStoreDataClient::listItems (const ListItemsRequest & request) slot
Provides a list of metadata entries about folders and objects in the specified
Parameters
request Request to send to AWS Elemental MediaStore Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 159 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListItemsResponse *>(send(request));
 }
putObject
PutObjectResponse * QtAws::MediaStoreData::MediaStoreDataClient::putObject (const PutObjectRequest & request) slot
Uploads an object to the specified path. Object sizes are limited to 10
Parameters
request Request to send to AWS Elemental MediaStore Data Plane.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file mediastoredataclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutObjectResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mediastore-data/mediastoredataclient.h
mediastore-data/mediastoredataclient.cpp