AWS SDK for Qt: QtAws::CloudHSM::CloudHSMClient Class Reference
QtAws::CloudHSM::CloudHSMClient Class Reference
Client for Amazon CloudHSM.
Public Slots
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
CreateHapgResponse * createHapg (const CreateHapgRequest &request)
CreateHsmResponse * createHsm (const CreateHsmRequest &request)
CreateLunaClientResponse * createLunaClient (const CreateLunaClientRequest &request)
DeleteHapgResponse * deleteHapg (const DeleteHapgRequest &request)
DeleteHsmResponse * deleteHsm (const DeleteHsmRequest &request)
DeleteLunaClientResponse * deleteLunaClient (const DeleteLunaClientRequest &request)
DescribeHapgResponse * describeHapg (const DescribeHapgRequest &request)
DescribeHsmResponse * describeHsm (const DescribeHsmRequest &request)
DescribeLunaClientResponse * describeLunaClient (const DescribeLunaClientRequest &request)
GetConfigResponse * getConfig (const GetConfigRequest &request)
ListAvailableZonesResponse * listAvailableZones (const ListAvailableZonesRequest &request)
ListHapgsResponse * listHapgs (const ListHapgsRequest &request)
ListHsmsResponse * listHsms (const ListHsmsRequest &request)
ListLunaClientsResponse * listLunaClients (const ListLunaClientsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyHapgResponse * modifyHapg (const ModifyHapgRequest &request)
ModifyHsmResponse * modifyHsm (const ModifyHsmRequest &request)
ModifyLunaClientResponse * modifyLunaClient (const ModifyLunaClientRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
Public Member Functions
CloudHSMClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMClient object.
CloudHSMClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudHSM.
<fullname>AWS CloudHSM Service</fullname>
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API
Definition at line 72 of file cloudhsmclient.h.
Constructor & Destructor Documentation
CloudHSMClient() [1/2]
QtAws::CloudHSM::CloudHSMClient::CloudHSMClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 98 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new CloudHSMClientPrivate(this), parent)
 {
     Q_D(CloudHSMClient);
     d->apiVersion = QStringLiteral("2014-05-30");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("cloudhsm");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon CloudHSM");
     d->serviceName = QStringLiteral("cloudhsm");
 }
CloudHSMClient() [2/2]
QtAws::CloudHSM::CloudHSMClient::CloudHSMClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 131 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new CloudHSMClientPrivate(this), parent)
 {
     Q_D(CloudHSMClient);
     d->apiVersion = QStringLiteral("2014-05-30");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("cloudhsm");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon CloudHSM");
     d->serviceName = QStringLiteral("cloudhsm");
 }
Member Function Documentation
addTagsToResource
AddTagsToResourceResponse * QtAws::CloudHSM::CloudHSMClient::addTagsToResource (const AddTagsToResourceRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Adds or overwrites one or more tags for the specified AWS CloudHSM
resource>
Each tag consists of a key and a value. Tag keys must be unique to each
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 174 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsToResourceResponse *>(send(request));
 }
createHapg
CreateHapgResponse * QtAws::CloudHSM::CloudHSMClient::createHapg (const CreateHapgRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Creates a high-availability partition group. A high-availability partition group is a group of partitions that spans multiple physical
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 202 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHapgResponse *>(send(request));
 }
createHsm
CreateHsmResponse * QtAws::CloudHSM::CloudHSMClient::createHsm (const CreateHsmRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Creates an uninitialized HSM
instance>
There is an upfront fee charged for each HSM instance that you create with the CreateHsm operation. If you accidentally provision an HSM and want to request a refund, delete the instance using the DeleteHsm operation, go to the AWS Support Center, create a new case, and select Account and Billing
Support>
It can take up to 20 minutes to create and provision an HSM. You can monitor the status of the HSM with the DescribeHsm operation. The HSM is ready to be initialized when the status changes to
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 241 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateHsmResponse *>(send(request));
 }
createLunaClient
CreateLunaClientResponse * QtAws::CloudHSM::CloudHSMClient::createLunaClient (const CreateLunaClientRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Creates an HSM
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 268 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLunaClientResponse *>(send(request));
 }
deleteHapg
DeleteHapgResponse * QtAws::CloudHSM::CloudHSMClient::deleteHapg (const DeleteHapgRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Deletes a high-availability partition
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 295 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHapgResponse *>(send(request));
 }
deleteHsm
DeleteHsmResponse * QtAws::CloudHSM::CloudHSMClient::deleteHsm (const DeleteHsmRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Deletes an HSM. After completion, this operation cannot be undone and your key material cannot be
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 322 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteHsmResponse *>(send(request));
 }
deleteLunaClient
DeleteLunaClientResponse * QtAws::CloudHSM::CloudHSMClient::deleteLunaClient (const DeleteLunaClientRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Deletes a
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 349 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLunaClientResponse *>(send(request));
 }
describeHapg
DescribeHapgResponse * QtAws::CloudHSM::CloudHSMClient::describeHapg (const DescribeHapgRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Retrieves information about a high-availability partition
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 376 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHapgResponse *>(send(request));
 }
describeHsm
DescribeHsmResponse * QtAws::CloudHSM::CloudHSMClient::describeHsm (const DescribeHsmRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Retrieves information about an HSM. You can identify the HSM by its ARN or its serial
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 403 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeHsmResponse *>(send(request));
 }
describeLunaClient
DescribeLunaClientResponse * QtAws::CloudHSM::CloudHSMClient::describeLunaClient (const DescribeLunaClientRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Retrieves information about an HSM
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 430 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLunaClientResponse *>(send(request));
 }
getConfig
GetConfigResponse * QtAws::CloudHSM::CloudHSMClient::getConfig (const GetConfigRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Gets the configuration files necessary to connect to all high availability partition groups the client is associated
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 457 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetConfigResponse *>(send(request));
 }
listAvailableZones
ListAvailableZonesResponse * QtAws::CloudHSM::CloudHSMClient::listAvailableZones (const ListAvailableZonesRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Lists the Availability Zones that have available AWS CloudHSM
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 484 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAvailableZonesResponse *>(send(request));
 }
listHapgs
ListHapgsResponse * QtAws::CloudHSM::CloudHSMClient::listHapgs (const ListHapgsRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Lists the high-availability partition groups for the
account>
This operation supports pagination with the use of the NextToken member. If more results are available, the NextToken member of the response contains a token that you pass in the next call to ListHapgs to retrieve the next set of
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 517 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHapgsResponse *>(send(request));
 }
listHsms
ListHsmsResponse * QtAws::CloudHSM::CloudHSMClient::listHsms (const ListHsmsRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Retrieves the identifiers of all of the HSMs provisioned for the current
customer>
This operation supports pagination with the use of the NextToken member. If more results are available, the NextToken member of the response contains a token that you pass in the next call to ListHsms to retrieve the next set of
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 550 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListHsmsResponse *>(send(request));
 }
listLunaClients
ListLunaClientsResponse * QtAws::CloudHSM::CloudHSMClient::listLunaClients (const ListLunaClientsRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Lists all of the
clients>
This operation supports pagination with the use of the NextToken member. If more results are available, the NextToken member of the response contains a token that you pass in the next call to ListLunaClients to retrieve the next set of
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 583 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListLunaClientsResponse *>(send(request));
 }
listTagsForResource
ListTagsForResourceResponse * QtAws::CloudHSM::CloudHSMClient::listTagsForResource (const ListTagsForResourceRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Returns a list of all tags for the specified AWS CloudHSM
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 610 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListTagsForResourceResponse *>(send(request));
 }
modifyHapg
ModifyHapgResponse * QtAws::CloudHSM::CloudHSMClient::modifyHapg (const ModifyHapgRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Modifies an existing high-availability partition
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 637 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyHapgResponse *>(send(request));
 }
modifyHsm
ModifyHsmResponse * QtAws::CloudHSM::CloudHSMClient::modifyHsm (const ModifyHsmRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Modifies an
HSM>
This operation can result in the HSM being offline for up to 15 minutes while the AWS CloudHSM service is reconfigured. If you are modifying a production HSM, you should ensure that your AWS CloudHSM service is configured for high availability, and consider executing this operation during a maintenance
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 670 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyHsmResponse *>(send(request));
 }
modifyLunaClient
ModifyLunaClientResponse * QtAws::CloudHSM::CloudHSMClient::modifyLunaClient (const ModifyLunaClientRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Modifies the certificate used by the
client>
This action can potentially start a workflow to install the new certificate on the client's
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 701 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ModifyLunaClientResponse *>(send(request));
 }
removeTagsFromResource
RemoveTagsFromResourceResponse * QtAws::CloudHSM::CloudHSMClient::removeTagsFromResource (const RemoveTagsFromResourceRequest & request) slot
This is documentation for AWS CloudHSM Classic. For more information, see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and the AWS CloudHSM Classic API Reference>
For information about the current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User Guide, and the AWS CloudHSM API Reference>
Removes one or more tags from the specified AWS CloudHSM
resource>
To remove a tag, specify only the tag key to remove (not the value). To overwrite the value for an existing tag, use
Parameters
request Request to send to Amazon CloudHSM.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 732 of file cloudhsmclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsFromResourceResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
cloudhsm/cloudhsmclient.h
cloudhsm/cloudhsmclient.cpp