AWS SDK for Qt: QtAws::S3::S3Client Class Reference
QtAws::S3::S3Client Class Reference
Client for Amazon Simple Storage Service (S3)
Public Slots
AbortMultipartUploadResponse * abortMultipartUpload (const AbortMultipartUploadRequest &request)
CompleteMultipartUploadResponse * completeMultipartUpload (const CompleteMultipartUploadRequest &request)
CopyObjectResponse * copyObject (const CopyObjectRequest &request)
CreateBucketResponse * createBucket (const CreateBucketRequest &request)
CreateMultipartUploadResponse * createMultipartUpload (const CreateMultipartUploadRequest &request)
DeleteBucketResponse * deleteBucket (const DeleteBucketRequest &request)
DeleteBucketAnalyticsConfigurationResponse * deleteBucketAnalyticsConfiguration (const DeleteBucketAnalyticsConfigurationRequest &request)
DeleteBucketCorsResponse * deleteBucketCors (const DeleteBucketCorsRequest &request)
DeleteBucketEncryptionResponse * deleteBucketEncryption (const DeleteBucketEncryptionRequest &request)
DeleteBucketInventoryConfigurationResponse * deleteBucketInventoryConfiguration (const DeleteBucketInventoryConfigurationRequest &request)
DeleteBucketLifecycleResponse * deleteBucketLifecycle (const DeleteBucketLifecycleRequest &request)
DeleteBucketMetricsConfigurationResponse * deleteBucketMetricsConfiguration (const DeleteBucketMetricsConfigurationRequest &request)
DeleteBucketPolicyResponse * deleteBucketPolicy (const DeleteBucketPolicyRequest &request)
DeleteBucketReplicationResponse * deleteBucketReplication (const DeleteBucketReplicationRequest &request)
DeleteBucketTaggingResponse * deleteBucketTagging (const DeleteBucketTaggingRequest &request)
DeleteBucketWebsiteResponse * deleteBucketWebsite (const DeleteBucketWebsiteRequest &request)
DeleteObjectResponse * deleteObject (const DeleteObjectRequest &request)
DeleteObjectTaggingResponse * deleteObjectTagging (const DeleteObjectTaggingRequest &request)
DeleteObjectsResponse * deleteObjects (const DeleteObjectsRequest &request)
GetBucketAccelerateConfigurationResponse * getBucketAccelerateConfiguration (const GetBucketAccelerateConfigurationRequest &request)
GetBucketAclResponse * getBucketAcl (const GetBucketAclRequest &request)
GetBucketAnalyticsConfigurationResponse * getBucketAnalyticsConfiguration (const GetBucketAnalyticsConfigurationRequest &request)
GetBucketCorsResponse * getBucketCors (const GetBucketCorsRequest &request)
GetBucketEncryptionResponse * getBucketEncryption (const GetBucketEncryptionRequest &request)
GetBucketInventoryConfigurationResponse * getBucketInventoryConfiguration (const GetBucketInventoryConfigurationRequest &request)
GetBucketLifecycleResponse * getBucketLifecycle (const GetBucketLifecycleRequest &request)
GetBucketLifecycleConfigurationResponse * getBucketLifecycleConfiguration (const GetBucketLifecycleConfigurationRequest &request)
GetBucketLocationResponse * getBucketLocation (const GetBucketLocationRequest &request)
GetBucketLoggingResponse * getBucketLogging (const GetBucketLoggingRequest &request)
GetBucketMetricsConfigurationResponse * getBucketMetricsConfiguration (const GetBucketMetricsConfigurationRequest &request)
GetBucketNotificationResponse * getBucketNotification (const GetBucketNotificationRequest &request)
GetBucketNotificationConfigurationResponse * getBucketNotificationConfiguration (const GetBucketNotificationConfigurationRequest &request)
GetBucketPolicyResponse * getBucketPolicy (const GetBucketPolicyRequest &request)
GetBucketReplicationResponse * getBucketReplication (const GetBucketReplicationRequest &request)
GetBucketRequestPaymentResponse * getBucketRequestPayment (const GetBucketRequestPaymentRequest &request)
GetBucketTaggingResponse * getBucketTagging (const GetBucketTaggingRequest &request)
GetBucketVersioningResponse * getBucketVersioning (const GetBucketVersioningRequest &request)
GetBucketWebsiteResponse * getBucketWebsite (const GetBucketWebsiteRequest &request)
GetObjectResponse * getObject (const GetObjectRequest &request)
GetObjectAclResponse * getObjectAcl (const GetObjectAclRequest &request)
GetObjectTaggingResponse * getObjectTagging (const GetObjectTaggingRequest &request)
GetObjectTorrentResponse * getObjectTorrent (const GetObjectTorrentRequest &request)
HeadBucketResponse * headBucket (const HeadBucketRequest &request)
HeadObjectResponse * headObject (const HeadObjectRequest &request)
ListBucketAnalyticsConfigurationsResponse * listBucketAnalyticsConfigurations (const ListBucketAnalyticsConfigurationsRequest &request)
ListBucketInventoryConfigurationsResponse * listBucketInventoryConfigurations (const ListBucketInventoryConfigurationsRequest &request)
ListBucketMetricsConfigurationsResponse * listBucketMetricsConfigurations (const ListBucketMetricsConfigurationsRequest &request)
ListBucketsResponse * listBuckets ()
ListMultipartUploadsResponse * listMultipartUploads (const ListMultipartUploadsRequest &request)
ListObjectVersionsResponse * listObjectVersions (const ListObjectVersionsRequest &request)
ListObjectsResponse * listObjects (const ListObjectsRequest &request)
ListObjectsV2Response * listObjectsV2 (const ListObjectsV2Request &request)
ListPartsResponse * listParts (const ListPartsRequest &request)
PutBucketAccelerateConfigurationResponse * putBucketAccelerateConfiguration (const PutBucketAccelerateConfigurationRequest &request)
PutBucketAclResponse * putBucketAcl (const PutBucketAclRequest &request)
PutBucketAnalyticsConfigurationResponse * putBucketAnalyticsConfiguration (const PutBucketAnalyticsConfigurationRequest &request)
PutBucketCorsResponse * putBucketCors (const PutBucketCorsRequest &request)
PutBucketEncryptionResponse * putBucketEncryption (const PutBucketEncryptionRequest &request)
PutBucketInventoryConfigurationResponse * putBucketInventoryConfiguration (const PutBucketInventoryConfigurationRequest &request)
PutBucketLifecycleResponse * putBucketLifecycle (const PutBucketLifecycleRequest &request)
PutBucketLifecycleConfigurationResponse * putBucketLifecycleConfiguration (const PutBucketLifecycleConfigurationRequest &request)
PutBucketLoggingResponse * putBucketLogging (const PutBucketLoggingRequest &request)
PutBucketMetricsConfigurationResponse * putBucketMetricsConfiguration (const PutBucketMetricsConfigurationRequest &request)
PutBucketNotificationResponse * putBucketNotification (const PutBucketNotificationRequest &request)
PutBucketNotificationConfigurationResponse * putBucketNotificationConfiguration (const PutBucketNotificationConfigurationRequest &request)
PutBucketPolicyResponse * putBucketPolicy (const PutBucketPolicyRequest &request)
PutBucketReplicationResponse * putBucketReplication (const PutBucketReplicationRequest &request)
PutBucketRequestPaymentResponse * putBucketRequestPayment (const PutBucketRequestPaymentRequest &request)
PutBucketTaggingResponse * putBucketTagging (const PutBucketTaggingRequest &request)
PutBucketVersioningResponse * putBucketVersioning (const PutBucketVersioningRequest &request)
PutBucketWebsiteResponse * putBucketWebsite (const PutBucketWebsiteRequest &request)
PutObjectResponse * putObject (const PutObjectRequest &request)
PutObjectAclResponse * putObjectAcl (const PutObjectAclRequest &request)
PutObjectTaggingResponse * putObjectTagging (const PutObjectTaggingRequest &request)
RestoreObjectResponse * restoreObject (const RestoreObjectRequest &request)
UploadPartResponse * uploadPart (const UploadPartRequest &request)
UploadPartCopyResponse * uploadPartCopy (const UploadPartCopyRequest &request)
Public Member Functions
S3Client (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new S3Client object.
S3Client (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new S3Client object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Storage Service (S3)
Definition at line 185 of file s3client.h.
Constructor & Destructor Documentation
S3Client() [1/2]
QtAws::S3::S3Client::S3Client (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new S3Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 199 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new S3ClientPrivate(this), parent)
 {
     Q_D(S3Client);
     d->apiVersion = QStringLiteral("2006-03-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("s3");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Simple Storage Service");
     d->serviceName = QStringLiteral("s3");
 }
S3Client() [2/2]
QtAws::S3::S3Client::S3Client (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new S3Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 232 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new S3ClientPrivate(this), parent)
 {
     Q_D(S3Client);
     d->apiVersion = QStringLiteral("2006-03-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("s3");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Simple Storage Service");
     d->serviceName = QStringLiteral("s3");
 }
Member Function Documentation
abortMultipartUpload
AbortMultipartUploadResponse * QtAws::S3::S3Client::abortMultipartUpload (const AbortMultipartUploadRequest & request) slot
Aborts a multipart upload.
To verify that all parts have been removed, so you don't get charged for the part storage, you should call the List Parts operation and ensure the parts list is
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AbortMultipartUploadResponse *>(send(request));
 }
completeMultipartUpload
CompleteMultipartUploadResponse * QtAws::S3::S3Client::completeMultipartUpload (const CompleteMultipartUploadRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 272 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CompleteMultipartUploadResponse *>(send(request));
 }
copyObject
CopyObjectResponse * QtAws::S3::S3Client::copyObject (const CopyObjectRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 285 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CopyObjectResponse *>(send(request));
 }
createBucket
CreateBucketResponse * QtAws::S3::S3Client::createBucket (const CreateBucketRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 298 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBucketResponse *>(send(request));
 }
createMultipartUpload
CreateMultipartUploadResponse * QtAws::S3::S3Client::createMultipartUpload (const CreateMultipartUploadRequest & request) slot
Initiates a multipart upload and returns an upload ID.
Note: After you initiate multipart upload and upload one or more parts, you must either complete or abort multipart upload in order to stop getting charged for storage of the uploaded parts. Only after you either complete or abort multipart upload, Amazon S3 frees up the parts storage and stops charging you for the parts
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 315 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateMultipartUploadResponse *>(send(request));
 }
deleteBucket
DeleteBucketResponse * QtAws::S3::S3Client::deleteBucket (const DeleteBucketRequest & request) slot
Deletes the bucket. All objects (including all object versions and Delete Markers) in the bucket must be deleted before
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 329 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketResponse *>(send(request));
 }
deleteBucketAnalyticsConfiguration
DeleteBucketAnalyticsConfigurationResponse * QtAws::S3::S3Client::deleteBucketAnalyticsConfiguration (const DeleteBucketAnalyticsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 342 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketAnalyticsConfigurationResponse *>(send(request));
 }
deleteBucketCors
DeleteBucketCorsResponse * QtAws::S3::S3Client::deleteBucketCors (const DeleteBucketCorsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 355 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketCorsResponse *>(send(request));
 }
deleteBucketEncryption
DeleteBucketEncryptionResponse * QtAws::S3::S3Client::deleteBucketEncryption (const DeleteBucketEncryptionRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 368 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketEncryptionResponse *>(send(request));
 }
deleteBucketInventoryConfiguration
DeleteBucketInventoryConfigurationResponse * QtAws::S3::S3Client::deleteBucketInventoryConfiguration (const DeleteBucketInventoryConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 381 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketInventoryConfigurationResponse *>(send(request));
 }
deleteBucketLifecycle
DeleteBucketLifecycleResponse * QtAws::S3::S3Client::deleteBucketLifecycle (const DeleteBucketLifecycleRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 394 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketLifecycleResponse *>(send(request));
 }
deleteBucketMetricsConfiguration
DeleteBucketMetricsConfigurationResponse * QtAws::S3::S3Client::deleteBucketMetricsConfiguration (const DeleteBucketMetricsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 407 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketMetricsConfigurationResponse *>(send(request));
 }
deleteBucketPolicy
DeleteBucketPolicyResponse * QtAws::S3::S3Client::deleteBucketPolicy (const DeleteBucketPolicyRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketPolicyResponse *>(send(request));
 }
deleteBucketReplication
DeleteBucketReplicationResponse * QtAws::S3::S3Client::deleteBucketReplication (const DeleteBucketReplicationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 433 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketReplicationResponse *>(send(request));
 }
deleteBucketTagging
DeleteBucketTaggingResponse * QtAws::S3::S3Client::deleteBucketTagging (const DeleteBucketTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 446 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketTaggingResponse *>(send(request));
 }
deleteBucketWebsite
DeleteBucketWebsiteResponse * QtAws::S3::S3Client::deleteBucketWebsite (const DeleteBucketWebsiteRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 459 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBucketWebsiteResponse *>(send(request));
 }
deleteObject
DeleteObjectResponse * QtAws::S3::S3Client::deleteObject (const DeleteObjectRequest & request) slot
Removes the null version (if there is one) of an object and inserts a delete marker, which becomes the latest version of
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 473 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteObjectResponse *>(send(request));
 }
deleteObjects
DeleteObjectsResponse * QtAws::S3::S3Client::deleteObjects (const DeleteObjectsRequest & request) slot
This operation enables you to delete multiple objects from a bucket using a single HTTP request. You may specify up to
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 500 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteObjectsResponse *>(send(request));
 }
deleteObjectTagging
DeleteObjectTaggingResponse * QtAws::S3::S3Client::deleteObjectTagging (const DeleteObjectTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 486 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteObjectTaggingResponse *>(send(request));
 }
getBucketAccelerateConfiguration
GetBucketAccelerateConfigurationResponse * QtAws::S3::S3Client::getBucketAccelerateConfiguration (const GetBucketAccelerateConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 513 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketAccelerateConfigurationResponse *>(send(request));
 }
getBucketAcl
GetBucketAclResponse * QtAws::S3::S3Client::getBucketAcl (const GetBucketAclRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 526 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketAclResponse *>(send(request));
 }
getBucketAnalyticsConfiguration
GetBucketAnalyticsConfigurationResponse * QtAws::S3::S3Client::getBucketAnalyticsConfiguration (const GetBucketAnalyticsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 539 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketAnalyticsConfigurationResponse *>(send(request));
 }
getBucketCors
GetBucketCorsResponse * QtAws::S3::S3Client::getBucketCors (const GetBucketCorsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 552 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketCorsResponse *>(send(request));
 }
getBucketEncryption
GetBucketEncryptionResponse * QtAws::S3::S3Client::getBucketEncryption (const GetBucketEncryptionRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 565 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketEncryptionResponse *>(send(request));
 }
getBucketInventoryConfiguration
GetBucketInventoryConfigurationResponse * QtAws::S3::S3Client::getBucketInventoryConfiguration (const GetBucketInventoryConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 578 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketInventoryConfigurationResponse *>(send(request));
 }
getBucketLifecycle
GetBucketLifecycleResponse * QtAws::S3::S3Client::getBucketLifecycle (const GetBucketLifecycleRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 591 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketLifecycleResponse *>(send(request));
 }
getBucketLifecycleConfiguration
GetBucketLifecycleConfigurationResponse * QtAws::S3::S3Client::getBucketLifecycleConfiguration (const GetBucketLifecycleConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 604 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketLifecycleConfigurationResponse *>(send(request));
 }
getBucketLocation
GetBucketLocationResponse * QtAws::S3::S3Client::getBucketLocation (const GetBucketLocationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 617 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketLocationResponse *>(send(request));
 }
getBucketLogging
GetBucketLoggingResponse * QtAws::S3::S3Client::getBucketLogging (const GetBucketLoggingRequest & request) slot
Returns the logging status of a bucket and the permissions users have to view and modify that status. To use GET, you
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 631 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketLoggingResponse *>(send(request));
 }
getBucketMetricsConfiguration
GetBucketMetricsConfigurationResponse * QtAws::S3::S3Client::getBucketMetricsConfiguration (const GetBucketMetricsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 644 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketMetricsConfigurationResponse *>(send(request));
 }
getBucketNotification
GetBucketNotificationResponse * QtAws::S3::S3Client::getBucketNotification (const GetBucketNotificationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 657 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketNotificationResponse *>(send(request));
 }
getBucketNotificationConfiguration
GetBucketNotificationConfigurationResponse * QtAws::S3::S3Client::getBucketNotificationConfiguration (const GetBucketNotificationConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 670 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketNotificationConfigurationResponse *>(send(request));
 }
getBucketPolicy
GetBucketPolicyResponse * QtAws::S3::S3Client::getBucketPolicy (const GetBucketPolicyRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 683 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketPolicyResponse *>(send(request));
 }
getBucketReplication
GetBucketReplicationResponse * QtAws::S3::S3Client::getBucketReplication (const GetBucketReplicationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 696 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketReplicationResponse *>(send(request));
 }
getBucketRequestPayment
GetBucketRequestPaymentResponse * QtAws::S3::S3Client::getBucketRequestPayment (const GetBucketRequestPaymentRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 709 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketRequestPaymentResponse *>(send(request));
 }
getBucketTagging
GetBucketTaggingResponse * QtAws::S3::S3Client::getBucketTagging (const GetBucketTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 722 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketTaggingResponse *>(send(request));
 }
getBucketVersioning
GetBucketVersioningResponse * QtAws::S3::S3Client::getBucketVersioning (const GetBucketVersioningRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 735 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketVersioningResponse *>(send(request));
 }
getBucketWebsite
GetBucketWebsiteResponse * QtAws::S3::S3Client::getBucketWebsite (const GetBucketWebsiteRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 748 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBucketWebsiteResponse *>(send(request));
 }
getObject
GetObjectResponse * QtAws::S3::S3Client::getObject (const GetObjectRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 761 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetObjectResponse *>(send(request));
 }
getObjectAcl
GetObjectAclResponse * QtAws::S3::S3Client::getObjectAcl (const GetObjectAclRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 774 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetObjectAclResponse *>(send(request));
 }
getObjectTagging
GetObjectTaggingResponse * QtAws::S3::S3Client::getObjectTagging (const GetObjectTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 787 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetObjectTaggingResponse *>(send(request));
 }
getObjectTorrent
GetObjectTorrentResponse * QtAws::S3::S3Client::getObjectTorrent (const GetObjectTorrentRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 800 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetObjectTorrentResponse *>(send(request));
 }
headBucket
HeadBucketResponse * QtAws::S3::S3Client::headBucket (const HeadBucketRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 813 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<HeadBucketResponse *>(send(request));
 }
headObject
HeadObjectResponse * QtAws::S3::S3Client::headObject (const HeadObjectRequest & request) slot
The HEAD operation retrieves metadata from an object without returning the object itself. This operation is useful if
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 827 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<HeadObjectResponse *>(send(request));
 }
listBucketAnalyticsConfigurations
ListBucketAnalyticsConfigurationsResponse * QtAws::S3::S3Client::listBucketAnalyticsConfigurations (const ListBucketAnalyticsConfigurationsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 840 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBucketAnalyticsConfigurationsResponse *>(send(request));
 }
listBucketInventoryConfigurations
ListBucketInventoryConfigurationsResponse * QtAws::S3::S3Client::listBucketInventoryConfigurations (const ListBucketInventoryConfigurationsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 853 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBucketInventoryConfigurationsResponse *>(send(request));
 }
listBucketMetricsConfigurations
ListBucketMetricsConfigurationsResponse * QtAws::S3::S3Client::listBucketMetricsConfigurations (const ListBucketMetricsConfigurationsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 866 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBucketMetricsConfigurationsResponse *>(send(request));
 }
listBuckets
ListBucketsResponse * QtAws::S3::S3Client::listBuckets () slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 879 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBucketsResponse *>(send(request));
 }
listMultipartUploads
ListMultipartUploadsResponse * QtAws::S3::S3Client::listMultipartUploads (const ListMultipartUploadsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 892 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListMultipartUploadsResponse *>(send(request));
 }
listObjects
ListObjectsResponse * QtAws::S3::S3Client::listObjects (const ListObjectsRequest & request) slot
Returns some or all (up to 1000) of the objects in a bucket. You can use the request parameters as selection criteria to
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 919 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListObjectsResponse *>(send(request));
 }
listObjectsV2
ListObjectsV2Response * QtAws::S3::S3Client::listObjectsV2 (const ListObjectsV2Request & request) slot
Returns some or all (up to 1000) of the objects in a bucket. You can use the request parameters as selection criteria to return a subset of the objects in a bucket. Note: ListObjectsV2 is the revised List Objects API and we recommend you use
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 934 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListObjectsV2Response *>(send(request));
 }
listObjectVersions
ListObjectVersionsResponse * QtAws::S3::S3Client::listObjectVersions (const ListObjectVersionsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 905 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListObjectVersionsResponse *>(send(request));
 }
listParts
ListPartsResponse * QtAws::S3::S3Client::listParts (const ListPartsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 947 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPartsResponse *>(send(request));
 }
putBucketAccelerateConfiguration
PutBucketAccelerateConfigurationResponse * QtAws::S3::S3Client::putBucketAccelerateConfiguration (const PutBucketAccelerateConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 960 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketAccelerateConfigurationResponse *>(send(request));
 }
putBucketAcl
PutBucketAclResponse * QtAws::S3::S3Client::putBucketAcl (const PutBucketAclRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 973 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketAclResponse *>(send(request));
 }
putBucketAnalyticsConfiguration
PutBucketAnalyticsConfigurationResponse * QtAws::S3::S3Client::putBucketAnalyticsConfiguration (const PutBucketAnalyticsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 986 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketAnalyticsConfigurationResponse *>(send(request));
 }
putBucketCors
PutBucketCorsResponse * QtAws::S3::S3Client::putBucketCors (const PutBucketCorsRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 999 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketCorsResponse *>(send(request));
 }
putBucketEncryption
PutBucketEncryptionResponse * QtAws::S3::S3Client::putBucketEncryption (const PutBucketEncryptionRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1012 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketEncryptionResponse *>(send(request));
 }
putBucketInventoryConfiguration
PutBucketInventoryConfigurationResponse * QtAws::S3::S3Client::putBucketInventoryConfiguration (const PutBucketInventoryConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1025 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketInventoryConfigurationResponse *>(send(request));
 }
putBucketLifecycle
PutBucketLifecycleResponse * QtAws::S3::S3Client::putBucketLifecycle (const PutBucketLifecycleRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1038 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketLifecycleResponse *>(send(request));
 }
putBucketLifecycleConfiguration
PutBucketLifecycleConfigurationResponse * QtAws::S3::S3Client::putBucketLifecycleConfiguration (const PutBucketLifecycleConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1051 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketLifecycleConfigurationResponse *>(send(request));
 }
putBucketLogging
PutBucketLoggingResponse * QtAws::S3::S3Client::putBucketLogging (const PutBucketLoggingRequest & request) slot
Set the logging parameters for a bucket and to specify permissions for who can view and modify the logging parameters.
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1065 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketLoggingResponse *>(send(request));
 }
putBucketMetricsConfiguration
PutBucketMetricsConfigurationResponse * QtAws::S3::S3Client::putBucketMetricsConfiguration (const PutBucketMetricsConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1078 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketMetricsConfigurationResponse *>(send(request));
 }
putBucketNotification
PutBucketNotificationResponse * QtAws::S3::S3Client::putBucketNotification (const PutBucketNotificationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1091 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketNotificationResponse *>(send(request));
 }
putBucketNotificationConfiguration
PutBucketNotificationConfigurationResponse * QtAws::S3::S3Client::putBucketNotificationConfiguration (const PutBucketNotificationConfigurationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1104 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketNotificationConfigurationResponse *>(send(request));
 }
putBucketPolicy
PutBucketPolicyResponse * QtAws::S3::S3Client::putBucketPolicy (const PutBucketPolicyRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1117 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketPolicyResponse *>(send(request));
 }
putBucketReplication
PutBucketReplicationResponse * QtAws::S3::S3Client::putBucketReplication (const PutBucketReplicationRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1130 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketReplicationResponse *>(send(request));
 }
putBucketRequestPayment
PutBucketRequestPaymentResponse * QtAws::S3::S3Client::putBucketRequestPayment (const PutBucketRequestPaymentRequest & request) slot
Sets the request payment configuration for a bucket. By default, the bucket owner pays for downloads from the bucket. This configuration parameter enables the bucket owner (only) to specify that the person requesting the download will be charged for the download. Documentation on requester pays buckets can be found at
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1146 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketRequestPaymentResponse *>(send(request));
 }
putBucketTagging
PutBucketTaggingResponse * QtAws::S3::S3Client::putBucketTagging (const PutBucketTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1159 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketTaggingResponse *>(send(request));
 }
putBucketVersioning
PutBucketVersioningResponse * QtAws::S3::S3Client::putBucketVersioning (const PutBucketVersioningRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1172 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketVersioningResponse *>(send(request));
 }
putBucketWebsite
PutBucketWebsiteResponse * QtAws::S3::S3Client::putBucketWebsite (const PutBucketWebsiteRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1185 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBucketWebsiteResponse *>(send(request));
 }
putObject
PutObjectResponse * QtAws::S3::S3Client::putObject (const PutObjectRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1198 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutObjectResponse *>(send(request));
 }
putObjectAcl
PutObjectAclResponse * QtAws::S3::S3Client::putObjectAcl (const PutObjectAclRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1211 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutObjectAclResponse *>(send(request));
 }
putObjectTagging
PutObjectTaggingResponse * QtAws::S3::S3Client::putObjectTagging (const PutObjectTaggingRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1224 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutObjectTaggingResponse *>(send(request));
 }
restoreObject
RestoreObjectResponse * QtAws::S3::S3Client::restoreObject (const RestoreObjectRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1237 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RestoreObjectResponse *>(send(request));
 }
uploadPart
UploadPartResponse * QtAws::S3::S3Client::uploadPart (const UploadPartRequest & request) slot
Uploads a part in a multipart upload.
Note: After you initiate multipart upload and upload one or more parts, you must either complete or abort multipart upload in order to stop getting charged for storage of the uploaded parts. Only after you either complete or abort multipart upload, Amazon S3 frees up the parts storage and stops charging you for the parts
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1254 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadPartResponse *>(send(request));
 }
uploadPartCopy
UploadPartCopyResponse * QtAws::S3::S3Client::uploadPartCopy (const UploadPartCopyRequest & request) slot
Parameters
request Request to send to Amazon Simple Storage Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1267 of file s3client.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UploadPartCopyResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
s3/s3client.h
s3/s3client.cpp