AWS SDK for Qt: QtAws::DataPipeline::DataPipelineClient Class Reference
QtAws::DataPipeline::DataPipelineClient Class Reference
Client for AWS Data Pipeline.
Public Slots
ActivatePipelineResponse * activatePipeline (const ActivatePipelineRequest &request)
AddTagsResponse * addTags (const AddTagsRequest &request)
CreatePipelineResponse * createPipeline (const CreatePipelineRequest &request)
DeactivatePipelineResponse * deactivatePipeline (const DeactivatePipelineRequest &request)
DeletePipelineResponse * deletePipeline (const DeletePipelineRequest &request)
DescribeObjectsResponse * describeObjects (const DescribeObjectsRequest &request)
DescribePipelinesResponse * describePipelines (const DescribePipelinesRequest &request)
EvaluateExpressionResponse * evaluateExpression (const EvaluateExpressionRequest &request)
GetPipelineDefinitionResponse * getPipelineDefinition (const GetPipelineDefinitionRequest &request)
ListPipelinesResponse * listPipelines (const ListPipelinesRequest &request)
PollForTaskResponse * pollForTask (const PollForTaskRequest &request)
PutPipelineDefinitionResponse * putPipelineDefinition (const PutPipelineDefinitionRequest &request)
QueryObjectsResponse * queryObjects (const QueryObjectsRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
ReportTaskProgressResponse * reportTaskProgress (const ReportTaskProgressRequest &request)
ReportTaskRunnerHeartbeatResponse * reportTaskRunnerHeartbeat (const ReportTaskRunnerHeartbeatRequest &request)
SetStatusResponse * setStatus (const SetStatusRequest &request)
SetTaskStatusResponse * setTaskStatus (const SetTaskStatusRequest &request)
ValidatePipelineDefinitionResponse * validatePipelineDefinition (const ValidatePipelineDefinitionRequest &request)
Public Member Functions
DataPipelineClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DataPipelineClient object.
DataPipelineClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DataPipelineClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Data Pipeline.
AWS Data Pipeline configures and manages a data-driven workflow called a pipeline. AWS Data Pipeline handles the details of scheduling and ensuring that data dependencies are met so that your application can focus on processing the
data>
AWS Data Pipeline provides a JAR implementation of a task runner called AWS Data Pipeline Task Runner. AWS Data Pipeline Task Runner provides logic for common data management scenarios, such as performing database queries and running data analysis using Amazon Elastic MapReduce (Amazon EMR). You can use AWS Data Pipeline Task Runner as your task runner, or you can write your own task runner to provide custom data
management>
AWS Data Pipeline implements two main sets of functionality. Use the first set to create a pipeline and define data sources, schedules, dependencies, and the transforms to be performed on the data. Use the second set in your task runner application to receive the next task ready for processing. The logic for performing the task, such as querying the data, running data analysis, or converting the data from one format to another, is contained within the task runner. The task runner performs the task assigned to it by the web service, reporting progress to the web service as it does so. When the task is done, the task runner reports the final success or failure of the task to the web
Definition at line 70 of file datapipelineclient.h.
Constructor & Destructor Documentation
DataPipelineClient() [1/2]
QtAws::DataPipeline::DataPipelineClient::DataPipelineClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DataPipelineClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 102 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new DataPipelineClientPrivate(this), parent)
 {
     Q_D(DataPipelineClient);
     d->apiVersion = QStringLiteral("2012-10-29");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("datapipeline");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Data Pipeline");
     d->serviceName = QStringLiteral("datapipeline");
 }
DataPipelineClient() [2/2]
QtAws::DataPipeline::DataPipelineClient::DataPipelineClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DataPipelineClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 135 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new DataPipelineClientPrivate(this), parent)
 {
     Q_D(DataPipelineClient);
     d->apiVersion = QStringLiteral("2012-10-29");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("datapipeline");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Data Pipeline");
     d->serviceName = QStringLiteral("datapipeline");
 }
Member Function Documentation
activatePipeline
ActivatePipelineResponse * QtAws::DataPipeline::DataPipelineClient::activatePipeline (const ActivatePipelineRequest & request) slot
Validates the specified pipeline and starts processing pipeline tasks. If the pipeline does not pass validation, activation
fails>
If you need to pause the pipeline to investigate an issue with a component, such as a data source or script, call
DeactivatePipeline>
To activate a finished pipeline, modify the end date for the pipeline and then activate
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 170 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ActivatePipelineResponse *>(send(request));
 }
addTags
AddTagsResponse * QtAws::DataPipeline::DataPipelineClient::addTags (const AddTagsRequest & request) slot
Adds or modifies tags for the specified
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 184 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AddTagsResponse *>(send(request));
 }
createPipeline
CreatePipelineResponse * QtAws::DataPipeline::DataPipelineClient::createPipeline (const CreatePipelineRequest & request) slot
Creates a new, empty pipeline. Use PutPipelineDefinition to populate the
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 198 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreatePipelineResponse *>(send(request));
 }
deactivatePipeline
DeactivatePipelineResponse * QtAws::DataPipeline::DataPipelineClient::deactivatePipeline (const DeactivatePipelineRequest & request) slot
Deactivates the specified running pipeline. The pipeline is set to the DEACTIVATING state until the deactivation process
completes>
To resume a deactivated pipeline, use ActivatePipeline. By default, the pipeline resumes from the last completed execution. Optionally, you can specify the date and time to resume the
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 218 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeactivatePipelineResponse *>(send(request));
 }
deletePipeline
DeletePipelineResponse * QtAws::DataPipeline::DataPipelineClient::deletePipeline (const DeletePipelineRequest & request) slot
Deletes a pipeline, its pipeline definition, and its run history. AWS Data Pipeline attempts to cancel instances associated with the pipeline that are currently being processed by task
runners>
Deleting a pipeline cannot be undone. You cannot query or restore a deleted pipeline. To temporarily pause a pipeline instead of deleting it, call SetStatus with the status set to PAUSE on individual components. Components that are paused by SetStatus can be
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 239 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePipelineResponse *>(send(request));
 }
describeObjects
DescribeObjectsResponse * QtAws::DataPipeline::DataPipelineClient::describeObjects (const DescribeObjectsRequest & request) slot
Gets the object definitions for a set of objects associated with the pipeline. Object definitions are composed of a set of fields that define the properties of the
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 254 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeObjectsResponse *>(send(request));
 }
describePipelines
DescribePipelinesResponse * QtAws::DataPipeline::DataPipelineClient::describePipelines (const DescribePipelinesRequest & request) slot
Retrieves metadata about one or more pipelines. The information retrieved includes the name of the pipeline, the pipeline identifier, its current state, and the user account that owns the pipeline. Using account credentials, you can retrieve metadata about pipelines that you or your IAM users have created. If you are using an IAM user account, you can retrieve metadata about only those pipelines for which you have read
permissions>
To retrieve the full pipeline definition instead of metadata about the pipeline, call
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 275 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePipelinesResponse *>(send(request));
 }
evaluateExpression
EvaluateExpressionResponse * QtAws::DataPipeline::DataPipelineClient::evaluateExpression (const EvaluateExpressionRequest & request) slot
Task runners call EvaluateExpression to evaluate a string in the context of the specified object. For example, a task runner can evaluate SQL queries stored in Amazon
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 290 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EvaluateExpressionResponse *>(send(request));
 }
getPipelineDefinition
GetPipelineDefinitionResponse * QtAws::DataPipeline::DataPipelineClient::getPipelineDefinition (const GetPipelineDefinitionRequest & request) slot
Gets the definition of the specified pipeline. You can call GetPipelineDefinition to retrieve the pipeline definition that you provided using
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetPipelineDefinitionResponse *>(send(request));
 }
listPipelines
ListPipelinesResponse * QtAws::DataPipeline::DataPipelineClient::listPipelines (const ListPipelinesRequest & request) slot
Lists the pipeline identifiers for all active pipelines that you have permission to
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 319 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListPipelinesResponse *>(send(request));
 }
pollForTask
PollForTaskResponse * QtAws::DataPipeline::DataPipelineClient::pollForTask (const PollForTaskRequest & request) slot
Task runners call PollForTask to receive a task to perform from AWS Data Pipeline. The task runner specifies which tasks it can perform by setting a value for the workerGroup parameter. The task returned can come from any of the pipelines that match the workerGroup value passed in by the task runner and that was launched using the IAM user credentials specified by the task
runner>
If tasks are ready in the work queue, PollForTask returns a response immediately. If no tasks are available in the queue, PollForTask uses long-polling and holds on to a poll connection for up to a 90 seconds, during which time the first newly scheduled task is handed to the task runner. To accomodate this, set the socket timeout in your task runner to 90 seconds. The task runner should not call PollForTask again on the same workerGroup until it receives a response, and this can take up to 90 seconds.
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 344 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PollForTaskResponse *>(send(request));
 }
putPipelineDefinition
PutPipelineDefinitionResponse * QtAws::DataPipeline::DataPipelineClient::putPipelineDefinition (const PutPipelineDefinitionRequest & request) slot
Adds tasks, schedules, and preconditions to the specified pipeline. You can use PutPipelineDefinition to populate a new
pipeline>
PutPipelineDefinition also validates the configuration as it adds it to the pipeline. Changes to the pipeline are saved unless one of the following three validation errors exists in the pipeline.
</p
An object is missing a name or identifier field.
A string or reference field is empty.
The number of objects in the pipeline exceeds the maximum allowed objects.
The pipeline is in a FINISHED state.
Pipeline object definitions are passed to the PutPipelineDefinition action and returned by the GetPipelineDefinition action.
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 371 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutPipelineDefinitionResponse *>(send(request));
 }
queryObjects
QueryObjectsResponse * QtAws::DataPipeline::DataPipelineClient::queryObjects (const QueryObjectsRequest & request) slot
Queries the specified pipeline for the names of objects that match the specified set of
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 385 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<QueryObjectsResponse *>(send(request));
 }
removeTags
RemoveTagsResponse * QtAws::DataPipeline::DataPipelineClient::removeTags (const RemoveTagsRequest & request) slot
Removes existing tags from the specified
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 399 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RemoveTagsResponse *>(send(request));
 }
reportTaskProgress
ReportTaskProgressResponse * QtAws::DataPipeline::DataPipelineClient::reportTaskProgress (const ReportTaskProgressRequest & request) slot
Task runners call ReportTaskProgress when assigned a task to acknowledge that it has the task. If the web service does not receive this acknowledgement within 2 minutes, it assigns the task in a subsequent PollForTask call. After this initial acknowledgement, the task runner only needs to report progress every 15 minutes to maintain its ownership of the task. You can change this reporting time from 15 minutes by specifying a reportProgressTimeout field in your
pipeline>
If a task runner does not report its status after 5 minutes, AWS Data Pipeline assumes that the task runner is unable to process the task and reassigns the task in a subsequent response to PollForTask. Task runners should call ReportTaskProgress every 60
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 423 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReportTaskProgressResponse *>(send(request));
 }
reportTaskRunnerHeartbeat
ReportTaskRunnerHeartbeatResponse * QtAws::DataPipeline::DataPipelineClient::reportTaskRunnerHeartbeat (const ReportTaskRunnerHeartbeatRequest & request) slot
Task runners call ReportTaskRunnerHeartbeat every 15 minutes to indicate that they are operational. If the AWS Data Pipeline Task Runner is launched on a resource managed by AWS Data Pipeline, the web service can use this call to detect when the task runner application has failed and restart a new
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 439 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ReportTaskRunnerHeartbeatResponse *>(send(request));
 }
setStatus
SetStatusResponse * QtAws::DataPipeline::DataPipelineClient::setStatus (const SetStatusRequest & request) slot
Requests that the status of the specified physical or logical pipeline objects be updated in the specified pipeline. This update might not occur immediately, but is eventually consistent. The status that can be set depends on the type of object (for example, DataNode or Activity). You cannot perform this operation on FINISHED pipelines and attempting to do so returns
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 456 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetStatusResponse *>(send(request));
 }
setTaskStatus
SetTaskStatusResponse * QtAws::DataPipeline::DataPipelineClient::setTaskStatus (const SetTaskStatusRequest & request) slot
Task runners call SetTaskStatus to notify AWS Data Pipeline that a task is completed and provide information about the final status. A task runner makes this call regardless of whether the task was sucessful. A task runner does not need to call SetTaskStatus for tasks that are canceled by the web service during a call to
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 472 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetTaskStatusResponse *>(send(request));
 }
validatePipelineDefinition
ValidatePipelineDefinitionResponse * QtAws::DataPipeline::DataPipelineClient::validatePipelineDefinition (const ValidatePipelineDefinitionRequest & request) slot
Validates the specified pipeline definition to ensure that it is well formed and can be run without
Parameters
request Request to send to AWS Data Pipeline.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 486 of file datapipelineclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ValidatePipelineDefinitionResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
datapipeline/datapipelineclient.h
datapipeline/datapipelineclient.cpp