AWS SDK for Qt: QtAws::KinesisVideoMedia::KinesisVideoMediaClient Class Reference
QtAws::KinesisVideoMedia::KinesisVideoMediaClient Class Reference
Client for Amazon Kinesis Video Streams Media (Kinesis Video Media)
Public Slots
GetMediaResponse * getMedia (const GetMediaRequest &request)
Public Member Functions
KinesisVideoMediaClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisVideoMediaClient object.
KinesisVideoMediaClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisVideoMediaClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Kinesis Video Streams Media (Kinesis Video Media)
Definition at line 34 of file kinesisvideomediaclient.h.
Constructor & Destructor Documentation
KinesisVideoMediaClient() [1/2]
QtAws::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisVideoMediaClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file kinesisvideomediaclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new KinesisVideoMediaClientPrivate(this), parent)
 {
     Q_D(KinesisVideoMediaClient);
     d->apiVersion = QStringLiteral("2017-09-30");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("kinesisvideo");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Video Streams Media");
     d->serviceName = QStringLiteral("kinesisvideo");
 }
KinesisVideoMediaClient() [2/2]
QtAws::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisVideoMediaClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 81 of file kinesisvideomediaclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new KinesisVideoMediaClientPrivate(this), parent)
 {
     Q_D(KinesisVideoMediaClient);
     d->apiVersion = QStringLiteral("2017-09-30");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("kinesisvideo");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Kinesis Video Streams Media");
     d->serviceName = QStringLiteral("kinesisvideo");
 }
Member Function Documentation
getMedia
GetMediaResponse * QtAws::KinesisVideoMedia::KinesisVideoMediaClient::getMedia (const GetMediaRequest & request) slot
Use this API to retrieve media content from a Kinesis video stream. In the request, you identify stream name or stream Amazon Resource Name (ARN), and the starting chunk. Kinesis Video Streams then returns a stream of chunks in order by fragment
number> <note>
You must first call the GetDataEndpoint API to get an endpoint to which you can then send the GetMedia requests.
</p </note>
When you put media data (fragments) on a stream, Kinesis Video Streams stores each incoming fragment and related metadata in what is called a "chunk." For more information, see . The GetMedia API returns a stream of these chunks starting from the chunk that you specify in the request.
</p
The following limits apply when using the GetMedia
API>
A client can call GetMedia up to five times per second per stream.
</p
Kinesis Video Streams sends media data at a rate of up to 25 megabytes per second (or 200 megabits per second) during a GetMedia session.
Parameters
request Request to send to Amazon Kinesis Video Streams Media.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 133 of file kinesisvideomediaclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetMediaResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
kinesis-video-media/kinesisvideomediaclient.h
kinesis-video-media/kinesisvideomediaclient.cpp