AWS SDK for Qt: QtAws::MQ::MqClient Class Reference
QtAws::MQ::MqClient Class Reference
Client for AmazonMQ.
Public Slots
CreateBrokerResponse * createBroker (const CreateBrokerRequest &request)
CreateConfigurationResponse * createConfiguration (const CreateConfigurationRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeleteBrokerResponse * deleteBroker (const DeleteBrokerRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DescribeBrokerResponse * describeBroker (const DescribeBrokerRequest &request)
DescribeConfigurationResponse * describeConfiguration (const DescribeConfigurationRequest &request)
DescribeConfigurationRevisionResponse * describeConfigurationRevision (const DescribeConfigurationRevisionRequest &request)
DescribeUserResponse * describeUser (const DescribeUserRequest &request)
ListBrokersResponse * listBrokers (const ListBrokersRequest &request)
ListConfigurationRevisionsResponse * listConfigurationRevisions (const ListConfigurationRevisionsRequest &request)
ListConfigurationsResponse * listConfigurations (const ListConfigurationsRequest &request)
ListUsersResponse * listUsers (const ListUsersRequest &request)
RebootBrokerResponse * rebootBroker (const RebootBrokerRequest &request)
UpdateBrokerResponse * updateBroker (const UpdateBrokerRequest &request)
UpdateConfigurationResponse * updateConfiguration (const UpdateConfigurationRequest &request)
UpdateUserResponse * updateUser (const UpdateUserRequest &request)
Public Member Functions
MqClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MqClient object.
MqClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MqClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AmazonMQ.
Amazon MQ is a managed message broker service for Apache ActiveMQ that makes it easy to set up and operate message brokers in the cloud. A message broker allows software applications and components to communicate using various
Definition at line 66 of file mqclient.h.
Constructor & Destructor Documentation
MqClient() [1/2]
QtAws::MQ::MqClient::MqClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MqClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 82 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new MqClientPrivate(this), parent)
 {
     Q_D(MqClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("mq");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AmazonMQ");
     d->serviceName = QStringLiteral("mq");
 }
MqClient() [2/2]
QtAws::MQ::MqClient::MqClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MqClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 115 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new MqClientPrivate(this), parent)
 {
     Q_D(MqClient);
     d->apiVersion = QStringLiteral("2017-11-27");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("mq");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AmazonMQ");
     d->serviceName = QStringLiteral("mq");
 }
Member Function Documentation
createBroker
CreateBrokerResponse * QtAws::MQ::MqClient::createBroker (const CreateBrokerRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 140 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBrokerResponse *>(send(request));
 }
createConfiguration
CreateConfigurationResponse * QtAws::MQ::MqClient::createConfiguration (const CreateConfigurationRequest & request) slot
Creates a new configuration for the specified configuration name. Amazon MQ uses the default configuration (the engine
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 154 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateConfigurationResponse *>(send(request));
 }
createUser
CreateUserResponse * QtAws::MQ::MqClient::createUser (const CreateUserRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 167 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateUserResponse *>(send(request));
 }
deleteBroker
DeleteBrokerResponse * QtAws::MQ::MqClient::deleteBroker (const DeleteBrokerRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 180 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBrokerResponse *>(send(request));
 }
deleteUser
DeleteUserResponse * QtAws::MQ::MqClient::deleteUser (const DeleteUserRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 193 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUserResponse *>(send(request));
 }
describeBroker
DescribeBrokerResponse * QtAws::MQ::MqClient::describeBroker (const DescribeBrokerRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 206 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeBrokerResponse *>(send(request));
 }
describeConfiguration
DescribeConfigurationResponse * QtAws::MQ::MqClient::describeConfiguration (const DescribeConfigurationRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 219 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigurationResponse *>(send(request));
 }
describeConfigurationRevision
DescribeConfigurationRevisionResponse * QtAws::MQ::MqClient::describeConfigurationRevision (const DescribeConfigurationRevisionRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 232 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeConfigurationRevisionResponse *>(send(request));
 }
describeUser
DescribeUserResponse * QtAws::MQ::MqClient::describeUser (const DescribeUserRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeUserResponse *>(send(request));
 }
listBrokers
ListBrokersResponse * QtAws::MQ::MqClient::listBrokers (const ListBrokersRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 258 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListBrokersResponse *>(send(request));
 }
listConfigurationRevisions
ListConfigurationRevisionsResponse * QtAws::MQ::MqClient::listConfigurationRevisions (const ListConfigurationRevisionsRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 271 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListConfigurationRevisionsResponse *>(send(request));
 }
listConfigurations
ListConfigurationsResponse * QtAws::MQ::MqClient::listConfigurations (const ListConfigurationsRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 284 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListConfigurationsResponse *>(send(request));
 }
listUsers
ListUsersResponse * QtAws::MQ::MqClient::listUsers (const ListUsersRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 297 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListUsersResponse *>(send(request));
 }
rebootBroker
RebootBrokerResponse * QtAws::MQ::MqClient::rebootBroker (const RebootBrokerRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 310 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RebootBrokerResponse *>(send(request));
 }
updateBroker
UpdateBrokerResponse * QtAws::MQ::MqClient::updateBroker (const UpdateBrokerRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 323 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateBrokerResponse *>(send(request));
 }
updateConfiguration
UpdateConfigurationResponse * QtAws::MQ::MqClient::updateConfiguration (const UpdateConfigurationRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 336 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateConfigurationResponse *>(send(request));
 }
updateUser
UpdateUserResponse * QtAws::MQ::MqClient::updateUser (const UpdateUserRequest & request) slot
Parameters
request Request to send to AmazonMQ.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 349 of file mqclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateUserResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
mq/mqclient.h
mq/mqclient.cpp