AWS SDK for Qt: QtAws::LexModelBuildingService::LexModelBuildingServiceClient Class Reference
QtAws::LexModelBuildingService::LexModelBuildingServiceClient Class Reference
Client for Amazon Lex Model Building Service.
Public Slots
CreateBotVersionResponse * createBotVersion (const CreateBotVersionRequest &request)
CreateIntentVersionResponse * createIntentVersion (const CreateIntentVersionRequest &request)
CreateSlotTypeVersionResponse * createSlotTypeVersion (const CreateSlotTypeVersionRequest &request)
DeleteBotResponse * deleteBot (const DeleteBotRequest &request)
DeleteBotAliasResponse * deleteBotAlias (const DeleteBotAliasRequest &request)
DeleteBotChannelAssociationResponse * deleteBotChannelAssociation (const DeleteBotChannelAssociationRequest &request)
DeleteBotVersionResponse * deleteBotVersion (const DeleteBotVersionRequest &request)
DeleteIntentResponse * deleteIntent (const DeleteIntentRequest &request)
DeleteIntentVersionResponse * deleteIntentVersion (const DeleteIntentVersionRequest &request)
DeleteSlotTypeResponse * deleteSlotType (const DeleteSlotTypeRequest &request)
DeleteSlotTypeVersionResponse * deleteSlotTypeVersion (const DeleteSlotTypeVersionRequest &request)
DeleteUtterancesResponse * deleteUtterances (const DeleteUtterancesRequest &request)
GetBotResponse * getBot (const GetBotRequest &request)
GetBotAliasResponse * getBotAlias (const GetBotAliasRequest &request)
GetBotAliasesResponse * getBotAliases (const GetBotAliasesRequest &request)
GetBotChannelAssociationResponse * getBotChannelAssociation (const GetBotChannelAssociationRequest &request)
GetBotChannelAssociationsResponse * getBotChannelAssociations (const GetBotChannelAssociationsRequest &request)
GetBotVersionsResponse * getBotVersions (const GetBotVersionsRequest &request)
GetBotsResponse * getBots (const GetBotsRequest &request)
GetBuiltinIntentResponse * getBuiltinIntent (const GetBuiltinIntentRequest &request)
GetBuiltinIntentsResponse * getBuiltinIntents (const GetBuiltinIntentsRequest &request)
GetBuiltinSlotTypesResponse * getBuiltinSlotTypes (const GetBuiltinSlotTypesRequest &request)
GetExportResponse * getExport (const GetExportRequest &request)
GetImportResponse * getImport (const GetImportRequest &request)
GetIntentResponse * getIntent (const GetIntentRequest &request)
GetIntentVersionsResponse * getIntentVersions (const GetIntentVersionsRequest &request)
GetIntentsResponse * getIntents (const GetIntentsRequest &request)
GetSlotTypeResponse * getSlotType (const GetSlotTypeRequest &request)
GetSlotTypeVersionsResponse * getSlotTypeVersions (const GetSlotTypeVersionsRequest &request)
GetSlotTypesResponse * getSlotTypes (const GetSlotTypesRequest &request)
GetUtterancesViewResponse * getUtterancesView (const GetUtterancesViewRequest &request)
PutBotResponse * putBot (const PutBotRequest &request)
PutBotAliasResponse * putBotAlias (const PutBotAliasRequest &request)
PutIntentResponse * putIntent (const PutIntentRequest &request)
PutSlotTypeResponse * putSlotType (const PutSlotTypeRequest &request)
StartImportResponse * startImport (const StartImportRequest &request)
Public Member Functions
LexModelBuildingServiceClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexModelBuildingServiceClient object.
LexModelBuildingServiceClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexModelBuildingServiceClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Lex Model Building Service.
<fullname>Amazon Lex Build-Time Actions</fullname>
Amazon Lex is an AWS service for building conversational voice and text interfaces. Use these actions to create, update, and delete conversational bots for new and existing client applications.
Definition at line 104 of file lexmodelbuildingserviceclient.h.
Constructor & Destructor Documentation
LexModelBuildingServiceClient() [1/2]
QtAws::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexModelBuildingServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 122 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new LexModelBuildingServiceClientPrivate(this), parent)
 {
     Q_D(LexModelBuildingServiceClient);
     d->apiVersion = QStringLiteral("2017-04-19");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("models.lex");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Amazon Lex Model Building Service");
     d->serviceName = QStringLiteral("lex");
 }
LexModelBuildingServiceClient() [2/2]
QtAws::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexModelBuildingServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 155 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new LexModelBuildingServiceClientPrivate(this), parent)
 {
     Q_D(LexModelBuildingServiceClient);
     d->apiVersion = QStringLiteral("2017-04-19");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("models.lex");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Amazon Lex Model Building Service");
     d->serviceName = QStringLiteral("lex");
 }
Member Function Documentation
createBotVersion
CreateBotVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createBotVersion (const CreateBotVersionRequest & request) slot
Creates a new version of the bot based on the $LATEST version. If the $LATEST version of this resource hasn't changed since you created the last version, Amazon Lex doesn't create a new version. It returns the last created
version> <note>
You can update only the $LATEST version of the bot. You can't update the numbered versions that you create with the CreateBotVersion
operation> </note>
When you create the first version of a bot, Amazon Lex sets the version to 1. Subsequent versions increment by 1. For more information, see versioning-intro.
</p
This operation requires permission for the lex:CreateBotVersion action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 197 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateBotVersionResponse *>(send(request));
 }
createIntentVersion
CreateIntentVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createIntentVersion (const CreateIntentVersionRequest & request) slot
Creates a new version of an intent based on the $LATEST version of the intent. If the $LATEST version of this intent hasn't changed since you last updated it, Amazon Lex doesn't create a new version. It returns the last version you
created> <note>
You can update only the $LATEST version of the intent. You can't update the numbered versions that you create with the CreateIntentVersion
operation> </note>
When you create a version of an intent, Amazon Lex sets the version to 1. Subsequent versions increment by 1. For more information, see versioning-intro.
</p
This operation requires permissions to perform the lex:CreateIntentVersion action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 227 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateIntentVersionResponse *>(send(request));
 }
createSlotTypeVersion
CreateSlotTypeVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::createSlotTypeVersion (const CreateSlotTypeVersionRequest & request) slot
Creates a new version of a slot type based on the $LATEST version of the specified slot type. If the $LATEST version of this resource has not changed since the last version that you created, Amazon Lex doesn't create a new version. It returns the last version that you created.
</p <note>
You can update only the $LATEST version of a slot type. You can't update the numbered versions that you create with the CreateSlotTypeVersion
operation> </note>
When you create a version of a slot type, Amazon Lex sets the version to 1. Subsequent versions increment by 1. For more information, see versioning-intro.
</p
This operation requires permissions for the lex:CreateSlotTypeVersion
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 257 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSlotTypeVersionResponse *>(send(request));
 }
deleteBot
DeleteBotResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBot (const DeleteBotRequest & request) slot
Deletes all versions of the bot, including the $LATEST version. To delete a specific version of the bot, use the DeleteBotVersion
operation>
If a bot has an alias, you can't delete it. Instead, the DeleteBot operation returns a ResourceInUseException exception that includes a reference to the alias that refers to the bot. To remove the reference to the bot, delete the alias. If you get the same exception again, delete the referring alias until the DeleteBot operation is
successful>
This operation requires permissions for the lex:DeleteBot
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 283 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBotResponse *>(send(request));
 }
deleteBotAlias
DeleteBotAliasResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotAlias (const DeleteBotAliasRequest & request) slot
Deletes an alias for the specified bot.
</p
You can't delete an alias that is used in the association between a bot and a messaging channel. If an alias is used in a channel association, the DeleteBot operation returns a ResourceInUseException exception that includes a reference to the channel association that refers to the bot. You can remove the reference to the alias by deleting the channel association. If you get the same exception again, delete the referring association until the DeleteBotAlias operation is
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 305 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBotAliasResponse *>(send(request));
 }
deleteBotChannelAssociation
DeleteBotChannelAssociationResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotChannelAssociation (const DeleteBotChannelAssociationRequest & request) slot
Deletes the association between an Amazon Lex bot and a messaging
platform>
This operation requires permission for the lex:DeleteBotChannelAssociation
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 323 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBotChannelAssociationResponse *>(send(request));
 }
deleteBotVersion
DeleteBotVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteBotVersion (const DeleteBotVersionRequest & request) slot
Deletes a specific version of a bot. To delete all versions of a bot, use the DeleteBot operation.
</p
This operation requires permissions for the lex:DeleteBotVersion
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 341 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteBotVersionResponse *>(send(request));
 }
deleteIntent
DeleteIntentResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteIntent (const DeleteIntentRequest & request) slot
Deletes all versions of the intent, including the $LATEST version. To delete a specific version of the intent, use the DeleteIntentVersion
operation>
You can delete a version of an intent only if it is not referenced. To delete an intent that is referred to in one or more bots (see how-it-works), you must remove those references first.
</p <note>
If you get the ResourceInUseException exception, it provides an example reference that shows where the intent is referenced. To remove the reference to the intent, either update the bot or delete it. If you get the same exception when you attempt to delete the intent again, repeat until the intent has no references and the call to DeleteIntent is successful.
</p </note>
This operation requires permission for the lex:DeleteIntent action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 372 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIntentResponse *>(send(request));
 }
deleteIntentVersion
DeleteIntentVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteIntentVersion (const DeleteIntentVersionRequest & request) slot
Deletes a specific version of an intent. To delete all versions of a intent, use the DeleteIntent operation.
</p
This operation requires permissions for the lex:DeleteIntentVersion
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 390 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteIntentVersionResponse *>(send(request));
 }
deleteSlotType
DeleteSlotTypeResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteSlotType (const DeleteSlotTypeRequest & request) slot
Deletes all versions of the slot type, including the $LATEST version. To delete a specific version of the slot type, use the DeleteSlotTypeVersion
operation>
You can delete a version of a slot type only if it is not referenced. To delete a slot type that is referred to in one or more intents, you must remove those references first.
</p <note>
If you get the ResourceInUseException exception, the exception provides an example reference that shows the intent where the slot type is referenced. To remove the reference to the slot type, either update the intent or delete it. If you get the same exception when you attempt to delete the slot type again, repeat until the slot type has no references and the DeleteSlotType call is successful.
</p </note>
This operation requires permission for the lex:DeleteSlotType
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 421 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSlotTypeResponse *>(send(request));
 }
deleteSlotTypeVersion
DeleteSlotTypeVersionResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteSlotTypeVersion (const DeleteSlotTypeVersionRequest & request) slot
Deletes a specific version of a slot type. To delete all versions of a slot type, use the DeleteSlotType operation.
</p
This operation requires permissions for the lex:DeleteSlotTypeVersion
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 440 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSlotTypeVersionResponse *>(send(request));
 }
deleteUtterances
DeleteUtterancesResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::deleteUtterances (const DeleteUtterancesRequest & request) slot
Deletes stored
utterances>
Amazon Lex stores the utterances that users send to your bot. Utterances are stored for 15 days for use with the GetUtterancesView operation, and then stored indefinitely for use in improving the ability of your bot to respond to user
input>
Use the DeleteStoredUtterances operation to manually delete stored utterances for a specific
user>
This operation requires permissions for the lex:DeleteUtterances
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 468 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteUtterancesResponse *>(send(request));
 }
getBot
GetBotResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBot (const GetBotRequest & request) slot
Returns metadata information for a specific bot. You must provide the bot name and the bot version or alias.
</p
This operation requires permissions for the lex:GetBot action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 486 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotResponse *>(send(request));
 }
getBotAlias
GetBotAliasResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotAlias (const GetBotAliasRequest & request) slot
Returns information about an Amazon Lex bot alias. For more information about aliases, see
versioning-aliases>
This operation requires permissions for the lex:GetBotAlias
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 504 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotAliasResponse *>(send(request));
 }
getBotAliases
GetBotAliasesResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotAliases (const GetBotAliasesRequest & request) slot
Returns a list of aliases for a specified Amazon Lex
bot>
This operation requires permissions for the lex:GetBotAliases
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 522 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotAliasesResponse *>(send(request));
 }
getBotChannelAssociation
GetBotChannelAssociationResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotChannelAssociation (const GetBotChannelAssociationRequest & request) slot
Returns information about the association between an Amazon Lex bot and a messaging
platform>
This operation requires permissions for the lex:GetBotChannelAssociation
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 540 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotChannelAssociationResponse *>(send(request));
 }
getBotChannelAssociations
GetBotChannelAssociationsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotChannelAssociations (const GetBotChannelAssociationsRequest & request) slot
Returns a list of all of the channels associated with the specified bot.
</p
The GetBotChannelAssociations operation requires permissions for the lex:GetBotChannelAssociations
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 559 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotChannelAssociationsResponse *>(send(request));
 }
getBots
GetBotsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBots (const GetBotsRequest & request) slot
Returns bot information as follows:
</p
If you provide the nameContains field, the response includes information for the $LATEST version of all bots whose name contains the specified
string>
If you don't specify the nameContains field, the operation returns information about the $LATEST version of all of your
bots>
This operation requires permission for the lex:GetBots
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 616 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotsResponse *>(send(request));
 }
getBotVersions
GetBotVersionsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBotVersions (const GetBotVersionsRequest & request) slot
Gets information about all of the versions of a
bot>
The GetBotVersions operation returns a BotMetadata object for each version of a bot. For example, if a bot has three numbered versions, the GetBotVersions operation returns four BotMetadata objects in the response, one for each numbered version and one for the $LATEST version.
</p
The GetBotVersions operation always returns at least one version, the $LATEST
version>
This operation requires permissions for the lex:GetBotVersions
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 588 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBotVersionsResponse *>(send(request));
 }
getBuiltinIntent
GetBuiltinIntentResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinIntent (const GetBuiltinIntentRequest & request) slot
Returns information about a built-in
intent>
This operation requires permission for the lex:GetBuiltinIntent
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 634 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBuiltinIntentResponse *>(send(request));
 }
getBuiltinIntents
GetBuiltinIntentsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinIntents (const GetBuiltinIntentsRequest & request) slot
Gets a list of built-in intents that meet the specified
criteria>
This operation requires permission for the lex:GetBuiltinIntents
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 652 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBuiltinIntentsResponse *>(send(request));
 }
getBuiltinSlotTypes
GetBuiltinSlotTypesResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getBuiltinSlotTypes (const GetBuiltinSlotTypesRequest & request) slot
Gets a list of built-in slot types that meet the specified
criteria>
For a list of built-in slot types, see Slot Type Reference in the Alexa Skills
Kit>
This operation requires permission for the lex:GetBuiltInSlotTypes
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 676 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetBuiltinSlotTypesResponse *>(send(request));
 }
getExport
GetExportResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getExport (const GetExportRequest & request) slot
Exports the contents of a Amazon Lex resource in a specified format.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 690 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetExportResponse *>(send(request));
 }
getImport
GetImportResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getImport (const GetImportRequest & request) slot
Gets information about an import job started with the StartImport
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 704 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetImportResponse *>(send(request));
 }
getIntent
GetIntentResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntent (const GetIntentRequest & request) slot
Returns information about an intent. In addition to the intent name, you must specify the intent version.
</p
This operation requires permissions to perform the lex:GetIntent action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 722 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIntentResponse *>(send(request));
 }
getIntents
GetIntentsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntents (const GetIntentsRequest & request) slot
Returns intent information as follows:
</p
If you specify the nameContains field, returns the $LATEST version of all intents that contain the specified
string>
If you don't specify the nameContains field, returns information about the $LATEST version of all intents.
</p
The operation requires permission for the lex:GetIntents action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 779 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIntentsResponse *>(send(request));
 }
getIntentVersions
GetIntentVersionsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getIntentVersions (const GetIntentVersionsRequest & request) slot
Gets information about all of the versions of an
intent>
The GetIntentVersions operation returns an IntentMetadata object for each version of an intent. For example, if an intent has three numbered versions, the GetIntentVersions operation returns four IntentMetadata objects in the response, one for each numbered version and one for the $LATEST version.
</p
The GetIntentVersions operation always returns at least one version, the $LATEST
version>
This operation requires permissions for the lex:GetIntentVersions
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 751 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetIntentVersionsResponse *>(send(request));
 }
getSlotType
GetSlotTypeResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotType (const GetSlotTypeRequest & request) slot
Returns information about a specific version of a slot type. In addition to specifying the slot type name, you must specify the slot type
version>
This operation requires permissions for the lex:GetSlotType
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 798 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSlotTypeResponse *>(send(request));
 }
getSlotTypes
GetSlotTypesResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotTypes (const GetSlotTypesRequest & request) slot
Returns slot type information as follows:
</p
If you specify the nameContains field, returns the $LATEST version of all slot types that contain the specified
string>
If you don't specify the nameContains field, returns information about the $LATEST version of all slot types.
</p
The operation requires permission for the lex:GetSlotTypes action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 855 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSlotTypesResponse *>(send(request));
 }
getSlotTypeVersions
GetSlotTypeVersionsResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getSlotTypeVersions (const GetSlotTypeVersionsRequest & request) slot
Gets information about all versions of a slot
type>
The GetSlotTypeVersions operation returns a SlotTypeMetadata object for each version of a slot type. For example, if a slot type has three numbered versions, the GetSlotTypeVersions operation returns four SlotTypeMetadata objects in the response, one for each numbered version and one for the $LATEST version.
</p
The GetSlotTypeVersions operation always returns at least one version, the $LATEST
version>
This operation requires permissions for the lex:GetSlotTypeVersions
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 827 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSlotTypeVersionsResponse *>(send(request));
 }
getUtterancesView
GetUtterancesViewResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::getUtterancesView (const GetUtterancesViewRequest & request) slot
Use the GetUtterancesView operation to get information about the utterances that your users have made to your bot. You can use this list to tune the utterances that your bot responds
to>
For example, say that you have created a bot to order flowers. After your users have used your bot for a while, use the GetUtterancesView operation to see the requests that they have made and whether they have been successful. You might find that the utterance "I want flowers" is not being recognized. You could add this utterance to the OrderFlowers intent so that your bot recognizes that
utterance>
After you publish a new version of a bot, you can get information about the old version and the new so that you can compare the performance across the two versions.
</p <note>
Utterance statistics are generated once a day. Data is available for the last 15 days. You can request information for up to 5 versions in each request. The response contains information about a maximum of 100 utterances for each
version> </note>
This operation requires permissions for the lex:GetUtterancesView
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 891 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetUtterancesViewResponse *>(send(request));
 }
putBot
PutBotResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putBot (const PutBotRequest & request) slot
Creates an Amazon Lex conversational bot or replaces an existing bot. When you create or update a bot you are only required to specify a name, a locale, and whether the bot is directed toward children under age 13. You can use this to add intents later, or to remove intents from an existing bot. When you create a bot with the minimum information, the bot is created or updated but Amazon Lex returns the response FAILED. You can build the bot after you add one or more intents. For more information about Amazon Lex bots, see how-it-works.
</p
If you specify the name of an existing bot, the fields in the request replace the existing values in the $LATEST version of the bot. Amazon Lex removes any fields that you don't provide values for in the request, except for the idleTTLInSeconds and privacySettings fields, which are set to their default values. If you don't specify values for required fields, Amazon Lex throws an
exception>
This operation requires permissions for the lex:PutBot action. For more information, see
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 920 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBotResponse *>(send(request));
 }
putBotAlias
PutBotAliasResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putBotAlias (const PutBotAliasRequest & request) slot
Creates an alias for the specified version of the bot or replaces an alias for the specified bot. To change the version of the bot that the alias points to, replace the alias. For more information about aliases, see
versioning-aliases>
This operation requires permissions for the lex:PutBotAlias action.
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 939 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutBotAliasResponse *>(send(request));
 }
putIntent
PutIntentResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putIntent (const PutIntentRequest & request) slot
Creates an intent or replaces an existing
intent>
To define the interaction between the user and your bot, you use one or more intents. For a pizza ordering bot, for example, you would create an OrderPizza intent.
</p
To create an intent or replace an existing intent, you must provide the
following>
Intent name. For example,
OrderPizza>
Sample utterances. For example, "Can I order a pizza, please." and "I want to order a
pizza.>
Information to be gathered. You specify slot types for the information that your bot will request from the user. You can specify standard slot types, such as a date or a time, or custom slot types such as the size and crust of a
pizza>
How the intent will be fulfilled. You can provide a Lambda function or configure the intent to return the intent information to the client application. If you use a Lambda function, when all of the intent information is available, Amazon Lex invokes your Lambda function. If you configure your intent to return the intent information to the client application.
</p
You can specify other optional information in the request, such
as>
A confirmation prompt to ask the user to confirm an intent. For example, "Shall I order your
pizza?>
A conclusion statement to send to the user after the intent has been fulfilled. For example, "I placed your pizza
order.>
A follow-up prompt that asks the user for additional activity. For example, asking "Do you want to order a drink with your
pizza?>
If you specify an existing intent name to update the intent, Amazon Lex replaces the values in the $LATEST version of the intent with the values in the request. Amazon Lex removes fields that you don't provide in the request. If you don't specify the required fields, Amazon Lex throws an exception. When you update the $LATEST version of an intent, the status field of any bot that uses the $LATEST version of the intent is set to
NOT_BUILT>
For more information, see
how-it-works>
This operation requires permissions for the lex:PutIntent
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1015 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutIntentResponse *>(send(request));
 }
putSlotType
PutSlotTypeResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::putSlotType (const PutSlotTypeRequest & request) slot
Creates a custom slot type or replaces an existing custom slot
type>
To create a custom slot type, specify a name for the slot type and a set of enumeration values, which are the values that a slot of this type can assume. For more information, see
how-it-works>
If you specify the name of an existing slot type, the fields in the request replace the existing values in the $LATEST version of the slot type. Amazon Lex removes the fields that you don't provide in the request. If you don't specify required fields, Amazon Lex throws an exception. When you update the $LATEST version of a slot type, if a bot uses the $LATEST version of an intent that contains the slot type, the bot's status field is set to
NOT_BUILT>
This operation requires permissions for the lex:PutSlotType
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1046 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutSlotTypeResponse *>(send(request));
 }
startImport
StartImportResponse * QtAws::LexModelBuildingService::LexModelBuildingServiceClient::startImport (const StartImportRequest & request) slot
Starts a job to import a resource to Amazon
Parameters
request Request to send to Amazon Lex Model Building Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1060 of file lexmodelbuildingserviceclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<StartImportResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
lex-models/lexmodelbuildingserviceclient.h
lex-models/lexmodelbuildingserviceclient.cpp