AWS SDK for Qt: QtAws::AutoScaling::AutoScalingClient Class Reference
QtAws::AutoScaling::AutoScalingClient Class Reference
Client for Auto Scaling.
Public Slots
AttachInstancesResponse * attachInstances (const AttachInstancesRequest &request)
AttachLoadBalancerTargetGroupsResponse * attachLoadBalancerTargetGroups (const AttachLoadBalancerTargetGroupsRequest &request)
AttachLoadBalancersResponse * attachLoadBalancers (const AttachLoadBalancersRequest &request)
CompleteLifecycleActionResponse * completeLifecycleAction (const CompleteLifecycleActionRequest &request)
CreateAutoScalingGroupResponse * createAutoScalingGroup (const CreateAutoScalingGroupRequest &request)
CreateLaunchConfigurationResponse * createLaunchConfiguration (const CreateLaunchConfigurationRequest &request)
CreateOrUpdateTagsResponse * createOrUpdateTags (const CreateOrUpdateTagsRequest &request)
DeleteAutoScalingGroupResponse * deleteAutoScalingGroup (const DeleteAutoScalingGroupRequest &request)
DeleteLaunchConfigurationResponse * deleteLaunchConfiguration (const DeleteLaunchConfigurationRequest &request)
DeleteLifecycleHookResponse * deleteLifecycleHook (const DeleteLifecycleHookRequest &request)
DeleteNotificationConfigurationResponse * deleteNotificationConfiguration (const DeleteNotificationConfigurationRequest &request)
DeletePolicyResponse * deletePolicy (const DeletePolicyRequest &request)
DeleteScheduledActionResponse * deleteScheduledAction (const DeleteScheduledActionRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits ()
DescribeAdjustmentTypesResponse * describeAdjustmentTypes ()
DescribeAutoScalingGroupsResponse * describeAutoScalingGroups (const DescribeAutoScalingGroupsRequest &request)
DescribeAutoScalingInstancesResponse * describeAutoScalingInstances (const DescribeAutoScalingInstancesRequest &request)
DescribeAutoScalingNotificationTypesResponse * describeAutoScalingNotificationTypes ()
DescribeLaunchConfigurationsResponse * describeLaunchConfigurations (const DescribeLaunchConfigurationsRequest &request)
DescribeLifecycleHookTypesResponse * describeLifecycleHookTypes ()
DescribeLifecycleHooksResponse * describeLifecycleHooks (const DescribeLifecycleHooksRequest &request)
DescribeLoadBalancerTargetGroupsResponse * describeLoadBalancerTargetGroups (const DescribeLoadBalancerTargetGroupsRequest &request)
DescribeLoadBalancersResponse * describeLoadBalancers (const DescribeLoadBalancersRequest &request)
DescribeMetricCollectionTypesResponse * describeMetricCollectionTypes ()
DescribeNotificationConfigurationsResponse * describeNotificationConfigurations (const DescribeNotificationConfigurationsRequest &request)
DescribePoliciesResponse * describePolicies (const DescribePoliciesRequest &request)
DescribeScalingActivitiesResponse * describeScalingActivities (const DescribeScalingActivitiesRequest &request)
DescribeScalingProcessTypesResponse * describeScalingProcessTypes ()
DescribeScheduledActionsResponse * describeScheduledActions (const DescribeScheduledActionsRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeTerminationPolicyTypesResponse * describeTerminationPolicyTypes ()
DetachInstancesResponse * detachInstances (const DetachInstancesRequest &request)
DetachLoadBalancerTargetGroupsResponse * detachLoadBalancerTargetGroups (const DetachLoadBalancerTargetGroupsRequest &request)
DetachLoadBalancersResponse * detachLoadBalancers (const DetachLoadBalancersRequest &request)
DisableMetricsCollectionResponse * disableMetricsCollection (const DisableMetricsCollectionRequest &request)
EnableMetricsCollectionResponse * enableMetricsCollection (const EnableMetricsCollectionRequest &request)
EnterStandbyResponse * enterStandby (const EnterStandbyRequest &request)
ExecutePolicyResponse * executePolicy (const ExecutePolicyRequest &request)
ExitStandbyResponse * exitStandby (const ExitStandbyRequest &request)
PutLifecycleHookResponse * putLifecycleHook (const PutLifecycleHookRequest &request)
PutNotificationConfigurationResponse * putNotificationConfiguration (const PutNotificationConfigurationRequest &request)
PutScalingPolicyResponse * putScalingPolicy (const PutScalingPolicyRequest &request)
PutScheduledUpdateGroupActionResponse * putScheduledUpdateGroupAction (const PutScheduledUpdateGroupActionRequest &request)
RecordLifecycleActionHeartbeatResponse * recordLifecycleActionHeartbeat (const RecordLifecycleActionHeartbeatRequest &request)
ResumeProcessesResponse * resumeProcesses (const ResumeProcessesRequest &request)
SetDesiredCapacityResponse * setDesiredCapacity (const SetDesiredCapacityRequest &request)
SetInstanceHealthResponse * setInstanceHealth (const SetInstanceHealthRequest &request)
SetInstanceProtectionResponse * setInstanceProtection (const SetInstanceProtectionRequest &request)
SuspendProcessesResponse * suspendProcesses (const SuspendProcessesRequest &request)
TerminateInstanceInAutoScalingGroupResponse * terminateInstanceInAutoScalingGroup (const TerminateInstanceInAutoScalingGroupRequest &request)
UpdateAutoScalingGroupResponse * updateAutoScalingGroup (const UpdateAutoScalingGroupRequest &request)
Public Member Functions
AutoScalingClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AutoScalingClient object.
AutoScalingClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AutoScalingClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Auto Scaling.
<fullname>Amazon EC2 Auto Scaling</fullname>
Amazon EC2 Auto Scaling is designed to automatically launch or terminate EC2 instances based on user-defined policies, schedules, and health checks. Use this service in conjunction with the AWS Auto Scaling, Amazon CloudWatch, and Elastic Load Balancing
Definition at line 129 of file autoscalingclient.h.
Constructor & Destructor Documentation
AutoScalingClient() [1/2]
QtAws::AutoScaling::AutoScalingClient::AutoScalingClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AutoScalingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 148 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new AutoScalingClientPrivate(this), parent)
 {
     Q_D(AutoScalingClient);
     d->apiVersion = QStringLiteral("2011-01-01");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("autoscaling");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("Auto Scaling");
     d->serviceName = QStringLiteral("autoscaling");
 }
AutoScalingClient() [2/2]
QtAws::AutoScaling::AutoScalingClient::AutoScalingClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AutoScalingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 181 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new AutoScalingClientPrivate(this), parent)
 {
     Q_D(AutoScalingClient);
     d->apiVersion = QStringLiteral("2011-01-01");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("autoscaling");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("Auto Scaling");
     d->serviceName = QStringLiteral("autoscaling");
 }
Member Function Documentation
attachInstances
AttachInstancesResponse * QtAws::AutoScaling::AutoScalingClient::attachInstances (const AttachInstancesRequest & request) slot
Attaches one or more EC2 instances to the specified Auto Scaling
group>
When you attach instances, Auto Scaling increases the desired capacity of the group by the number of instances being attached. If the number of instances being attached plus the desired capacity of the group exceeds the maximum size of the group, the operation
fails>
If there is a Classic Load Balancer attached to your Auto Scaling group, the instances are also registered with the load balancer. If there are target groups attached to your Auto Scaling group, the instances are also registered with the target
groups>
For more information, see Attach EC2 Instances to Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 225 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachInstancesResponse *>(send(request));
 }
attachLoadBalancers
AttachLoadBalancersResponse * QtAws::AutoScaling::AutoScalingClient::attachLoadBalancers (const AttachLoadBalancersRequest & request) slot
Attaches one or more Classic Load Balancers to the specified Auto Scaling
group>
To attach an Application Load Balancer instead, see
AttachLoadBalancerTargetGroups>
To describe the load balancers for an Auto Scaling group, use DescribeLoadBalancers. To detach the load balancer from the Auto Scaling group, use
DetachLoadBalancers>
For more information, see Attach a Load Balancer to Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 279 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachLoadBalancersResponse *>(send(request));
 }
attachLoadBalancerTargetGroups
AttachLoadBalancerTargetGroupsResponse * QtAws::AutoScaling::AutoScalingClient::attachLoadBalancerTargetGroups (const AttachLoadBalancerTargetGroupsRequest & request) slot
Attaches one or more target groups to the specified Auto Scaling
group>
To describe the target groups for an Auto Scaling group, use DescribeLoadBalancerTargetGroups. To detach the target group from the Auto Scaling group, use
DetachLoadBalancerTargetGroups>
For more information, see Attach a Load Balancer to Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 250 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<AttachLoadBalancerTargetGroupsResponse *>(send(request));
 }
completeLifecycleAction
CompleteLifecycleActionResponse * QtAws::AutoScaling::AutoScalingClient::completeLifecycleAction (const CompleteLifecycleActionRequest & request) slot
Completes the lifecycle action for the specified token or instance with the specified
result>
This step is a part of the procedure for adding a lifecycle hook to an Auto Scaling
group>
(Optional) Create a Lambda function and a rule that allows CloudWatch Events to invoke your Lambda function when Auto Scaling launches or terminates
instances>
(Optional) Create a notification target and an IAM role. The target can be either an Amazon SQS queue or an Amazon SNS topic. The role allows Auto Scaling to publish lifecycle notifications to the
target>
Create the lifecycle hook. Specify whether the hook is used when the instances launch or
terminate>
If you need more time, record the lifecycle action heartbeat to keep the instance in a pending
state>
If you finish before the timeout period ends, complete the lifecycle action.
</p
For more information, see Auto Scaling Lifecycle in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 325 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CompleteLifecycleActionResponse *>(send(request));
 }
createAutoScalingGroup
CreateAutoScalingGroupResponse * QtAws::AutoScaling::AutoScalingClient::createAutoScalingGroup (const CreateAutoScalingGroupRequest & request) slot
Creates an Auto Scaling group with the specified name and
attributes>
If you exceed your maximum limit of Auto Scaling groups, the call fails. For information about viewing this limit, see DescribeAccountLimits. For information about updating this limit, see Auto Scaling Limits in the Auto Scaling User
Guide>
For more information, see Auto Scaling Groups in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 351 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateAutoScalingGroupResponse *>(send(request));
 }
createLaunchConfiguration
CreateLaunchConfigurationResponse * QtAws::AutoScaling::AutoScalingClient::createLaunchConfiguration (const CreateLaunchConfigurationRequest & request) slot
Creates a launch
configuration>
If you exceed your maximum limit of launch configurations, the call fails. For information about viewing this limit, see DescribeAccountLimits. For information about updating this limit, see Auto Scaling Limits in the Auto Scaling User
Guide>
For more information, see Launch Configurations in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 378 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateLaunchConfigurationResponse *>(send(request));
 }
createOrUpdateTags
CreateOrUpdateTagsResponse * QtAws::AutoScaling::AutoScalingClient::createOrUpdateTags (const CreateOrUpdateTagsRequest & request) slot
Creates or updates tags for the specified Auto Scaling
group>
When you specify a tag with a key that already exists, the operation overwrites the previous tag definition, and you do not get an error
message>
For more information, see Tagging Auto Scaling Groups and Instances in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 403 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateOrUpdateTagsResponse *>(send(request));
 }
deleteAutoScalingGroup
DeleteAutoScalingGroupResponse * QtAws::AutoScaling::AutoScalingClient::deleteAutoScalingGroup (const DeleteAutoScalingGroupRequest & request) slot
Deletes the specified Auto Scaling
group>
If the group has instances or scaling activities in progress, you must specify the option to force the deletion in order for it to
succeed>
If the group has policies, deleting the group deletes the policies, the underlying alarm actions, and any alarm that no longer has an associated
action>
To remove instances from the Auto Scaling group before deleting it, call DetachInstances with the list of instances and the option to decrement the desired capacity so that Auto Scaling does not launch replacement
instances>
To terminate all instances before deleting the Auto Scaling group, call UpdateAutoScalingGroup and set the minimum size and desired capacity of the Auto Scaling group to
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 437 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteAutoScalingGroupResponse *>(send(request));
 }
deleteLaunchConfiguration
DeleteLaunchConfigurationResponse * QtAws::AutoScaling::AutoScalingClient::deleteLaunchConfiguration (const DeleteLaunchConfigurationRequest & request) slot
Deletes the specified launch
configuration>
The launch configuration must not be attached to an Auto Scaling group. When this call completes, the launch configuration is no longer available for
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 456 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLaunchConfigurationResponse *>(send(request));
 }
deleteLifecycleHook
DeleteLifecycleHookResponse * QtAws::AutoScaling::AutoScalingClient::deleteLifecycleHook (const DeleteLifecycleHookRequest & request) slot
Deletes the specified lifecycle
hook>
If there are any outstanding lifecycle actions, they are completed first (ABANDON for launching instances, CONTINUE for terminating
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 475 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteLifecycleHookResponse *>(send(request));
 }
deleteNotificationConfiguration
DeleteNotificationConfigurationResponse * QtAws::AutoScaling::AutoScalingClient::deleteNotificationConfiguration (const DeleteNotificationConfigurationRequest & request) slot
Deletes the specified
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 489 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteNotificationConfigurationResponse *>(send(request));
 }
deletePolicy
DeletePolicyResponse * QtAws::AutoScaling::AutoScalingClient::deletePolicy (const DeletePolicyRequest & request) slot
Deletes the specified Auto Scaling
policy>
Deleting a policy deletes the underlying alarm action, but does not delete the alarm, even if it no longer has an associated
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 508 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeletePolicyResponse *>(send(request));
 }
deleteScheduledAction
DeleteScheduledActionResponse * QtAws::AutoScaling::AutoScalingClient::deleteScheduledAction (const DeleteScheduledActionRequest & request) slot
Deletes the specified scheduled
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 522 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteScheduledActionResponse *>(send(request));
 }
deleteTags
DeleteTagsResponse * QtAws::AutoScaling::AutoScalingClient::deleteTags (const DeleteTagsRequest & request) slot
Deletes the specified
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 536 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteTagsResponse *>(send(request));
 }
describeAccountLimits
DescribeAccountLimitsResponse * QtAws::AutoScaling::AutoScalingClient::describeAccountLimits () slot
Describes the current Auto Scaling resource limits for your AWS
account>
For information about requesting an increase in these limits, see Auto Scaling Limits in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 556 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAccountLimitsResponse *>(send(request));
 }
describeAdjustmentTypes
DescribeAdjustmentTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeAdjustmentTypes () slot
Describes the policy adjustment types for use with
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 570 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAdjustmentTypesResponse *>(send(request));
 }
describeAutoScalingGroups
DescribeAutoScalingGroupsResponse * QtAws::AutoScaling::AutoScalingClient::describeAutoScalingGroups (const DescribeAutoScalingGroupsRequest & request) slot
Describes one or more Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 584 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAutoScalingGroupsResponse *>(send(request));
 }
describeAutoScalingInstances
DescribeAutoScalingInstancesResponse * QtAws::AutoScaling::AutoScalingClient::describeAutoScalingInstances (const DescribeAutoScalingInstancesRequest & request) slot
Describes one or more Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 598 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAutoScalingInstancesResponse *>(send(request));
 }
describeAutoScalingNotificationTypes
DescribeAutoScalingNotificationTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeAutoScalingNotificationTypes () slot
Describes the notification types that are supported by Auto
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 612 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAutoScalingNotificationTypesResponse *>(send(request));
 }
describeLaunchConfigurations
DescribeLaunchConfigurationsResponse * QtAws::AutoScaling::AutoScalingClient::describeLaunchConfigurations (const DescribeLaunchConfigurationsRequest & request) slot
Describes one or more launch
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 626 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLaunchConfigurationsResponse *>(send(request));
 }
describeLifecycleHooks
DescribeLifecycleHooksResponse * QtAws::AutoScaling::AutoScalingClient::describeLifecycleHooks (const DescribeLifecycleHooksRequest & request) slot
Describes the lifecycle hooks for the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 654 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLifecycleHooksResponse *>(send(request));
 }
describeLifecycleHookTypes
DescribeLifecycleHookTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeLifecycleHookTypes () slot
Describes the available types of lifecycle
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 640 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLifecycleHookTypesResponse *>(send(request));
 }
describeLoadBalancers
DescribeLoadBalancersResponse * QtAws::AutoScaling::AutoScalingClient::describeLoadBalancers (const DescribeLoadBalancersRequest & request) slot
Describes the load balancers for the specified Auto Scaling
group>
Note that this operation describes only Classic Load Balancers. If you have Application Load Balancers, use DescribeLoadBalancerTargetGroups
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 687 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancersResponse *>(send(request));
 }
describeLoadBalancerTargetGroups
DescribeLoadBalancerTargetGroupsResponse * QtAws::AutoScaling::AutoScalingClient::describeLoadBalancerTargetGroups (const DescribeLoadBalancerTargetGroupsRequest & request) slot
Describes the target groups for the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 668 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeLoadBalancerTargetGroupsResponse *>(send(request));
 }
describeMetricCollectionTypes
DescribeMetricCollectionTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeMetricCollectionTypes () slot
Describes the available CloudWatch metrics for Auto
Scaling>
Note that the GroupStandbyInstances metric is not returned by default. You must explicitly request this metric when calling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 706 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeMetricCollectionTypesResponse *>(send(request));
 }
describeNotificationConfigurations
DescribeNotificationConfigurationsResponse * QtAws::AutoScaling::AutoScalingClient::describeNotificationConfigurations (const DescribeNotificationConfigurationsRequest & request) slot
Describes the notification actions associated with the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 720 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeNotificationConfigurationsResponse *>(send(request));
 }
describePolicies
DescribePoliciesResponse * QtAws::AutoScaling::AutoScalingClient::describePolicies (const DescribePoliciesRequest & request) slot
Describes the policies for the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 734 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribePoliciesResponse *>(send(request));
 }
describeScalingActivities
DescribeScalingActivitiesResponse * QtAws::AutoScaling::AutoScalingClient::describeScalingActivities (const DescribeScalingActivitiesRequest & request) slot
Describes one or more scaling activities for the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 748 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingActivitiesResponse *>(send(request));
 }
describeScalingProcessTypes
DescribeScalingProcessTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeScalingProcessTypes () slot
Describes the scaling process types for use with ResumeProcesses and
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 762 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScalingProcessTypesResponse *>(send(request));
 }
describeScheduledActions
DescribeScheduledActionsResponse * QtAws::AutoScaling::AutoScalingClient::describeScheduledActions (const DescribeScheduledActionsRequest & request) slot
Describes the actions scheduled for your Auto Scaling group that haven't run. To describe the actions that have already run, use
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 777 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeScheduledActionsResponse *>(send(request));
 }
describeTags
DescribeTagsResponse * QtAws::AutoScaling::AutoScalingClient::describeTags (const DescribeTagsRequest & request) slot
Describes the specified
tags>
You can use filters to limit the results. For example, you can query for the tags for a specific Auto Scaling group. You can specify multiple values for a filter. A tag must match at least one of the specified values for it to be included in the
results>
You can also specify multiple filters. The result includes information for a particular tag only if it matches all the filters. If there's no match, no special message is
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 802 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTagsResponse *>(send(request));
 }
describeTerminationPolicyTypes
DescribeTerminationPolicyTypesResponse * QtAws::AutoScaling::AutoScalingClient::describeTerminationPolicyTypes () slot
Describes the termination policies supported by Auto
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 816 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeTerminationPolicyTypesResponse *>(send(request));
 }
detachInstances
DetachInstancesResponse * QtAws::AutoScaling::AutoScalingClient::detachInstances (const DetachInstancesRequest & request) slot
Removes one or more instances from the specified Auto Scaling
group>
After the instances are detached, you can manage them independent of the Auto Scaling
group>
If you do not specify the option to decrement the desired capacity, Auto Scaling launches instances to replace the ones that are
detached>
If there is a Classic Load Balancer attached to the Auto Scaling group, the instances are deregistered from the load balancer. If there are target groups attached to the Auto Scaling group, the instances are deregistered from the target
groups>
For more information, see Detach EC2 Instances from Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 850 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachInstancesResponse *>(send(request));
 }
detachLoadBalancers
DetachLoadBalancersResponse * QtAws::AutoScaling::AutoScalingClient::detachLoadBalancers (const DetachLoadBalancersRequest & request) slot
Detaches one or more Classic Load Balancers from the specified Auto Scaling
group>
Note that this operation detaches only Classic Load Balancers. If you have Application Load Balancers, use DetachLoadBalancerTargetGroups
instead>
When you detach a load balancer, it enters the Removing state while deregistering the instances in the group. When all instances are deregistered, then you can no longer describe the load balancer using DescribeLoadBalancers. Note that the instances remain
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 889 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachLoadBalancersResponse *>(send(request));
 }
detachLoadBalancerTargetGroups
DetachLoadBalancerTargetGroupsResponse * QtAws::AutoScaling::AutoScalingClient::detachLoadBalancerTargetGroups (const DetachLoadBalancerTargetGroupsRequest & request) slot
Detaches one or more target groups from the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 864 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DetachLoadBalancerTargetGroupsResponse *>(send(request));
 }
disableMetricsCollection
DisableMetricsCollectionResponse * QtAws::AutoScaling::AutoScalingClient::disableMetricsCollection (const DisableMetricsCollectionRequest & request) slot
Disables group metrics for the specified Auto Scaling
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 903 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DisableMetricsCollectionResponse *>(send(request));
 }
enableMetricsCollection
EnableMetricsCollectionResponse * QtAws::AutoScaling::AutoScalingClient::enableMetricsCollection (const EnableMetricsCollectionRequest & request) slot
Enables group metrics for the specified Auto Scaling group. For more information, see Monitoring Your Auto Scaling Groups and Instances in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 919 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnableMetricsCollectionResponse *>(send(request));
 }
enterStandby
EnterStandbyResponse * QtAws::AutoScaling::AutoScalingClient::enterStandby (const EnterStandbyRequest & request) slot
Moves the specified instances into the standby
state>
For more information, see Temporarily Removing Instances from Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 939 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<EnterStandbyResponse *>(send(request));
 }
executePolicy
ExecutePolicyResponse * QtAws::AutoScaling::AutoScalingClient::executePolicy (const ExecutePolicyRequest & request) slot
Executes the specified
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 953 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExecutePolicyResponse *>(send(request));
 }
exitStandby
ExitStandbyResponse * QtAws::AutoScaling::AutoScalingClient::exitStandby (const ExitStandbyRequest & request) slot
Moves the specified instances out of the standby
state>
For more information, see Temporarily Removing Instances from Your Auto Scaling Group in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 973 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ExitStandbyResponse *>(send(request));
 }
putLifecycleHook
PutLifecycleHookResponse * QtAws::AutoScaling::AutoScalingClient::putLifecycleHook (const PutLifecycleHookRequest & request) slot
Creates or updates a lifecycle hook for the specified Auto Scaling
Group>
A lifecycle hook tells Auto Scaling that you want to perform an action on an instance that is not actively in service; for example, either when the instance launches or before the instance
terminates>
This step is a part of the procedure for adding a lifecycle hook to an Auto Scaling
group>
(Optional) Create a Lambda function and a rule that allows CloudWatch Events to invoke your Lambda function when Auto Scaling launches or terminates
instances>
(Optional) Create a notification target and an IAM role. The target can be either an Amazon SQS queue or an Amazon SNS topic. The role allows Auto Scaling to publish lifecycle notifications to the
target>
Create the lifecycle hook. Specify whether the hook is used when the instances launch or terminate.
</p
If you need more time, record the lifecycle action heartbeat to keep the instance in a pending
state>
If you finish before the timeout period ends, complete the lifecycle
action>
For more information, see Auto Scaling Lifecycle Hooks in the Auto Scaling User
Guide>
If you exceed your maximum limit of lifecycle hooks, which by default is 50 per Auto Scaling group, the call fails. For information about updating this limit, see AWS Service Limits in the Amazon Web Services General
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1030 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutLifecycleHookResponse *>(send(request));
 }
putNotificationConfiguration
PutNotificationConfigurationResponse * QtAws::AutoScaling::AutoScalingClient::putNotificationConfiguration (const PutNotificationConfigurationRequest & request) slot
Configures an Auto Scaling group to send notifications when specified events take place. Subscribers to the specified topic can have messages delivered to an endpoint such as a web server or an email
address>
This configuration overwrites any existing
configuration>
For more information see Getting SNS Notifications When Your Auto Scaling Group Scales in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1055 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutNotificationConfigurationResponse *>(send(request));
 }
putScalingPolicy
PutScalingPolicyResponse * QtAws::AutoScaling::AutoScalingClient::putScalingPolicy (const PutScalingPolicyRequest & request) slot
Creates or updates a policy for an Auto Scaling group. To update an existing policy, use the existing policy name and set the parameters you want to change. Any existing parameter not changed in an update to an existing policy is not changed in this update
request>
If you exceed your maximum limit of step adjustments, which by default is 20 per region, the call fails. For information about updating this limit, see AWS Service Limits in the Amazon Web Services General
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1077 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutScalingPolicyResponse *>(send(request));
 }
putScheduledUpdateGroupAction
PutScheduledUpdateGroupActionResponse * QtAws::AutoScaling::AutoScalingClient::putScheduledUpdateGroupAction (const PutScheduledUpdateGroupActionRequest & request) slot
Creates or updates a scheduled scaling action for an Auto Scaling group. When updating a scheduled scaling action, if you leave a parameter unspecified, the corresponding value remains
unchanged>
For more information, see Scheduled Scaling in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1097 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<PutScheduledUpdateGroupActionResponse *>(send(request));
 }
recordLifecycleActionHeartbeat
RecordLifecycleActionHeartbeatResponse * QtAws::AutoScaling::AutoScalingClient::recordLifecycleActionHeartbeat (const RecordLifecycleActionHeartbeatRequest & request) slot
Records a heartbeat for the lifecycle action associated with the specified token or instance. This extends the timeout by the length of time defined using
PutLifecycleHook>
This step is a part of the procedure for adding a lifecycle hook to an Auto Scaling
group>
(Optional) Create a Lambda function and a rule that allows CloudWatch Events to invoke your Lambda function when Auto Scaling launches or terminates
instances>
(Optional) Create a notification target and an IAM role. The target can be either an Amazon SQS queue or an Amazon SNS topic. The role allows Auto Scaling to publish lifecycle notifications to the
target>
Create the lifecycle hook. Specify whether the hook is used when the instances launch or
terminate>
If you need more time, record the lifecycle action heartbeat to keep the instance in a pending state.
</p
If you finish before the timeout period ends, complete the lifecycle
action>
For more information, see Auto Scaling Lifecycle in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1144 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<RecordLifecycleActionHeartbeatResponse *>(send(request));
 }
resumeProcesses
ResumeProcessesResponse * QtAws::AutoScaling::AutoScalingClient::resumeProcesses (const ResumeProcessesRequest & request) slot
Resumes the specified suspended Auto Scaling processes, or all suspended process, for the specified Auto Scaling
group>
For more information, see Suspending and Resuming Auto Scaling Processes in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1164 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ResumeProcessesResponse *>(send(request));
 }
setDesiredCapacity
SetDesiredCapacityResponse * QtAws::AutoScaling::AutoScalingClient::setDesiredCapacity (const SetDesiredCapacityRequest & request) slot
Sets the size of the specified Auto Scaling
group>
For more information about desired capacity, see What Is Auto Scaling? in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1184 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetDesiredCapacityResponse *>(send(request));
 }
setInstanceHealth
SetInstanceHealthResponse * QtAws::AutoScaling::AutoScalingClient::setInstanceHealth (const SetInstanceHealthRequest & request) slot
Sets the health status of the specified
instance>
For more information, see Health Checks in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1203 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetInstanceHealthResponse *>(send(request));
 }
setInstanceProtection
SetInstanceProtectionResponse * QtAws::AutoScaling::AutoScalingClient::setInstanceProtection (const SetInstanceProtectionRequest & request) slot
Updates the instance protection settings of the specified
instances>
For more information, see Instance Protection in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1223 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SetInstanceProtectionResponse *>(send(request));
 }
suspendProcesses
SuspendProcessesResponse * QtAws::AutoScaling::AutoScalingClient::suspendProcesses (const SuspendProcessesRequest & request) slot
Suspends the specified Auto Scaling processes, or all processes, for the specified Auto Scaling
group>
Note that if you suspend either the Launch or Terminate process types, it can prevent other process types from functioning
properly>
To resume processes that have been suspended, use
ResumeProcesses>
For more information, see Suspending and Resuming Auto Scaling Processes in the Auto Scaling User
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1252 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<SuspendProcessesResponse *>(send(request));
 }
terminateInstanceInAutoScalingGroup
TerminateInstanceInAutoScalingGroupResponse * QtAws::AutoScaling::AutoScalingClient::terminateInstanceInAutoScalingGroup (const TerminateInstanceInAutoScalingGroupRequest & request) slot
Terminates the specified instance and optionally adjusts the desired group
size>
This call simply makes a termination request. The instance is not terminated
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1270 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<TerminateInstanceInAutoScalingGroupResponse *>(send(request));
 }
updateAutoScalingGroup
UpdateAutoScalingGroupResponse * QtAws::AutoScaling::AutoScalingClient::updateAutoScalingGroup (const UpdateAutoScalingGroupRequest & request) slot
Updates the configuration for the specified Auto Scaling
group>
The new settings take effect on any scaling activities after this call returns. Scaling activities that are currently in progress aren't
affected>
To update an Auto Scaling group with a launch configuration with InstanceMonitoring set to false, you must first disable the collection of group metrics. Otherwise, you will get an error. If you have previously enabled the collection of group metrics, you can disable it using
DisableMetricsCollection>
Note the
following>
If you specify a new value for MinSize without specifying a value for DesiredCapacity, and the new MinSize is larger than the current size of the group, we implicitly call SetDesiredCapacity to set the size of the group to the new value of
MinSize>
If you specify a new value for MaxSize without specifying a value for DesiredCapacity, and the new MaxSize is smaller than the current size of the group, we implicitly call SetDesiredCapacity to set the size of the group to the new value of
MaxSize>
All other optional parameters are left unchanged if not
Parameters
request Request to send to Auto Scaling.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 1315 of file autoscalingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<UpdateAutoScalingGroupResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
autoscaling/autoscalingclient.h
autoscaling/autoscalingclient.cpp