AWS SDK for Qt: QtAws::Pricing::PricingClient Class Reference
QtAws::Pricing::PricingClient Class Reference
Client for AWS Price List Service (Pricing)
Public Slots
DescribeServicesResponse * describeServices (const DescribeServicesRequest &request)
GetAttributeValuesResponse * getAttributeValues (const GetAttributeValuesRequest &request)
GetProductsResponse * getProducts (const GetProductsRequest &request)
Public Member Functions
PricingClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PricingClient object.
PricingClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PricingClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Price List Service (Pricing)
AWS Price List Service API (AWS Price List Service) is a centralized and convenient way to programmatically query Amazon Web Services for services, products, and pricing information. The AWS Price List Service uses standardized product attributes such as Location, Storage Class, and Operating System, and provides prices at the SKU level. You can use the AWS Price List Service to build cost control and scenario planning tools, reconcile billing data, forecast future spend for budgeting purposes, and provide cost benefit analysis that compare your internal workloads with
AWS>
Use GetServices without a service code to retrieve the service codes for all AWS services, then GetServices with a service code to retreive the attribute names for that service. After you have the service code and attribute names, you can use GetAttributeValues to see what values are available for an attribute. With the service code and an attribute name and value, you can use GetProducts to find specific products that you're interested in, such as an AmazonEC2 instance, with a Provisioned IOPS
volumeType>
Service
Endpoin>
AWS Price List Service API provides the following two
endpoints>
https://api.pricing.us-east-1.amazonaws.co>
Definition at line 38 of file pricingclient.h.
Constructor & Destructor Documentation
PricingClient() [1/2]
QtAws::Pricing::PricingClient::PricingClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PricingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 78 of file pricingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new PricingClientPrivate(this), parent)
 {
     Q_D(PricingClient);
     d->apiVersion = QStringLiteral("2017-10-15");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("api.pricing");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Price List Service");
     d->serviceName = QStringLiteral("pricing");
 }
PricingClient() [2/2]
QtAws::Pricing::PricingClient::PricingClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PricingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 111 of file pricingclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new PricingClientPrivate(this), parent)
 {
     Q_D(PricingClient);
     d->apiVersion = QStringLiteral("2017-10-15");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("api.pricing");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Price List Service");
     d->serviceName = QStringLiteral("pricing");
 }
Member Function Documentation
describeServices
DescribeServicesResponse * QtAws::Pricing::PricingClient::describeServices (const DescribeServicesRequest & request) slot
Returns the metadata for one service or a list of the metadata for all services. Use this without a service code to get the service codes for all services. Use it with a service code, such as AmazonEC2, to get information specific to that service, such as the attribute names available for that service. For example, some of the attribute names available for EC2 are volumeType, maxIopsVolume, operation, locationType, and
Parameters
request Request to send to AWS Price List Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 141 of file pricingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeServicesResponse *>(send(request));
 }
getAttributeValues
GetAttributeValuesResponse * QtAws::Pricing::PricingClient::getAttributeValues (const GetAttributeValuesRequest & request) slot
Returns a list of attribute values. Attibutes are similar to the details in a Price List API offer file. For a list of available attributes, see Offer File Definitions in the AWS Billing and Cost Management User request Request to send to AWS Price List Service. A pointer to a related response object. The caller is to take responsbility for the resulting pointer.
Definition at line 159 of file pricingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetAttributeValuesResponse *>(send(request));
 }
getProducts
GetProductsResponse * QtAws::Pricing::PricingClient::getProducts (const GetProductsRequest & request) slot
Returns a list of all products that match the filter
Parameters
request Request to send to AWS Price List Service.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 173 of file pricingclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetProductsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
pricing/pricingclient.h
pricing/pricingclient.cpp