AWS SDK for Qt: QtAws::Shield::ShieldClient Class Reference
QtAws::Shield::ShieldClient Class Reference
Client for AWS Shield.
Public Slots
CreateProtectionResponse * createProtection (const CreateProtectionRequest &request)
CreateSubscriptionResponse * createSubscription (const CreateSubscriptionRequest &request)
DeleteProtectionResponse * deleteProtection (const DeleteProtectionRequest &request)
DeleteSubscriptionResponse * deleteSubscription (const DeleteSubscriptionRequest &request)
DescribeAttackResponse * describeAttack (const DescribeAttackRequest &request)
DescribeProtectionResponse * describeProtection (const DescribeProtectionRequest &request)
DescribeSubscriptionResponse * describeSubscription (const DescribeSubscriptionRequest &request)
GetSubscriptionStateResponse * getSubscriptionState (const GetSubscriptionStateRequest &request)
ListAttacksResponse * listAttacks (const ListAttacksRequest &request)
ListProtectionsResponse * listProtections (const ListProtectionsRequest &request)
Public Member Functions
ShieldClient (const QtAws::Core::AwsRegion::Region region=QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ShieldClient object.
ShieldClient (const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ShieldClient object.
Public Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QString apiVersion () const
Get the serivce API version this client implementts.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QString endpointPrefix () const
Get the endpoint prefix associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceFullName () const
Get the full name of the Amazon service this client accesses.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from QtAws::Core::AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Shield.
<fullname>AWS Shield Advanced</fullname>
This is the AWS Shield Advanced API Reference. This guide is for developers who need detailed information about the AWS Shield Advanced API actions, data types, and errors. For detailed information about AWS WAF and AWS Shield Advanced features and an overview of how to use the AWS WAF and AWS Shield Advanced APIs, see the AWS WAF and AWS Shield Developer
Definition at line 52 of file shieldclient.h.
Constructor & Destructor Documentation
ShieldClient() [1/2]
QtAws::Shield::ShieldClient::ShieldClient (const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ShieldClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 72 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::region().
 : QtAws::Core::AwsAbstractClient(new ShieldClientPrivate(this), parent)
 {
     Q_D(ShieldClient);
     d->apiVersion = QStringLiteral("2016-06-02");
     d->credentials = credentials;
     d->endpointPrefix = QStringLiteral("shield");
     d->networkAccessManager = manager;
     d->region = region;
     d->serviceFullName = QStringLiteral("AWS Shield");
     d->serviceName = QStringLiteral("shield");
 }
ShieldClient() [2/2]
QtAws::Shield::ShieldClient::ShieldClient (const QUrl & endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ShieldClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 105 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::credentials(), and QtAws::Core::AwsAbstractClient::endpoint().
 : QtAws::Core::AwsAbstractClient(new ShieldClientPrivate(this), parent)
 {
     Q_D(ShieldClient);
     d->apiVersion = QStringLiteral("2016-06-02");
     d->credentials = credentials;
     d->endpoint = endpoint;
     d->endpointPrefix = QStringLiteral("shield");
     d->networkAccessManager = manager;
     d->serviceFullName = QStringLiteral("AWS Shield");
     d->serviceName = QStringLiteral("shield");
 }
Member Function Documentation
createProtection
CreateProtectionResponse * QtAws::Shield::ShieldClient::createProtection (const CreateProtectionRequest & request) slot
Enables AWS Shield Advanced for a specific AWS resource. The resource can be an Amazon CloudFront distribution, Elastic Load Balancing load balancer, Elastic IP Address, or an Amazon Route 53 hosted
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 132 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateProtectionResponse *>(send(request));
 }
createSubscription
CreateSubscriptionResponse * QtAws::Shield::ShieldClient::createSubscription (const CreateSubscriptionRequest & request) slot
Activates AWS Shield Advanced for an
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 146 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<CreateSubscriptionResponse *>(send(request));
 }
deleteProtection
DeleteProtectionResponse * QtAws::Shield::ShieldClient::deleteProtection (const DeleteProtectionRequest & request) slot
Deletes an AWS Shield Advanced
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 160 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteProtectionResponse *>(send(request));
 }
deleteSubscription
DeleteSubscriptionResponse * QtAws::Shield::ShieldClient::deleteSubscription (const DeleteSubscriptionRequest & request) slot
Removes AWS Shield Advanced from an account. AWS Shield Advanced requires a 1-year subscription commitment. You cannot delete a subscription prior to the completion of that commitment.
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 175 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DeleteSubscriptionResponse *>(send(request));
 }
describeAttack
DescribeAttackResponse * QtAws::Shield::ShieldClient::describeAttack (const DescribeAttackRequest & request) slot
Describes the details of a DDoS attack.
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 189 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeAttackResponse *>(send(request));
 }
describeProtection
DescribeProtectionResponse * QtAws::Shield::ShieldClient::describeProtection (const DescribeProtectionRequest & request) slot
Lists the details of a Protection
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 203 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeProtectionResponse *>(send(request));
 }
describeSubscription
DescribeSubscriptionResponse * QtAws::Shield::ShieldClient::describeSubscription (const DescribeSubscriptionRequest & request) slot
Provides details about the AWS Shield Advanced subscription for an
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 217 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<DescribeSubscriptionResponse *>(send(request));
 }
getSubscriptionState
GetSubscriptionStateResponse * QtAws::Shield::ShieldClient::getSubscriptionState (const GetSubscriptionStateRequest & request) slot
Returns the SubscriptionState, either Active or
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 231 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<GetSubscriptionStateResponse *>(send(request));
 }
listAttacks
ListAttacksResponse * QtAws::Shield::ShieldClient::listAttacks (const ListAttacksRequest & request) slot
Returns all ongoing DDoS attacks or all DDoS attacks during a specified time
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 245 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListAttacksResponse *>(send(request));
 }
listProtections
ListProtectionsResponse * QtAws::Shield::ShieldClient::listProtections (const ListProtectionsRequest & request) slot
Lists all Protection objects for the
Parameters
request Request to send to AWS Shield.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 259 of file shieldclient.cpp.
References QtAws::Core::AwsAbstractClient::send().
 {
     return qobject_cast<ListProtectionsResponse *>(send(request));
 }
The documentation for this class was generated from the following files:
shield/shieldclient.h
shield/shieldclient.cpp